### ISSUE TITLE
Build settings are passed as user-defined value

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#100]
**Describe the bug**
Build setting passed as user-defined value in generated projects

**To Reproduce**
```swift
        Target(
            name: "______",
            platform: .iOS,
            product: .app,
            bundleId: "com.xcodepm._____",
            infoPlist: "____/Info.plist",
            sources: "____/**",
            entitlements: "____/____dev.entitlements",
            dependencies: [
                .carthage("Alamofire"),
            ],
            settings: Settings(
                base: ["SWIFT_OBJC_BRIDGING_HEADER": "${PROJECT_DIR}/___/BridgingHeader.h"],
                debug: nil,
                release: nil
            )
        )
```

**Expected behavior**
Set bridging header build setting to desired value.

**Screenshots**
<img width="691" alt="screenshot 2018-08-21 at 00 10 14" src="https://user-images.githubusercontent.com/2551911/44369447-bd425e00-a4d6-11e8-9f83-0eed2e712eaa.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version beta

**Comment by pepibumur** [comment]
Interesting. We might be doing some escaping/formatting with those strings. Thanks for the report @zdnk
