### ISSUE TITLE
Incorrect CustomConfigurations generated

### ISSUE THREAD

**Issue by ferologics** [tuist/tuist#1024]
**Describe the bug**
There’s an issue where basically compiler says that I’m not creating the `CustomConfiguration`s that I’m creating, but it only happens if I specify the run action on the `Scheme`.

```
Error: 
- The build configuration 'Dev' specified in the scheme's run action isn't defined in the project.
- The build configuration 'Staging' specified in the scheme's run action isn't defined in the project.
- The build configuration 'Production' specified in the scheme's run action isn't defined in the project.
Error: Fatal linting issues found
```

When I don’t specify a run action generated project has 5 configurations `Dev, Staging, Production, Debug, Release`. Tuist should have generated the 3 configurations that I’m giving it, without the additional `Debug` and `Release` configurations.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/5576161/74938377-2cf81880-53ee-11ea-87c5-a1fd8b5aec26.png">

**To Reproduce**

1. Download [CustomConfiguration.zip](https://github.com/tuist/tuist/files/4231819/CustomConfiguration.zip) project
3. Run `./bin/tuist/tuist generate`
5. Remove run action on line 66 in `Project+Templates.swift` file
6. See the 5 configurations that Tuist generated.

**Expected behavior**
Tuist should have generated the 3 configurations that I’m giving it, without the additional `Debug` and `Release` configurations.

Assuming that I have 3 environments `[.dev, .staging, .production]` the function `makeConfiguration()` should only return the `[Dev, Staging, Production]` configurations.

**Desktop (please complete the following information):**

- OS: macOS `10.15.3 Beta (19D62e)`
- Tuist Version `1.2.0`

**Additional Context**
[`Settings`](https://tuist.io/docs/usage/projectswift/#settings) with an array of [`CustomConfiguration`s](https://tuist.io/docs/usage/projectswift/#custom-configuration)
https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Settings.swift#L205

[`Scheme`](https://tuist.io/docs/usage/projectswift/#scheme) with actions on a target
https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Scheme.swift

**Comment by kwridan** [comment]
Thanks for raising this @ferologics and for including the sample project!

I believe the issue here is the `settings` are missing from the `Project` 

e.g. modifying the example to leverage the settings

```swift
// ...
return Project(name: name, settings: settings, targets: [app], schemes: schemes)
```

Should pass the lint check and generate a project with only the specified configurations. From my recollection, the custom configurations are aggregated `Project` + `Target`s and seeing there wasn't one specified at the project level it defaulted to `Debug` and `Release`

Hope this helps

**Comment by ferologics** [comment]
Thank you for the suggestion, this fixes my problem. ❤️
