### ISSUE TITLE
Custom project/module templates

### ISSUE THREAD

**Issue by TimurBK** [tuist/tuist#1035]
## Need/problem

I want to be able to use custom structure when generating project/module. I found that it was mentioned [here](https://github.com/tuist/tuist/issues/235#issuecomment-466795492) under scaffolding but I couldn't find a way to do it now.

## Motivation

Different companies have different opinions/accepted structure of the project(and maybe even templates with some scripts to rename files). In this sense project structure generated by `tuist init ...` might not satisfy the requirements and developers would have to edit/create structure manually. If custom structure could be used that would make `init`/new command more useful.

Almost the same scenario would happen when later developer would need to add a new module into the existing project(except that I couldn't find any command to do this apart from running `init` again). Creating folder structure manually would be tedious and if some scripts are involved that means more steps outside of tuist.

## Detailed design

From user perspective that would look like `tuist init/bootstrap <template name> <module name> <other arguments>`.  Other arguments should allow us to reasonably customise template. As an example: module can contain the functionality itself, demo app to run that will include that functionality, various tests(unit/ui/snapshot/performance/etc), mocks, accessibility etc. But if you are implementing non-UI things(i.e. networking) there's no sense to include snapshot tests and accessibility for example so it would be nice not to generate them and their files at all.

From implementation standpoint there should be some way to declare template structure so that it could be validated as well. Then we somehow register them with tuist to be able to use them(some templates folder?). Extension of `init` command and/or new command (`bootstrap`?) will be needed as well. 

# Drawbacks

Why should we *not* do this? Please consider:
(I'm not exactly familiar with internals of tuist so what's below might be not accurate)
- implementation cost, both in term of code size and complexity: Probably most complex thing would be implementation of structure for template and validation. 
- the impact on teaching people Tuist: additional feature that should be documented - how to create new templates and template format
- integration of this feature with other existing and planned features - ?(couldn't find any issues with that, not familiar enough) 
- cost of migrating existing projects (is it a breaking change?): not a breaking change so should not cost anything

There are tradeoffs to choosing any path. Attempt to identify them here.

More complexity in code and additional structure to define templates.

## Alternatives

I could think of 1 alternative so far: 
Hardcode structure in new command, that would require every developer to make own custom command for that which would result in many similar implementations that couldn't be contributed back.

# Adoption strategy

Incremental change to init command/creation of new command

# How we teach this

As more flexible extension of `init` command.

# Unresolved questions

How do we actually define a template? Exact structure, command changes etc.

**Comment by pepibumur** [comment]
cc @fortmarek it seems there's some interest in the scaffolding feature that you are working on :)

**Comment by fortmarek** [comment]
Hey!

Glad to see interest in this feature - I have been working on it [here](https://github.com/tuist/tuist/issues/813). It's still WIP, I'll be sure to add a fixture this week, so you can play with it if you desire.

Currently, you can check out a template in `Templates/default`, follow the issue to follow the progress - I'd like to get a working example done by the end of this week.

**Comment by TimurBK** [comment]
Hey. 🙂 
Looks like I missed that. Looks exactly what I'm looking for. Will close and move there.
