### ISSUE TITLE
Adopt ArgumentParser for the command-line tool

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#1040]
## Context 🕵️‍♀️

Tuist uses `SPMUtility` framework (which is part of the [Swift Package Manager repository](https://github.com/apple/swift-package-manager)) for command-line argument parsing. Recently Apple announced a new [ArgumentParser](https://swift.org/blog/argument-parser/) library:

> We’re delighted to announce [ArgumentParser](https://github.com/apple/swift-argument-parser), a new open-source library that makes it straightforward — even enjoyable! — to parse command-line arguments in Swift.

The API of the library simplifies the argument parsing logic a lot. There is no boilerplate and the code is very readable and easy to follow. I believe `Tuist` can greatly benefit from it. 

[`swift-format`](https://github.com/apple/swift-format) already created a [pull request](https://github.com/apple/swift-format/pull/154) with the integration of ArgumentParser.

## Proposal 🎉

I would like to propose the integration of ArgumentParser for the command-line argument parsing in `TuistKit` framework.

**Comment by natanrolnik** [comment]
I'll try to take this one

**Comment by ollieatkinson** [comment]
@fortmarek pointed out:
> I'd just look into what it doesn't support at the moment - in the blog post they have mentioned they will not adopt it in spm because it'd regress the functionality in some aspects - those should be mentioned here https://github.com/apple/swift-argument-parser/issues

**Comment by fortmarek** [comment]
@natanrolnik have you had time to work on it? If not, I'll create a kick-off WIP PR to start the work on it and you can join me there if you find the time 🙂

**Comment by natanrolnik** [comment]
@fortmarek unfortunately I didn’t have the time. If you start I can try “joining” you and we could split some files.

**Comment by fortmarek** [comment]
Sounds great @natanrolnik! I'll definitely let you know.

**Comment by mollyIV** [comment]
Maybe we could create a sub-task per command? Plus one sub-task for linking the new library. We could create a parent branch where we'd merge all the sub-tasks. And by sub-tasks I mean simple checkbox list like: 

- [ ] Use Argument Parser library in tuist up command.
- [ ] Use Argument Parser library in tuist generate command.  

In that way we could work in parallel on a smaller pieces. 

Thoughts? 

I'll gladly help too 😊😊

**Comment by fortmarek** [comment]
I think that's a great idea @mollyIV ! I'd just make sure that we get one command right and then we can divide up the rest of the work. We will need to figure out what our conventions will be - and there are some issues we have to resolve first, for example it is not possible to use custom initializers for `ParsableCommand`, so we will need to find a way how to inject our dependencies.
@pepibumur has proposed to solve this with adding an extra layer and using `ParsableCommand` just for parsing and for the feature composition we could introduce `Interactor` (naming not setttled) that'd then be injectable.

I'll try to kick it off later today, so we can start working on it.

**Comment by pepibumur** [comment]
Yeah, I suggested extracting logic from commands into services. The responsibilities would be:
- **Commands:** Parsing the arguments and passing them down to services.
- **Services:** Business logic of the commands. They represent users' intents. 

The services would be classes, with a method that takes all the arguments that can be passed to a command. For instance:

```swift
protocol GenerateServicing {}
class GenerateService: GenerateServicing {
  func run(path: AbsolutePath) throws {
    // Logic
  }
}
```

That way we can test the business logic, without implicitly testing the arguments parsing too. In fact, I don't think commands would need tests anymore, because they'd just be a name, description, and list of arguments, and I don't see a value on testing those things.

**Comment by pepibumur** [comment]
@mollyIV what about joining our Slack? It'll be easier to coordinate the work with @fortmarek, https://slack.tuist.io

**Comment by mollyIV** [comment]
Sure 🙌  I just did.
