### ISSUE TITLE
Could not find or use auto-linked framework in Tests

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#1058]
**Describe the bug**
When you create a test target, in the dependencies is the target that you want to test - and that *should* include all the dependencies of that target. That means if I have a Carthage framework that I then need to also leverage in tests, I'd expect it to work.

Unfortunately, when you import such a dependency, you get this error:
```
ld: warning: Could not find or use auto-linked framework 'BetterLabel'
Undefined symbols for architecture x86_64:
  "type metadata accessor for BetterLabel.BetterLabel", referenced from:
      variable initialization expression of CarthageTestsKitTests.CarthageTestsKitTests.betterLabel : BetterLabel.BetterLabel in CarthageTestsKitTests.o
      CarthageTestsKitTests.CarthageTestsKitTests.init(invocation: __C.NSInvocation?) -> CarthageTestsKitTests.CarthageTestsKitTests in CarthageTestsKitTests.o
      CarthageTestsKitTests.CarthageTestsKitTests.init(selector: ObjectiveC.Selector) -> CarthageTestsKitTests.CarthageTestsKitTests in CarthageTestsKitTests.o
      CarthageTestsKitTests.CarthageTestsKitTests.init() -> CarthageTestsKitTests.CarthageTestsKitTests in CarthageTestsKitTests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**

1. Add a framework to your project
2. `import` that framework in tests and use one of the methods of that framework
3. voila - error

Alternatively, I have created an example project [here](https://github.com/fortmarek/TuistCarthage). Just head to `Projects/CarthageTestsKit`, generate the project and try to run the tests. [This](https://github.com/fortmarek/TuistCarthage/blob/master/Projects/CarthageTestsKit/Tests/CarthageTestsKitTests.swift) file is the culprit here.

**Expected behavior**
I'd expect that Xcode can find the auto-linked framework that is in the test's "parent" target.

**Desktop (please complete the following information):**

- OS: macOS 
- Version: 10.15.1
- Tuist version: 1.3.0

**Additional context**
If someone can confirm that it, indeed, is a bug, I am willing to look into it to see where the problem lies 🙂

I feel this is very closely tied to this [issue](https://github.com/tuist/tuist/issues/253) but, if I understand it correctly, that was about transitive dependencies between targets, but does not apply to tests (which I figured from [this](https://github.com/tuist/tuist/blob/dc2757424578b56872cc62d739dec15235090d95/Sources/TuistCore/Graph/Graph.swift#L402) part of Graph code)

@ollieatkinson you have fixed the bug mentioned above, maybe you could have some insight into this?

**Comment by kwridan** [comment]
Thanks for including a sample project @fortmarek! 

I wasn't able to get the the same linker error :/ (I was using Tuist 1.5.4)
The test compiled successfully for me, I did get a different unrelated runtime error:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'Main' in bundle NSBundle
```

**Comment by fortmarek** [comment]
Thanks for looking into it @kwridan. Adding those dependencies to the test target is probably the right thing to do anyway, therefore I will close this.
