### ISSUE TITLE
[Discussion] Supporting cached frameworks during the generation

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#1059]
Related: https://github.com/tuist/tuist/issues/977

## Context

As you might now, I'm working on adding support for caching to Tuist. In a nutshell, the way it works is that for each framework target that is part of the dependency graph we try to get their pre-compiled xcframework from a cache, and **adjust the graph** accordingly to replace dependencies and transitive dependencies of the entry point targets with their xcframeworks if possible.

Since an image is worth a thousand words, the image below represents what we are trying to achieve:

![Untitled Diagram-Page-7](https://user-images.githubusercontent.com/663605/75870978-24e7a200-5e0c-11ea-994b-ce5b70b2f026.png)

## Proposals
I've been pondering several ideas around how to achieve that and I'd like to share them with you to get your thoughts on them.

### Proposal 1: Graph mutation
The first idea is to mutate the graph after loading it to memory and determining which changes need to be applied based on the targets whose .xcframework exist in the cache.

#### Advantages
- We don't need to change anything in the logic that generates the Xcode projects because it already supports generating nodes that are .xcframeworks.

#### Disadvantages
- The mutation operation requires IO (pull the .xcframeworks from the cache) which doesn't align with the effort of eliminating side effects during the manipulation of the graph.
- The logic is tied to the caching feature and cannot be reused to support swapping Carthage dependencies with their source code.
- Since we'll mutate the graph (reference type) that might complicate future optimisations leveraging threads.
- The mutation logic might end up being really hard to be reasoned about.

### Proposal 2: Introduction of a new node type
With this approach we'd still need to mutate the graph, but it'd be less aggressive than with the approach 1 because we'd only need to change the node types. We'd introduce a new node type along the lines of:

```swift
.cached(project: "./Feature", target: "Feature", xcframework: "/path/to/Feature.xcframework") 
```

#### Advantage
- The mutation is less aggressive and easier to reason about. We are just changing the node type.
- We can assume the path where the .xcframework will exists if it's pulled from the cache, minimising the IO significantly. The only IO necessary would be to get the hash of the targets, which is necessary to look up the xcframework in the cache.
- We'll be able to provide a user API if we believe there's a need for that.

#### Disadvantages
- We'd need to adjust the logic that generates the Xcode projects to take into account the new node type. That complicates the generation logic.
- We wouldn't be able to reuse it for the use case that @ollieatkinson brought up to do something similar with Carthage dependencies. In this case the source code lives in another Xcode project and it's a precompiled framework instead of an .xcframework.

cc @tuist/core  / @andreacipriani / @RomainBoulay / @vytis

**Comment by kwridan** [comment]
Thanks for putting this together @pepibumur 

You've summed up the pros and cons of both approaches quite nicely. 

> Proposal 1: Graph mutation
> The mutation operation requires IO (pull the .xcframeworks from the cache) which doesn't align with the effort of eliminating side effects during the manipulation of the graph.

Not sure there a way around that, there will be IO somewhere in the pipeline for this work to happen :( - it needn't be at loading time, but perhaps an explicit step after loading.

```swift
let graph = graphLoader.load(...)
let updatedGraph = transform(graph)
```

> Since we'll mutate the graph (reference type) that might complicate future optimisations leveraging threads.

- In the event the mutation occurs ahead of generation it should be ok even with concurrency (assuming generation is what would be run concurrently e.g. for each project)
- We can revisit the graph types, additionally we aren't restricted to one graph :) - each graph serves a purpose for the components its used within, we can make another more suitable for this task.

> The mutation logic might end up being really hard to be reasoned about.
Let's look for opportunities to simplify it if we can - creating simpler / intermediary graph representations may help us here. The existing `Graph` type could be retired back to being private detail of the generator. Instead we could provide the generator with a different simpler input type.

> Proposal2: Introduction of a new node type
> We'd need to adjust the logic that generates the Xcode projects to take into account the new node type. That complicates the generation logic.

Indeed adding more non Xcode project generation logic to the generator would unnecessarily complicate it. We can look for opportunities for composing / layering components, e.g. as things stand, I believe the generator is capable of producing the desired results by tweaking its input. 

I'd like to propose another option inspired by the previous 2 (still in raw form). 

### Propsals 3: Manifest Graph Transformation

We could create a separate value type graph of manifests (the `ProjectDescription` types). Those can be loaded transitively without needing to map them just yet.

```swift
import Basic
import ProjectDescription

public struct ManifestGraph {
    public var workspace: (AbsolutePath, Workspace)?
    public var projects: [AbsolutePath: Project]
}

public protocol ManifestGraphLoading {
    func load(at path: AbsolutePath) throws -> ManifestGraph
}
```

Once loaded we can modify this lighter weight graph to replace `.cached` > `.xcframework` or `.framework` based on the desired logic.

![manifest-transformer](https://user-images.githubusercontent.com/11914919/76165778-b0856980-6151-11ea-96e5-5b37fb6f39fb.png)

An example (without transitive lookups):

```swift
class ReplaeCachedProjectsManifestTransformer {
    func transform(graph: ManifestGraph) -> ManifestGraph {
        var updated = graph
        updated.projects = graph.projects.mapValues(transform)
        return updated
    }

    private func transform(project: Project) -> Project {
        let targets = project.targets.map(transform)
        return project.replacing(targets: targets)
    }

    private func transform(target: Target) -> Target {
        let dependencies: [TargetDependency] = target.dependencies.flatMap {
            switch $0 {
            case let .cachedProject(target: _, path: _, cachedPath: cachedPath):
                // TODO: transitive lookups can be done here
                return [.xcFramework(path: cachedPath)]
            default:
                return [$0]
            }
        }
        return target.replacing(dependencies: dependencies)
    }
}
```

**Advantages**

- No changes required to the generation logic (like option 1)
- Allows adding further transformations (e.g. for both xcframeworks and Carthage)
- Avoids needing to introduce new model types that aren't used by the generator directly

**Disadvantages**

- An additional piece in the pipeline 
- Some of the graph operations like doing transitive look-up may seem duplicative
