### ISSUE TITLE
Incorrect output archive type

### ISSUE THREAD

**Issue by ferologics** [tuist/tuist#1060]
**Describe the bug**
Fastlane`build_app` outputs a `Generic Xcode Archive` instead of `iOS App Archive` after making changes to the project template. This happened once I made changes to the project schemes with custom configurations where the production configuration has custom settings as following:
```
"CODE_SIGN_STYLE : "Manual",
"CODE_SIGN_IDENTITY": "iPhone Distribution",
"PROVISIONING_PROFILE_SPECIFIER": "match AppStore com.test.app"
```

**To Reproduce**
This issue is hard to reproduce, I’m opening a ticket for now, but idk if I can make a fixture that reproduces the error, because it requires a custom account, provisioning profile, and certificate.

**Expected behavior**
Fastlane `build_app` outputs an `iOS App Archive`

**Desktop (please complete the following information):**

- OS: macOS 10.15.3 Beta (19D62e)
- Version: 1.2.0

**Additional context**

[Error.log](https://github.com/tuist/tuist/files/4293581/error.log) from terminal.

Apple [technical note on generic/ios app archives](https://developer.apple.com/library/archive/technotes/tn2215/_index.html#//apple_ref/doc/uid/DTS40011221-CH1-PROJ) statement:
> Your archive contains static libraries or frameworks.
> You must set "Skip Install" to YES to prevent your static libraries or framework from being added to your archive.

> Note: If your archive contains unexpected items such as header files, static libraries, or frameworks, then it is a generic Xcode archive.

I tried to set the `export_xcargs: "SKIP_INSTALL=YES"` on `fastlane build_app` command but this did not result in an `iOS App Archive`.

**Comment by pepibumur** [comment]
Hi @ferologics. Thanks for bringing this up and sorry for the inconveniences caused by the issue.
Would you mind including a [reproduction case](https://tuist.io/docs/contribution/reporting-bugs/#reproducible-cases) that we can use for debugging the issue?
