### ISSUE TITLE
lint command not available

### ISSUE THREAD

**Issue by c0diq** [tuist/tuist#1086]
## Context 🕵️‍♀️

The documentation states `lint` is an option to help find issues with setup. The command is missing.

## What 🌱

> Documentation [lint](https://tuist.io/docs/usage/commands/#lint) is not working:
```
> tuist lint
Error: expected arguments: build, init, cache, create-issue, up, focus, dump, generate, edit, version, graph
> tuist version
1.3.0
```

## Proposal 🎉

> Fix or update documentation

**Comment by pepibumur** [comment]
Hi @c0diq. Even though the lint command is documented, it hasn't been released yet. It'll be part of the next release that will be published tomorrow. Stay tuned!

**Comment by c0diq** [comment]
@pepibumur Can we get this in the new release https://github.com/tuist/tuist/pull/1062 ? I am not able to understand the issue with the changelog action complaining.
