### ISSUE TITLE
Build command

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#111]
## Context 🕵️‍♀️
SPM alike, Tuist can provide a command to build the project in the current directory. The command would wrap `xcodebuild`, simplifying the interface and inferring things whenever it's possible. For instance, we know the path to the project and workspace.

## What 🌱
Being in a folder where a project is defined, a developer could execute:

```bash
tuist build # main/default target
tuist build target
```

## Proposal 🎉
- Add `build` command which is a gateway to `xcodebuild`.
- Proxy the arguments passed to `xcodebuild`. For example, if a `-destination` command is passed, we should pass it to `xcodebuild`.
- Print the output from `xcodebuild` without any formatting. We might add some improvements here in  the future, but for now, let's keep the raw output.

**Comment by pepibumur** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build command](https://trello.com/c/bLQtUQvX/7-build-command)
