### ISSUE TITLE
Test command

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#112]
## Context 🕵️‍♀️
SPM alike, Tuist can provide a command to test the project in the current directory. The command would wrap `xcodebuild`, simplifying the interface and inferring things whenever it's possible. For instance, we know the path to the project and workspace.

[Here's](https://github.com/tuist/tuist/issues/111) the other issue to something similar for building the target.

## What 🌱
Being in a folder where a project is defined, a developer could execute:

```bash
tuist test # main/default target
tuist test target
```

## Proposal 🎉
- Add `test` command which is a gateway to `xcodebuild`.
- Proxy the arguments passed to `xcodebuild`. For example, if a `-destination` command is passed, we should pass it to `xcodebuild`.
- Print the output from `xcodebuild` without any formatting. We might add some improvements here in  the future, but for now, let's keep the raw output.

**Comment by pepibumur** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test command](https://trello.com/c/XHHp9V5g/8-test-command)
