### ISSUE TITLE
Custom up command in the setup manifest to install the packages from Mint

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#1122]
## Context 🕵️‍♀️

It is possible to define a custom [up command](https://tuist.io/docs/usage/commands/#up) in the setup manifest. Let's assume a project setup depends on some packages installed via [Mint](https://github.com/yonaskolb/Mint). Mint allows to specify the list of packages in [Mintfile](https://github.com/yonaskolb/Mint#mintfile), for example:

```
yonaskolb/xcodegen@1.10.3
yonaskolb/genesis@0.2.0
```

The benefit of it is that the versions are centralized and you can simply call:

```
mint run xcodegen
```

Mint will take care of using the correct version of a package defined in a Mintfile. 

## What 🌱

Assuming we have Mintfile:

```
apple/swift-format@master
krzysztofzablocki/Sourcery@0.17.0
``` 

we can check if all the packages are installed via:

```bash
$ cat Mintfile | xargs -n 1 mint which
/usr/local/lib/mint/packages/github.com_apple_swift-format/build/master/swift-format // 👍 a swift-format is installed
/usr/local/lib/mint/packages/github.com_krzysztofzablocki_Sourcery/build/0.17.0/sourcery // 👍 Sourcery is installed
```

I am trying to set it up in a  `Setup` file:

```swift
let setup = Setup([
  .homebrew(packages: ["mint"]),
  .custom(
    name: "mint",
    meet: ["mint", "bootstrap"],
    isMet: ["cat", "Mintfile", "|", "xargs", "-n", "1", "mint", "which"]
  )
])
```

When I call `tuist up`, looks like the pipe character **'|' is escaped and `isMet` check does not work as intendent**:

```bash
...
/usr/bin/env which cat
/bin/cat

/bin/cat Mintfile '|' xargs -n 1 mint which

Configuring mint
/usr/bin/env which mint
/usr/local/bin/mint

/usr/local/bin/mint bootstrap
...
```

**Workaround**

As a workaround the command checking that each packages is installed could be extracted to a separate script file:

```
#!/bin/bash

cat Mintfile | xargs -n 1 mint which
```

```swift
let setup = Setup([
  .homebrew(packages: ["mint"]),
  .custom(
    name: "mint",
    meet: ["mint", "bootstrap"],
    isMet: ["./mint-is-met.sh"]
  )
])
```

## Question 🤔 

I've been wondering if there's a better way than extracting `isMet` logic to a separate script? 🤔 

💡 Maybe it's even worth to consider adding a Mint to a set of predefined commands:

```swift
let setup = Setup([
    .mint(packages: ["krzysztofzablocki/Sourcery@0.17.0"]),
    ...
  ])
```

Thank you so much for your help 🙇

**Comment by pepibumur** [comment]
> 💡 Maybe it's even worth to consider adding a Mint to a set of predefined commands:

I think it’s a good idea. Would you like to open a PR with the contribution yourself?

**Comment by mollyIV** [comment]
Sure, I can give it a shoot 👍 

Before starting the implementation, I'd like to clarify few things:

**1. Supporting Mintfile by default**

In the simplest form of installing the packages via Mint, we could support Mintfile by default:

```swift
import ProjectDescription

let setup = Setup([
  .mint()
])
```

We could also expose the option of linking the packages globally (optional parameter in a constructor): 

```swift
import ProjectDescription

let setup = Setup([
  .mint(linkPackagesGlobally: true)
])
```

The [`mint bootstrap`](https://github.com/yonaskolb/Mint#usage) command would be executed under the hood. 

2. Installing individual packages

In that case, we would not take Mintfile into account. The API could look like:

```swift
import ProjectDescription

let setup = Setup([
  .mint(packages: [
    .package("githubName/repo", .exact("1.2.3")),
    .package("https://example.com/example-package.git", .branch("master"))
  ])
])
```

The [`mint install <package>`](https://github.com/yonaskolb/Mint#usage) command would be executed under the hood. We could expose the option of linking the packages globally (optional parameter in a constructor), very same as mentioned in point 1. 

Does that sound good? 🤔

**Comment by pepibumur** [comment]
I'd go for the option 1. The downside of adding support for 2) is that there'd be an extra API that we'd need to maintain. It's not a lot of work, but since that information can live in the `Mintfile`, I don't see why we should provide a second interface.

Does it generate a lockfile that we can use to know if we need to run the mint command?

**Comment by mollyIV** [comment]
> Does it generate a lockfile that we can use to know if we need to run the mint command?

There's no lockfile, but Mint has a `which` command:

```
$ mint which --help

Usage: mint which <package> [<executable>] [options]

Prints the full path to the installed executable
```

So the idea is that we could read a Mintfile line by line and check if every package is installed:

```
$ cat Mintfile | xargs -n 1 mint which
```

If it is not, we the `isMet ` condition will not be satisfied.

**Comment by pepibumur** [comment]
Can we check if the version installed matches the one indicated in the Mintfile?

**Comment by mollyIV** [comment]
Yes, we can. Let's say that In Mintfile a user would specify the version like:

```
apple/swift-format@swift-5.1-branch
```

Then calling:

```bash
$ mint which apple/swift-format@swift-5.1-branch
```

would check if the very same version specified in Mintfile is installed on a user machine. 

![image](https://user-images.githubusercontent.com/10795657/76998317-2dd08b80-6955-11ea-9cfa-d8ef00d787ed.png)

**Comment by pepibumur** [comment]
Perfect! The idea sounds good to me 🤗
