### ISSUE TITLE
Generate reference pages

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#114]
## What 🕵️‍♀️
Like [CocoaPods](https://guides.cocoapods.org/syntax/podfile.html) does to document the syntax of the `Podfile` and the `.podspec` files, we should have a reference on the website as well. The reference is useful for developers to know which attributes are available in the API and their keys when defining the manifests as a yaml or json.

**Comment by santos88** [comment]
@pepibumur is this issue regarding to upload the current /doc files into a public server? or to choose an alternative to the current Jazzy auto generated documentation?

**Comment by pepibumur** [comment]
The goal of the task is:
- Add the `.jazzy.yaml` file in those Swift projects that don't have it.
- Update the `RELEASE.md` and include a step to generate the documentation by [running this script](https://github.com/tuist/jazzy-theme)
- Enable GitHub pages for those repositories *(from the /docs directory)*

I'll update the website and add a new section where we list all the organization projects.

**Comment by pepibumur** [comment]
This is already done :). All projects are now listed [here](https://tuist.io/open-source/) and include a link to their references.
