### ISSUE TITLE
Tuist list output

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#1147]
## Need/problem

As @pepibumur has described [here](https://github.com/tuist/tuist/pull/1129#pullrequestreview-379333013), it'd be great to make `tuist scaffold --list` output readable by grep and also add option for changing the output to JSON.

## Motivation

Both additions will make it easier for developers to work with the listed templates - which will definitely come in handy when we/developers start adding more templates

## Detailed design

Changing the default output to a table-like one.
Adding option `--json` to print the list in `.json` format

# Drawbacks

None, AFAIK

## Alternatives

Different output format, but I feel people from Unix world should be at home with grep-parsable tables.

**Comment by mollyIV** [comment]
Hey @fortmarek,

If you do not mind, I would like to give it a shoot 💪

**Comment by fortmarek** [comment]
Sure, go ahead, @mollyIV!

Let me know if you need any help and thanks for taking this on 🙂
