### ISSUE TITLE
Unwanted warning about Info.plist files added as resources

### ISSUE THREAD

**Issue by sgrgrsn** [tuist/tuist#1170]
Firebase (and possibly other services) requires us to add a plist file as a resource for the app target to configure it properly. Tuist gives us a warning when trying to do so.

**Steps to reproduce**
1. Create a project with a plist file in the resources folder.
2. Run `tuist generate`
3. See the warning: `Info.plist at path /path/to/project/Resources/GoogleService-Info.plist being copied into the target AppProject product.`

I've also create a sample project you can run to reproduce it:
[SampleProjectInfoPlist.zip](https://github.com/tuist/tuist/files/4403346/SampleProjectInfoPlist.zip)

**Expected behavior**
I didn't expect to be warned about including the plist file for Firebase as it should be a part of the resources in the app target.

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Version: 1.5.2

**Additional context**
@pepibumur asked be to create this issue with the following message on the Slack channel:
> Would you mind opening an issue to get rid of that check? That's a good example of a false positive that you should have not been warned about.

**Comment by sgrgrsn** [comment]
@pepibumur I've created the issue we discussed on Slack today.

**Comment by sgrgrsn** [comment]
@pepibumur I would like to make a PR for this - do you think we should just remove the check all together, or did you have something in mind to make the check smarter?

**Comment by olejnjak** [comment]
I haven't looked into code of the check, but I think this warning is quite nice, I assume that right now the check just checks target resources for files containing _Info.plist_ in name, maybe it would be possible to check if target resource files contain file defined in its `INFOPLIST_FILE` build setting?

**Comment by sgrgrsn** [comment]
Yes, right now it's just a simple check on the copied resource files. The warning will show if one of the files includes `Info.plist` in the filename.

```swift
private func lintCopiedFiles(target: Target) -> [LintingIssue] {
    var issues: [LintingIssue] = []

    let files = target.resources.map(\.path)
    let infoPlists = files.filter { $0.pathString.contains("Info.plist") }
    let entitlements = files.filter { $0.pathString.contains(".entitlements") }

    issues.append(contentsOf: infoPlists.map {
        let reason = "Info.plist at path \($0.pathString) being copied into the target \(target.name) product."
        return LintingIssue(reason: reason, severity: .warning)
    })
    issues.append(contentsOf: entitlements.map {
        let reason = "Entitlements file at path \($0.pathString) being copied into the target \(target.name) product."
        return LintingIssue(reason: reason, severity: .warning)
    })

    issues.append(contentsOf: lintInfoplistExists(target: target))
    issues.append(contentsOf: lintEntitlementsExist(target: target))
    return issues
}
```

I was thinking that we could change the check to see if one of the copied resource files are equal to the one defined in the targets info plist path, and then only raise the warning in that case.

What do you think about that? @olejnjak

**Comment by olejnjak** [comment]
Yes I think that's more concretely the solution suggested above 👍

**Comment by sgrgrsn** [comment]
Alright - I'll see if I can come up with a PR with this change 👍 

It's my first attempt to contribute to open source with actual code changes, so I hope I will succeed 😃

**Comment by sgrgrsn** [comment]
@olejnjak @pepibumur 
I've made a PR draft - what do you think about the approach?

https://github.com/tuist/tuist/pull/1203
