### ISSUE TITLE
Bad deployment target XCode 11.4 Tuist 1.5.4

### ISSUE THREAD

**Issue by JulianAlonso** [tuist/tuist#1184]
**Describe the bug**
I'm using XCode 11.4 and Tusit 1.5.4, DeploymentTarget it's always set to Default, but I have configured to 11 on the target configuration

**To Reproduce**

1. run `tuist generate`
2. check project deployment target

<img width="337" alt="Screenshot 2020-04-03 at 12 46 19" src="https://user-images.githubusercontent.com/5766613/78354098-83d73d00-75ab-11ea-9189-33dfa9f0838e.png">

**Expected behavior**
Deployment target set to 11.0

**Additional context**
You can check the whole project on https://github.com/JulianAlonso/Injection

**Comment by pepibumur** [comment]
This is not a legit bug. I double-checked the generation logic and we are generating the right build settings for the deployment target specified by the targets. @JulianAlonso was expecting the projects to have that deployment target setting too, but as I pointed out, we don't have an API for that and they need to be set manually through build settings.
