### ISSUE TITLE
Tuist changes the project file with cocoapods as a dependency

### ISSUE THREAD

**Issue by remover** [tuist/tuist#1198]
## Context 🕵️‍♀️

Tuist 1.5.4

## What 🌱

With a simple project that uses cocoapods as a dependency, running `tuist generate` changes the project file even if there are no code / podfile changes of any sort.

to repro:

download the attached project
run `tuist generate`
stage your changes
run `tuist generate` again
observe there's more changes in the project file

compare this with `running bundle exec pod install --repo-update` directly instead of `tuist generate` in the above steps. 
as expected there are no changes

[soundcloud-basic-pods-issue.zip](https://github.com/tuist/tuist/files/4439741/soundcloud-basic-pods-issue.zip)

**Comment by pepibumur** [comment]
@remover I'm not able to reproduce this one. Would you mind trying with the latest Tuist version, 1.6.0

**Comment by remover** [comment]
same issue with 1.6.0 :(

when i run tuist generate --verbose i get:

```
...
Checking if /Users/donalobrien/Documents/ProjectGeneration/soundcloud-basic-pods-issue/Podfile exists... true
The target SoundCloud doesn't contain source files.
Generating workspace SoundCloud.xcworkspace
Generating project SoundCloud
xcode-select -p
/Applications/Xcode11.4.app/Contents/Developer

bundle show cocoapods

/usr/bin/env which pod
/Users/donalobrien/.rvm/gems/ruby-2.6.3/bin/pod

Installing CocoaPods dependencies defined in /Users/donalobrien/Documents/ProjectGeneration/soundcloud-basic-pods-issue/Podfile
bundle exec pod install --project-directory=/Users/donalobrien/Documents/ProjectGeneration/soundcloud-basic-pods-issue
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

Project generated.
Total time taken: 2.819s
```

**Comment by pepibumur** [comment]
What version of CocoaPods are you using?

**Comment by remover** [comment]
1.8.4... that should be specified in the `Gemfile`

btw a few of my colleagues have been able to reproduce this...

**Comment by RomainBoulay** [comment]
Hello friends!! I was wondering if things were moving here + if we could help?

We have found a way to temporary workaround the issue but we know that it is not the best solution. Would be amazing to have this solved by tuist directly!

**Comment by pepibumur** [comment]
I'm afraid this is an issue on the CocoaPods side. It returns a deterministic result when `pod install` is run on a project with Pods already integrated, but it fails to do it deterministically when it's run on a clean project. I'll come up with a reproducible case that you can use to open a ticket on CocoaPods.

**Comment by andreacipriani** [comment]
I can also confirm that I can reproduce the issue, see attached diff after re-running `tuist generate` 
[diff.txt](https://github.com/tuist/tuist/files/4630058/diff.txt)

**Comment by grigorye** [comment]
Folks, I'm not 100% this is relevant, but I believe that I faced similar problem with XcodeGen-generated projects (which also uses Tuist's XcodeProj).

This is the original issue in CocoaPods:

https://github.com/CocoaPods/CocoaPods/issues/9359

From what I understand, it's easily fixable by something like this as a post-processing stage after `pod install`:

```
let xcodeproj = try XcodeProj(path: projectPath)
xcodeproj.pbxproj.invalidateUUIDs()
try xcodeproj.write(path: projectPath)
```

It's also available as a Swift-package I published below:

https://github.com/grigorye/xcodeprojFixUUIDs

We've been using it in production for quite some time and so far it works as expected.

**Comment by remover** [comment]
thanks for the tip @grigorye ... in the end we git ignored the project files but i will keep this in mind in case we need to come back to it
