### ISSUE TITLE
Add ability to generate Command Line Tool product types

### ISSUE THREAD

**Issue by raven** [tuist/tuist#1224]
## Need

I'd like to see Tuist have the ability to create Command Line Tools.

![image](https://user-images.githubusercontent.com/316931/79205561-73637400-7e81-11ea-9ab6-5f0018269f2c.png)

## Motivation

When working on iOS apps, I occasionally create a macOS Command Line Tool as an alternative "interface" to the application core frameworks. I have also recently been experimenting with spinning up CLIs for interacting with running iOS apps, as per: https://rambo.codes/posts/2020-03-01-writing-command-line-interfaces-for-ios-apps 

## Detailed design

This would involve extending the `Product` enum with a `.commandLineTool` case, and all that flows from that. (Currently researching what is involved)

## Drawbacks

This will further add complexity to the `Product` type. 

## Alternatives

Generating Command Line Tool targets manually via Xcode outside of the tuist workflow. This is less than ideal in the use cases I've highlighted above where it makes sense to 

## Adoption strategy

This isn't a breaking change, should be purely additive.

## How we teach this

Documentation should be updated to highlight this capability.

**Comment by kwridan** [comment]
Hi @raven, thanks for putting together this proposal.

> Detailed design

It will also be helpful to get an idea of any special rules for this new product type that we can codify in linters (e.g. command line tools can't contain resources). 

> Alternatives

It's worth taking into consideration that the Swift Package Manager may be able to fill this role and is perhaps better geared to support command line tools in general. 

That said, if you're attempting to leverage frameworks that aren't packages for your existing app, it may not be able to support that giving this proposal some value.
