### ISSUE TITLE
Error when generating project containing localized intentdefinition

### ISSUE THREAD

**Issue by Rag0n** [tuist/tuist#1225]
**Describe the bug**
This case works: target with .intentdefinition file added as source file.

This case doesn't work: target with localized .intentdefinition file added as source file.

Next error is received hen trying to generate project for the second case:
`Trying to add a file at path ..../Intents/Base.lproj/Example.intentdefinition to a build phase that hasn't been added to the project.`

I think issue exist because in this case .intentdefinition is located inside .lproj folder(eg: Base.lproj/Example.intentdefinition)

**To Reproduce**

1. Add appExtension target
2. Add .intentdefinition to this target as source file
3. Add localization for this .intentdefinition
4. Generate project

**Expected behavior**
Project is successfully generated.

**Additional context**
As a workaround I'm currently generating project with intentdefinition without localization. Then I'm manually adding localization.

**Comment by kwridan** [comment]
Thanks for flagging this @Rag0n 

Good catch, Tuist currently supports localized resources but not sources and is the reason for that error. It's something that can be added. 

From what I saw the logic is very similar to how resources are handled.

e.g.

- Add a `PBXVariantGroup`

```diff
+ FBF61BCD2446D887004672B4 /* Intents.intentdefinition */ = {
+     isa = PBXVariantGroup;
+     children = (
+         FBF61BCC2446D887004672B4 /* Base */,
+         FBF61BCF2446D88C004672B4 /* en */,
+     );
+     name = Intents.intentdefinition;
+     sourceTree = "<group>";
+ };
```

- Add a reference to the group within the file elements

```diff
FBF61BA92446D846004672B4 /* IntentsExtension */ = {
    isa = PBXGroup;
    children = (
        FBF61BAA2446D846004672B4 /* IntentHandler.swift */,
        FBF61BAC2446D846004672B4 /* Info.plist */,
+        FBF61BCD2446D887004672B4 /* Intents.intentdefinition */,
    );
    path = IntentsExtension;
    sourceTree = "<group>";
};
```

- Add a `PBXBuildFile` referencing that group to the sources build phase

```diff
+ FBF61BCB2446D887004672B4 /* Intents.intentdefinition in Sources */ = {isa = PBXBuildFile; fileRef = FBF61BCD2446D887004672B4 /* Intents.intentdefinition */; };
```
