### ISSUE TITLE
Pods project not imported into workspace when tuist generate is launched from root "Workspace" directory 

### ISSUE THREAD

**Issue by che1404** [tuist/tuist#1226]
First of all, thank you so much for this wonderful tool. I'm really enjoying playing with it!

**Describe the bug**
The Pods project for an app is not being generated on `tuist generate` , when the app contains Cocoapods dependencies and we run the command from a root "Workspace" directory.

**To Reproduce**

1. Clone the repo git@github.com:che1404/tuist-issue.git, which contains a minimal example
2. Run tuist focus from the root directory and observe that the workspace doesn't have any Pods project
3. cd to the Project/AppUsingPods folder and run tuist focus in there. Observe that this time, the Pods project has been successfully generated, and the project builds just fine.

**Expected behavior**
I would expect tuist generate/focus to add the Pods project when it is launched from the root directory as well, so the build works.

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Version 10.15.4
- Tuist version 1.5.4

**Comment by ferusinfo** [comment]
First day user of Tuist here - seeing this problem as well. I can build the app from workspace generated by pods, but not by opening the project using `tuist focus`

**Comment by ollieatkinson** [comment]
You can workaround the issue by specifying a reference to the pods project in the workspace:

```swift
import ProjectDescription

let workspace = Workspace(name: "Descansare", projects: [
    "Projects/AppUsingPods"
], additionalFiles: [ "Projects/AppUsingPods/Pods/Pods.xcodeproj" ])

```

**Comment by tpsantos** [comment]
Hi, @pepibumur 

I'm having the same problem, I followed the "Getting Started" tutorial of the documentation, however when I add `.cocoapods (path:".")` in `project.swift` and `tuist generate`, the workspace does not find the pods added to the uFeature (MyAppKit) podfile.

What would be the best practice, each uFeature with its installation of Cocoapods? If the features share a pod, can we have version conflict issues?

![Screen Shot 2020-10-27 at 11 58 35](https://user-images.githubusercontent.com/6114093/97319534-bef0d480-184b-11eb-9f19-7797b3e06659.png) ![Screen Shot 2020-10-27 at 11 58 53](https://user-images.githubusercontent.com/6114093/97319586-c9ab6980-184b-11eb-8972-833db1d52f85.png)

**Comment by pepibumur** [comment]
We are moving away from the current approach to integrate pods and therefore this issue is no longer relevant. I'll close it.
