### ISSUE TITLE
Carthage support for binary json is broken

### ISSUE THREAD

**Issue by c0diq** [tuist/tuist#1232]
**Describe the bug**
If a cartfile contains a binary reference, `tuist up` will fail due to incorrectly parsing the dependency name from `Cartfile.resolved` file by failing to remove the file extension `.json` from it.

**To Reproduce**

1. Create a Cartfile with contents
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseGoogleSignInBinary.json"
```
2. Run `tuist up` once and see it doint
```
/usr/local/bin/carthage update --project-directory /Users/srebaud/dev/iOS/Frameworks/SignIn --platform iOS
```
3. See it works and create a Cartfile.resolved with contents
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseGoogleSignInBinary.json" "6.22.0"
```
4. Run `tuist up` again
3. See error this time

```
/usr/local/bin/carthage update --project-directory /Users/srebaud/dev/iOS/Frameworks/SignIn --platform iOS FirebaseGoogleSignInBinary.json

The '/usr/local/bin/carthage' command exited with error code 1
```
Executing the carthage command manually yields the error:
```
No entry found for dependency firebasegooglesigninbinary.json in Cartfile.
```

**Expected behavior**
Tuist is executing the carthage command with `FirebaseGoogleSignInBinary.json` instead of `FirebaseGoogleSignInBinary`. Separately I don't think it should try to update if there's a Cartfile.resolved which pins the version. It should just do `carthage bootstrap`.

- OS: macOS 10.15.4
- Version tuist 1.6.0

**Comment by pepibumur** [comment]
Thanks for reporting this @c0diq. I'll take a look and try to fix it.

**Comment by thedavidharris** [comment]
> Separately I don't think it should try to update if there's a Cartfile.resolved which pins the version. It should just do carthage bootstrap.

Can't find an issue on this in particular but I've noticed this is a Carthage problem, it'll just always go download it regardless.

**Comment by softmaxsg** [comment]
There is a PR (#1675) that fixes the issue.
