### ISSUE TITLE
Adding an additional Copy File Build Phase

### ISSUE THREAD

**Issue by xr1337** [tuist/tuist#1275]
## Context 🕵️‍♀️
I would like to add a new **Copy File Build Phase** to my current project.
Looking at **TargetAction**, I cant find a way to configure the project

## What 🌱
I am adding another app target which will act as a launcher for my main app.

Attached is an output example of my build phase
<img width="983" alt="Screenshot 2020-04-27 at 9 46 27 PM" src="https://user-images.githubusercontent.com/2070518/80379735-129c5880-88d1-11ea-902f-71b1c6ed934e.png">

**Comment by pepibumur** [comment]
Hi @xr1337 👋 
Correct me if I'm wrong, but is that to support "launching at login" on your macOS application. If so, I'll try to think of an abstraction that you can use instead of having to declare that build phase yourself.

**Comment by xr1337** [comment]
Hi Pedro

Yup, it is to support ‘launching at login’

Thank you

**Comment by pepibumur** [comment]
We've already added support for this.
