### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by alexanderjrobinson** [tuist/tuist#1287]
**Describe the bug**
The link to the project documentation in the README.md redirects to the wrong location.

**To Reproduce**

1. Go to Github repo tuist/tuist
2. Click on 'project documentation' in the Documentation section of README.md
3. URL redirects from https://tuist.io/docs to https://tuist.io/docs/usage/getting-started/,%20/docs/
4. Shows Page Not Found 

**Expected behavior**
Link to the getting started page of the project documentation

**Comment by pepibumur** [comment]
Thanks for reporting this, @alexanderjrobinson. The link [should be pointing](https://github.com/tuist/tuist/commit/58d7be1d2fb44fb622f7213bdf6bc84ccd5b44a7) to the right page now.
