### ISSUE TITLE
freshly generated project causes NSException when run

### ISSUE THREAD

**Issue by Evylon** [tuist/tuist#1288]
**Describe the bug**
When trying to run a freshly generated project with xcode, I encouter an NSException

`Could not find a storyboard named 'Main' in bundle NSBundle`

**To Reproduce**
1.`mkdir MyApp` 
2. `cd MyApp`
3. `tuist init --platform ios`
4. open `myApp.xcworkspace` XCode and run target `MyApp`
5. Build Successful but encounter runtime Error

**Expected behavior**
No error should occur I guess

**Screenshots**
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/46427024/80507430-23070e80-8977-11ea-8e81-e3656aa1ef63.png">

**Desktop (please complete the following information):**

- OS: macOS 10.15.3 (19D76)
- tuist version 1.7.1
- XCode version 11.4.1 (11E503a)

**Additional context**
I'm completely new to tuist and just started trying it out. Maybe I'm missing something?

**Comment by pepibumur** [comment]
Thanks for opening this issue @Evylon. It seems a legit error so I'll fix it and land a fix for the next release.

**Comment by Evylon** [comment]
Awesome thanks for the quick response.
