### ISSUE TITLE
Bundle Id Prefix

### ISSUE THREAD

**Issue by alexanderjrobinson** [tuist/tuist#1291]
## Need/problem

Currently the bundle id prefix is a literal string in the default ProjectDescriptionHelper template that used during project generation. Ideally the bundle id prefix would maintain in one place and available to be used in any template similar to the project name. 

## Motivation

Provide a single place to manage the bundle id prefix to be used across templates. 

## Detailed design

Option 1: Add a command line parameter to init to specify a bundle id prefix similar to the name attribute. The default templates would need to be updated to use the new parameter. The bundle id prefix parameter could be optional with a placeholder default value.

Option 2: Add a bundle id prefix property to the Config class to be used in the default templates. The default templates would need to be updated to use the Config class for the bundle id prefix and default to a placeholder value if not available. This is more complicated because a Config instance is optional. 

# Drawbacks

Why should we *not* do this? Please consider:

- implementation cost, both in term of code size and complexity
Requires updating the init command, project templates, and documentation
- the impact on teaching people Tuist
Adds an additional parameter for creating a new project
- integration of this feature with other existing and planned features
Unknown
- cost of migrating existing projects (is it a breaking change?) 
If the bundle id parameter is optional it should not impact migration of existing projects.

There are tradeoffs to choosing any path. Attempt to identify them here.

## Alternatives

List here the alternatives that you considered to tackle the problem and why you ruled them out in favour of your proposed solution.

# Adoption strategy

If we implement this proposal, how will existing Tuist developers adopt it? Is
this a breaking change?

# How we teach this

What names and terminology work best for these concepts and why? How is this
idea best presented? As a continuation of existing Tuist patterns?

Would the acceptance of this proposal mean the Tuist documentation must be
re-organized or altered? Does it change how Tuist is taught to new developers
at any level?

How should this feature be taught to existing Tuist developers?

# Unresolved questions

Optional, but suggested for first drafts. What parts of the design are still
TBD?

**Comment by kwridan** [comment]
Hi @alexanderjrobinson , thanks for suggesting this.

The bundle ID is defined as a string within the default template in `Tuist/ProjectDescriptionHelpers/Project+Templates.swift`, this can already act as the single canonical source, not sure I follow the issue there?

@fortmarek has done some awesome work to support the definition of custom templates with custom arguments too:

https://tuist.io/docs/commands/scaffold/

I believe between that and [`ProjectDescriptionHelpers`](https://tuist.io/docs/usage/helpers/) consistency can be achieved without constant repetition. 

As an alternate, one option we have used is defining the prefix in our `.xcconfig` file and declare the bundle ID as that setting (this was done to support multiple IDs based on configuration #927).

e.g.

```swift
bundleId: "${CUSTOM_BUNDLE_ID_PREFIX}.\(name)",
```

Hope this helps.
