### ISSUE TITLE
Support updating package dependencies 

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#1292]
## Need/problem

After updating a swift package dependency in `Project.swift` I want the next time I generate my project for things to work out. 

At the moment after updating the dependency you may be faced with the following error:

```
Using version 1.7.1 defined at /Users/oliver/Development/Tuist/example/.tuist-version
Generating workspace TuistProject.xcworkspace
Generating project TuistProject
Generating project ExampleApp
Resolve Package Graph

Fetching https://github.com/ollieatkinson/package-dependency

Fetching https://github.com/ollieatkinson/package-dependency-transitive


Resolved source packages:
  Logger: https://github.com/ollieatkinson/package-dependency @ branch
  Networking: https://github.com/ollieatkinson/package-dependency-transitive @ swift-package-manager

xcodebuild: error: Could not resolve package dependencies:
  terminated(128): /Applications/Xcode_11.3.1.app/Contents/Developer/usr/bin/git -C /Users/oliver/Library/Developer/Xcode/DerivedData/TuistProject-fjvmqfnjqamvnjdxoyqzgttdfzbz/SourcePackages/repositories/package-dependency-1ed9568d rev-parse --verify 'branch^{commit}' output:
    fatal: Needed a single revision
    

The 'xcodebuild' command exited with error code 74
```

To work around this issue, you can delete `.package.resolved` and derived data.

## Motivation

To create a better experience when using Swift Packages and Tuist we should look at ensuring the user has a way to update dependency references when they update their Project.swift file.

This process could be automated, but I would imagine a good first-step would be to create a manual flag to allow this to happen.

## Detailed design

We should look at the package manager for inspiration here, it provides a `swift package update` command line utility in order to update references in the `.resolved` file from the `Package.swift` file.

I would suggest we look at mimic'ing this behaviour.

TBC..
# Drawbacks

If we don't implement this, the experience for users may be difficult and they may be unaware of how to resolve the problem.
# Adoption strategy

This is additive.

# How we teach this

We would introduce new documentation and provide error messages when the package manager fails to install with tips about the commands that are available to update package dependencies.

**Comment by fortmarek** [comment]
Thanks for raising the issue @ollieatkinson!

This is something we should definitely tackle as the current workaround is not ideal, at all.

I wholeheartedly agree that we should mimic the behavior of `swift package update` (after all, we have tried to keep the similarity to SPM during the whole implementation of packages in tuist).

There are two ways, that I see viable, how to approach this:
1. Add a flag to `tuist generate`. Running eg `tuist generate --update` would update packages. Benefit would be that we could bundle under that flag different things to update (for example we could update pods, too). As a downside, it might not be immediately clear what *exactly* will be updated.
2. Add `tuist package update` command. Under a new `tuist package` we could potentially bundle more commands concerning `swift package`, for now it'd be just an additional namespace. What I see as a downside is the fact that we will need to add yet another command (and we already have plenty)

Regarding the suggestion of automating this process, I am not sure how we could do so? (trying to update packages on every `generate` does not sound like a good idea). Could you maybe expand on that, @ollieatkinson ?

And as for the implementation, I am not sure if you can update packages that are bundled in Xcode from command line? From a quick search, it does not seem to be possible. But what we can do is something like this:
1. Delete `Package.resolved` in `.xcworkspace` directory
2. Run `-resolvePackageDependencies` with `xcodebuild`
3. Copy new `Package.resolved` to `.package.resolved`

**Comment by ollieatkinson** [comment]
> Regarding the suggestion of automating this process, I am not sure how we could do so? (trying to update packages on every generate does not sound like a good idea). Could you maybe expand on that, @ollieatkinson ?

When a user edits the Project.swift file to modify a package dependency version, we should know about it because we can compare against the previous - sure it's not a totally fool-proof way but it could be a purely additive check to provide assistance where we know we can.

**Comment by fortmarek** [comment]
Ah, OK, that makes sense. The command we discussed above will be necessary anyway when the user wants to update the packages without changing the version requirements, so it'll be a good first step 👍

**Comment by pepibumur** [comment]
This is being worked on by the project to standardize the integration of third-party dependencies. There will be a command to do so `tuist dependencies update` cc @laxmorek
