### ISSUE TITLE
Missing Carthage framework should warn, not error when missing

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#1294]
**Describe the bug**

When a Carthage framework is not yet fetched I would expect to see this warning when generating the xcodeproj: 

https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Linter/GraphLinter.swift#L177

However due to a recent change in FrameworkNodeLoader it means this is always reported as a fatal error as a missing framework.

https://github.com/tuist/tuist/blob/8337c02bc932afaf110d7946af0664447022c637/Sources/TuistCore/NodeLoaders/FrameworkNodeLoader.swift#L42

This is especially bad if the framework's are pulled in via Carthage and managed via Tuist because you are not able to generate the frameworks to build.

**To Reproduce**

Steps to reproduce the behaviour:

1. Use fixture `ios_app_with_carthage_frameworks`
2. Delete `Carthage/Build`
3. Run `tuist generate`

**Expected behaviour**
Get a warning about a missing dependency

**Screenshots**

![image](https://user-images.githubusercontent.com/1382565/80822994-ab81eb00-8bd3-11ea-841c-8d430c6b260e.png)

**Additional context**

This is due to a recent change made by @pepibumur in regards to XCFrameworks, I do not yet have a workaround available.

**Comment by pepibumur** [comment]
Hey @ollieatkinson, I think we can close this one. As we discussed, the new behavior prevents developers from fro getting a generated project that won't compile because certain elements like dependencies, in this case, are missing.

**Comment by ollieatkinson** [comment]
I understand but I am a little hesitant here - maybe it's the way I have things configured but we are currently using Carthage as a means to manage versions across repositories (both our own, and other teams) and Tuist to generate those projects. 

I understand Tuist is geared toward a mono-repository but it's not something we are able to move to as a strategy. I will have to consider what a solution would look like for us moving forward

**Comment by ollieatkinson** [comment]
I will close this issue, and if I have something more concrete to consider may think about re opening it
