### ISSUE TITLE
Difference from XcodeGen?

### ISSUE THREAD

**Issue by toshi0383** [tuist/tuist#131]
Hi, I was just curious, but what was the motivation of creating "yet another XcodeGen" ?

**Comment by pepibumur** [comment]
Hi @toshi0383, I'm happy to answer that for you.

First and foremost, although Tuist leverages project generation it's not its end goal. The tool aims to provide a standard set of actions to interact with projects. To achieve that reliably, we made the decision to generate the project from a manifest file, which to some extend overlaps with what XcodeGen does.

We could have used XcodeGen to do the project generation part, but that'd introduce a level of indirection having to convert from our manifest format to XcodeGen's expected one, and from XcodeGen in-memory representation to Xcode project and workspace. We saved that intermediate step by generating the project ourselves. 

XcodeGen's manifest format is very aligned with Xcode projects format, offering a format for defining a project other than Xcode's. It's not bad or good, it's just one approach which might be what some projects. Tuist's manifest is a simplified, and even restrictive, version of an Xcode project. It hides all the implementation details from the project making it easier for developers to reason about how their projects look like.

Having said that, I wouldn't call this project another XcodeGen. They both are based on a similar idea, but they have different goals.

Let me know if that answers your question.

**Comment by toshi0383** [comment]
Thanks for the explanation!
But, what does “interact” mean? Like adding files and so on ?

**Comment by pepibumur** [comment]
> Thanks for the explanation!

No problem

> But, what does “interact” mean? Like adding files and so on?

Having a standard interface in the command line where you can perform the most common actions: build, test, run, release.

Tuist will infer the `xcodebuild` command and run it without the developer having to introduce arguments at all.

I focused on building the project generation, which is necessary to build those actions on top.

**Comment by toshi0383** [comment]
Oh ok, so it's basically like XcodeGen + fastlane?

**Comment by dcordero** [comment]
Fastlane does a ton of things so imho, at least so far, I think the role of Tuist is more similar to Swift Package Manager but adding support for Apps. I do not know about the long-term goal though.

**Comment by toshi0383** [comment]
@pepibumur @dcordero 
Thanks, now I got the picture.

I like the idea of applying "type checking in compile time" to the project generation. That sounds fantastic!
And thanks for updating the website so quickly. I will take a look.👌

**Comment by pepibumur** [comment]
Glad that it helped you get the picture. I'll close this issue then.
Don't hesitate to open another one if you have any other question/concern.
