### ISSUE TITLE
Disable Main thread checker

### ISSUE THREAD

**Issue by gbasile** [tuist/tuist#1321]
**Describe the bug**
I can't manage to disable the main thread checker on the RunAction. This is more a request for help more than a bug, because this feature should work on Tuist. 

**To Reproduce**
```
let uiTestsTarget = Target(
    name: "UITests",
    platform: .iOS,
    product: .uiTests,
    bundleId: "com.xxx.xxx.xxx.UITests",
    deploymentTarget: deploymentTarget,
    infoPlist: "UITests/Tests/Info.plist",
    sources: "UITests/Tests/**",
    dependencies: [
    .target(name: "XXX"),
    ]
)

…

 Scheme(name: "XXX UITests",
                shared: true,
                buildAction: BuildAction(targets: ["XXX"]),
                testAction: TestAction(targets: ["UITests"]),
                runAction: RunAction(configurationName: "Debug"),
                archiveAction: ArchiveAction(configurationName: "Debug")
)
```

**Expected behavior**
Under Scheme/Run/Diagnostic I would like to disable the MainThreadChecker

**Screenshots**
![screenshot 2020-05-11 at 13 06 24](https://user-images.githubusercontent.com/797790/81555134-41620680-9388-11ea-96c4-4a897289bed4.png)

**Comment by kwridan** [comment]
Hi @gbasile, thanks for raising this.

As things stand there isn't a way to control that particular setting via the project manifests, it could be considered for a future enhancement. 

This could be considered for both the **Run** and **Test** action as they both have nearly the same options (The Run action has an additional _"Memory graph on Resource Exception"_)

**Comment by pepibumur** [comment]
Hey @gbasile I opened a PR to make that setting configurable https://github.com/tuist/tuist/pull/1382. Please, take a lot and let me know if that would help mitigate the issue that you are facing.
