### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by igorkulman** [tuist/tuist#137]
**Describe the bug**
Installation using the method in README fails

**To Reproduce**
1. run `eval "$(curl -sL https://raw.githubusercontent.com/tuist/tuist/master/script/install)"`
2. see something like `jq not found` flash briefly before the terminal crashes

**Expected behavior**
Tuist installs

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: 10.13.6

**Comment by pepibumur** [comment]
Thanks for reporting this @igorkulman. That command runs [this script](https://github.com/tuist/tuist/blob/master/script/install) on your system. Would you mind running the commands in that script manually to spot which one is failing?

**Comment by igorkulman** [comment]
The problem was `jq`, I had to install it from homebrew to make the script working. I think you should add the info to README.

**Comment by pepibumur** [comment]
thanks @igorkulman. I've updated the README accordingly.

**Comment by pepibumur** [comment]
We changed the installation script so you shouldn't have that issue anymore.
