### ISSUE TITLE
Sorting project files and folders

### ISSUE THREAD

**Issue by igorkulman** [tuist/tuist#140]
**Is your feature request related to a problem? Please describe.**
Sorting the project files with folders and files mixed up is not ideal, at least not for everybody (we all have our own OCDs :)

<img width="214" alt="screen shot 2018-09-25 at 12 03 55" src="https://user-images.githubusercontent.com/4746070/46007735-19426880-c0bb-11e8-8d51-88b331026c5a.png">

**Describe the solution you'd like**
[xcodegen](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#options) has 3 options for this:
<img width="697" alt="screen shot 2018-09-25 at 12 01 45" src="https://user-images.githubusercontent.com/4746070/46007668-e7c99d00-c0ba-11e8-9db3-cc0e6f1600e3.png">

**Comment by pepibumur** [comment]
Looking at it I agree with you. What about sorting them by type and then by name? 

Tuist aims to be stronger with conventions by drawing a line between being very configurable, as XcodeGen, and very strict.

If there’s a good justification, like in this case, that line can be moved.

**Comment by igorkulman** [comment]
Something like `top` as a default work, no need to make it extra configurable, just use some reasonable default.

**Comment by ladislas** [comment]
my $0.02 on this:

having top as the default is great but I would also love to be able to do it by name then.

my understanding is that with tuist, I can remove .xcodeproj & .xcodeworkspace, regenerate the project and it will keep working as before. Thus, it's not possible to have a custom folder structure in xcode and keep it if you change computer.

But that would not be an issue IMO.

**Comment by pepibumur** [comment]
> My understanding is that with tuist, I can remove .xcodeproj & .xcodeworkspace, regenerate the project and it will keep working as before. Thus, it's not possible to have a custom folder structure in xcode and keep it if you change computer.

The format of the project will be deterministic. If you generate the project several times with the same files and manifests in your system you should get the same results. We aim to define conventions, like in this case how files and groups are sorted, and try not to make it too much configurable, which could potentially make things more complex and confusing.
