### ISSUE TITLE
Environment thinning causes heartache

### ISSUE THREAD

**Issue by kalkwarf** [tuist/tuist#1413]
**Describe the bug**
When running `tuist up`, with a custom setup rule, the environment passed to the tool/script is thinned out by the `acceptedEnvironmentVariables` filter. This means that keys defined in my environment are not available to the setup process.

**To Reproduce**
```
let setup = Setup([
    .custom(name: "Bootstrap", meet: ["./Bootstrap.py"], isMet: ["false"])
])
```

in Bootstrap.py, attempt to extract the variable:
```
print(os.environ['MY_SECRET_TOKEN'])
```

**Expected behavior**
The token is present.

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Xcode 11.5

The code that filters the environment is very deliberate, but I couldn't locate the reasoning behind it.

The tokens I expect to have access to are unique to each developer, so I can't pass them in the Environment construct. What are my options for getting more context into the script running at setup time?

**Comment by pepibumur** [comment]
> The code that filters the environment is very deliberate, but I couldn't locate the reasoning behind it.

The initial reasoning was preventing some environment variables from causing non-deterministic behaviors in the processes run by Tuist, but at this point I think it's causing more troubles than helping. I'd suggest removing the filter and giving the sub-processes full access to the variables that the Tuist process has access to. What do you think?

Would you like to open a PR and contribute yourself? Otherwise we can do it too.

**Comment by kalkwarf** [comment]
Thanks for the explanation. PR open.

**Comment by kalkwarf** [comment]
I could use a clue. CI is failing one of the tests:
```
2020-06-05T14:20:24.2998140Z /Users/runner/runners/2.263.0/work/tuist/tuist/Tests/TuistSupportIntegrationTests/System/SystemIntegrationTests.swift:77: error: -[TuistSupportIntegrationTests.SystemIntegrationTests test_without_DEVELOPER_DIR] : XCTAssertFalse failed
```
If I run locally in Xcode, that test passes, which makes sense, since that variable isn't typically set manually.

I tried to run `swift test`, but the project fails to build, which is… odd?
```
~/Projects/github/tuist/Tests/TuistAutomationTests/Utilities/BuildGraphInspectorTests.swift:8:18: error: no such module 'TuistCoreTesting'
@testable import TuistCoreTesting
```

I assume that test isn't relevant now that we're not filtering. However, the test above it looks suspicious, too. Should they both be removed?

**Comment by kalkwarf** [comment]
This appears to be fixed in current versions. Thanks!
