### ISSUE TITLE
Installation steps are wrong

### ISSUE THREAD

**Issue by santos88** [tuist/tuist#142]
**Describe the bug**
When a new user tries to follow the installation steps on www.tuist.io is not possible to install the app.

**To Reproduce**
1. Go to www.tuist.io/
2. Scroll down to the "Start using it" section
3. copy and paste to the terminal 
`eval "$(curl -sL https://bit.ly/2JWMfx8)"
`
```
zsh: command not found: jq
(23) Failed writing body
Couldn't find tuistenv on the latest release

```

**Expected behavior**
The user should install the app without troubles and see the final message

> "Tuist installed. Try running 'tuist'"

**Desktop (please complete the following information):**
 - macOS Mojave

**Additional context**
This is also happening if the user follows the instructions from https://tuist.io/guides/1-getting-started

**Comment by pepibumur** [comment]
Hi @santos88.
I'd fixed this already but I forgot to update the getting started page on the website. The script should be:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/tuist/install/master/install)"
```

Could you try that one and let me know if it works? Also, is there any other place besides the getting started page where the old script is referenced?

**Comment by santos88** [comment]
@pepibumur the new script is working as expected. Thanks!
