### ISSUE TITLE
tuist build builds wrong workspace

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#1423]
**Describe the bug**
I have a `.xcworkspace` in my root directory. But since we use Danger, I also have a workspace at `.swiftpm/xcode/package.xcworkspace` (but this is also the case for eg Carthage checkouts and there are other valid reasons to have multiple workspaces)
Then when I run `tuist build`, I get a following error: 
`error: The workspace named "package" does not contain a scheme named "MyScheme". The "-list" option can be used to find the names of the schemes in the workspace.`

When I ran with `--verbose`, the `xcodebuild` command looks like this: 
` /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean build -scheme MyScheme -workspace /Users/marekfort/MyProject/.swiftpm/xcode/package.xcworkspace -sdk iphonesimulator`

The reason is quite simple, it's due to a [BuildGraphInspector locating of workspace](https://github.com/tuist/tuist/blob/master/Sources/TuistAutomation/Utilities/BuildGraphInspector.swift#L55). Unfortunately, the glob in my case finds first the `package` workspace. 

**To Reproduce**
clone this [repo](https://github.com/fortmarek/BuildPackage) and run `tuist build`

**Expected behavior**
`tuist build` succeeds

**Desktop (please complete the following information):**

- OS: macOS
- Version: 1.10.0

**Additional context**
I'd gladly fix this but I am not sure what's the right way. One way could be checking the name of the scheme and output of `xcodebuild project.xcworkspace -list`, but maybe there is a better solution to this. Would you have some insight into this, @pepibumur ?

**Comment by pepibumur** [comment]
Just had an idea. I think we could create an empty file inside the generated Xcode projects and workspaces to flag them as Tuist-generated Xcode artifacts. That’d help remove the ambiguity when determining which workspace to use. What do you think @fortmarek ?

**Comment by fortmarek** [comment]
💡 I think this should work! Adding an empty file to a `.xcworkspace` directory is a valid addition as it does not break anything. I can tackle this if you want to or feel free to go for it yourself 🙂

**Comment by pepibumur** [comment]
Sure! Go ahead.
