### ISSUE TITLE
Signing vendor

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#1426]
## Need/problem

As the signing [PR](https://github.com/tuist/tuist/pull/1186) nears its merge into the master, I'd like to start the next step and that is generating certificates and provisioning profiles automatically for the user.

## Motivation

While fastlane is a great tool, we can leverage what we know about the project and use the knowledge to make the signing integration more seamless. 

## Detailed design

OK, let's get technical 😜 
I'd use the suggestion from @pepibumur and name the new command `vendor`.
So, the user would run `tuist signing vendor` and it'd generate the needed provisioning profiles and certs. 
Now, I think it'd be good to make sure that we generate profiles only for schemes that user wants. There are two paths we can take: Ask the user in the CLI (possibly giving them a list of buildable schemes) or we can incorporate signing into `ProjectDescription`. The CLI approach might be simpler to implement, but since every scheme can have a different team, we'd need to ask repetitively for information which might be tedious for the user. That's why I think we should add this to `ProjectDescription`. `Scheme` could have a new parameter called `signing`:
```swift
enum Signing {
   case manual // default
   case automatic(teamId: String)
}
```
We can then infer all the other necessary information.

- After we have a list of schemes and team IDs we can:
- Log in the user - I am not yet sure how this will work specifically, but we have to have some way to authenticate the user before interacting with app store connect. That means asking for the Apple ID and password in the CLI. A different, and maybe better approach, would be instructing the user to create an API key at https://appstoreconnect.apple.com/access/api first and then using it for subsequent operations. The great benefit of this is we can encrypt this file in `Tuist/Signing` with `master.key` and running `tuist vendor` will be seamless for other users. It'd also be easier then to implement next steps with [this](https://github.com/AvdLee/appstoreconnect-swift-sdk#2-create-your-api-configuration) library.
-  fetch from app store connect the list of provisioning profiles and certificates for the teams we are vendoring for.
- compare it with the list of profiles and certificates we need and generate new ones if necessary (current are a) revoked b) missing). The generated certs and profiles will follow our signing conventions.
- after we generate certs and profiles, we put them in `Tuist/Signing` directory and after that signing should work reliably ✨  (I hope I have not forgotten any steps, if so, please write it down below 👇 )

# Adoption strategy

Add appropriate documentation. Also I'd love to get some feedback from multiple users before announcing it to the wider community.

# How we teach this

Add a proper documentation. Once signing is all up and running, it'd be great to make a more elaborate blogpost/video that would show the whole process of how easy signing is with tuist.

# Unresolved questions

As mentioned in `Detailed design`, I am not sure how to a) get a list of schemes to generate signing artifacts for and for which team id they should be generated for b) how to authenticate the user

**Comment by pepibumur** [comment]
Hey @fortmarek, I think having this command will be very useful for developers to re-generate certificates and profiles directly from their terminal. The first thing that popped into my mind while reading the description is that using Apple's official API might not be a good idea. The API still doesn't support enterprise accounts, so some users might want to generate enterprise certificates and they'll find out that Tuist doesn't support it because we are using Apple's official API. What we could do is using [this utility](https://github.com/xcodereleases/xcinfo/blob/master/Sources/OlympUs/OlympUs.swift) from xcinfo, to authenticate using cookies (like Fastlane does) and use the undocumented API that Fastlane's match has always been using. What do you think? We can take that code and add support for the endpoints for certificates and profiles. We can use Fastlane's Match codebase as a reference.

Regarding the interface, I don't think the signing configuration should be at the scheme level. Signing is something that is associated with a target and a configuration *(e.g. the profile for signing MyApp for debug)*. For that reason, I'd expose the configuration at the target level. What about something along the lines of:

```swift
let target = Target(signing: [
  .apple(teamId: "XYZ", config: "Debug"),
  .apple(teamId: "Bar", config: "Internal") // Enterprise developer account
])
```

I wonder if it'd make sense to define it at the project level instead? I doubt teams will have the need for such granularity. Teams usually define signing certificates per project.

**Comment by fortmarek** [comment]
> What do you think? We can take that code and add support for the endpoints for certificates and profiles. We can use Fastlane's Match codebase as a reference.

Oh, I have not realized the limiitation with enterprise accounts :( 
Then yes, let's try to mimic the Fastlane's authentication. 

> I wonder if it'd make sense to define it at the project level instead?

I agree, let's move it to `Project` then

I feel the biggest obstacle will be communicating with Apple's API, but otherwise I think that the basic design is more-or-less settled. I'll try to kick it off with WIP PR once I get something working, thanks for the input @pepibumur 👍

**Comment by fortmarek** [comment]
> use the undocumented API that Fastlane's match has always been using

I have been thinking about this and I think it might be better for us not to take this path. The undocumented API changes quite often and I don't think that we have the manpower to keep it always up to date ([PR](https://github.com/fastlane/fastlane/pull/16626) that lead me to change my mind). Besides, we can offer a more stable alternative to Fastlane's solution as the undocumented API can change at any time and it might (and often does) break parts of fastlane toolchain completely. 

Of course, it would be shame that enterprise accounts would not be supported, but a) this is limitation imposed by Apple b) Apple can add support to it at any time (WWDC looking at you 👀 😅)

What do you think, @pepibumur?

**Comment by fortmarek** [comment]
Now that I have started tinkering with the implementation, it occurred to me that maybe a new command `vendor` might not be necessary. We can already tell if we should generate certificates and provisioning profiles just by the fact that the user adds `signing` enum for a given configuration. You just add it to your manifest and tuist automatically does everything for you - we can even tell if a certificate is eg expired and regenerate it automatically, too 🤯

**Comment by fortmarek** [comment]
I'll continue dumping my thoughts here as I stumble upon problems during the [implementation](https://github.com/tuist/tuist/tree/signing_vendor) - there will be needed only one development/distribution certificate for one team and so it might make more sense to have only development/distribution certificate for each team; unfortunately, if you start a new project with a team that already has a valid certificate, there is a high change that you do not have a necessary `.p12` key which only the user that created a certificate would have. 

The only solution to this that I see is just create a new certificate for each new project - that way we can ensure that the `.p12` key will be in `Tuist/Signing` directory. Is there any downside for having possibly a high number of certificates (aka usually two certificates per project ? )

**Comment by pepibumur** [comment]
> I have been thinking about this and I think it might be better for us not to take this path. The undocumented API changes quite often and I don't think that we have the manpower to keep it always up to date (PR that lead me to change my mind). Besides, we can offer a more stable alternative to Fastlane's solution as the undocumented API can change at any time and it might (and often does) break parts of fastlane toolchain completely.

Agree. Sooner or later Apple will add support for enterprise accounts so I'd rather stick to the public documented API.

> Now that I have started tinkering with the implementation, it occurred to me that maybe a new command vendor might not be necessary. We can already tell if we should generate certificates and provisioning profiles just by the fact that the user adds signing enum for a given configuration. You just add it to your manifest and tuist automatically does everything for you - we can even tell if a certificate is eg expired and regenerate it automatically, too 🤯

That's a good idea, although bear in mind that re-generation of certificates and profiles requires authentication with the store, so we need to prompt the user for username and password. That would make a command like `tuist generate`, which is not interactive, interactive. I'd rather have an interactive command, `tuist signing sync`, that takes care of all of that.

> The only solution to this that I see is just create a new certificate for each new project - that way we can ensure that the .p12 key will be in Tuist/Signing directory. Is there any downside to having possibly a high number of certificates (aka usually two certificates per project ? )

What about something like this:
- If we detect there's already a certificate created, and that it exists in the local keychain with its private key we export it to the `Tuist/Signing` directory.
- Otherwise, if we detect that there's already a certificate create, but the private key doesn't exist in the keychain we prompt the user for forcing its re-generation.
- If nothing exists, then we create everything.

I think an interactive experience where we drive the user through the creation of the signing artifacts makes sense:

```
$ We detected a development certificate with team with ID XX already exists in your keychain with a private key. Would you like to use that one?
$ y
$ Exporting and encrypting certificate...
```

**Comment by fortmarek** [comment]
Thanks for the feedback @pepibumur!

> prompt the user for username and password

this is not necessary, all that is necessary to generate a certificate/profile is API key that will be placed and encrypted in `Tuist/Signing`. But if some interaction from the user will be necessary for generating certificates, let's move it to a new command.

> Otherwise, if we detect that there's already a certificate create, but the private key doesn't exist in the keychain we prompt the user for forcing its re-generation

I am not sure this is the correct approach - I have a project A that someone else set up. When I decide to create a project B with this approach I will break project A's signing. And although it'd be easy to fix it, I still don't like the idea of breaking signing in other projects unrelated to each other.

**Comment by lucasilverentand** [comment]
@fortmarek How is this feature coming along? I'm looking to replace Fastlane completely with Tuist, and this is the final missing puzzle piece to getting there. How can I help get there faster?

**Comment by fortmarek** [comment]
Hi @lucasilverentand!

Thanks for the interest 🖤 the biggest issue with vendor at the moment is the sync of certificates which are shared across the organization's projects. Therefore, a server-side component might be necessary for this to work seamlessly. We could either use fastlane's approach and use a dedicated repository for that - or use a server (either self-hosted or we could prepare some hosted solution ourselves).

However, we don't have a clear vision of how that feature should look like at the moment. I hope I can get back to you sometime next week with more info if that's fine by you? We'd very much appreciate any help on this.

**Comment by lucasilverentand** [comment]
@fortmarek That would be great, I'm currently thinking of starting a dashboard for developers to manage their apps in one place, but that's still very much in the making. But it could perhaps include some sort of certificate syncing.

One thing is sure, this feature needs a lot of thought.

**Comment by fortmarek** [comment]
> That would be great, I'm currently thinking of starting a dashboard for developers to manage their apps in one place, but that's still very much in the making. But it could perhaps include some sort of certificate syncing

we actually had that idea as well - we wanted to provide a centralized place to see insights to your app as well as some additional management - e.g.

**Comment by lucasilverentand** [comment]
@fortmarek I most definitely will do.

**Comment by fortmarek** [comment]
We currently don't have plans to add support for this.
