### ISSUE TITLE
Overriding developmentRegion

### ISSUE THREAD

**Issue by Jauzee** [tuist/tuist#1445]
## Need/problem

Overriding value of `developmentRegion` property on xcodeproj.

## Motivation

It defaults to `en`, but some projects do not support english localisation and do override value of this property to another region, for example `ru`.

# Drawbacks

I don't see any. I'm not sure about the implementation but from user's perspective it should be just like one more option to tune.

## Alternatives

I didn't find a way to override this value using current Tuist implementation. As an alternative I can only think of some post processing script to do search & replace.

# Adoption strategy

It's a non-breaking change.

**Comment by pepibumur** [comment]
Hi @Jauzee. The [test action](https://tuist.io/docs/usage/projectswift/#test-action) model supports defining the test region. Is that what you need or am I missing something?

**Comment by Jauzee** [comment]
@pepibumur nope. I mentioned that option in documentation, but it's only for test targets. What we need in our project is to define development region for the whole project — that way you can override the Base localization. It defaults to English (`en`) and you can not change it from Xcode directly.

Some relevant SO posts: [# 1](https://stackoverflow.com/questions/25871815/changing-the-development-language-in-xcode), [# 2](https://stackoverflow.com/questions/33952624/how-to-set-language-other-than-english-as-the-development-language-and-base-loca)

**Comment by Jauzee** [comment]
Seems like it's possible to solve the issue by providing custom xcconfig file. I will try to do so.

**Comment by kwridan** [comment]
Thanks for raising this @Jauzee 

@pepibumur I believe that setting is baked into the `.pbxproj` file (would be curious to find out if the xcconfig settings do the trick).

![Screen Shot 2020-06-16 at 7 43 52 AM](https://user-images.githubusercontent.com/11914919/84740523-74aa3d80-afa5-11ea-9730-90d0ed77fbb2.png)

Tuist currently has that hard coded to English:

https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/ProjectGenerator.swift#L157

In addition to the default regions `en` and `Base` in the case there are localized resources for any other languages, Tuist will automatically add those too.

e.g.

https://github.com/tuist/tuist/tree/master/fixtures/ios_app_with_framework_and_resources/App

I think this is a good candidate for being exposed in manifests either directly in `Project.swift` for an individual project, or `Config.swift` to apply to the entire workspace. 

```swift
import ProjectDescription

let project = Project(
  // ...
  developmentRegion: "fr",
)
```

or

```swift
import ProjectDescription

let config = Config(
  generationOptions: [
    .developmentRegion("fr"),
  ]
)
```

_(Internally in Tuist we can add this to `TuistCore.Project` and map it using model mappers like we do with auto generated schemes)_

**Comment by jeroenleenarts** [comment]
What @Jauzee is talking about is actually done in this line https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/ProjectGenerator.swift#L132
