### ISSUE TITLE
No ProjectDescriptionHelpers scheme when running tuist edit on 1.11.0 

### ISSUE THREAD

**Issue by remover** [tuist/tuist#1460]
**Describe the bug**

No ProjectDescriptionHelpers scheme is generated when running tuist edit on 1.11.0. There is a related issue: I can never build the Manifests scheme without building this scheme first. I get a build error:

```
Could not build Objective-C module 'ProjectDescriptionHelpers'
```

Usually I build ProjectDescriptionHelpers, which then allows me to build the Manifests scheme. Not being able to build ProjectDescriptionHelpers essentially means that we can't update Tuist.

**To Reproduce**

mkdir TuistEditExample
cd TuistEditExample
tuist local 1.11.0
tuist init
tuist edit

**Expected behavior**
there is a ProjectDescriptionHelpers scheme

**Screenshots**

**Desktop (please complete the following information):**

- OS: 10.15.5 (19F101)
- Version 1.11.0

**Additional context**

here's zip of the results of the steps above
[TuistEditExample.zip](https://github.com/tuist/tuist/files/4782320/TuistEditExample.zip)

**Comment by fortmarek** [comment]
Yeah, I can easily reproduce this, too, I'll take a look at where it has gone, thanks for reporting
