### ISSUE TITLE
`.disableAutogeneratedSchemes` doesn't work

### ISSUE THREAD

**Issue by laxmorek** [tuist/tuist#1461]
**Describe the bug**
Tuist generates default schemes even if `.disableAutogeneratedSchemes` is set in `Config.swift`

**Expected behavior**
When `.disableAutogeneratedSchemes` is added to `Config` then Tuist should generate only custom defined schemes (skip default auto generated schemes)

**Desktop (please complete the following information):**
- OS: macOS 10.15.5
- Version 1.11.0

**Guessing:**
Probably related to changes from: https://github.com/tuist/tuist/pull/1357

**Comment by pepibumur** [comment]
@laxmorek would you mind checking if the generated Xcode project contains schemes under `MyProject.xcodeproj/xcshareddata/xcschemes/**`?

**Comment by laxmorek** [comment]
it doesn't contains :)

**Comment by laxmorek** [comment]
I have made a mistake. Schemes are being written by CocoaPods.
