### ISSUE TITLE
Installing tuist downgrades the command line tools from Mojave to High Sierra

### ISSUE THREAD

**Issue by asalom** [tuist/tuist#148]
**Describe the bug**
While having the Mojave Command Line Tools 10.14, I installed `tuist` with the following command and it downgraded them to High Sierra 10.13
I never had `tuist` installed before, this was the first time so I wasn't coming from an older version.

```shell
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/tuist/install/master/install)"
```

**Expected behavior**
I expected the command to install `tuist` while leaving the Command Line Tools intact

**Screenshots**

<img width="682" alt="screenshot 2018-10-12 at 16 57 37" src="https://user-images.githubusercontent.com/1466079/46876989-fd232300-ce3f-11e8-9caa-3789f63181a1.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14

**Comment by pepibumur** [comment]
Thanks for reporting the issue. The bug must be in [this script](https://github.com/tuist/install/blob/master/install#L136)

**Comment by asalom** [comment]
I'm not sure if this helps but I'm using Xcode's command line tools

```shell
> xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

**Comment by fwal** [comment]
The code in the check is hard coded https://github.com/tuist/install/blob/master/install#L114L119
It should probably check the path returned by `xcode-select --print-path`

**Comment by fwal** [comment]
Went ahead and made a PR 🙂
