### ISSUE TITLE
Manifests scheme of tuist edit fails to compile with multiple Template.swift files

### ISSUE THREAD

**Issue by remover** [tuist/tuist#1485]
**Describe the bug**

`tuist edit` will include all the `Template.swift` files (this name is i believe enforced by Tuist) and subsequently the `Manifests` scheme won’t compile due to duplicate filenames. 

**To Reproduce**

- create more than one template according to the [docs](https://tuist.io/docs/commands/scaffold/)
- run `tuist edit`
- attempt to compile the `Manifests` scheme

**Expected behavior**
the scheme should build but doesn't due to multiple files with the same name

**Desktop (please complete the following information):**

- OS: MacOS
- Version 1.6.0

**Comment by fortmarek** [comment]
Thanks for reporting, I'll try to address this 🙂
