### ISSUE TITLE
Xcode 12 Support

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#1497]
## Overview

Creating an issue to collate / track Tuist's support of various Xcode 12 features (originally stated in #1493) 

## Widget Extensions

**Status:** Supported _(Room for improvement)_

This works like existing app extensions (e.g. Notification Service Extension) which Tuist already supports.

- `productType = "com.apple.product-type.app-extension"`
- Info.plist `"NSExtensionPointIdentifier": "com.apple.widgetkit-extension"`

Example manifest:

```swift
Target(name: "WidgetExtension",
       platform: .iOS,
       product: .appExtension,
       bundleId: "io.tuist.App.WidgetExtension",
       infoPlist: .extendingDefault(with: [
           "CFBundleDisplayName": "$(PRODUCT_NAME)",
           "NSExtension": [
                   "NSExtensionPointIdentifier": "com.apple.widgetkit-extension"
               ]
       ]),
       sources: "WidgetExtension/**",
       dependencies: [
                            
 ])
```

Some general improvements can be made to extension schemes in #1494 

## Development Assets

**Status:** Supported _(Room for improvement)_

Xcode 12 supports defining a set of "assets" (both resources and sources) as development assets, that is a set that is exclusively used for development and previews. Those are excluded when archiving the final product.

Taking a look at how this is defined in Xcode, it seems like the developments sources and resources are part of the regular build phases however there's an additional build setting to their path

- `DEVELOPMENT_ASSET_PATHS = "\"AppWithClips/Preview Content\"";`

Example manifest:

_It's a bit easier to re-organize the `PreviewContent` directory to have two distinct subdirectories, one for `Sources` and another for `Resources`_

```swift
Target(name: "MyApp",
       platform: .iOS,
       product: .app,
       bundleId: "io.tuist.App",
       infoPlist: .default,
       sources: [
            "Sources/**",
            "PreviewContent/Sources/*",
       ],
       resources: [
            "PreviewContent/Resources/*",
       ],
       settings: Settings(base: [
            "DEVELOPMENT_ASSET_PATHS": ["PreviewContent/Sources", "PreviewContent/Resources"] 
       ])
```

_**Note:** The direct parent directory of the assets to be excluded needs to be specified within the build setting._

Some ideas for improvements could be possibly add a `developmentSources` and `developmentResources` property on the manifest to specify the paths and Tuist could ensure they are added to the existing build phases and the build setting is updated accordingly.

---

Those are some of the features I spotted, if anyone knows of any others we can update the list :)

**Comment by icedice** [comment]
I curios, was this ever implemented?
