### ISSUE TITLE
Tuist focus should use root .package.resolved

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#1518]
**Describe the bug**
Currently, if you run `tuist focus`, tuist starts building a new `Package.swift` because it can not find it in the current directory.

`tuist` should always look into the root when resolving swift packages to make sure this process is not duplicated.

**To Reproduce**

1. `tuist init`
2. Add a swift package
3. `tuist generate` -> `.package.resolved` will be added to the root
4. `tuist focus` for some project in `Projects`dir -> new `.package.resolved` will be created

I'll try to fix it in the following days 🙂

**Comment by ecerney** [comment]
@fortmarek I don't think this fix is correct, but tell me if I'm wrong. I have a main project with a folder of different frameworks each generating an xcode project using Tuist. If I generate a project from any of these sub folders, the root .package.resolved is edited for that specific framework. So each time I go to a different subfolder and generate (or `focus`), the .package.resolved is wiped and the resolve for that specific framework is added. Should there not be a package.resolved in each of these subfolders instead?

MyApp
->.package.resolved (keeps getting edited for whichever framework was last generated)
->Frameworks
---->Framework1 (should have its own .package.resolved but doesn't)
--------->Project.swift
---->Framework2 (should have its own .package.resolved but doesn't)
--------->Project.swift

**Comment by fortmarek** [comment]
This seems to have worked for my specific use case where it'd resolve the same `.package.resolved` since the deps for the subproject were the same as for the main one, but your logic seems sound to me.
I think a simple revert should do just fine, feel free to go ahead with it or I can do it sometime next week (vacation time 🌴).

**Comment by ecerney** [comment]
Hey @fortmarek forgot about this and just coming back to it now. Wondering if you have any time, because it would be great if it still worked for your use case too, if you could revert it, or better yet add an option to make it behave like you wanted? I haven't looked at the code much so not sure the level of difficulty. Hope you had a good vacation 🌴

**Comment by fortmarek** [comment]
Ahh, I am so sorry @ecerney, forgot about this, I'll look at it over the weekend 🙂
