### ISSUE TITLE
Tuist not compatible with Swift 4.2.1

### ISSUE THREAD

**Issue by ladislas** [tuist/tuist#153]
**Describe the bug**

After updating Xcode yesterday, I tried using the `tuist init` command but got the following error messsage:

<img width="467" alt="screenshot 2018-11-04 15 18 55" src="https://user-images.githubusercontent.com/2206544/47965245-f8b7e780-e044-11e8-8401-0966e05cf1a3.png">

**To Reproduce**

1. Install latest Xcode version with Swift 4.2.1
2. Run `tuist init ...`

**Expected behavior**

Tuist should support Swift 4.2.1

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.14.1 (18B75)
- Xcode Version 10.1 (10B61)

**Comment by pepibumur** [comment]
Thanks for bringing this up @ladislas. I've released a new version, 0.8.0 which is compiled with Swift 4.2.1. Please, run `tuist update` and let me know if it works.

Moreover, I've opened [this issue](https://github.com/tuist/tuist/issues/156) to handle that scenario better. I'm curious to know what you think about the approach that I suggested.

**Comment by ladislas** [comment]
Thanks! I’ll try it out when I get home.
