### ISSUE TITLE
Allow graph command to ignore Test targets and or external dependency targets

### ISSUE THREAD

**Issue by jeroenleenarts** [tuist/tuist#1538]
## Need/problem

Allow generating a clean dependency graph without Tests targets and/or 3rd party dependencies.

## Motivation

On a bigger project the graph command output can become a bit cluttered due to the Test and external dependencies. During discussions with my team I notices it is useful to have a "clean" dependency graph displaying only the artifacts that are original to our team which are packaged into the resulting app.

## Detailed design

Provide two arguments.
- `skipTestTargets`
- `skipThirdParty`

The filtering can happen in the [GraphToDotGraphMapper](https://github.com/tuist/tuist/blob/183304963b1e5f3740086b4f2a789318873ae111/Sources/TuistGenerator/Dot/GraphToDotGraphMapper.swift#L18).

# Drawbacks

- How to deal with dependencies of the test targets that are not part of the`main` target?

## Alternatives

Chopping up the Dot file with a sed command works as well.

# Adoption strategy

This is non-breaking.

# How we teach this

This can be explained in the `-h` output of the Graph command and on the command description on the website.

**Comment by jeroenleenarts** [comment]
I would mind having a stab at this myself.

**Comment by pepibumur** [comment]
> I would not mind having a stab at this myself.

That'd be awesome!
