### ISSUE TITLE
CoreData model is not added to "Compile Sources" phase.

### ISSUE THREAD

**Issue by jeroenleenarts** [tuist/tuist#1539]
**Describe the bug**
I have a project with a CoreData model. It uses class generation. `tuist focus` results in a project with loads of errors due to missing Core Data objects.

**To Reproduce**

1. Create a project with a core data model with model classes generated to Swift.
2. Use one of the generated models in some other code.
3. See errors

**Expected behavior**
The compiler should be able to compile against the generated CoreData models.

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.2

**Comment by kwridan** [comment]
Hi @jeroenleenarts, thanks for flagging this.

We have a small fixture in https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_coredata/Project.swift which can do with some further improvements to help catch this. 

Looking at https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/BuildPhaseGenerator.swift#L212 it looks like the models are being added the resource build phase instead which explains the issues you're seeing :( 

My CoreData knowledge/experience is a bit limited, if I understood the issue those should be in the sources build phase? I wonder why there were included in the resources build phase instead.

I've pushed a draft PR with those changes, but worth sanity checking it

https://github.com/tuist/tuist/pull/1542

**Comment by jeroenleenarts** [comment]
When using class gen in CoreData it needs to be in the build phase if my understanding is correct. If you maintain your core data classes manually having the model only as a resource is not a problem.

I am looking for some Apple references to support the above. What noticed on my project was all Core Data classes missing. Once I added the model dir to the build phase, tHey were all gone.
