### ISSUE TITLE
Add --force flag to the tuistenv update command

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#156]
**Is your feature request related to a problem? Please describe.**
If the latest local version of tuist is compiled locally with an old version of Swift, Tuist doesn't know how to handle that scenario.

**Describe the solution you'd like**
Add a `--force` flag to the `update` command. When passed, it recompiles the latest version, regardless of a version existing locally.

```
tuist update --force
```

**Describe alternatives you've considered**
- Showing a message letting the developer know that they can delete and install the version again.

**Additional context**
Related https://github.com/tuist/tuist/issues/153

**Comment by ladislas** [comment]
Looks good to me. 

Add the fact that they can run this command if the previous fails to the error message. 
Homebrew does a good job at that when you need to force link something for example.

**Comment by pepibumur** [comment]
> Add the fact that they can run this command if the previous fails to the error message.

That's a good idea :+1:. I'll definitively change the error to suggest running the command.
