### ISSUE TITLE
Looking for clarity on how `Settings` are used

### ISSUE THREAD

**Issue by kalkwarf** [tuist/tuist#1570]
I'm almost certainly doing something wrong, and the existing documentation is a little sparse.

Given some project settings:
```
public let projectSettings = Settings(
  debug: Configuration(xcconfig: Path("../../xcconfigs/Debug.xcconfig")),
  release: Configuration(xcconfig: Path("../../xcconfigs/Release.xcconfig")),
  defaultSettings: .none
)
```
where `Debug.xcconfig` contains

`CLANG_ADDRESS_SANITIZER_CONTAINER_OVERFLOW = YES`

then using the stock template (with the single addition of `settings: projectSettings`):
```
    public static func project(name: String,
                               product: Product,
                               platform: Platform,
                               dependencies: [TargetDependency] = [],
                               infoPlist: [String: InfoPlist.Value] = [:]) -> Project {
        return Project(name: name,
                       settings: projectSettings,
                       targets: [
                        Target(name: name,
                                platform: platform,
                                product: product,
                                bundleId: "io.tuist.\(name)",
                                infoPlist: .extendingDefault(with: infoPlist),
                                sources: ["Sources/**"],
                                resources: [],
                                dependencies: dependencies),
                        Target(name: "\(name)Tests",
                                platform: platform,
                                product: .unitTests,
                                bundleId: "io.tuist.\(name)Tests",
                                infoPlist: .default,
                                sources: "Tests/**",
                                dependencies: [
                                    .target(name: "\(name)")
                                ])
                      ])
    }
```
I would expect that flag to be set at the `Project` level of the generated Xcode project. It is not:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1033839/87726614-5a72a380-c78d-11ea-860d-7a8113491330.png">

Passing a `SettingsDictionary` in for a `Target` seems to be ignored as well, and only the values at `BuildSettingsProvider.swift:196` appear in the generated project file.

Unfortunately, the Reactiveness of Tuist makes it hard for me to reason about where the values are supposed to come from.

Can somebody please explain it to me? I volunteer to open a PR for the documentation once I understand. :-)

**Comment by kwridan** [comment]
Hi @kalkwarf, thanks for posting this!

The screenshots are really helpful, I can already spot one thing to help us troubleshoot this.

I replicated the described setup

```sh
$ tuist version
1.12.2
$ mkdir MyApp
$ cd MyApp
$ tuist init
$ mkdir xcconfigs
$ echo "CLANG_ADDRESS_SANITIZER_CONTAINER_OVERFLOW = YES" > xcconfigs/Debug.xcconfig
$ echo "CLANG_ADDRESS_SANITIZER_CONTAINER_OVERFLOW = NO" > xcconfigs/Release.xcconfig
...
```

I then updated `Tuist/ProjectDescriptionHelpers/Project+Templates.swift`

```swift
public let projectSettings = Settings(
  debug: Configuration(xcconfig: Path("../../xcconfigs/Debug.xcconfig")),
  release: Configuration(xcconfig: Path("../../xcconfigs/Release.xcconfig")),
  defaultSettings: .none
)

// ...

public static func project(name: String,
                               product: Product,
                               platform: Platform,
                               dependencies: [TargetDependency] = [],
                               infoPlist: [String: InfoPlist.Value] = [:]) -> Project {
        return Project(name: name,
                       settings: projectSettings,
                       targets: [
                        Target(name: name,
                // ...
           )
```

The generated project does contain the settings defined in the xcconfig:

<img width="1436" alt="Screenshot 2020-07-17 at 06 37 37" src="https://user-images.githubusercontent.com/11914919/87752602-a3137680-c7f8-11ea-8fa4-8ddfc16a5641.png">

Note the config column is missing in the screenshot you posted, this indicates somehow it's not getting configured - does `playgroundKit` leverage the templates?

e.g.

`Projects/MyAppKit/Project.swift`

```swift
import ProjectDescription
import ProjectDescriptionHelpers

let project = Project.framework(name: "MyAppKit", platform: .iOS, dependencies: [
    .project(target: "MyAppSupport", path: .relativeToManifest("../MyAppSupport"))
])
```

--- 

On a small related note for defining paths within the template, you can leverage some of the static methods on `Path` to make it even more clear as to which type of path to leverage. (https://tuist.io/docs/usage/projectswift/#path)

e.g.

```swift
public let projectSettings = Settings(
  debug: Configuration(xcconfig: .relativeToRoot("xcconfigs/Debug.xcconfig")),
  release: Configuration(xcconfig: .relativeToRoot("xcconfigs/Release.xcconfig")),
  defaultSettings: .none
)
```

Hope this helps

**Comment by kalkwarf** [comment]
Interesting. Thank you for the thorough response. Somehow I missed the `relativeToRoot` helper when I read the documentation. It definitely makes the code more explicit.

My `Projects/playgroundKit/Project.swift` looks like this:
```
import ProjectDescription
import ProjectDescriptionHelpers

let project = Project.framework(
  name: "playgroundKit",
  platform: .iOS,
  dependencies: [
])
```

After changing my paths to use the helper, the project was correctly generated. I didn't think that should matter, so I changed back to my explicit `Path` declaration, and it still generates the correct project. 

I am completely baffled. I can only blame Xcode.
