### ISSUE TITLE
Warming the cache rebuilds frameworks that already exist in the cache

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#1581]
## Context 🕵️‍♀️
@thedavidharris posted on Slack:

> We have ~100, and I was noticing that a lot of modules seemed to get rebuilt when running `tuist cache warm`. Cursory glance, seemed to be that whenever a module was built, it would rebuild all downstream dependencies regardless if it had been build in that run or not. i.e. When A->B->C is the graph, C was getting built 3 times.

## What 🌱

It's possible there's a bug in the logic that determines what frameworks should be re-built. We should investigate this further.

**Comment by RomainBoulay** [comment]
Great, thanks for reporting. I'll take a look!

**Comment by pepibumur** [comment]
This should already be fixed on master :)
