### ISSUE TITLE
Referencing a resource from with a framework dependency breaks generator

### ISSUE THREAD

**Issue by kalkwarf** [tuist/tuist#1584]
**Describe the bug**
Adding a dependency to `GoogleMaps.framework` *and* a Resources reference to `GoogleMaps.bundle` causes errors generating projects.

**To Reproduce**
1. Create a trivial project, and add a `Vendor` directory to the root, then acquire `GoogleMaps.framework` and put it there.
1. Describe a framework target with one dependency, and one resource:

``` swift
Target(name: "playground",
       platform: .iOS,
       product: .framework,
       bundleId: "io.tuist.\(name)",
      infoPlist: .extendingDefault(with: infoPlist),
      sources: ["Sources/**"],
      resources: [ .folderReference(path: .relativeToRoot("Vendor/GoogleMaps.framework/Resources/GoogleMaps.bundle")) ],
      dependencies: [ .framework(path: .relativeToRoot("Vendor/GoogleMaps.framework")) ],
      settings: settings)
```

_notice that `GoogleMaps.bundle` is nested inside the framework_

1. `tuist generate`

**Expected behavior**
I expected the framework target to be generated, with a dependency on `GoogleMaps.framework` and a Copy Resources phase to move the `GoogleMaps.bundle` to the root of the Resources folder. Instead, an error is reported:

`Couldn't find a reference for the file at path /Users/me/Desktop/playground/Vendor/GoogleMaps.framework.`

**Screenshots**
Here is a screenshot of the framework, so you can see the nesting:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/1033839/88340753-5d7c0f80-cd0a-11ea-8688-a558a2a89414.png">

Removing the framework from the dependencies results in the Copy phase being correctly created:

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1033839/88341738-23ac0880-cd0c-11ea-9779-185368c90dec.png">

I tracked the origin of the exception down to this coercion failing (elements[path] returns an object, but the cast/coercion fails):

``` swift
    func file(path: AbsolutePath) -> PBXFileReference? {
        elements[path] as? PBXFileReference
    }
```

but I'm a little lost as to why this is happening.

**Comment by kwridan** [comment]
Hi @kalkwarf thanks for flagging this.

To double check, is the resource bundle intended to be consumed in this manner? Typically a framework's resources are bundled and accessed via the framework itself as opposed to directly extracting / embedding it.

Looks like we've hit this before:
https://github.com/tuist/tuist/issues/1334#issuecomment-626901732

The workaround suggested there if it is indeed intended to be used this way is to create a symlink for the `.bundle elsewhere (e.g. `Vendor/GoogleMaps.bundle`) such that it doesn't share the same hierarchy of the `.framework` which is the cause for the error you're seeing.

One improvement we can do is to add a lint rule that warns / errors in the event a resource being referenced resided within a dependency to help surface this issue and suggest some potential remedy actions.

Hope this helps!

**Comment by kalkwarf** [comment]
Yeah, it's not my idea of a great solution, but calls into GoogleMaps fail, asserting that the bundle is expected in the hosting application's resources. I really hate symlinks, and one of the motivations for using Tuist was that I could eliminate all the symlinks in our repo, because any given file can be referenced directly by a `Project.swift`.

The workaround I came up with was to add a script phase that copies the bundle by hand. It's not elegant, but it works, and doesn't add symlinks to my source tree.

Thanks for the answer, and suggestions!

**Comment by pepibumur** [comment]
this is duplicated https://github.com/tuist/tuist/issues/1779
