### ISSUE TITLE
Add `--json` option to scaffold's output listing command

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#1589]
## Context 🕵️‍♀️

This is a follow-up task related to [Tuist list output](https://github.com/tuist/tuist/issues/1147). 

## What 🌱

Add `--json` option to print the list of templates in `json` format.

```bash
$ tuist scaffold list --json
```

**Comment by pepibumur** [comment]
Thanks for tackling this one @mollyIV 👏  very appreciated. You are ramping up very quickly in the project.
