### ISSUE TITLE
Build Configurations missing from generated project

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#159]
When defining the project, I have set up both `debug` & `release` configurations, with xcconfig files, in my settings, but I only get get the `Debug` configuration in the resulting project.

I can see both xcconfig files in the generated project, but only `Debug` is created in the project.

Everything works fine if I add the `Release` build configuration and point it to the xcconfig file manually.

Am I missing something?

```swift
let settings = Settings(
  base: […],
  debug: Configuration(settings: […], xcconfig: Paths.xcconfig(.debug)),
  release: Configuration(settings: […], xcconfig: Paths.xcconfig(.release))
)

let project = Project(
  name: "ProjectName",
  settings: settings,
  targets: [
    Target(name: "FrameworkName",
      platform: .iOS,
      product: .framework,
      bundleId: "com.org.project",
      infoPlist: "Info.plist",
      sources: "Sources/**",
      resources: "Resources/**",
      headers: Headers(public: "Headers/Public/*"),
      actions: [...],
      dependencies: [...],
      settings: settings
    )
  ]
)
```

**Comment by pepibumur** [comment]
This is another feature made on purpose. Since `Release` configuration is barely used, Tuist only generates the `Debug` configuration. You can pass the flag `--config Release` to generte a different configuration.

Do you think this would be a limiting thing for you? Do developers in your team usually compile the `Release` configuration when they are working on the project?

**Comment by enhorn** [comment]
We use three different configurations currently, `debug`, `preview` and `release`, in our live project. Preview and release id build by our CI server.

For us, our AdHoc `preview` is built each night.

As we can't build our whole workspace yet, as the main app target contains app extensions, we currently do a one-off when adding new sub-projects to our workspace, which we then add the preview and release configurations to. We then link the sources, resources etc from the main file back to the Tuist generated project and workspace so that there is a fully functioning Tuist workspace with all our projects.
