### ISSUE TITLE
Generated resource bundle does not have Info.plist file.

### ISSUE THREAD

**Issue by Mateusz-Chechlinski** [tuist/tuist#1602]
**Description**
When target's product is set to `staticFramwork` and there are some resources in the project, Tuist will automatically generate a new target for a resource bundle as well as an utility extension `Bundle+Module.swift` for retrieving the right bundle. It works mostly fine, except that the generated resource bundle does not contain an `Info.plist` file. As a result, `UIImage(named:in:compatibleWith)` is not able to retrieve an asset from a compiled `Assets.car` file.

**To Reproduce**
1. Define a project with a target similar to this one:
```
        Target(
            name: "Module",
            platform: .iOS,
            product: .staticFramework,
            bundleId: "io.tuist.Module",
            deploymentTarget: .default,
            infoPlist: .file(path: "Module/Info.plist"),
            sources: [.init("\(name)/**", excluding: "**/*Spec.swift")],
            resources: [
                "Module/**/*.storyboard",
                "Module/**/*.xib",
                "Module/Resources/**",
            ],
            settings: .default
        )
```
2. Add an asset catalog to the module (for example: `Images.xcassets`)
3. Add an asset to the asset catalog (let's call it "some-asset" in the example)
4. Generate the project with `tuist generate`

**Actual behavior**
A project `Module` is generated. It has a target `ModuleResources` (which is a bundle target). An extension `Bundle+Module.swift` is generated.

**Expected behavior**
Except the existing behaviour described above, a default Info.plist file is generated for the `ModuleResources` target. As a result it is possible to retrieve the asset from the asset catalog with the following syntax:
`UIImage(named: "some-asset", in: ModuleResources.bundle, compatibleWith: nil)`. When `Info.plist` is missing, it is only possible to retrieve regular resources and it isn't possible to use `*.xcassets` catalog.

**Desktop (please complete the following information):**
- Tuist 1.14.0

**Comment by kwridan** [comment]
Hi @Mateusz-Chechlinski, thanks for flagging this!

Indeed seems like a case we missed.

I had a quick look and there are two reasons for this:

1. We're not setting `infoPlist: .extendingDefault(with: [:])` on the Resource target in the [ResourceMapper](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift#L32)  _(This would instruct Tuist to generate the default infoPlist file for that target)_ 

2. The order in which we add the resource target in the [mappers pipeline](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/GraphMappers/ProjectMapperProvider.swift#L28) is after generating info plists, as such we'd need to swap the order to ensure the info plists mapper takes place after the resources mapper

**Comment by Juanpe** [comment]
Hi!

Is anybody working on this? I'd be happy to start to work on this :)

**Comment by kwridan** [comment]
Hi @Juanpe, yes please you're more than welcome to give this a go :) 

happy to assist if you have any queries.
