### ISSUE TITLE
Xib/Storyboard localization files aren't grouped correctly

### ISSUE THREAD

**Issue by natanrolnik** [tuist/tuist#1607]
**Describe the bug**

When using localized xib or storyboard files, the project tuist generates doesn't group them in the same way as Xcode does.

**To Reproduce**

Open [the attached zip file](https://github.com/tuist/tuist/files/5012335/tuist-xib-repro.zip). In `tuist-xib-repro-works.xcworkspace`, in the `tuist-xib-reproKit` resources, you can see how Xcode groups the strings under the xib file group. When you open the `tuist-xib-repro.xcworkspace` and check the generated one, you'll see that the strings file are located "outside" of the xib.

Besides that, in the "Copy Bundle Resources" build phase, they also differ. While in the manual project the .xib file is considered part of the localization folder and doesn't show the strings, the generated project's phase includes both .strings files and the .xib.

**Screenshots**

<img width="560" alt="Captura de Tela 2020-08-02 às 18 14 57" src="https://user-images.githubusercontent.com/1164565/89126146-14874080-d4ec-11ea-9c89-d22775979cc9.png">

<img width="1493" alt="Captura de Tela 2020-08-02 às 18 16 29" src="https://user-images.githubusercontent.com/1164565/89126193-83fd3000-d4ec-11ea-9569-e8cf23b657cc.png">
**Desktop (please complete the following information):**

**Expected Result**
Have the same behavior as localizing these files in a manual project.

- OS: macOS 10.15
- Version 1.14.0

**Comment by cooksimo** [comment]
Did you find a workaround or anything for this? I have the same issue

**Comment by svenmuennich** [comment]
We also ean into this issue. I'll look into fixing this via PR next week.

**Comment by svenmuennich** [comment]
I opened a PR: https://github.com/tuist/tuist/pull/3075
