### ISSUE TITLE
Absolute Path in Embed Precompiled Frameworks

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#161]
The idea is to always generate Xcode project locally, right? So not sure if this is an actual issue for Tuist.

### Scenario
In my current project, we use Tuist to generate our sub-project in a standardized way and then copying them to our main project and add to our current workspace. We have a fairly complex setup with an action extension, notification service extension and a notification content extension, so we can't replace main app yet with a Tuist generated one.

### Issue
In the generated project, for my tests and app targets, the build phase `Embed Precompiled Frameworks` uses an absolute path to the `tuist` command, which naturally won't work on multiuser projects.

**Comment by pepibumur** [comment]
Thanks for reporting this @enhorn. We can update the build phase to use the `tuist` available in the environment instead of the absolute one.

Also, I'm curious to know more about that complexity that you talk about in your project. That'll help prioritize the work on Tuist.

**Comment by enhorn** [comment]
@pepibumur  For as far as I've seen, I've been able to generate all our sub-projects without issues, except the main one with the app target & bundled extension targets. We have 10 projects in a workspace now, where currently only the main app project can't be built due to the app extensions.

As far as I can tell, when all cases [here](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Product.swift) are supported by Tuist (`.appExtension` for our project), I'll probably be able to generate our whole project.

**Comment by pepibumur** [comment]
That's great to hear! I'll do my best to provide support for that so that you can use Tuist to generate the whole project. Thanks for reporting all the issues, by the way, I appreciate it a lot 🙏
