### ISSUE TITLE
Xcassets not added to targets

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#162]
### Scenario:
I have an asset catalogue (`Assets.xcassets`) that I have placed in my `resources` folder, that I have added to the target with `resources: "Resources/**"`.

### Issue
The catalogue gets added to the generated project as expected, but isn't selected in the target memberships list. Other resources are have correct target memberships set.

### Expected Result
Asset catalogues should have the correct target membership, just like other types of resources.

**Comment by pepibumur** [comment]
Thanks for reporting this @enhorn. I'll move the discussion to [this other issue](https://github.com/tuist/tuist/issues/138) where the same issue was reported.
