### ISSUE TITLE
Empty "Expand Variables Based On" in TestAction if some environment or arguments are set

### ISSUE THREAD

**Issue by AlbertMontserrat** [tuist/tuist#1625]
**Describe the bug**
When we specify some arguments or environment variables in the TestAction (in Scheme specification), the MacroExpansion property is hardcoded to `nil`. This makes that this arguments or variables cannot use the macros from the main target (like $(SRCROOT), $(PROJECT_DIR), etc.

**To Reproduce**

1. Configure a scheme with a TestAction adding an environment variable that uses some macro.
2. `tuist generate`
3. Check the generated Project -> Scheme -> Test
4. The `Expand Variable Based On` is set to `None`, and when running tests, the macro is not resolved.

**Expected behavior**
The same that happens when no environment is set, we can use macros from another target.
IMO, TestAction class should have an extra argument that is a target reference to be used as a macro extension.

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.3
- Tuist version: 1.11.0

**Comment by danyf90** [comment]
There should be a `expandVariableFromTarget` for that now
