### ISSUE TITLE
Setting host application target dependency doesn't work

### ISSUE THREAD

**Issue by gbrhaz** [tuist/tuist#1629]
**Describe the bug**
I have a `uiTests` target that needs a dependency on the host application. Setting the relevant dependency works in that the dependency appears in the dependencies list, but doesn't set the 'Target Application' under the 'General' tab. It stays as 'None'.

**To Reproduce**

```
Target(
            name: "AppNameUITests",
            platform: .iOS,
            product: .uiTests,
            bundleId: "SomeBundleId",
            infoPlist: "Supporting Files/Info.plist",
            sources: [
                SourceFileGlob("Tests/UI/**", excluding: [])
            ],
            resources: resources,
            dependencies: [
                .target(name: "HostApp")
            ]
        )
```

**Expected behavior**
I'd expect the Target Application dropdown to be set.

**Desktop (please complete the following information):**

macOS 10.15.4
Tuist 1.13.1

**Comment by kwridan** [comment]
Hi @gbrhaz, thanks for flagging this.

I just double checked with Tuist 1.14.0 on a fixture we have with a similar setup https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_tests/Project.swift, it appears to be working as expected. 

![Screen Shot 2020-08-06 at 3 29 40 PM](https://user-images.githubusercontent.com/11914919/89544168-af885f00-d7f9-11ea-9348-4277192f13f6.png)
![Screen Shot 2020-08-06 at 3 29 45 PM](https://user-images.githubusercontent.com/11914919/89544172-b0b98c00-d7f9-11ea-91e1-78bf25d25ba8.png)


Mind trying to make a small fixture that reproduces the issue you're seeing?

Thanks!

**Comment by gbrhaz** [comment]
Hi @kwridan I've just done a bit of testing and it looks like the issue occurs when the `.app` target has a name that contains a dash in it; using your example above, edit to the following:

```
import ProjectDescription

let project = Project(name: "App",
                      targets: [
                          Target(name: "App-dash",
                                 platform: .iOS,
                                 product: .app,
                                 bundleId: "io.tuist.App",
                                 infoPlist: .file(path: .relativeToManifest("Info.plist")),
                                 sources: .paths([.relativeToManifest("Sources/**")]),
                                 dependencies: [
                                     /* Target dependencies can be defined here */
                                     /* .framework(path: "framework") */
                                 ],
                                 settings: Settings(base: ["CODE_SIGN_IDENTITY": "",
                                                           "CODE_SIGNING_REQUIRED": "NO"])),
                          Target(name: "AppTests",
                                 platform: .iOS,
                                 product: .unitTests,
                                 bundleId: "io.tuist.AppTests",
                                 infoPlist: "Tests.plist",
                                 sources: "Tests/**",
                                 dependencies: [
                                     .target(name: "App-dash"),
                                 ],
                                 settings: Settings(base: ["CODE_SIGN_IDENTITY": "",
                                                           "CODE_SIGNING_REQUIRED": "NO"])),
                          Target(name: "AppUITests",
                                 platform: .iOS,
                                 product: .uiTests,
                                 bundleId: "io.tuist.AppUITests",
                                 infoPlist: "Tests.plist",
                                 sources: "UITests/**",
                                 dependencies: [
                                    .target(name: "App-dash"),
                                    ])
])
```

You will now see that the UITests target no longer has Target Application set. The UnitTests target, interestingly, does have its Host Application set correctly.

**Comment by kwridan** [comment]
oh wow, that is unexpected. 

Thank you for looking further into this, will have a look to see what may be causing this.
