### ISSUE TITLE
Installation script doesn't install new releases

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#163]
I currently have the `0.7.0` release installed.

I try to rerun this command:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/tuist/install/master/install)"`

And get this output:
```
==> Installing Tuist
Getting versions available
Downloading...
==> Tuist installed 🎉
- Run `tuist --help` to get started
- Further documentation: 
    https://tuist.io
```

The installation script doesn't overwrite current binary (`/usr/local/bin/tuist version` reports `0.7.0`), and I only have the `0.7.0` folder in `~/.tuist/Versions`.

Is there currently a way to install updates, or do I need to uninstall & reinstall?

**Comment by pepibumur** [comment]
Could you try running `tuist update`?  [This page](https://tuist.io/guides/4-managing-versions) explains how versions are managed by Tuist.

**Comment by enhorn** [comment]
I swear I've tried it, must have accidentally pressed the wrong key or something similar. Embarrassing. 😑
Oh well, it updated it just perfectly. Thanks!

**Comment by pepibumur** [comment]
No worries! The `update` command was added to make the update process as seamless as possible. Glad that it worked.
