### ISSUE TITLE
Swift packages are always linked regardless of target type

### ISSUE THREAD

**Issue by jtyrie** [tuist/tuist#1648]
**Describe the bug**
If a swift package is a dependency of multiple targets in the hierarchy of an app, the package will be linked each time, causing a duplicate symbols error. 

I have updated the ios_app_with_static_libraries fixture here https://github.com/tuist/tuist/compare/master...jtyrie:spm-duplicated-linking to show this use case. Both the App target and Module B are linking the package SPMA. 

(I can't actually build this because I don't have swift 5.2 yet, but you can see the linking issue) 

**To Reproduce**
See above link or
- Create a local swift package
- Add as a dependency to a tuist static library 
- Add as a dependency on the main app.

**Expected behaviour**
- The package can only be linked once to allow successful building. 
- Chatting to @ollieatkinson, he suggests the package should only be linked if the target is a top level target, i.e. app / app extension / tests.

**Desktop (please complete the following information):**
- OS: macOS 
- Version 10.14.4

**Comment by jtyrie** [comment]
I've updated the sample app. The issue with using `Link Binary with libraries` instead of `Dependencies` is that it causes duplicate symbol errors when the `-ObjC` other linker is being used

**Comment by kwridan** [comment]
Thanks for flagging this @jtyrie 

Indeed the current integration with Swift Packages doesn't cover scenarios where multiple targets depend on the same packages. All other dependencies in Tuist are part of a graph where various rules are followed to determine when to link / embed dependencies, whereas Swift Packages are always linked without respecting those rules and hence resulting in the errors you flagged.

@zdnk and myself made an attempt at addressing this in #1831 but we kept hitting more edge cases as there are some implicit behaviours by Xcode based on the Package Product type (auto, static, dynamic). I haven't had a chance to figure them all out yet. On a slightly related topic #1674 is being worked on which may help address some of those integration issues in the future.

**Comment by danyf90** [comment]
Should be solved using Dependencies.swift
