### ISSUE TITLE
Docs: Improve adoption guidelines for xcconfig extraction 

### ISSUE THREAD

**Issue by garvankeeley** [tuist/tuist#1659]
The [docs](https://tuist.io/docs/usage/adoption-guidelines/#extract-your-build-settings-into-xcconfig-files) recommend this to get started by extracting build settings to an xcconfig:
`xcodebuild -scheme "MyScheme" -showBuildSettings >> MyScheme.xcconfig`
which produces a 450-line xcconfig, this is too much output to be useful; xcconfigs are typically a minimal set of customized keys, and Xcode defaults should be used for the vast majority of build settings.

Is there a more actionable starting suggestion that could be provided?

For instance it might be more useful to open the `.pbxproj` directly and search for `buildSettings = {` and extract those manually to an xcconfig file.

Note: if this should be reformatted as bug or RFC please LMK.

**Comment by pepibumur** [comment]
Thanks for bringing this up @garvankeeley. In fact, we've been pondering for a while providing a set of commands to assist developers in the migration to Tuist. Your issue gave me the idea to move this forward so I added the first command on [this PR](https://github.com/tuist/tuist/pull/1660):

```bash
tuist migration settings-to-xcconfig
```

It'd be great if you take a look at that PR and give us feedback.
