### ISSUE TITLE
Migration command that exits unsuccessfully if build settings are not empty

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#1681]
## Context 🕵️‍♀️
To ease the migration of projects to Tuist, teams might want to add a check on CI to ensure that no one has modified the build settings of a target or project after [extracting them](https://github.com/tuist/tuist/pull/1660) into an xcconfig file.

## What 🌱
Add a new command, `tuist migration check-empty-settings`, that exits with an unsuccessful status code if the build settings of a target or a project are not empty.

**Comment by kalkwarf** [comment]
This appears to be implemented in commit 152d11e

**Comment by adellibovi** [comment]
@pepibumur should this be closed as the command already exists? or what are we missing?

**Comment by pepibumur** [comment]
Yeah, it should be closed now.
