### ISSUE TITLE
[Enhancement] Add isMet support for the Rome Up command

### ISSUE THREAD

**Issue by miscampbell** [tuist/tuist#1685]
**Describe the bug**
The current Rome up command does not use the isMet method to validate whether it should run or not. We need to add support to check if the framework needs to be updated and then only execute the `rome download --platform ios --cache-prefix <Cache-Prefix>` when the required frameworks are not found.

**Additional context**
Adding this support will require us to look into the Rome project and understand how the frameworks are stored.

**Comment by pepibumur** [comment]
We are removing [tuist up](https://github.com/tuist/tuist/pull/3443) in the upcoming 2.0 release and therefore we are no longer providing support for `tuist up`.
