### ISSUE TITLE
Local SPM dependency added with absolute path, not relative

### ISSUE THREAD

**Issue by gbrhaz** [tuist/tuist#1691]
**Describe the bug**
Adding a local dependency is added to the pbxproj with an absolute path, not relative (`PBXFileReference.path` entry). This means everything works fine for local machine, but as soon as it's run in a CI environment or someone else's machine, things start to break down.

**To Reproduce**
Add local dependency with a relative path:

```
packages: [
        .package(path: "../../LocalDependency")
    ],
```

And in Target:

```
dependencies: [
                .package(product: "LocalDependency")
            ],
```

**Expected behavior**
Local dependency should be added with a relative path, which happens when you drag and drop a local Package directly.

**Desktop (please complete the following information):**

- OS: [e.g. macOS] 10.15.4
- Xcode 11.3.1

**Comment by kwridan** [comment]
Thanks for flagging this @gbrhaz.

Submitted a fix to address this #1706
