### ISSUE TITLE
CocoaPods execution command/path is not settable

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#1704]
**Describe the bug**
cocoapods is not executed as it is not installed in bundler or system, but with rbenv in bundler

**To Reproduce**
install rbenc, install ruby v 1.7.1 in rbenv. install bundler and install cocoapods

**Expected behavior**
well, i did not expect it to work, but i would specet to have option to set exeuction "command"/"path" or something for any tool that Tuist uses

**Comment by pepibumur** [comment]
We plan to deprecate the existing approach to integrate Pods and therefore this issue is no longer relevant. Hence I'll close it.
