### ISSUE TITLE
`tuist edit` should include Setup.swift

### ISSUE THREAD

**Issue by caipre** [tuist/tuist#1714]
**Describe the bug**
The `tuist edit` command does not include `Setup.swift` in the generated project. 

**To Reproduce**
1. Create `Setup.swift` (or run `tuist init`)
2. Run `tuist edit`

**Expected behavior**
The `tuist edit` command should bring all Tuist files into its project if they exist.

I might take a peek at tackling this later this week.

**Comment by laxmorek** [comment]
@fortmarek has suggested to include `Config.swift` into `tuist edit` too.

@caipre I can add it during the next weekend. 

I wanted to check how `tuist edit` works so I will be able to "kill to birds with a one stone".

**Comment by laxmorek** [comment]
@caipre you can try changes from https://github.com/tuist/tuist/pull/1745 :)
