### ISSUE TITLE
Directory names with dashes not supported

### ISSUE THREAD

**Issue by JanGorman** [tuist/tuist#1741]
**Describe the bug**
If the directory name that you create your tuist project in contains a dash, the generated code does not compile

**To Reproduce**

1. Make a directory for a tuist project `mkdir twist-test && cd $_`
2. Run the steps in documentation to create a project in this directory https://github.com/tuist/tuist#bootstrap-your-first-project-
3. `tuist build` fails because the generated Swift code contains invalid syntax:

```
❌ /some/dir/tuist-test/Targets/tuist-testUI/Sources/tuist-testUI.swift:3:25: expected '{' in class


❌ /some/dir/tuist-test/Targets/tuist-testUI/Sources/tuist-testUI.swift:3:33: top-level statement cannot begin with a closure expression


❌ /some/dir/tuist-test/Targets/tuist-testUI/Sources/tuist-testUI.swift:4:5: attribute 'public' can only be used in a non-local scope


❌ /some/dir/tuist-test/Targets/tuist-testUI/Sources/tuist-testUI.swift:4:19: static methods may only be declared on a type


❌ /some/dir/tuist-test/Targets/tuist-testUI/Sources/tuist-testUI.swift:3:33: expressions are not allowed at the top level


❌ /some/dir/tuist-test/Targets/tuist-testUI/Sources/tuist-testUI.swift:3:33: closure expression is unused
```

**Expected behavior**
The generated code should escape invalid characters or the bootstrap script should warn about invalid characters in the directory name and not generate a project in the first place.

**Screenshots**
<img width="391" alt="Screenshot 2020-09-03 at 07 33 57" src="https://user-images.githubusercontent.com/138166/92075057-e8473400-edb7-11ea-8f7a-6f5c0fc4dde1.png">

**Desktop (please complete the following information):**

- OS: macOS 
- Version 10.15.6

**Comment by fortmarek** [comment]
Yeah, I'll tackle it once [this is](https://github.com/tuist/tuist/pull/1635) is merged. I'd like to use for `tuist init` and `scaffold` templates [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit) which is what we already use for the aforementioned PR. This'll also need to add some custom filter `camelized` which will leverage a method with the same name that is already declared in the tuist project.

Thanks for flagging this!
