### ISSUE TITLE
Swift static lib dependency cannot be accessed from objective-c

### ISSUE THREAD

**Issue by remover** [tuist/tuist#1760]
**Describe the bug**

If `App` depends on `A`, which is a `.staticLibrary`, `A` cannot be accessed from objective-c code in `App`

**To Reproduce**

1. Download the attachment
2. cd `ios_app_with_static_libraries`
3. build the app
4. See errors in `AccessA.m` where neither import seems to work

**Expected behavior**

i would expect to be able to access the swift code in `A` from `App` by using the correct import

**Desktop (please complete the following information):**

- OS: OSX 10.15.6

**Additional context**

[ios_app_with_static_libraries.zip](https://github.com/tuist/tuist/files/5184085/ios_app_with_static_libraries.zip)

**Comment by matiasvillaverde** [comment]
One of the solutions that we found to the problem is to manually add the Swift generated headers into the path. We did this by adding a script in the build phases. 

```
target_dir=${BUILT_PRODUCTS_DIR}/include/${PRODUCT_MODULE_NAME}/

# Ensure the target include path exists
mkdir -p ${target_dir}

# Copy any file that looks like a Swift generated header to the include path
cp ${DERIVED_SOURCES_DIR}/*-Swift.h ${target_dir}
```

We found [this article useful](https://paul-samuels.com/blog/2018/01/14/swift-static-library-in-objective-c/)
