### ISSUE TITLE
Adding `disableSynthesizedResourceAccessors` to Config.swift as described does not work

### ISSUE THREAD

**Issue by jeroenleenarts** [tuist/tuist#1783]
**Describe the bug**
Adding `disableSynthesizedResourceAccessors` to Config.swift as described does not work.

**To Reproduce**
Follow guide: https://tuist.io/docs/usage/resources/
Make sure no resource accessors are in your Derived dirs.

**Expected behavior**
No resources will be generated.

**Desktop (please complete the following information):**

- OS: MacOS
- Version 10.15.6

**Comment by lukysnupy** [comment]
I face the same issue, the `GenerationOptions` doesn't contain that case.

```swift
public enum GenerationOptions : Encodable, Decodable, Equatable {

        case xcodeProjectName(ProjectDescription.TemplateString)

        case organizationName(String)

        case disableAutogeneratedSchemes
    }
```

**Comment by jeroenleenarts** [comment]
This is fixed by https://github.com/tuist/tuist/releases/tag/1.18.1
