### ISSUE TITLE
Tuist clean does not remove derived folders

### ISSUE THREAD

**Issue by jeroenleenarts** [tuist/tuist#1785]
**Describe the bug**
I expect `tuist clean` to remove all derived folders. It does not.

**To Reproduce**
Run tuist clean.

**Expected behavior**
Besides caches, also derived folders are removed.

**Comment by jeroenleenarts** [comment]
The `DeleteDerivedDirectoryProjectMapper` seems to contain the behavior I am looking for.

I noticed this issue when I rolled back from 1.18.0 to 1.17.0. I needed to get the bad generated code out.

**Comment by pepibumur** [comment]
Hey @jeroenleenarts. Why would you expect the `clean` to delete your project files? `tuist clean` is intended to be used for deleting global files that Tuist needs to generate to speed up the loading of the manifests and to cache your frameworks (i.e. `tuist cache warm`). Would you mind detailing your use case further?

**Comment by pepibumur** [comment]
I'm closing this for now since deleting derived files in the project's repository is not the responsibility of `tuist clean`
