### ISSUE TITLE
Add GitHub workflow that runs in the runner

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#1788]
The goal of this epic is to set up the Mac mini that we got from MacStadium with GitHub runner, Ruby, and Xcode so that we can run performance tests there.

**Comment by jeroenleenarts** [comment]
Why not install a Github Runner?

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by pepibumur** [comment]
Ouch, good point. I think using the GitHub runner is a much better idea 💡
