### ISSUE TITLE
Package resolution step during project generation

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#1811]
Hello,
I have noticed that this step takes considerable time on CIs. Is this step really required?
I guess that the purpose is to check that the referenced packages are all available.

**Comment by fortmarek** [comment]
Hi!

The reason for that step is as follows:
We can't rely on Xcode projects' existence. And if you add a package via Xcode, it's located inside `*.xcworkspace/xcshareddata/swiftpm/Package.resolved`.

To make sure that dependencies are always resolved to the same version, we need to create `.package.resolved` that *tuist owns*. But the only point when we can reliably do that is during the generation unfortunately 🙁 

On the other hand, if you build your project with eg `xcodebuild`, this resolution will need to happen at some point anyway - so, we'll just doing it eagerly here. If you have already packages resolved, the step should be considerably quick. 

Does this answer your question, @zdnk? Feel free to post any suggestion of how we can do this better. If this answers your question, consider closing this issue, thanks 🙂

**Comment by fortmarek** [comment]
Closing for now, we can reopen the issue if necessary
