### ISSUE TITLE
Synthesized Resource Accessors failure

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#1813]
**Describe the bug**
When running `tuist generate` it fails if I dont configure the generation with `.disableSynthesizedResourceAccessors`.
This issue emrged when I updated from 1.15 to 1.18.1

Also, this config option is not mentioned in the documentation.

**To Reproduce**
I am not sure which resource/target is causing this in our project.
We are using asset catalogs with pngs, jpegs and pdfs.

```
Determining the /Derived directories that should be deleted within <redacted>/ios-app
We received an error that we couldn't handle:
    - Localized description: The data couldn’t be read because it isn’t in the correct format.
    - Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not a valid property list.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Cannot parse a NULL or zero-length data" UserInfo={NSDebugDescription=Cannot parse a NULL or zero-length data})))"
```

**Expected behavior**
Project generation succeeds with default configuration.

**Desktop (please complete the following information):**

- Version 1.18.1

**Comment by zdnk** [comment]
Figured it out, it is caused by SwiftGen tryijg to parse empty `*.strings' files.

**Comment by fortmarek** [comment]
Hey @zdnk!

Thanks for the issue and for the fact that you figured it out and let us know 🙂 

> Also, this config option is not mentioned in the documentation.

You're right, I'll add that.

> Figured it out, it is caused by SwiftGen tryijg to parse empty `*.strings' files.

Huh, interesting. I think we can recognize empty `*.strings` files and show a warning to notice the user about that. I'll add some tests for that, after adding them we can close this issue (if your solution works for you now)
