### ISSUE TITLE
Support running `tuist edit` while debugging Tuist in Xcode

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#1814]
## Overview

While developing tuist, Xcode is often used to debug / test out new features. Typically the tuist commands are added as launch arguments in the `tuist` scheme.

The `tuist edit` command successfully works and launch a new instance of Xcode with the manifest loaded in it. Attempting to build the manifest however fails due to the `ProjectDescription` paths not being set correctly in the manifest editor Xcode project.

## Workaround

`swift run tuist edit` can be used from the command line as opposed to Xcode while this issue is fixed.

## Reference

> It appears that the problem is related to search paths. In the project generated by `tuist edit`, the framework search path points to `~/Library/Developer/Xcode/DerivedData/tuist-bggkhtdqqctkgpgksefefjesrvfj/Build/Products/Debug/PackageFrameworks`, and in that directory the `ProjectDescription.framework` does exist. However, `ProjectDescription.swiftmodule` is in the parent directory (`Debug`). 
>
> Changing the three search paths to point at `Debug` allows the Manifests project to build.

_Originally posted by @kalkwarf in https://github.com/tuist/tuist/pull/1782#issuecomment-696830359_

**Comment by kalkwarf** [comment]
BTW, it's not just the `edit` command. `tuist generate` fails with he same error: 
```
[31mCouldn't find ProjectDescription[0m
Program ended with exit code: 1
```

**Comment by kwridan** [comment]
Mind trying with the changes in #1819 ? I believe it may be the same issue.

**Comment by kalkwarf** [comment]
I confirm this now works properly.

**Comment by kwridan** [comment]
thanks for confirming @kalkwarf - will close this out
