### ISSUE TITLE
Add support for dynamic Swift Package libraries

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#1820]
**Describe the bug**
Adding local package to the project and as dependency to iOS app target does link it, but does not embed & sign it.

**To Reproduce**
Project.swift
```swift
packages: [
        // Local
        .package(path: "./TWLogging/"),
]
```

In app target:
```swift
dependencies: [
        .package(product: "TWLogging"),
]
```

**Expected behavior**
Tuist sets up correctly embedding of the package in the app. Links, embeds and signs.

**Screenshots**
<img width="531" alt="Screenshot 2020-09-24 at 16 11 06" src="https://user-images.githubusercontent.com/2551911/94156614-90649000-fe80-11ea-9348-7cdc2f656979.png">

**Desktop (please complete the following information):**
- Version 1.18.1

**Comment by kwridan** [comment]
Thanks for flagging this @zdnk - are you seeing any errors at runtime due to this?

Is `TWLogging` a dynamic or static library? The reason I ask is, for static libraries I believe not embedding is the correct behaviour.

Currently Tuist doesn't parse the Swift package manifest and doesn't have any knowledge on the product types :/

**Comment by zdnk** [comment]
It is dynamic library.

> Currently Tuist doesn't parse the Swift package manifest and doesn't have any knowledge on the product types :/

I see, what would you suggest then?
The issue is I need to use that package in multiple dynamic frameworks in our project.

**Comment by kwridan** [comment]
Two things I could think of at the moment:

- If the library is in your control, potentially changing it back to static library, and creating a wrapper dynamic framework (in Tuist) which can be used by your other dynamic frameworks. Not ideal but may assist in the interim (e.g. not ideal, but possibly the `@_exported` import may be of use - see https://davedelong.com/blog/2018/01/19/simplifying-swift-framework-development/)

- A slightly longer term option is to update Tuist to support detecting or specifying the product type:

```swift
dependencies: [
        .package(product: "TWLogging", productType: .dynamicLibrary),
]
```

That way the correct embed logic would be applied.

Specifying will be easier than detecting (parsing other system/tools manifests shouldn't be taken lightly as it will have an ongoing cost burden). 

cc: @fortmarek any other suggestions / ideas ?

**Comment by zdnk** [comment]
I think I woukd be more satisfied with the option 2 :) I figured the option 1 myself and considered it on multiple occasions, but it's dirty solution I dont really like.

Anyway would the Tuist team have the time to look into this and implement solution you proposed? Otherwise if you could provide pointers to what files are related to this (besides ProjectDescription obviously) so I can implement this behavior :)

**Comment by fortmarek** [comment]
> A slightly longer term option is to update Tuist to support detecting or specifying the product type

I agree - I'd just keep `.staticLibrary` as the default value to ensure this is not a breaking change.

> Anyway would the Tuist team have the time to look into this and implement solution you proposed? Otherwise if you could provide pointers to what files are related to this (besides ProjectDescription obviously) so I can implement this behavior :)

If you have the time resources, it'd be great if you could take a stab at this!

Yes, besides `ProjectDescription` you'll also add a new associated value to `Dependency.package` case (defined in `Dependency.swift`), so we can track the `productType`.

You can then leverage this `productType` in `LinkGenerator.swift` where you can embed it if it is a dynamic library. There is a fixture called `ios_app_with_local_package` on which you can test it out (just change one the product types of the package to `.dynamic`).

Feel free to ask if there is anything you'll need help with.

**Comment by josh150** [comment]
I just ran into this as well and the functionality would definitely be nice to have. My workaround was to add a post-build target action that utilized a slightly modified copy of the embed frameworks script from cocoapods.

```
.post(
	path: "./Scripts/embed_frameworks.sh",
	name: "Embed Package Frameworks",
	inputPaths: [
		"Resolver-Dynamic",
		"Foo",
		"Bar",
		"Baz",
	],
	basedOnDependencyAnalysis: false
),
```

In my copy of the embed frameworks script, at the bottom, I replaced the if blocks that manually specified which frameworks to install with the following scripting.

```
for (( n=0; n < $SCRIPT_INPUT_FILE_COUNT; n++ ))
do
	tmp="SCRIPT_INPUT_FILE_$n"
        FWK=${!tmp}
	install_framework "$FWK.framework"
done
```

The other improvement I needed to make was accounting for the fact that build and archive oddly place the frameworks into different paths and the "PackageFrameworks" path isn't available from any env vars. This is why I chose to go with a product name based approach for the input files. The following script is from install_frameworks.


```
if [ -r "${BUILT_PRODUCTS_DIR}/$1" ]; then
    local source="${BUILT_PRODUCTS_DIR}/$1"
  elif [ -r "${BUILT_PRODUCTS_DIR}/$(basename "$1")" ]; then
    local source="${BUILT_PRODUCTS_DIR}/$(basename "$1")"
  elif [ -r "${BUILT_PRODUCTS_DIR}/PackageFrameworks/$(basename "$1")" ]; then
    local source="${BUILT_PRODUCTS_DIR}/PackageFrameworks/$(basename "$1")"
  elif [ -r "$1" ]; then
    local source="$1"
  else 
  	echo "Unable to locate framework: $1"
  	exit 1
  fi
```

I've attached the full script here: [embed_frameworks.txt](https://github.com/tuist/tuist/files/5710317/embed_frameworks.txt)

**Comment by mihaicris-adoreme** [comment]
I ran into this issue, I am not in control of this package, thus for now I have to keep it in Cocoapods, otherwise, configured as package in Tuist, won't work.

👍 for this syntax: 
`dependencies: [
        .package(product: "ProductName", productType: .dynamicLibrary),
]`

**Comment by zdnk** [comment]
Yeah, it is the only thing that is currently blocking us from converting our application modules/frameworks to SPM packages :(

**Comment by pavm035** [comment]
Same for us it's a blocker now

**Comment by pavm035** [comment]
Meanwhile can we generate custom tuist executable by ourself with temporary fix by forking this project? i tried to generate executable but failed :( not sure if we are allowed to generate executable/artificats by ourself

**Comment by pavm035** [comment]
For me @josh150  idea works well, but looks like inputPaths does not work anymore so i used arguments to resolve this issue

```swift
.post(
    path: "./Scripts/embed_frameworks.sh",
    arguments: [
      "Foo",
      "Bar"
      ],
      name: "Embed Package Frameworks",
      basedOnDependencyAnalysis: false
 )
```

inside shell script added this script at the bottom
```
# process input agruments(frameworks)
frameworks=("$@")
for i in "${frameworks[@]}"
do
  install_framework "$i.framework"
done
```

**Comment by danyf90** [comment]
Closed in favor of using Dependencies.swift
