### ISSUE TITLE
Extend tuist focus to delete the Swift packages that are not referenced by other targets

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#1823]
## Context 🕵️‍♀️
The tree-shaking logic in the `tuist focus` command doesn't remove the Swift Packages that have no dependant targets as explained in this [community topic.](https://community.tuist.io/t/spm-dependancies-in-ufeatures-example-project/128). Because of that when the Xcode project launches it, it has to resolve dependencies that are not used anywhere.

## What 🌱
Extend the focus command to remove the packages that are not referenced by any target.

**Comment by danyf90** [comment]
Do we still care about this now that we have Dependencies.swift?

**Comment by fortmarek** [comment]
> Do we still care about this now that we have Dependencies.swift?

Let's close this, we want to focus on `Dependencies.swift`.
