### ISSUE TITLE
Add ability to generate test scheme of only changed targets

### ISSUE THREAD

**Issue by thedavidharris** [tuist/tuist#1828]
## Need/problem

On CI, the most efficient way to run all tests is to combine them into a single scheme and let Xcode handle all the parallelization of the build process (tests still run on a single process). Given that Tuist has the ability to hash modules to determine changes, a future optimization would be to filter out targets that have not changed from a target branch, and create scheme that only has the changed targets.

## Motivation

https://github.com/tuist/tuist/pull/1765 creates an `xxx-Project` scheme that efficiently uses xcodebuild's planning to build all the tests in the fastest possible manner in the current build system. Outside of Tuist, we found such an approach on really large projects can shave 50% or more off of CI time. 

Also on really large projects, usually small PRs in theory don't need to actually test all the schemes, but only the scheme that has changed and any other associated imports. Inputs that change the configuration, such as compiler version flags

## Detailed design

As part of a future `tuist test` command, a flag for `tuist test --changed-modules` could be added that would:

1. Identify modules that have changed, similar to the caching mechanism
2. Create a scheme on the fly similar to `xxx-Project` but instead only with the modules identified in step 1
3. Run those tests

# Drawbacks

There are a few implementation details here that would need to be discussed:

- Determining the base branch from which to calculate changes
- Identifying edge cases in the hashing methodology that would not capture overall project or environment changes

Both of these may add some complexity

## Alternatives

This could be something put as an example of how to facilitate instead of in the codebase itself.

# Adoption strategy

Not a breaking change, but a new command

# How we teach this

Can be documented as a subcommand within `tuist test`, or if not part of the core Tuist codebase can 

# Unresolved questions

See the drawbacks section.

**Comment by fortmarek** [comment]
Thanks for creating this issue @thedavidharris!

The `test` command is now merged in master and therefore it makes sense to start working on this.

I'd just expand here on the detailed design with some of my remarks:

> Identify modules that have changed, similar to the caching mechanism

I am not that familiar with the caching mechanism, but I think we should be able to leverage some of its functionality. On the other hand, it might make more sense to use `git` output to properly identify changed files - for each target we would have loop through its sources and see if any of them have been changed. This might not be very performant, though, so we might have to look into how to optimize this if we decide to go down this path - but it can be good enough for starters.

> Create a scheme on the fly similar to xxx-Project but instead only with the modules identified in step 1

I am on the fence about this - creating a new scheme on the fly might complicate a few things (we'd have to modify the current `.pbxproj` and after the `test` command is done, delete the appropriate scheme again). My suggestion, at least for the first iteration, is to leverage automatically generated test schemes (aka each test target has its own scheme). 
What we could then do is run those test schemes individually based on the modified files (this can be slower than using a new scheme that contains all test suites we want and testing it, so it's something to take into account)

> Determining the base branch from which to calculate changes

I think that if the user just runs `tuist test --changed-modules`, it'd make sense to compare it to the not-yet-committed changes. But, of course, we also need to let the user specify which branch or which commit to compare it to if they don't want to diff it against the local changes. For starters, I'd just add `--branch` option - aka if you run `tuist test --changed-modules --branch main`, then it'd compare the changes between the current branch and the `main` branch. 

My last note and open question is regarding what we consider a changed module. Naturally, if there are changed files in the module, then we should consider the module to be changed. *But* let's consider the following example: I have modules A, B, C where B imports A as a dependency and similarly C imports B as a dependency. Now, when we make changes to B, do we consider C a changed module? I *think* that we should - for example B can contain some models that C leverages and therefore we'd want to run the tests. But I would not make this relationship transitive - if I change something in A, I would not consider C a changed module (and I would not run tests for it), I'd just run tests for A and B. Does that make sense or am I missing something?

@tuist/core, any thoughts?

**Comment by thedavidharris** [comment]
Similar discussion on Bazel here: https://github.com/bazelbuild/bazel/issues/7962. This is conceptually similar to RuleKeys: https://buck.build/concept/rule_keys.html.

> I am not that familiar with the caching mechanism, but I think we should be able to leverage some of its functionality.

That would be my easiest assumption. If the target does not need to be re-built per the cache, it shouldn't need to be re-tested either.

> What we could then do is run those test schemes individually based on the modified files (this can be slower than using a new scheme that contains all test suites we want and testing it, so it's something to take into account)

This is fair, but it can take many times longer to finish to the point where projects without large number of modules would be better off continuing to just run tests on xxx-Project, so I think it's a good path to iterate on but for anyone who would really benefit from this goal (which, I'm curious what the audience is, it seems our project is magnitudes larger than most on Tuist at the moment), they would need that functionality.

> For starters, I'd just add --branch option - aka if you run tuist test --changed-modules --branch main, then it'd compare the changes between the current branch and the main branch.

This would be difficult to do because you'd have to be checking out different branches. What we've done in some of our BUCK builds:

1. After every merge, CI runs a job on the main branch to create a file that outputs the RuleKey hash for each target (`buck targets --show-rulekey //...`) and cache that file in the CI cache
2. When CI is triggered for a branch, run `buck targets --show-rulekey //...` for the branch and then diff that output from the output in the master branch. 

In this model you'd just need a "reference" to compare against. `tuist cache print-hashes` is likely what we'd want to work with here.

> if I change something in A, I would not consider C a changed module (and I would not run tests for it), I'd just run tests for A and B

I think because of Swift's nature you have to consider C a changed model here, since imports are automatically exported and that can have interesting affects. If A was only imported with something like `@_implementationOnly import` then you could make an argument for it, but even things like compiler inputs I think could have some effect up the chain.

It's definitely best to align some of the hashing work around caching with this type of work for sure.

**Comment by pepibumur** [comment]
I'm chiming in here:
- **Scheme generation:** I really think this is the way forward. We should leverage Xcode's primitives and let Xcode determine what building and running test mean. @fortmarek brought a very valid concern which is what do we do with that scheme that we have generated for the `tuist test` command. My suggestion here is that all the automation commands (build, test) generate the projects in a global directory, e.g. `~/.tuist/Cache/Projects` where each folder represents a project, (e.g. `~/.tuist/Cache/Projects/MyApp-{fingerprint}`) where the fingerprint is generated from the path where the project is located. This has the downside that for Xcode it'll be 2 projects: the one that you are editing, and the one that you are building through Tuist. However, I think is a safe trade-off. 
  - The implementation of this would require 2 mappers, one that changes the paths of each of the projects in the graph to be generated in that temporary directory, and another one that generates the scheme.
- **Determining the base branch**: I think this should be part of the `Config.swift`:
```swift
import ProjectDescription

let config = Config(versionControl: .git(baseBranch: "master"))
```
- **Naming convention:** In order to determine which test files are associated to which source files, we need to establish a naming convention for the tests. For example, if a source file is called `MyController.swift`, the tests class should have the same name but suffixed with `Tests` (e.g. `MyControllerTests.swift`).

To determine what tests we'd need to run we can take the following input:
- Files that have changed from the version control system (we can focus on git initially).
- The dependency graph. 
- Arguments passed to the `tuist test` command.

**Comment by fortmarek** [comment]
Thanks for the input @pepibumur!

I think that the last piece we need to decide on if we can use version control system for finding which files have changed - @thedavidharris, you have mentioned that we'd need to check out different branches - is that the case, though? I think we can leverage `git diff` to get a list of changed files - or is there some other reason we'd need to check out branches? (but if so, then we'd need to step aside from version control option). But maybe we are missing something 🤔

**Comment by thedavidharris** [comment]
@fortmarek yeah you could just do a fetch and then diff of the branches, that would work.

Think you could either do it with the git references or just a reference rulekey, the latter may be easier as the rulekey implementation somewhat exists right now for the caching mechanisms.

I don't think I would do this at a file level where naming convention would matter: this is effectively just caching but for the run test part, so if a module is unchanged from a prior cached state that would have passed CI, it's not needed for that module to undergo changes. At a build system level, anything that's rebuilt within a module would need to have it's test re-run.

**Comment by fortmarek** [comment]
> Think you could either do it with the git references or just a reference rulekey, the latter may be easier as the rulekey implementation somewhat exists right now for the caching mechanisms.

I'd love to reuse the caching mechanism - but I am not sure when to save the reference rulekey for it to work reliably, without the user thinking about it. 

Eg. in your solution that you currently use with BUCK, you said:

> After every merge, CI runs a job on the main branch to create a file that outputs the RuleKey hash for each target (buck targets --show-rulekey //...) and cache that file in the CI cache

And I am worried that if we go down the rule-key path, the users will need to configure this - while leveraging git only should be possible to build without any configuration from the user (or almost none). Therefore, I think I will try first using git and see if I stumble upon any unresolvable issues

**Comment by thedavidharris** [comment]
> And I am worried that if we go down the rule-key path, the users will need to configure this - while leveraging git only should be possible to build without any configuration from the user (or almost none). Therefore, I think I will try first using git and see if I stumble upon any unresolvable issues

I don't disagree that's a potential stumbling block, but git-based configuration can require some effort as well, i.e. our CI does full shallow single-branch clones, so we don't have that comparison branch. Probably something we could fix, but our tree is pretty large so it's a little computationally inefficient when we're trying to shave time.

**Comment by fortmarek** [comment]
> I don't disagree that's a potential stumbling block, but git-based configuration can require some effort as well, i.e. our CI does full shallow single-branch clones, so we don't have that comparison branch. Probably something we could fix, but our tree is pretty large so it's a little computationally inefficient when we're trying to shave time.

It's true that if we look at it through a lens of caching, we can just reuse what we already have. I think when running `tuist test --changed-modules`, we could:
- create a new directory `~/.tuist/Tests` where we would save a hash of targets which tests have been successful (this hash could be created when runing `tuist test` without `--changed-modules`, too)
- see which targets do not have their hash present in `~/.tuist/Tests`
- run tests
- save the hashes we use in cache to `~/.tuist/Tests`

I have been prototyping with the git-based approach and the leveraging cache logic might be a better idea after all. 

AFAICT rulekey-approach should also be possible to do without any configuration which was the main reason I was leaning to git-based approach in the first place. Does the outlined solution make sense to you, @pepibumur @thedavidharris or am I missing something? (I have not really worked on `tuist cache`, so I might be missing some context there)

**Comment by andreacipriani** [comment]
> > I don't disagree that's a potential stumbling block, but git-based configuration can require some effort as well, i.e. our CI does full shallow single-branch clones, so we don't have that comparison branch. Probably something we could fix, but our tree is pretty large so it's a little computationally inefficient when we're trying to shave time.
> 
> It's true that if we look at it through a lens of caching, we can just reuse what we already have. I think when running `tuist test --changed-modules`, we could:
> 
> * create a new directory `~/.tuist/Tests` where we would save a hash of targets which tests have been successful (this hash could be created when runing `tuist test` without `--changed-modules`, too)
> * see which targets do not have their hash present in `~/.tuist/Tests`
> * run tests
> * save the hashes we use in cache to `~/.tuist/Tests`
> 
> I have been prototyping with the git-based approach and the leveraging cache logic might be a better idea after all.
> 
> AFAICT rulekey-approach should also be possible to do without any configuration which was the main reason I was leaning to git-based approach in the first place. Does the outlined solution make sense to you, @pepibumur @thedavidharris or am I missing something? (I have not really worked on `tuist cache`, so I might be missing some context there)

I can confirm from the "cache" point of view that a `targetHash` should identify a target uniquely. If you change a file in the target the hash will change. So yes, this approach should work IMO.
