### ISSUE TITLE
Add scheme to regenerate the project

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#183]
## Context 🕵️‍♀️
Although the Project manifest can be edited on Xcode, regenerating the project requires running the `tuist generate` command from the terminal and sometimes, closing and re-opening Xcode. Although this action is not performed that frequenly, when it's done it's a bit annoying.

## What 🌱
Since Tuist will generate schemes for the project, one of the schemes could just run a shell command that:
1. Regenerates the project.
2. Closes any instance of Xcode
3. Reopens it again.

The lifecycle of that command should be decoupled from Xcode in order for the whole flow to work.

**Comment by dangthaison91** [comment]
@pepibumur Will this get any benefits from #195 and #200 ?

**Comment by pepibumur** [comment]
It all depends on the implementation of the logic that generates the schemes. We might need to adjust it a little bit to generate the scheme described above.

**Comment by kwridan** [comment]
Would something like this help?

https://github.com/tuist/tuist/tree/features/regenerate-project-when-building-manifest

**Comment by kwridan** [comment]
With the introduction of the edit command #703, one idea would be to create a custom scheme that runs `tuist` with launch arguments of `generate --path /path/to/project`

**Comment by danyf90** [comment]
As the generation options are becoming more and more (fetching dependencies, warming caches, etc.), I don't think we'll be able to find a clean DX for this, and I would stick to invoking the CLI.

@kwridan @fortmarek do you think we can close this?

**Comment by fortmarek** [comment]
I agree 👍 Alternative for developers would be to add support for aggregate targets ([issue](https://github.com/tuist/tuist/issues/3388) here) – or create our very own SPM plugin. But imho, using the CLI offers already pretty good DX, so I don't see a real need to implement this now.
