### ISSUE TITLE
Replicate system folders in the generated workspace

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#187]
## Context 🕵️‍♀️
When projects get added to the generated workspace, we flatten them into the workspace root. As @kwridan suggested on [this thread](https://github.com/tuist/tuist/issues/172#issuecomment-448758374) we could follow the project's convention for workspaces as well:

> It’ll be familiar, and it keeps with the conventions paradigm. Additionally it’ll be consistent to how the files / groups are setup for the sources.

## What 🌱
Instead of flattening the projects, replicate folders structure in the workspace.

**Comment by kwridan** [comment]
Resolved by #298

**Comment by pepibumur** [comment]
![giphy](https://user-images.githubusercontent.com/663605/54864292-a22e1a00-4d55-11e9-8259-036eb899f8cc.gif)
