### ISSUE TITLE
Environment substitutions not performed on output paths during cache warm

### ISSUE THREAD

**Issue by kalkwarf** [tuist/tuist#1870]
**Describe the bug**
`tuist cache warm` fails with file not found when a `targetAction.outputPaths` or `targetAction.outputFileListPaths` use environment variables

**To Reproduce**
1. Generate a script phase that references `DERIVED_FILE_DIR`, like so
```
pre(
  path: .relativeToRoot("scripts/xcode/bootstrap-check.sh"),
  arguments: [],
  name: "Bootstrap check",
  inputFileListPaths: [
    .relativeToRoot("scripts/xcode/bootstrap-check-input.xcfilelist"),
    .relativeToRoot("Tuist/tuist-files.xcfilelist")
  ],
  outputPaths: ["$(DERIVED_FILE_DIR)/bootstrap_check_ran.txt"]
)
```
2. Run `tuist cache warm`
3. See error `File not found at /Path/To/Project/$(DERIVED_FILE_DIR)/bootstrap_check_ran.txt`

**Expected behavior**
The path to the output file needs to be expanded.

**Desktop (please complete the following information):**
- OS: 10.15.6
- Version 1.20.0

**Additional context**
The default when adding a derived file is `$(DERIVED_FILE_DIR)/newOutputFile`. I can't figure out how we can handle this.

**Comment by erkekin** [comment]
this is still an issue and it is not related to` tuist cache` only, happens when `tuist test` is run too
