### ISSUE TITLE
Support for Multiple Configurations

### ISSUE THREAD

**Issue by khoogheem** [tuist/tuist#1882]
## Need/problem

Current Tuist looks to only support a Dev/Release Configuration.
However in most of the projects I have worked on having the Apple Standard two configurations just doesn't work.

We typically have a Dev/Release and BetaTest Configuration

Where the BetaTest may be an Ad-Hoc setup but may be setup to have env as DEV or PROD to point to different backend services

**Comment by kwridan** [comment]
Hi @khoogheem 

I believe you can already achieve what you're after by specifying custom configurations in the manifest:
https://tuist.io/docs/usage/project-description/#custom-configuration

Here is an example of adding a third configuration "Beta":
https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_multi_configs/App/Project.swift#L3

Hope this helps.

**Comment by khoogheem** [comment]
hmm.. is that recent?  in the last month?
either way I will close this then as at the time I looked at it.. it. appeared to only have two set configurations you could use
