### ISSUE TITLE
`tuist local` with branch name containing slash

### ISSUE THREAD

**Issue by olejnjak** [tuist/tuist#1899]
**Describe the bug**

If we use tuist from custom branch, that has name containing a slash e.g. `bugfix/transitive_app_extension`, running `tuist local` successfully creates _.tuist.version_ file with correct branch name but running `tuist bundle` then fails. Well all call to tuist require new compilation and then fail (if `.tuist-bin` is not present obviously).

**To Reproduce**

1. run `tuist local bugfix/transitive_app_extension`
2. run `tuist bundle`
3. see error

```
olejnjak@Jakub-MacBook project % tuist bundle
Bundling the version bugfix/transitive_app_extension in the directory /Users/olejnjak/project/.tuist-bin
Version bugfix/transitive_app_extension not available locally. Installing...
Pulling source code
Cloning into '/var/folders/0g/y_6j5jd50s75h7m568jhpzrm0000gn/T/TemporaryDirectory.hzudhk'...
Updating files: 100% (2167/2167), done.
Building using Swift (it might take a while)
Version bugfix/transitive_app_extension installed
We received an error that we couldn't handle:
    - Localized description: The file “TemporaryDirectory.WeVAUV” doesn’t exist.
    - Error: Error Domain=NSCocoaErrorDomain Code=4 "The file “TemporaryDirectory.WeVAUV” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/var/folders/0g/y_6j5jd50s75h7m568jhpzrm0000gn/T/TemporaryDirectory.WeVAUV, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/olejnjak/.tuist/Versions/bugfix/transitive_app_extension, NSFilePath=/var/folders/0g/y_6j5jd50s75h7m568jhpzrm0000gn/T/TemporaryDirectory.WeVAUV, NSUnderlyingError=0x7fd871e045b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}"
```

**Expected behavior**

Well this is a good point, in the best scenario I would love tuist to just work with such named branches, but I can imagine that the complexity of this behavior is too high. So I can think about a few solutions:
1. convert `/` in branch names to different character, which might be tricky
2. when running `tuist local` with such branch name warn user that it is not recommended or fail with error and suggest to use commit hash instead as that works just fine
3. support nested directories in `.tuist/Versions`

**Desktop (please complete the following information):**

- OS: macOS Big Sur (20A5384c)
- Tuist Version: 1.21.0

**Additional context**
Well I'd like to discuss the possible solutions so I can implement it right away. For me the candidate is 2. as it is clear, simple and makes sense.

Thanks in advance!

**Comment by danyf90** [comment]
`tuist local` only supports versions as of now
