### ISSUE TITLE
Generating a project name with certain characters creates bad bundle identifiers

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#193]
**Describe the bug**
Bundle identifiers have a restricted set of characters which are allowed. It must be a UTI that contains only alphanumeric (`A-Z`,`a-z`,`0-9`), hyphen (`-`), and period (`.`) characters.

**To Reproduce**

1. Generate a project with an underscore (`_`)
2. Build in Xcode
3. See build warning

```
warning: invalid character in Bundle Identifier. This string must be a uniform type identifier (UTI) that contains only alphanumeric (A-Z,a-z,0-9), hyphen (-), and period (.) characters.
```

**Expected behavior**
We should transform the characters to valid ones and inform the user we had to make that decision during `tuist generate`.

**Comment by pepibumur** [comment]
Thanks for bringing this up @ollieatkinson. This is definitively a bug that should be fixed 👍
