### ISSUE TITLE
Add integration tests for the generate command

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#197]
## Context 🕵️‍♀️
Despite Tuist having unit tests for most of the components in the project, it lacks some integration tests that verify that all the commands provided by the tool generate the right output. Lacking those tests makes it hard to add changes with confidence.

For instance, it'll facilitate the refactoring work that @kwridan and @marciniwanicki plan to do as explained on [this issue](https://github.com/tuist/tuist/issues/192).

## What 🌱
We can start by adding integration tests to the main command of the tool, generate. The integration test can use a manifest that contains all supported properties as an input, and verify the generated Xcode project is valid. I suggest recreating a standard project that might contain an app, framework and test targets.

## Proposal 🎉
Integration tests are written with [Cucumber](https://github.com/cucumber/cucumber-ruby), under the [features](https://github.com/tuist/tuist/tree/master/features) directory. Add one or more tests for those commands before starting with any refactoring work.

**Comment by marciniwanicki** [comment]
Would it be a good idea to restructure the `fixtures` folder slightly such that the projects have less meaningful folders names e.g. "sample_1", "sample_2", "sample_3", but are well described in a `README.md` within the fixtures folder?

e.g. 

```
fixtures
├── README.md
├── sample_app_1
│   └── ...
├── sample_app_2
│   └── ...
└── sample_app_3
    └── ...
```

Having meaningful names is actually nicer, however as we want to add more integration tests (as mentioned in https://github.com/tuist/tuist/issues/198, https://github.com/tuist/tuist/issues/197 for happy and non-happy paths), the folder names might grow leaving short names inaccurate and too generic (`multiple_projects`) and long names difficult to follow (`multiple_projects_with_static_and_dynamic_frameworks`). It seems to be quite tricky to include all the information about the content in a single, relatively short string.

```
fixtures
├── multiple_projects_with_static_and_dynamic_frameworks
│   └── ...
├── multiple_projects_with_static_and_dynamic_frameworks_invalid_manifest
│   └── ...
└── app_with_tests
    └── ...
```

Or perhaps some hybrid of the two approaches?

**Comment by ollieatkinson** [comment]
I came across one problem with less meaningful folders names today. I wanted to write a new acceptance test and did not know what number to select - at least with more meaningful names this problem is avoided.

I like your idea of a markdown file describing the fixtures in more detail and I think we should do that with whatever solution we choose.

**Comment by pepibumur** [comment]
The problem that I see in trying to find meaningful names is that we can easily end up with inconsistent names. For instance, if you look at Facebook's [xctool](https://github.com/facebook/xctool/tree/master/xctool/xctool-tests/TestData) it's hard to guess the naming convention that they are following and what the use cases actually are.

I'm inclined towards just using an incremental number as the folder name and having a README file in the fixtures directory that describes the use case that we're trying to test with each project.

What do you think @ollieatkinson / @marciniwanicki ?
