### ISSUE TITLE
Support define Scheme in Manifest

### ISSUE THREAD

**Issue by dangthaison91** [tuist/tuist#199]
**Is your feature request related to a problem? Please describe.**
In our project, we created 3 schemes with different build configurations, xcconfigs for 3 environments: 

**- App-Dev**
**- App-Staging**
**- App-Production**

 So we would like Tuist Manifest will support custom `Scheme`.

**Describe the solution you'd like**
Tuist will generate Scheme which is defined in the manifest. If there is no schemes is defined, fallback to using **Auto-create** scheme for each target.

**Comment by pepibumur** [comment]
> Tuist will generate Scheme which is defined in the manifest. If there is no schemes is defined, fallback to using Auto-create scheme for each target.

I'd rather keep the automatically-generated schemes with the ones defined by the user. If we see this is a bit inconvenient for developers, we can introduce an attribute to disable that behaviour. The reason to keep the automatic generation is that you might not want to re-define the schemes for all the targets in the projects.

Let's say your app, which has three flavours, dev, staging, and production, depends on a target, MyUI, which is defined with Tuist. For that target, you might be interested in having a scheme to compile the framework, but you don't need any custom configuration in the scheme. In that case, you can let Tuist generate a basic scheme for you.

what do you think @dangthaison91 ?

**Comment by dangthaison91** [comment]
That makes sense @pepibumur . Currently, our project is trying to separate app features into multi-project, approach feature-framework development. We often create only one scheme for each framework without any configuration. Automatically generate schemes that are not defined will help to simplify project manifest file. I will update PR #200

**Comment by dangthaison91** [comment]
Resolved by #336
