### ISSUE TITLE
Swift package dependencies should support `.branch`

### ISSUE THREAD

**Issue by caipre** [tuist/tuist#1996]
**Describe the bug**
The [`.package` attribute of a `Project` description](https://tuist.io/docs/usage/project-description/#package) allows version specifiers and local package names, but does not allow a branch specifier. The Swift Package Manager does support such a specifier, as described here: https://github.com/apple/swift-package-manager/blob/main/Documentation/PackageDescription.md#package-dependency-requirement

**To Reproduce**

A `Project.swift` file with the following:

```swift
let project = Project(
  name: "Example",
  packages: [
    .package(path: "https://github.com/example/example", .branch("master"))
  ]
)
```

**Expected behavior**
It should be possible to add a package dependency using a `.branch` specifier, as in Swift Package Manager.

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.7

**Comment by andreacipriani** [comment]
cc @ollieatkinson to know if there were some limitations or if I can go ahead and support this

**Comment by ollieatkinson** [comment]
Hi @caipre, We actually already support this as well as [a wide range of package version requirements](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Package.swift#L53). 

I do notice a problem with the reproduction `Project.swift` you provided - the label to refer to a remote package url is incorrect:
```diff 
- .package(path: "https://github.com/example/example", .branch("master")) 
+ .package(url: "https://github.com/example/example", .branch("master"))
```

↑ Note the label is `url` not `path`. This naming convention is taken from Swift Package Manager itself. If this does not work, and we do not support some of the specifiers offered by Swift Package Manager then we can look at raising a ticket to implement the differences

**Comment by caipre** [comment]
hmm, well now I'm very confused as to what I was doing before. Unfortunately I've closed the terminal so no longer have the scrollback. My best guess is that I was writing `.package(url: ..., branch: ...)`, with `branch` as a label instead of an initializer.

(The `path` vs `url` thing was a typo; my fault for writing the example from scratch instead of providing a real failing case!)

Thanks for the quick response @ollieatkinson !
