### ISSUE TITLE
Can't disable `xxx-Project` scheme generating. 

### ISSUE THREAD

**Issue by laxmorek** [tuist/tuist#1997]
**Describe the bug**
I added `.disableAutogeneratedSchemes` to my `Config.swift` but `tuist generate` generated `xxx-Project` scheme.

**To Reproduce**
1. Add `.disableAutogeneratedSchemes` to `Config.swift`
2. Run `tuist generate`
3. Open Xcode and check list of schemes.
4. See unwanted `xxx-Project` scheme.

**Expected behavior**
Adding `.disableAutogeneratedSchemes` to `Config.swift` should disable `xxx-Project` scheme generating.

**Comment by fortmarek** [comment]
Hi 👋

I think this is due to some caching of schemes. Can you first remove `.xcodeproj` and `.xcworkspace` directories first and only after that run `tuist generate`. I believe it will not be shown there afterwards - but it'd be great if you could check that 🙂

**Comment by laxmorek** [comment]
I have checked it. You have right. We can close this issues.
