### ISSUE TITLE
Support adding file/folder as reference

### ISSUE THREAD

**Issue by dangthaison91** [tuist/tuist#202]
We have some files/folder as reference in the current project. Some are json files for stubbing Networking, some is linked from Pod library. They are set as `copy files = false`.

This will require config sources paths as array:

```swift
sources: [.file("Tuist/Config.swift"), .folder("Tuist/StubResponse"), .group("Tuist/Source/**/*")]
```
<img width="229" alt="screen shot 2019-01-17 at 10 47 03 pm" src="https://user-images.githubusercontent.com/6436310/51330345-ea0c9880-1aa9-11e9-9b88-3ba3b13d61a0.png">

**Comment by pepibumur** [comment]
This is a good idea @dangthaison91 👏. 

I think whether the element is a file or a folder is information that we can get from the file system, so I would not have cases such as a `.file` or `.folder`. Instead, we can have a type that looks like this (I'm pseudo-coding):

```swift
public struct FileReferences {
   
    let glob: String
    let copy: Bool

   init(glob: String, copy: Bool = true) {
    self.glob = glob
    self.copy = copy
  }
  
  public static func glob(_ glob: String, copy: Bool = true) -> FileReferences{
    return FileReferences(glob: glob, copy: copy)
  }   
}

extension FileReferences: ExpressibleByStringLiteral {}
```

Notice that by conforming the `ExpressibleByStringLiteral ` we can initialise the object using a string, making our change backwards compatible. If you initialise the object with a string, it'd default to a glob pattern with the copy value set to true. Your sources attribute in the target would look like:

```swift
sources: ["Sources/**/*.swift", .glob("Sources/Fixtures/**/*.json", copy: false)]
```

Thoughts? cc @asalom

**Comment by dangthaison91** [comment]
Should we define `FileReferences` as an enum then we can support `.include/.exclude` as you already mentioned in #162 :

```swift
public enum FileReference {
    case include(glob: String, copy: Bool)
    case exclude(glob: String, copy: Bool)
}
```
The downside is that by default Swift Enum doesn't support associated default values, so if we still one support backward compatible, we must add more code to have default values:

```swift
public enum FileReference {
    case include(glob: String, copy: Bool)
    case exclude(glob: String, copy: Bool)

    static func includePath(_ glob: String, copy: Bool = true) -> FileReference {
        return FileReference.include(glob: blog, copy: copy)
    }
...
}
```

Usage:

```swift
sources: [.include("Sources/**/*.swift"),
          .include("OtherSources/*.swift", copy: false),
          .exclude("Sources/Fixtures/**/*.json")]
```

**Comment by pepibumur** [comment]
> Should we define `FileReferences` as an enum then we can support `.include/.exclude` as you already mentioned in #162 .

I've slept over that idea, and I'm not 100% convinced. What I like about keeping the interface of file references restrictive to some extent, is that it's an opportunity for us to encourage developers to simplify the structure of their files and folders. 

That doesn't mean that we can't revisit the decision in the future if we see that this limitation brings unnecessary inconveniences.

I'm curious to know what other people think cc @marciniwanicki @kwridan @ollieatkinson. They've been using Tuist so they're more familiar with the usage of the API than I am.

**Comment by kwridan** [comment]
A bit of a late reply 😞

In many of our use cases we did find a need to support "project files" i.e. ones that aren't in any build phase, like READMEs and Documentation files. There's definitely a need to support those kind of files. Not sure if they technically belong to the target or the project. 

e.g. 

- Sources
  - SourceA.swift
  - SourceB.swift
  - Documentation
    - A.md
    - B.md
  - StubData
    - a.json
    - b.json

vs.

- Sources
  - SourceA.swift
  - SourceB.swift
- Documentation
  - A.md
  - B.md
- StubData
  - a.json
  - b.json

The latter approach may help alleviate the need to exclude those sources explicitly. We do have use cases where we need an explicit exclude, but our use cases might be the odd ones rather than the norm.

The ability to add multiple `sources` and `resources`(https://github.com/tuist/tuist/pull/201) is welcome addition. Folder references would be a great follow up :)

**Comment by kwridan** [comment]
Workspace improvements (#298) were recently added to Tuist 🎉

Perhaps we can unify approaches and have a consistent API?

e.g.

```swift
let project = Project(name: "App",
                      targets: [
                           // ...
                      ],
                      additionalFiles: [
                         "Documentation/**",
                         .folderReference("StubData")
                      ])
```

**Comment by kwridan** [comment]
The unified approach could look something like this:

## Additional Files

To include any file (including swift) that shouldn't be part of any build phases: 

```swift
let project = Project(name: "App",
                      targets: [
                           // ...
                      ],
                      additionalFiles: [
                         "Documentation/**",
                         "Dangerfile.swift"
                      ])
```

To include a folder reference that is not part of any build phase:

```swift
let project = Project(name: "App",
                      targets: [
                           // ...
                      ],
                      additionalFiles: [
                         .folderReference(path: "Designs")
                      ])
```

That could be one incremental addition to Tuist

## Target Resources

Another addition would be to support the same semantics for `resources` on `Target`:

```swift
Target(name: "App",
            // ...
            resources: [
                  "Assets/**",
                  .folderReference(path: "StubData")
            ]),
```

This will include `StubData` as a folder reference in Xcode and copy the folder (i.e. be part of the resources build phase).

This approach can help clarify and distinguish what can be copied vs not. If I'm not mistaken, copying a folder reference is only applicable to resources as opposed to sources.

**Comment by Tulleb** [comment]
@kwridan I'm having some issue adding a non-swift file (hiding generated swift files inside) like `*.rcproject` (RealityKit file type) to my target compile sources because it is not a `.swift` file.

Here is my Target declaration (with the file located next to other successfully imported `.swift` files):
```
Target(
...
  sources: ["\(frameworkPath)/Sources/**"],
...
)
```

**Comment by Tulleb** [comment]
@BenjaminPrieur 🙏
