### ISSUE TITLE
RFC: Add ability to specify location for ProjectDescriptionHelpers

### ISSUE THREAD

**Issue by luispadron** [tuist/tuist#2021]
## Need/problem

Currently the only way to include helpers to `ProjectDescription` is by including them under `Tuist/ProjectDescriptionHelpers`. 

## Motivation

We would like to solve the issue of having to specify helpers under `Tuist/ProjectDescriptionHelpers` by allowing users to specify a path, either local or remote. This path would point to a directory of `.swift` files which would be used to define the `ProjectDescriptionHelpers` for Tuist.

### Where to define the path to `ProjectDescriptionHelpers`

I believe that defining this in a `Config.swift` would be ideal as it seems to match correctly with `generationOptions`.

```swift
let config = Config(
    .helpers(.git(url: "GitHub.com/some.git", tag: "1.0"))
)
```

or 

```swift
let config = Config(
    .helpers(.local("../helpers")
)
```

After collecting the path for the helpers we can recursively collect the sources listed in the directory and use these files as the helpers. We can simply copy these to the `Tuist/ProjectDescriptionHelpers` directory and (ideally) the rest of the process would remain the same.

Expectations:
- User can set path to helpers (either remote or locally)
- The helpers can import `ProjectDescription`
- When running `tuist edit` the project helpers get correct completion

# Drawbacks

One drawback is that this adds more complexity to Tuist and to the `Config`. However, I'd say allowing this flexibility is worth it. We can even extend this further to allow a list of locations so these could act as plugins of some sort.

A drawback of copying the listed sources to `Tuist/ProjectDescriptionHelpers` is that this may not be as expected as copying them to `Derived`. However, being newt to the source code im not sure how much harder it would be to move these to `Derived`.

## Alternatives

We don't allow this and instead require users to find some other way of doing this, such as:
- Use a git submodule of some sort and having it live in the `Tuist/ProjectDescriptionHelpers` directory.
- Copying and pasting?

# Adoption strategy

This is strictly an additive change (minus maybe having to load `Config` before the project helpers, not sure if this is breaking). 

# How we teach this

This (to me) felt like a feature I expected to be available from the start so I believe adding some extra documentation and some callouts is enough to get this feature into developers hands.

By keeping it simple with the requirement that these are remote or local paths to a directory of swift files we can more easily teach to developers.

# Unresolved questions

- What requirements should we set to the files that are helpers? Are they only allowed to import `Foundation` and `ProjectDescriptionHelpers`
- Do we have any tooling for downloading and copying files from a git remote?

**Comment by luispadron** [comment]
✋🏼 I could contribute this feature if I could get some help with the unresolved questions.

**Comment by luispadron** [comment]
Updated RFC to include the `git` approach for cloning files as this would be a basic requirement of the initial implementation.

**Comment by fortmarek** [comment]
Thanks for writing up this proposal and for volunteering to implement this - we would love to leverage that at our company 😏 

Anyways, here are some of my notes:

> A drawback of copying the listed sources to Tuist/ProjectDescriptionHelpers is that this may not be as expected as copying them to Derived. However, being newt to the source code im not sure how much harder it would be to move these to Derived.

I belive it's better to add them to `Tuist/Derived` or `Tuist/ProjectDescriptionHelpers/Derived` directory - it should be fairly easy. To make sure users don't make changes in them, we can also try to lock those files - similarly to what cocoapods does when you try to edit some file from a Pod in the current workspace. Additionaly, I'd add that directory to `.gitignore` when initializing the project with tuist.

> I believe that defining this in a Config.swift would be ideal as it seems to match correctly with generationOptions.

I agree 👍  -> I just would add it as its own property and not to `generationOptions` directly as I think it's a little bit different. Evaluating `Config.swift` before `tuist edit` should not be a breaking change - you'll just have to add that bit of logic 🙂 

> What requirements should we set to the files that are helpers? Are they only allowed to import Foundation and ProjectDescriptionHelpers

I wouldn't impose any restrictions - whatever compiles is fine with us, I think - I don't even know how we'd want to impose those restrictions, actually.

> Do we have any tooling for downloading and copying files from a git remote?

I don't think so, but we will need a `GitController` for a different PR, too, so feel free to create one -> it can simply copy the git interface, that means something like: 

```swift
protocol GitControlling {
   func clone(url: URL) throws
}

final class GitController: GitControlling {
  func clone(url: URL) throws {
     System.shared.run("git", "clone", url.absoluteString)
  }
}
```

Feel free to ping me on Slack if you want any help with the implementation, I'd gladly help you out and give you some pointers 🙂

**Comment by luispadron** [comment]
@fortmarek Thanks for the suggestions these are helpful! Ive started an in progress pr at #2026.

**Comment by fortmarek** [comment]
Great! Ping me there when you want me to look at it, again thanks for doing this, @luispadron 👏
