### ISSUE TITLE
Missing required module 'XXX' when running unit tests with cached dependencies

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#2023]
**Describe the bug**

Running unit tests via `tuist test` command can lead to missing required module 'XXX' when some of the dependent targets are present in the local cache.

The issue might relate to a bug mentioned in [[META] Cache issues & improvements](https://github.com/tuist/tuist/issues/1975):

> ... using tuist focus may lead to an incorrect project generation when some of the dependent targets are present in the local cache.

**To Reproduce**

In order to make the reproduction of a bug easier, I prepared a demo project: 
* [demo.zip](https://github.com/tuist/tuist/files/5523617/demo.zip)

The project consists of:

* `FrameworkA` - no depdendencies
* `FrameworkB` - links `FrameworkA`
* `FrameworkC` - links `FrameworkB`
* `Demo` - main application, links `FrameworkC`

Preconditions:

* clean derived data folder
* `tuist clean`

Steps:

1. Go to Projects/Demo and warm up the cache:

```bash
$ cd Projects/Demo
$ tuist cache warm
```

2. Clean `DerivedData` folder
3. Go to `FrameworkC` project and run the unit tests via:

```
$ cd ../Projects/FrameworkC
$ tuist generate
$ tuist focus FrameworkC -n // <--- to leverage the cached dependencies
$ tuist test FrameworkC -d "iPhone 11 Pro" -o "14.0" --verbose
```

* full logs: [logs.log](https://github.com/tuist/tuist/files/5530252/logs.log)

```
The 'xcodebuild' command exited with error code 65 and message:
Testing failed:
	Missing required module 'FrameworkA'
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	CompileSwift normal x86_64 ~/Desktop/demo/Projects/FrameworkC/Sources/FrameworkC.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Expected behavior**

I'd expect to get unit tests running successfully. 

**Desktop**

- macOS 10.15.7, Xcode 12.0.1
- `Tuist` version 1.23.0

**Additional context**

Step 2 (cleaning derived data folder) is critical here. If we didn't remove `DerivedData` folder and followed the other repro steps, unit tests would run successfully.  

The reproduce steps can be quite common scenario on CI:

* extract cached dependencies for a project
* clean derived data
* run selective unit tests (only for the target that chagned)

**Comment by pepibumur** [comment]
Thanks for reporting this @mollyIV. We'll look into it.

**Comment by mollyIV** [comment]
I tried `Tuist` version `1.24.0` and got the same bug. I also tried to replace the last steps from steps to repro, `tuist test` command, with `tuist build` and a bit more context from an error message:

```
❯ FrameworkC tuist build
Building scheme FrameworkC
❌ error: The linked framework 'FrameworkB.framework' is missing one or more architectures required by this target: arm64. (in target 'FrameworkC' from project 'FrameworkC')
The 'xcodebuild' command exited with error code 65 and message:
** BUILD FAILED **
```

Please let me know if you have problems with reproduction, or there's anything I can help with :bow:

**Comment by pepibumur** [comment]
@mollyIV cached frameworks are built for the simulator architecture. Are you trying to run the app on a real device?

**Comment by mollyIV** [comment]
👋 @pepibumur , 

No, I am not. I am just trying to run the unit tests 😉 In the test command I specify a device and os type:

```
$ tuist test FrameworkC -d "iPhone 11 Pro" -o "14.0" --verbose
```

When I provided a simulator identifier as a device type, I got an error with the following list of available devices:

```
Could not find a suitable device for iOS, device name 7CAC895A-CF5F-4F7B-9C00-174FD1646C36. Did find Apple Watch Series 4 - 40mm (watchOS 7.0), Apple Watch Series 4 - 44mm (watchOS 7.0), Apple Watch Series 5 - 40mm (watchOS 7.0), Apple Watch Series 5 - 44mm (watchOS 7.0), Apple Watch Series 6 - 40mm (watchOS 7.0), Apple Watch Series 6 - 44mm (watchOS 7.0), iPhone 8 (iOS 13.0), iPhone 8 Plus (iOS 13.0), iPhone Xs Max (iOS 13.0), iPhone Xʀ (iOS 13.0), iPhone 11 (iOS 13.0), iPhone 11 Pro (iOS 13.0), iPhone 11 Pro Max (iOS 13.0), iPad Pro (9.7-inch) (iOS 13.0), iPad Pro (11-inch) (iOS 13.0), iPad Pro (12.9-inch) (3rd generation) (iOS 13.0), iPad Air (3rd generation) (iOS 13.0), iPhone 8 (iOS 14.0), iPhone 8 Plus (iOS 14.0), iPhone 11 (iOS 14.0), iPhone 11 Pro (iOS 14.0), iPhone 11 Pro Max (iOS 14.0), iPhone SE (2nd generation) (iOS 14.0), iPod touch (7th generation) (iOS 14.0), iPad Pro (9.7-inch) (iOS 14.0), iPad (7th generation) (iOS 14.0), iPad Pro (11-inch) (2nd generation) (iOS 14.0), iPad Pro (12.9-inch) (4th generation) (iOS 14.0), iPad Air (3rd generation) (iOS 14.0), iPad (8th generation) (iOS 14.0), iPad Air (4th generation) (iOS 14.0), iPhone 8 (iOS 13.2), iPhone 8 Plus (iOS 13.2), iPhone Xs 13.2 (iOS 13.2), iPhone 11 (iOS 13.2), iPhone 11 Pro (iOS 13.2), iPhone 11 Pro Max (iOS 13.2), iPad Pro (9.7-inch) (iOS 13.2), iPad (7th generation) (iOS 13.2), iPad Pro (11-inch) (iOS 13.2), iPad Pro (12.9-inch) (3rd generation) (iOS 13.2), iPad Air (3rd generation) (iOS 13.2), iPhone 8 (iOS 13.1), iPhone 8 Plus (iOS 13.1), iPhone 11 (iOS 13.1), iPhone 11 Pro (iOS 13.1), iPhone 11 Pro Max (iOS 13.1), iPad Pro (9.7-inch) (iOS 13.1), iPad Pro (11-inch) (iOS 13.1), iPad Pro (12.9-inch) (3rd generation) (iOS 13.1), iPad Air (3rd generation) (iOS 13.1), Apple TV (tvOS 14.0), Apple TV 4K (tvOS 14.0), Apple TV 4K (at 1080p) (tvOS 14.0)
```

**Comment by pepibumur** [comment]
Interesting, for some reason it's trying to build for the device architecture and it can't link the framework because it's been cached for simulator. Would you mind trying to run the same command with `--verbose`. I'm curious to see the underlying `xcodebuild` command that we run _(hide any sensitive data)_

**Comment by mollyIV** [comment]
Sure, I attached the full logs to the ticket description: https://github.com/tuist/tuist/files/5530252/logs.log.
