### ISSUE TITLE
App id does not correspond to xcconfig PRODUCT_BUNDLE_IDENTIFIER

### ISSUE THREAD

**Issue by leszko11** [tuist/tuist#2027]
**Describe the bug**
`tuist generate` command fails when project uses Tuist Signing and xcconfig files with `PRODUCT_BUNDLE_IDENTIFIER` property specified

**To Reproduce**

1. Provide provisioning profiles and certificates under `Tuist/Signing` directory
2. Provide xcconfig file with `PRODUCT_BUNDLE_IDENTIFIER` property
3. run `tuist generate` command

tuist fails with error

`App id TEAM_ID.BUNDLE_IDENTIFIER does not correspond to TEAM_ID.$(PRODUCT_BUNDLE_IDENTIFIER). Make sure the provisioning profile has been added to the right target.`

**Expected behavior**

It will be great if tuist will be capable of using Bundle Id declared in xcconfig file

**Desktop (please complete the following information):**

- OS: macOS
- Version 1.22

**Comment by fortmarek** [comment]
Hi @leszko11!

The problem stems from [this](https://github.com/tuist/tuist/blob/main/Sources/TuistSigning/Linter/SigningLinter.swift#L36) line -> the `bundleId` in your case is not resolved unfortunately and thus does not correspond to the bundle id of the provisioning profile.

We can either:
- do not lint the `bundleId` if we recognize that it's something derived from build settings
- resolve build settings and see what the value of the property is - we could do this as this is run as a post generation action (in `SigningInteractor`). 

Resolving build settings comes with a set of side effects I am not sure we'd want to run during generation - I'd be inclined to choose the first option. Would you like to take a stab at this, @leszko11? I can give you some additional pointers if you wanted to take this on 🙂

**Comment by leszko11** [comment]
Thanks for your response @fortmarek!

I did some debugging while reporting this issue and I also think the first option sounds more reasonable.

I'm on it! :)

**Comment by fortmarek** [comment]
Awesome! Let me know if you need any help ❤️
