### ISSUE TITLE
Allow optional paths in Target sources

### ISSUE THREAD

**Issue by ferologics** [tuist/tuist#2055]
## Need/problem

Defining optional directories for source files.

## Motivation

I have one function that makes a framework target. I use it to generate multiple targets. Some of the targets have different folder structure. Tuist should be able to tell if the directory exists or not. If not then it should not complain that it does not exist, rather it should skip the directory.

## Detailed design

Path could have a property "isOptional" that would be read and if true it would be used to check whether the sources at that path should be included or not. If no files reside within this path then it is skipped.

There seems to be some existing support for path resolution so maybe we could amend it? The `resolve(path: Path)` function inside `GeneratorPaths` already throws an error if it fails to resolve root. There could be a `PathDirectoryResolving` dependency passed down and it could throw an error / check if path exists. Maybe returning an optional AbsolutePath instead of throwing an error could be compactMapped on and only the valid paths are generated from.

# Drawbacks

Why should we *not* do this? Please consider:
- It may be a bad practice to define optional paths because targets should be specific and not generic?
- I may be misusing Tuist and need to learn more about it's advanced Templating features that would eliminate my problem?
- Could have an impact on project generation complexity? Generating a project could take more?

## Alternatives

Hardcode all of my target paths. In which case I might as well use an xcode project instead 🤦 

# Adoption strategy

I think that this is an API additive change.

# How we teach this

We document it in the Path documentation.

How should this feature be taught to existing Tuist developers?

Let them use Tuist more.

# Unresolved questions

Most of the parts are just ideas after skimming source for 5 min so I expect that the proposed design to change significantly from my naive approach.

**Comment by kwridan** [comment]
hi @ferologics , thanks for raising this and the nice write up!

Mind sharing a few examples of the use case you're trying to solve for to help us better understand it?

A few initial thoughts:

> It may be a bad practice to define optional paths because targets should be specific and not generic

Indeed, you'll need to balance consistency between your targets vs. some flexibility and inconsistency. This of course will depend on your use case _(some projects may be easy to re-arrange in one go, some others may be harder at first and require incremental updates over time)_

That said, there is already a lot of flexibility available today which may solve the issues you are facing.

For example, if all your targets have sources within a `Sources` directory, then this general glob pattern should cater for all cases and there shouldn't be a need to specify optional paths:

```swift
Target(
   // ...,
   sources: [
      "Sources/**"
   ]
)
```

In the case you have different requirements for different targets, you could always create new helper methods for the different types while maintaining consistency for each of those target types.

e.g.

```swift
func mocksFramework(name: String) -> Target {
  Target(
      // ..
      sources: [
          "Mocks/**",
      ]
  )
}
```

And in the case where that is not possible, you can always manually specify the paths on a case by case basis too _(with or without the helper methods)_:

```swift
func framework(name: String, sources: [Path]) -> Target {
  Target(
      // ..
      sources: sources
  )
}
```

> Hardcode all of my target paths. In which case I might as well use an xcode project instead

Hopefully should not come to that 😅.

Hope this helps!

**Comment by ferologics** [comment]
My original use case was to support the following framework `Sources` structure:
```
Targets/Fonts/
├── Sources
├── Generated
├── Templates
└── Tests
```

For that I had to put `stub.swift` inside `Generated` folders where no files would be generated yet. I had to do the same for `Templates` with `stub.stencil`. As you can guess, the whole topic was initiated by the needed to generate some swift files using Sourcery.

As you rightly point out; 'optional' source files can nested inside the `Sources/**`. Instead of having a `stub.swift` in folders outside of `Sources` folder I can just put empty folders in `Sources`. This is my current target source file structure:

```
Targets/Fonts/Sources/
├── API
├── Generated
└── Templates
```

I think it makes sense to group all of the source files within `Sources`. I think your suggestion for file structure resolves my issue thus - unless you think that there's more to dig into here - we can close the RFC.

**Comment by kwridan** [comment]
Glad to hear you were able to resolve the issue you were facing, we can can close this.
