### ISSUE TITLE
AppStore 

### ISSUE THREAD

**Issue by azoo61** [tuist/tuist#2078]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**

**Comment by fortmarek** [comment]
Hi @azoo61! I am not sure if this was done by a mistake, but I don't see a bug being reported here -> closing this 🙂 feel free to reopen or create a new issue with more information
