### ISSUE TITLE
Add a carthage TargetDependency

### ISSUE THREAD

**Issue by ferologics** [tuist/tuist#2102]
## Need/problem

Specifying the full path of the framework to Carthage build folder via `.framework(path: "Carthage/Build/platform/some.framework"` is cumbersome.

## Motivation

Using Carthage dependencies in Tuist should be easier than using the `framework` with path.

## Detailed design

Implementation:
```swift
public extension TargetDependency {
    /// Helper function that maps a Carthage framework name to its target dependency framework path
    static func carthage(name: String, platform: Platform = .iOS) -> TargetDependency {
        .framework(path: Path("Carthage/Build/\(platform.rawValue)/\(name).framework"))
    }
}
```
Usage:
```swift
let project = Project.app(name: "SevenHeaven", dependencies: .carthage(name: "Realm"))
```

# Drawbacks

Users could have a different `Carthage/Build/{platform}/{name}.framework` path for Carthage?

## Alternatives

Using this in my project locally.

# Adoption strategy

Easy peasy.

# How we teach this

Update the TargetDependency documentation to include this.

**Comment by pepibumur** [comment]
Hey @ferologics! Thanks for bringing this up. Although I think it's a good idea, I think your need is already being addressed by the project @facumenzella and @laxmorek are working on to provide an API for dependencies. The long story short version of what they are doing is that there'll be a `Dependencies.swift` file under the `/Tuist` directory, and you'll be able to declare your third-party dependencies:

```swift
let dependencies = Dependencies([
  .carthage(....)
])
```
And there'll be an API for fetching and updating them automatically for you, `tuist dependencies fetch` & `tuist dependencies update`. The idea is also having support for SPM packages.

That being side, I think we can close this one in favor of that work. What do you think?

**Comment by ferologics** [comment]
Closing in favor of project chimera 🤩
