### ISSUE TITLE
Enable swiftlint

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#212]
**Is your feature request related to a problem? Please describe.**
Running swiftlint on master reveals there are some existing lint issues. 

```
Done linting! Found 116 violations, 32 serious in 142 files.
```

In an effort to keep the code style consistent, re-instating swiftlint will be very helpful.

**Describe the solution you'd like**

- [ ] Do a sweep of fixes to resolve all flagged issues on master
- [ ] Investigate why the swiftlint step isn't currently running on pull requests

**Additional context**

There is already a [.swiftlint.yml](https://github.com/tuist/tuist/blob/master/.swiftlint.yml) file in the repository and a step in the [Dangerfile](https://github.com/tuist/tuist/blob/master/Dangerfile#L11) so the setup appears to be in place for swiftlint.

**Comment by pepibumur** [comment]
Thanks for bringing this issue up. I'll tackle it if you don't mind. I think now that we start having more contributions, it's important that we all embrace the same code style conventions, for both Ruby and Swift.

**Comment by kwridan** [comment]
Agreed 👍 - thanks for the speedy turnaround!
