### ISSUE TITLE
Tuist build command fails to compile a project with a Carthage dependency on Xcode12 (arm64)

### ISSUE THREAD

**Issue by ferologics** [tuist/tuist#2124]
**Describe the bug**
Since Xcode 12 and iOS 13 the arm64 arch needs to be excluded - https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

If you run `tuist build Xcode12` it internally produces the following command:
```
xcodebuild clean build -scheme Xcode12 -workspace Xcode12.xcworkspace -sdk iphonesimulator
```

In theory the framework produced by carthage should work fine according to the [workaround](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md).

**To Reproduce**

1. Download [Xcode12.zip](https://github.com/tuist/tuist/files/5654832/Xcode12.zip)
2. Run `tuist up` (optional)
3. Run `tuist generate` (optional)
4. Run `tuist build`

**Expected behavior**
Tuist builds the project.

**Screenshots**
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/5576161/101395250-f5e5eb80-38c9-11eb-8a76-033a95856a31.png">

**Desktop (please complete the following information):**

- OS: `macOS 11.1 Beta (20C5048k)`
- Version: `1.26.0`

**Comment by ferologics** [comment]
@tuist/core

**Comment by ferologics** [comment]
Also note that Carthage is moving to `XCFrameworks`. See https://github.com/Carthage/Carthage/pull/3071

**Comment by laxmorek** [comment]
I had similar issue. To fix it I excluded `arm` architectures for simulators using `BuildSettings`.

My project supports iOS and tvOS so I excluded architectures for both platforms. You can adjust this solution for you needs.

**The fix:**  

1. Under `Tuist/ProjectDescriptionHelpers` directory I created  `BuildSettings.swift`

```swift
import ProjectDescription

public typealias BuildSettingDictionary = [BuildSettings: SettingValue]

public enum BuildSettings: String {
    case bridgingHeader = "SWIFT_OBJC_BRIDGING_HEADER"
    case excludedArchs_iOSSimulator = "EXCLUDED_ARCHS[sdk=iphonesimulator*]"
    case excludedArchs_tvOSSimulator = "EXCLUDED_ARCHS[sdk=appletvsimulator*]"
}

public extension BuildSettingDictionary {
    static func buildBaseBuildSettingsDictionary() -> BuildSettingDictionary {
        [
            .excludedArchs_iOSSimulator: .init(stringLiteral: Constants.excludedArchitecture),
            .excludedArchs_tvOSSimulator: .init(stringLiteral: Constants.excludedArchitecture),
        ]
    }
}
```

where `Constants.excludedArchitecture`:

```swift
static let excludedArchitecture = "arm64 arm64e armv7 armv7s armv6 armv8 i386"
```

2. I defined `ProjectDescription.Settings`

```swift
Settings(
    base: Dictionary(uniqueKeysWithValues: BuildSettingDictionary.buildBaseBuildSettingsDictionary().map { ($0.0.rawValue, $0.1) })
)
```

3. And I used these build settings in `ProjectDescription.Settings .Target` definitions

```swift
Target(
    name: "Foo",
    //
    //
    //
    settings: buildSettings
)
```

**Comment by ferologics** [comment]
Right on money @laxmorek! I added your build settings to all targets and now the `tuist build` command compiles 🚀

**Comment by laxmorek** [comment]
I am closing this issue then. 🙂
