### ISSUE TITLE
Support for using playgrounds?

### ISSUE THREAD

**Issue by subdigital** [tuist/tuist#2130]
I'm just getting familiar with Tuist, so it's entirely possible that I'm missing something...

I added a Playground to a project so I could iterate quickly on some UI code. Then I ran `tuist focus <UITarget>` again and it regenerated the project, but this time the Playground was removed and replaced with a Folder reference with `Contents.swift` inside of it.

A) Can I work around this by telling the `Project.swift` file about it?
B) should `tuist` be aware of .playground folders and handle this automatically? If so, maybe this is a good starter issue?

**Comment by kwridan** [comment]
Hi @subdigital thanks for raising this.

Playgrounds are supported, there are currently two options you could follow to add them to your projects.

**1) Implicitly **

This could be better documented (another good starter issue), Tuist automatically scans for a directory called `Playgrounds` at the root of the project and automatically adds its contents to the project.

e.g. see [this fixture](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_tests)

**2) Explicitly**

The option above may not be feasible or desirable in all cases (as it will depend on your project structure), you can manually specify playgrounds to be added to the project via leveraging `additionalFiles` within your `Project.swift`

e.g.

```swift
let project = Project(
 // ...
 additionalFiles: [
    "MyPlaygrounds/**/*.playground"
 ]
)
```

You do raise an interesting point, should the `Playgrounds` files be mixed in your sources, indeed they will accidentally get picked up and add to your targets which isn't desirable. 

To mitigate this there are few further options:
- The simplest is move the playgrounds to a separate directory not within sources of a specific target and using using `additionalFiles` to specify their location
- You could experiment with using exclude patterns when specifying sources (though this could get quite messy)

e.g.

```swift
Target(
   sources: [
       SourceFileGlob("Sources/**", excluding: "Sources/MyComponent/Playgrounds/**"),
    ],
)
```

Hope this helps!

**Comment by pepibumur** [comment]
This made me think that we can provide a more expressive API for users. Maybe something along the lines of:

```swift
let target = Target(playgrounds: "Playgrounds")
```

The problem with the implicit approach is that it's hard for developers to discover. If we make it part of the API Xcode's autocompletion will hint them that there's a `playgrounds` argument that they can use. What do you think?

Also, I think we could just the logic that unfolds glob wildcards to discard any playgrounds from the list.

**Comment by subdigital** [comment]
> Also, I think we could just the logic that unfolds glob wildcards to discard any playgrounds from the list.

+1 on this, I think this could probably be handled automatically. While I'm working in a focused target I am free to add Swift files, etc... but adding a playground means I have to go back and modify the manifest, which is some added friction.

I like the idea of adding an explicit playgrounds API, which would aid in discovery. Would this mean a separate (framework) target with playgrounds in them, or just an additional section for discovering and adding playgrounds properly to an existing target?

**Comment by subdigital** [comment]
I suppose as a _user_ of tuist the distinction doesn't matter much to me, but it should probably match what Xcode does conceptually. 

The important bit, for me, is to make sure that I have the freedom to create playgrounds in my targets so that I can easily experiment and iterate on ideas.

Consider this setup for instance:

```
 AppUI  ⬅ AppUI Tests
    ⬆
AppTarget ⬅  AppTests
     ⬇              
  MyAppKit ⬅  MyAppKitTests
```

In this scenario I'd like to have a playground in the UI Tests target so that I could quickly build and view/interact with components without having to build any of the other targets.

For me this seems like one of the benefits of modularization, so that you can work on small pieces without needing to build the whole.

**Comment by pepibumur** [comment]
In that case, I think the solution that I'm proposing is not ideal. If you add a playground and your `Target` instance doesn't have playgrounds configured the next time the project is focused the playgrounds will disappear. 

Do you usually add those playgrounds close to the source files? I'm asking because if you have let's say a target defined like this:

```swift
let target = Target(sources: "Sources/**/*")
```

If you add a Playground under that `Sources/` directory, we could detect that the file is a playground and add it as such. However, if your glob wildcard is something like `Sources/**/*.swift` that won't' work. 

We can extend the current logic to work like that, but developers might get unexpected results if their glob pattern doesn't match playgrounds in subdirectories.

**Comment by subdigital** [comment]
I wish I could add the playground directly next to the code I want to exercise, but unfortunately Xcode requires that it be in an imported framework.

In a new project you could probably guide people into putting the playgrounds into known directories, but so far it seems tuist is pretty flexible in terms of what your conventions are.

I think it _could_ be smart enough to figure out that a *.swift file was actually inside of a Foo.playground folder and ignore it (treating only the parent folder as an additional file reference in the target.

I haven't looked the code that generates the target yet, but I imagine it would be possible to write a function `isInsidePlaygroundPath(_ file: String) -> Bool` given one of the full file paths.

**Comment by pepibumur** [comment]
> I think it could be smart enough to figure out that a *.swift file was actually inside of a Foo.playground folder and ignore it (treating only the parent folder as an additional file reference in the target.

I like this idea! I'll play with it and ping you once I have the PR.

**Comment by subdigital** [comment]
😄 let me know if I can help in any way. I'm eager to see the PR though, I peeked around the code a bit and had no idea where to even look to begin. 🙏  Thanks!

**Comment by pepibumur** [comment]
[Here](https://github.com/tuist/tuist/pull/2132) you go! I'll add some comments there that can help you understand how the generation workflow works. I'll also update the documentation to make it clear for users that Playgrounds are sources too.

**Comment by pepibumur** [comment]
@all-contributors add @subdigital for idea

**Comment by subdigital** [comment]
😅 too kind :)
