### ISSUE TITLE
Support generate Package.swift ?

### ISSUE THREAD

**Issue by smartrejames** [tuist/tuist#2136]
Thank you so much for creating this great tool, the reason is I'd like to use VSCode instead of Xcode for my main development IDE. I'm using sourcekit-lsp + swift-format + SwiftLint and the experience quite acceptable for me, but sourcekit-lsp requires Package.swift to build index cache, I had to convert Project.swift to Package.swift manually. I'm not sure if there is any other way to do it.

**Comment by danyf90** [comment]
This is currently not possible and there is no plan to support this (as they are not even feature equivalent).

You might be able to do some scripting using the output of `swift dump` which prints the project in JSON format

**Comment by haifengkao** [comment]
I think it can be done as a tuist task plugin.

**Comment by danyf90** [comment]
> I think it can be done as a tuist task plugin.

Yes you can, at least for simple scenarios. If you want to try and need help feel free to ask! 🙌

**Comment by haifengkao** [comment]
all done 
https://github.com/haifengkao/PackageSwiftGenerator

@danyf90 `Tuist.graph` returns the dependency of a project in the form of `Target` array, but Package.swift specify the dependency as `Product` of package. If the Product name doesn't match the Target name, the Package.swift cannot be correctly generated. It is also possible that a Product consists multiple Targets. 
For now, I have to hardcode the mapping between Product name and Target name to workaround this issue. 

To resolve this issue,  tuist has to support the dependency to Products of Swift package.

**Comment by danyf90** [comment]
Can you elaborate on what's the problem (possibly on slack)?
Tuist doesn't have the concept of Products, so the generated Package will have 1-1 mapping between product and targets I guess

**Comment by haifengkao** [comment]
For example, https://github.com/SwiftRex/SwiftRex/blob/develop/Package.swift
`CombineRex` is a product, which has two targets ["SwiftRex", "CombineRex"].
Tuist will return dependency `["SwiftRex", "CombineRex"]`,

but Package.swift has to specify the dependency to the product (which is `CombineRex`)
```
.target(name: "Hello",
     dependencies: [.product(name: "CombineRex", package: "SwiftRex")]
)
```

**Comment by haifengkao** [comment]
@danyf90 I found a serious problem --> `Derived/Sources` folder 
Swift package doesn't allow source files to be separated in different folders.
If the tuist project has derived files generated by Tuist plugin, the derived files cannot be included in the swift package. 
Therefore we won't be able to generate a working swift package.
