### ISSUE TITLE
Tuist format

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#2149]
## Context 🕵️‍♀️
@unxavi brought up the idea of having a command that developers can use to format their code. In the same way, they can do `tuist lint code`, they could run `tuist format code`. Under the hood, we'd run [SwiftFormat](https://github.com/nicklockwood/SwiftFormat) passing the right arguments.

## Implementation
Here are some steps we'd need to take to execute this project. I'm providing the steps to ease the contribution for anyone interested in working on it.
- Like we are doing with SwiftLint and SwiftDoc, we can create a [Rake task](https://github.com/tuist/tuist/blob/main/Rakefile#L63) to vendor the SwiftFormat's binary into Tuist.
- We'd need to add a new [command group](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Commands/LintCommand.swift), `FormatCommand`, and a [command](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Commands/Lint/LintCodeCommand.swift), `FormatCodeCommand` and register them in the [CLI](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Commands/TuistCommand.swift#L8)
- Like we do [with linting](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Services/Lint/LintCodeService.swift), we'd add a new service, `FormatCodeService`, that loads the project graph and calls the vendored SwiftFormat with the right arguments.
- Last and not least, we'd need to add a new [page](https://github.com/tuist/tuist/blob/main/website/markdown/docs/commands/linting.mdx) to the documentation, `formatting.mdx`, and reference it from the sidebar [links](https://github.com/tuist/tuist/blob/main/website/markdown/docs/links.mdx).

**Comment by ferologics** [comment]
@pepibumur what do you think of using Apple's [swift-format](https://github.com/apple/swift-format) over nicklockwood's SwiftFormat as "first-class-Swift-ecosystem citizen"? There's some overhead in terms of [matching the Swift versions](https://github.com/apple/swift-format) but maybe worth the consideration? That being said, SwiftFormat certainly has larger community adoption.

**Comment by pepibumur** [comment]
That's a good point. I'm inclined towards using Apple's solutions, however, the way they are using branches to match with Swift versions complicates its usage. We'd need to vendor a binary for each Swift version that we are supporting, which is not ideal. I'll have to give it another thought.

![image](https://user-images.githubusercontent.com/663605/102508912-3857b700-4086-11eb-99e6-a154a1d7842a.jpeg)

**Comment by ferologics** [comment]
For what I know it's possible to use the Github Actions [build matrix](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix) and specify the Xcode version that way:
```
strategy:
      matrix:
        xcode:
          - 11.3
          - 11.7
          - 12
```

**Comment by unxavi** [comment]
Hi,

I've been away for a couple of days, I've been thinking on this and I'm not sure if this is Tuist making more than it should. I don't mean to be disrespectful of course.

But I've been thinking myself if to use SwiftFormat or Swift-Format, and of course there is also autocorrect from SwiftLint, and there is always going to be different choices in different projects and none is wrong. What I mean is that maybe Tuist shouldn't focus on this and let that be a different tool? 

I think I will finally decide to go with Swift-Format by the way, and this is just an opinion of course

**Comment by pepibumur** [comment]
👋 It's good to bring up opinions. The stance we are taking with Tuist is that we are codifying our opinions into Tuist workflows, but not requiring users to follow them. If you take the build command for instance, one could suggest not doing it because Fastlane exists, however, we'd be able to provide optimizations that wouldn't otherwise be possible with Fastlane, like building only the targets affected by the changes.

We might have done a poor job at explaining what Tuist is, but we are evolving it to be a tool that provides optimized and opinionated workflows that leverage project generation.

As I mentioned early, team can opt for other opinions and workflows, but in doing so, they might me missing out on the opportunity of receiving optimizations and improvements.

**Comment by pepibumur** [comment]
We revisited the definition of what Tuist is and this command doesn't align with the project's direction anymore. Tuist's core functionality will gravitate around providing value through the project graph.
