### ISSUE TITLE
tuist and Swift Package Manager

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#215]
I've been thinking about the future of tuist and where it sits when swift package manager matures and offers integration with xcode. Here are my thoughts on the direction that we should take.

1. Swift is clearly the future
2. Swift Package Manager will be the package manager of choice
3. tuist may still be a useful tool for years to come, and even after.
4. We should make an effort to support and adopt swift package manager.

In the context of swift package manager, and looking ahead to the release of swift 5 we can see that the package file has added support for defining the list of supported platforms.

https://github.com/apple/swift-evolution/blob/master/proposals/0236-package-manager-platform-deployment-settings.md

This means there's now support for code-only iOS generated projects inside of swift package manager. Resources are still a work in progress.

https://github.com/abertelrud/swift-evolution/blob/package-manager-resources/proposals/NNNN-package-manager-resources.md

I think tuist we should work to support swift package manager packages directly, introduce a new dependency type.

Would be interested to hear your thoughts @pepibumur @kwridan @marciniwanicki

**Comment by pepibumur** [comment]
This is something I've also been thinking about, sometimes even wondering if Tuist would step into the domain of the Swift Package Manager. I think this is somewhat unlikely but it's good to keep an eye on what Apple is doing.

I think both projects are seeking different goals. On one side Tuist is making easier to configure Xcode projects regardless of its size. It's dealing with things that have traditionally been a pain in the ass, like the linking of dependencies (I'd like to call out here the great work that you have done in that regards). On the other side, the SPM has been focused on facilitating the creation of packages for both, Linux and macOS, and the resolution of all the dependencies the packages depend on.

I believe there's an opportunity here for Tuist, and that is adding support for **external dependencies**. I see the `Project.swift` being able to define external dependencies, that the SPM would resolve, pull, and configure in an Xcode project that we can link against. This is also an opportunity for Apple to step into Tuist's domain by finding a way to integrate the Swift Package Manager dependencies into existing projects. I'd not be surprised if they do it, but it'd be a lot of effort to do it well given all the complex scenarios that they might find in companies projects. In the case of Tuist we have more control on the projects so we could integrate it more reliably.

This is how I picture the integration:

```swift
let project = Project(name: "Whatever", targets: [
  Target(name: "Target", dependencies: [
  .package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", from: "1.0.0")
]])
```

The complexity will lie in merging both, the project and the SPM dependencies tree. I think it'd require a fair amount of work to but it's not impossible.

**Comment by kwridan** [comment]
This is a great idea! There are a few attempts at solving some of the short comings today via additional scripts that leverage Cocoapod's xcodeproj library (e.g. https://www.ralfebert.de/ios-examples/xcode/ios-dependency-management-with-swift-package-manager/)

**Comment by kwridan** [comment]
#394
