### ISSUE TITLE
Redesign the website

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#217]
I'm the aim of shaping Tuist as a product for developers, I think one of the components that requires some love is the website. The website is one of the places where the developer might get to know for the first time about the project. We are not a business that needs to funnel users into buying something, but it's a good opportunity for us to share Tuist's mission and convince developers to give the Tuist a try.

I think the current website is not appealing, nor it's clear what the tool is for. For that reason, I'd like to re-design both its UI and the content. When I think about other open source projects like CocoaPods, Homebrew, or React, there are some visual traits that I can quickly associate to those projects. I think those projects have a visual identity and mission statement that Tuist lacks.

I'm dumping on this issue a draft proposal of the things that I think we should include/take into account for the new website.

## Landing page sections
- Why
  - The goal here is to sell the tool. I think we could include some scenarios where you might consider using the tool. Some ideas: your project is growing in targets and the maintenance became a burden, you don't understand Xcode intricacies and would like someone to take care of that for you...
- Features: What do you get with Tuist?
  - Type-safe project definition
  - Built-in standard commands
  - Easy static and dynamic linking
  - Fewer version control conflicts
- Mission:
  - Why are we building Tuist? What are we aiming for? I think putting a story behind the tool makes the tool more appealing. A few weeks ago I tried to come up with a statement for the mission and this is what I came up with: `Provide a command line tool that makes the interaction with Xcode projects accessible, standard, and convenient at any scale, built on the principles of ease of use and reliability, and powered by Swift in the open.` What do you think?
- Getting started:
  - A few commands that can be executed to install the tool and get it up and running.
- Contributors:
  - Tuist wouldn't exist without the effort that they put into pushing the tool forward. They deserve all deserve a recognition on the website.
- Tuist in production:
  - When we have enough testimonials, we could include them in this section. Developers like to see if there's any other company or project that is already happy with the tool.
- Get involved:
  - Since it's an open source tool, the website is a good place to encourage developers to contribute. We can include a list of resources that they can look at if they are interested in contributing.

## Other website sections
- Blogs: We can use it to announce releases and perhaps blog posts where users of Tuist talk about how they are using it in their projects.
- FAQ: I'm not sure if this is helpful 🤔. I came up with most of the questions in the current FAQ so I'm not sure if they are relevant to the users.

## Links to include
- GitHub organization
- Join Slack
- Spectrum community
- Releases page

## Design inspiration
Here are some website designs that I liked:
- [Rust](https://www.rust-lang.org)
- [Fastlane](https://fastlane.tools)

Is there anything that you'd change or include? Feel free to dump any idea that pops in your head in this issue. cc @marciniwanicki @ollieatkinson @kwridan

**Comment by pepibumur** [comment]
Also I'm curious to know if there's any landing page of a project whose design you like a lot. I'm particularly in love with Rust's.

**Comment by ollieatkinson** [comment]
> Also I'm curious to know if there's any landing page of a project whose design you like a lot. I'm particularly in love with Rust's.

I really like: https://rocket.rs
The thing which draws me to it is the clear way to get involved. "Get Started" or "Learn More".

**Comment by marciniwanicki** [comment]
https://fastlane.tools & https://rocket.rs are awesome! :)

a bit simpler: 
- https://angular.io
- https://arrow-kt.io
- https://akka.io 
- or even something lovely plain like https://kafka.apache.org

Would be nice to a have a short demo video (embedded player) :)

**Comment by pepibumur** [comment]
Thanks for the recommendations ❤️. I'll sketch something and share it with you.

**Comment by kwridan** [comment]
One more :)

I like the video idea, but perhaps some JS & CSS could make that look nicer:

e.g. 

https://codepen.io/anon/pen/daqzKj

**Comment by pepibumur** [comment]
❤️❤️❤️❤️❤️❤️ like that interactive terminal. I'll fit it somewhere in the design.

**Comment by pepibumur** [comment]
Adding another one to the list:
- https://play.pocketcasts.com/
