### ISSUE TITLE
No test coverage whit option enableCodeCoverage and running tuist test

### ISSUE THREAD

**Issue by unxavi** [tuist/tuist#2182]
**Describe the bug**
Lack of coverage when using the **option** **.enableCodeCoverage** on the test targets

**To Reproduce**

1. Create a directory **example** and go to this path
2. Init a new Tuist project` tuist init --platform ios`
3. `tuist edit` and enable `.enableCodeCoverage` on the project options
4. Run `tuist test`
5. Review the test coverage reports, there is no coverage info

**Expected behavior**
**xcresult** should have coverage report

**Screenshots**
![image](https://user-images.githubusercontent.com/3817679/102861774-6cd5c500-4430-11eb-8928-3fef78c8c2a3.png)

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.1 

**Additional context**
I think the issue is that when the `.enableCodeCoverage` option is enable, it sets the autogenerate schemes with coverage enable for the target itself. If you run the test on a specific non test scheme, example **ExampleUI** or **ExampleKit** then the coverage is collected.

**tuist test** run the test targets, which they have enable codeCoverage but has set the target to collect to it self

![image](https://user-images.githubusercontent.com/3817679/102862261-1c129c00-4431-11eb-885c-6d14ce5c50c7.png)

I think (I could be wrong, I've many time without making iOS development) that the target define on **Targets** should be **ExampleUI** instead of **ExampleUITests**

**Comment by adellibovi** [comment]
Shouldn't the default behaviour be that if we enable code coverage we gather coverage for all targets? It would also fix this edge case. Was there a specific reason to limit it? cc: @kwridan
