### ISSUE TITLE
Choose a path for the test xcresult when running tuist test

### ISSUE THREAD

**Issue by unxavi** [tuist/tuist#2186]
## Need/problem

Some code analysis tools, for example SonarQube/Sonarcloud ask you to convert the files xcresult to their format before send them to the server for analysis.

## Motivation

xcresult files and stored under xcode DerivedData which on a CI server this directory changes all the time. If we could set a path where to export the results, could be easer for the developer to them extract them and do whatever we need with them, like when the command `xcodebuild` is run, we can setup an argument  **derivedDataPath**

We could probably do something with the  **find** command on the CI, but I think it's not ideal

## Detailed design

When running `tuist test` we should have an argument that accepts a path for the logs, I'm not sure if it could be worth for any other tuist command

# Drawbacks

Why should we *not* do this? Please consider:

Non comes to my head

## Alternatives

We could probably do something with the  **find** command on the CI, but I think it's not ideal

# Adoption strategy

If we implement this proposal, how will existing Tuist developers adopt it? Is
this a breaking change?

Is not a breaking change, they will just need to update how they collect logs/coverage data

# How we teach this

Docs should be updated to reflect the new argument

# Unresolved questions

None

**Comment by fortmarek** [comment]
Hi @unxavi!

Sorry for the delayed response.

I think this can be solved in the same fashion as [tuist build](https://github.com/tuist/tuist/issues/2392).

We can do a follow-up PR for `tuist test` after `tuist build` is implemented (maybe @natanrolnik can chime in here if his PR can almost get us there to fix this)
