### ISSUE TITLE
Importing Multi-Platform Packages In Extensions Throwing  Lint Error

### ISSUE THREAD

**Issue by joeblau** [tuist/tuist#2197]
**Describe the bug**

If you import a multi-platform SPM package like [Swift Composable Architecture]() into an extension, the Tuist Linter throws a warning about the package already being linked to another target.

**To Reproduce**

1. Create a project with a cross platform swift package
2. Import the package across multiple targets and particularly make sure you include an extension
3. Run `tuist generate -O`

```swift
import ProjectDescription

let project = Project(name: "Project",
                      packages: [
                        .package(url: "git@github.com:pointfreeco/swift-composable-architecture.git", .upToNextMajor(from: "0.9.0")),
                      ],
                      targets: [
                        Target(name: "Project",
                               platform: .iOS,
                               product: .app,
                               ...
                               dependencies: [
                                .package(product: "ComposableArchitecture"),
                               ])
                        ),
                        Target(name: "ProjectWatchKitApp",
                               platform: .watchOS,
                               product: .watch2App,
                               ...
                               dependencies: [
                                .target(name: "VeloWatchKitExtension"),
                               ])
                        ),
                        Target(name: "ProjectWatchKitExtension",
                               platform: .watchOS,
                               product: .watch2Extension,
                               ...
                               dependencies: [
                                .package(product: "ComposableArchitecture"),
                               ])
                        ),
                      ]
)
```

**Expected behavior**
I would expect the linter to not throw errors. The package is compatible with both watchOS and iOS.

**Screenshots**

![image](https://user-images.githubusercontent.com/1218847/103156208-37e0af80-475b-11eb-835a-17920b91b24b.png)

**Desktop (please complete the following information):**

- CPU: ARM (M1)
- OS: macOS
- Version: 1.28.0

**SAMPLE PROJECT**

Here is a sample project that exhibits this issue: https://github.com/joeblau/tuist-sandbox

**Comment by pepibumur** [comment]
@all-contributors add @joeblau for bug

**Comment by joeblau** [comment]
I attached a sample project

**Comment by kwridan** [comment]
Thanks for flagging this @joeblau - I pushed a PR which should address this issue.
