### ISSUE TITLE
Some documentation adjustments

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#220]
## Context 🕵️‍♀️
As you might know, we currently have two flavours of documentation:
- Documentation for developers working in the project. The documentation is generated automatically from the comments in the code using [jazzy](https://github.com/realm/jazzy). I gets generated when a new version is released.
- Documentation for users of the tool *(also developers)* that are interested in the public interface of the tool: how to use it, what commands are available...

I have the impression that the having the documentation for developers on a website is not that valuable as I thought it'd be *(need to confirm this with people contributing to the project)*. I think it'd be different if the project was a library that developers import into their projects but that's not the case. I find valuable though documenting the things in code so that Xcode shows it to the developers that are dealing with the internal APIs.

In regards to the documentation for users of the tool, I think having it on a different repository makes it a bit inconvenient the process of developing and documenting a feature. It results in two PRs, on the Tuist repository and the other one on the documentation repository.

## What 🌱
I propose the following adjustments:
- Get rid of the Jazzy documentation and update the release steps accordingly.
- Merge the documentation into a `/docs` directory in the Tuist repository and close the other repository.

Thoughts @ollieatkinson / @kwridan / @marciniwanicki ?

**Comment by ollieatkinson** [comment]
> I have the impression that the having the documentation for developers on a website is not that valuable

Agree

> In regards to the documentation for users of the tool, I think having it on a different repository makes it a bit inconvenient the process of developing and documenting a feature.

Yes, looking elsewhere for documentation is always off-putting. I really like what RxSwift do and have markdown files for their usage: https://github.com/ReactiveX/RxSwift/tree/master/Documentation

However, we can improve on that and create a richer README to help guide you to the right documentation piece.

---

> * Get rid of the Jazzy documentation

Would jazzy be removed altogether? or would you still leave the possibility in to generate the locally? I'm actually in favour of not having it at all.

I wrote some thing to spit out the API for my modules, which I've found much more valuable than Jazzy at times. 

Since we are looking at breaking up the tuist lib further it might help us here too. https://github.com/ollieatkinson/Guise

**Comment by pepibumur** [comment]
> However, we can improve on that and create a richer README to help guide you to the right documentation piece.

Agree. Landing on a page with a bunch of markdown files is weird. I'll make sure there's a README that helps the users navigate. 

> Would jazzy be removed altogether? or would you still leave the possibility in to generate the locally? I'm actually in favour of not having it at all.

Not having it at all. It generates HTML from the code documentation which I don't think is useful given that you can check it in Xcode. I'd see the value if the project was a library, but it's not the case.

> I wrote some thing to spit out the API for my modules, which I've found much more valuable than Jazzy at times.

This is very interesting. It's easy to disregard the public API when reviewing code. I've opened [an issue](https://github.com/tuist/tuist/issues/221) to add the tool to the project.
