### ISSUE TITLE
Use Guise to generate the public interface

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#221]
## Context 🕵️‍♀️
As @ollieatkinson pointed out here, Tuist could use [Guise](
https://github.com/tuist/tuist/issues/220#issuecomment-463568524), a tool that he built for his team that generates a public interface from for Swift modules.

## What 🌱
Adding this tool right now wouldn't bring much value because the public interface of the tool is the command line tool. However, after @kwridan & @marciniwanicki finish up with their work on splitting up targets and making them more reusable outside Tuist, it'd be very valuable being able to review the changes in the public API. We could detect things like breaking changes or undocumented elements.

## Proposal 🎉

After [this work is complete](https://github.com/tuist/tuist/issues/205) introduce `Guise` and make sure it runs automatically when the project is compiled. For the latter we might need to wait until the Swift Package Manager allows defining build phases.

**Comment by pepibumur** [comment]
Also, we could detect when the public API changed and send a warning using Danger telling developers to update the documentation.

**Comment by ollieatkinson** [comment]
At the moment Guise relies on the environment variables set by xcodebuild - I need to try figure out how to define what I need just using SwiftPM.

**Comment by pepibumur** [comment]
> At the moment Guise relies on the environment variables set by xcodebuild - I need to try figure out how to define what I need just using SwiftPM.

If I'm not wrong, I think that's something that the Package manifest will support soon.

**Comment by ollieatkinson** [comment]
> If I'm not wrong, I think that's something that the Package manifest will support soon.

I think so, but interestingly enough with the post described here https://swift.org/blog/5-1-release-process/ mentions the inclusion of a new `.swiftinterface` file.

Would need to see it in action but it might make Guise redundant. I will update this thread once I've had chance to review it.

**Comment by pepibumur** [comment]
> Would need to see it in action but it might make Guise redundant. I will update this thread once I've had chance to review it.

Awesome! Let's keep our eyes on that progress.

**Comment by marciniwanicki** [comment]
Nice idea! btw is the link to Guise in the description incorrect? Should it point to https://github.com/ollieatkinson/Guise ?
