### ISSUE TITLE
How to run tuist locally?

### ISSUE THREAD

**Issue by RomanPodymov** [tuist/tuist#2217]
## Context 🕵️‍♀️

I added some custom features to my tuist's fork. But I cannot test them.

## What 🌱

I opened Package.swift in Xcode 12.3 and then run tuist with `init --platform ios`. Getting error **The 'swiftc' command exited with error code 255 and message: JIT session error: Symbols not found**.

## Proposal 🎉

As for me users should be able to run tuist locally. Or how can I do it?

**Comment by laxmorek** [comment]
Hey @RomanPodymov 👋

Have you seen [this](https://tuist.io/docs/contribution/getting-started/#run-tuist-from-xcode)?

**Comment by RomanPodymov** [comment]
Hello @laxmorek 
Many thanks.
