### ISSUE TITLE
Disable project's `use base internationalization` option

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#2219]
**Describe the bug**
Is it possible to disable `use base internationalization` project's config?

**Comment by kwridan** [comment]
Hi @rowwingman thanks for flagging this - currently there isn't an option to do so I'm afraid. 

It was added a while back https://github.com/tuist/tuist/issues/995 to ensure generated projects followed Xcode's recommended defaults - are there cases where it isn't required and doesn't generate a warning?

**Comment by rowwingman** [comment]
For example, you don't use base language. In my case I provide an option to change language inside app, so it's not convent to use base in this case, that's why base is always is empty.

**Comment by pepibumur** [comment]
Ups sorry

**Comment by rowwingman** [comment]
@kwridan @pepibumur What do you think If I add use Base in the Config.swift file by adding new option `.useBaseInternationalization`, and remove Base from default?

**Comment by kwridan** [comment]
> @kwridan @pepibumur What do you think If I add use Base in the Config.swift file by adding new option .useBaseInternationalization, and remove Base from default?

Perhaps we can do the inverse, keep the defaults as they are to avoid breaking changes for existing projects and introduce a generation option to specify the default regions at the project level.

e.g.

```swift
Project(
  // ...
  generationOptions: [
      .defaultRegions(["en", "Base"]) // default if not specified
  ]
)
```

and in your case, you can specify an empty set to remove base:

```swift
Project(
  // ...
  generationOptions: [
      .defaultRegions([])
  ]
)
```

This option would be used to directly control `defaultRegions` on this [line](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift#L151).

Would something like that work?

**Comment by ErikAbele** [comment]
This one can be closed now since there's a `defaultKnownRegions` options which does exactly that.

**Comment by pepicrft** [comment]
Thanks @ErikAbele. Would you update anything in our documentation to make this more obvious for future users?
