### ISSUE TITLE
Localized Strings Can Not Be Shared Across Frameworks

### ISSUE THREAD

**Issue by joeblau** [tuist/tuist#2220]
**Describe the bug**

Currently, Tuist assumes that the String Bundle is based on the name of the Target. This becomes a problem if your target is has localized strings because you can't have 1 consistent name to reference the strings.

**To Reproduce**

1. Clone this repo: https://github.com/joeblau/tuist-sandbox
2. These lines can not be uncommented because the build will fail for one framework or another https://github.com/joeblau/tuist-sandbox/blob/main/Libraries/Shared/Sources/SharedStruct.swift#L19-L20

**Expected behavior**

I would expect a multi platform Framework to be able to reference localized strings consistency.
I want to say `SharedStrings.thisIsASharedString` and have my string reflect correctly in `iOS` and `watchOS`

**Desktop (please complete the following information):**

- OS: macOS Big Sur
- Version Tuist: 1.28.0

**Additional context**

Sample Project: https://github.com/joeblau/tuist-sandbox

**Comment by fortmarek** [comment]
Hi!

I realize this is a delayed response but this will be solved soon via [this](https://github.com/tuist/tuist/pull/2746) PR which will enable you to create your own templates. I agree that tuist's default behavior is awkward for your case but I don't really see how we can accommodate it without fundamentally changing how it works (and subsequently making it worse for other use-cases)

I'll mark this issue to be resolved along with that PR.

Feel free to reopen / write here if you think that custom templates are not the right solution here.

**Comment by joeblau** [comment]
Thanks for responding — I'll take a look at the custom template PR this weekend.
