### ISSUE TITLE
Add support for specifying simulated location when running the app in Debug mode

### ISSUE THREAD

**Issue by marcinreliga-fn** [tuist/tuist#2242]
**Describe the bug**
Currently it's not possible to set predefined simulated location in project description. The only option is to manually select the location in Xcode, by editing the scheme. This action has to be repeated every time after the project has been generated.

Here's the option:
<img width="449" alt="Screen Shot 2020-12-23 at 11 11 03" src="https://user-images.githubusercontent.com/76949651/103534409-184e3300-4e8f-11eb-9eed-2f264a1a635d.png">

**Expected behavior**
After manually editing above option in Xcode, the `.xcscheme` file gets added the following section: 
`<LocationScenarioReference ...></LocationScenarioReference>`, containing the reference to the selected `.gpx` file with simulated location details.

It would be great if this can be defined in `Project.swift` file, so every time the Xcode project and schemes are generated, this predefined simulated location is already set up.

**Additional context**
I noticed that `LocationScenarioReference` is already referenced in https://github.com/tuist/XcodeProj/blob/04e7c3b91f9307a2009718ce6817e7c961545a3b/Sources/XcodeProj/Scheme/XCScheme%2BLaunchAction.swift#L177, but I understand that this is not supported from the `Project.swift` level yet.

**Comment by pepibumur** [comment]
@all-contributors add @marcinreliga-fn for ideas

**Comment by marcinreliga-fn** [comment]
Hey, looks like this issue is already solved by https://github.com/tuist/tuist/pull/2616? 

Thanks a lot!
