### ISSUE TITLE
Add support for enabling/disabling synthesizing interfaces for resources in a per-project basis

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#2249]
## Context 🕵️‍♀️
As @sgrgrsn brought up [here](https://github.com/tuist/tuist/discussions/2248), it'd be useful to allow disabling/enabling the synthesizing of interfaces for resources on a per-project basis.

## What 🌱
We can extend the generation option to support passing a list of projects for which the synthesizing should be disabled/enabled. I think we can deprecate the existing `.disableSynthesizedResourceAccessors` in favor of something along the lines of:

```swift
let config = Config(generationOptions: [.synthesizedResourceAccessors(projects: .all)])
let config = Config(generationOptions: [.synthesizedResourceAccessors(projects: ["A", "B"])])
let config = Config(generationOptions: [.synthesizedResourceAccessors(projects: .except(["A", "B"]))])
```

**Comment by sgrgrsn** [comment]
I was thinking if it would be better to specify the setting when defining the projects in the manifests instead of coupling the `Config.swift` with the actual project names. If we have it as a part of the project descriptions we would also avoid ending up in a situation where the Config enables the synthesizing on a project that no longer exists.
I think the config could then be changed to have the default setting. Something like:

```swift
let config = Config(generationOptions: [.synthesizedResourceAccessorsDefault(true)])
let config = Config(generationOptions: [.synthesizedResourceAccessorsDefault(false)])
```

I hope it makes sense - let me know what you think 👍

**Comment by rstone4-chwy** [comment]
If I wanted to take this on as a first time PR, do you have any suggestions on where to start looking or what you want the final API to look like?

**Comment by fortmarek** [comment]
> I was thinking if it would be better to specify the setting when defining the projects in the manifests instead of coupling the Config.swift with the actual project names

I agree with this

> let config = Config(generationOptions: [.synthesizedResourceAccessorsDefault(true)])

Maybe we could keep `disableSynthesizedResourceAccessors` which would translate to `.synthesizedResourceAccessorsDefault(false)]`? And without this flag it'd default to `.synthesizedResourceAccessorsDefault(true)`.

Did you have @sgrgrsn any specific API for how the `Project` configuration could look like?

On a different note:
Thanks for the interest @rstone4-chwy!

This is, indeed, a good first issue once we decide on the API. Feel free to come up with eg. the `Project` configuration of accessors and we can discuss it more here. Aftewards, I'll be happy to guide you further and give you some leads as to where to look. There are also other good issues for new contributors as this one is not completely ready yet. Feel free to hit me up at slack.tuist.io, too

**Comment by sgrgrsn** [comment]
> Did you have @sgrgrsn any specific API for how the `Project` configuration could look like?

Could it be something like this, @fortmarek?
```swift
Project(
    name: "Project with resources",
    synthesizedResourceAccessors: true
)
```

Or do you think we should have something like the `generationOptions` as in the `Config` structure?

**Comment by fortmarek** [comment]
I believe that makes sense, I agree with this proposal 👍

**Comment by pepibumur** [comment]
I like that this can be defined at a per-project level. I think eventually we should remove those global options in favor of per-project definitions.

**Comment by rstone4-chwy** [comment]
I haven't forgotten about this, just been busy. I'll try to get in the slack tonight and see if I can get a start on how this would be setup.

**Comment by danyf90** [comment]
Fixed in https://github.com/tuist/tuist/pull/3963 getting rid of the `Config.disableSynthesizedResourceAccessors` and adding it as `ProjectDescription.Project.ProjectOption`
