### ISSUE TITLE
tuist graph is not working for homebrew 2.7.0

### ISSUE THREAD

**Issue by JohnnyKei** [tuist/tuist#2300]
**Describe the bug**
`tuist graph` is not working for homebrew 2.7.0.
I could not generate a dependency graph.
The Error was happened below.

```
The 'brew' command exited with error code 1 and message:
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
```

**Expected behavior**
generate a dependency graph image file.

**Desktop**

- OS: macOS Catalina 10.15.7
- Version: 1.26.0
- homebrew version: 2.7.0

**Comment by pepibumur** [comment]
Thanks for reporting this @JohnnyKei

**Comment by sgrgrsn** [comment]
I'm facing the same issue. I can see @pepibumur marked it as a `good-first-issue`. I would like to look into this if someone could help me out by pointing in the right direction of where to look.

**Comment by pepibumur** [comment]
> I'm facing the same issue. I can see @pepibumur marked it as a good-first-issue. I would like to look into this if someone could help me out by pointing in the right direction of where to look.

Sure! I'd start from [here](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Services/GraphService.swift#L68) notice that there's some logic there to install Graphvz if it's not installed in the system. You might want to add a version check there to ensure we are using the API as expected depending on the version.

**Comment by sgrgrsn** [comment]
Solved in https://github.com/tuist/tuist/pull/2446
