### ISSUE TITLE
StoreKit Configuration file for scheme

### ISSUE THREAD

**Issue by MarvinNazari** [tuist/tuist#2303]
As of Xcode 12, It's possible to use a StoreKit configuration file for a scheme, as of today it's not possible to add this in the Tuist Project config. Is this even possible to add?

You can find it in Edit Scheme -> Options -> StoreKit Configuration.

**Comment by kwridan** [comment]
Hi @MarvinNazari - thanks for raising this.

Indeed at the moment there isn't an option to add this. 

However that's something that can be added, from a cursory look the following is needed to support this:

- Update the manifest scheme types in `ProjectDescription.RunAction` to include a new `Options` property to host the path to the store kit configuration (as well as other future additions from the Options tab)

```swift
struct RunAction {
    // ...
    var options: RunActionOptions?
}

struct RunActionOptions {
    var storeKitConfigurationPath: Path?
}
```

This will allow creating custom schemes that can reference this configuration

- Update the corresponding models in `TuistCore` to copy across the options
- Update the `SchemeDescriptorGenerator` to include `storeKitConfigurationFileReference` to the `XCScheme.LaunchAction` when the store kit option is set
- For convenience, automatically include the referenced storeKitConfiguration file to the Project / Workspace where the scheme is defined as an `additionalFile` so it appears in Xcode's project navigator
- For convenience, add a lint check to ensure the referenced StoreKit Configuration path exists

For reference, this is a PR @pepibumur contributed to add support for diagnostics options which entails a fairly similar set of changes https://github.com/tuist/tuist/pull/1382.

**Comment by bolismauro** [comment]
Hi! I'll give this a shot :)
