### ISSUE TITLE
tuist generate fails with "no such module" when Project+Templates.swift has a compiler error

### ISSUE THREAD

**Issue by AndrewSB** [tuist/tuist#2319]
This might only be on M1 machines (so a follow on from #2082). I'm on the latest release 1.31.0

occasionally, I see an error when running `tuist generate` saying
```
The 'swiftc' command exited with error code 1 and message:
/Users/asb/Developer/apex-ios/Project.swift:2:8: error: no such module 'ProjectDescriptionHelpers'
```

Also, when running `tuist edit` I get an error in the generated project that `ProjectDescriptionHelpers` was not built from apple silicon.

I have a feeling the two are related. how are `ProjectDescriptionHelpers` vended? is that part of what gets unzipped by the tuist installer? or are they built on demand by each project.

**Comment by AndrewSB** [comment]
this might also be user error inside my `Project+Templates`, but I'd like to see a more useful error message than "no such module". what can I do to find the root cause?

**Comment by AndrewSB** [comment]
found it, yes. it was an error inside my `Project+Templates.swift`. Once I fixed the error, I see the remaining (valid) errors:

```
/Users/asb/Developer/apex-ios/Tuist/ProjectDescriptionHelpers/Project+Templates.swift:14:33: error: cannot find 'additionalTargets' in scope
        var localDependencies = additionalTargets.map { $0.name }
                                ^~~~~~~~~~~~~~~~~
/Users/asb/Developer/apex-ios/Tuist/ProjectDescriptionHelpers/Project+Templates.swift:33:31: error: cannot convert value of type '[Target]' to expected argument type '[TargetDependency]'
                dependencies: dependencies)
                              ^
/Users/asb/Developer/apex-ios/Tuist/ProjectDescriptionHelpers/Project+Templates.swift:33:31: note: arguments to generic parameter 'Element' ('Target' and 'TargetDependency') are expected to be equal
                dependencies: dependencies)
```

it confuses me why the syntax error I fixed caused me to get an error saying there was no such module instead of explaining why the module wasn't built

**Comment by pepibumur** [comment]
Hey @AndrewSB. 
As part of the generation process, Tuist compiles all the files inside the `ProjectDescriptionHelpers` directory as part of a module. According to the error, it seems that something in the syntax is not right and that's causing the compilation of the helpers to fail. I assume you can't debug the issue because you can't edit the project on an M1 right? I'll try to investigate that further.

**Comment by AndrewSB** [comment]
I can edit, but the xcodeproj I'm given with the manifests doesn't build.

What I'm doing right now is editing the project, then going back to the terminal, running `tuist generate`, and fixing the errors generate gives me

**Comment by luispadron** [comment]
👋🏼 @AndrewSB @pepibumur 

As far as the editing issues goes, I think it may be because we are excluding `arm64` in the generated project we create for editing: [see here](https://github.com/tuist/tuist/blob/0705ab05053e6df7ffbe9fcf6729dea1622c7ff7/Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift#L302). 

Going to create a branch for you to try, @AndrewSB, since I dont actually have an M1 mac. Check out https://github.com/tuist/tuist/tree/luis/arm64-edit-fix to see if it works. 

```swift
#if arch(x86_64)
let projectSettings = Settings(
    base: [
        "ONLY_ACTIVE_ARCH": "NO",
        "EXCLUDED_ARCHS": "arm64",
    ],
    configurations: Settings.default.configurations,
    defaultSettings: .recommended
)
#else
let projectSettings = Settings(
    base: [],
    configurations: Settings.default.configurations,
    defaultSettings: .recommended
)
#endif
```

**Comment by didix21** [comment]
Any news about this issue? I finding the same problem on my M1 mac,

**Comment by fortmarek** [comment]
This should work with the newest release as it's native on M1 Macs - any ideas here @pepibumur?

**Comment by pepibumur** [comment]
I looked into this further. Here's what I found. We need to adjust the `EXCLUDED_ARCHS` build setting as suggested by @luispadron. I'd change the approach a little bit to do it at runtime. Because we exclude arm64 when buiding for arm64, the helpers don't compile and it fails to link it.

**Comment by pepibumur** [comment]
[This](https://github.com/tuist/tuist/pull/3199) should mitigate the issues when editing projects.

**Comment by kusainovaka** [comment]
Hello, I have same problem, try to change tuist version from 3 to 4
On old version all works
```
error: no such module 'ProjectDescriptionHelpers'
import ProjectDescriptionHelpers
```
 Tuist version 4.20.0, Xcode version 15.4 , Apple M3 Pro

**Comment by fortmarek** [comment]
Hey @kusainovaka 👋 

Would you mind creating a new issue with a reproducible sample or more details as to what you are experiencing? 

Have you reinstalled Tuist as [per the guidelines](https://docs.tuist.io/references/migrations/from-v3-to-v4.html#dropped-version-management-through-tuistenv) when changing the version from 3 to 4?
