### ISSUE TITLE
SPM: Importing A into B & C leads to duplication of library code

### ISSUE THREAD

**Issue by AndrewSB** [tuist/tuist#2322]
hey! as I'm migrating to tuist I'm having issues with my dependencies.

I have the following first party graph

```
   +-----------> Kit  +---------> UI
   |               +              +
App|               |              |
+  |               |              |
|  +--->Lib        |              |
|        +         |              |
|        |         |              |
|        |         |              |
|        |         |              |
|        |         |              |
|        |         v              |
|        +--->                    |
|              Prelude   <--------+
+------------>

```

Prelude & all the other frameworks depend on common 3rd party dependencies, when I include the dependencies in both of the target definitions, I get the following error

`Swift package product 'Starscream' is linked as a static library by 'Kit' and 'Prelude'. This will result in duplication of library code.`

Am I to include them dynamically instead? Or should I omit them from the parent in the graph, and allow the implicit linking through the child? Is there documentation I could have looked up for this instead of creating an issue?

**Comment by AndrewSB** [comment]
reading through https://tuist.io/docs/building-at-scale/microfeatures/, I'm remembering that I probably want to use dynamic frameworks instead of static with my current dependency structure.

1. not sure how to express that in the tuist `Project`/`Target`/`TargetDependency` syntax
2. hoping the added startup cost isn't too bad for switching my ~20 SPM dependencies to be dynamic

**Comment by AndrewSB** [comment]
so I'd expect the `Package` API to have a dynamic option, but I dont see it in https://github.com/tuist/tuist/blob/main/Sources/TuistCore/Models/Package.swift

looking around a little more

**Comment by AndrewSB** [comment]
found https://github.com/tuist/tuist/issues/1820 in the issues, looks like a KP

**Comment by pepibumur** [comment]
Hey @AndrewSB, with SPM it is the packages that define how they should be linked from the app. Tuist doesn't know whether it's static or dynamic and assumes it's static. One way to solve this issue is by wrapping that static package dependency in a framework that can then be linked dynamically from other targets.
There's some work going on to change the integration with SPM to allow changing the type of linking. However, this is still WIP and will take some time until we get there.

**Comment by danyf90** [comment]
Should be solved using Dependencies.swift

**Comment by jinaiyuanbaojie** [comment]
> Should be solved using Dependencies.swift

Hi team. Is it solved?
