### ISSUE TITLE
Failure to link homebrew dependency during `tuist up`

### ISSUE THREAD

**Issue by caipre** [tuist/tuist#2323]
**Describe the bug**
When declaring project dependencies, `.homebrew` packages that are already installed on the system can cause the `tuist up` command to fail. The command [is documented](https://tuist.io/docs/commands/up/#homebrew-packages) as "installs the Homebrew packages if they don't exist in the system." It seems that `brew install` can fail unexpectedly when a symlink for the binary already exists.

The error from `brew` is:

```console
$ /usr/local/bin/brew install swiftlint
==> Downloading https://homebrew.bintray.com/bottles/swiftlint-0.42.0.catalina.bottle.tar.gz
==> Pouring swiftlint-0.42.0.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/swiftlint
Target /usr/local/bin/swiftlint
already exists. You may want to remove it:
  rm '/usr/local/bin/swiftlint'

To force the link and overwrite all conflicting files:
  brew link --overwrite swiftlint

To list all files that would be deleted:
  brew link --overwrite --dry-run swiftlint

Possible conflicting files are:
/usr/local/bin/swiftlint
==> Summary
🍺  /usr/local/Cellar/swiftlint/0.42.0: 6 files, 12.2MB
The '/usr/local/bin/brew' command exited with error code 1
```

**To Reproduce**
I'm not able to reproduce the behavior locally, but it is reproducible in the GitHub actions workflow of my project: https://github.com/caipre/point-free-wg/pull/6/checks?check_run_id=1731887004

**Expected behavior**
The `tuist up` command should not fail when a dependency is already installed.

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.7

**Additional context**
This may have a similar root cause as https://github.com/tuist/tuist/issues/2082 (ie, a permissions error) , but the reported errors are different and I don't believe my workflow is running on an M1 mac. The similarity is in the successful install followed by a failure to link.

**Comment by caipre** [comment]
I was curious about the permissions and found that they should be okay:

```console
$  ls -lad /usr/local/bin
drwxrwxr-x  586 runner  admin  18752 Jan 20 02:48 /usr/local/bin
$  ls -la /usr/local/bin/swiftlint
lrwxr-xr-x  1 runner  admin  40 Dec 13 01:37 /usr/local/bin/swiftlint -> ../Cellar/swiftlint/0.41.0/bin/swiftlint
$  brew list --formula | grep swift
swiftlint
$  whoami
runner
```

https://github.com/caipre/point-free-wg/pull/8/checks?check_run_id=1732143975

**Comment by pepibumur** [comment]
Tuist up is [going away](https://github.com/tuist/tuist/pull/3443) in the next major release 2.0 and therefore I'm closing this issue.
