### ISSUE TITLE
Allow to add resources shared between multiple targets along with specific resources for each one

### ISSUE THREAD

**Issue by wacumov** [tuist/tuist#234]
I have a project with multiple targets. These targets are different iOS and tvOS apps. These apps share most of the code and most of the resources. But every app has some unique resources.

I think that tuist can be very useful in this case. But I am stuck in finding a way to add some resources to all targets and some resources to only one target.

Is there a solution at this stage of tuist development?

If not, probably `resources` parameter in `Target` initializer should become an Array of paths?

This issue addresses sources as well.

**Comment by pepibumur** [comment]
Thanks @wacumov for opening the issue. That's something that is already being [worked on](https://github.com/tuist/tuist/pull/201). Do you think that'll help with the need you have?

**Comment by wacumov** [comment]
Yes, this is exactly what I need. Thanks for the quick response!
