### ISSUE TITLE
Show progress for "cache warm" command

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#2357]
Hi,

I was thinking that it could be good to show a simply progress while executing the "cache warm" command, something as "Building cacheable targets: X out of Y". I personally find it useful when having more then few targets.

This is not really a bug, just wanted to know if this could be an acceptable improvement, if so I would like to move on and open a PR for this :)
What do you think? Otherwise feel free to close this issue 😄

**Comment by fortmarek** [comment]
Hi!

I think you have already taken a step into a direction of this [here](https://github.com/tuist/tuist/pull/2377/files#diff-cb9ccc44ceea934d4613dadcb127d137c6548582f7fcb056b21836fab52bad52R122) 😁 

I wonder if we can make this even more convenient and take inspiration from SPM.
Right now, I don't really like the fact that `tuist cache warm` clutters the whole output and terminal window - I think we could keep replacing only the current line with a number of already cached modules, similarly to what happens when running `swift build`.

I would imagine something like `[2/20] [Module] Compiling File.swift` where `2/20` would mark the number of modules built. 

For this we could use [ProgressAnimation](https://github.com/apple/swift-tools-support-core/blob/32999390a038febc34a412e1f7db5c5456720918/Sources/TSCUtility/ProgressAnimation.swift) from `TSCUtility` which is the exact thing that `swift build` uses under the hood.

What do you think @andreacipriani @RomainBoulay ?

Of course if error occurs, we should show the steps leading up to it - plus I'd keep the behavior as-is when using `--verbose`

**Comment by andreacipriani** [comment]
> Hi!
> 
> I think you have already taken a step into a direction of this [here](https://github.com/tuist/tuist/pull/2377/files#diff-cb9ccc44ceea934d4613dadcb127d137c6548582f7fcb056b21836fab52bad52R122) 😁
> 
> I wonder if we can make this even more convenient and take inspiration from SPM.
> Right now, I don't really like the fact that `tuist cache warm` clutters the whole output and terminal window - I think we could keep replacing only the current line with a number of already cached modules, similarly to what happens when running `swift build`.
> 
> I would imagine something like `[2/20] [Module] Compiling File.swift` where `2/20` would mark the number of modules built.
> 
> For this we could use [ProgressAnimation](https://github.com/apple/swift-tools-support-core/blob/32999390a038febc34a412e1f7db5c5456720918/Sources/TSCUtility/ProgressAnimation.swift) from `TSCUtility` which is the exact thing that `swift build` uses under the hood.
> 
> What do you think @andreacipriani @RomainBoulay ?
> 
> Of course if error occurs, we should show the steps leading up to it - plus I'd keep the behavior as-is when using `--verbose`

+1 from me, the current output was useful while building the feature, for debugging purposes, now that it's starting to work consistently we could cut it out

**Comment by RomainBoulay** [comment]
Hey @fortmarek,

Thanks for proposing new ideas to improve this feature, that's really appreciated!
I'm totally supportive for your idea about adding some sort of progression on the output.

I'm less on board though regarding the idea to only update the last line of the output. To elaborate a bit, I think it's very valuable to let the user know what was found locally, fetched remotely, or build (and potentially uploaded). 

Also, as Andrea mentioned, having a full output would help debugging potential issues. As this feature is still quite new, I would recommend keeping a full output.

That said, I also don't want to decide for everyone, so I'm happy to continue this discussion if you feel like it @fortmarek @andreacipriani?

**Comment by RomainBoulay** [comment]
(sorry @adellibovi, I initially mentioned Marek in my message above... it's my bad, it's too late 😁)

**Comment by adellibovi** [comment]
As far as we show the progress I am fine with both of solution, I already implemented the one that prints together with the full output while developing #2377 (in my tests I had about 100 targets and helped me a lot, specially since I couldn't guess at which point it was the process as no longer sorted alphabetical 😄)

**Comment by fortmarek** [comment]
> I'm less on board though regarding the idea to only update the last line of the output. To elaborate a bit, I think it's very valuable to let the user know what was found locally, fetched remotely, or build (and potentially uploaded).

Sorry, what I had in mind was actually the output from the actually building when not found in cache which is causing the most clutter right now. But this might be for a separate issue as that is not exactly tied to `tuist cache warm`.

I think it should be possible to keep the "progress line" at the last line of the CLI, so it's always easily visible.

**Comment by RomainBoulay** [comment]
Ha sorry @fortmarek, I misunderstood 👍 Your idea sounds good to me!!

I was thinking that, in general, if we wanted to declutter the output, maybe we could split the information between the standard output and a log file(s)?

This way, we could treat the standard output as a UI that may refresh itself to avoid a lengthy output, and also record more detailed information/warnings/errors in log file(s)? What do you all think?  (cc @pepibumur)

**Comment by fortmarek** [comment]
Yeah, log files crossed my mind, too. I think they would be a good solution - especially for the output from `xcodebuild` which is not under our direct control and is quite verbose. We can save the file to eg. `~/.tuist/Logs` and output the location when the command ends.

**Comment by pepibumur** [comment]
> Yeah, log files crossed my mind, too. I think they would be a good solution - especially for the output from xcodebuild which is not under our direct control and is quite verbose. We can save the file to eg. ~/.tuist/Logs and output the location when the command ends.

I like the idea of storing the logs globally. Maybe when starting the build we can print something along the lines of:

```
The build logs will be stored at ~/.tuist/Logs/{random-uuid}.log
```

**Comment by danyf90** [comment]
Now that we build all the targets with a single `xcodebuild` I don't think we have anymore the visibility needed to provide a progress on the build, right @adellibovi ? Do you think we can close this? 🚀

**Comment by adellibovi** [comment]
> Now that we build all the targets with a single `xcodebuild` I don't think we have anymore the visibility needed to provide a progress on the build, right @adellibovi ? Do you think we can close this? 🚀

LGTM, I would close it, also because currently it is way faster then when we opened this issue :)
