### ISSUE TITLE
Use Codable to encode the Manifest models and get rid of the models in TuistKit

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#236]
## Context 🕵️‍♀️
When we set up the encoding logic for the manifest models we followed the SwiftPM approach. They came up with their own approach for encoding the models into a JSON.

Recently, a discussion came up on whether it'd make sense to continue down that path or leverage the Swift `Codable` protocol. Moreover, we pondered the idea of removing duplicities and have the models defined in a single place. That'd ease maintenance but couple Tuist and manifest versions.

Conversely to the SwiftPM that has a more mature API and decouples the versioning of the tool and the manifest, we are not currently decoupling them because it'd add extra overhead while we're iterating on the manifest format. For that reason, I don't think it's worth having the models defined in two different places that map 1 to 1.

At some point in the future when we adhere strictly to semantic versioning. It'll probably make sense to bring the decoupling back together with a way for manifests to define the version they'd like to use *(like the Package.swift indicating the version with a comment at the top)*

## What 🌱
- Get rid of the models from `TuistKit`.
- Add `ProjectDescription` as dependency of `TuistKit`.
- Make the models conform the protocol `Encodable` publicly.
- Extend the models in `TuistKit` to conform the `Decodable` protocol.

@tuist/core

**Comment by ollieatkinson** [comment]
As @kwridan and @pepibumur pointed out on slack, Tuist does not have to use the same approach as SwiftPM when it comes to the Project.swift encode/decode.

Currently the follow is as follows:

```
`ProjectDescription.Project` > json > `TuistKit.Project`
```

We could avoid having the `TuistKit.Project` model and just initialise the model from `ProjectDescription.Project` again making the flow look like:

```
`ProjectDescription.Project` > json > `ProjectDescription.Project`
```

With the `Codable` protocol we could pass a context with the decoder that would contain any information we need to be able to infer.

**Comment by kwridan** [comment]
I'll pushing a PR today with part of the decoupling needed for https://github.com/tuist/tuist/issues/205

**Comment by pepibumur** [comment]
Great work @kwridan. Maintaining the duplicated models was a significant and unnecessary overhead for the project.

**Comment by kwridan** [comment]
I'm debating if the library efforts #205 help or hinder this 😞

The plan is to move most of the models in `TuistKit/Models` to `TuistGenerator/Models` to allow re-using the generator and as such would require having those decoupled models. This way the models can be more flexible without impacting the `ProjectDescription` API exposed to users.

My original suggestion was to reduce the overhead of manually extracting values from json by leveraging `Codable` nature of the `ProjectDescription`. 

e.g. 

`GraphManifestLoader` could be updated to:

```swift
protocol GraphManifestLoading {
    func loadProject(at path: AbsolutePath) throws -> ProjectDescription.Project
    func loadWorkspace(at path: AbsolutePath) throws -> ProjectDescription.Workspace
    // ...
}
```

Sadly there would still be the overhead of mapping models - I pushed a [branch with an example](https://github.com/bloomberg/tuist/blob/feature/236-decodable-manifests/Sources/TuistKit/Generator/GeneratorModelLoader.swift).

**Comment by kwridan** [comment]
#244 eliminates most of the `JSON` conversion, only bit left is for `Up` as it's a class hierarchy we'd need to add some custom decode logic.

**Comment by pepibumur** [comment]
How does it feel to get rid of a lot of boilerplate code?

![giphy](https://user-images.githubusercontent.com/663605/53821768-b52ba680-3f6e-11e9-8110-f21afde92e9c.gif)

**Comment by kwridan** [comment]
ah yes! let me re-open this :)

**Comment by kwridan** [comment]
Re-opening to address migration of the `UP` command
