### ISSUE TITLE
Improve `tuist migration list-targets` by sorting using topological order

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#2381]
Hi,
Currently `tuist migration list-targets` sorts based on the number of dependencies, while this is a very good start, it can be not optimal. In my opinion, now that we have topological sorting as in #2377, we could apply the very same logic for this command.
As this is a breaking change (the order will be different) I wanted to hear your opinions, I think this could replace the default behaviour, yet, if we have good reason about why to maintain the current sorting too, we can add an option.

**Comment by pepibumur** [comment]
Even though it's a breaking change, I don't expect users to have built something that relies on the output format. That being said, I'd go ahead and implement it.
