### ISSUE TITLE
Showing which targets are not cacheable

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#2382]
While talking with @fortmarek, we pointed out that currently we do not show (as info or debug) which targets are not cacheable.
One option would be to simply show a "_The target X is not cacheable. Skipping_" during the `tuist cache warm`.
Potentially if #2357 get implemented, this info would be available under the `--verbose` option.

Does it make sense to show during the `tuist cache warm`, or would it make sense in other command like `tuist cache print-hashes`, or both :)
Thoughts?

**Comment by pepibumur** [comment]
In fact, I was thinking about having a command like:
```
tuist cache graph
```
That shows you a dependency graph like the one that you get with `tuist graph`, but where we use colors to show what targets can be replaced with their pre-compiled versions and which ones not. We can also add a description indicating why they are not cacheable. This would be extremely useful for debugging purposes.

Would you like to give this one a shot @adellibovi ? You can use the existing `tuist graph` command as a reference.

**Comment by adellibovi** [comment]
@pepibumur, sure that could be nice too. A question, in order to understand what you mean, if we have `tuist graph` would we still have the other two options for consistency or not? Or what's your view?

**Comment by pepibumur** [comment]
I was thinking about something along the lines of the diagram below. I think it's easier to debug the caching visually than it is printing logs. You can use the green color to indicate that the target can be replaced with its counterpart from the cache, and the red to indicate that you cannot. 

![image](https://user-images.githubusercontent.com/663605/106006234-48b37680-60b5-11eb-8e08-516da9aed77a.png)

**Comment by robertherdzik** [comment]
Hi, could you explain me please, what are the rules which you use to determine which target is cacheable or not?

**Comment by fortmarek** [comment]
Hey @robertherdzik!

You can find the logic [here](https://github.com/tuist/tuist/blob/main/Sources/TuistCache/ContentHashing/CacheGraphContentHasher.swift). We deem targets of type `.framework`, `.staticFramework`, and `.bundle` as cacheable. A target can also only be cacheable if all of its targets are also cacheable.

**Comment by pepicrft** [comment]
I'm closing this since we are already tracking the improvement elsewhere.
