### ISSUE TITLE
Improve tuist cache to support caching warming of one or more listed targets

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#2384]
Hello 👋 
I was thinking that it could be nice to pre-cache only a small subset of targets, in particular the ones related to the target you want to focus on.
This would avoid having to wait for the whole cache to complete and you could potentially start to work on a single target sooner.
I am thinking in two approaches:
* to change the `tuist focus targetName` to support a `--force-cache` or updating the default behaviour (since we already have the --no-cache to opt out)
* to change the `tuist cache warm` to somehow pass a target.

My personal preference would be something more related to the `tuist focus` as it feels more "easy" to use.
What's your view?

**Comment by pepibumur** [comment]
I'm more inclined towards extending `tuist cache warm` to support passing a list of targets that you'd like to cache:
```
tuist cache MyFramework
```
I think we should then cache this framework and its dependencies. What do you think? This would be a very useful addition.

**Comment by adellibovi** [comment]
Sounds good ;) just a nit, it would be `twist cache warm MyFramework` won't it?

**Comment by pepibumur** [comment]
Right! That's what I meant. I think you can take the existing logic and did a bit of filtering before building :)

**Comment by adellibovi** [comment]
Yeah, implementation should be pretty straight forward having #2377
