### ISSUE TITLE
When running `tuist build`, the result of the build is placed in a "randomly" generated folder inside Xcode derived data folder.

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#2392]
When running `tuist build`, the result of the build is placed in a "randomly" generated folder inside Xcode derived data folder.
Is there a way to know what these folder is?

For example:
- `xcodebuild` allows to pass a `-derivedDataPath` argument to specify the output folder
- `swift build` from SPM allows to pass a `--show-bin-path` argument that prints to console the output path of the build

But I can't find any similar parameter for `tuist build`.
How can I get the build artifact (for example when building in CI)?

_Originally posted by @danyf90 in https://github.com/tuist/tuist/discussions/2330_

**Comment by pepibumur** [comment]
I'm dumping some thoughts around how I think the implementation/interface should be:
- As a user, I'd expect Tuist build to use the global derived data and therefore do incremental builds when possible.
- As a user, I'd expect to be able to specify where to output the artifacts of the build.

I think we can add a new argument, `tuist build --output-directory build/` to tell Tuist that our intent is to get the artifacts exported. We already have [some logic](https://github.com/tuist/tuist/blob/main/Sources/TuistCache/Utilities/CacheFrameworkBuilder.swift#L126) in the codebase to locate the output artifacts under derived data. We can extract that into a class, that we can reuse from `BuildService`.

**Comment by natanrolnik** [comment]
I started working on this, and was able to advance in [this commit](https://github.com/tuist/tuist/commit/da85d762c962ae8e8e6d78ec7daf460bc9be7995).

But it's not done yet, and I have a few questions:

1 - When should the copy be done? After each scheme is built?
2 - What should be copied into the output directory? Everything inside the build directory folder? Only the specified product by the scheme, or also all the frameworks?
3 - How to get the SDK parameter required by `XcodeBuildLocating`? From the build arguments?
4 - How to get the configuration when it's nil, or not present in the scheme? [See here](https://github.com/tuist/tuist/blob/main/Sources/TuistAutomation/Utilities/BuildGraphInspector.swift#L69)

**Comment by fortmarek** [comment]
Hi, I might need this for selective testing, so jumping in here (I actually wanted to take this on but you were faster @natanrolnik 😅)

> When should the copy be done? After each scheme is built?

I think this is gonna be the easiest approach as we don't have to deal with situation when scheme is not built. I think [this](https://github.com/tuist/tuist/commit/da85d762c962ae8e8e6d78ec7daf460bc9be7995#diff-db3a3130ece8058bc607d903f67cdec46c0c10bd4bbeb06e9be490d031eaec0dR126) location, as you mentioned, is the right place to do so.

> What should be copied into the output directory? Everything inside the build directory folder? Only the specified product by the scheme, or also all the frameworks?

I don't think there is a significant downside if we copy everything, so I'd just do so.

> How to get the SDK parameter required by XcodeBuildLocating? From the build arguments?

The build arguments will not work for macOS because the build artifacts for macOS are at `DerivedDataPath/Build/Products/configuration` and the platform SDK is not used there at all. I think `XcodeBuildLocator` can be simply passed `Platform` and switch the appropriate values there.

> How to get the configuration when it's nil, or not present in the scheme? See here

yeah, this is tricky. I could not find much info about this, after a little experimentation it seems that it defaults to `Debug` if it can be found. Otherwise, it chooses the first configuration from the list (search for `XCConfigurationList` in `.pbxproj`). Maybe @kwridan has dealt with this at some point?

**Comment by kwridan** [comment]
`xcodebuild -showBuildSettings` is your friend :) - that will effectively resolve all build settings, it will take into account defaults, project and target values - it's best to leverage that than attempt to write a configuration resolver from scratch.

Looks like there's already a utility for that already:

- https://github.com/tuist/tuist/blob/master/Sources/TuistAutomation/XcodeBuild/XcodeBuildController.swift#L130

Note, you can simplify the logic significantly by leveraging the `--json` flag, we've done something similar in `xcdiff`

- https://github.com/bloomberg/xcdiff/blob/main/Sources/XCDiffCore/Comparator/ResolvedSettingsComparator.swift#L82

Hope this helps

**Comment by fortmarek** [comment]
> xcodebuild -showBuildSettings is your friend :) - that will effectively resolve all build settings, it will take into account defaults, project and target values - it's best to leverage that than attempt to write a configuration resolver from scratch.

I agree that it'd be great if we could extract the default configuration from xcodebuild itself, I am not so sure if it's possible from `-showBuildSettings`. 

I have tried this on `ios_app_with_tests` fixture and I got the following results:
`xcodebuild -workspace App.xcworkspace -scheme App-Project-iOS -derivedDataPath -destination "id=some_id"`
 builds `Debug` configuration.

Running `xcodebuild -workspace App.xcworkspace -scheme App-Project-iOS -derivedDataPath -showBuildSettings | grep Debug` did not find anything 😐 there is a key-value pair `CONFIGURATION = Release` but that does not seem to be used. I must be missing something?

**Comment by kwridan** [comment]
ah sorry I misunderstood the question the original question - is the goal to get the name of the configuration "Debug" / "Release" when not explicitly specified in `Target` or `Scheme`? 

We had to do something similar in the scheme descriptor generator where we default to looking it up via the `Project`:
https://github.com/tuist/tuist/blob/main/Sources/TuistGraph/Models/Project.swift#L156

**Comment by fortmarek** [comment]
Ah, yeah, that's exactly it I think. I'm glad it corresponds to my findings 😛

**Comment by fortmarek** [comment]
But, and I don't know if that's what you had in mind, we can use `-showBuildSettings` to read the derived data folder (`TARGET_BUILD_DIR` key) which might be better than having to switch depending on the platform - on the other hand, it might slow the process a little bit.

**Comment by danyf90** [comment]
Hi @natanrolnik, did you had the time to do any progress on this? 🙏

**Comment by natanrolnik** [comment]
Hey @danyf90, unfortunately I did not. 

A few days ago @fortmarek and I talked and I understood he would try to work on this one, but I might be wrong.

**Comment by fortmarek** [comment]
I took some tidbits from this but I am not working on this directly
