### ISSUE TITLE
Generate a project for the root manifest files

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#240]
## Context 🕵️‍♀️
When we set up the workspace there are currently two manifest files which apply to the all of the projects in it. We should have auto-complete on these manifest files and we should be able to compile them to ensure they are valid.

## What 🌱
- Create a Manifests.xcodeproj which contains any top level manifests.

@tuist/core

**Comment by kwridan** [comment]
resolved via #703

**Comment by pepibumur** [comment]
![image](https://media.giphy.com/media/26tPghhb310muUkEw/giphy.gif)
