### ISSUE TITLE
Test command derived data path

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#2401]
**Describe the issue**
`tuist test` generates a new `.xcodeproj` to a temp directory - but this means that it has a different derived data path from the original project. 

**Expected behavior**
As a user I'd expect that derived data is shared. We can leverage [this](https://github.com/tuist/tuist/issues/2392) logic once done

**Comment by pepibumur** [comment]
> As a user I'd expect that derived data is shared. We can leverage this logic once done

If we place the Xcode project in a temporary directory, how will you get Xcode to reuse it?

**Comment by fortmarek** [comment]
> If we place the Xcode project in a temporary directory, how will you get Xcode to reuse it?

I think passing `-derivedDataPath` to `xcodebuild` should do the trick - do you think that would break something?

**Comment by pepibumur** [comment]
I don't think so. Xcode [uses the project path](https://github.com/tuist/tuist/blob/main/Sources/TuistCache/Utilities/XcodeProjectPathHasher.swift#L14) to determine the directory under derived data where the project artifacts will be stored. So even if you tell `xcodebuild` to use another derived data, it'll fingerprint the path, and that won't match the original project's fingerprint.

**Comment by fortmarek** [comment]
This fingerprinting is not applied when you pass `-derivedDataPath` option - eg. if I run xcodebuild with `-derivedDataPath Data`, the derived data of the project itself will be right in the `Data` directory.
