### ISSUE TITLE
Parallelize the auto-generated test scheme.

### ISSUE THREAD

**Issue by jakeatoms** [tuist/tuist#2426]
**Describe the enhancement**
I would like to execute tests in parallel without having to create the test scheme by hand. Various scheme-related properties are already available on the `Target` API, so we could just pass another flag to enable parallelization on the scheme.

I will be opening a PR for discussion shortly!

**Comment by kwridan** [comment]
Thanks for flagging this @jakeatoms and the for the PR.

It's worthing looking holistically at this before introducing more parameters to the `Target` API. 

I believe the scheme related convenience APIs (like `environment` and `arguments`) have been in the `Target` api historically and have been left in for backwards compatibility. We need to be careful not to duplicate the APIs unnecessarily, the `Scheme` API is quite large and has many more options which I'm sure could benefit from similar conveniences (e.g. `SchemeDiagnosticsOption`s like enabling `mainThreadChecker` and others that may be introduced). It might not be scalable to keep adding properties on `Target` for each scheme property.

Have you considered using [`ProjectDescriptionHelpers`](https://tuist.io/docs/usage/helpers/) to help simplify the creation of `Scheme`? You can have a few functions to help make custom schemes with all the desired options in a consistent fashion for your projects there if needed?

Perhaps what we're missing is a way to customise some default options? We have prior art for this too in [`Config.swift`]( https://tuist.io/docs/usage/config/#generationoption) for options like `enableCodeCoverage`, which perhaps this is more akin to?

**Comment by jakeatoms** [comment]
> Thanks for flagging this @jakeatoms and the for the PR.
> 
> It's worthing looking holistically at this before introducing more parameters to the `Target` API.
> 
> I believe the scheme related convenience APIs (like `environment` and `arguments`) have been in the `Target` api historically and have been left in for backwards compatibility. We need to be careful not to duplicate the APIs unnecessarily, the `Scheme` API is quite large and has many more options which I'm sure could benefit from similar conveniences (e.g. `SchemeDiagnosticsOption`s like enabling `mainThreadChecker` and others that may be introduced). It might not be scalable to keep adding properties on `Target` for each scheme property.
> 
> Have you considered using [`ProjectDescriptionHelpers`](https://tuist.io/docs/usage/helpers/) to help simplify the creation of `Scheme`? You can have a few functions to help make custom schemes with all the desired options in a consistent fashion for your projects there if needed?
> 
> Perhaps what we're missing is a way to customise some default options? We have prior art for this too in [`Config.swift`](https://tuist.io/docs/usage/config/#generationoption) for options like `enableCodeCoverage`, which perhaps this is more akin to?

Hi Kas,

Your concern about adding yet more to the Target was also a concern of mine when I wrote this, so I'm happy to discuss alternatives here! Let me back up and talk about why I took this (admittedly interim) approach vs using a `Scheme`:

I have been encountering an issue with our UI tests wherein the custom `Scheme` added to the `Project` fails to install the app on the simulator and execute the tests. The autogenerated scheme via the `Target` does work as expected. I have a [Slack thread](https://tuistapp.slack.com/archives/C018QG7U7SN/p1611849978020900) in the #support channel regarding this issue. I've not been able to uncover where the difference between the 2 code paths exists yet. I haven't opened a bug Issue yet because I was hoping to have a better grasp of the issue first. I'm going to keep plugging away at that issue, but just thought I'd try this PR as a workaround to unstick us for the time being. 

I suspect the underlying difference is in the project file itself rather than the generated scheme, but I just haven't found it yet.

**Comment by jakeatoms** [comment]
After some more experimentation, I narrowed down the issue to the `shouldUseLaunchSchemeArgsEnv` flag on the `TestAction`. The autogenerated scheme sets this to `YES` while the custom `Scheme` does not. If I check that box in Xcode on the custom scheme, then the tests execute. I'll open a bug Issue describing this and then get to work on a PR to expose that on `TestAction`. The easiest implementation would be to just have a boolean flag on the initializer, but I wonder if it might be better to design something that prevents invalid state, such as an enum with associated values.
