### ISSUE TITLE
Running the focus command can yield an error in Xcode when launching a second time

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#243]
**Describe the bug**
Running `tuist focus` on a directory with an existing project can result in Xcode displaying the following error:

<img width="532" alt="screen shot 2019-02-24 at 4 21 06 pm" src="https://user-images.githubusercontent.com/11914919/53302035-f24ab700-3851-11e9-8a7e-73537cfd76ef.png">

**To Reproduce**

1. Navigate to `fixtures/ios_app_with_tests`
1. Run `tuist focus`
1. Close the Xcode window (⌘ W) 
1. Run `tuist focus` a second time

**Additional Context**

Quitting Xcode (⌘ Q) doesn't exhibit this issue. It seems while Xcode is running, opening projects is a quicker operation than when it's completely closed. In this scenario it may be reading the workspace file from disk before tuist completed generating/writing it.

**Comment by pepibumur** [comment]
Yeah, [will need to get this one worked on](https://github.com/tuist/xcodeproj/pull/327) to fix this. xcodeproj is currently very aggressive when it writes the files back to disk and that's causing Xcode not to know how to reload the project.
Thanks for opening the issue.

**Comment by pepibumur** [comment]
I'm working on fixing this one

**Comment by kwridan** [comment]
Thanks @pepibumur! Interesting issue - the strange bit is, for the scenario above the Xcode project itself is not opened while the generation takes place. I wonder if Xcode is caching recent projects while it's still running.

Interestingly introducing some delay seems to reduce its occurrence.

e.g.
`tuist generate && sleep 2 && open App.xcworkspace`

**Comment by pepibumur** [comment]
> I wonder if Xcode is caching recent projects while it's still running.

Maybe 🤔. With the change that I proposed on xcodeproj that shouldn't happen anymore because files would only get written if they changed.

**Comment by kwridan** [comment]
I locally updated `tuist` to use that branch of `xcodeproj` to test locally - sadly it's still occurring.

Dug a bit further and turns out the workspace does end up getting written to disk due to being different!

`existingString`:

```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Workspace\n   version = \"1.0\">\n   <FileRef\n      location = \"group:Workspace.swift\">\n   </FileRef>\n   <FileRef\n      location = \"group:App/MainApp.xcodeproj\">\n   </FileRef>\n   <FileRef\n      location = \"group:Framework1/Framework1.xcodeproj\">\n   </FileRef>\n   <FileRef\n      location = \"group:Framework2/Framework2.xcodeproj\">\n   </FileRef>\n</Workspace>\n"
```

vs. 

`string`:
```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Workspace\n   version = \"1.0\">\n   <FileRef\n      location = \"group:Workspace.swift\">\n   </FileRef>\n   <FileRef\n      location = \"group:Framework1/Framework1.xcodeproj\">\n   </FileRef>\n   <FileRef\n      location = \"group:Framework2/Framework2.xcodeproj\">\n   </FileRef>\n   <FileRef\n      location = \"group:App/MainApp.xcodeproj\">\n   </FileRef>\n</Workspace>\n"
```

The sort order of workspace elements differs between runs resulting in changing the workspace file.

Will investigate the sort issue further.

**Comment by pepibumur** [comment]
> The sort order of workspace elements differs between runs resulting in changing the workspace file.

Ouch, we've had this issue before and had to introduce some logic for sorting the elements properly. We have some tests on the xcodeproj that verify that the order of the elements is right after writing the project *(using git diffing)* but we don't have tests for workspaces to detect this.

Good catch @kwridan
