### ISSUE TITLE
Tuist doc does not use `serve` public attribute

### ISSUE THREAD

**Issue by AlbertMontserrat** [tuist/tuist#2435]
**Describe the bug**
When using `tuist doc` command, the property `--serve` doesn't seems to be used internally in the DocService.

We wanted `tuist doc` to generate the documentation of our app and being able to bundle this generated web pages and publish them using Gitlab pages. Currently, the web pages are being saved in a temporary folder, always, and also always fires the web server at the end. As the documentation of `serve` property says:

```
It creates the project in the current directory or the one indicated by -p and doesn't block the process
```

So it looks quite what we need to.

**To Reproduce**
Compare both `tuist doc` and `tuist doc --serve` and check if there's any difference.

**Expected behavior**
Being able to use `serve` property to build the documentation in the current folder and also not triggering the server execution.

**Comment by fortmarek** [comment]
Hi! I don't know that much about `tuist doc`, maybe @facumenzella might have more info as he implemented this feature? Feel free to tag me here again if he doesn't have time to respond in the next few days and I can have a look instead.

**Comment by AlbertMontserrat** [comment]
Hello @fortmarek some news about that? 🙏

**Comment by fortmarek** [comment]
Hi @AlbertMontserrat!

Would you be willing to fix this? It seems, indeed, that `server` arguments is not leveraged in any way 🙈 

I think you should be able to pass `serve` to `DocService.run()` and hiding the running of server behind `if server { ... }` in the same component.

**Comment by danyf90** [comment]
`tuist doc` removed in 2.0.0
