### ISSUE TITLE
Should artefacts from `tuist cache warm` be stored in a shared directory or under the local project?

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#2440]
Hi everyone,
In a conversation with @fortmarek we briefly talked about the cache location.
I am opening this issue to move further the discussion.

It could be convenient to have the cached artefacts under the project directory instead of a shared one (similar to other package managers, npm, spm etc..).
While an obvious option would be to pass a parameter to specify where to store the cache, I was wondering what's the reason for using the currently shared one and if it would make sense to replace it with the project one instead.

One of the benefits for the "local project cache" that comes to my mind are:
* It could enable teams to git-lfs commit their cache, making loading from cache as easy as caching branches, magical experience!
* CI could benefits from local project cache too, think about cleaning or running multiple jobs
* By having local project cache it is easier to detect "out-of-dated" artefacts, enabling, for example, to be cleaned away when running `tuist cache warm`.

Looking forward to hear from you!

**Comment by fortmarek** [comment]
@andreacipriani @RomainBoulay thoughts? I got the same question from @mollyIV, so it might be worth taking a look at this - I am not familiar enough with cache at the moment to answer this with certainty as I have started working with it only recently.

**Comment by bolismauro** [comment]
I'm extremely in favor of this.

I started investigating this from a CI perspective (that is, reducing building times) and this proposal may help in these regards a lot.

I know some time ago there was a "cloud-storage" for caches, but it has been removed as far as I can see. This doesn't cover 100% that need, but it partially fills the gap

**Comment by andreacipriani** [comment]
> @andreacipriani @RomainBoulay thoughts? I got the same question from @mollyIV, so it might be worth taking a look at this - I am not familiar enough with cache at the moment to answer this with certainty as I have started working with it only recently.

I think we should provide flexibility and give the possibility to change the location of the local cache. 👍

**Comment by andreacipriani** [comment]
> I'm extremely in favor of this.
> 
> I started investigating this from a CI perspective (that is, reducing building times) and this proposal may help in these regards a lot.
> 
> I know some time ago there was a "cloud-storage" for caches, but it has been removed as far as I can see. This doesn't cover 100% that need, but it partially fills the gap

There is still a generic [cloud](https://github.com/tuist/tuist/tree/main/Sources/TuistCloud) protocol implemented on the client to connect with a server.  Let's have a chat about it, you can Slack me!

**Comment by fortmarek** [comment]
This was already possible with `TUIST_CACHE_DIRECTORY` which was just undocumented as it's primary use for testing. But it can be easily used for custom location of the cache, too.

https://tuist.io/docs/building-at-scale/caching/
Fixed in [#2450](https://github.com/tuist/tuist/pull/2450) thanks @andreacipriani

**Comment by pepibumur** [comment]
I'm reopening this. That variable was never intended to be used publicly, only for testing purposes. We should add an argument or allow configuring that through a setting in the Config.swift file.

**Comment by fortmarek** [comment]
Sure - I think `Config.swift` might be a better option, so the users won't have to think about where the cache is actually leveraged (and it also lets us adding cache to features which are not using it at the moment).

Usually, users will probably want to use a different path for CI and for the local runs, so I'd also add that they can use `Environment.isCI?.getBoolean(default: false)` for that.
