### ISSUE TITLE
How to set if I want default tab indent to 2 in Text Settings?

### ISSUE THREAD

**Issue by jinuman** [tuist/tuist#2448]
**Describe the bug**
Hi. First of all, I really appreciate what you guys have done. 😄

<img width="260" alt="tab-indent" src="https://user-images.githubusercontent.com/26243835/107066320-29d58280-6821-11eb-9b6d-a37d031245e6.png">

I want my project have `Tab: 2, Indent: 2` by default after `tuist generate`, but I cannot find solution for that from document.

My main target looks like below
```Swift
Target(
    name: "PhotoSearcher",
    platform: .iOS,
    product: .app,
    bundleId: "com.jinuman.PhotoSearcher",
    infoPlist: "PhotoSearcher/Supporting Files/PhotoSearcher-Info.plist",
    sources: ["PhotoSearcher/Sources/**"],
    resources: ["PhotoSearcher/Resources/**"],
    actions: targetActions,
    dependencies: [
        .cocoapods(path: ".")
    ],
    settings: targetSettings
),
```

Could anyone help me find solution?

**Comment by kwridan** [comment]
Hi @jinuman 

Sadly there aren't any options available in Tuist to customise this particular setting.

Taking a closer look at how those settings are controlled in the Xcode Project file:

Seems to be a property at the root group level:

```diff
                4102E3E068508DD683953C7D = {
			isa = PBXGroup;
			children = (
				52611B11A5E6A7198C4E57A3 /* Project */,
				BDD1182E50DC622819F25364 /* Frameworks */,
				12F86983915672C244201F6A /* Playgrounds */,
				E9C3DB3EC6D7655028A9C0D3 /* Products */,
			);
+			indentWidth = 2;
			sourceTree = "<group>";
+			tabWidth = 2;
		};
```

There isn't an API for this low level of customisation in Tuist itself at this time. The challenge is there are a lot of those small low level settings and it will be difficult to expose properties for all of them in the Tuist manifests (the API would grow significantly). It's something to reconsider for future versions on how to offer access to customisations like this in a scalable fashion.

 You can possibly do some post processing yourself after Tuist generates projects using other libraries like [tuist/XcodeProj](https://github.com/tuist/XcodeProj) (Swift) or [CocoaPods/Xcodeproj](https://github.com/CocoaPods/Xcodeproj) (ruby).

**Comment by jinuman** [comment]
Ah ha. Many thanks for the explanation. @kwridan 

I figured out with [SwiftFormat](https://github.com/nicklockwood/SwiftFormat). Edit `Setup.swift` file and `Project.swift` file to have post processing after generate.

Hopefully customize low level in Tuist in the future. 😄

**Comment by DimaMishchenko** [comment]
I think it would be a good addition directly to `tuist`, to use it over post hooks without any extra effort.

As far as I can see this should be a pretty lightweight change. Those setting are just a part of the `mainGroup` in `PBXProject`. I'd suggest to add this configuration into `Project` manifest? 

Rough API example:
``` swift
public struct TextSettings {
    public let usesTabs: Bool?
    public let indentWidth: UInt?
    public let tabWidth: UInt?
    public let wrapsLines: Bool?
}
// In Project 
let project = Project(
    name: "Project",
    textSettings: TextSettings(usesTabs: true, indentWidth: 2, tabWidth: 2)
)
```

@fortmarek @kwridan What do you think?

**Comment by kwridan** [comment]
Thanks for the follow up @DimaMishchenko and for investigating the details 👍 

It sounds less cumbersome than I had originally thought. To help keep the `Project` API lean one suggestion I had would be to  possibly move this to a nested structure as opposed to having it at the top level, for example:


```swift
struct ProjectOptions { // or ProjectGenerationOptions
   var textSettings: TextSettings?
}

let project = Project(
    name: "Project",
    options: .options(
          textSettings: TextSettings(usesTabs: true, indentWidth: 2, tabWidth: 2),
    )
)
```

The rationale is, this could host some of the properties that are defined in [`Config.swift`](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Config.swift#L8) today. This has been brought up on a few occasions where there's a desire to move some of those options to `Project.swift`, and this could be a place to group those auxiliary generation options together. Does that sound reasonable?

Lastly, would you like to contribute this addition? 🙂

**Comment by DimaMishchenko** [comment]
`ProjectOptions` makes sense for me. 
What about nested type? 
``` swift
extension Project {
  public struct Options {...}
}
```

And yes, would be happy to contribute, will try to find some free time for this next week. @kwridan

**Comment by kwridan** [comment]
Sure, the nested type works nicely too. Thanks @DimaMishchenko 🙏

**Comment by fortmarek** [comment]
Thanks for the follow-up @DimaMishchenko and @kwridan!

I'd just like to give my thoughts on the proposed API:

```swift
let project = Project(
    name: "Project",
    options: .options(
          textSettings: TextSettings(usesTabs: true, indentWidth: 2, tabWidth: 2),
    )
)
```

We could maybe copy the API of `Config.generationOptions` which is an array `[GenerationOption]`. Instead of having a bit clumsy `options: .options(...)` we would have `options: [...]`. However, it does mean you could define one setting twice, so I don't have a strong opinion on which of the APIs are better in the end.

**Comment by danyf90** [comment]
I like @fortmarek proposal as I think it makes the configuration more compact (no `options`, `textSettings` repetitions) and from a UX point of view is easier to search among the available options by just adding a `.` and then trigger the autocomplete.

Regarding the possibility to specify the option twice, we can add some validation if we think it is a problem.

On a side note, I think it would be a great addition as everytime I have to work on tuist I have to tweak the indent settings as I normally use 2 :D
