### ISSUE TITLE
Got No such module 'MyPlugin' when trying to use local Plugin.

### ISSUE THREAD

**Issue by sarunw** [tuist/tuist#2455]
**Describe the bug**
Project from `tuist edit` can't recognize my custom Plugin.

**To Reproduce**
1. Create a plugin following this [article](https://tuist.io/docs/plugins/creating-plugins/)
2. Try to use the Plugin in my project by reference it in **Project.swift**.
3. Running `tuist edit`, but I got "No such module 'MyPlugin'"

**Plugin.swif**
```
import ProjectDescription

let plugin = Plugin(name: "SarunwPlugin")
```

**Project+sarunw.swift**
```
import ProjectDescription

public extension Project {
    static func app(name: String) -> Project {
        return Project(
                name: "MyApp3",
                targets: [
                    Target(
                        name: "MyApp",
                        platform: .iOS,
                        product: .app,
                        bundleId: "com.sarunw.myapp",
                        infoPlist: .extendingDefault(
                            with: [
                                "UILaunchScreen": [:]
                            ]
                        ),
                        sources: [
                            "Sources/**"
                        ]
                    )
                ]
                )
    }
}
```

**Project.swift**
```
//
//  Project.swift
//  sarunwManifests
//
//  Created by Sarun Wongpatcharapakorn on 2/8/21.
//

import ProjectDescription
import SarunwPlugin

let project = Project.app(name: "MyApp")
```

**Config.swift**
``` 
//
//  Config.swift
//  sarunwManifests
//
//  Created by Sarun Wongpatcharapakorn on 2/8/21.
//

import ProjectDescription

let config = Config(
    plugins: [
       .local(path: "/Users/...absolute path to my plugin folder../SarunwPlugin")
    ],
    generationOptions: []
)

```

The path seems to be correct since I can run `tuist generate` and everything got generated correctly.

**Expected behavior**
I should be able to edit Project.swift with proper reference to the helper's class from my Plugin.

**Desktop (please complete the following information):**

- OS: BigSur 
- Version 11.2

**Comment by luispadron** [comment]
@sarunw This is in the works! Im currently working on making it so you can edit plugins with `tuist edit` and will follow that up with `tuist edit` support for projects with plugins.

**Comment by luispadron** [comment]
@sarunw Support for this has been merged. Should be in the next release, please re-open if you experience any issues
