### ISSUE TITLE
RFC: Adding support for tuist init with custom template path parameter

### ISSUE THREAD

**Issue by sarunw** [tuist/tuist#2456]
## Need/Problem
Currently there is no easy way to customize how to bootstrap a project. The only way Tuist provides is `tuist init`. While it good for newcomers to get used to what Tuist has to offer, it doesn't provide much value to real projects with different architecture and conventions.

This proposal aims to mitigate this problem by add an extension point to `tuist init` so users can choose their own template files.

## Proposed solution
Add new template path option to `tuist init`..`
| Option | Description |
|----|-----|
|-m, [--template-path=TEMPLATE] | Path to some application template |

- `-t`, and `-p` have been used, so I use `-m` the same as rails.
- We can make `-m` accept URL path for shared template in the future.

## Details design
I'm still new to Tuist, but the change we need to make this happened should be around these two files.
- `InitService`: add a new parameter to the initizalier.
- `TemplatesDirectoryLocating`: use provided template path argument to find the template.

## Adoption strategy
This will be purely additive, so we'll just have to update the documentation

## Questions
1. Should we have a way to easily edit this shared template?

## Alternatives considered
From my understanding, the different between `init` and `scaffold` right now is that `init` need directory to be empty. If we remove that constraint, we could add shared template feature to Plugin and merge `init` and `scaffold` together. (But without that constraint I don't know it would make two method identical or not).

Not sure this is a good idea though since Plugin seem like a mechanic to share thing **after** the project has already been setup. (From the fact that it need Config.swift).

**Comment by fortmarek** [comment]
Hi @sarunw!

Thanks for the RFC 🖤 

> While it good for newcomers to get used to what Tuist has to offer, it doesn't provide much value to real projects with different architecture and conventions.

I definitely agree with this point

> Should we have a way to easily edit this shared template?

I think we should - otherwise we lose on the autocompletion and static typing features of Swift

> From my understanding, the different between init and scaffold right now is that init need directory to be empty. If we remove that constraint, we could add shared template feature to Plugin and merge init and scaffold together. (But without that constraint I don't know it would make two method identical or not).

You are right these features are closely coupled - another difference is that `init` looks for templates in `~/.tuist/Versions/x.y.z/Templates` whereas `scaffold` doesn't. I'd try to keep these two separate, though, as each describes a different intent. That being said, I think we could allow `Config.swift` to be present in the directory when running `tusit init`. But I'd first try to implement `scaffold` plugin and see how this fits together if that makes sense?

**Comment by sarunw** [comment]
I end up moving `Tuist/Templates` one step up in the hierarchy and it works the way I want. I write a detailed post here https://sarunw.com/posts/tuist-init/ for those who struggle with the same issue.

**Comment by TYRONEMICHAEL** [comment]
@sarunw followed your post, but getting `Could not find template... Make sure it exists at...`. @fortmarek is this something that instead should be tried to be implemented with a plugin, to is @sarunw approach the right one?
