### ISSUE TITLE
Tuist and signing

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#246]
## Context 🕵️‍♀️
Fastlane does a pretty good job dealing with certificates and provisioning profiles, and we could potentially integrate with it so that developers don't need to manage them themselves. However, I don't believe integrating Tuist with Fastlane is a good idea:
- We'd need to check if the Ruby environment is properly set up. Being honest, it's not easy because developers environment is very unpredictable. If we assume things are right and provide the users with an interface to Fastlane that is broken, it'll make the experience using Tuist horrible.
- Fastlane output doesn't align with Tuist's, which strives to be simple and contain the basic information that the user needs. Running Match would result in a very polluted standard output telling developers how much time they saved because of Fastlane, or a summary of the tasks that are being executed.

## What 🌱
I think we can take a different and simpler approach here, built into Tuist and that doesn't require any dependency with a third party library.

## Proposal 🎉
1. Projects would contain a folder, `Certificates` where all the provisioning profiles would be.
2. Certificates and provisioning profiles would follow a naming convention:
   - Certificates/Target.Configuration.mobileprovision *(e.g. MyApp.Debug.mobileprovision )*
   - Certificates/Configuration.p12 *(e.g. Release.mobileprovision)*
2. We don't generate them for the users. They are responsibles for going to the developer account and generate them themselves *(we could automate this in the future)*.
3. When generating the project:
  - Tuist would configure the provisioning profile accordingly if it finds any provisioning profile in the certificates directory.
  - It'd install the certificate in the keychain if it doesn't exist.
  - It'd also alert the user about:
    - Expired certificates
    - Certificates that are about to expire.
    - Provisioning profiles that lack a certificate and thus can't be used to sign an app.

## Security 🔑 
With the proposal above anyone that has access to the repository has access to the certificates. Is that good? That's something Fastlane controls by having the certificates in a different repository where you can give/revoke access to people. Since having another repository for that is an unnecessary overhead in my opinion I think we could provide symmetric encryption and decryption out of the box:
1. There'd be a `master.key` file in the certificates directory *(.gitignored by default)*
2. Tuist would offer the following commands:
  - `tuist certificates encrypt`: It'd encrypt the certificates and provisioning profiles and remove the unencrypted version.
  - `tuist certificates decrypt`: It'd encrypt any provisioning profile and certificate in the directory.
3. `tuist generate` would decrypt the files as part of the process of configuring the environment for signing

### Different key per configuration
We might want developers to not have access to the `Release` key for security reasons. To enable that, we could have keys per configuration:
```
Certificates/
  Debug.key
  Release.key
  Debug.p12.enc
  Release.p12.enc
  MyApp.Debug.mobileprovision.enc
  MyApp.Release.mobileprovision.enc
```

## Some advantages over Match

- We keep everything in one repository.
- We can configure the project for the user because we control its generation.

cc @tuist/core

**Comment by steprescott** [comment]
This is an area that I am quite interested in so would be great to get your full thoughts.

**Comment by pepibumur** [comment]
> This is an area that I am quite interested in so would be great to get your full thoughts.

I think I dumped most of them on the issue body. Is there anything you'd like to know more about? What's your experience configuring signing in your projects @steprescott ?

**Comment by fortmarek** [comment]
This would be so great! 
Now, I think it might make sense to allow custom naming of the certificates - to make it compatible with whatever conventions the team has, but also should be enough to support `fastlane match`-generated certs out of the box (which will still be a go-to solution for generating certs, at least before that feature is implemented in `tuist`, too)

The security part makes sense to me, but what I did not understand is where would `master.key` come from? Because, if I understood this correctly, this will have to be shared across the whole team to make this work.

**Comment by pepibumur** [comment]
> Now, I think it might make sense to allow custom naming of the certificates - to make it compatible with whatever conventions the team has, but also should be enough to support fastlane match-generated certs out of the box (which will still be a go-to solution for generating certs, at least before that feature is implemented in tuist, too)

Although conforming existing conventions eases the transition to Tuist, we should not let them constraint our design. Signing is an interesting area where Fastlane relieved some pain, but I think there's still opportunity to make signing completely seamless for users.

Rather than saying we should build the feature to run Fastlane, what if we build the feature imagining how we'd love it to be and then provide an easy way for users to port their setups to Tuist's approach?

> The security part makes sense to me, but what I did not understand is where would master.key come from? Because, if I understood this correctly, this will have to be shared across the whole team to make this work.

`master.key` would be a private key that Tuist uses to decrypt encrypted project elements, like certificates & provisioning profiles, and perhaps more elements in the future. It can be generated at any time, and developers just need to place it in their local repository in order for the signing logic to run.

**Comment by fortmarek** [comment]
OK, I agree that we should not let our design be influenced by the current conventions 🙂 

I still don't really understand where would `master.key` come from - I clone a repo where there are encrypted certificates, I run `tuist generate` - now they should be decrypted with `master.key`, but I don't see where that key came from if I never worked on that project before.

**Comment by pepibumur** [comment]
> I still don't really understand where would master.key come from - I clone a repo where there are encrypted certificates, I run tuist generate - now they should be decrypted with master.key, but I don't see where that key came from if I never worked on that project before.

The key is generated the first time something needs to be encrypted and should be stored and shared with all the members of the team *(using 1Password or any key management system used at your company)*.

That means that after cloning the repository you'll have to place the key yourself, otherwise features like signing wouldn't work.

Alternatively, we can get rid of that extra layer of security and store the certificates & provisioning profiles unencrypted in the repository. In the end, if you trust the people in your organization, who has access to the repository and the keys, why shouldn't they have access to the certificates and prov. profiles. Adding that extra security layer adds a lever of indirection and friction that we could avoid.

**Comment by fortmarek** [comment]
So, maybe we could allow both approaches, first building out the less safe version, but if there are people who want that extra layer of security, we might allow that later, too? The more secure approach would bring some friction and I feel like that a lot of devs just want it to be as easy as possible and I don't see a reason to force others into the more complicated, albeit a little bit safer, solution.

**Comment by pepibumur** [comment]
Agree. The way I picture this feature is allowing automatic renovation of the certs. and provisioning profiles and with extra safety built-in but we can start with something simple and then add those enhancements later. What about something along the lines of:

- Certificates are placed in the `Tuist/Keys` directory. Tuist determines the location of the `Tuist` directory by traversing up the folders hierarchy and finding the folder that contains the `TuistConfig.swift`.
- We can define a naming convention for the certificates and provisioning profiles:
  - Certificates: `team-id.type.cert` *(e.g. XYZ.development.cert)*
  - Provisioning profiles: `target.[configs].p12` *(e.g. MyApp.Debug-Debug2.p12)*
- Then for each target Tuist would:
  - Find if there are associated provisioning profiles.
  - If there are, it'd check if it's tied to any of the existing certificates. If not, it'll fail.
  - Verify if both, the certificate and provisioning profiles are good *(not expired or invalidated)*
  - Set the right build settings to the project based on the selected provisioning profiles and certificates.

I think we can start with something conventional and reconsider the approach if we see that teams need a more customizable approach.

**Comment by pepibumur** [comment]
[This issue](https://github.com/tuist/tuist/issues/951) is related.
