### ISSUE TITLE
`tuist test` command is failing when a project iOS app target links Carthage dependency

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#2478]
**Describe the bug**
`tuist test` command is failing when a project iOS app target links Carthage dependency.

**To Reproduce**

1. Download a demo project: [demo.zip](https://github.com/tuist/tuist/files/5944072/demo.zip).
2. Unzip a demo project and go into main directory. 
3. Bootstrap Carthage's dependencies via `./carthage.sh bootstrap --platform iOS --cache-builds --no-use-binaries` ([Carthage workaround](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md) when using with Xcode 12 )
4. Generate a project via `tuist generate`
5. Run tests via `tuist test MyApp -d 'iPhone 11 Pro' -o '14.0'`
6. See the error:

```
❯ test-command tuist test MyApp -d 'iPhone 11 Pro' -o '14.0'
Using version 1.32.0 defined at /Users/djankowski/Desktop/test-command/.tuist-version
Generating project for testing
Generating workspace MyApp.xcworkspace
Generating project MyApp
Testing scheme MyApp
Testing failed:
	Framework not found Alamofire
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	Ld /Users/djankowski/Library/Developer/Xcode/DerivedData/MyApp-dsmukftsewzhcqafnlyacpadyxzz/Build/Products/Debug-iphonesimulator/MyApp.app/MyApp normal
(1 failure)
The 'xcodebuild' command exited with error code 65
```

Steps to reproduce the bug in a nutshell: 

```bash
$ cd demo
$ ./carthage.sh bootstrap --platform iOS --cache-builds --no-use-binaries
$ tuist generate
$ tuist test MyApp -d 'iPhone 11 Pro' -o '14.0'
```

**Expected behavior**
The tests should pass. Tested on `tuist` 1.30.0 version are passing just fine:

```
❯ test-command tuist test MyApp -d 'iPhone 11 Pro' -o '14.0'
Using version 1.30.0 defined at /Users/djankowski/Desktop/test-command/.tuist-version
Testing scheme MyApp
[MyApp] Compiling Bundle+MyApp.swift
[MyApp] Compiling AppDelegate.swift
[MyApp] Processing MyApp.plist
[MyApp] Running script Embed Precompiled Frameworks
[MyApp] Touching MyApp.app
[MyAppTests] Processing MyAppTests.plist
[MyAppTests] Running script Embed Precompiled Frameworks
[MyAppTests] Touching MyAppTests.xctest
All tests
Test Suite MyAppTests.xctest started
MyAppTests
    ✔ test_twoPlusTwo_isFour (0.006 seconds)
Test Succeeded
The project tests ran successfully
```

**Desktop:**

- OS: macOS 11.0.1
- Tuist Version: 1.32.0

**Additional context**

The error is happening on [`tuist` 1.32.0](https://github.com/tuist/tuist/releases/tag/1.32.0) version which includes plenty of changes related to `test` command.

**Comment by fortmarek** [comment]
Thanks @mollyIV! We have recently changed how `tuist test` works under the hood and it generates the test project in a different location than the one you interact with which is probably causing this.

I will investigate this further.

**Comment by mollyIV** [comment]
Hey @fortmarek 👋 

Due to quite a few changes in the past releases, I tried to reproduce a bug with `tuist 1.36.0` and `Xcode 12.4` and everything seems to be working just fine 😊 

```bash
❯ demo tuist test MyApp -d 'iPhone 11 Pro' -o '14.4'
Using version 1.36.0 defined at ~/Downloads/demo/.tuist-version
Generating project for testing
Generating workspace MyApp.xcworkspace
Generating project MyApp
Testing scheme MyApp
...
[MyAppTests] Touching MyAppTests.xctest
All tests
Test Suite MyAppTests.xctest started
MyAppTests
    ✔ test_twoPlusTwo_isFour (0.004 seconds)
Test Succeeded
Tests Passed: 0 failed, 1 total (0.010 seconds)
The project tests ran successfully
```

I believe we can close the issue and re-open if happens again. Thank you!

**Comment by fortmarek** [comment]
Awesome, thanks for getting back to me @mollyIV!
