### ISSUE TITLE
Can't work with Tuist project

### ISSUE THREAD

**Issue by bolismauro** [tuist/tuist#2502]
**Describe the bug**
The Tuist project doesn't compile on my machine.
The problem is related to dependencies, and in particular to Stencil

**To Reproduce**

1. Clone Tuist
2. Open `Package.swift`

**Expected behavior**
The project compiles

**Screenshots**
![image](https://user-images.githubusercontent.com/771999/107753057-d92dc000-6d1f-11eb-8c6c-fc055fbe13f3.png)

Here you can see that `Stencil` is missing (sometimes it is grayed out)
![image](https://user-images.githubusercontent.com/771999/107753078-e64aaf00-6d1f-11eb-8469-94485dc75ae1.png)

**Desktop (please complete the following information):**

- OS: MacOS 11.0.1
- Xcode 12.3

**Additional context**
I tried to delete the project, re-download it, re-fetch the dependencies or to remove Stencil and add it back. Nothing works

**Comment by bolismauro** [comment]
I tried to delete the `DerivedData` folder and switch back to Xcode 12.1, this is the result
![image](https://user-images.githubusercontent.com/771999/107769881-e7d4a100-6d38-11eb-9d6f-1355d77657e4.png)

In both cases I compiled the `ProjectDescription` target (it compiles) and then I've compiled `tuist` (it doesn't compile).

I wonder if there is something broken in my computer, but I cannot figure it out

**Comment by bolismauro** [comment]
Update: I added `TuistCoreTesting` to the scheme list and compiled it.
The project now works.

It looks like a Xcode-related issue. The problem is that If I clean build everything, I go back to the previous situation

**Comment by fortmarek** [comment]
Hi @bolismauro!

I have already seen the first error with stencil you posted above.

What helped me was a combination of cleaning derived data and running `Reset package cache`. The problem, at least in my case, was that resolving of packages incorrectly deleted the Stencil dependency. I don't think this is something we can fix as it is an issue of SPM + Xcode 😐

**Comment by bolismauro** [comment]
Have you seen the `TuistCoreTesting` one as well?
At the moment, I managed to compile the project by adding a new scheme and run CMD+U. Then everything works.

PS: Do you plan to move Tuist to Tuist? It would be great :P is there something that prevents this from happening?

**Comment by bolismauro** [comment]
I just discovered that I cannot run acceptance tests for the very same reason
![Uploading image.png…]()

**Comment by fortmarek** [comment]
> If this is because of SPM I think there is very little we can do

yep, I think this might be the case. I have not seen anything like that personally. 

Have you tried running `swift build` from main branch? I'd also try to delete `.build` folder in the root dir. 

> (maybe add something in the Getting Started doc?)

We could do that, although, I am not sure to how many people the failures you wrote about apply. Also they might change based on the Xcode version as this is most likely not a problem on our side.

> Do you plan to move Tuist to Tuist? It would be great :P is there something that prevents this from happening?

It is something we have considered - I think the only thing preventing from something like that to happen is someone having the time to invest it in the migration.

**Comment by bolismauro** [comment]
> Have you tried running swift build from main branch? I'd also try to delete .build folder in the root dir.

I tried and it fails. I even tried switching to Xcode 12.1 and it fails. I'm really puzzled

**Comment by pepibumur** [comment]
Joining late but, this is an issue with SPM resolution of dependencies. We've already considered moving to Tuist, but it's a big undertaking so we haven't been able to prioritize it. Should I close this issue?

**Comment by bolismauro** [comment]
If the only solution is moving away from SPM, then yes :)

**Comment by fortmarek** [comment]
AFAICT it is, feel free to reopen if there is anything that can be done on our side
