### ISSUE TITLE
Enable setting a parameter for Carthage in project setup to use xcframework

### ISSUE THREAD

**Issue by parse** [tuist/tuist#2503]
**Describe the bug**
Given this Cartfile:
```
let setup = Setup([
    .carthage(platforms: [.iOS]),
])
```

When running `tuist up` it runs: 
`/usr/local/bin/carthage bootstrap --project-directory /Users/parse/prog/tuist-mo --platform iOS BinaryDependency Alamofire` 

This however creates some issues with some packages and with the move towards `xcframework` that is going on in the ecosystem now I'd like to request adding support for adding the flag `--use-xcframeworks` flag. So the complete command would become: 

`/usr/local/bin/carthage bootstrap --project-directory /Users/parse/prog/tuist-mo --platform iOS BinaryDependency Alamofire --use-xcframeworks`

Suggestion for options:

```
let setup = Setup([
    .carthage(platforms: [.iOS], useXcframework: true),
])
```

**Expected behavior**
This command will run:
`/usr/local/bin/carthage bootstrap --project-directory /Users/parse/prog/tuist-mo --platform iOS BinaryDependency Alamofire --use-xcframeworks`

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 
- Version 11.1
- Tuist Version 1.32

**Additional context**
Using Carthage version 0.37.0

**Comment by pepibumur** [comment]
Hey @parse. I think this is a good idea. Would you like to tackle it yourself? I can give you some pointers if you are interested.

**Comment by laxmorek** [comment]
Im working on adding `--use-xcframeworks` flag for `carthage` installation when you are using our new `Dependencies.swift`(discussion here: #2504).

I think I will be able to adjust `Setup` too.

**Comment by parse** [comment]
> Im working on adding `--use-xcframeworks` flag for `carthage` installation when you are using our new `Dependencies.swift`(discussion here: #2504).
> 
> I think I will be able to adjust `Setup` too.

Fantastic news. I can keep my workaround until this gets addressed. The workaround for other people interested is simply ignoring the `tuist up` command (as it will fail the build) and running: 

```
carthage update --use-xcframeworks
./.tuist-bin/tuist generate
```

**Comment by laxmorek** [comment]
I have started to work on it.
