### ISSUE TITLE
Dependencies.swift - Add XCFramework option for Carthage

### ISSUE THREAD

**Issue by bolismauro** [tuist/tuist#2504]
**Describe the bug**
Carthage 0.37 supports XCFrameworks, which solves a lot of problems that developers have when working with this dependency manager.

At the current stage, there is no way to specify the proper flag to use xcframeworks.

Given the current structure of the `Dependencies.swift` file, and the fact that the flag should not be enabled on per-dependency basis, I'd suggest something like this when it comes to public API

```swift
import ProjectDescription
let dependencies = Dependencies(
  carthage: .init(
	useXCFrameworks: true
  ),
  dependencies: [
    .carthage(origin: .github(path: "Alamofire/Alamofire"), requirement: .exact("5.0.4"), platforms: [.macOS])
])
```

Note that this change is not breaking, as the code can be changed in a way to make it back compatible

```swift
import Foundation

/// A `Dependencies` manifest allows for defining external dependencies for Tuist.
public struct Dependencies: Codable, Equatable {
	/// variables here

    /// Initializes a new `Dependencies` manifest instance.
    /// - Parameter dependencies: List of dependencies.
    public init(_ dependencies: [Dependency] = []) {
		self.init(carthage: .init(), dependencies: dependencies)
    }

    public init(carthage: Dependencies.CarthageOptions, dependencies: [Dependency) {
      /// assignments here
      dumpIfNeeded(self)
    }
}
```

When it comes to the implementation, I'm struggling in checking the Tuist code, as the project doesn't compile and navigation is broken (see #2502). As soon as I fix it, I'll write how it can be implemented (or open a PR directly).

**Additional context**
Please note that I assume this is different from #2503, as that issue is related to the `Setup` phase, whereas here we discuss the Dependencies/Chimera project.

For the use cases I have in mind, I'd love to keep the two things separated

**Comment by fortmarek** [comment]
Hi @bolismauro!

Yes, I think we should support this and the API seems reasonable to me. I'd just maybe rename `carthage` parameter in `Dependencies` initializer to eg `carthageOptions`, so the value doesn't conflict with `.carthage(...)` dependency.

It'd be ideal if we could just make xcframework a default but, at least for the time being, we should definitely allow both options.

If you have further troubles with running the project, feel free to hit me up on Slack, so you have a working project asap. 

Looping in @laxmorek and @pepibumur if they have thoughts on this.

**Comment by laxmorek** [comment]
I'm implementing it.

**Comment by laxmorek** [comment]
I wanted to avoid it but it seems `Dependencies.swift` should give possibility for small providing adjustments. I would prefer to enforce `XCFramework` for `cartage` but I understand that projects may have different needs. 

In my opinion `Dependencies.CarthageOptions` may be not necessary when project doesn't use `carthage`. 

I would like to propose new structure for `Dependencies` where options are connected with dependencies managers that they relates to.

 ```swift
public struct Dependencies: Codable, Equatable {
    public let carthage: Carthage?
    public let cocoapods: Cococapods?
    
    public init(carthage: Carthage? = nil, cocoapods: Cococapods? = nil) {
        self.carthage = carthage
        self.cocoapods = cocoapods
    }
}
 
extension Dependencies {
    public struct Carthage: Codable, Equatable {
        let option: Options
        let dependencies: [Dependency]
        
        init(option: Options, dependencies: [Dependency])
    }
    
    public struct Cococapods: Codable, Equatable {
        // TODO:
    }
}

extension Dependencies.Carthage {
    struct Options {
        let useXCFrameworks: Bool
    }
    
    struct Dependency {
        let origin: Origin
        let requirement: Requirement
    }
    
    public enum Origin: Codable, Equatable {
        case github(path: String)
        case git(path: String)
        case binary(path: String)
    }

    public enum Requirement: Codable, Equatable {
        case exact(Version)
        case upToNext(Version)
        case atLeast(Version)
        case branch(String)
        case revision(String)
    }
}
```

Example of usage:

```swift
let dependencies = Dependencies(
    carthage: .init(
        option: .init(useXCFrameworks: true),
        dependencies: [
            .init(origin: .github(path: "foo/bar"), requirement: .exact("1.1.1"))
        ]
    )
)
```

CC @fortmarek @pepibumur @bolismauro 

@facumenzella (structs replaces enums again :P )

**Comment by bolismauro** [comment]
I like your proposal better @laxmorek.
I thought keeping backward compatibility was a must have, and that's the reason for the original proposal. However, I think that this is more clean :)

I'm not sure how far you want to go, but we can also allow everyone to specify arbitrary commands.
For instance

```swift
extension Dependencies.Carthage {
  struct Option {
    let name: String
	let parameters: String?

	// NB: here we should handle parameters better
    var cliFlag: String { "--\(self.name) \(self.parameters)" }

    static var useXCFrameworks: Self = .init(name: "use-xcframeworks", parameters: nil)
    static func platforms(_ platforms: Platform...) {
       .init(name: "platform", parameters platforms.map({ $0.rawValue }).join(",")
    }
  }

  enum Platform { ... }
}
```

usage
```swift
let dependencies = Dependencies(
    carthage: .init(
        options: [
			.useXCframeworks,
			.platforms(.iOS, .macOS),
            .init(name: "not-mapped", parameters: "some value")
        ]
        dependencies: [
            .init(origin: .github(path: "foo/bar"), requirement: .exact("1.1.1"))
        ]
    )
)
```

If there is some parameter we must be sure it is there, we can make `Option` Hashable, make `options` a Set, check if the user has added that flag and if not, add it (or something on this line).

Going back to backward compatibility; Truth to be told, we can keep source compatibility with the current `Dependencies.swift` file, but it would require to keep the current enum around. What's the approach you guys follow in these cases?

PS: Our teams don't install tools globally, but locally. I was thinking how to make this available by passing a path. This is a lot away from this proposal, but it may impact the struct shape as well. Should I open another issue?

**Comment by laxmorek** [comment]
> PS: Our teams don't install tools globally, but locally. I was thinking how to make this available by passing a path. This is a lot away from this proposal, but it may impact the struct shape as well. Should I open another issue?

I have started to think about including `carthage` binary into `tuist` but it will be another discussion. We don't want to make `tuist` too big.

> PPS: @laxmorek please let me know if you don't have time to work on this. I'm trying to familiarize with Tuist and this may be a good step in knowing the codebase better. Not sure how difficult it would be for a novice to perform this change though

I want to work on it because this proposal may introduce bigger changes so I want to keep an eye on it. I will code it but lets figure out it together. :) 

> Going back to backward compatibility; Truth to be told, we can keep source compatibility with the current Dependencies.swift file, but it would require to keep the current enum around. What's the approach you guys follow in these cases?

These are early days of `Dependencies.swift`. I think we can still be adjusting it.

**Comment by bolismauro** [comment]
For the Carthage binary I agree that it would be not ideal to include it in Tuist. I think that a parameter with the path will do. We can discuss it in a separated pr :D


Sure for the changes! Feel free to ping me for feedback or other things

**Comment by dharr419-ford** [comment]
> I have started to think about including carthage binary into tuist but it will be another discussion. We don't want to make tuist too big.

Would rather have something in the config to take in the path if anything, vendoring these tools does increase the size of the tuist bundle. I'm already not a huge fan of it using vendored swiftlint and pretty-print binaries at the moment
