### ISSUE TITLE
Linting incorrectly identifies both framework and app targets as libraries

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#251]
**Describe the bug**
The linting wrongfully identifies (?) my framework target, test target and app target as libraries.
Getting unexpected errors.

```
...
Target ModuleName cannot contain resources. Libraries don't support resources.
Target ModuleNameTests cannot contain resources. Libraries don't support resources.
Target ModuleNameApp cannot contain resources. Libraries don't support resources.
...
```

**Setup**
```swift
let project = Project(
  name: "ModuleName",
  targets: [
    Target(name:"ModuleName",
      platform: .iOS,
      product: .framework,
      bundleId: "com.organization.ModuleName${BUNDLE_SUFFIX}",
      infoPlist: "Info.plist",
      sources: "Sources/**",
      resources: "Resources/**"
    ),
    Target(name: "ModuleNameTests",
      platform: .iOS,
      product: .unitTests,
      bundleId: "com.organization.ModuleNameTests${BUNDLE_SUFFIX}",
      infoPlist: "Tests.plist",
      sources: "Tests/**",
      resources: "Resources/**"
    ),
    Target(name: "ModuleNameApp",
      platform: .iOS,
      product: .app,
      bundleId: "com.organization.ModuleNameApp${BUNDLE_SUFFIX}",
      infoPlist: "App.plist",
      sources: "AppSources/**",
      resources: "AppResources/**"
    )
  ]
)
```

**Expected behavior**
I expect apps and frameworks to be able to bundle resources.

**Comment by kwridan** [comment]
Hi @enhorn thanks for flagging this!

Looks like this has been fixed on [master](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Linter/TargetLinter.swift#L109) via a different (PR #194) by @ollieatkinson 

It'll be in the next release - you can build from source to test it out.

**Comment by pepibumur** [comment]
In case you don't know about it @enhorn, there's an easy way to test the latest commit on master in your project. Just run the following command on the project's directory:

```
tuist local master
```

It'll pull, compile and install the latest commit on master so that you can try it on your project. Let us know if it works so that we can close the issue.

**Comment by enhorn** [comment]
Thanks @kwridan & @pepibumur, not getting this anymore when generating with `master`. :-)
