### ISSUE TITLE
UnitTests with `Host Application` broken linking when using static libraries as dependencies

### ISSUE THREAD

**Issue by fila95** [tuist/tuist#2523]
**Describe the bug**
I have a problem with a project I’m generating with Tuist, and I think I might have found a bug 🐛 

We have an implementation target to be tested, and the test target that requires to be run using a demo target as host application.
As reported [here](https://tuist.io/docs/dependencies/local/), we have set the demo target as dependency of the test target so that it is automatically set as Host application.
When doing so, the implementation target is somehow automatically removed from the `Link Binary With Libraries` `Build Phase` of the test target.
This make the linking fail as the test target seems to not be able to link symbols that are defined in the implementation target and not used by the demo.
We are using `staticLibraries` product type for our targets. It seems that if we use `framework` the `Link Binary With Libraries` is correct instead and everything works properly.

**To Reproduce**

1. Download the Attached project
2. Generate project with command `tuist generate`
3. Run UnitTests
5. Notice that if in `Project.swift` `staticLibrary` is replaced with `framework` tests will run perfectly

**Expected behavior**
Tests should find all the symbols from the targets assigned to them

**Screenshots**
Linking error:
<img width="854" alt="compile_error" src="https://user-images.githubusercontent.com/7265334/108053834-37271400-704e-11eb-80f2-d9b1da9f11fc.png">

Project build settings with static libraries and demo as tests dependency target:
<img width="862" alt="with_static_lib_and_demo" src="https://user-images.githubusercontent.com/7265334/108053845-3aba9b00-704e-11eb-9b11-2254f9a2dd55.png">

Project build settings with framework and demo as tests dependency target:
<img width="862" alt="with_framework_and_demo" src="https://user-images.githubusercontent.com/7265334/108053847-3b533180-704e-11eb-8417-b62614cf0ba6.png">

Project build settings with only the static library as tests dependency target:
<img width="864" alt="with_static_lib_no_demo" src="https://user-images.githubusercontent.com/7265334/108053850-3b533180-704e-11eb-9c5b-8bff7da5d826.png">

**Desktop (please complete the following information):**

- OS: macOS
- OS Version: 11.2 (20D64)
- Tuist Version: 1.34.0

**Additional context**
[test_project.zip](https://github.com/tuist/tuist/files/5988064/test_project.zip)

**Comment by fortmarek** [comment]
Hi @fila95, thanks a lot for the issue and for the demo project!
The heart of the issue lies [here](https://github.com/tuist/tuist/blob/main/Sources/TuistCore/ValueGraph/ValueGraphTraverser.swift#L273)

I found a bug linked to this from a long time ago [here](https://github.com/tuist/tuist/issues/658)

AFAICT:
If we added the static library to the unit tests target, it could lead to duplicated symbols.
You can easily reproduce this by adding `libA.a` to `ATests` plus adding `-all_load` to `OTHER_LDFLAGS`.

I think this might be an issue in how your project is setup and not in tuist.

Let me know if that makes sense or if you think there is a solution to this that could help you.

**Comment by kwridan** [comment]
The sample project is really helpful, thanks @fila95 !

Ouch looks like there are more edge cases than we originally knew!

@fortmarek is right, the logic we see was added on purpose (by past me 😅), the sample project indeed highlights the issue and brings to light a few interesting observations.

### Swift Only Code + Static Libraries (`.a` products)

In the sample project, the Swift struct can't be resolved at build time in the test target. Interestingly the view controller can, if we change the test to:

```swift
class Tests: XCTestCase {
  func test_testModels() {
    // let model = TestStruct(name: "123", number: 100)
    // model.log()
    let vc = ViewController()
    print(vc)
  }
}
```

The test successful builds and runs!

The behaviour for Swift only vs ObjC backed types differs here.

### Static Libraries (`.a` products) vs Static Frameworks (`.framework` products)

Changing the product type from a `.staticLibrary` to a `.staticFramework` gets the sample project tests to run successfully.

```swift
let targetA = Target(
  name: "A",
  platform: .iOS,
  product: .staticFramework,
  bundleId: "targetA",
  infoPlist: .default,
  sources: [
    .init(.relativeToRoot("Targets/A/**"))
  ],
  dependencies: []
)
```

_In Tuist there's another product type called `.staticFramework` which is similar to `.staticLibrary` except the final packaged product is a `.framework` (it sets the build setting `MACH_O_TYPE` to `staticlib`). The framework packaging is easier to deal with especially when it comes to mixed language modules with headers._

### Using the symbols in the app

Going back to the original `.staticLibrary` product type, the sample will work as long as the symbols are used in the host application.

e.g.

```swift
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {

    let model = TestStruct(name: "test", number: 12)
    model.log()

    self.window = UIWindow(frame: UIScreen.main.bounds)
    self.window?.rootViewController = ViewController()
    self.window?.makeKeyAndVisible()
    return true
  }
}

```

If we update `AppDelegate` to use the `TestStruct`, the sample project tests build and run!

---

Perhaps switching to `.staticFramework` would solve your immediate issue @fila95 ? 

🤔 Not sure how best to model the `.staticLibrary` use case where symbols aren't used by the host application while also avoiding duplicate symbols for the ones that are ...

**Comment by kwridan** [comment]
Ah small update:

Actually, using any symbol from the static library in the host app will fix the issue (doesn't have to be the exact one used in the test). If non of the code from `A` is needed in the App target, perhaps the app target doesn't need to depend on `A` and only the test target does? (in that scenario the test target will explicitly link `A`).

Hope this helps!

**Comment by danyf90** [comment]
Hi @fortmarek @kwridan, many thanks you for your help 🙌 

We are trying to proceed as you have suggested, but it looks like staticFrameworks are not allowed as dependency of a share extension:
```swift
            LintableTarget(platform: .iOS, product: .appExtension): [
            LintableTarget(platform: .iOS, product: .staticLibrary),
            LintableTarget(platform: .iOS, product: .dynamicLibrary),
            LintableTarget(platform: .iOS, product: .framework),
        ],
```

Could you please let us know whether there is a reason why it is not allowed, or if you think it is a misconfiguration fo the linter?

**Comment by fortmarek** [comment]
I believe there is not a specific reason - would you like to create a PR for that?

**Comment by danyf90** [comment]
@fortmarek opened the PR here
