### ISSUE TITLE
Not Inheriting Dependencies Dependencies

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#253]
Trying to get rid of my autogenerated list of dependencies. 😇

**Describe the bug**
- Project A
  - Framework A
    - Dependencies: [
      **Framework**("CarthageA"),
      **Framework**("CarthageB")
    ]
  - UnitTests A
    - Dependencies: [**Target**("Framework A")]
  - Project App A
    - Dependencies: [**Target**("Framework A")]

- Project B
  - Framework B
    - Dependencies: [
      **Project**("Project A", "../ProjectA"),
      **Framework**("CarthageC"),
      **Framework**("CarthageD")
    ]
  - UnitTests B
    - Dependencies: [**Target**("Framework B")]
  - Project App B
    - Dependencies: [**Target**("Framework B")]

- Project C
  - Framework C
    - Dependencies: [
      **Project**("Project A", "../ProjectA"),
      **Project**("Project B", "../ProjectB"),
      **Framework**("CarthageE"),
      **Framework**("CarthageF")
    ]
  - UnitTests C
    - Dependencies: [**Target**("Framework C")]
  - Project App C
    - Dependencies: [**Target**("Framework C")]

Building any of the three targets of `Project C` fails with:
`ld: warning: Could not find auto-linked framework 'CarthageA'`
`ld: warning: Could not find auto-linked framework 'CarthageB'`
…
`ld: symbol(s) not found for architecture x86_64`

A simplified graph of the dependencies:
![dependecies](https://user-images.githubusercontent.com/657370/53802996-9cf26200-3f43-11e9-83a9-80f32af01c78.png)

Pink boxes = Project A
Green Box = Project B
Blue Box = Project C

**Expected behavior**
I expect that the dependencies from `Project A -> Framework A` would be included in the dependencies in `Project C -> Framework C` (and the other two targets in `Project C`).

**Example project definition**
```swift
let settings = Settings(
  base: [:],
  debug: Configuration(xcconfig: "../Configurations/debug.xcconfig"),
  release: Configuration(xcconfig: "../Configurations/release.xcconfig")
)

let project = Project(
  name: "AppModule1",
  settings: settings,
  targets: [
    Target(name: "AppModule1",
      platform: .iOS,
      product: .framework,
      bundleId: "com.company.AppModule1",
      infoPlist: "Info.plist",
      sources: "Sources/**",
      resources: "Resources/**",
      dependencies: [
        .project(target: "NetworkAndModels", path: "../NetworkAndModels"),
        .project(target: "UIComponents", path: "../UIComponents"),
        .project(target: "CombinedFramework", path: "../CombinedFramework")
      ],
      settings: settings
    ),
    Target(name: "AppModule1App",
      platform: .iOS,
      product: .app,
      bundleId: "com.company.AppModule1App",
      infoPlist: "Info.plist",
      sources: "Sources/**",
      resources: "Resources/**",
      dependencies: [
        .target(name: "AppModule1")
      ],
      settings: settings
    )
  ]
)
```

Perhaps I'm missing something?

**Comment by pepibumur** [comment]
No, it's clearly a bug. Thanks for reporting it so clearly described.

**Comment by Rag0n** [comment]
Even simple transitive dependencies doesn't work(.framework):

**Project.swift:**
```
let project = Project(name: "TuistSample",
                      targets: [
                        Target(name: TuistSample",
                               platform: .iOS,
                               product: .app,
                               bundleId: "io.github.ragon.tuistSample",
                               infoPlist: "Info.plist",
                               sources: "Sources/**",
                               dependencies: [
                                    .project(target: "Core", path: "../../Core"),
                                ])
                      ])
```

**Core's Project.swift**
```
let project = Project(name: "Core",
                      targets: [
                        Target(name: "Core",
                               platform: .iOS,
                               product: .framework,
                               bundleId: "io.github.ragon.Core",
                               infoPlist: "Info.plist",
                               sources: "Sources/**",
                               dependencies: [
                                    .framework(path: "../Carthage/Build/iOS/RxSwift.framework")
                                ]),
                      ])
```

After project generation RxSwift is not embeded into the ios application and therefore it crashes with "Reason: image not found"

**Comment by ollieatkinson** [comment]
AFAIK this can be solved by introducing this into the graph linker: 
```swift
        let transitiveFrameworks = findAll(targetNode: targetNode, test: isFramework)
            .map(\.path)
            .map(DependencyReference.absolute)

        references.append(contentsOf: transitiveFrameworks)
```

Let me check it, write a fixture test and push up the code;
