### ISSUE TITLE
Tuist template with directory

### ISSUE THREAD

**Issue by sarunw** [tuist/tuist#2535]
## What 🌱

Right now tuist template only supports files.

When I try to copy a directory over with the following template. (`foo` is a directory).
``` 
import ProjectDescription
let nameAttribute: Template.Attribute = .required("name")
let template = Template(
    description: "Custom template",
    attributes: [
        nameAttribute,
        .optional("platform", default: "ios"),
    ],
    files: [
        .string(path: "Project.swift",
                contents: "My template contents of name \(nameAttribute)"),
        .file(path: "generated/Up.swift",
              templatePath: "generate.stencil"),
        .file(path: "foo", templatePath: "foo"),
    ]
)
```

I got the following error.

```
We received an error that we couldn't handle:
    - Localized description: The file “foo” couldn’t be opened because you don’t have permission to view it.
    - Error: Error Domain=NSCocoaErrorDomain Code=257 "The file “foo” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/mypath/Tuist/Templates/sarunw/foo, NSUnderlyingError=0x7f7fd5d14a20 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}"
```

## Context 🕵️‍♀️
I want to copy something as is like Asset Catalog
![image](https://user-images.githubusercontent.com/795368/108316181-1ea22f80-71ef-11eb-9374-5947f7108484.png)

## Proposal 🎉

Do you have any plan to support directory copy? Is it something that makes sense for Tuist?

**Comment by fortmarek** [comment]
Hi @sarunw!

This is already supported if you do the following:
```
.file(path: "AppIcon.appiconset/Contents.json", templatePath: "Contents.json")
```

I agree though that it is something we should support more intuitively.

I propose to add `.folder(path: "Assets.xcassets", templatePath: "path-to-template-assets")` to `files` property which would simply copy the folder to `path`.

I think this would be nice, non-intrusive addition. What do you think, @sarunw? Would you like to go ahead and implement this? 🙂

**Comment by sarunw** [comment]
@fortmarek Sure, do I need to create RFC for this, or can I start doing it?

**Comment by fortmarek** [comment]
I don't think this necessitates RFC as the scope of the changes this introduces should be quite small, so you might just skip that step and start with the implementation 🙂 if you need some earlier feedback, you can create a draft PR before you polish the PR to a mergeable state.

**Comment by sarunw** [comment]
@fortmarek Thanks, any place where I can ask about the project if I got a question?

**Comment by fortmarek** [comment]
We have [slack](https://slack.tuist.io/) where you can ask some more specific questions related to the development.

As for the implementation, you'll have to update `Template` models in `ProjectDescription` and `TuistCore`, afterwards you can adjust `TemplateGenerator`.

**Comment by danyf90** [comment]
[directory](https://github.com/tuist/tuist/blob/01bd219713bc270b571b2937bc1fc52799518ae7/Sources/ProjectDescription/Template/Template.swift#L77) is now available :tada:
