### ISSUE TITLE
Project packages: Missing "name" for Swift Packages

### ISSUE THREAD

**Issue by innoreq** [tuist/tuist#2547]
**Describe the bug**
When specifying a package for the related list as Project parameter, it is not possible to specify a name:
```
	.package(name: "ComposableArchitecture",
			 url: "https://github.com/pointfreeco/swift-composable-architecture",
			 .upToNextMajor(from: "0.13.0")),
```

This leads to an error "extra argument in call".

Without the name, the "tuist generate" command leads to this error:

```
xcodebuild: error: Could not resolve package dependencies:
  declared name 'ComposableArchitecture' for package dependency 'https://github.com/pointfreeco/swift-composable-architecture' does not match the actual package name 'swift-composable-architecture'
  dependency 'ComposableArchitecture' in target 'HFDataAccessTests' requires explicit declaration; reference the package in the target dependency with '.product(name: "ComposableArchitecture", package: "swift-composable-architecture")' and provide the name of the package dependency with '.package(name: "swift-composable-architecture", url: "https://github.com/pointfreeco/swift-composable-architecture", from: "0.13.0")'
  dependency 'ComposableArchitecture' in target 'HFDataAccess' requires explicit declaration; reference the package in the target dependency with '.product(name: "ComposableArchitecture", package: "swift-composable-architecture")' and provide the name of the package dependency with '.package(name: "swift-composable-architecture", url: "https://github.com/pointfreeco/swift-composable-architecture", from: "0.13.0")'
```

**Expected behavior**
It should be possible to specify packages with all options as in the SPM in a normal Xcode project.

**Comment by fortmarek** [comment]
Hi @innoreq!

To integrate `ComposableTuistArchitecture` you can take inspiration [here](https://github.com/fortmarek/ComposableTuistArchitecture/blob/master/Projects/ComposableTuistArchitecture/Project.swift)

You'll need to add it to `packages` and then a `.product` to `dependencies`.

**Comment by fortmarek** [comment]
You are right it is not possible to adjust the name of the package but afaict this is only reflected in the Xcode's sidebar in the list of packages and does not have a real impact on the project itself as you are integrating the products and not the whole package. This is probably something we could add but it's more of a cosmetic change rather than anything else (unless I'm missing something)

**Comment by innoreq** [comment]
Cool, thanks - it's working. What was needed:

```
let target = Target(...
dependencies: [
	.package(product: "ComposableArchitecture"),
	.package(product: "CasePaths"),
]
...

let project = Project(...
packages: [
		.remote(
			url: "https://github.com/pointfreeco/swift-composable-architecture",
			requirement: .upToNextMajor(from: "0.14.0")
		),
	],
...
```
