### ISSUE TITLE
Library search path build setting is not set

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#256]
**Describe the bug**
Generated projects fail to build when depending on c / Objective-C static libraries.

**To Reproduce**

- Given a prebuilt static library, headers and a module map

e.g.
```
prebuilt/
├── include
│   └── ObjcStaticLibrary
│       ├── LibraryClass.h
│       ├── ObjcStaticLibrary.h
│       └── module.modulemap
└── libObjcStaticLibrary.a
```

- Add a dependency on that static library

e.g.

```swift
let project = Project(name: "App",
                      targets: [
                          Target(name: "App",
                                 platform: .iOS,
                                 product: .app,
                                 bundleId: "io.tuist.App",
                                 infoPlist: "Info.plist",
                                 sources: "Sources/**",
                                 dependencies: [
                                     .library(path: "prebuilt/libObjcStaticLibrary.a", publicHeaders: "prebuilt/include", swiftModuleMap: nil)
                          ])
               ])

```

- run `tuist generate`
- build the generated project

*build fails!*

**Expected behavior**
The generated project should build with the following error:

```
ld: library not found for -lObjcStaticLibrary
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Additional context**

Investigating this further, it seem's the `LIBRARY_SEARCH_PATHS` build setting is not set. 
Setting it to `$(SRCROOT)/prebuilt` fixes the issue.

Let me know if I made some false assumptions in my setup

**Comment by pepibumur** [comment]
That seems a legit issue. Good catch @kwridan
