### ISSUE TITLE
Add `--skip-ui-tests` parameter to `tuist test` command to skip UI Tests targets from being executed

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#2562]
## Context 🕵️‍♀️

`tuist test` command runs tests for a project and all targets. However, in some cases, there may be a need to exclude some test targets from execution. For example, a project can contain a UI Tests target which is very time consuming to run. To mitigate this issue one might have a dedicated workflow on CI to run only UI Tests and a separate one for Unit Tests. 

## Proposal 🎉

I'd like to propose new parameter to add to `tuist test` command:

```bash
OPTIONS:
--skip-ui-tests       Skip UI Tests targets when testing 
```

The example:

```
$ tuist test --skip-ui-tests
```

Kudos to @fortmarek for the idea 👏 

Edited: changed an option from `--skip` to `--skip-ui-tests`.

**Comment by fortmarek** [comment]
For starters we could maybe add `--skip-ui-tests` which would skip all UI tests instead of you having to specify which ones and see if there is a need for a more granular approach in form of `--skip {list of targets}`. What do you think, @mollyIV?

We could also similarly add `--skip-unit-tests`.

**Comment by mollyIV** [comment]
I guess we could do that. However, if there was a need to introduce more granular approach in form of `--skip {list of targets}`, we'd need to introduce a precedence for the options. Let's say we had a project with the following structure:

```
MyApp
  - MyApp
  - FrameworkA
  - FrameworkB
  - FrameworkATests
  - FrameworkBTests
```

and we would run: 

```bash
$ tuist test --skip-unit-tests --skip FrameworkA
```

Would we skip all the unit tests or only a `FrameworkA`? 

To solve the above, precedence for options would be required. It could be an extra complexity for an end user. 

Thoughts? 🤔

**Comment by fortmarek** [comment]
I think precedence per se is not necessary - if I want to skip unit tests plus I specify FrameworkA, I'd expect both unit tests and FrameworkA to be skipped. But I hope if we introduce `--skip-unit-tests` and UI tests, there won't be a real need to introduce `--skip`.

**Comment by mollyIV** [comment]
> if I want to skip unit tests plus I specify FrameworkA, I'd expect both unit tests and FrameworkA to be skipped.

Hmm, it sounds ambiguous, doesn't it? Anyways, let's maybe not think that ahead and indeed, there may be not a need for more granularity when skipping the tests 👍 Let me update the issue description.
