### ISSUE TITLE
Support playgrounds inside of a workspace (and maybe other document formats too)

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#258]
Currently the Workspace.swift is a great way to organise what projects you want in your workspace. It would be awesome to add support for playground books too. 

Adding support for _other_ kinds of documents inside of workspace would be great too. I would really like support for the following:

- Playground's
- Folder references (like SwiftPM)
- Markdown documentation

---

See: 

https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Workspace.swift

**Comment by kwridan** [comment]
This will actually help out the library too 👍 (to allow adding manifest files - second to last item in #205) 

I would perhaps also add the ability to specify project level files too - e.g. Each project may have a README, documentation etc..

```swift
class Workspace {
     // ...
      var additionalFiles: [String] 
}
```

```swift
class Project {
     // ...
      var additionalFiles: [String] // those will be in the project hierarchy but not in any build phase
}
```

Or possibly even follow SwiftPMs everything that isn't defined is a reference? (less configuration)

**Comment by pepibumur** [comment]
> Or possibly even follow SwiftPMs everything that isn't defined is a reference? (less configuration)

Not a big fan of that though. Thoughts @ollieatkinson / @marciniwanicki ?

**Comment by ollieatkinson** [comment]
I'm not too convinced we should put everything in the workspace, but maybe it's a feature we could offer as part of the workspace settings.

How about some API similar to this?

```swift
let workspace = Workspace(
    name: "Project",
    elements: [
        .project(path: "MyFramework"),
        .file(path: "path/to/some.file"),
        .group(name: "SampleApps", contents: [
            .project(path: "SampleApps/X"),
            .project(path: "SampleApps/Y"),
        ]),
        .group(name: "Carthage", contents: [
            .file(path: "Carthage/Checkouts/RxSwift/RxSwift.xcodeproj"),
            .file(path: "Carthage/Checkouts/OtherFramework/OtherFramework.xcodeproj"),
        ])
    ]
)
```

**Comment by pepibumur** [comment]
If the project `SampleApps/X` depends on an project that is not defined in the workspace, what would you do?

**Comment by ollieatkinson** [comment]
I think we have a couple options here:

1. Fail during linting
2. Automatically include them inside the workspace under a "Dependencies" group

Not sure what I think is best, is there anything I have missed?
