### ISSUE TITLE
[Spike] Xcode 12.5b2, Swift Package Manager and Dynamic Linking

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#2597]
## Context 🕵️‍♀️

Xcode 12.5 has now introduced some new behaviour to allow for package manager products to be linked to multiple dynamic products, wether they be frameworks, test bundles or apps. 

> The Swift Package Manager now builds package products and targets as dynamic frameworks automatically, if doing so avoids duplication of library code at runtime. (59931771) (FB7608638)

## What 🌱

For clarity, I have opened this issue to track any findings so we can reference or revisit in the future through the GitHub search.

**Comment by ollieatkinson** [comment]
Using the fixture `ios_app_with_local_swift_package` as a base I phrased it such that `Frameworks/FrameworkA` is a dynamic framework by changing the manifest to the following:

```diff
import ProjectDescription

let project = Project(
    name: "FrameworkA",
    packages: [
        .package(path: "../../Packages/PackageA")
    ],
    targets: [
        Target(
            name: "FrameworkA",
            platform: .iOS,
-           product: .staticFramework,
+           product: .framework,
            bundleId: "io.tuist.FrameworkA",
            infoPlist: "Config/FrameworkA-Info.plist",
            sources: "Sources/**",
            dependencies: [
                .package(product: "LibraryA"),
            ]
        )
    ]
)
```

By doing this and generating the Tuist project we run into a problem when trying to compile. 

```
CodeSign /Users/oliver/Library/Developer/Xcode/DerivedData/App-amvgzvqlaxiepcgkydmhwrhyymvg/Build/Products/Debug-iphonesimulator/FrameworkA.framework/Frameworks/LibraryA_-45B7D7FD329DE2E2_PackageProduct.framework/Versions/A (in target 'FrameworkA' from project 'FrameworkA')
    cd /Users/oliver/Development/Tuist/fixtures/ios_app_with_local_swift_package/Frameworks/FrameworkA
    export CODESIGN_ALLOCATE\=/Applications/Xcode-12.5-beta2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
    Signing Identity:     "-"
    
    /usr/bin/codesign --force --sign - --timestamp\=none --preserve-metadata\=identifier,entitlements,flags /Users/oliver/Library/Developer/Xcode/DerivedData/App-amvgzvqlaxiepcgkydmhwrhyymvg/Build/Products/Debug-iphonesimulator/FrameworkA.framework/Frameworks/LibraryA_-45B7D7FD329DE2E2_PackageProduct.framework/Versions/A

/Users/oliver/Library/Developer/Xcode/DerivedData/App-amvgzvqlaxiepcgkydmhwrhyymvg/Build/Products/Debug-iphonesimulator/FrameworkA.framework/Frameworks/LibraryA_-45B7D7FD329DE2E2_PackageProduct.framework/Versions/A: bundle format unrecognized, invalid, or unsuitable
Command CodeSign failed with a nonzero exit code
```

Peeking inside of the built FrameworkA.framework we can see Xcode has tried to generate a dynamic framework and embed it in the Frameworks directory:

![image](https://user-images.githubusercontent.com/1382565/109554274-eabaea00-7acb-11eb-859b-fa4e5590a64b.png)

This may pose us some problems and will still result in duplicate code, just no warning. Having no control over this is likely going to cause us some troubles as Xcode at build-time can just change how they want to link the products

**Comment by ollieatkinson** [comment]
I created a post on the swift forums asking if it’s possible to disable the behaviour: https://forums.swift.org/t/xcode-12-5-and-automatic-dynamic-linking-of-products/45197

This would at least give us some control and avoid breaking anyones build when upgrading to Xcode 12.5

**Comment by ollieatkinson** [comment]
https://forums.swift.org/t/swift-packages-in-multiple-targets-results-in-this-will-result-in-duplication-of-library-code-errors/34892/52

Acknowledgement of the code signing problems in Xcode 12.5

**Comment by danyf90** [comment]
Closed in favor of Dependencies.swift
