### ISSUE TITLE
commitlint can't be setup with `tuist up`

### ISSUE THREAD

**Issue by innoreq** [tuist/tuist#2601]
**Describe the bug**
Setup.swift defines this:
```
let setup = Setup([
	.homebrew(packages: ["swiftlint"]),
	.homebrew(packages: ["swiftformat"]),
	.homebrew(packages: ["sourcery"]),
	.homebrew(packages: ["bartycrouch"]),
	.homebrew(packages: ["swiftgen"]),
	.homebrew(packages: ["npm"]),
	.custom(name: "commitlint",
			meet: ["/usr/local/bin/npm install --save-dev @commitlint/{config-conventional,cli}"],
			isMet: ["commitlint"])
])
```

While all homebrew stuff are handled correctly, commitlint can't be installed due to this error:

```
We received an error that we couldn't handle:
    - Localized description: The operation couldn’t be completed. (TSCBasic.Process.Error error 0.)
    - Error: could not find executable for '/usr/local/bin/npm install --save-dev @commitlint/{config-conventional,cli}'"
```

When executing the installation command on the terminal, everything's working fine.

Based on the docs, I think that the usage is correct, so there might be some other problem that I can't figure out.

**Expected behavior**
Swiftlint should be installed via npm.

**Desktop (please complete the following information):**

OS: macOS 11.2.2
Xcode: Version 12.4 (12D4e)

**Comment by innoreq** [comment]
May be a problem with npm, though closing the issue for the moment.

**Comment by innoreq** [comment]
I caught the wrong npm installation command (did never use npm, though...). The correct one is:

```
npm install -g @commitlint/cli @commitlint/config-conventional
```

Executing this on the command line works finde, and `commitlint` can be called after that.

Using this command line for tuist:

```
let setup = Setup([
	.homebrew(packages: ["swiftlint"]),
	.homebrew(packages: ["swiftformat"]),
	.homebrew(packages: ["sourcery"]),
	.homebrew(packages: ["bartycrouch"]),
	.homebrew(packages: ["swiftgen"]),
	.homebrew(packages: ["npm"]),
	.custom(name: "commitlint",
			meet: ["/usr/local/bin/npm install -g @commitlint/cli @commitlint/config-conventional"],
			isMet: ["commitlint"])
])
```

and executing `tuist up` leads to the same error:

We received an error that we couldn't handle:
    - Localized description: The operation couldn’t be completed. (TSCBasic.Process.Error error 0.)
    - Error: could not find executable for '/usr/local/bin/npm install -g @commitlint/cli @commitlint/config-conventional'"
```

**Comment by pepibumur** [comment]
Tuist up is [going away](https://github.com/tuist/tuist/pull/3443) in the next major release 2.0 and therefore I'm closing this issue.
