### ISSUE TITLE
Hide/Show Scheme

### ISSUE THREAD

**Issue by migfabio** [tuist/tuist#2603]
**Describe the bug**
It's not possible, at the moment, specify in the manifest what scheme we could hide/show. The reason behind that is for a monorepo project with microfeatures, will be a pain having tons of schemes in the main app project.

**Screenshots**
![Screenshot 2021-03-03 at 12 19 47](https://user-images.githubusercontent.com/4320402/109808277-cde2fb80-7c1e-11eb-9ec1-ac72ebc543a5.png)

What do you guys think about it? Would be nice to have this feature in Tuist? Is there any workaround?

**Comment by fortmarek** [comment]
Hi @migfabio!

Thanks for raising this.

While this is something we could definitely add, I share a concern already raised [here](https://github.com/tuist/tuist/issues/2448#issuecomment-774184156).

There are two ways to achieve having not all autocreated schemes:
- add option to disable autocreate schemes
- add option to hide schemes

I'd be rather for adding option to disable autocreate schemes as for hiding a scheme you'd need to first define it in `Project.swift` and hiding it which is a little bit cumbersome.

One way to ensure that users are not hindered by the number of options in `Project.swift` while also enabled it is to add `Project.generationOptions` mentioned [here](https://github.com/tuist/tuist/discussions/2564#discussioncomment-404421).

We could also change the flag `disableAutogeneratedSchemes` to also include schemes created by Xcode but it'd be a breaking behavior, so the former option might be a better fit.

**Comment by migfabio** [comment]
Thanks for you answer @fortmarek 

I understand your concerns. I am wondering if I am the only one facing this "annoyance" or others feel the same.

The request comes because I am converting a project from Cocoapods. I don't want to end up creating a sort of `Pods` project to achieve this 😄 
But I also understand that probably it's not valuable to create a breaking behaviour.

**Comment by fortmarek** [comment]
@tuist/core any additional thoughts? I think `Project.generationOptions` might be the best way to achieve this.

**Comment by fortmarek** [comment]
`Project.generationsOptions` is something we'd like to incorporate anyways and this is a good candidate, so if you want to take this on @migfabio, feel free, I can send you some pointers if needed 🙂

**Comment by kwridan** [comment]
👋

> I'd be rather for adding option to disable autocreate schemes as for hiding a scheme you'd need to first define it in Project.swift and hiding it which is a little bit cumbersome.

+1 and would easily go out of sync if new targets are added etc...

> @tuist/core any additional thoughts? I think `Project.generationOptions` might be the best way to achieve this.

I believe so, though before making changes, we can quickly examine the final outcome by setting the existing config option which does this today:

e.g. https://github.com/tuist/tuist/blob/main/fixtures/ios_app_with_custom_configuration/Tuist/Config.swift

```swift
import ProjectDescription

let config = Config(
  generationOptions: [
    .disableAutogeneratedSchemes
  ]
)
```

This will prevent Tuist from generating any of schemes automatically (any manually defined schemes will still be generated). 

@migfabio worth giving that a try on your project to see if it helps reduce the schemes?

From my testing, it will produce less schemes _(e.g. test targets will no longer have a scheme auto generated for them automatically)_, but sadly won't prevent Xcode from auto-generating schemes for each target 😞

Suppressing / Hiding Xcode auto-generated schemes could be investigated further if there's interest by examine what files Xcode modifies and if its feasible for Tuist to control / modify them.

**Comment by migfabio** [comment]
Hi @kwridan! I've already enabled that configuration. Yes, it reduced a little bit, but the project has some sort of 10/12 µ-modules (+ each module has its own hosting app 😅)

> Suppressing / Hiding Xcode auto-generated schemes could be investigated further if there's interest by examining what files Xcode modifies and if its feasible for Tuist to control / modify them.

I can start this investigation and report it back here

**Comment by fortmarek** [comment]
> I can start this investigation and report it back here

that'd be appreciated @migfabio, it'd be helpful how this works in Xcode under the hood 🙂

**Comment by migfabio** [comment]
@fortmarek I've created two simple frameworks and one app and add them into a Workspace. This is the directory tree structure

<details>
  <summary>Click here to see the directory tree</summary>

```
.
├── ModuleA
│   ├── ModuleA
│   ├── ModuleA.xcodeproj
│   │   ├── project.xcworkspace
│   │   │   ├── xcshareddata
│   │   │   └── xcuserdata
│   │   │       └── fmignogna.xcuserdatad
│   │   ├── xcshareddata
│   │   │   └── xcschemes
│   │   └── xcuserdata
│   │       └── fmignogna.xcuserdatad
│   │           └── xcschemes
│   └── ModuleATests
├── ModuleB
│   ├── ModuleB
│   ├── ModuleB.xcodeproj
│   │   ├── project.xcworkspace
│   │   │   ├── xcshareddata
│   │   │   └── xcuserdata
│   │   │       └── fmignogna.xcuserdatad
│   │   ├── xcshareddata
│   │   │   └── xcschemes
│   │   └── xcuserdata
│   │       └── fmignogna.xcuserdatad
│   │           └── xcschemes
│   └── ModuleBTests
├── MyApp
│   ├── MyApp
│   │   ├── Assets.xcassets
│   │   │   ├── AccentColor.colorset
│   │   │   └── AppIcon.appiconset
│   │   └── Base.lproj
│   ├── MyApp.xcodeproj
│   │   ├── MyWorkspace.xcworkspace
│   │   │   ├── xcshareddata
│   │   │   └── xcuserdata
│   │   │       └── fmignogna.xcuserdatad
│   │   ├── project.xcworkspace
│   │   │   ├── xcshareddata
│   │   │   └── xcuserdata
│   │   │       └── fmignogna.xcuserdatad
│   │   └── xcuserdata
│   │       └── fmignogna.xcuserdatad
│   │           └── xcschemes
│   ├── MyAppTests
│   └── MyAppUITests
└── MyWorkspace.xcworkspace
    ├── xcshareddata
    └── xcuserdata
        └── fmignogna.xcuserdatad
```

</details>

If I hide ModuleA scheme, the file that has been changed is `/ModuleA/ModuleA.xcodeproj/xcuserdata/fmignogna.xcuserdatad/xcschemes/xcschememanagement.plist`

```diff
 		<key>ModuleA.xcscheme_^#shared#^_</key>
 		<dict>
 			<key>isShown</key>
-			<true/>
+			<false/>
 			<key>orderHint</key>
 			<integer>0</integer>
 		</dict>
```

But generally, you put this file into the `.gitignore`. 😞

**Comment by danyf90** [comment]
Added Scheme.hidden property in 2.2.0
