### ISSUE TITLE
SwiftUI previews on static framework.

### ISSUE THREAD

**Issue by gtsifrikas** [tuist/tuist#2609]
**Describe the bug**
In mFeature architecture using static frameworks, when use create a SwiftUI View preview not working and throws 
```
ConfigurationError: noPreviewInfos(arch: "x86_64", sdkRoot: "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk")
```

Most probably is not related with Tuist but I'm putting here as placeholder or if someone has any idea how to solve it. I'll try to figure out a solution in the meanwhile.

**To Reproduce**
- Use https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_framework_linking_static_framework fixture
- Add a swiftui view in UIComponents
- Try to use the preview functionality

- OS: Big Sur 11.2.2, xcode 12.4

**Comment by kwridan** [comment]
Hi @gtsifrikas 

I believe as things stand Swift UI previews are not supported in Static libraries:

![Screenshot 2021-03-05 at 08 01 42](https://user-images.githubusercontent.com/11914919/110085488-161e2d00-7d89-11eb-81d0-50e3a5e5f09a.png)

As such the same would apply for Static Frameworks _(the difference is the final packaging, static frameworks are packaged as `.framework` vs static libraries as `.a` products)_.

The only workarounds I've found to deal with this locally is to temporarily generate a dynamic framework during development only to get previews working.

You can leverage Tuist's dynamic configuration feature https://tuist.io/docs/usage/dynamic-configuration/ to do this in a somewhat elegant manner _(the feature works with `tuist generate` as well)_.

Hope this helps!

**Comment by gtsifrikas** [comment]
Thanks @kwridan. I ended up with exactly that. Generating dynamic frameworks when I want to use SwiftUI Previews.

**Comment by MarcoCadei** [comment]
I'm trying to do just this but with no luck. How did you do it @gtsifrikas?

**Comment by ammerzon** [comment]
I would also be interested in how you achieved that @gtsifrikas 😁
