### ISSUE TITLE
Info.plist generation

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#261]
## Context 🕵️‍♀️
We have done a pretty good job abstracting complexities related to things like the linking of frameworks. I think Tuist can go even further and deal with the configuration of the `Info.plist` files.

You might wonder why would I want a tool to generate those `Info.plist` files. Here are some reasons:
1. Most `Info.plist` files have the same structure. Only a few attributes change.
2. The creation of a new target not only requires defining the target in the manifest file but creating an `Info.plist` file for the target. In most cases, developers will copy & paste existing files and change their attributes.
3. If you do copy & pasting assuming all `Info.plist` will be the same you'll likely run into surprises when certain things don't work because you forgot adding required attributes.

## What 🌱
Tuist would generate the `Info.plist` file in the project directory or use an existing one if the user prefers so.

## Proposal 🎉

```swift
let target = Target(infoPlist: .path("./Info.plist"))
let target = Target(infoPlist: .base(extend: ["MY_VARIABLE": "VALUE"])
```

The generation of the `Info.plist` file would allow us running some validations and setting the attributes that are required by the target that is associated to the `Info.plist`.

cc @tuist/core

**Comment by kwridan** [comment]
I believe this has already been implemented 👍 

#380 & #448
