### ISSUE TITLE
tuist up: Mint exited with error code 1 when asking to overwrite existed symlink

### ISSUE THREAD

**Issue by migfabio** [tuist/tuist#2624]
**Describe the bug**
Given `.mint(linkPackagesGlobally: true)` in my setup, when I do `tuist up` and I have some tools already installed globally, I'll get this error `Overwrite it with Mint's symlink? (y/n) The 'mint' command exited with error code 1`

**To Reproduce**

1. Create a Mintfile with some tools you have already installed globally (for example, via Homebrew)
2. Put `.mint(linkPackagesGlobally: true)` in your `Setup.swift`
3. Run `tuist up`

**Expected behavior**
Supposed to overwrite the existed symlink with the Mint's one, or give the ability to the user to choice yes or no.

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Version 10.15.7

**Comment by pepibumur** [comment]
Tuist up is [going away](https://github.com/tuist/tuist/pull/3443) in the upcoming 2.0 major release and therefore I'm closing this issue.
