### ISSUE TITLE
Xcode warns to use recommended build settings after generating a project

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#263]
![cc58eaf1-8660-45f2-adc9-bc23819040ff](https://user-images.githubusercontent.com/1382565/54023507-074a1300-418d-11e9-8543-8c7a38572396.png)

---

Tuist should generate a project without any warnings or recommendations.

**Comment by pepibumur** [comment]
Agree. I wonder if we can have some tests that validate that Xcode doesn't generate warnings for the projects that we generate. Something like:

```
xcodebuild --warnings
```

**Comment by kwridan** [comment]
https://github.com/tuist/xcodeproj/pull/417 will help resolve one of those warnings

**Comment by ollieatkinson** [comment]
Latest master does not produce any warnings 

![A0456DBB-E860-4B8A-9E50-5F0D4E699BF7](https://user-images.githubusercontent.com/1382565/59551886-2caea000-8f78-11e9-963c-92f993ed6aed.png)
