### ISSUE TITLE
Dependencies.swift - Add --no-use-binaries option to Carthage

### ISSUE THREAD

**Issue by migfabio** [tuist/tuist#2636]
**Describe the bug**
At the current stage, there is no way to specify the proper flag to not use the prebuilt framework into `Dependencies.swift`.

**Additional context**
This should be a simple addition and I would love to help here if you all agree that this could be useful.

**Comment by laxmorek** [comment]
Hey @migfabio 

The change you are suggesting is already in review you can follow the status here: https://github.com/tuist/tuist/pull/2608
