### ISSUE TITLE
Unexpected auto-generated schemes test action

### ISSUE THREAD

**Issue by FranzBusch** [tuist/tuist#2639]
**Describe the bug**
When generating a project with Tuist it automatically tries to generate schemes for targets. This heuristic is currently implemented in [AutogeneratedSchemesProjectMapper.swift](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift). The code there is iterating through all targets and for each target it searches for all test bundles that have the target as a dependency. This means that for a target A the scheme test action runs all the test bundles of targets that dependencies on target A which is in my opinion unexpected.

**To Reproduce**
Setup a project like this:

- Target A (static lib) & Target ATests (test bundle)
- Target B (static lib) & Target BTests (test bundle)
- Target C (static lib) & Target CTests (test bundle)

In this setup Target B should depend on Target A and Target C on Target B. And it will result that the auto generated scheme of Target A will run Target ATests, Target BTests and Target CTests.

**Expected behavior**
In the above example it should only run the Target ATests and we should change the heuristic to check if there is a test bundle target with the same name as target name but prefixed with `Tests`.

**Comment by pepibumur** [comment]
I'd expect it to behave the way you describe. I'm curious what @tuist/core thinks about this?

**Comment by kwridan** [comment]
Thanks for raising this @FranzBusch,

To capture some of the discussion in slack

This behaviour was first introduced in https://github.com/tuist/tuist/pull/818 and I believe there wasn't anything specific about the chosen heuristic there aside from perhaps cover the cases where the convention is followed? The convention of `Target` and `TargetTests` is very common and perhaps works as a better heuristic than the one already in use.

Some additional use-cases I can think of _(we may not need to cater for all of them, as users can still define custom schemes if needed)_

For a target `MyTarget`:

- `MyTargetTests`
- `MyTargetUITests`
- `MyTargetIntegrationTests`

**Comment by kwridan** [comment]
Some of the initial discussions can be found here https://github.com/tuist/tuist/issues/569, re-reading it perhaps it was done to mimic Xcode's default behaviour?

For example: 

Xcode will automatically add test bundles _(even if they don't follow the convention)_ to the corresponding scheme, so in this example adding `CustomTests`

![xcode](https://user-images.githubusercontent.com/11914919/110624182-c8912e00-8195-11eb-9a2b-a4f11cfb631f.png)

Xcode will automatically get it added to the `App` scheme's list of testable targets. That said this only applies for app targets and not framework targets from my quick test.

If we retain the existing heuristic, perhaps only for app targets, vs the naming one for non app targets? or possibly stick with the naming one for all to keep it simple?

**Comment by kwridan** [comment]
There's a `-Project` scheme which achieves this I believe. 

https://github.com/tuist/tuist/pull/1765

**Comment by FranzBusch** [comment]
Good to know! Still trying to setup our app target and haven't gotten to the point. Would you think it makes sense for me to open a PR to change the automated scheme generation behaviour to use the name based heuristic?
