### ISSUE TITLE
A newly generated project uses the old syntax for 'UIApplication.LaunchOptionsKey'

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#264]
![98b1c0d5-86df-44c4-90ca-b1c08f94fec9](https://user-images.githubusercontent.com/1382565/54023593-44aea080-418d-11e9-9b92-08fa1edf45f1.png)

--- 

tuist should use the newer swift 4.2 syntax. But that opens up another question ... should tuist support more swift language versions?

**Comment by pepibumur** [comment]
Good question. We could use the system's Swift version to determine the format of the file.

**Comment by steprescott** [comment]
So the changes made in https://github.com/tuist/tuist/pull/269 remove this and puts the `AppDelegate.swift` to the minimum needed and leaves the rest to the Storyboards.

**Comment by pepibumur** [comment]
Awesome. Thanks for tackling it @steprescott

**Comment by kwridan** [comment]
#291 has resolved this particular warning. Storyboard support will also be helpful in this area too
