### ISSUE TITLE
The default generated project does not include a LaunchScreen storyboard

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#265]
The default generated project does not include a LaunchScreen storyboard meaning that the default view on an iPhone X is clipped top and bottom (see picture).

![876a8a40-f06e-416f-9b45-872fa3ec5a38](https://user-images.githubusercontent.com/1382565/54026558-29945e80-4196-11e9-8df9-3cb7d54938f6.png)

tuist should generate the application project with the launch screen storyboard.

**Comment by pkassonqh** [comment]
Has this feature been merged into latest ?   Are there examples on how to configure the project to generate this or other storyboards / view controllers ?

**Comment by ollieatkinson** [comment]
This issue is only a problem because the default generated project does not include it. You should be able to include the `LaunchScreen.storyboard` using the `resources:` parameter on the target. 

To make it work you also need to set `UILaunchStoryboardName` in the Info.plist - if you set this in the project for the application it _should_ automatically insert it for you.

![](https://useyourloaf.com/assets/images/2014/2014-12-24-005.png)

![](https://useyourloaf.com/assets/images/2014/2014-12-24-003.png)

**Comment by mollyIV** [comment]
Hey 👋 I gave it a shoot: https://github.com/tuist/tuist/pull/1911.
