### ISSUE TITLE
Add automation for workflows

### ISSUE THREAD

**Issue by luispadron** [tuist/tuist#2654]
## Context 🕵️‍♀️

Whenever a new feature acceptance test is added the [workflows/tuist.yml](https://github.com/tuist/tuist/blob/main/.github/workflows/tuist.yml) must be manually modified such that the acceptance test is added. This is error prone and allows for tests to be skipped.

## What 🌱

We've been noticing that not all acceptance tests are run always because of forgetting to update the `tuist.yml` workflow. This leads to other developers having to catch/fix these errors even though this should've been fixed before the PR was merged.

## Proposal 🎉

We should find a way to automate updating `tuist.yml` workflow such that all acceptance tests are added & removed as needed.

**Comment by danyf90** [comment]
IMO if you add a new test file you at least check it runs on the PR where you add it, so there is very little chance to miss it
