### ISSUE TITLE
Signing: Support of .pem

### ISSUE THREAD

**Issue by innoreq** [tuist/tuist#2675]
**Describe the bug**
We just set up the signing with tuist according to the documentation. However, we could not export the keychain's private key as .p12, but only as .pem. When performing the setup as described, the .cer files are changing to .cer.encrypted, while the .pem files stay unmodified. We assume that they also should be .pem.encrypted.

**Expected behavior**
tuist should support the handling of .pem files during the encryption process as well.
Additionally, it would be helpful if the documentation would illustrate the content of the "signing" folder before and after the encryption by example, so that it is possible to check if that process was performed successfully.

**Desktop (please complete the following information):**

- OS: macOS 11.2.3
- Xcode: 12.4

**Comment by fortmarek** [comment]
Hi @innoreq!

> However, we could not export the keychain's private key as .p12, but only as .pem.

Do you know why that is not possible?

> We assume that they also should be .pem.encrypted.

Yes, right now we don't support that but it should not hard to implement. In `SigningFilesLocator` there's functions `locateEncryptedPrivateKeys` and `locateUnencryptedPrivateKeys` where we could also add `pem` alongside `cer`.

Would you like to give this a go @innoreq? I think it's a good starter task. I can give you pointers if you need any.

> Additionally, it would be helpful if the documentation would illustrate the content of the "signing" folder before and after the encryption by example, so that it is possible to check if that process was performed successfully.

I agree - this could be done along with this issue. But basically, as you might have noticed, you want all files have `.encrypted` suffix after the encryption is done.
