### ISSUE TITLE
Can't run tuist up on M1

### ISSUE THREAD

**Issue by artemkrachulov** [tuist/tuist#2704]
**Describe the bug**
`tuist up` fails.

**To Reproduce**
Steps to reproduce the behaviour with new MacBook Pro with M1 chip:

1. Install Brew
2. Install Tuist
3. Run `tuist up`
4. Get error:
<img width="713" alt="Screenshot 2021-03-25 at 21 39 28" src="https://user-images.githubusercontent.com/7997760/112533421-99440900-8db2-11eb-975f-3e730ee3f62b.png">

HOMEBREW_PREFIX: /opt/homebrew

**Suggestion**
Different executable file locations. **Tuist** located in `/usr/local/bin` since **Brew** in  `/opt/homebrew`. How to set different executable Brew  path for Tuist?

**Comment by fortmarek** [comment]
Hi @artemkrachulov!

Seems like `/usr/local/bin/brew` path is currently hardcoded.

Could you try [here](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Up/UpHomebrew.swift#L50) and [here](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Up/UpHomebrew.swift#L71) to change `"/usr/local/bin/brew"` to `"/usr/bin/env", "brew"`? 

If that works, could you create a PR for this?

**Comment by ferologics** [comment]
A potential workaround would be to `ln -s /opt/homebrew/bin/brew /usr/local/bin/brew` but what @fortmarek wrote should actually fix the root cause of the issue.

**Comment by pepibumur** [comment]
[This PR](https://github.com/tuist/tuist/pull/2711) should fix it.
