### ISSUE TITLE
How to run a target action after source compilation but *before* signing frameworks

### ISSUE THREAD

**Issue by bvirlet** [tuist/tuist#2708]
## Context 🕵️‍♀️

I need to run a TargetAction on a framework (lipo) after the frameworks have been embedded, but before the frameworks are signed. 

## What 🌱

If I understand correctly, the only order you can choose for TargetActions is *before* source compilation (`.pre`) or *after* all pre-existing target actions (`.post`).

Am I understanding this properly? Are there any recommended workarounds?

**Comment by fortmarek** [comment]
Hi!

Could you please expand your use-case?

There is no way afaik to do this and I worry that adding something like that would complicate the current API, so it'd be better to achieve the end result in a different way.

**Comment by bvirlet** [comment]
Hi @fortmarek,

The context for for this: https://github.com/krzyzanowskim/OpenSSL/issues/115. TLDR: I have to be able to remove a slice (arm64e) from a framework. I don't want to remove the slice from the file in SRCROOT, but from the build products, but this still has to happen *before* it's codesigned.

Note that to work around this issue, I regenerated the framework without the slice (and since then @kryzanowskim also removed the problematic arm64e slice from the official framework), but maybe it would still be a good idea to be able to add a build phase pre-codesigning? Or would you see another way of doing this?

**Comment by danyf90** [comment]
Seems fixed in the library
