### ISSUE TITLE
Tuist embed fails

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#273]
I'm running Tuist from `master`.
I get all my expected inherited frameworks in the `Embed Precompiled Frameworks` build phase.

However, `tuist embed` fail for each framework with the following output:
```
Using version master defined at /Users/enhorn/Repos/company/ios/Project Tuist/.tuist-version
Embedding framework ../../Project/Carthage/Build/iOS/CarthageFramework.framework
❌ Error: The build variable CONFIGURATION is missing.
```

And nothing ends upp in the app bundle. :-/

**Comment by enhorn** [comment]
Get the same error message trying to run the command  in the terminal:
```
> tuist embed "../../Project/Carthage/Build/iOS/CarthageFramework.framework"
Embedding framework ../../Project/Carthage/Build/iOS/CarthageFramework.framework
❌ Error: The path to the framework is missing.
```

**Comment by pepibumur** [comment]
Hey @enhorn,

This issue should be already fixed but you might need to re-install Tuist in your system. You can do it by running the installation step on the README. 

We opened [an issue](https://github.com/tuist/tuist/issues/260) to improve the update process for next time.

Could you try that out and let us know if it works?

**Comment by enhorn** [comment]
Yes, thanks, running the install script again fixed the issue!
