### ISSUE TITLE
Question: The New Build System detects a cycle in dependencies between targets.

### ISSUE THREAD

**Issue by SergeyKovalenko** [tuist/tuist#2738]
It's not an issue of tuist itself but I would be appreciated if somebody could help me to understand why this happening.

I'm trying to move some basic testing components (like FakeAppDelegate, basic matchers, etc.) to a standalone framework to be able to reuse them in the different test targets. 

Here is how the basic setup looks like:

![graph](https://user-images.githubusercontent.com/872805/112715582-b29ba100-8ee9-11eb-9d54-590faeff1f8f.png)

Third-party dependencies are managed using cocoapods.

When building `AppTests` I'm getting:
```
Cycle inside AppTests; building could produce unreliable results.
Cycle details:
→ Target 'AppTests' has copy command from '/Applications/Xcode-12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework' to '/Users/sergey/Library/Developer/Xcode/DerivedData/App-hesozhxduqjmeaavnxpbajnwiqrv/Build/Products/Debug-iphonesimulator/App.app/Frameworks/XCTAutomationSupport.framework'
○ Target 'AppTests': CodeSign /Users/sergey/Library/Developer/Xcode/DerivedData/App-hesozhxduqjmeaavnxpbajnwiqrv/Build/Products/Debug-iphonesimulator/App.app/PlugIns/AppTests.xctest/Frameworks/TestsKit.framework
○ That command depends on command in Target 'AppTests': script phase “[CP] Embed Pods Frameworks”
```

I was managed to silence this error in a couple of ways, but none of them doesn't really suites my need:
 
-  by converting `TestsKit` to the static framework. But with the static framework I can't use fake app delegate while running unit tests, like so:
```
_ = UIApplicationMain(CommandLine.argc, CommandLine.unsafeArgv, nil, NSClassFromString("TestingAppDelegate") ?? AppDelegate.self)
```
-  by removing "Code Sign On Copy" option from `TestsKit` in `Embed Frameworks` build phase or by moving  `[CP] Embed Pods Frameworks` build step before `Embed Frameworks` step.  I can't automate this process using tuist

<img width="897" alt="Screenshot 2021-03-27 at 10 50 48" src="https://user-images.githubusercontent.com/872805/112715673-600eb480-8eea-11eb-8d73-049dea0cf36a.png">

I'm wondering is there any other option that allows me to use `TestsKit` as dynamic Frameworks and cocoapods as a third-party dependency manager?

Here is a sample project where this issue could be reproduced:  https://github.com/SergeyKovalenko/TuistTestKitSample

**Comment by fortmarek** [comment]
Hi, I will close this as this is not specifically tuist-related. Feel free to post this to our [discussions](https://github.com/tuist/tuist/discussions) which might be a better place for this kind of question.

I'd like to give you some help here but I'm not very familiar with CocoaPods as I have not been using it for quite long (and it seems to be quite related to what CocoaPods does and how it augments your project).

I realize that migrating from CocoaPods might not be on the table but I'd recommend looking into it going forward as with CocoaPods you might lose some tuist optimizations in the future.

Thanks for your understanding!

**Comment by maxheld** [comment]
@SergeyKovalenko we found a solution to your problem, we posted it here in the discussions: https://github.com/tuist/tuist/discussions/2817. I hope it helps

**Comment by VorkhlikArtem** [comment]
Hello @SergeyKovalenko,

Just add this empty pre-script in unitTest Target's scripts in your manifest Project.swift:
`.pre(script: " ", name: "[CP] Embed Pods Frameworks")`
And after tuist generate -n && pod install you will get a build phase _[CP] Embed Pods Frameworks_ above in your unitTest build phases. It will help to prevent the cycle error in unit-test targets.

This is my full troubleshooting over it: https://github.com/tuist/tuist/discussions/5989. Please check it out
I hope I helped you and others who come across this problem
