### ISSUE TITLE
Target product names should be able to contain spaces

### ISSUE THREAD

**Issue by bvirlet** [tuist/tuist#2745]
**Describe the bug**
When trying to use a target product name with a space, `tuist generate` raises an error: `Invalid product name 'My App'. This string must contain only alphanumeric (A-Z,a-z,0-9) and underscore (_) characters.`

Yet, product names (CFBundleName) can contains spaces. See below screenshot of a simple Xcode project: 

<img width="973" alt="image" src="https://user-images.githubusercontent.com/792706/112890603-5dbd7d80-90d7-11eb-9f5c-17f636dff7c7.png">

Related Tuist unit tests:

https://github.com/tuist/tuist/blob/eaf74cb2fe6367b480b6ec26018398e1bdeaf2f9/Tests/TuistGeneratorTests/Linter/TargetLinterTests.swift#L25

**Additional context**

This isn't a major issue but makes migrating our project to Tuist a bit more tedious (we need to change the product name, and change some logic that relied on the product name).

**Comment by fortmarek** [comment]
Hi @bvirlet!

I'd say that having `PRODUCT_NAME` might not be the best practice but I agree it's frustrating that we are more strict in this case than Xcode.

Seeing that @ollieatkinson has implemented this [here](https://github.com/tuist/tuist/pull/435/files#diff-198b850ef8102d961e3ceaa12fcb0bec7daef3371a61ddbcf3e429d6921bfdeeR22), what do you think about relegating this to a warning? I don't have a very strong opinion on this, though.

**Comment by bvirlet** [comment]
Hi @fortmarek,

A warning sounds fair. It will help with best practices (I agree it's better without spaces) but will make it easier to migrate to Tuist: It took me some time to understand what was going on, and then some time to fix all my product names, and then tweak some Fastlane/CI scripts that were also referencing the old product names with the space.

**Comment by fortmarek** [comment]
If you have some time @bvirlet, you can change the severity to `.warning` in the function you linked above 👍
