### ISSUE TITLE
Decouple embed frameworks build phase from Tuist

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#276]
## Context 🕵️‍♀️
The embed build phase that we generate to copy the frameworks into the product depends on Tuist being installed in the system. This makes it impossible to compile the app without having Tuist installed in the system.

For instance, we can see [on this issue](https://github.com/tuist/tuist/issues/273) how some users are not able to compile the app because there's a bug in the Tuist version that they have installed.

## What 🌱
Decouple the embed phase from Tuist. Some ideas that come to my mind:
- Generate a script in the project directory (bash script) and call it from the build phase.
- Add the content of the script to the build phase.

cc @tuist/core

**Comment by pepibumur** [comment]
I think this one will be useful for you @marciniwanicki / @kwridan

**Comment by kwridan** [comment]
Resolved via https://github.com/tuist/tuist/pull/610

**Comment by pepibumur** [comment]
![gif](https://media.giphy.com/media/10hO3rDNqqg2Xe/giphy.gif)
