### ISSUE TITLE
Collision with `swift-package-manager`: `No such module 'Basic'`

### ISSUE THREAD

**Issue by jakeatoms** [tuist/tuist#2770]
**Describe the bug**
We have some Swift CLI tools in our repo and when they get built, we end up with a `Workspace.swift` file in the `swift-package-manager` checkout deep within `.build`. When we run `tuist edit`, the resulting `Manifests` target fails to build with `No such module 'Basic'`.

**To Reproduce**

1. Build a package that depends on `swift-package-manager`
```swift
  dependencies: [
    // Dependencies declare other packages that this package depends on.
    // .package(url: /* package url */, from: "1.0.0"),
    .package(url: "https://github.com/apple/swift-package-manager.git", from: "0.1.0"),
  ]
```
2. Run `tuist edit`
3. Build `Manifests` target

**Expected behavior**
non-Tuist related files should be excluded from `edit`.

**Screenshots**
<img width="695" alt="image" src="https://user-images.githubusercontent.com/3605966/113430196-bcb91600-93a7-11eb-8eed-e78b82f0078c.png">

**Comment by fortmarek** [comment]
Hi @jakeatoms!

Thanks for raising this - we want to revamp a little bit how `tuist edit` works to fix this. Tagging @luispadron as he is working on this.

**Comment by kwridan** [comment]
For reference, the discussion is taking place here: #2775

**Comment by pepibumur** [comment]
Because the discussion has been moved to the thread and we already have a reference from there, I'll close this issue.
