### ISSUE TITLE
Optimize Github Actions by auto cancelling previous queue per branch/pr.

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#2773]
Hi, while talking with @fortmarek, I was mentioning that in other CIs, you could have only 1 queue trigger per each branch/pr, so that multiple commits in short time won't result in multiple enqueue of Github actions. Since we (generally) care about the most up to date CI results, it would be good to automatically cancel previous actions for the same PR, if any.

I didn't had a look about how (and if) this is possible with Github Actions just yet, creating this issue so we may have a look in the future.

For reference:
* Github open issue, https://github.community/t/github-actions-cancel-redundant-builds-not-solved/16025/38
* A possible action https://github.com/styfle/cancel-workflow-action

**Comment by pepibumur** [comment]
Thanks a lot for reporting this @adellibovi. Would you mind tackling this one? Otherwise I can also contribute to it myself.
