### ISSUE TITLE
Remove deprecated TUIST_FORCE_CONFIG_CACHE_DIRECTORY

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#2777]
Hi,
Now that we can configure the cache directory with #2566, we may remove this internal environment parameter.

**Comment by pepibumur** [comment]
> Now that we can configure the cache directory with #2566, we may remove this internal environment parameter.

`TUIST_FORCE_CONFIG_CACHE_DIRECTORY` can't find where we are using this variable :/

**Comment by adellibovi** [comment]
@pepibumur "workspace.rb" :)

**Comment by pepibumur** [comment]
I was confused because the name is `TUIST_CACHE_DIRECTORY`. I think that variable should remain because it exists for the acceptance tests to be able to change the path only for test purposes. The manifest-based API that you introduced is user-facing and serves a different purpose.

**Comment by fortmarek** [comment]
Ah, right, this was my suggestion, I have not realized the user-facing API is only configurable via manifest (if it was configurable from CLI, we could probably delete it). I guess we can close this one then (feel free to reopen @adellibovi if you think it's not the case)
