### ISSUE TITLE
Tuist generate resources ( localized + assets )

### ISSUE THREAD

**Issue by taimur** [tuist/tuist#2779]
Whenever we execute command `tuist generate` it shows changes in localized files and assets. Is someone experiencing similar issue ?

**Comment by fortmarek** [comment]
Hi @taimur!

If you don't want the synthesized resource accessors generated by tuist by default, you can add `.disableSynthesizedResourceAccessors`.

Let me know if that solves what you are trying to do, so we can close this.

**Comment by taimur** [comment]
Thanks a lot. I just added it to Config file. This is how it looks. 

```
import ProjectDescription
let config = TuistConfig(
    generationOptions: [
     .disableSynthesizedResourceAccessors,
     .disableAutogeneratedSchemes
        
    ]
)

```
Now It shows the resource files are deleted when I execute tuist generate command. PFA screenshot.

![image](https://user-images.githubusercontent.com/900314/113509608-8de99e00-9567-11eb-86f3-5c0e3f9131f2.png)

**Comment by fortmarek** [comment]
Yes, they should not be present anmore when `.disableSynthesizedResourceAccessors` is present in your `Config`. Could you maybe elaborate what exactly you are trying to achieve and what is the unexpected behavior?

**Comment by taimur** [comment]
I dont want any changes to the resources file whenever I execute `tuist generate`. But I need these files in the project. If I make any changes to these files, add a string or an image. I want to commit the changes to my repo.

**Comment by fortmarek** [comment]
Generally speaking, I'd advise you to not commit contents of `Derived` directory as they are just a by-product of `tuist generate` and its contents do change between tuist versions.

That being said, I realize some teams do want to have all the files, even generated, committed. 

> I dont want any changes to the resources file whenever I execute tuist generate

If you changed eg. `.strings` file, the files should change with `tuist generate`.

If the generated files change even though the resources have not then we'd probably have indeterministic behavior which is not great. In that case, it'd be great if you could create a reproducible sample or at least showing the unexpected diffs.

**Comment by fortmarek** [comment]
Closing for now until there is more info available. Feel free to reopen if needed!
