### ISSUE TITLE
Support Tap/Cask in UpHomebrew

### ISSUE THREAD

**Issue by enhorn** [tuist/tuist#278]
An example Brewfile could like this:

```
tap 'mono0926/license-plist'
tap 'peripheryapp/periphery'
brew 'swiftgen'
brew 'license-plist'
cask 'periphery'
```

As I've understood it, the current `UpHomebrew` only supports packages that can be installed directly with `> brew install ***`, which doesn't fully support the example Brewfile above.

Am I correct?

**Comment by pepibumur** [comment]
@enhorn thanks for all your suggestion, they are so useful to keep improving Tuist ❤️.
I started tackling this one. Instead of adding support for a `Brewfile` which would require us to parse the `Brewfile` and understand each of the lines in the file, I'm adding support for both taps and casks directly on the manifest file. I was thinking about something like this:

```swift
.homebrewTap(repositories: ["whatever"])
.homebrewCask(projects: ["whatever"])
```

What do you think?

**Comment by enhorn** [comment]
@pepibumur Happy to help, and getting helped, so far Tuist have saved a lot of time for us on our project, even before we can go all in. 😊

That works for me.

Great having it directly in the manifest file. Any plans of updating the UpCarthage in a similar way? Sure, Carthage has the `Cartfile.resolved` file, but that can stay.

**Comment by pepibumur** [comment]
I think it's fine keeping the `Cartfile`. In that case, we implemented the logic that allows us to determine what's missing or outdated and thus, what needs to be updated.

**Comment by leszko11** [comment]
Hi @pepibumur!
Is this issue still active? I can help with a `Cask` part :)

**Comment by pepibumur** [comment]
Hey @leszko11!
Sure, contributions are always welcome. As far as I know this is not being worked on. Feel free to take it on. I'm sure a lot of users would love to see this improvement landing in the project.

Let me know if you need some guidance when working on it 😋

**Comment by leszko11** [comment]
@pepibumur Cool, I'm on it!
