### ISSUE TITLE
tvOS Top Shelf Extension Target not supported

### ISSUE THREAD

**Issue by rmnblm** [tuist/tuist#2791]
**Describe the bug**
Adding `.target(name: "TopShelfExtension")` to the tvOS target results in the following error upon generating the project:

``` bash
> tuist generate
Target tvOS has a dependency with target TopShelfExtension of type app extension for platform 'tvOS' which is invalid or not supported yet.
```

**To Reproduce**

1. Create tvOS target with platform `.tvOS` and product `.app`.
2. Create app extension target with platform `.tvOS` and product `.appExtension`
3. Add target dependency to tvOS target `.target(name: "TopShelfExtension")`
4. Run `tuist generate`

**Expected behavior**
The project should be generated without any erros.

**Desktop (please complete the following information):**

- OS: macOS Big Sur 
- Version: 11.2.1

**Additional context**
I realize that there is a `case tvExtension` in [`Product.swift`](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Product.swift), which is not supported yet. My question is whether this is on any roadmap or available in the near future and if there is an easy workaround until it gets implemented. Obviously, adding the target manually would solve the problem.

**Comment by fortmarek** [comment]
Hi @rmnblm!

`tvExtension` is commented out since so far there has been no one who would use it in their project. 

My suggestion is to try to uncomment it and see if there are any issues.

If there are not, I think you could go ahead and create a PR. If there are, you can report that here and we can discuss how to fix that if you don't see an easy way out.

**Comment by rmnblm** [comment]
Hi @fortmarek 

I uncommented `.tvExtension`. Running `tuist generate` works fine, no errors whatsoever. However, the extension target is not added as target to the tvOS target. Any ideas what's missing? ☺️
