### ISSUE TITLE
Default .interfaceBuilder synthesizer template missing

### ISSUE THREAD

**Issue by rstone4-chwy** [tuist/tuist#2812]
**Describe the bug**
After updating to 1.40.0 as a test for synthesized resource accessors on our project I added `.assets()` and `.interfaceBuilder()` to the `resourceSynthesizers` parameter. When running generate a failure message of `Default template for parser interfaceBuilder not available.` stops the generation.

**To Reproduce**
1. Create a project default blank project using `tuist init`
2. Edit `Manifests > Tuist > ProjectDescriptionHelpers > Project + Templates.swift` add `synthesizedResources: [.interfaceBuilder()]` below line 17.
3. Save
4. Run `tuist generate`

**Expected behavior**
Project generates

**Screenshots**
<img width="545" alt="image" src="https://user-images.githubusercontent.com/64436740/114872639-86788f00-9dc8-11eb-9e96-ac3310856841.png">

- OS:MacOS 10.15.7
- Version 1.40.0

**Comment by fortmarek** [comment]
Hi @rstone4-chwy!

You have to provide a default template for interface builder by yourself by adding it to `Tuist/ResourceSynthesizers/InterfaceBuilder.stencil`

That being said, I am not opposed to adding it to tuist as well, I can give you some pointers if you wanted to implement it.
