### ISSUE TITLE
Configuration for test action in custom scheme 

### ISSUE THREAD

**Issue by HoustonUA** [tuist/tuist#2813]
**Describe the bug**
Hello. 
I have three custom configuration for my project.
![CustomConfigurations](https://user-images.githubusercontent.com/19517144/115025445-0aff0680-9eca-11eb-9943-a87bdf69fa00.png)

And I'm trying to implement custom scheme like that.
![CustomScheme](https://user-images.githubusercontent.com/19517144/115025647-4b5e8480-9eca-11eb-88ab-21cb97c36993.png)

And when I try to execute '**tuist generate**' command the console shows me:
"The build configuration 'Debug' specified in the scheme's test action isn't defined in the project."

And that's logical because there is actually no such configuration because I have the custom ones.
We can see the '**config**' property in the **TestAction** initialiser, but there are only predefined configuration: **.debug** and **.release** (PresetBuildConfiguration).

So how can I specify some custom configuration from the list from the first screenshot? For instance I want to use my custom '**Dev**' configuration in **TestAction**.

**To Reproduce**
1. Create custom configurations without default **.debug** and **.release**.
2. Create custom scheme.
3. Create **TestAction** in newly create custom scheme.
4. Specify **.debug** (PresetBuildConfiguration) configuration.

**Expected behavior**
The possibility to specify my own custom configuration in _TestAction's_ **config** property.

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.0.1 (20B29)

**Comment by kwridan** [comment]
Hi @HoustonUA - thanks for flagging this

There's an [alternate initialiser](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/TestAction.swift#L82) that takes `configurationName` which you can use to specify the appropriate custom configuration name like `"Test"`, `"Dev"`, or `"Production"`. 

Hope this helps

**Comment by HoustonUA** [comment]
@kwridan oh my God. I really haven't noticed that there is another initialiser.
Sorry for this question and thanks a lot for quick and great response! :)

**Comment by kwridan** [comment]
No worries - looking at the [docs](https://docs.tuist.io/manifests/project#test-action) the mention of it is a bit hidden because of the other parameters, it's easy to miss 😅
