### ISSUE TITLE
messagesExtension is not embedding frameworks

### ISSUE THREAD

**Issue by michaelmcguire** [tuist/tuist#2818]
**Describe the bug**
When defining a `messagesExtension` that depends on other dynamic framework targets, the frameworks are not included in the `Embed Frameworks` Build Phase.

**To Reproduce**

1. Create basic project using `tuist init --platform ios --name MyApp`
2. Modify the example `makeFrameworkTargets` code to set `APPLICATION_EXTENSION_API_ONLY` to `YES`
3. Add a target to the project with a `product .messagesExtension` and include the `dependencies` from the app target
4. Generate Xcode project
5. Dependencies to the `MyAppKit.framework` and `MyAppUI.framework` are not embedded in the extension.

**Expected behavior**
Dependencies for the extension should be embedded in the final product.

**Screenshots**
![image](https://user-images.githubusercontent.com/429790/115604215-f8a01680-a295-11eb-9e0a-1e0c2aa9b638.png)

**Desktop (please complete the following information):**

- OS: `macOS 11.2.3`
- Tuist version: `1.39.1`

**Additional context**
Here is the final `Project+Templates.swift` after making changes to the generated example:

```swift
import ProjectDescription

/// Project helpers are functions that simplify the way you define your project.
/// Share code to create targets, settings, dependencies,
/// Create your own conventions, e.g: a func that makes sure all shared targets are "static frameworks"
/// See https://tuist.io/docs/usage/helpers/

extension Project {
  /// Helper function to create the Project for this ExampleApp
  public static func app(name: String, platform: Platform, additionalTargets: [String]) -> Project {
    var targets = makeAppTargets(
      name: name,
      platform: platform,
      dependencies: additionalTargets.map { TargetDependency.target(name: $0) })
    targets += additionalTargets.flatMap({ makeFrameworkTargets(name: $0, platform: platform) })
    return Project(
      name: name,
      organizationName: "tuist.io",
      targets: targets)
  }
  
  // MARK: - Private
  
  /// Helper function to create a framework target and an associated unit test target
  private static func makeFrameworkTargets(name: String, platform: Platform) -> [Target] {
    let sources = Target(
      name: name,
      platform: platform,
      product: .framework,
      bundleId: "io.tuist.\(name)",
      infoPlist: .default,
      sources: ["Targets/\(name)/Sources/**"],
      resources: [],
      dependencies: [],
      settings: Settings(base: ["APPLICATION_EXTENSION_API_ONLY": "YES"]))
    let tests = Target(
      name: "\(name)Tests",
      platform: platform,
      product: .unitTests,
      bundleId: "io.tuist.\(name)Tests",
      infoPlist: .default,
      sources: ["Targets/\(name)/Tests/**"],
      resources: [],
      dependencies: [.target(name: name)])
    return [sources, tests]
  }
  
  /// Helper function to create the application target and the unit test target.
  private static func makeAppTargets(name: String, platform: Platform, dependencies: [TargetDependency]) -> [Target] {
    let platform: Platform = platform
    let infoPlist: [String: InfoPlist.Value] = [
      "CFBundleShortVersionString": "1.0",
      "CFBundleVersion": "1",
      "UIMainStoryboardFile": "",
      "UILaunchStoryboardName": "LaunchScreen"
    ]
    
    let mainTarget = Target(
      name: name,
      platform: platform,
      product: .app,
      bundleId: "io.tuist.\(name)",
      infoPlist: .extendingDefault(with: infoPlist),
      sources: ["Targets/\(name)/Sources/**"],
      resources: ["Targets/\(name)/Resources/**"],
      dependencies: dependencies
    )
    
    let testTarget = Target(
      name: "\(name)Tests",
      platform: platform,
      product: .unitTests,
      bundleId: "io.tuist.\(name)Tests",
      infoPlist: .default,
      sources: ["Targets/\(name)/Tests/**"],
      dependencies: [
        .target(name: "\(name)")
      ])
    
    let extensionName = "MessagesExtension"
    let extensionTarget = Target(
      name: extensionName,
      platform: platform,
      product: .messagesExtension,
      bundleId: "ios.tuist.\(extensionName)",
      infoPlist: .default,
      sources: ["Targets/\(extensionName)/Sources/**"],
      resources: ["Targets/\(extensionName)/Resources/**"],
      dependencies: dependencies
    )
    
    return [mainTarget, testTarget, extensionTarget]
  }
}
```

**Comment by michaelmcguire** [comment]
After working on this most of the day, I've learned that the default Xcode template for an iMessage Extension sets the `LD_RUNPATH_SEARCH_PATHS` to include `@executable_path/../../Framework` so frameworks are loaded from the main app's deployed frameworks. This is obviously better than having an additional copy with the app extension as well. So the "real" problem here might be that the default settings for an iMessage Extension doesn't do this.

**Comment by kwridan** [comment]
Thanks for raising and looking into this @michaelmcguire 

Indeed it looks like we're missing some default settings for `.messageExtension` product types. We do set those for the generic `.appExtension` (e.g. the product type we'd use for notification service extension)

![Screenshot 2021-04-22 at 07 13 11](https://user-images.githubusercontent.com/11914919/115664852-52f2b300-a33a-11eb-9efd-edeb1b086c21.png)

Default settings are obtained via [XcodeProj's `BuildSettingsProvider`](https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Utils/BuildSettingsProvider.swift), Tuist translates the various product types it supports to the corresponding XcodeProj product type (a smaller generic set) in [`SettingsHelper`](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/SettingsHelper.swift#L32). I believe it's a matter of extending the mapping to treat both `.appExtension` and `.messageExtension` as `BuildSettingProvider.Product.appExtension`.

Would you be interested in contributing that change? Happy to also do this.

**Comment by michaelmcguire** [comment]
> Thanks for raising and looking into this @michaelmcguire
> 
> Indeed it looks like we're missing some default settings for `.messageExtension` product types. We do set those for the generic `.appExtension` (e.g. the product type we'd use for notification service extension)
> 
> ![Screenshot 2021-04-22 at 07 13 11](https://user-images.githubusercontent.com/11914919/115664852-52f2b300-a33a-11eb-9efd-edeb1b086c21.png)
> 
> Default settings are obtained via [XcodeProj's `BuildSettingsProvider`](https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Utils/BuildSettingsProvider.swift), Tuist translates the various product types it supports to the corresponding XcodeProj product type (a smaller generic set) in [`SettingsHelper`](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/SettingsHelper.swift#L32). I believe it's a matter of extending the mapping to treat both `.appExtension` and `.messageExtension` as `BuildSettingProvider.Product.appExtension`.
> 
> Would you be interested in contributing that change? Happy to also do this.

Absolutely! Thank you for the explanation, I should be able to open a PR this week.

**Comment by kwridan** [comment]
Ah no worries, I'm sure there will be more opportunities soon - you are welcome to review it / test out which will be also be very helpful seeing you have a real use case that this addresses.
