### ISSUE TITLE
How to handle "Validate Project Settings - Update to recommended settings"?

### ISSUE THREAD

**Issue by innoreq** [tuist/tuist#2822]
**Describe the bug**
I'm not sure if this is really a bug, but it's definitely an unwanted behaviour: After generating a workspace with many modules using tuist, Xcode reports for each single project the above warning. I now tried to diff the existing and the fixed .xcodeproj, and to apply the indicated changes to the build settings in the tuist manifests. However, this does not fix the warnings, it seems that those changes are not persisted for any reason, while other settings are applied.

**To Reproduce**
Probably by using a newer version of Xcode.

**Expected behavior**
When manually defining those settings in a manifest, this should silence the related warnings.

**Desktop (please complete the following information):**
- macOS 11.4 Beta (20F5046g)
- Xcode 12.5 (12E262)
- tuist 1.36.0

**Additional context**
As an example: There is a warning "Enable Recommended Warning - This will enable the following recommended compiler warning: Quoted include in Framework Header".
After checking the diff, I defined this entry for the SettingsDictionary:
```
"CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER" : "YES",
```
That dictionary is used for a framework Settings:
```
	public static var framework: Settings {
		
		return Settings(
			base: frameworkSettings,
			debug: .init(settings: frameworkSettings),
			release: .init(settings: frameworkSettings),
			defaultSettings: .none
		)
	}
```
which is then used for the project manifest.

**Comment by fortmarek** [comment]
Hey @innoreq!

Yes, you are right, we should add that to default build settings. I have made the change [here](https://github.com/tuist/XcodeProj/pull/608), after that we can upstream it to tuist.

**Comment by fortmarek** [comment]
This should be now resolved in the latest tuist version.
