### ISSUE TITLE
Checksum verification as part of the installation

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#2825]
## Context 🕵️‍♀️
Codecov had a [security incident](https://about.codecov.io/security-update/) recently that caused environments to run a hacker's bash uploader and report sensitive information to the hacker.

## What 🌱
The approach our uses follow on CI for running Tuist is vulnerable to this types of hacks and therefore I think we should add some safeguards to prevent something like this from happening. Like Rails does, each release could include a checksum that we can validate when installing Tuist in a CI environment.

**Comment by danyf90** [comment]
We are already doing it in our CI, I don't think we need to do anything on the Tuist side
