### ISSUE TITLE
Support ignoring shared schemes from the generate command

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#289]
## Context 🕵️‍♀️

Generating shared schemes means it's possible to build them using `xcodebuild`. This is great for normal use-cases however it [introduces some complications when using Carthage](https://github.com/Carthage/Carthage/pull/1990). 

## What 🌱

Carthage are unwilling to fix the problem, so to avoid tuist built frameworks taking a long time to build when depended on through Carthage - we should offer a way to ignore sharing some schemes.

reference: https://github.com/Carthage/Carthage/pull/1990

This would probably make sense as part of the command line tool when running the `generate` command.

Potential solutions:

```sh
tuist generate --ignore-schemes 'Toolkit-Project,LayoutNib,LayoutNib-Project'
```

```sh
tuist generate --ignore-scheme Toolkit-Project \
               --ignore-scheme Toolkit-Project \
               --ignore-scheme LayoutNib \
               --ignore-scheme LayoutNib-Project
```

```sh
tuist generate --only-scheme Toolkit
```

I appreciate any suggestions which you might have on this @tuist/core

**Comment by dangthaison91** [comment]
@ollieatkinson As we support Scheme manifest in PR #336 #341  and Tuist support define all in the manifest file so IMHO we should support ignore scheme in `Project/Workspace.swift` too.

Currently, Tuist will generate schemes for both defined scheme in the manifest and auto-generate target schemes.
```swift
let scheme = Scheme(name: "App-Release", ...)
let target = Target(name: "App", ....)
```
Above will generate both `App` and `App-Release` as shared scheme.

Should we generate `App-Release` only cause it is explicitly defined? If we agree to do that I think it will fit your suggestion to have option to ignore generate `shared` Scheme.

We can skip auto generating shared scheme for a Target if a scheme include that Target is defined. ofc we can mark it as local Scheme ~ `shared = false`.

cc @tuist/core

**Comment by pepibumur** [comment]
Do you think it'd be inconvenient from the user point of view defining a `Project.swift` for Carthage containing only the targets whose schemes will be compiled by Carthage? How common is that a project that contains a Carthage framework contains other targets that are irrelevant to Carthage.

If that's a common case, then I think it's fine introducing `--ignore-scheme` and `--only-scheme` arguments. That might be an interesting challenge for you @dangthaison91 to address.

**Comment by dangthaison91** [comment]
I'm not a Carthage user so have no ideas if it could be problem with it. Scheme is just introduced and not release yet so we could wait to other user tried it first.

**Comment by ollieatkinson** [comment]
This is no longer required as now we can specify custom schemes.
