### ISSUE TITLE
Is it possible to run CocoaPods without repo-update?

### ISSUE THREAD

**Issue by Tovkal** [tuist/tuist#2893]
## Context 🕵️‍♀️

I have a project where the Pods are committed to the repository and I am now migrating to Tuist. On of the targets in this modular project has dependencies via Cocoapods.

## What 🌱

When running `tuist generate`, tuist is calling `pod install --repo-update`. This is specially quite slow on CI (that is why we have Pods committed to the repo in the first place 🥲), as it needs to download the whole repo.

In [CocoaPodsInteractor.swift (L46)](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/CocoaPodsInteractor.swift) I see the following code:

```
    public func install(graphTraverser: GraphTraversing) throws {
        do {
            try install(graphTraverser: graphTraverser, updatingRepo: false)
        } catch let error as CocoaPodsInteractorError {
            if case CocoaPodsInteractorError.outdatedRepository = error {
                logger.warning("The local CocoaPods specs repository is outdated. Re-running 'pod install' updating the repository.")
                try self.install(graphTraverser: graphTraverser, updatingRepo: true)
            } else {
                throw error
            }
        }
    }

    fileprivate func install(graphTraverser: GraphTraversing, updatingRepo: Bool) throws {
```

where `updatingRepo` does not seem to be settable from the outside. Am I right in assuming that, currently, there's no option to tell tuist not to run cocoapods without `--repo-update`?

**Comment by laxmorek** [comment]
Hey @Tovkal  

I think there is no option to remove `--repo-update` flag.

I think we could add it as a new option for `Config.swift` manifest file. [DOCS](https://docs.tuist.io/manifests/config#generationoption)

I could be named `.disablePodRepoUpdate`? 

What do you think @tuist/core  ?

**Comment by Tovkal** [comment]
After looking at this again with my brain on (🙈), I think this is not something related to tuist but rather cocoapods. Until now, as we had `Pods/` commited to the repo, there was no need for us to run `pod install` on CI. But now, with tuist, we do, as the projects are generated and it does not have the cocoapods dependencies. That causes `pod install` to clone `https://github.com/CocoaPods/Specs.git`, which does not exist in the CI machine and takes a long time.

So I am closing this, as tuist just executes `try install(graphTraverser: graphTraverser, updatingRepo: false)` so there's no need for an additional option in `Config.swift`.

Thanks for the help!
