### ISSUE TITLE
Tuist generate takes a lot of time in CI

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#2915]
**Describe the bug**
Running `tuist generate` locally usually takes just a few seconds, but when run in CI it takes more than a minute.
We have experienced it both in CircleCI and in GitHub action.
For reference in [this job](https://github.com/BendingSpoons/tempura-swift/runs/2519907173?check_suite_focus=true#step:4:9) it took 100 seconds (you have to enable timestamps to see the duration of each step) from the `Version 1.40.0 installed` to the `Generating workspace Tempura.xcworkspace` step:
```
Thu, 06 May 2021 16:03:48 GMT Version 1.40.0 installed
Thu, 06 May 2021 16:05:28 GMT Generating workspace Tempura.xcworkspace
```

**To Reproduce**

1. Setup a CI job that runs `tuist generate`
2. Run it

**Expected behavior**
`tuist generate` should takes a few seconds also in CI

**Additional context**

**Comment by kwridan** [comment]
Hi @danyf90 thanks for flagging this.

I believe what you're witnessing is Tuist's manifest caching behaviour working locally but not on CI. Depending on the CI setup, if the nodes where generation is made is not persisting the Tuist cache it will likely be slower on each generation. You could verify locally by comparing the "cold" (without cache) and "warm" (with cache) generation times.

- Wipe the local cache via `tuist clean`
- Run `tuist generate` _(this would be a "cold" measurement)_
- Run `tuist generate` again _(this would be the "warm" measurement)_

You could also conduct the same experiment on CI to see the measurement difference.

**Comment by fortmarek** [comment]
To cache on CI you can initialize your `Config` such as `let config = Config(cache: .cache(path: .relativeToRoot("Cache"))]))` (from [here](https://docs.tuist.io/building-at-scale/caching/#caching-profile)) and cache on CI the `ROOT/Cache` path. This should ensure that your generate runs on CI will be warm. I think we should edit the documentation to signal that this setting does not only apply to `tuist cache` only but also to caching of the manifests.

**Comment by danyf90** [comment]
I agree that in CI we are not caching the project, but I don't think that's the problem here.
The project is quite small, and I don't see how it could take 100 seconds just for the project generation part, excluding the pods (locally it takes 5 seconds on a cold start, including also the CocoaPods part if pods are cached).

From the logs you can see the time is spent between those 2 lines:
```
Thu, 06 May 2021 16:03:48 GMT Version 1.40.0 installed
Thu, 06 May 2021 16:05:28 GMT Generating workspace Tempura.xcworkspace
```
Isn't tuist caching involved only starting from `Generating workspace Tempura.xcworkspace`?

**Comment by fortmarek** [comment]
> Isn't tuist caching involved only starting from Generating workspace Tempura.xcworkspace?

No, because first we parse and compile all manifests, create a graph from them and only then start generating the workspace (which is when we output that string). However, I agree that for the project of that size, generate should be faster even on a cold run. If you run `tuist clean && tuist generate` locally, do you see cca. the same generation time?  If so, we could profile and see what the bottleneck is.

**Comment by danyf90** [comment]
nope, locally is much faster also with a cold start 👌

```
➜  tempura-swift git:(master) time tuist clean && tuist generate
Using version 1.40.0 defined at /Users/df/Developer/tempura-swift/.tuist-version
Successfully cleaned artefacts at path /Users/df/.tuist/Cache
tuist clean  0.04s user 0.03s system 97% cpu 0.078 total
Using version 1.40.0 defined at /Users/df/Developer/tempura-swift/.tuist-version
Generating workspace Tempura.xcworkspace
Generating project Tempura
Installing CocoaPods dependencies defined in /Users/df/Developer/tempura-swift
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
Project generated.
Total time taken: 2.543s
```

**Comment by himshikhar-sc** [comment]
Is there any way around this? Cold on local taking 8 secs and on CI taking 6 mins!

**Comment by himshikhar-sc** [comment]
> To cache on CI you can initialize your `Config` such as `let config = Config(cache: .cache(path: .relativeToRoot("Cache"))]))` (from [here](https://docs.tuist.io/building-at-scale/caching/#caching-profile)) and cache on CI the `ROOT/Cache` path. This should ensure that your generate runs on CI will be warm. I think we should edit the documentation to signal that this setting does not only apply to `tuist cache` only but also to caching of the manifests.

Tried this but the time in CI for project generation is still over 6 mins.

**Comment by fortmarek** [comment]
Hey @himshikhar-sc 👋 

If your project uses `.package`s defined in `Project.swift` (i.e. not via `Dependencies.swift`). You may wanna add `disablePackageVersionLocking` (see [here](https://docs.tuist.io/manifests/config/)) to your `Config.swift` if that's the case and see if `tuist generate` runs faster. Note that the build as a whole will probably still be slow since your packages are not cached and need to be resolved and built again.
