### ISSUE TITLE
Tuist generate project caching

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#2916]
**Describe the bug**
We have some project file which depends on external files not known by tuist.
Looks like tuist performs some caching and if only those file change, we need to perform a `tuist clean` in order to be able to properly regenerate the project.

**To Reproduce**

1. Download the attached zip
2. Generate the project using `tuist generate --open`
3. See that the main target name is `Found`
4. Close the project
5. Delete the file named `test`
6. Generate the project using `tuist generate --open`
7. See that the main target name is still named `Found`
8. Close the project
9. Clean the tuist cache using `tuist clean`
10. Generate the project using `tuist generate --open`
11. See that the main target name is now named `NotFound`

**Expected behavior**
It would be handy to have the possibility to inform tuist of additional files the project definition depends on, so that the `tuist generate` can work properly when those files change, without the need to manually run `tuist clean`

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Version: 1.40.0

**Additional context**
Sample project: [TestProject.zip](https://github.com/tuist/tuist/files/6450584/TestProject.zip)

**Comment by kwridan** [comment]
Hi @danyf90, mind re-attaching the sample project or pushing to GitHub? The attached `.zip` seems empty.

> Looks like tuist performs some caching and if only those file change, we need to perform a tuist clean in order to be able to properly regenerate the project.

The project manifests (`Project.swift`, helpers, etc...) are all cached to a json representation speed up generation to avoid needing to compile the Swift manifests each time which is much slower. Caching is done at the manifest level rather than the individual project sources/files - i.e. the manifest files will only ever be complied once if their contents don't change.

Would be good to see the sample manifest/project to get a better idea of what's happening in this specific case.

**Comment by danyf90** [comment]
@kwridan please try now :pray:

**Comment by kwridan** [comment]
Thanks @danyf90 

Ah I see what is happening:

> `return FileManager.default.fileExists(atPath: "test") ? "Found" : "NotFound"`

Having executable code like this in the manifest is _possible_ but isn't the intended usage as it means the manifest is no longer deterministic 😞

Tuist supports [generation time configuration](https://docs.tuist.io/guides/environment) via special environment variables which may help in your case?

**Comment by danyf90** [comment]
:sisi: I imagined that was the problem.

The attached project is an over-simplification, but in our real scenario our tuist plugin provides helpers to generate the project using a lot of parameters/information coming from our backend, and passing all of them via environment variable would mean to have to pass a lot of them, so we have decided to serialize them to a file on disk

Our current workaround to this problem, is to manually run a `tuist clean` everytime such information changes, but it would be handy to be able to pass such information to Tuist (e.g. passing a list of files in the `Project` init which are taken into account in the caching mechanism)

**Comment by kwridan** [comment]
> it would be handy to be able to pass such information to Tuist (e.g. passing a list of files in the Project init which are taken into account in the caching mechanism)

Another approach along the same lines is to serialise the desired parameters to a file in environment variable form:

e.g.

```
# tuist.env
export TUIST_APP_NAME=MyAppName
export TUIST_APP_LOCALE=en
# ...
```

And then when invoking tuist:

```sh
source tuist.env
tuist generate
```

Hope something like that helps :)

**Comment by danyf90** [comment]
Thanks @kwridan , that's definitely a possibility, but it's still suboptimal with respect to a JSON.
For example, we have some set of information which is needed for all the bundle ids of the app, and putting them in a JSON dictionary keyed by the bundle id makes the data much more structured, and easier to be read from the plugin.

**Comment by pepibumur** [comment]
I'm chiming in here. As @kwridan mentioned, manifests should contain no side effects. If there's a need for that, I'd instead figure out how to incorporate that into Tuist with a proper API. Otherwise, we might fall into the trap of [optimizing](https://github.com/tuist/tuist/issues/3311) towards practices that are not recommended.

Considering you are generating a file at generation time and you'd like the hashing logic to account for it, what if we provide an API for passing additional hashable paths? For example:

```swift
let target = Target(additionalHashableDependencies: [.file("./test")])
```
Then the hashing logic would hash the file if it exists, and ignore if it doesn't.

**Comment by danyf90** [comment]
Thanks @pepibumur I was thinking of something along the lines of what you are proposing 🚀

Note that in my case the problem is not the hash/caching of a target, but rather that the project is not regenerated at all, because nothing known to Tuist is changed.

Probably it's due to the caching of ProjectDecriptionHelpers (in our real use case the helper is coming from a plugin).

**Comment by danyf90** [comment]
@fortmarek @pepibumur what do you think of adding an .additionalHashableDependencies to ProjectDescription.Project.ProjectOption?

**Comment by luispadron** [comment]
Slightly related to this issue (although more about how plugin are cached in general) #3370 fixes some issues around how the manifest were cached and introduces hashing to the contents of plugins.

**Comment by fortmarek** [comment]
> what do you think of adding an .additionalHashableDependencies to ProjectDescription.Project.ProjectOption?

Yes, this does feel as an appropriate place for that.

**Comment by danyf90** [comment]
As the problem is in caching of the Project manifest itself, I'm not sure we can solve it this way (or in any other way).

If we add this field, to calculate the hash to load from cache, we would need to load the manifest, which would defeat the purpose of having a cache in the first place :D

Do you have any other idea on how this can be achieved? Otherwise we can continue to clear the `~/.tuist/Cache/Manifests` cache on our side :D

**Comment by pepibumur** [comment]
Let's move the discussion about caching the loading of manifests to another issue.

**Comment by danyf90** [comment]
@pepibumur maybe the description is not clear but this is exactly that issue 🤔

**Comment by pepibumur** [comment]
Sorry, I meant the comment around [plugin caching](https://github.com/tuist/tuist/issues/2916#issuecomment-907698770). Let's keep the discussion focused on the issue you are bringing up here. I'd love to see an RFC proposal in the discussion forum with some potential solutions with their tradeoffs and your proposed solution.
