### ISSUE TITLE
 Setting the `CURRENT_PROJECT_VERSION` and `MARKETING_VERSION` not working.

### ISSUE THREAD

**Issue by VinayakKkini** [tuist/tuist#2918]
**Describe the bug**
 Setting the `CURRENT_PROJECT_VERSION` and `MARKETING_VERSION` not working.
 
**To Reproduce**

Create a default project following the guide: https://docs.tuist.io/tutorial/get-started/

Create the following extension in `Project+Templates.swift` 
```
extension SettingsDictionary {
    func setProjectVersions() -> SettingsDictionary {
        let currentProjectversion = "2.0.0"
        let markettingVersion = "3"
        return appleGenericVersioningSystem().merging([
            "CURRENT_PROJECT_VERSION": SettingValue(stringLiteral: currentProjectversion),
            "MARKETING_VERSION": SettingValue(stringLiteral: markettingVersion)
        ])
    }
}
```

Update the project instantiation  to include the above settings.

```
        return Project(name: name,
                       organizationName: "tuist.io",
                       settings: Settings(base: Settings().base.setProjectVersions(),
                                          configurations: [],
                                          defaultSettings: .recommended
                       ),
                       targets: targets
        )
```

**Expected behavior**

The `CURRENT_PROJECT_VERSION` and `MARKETING_VERSION`  should be updated in the generated project.

**Screenshots**
- None

**Desktop (please complete the following information):**
- OS: iOS
- Version: 1.34.0

**Additional context**
We use agvtool update the app version which updates only the plist file.(`CFBundleVersion`, `CFBundleShortVersionString`). We use fastlane to increment the build and version numbers. This action reads from the build settings of the project and not from the plist file. 

So we are trying to read the values from plist file and update the build settings.

**Comment by kwridan** [comment]
Hi @VinayakKkini , thanks for raising this.

Testing locally I was able to get the versions set in the generated projects.

![Screenshot 2021-05-10 at 07 06 27](https://user-images.githubusercontent.com/11914919/117613201-6a190980-b15e-11eb-9187-ec23fa767d4e.png)


A few small modifications I did to the steps described was using `SettingsDictionary().setProjectVersions()` and removing `configurations: []` as that yields generation errors _(means the project should have 0 configurations, which is invalid)_:

```swift
return Project(name: name,
                       organizationName: "tuist.io",
                       settings: Settings(
                           base: SettingsDictionary().setProjectVersions(),
                           defaultSettings: .recommended
                       ),
                       targets: targets)
```

Hope this helps

**Comment by pepibumur** [comment]
Feel free to reopen the issue if the solution proposed by @kwridan doesn't work for you :)
