### ISSUE TITLE
Create a GitHub action for Tuist

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#2973]
## Context 🕵️‍♀️
I started [implementing](https://github.com/tuist/tuist-action) a GitHub action to ease the usage of Tuist on GitHub workflows, but I didn't finish it.

## What 🌱
It'd be great to finish it and add a new section on the documentation site, **Continuous integration**, where we document how to do continuous integration of Tuist projects using this action.

**Comment by danyf90** [comment]
https://docs.tuist.io/guides/continuous-integration/#github-actions
