### ISSUE TITLE
Implement Bitrise step

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#2975]
## Context 🕵️‍♀️
Many CI services these days provide building blocks that can be combined to design the pipelines. One of the providers offering that option is [Bitrise](https://bitrise.com). Like I proposed [here](https://github.com/tuist/tuist/issues/2973) for GitHub actions, I think we should provide a Bitrise step (implemented in GoLang) and document how to set up CI for Tuist projects to run on Bitrise.

[Here](https://blog.bitrise.io/post/how-to-create-bitrise-step-in-go-flutter-example) is some useful documentation around how to create a Bitrise step

**Comment by ronanociosoig-200** [comment]
The correct link for Bitrise is this one: https://www.bitrise.io/

**Comment by leszko11** [comment]
I will give it a shot 🙋‍♂️

**Comment by pepibumur** [comment]
@leszko11 go for it! 🚀🚀🚀🚀🚀

**Comment by danyf90** [comment]
https://docs.tuist.io/guides/continuous-integration/#bitrise
