### ISSUE TITLE
Add a page to the documentation website to list all the fixtures

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#2980]
## Context 🕵️‍♀️
One recurrent thing that contributors and maintainers do on Slack is pointing people to fixture projects that they can use as a reference to set up their projects. This is time we are currently spending and that we could use more wisely if it was easier to discover those fixtures through the documentation website.

## What 🌱
I'd add a new page to the documentation website to list all the fixtures. We currently have a README.md file in the fixtures folder, but it's not straightforward to find. What I propose doing is adding a manifest file to each fixture directory, `.tuist-fixture.yaml` with the following content:

```yaml
title: "iOS app with CocoaPods frameworks"
platforms: ["iOS", "macOS"]
description: "...."
```
During the documentation build process, we'd read those files and generate a markdown page where each fixture project is represented by a section.

**Comment by danyf90** [comment]
Fixed in https://github.com/tuist/tuist/pull/4660
