### ISSUE TITLE
Don't hardcode the swift tools used when building the Swift packages

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#2982]
## Context 🕵️‍♀️
The `Package.swift` manifest that we generate for resolving and pulling the Swift packages of the project has the version of the Swift tools [hardcoded](https://github.com/tuist/tuist/blob/a34eccbcc702c11e8314420e30a658d64d3f8de3/Sources/TuistGraph/Models/SwiftPackageManagerDependencies.swift#L19). We can't make this assumption because it's the project the one deciding the version of Swift, not us.

## What 🌱
- Add a new attribute to the `Config.swift` where developers can indicate the version of Swift the project is using.
- Make it optional so it's not a breaking change. When it's not defined, I'd fallback to the environment's Swift version.

**Comment by apps4everyone** [comment]
you could also use the value for used e.g. in build settings .custom("SWIFT_VERSION", "5.4")...

**Comment by apps4everyone** [comment]
for the project

**Comment by apps4everyone** [comment]
maybe also `platforms´: e.g.: [.iOS(.v12)],
