### ISSUE TITLE
Shipped binary does not run natively on Apple Silicon

### ISSUE THREAD

**Issue by Christopher-Thiebaut** [tuist/tuist#2997]
## Context 🕵️‍♀️

> Currently, some of my app's dependencies do have the arm64 slice required by the iOS simulator on M1 Macs.  Since compile times for my app are much better on my M1 machine than on the intel machine available to me, I would like to be able to exclude those dependencies and do development on my project with an M1 Mac while working on portions of the app that do not require dependencies that are incompatible with Apple Silicon.
> 
> To that end, I wanted to use compiler directives such as :
> ```
>     public static var exampleDependency: TargetDependency {
>         #if arch(arm64)
>         return .project(
>             target: "ExampleDependency",
>             path: .relativeToRoot("Shims")
>         )
>         #else
>         return .xcFramework(path: "binaries/ExampleDependency.xcframework")
>         #endif
>     }
> ```
> to replace the incompatible dependency with a non-functional (but buildable) on only while working on an arm Mac.

## What 🌱

> Since project generation for the script-installed version always runs through Rosetta, any compiler directives related to ARM to not work.  (My current workaround is to build tuist from source, but that doesn't seem ideal.)

## Proposal 🎉

> The executable installed by the install script should be a universal binary if possible

**Comment by fortmarek** [comment]
Hi @Christopher-Thiebaut!

I have created a [PR](https://github.com/tuist/tuist/pull/3010) for this - right now, I am stuck at an error described there, will investigate further. Feel free to try the PR out, too (just check the branch and run `./fourier bundle all` to reproduce)

**Comment by Christopher-Thiebaut** [comment]
Thanks, @fortmarek I’ll have a look at that soon.

**Comment by apps4everyone** [comment]
great, any news here? Should I test on a M1?

**Comment by fortmarek** [comment]
I have not been able to finish the PR yet. I hope to finish it soon and will ping you once it's ready to test.
