### ISSUE TITLE
`swiftlint` fails on master

### ISSUE THREAD

**Issue by steprescott** [tuist/tuist#304]
**Describe the bug**

**To Reproduce**

1. Checkout master
2. Run `swiftlint` see there are violations.

**Expected behavior**
No violations to be found

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.13.6

**Additional context**
When I pulled in `master` to my branch & ran the linters with `rake style_correct` I found issues there. However after running `rake style_correct` Danger is now failing in my PR https://github.com/tuist/tuist/pull/269

**Comment by kwridan** [comment]
thanks for raising this, looks like there are a few updates needed for swiftformat too
