### ISSUE TITLE
Tuist Install error

### ISSUE THREAD

**Issue by stanikel-ford** [tuist/tuist#3055]
bash <(curl -Ls https://install.tuist.io)                                                                                                  ✔  10121  15:25:20
==> Downloading tuistenv...
==> Unzipping tuistenv...
==> Installing tuistenv...
Password:
mv: rename /tmp/tuistenv/tuistenv to /usr/local/bin/tuist: No such file or directory
/dev/fd/11: line 15: abort: command not found
sudo: 4294967295: invalid value
sudo: error initializing audit plugin sudoers_audit
/dev/fd/11: line 15: abort: command not found
==> tuistenv installed. Try running 'tuist'
==> Check out the documentation at https://tuist.io/docs

**Comment by luispadron** [comment]
Hey! This is a known issue caused by the latest release. We are looking into it and will have a fix tomorrow.

**Comment by fortmarek** [comment]
Thanks for reporting! Yes, this was caused by the latest release. I have fixed it manually plus [here](https://github.com/tuist/tuist/commit/ba28383dc89aab1d411002c0303fe794e24db767) for future releases.
