### ISSUE TITLE
[RFC] Add support for remote tuist dependencies in the Dependencies.swift file

### ISSUE THREAD

**Issue by danieleformichelli** [tuist/tuist#3057]
## Need/problem

The [Dependencies.swift](https://docs.tuist.io/guides/third-party-dependencies) project will allow to seamlessly integrate Tuist projects with third party dependencies from the three dependency managers in the industry for Xcode projects: `Carthage`, `CocoaPods`, and `Swift Package Manager`.

First party dependencies can be integrated using the same mechanism, providing they are distributed using one of the supported dependency managers.

Even if first party dependencies are already defined as `Tuist` projects (potentially with their own `Dependencies.swift` file), the main `Tuist` project should still need to leverage one of the three dependency managers to import it. To do so, the first party dependencies should expose their manifest file (`Podfile`, `Cartfile`, or `Package.swift`), which must also be kept in sync with whatever is written in their `Dependencies.swift`.

`Tuist` already allows to define dependencies from local `Tuist` project, but it currently doesn't work if that project defines some third-party dependencies in its `Dependencies.swift` file.

## Motivation

- We would provide a better experience integrating first-party dependencies defined with `Tuist` because developers don't need to define an additional manifest file.
- Developers would be sure that what they are testing while developing the library (defined in `Tuist`'s `Project.swift` file) is actually what will be imported in their app (which would need to be defined with another dependency manager, for example in a `Package.swift`).
- It's one more reason to adopt Tuist over other project generators.

### `Tuist/Dependencies.swift`

We would introduce a new property in the `Dependencies` struct file that projects could use to list the Tuist local or remote dependencies of their project:

```swift
import ProjectDescription

let dependencies = Dependencies(
    carthage: …,
    swiftPackageManager: …,
    tuist: [
        .init(git: "https://github.com/tuist/first-party", path: "ALibrary", .exact("X.Y.Z")),
        .init(local: "/path/to/Tuist/Project/"),
    ]
)
```

_Note_: the `path` parameter is optional (defaulting to the repo root) and is useful in case dependencies are part of a monorepo.

### `tuist dependencies fetch/update`

When running `tuist dependencies fetch/update` Tuist should be able to:
1. resolve the tuist dependencies to the actual versions/branch/commit to be used
   - This might be tricky, and in a first iteration we could just allow exact versioning, so we don't need to handle the dependencies resolution
2. download the dependencies and solve their `Dependencies.swift` recursively:
   - This could be done resolving all Tuist dependencies first, and then handle all the other dependencies as if they were defined in the "main" `Dependencies.swift` file. Of course there might be some conflicts (e.g. defining incompatible version ranges for the same dependency) and they should be handled properly
   - We will also need some kind of lock file, when we will actually implement version resolution in point 1
3. serialize the tuist graph so that it can be loaded in the main project
   - This should be quite easy as dependencies are already defined with tuist. We might even not need to do anything and the dependencies could be added using the already available [TargetDependency.project](https://docs.tuist.io/guides/dependencies#target-dependencies-across-projects) type, pointing to the project checked out at point 2

## Alternatives

- Developers need to keep defining separate manifests to integrate first party dependencies and their dependencies, which might be problematic in some cases.

## How we teach this

- We already have [documentation](https://docs.tuist.io/guides/third-party-dependencies/) about how to deal with third-party dependencies so we'd need to update it to onboard existing and new users into the new functionality.

**Comment by danyf90** [comment]
Closing as I don't think we'll work on it anytime soon

**Comment by fortmarek** [comment]
We no longer have `Dependencies.swift`, so I don't think this is relevant anymore. Let me know if you think otherwise
