### ISSUE TITLE
tuist edit is failing with error: Couldn't find resource named ProjectAutomation

### ISSUE THREAD

**Issue by didix21** [tuist/tuist#3065]
**Describe the bug**

`tuist edit` seems to be broken in tuist v1.44.0. When running the command the following error appers: 
`Couldn't find resource named ProjectAutomation`.

With v1.40.0 seems to work fine.

**To Reproduce**

1. `tuist install 1.44.0`.
2. `tuist local 1.44.0`.
3. `tuist init --platform ios`.
4. `tuist edit`.

**Expected behavior**

After running `tuist edit` must open xcode and allow to modify Project.swift file.

**Screenshots**

**Desktop (please complete the following information):**

- MacBook Air (M1, 2020)
- OS: macOS Big Sur v11.4
- Version: 1.44.0
- XCode 12.4

**Comment by danyf90** [comment]
Should be fixed if you try to reinstall it 🙏 
```
tuist uninstall 1.44.0 && tuist update
```

**Comment by didix21** [comment]
works, thanks!!
