### ISSUE TITLE
Homebrew error when running tuist up in Apple Silicon Macs (M1)

### ISSUE THREAD

**Issue by didix21** [tuist/tuist#3066]
**Describe the bug**
After running `tuist up` and installing carthage from `Setup.swift` using Homebrew on Apple Silicon macs fails. The following error is shown:

```bash
Using version 1.44.0 defined at /Users/didaccollpujals/repos/localfilter/KidsApp-tuist/.tuist-version
Setting up the environment defined in /Users/didaccollpujals/repos/localfilter/KidsApp-tuist/Setup.swift
Configuring Homebrew
Installing Homebrew package: carthage
/usr/bin/env brew install carthage
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
The '/usr/bin/env' command exited with error code 1
``` 

If I run `brew install carthage` works fine. 

**To Reproduce**

1. Configure Setup.swift:

```Swift
import ProjectDescription

let setup = Setup(
    requires: [],
    actions: [
        .homebrew(packages: ["carthage"]),
        .rome(platforms: [.iOS], cachePrefix: "5.3.2"),
        .carthage(platforms: [.iOS], useXCFrameworks: false, noUseBinaries: false),
    ]
)
```

**Expected behavior**
Install Carthage.

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.4
-  Mac: Apple Silicon.
- Version 1.44.0

**Additional context**
I could see some troubles related with M1 and homebrew are already solved here: [https://github.com/tuist/tuist/pull/2711](https://github.com/tuist/tuist/pull/2711). 

Any idea how to solve this?

**Comment by fortmarek** [comment]
Hi @didix21!

I believe [this](https://github.com/tuist/tuist/pull/3010) should fix it since the error seems to originate from the fact that tuist is run from rosetta. I will, unfortunately, have time to finish that only in the latter half of next week, probably. 

As for the current workaround, I worry there might not be any without modifying the source code - at least that's what I gathered from [this](https://github.com/Homebrew/brew/issues/10313) issue. IMHO, it's about time we support M1 Macs properly. If you wanted to, feel free to take on the PR, just let me know.

**Comment by didix21** [comment]
Hi @fortmarek 

Thanks for the quick answer.

**Comment by IlMatveev** [comment]
@fortmarek, when to expect a release with a fix for this issue?

**Comment by fortmarek** [comment]
Unfortunately, we have run into some issues - described in more detail [here](https://forums.swift.org/t/linking-against-a-fat-dynamic-framework-fails-in-arm64/49915). We will first need to resolve that before merging that PR

**Comment by didix21** [comment]
Hi @fortmarek, the issue you're mentioning is related or maybe causing this error?

```bash
Unable to use malformed module source info '/Users/username/.tuist/Versions/1.46.0/ProjectDescription.framework/Modules/ProjectDescription.swiftmodule/Project/x86_64-apple-macos.swiftsourceinfo'
Could not build Objective-C module 'ProjectDescriptionHelpers'

```

**Comment by fortmarek** [comment]
Hi, @didix21 - the error you see happens still when you run tuist up or in some other case?

**Comment by didix21** [comment]
Hi @fortmarek, I've found an issue already open about this: https://github.com/tuist/tuist/issues/2319. Answering your questions, it happens when I use tuist edit and I build the project Manifest.

**Comment by fortmarek** [comment]
Let's close this then and continue the discussion in that issue. Feel free to reopen if needed!
