### ISSUE TITLE
Localized intents definition files

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#3079]
**Context**

Per https://github.com/tuist/tuist/pull/3075#pullrequestreview-686566208 it seems we may not be handling the localization of intent definition files correctly in all cases. 

**Details**

Manually enabling localization in Xcode for intent definition files ends up nesting `.strings` files within it rather than other intent definition files. However it seems that #1269 added that behavior on purpose. Are there cases where both are possible or was it done by mistake?

![122437331-85630a00-cf91-11eb-9269-9396a9d84ef8](https://user-images.githubusercontent.com/11914919/122551544-06231400-d02d-11eb-8e1a-c0acc60dfe5d.png)

**Next Steps**

- [ ] Find out if both behaviours are correct
- [ ] Add support for nesting strings files within `.intentdefinition` files (in a similar manner to #3075)

**Comment by soaurabhcompass** [comment]
@kwridan I'm trying to figure out if there's a way to set target membership options for an `.intentdefinition` file. Would appreciate if you can help with a way around this.

<img width="143" alt="Target_Membership" src="https://user-images.githubusercontent.com/82376303/126837512-393047f5-c951-4064-b415-f3f4e1c9e0e2.png">
