### ISSUE TITLE
Add Punic to Environment Commands

### ISSUE THREAD

**Issue by DrewKiino** [tuist/tuist#3082]
## Context 🕵️‍♀️

Rome doesn't currently support remote caching `xcframeworks` while [Punic](https://github.com/summerlabs/punic) currently does, I think this integration would be great to share as part of the toolbox Tuist offers.

## What 🌱

Currently in the more recent versions of Xcode that require `xcframeworks` to be build from Carthage, the current setup of commands from Tuist doesn't allow easy integrations of such libraries to help support remove caching.

## Proposal 🎉

Add `Punic` to the set of integration tools given out by Tuist 👍🏼

**Comment by danyf90** [comment]
Closed as the preferred way of importing carthage is now Dependencies.swift
