### ISSUE TITLE
Generation fails in the event an empty .xcworkspace directory exists

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#309]
**Describe the bug**

In the event a workspace container (`.xcworkspace`) directory exists, `tuist generate` fails with the following error:

```
Error: The file “contents.xcworkspacedata” couldn’t be opened because there is no such file.
```

**To Reproduce**

- Run `tuist generate` within any of the fixtures in
- Delete the contents of the of the generated `.xcworkspace` (but not the directory itself)
- Run `tuist generate` a second time

Notice the error:

```
Error: The file “contents.xcworkspacedata” couldn’t be opened because there is no such file.
```

**Expected behavior**
Generation should succeed

**Additional context**

This can happen in cases where a checked in workspace file is deleted - e.g. 
https://github.com/tuist/tuist/pull/308

We could perhaps also check for the existence of a `.xcworkspacedata` file [here](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Generator/WorkspaceGenerator.swift#L121) to mitigate this.

**Comment by ollieatkinson** [comment]
> We could perhaps also check for the existence of a .xcworkspacedata file [here](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Generator/WorkspaceGenerator.swift#L121) to mitigate this.

This seems like a reasonable solution.
