### ISSUE TITLE
Error compiling the ProjectDescription framework

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#310]
**Describe the bug**
I created a project using Tuist and then built the `ProjectDescription` scheme. It compiles successfully but the linking command fails:

```
error: unable to open dependencies file (/Users/pedropinera/Library/Developer/Xcode/DerivedData/App-elzcgkrwqcgflmdpmbfiuvrmthbd/Build/Intermediates.noindex/App.build/Debug/AppDescription.build/Objects-normal/x86_64/AppDescription_dependency_info.dat)Command Ld emitted errors but did not return a nonzero exit code to indicate failure
```

**To Reproduce**
1. Create a new project with `tuist init`.
2. Generate the project `tuist generate`
3. Open the Xcode project.
4. Try to build the `xxxDescription` scheme.

**Expected behavior**
The target should compile successfully without any linker errors.

**Screenshots**
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/663605/54902072-a33b8480-4ed8-11e9-87d8-74614d6c2482.png">

**Desktop (please complete the following information):**
- Version: 0.11.0

**Comment by kwridan** [comment]
The next version should resolve this :)

https://github.com/tuist/tuist/pull/287

**Comment by pepibumur** [comment]
Ouch, I completely forgot about that one. Thanks @kwridan
