### ISSUE TITLE
📦 [v1.45.0][Dependencies.swift] The `tuist dependencies fetch` command fails. 

### ISSUE THREAD

**Issue by laxmorek** [tuist/tuist#3107]
**Describe the bug**

Since version `1.45.0` the `tuist dependencies fetch` command has started to fail for some Carthage dependencies: 

![205551031_816423105972582_2948630637521963999_n](https://user-images.githubusercontent.com/4774319/123328985-8faa7880-d53c-11eb-962d-940db40f8331.png)

**To Reproduce**

1. Update `tuist` to `1.45.0`.
2. Update the `Dependencies.swift` manifest file: 

```swift
import ProjectDescription

let dependencies = Dependencies(
    carthage: [
        .github(path: "realm/realm-cocoa", requirement: .exact("10.7.6")),
    ],
    platforms: [.iOS]
)
```

3. Run `tuist dependencies fetch`

**Expected behavior**

The `tuist dependencies fetch` should complete without errors.

**Additional context**

`tuist` tries to decode [VersionFiles](https://github.com/Carthage/Carthage/blob/master/Documentation/VersionFile.md#version-files) that was produced by `Carthage` to [CarthageVersionFile](https://github.com/tuist/tuist/blob/main/Sources/TuistDependencies/Carthage/Models/CarthageVersionFile.swift). For some dependencies (e.g. [realm-cocoa](https://github.com/realm/realm-cocoa)) some properties of `CarthageVersionFile .Product` may not exist.

`.Kingfisher.version` - all properties exist

<img width="629" alt="Zrzut ekranu 2021-06-24 o 22 56 53" src="https://user-images.githubusercontent.com/4774319/123331348-7951ec00-d53f-11eb-8ae8-0638418b95b9.png">

`.realm-cocoa.version` - `swiftToolchainVersion` doest exist 

<img width="633" alt="Zrzut ekranu 2021-06-24 o 23 07 11" src="https://user-images.githubusercontent.com/4774319/123332538-ea45d380-d540-11eb-87e7-44a5ba29b751.png">

**How to fix it?**

1. We can make properties of `CarthageVersionFile .Product` optional and decode them using `decodeIfPresent`.
2. We can stop decoding all properties since we don't need all of them. Today we need only `CarthageVersionFile .Product.name` and `CarthageVersionFile .Product.container`. `CarthageVersionFile .Product.identifier` was removed in [#3099](https://github.com/tuist/tuist/pull/3099). Other properties are not used.

**Comment by danyf90** [comment]
I agree we should decode only the fields we need 👍

**Comment by fortmarek** [comment]
Thanks for finding this! Yes, I think it's a good idea to just decode information that we need. Can we sure about the fields that we do need that those will always be present?

**Comment by laxmorek** [comment]
Thanks for your answers. 

> I agree we should decode only the fields we need

I prefer this strategy as well. 

> Can we sure about the fields that we do need that those will always be present?

Today we need `container` and `identifier` fields. Unfortunately I haven't found any informations that they always be present or not. :/

**Comment by fortmarek** [comment]
> Unfortunately I haven't found any informations that they will always be present or not. :/

Let's presume it is - if we encounter an error regarding this, we can always change it to optional 🙂

**Comment by havebeenfitz** [comment]
Hi! I experience kind of the same thing but after update with different key, which is not present

I have the `WebRTC` library that doesn't follow version convention, so it reqiured some hacks

I have the `json` file which states:

```
{
    "2.1.0": "https://demo.ahoyrtc.com/v2.1.zip"
}

```
And in the `Dependency.swift` I have

`.binary(path: "LocalDependencies/AhoyRTC.json", requirement: .exact("2.1.0"))`

And it fails with this:

```
We received an error that we couldn't handle:
    - Localized description: The data couldn’t be read because it is missing.
    - Error: keyNotFound(CodingKeys(stringValue: "container", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "iOS", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"container\", intValue: nil) (\"container\").", underlyingError: nil))"
```

.version file unfortunately doesn't have a `container` But it was a 

```
{
  "Mac" : [

  ],
  "watchOS" : [

  ],
  "tvOS" : [

  ],
  "commitish" : "2.1.0",
  "iOS" : [
    {
      "name" : "AhoyKit",
      "hash" : "c963ec94999f3fe64f75880ba394338d5c694a5cec8f756bc35481f3b8c8b4d2",
      "linking" : "dynamic"
    },
    {
      "name" : "WebRTC",
      "hash" : "3a9ced64f6f8ccca46dc0038bdbf3efd8cf98f73cbc29ee1b00d98757b7fab33",
      "linking" : "dynamic"
    }
  ]
}
```

I'm not sure if this hack with versions is causing the issue or not, but it would be great to exclude `container` key from required as well I  guess
