### ISSUE TITLE
When running tuist through mint it does not locate the ProjectDescription framework

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#315]
**Describe the bug**

When running tuist through mint it does not locate the ProjectDescription framework

```
mint run tuist/tuist tuist generate 
🌱  Using tuist/tuist 0.13.0 from Mintfile.
🌱  tuist 0.13.0 already installed
🌱  Running tuist 0.13.0...
❌ Error: Couldn't find ProjectDescription
```

**To Reproduce**

1. `$ mint run tuist/tuist tuist generate`

**Comment by pepibumur** [comment]
We'll need to add the directory where Mint builds the projects to the path where frameworks and libraries are looked up. Good catch @ollieatkinson. 

I wonder if it makes sense to offer support for it. I think it'd make sense if we didn't provide any mechanism for managing several versions of Tuist but we do.

**Comment by ollieatkinson** [comment]
I had the same thought, since we have the ability to support versioning from within the tool I don't think we need to let another tool manage it too.

**Comment by ollieatkinson** [comment]
Closing as wont-fix
