### ISSUE TITLE
Allow to define a custom location for a remote plugin

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3150]
**Describe the bug**
We have a monorepo with a number of projects, and we would like to be able to also have our tuist plugins in the same monorepo.

The problem is that tuist assumes the `Plugin.swift` file to be in the monorepo root which is a problem for 2 reasons:
1. It doesn't allow to have 2 plugins in the same repo
2. we would like each project to be confined in its own folder

**Expected behavior**
The `Config.plugin.git` method could accept an additional parameter which specifies the location of the Plugin.swift file (defaulting to `Plugin.swift` in the root of the repo)

**Comment by fortmarek** [comment]
Hi @danyf90!

Could you maybe expand a little on your setup?

If I understand it correctly, you have something along the lines of:

```
| - monorepo
|       - Project
|            - Config.swift
|            .....
|       - PluginA
|            - Plugin.swift
|       - PluginB
|            - Plugin.swift
```

What exactly is then failing? You should be able to reference the plugin files from `Project/Config.swift` or?

**Comment by danyf90** [comment]
The other items in the monorepo are not importing the plugin directly (actually we expose part of it through SPM, but it's not relevant for this), so what we have is
```
 | - monorepo
|       - SomeProjectA
|            …
|       - SomeProjectB
|            …

 | - pluginrepo
|       - ProjectDescriptionHelpers
|            …
|       - Plugin.swift
|            …
```

and what we would like to have is
```
 | - monorepo
|       - SomeProjectA
|            …
|       - SomeProjectB
|            …
|       - Plugin
|            - ProjectDescriptionHelpers
|                 …
|            - Plugin.swift
|                 …
```
