### ISSUE TITLE
Support Xcode 10.2 and Swift 5

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#316]
**Describe the bug**

When Xcode 10.2 is the selected version of Xcode to use for xcodebuild tuist will not run.

```
tuist generate
No local versions available. Installing the latest version 0.13.0
Verifying the Swift version is compatible with your version 5.0
❌ Error: Found 5.0 Swift version but expected 4.2.1
```

**Comment by pepibumur** [comment]
Great that the tool is catching the incompatibility. The good thing is that from Swift 5 we shouldn't have to check that anymore.
