### ISSUE TITLE
Add Carthage frameworks to DependencyGraph

### ISSUE THREAD

**Issue by havebeenfitz** [tuist/tuist#3174]
## Context 🕵️‍♀️

There is a case when Dependencies Graph is not quite accurate

## What 🌱

When we import `Carthage` dependency as a `binary`, `Carthage` `*.version` file is created without the `container` key and Dependecy graph relies on that key. So for now graph is just hiding this dependency with warning. Warning will be raised after [3164](https://github.com/tuist/tuist/pull/3164#issue-685323953) is merged.

## Proposal 🎉

So we need to add those `binary` dependencies to graph, but we also need to take into account various platforms if included in `Dependencies.swift`, such as `macOS`, `tvOS` and others. When imported as `binary`, `Carthage/Build` creates additional folder name by OS, for example. `iOS` or `Mac` so the path looks different, for example: `/Carthage/Build/iOS/GoogleMaps.framework`. 

The plan is to match the framework with the platform and give the `DependenciesGraph` it's content in the following format: `{dependencyName}.{dependencyPlatform}.framework`, for example: `GoogleMaps.iOS.framework`. That way we will have all the frameworks present in graph when requesting it by `tuist graph`

**Comment by danyf90** [comment]
Closing as we are dropping support for carthage in dependencies.swift
