### ISSUE TITLE
Tips for running on the CI

### ISSUE THREAD

**Issue by dtorres** [tuist/tuist#3188]
It would be great to have an official guideline to run Tuist on the CI and how to improve performance.
In the meantime, here are some of the things I've found while adopting it in Circle CI

- Since Tuist doesn’t generate any sort of .lock file, I ended up creating my own to act as a key for cache retrieval
- A cache miss in Tuist results in the whole manifest being loaded (5s vs 40s in our case) so having an accurate state is important 
     - We are currently caching `~/.tuist/Versions` and `~/.tuist/Cache`
     - Our cache key is the hash of the file resulting from this command: 
     ```bash
          find Project.swift Tuist -type f | xargs shasum > Tuist.lock
     ```
- Caching the Tuist binaries instead of vendoring (adding to the repository) seems to be better (at least in Circle CI, restoring a complex directory hierarchy such as Tuist’s resulted also in ~30s difference)
- For a project with a few targets (2 main apps, 3 internal dependencies), there doesn’t seem to be a measurable advantage to using focus over generating the whole project
- Executing tuist directly instead of installing tuist-env is possible but again, gains were minor, even when this involves a network request

**Comment by didix21** [comment]
I agree, some tips for running on CI would be fine to be documented. However, I'm wondering if caching `~/.tuist/Cache` is  something that should be done in a CI. The problem I see is when running tests. Tuist checks which target has changed and then run tests for that target or not. But maybe on the CI always must run all tests.

```Bash
Generating project for testing
TargetTests1 has not changed from last successful run, skipping...
TargetTests2 has not changed from last successful run, skipping...
```

**Comment by dtorres** [comment]
We don’t (currently) run the tests with Tuist, however when we eventually do, it would make sense for us to only run a subset of tests so it works for us.

I’m not on the computer so I can’t check if it already exists, but maybe an option to explicitly run all tests is what you actually want
