### ISSUE TITLE
Add `excludes` variable to ResourceFileLists

### ISSUE THREAD

**Issue by havebeenfitz** [tuist/tuist#3192]
## Context 🕵️‍♀️

> You can exclude certain files in `SourceFileGlob`, but it would be nice to have that for `ResourceFileElement` as well. Maybe it would be nice to rename `ResourceFileElement` to `ResourceFileGlob`. That way API would be more consistent and easy to use

## Proposal 🎉

> Add `excludes` variable to `ResourceFileElements` with default [ ] in initializer to avoid breaking changes. React to not empty `excludes` and don't add this files to project resources

**Comment by danyf90** [comment]
I think it makes sense to add this capability to resources as well 👍 
It would also solve some problems with Dependencies.swfit, as we might need to exclude some resources from some packages, depending on the Package manifest
