### ISSUE TITLE
🐶 [DogFood] Group related targets in the same scheme

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3213]
Right now, there are a lot of auto-generated schemes in the Tuist Xcode project generated with Tuist (they don't even fit in the screen and it's painful to have to reach the bottom of the screen and scroll the list to be able to edit the Scheme execution, for example to choose the parameters to be passed).
It would probably help to group similar ones in the same scheme, for example having a `TuistDependencies` scheme with `TuistDependencies` and `TuistDependenciesTesting` as build phase, and `TuistDependenciesTests` as test phase.
This would cut the list approximately to 1/3, making it much easier to discover the desired scheme

**Comment by fortmarek** [comment]
> they don't even fit in the screen and it's painful to have to reach the bottom of the screen and scroll the list to be able to edit the Scheme execution, for example to choose the parameters to be passed

Just for the reference, you can use Xcode shortcuts for this (ctrl + 0 and then start typing to find the right scheme). But yeah, if you don't know what you're looking for, you'll still need to scroll through that list.

> It would probably help to group similar ones in the same scheme, for example having a TuistDependencies scheme with TuistDependencies and TuistDependenciesTesting as build phase, and TuistDependenciesTests as test phase.

While that would help, I think we should stick to the defaults tuist offers as much as possible. So, if we don't deem `TuistDependenciesTests` to be necessary, we should probably consider not auto-generating at all (for some cases, at least - e.g. if a test target is only testing a single framework, it might make sense to just add it as a test action there)

**Comment by danyf90** [comment]
> While that would help, I think we should stick to the defaults tuist offers as much as possible. So, if we don't deem TuistDependenciesTests to be necessary, we should probably consider not auto-generating at all (for some cases, at least - e.g. if a test target is only testing a single framework, it might make sense to just add it as a test action there)

I agree with this 👍
