### ISSUE TITLE
ProjectFileElement cannot distinguish folders from files

### ISSUE THREAD

**Issue by marciniwanicki** [tuist/tuist#322]
**Describe the bug**
Project generation will fail if any of the source file parents (folders) contains "." in its name. `ProjectFileElements` has a method `isGroup` which decides if an absolute path should be reflected by a group in the project or not. Currently, the implementation using the filename format to determine the type of the element.

As a result, also some files might be generated as groups if they do not have an extension, i.e. `Makefile` or `README`.
<img width="245" alt="Screen Shot 2019-04-16 at 10 16 36 AM" src="https://user-images.githubusercontent.com/946649/56197561-03819a00-6031-11e9-8fb6-7dc5902b8436.png">

```swift
    func isGroup(path: AbsolutePath) -> Bool {
        return !isVersionGroup(path: path) && path.extension == nil
    }
```

**To Reproduce**
- Create a new folder with "." inside `Sources`, i.e. `Headers.private`
- Run the generation 
- Result: 
```
Error: The operation couldn’t be completed. (TuistGenerator.BuildPhaseGenerationError error 0.)
	 Description: Trying to add a file at path /Project/Sources/Headers.private/SourceFile.swift to a build phase that hasn't been added to the project.
```

**Expected behavior**
All source files and groups are generated correctly without any errors.

**Additional context**
It's very easy to just rename the folder but in some cases people might want to use 3rd party projects without modifying them locally.

**Comment by pepibumur** [comment]
I'm looking into this one.

**Comment by kwridan** [comment]
#338 resolves this issue 🙂
