### ISSUE TITLE
Import plugins inside tasks

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#3229]
## Context 🕵️‍♀️

I've a block of code that I want to run inside of more than one task. 
I've tried to create a plugin and import inside the task, but It's not possible, seems like plugins are only for project (you could define tasks inside a plugin and run it but their cannot be used from other tasks)

## What 🌱

I want to reuse code for tasks not for project generation. This code is something like utilities for tasks

## Proposal 🎉

Add support to import plugins inside tasks or make tasks that could use other tasks or something that allows to reuse code to use in tasks. Maybe add support to add dependencies to task autogenerated frameworks could be a solution.

Thanks for your support

**Comment by fortmarek** [comment]
Thanks @jesus-qt for raising this!

It is a known limitation, I'd like to work on this soon. As it has not been raised in any issue, I'll keep this opened 👍

**Comment by danyf90** [comment]
Should now be possible since Tuist 3.0
