### ISSUE TITLE
Bug: Tuist Test -T does not exists

### ISSUE THREAD

**Issue by jesus-qt** [tuist/tuist#3230]
**Describe the bug**
We cannot redirect the result of test to a concrete path.

**To Reproduce**
* tuist test --help:
` tuist test [<scheme>] [--clean] [--path <path>] [--device <device>] [--os <os>] [--configuration <configuration>] [--skip-ui-tests]`

Documentation:
[Tuist.io](https://docs.tuist.io/commands/test/#arguments)
--result-bundle-path | -T | Path where test result bundle will be saved

**Desktop (please complete the following information):**

- OS: macOs 11.3.1
- Tuist Version: 1.46.1

**Comment by fortmarek** [comment]
Hi @jesus-qt!

This option is only on `main` at the moment (as it's in the [#Next section in changelog](https://github.com/tuist/tuist/blob/main/CHANGELOG.md#next)). I will create a new release soon that should contain this.
