### ISSUE TITLE
❌ Error: The file  couldn’t be saved in the folder 

### ISSUE THREAD

**Issue by dangthaison91** [tuist/tuist#324]
**Describe the bug**
```ruby
Generating project FeatureA
❌ Error: The file “FeatureA.xcodeproj” couldn’t be saved in the folder “FeatureA”.
```
**To Reproduce**

1. Create sample project in another Volume, not same location where Tuist is installed (often is `/usr/local/bin/`)
2. Run generate
3. Try to put project at the same Volume with `Tuist`, it will generate successfully.

**Expected behavior**
Generated project file will be saved successfully.

**Additional context**
I found that Tuist is using `replaceItemAt` function to overwrite generated file. According to Apple documents, this function will only work when **originalItemURL and newItemURL parameters are located on the same volume**:

[https://developer.apple.com/documentation/foundation/filemanager/2293212-replaceitemat](url)

IMHO, the simple solution could be: first remove current file then copy the new generated file to project location.

```swift
    public func replace(_ to: AbsolutePath, with: AbsolutePath) throws {
        try FileManager.default.removeItem(at: to.url)
        try FileManager.default.copyItem(at: with.url, to: to.url)
    }

```

**Comment by kwridan** [comment]
Thanks for flagging this @dangthaison91! 

The motivation for using `replaceItem` was to mitigate data loss should the write fail. 

Reading the docs further it seems there's a suggestion on how to solve this issue:

> This method works only when the `originalItemURL` and `newItemURL` parameters are located on the same volume. Attempting to call this method by passing `originalItemURL` and `newItemURL` parameters that have locations on different volumes results in an error. Instead, you can call the `url(for:in:appropriateFor:create:)` method, passing `FileManager.SearchPathDirectory.itemReplacementDirectory` as the search path directory, to get a temporary `URL` on the destination's volume that is suitable for use with this method.

e.g.

```swift
let fileManager = FileManager.default
let tempUrl = try fileManager.url(for: .itemReplacementDirectory,
                                              in: .userDomainMask,
                                              appropriateFor: to.url,
                                              create: true)
                                        .appendingPathComponent("temp")
try fileManager.copyItem(at: with.url, to: tempUrl)
 _ = try fileManager.replaceItemAt(to.url, withItemAt: tempUrl)
```

Locally managed to reproduce this issue by placing one of the fixtures in my Google Drive and attempting to generate it via Tuist.

**Comment by kwridan** [comment]
As an optimization, we could consider changing/Adding `FileHandler.inTemporaryDirectory` to one that takes an additional parameter to determine which volume it should create the temporary directory in e.g. 

```swift
public func inTemporaryDirectory(for destination: AbsolutePath, _ closure: (AbsolutePath) throws -> Void) throws {
        let fileManaer = FileManager.default
        let tempUrl = try fileManager.url(for: .itemReplacementDirectory,
                                          in: .userDomainMask,
                                          appropriateFor: destination.url,
                                          create: true).appendingPathComponent("temp")
        closure(AbsolutePath(tempUrl.path))
        try fileManaer.removeItem(at: tempUrl)
    }
```

This would ensure the temp directories used during the writing process are suitable for use with `replaceItem`/
