### ISSUE TITLE
📦 [Dependencies.swift][SPM] Fix `Firebase` import

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3241]
**Describe the bug**
The [Firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk) doesn't link correctly when imported via `Dependencies.swift`.

**To Reproduce**
1. Download the [attached project](https://github.com/tuist/tuist/files/6945463/TuistTest.zip)
2. Run `tuist dependencies fetch` and `tuist generate --open`
3. Build from Xcode
4. Linking fails with errors:
```
Undefined symbol: std::terminate()
Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)
Undefined symbol: ___cxa_begin_catch
Undefined symbol: leveldb::WriteBatch::WriteBatch()
Undefined symbol: leveldb::WriteBatch::Clear()
Undefined symbol: operator delete[](void*)
Undefined symbol: leveldb::WriteBatch::~WriteBatch()
Undefined symbol: leveldb::WriteBatch::Put(leveldb::Slice const&, leveldb::Slice const&)
Undefined symbol: leveldb::WriteBatch::Delete(leveldb::Slice const&)
Undefined symbol: leveldb::DB::Open(leveldb::Options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, leveldb::DB**)
Undefined symbol: leveldb::Status::ToString() const
Undefined symbol: ___gxx_personality_v0
Undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()
Undefined symbol: leveldb::Options::Options()
```

**Comment by danyf90** [comment]
The `std::` ones go away if we manually add `libc++.tbd` as linker dependency in the `Link Binary With Libraries` build phase.

The others missing symbols seems to come from the `leveldb` dependency.

@fortmarek @pepibumur @kwridan do you have any idea of what we might be missing? 🙏

**Comment by kwridan** [comment]
Hi @danyf90 

Looks like you've already found one of the issues re: `libc++.tbd`, any target that has c++ code need to declare a dependency on `.sdk(name: "libc++.tbd")` - the generator logic will ensure this propagates to the appropriate target (ref: https://github.com/tuist/tuist/issues/438).

The other issue with levels db, seems like generated project for it is missing sources?

![Screenshot 2021-08-09 at 13 16 49](https://user-images.githubusercontent.com/11914919/128705341-2b661f9f-5dd9-4234-a2a5-034696d2caf2.png)
 
Hope this helps!

**Comment by danyf90** [comment]
Many thanks for your help!

For the `libc++.tbd` dependency, we are adding it if defined in the SPM package (e.g. [here](https://github.com/firebase/firebase-ios-sdk/blob/853fdf91430228e137f926b8a5bb28c698a95542/Package.swift#L289)), but in this case looks like that setting is missing 🤔 

Thanks for pointing out the empty sources, will have a look at the generated project and will let you know 🙌
