### ISSUE TITLE
📦 [Dependencies.swift][SPM] Avoid absolute paths in generated graph.json

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3242]
The SPM to Tuist project mapping right now uses absolute paths for some properties.
We should try to change it to use relative path wherever possible to improve project portability

**Comment by danyf90** [comment]
@fortmarek @pepibumur the graph.json is just a number of serialized `Project.swift` so we can't really change it unless we change the Codable logic of TuistGraph, which I don't think is something we want to do, right?

**Comment by pepibumur** [comment]
What about using a custom encoder/decoder that has the context of the path from where the `graph.json` is loaded. Then you can use that information to make the paths relative when encoding, and absolute when decoding.

**Comment by danyf90** [comment]
It's surely possible, but before doing such a non-trivial change, I would like to understand what are the actual benefits of doing it.

As far as I can tell, the graph.json file should not be committed and is generated by the `tuist dependencies fetch` command, so there isn't much benefit in making it use relative paths instead of absolute ones.
Could you please clarify what we would gain from this change? 🙏

**Comment by pepibumur** [comment]
> Could you please clarify what we would gain from this change? 🙏

We'd gain not having a project that depends on the environment. We are assuming now that developers won't be committing that directory but this is an assumption. Tuist doesn't enforce that and therefore it doesn't prevent developers from doing that and ending up with projects that fail to be generated. I think it's a good principle to align with to prevent issues like that one.
