### ISSUE TITLE
Fixtures and example improvement

### ISSUE THREAD

**Issue by Craz1k0ek** [tuist/tuist#3258]
## Context 🕵️‍♀️

I ran into some issues whilst creating a project with CoreData. I ended up going to the Slack channel where I got pointed to the fixtures folder. This is a big resource for users, as there are some very nice project templates and examples, but there is nothing on the website or in the README that points to this folder.

## What 🌱

There are multiple options to help users find these fixtures. For a starter I would point to this folder (and maybe clean up the folder a little) from the website. In addition, it might be a cool idea to add these fixtures as templates/scaffold to leverage the `tuist scaffold` command fully. The latter one might require the fixtures to have some minor tweaks.

**Comment by luispadron** [comment]
@Craz1k0ek Agree! Feel free to put up a PR with changes to the README you think would be helpful, happy to review!

**Comment by fortmarek** [comment]
> it might be a cool idea to add these fixtures as templates/scaffold to leverage the tuist scaffold command fully.

I love this! This would make a big difference for the users. If you wanted to implement this, I can give you some pointers. I'd start with a draft PR that would include an example of one template and we can go from there.

**Comment by danyf90** [comment]
Duplicate of https://github.com/tuist/tuist/issues/2980
