### ISSUE TITLE
Linker flags for Cocoapods and SPM dependencies got mixed up followed by undefined symbols

### ISSUE THREAD

**Issue by havebeenfitz** [tuist/tuist#3259]
**Describe the bug**
In our project there are 3 dependency managers. The reason for that is that we're in transition from Carthage to SPM and we're also forced to use Cocoapods for some unavoidable product libraries. Cocoapods generates -ObjC for `Other Linker Flags` in target build settings. And Firebase Analytics, which used from SPM, requires the same flag which we need to force set on target

When Xcode tries to link all compiled sources, it fails with `undefined symbols for architecture ...`

**To Reproduce**

1. Install dependency  containing Objective-C through Cocoapods
2. Install dependency  containing Objective-C through SPM
3. Build the application
4. Objective C methods called from SPM dependency are not seen by linker with `undefined symbols` error

**Expected behavior**
The application builds successfully

**Screenshots**

<img width="394" alt="Screenshot 2021-08-03 at 11 36 41" src="https://user-images.githubusercontent.com/31866271/127984921-ccf64815-a497-46ac-9701-6757aac80c3b.png">
<img width="564" alt="Screenshot 2021-08-03 at 11 36 52" src="https://user-images.githubusercontent.com/31866271/127984929-23032487-7ee9-4840-8d9b-33bc052fa732.png">

Cocoapods xcconfig:
<img width="293" alt="Screenshot 2021-08-03 at 11 37 42" src="https://user-images.githubusercontent.com/31866271/127985017-a4f45042-cb09-4ab4-8995-a0df085c757e.png">

- Xcode 12.5.1
- tuist 1.47.0

**Additional context**

Target `OTHER_LD_FLAGS` with tuist:

`$(inherited) -ObjC` translates to `-ObjC {other flags generated by cocoapods}`. Last `-ObjC` overriden by `pod install` I guess

Target `OTHER_LD_FLAGS` with xcodegen

`$(inherited) -ObjC` translates to `-ObjC {other flags} -ObjC`

---

However adding `-ObjC` manually to tuist generated target build settings doesn't help to fix the linking phase, same `undefined symbols` occurs

**Comment by Banck** [comment]
@havebeenfitz Hello!
Did you solve this issue?

**Comment by danyf90** [comment]
It should work fine now using Dependencies.swift for SPM, as you can see from [this fixture](https://github.com/tuist/tuist/blob/main/projects/tuist/fixtures/app_with_spm_dependencies/Project.swift)

**Comment by Banck** [comment]
@danyf90 Strange.. With this approach i can't even build: **Expected a platform name here**
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/6259254/149392935-171f12bc-5655-4b95-bae9-4b3e82c7e934.png">

**Comment by Banck** [comment]
> @havebeenfitz Hello!
> Did you solve this issue?
This issue happens because of deployment target iOS 10.0. Due to 32 bit architecture

**Comment by havebeenfitz** [comment]
Unfortunately, I had to drop the tuist adoption in that project. Ran out of time
