### ISSUE TITLE
`tuist local master` fails

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#326]
# Issue

It appears using `tuist local master` fails to install the latest version of tuist which is now being built with Swift 5.

# Details

`TuistEnvKit` may require an update to support Swift 5. 

# Reference

![image](https://user-images.githubusercontent.com/605076/56098337-27958c00-5f08-11e9-924d-33b6c24d6cc1.png)

_Originally posted by @freak4pc in https://github.com/tuist/tuist/pull/317#issuecomment-483050927_

**Comment by kwridan** [comment]
I wonder if it's worth adding an acceptance test for `tuistenv`?  this can easily be missed :/

**Comment by freak4pc** [comment]
It should probably be part of CI if it's not already

**Comment by pepibumur** [comment]
> I wonder if it's worth adding an acceptance test for tuistenv? this can easily be missed :/

We should 😬

**Comment by ollieatkinson** [comment]
From my limited checking, it's because we are still referencing `-Xswiftc -static-stdlib` from TuistEnvKit:

![A37E384E-077F-427E-BAE3-F09ECC260C4C](https://user-images.githubusercontent.com/1382565/56505835-a3996080-6514-11e9-9095-4859230cfe54.png)

In regards to the acceptance test, what would be the best way to validate tuistenv @pepibumur ?

**Comment by pepibumur** [comment]
> In regards to the acceptance test, what would be the best way to validate tuistenv @pepibumur ?

I suggest writing an acceptance test that:
- Compiles `tuist` and `tuistenv`.
- Places tuist in `~/.tuist/Versions/x.y.z`
- Adds a `.tuist-version` file in a temporary directory pointing to `x.y.z`.
- Run `tuistenv` from that directory passing the `--help` command.
- Remove the files that have been created for the test and placed in the environment.
