### ISSUE TITLE
Dependencies.swift SPM BinaryTarget’s xcframework are not available in artifacts folder

### ISSUE THREAD

**Issue by apps4everyone** [tuist/tuist#3269]
When using the new Dependencies.swift (build from feature/dependencies/spm/container) SPM external dependencies with BinaryTargets the xcframework's are not available in the artifacts folder.

I get the error:
Couldn’t find xcframework at ...project/Tuist/Dependencies/SwiftPackageManager/artifacts/XYZSDK/ZYX.xcframework

**Comment by danyf90** [comment]
Hi @apps4everyone, could you add a real case example?
Using the project attached in this [issue](https://github.com/tuist/tuist/issues/3241) the Firebase artifacts get correctly downloaded in the artifacts folder

**Comment by apps4everyone** [comment]
hey, thx tested you example and it worked. Unfortunately it is an internal swift package with:

.binaryTarget(
  name: "ZYX",
  path: "frameworks/ZYX.xcframework"
),

inside the package. The difference I can see here is Firebase is using zip with url and hash not path.

**Comment by danyf90** [comment]
Is the artifact used in any of the products of that package? If not, it's probably the reason why SPM doesn't download it.

**Comment by apps4everyone** [comment]
it is used inside of the Package.

**Comment by danyf90** [comment]
As discussed with @apps4everyone , there is a missing mapping for SPM packages with local binary dependencies (while remote ones work fine).
He will open a PR to fix the problem
