### ISSUE TITLE
Prevent committing wrongly formatted code to avoid wasting CI time

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3277]
It happens often that I push some code which then fails in PR due to linting/formatting issues.

Wouldn't be helpful to prevent that with client-side checks to avoid wasting CI time?

For example we could add linting and formatting as pre-push hook, or even as build phase now that we are defining the project using Tuist

**Comment by fortmarek** [comment]
This is already bundled with fourier - you can just run `./fourier up` to set up the hooks 🙂 

However, I like the idea of adding it as a build phase, so I'll leave this issue open as that's something we can and probably should do.

**Comment by apps4everyone** [comment]
`./fourier up` hook is not working with `sourcetree`

**Comment by fortmarek** [comment]
I think it's out of purview to handle integrations with git GUIs (there's a bunch out there!). However, if you want to fix this, feel free to do so 💯

**Comment by danyf90** [comment]
I think having it configured in `./fourier up` is enough, closing it 🚀
