### ISSUE TITLE
Tuist embed doesn't code sign frameworks

### ISSUE THREAD

**Issue by Rag0n** [tuist/tuist#328]
I'm using prebuild frameworks and everything works fine on simulator, but when installing app on device there is an error ["App installation failed. No code signature found"](https://stackoverflow.com/questions/38371044/ios-app-testing-app-installation-failed-no-code-signature-found).

I have made a xcarchive and verified frameworks:
```
xcrun codesign --verify --verbose Alamofire.framework/
Alamofire.framework/: code object is not signed at all
In architecture: armv7
```

**Describe the bug**
tuist embed doesn't code sign frameworks.

**To Reproduce**
```
let project = Project(name: "Feature",
                      targets: [
                        Target(name: "FeatureFramework",
                               platform: .iOS,
                               product: .framework,
                               bundleId: "feature",
                               infoPlist: "Info.plist",
                               sources: "Sources/**/*",
                               resources: ["Sources/**/*.storyboard", "Sources/**/*.xib"],
                               dependencies: [
                                   .framework(path: "../../Prebuild/Alamofire/Alamofire.framework")
                               ]),
                       Target(name: "FeatureExample",
                               platform: .iOS,
                               product: .app,
                               bundleId: "FeatureExample",
                               infoPlist: "Examples.plist",
                               sources: "Examples/Sources/**/*",
                               resources: "Examples/Resources/**/*",
                               dependencies: [
                                    .target(name: "FeatureFramework"),
                                ]),
                      ])
```

**Expected behavior**
Prebuild frameworks are code signed.

**Workaround**
Move frameworks from "Embed Precompiled Frameworks" to "Embed frameworks" phase.

**Comment by pepibumur** [comment]
Thanks for opening this issue @Rag0n. This is clearly a bug in the logic that copies the precompiled frameworks over into the product bundle. We'll look into it.

**Comment by dangthaison91** [comment]
@Rag0n @pepibumur  Follow Apple document, not every app need to enable Code Sign On Copy, only `iMessage` app require it.

https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-EMBED_IN_APP_SECTION

But when I manual embed Frameworks on Xcode, Code Sign On Copy always is set to checked. So IMHO, for generated xcodepro itj should checked always.

**Comment by ollieatkinson** [comment]
@pepibumur If I am correctly thinking about this, we would need to add a new function to this class which signs the framework before copying:

https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Embed/FrameworkEmbedder.swift#L66
