### ISSUE TITLE
[Dependencies.swift] Some Dependencies are not working or compiling

### ISSUE THREAD

**Issue by apps4everyone** [tuist/tuist#3286]
Errors on tuist generate:

R.swift.Library
`R.swift.Library` is not a valid configured external dependency
AppCenter
`AppCenter` is not a valid configured external dependency
JWTDecode.swift

Error on run TuistTest.xcworkspace target TuistTest:
CrashReporter -> some compile error

Example Project:
[TuistTest1.zip](https://github.com/tuist/tuist/files/6969047/TuistTest1.zip)

**Comment by danyf90** [comment]
For the `is not a valid configured external dependency` errors, you need to use the Swift Product name (e.g. [Rswift](https://github.com/mac-cain13/R.swift.Library/blob/3a64127e8113cc33179504dfadc91b361d55a0b1/Package.swift#L13)) in the Project.swift

**Comment by apps4everyone** [comment]
ok, thx now I get this error:
Compiling for iOS 12.4, but module 'SwiftSoup' has a minimum deployment target of iOS 14.5

**Comment by apps4everyone** [comment]
and those Xcode warnings:

<img width="579" alt="Screenshot 2021-08-11 at 16 30 41" src="https://user-images.githubusercontent.com/1915802/129048119-e99e4cd5-103f-436b-a1e4-ffd917d182e0.png">

**Comment by apps4everyone** [comment]
thx, now I have this error:
Multiple commands produce '.../KeychainAccess.build/Objects-normal/arm64/Keychain.o':
1) Target 'KeychainAccess' (project 'KeychainAccess') has compile command for Swift source files
2) Target 'KeychainAccess' (project 'KeychainAccess') has compile command for Swift source files

Because I have KeychainAccess it in my Dependency.swift but also another SPM (not possible to move this because if this issue: https://github.com/tuist/tuist/issues/3269) also import's the KeychainAccess.

**Comment by danyf90** [comment]
You are adding the same target twice, so the problem is expected 👍 
i'll try to reply on the other issue

**Comment by apps4everyone** [comment]
but it's still an issue if user want's to mix Package + Dependencies.swift not? Or is it possible to add local SPM to Dependencies.swift?

**Comment by fortmarek** [comment]
> it's still an issue if user want's to mix Package + Dependencies.swift not

I don't think this a scenario we want to optimize for. You either use what Apple provides or use what tuist provides. Using both brings unnecessary complexity.

> Or is it possible to add local SPM to Dependencies.swift?

Yes, you can just use `.package(path: Path)` initializer for the package.

**Comment by apps4everyone** [comment]
looks like the infos are ignored:
exclude: [
    “./Resources/Info.plist”
],
resources: [
    .process(“./Resources”)
]

also here in this package are some compiler errors:
https://github.com/microsoft/plcrashreporter/blob/master/Package.swift

**Comment by apps4everyone** [comment]
here is an example of the exclude:

// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SomeSDK",
    defaultLocalization: "en",
    platforms: [.iOS(.v12)],
    products: [
        .library(
            name: "SomeSDK",
            targets: ["SomeSDK"])
    ],
    dependencies: [
        // Keychain access
        .package(url: "https://github.com/kishikawakatsumi/KeychainAccess.git", from: "4.2.1"),
        // SwCrypt
        .package(url: "https://github.com/soyersoyer/SwCrypt.git", from: "5.1.3")
    ],
    targets: [
        .target(
            name: "SomeSDK",
            dependencies: [
                "SwCrypt",
                "KeychainAccess"
            ],
            path: "Sources/SomeSDK",
            exclude: [
                "./Resources/Info.plist"
            ],
            resources: [
                .process("./Resources")
            ]
        ),
        .testTarget(
            name: "SomeSDKTests",
            dependencies: ["SomeSDK"],
            path: "Tests/SomeSDKTests",
            exclude: [
                "./Resources/Info.plist"
            ],
            resources: [
                .process("./Resources")
            ]
        )
    ]
)

**Comment by danyf90** [comment]
If the exclude also apply to resources, I think in order to solve this we should solve [this other issue](https://github.com/tuist/tuist/issues/3192) first
