### ISSUE TITLE
Performance metrics - time the generation process

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#329]
## Proposal 

Tuist enables the modularisation of large projects to several smaller Xcode projects through its powerful project generation features. It would be great to keep an eye on how long the generation process takes for both users and developers of Tuist.

For users, as they add more dependencies it's great feedback on the impact of their changes and equally for developers of Tuist as changes are made or new features are added having a benchmark would be helpful to also see the impact of those changes.

## Details

- To start out simple, we could just display the total time taken to generate the project (like Sorcery does)

```
$ tuist generate
Generating workspace Workspace.xcworkspace
Generating project Framework1
Generating project MainApp
Generating project Framework2
✅ Success: Project generated
Total time taken: 0.771s
```

- A follow up could be to add a performance test where we have a large-ish project (either as a fixture or one we dynamically generate for the test)

## Alternatives

One can simply call the `time` command 

e.g.

```
$ time tuist generate
Generating workspace Workspace.xcworkspace
Generating project Framework2
Generating project MainApp
Generating project Framework1
✅ Success: Project generated.

real	0m0.771s
user	0m0.437s
sys	0m0.325s
```

**Comment by pepibumur** [comment]
I like this idea. I'm more inclined towards the first option. It doesn't add much noise to the logs and I think developers would find it valuable.
