### ISSUE TITLE
Generated project won't include .cc files but will include .cpp files

### ISSUE THREAD

**Issue by eytanbiala** [tuist/tuist#3290]
## Context 🕵️‍♀️

I'm just getting started with tuist. Our project has a mix of .m, .swift, .mm, .c, and .cc sources which I'm trying to add to one target.

## What 🌱

For some reason, the .cc files are not included in the project even though specified in the sources glob. Here is my target definition:

```
    Target(
      name: "Example",
      platform: .iOS,
      product: .app,
      bundleId: "com.example.app",
      infoPlist: "SupportingFiles/Info.plist",
      sources: [
        "Source/**/*.{c,cc,cpp,m,mm,swift,metal}",
      ],
      headers: Headers(
        private: [
          "Source/**/*.h",
        ]
      ),
```

However if I rename a .cc files to .cpp, then it does show up in the project.

I tried cloning the tuist repo itself and adding a .cc case to TargetTests.test_sources(), however that test passes. Same for ProjectFileElementsTests.test_targetFiles()

**Comment by kwridan** [comment]
Thanks for raising this @eytanbiala!

Support for `.cc` files has recently been added by @danyf90 in #3273 which should be part of version [1.48](https://github.com/tuist/tuist/blob/main/CHANGELOG.md#1480---packer)+, mind checking which Tuist version you running?

You can get the latest update via `tuist update`.

**Comment by eytanbiala** [comment]
Crazy! I installed tuist recently, I guess just before that release.

`tuist update` and it's all working now :)

**Comment by eytanbiala** [comment]
Thanks for the quick response!
