### ISSUE TITLE
`./fourier bundle tuist` fails

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3292]
I am trying to bundle tuist from [this branch](https://github.com/tuist/tuist/pull/3276) using the `./fourier bundle tuist` command but it fails with error:
```
error: Build input file cannot be found: '/Users/df/Developer/_Others/tuist/Sources/ProjectDescription/Lab.swift' (in target 'ProjectDescription' from project 'Tuist')
```

**Comment by apps4everyone** [comment]
you have to remove project and workspace file before

**Comment by fortmarek** [comment]
Yep, exactly as @apps4everyone says. It is due to the fact that we want to build the package with xcodebuild which prefers .xcodeproj instead of Package.swift. As a solution, we should add the removel of xcode project to the bundle command.

**Comment by danyf90** [comment]
Thanks, I think we should keep this open and add the removal of xcode project to the bundle command as Marek suggests 🙌
