### ISSUE TITLE
Manually adding `-ObjC` flag is required when linking some Objc libraries

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3294]
**Describe the bug**
When using some Objc libraries, for example importing Adjust from SPM using Dependencies.swift, the app crashes during startup unless the `-ObjC` is passed in the `OTHER_LDFLAGS` setting

**To Reproduce**

1. Add adjust to your SPM dependencies
2. Wire it to the app
3. When the app starts, it crashes with an `unrecognized selector sent to instance` error like the one reported [here](https://github.com/adjust/ios_sdk/issues/158)

**Expected behavior**
It would be nice to find a way to make Tuist add the flag when needed

**Comment by bojanstef** [comment]
> When using some Objc libraries, for example importing Adjust from SPM using Dependencies.swift, the app crashes during startup unless the -ObjC is passed in the OTHER_LDFLAGS setting

This is still happening for me.

**Comment by RobinFarmer** [comment]
I was able to get Tuist to add the flags with the `tuist generate` command with the following settings added to my target:

```
settings: .settings(
    base: [
         "OTHER_LDFLAGS": ["-lc++", "-Objc"]
    ]
)
```

**Comment by fortmarek** [comment]
This should no longer be needed. If you are still running into this, please, create a new issue with a reproducible sample 🙏
