### ISSUE TITLE
Setup.swift homebrew not working on M1

### ISSUE THREAD

**Issue by apps4everyone** [tuist/tuist#3299]
When running:

`let setup = Setup([
    .homebrew(packages: ["swiftlint", "carthage"])
])`

I get the error:

`Configuring Homebrew
Installing Homebrew package: swiftlint
/usr/bin/env brew install swiftlint
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
  arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
The '/usr/bin/env' command exited with error code 1`

Rosetta should be avoided on M1 as tuist is now running natively on M1.

**Comment by apps4everyone** [comment]
@pepibumur does this run on your M1?

**Comment by pepibumur** [comment]
Hey @apps4everyone. Based on the output, it seems we need to add the `arch -arm64` arguments when installing Homebrew formulas on M1s. Unfortunately, I can't prioritize this, but if you are interested in fixing it, I can give you some pointers to make that contribution happen.

**Comment by apps4everyone** [comment]
isn't it more like to change to `opt/homebrew/bin` ?

**Comment by apps4everyone** [comment]
all `/usr/bin/env` should be on M1 `opt/homebrew/bi`

**Comment by pepibumur** [comment]
The logic should be something along the lines of:
- If Homebrew is installed as x86 using Rosetta, then we should use the Rosetta path.
- If Homebrew is installed as arm64, then we should use the M1 path

**Comment by apps4everyone** [comment]
getting stuck with:
posix_spawn error: Permission denied (13)

**Comment by apps4everyone** [comment]
> getting stuck with:
> posix_spawn error: Permission denied (13)

@pepibumur any hint to continue with this blocking bug for M1 users? thx

**Comment by pepibumur** [comment]
Hey @apps4everyone the error that you provided lacks some context so I can't provide any guidance.
- When do you get that error?
- What leads to that error? What are you trying to run?
- What's the underlying command that causes the error?
- What happens if you run that command directly in your shell?

**Comment by apps4everyone** [comment]
hey @pepibumur thx for helping. Opened with my current work a PR, if you run there `tuist up` with:
let setup = Setup([ .homebrew(packages: ["swiftlint", "carthage"]) ])
I geht the error `posix_spawn error: Permission denied` (13) on installing `carthage`.

**Comment by pepibumur** [comment]
The `tuist up` is [going away](https://github.com/tuist/tuist/pull/3443) in Tuist 2.0 and therefore we are no longer providing support for the command here.
