### ISSUE TITLE
Linking a static framework within a Carthage Framework as a Resource

### ISSUE THREAD

**Issue by NoahKnudsen** [tuist/tuist#330]
**Describe the bug**
When adding a resource contained within a Carthage framework, we are getting the following error: 

```❌ Error: Trying to add a file at path /Users/noah/Repos/my-project/Carthage/Build/iOS/FirebaseFirestore.framework/gRPCCertificates.bundle to a build phase that hasn't been added to the project.```

This resource is a static framework that doesn't come with the other resources.

Heres the resources section from the `Project.swift`:
```
resources: [
                "Resources/*.{xib,png,jpg,storyboard,pdf}",
                "Sources/GoogleService-Info.plist",
                "../Carthage/Build/iOS/FirebaseFirestore.framework/gRPCCertificates.bundle",
            ],
```

We've currently worked around the error by creating a symbolic link to the framework and linking it like so:
```
resources: [
                "Resources/*.{xib,png,jpg,storyboard,pdf}",
                "Sources/GoogleService-Info.plist",
                "gRPCCertificates.bundle", <- Symbolic link into the Carthage framework
            ],
```

**Desktop (please complete the following information):**

- OS: macOS 10.13.6
- Tuist Version 0.13.0

**Comment by kwridan** [comment]
I believe this is caused by #322
