### ISSUE TITLE
[Clean] Add `tuist clean` parmeter to exclude caches

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3311]
Due to [this problem](https://github.com/tuist/tuist/issues/2916) we sometime need to manually perform `tuist clean` to be able to properly generate our Xcode project.

When doing so, we would like to avoid to also clean the `tuist cache warm` cache.

What do you think of enhancing the `tuist clean` command to add a parameter to exclude part of the cache from the clean. For example:
```
tuist clean --exclude BuildCache
```

**Comment by fortmarek** [comment]
As Pedro mentioned in the `generate project caching`, this could quickly become a "trap of optimizing towards practices that are not recommended". I'm in favor of closing this issue and rather fixing the underlying problems with the hashing functionality. What do you think @danyf90?

**Comment by danyf90** [comment]
Good to me, as long as we solve the other problem 🙌
