### ISSUE TITLE
[Dependencies.swift] Project generation fails with disableBundleAccessors option

### ISSUE THREAD

**Issue by dtorres** [tuist/tuist#3313]
**Describe the bug**
Project generation fails with disableBundleAccessors option

**To Reproduce**

- clone https://github.com/dtorres/tuist-fail-spm-deps
- fetch dependencies
- try to generate project

**Expected behavior**

Project is successfully generated

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**

**Comment by danyf90** [comment]
@pepibumur @fortmarek @laxmorek 
Right now the Package to Project mapping defaults to staticFramework if the type is not defined in the Package.swift file.
What do you think of changing the logic to default to dynamicFramework if the target contains resources?

**Comment by dtorres** [comment]
Ohhh! That may explain why when I was testing this feature my build times grew 2x (from 8 mins to 20).

Thanks for the hint @danyf90. 
I agree with that conditional default

**Comment by fortmarek** [comment]
>  What do you think of changing the logic to default to dynamicFramework if the target contains resources?

That's fine by me - we should also look into fully supporting the `.automatic` option and choose the optimal default for other cases as well.

**Comment by danyf90** [comment]
Yes, for that we already have [this issue](https://github.com/tuist/tuist/issues/3112), but it's a broader change as we should probably need some generation time checks to handle it (the type might depend on which targets depend on it).

**Comment by danyf90** [comment]
@dtorres do you want to try to implement this change? should not be hard, all the logic should be in the `PackageInfoMapper.swift` file.

Also, as a temporary workaround you can override the "computed" product type in the `Dependencies.swift` file: https://docs.tuist.io/manifests/dependencies#swiftpackagemanagerdependencies

**Comment by pepibumur** [comment]
What'd be the criteria for deciding whether something should be dynamic or static? Whether it contains resources or not? What happens in the scenario where we have a static package target with resources and the `. disableBundleAccessors` is not passed? Does it work with our synthesized accessors?

**Comment by danyf90** [comment]
I think in that case linting will pass, but compilation probably won't work anyway, because the package would not use the synthesizer accessor, right?

That's another reason to use a dynamic framework in that case.

**Comment by fortmarek** [comment]
> do not consider the disableBundleAccessors for the SPM generation part (closer to the SPM logic)

Yes, we don't need to let users customize everything if we find it makes it harder to reason about. I'm in favor of this 👍

**Comment by danyf90** [comment]
Fixed in 3.0
