### ISSUE TITLE
Specify ordering for all generated array-like structures

### ISSUE THREAD

**Issue by nugmanoff** [tuist/tuist#3324]
## Context 🕵️‍♀️

I have a workspace with multiple projects in it and I was looking for a way to apply some custom order to the array of projects inside workspace + and I was earlier looking for such a feature to apply order to file groups inside project itself.

## What 🌱

Currently both [projects](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/WorkspaceDescriptorGenerator.swift#L90) inside workspace and file groups inside project gets sorted alphabetically or by [filesBeforeGroupSort](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Extensions/Xcodeproj+Extras.swift#L15) (like a relevant option in Xcode → Sort By option)

## Proposal 🎉

Provide option to specify for ordering for all sequential structures. Similar to [groupOrdering](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#groupOrdering) in XcodeGen

These may include:
- Projects inside workspace
- File groups inside project (in the root)
- File groups inside file groups (nested)
- Schemes list

Create some generic ordering mechanism that can be applied to any sequence/array, and let user provide relevant options.
I am new to Tuist codebase, I surfed it for a few minutes, and I think it could easily be done, e.g. for Workspace it can be applied as the [last mapper in sequence](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/GraphMappers/WorkspaceMapperProvider.swift) or maybe even [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/WorkspaceDescriptorGenerator.swift#L90), similar thing exists for [schemes](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift#L74)

**Comment by fortmarek** [comment]
Hey @nugmanoff!

I think this is an interesting idea, but I'm hesitant about adding this a new option as I'm not sure if it brings enough value to justify for adding to our core.

This would be really easy to do if we had custom project mappers. That is, however, a complicated feature but one we should try to explore at some point.

The idea is that you could define something like:

```swift
let project = Project(mappers: [MyMapper()])

struct MyMapper: ProjectMapping {
   func map(_ project: Project) -> Project {
     // Reorder files in the way you desire
    // Return a project with files reordered
  }
}

```

This would untap a whole set of customizability without bloating our core product.

**Comment by moritzsternemann** [comment]
I think this issue is related to a problem we are currently facing in our Tuist-generated project:

The list of targets in the _New File_ prompt and in the _Target Membership_ inspector are not in alphabetical order. This makes it almost impossible to find the correct target in Xcode when adding a new file to a project with many targets. I found [this StackOverflow post](https://stackoverflow.com/questions/22489666/can-i-sort-the-schemes-and-targets-list-alphabetically-in-xcode) which talks about a similar issue and a possible solution.

From @nugmanoff's post, I see the code that sorts projects, file groups, files alphabetically. Is it possible to do something similar for targets easily?

**Comment by fortmarek** [comment]
> Is it possible to do something similar for targets easily?

Yeah, I think so. The final order should be based on the order we generate targets. If we order targets alphabetically _before_ generating them, you should see them sorted in Xcode, too.

**Comment by danyf90** [comment]
Closing as per the discussion [here](https://github.com/tuist/tuist/pull/4707)
