### ISSUE TITLE
Documentation: Missing Schemes in Get Started Contributing

### ISSUE THREAD

**Issue by hisaac** [tuist/tuist#3325]
## Context 🕵️‍♀️

I'm trying to run Tuist locally to debug something, but the instructions in the "Get Started" page on how to contribute seem inaccurate.

## What 🌱

On the "Get Started" page, in the final section titled [Run Tuist From Xcode](https://docs.tuist.io/contributors/get-started/#run-tuist-from-xcode), it provides [two steps to get Tuist pointed at your project](https://github.com/tuist/tuist/blob/4e18afb2aa55806a364e66030cd011b7bb48718b/projects/docs/docs/contributors/get-started.md#L71-L72):

> - Build the `ProjectDescription` and `ProjectAutomtation` schemes first
> - Edit the `tuist` scheme

The issue is, when I open the project in Xcode, I don't see a `ProjectAutomation` scheme, or a `tuist` scheme, so I can't follow the instructions.

These are the schemes I see in Xcode:

<img width="287" alt="Screen Shot 2021-08-22 at 11 13 00 PM" src="https://user-images.githubusercontent.com/923876/130389163-8ed1af84-7e5d-4c17-a7ab-5f44ba2202d4.png">

Am I doing something wrong, or does the documentation need to be updated?

**Comment by fortmarek** [comment]
Hey @hisaac!

I agree it should be clarified this is only true for when you want to edit tuist with the package project, rather than generating the project with tuist and use the generated workspace.

Generally, `Run Tuist from Xcode` is only applicable if you don't edit tuist with tuist (we'd like to deprecate this option at some point).

I'll keep this issue open until we clarify this in the documentation, thanks!

**Comment by hisaac** [comment]
Ah, I see now. So if I open the `Package.swift` file instead of generating and opening the `Tuist.xcworkspace` file, then I see the `tuist` scheme, and can debug as expected. Thanks!

**Comment by fortmarek** [comment]
> Ah, I see now. So if I open the Package.swift file instead of generating and opening the Tuist.xcworkspace file, then I see the tuist scheme, and can debug as expected. Thanks!

You should also be able to see tuist scheme when opening `Tuist.xcworkspace`. This is the preferred way of doing things as it helps us uncover issues earlier when we edit tuist with tuist. However, using `Package.swift` is also fine if you prefer it.

**Comment by hisaac** [comment]
NOW I see what's going on, I was using a very outdated branch of the project, not the most recent `main`.

Sorry, this was just a mistake on my part. Things are working as expected now that I've got the most recent code.

🤦‍♂️
