### ISSUE TITLE
There is no possibility to add non system framework dependency optionally

### ISSUE THREAD

**Issue by OlgaMatsyk** [tuist/tuist#3329]
**Describe the bug**
We have an integration task with SDK that requires iOS 13+ , our app deployment target is iOS 11, so I’m curious if we can integrate SDK optionally, so we can still support older iOS versions with some alert to users that new feature is not available with their current iOS version but they can still use older iOS versions if they want.
Currently, there is no possibility to add non system framework dependency optionally as for example in tuist there is possibility to add system SDK with `reqired` or `optional` status.

**To Reproduce**

1. Add SDK dependency  `.framework(path: “path-to-framework/Framework.framework”) `
2. perform `tuist generate `
3. observe added SDK in 
<img width="604" alt="Screen Shot 2021-08-23 at 11 34 14" src="https://user-images.githubusercontent.com/25596260/130426885-0dbc8867-9c3d-458d-92f8-d2eb50a2354a.png">
4. SDK was added with required option.

**Expected behavior**
It would be great to have an option to add non system sdk optionally the same as it is implemented for system SDK's
`.framework(path: “path-to-framework/Framework.framework” status: .optional)
`
<img width="553" alt="Screen Shot 2021-08-23 at 11 34 46" src="https://user-images.githubusercontent.com/25596260/130427854-0847cbf3-ec68-4bb5-91fe-e4ed928d4f4a.png">

**Comment by kwridan** [comment]
Thanks for raising this @OlgaMatsyk 

Adding this new option should be do-able, I wonder if there's more configuration needed to support the use case you presented in addition to this extra option. Does manually tweaking that option achieve the desired results when running the app on a device with an OS < iOS 13?

**Comment by OlgaMatsyk** [comment]
@danyf90 I've tried this approach and the thing is that I'm still getting error
<img width="967" alt="Screen Shot 2021-08-25 at 18 47 42" src="https://user-images.githubusercontent.com/25596260/130823492-26ebc456-b13e-4a71-afef-528c454b7087.png">

**Comment by danyf90** [comment]
Just guessing, maybe with `if #available(ios 13.0 *)`?

**Comment by OlgaMatsyk** [comment]
@danyf90 with` if #available(ios 13.0 *)?` I can not import module, as 'if' can not be used while import, so it will not compile

**Comment by fortmarek** [comment]
I think you cannot conditionally import a framework based on iOS version if the minimum target of that framework is higher than yours. 

> I'll try to discuss this with framework creators maybe adding @available attribute to annotate API with availability information.

This might be the best option going forward.

I still wonder, though, if there is a valid case to weakly import a third-party framework. Can't think of any right now.

**Comment by OlgaMatsyk** [comment]
@fortmarek Thank you for reply. Yes after some investigations I think the same. It was possible with Objective C (for example I've imported Dropbox SDK conditionally) but looks like there i￼s no way to do that using Swift. Thank you for investigations and quick reply:) I'll recommend increase deployment target for our project.

**Comment by fortmarek** [comment]
I'm closing this for now until a valid use-case for this feature comes up. Thanks for the issue @OlgaMatsyk, though!

**Comment by ffittschen** [comment]
Hi @fortmarek, can we reopen this issue please? There were a couple of valid reasons in [this Slack thread](https://tuistapp.slack.com/archives/C018QG7U7SN/p1636452751088200):
1. The dependency is a closed source 3rd party dependency and there might be missing architectures for a particular platform
2. The dependency should only be part of development builds

Especially the second approach is used by a variety of developer tools. Sometimes it is explicitly recommended, such as with [Reveal](https://support.revealapp.com/hc/en-us/articles/360022666651), other times it's just some tool that simply should not be part of release builds, such as [DBDebugToolkit](https://github.com/dbukowski/DBDebugToolkit), [Flex](https://github.com/FLEXTool/FLEX), or [Atlantis](https://github.com/ProxymanApp/atlantis).

**Comment by ffittschen** [comment]
As this was discussed on Slack again, I'll also post our workaround here for better visibility: We are using generation-time configuration to optionally add a dependency or not:

```swift
// Project.swift
let buildForRelease = Environment.buildForRelease.getBoolean(default: false)

static let networking: Target = {
    var targetDependencies: [TargetDependency] = [.external(name: "GRPC")]
    if !buildForRelease {
        targetDependencies.append(.external(name: "Atlantis"))
    }
    // ...
}()
```
