### ISSUE TITLE
[Dependencies.swift][Carthage] Cannot generate project with Carthage dependency

### ISSUE THREAD

**Issue by olejnjak** [tuist/tuist#3331]
**Describe the bug**
Looks like we have run to an issue when incorrect path is checked when generating project with Carthage dependency. 

I guess only bad path is checked when generating project.

**To Reproduce**

1. Use attached minified project
2. run `tuist dependencies fetch`
3. run `tuist generate`

```
olejnjak@Jakub-Macbook CarthageExample % tuist generate
Couldn't find xcframework at /Tuist/Dependencies/Carthage/Alamofire.xcframework
```

**Expected behavior**
Generation should be successful

**Desktop (please complete the following information):**

- OS: macOS
- Version: 11.5.2

**Additional context**
Project uses Alamofire dependency added via Carthage.

[CarthageExample.zip](https://github.com/tuist/tuist/files/7031638/CarthageExample.zip)

**Comment by danyf90** [comment]
It should be fixed in [this PR](https://github.com/tuist/tuist/pull/3300) (which has not been released yet)

**Comment by olejnjak** [comment]
Aaa good, will try on `main` and close this issue eventually 👍

**Comment by olejnjak** [comment]
Fixed 👍

**Comment by fortmarek** [comment]
Thanks for checking @olejnjak! I will create a new release later this week, so you don't have to rely on `main` due to this bug.

**Comment by zdnk** [comment]
How do I install main? It is currently blocking me :(

**Comment by maxkazakov** [comment]
I'm really waiting for release with this fix

**Comment by olejnjak** [comment]
https://github.com/tuist/tuist/releases/tag/1.49.0 or better https://github.com/tuist/tuist/releases/tag/1.49.2

**Comment by mihailkalichkov** [comment]
how can i install 1.49.2 version? The highest i can get with "tuist update" is 1.48.1

**Comment by danyf90** [comment]
@mihailkalichkov reinstall it using `bash <(curl -Ls https://install.tuist.io)`
