### ISSUE TITLE
Warnings generating a new project

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#334]
## Context 🕵️‍♀️
I just updated to the latest version and ran the following commands:
- `tuist init`
- `tuist focus`

**Expected**
Get the project generated without any warnings on the console

**Got**
![image](https://user-images.githubusercontent.com/663605/56869957-62b7b500-6a08-11e9-9240-f15b38e634b1.png)

**Comment by kwridan** [comment]
Ah this due to the changes I introduced for #318 where a warning is displayed if the glob patterns specified doesn't yield any files. It was perhaps too strict, we can remove it.

https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Generator/GeneratorModelLoader.swift#L112
