### ISSUE TITLE
Tuist install fails on a CI system, gets rate limited by GitHub.

### ISSUE THREAD

**Issue by michallaskowski** [tuist/tuist#3341]
**Describe the bug**
Recent change to use GitHub releases to fetch the binary causes issues on CI systems, which get rate limited. 
https://github.com/tuist/tuist/pull/3336/files#diff-14b680935f42f2ba5b32d6c65ac9daf4d6cd4c1f3f7434bfc9efc8ecf5f5e183

Debugged via ssh on a machine that get's the error:
`curl "https://api.github.com/repos/tuist/tuist/releases/latest"`
```
{"message":"API rate limit exceeded for 207.254.34.148. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

From GitHub docs:
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

**To Reproduce**
Make a lot of calls to GitHub API's from one machine, or use one of CI SaaS platforms. 

**Expected behavior**
Tuist version is fetched, Tuist is installed.

**Desktop**

- OS: macOS
- Version BigSur

**Comment by michallaskowski** [comment]
One possible fix, except reverting the changes, would be to remove a call to fetch latest version from API, and just use 
`https://github.com/tuist/tuist/releases/download/latest/tuistenv.zip` to download latest binaries. Not sure how it works with pre-releases, but I would assume it would work fine.

**Comment by fortmarek** [comment]
Thanks for flagging @michallaskowski!

We should fix this asap, indeed.

`https://github.com/tuist/tuist/releases/download/latest/tuistenv.zip` unfortunately returns `Not found`. I am not sure if it's possible to download latest artifacts without making an API call?

**Comment by michallaskowski** [comment]
You are right, this doesn't work, I haven't checked properly.

**Comment by fortmarek** [comment]
I've reverted the changes in the PR as temporary hot fix. Once I get some 👀 on it, I'll merge it.
