### ISSUE TITLE
Can't add `.xib` files as sources

### ISSUE THREAD

**Issue by nugmanoff** [tuist/tuist#3349]
Hey there! First of all, thanks for an amazing project!

## Context 🕵️‍♀️

I was trying to add my `xib` files that reside in `Sources/` folder along with `.swift` files as sources

## What 🌱

Glob patterns that I've used for sources:

- `"/Sources/**"`
- `"/Sources/**/*"`
- `"/Sources/**/*"`
- `"/Sources/**/*.{swift, xib}"`
- `"/Sources/**/*.xib"`

neither of them adds xib files

**Comment by nugmanoff** [comment]
**Upd:** 

I've stumbled upon this one #3290, and now I see that `.xib` file is not a valid source file extension, but I need to have it included in `Sources/` directory alongside with `.swift` files. What are the options? Can we add it valid source file extension list?

**Comment by kwridan** [comment]
Hi @nugmanoff

In Tuist and in Xcode, there's a distinction between source code files (sources) and resources which are mapped to the corresponding Xcode build phases. `xib` files are considered resources, for this you'll need to specify them in the `resources` section of your project manifest. 

Example:

```swift
Target(
// ...
  sources: [
     "Sources/**"
  ],
  resources: [
      "Sources/**/*.xib"
  ]
)
```

Here's a more complete fixture example:

https://github.com/tuist/tuist/blob/main/projects/tuist/fixtures/ios_app_with_framework_and_resources/App/Project.swift

Hope this helps!

**Comment by nugmanoff** [comment]
@kwridan thanks so much! It worked!
