### ISSUE TITLE
Plist values dosen't have support for floating value.

### ISSUE THREAD

**Issue by MarvinNazari** [tuist/tuist#3355]
There is Plist value called `Number`, which looks like this `<real>0.8</real>`. It supports even floating number, showing in the example. this is missing in Tuist, you can only use `.integer()` which is only Int.

Here is an example.

```swift
<dict>
	<key>UNNotificationExtensionCategory</key>
	<array>
		<string>product</string>
	</array>
	<key>UNNotificationExtensionDefaultContentHidden</key>
	<true/>
	<key>UNNotificationExtensionInitialContentSizeRatio</key>
	<real>0.8</real>
</dict>
```

<img width="955" alt="Screen Shot 2021-08-26 at 12 58 43" src="https://user-images.githubusercontent.com/926772/130951166-1d9686aa-035a-45a7-9db7-336b03bcf17c.png">

**Comment by fortmarek** [comment]
No, I don't think anything related to that is happening in [xcodeproj](https://github.com/tuist/XcodeProj/).
afaict, the plist is generated [here](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Mappers/GenerateInfoPlistProjectMapper.swift#L62), so all changes should be done imho only in the tuist repo.
