### ISSUE TITLE
zsh as default shell 

### ISSUE THREAD

**Issue by DarkoDamjanovic** [tuist/tuist#3358]
Currently `/bin/sh` is configured as default for script build phases. We would ask you to consider `/bin/zsh` as the future default or make it configurable. `/bin/zsh` is already default in macOS since Catalina. We experienced some problems on M1 machines and homebrew which doesn't setup all installed tools correctly to run with `/bin/sh`. 

Thanks for your attention.

**Comment by fortmarek** [comment]
> Isn't /bin/sh still the default when creating scripts from Xcode?

I agree with this. 

> In any case, I agree it might make sense to provide a way to allow to choose a different shell in cases which the default /bin/sh is not enough

Yeah, I think we should enable users to configure this. I'd probably add the following:

```swift
// add the following parameter to `TargetAction` and its initializers
shell: Shell

enum Shell {
   case zShell // /bin/zsh
   case bourneShell // /bin/sh
   case custom(String) 
```

We can also keep it simple (KISS 💋) and just add shell: String where default value would be `"/bin/sh"`.

**Comment by DarkoDamjanovic** [comment]
👍🏻

**Comment by danyf90** [comment]
I would go for a simple String, as the actual installation path might be different.

@DarkoDamjanovic do you want to try to implement this? 🚀

**Comment by DarkoDamjanovic** [comment]
Ok, will look into it.
