### ISSUE TITLE
Error logs during tuist generate libauthinstall.dylib

### ISSUE THREAD

**Issue by apps4everyone** [tuist/tuist#3372]
Error logs during tuist generate (tested 1.48.0 - 1.49.1 on M1)

Logs:

Resolving package dependencies using xcodebuild
objc[13969]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f356fad8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x117edc2c8). One of the two will be used. Which one is undefined.

objc[13969]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f356fb28) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x117edc318). One of the two will be used. Which one is undefined.

Project generated.

**Comment by junkpiano** [comment]
@apps4everyone Hi, can you tell how to fix this issue?

**Comment by apps4everyone** [comment]
Und fortunately I haven't fixed or closed this ticket.
