### ISSUE TITLE
.framework usage error (Couldn't find a reference for the file)

### ISSUE THREAD

**Issue by nilsnilsnils** [tuist/tuist#3389]
Generate error when using 
`.framework(path: "//.../Frameworks/CrashReporter.framework/"),`

I have read the documentation and I think that's all what I have to do.
[framework-dependencies](https://docs.tuist.io/guides/dependencies/#framework-dependencies)

Yes I checked the path twice and the verbose log also say that the path is correct and there is a framework.

Error message is:

```
Checking if /Users/...../Frameworks/CrashReporter.framework exists... true
xcode-select -p
/Applications/Xcode.app/Contents/Developer

Checking if /Applications/Xcode.app/Contents/Info.plist exists... true
Generating workspace tuist.xcworkspace
Generating project cttuist
/usr/bin/xcrun swift --version
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
Target: x86_64-apple-darwin20.6.0

Couldn't find a reference for the file at path /Users/..../Frameworks/CrashReporter.framework.
```

`.sdk, .library,  .xcframework, .package` is working only `.framework` isn't

If I use it via `.sdk` the error is gone, but I think that's not 100% correct and maybe there are errors later on device / release builds

tuist 1.49.2

Is this a bug in tuist or did I something wrong ?

**Comment by adellibovi** [comment]
Hi @nilsnilsnils, could you attach a demo project to reproduce the error? There is a double slash at the beginning, is that correct?

**Comment by danyf90** [comment]
Closing as stale
