### ISSUE TITLE
📦[Dependencies.swift] Provide an `outdated` subcommand for dependencies

### ISSUE THREAD

**Issue by mgray88** [tuist/tuist#3395]
## Context 🕵️‍♀️

Both cocoapods and carthage currently provide an `outdated` command to print out a list of outdated dependencies. SPM unfortunately doesn't seem to have something similar, however there are some tools created for that purpose:
https://github.com/kiliankoe/swift-outdated

## What 🌱

It would be great to have `outdated` added to `tuist dependencies` to be able to quickly see which dependencies need updating. I'm not sure what extra work would be required for an `update` command, but thought maybe that would be better as a separate proposal.

**Comment by danyf90** [comment]
Tuist leaves the dependencies files on the system, so such tools/command can be run directly on those files, without the need for a dedicated tuist command
