### ISSUE TITLE
Task `readLine` issue

### ISSUE THREAD

**Issue by DimaMishchenko** [tuist/tuist#3396]
**Describe the bug**
`readLine()` not works correctly in Tasks. 

**To Reproduce**
Add something like:
``` swift
let input = readLine()
```
In this case `readLine()` will return `nil` immediately.

**Expected behavior**
Task should wait for user input.

**Comment by DimaMishchenko** [comment]
Seems like issue still exists even after Plugin 2.0 and Tuist 3.x.

It's interesting that everything works fine if you run `swift run --configuration debug --package-path /path/to/plugin run-test-command`.
And return `nil` immediately if use `tuist plugin run`.

But it's good that now direct `swift run` call can be used as a workaround. 

probably need to cc @fortmarek 😄

**Comment by lordcodes** [comment]
This seems to relate to how the plugin task is executed using `Process`.
The Swift Process API doesn't seem to connect to standard input by default, which is a widely reported issue with running commands using it.
There seems to be a [workaround posted onto the Swift Forums](https://forums.swift.org/t/how-to-allow-process-to-receive-user-input-when-run-as-part-of-an-executable-e-g-to-enabled-sudo-commands/34357/4) to get Process to connect to standard input. 

```swift
// Create the process
let process = Process()

// Setup the process
process.launchPath = "/bin/sh"
process.arguments = ["-c", "sudo echo foo"]

// Create a pipe that connects to stdin of the new process
let pipe = Pipe()
process.standardInput = pipe

// Create a process that reads from STDIN and writes that read 
// data into the pipe
let fileHandle = FileHandle(fileDescriptor: STDIN_FILENO)
fileHandle.readabilityHandler = { handle in
    let data = handle.availableData
    if data.count > 0 {
       pipe.fileHandleForWriting.write(data)
    }
}

// Launch the process
process.launch()
```

TuistSupport/System/System.swift has a function runAndPrint which is used to run the task. The Process in there needs to be adapted to connect to standard input as above.

**Comment by fortmarek** [comment]
Tasks are no longer actively maintained. Thanks for your understanding!
