### ISSUE TITLE
RunAction with language

### ISSUE THREAD

**Issue by Johnny992** [tuist/tuist#3398]
Hello folks. 
I need example how to use param runAction with option "language" in Scheme.

After tuist generate - 
runAction: RunAction(executable: "XXX", options: RunActionOptions(language: SchemeLanguage(identifier: "pl"))) 

I get info: 
 type 'SchemeLanguage' does not conform to expected type 'Decoder'
            runAction: RunAction(executable: "XXX", options: RunActionOptions(language: SchemeLanguage(identifier: "pl")))

the same issue for: runAction: RunAction(executable: "XXX", options: RunActionOptions(language: "pl")) 
            
tuist version: - 1.48.1

**Comment by kwridan** [comment]
Hi @Johnny992 

Thanks for flagging this!

This seems to work for me locally 🤔

```swift
runAction: RunAction(
  executable: .project(path: "App", target: "App"),
  options: .options(language: "pl")
)
```
