### ISSUE TITLE
Fail to load stencils using {% extends %}

### ISSUE THREAD

**Issue by Craz1k0ek** [tuist/tuist#3406]
**Describe the bug**
When trying to leverage the `Stencil` or `StencilKit` functionality of extending stencils using `tuist scaffold`, you receive the error

```
We received an error that we couldn't handle:
    - Localized description: The operation couldn’t be completed. (Stencil.TemplateSyntaxError error 1.)
    - Error: Template named `Base.stencil` does not exist. No loaders found"
```

**To Reproduce**
I've attached a [minimal project](https://github.com/tuist/tuist/files/7115065/StencilBug.zip) to reproduce the issue. In the project I have created a framework scaffold that should use the stencils.

1. Unzip the source code
2. Run the command `tuist scaffold framework --name AnyName`
3. See the error

**Expected behavior**
I would like to be able to use the `{% extends %}` tag provided by `Stencil`. In addition, I'd like to have directories that contain `.stencil` files to be automatically added to the Manifest project when running `tuist edit`. Right now, the `Stencils` directory, as provided in the example, is not visible when opening the Manifest project.

**Desktop (please complete the following information):**

- OS: macOS 11.5.2
- Tuist: 1.46.1

**Comment by devyhan** [comment]
I think the `stencilSwiftEnvironment` is bridged with the stencil syntax parsing.

But `stencilSwiftEnvironment` in current Tuist doesn't inject `Loader` so it can't found inherited templates from `ExtendsNode` in `StencilSwiftKit`.

And I found to [this PR](https://github.com/SwiftGen/StencilSwiftKit/pull/154) in `StencilSwiftKit` and found that {% extends %} was working good after updating the dependency version and injected `Loader`.

I'll post a PR on this issue soon.

**Comment by devyhan** [comment]
@Craz1k0ek 
The issue where the Stencils directory doesn't appear is split into that [issue](https://github.com/tuist/tuist/issues/4845) as per @danif09's comment. 🙏
