### ISSUE TITLE
Looks like Product Folder missing in generarted Xcode project

### ISSUE THREAD

**Issue by pavm035** [tuist/tuist#3414]
Looks like Products folder missing after generated Xcode Project, any ideas?

<img width="360" alt="Screen Shot 2021-09-07 at 22 09 14" src="https://user-images.githubusercontent.com/6092412/132354748-78d16988-4c21-4b63-9de4-abe1305deadb.png">

**Comment by fortmarek** [comment]
Hi @pavm035, could you please fill out the bug report template, so we can help you further? You can find it [here](https://github.com/tuist/tuist/issues/new?assignees=&labels=&template=Bug_report.md)

A reproducible sample/set of steps would be helpful here.

Thanks!

**Comment by pavm035** [comment]
@fortmarek  sorry about that and here is the template

**Products folder missing**
When you generate sample project using Tuist Product folder missing from the generated project

**To Reproduce**
1. Create sample App with Tuist
2. Generate Project using `tuist generate -P`

**Expected behavior**
It should generate Product folder like regular Xcode project

**Screenshots**


**Desktop (please complete the following information):**

- OS: macOS
- Version 11.4

Sample projet attached here
[MyApp.zip](https://github.com/tuist/tuist/files/7122215/MyApp.zip)

**Comment by pavm035** [comment]
Sorry nvm i think it's Xcode13 feature, it's moved under Product -> Show Build Folder In Finder

Excerpt
https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes

**Project Navigator
New Features**
`The project navigator hides the Products group when it’s in the default location. The Product > Show Build Folder in Finder menu item replaces the most common use. (71561549)`
