### ISSUE TITLE
Unable to link Intent.intentDefinition file to multiple targets

### ISSUE THREAD

**Issue by pavm035** [tuist/tuist#3424]
Unable to link intent file to multiple targets and also not sure how to generate intent classes only to particulart target?

Create sample app with intents extension

**Expected behavior**
Should be able to add intent file to multiple target and generate class only to specific target(framework)

<img width="1788" alt="Screen Shot 2021-09-09 at 16 55 56" src="https://user-images.githubusercontent.com/6092412/132677503-9e18fbe6-050d-447c-af60-8c8ffcf7643d.png">

**Comment by kwridan** [comment]
Hi @pavm035 

I believe linking the intent definition file to multiple targets should be possible when adding it to the target `sources`:

e.g.

```swift
Project(
    name: "MyProject",
    targets: [
        Target(
            name: "App",
            // ...
            sources: [
                "App/**",
                "Intents/MyIntents.intentdefinition"
            ]
        ),
        Target(
            name: "MyIntentsExtension",
            // ...
            sources: [
                "IntentsExtension/**",
                "Intents/MyIntents.intentdefinition"
            ]
        )
    ]
)
```

There's an open issue regarding the second part of your question https://github.com/tuist/tuist/issues/3227 regarding how to set the appropriate attributes. Sadly we haven't had a chance to address it yet, if it's something you're interested in contributing happy to guide you through it. I may be able to take a stab it in the coming weeks as it happens I've recently been experimenting with intents in a side project.

**Comment by pavm035** [comment]
Hi Thanks @kwridan for quick reply, i had some bug in project file now i can link into multiple targets, but as you mentioned in other issues setting attributes is limitation, since i'm new to this tool and not sure how soon i can contribute or get started with lib

**Comment by kwridan** [comment]
no worries 👍 

will close this issue - we can track the remaining attributes issue in https://github.com/tuist/tuist/issues/3227
