### ISSUE TITLE
Dependency on existing xcodeproj

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#343]
**Is your feature request related to a problem? Please describe.**
Currently we have a project containing several targets compiling static library using google j2objc tool, custom sqlite build and our shared core between multiple apps in C++.
I wasn't able to figure out how to add dependency on this existing project and its targets using Tuist.

**Describe the solution you'd like**
Ability to add dependency on existing target in existing xcodeproj file,.

**Comment by kwridan** [comment]
Hi @zdnk, 

Thanks for raising this. I find this quite interesting, as we've experimented with this concept (at work) to allow depending on projects that weren't generated with Tuist yet as a temporary measure while working on generating those dependencies too. 

The biggest caveat we found with this approach was when the project being referenced had its own dependency tree, the generated workspace would be incomplete and would fail to build. To work around this, we had to use a custom workspace that included all projects.

I'm curious about your use case if you don't mind sharing some more information, are there any limitations that prevent writing a manifest file for those projects to get Tuist to generate them too?

In the interim you can try out defining a custom [workspace manifest](https://github.com/tuist/tuist/blob/master/docs/usage/2-manifest.md#workspaceswift) where you include all the projects you're interested in referencing as `additionalFiles`:

e.g. 

```swift
import ProjectDescription

let workspace = Workspace(name: "CustomWorkspace",
                          projects: [
                            "MyTuistGeneratedProject",
                          ],
                          additionalFiles: [
                            "ExistingProject.xcodeproj",
                          ])
```

**Comment by zdnk** [comment]
Well we are using j2objc tool for for some core written in Java, then we have C++ project, custom build of sqlite etc. They are configured in certain way and I right now we are not touching them so much so I would really like just simply reuse them.

Besides I was fighting with adding `.java` files using Tuist and actually having trouble setting up headers in C++ project.

**Comment by zdnk** [comment]
Also, we are using Build Rules to process the Java files.

**Comment by kwridan** [comment]
Thanks for sharing - I have a better picture of the scenario, quite an intricate setup by the sounds of it. 

I personally see the value of such a dependency type for these scenarios and even for the incremental adoption scenarios. The challenge is supporting such a feature reliably somehow as there are quite a few edge cases 😕

Did adding the project to the workspace via `additionalFiles` help at all? I guess the missing thing there is linking in the product of that project.

**Comment by zdnk** [comment]
I did not try it yet, as I said I am a little afraid of what it will do with CocoaPods together.
Anyway, yes, there still will be linking issues, every time, the developer needs to link the products from the project to the generated one.

**Comment by zdnk** [comment]
Another issue: Linking framework with `FRAMEWORK_SEARCH_PATHS` is not possible. Tuist checks the paths during generation without looking at `FRAMEWORK_SEARCH_PATHS`

**Comment by dcvz** [comment]
I’m also looking to do something similar. Basically include an already existing `.xcodeproj`.

In my case the `.xcodeproj` is simple and only generates a static lib which I’d then need to link.

Has there been any developments in adding an existing `.xcodeproj` and the library it generates as a dependency? Or any workaround?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pepibumur** [comment]
> Has there been any developments in adding an existing .xcodeproj and the library it generates as a dependency? Or any workaround?

There hasn't. I'm not 100% sure of this being a good idea because we'd be merging existing targets into the Tuist's dependency graph, on which we run a lot of validations to make sure that things are properly configured. By introducing those elements that are slightly out of our control, users might face compilation issues and therefore think that it's something that Tuist should know how to handle.

You can workaround this by adding the project to the workspace, which is currently possible, and link that static framework using build settings flags. The latest version of Xcode is able to infer the implicit dependencies and compile your project's target first, and then do the linking. That should work.

**Comment by dcvz** [comment]
Thanks for the answer @pepibumur :)

I've only spent an hour or so working with `tuist` and yeah I can see that it doesn't really fit the philosophy of what ya'll are trying to build.

Thanks for the workaround! I'll give it a try (in the end I'm actually fighting a problem with cocoapods).

Side note: I saw that one of the goals was to support `ReactNative` -- I've successfully setup a RN project already 👍 It's much easier now that RN has moved to using cocoapods by default.

**Comment by dcvz** [comment]
For others who may also need to do some of this dark magic:

1. I defined a custom workspace and included the `xcodeproj` as mentioned in https://github.com/tuist/tuist/issues/343#issuecomment-491075305
2. Linked the resulting static lib via flags: `"OTHER_LDFLAGS": "$(inherited) -lStaticLib",`

**Comment by dcvz** [comment]
@pepibumur & @kwridan I think it's been answered that this deliberately not supported and probably won't be. Does it make sense to close this issue?

**Comment by pepibumur** [comment]
Thanks for sharing the steps that you followed for the shake of visibility. 

> @pepibumur & @kwridan I think it's been answered that this is deliberately not supported and probably won't be. Does it make sense to close this issue?

Agree. Closing it :)
