### ISSUE TITLE
Support Reverse-Domain-Name Style Named SPM Dependencies

### ISSUE THREAD

**Issue by moritzsternemann** [tuist/tuist#3432]
**Describe the bug**
I have a Project with an SPM dependency that is named in reverse-domain-name style and has a target with the same name (`com.example.proto-types-swift-stubs`). When importing the package as a dependency through `Dependencies.swift`, building the generated project fails because the product of the dependency can't be found.

**To Reproduce**

1. Use the attached minimal example zip. Navigate to the *tuist-dependency-test* directory
2. Run `tuist dependencies fetch`
3. Run `tuist generate`
4. Open the generated workspace
5. Build the main *TuistDependencyTest* target
6. Observe that the imported module `com_example_proto_types_swift_stubs` in `AppDelegate.swift` can not be found (funnily autocomplete in Xcode works fine)

During step 3, Tuist prints a warning that product name of the dependency contains invalid characters, namely the `.`.
I found that the linting code, that produces the warning, was introduced here: https://github.com/tuist/tuist/pull/435#discussion_r300593432, but couldn't figure out the reasoning for why products with a dot in the name are not supported.
To simplify the setup, I included the dependency as a local Swift package. The same issue can be observed when using a remote package as well.

For reference I included a sample Xcode project which imports the identical SPM package dependency using Xcode's built-in SPM dependency management. This project builds successfully. You can find this project in the *spm-dependency-test* directory in the attached zip file.

[tuist-dependency-test.zip](https://github.com/tuist/tuist/files/7144496/tuist-dependency-test.zip)

**Expected behavior**
I expect Tuist handled SPM dependencies and generated projects to support all packages that Xcode's built-in package management system supports.

**Desktop:**

- OS: macOS 11.5.2 / macOS 12 Developer Beta 6, Xcode 12.5.1
- Tuist Version: 1.49.2

**Comment by danyf90** [comment]
Hey @moritzsternemann,
Thanks for the sample project, I can confirm I can reproduce the reported issue.
The problem is that we are not handling special characters (e.g. `.` and `-`) correctly, which leads to a wrong target name.

To fix this, we should just need to change the `PackageInfoMapper` to "sanitize" the names we read from the `Package.swift` mapping `.` and `-` (do you know if there are any other special characters?) to `_`.

If you want to try to fix this and the information above is not enough, i am happy to provide any other info you might need 🙌

**Comment by moritzsternemann** [comment]
I think `.` and `-` are probably the most common special characters that appear in project and target names. Maybe unsupported characters like `/`, `~`, `(`, `{` and so on should be sanitized as well but I don't think they see much use in this case anyway.

Thanks for the pointers, I'll try to fix it today and will reach out again if I have any questions 🙃
