### ISSUE TITLE
Xcode project missing build setting

### ISSUE THREAD

**Issue by flowbe** [tuist/tuist#3442]
**Describe the bug**
Xcode shows a warning asking me to update the project to recommended settings. When I click, it wants to turn on "Missing Localizability" because my project is localized for multiple languages.

**To Reproduce**

1. Create a Tuist project
2. Add localization
3. `tuist generate`
4. Open the project in Xcode
5. Observe the warning

**Expected behavior**
There should be no warning for the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/8288625/133078177-9009d4b9-5d53-423d-b4b7-9682335c3f81.png)

![image](https://user-images.githubusercontent.com/8288625/133077747-f1c13e5f-716f-4f84-8e99-bf5148e6615d.png)

**Desktop (please complete the following information):**

- OS: macOS 11.5.2
- Version 1.48.1
- Xcode 13.0 beta 5

**Comment by flowbe** [comment]
Hi @fortmarek, I just created the [PR](https://github.com/tuist/XcodeProj/pull/641). Let me know if I need to change anything

**Comment by pepibumur** [comment]
@flowbe you'll have to now update the dependency on the Tuist side. After doing that, feel free to close this issue.

**Comment by flowbe** [comment]
Hi @pepibumur,
Thanks for the info. My PR was merged but they didn't create a new release yet. Am I supposed to do it?

**Comment by pepibumur** [comment]
>  Thanks for the info. My PR was merged but they didn't create a new release yet. Am I supposed to do it?

No. Releases follow a fixed schedule so if your PR was already merged, your fix will go in the next release of Tuist.
