### ISSUE TITLE
Unable to build with Xcode13 RC

### ISSUE THREAD

**Issue by pavm035** [tuist/tuist#3454]
Looks like there are some build errors with Xcode13 RC as mentioned one of the example here
https://github.com/kylef/PathKit/issues/77

**Comment by fortmarek** [comment]
Thanks for raising this - is PathKit the only issue? If so, we should wait for them to fix it or do that work ourselves.

**Comment by pavm035** [comment]
I think there are some other issue like in xcodeproj but all of them from SPM/dependencies

**Comment by shakedHouzz** [comment]
The generate command also is not working with Xcode 13.
Getting the error:
The 'swiftc' command exited with error code 1 and message:
error: link command failed with exit code 1 (use -v to see invocation)
ld: framework not found ProjectDescription

**Comment by Xopoko** [comment]
@shakedHouzz I have the same. After upgrading to Xcode 13, the generate command doesn't work and throws an error.

**Comment by fortmarek** [comment]
We will try to make a new release today to remedy this.
