### ISSUE TITLE
🌎 [Remote cache] Missing authentication token in exists call not detected when it causes a redirect

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3476]
**Describe the bug**
Some authentication mechanisms (e.g. [Google IAP](https://cloud.google.com/iap)), redirect to a login page in case the authentication token is not present.

With the current logic, the `CacheRemoteStorage.exists` method returns true, because the cloud client follows the redirect, and the login page returns 200, which is considered as acknowledge that the remote cache exists.

We should find a way to avoid that, some possible options:
- disable redirects in the URLSession we use for the cache -> do you think anyone needs this to be enabled?
- detect the redirection from the response (for example, the response.mimeType is `text/html` instead of `text/json` in this case)

**Comment by fortmarek** [comment]
> disable redirects in the URLSession we use for the cache -> do you think anyone needs this to be enable?

I'm leaning to this option. I wouldn't make assumptions and only apply it to the current specific case we are dealing with. I'm not aware of better options here.

**Comment by pepibumur** [comment]
> disable redirects in the URLSession we use for the cache -> do you think anyone needs this to be enabled?

It sounds reasonable. I'd advise though against authenticating through Google IAP when hitting those endpoints. Use Google to authenticate a user through a `tuist cloud login` command, and store a token that you can use to authenticate `exist` and `fetch` requests.

**Comment by danyf90** [comment]
@pepibumur that's more or less what we are doing. The problem we have is that if a user lauches a `tuist cache warm` without logging in before, the `exists` method returns true for the remote cache.

**Comment by danyf90** [comment]
[Implemented here](https://github.com/tuist/tuist/pull/3480) ✅
