### ISSUE TITLE
Why tuist is generating duplicated schemes for App

### ISSUE THREAD

**Issue by rafagan** [tuist/tuist#3483]
Tuist is generating two schemes for `.app` products: ${PROJECT_NAME} and ${PROJECT_NAME}-Project. 

Why this is happening?

**Comment by fortmarek** [comment]
Hi @rafagan!

`${PROJECT_NAME}` is a convenience scheme that will include _all_ tests and buildable targets - even if they directly don't depend on the app target.

This is useful for a) running all tests present in the project b) making sure everything in the whole project is buildable at all times.

However, I agree it might feel confusing if you don't have many targets, yet.

Does this answer your question?

**Comment by rafagan** [comment]
Hum, ok. Another one. I need to configure a Scheme that sets the RunAction executable to `Ask on Launch` and `Expand Variables Based On` equals to a Target different from the Scheme target. How can I achieve that

**Comment by fortmarek** [comment]
Hey, could you please post your question [here](https://github.com/tuist/tuist/discussions/categories/q-a)? Github issues are mostly for tracking bugs/features and not questions. Thanks!
