### ISSUE TITLE
Tuist does not generate a WorkspaceSettings.xcsettings file

### ISSUE THREAD

**Issue by Unknoob** [tuist/tuist#3487]
**Describe the bug**
XCode uses the `WorkspaceSettings.xcsettings` file inside the Workspace to know whether it should generate schemes automatically for every target or not. When we open `XCode -> Manage Schemes` and toggle the `Autogenerate schemes` option, it saves the setting on this file.

Here's an example of the file created by xcode upon toggling `Autogenerate schemes`. It is located in `Workspace.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded</key>
	<false/>
</dict>
</plist>
```

Tuist currently does not generate this file, so for example, when using the `.disableAutogeneratedSchemes` in our `Config.swift` file, Tuist does not automatically generate schemes for all targets, but upon opening a workspace with a huge number of targets on XCode we are presented with a dialog asking whether we want XCode to generate the schemes automatically or manually.

![Screen Shot 2021-09-21 at 11 23 56](https://user-images.githubusercontent.com/3520727/134362562-67a378e9-0fb5-4b96-bb1e-3e19e1092622.png)

I think Tuist should generate this settings file since the `IDEWorkspaceSharedSettings_AutocreateContextsIfNeeded` option used by XCode is the same as using the `disableAutogeneratedSchemes` setting on Tuist.
[Apparently XcodeProj has support for generating it but Tuist is not using it](https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Project/WorkspaceSettings.swift).

**To Reproduce**

1. Generate a Workspace file on Tuist
2. Open the workspace in finder and see that there's no `WorkspaceSettings.xcsettings` file inside `xcshareddata`
3. Open the workspace in Xcode, go to Manage Schemes and toggle the `Autocreate schemes` option
4. Check the `xcshareddata` directory again and see that XCode created the `WorkspaceSettings.xcsettings` to store whether it should automatically generate schemes for target or not

**Expected behavior**
Tuist should generate the `WorkspaceSettings.xcsettings` inside the workspace.

**Desktop:**

- OS: macOS
- Version 11.5.2
- XCode 12.5.1

**Comment by jakeatoms** [comment]
I'll pick this up today. My team is hitting this issue as well since moving away from auto-schemes.
