### ISSUE TITLE
[Dependencies.swift][SPM] Build Errors in PLCrashReporter Dependency

### ISSUE THREAD

**Issue by moritzsternemann** [tuist/tuist#3488]
**Describe the bug**
*This was already briefly mentioned in #3286 but not investigated further yet.*

When importing [microsoft/plcrashreporter](https://github.com/microsoft/plcrashreporter) as a SPM dependency using Tuists Dependencies.swift, there are build errors in the dependencies source code.

**To Reproduce**

1. Use the attached minimal example zip
2. Run tuist dependencies fetch
3. Run tuist generate
4. Open the generated workspace
5. Build the main TuistPLCrashreporter target
6. Observe build errors in the CrashReporter target

Note that importing the same dependency using Xcodes SPM integration does not result in any build errors.

**Expected behavior**
I expect Tuist handled SPM dependencies to be compatible, when they are compatible with Xcode's built-in package management system.

**Desktop:**

- OS: macOS 11.5.2 / macOS 12 Developer Beta 6, Xcode 12.5.1
- Tuist Version: 1.49.2

[tuist-plcrashreporter.zip](https://github.com/tuist/tuist/files/7212417/tuist-plcrashreporter.zip)

**Comment by fortmarek** [comment]
Hey!

Sorry for not getting back to you sooner. Could you send details about the build errors you observe and if possible try it out with the latest tuist version? We can then investigate this further. Thanks!

**Comment by moritzsternemann** [comment]
After a while, I finally found an inconsistency that is probably the issue here:

I compared the build steps of a the `CrashReporter` target generated by Tuist with the build steps of the same target when importing the dependency via Xcode's SPM integration. I found that the Tuist-generated target has a Headers build phase copying header files from the PLCrashReporter sources to `Build/Products/Debug-iphonesimulator/CrashReporter.framework/Headers` whereas building the target in the standard Xcode project doesn't copy any header files.
When I removed the entire Headers build phase from the Tuist-generated target in Xcode, the build of the `CrashReporter` target was successful.

I'm not completely familiar with the inner workings of SPM and TuistDependencies and don't really know in which cases this Headers build phase is required for SPM dependencies. Maybe you have an idea here, @fortmarek?


I updated the example project to work with the latest Tuist version: [tuist-plcrashreporter.zip](https://github.com/tuist/tuist/files/7619102/tuist-plcrashreporter.zip).

**Comment by danyf90** [comment]
The Tuist logic tries to mimic the SPM one, and currently it is to add the copy headers phase if the package contains an umbrella header (i.e. and header with the same name of the package).

This is probably an edge case which is not handled correctly, but I am not sure what we should change here 🤔

**Comment by ffittschen** [comment]
Hi all, I just started digging into this as well.

Using a slightly updated version of the example project ([tuist-plcrashreporter.zip](https://github.com/tuist/tuist/files/7869880/tuist-plcrashreporter.zip)) provided by @moritzsternemann, the build will succeed if I make 2 small changes in the build settings of the PLCrashReporter.xcodeproj generated by tuist:

```diff
- ALWAYS_SEARCH_USER_PATHS = YES
+ ALWAYS_SEARCH_USER_PATHS = NO

- USE_HEADERMAP = NO
+ USE_HEADERMAP = YES
```

Is there any way we can define these build settings somewhere so that tuist picks them up during the generation of the project?

<img width="750" alt="Screen Shot 2022-01-14 at 11 49 02@2x" src="https://user-images.githubusercontent.com/7734806/149503646-4bc70e72-5f70-4a82-9937-021906139bd2.png">

**Comment by danyf90** [comment]
If it works, it would be great to add it to our `app_with_spm_dependencies` fixtures

**Comment by ffittschen** [comment]
Awesome, I just tested it and it works in the example project 🥳 Will try the same in our real project later today. I can also prepare a PR for the `app_with_spm_dependencies` fixtures. Should I just add the PLCrashReporter dependency and the targetSettings to the existing fixture?

**Comment by danyf90** [comment]
> Should I just add the PLCrashReporter dependency and the targetSettings to the existing fixture?

Yes, there should already be an acceptance test in place trying to build that project, so if any problem arises, it should be detected there
