### ISSUE TITLE
Unstable list of project dependencies

### ISSUE THREAD

**Issue by marciniwanicki** [tuist/tuist#349]
**Describe the bug**
Running `tuist generate` second time without modyfing the project can result in unexpected differences in xcodeproj file.

![Screen Shot 2019-05-14 at 8 03 07 AM](https://user-images.githubusercontent.com/946649/57678429-103de180-7621-11e9-8c84-135faf8c1c8a.png)

**To Reproduce**

1. Create a project depending on few frameworks (you can also use one of the fixtures, i.e. `fixtures/ios_app_with_frameworks` but first you will need to remove `*.xcodeproj` line from the `.gitignore` file in the Tuist root directory).
2. Run `generate` command
3. Stage changes (do not need to commit them)
4. Run `generate` command again without making any changes to the project
5. Check `git diff` 

**Expected behavior**
Expected empty diff, the `generate` command should be fully deterministic and produce the same output for a given input.

**Desktop (please complete the following information):**

- OS: macOS
- Version: master (7935c55856764f5c8f7c65ea37aa926443119f8b)

**Comment by pepibumur** [comment]
This is most likely an issue in XcodeProj. Thanks for opening the issue @marciniwanicki

**Comment by marciniwanicki** [comment]
I had a brief look today, I think it's a `Graph` 's cache implementation issue.

```swift
    var projects: [Project] {
        return Array(cache.projects.values)
    }

    var projectPaths: [AbsolutePath] {
        return Array(cache.projects.keys)
    }
```

where `var projects: [AbsolutePath: Project] { get }`

We might need an `OrderedMap` -like type. Sorting those key-value pairs would be a quick fix but it just does not feel right :)

**Comment by marciniwanicki** [comment]
It's not event that, I confused it with the ordering of the products in the console logs, the dependencies unstable ordering is probably caused by the `Graph`: 
```
func embeddableFrameworks(path: AbsolutePath, name: String, system: Systeming) throws -> Set<DependencyReference>
```
