### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by marciniwanicki** [tuist/tuist#350]
**Is your feature request related to a problem? Please describe.**
Ensuring the consistency between existing and generated projects is one of the methods we use in our team to mitigate the risks while migrating to Tuist. The generator uses built-in settings that can override values already stored in `.xcconfig` files (via tuist `ConfigGenerator.swift` and xcodeproj `BuildSettingsProvider.swift`). This behavior unfortunately makes the comparison of the headers much harder and stops us from using the `.xcconfig` for some of the settings.

**Describe the solution you'd like**
The goal is to let the client code control default settings and guarantee that all the configs in the `.xcconfig` files are preserved. I'm not entirelly sure what's the best way to achieve it, curious what others think about that scenario. 

I was thinking that initially we could make this feature available only in the `TuistGenerator`, maybe once we have `include` (or slimiar functionality) implemented, we can expose it via command line if people find it useful.
For now we could probably solve it by abstracting `BuildSettingsProvider` and injecting the implementation into `ConfigGenerator`. Client code could still leverage `BuildSettingsProvider.swift` by calling it internally and just niling selected settings, also it would omit `BuildSettingsProvider.swift` completely and provide only a small subset of default settings.

**Describe alternatives you've considered**
- Another approach might be an interceptor for the config generator. It could tweak the build configuration before it's assign to XcodeProj. That would allow us to forward selected set of default settings without any changes, tweak some and remove the rest. This "interceptor" concept could be used in other parts for applying adhoc modifications.

```
protocol ConfigGeneratorInterceptor {

    func didGenerate(buildSettings: inout [String: Any], target: Target, configuration: Configuration?)
}
```

- I guess we could also try to read `.xcconfig` and ignore a default setting if it's already defined in the file. The implementation might become quite complex as the configuration files allow importing other files, also it would require accessing file system what might affect the performance.

**Desktop (please complete the following information):**

- OS: macOS
- Version: master (7935c55856764f5c8f7c65ea37aa926443119f8b)

**Comment by pepibumur** [comment]
> The goal is to let the client code control default settings and guarantee that all the configs in the .xcconfig files are preserved. I'm not entirelly sure what's the best way to achieve it, curious what others think about that scenario.

I didn't think about this one but you are totally right.

Keeping the implementation details aside and thinking more from the product point of view, I'd adopt the following approach:
- When I generate a new project, in which I haven't configured any settings or xcconfig files, Tuist defaults to generating those settings for you.
- If I set settings or xcconfig files, Tuist understands that the user is taking control over the settings and therefore it doesn't generate them.

This would help you with the transition process using xcconfig files. If we see this confuses developers, we can rethink it.

The only downside of this approach is that it's a breaking change but I'd rather introduce it, instead of complicating the API with more flags that bring nothing but confusion.

**Comment by marciniwanicki** [comment]
Would be great to find something that can fix it but does not introduce any braking changes. I've pushed a simple implementation to demo the `DefaultSettingsProvider`: https://github.com/bloomberg/tuist/tree/feature/350-default-settings

Added `useDefaultSettings` to `Settings` in both manifest and generator models. By the default it's set to `true` but can be set to `false` to force the generator to ignore default settings. 

@kwridan had also a nice idea to use `nil` for all the settings that shouldn't be fetched from the default settings. Maybe I will try it out tomorrow :)

**Comment by pepibumur** [comment]
> Added useDefaultSettings to Settings in both manifest and generator models. By the default it's set to true but can be set to false to force the generator to ignore default settings.

Like this one :+1:

**Comment by kwridan** [comment]
Looking through the default settings, I'd class them under two categories

- essential
- recommended 

for example, setting the `SDKROOT` is quite a critical one, whereas the warning settings like `CLANG_WARN_EMPTY_BODY` can be part of recommended.

**Comment by pepibumur** [comment]
I really like the idea of having essential and recommended settings

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
