### ISSUE TITLE
[Dependencies.swift][SPM] Could not build Objective-C module 'FBSDKLoginKit'

### ISSUE THREAD

**Issue by PSKuznetsov** [tuist/tuist#3503]
**Describe the bug**
When building/caching Facebook-ios-sdk as a SPM dependency using Tuists Dependencies.swift get following error:
` include of non-modular header inside framework module 'FBSDKShareKit.FBSDKCoreKitImport': '/Users/user/Downloads/tuist-main/projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKit/include/FBSDKCoreKit.h'
#import <FBSDKCoreKit.h>`

**To Reproduce**

1. Go to '.tuist/fixtures/app_with_spm_dependencies'
2. Run tuist dependencies fetch
3. Run tuist cache warm

**Expected behavior**
Facebook SDK builds with no error

**Desktop (please complete the following information):**

- OS: macOS 11.5.2, Xcode 13, Swift 5.5
- Tuist version 1.51.0

**Comment by danyf90** [comment]
Should be fixed using Facebook 12.x+ and Tuist 2.3.2+
