### ISSUE TITLE
Xcode 13.0 SwiftC bug report

### ISSUE THREAD

**Issue by ViniciusDeep** [tuist/tuist#3504]
**Describe the bug**

When I use Xcode 12.1 .... 12.5.1 Tuist does work in our project, but when updated to 13 this found a new issue

**To Reproduce**
Just Run: tuist generate

**Expected behavior**
Project is generated with success

**Screenshots**
<img width="550" alt="Captura de Tela 2021-09-23 às 12 55 15" src="https://user-images.githubusercontent.com/32227073/134541696-959794ce-6d62-4fc3-b5ab-cba2c1123bd5.png">
This is our problem, at Xcode 13

**Desktop (please complete the following information):**
MacOS Big Sur 11.3.1
Mac 16Inch I7

**Additional context**

**Comment by fortmarek** [comment]
Hey @ViniciusDeep!

Thanks for the report. We are aware of this issue and it's already tracked [here](https://github.com/tuist/tuist/issues/3454). Hopefully, [this](https://github.com/tuist/tuist/pull/3499) should fix the issue. 

I'll close this as a dupe, if you have any additional questions/concerns, please report them in the other issue.

**Comment by ViniciusDeep** [comment]
Hey @fortmarek 

Greetings,

The issue was solved?

**Comment by fortmarek** [comment]
[This](https://github.com/tuist/tuist/pull/3499) has, unfortunately, still not been merged. Has it started working for you @ViniciusDeep? There have been other PRs that could have possibly influenced this.

**Comment by ViniciusDeep** [comment]
@fortmarek Thank's for the answer.

Still not work here, but I can watch that https://github.com/tuist/tuist/pull/3499 PR is merge, I think that need launch a new version with these fix.

@fortmarek Thanks for report

**Comment by danyf90** [comment]
@ViniciusDeep have you tried to run a `tuist clean`? those changes should be related to your issue

**Comment by ViniciusDeep** [comment]
@danyf90 Yeah, but the issue has continued
