### ISSUE TITLE
Add support for specifying the `RunAction` launch behaviour

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#3511]
## Context 🕵️‍♀️

Xcode offers two launch behaviours (or styles) via the scheme editor

- Automatically
- Wait for the executable to be launched

![launch-style](https://user-images.githubusercontent.com/11914919/134709749-7320a75b-8014-4157-a76d-6eab5d2e9462.png)

Controlling this option isn't currently possible for projects generated with Tuist.

## Proposal 🎉

Introduce a new property on `RunAction` that allows controlling this behaviour.

### API

Introduce a new **optional** property to `RunAction` which defaults to `nil` - this ensures backwards compatibility and allows Tuist to continue to control the default behaviour when not explicitly specified.

```swift
struct RunAction {
 // ...
 var launchStyle: LaunchStyle? = nil
}
```

The new property would be an enum with two options that reflects the options visible in the UI:

```swift
enum LaunchStyle { 
  case automatic
  case waitForExecutableToBeLaunched
}
```

This would only be added to `RunAction` seeing it's not applicable to any of the other actions.

### Implementation

From what I can see, this is already available in `XcodeProj` via [`LaunchAction.launchStyle`](https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Scheme/XCScheme+LaunchAction.swift#L42). This option can be configured within the `SchemeDescriptorGenerator` based on the new `RunAction` option.

### Name

Seeing this is introducing a new API, it's worth taking a moment to think through the possible names:

- `LaunchStyle`: The current underlying XcodeProj nomenclature
- `LaunchBehaviour`: A possible alternate

### Should this be added?

Tuist generally exposes a high level API on top of XcodeProj as opposed to offering every single option and setting, the scheme editor in Xcode has many options that are currently not exposed in Tuist. For some of those, this is on purpose to keep the API simple and allow Tuist to control them automatically based on certain rules and use cases, for others it was initially omitted as it wasn't needed at the time and would be later added should a need arise.

The question is, to which category does this specific option lie?

## Alternatives

If the need for this is a one off _(e.g. debugging / troubleshooting an issue)_, simply changing it manually in the scheme editor when needed should suffice without needing to have this be part of the generated project. 

## Additional Notes

_Originally requested by @rafagan in https://github.com/tuist/tuist/discussions/3486_

**Comment by kwridan** [comment]
From my past use cases - I've always gone for the suggested alternative of manually changing it as I never felt it was something I needed to have be permanently part of the generated project. 

For example when needing to debug the app launching due to external events such as:
 - Notifications
 - Universal links 
 - Quick actions
 - Siri shortcuts

Would be keen to hear if there are use cases / workflows where this needs to be permanently part of the generated scheme.

**Comment by rafagan** [comment]
Extensions (e.g. iMessage Stickers)simply don't run without these configurations. So, the generated Scheme is incomplete. Also, there's also any reason to don't provide it if there's someone interested in this kind of generation.
