### ISSUE TITLE
Headers issue

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#352]
**Describe the bug**
> ❌ Error: Trying to add a file at path ...../Support to a build phase that hasn't been added to the project.

**To Reproduce**
`headers: Headers(public: nil, private: nil, project: "./Support"),`

**Expected behavior**
All headers in Support directory will be added to the project as project headers.

**Desktop:**

- OS: latest
- Version latest

**Comment by zdnk** [comment]
I think I see the issue. We have headers scattered all around the project and not in single folders. Tuist is expecting them to be all in single folder.

**Comment by kwridan** [comment]
Hi @zdnk

I believe tweaking the glob pattern for headers will resolve this issue:

e.g.

`Support/**/*.h`

**Comment by zdnk** [comment]
I see, would be fine to document this somewhere as it says it needs "directory" in documentation. What about headers that are outside of the scope of "Support" dir and still should be project headers?

**Comment by zdnk** [comment]
Another issue: Linking framework with FRAMEWORK_SEARCH_PATHS is not possible. Tuist checks the paths during generation without looking at FRAMEWORK_SEARCH_PATHS

EDIT: This also sucks for adding dependency on system/built-in frameworks

**Comment by kwridan** [comment]
> I see, would be fine to document this somewhere as it says it needs "directory" in documentation

The documentation could do with an update here. There is still a bug here actually as specifying a very permissive glob pattern (e.g. `Sources/**`) can easily cause a failure too! :( - Filtering out paths to only include header files can help alleviate this. 

> What about headers that are outside of the scope of "Support" dir and still should be project headers?

This isn't currently supported for headers, but shouldn't be too hard to add. Both `sources` and `resources` have been changed recently to support an array of paths / glob patterns (see #266). I've raised #354 for this, if you're interested in contributing it would be a great enhancement to Tuist.

> Another issue: Linking framework with FRAMEWORK_SEARCH_PATHS is not possible. Tuist checks the paths during generation without looking at FRAMEWORK_SEARCH_PATHS

Can you elaborate more on this (an example may help)?

> EDIT: This also sucks for adding dependency on system/built-in frameworks

There's a work in progress PR to support system dependencies #272

**Comment by zdnk** [comment]
> Can you elaborate more on this (an example may help)?

Well in the same way you are importing headers in source files, the compiler is looking for those headers in configured header search paths. The same system works with frameworks I believe. You should be able to simply specify framework name and the compiler/xcode will find the framework using the configured framework search paths. Or I am completely wrong :D

**Comment by zdnk** [comment]
Maybe it would be nice to add option like `unchecked`/`unvalidatedFramework(path: String)` dependency option or something similar so Tuist offers this option that you configure the search paths yourself and you actually know what you are doing. For example, search paths might use some variables in the paths (our case, `$(J2OBJC_HOME)/frameworks`) and we have just linked the 2 frameworks we are using from `j2objc` and it finds them automatically. This is not possible to configure with Tuist as using `.framework` yields error that it cannot find the file.

**Comment by kwridan** [comment]
You can manually specify custom build settings, this may help your use case:

e.g.

```swift
Target(name: "App",
       // ...
        settings: Settings(base: [
                "FRAMEWORK_SEARCH_PATHS": "$(inherited) $(J2OBJC_HOME)/frameworks",
                ”OTHER_LD_FLAGS”: “-framework MyCustomFramework"
            ]))
```

**Comment by zdnk** [comment]
Yep, thats what I did in the end.

**Comment by kwridan** [comment]
Docs have been updated and specifying headers in the manifest should be less error prone in the next release - thanks for flagging this 👍
