### ISSUE TITLE
add xcdatamodel file to Target doesn't work

### ISSUE THREAD

**Issue by Odyflame** [tuist/tuist#3522]
**Describe the bug**

when run tuist generate, there's some error.
`'Trying to add a file at path "path/\(AppName).xcdatamodeld" to a build phase that hasn't been added to the project.`
and i think my Project.swift file is writen right.

```
Target(
        name: "AppName",
        platform: .iOS,
        product: .app,
        bundleId: "com.com.com",
        deploymentTarget: DeploymentTarget.iOS(
            targetVersion: "13.0",
            devices: [DeploymentDevice.iphone]
        ),
        infoPlist: "\(plist path...)",
        sources: [ "AppName/**" ],
        resources: [ "AppName/**" ],
        ],
        coreDataModels: [
            CoreDataModel("\(path..).model.xcdatamodeld", currentVersion: "model")
        ]
    )
```
i add coreDataModels and write them.

i think the tuist can't find xcdatamodeld path..

is there any ideas that solve this problem?

**Comment by kwridan** [comment]
Hi @Odyflame 

Are you able to reproduce in a sample project you can attach?

I sanity checked the [core data fixture](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_coredata) and it seems to generate fine with the latest version 1.51.1, worth examining it to see which tweaks / scenarios cause the failure.

Thanks!

**Comment by Odyflame** [comment]
my processes.

1, i clone file that @andreacipriani 's [sample project](https://github.com/andreacipriani/tuist-mapping-model), #910. 
2. add xcDatamodel and create NSManagedObject subclasses.
3. and edited project.swift for resorces for mappingapp.xcdatamodelid.
4. enter tuist generate, and it emit error that
```
 Trying to add a file at path /Users/cado.avo/Cado/Study/tuist-mapping-model-master/App/Sources/23-24.xcmappingmodel/xcmapping.xml to a build phase that hasn't been added to the project.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

i think maybe it's tuist error.
here's my used [sampel repo](https://github.com/Odyflame/TuistSampleAppForIssue)

**Comment by Odyflame** [comment]
yeah, your codes successfully make project.

```
let target = Target(
                name: "Example",
                platform: .iOS,
                product: .app,
                bundleId: "com.example.mappingmodel",
                infoPlist: InfoPlist(stringLiteral: "App.plist"),
                sources: "Sources/**",
                resources: "Sources/**"
                coreDataModels: [
                    CoreDataModel("Sources/mappingapp.xcdatamodeld"),
                ]
            )
let project = Project(
    name: "MappingModelExample", 
    targets: [target]
)
```
there are some issue that if i want use coredata i should divide source files and resources file
it make me solve this problem..

**Comment by lucaspioto** [comment]
Is it possible to put coredata in the Resources folder?
