### ISSUE TITLE
Xcode 13 - Dependencies.swift - bitcode not enabled for dependency error

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#3526]
**Describe the bug**
When generating project with SPM dependencies in Dependencies.swift, and using [Apollo](https://github.com/apollographql/apollo-ios) and opening generated workspace in Xcode 13, the build fails because Apollo is not built with bitcode, I checked the Tuist generated Apollo project build settings and bitcode is enabled.

It works fine in Xcode 12!

<img width="1849" alt="Screenshot 2021-09-30 at 12 53 11" src="https://user-images.githubusercontent.com/2551911/135442427-729c8472-3c7c-4c45-9865-f0768560c455.png">

Example project: https://github.com/zdnk/tuist-apollo-dependency-example

It only occurs when:
- building with Xcode 13
- building for device or archiving
- the Apollo dependency is linked in framework which is linked in the app

Last tested on Tuist 2.0.2, Xcode 13

UPDATE: seems to happening for any dependency linked to framework which is then linked to app.

**To Reproduce**
Project.swift
```swift
import ProjectDescription

let baseSettings = SettingsDictionary()
    .bitcodeEnabled(true)

let project = Project(
    name: "TuistApollo",
    settings: .settings(base: baseSettings),
    targets: [
        // App
        .init(
            name: "App",
            platform: .iOS,
            product: .app,
            productName: "TuistApollo",
            bundleId: "com.TuistApollo.application",
            deploymentTarget: .iOS(targetVersion: "14.0", devices: .iphone),
            infoPlist: .default,
            sources: [
                "Targets/TuistApollo/Sources/*.swift",
            ],
            dependencies: [
                .external(name: "Apollo"),
                .target(name: "API"),
            ]
        ),

        .init(
            name: "API",
            platform: .iOS,
            product: .framework,
            productName: "API",
            bundleId: "com.TuistApollo.api",
            deploymentTarget: .iOS(targetVersion: "14.0", devices: .iphone),
            infoPlist: .default,
            sources: [
                "Targets/TuistAPI/Sources/*.swift",
            ],
            dependencies: [
                .external(name: "Apollo"),
            ]
        ),

    ]
)
```

Dependencies.swift
```swift
import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/apollographql/apollo-ios.git", requirement: .upToNextMajor(from: "0.43.0")),
    ],
    platforms: [.iOS]
)
```

Generate the project/workspace:
```
tuist dependencies fetch
```
```
tuist generate
```

**Desktop (please complete the following information):**

- Tuist: 1.51.1
- OS: macOS Monterey
- Version 12.0 Beta (21A5506j)

**Comment by zdnk** [comment]
any pointer where/what is the issue?

**Comment by zdnk** [comment]
same on 2.0.1

**Comment by danyf90** [comment]
Hey @zdnk 👋 
Could you please attach a sample project to reproduce the issue (e.g. as done [here](https://github.com/tuist/tuist/issues/3459))?

**Comment by marciliojrs** [comment]
I'm having the same issue. Everything working when building for simulators but I'm getting the same message for device builds.

**Comment by zdnk** [comment]
version 2.1.1 using `tuist generate` just outputs
> Using version 2.1.1 defined at /Users/zdnk/projects/locksign/ios-app/.tuist-version

And thats it, nothing is generated.

**Comment by zdnk** [comment]
> Try flipping `ENABLE_TESTING_SEARCH_PATHS = YES` in any of the xcodeproj files for a converted SPM module to `NO` as I believe that will fix it.

@thedavidharris After moving GRDB back to packages in `Project.swift` this workaround works :)
Now does this break anything else, why is it causing this issue and how to fix it?

**Comment by wattson12** [comment]
> Now does this break anything else, why is it causing this issue and how to fix it? 

I'm interested if this breaks anything, but I've added a PR which adds this change for all SPM packages to help test https://github.com/tuist/tuist/pull/3653

**Comment by zdnk** [comment]
after checking with Tuist 2.3.0, the issue when running `tuist generate` and it does not do anything when GRDB (https://github.com/zdnk/GRDB.swift) is in Dependencies.swift as SPM package is stil there.

**Comment by zdnk** [comment]
also, `Tuist/Dependecies/SwiftPackageManager` is empty

**Comment by danyf90** [comment]
@zdnk  this looks like a different error wrt the original one, could you please open a separate issue and provide all the required information? 🙏
