### ISSUE TITLE
Where is .cocoapods in Tuist 2?

### ISSUE THREAD

**Issue by rafagan** [tuist/tuist#3535]
The dependency .cocoapods is missed in new version as described [here](https://docs.tuist.io/1/guides/dependencies):

`.cocoapods(path: ".") // Expects a Podfile in the directory of the target's project`

How can I achieve the same result?

**Comment by fortmarek** [comment]
Hey @rafagan!

Removing it was not a light decision but we generally thought it was mostly creating confusion and it did not provide much value. You can read more about it as well as read about our suggestion how to migrate to a different solution [here](https://github.com/tuist/tuist/blob/main/CHANGELOG.md#removed)
