### ISSUE TITLE
Missing swift version in ProjectDescriptionHelpers hash calculation

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3542]
As discussed [on Slack](https://tuistapp.slack.com/archives/C01FX6HDWH2/p1632814831001200), after updating to Xcode 13 I am getting the following error when using a plugin:
```
/XXX/Project.swift:4:8: error: module compiled with Swift 5.4.2 cannot be imported by the Swift 5.5 compiler: /XXX/.tuist/Cache/ProjectDescriptionHelpers/3dc1711/46c0f7a3b7c2e0fc2528bb83b1e66507/ProjectDescriptionHelpers.swiftmodule
import ProjectDescriptionHelpers
```

Of course it can be fixed with a tuist clean projectDescriptionHelpers, but maybe we should add the swift version to the cache hash?

**Comment by adellibovi** [comment]
@danyf90 closing this as it seems we already do that in the ProjectDescriptionHelpersHasher.
