### ISSUE TITLE
Warning and errors in `tuist edit`

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3543]
**Describe the bug**
When using `tuist edit` I am getting unexpected warnings and errors:
1. on the `import ProjectDescription` line: `'/Users/XXX/.tuist/Versions/2.0.2/ProjectDescription.framework/Modules/ProjectDescription.swiftmodule/Project/x86_64-apple-macos.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules`
2. If I have some simple logic, like the one below, I get 2 errors: `Global 'let' declaration requires an initializer expression` on the `let name: String` line, and `Cannot call value of non-function type 'Environment.Value?'` on the `if` line.

Sample logic for point 2:
```
let name: String
let envName = Environment.name.getString(default: "")
if Environment.name(default: "").isEmpty {
    name = "DefaultNAme"
} else {
    name = envName
}
```

Despite the errors in `tuist edit`, a `tuist generate` then works fine

**To Reproduce**

1. Go to an empty folder
2. Run `tuist init`
3. Run `tuist edit`
3. Add a logic condition as the example above

**Expected behavior**
No warning and error should be shown

- OS: BigSur
- Version 2.0.2

**Comment by danyf90** [comment]
Seems fixed in `2.2.0` 🚀

**Comment by VilleWitt** [comment]
I get this, fairly similar message, but different version: 

> '/Users/XXX/.tuist/Versions/2.7.2/ProjectDescription.framework/Modules/ProjectDescription.swiftmodule/Project/x86_64-apple-macos.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules

$ swift --version
swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx12.0

Xcode: Version 13.2.1 (13C100)

**Comment by luispadron** [comment]
#4132 should resolve this issue!
