### ISSUE TITLE
TargetAction extension

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#355]
Currently the `TargetAction` does not allow to set input/output files or file lists, but there is also missing the option from Xcode "Run only when installing" which is kinda important if you wanna add some build phase that strips symbols of unwanted architectures from embedded frameworks.

**Comment by kwridan** [comment]
@Rag0n has a PR for this already 🙂

https://github.com/tuist/tuist/pull/353

**Comment by ollieatkinson** [comment]
Closed by https://github.com/tuist/tuist/pull/353
