### ISSUE TITLE
Installation fail with `tuist install tuist/tuist-up`

### ISSUE THREAD

**Issue by pmieszal** [tuist/tuist#3555]
**Describe the bug**
I face an installation failure when run `tuist install tuist/tuist-up`.
I'm using latest `tuist` 2.0.2 version.

```
Downloading version tuist/tuist-up
Installing...
The '/usr/bin/unzip' command exited with error code 9 and message:
[/var/folders/cr/3d3q8ls91hsgfq89nskrmf_w0000gn/T/TemporaryDirectory.iXtMtH/tuist.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/cr/3d3q8ls91hsgfq89nskrmf_w0000gn/T/TemporaryDirectory.iXtMtH/tuist.zip or
        /var/folders/cr/3d3q8ls91hsgfq89nskrmf_w0000gn/T/TemporaryDirectory.iXtMtH/tuist.zip.zip, and cannot find /var/folders/cr/3d3q8ls91hsgfq89nskrmf_w0000gn/T/TemporaryDirectory.iXtMtH/tuist.zip.ZIP, period.

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

**To Reproduce**

1. run `tuist install tuist/tuist-up`

**Expected behavior**
Installation should be successful 🧐

**Desktop (please complete the following information):**

- OS: macOS
- Version 11.5.2
- Apple M1

**Comment by fortmarek** [comment]
Hi @pmieszal!

The installation method you are referring to _has not been implemented yet_ and will be a part of Plugins 2.0 once we ship them.

You can use e.g. [mint](https://github.com/yonaskolb/Mint) to install the tool. I have [updated](https://github.com/tuist/tuist-up/commit/eaf8178bed485cef79abc01d55bfd26b46938353) the readme to make this more obvious. Let me know if you need any further help!
