### ISSUE TITLE
Moving from v1.48.1 to 1.50.0 Removed Essentials

### ISSUE THREAD

**Issue by jsorge** [tuist/tuist#3556]
**Describe the bug**
When I updated Tuist from v1.48.1 to v1.50.0 using a local `.tuist-version` file in our repo, then running `tuist bundle`, many files were deleted. This includes the ProjectAutomation framework as well as tooling from `vendor` (swift-doc, swiftlint, and xcbeautify). This caused the `tuist edit` command to start failing because ProjectAutomation was no longer found.

**Desktop (please complete the following information):**

- OS: macOS 11.6.1
- Version v1.48.1 -> v1.50.0

**Comment by pepibumur** [comment]
Following up on this one
