### ISSUE TITLE
Carthage dependencies are built from source even if a pre-built framework is available

### ISSUE THREAD

**Issue by wattson12** [tuist/tuist#3586]
**Describe the bug**
The use of both `--use-xcframeworks` and `--no-use-binaries` results in `carthage` dependencies being rebuilt from source even if there is a `.xcframework` available 

**To Reproduce**

1. Add a carthage dependency using a library / version which includes a pre-built XCFramework (e.g. `realm/realm-cocoa` / `v10.17.0`) 
2. Run `tuist dependencies fetch`
3. Observe in logs that the target is being built rather than being downloaded (I recommend killing the process here because building this target takes a long time)

**Expected behavior**
If a framework is available we should have the option to use that binary rather than re-building. Note that this behaviour is consistent with using `carthage` directly so to get this expected behaviour we would need to be able to optionally remove the `--no-use-binaries` flag 

**Dependencies fetch logs**

This is the start of the logs, before I killed the process
```
*** No Cartfile.resolved found, updating dependencies
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "v10.17.0"
*** No cache found for realm-cocoa, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/q2/pj0jqvd90sv9mwbc02l_tjnc0000gn/T/carthage-xcodebuild.4w1hbr.log
*** Building scheme "Realm iOS static" in Realm.xcworkspace
....
```

**Desktop (please complete the following information):**

- OS: macOS 11.6
- Tuist version: 2.0.2

**Additional context**

I asked a question about this behaviour in [slack](https://tuistapp.slack.com/archives/C018QG7U7SN/p1634749325301300) and shared a workaround for this issue using a local json mapping to the release. In that thread the options to provide a test for this workaround or to allow a user to configure the carthage options (this was previously allowed but removed in [this MR](https://github.com/tuist/tuist/pull/3043))

When I pull the same dependency using `carthage` directly but without the `--no-use-binaries` flag this is the output 

```
*** No Cartfile.resolved found, updating dependencies
*** Cloning realm-cocoa
*** Checking out realm-cocoa at "v10.17.0"
*** xcodebuild output can be found in /var/folders/q2/pj0jqvd90sv9mwbc02l_tjnc0000gn/T/carthage-xcodebuild.GOoTKH.log
*** Downloading realm-cocoa binary at "v10.17.0"
```

**Comment by fortmarek** [comment]
We will be removing support for Carthage. See the reasoning here: https://github.com/tuist/tuist/discussions/5414
