### ISSUE TITLE
Adding Support to SwiftUI Image to `assetsTemplate`

### ISSUE THREAD

**Issue by leogdion** [tuist/tuist#3595]
## Context 🕵️‍♀️

Currently the default template only adds support for UIKit/AppKit Images. It would be nice to be able to add a property for `SwiftUI.Image`.

## What 🌱

`SwiftUI.Image` is missing as a property of a resource image from the default `assetTemplate` in `AssetsTemplate.swift`.

## Proposal 🎉

I am open to ideas on this one but the most basic way is to add a new property:
```
    #if canImport(SwiftUI)
    @available(iOS 13.0, *)
    {{accessModifier}} var suiImage: Image {
        let bundle = {{bundleToken}}.bundle
        return Image(name, bundle: bundle)
    }
    #endif
```

Also extend `SwiftUI.Image` with an initializer which takes a `{{imageType}}` and automates the bundle component:

```
extension Image {
  init(_ resourceImage: {{imageType}}) {
    self.init(resourceImage.name, bundle:  {{bundleToken}}.bundle)
  }
}
```

**Comment by arunrdd** [comment]
I'm working on a project that uses both SwiftUI and UIKit. Why provide a choice when the interoperability between both is clearly supported in the iOS ecosystem? It's best I think for SwiftGen to support both types of accessors, as neither SwiftUI nor UIKit is on path for deprecation or did I miss something here 🤔

**Comment by fortmarek** [comment]
Hey @arunrdd 👋 

Yes, I think it makes sense to support both. However, as a user you might want to make SwiftUI or UIKit the default, so it's more convenient to access the assets instead of always having to specify whether you are trying to get a SwiftUI or UIKit asset.
