### ISSUE TITLE
[Dependencies.swift][SPM] Build fails due to minimum deployment target

### ISSUE THREAD

**Issue by ammerzon** [tuist/tuist#3596]
**Describe the bug**
I added `swift-composable-architecture` as dependency. Until #3173 is implemented I set the SPM deployment target as done [here](https://github.com/tuist/tuist/blob/master/projects/tuist/fixtures/app_with_spm_dependencies/Tuist/Dependencies.swift#L13).

<details>
  <summary>Dependencies.swift</summary>

```swift
import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: .init(
        [
            .package(url: "https://github.com/pointfreeco/swift-composable-architecture", .upToNextMajor(from: "0.28.0")),
        ],
        deploymentTargets: [
            .iOS(targetVersion: "15.0", devices: [.iphone])
        ]
    ),
    platforms: [.iOS]
)
```
</details>

Nevertheless, I still got the following error message: `Compiling for iOS 13.0, but module 'OrderedCollections' has a minimum deployment target of iOS 15.0`.

**To Reproduce**

1. Add `swift-composable-architecture` as dependency
2. Run `tuist bundle`
3. Run `tuist dependencies fetch`
4. Run `tuist generate`
5. Open the workspace and start a build

**Expected behavior**
The build should not fail.

**Desktop**

- OS: macOS
- Version: 11.6

**Additional context**

[app_spm_deployment_target.zip](https://github.com/tuist/tuist/files/7412230/app_spm_deployment_target.zip)

**Comment by tapwork** [comment]
How can I set the deployment targets in the Dependencies.swift?

**Comment by danyf90** [comment]
> How can I set the deployment targets in the Dependencies.swift?

Shouldn't be needed anymore
