### ISSUE TITLE
📦 [Dependencies.swift][SPM] 'No such module' with custom configurations

### ISSUE THREAD

**Issue by mgray88** [tuist/tuist#3599]
**Describe the bug**
Related to #3563 but different failure issue. That issue documents the "missing configurations" issue that occurs with `tuist dependencies fetch`. Those however are just warnings, and if the fetch succeeds otherwise, when attempting a build a target with a custom configuration, `No such module...` errors are thrown on import statements

**To Reproduce**

1. Download the attached [project](https://github.com/tuist/tuist/files/7420159/tuisty.zip)
2. `tuist dependencies fetch`
3. `tuist generate --open`
4. Build either `Success` or `Fail` targets

**Expected behavior**
Both the `Success` and `Fail` targets should compile.

**Desktop (please complete the following information):**

- OS: macOS 11.6
- Version: tuist 2.1.0

**Comment by pepibumur** [comment]
Hey @mgray88, thanks for reporting this, and apologies for the inconveniences it's causing. We are still uncovering some edge cases in the logic that integrates packages into your project's graph and this seems to be one of them. I've taken note of this and we'll soon work on providing you with a solution.
