### ISSUE TITLE
💡 Facilitate focusing on project targets

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3614]
It would be nice to have an easy way to focus on project defined targets, and include dependencies as binaries.

We could enhance the `cache` and `focus` command to accept a new parameter, for example:
```
tuist cache warm --project-targets --dependencies only
tuist cache focus --project-targets
```

Would create a focused project including all project defined targets, and linking external dependencies as binaries.
This would also be included in the `./fourier generate tuist` to automatically create a focused project for that

**Comment by fortmarek** [comment]
`tuist cache warm --project-targets --dependencies only` is there a need for this? This feels a little overcomplicated to me imho. As a user, I'm not sure if I would understand this right away.

`tuist cache focus --project-targets` - this looks good, it is well-readable and useful! 🚀

**Comment by danyf90** [comment]
If we don't provide the command, how would the user warm the cache only for the required targets?

**Comment by fortmarek** [comment]
> If we don't provide the command, how would the user warm the cache only for the required targets?

I don't think such functionality is detached from "Facilitate focusing on projects targets", no? You can still focus on project targets and warm the cache as a whole. If we wanted to facilitate doing cache warm for dependencies only, I'd maybe find something like `tuist cache warm --dependencies` or `--dependencies-only` more readable.

**Comment by danyf90** [comment]
I don't think people wants to cache things they don't actually need, and that's why we already have `--dependencies-only` so when you do `tuist cache warm X --dependencies-only` only builds X dependencies, and not X itself.

Given that, to achieve the result requested in this RFC, we would need a way to pass in the list of project target to tuist cache warm.

Now that I think more about it, I think the `--project-targets` is redundant in both commands:
- `tuist cache warm` (without a list of target) right know builds everything, and just ignores the `--dependencies-only` parameter. We could just fix its behavior to consider it, so that `tuist cache warm --dependencies-only` only warms external dependencies
- `tuist focus` (without a list of target) right know is not a valid command. We could just make it valid and make it focus on project targets.

What do you think @tuist/core ?

**Comment by luispadron** [comment]
@danyf90 Im in favor of what you propose. I imagine using this to just cache the external dependencies to my project but not actually the project targets themselves. I can't think of too many cases (except for really stable targets) where i would want my direct target dependencies cached, we already use small-ish projects so we don't need to deal with building the whole thing. 

I like this update to make focus easier to use without providing a target to focus and instead just focusing on all the project targets. I also like the ability to only cache the dependencies.. i almost wonder if we should invert this:

- `tuist focus`: by default focuses on all project targets with the ability to provide specific targets to focus on. 
- `tuist cache warm`: by default warms only external project dependencies with ability to provide `--all` to warm all the targets in the graph.

**Comment by danyf90** [comment]
I agree that inverting the `tuist cache warm` (i.e. having a --all instead of a --dependency-only) would provide a better API, but it would be a major change so I would stick with current behavior

**Comment by fortmarek** [comment]
Thanks @danyf90 for the clarifications!

I agree with your proposed changes 👌

**Comment by pepibumur** [comment]
I'm onboard with the idea. Just a nitpicky thing, would `--only-dependencies` read more natural? If you map the intent to a sentence: 
  I want to **warm** the **cache** with **only** the **dependencies**
