### ISSUE TITLE
Tuist ignores static libraries in xcframeworks 

### ISSUE THREAD

**Issue by pokryfka** [tuist/tuist#3621]
**Describe the bug**

Dependency (Carthage binary FirebaseAnalytics) is not (signed and) embedded by the app causing linking problem.

Note that `Tuist` does not expose any interface to explicitly  configure how a framework is embedded.

**To Reproduce**

I created a sample project to present the problem: https://github.com/pokryfka/tuist-demo

Its the template project generated by tuist (version 2.1.0) plus a Carthage binary package in `Tuist/Dependencies.swift`:

```swift
import ProjectDescription

let dependencies = Dependencies(
    carthage: [
        .binary(path: "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json", requirement: .exact("8.9.0")),
    ],
    platforms: [.iOS]
)
```

and then adding it in `Tuist/ProjectDescriptionHelpers/Project+Templates.swift`

```swift
--- a/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
+++ b/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
@@ -21,6 +21,10 @@ extension Project {

     /// Helper function to create a framework target and an associated unit test target
     private static func makeFrameworkTargets(name: String, platform: Platform) -> [Target] {
+        // hack just for the demo
+        // note that the dependency is not embeeded in the target (which is ok)
+        // nor in the app (even if added explicitly as a dependency in the app target)
+        let dependencies: [String] = name == "MyAppKit" ? ["FirebaseAnalytics"] : []
         let sources = Target(name: name,
                 platform: platform,
                 product: .framework,
@@ -28,7 +32,8 @@ extension Project {
                 infoPlist: .default,
                 sources: ["Targets/\(name)/Sources/**"],
                 resources: [],
-                dependencies: [])
+                dependencies: dependencies.map { .external(name: $0) }
+            )
         let tests = Target(name: "\(name)Tests",
                 platform: platform,
                 product: .unitTests,
```

**Expected behavior**

`FirebaseAnalytics.xcframework` is Embedded and Signed by `MyApp`.

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.0.1

**Comment by pepibumur** [comment]
Thanks for reporting this @pokryfka and apologies for the inconveniences this is causing. We'll try to provide you with a solution soon.

**Comment by AnisovAleksey** [comment]
@pokryfka  but current example working as expected. Another issue here that you should add all frameworks of FirebaseAnalytics. 

Full list of xcframeworks:
```
FirebaseAnalytics.xcframework
GoogleDataTransport.xcframework
FirebaseCore.xcframework
GoogleUtilities.xcframework
FirebaseCoreDiagnostics.xcframework
PromisesObjC.xcframework
FirebaseInstallations.xcframework
GoogleAppMeasurement.xcframework
nanopb.xcframework
GoogleAppMeasurementIdentitySupport.xcframework
```

and here little issue that Carthage download Firebase.framework to the iOS folder (Carthage/Build/iOS) and it isn't available through simple `.external("Firebase")`, instead we should use `.framework(path: "Tuist/Dependencies/Carthage/Build/iOS/Firebase.framework")`

**Comment by pokryfka** [comment]
Thank you for following up on that.

I am trying to import `xcframework`, not `framework`

And so I add dependencies for each of the them like `.xcframework(path: "Tuist/Dependencies/Carthage/Build/iOS/FirebaseAnalytics.xcframework")`

I am not trying to and dont want to import `iOS/Firebase.framework`

That's what I have been doing and its works fine for other xcframeworks,
except for Firebase which are listed as dependencies but only as "Do No Embed".

**Comment by AnisovAleksey** [comment]
@pokryfka 
sorry for confusing, my issue was about Google AdMob.

About your issue
If dependency listed as "Do No Embed"  - what problem this cause? Crash or problems with uploading to the AppStore?

**Comment by pokryfka** [comment]
> @pokryfka sorry for confusing, my issue was about Google AdMob.
> 
> About your issue If dependency listed as "Do No Embed" - what problem this cause? Crash or problems with uploading to the AppStore? I just trying to run your sample project and it's working fine. Yes, this listed as "Do No Embed", but working :)

If required dynamic library (Framework contains dynamic libraries) is not available, its a crash at runtime.

There may be no crash if you dont use it (I did not modified your template app, so it does not use referenced Framework),
try to import and use it and it will crash (just importing should be enough).

(Also might be that it will not crash until to deploy it to device/simulator; the files are available on your macOS which might be enough for local runtimes).

**Comment by pokryfka** [comment]
> @pokryfka sorry for confusing, my issue was about Google AdMob.
> 
> About your issue If dependency listed as "Do No Embed" - what problem this cause? Crash or problems with uploading to the AppStore? I just trying to run your sample project and it's working fine. Yes, this listed as "Do No Embed", but working :)

Its crash, as soon as you try to import not existing libraries.

**Comment by pokryfka** [comment]
This has not been fixed since Nov 1st, so I got to the point that I either need to stop using Tuist or fix it myself :-) 

I debugged it the problem is because Firebase `xcframework`s are static (or at least recognized that way),
while the other `xcframework`s are recognized as dynamic.

then `GraphTraverser` filters out not dynamic libraries in

```swift
        /// Precompiled frameworks
        let precompiledFrameworks = filterDependencies(
            from: .target(name: name, path: path),
            test: isDependencyPrecompiledDynamicAndLinkable,
            skip: canDependencyEmbedProducts
        )
        .lazy
        .compactMap(dependencyReference)
        references.formUnion(precompiledFrameworks)
``` 

the implementation of `isDependencyPrecompiledDynamicAndLinkable` (with a quick fix) for reference:

```swift
    func isDependencyPrecompiledDynamicAndLinkable(dependency: GraphDependency) -> Bool {
        switch dependency {
        case let .xcframework(_, _, _, linking):
            // TODO: fixes embedding of Firebase xcframeworks (does not follow what name would suggest)
            return linking == .dynamic || linking == .static
        case let .framework(_, _, _, _, linking, _, _),
             let .library(path: _, publicHeaders: _, linking: linking, architectures: _, swiftModuleMap: _):
            return linking == .dynamic
        case .bundle: return false
        case .packageProduct: return false
        case .target: return false
        case .sdk: return false
        }
    }
```

why not embedding static frameworks?

**Comment by pokryfka** [comment]
I was eager to make the change in the filter but after 2nd though, I think the parser needs to be fixed:

specifically in 

 `PrecompiledMetadataProvider` in `readMetadatasFromFatHeader` fails to parse the header via `readMetadataFromMachHeaderIfAvailable` and assumes `BinaryLinking.static`

```swift
            binary.seek(to: UInt64(fatArch.offset))
            if let value = try readMetadataFromMachHeaderIfAvailable(binary: binary) {
                binary.seek(to: currentOffset)
                return value
            } else {
                binary.seek(to: currentOffset)

                guard let architecture = readBinaryArchitecture(cputype: fatArch.cputype, cpusubtype: fatArch.cpusubtype) else {
                    throw PrecompiledMetadataProviderError.architecturesNotFound(binaryPath)
                }

                return (architecture, .static, nil)
            }
```

**Comment by kwridan** [comment]
Hi @pokryfka 

Thanks for raising this. 

To my knowledge, static products don't need to be embedded in the application, it's typically only dynamic ones that do. Static product symbols are linked into the final binary (e.g. the application binary) whereas dynamic product symbols are only referenced and require a lookup at runtime as such they are embedded.

This logic has been applied to regular targets, pre-complied libraries and frameworks. 

Are there perhaps cases where this doesn't apply or isn't correct that we may have missed?

**Comment by pokryfka** [comment]
for reference:

fat header of `AWSAppSync` (recognized by Tuist parser correctly):

```
otool -f AWSAppSync

Fat headers
fat_magic 0xcafebabe
nfat_arch 3
architecture 0
    cputype 16777223
    cpusubtype 3
    capabilities 0x0
    offset 16384
    size 3616800
    align 2^14 (16384)
architecture 1
    cputype 7
    cpusubtype 3
    capabilities 0x0
    offset 3637248
    size 3579104
    align 2^14 (16384)
architecture 2
    cputype 16777228
    cpusubtype 0
    capabilities 0x0
    offset 7225344
    size 3607248
    align 2^14 (16384)
```

fat header of `FirebaseAnalytics` (NOT recognized by Tuist parser correctly):

```
otool -f FirebaseAnalytics

Fat headers
fat_magic 0xcafebabe
nfat_arch 3
architecture 0
    cputype 7
    cpusubtype 3
    capabilities 0x0
    offset 68
    size 101992
    align 2^2 (4)
architecture 1
    cputype 16777223
    cpusubtype 3
    capabilities 0x0
    offset 102064
    size 106656
    align 2^3 (8)
architecture 2
    cputype 16777228
    cpusubtype 0
    capabilities 0x0
    offset 208720
    size 129816
    align 2^3 (8)
Archive : FirebaseAnalytics (architecture i386)
Archive : FirebaseAnalytics (architecture x86_64)
Archive : FirebaseAnalytics (architecture arm64)
```

**Comment by pokryfka** [comment]
> Hi @pokryfka
> 
> Thanks for raising this.
> 
> To my knowledge, static products don't need to be embedded in the application, it's typically only dynamic ones that do. Static product symbols are linked into the final binary (e.g. the application binary) whereas dynamic product symbols are only referenced and require a lookup at runtime as such they are embedded.
> 
> This logic has been applied to regular targets, pre-complied libraries and frameworks.
> 
> Are there perhaps cases where this doesn't apply or isn't correct that we may have missed?

I closed PR I made, trying to investigate it further.

I did check that the libraries provided by Firebase are static.

The frameworks (even though then contain static libraries) need to be embedded, otherwise the app crashes when trying to import them.

**Comment by pokryfka** [comment]
Actually this still does not work properly - its half the fix:
while the frameworks are embedded the are not linked.
(Adding them manually in `Build Phase` > `Link Binary With Libraries` fixes that.)

**Comment by adellibovi** [comment]
Worth mentioning, installing Firebase via Carthage is defined as experimental, as in Firebase's Github: https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md

> This page introduces and provides instructions for an experimental Firebase [Carthage](https://github.com/Carthage/Carthage) distribution. Based on feedback and usage, the Firebase team may decide to [make the Carthage distribution official](https://github.com/firebase/firebase-ios-sdk/issues/1862).

cc: @kwridan

**Comment by adellibovi** [comment]
@pokryfka I would suggest closing this issue, it seems that official Carthage support for Firebase will never become a reality, and they suggest using SPM instead. If you have issues with integrating Firebase SPM with tuist, feel free to open another issue. Thanks 🙏 
https://github.com/firebase/firebase-ios-sdk/issues/1862#issuecomment-504236884

**Comment by pokryfka** [comment]
> @pokryfka I would suggest closing this issue, it seems that official Carthage support for Firebase will never become a reality, and they suggest using SPM instead. If you have issues with integrating Firebase SPM with tuist, feel free to open another issue. Thanks 🙏
> [firebase/firebase-ios-sdk#1862 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/1862#issuecomment-504236884)

Firebase is just a specific example, in general the problem is caused by xcframework with static libraries.

**Comment by adellibovi** [comment]
@pokryfka can you reproduce a very small demo? I checked the other demo project and it seems to have other issues.
What I would suggest is to try to: have a 1 app + 1 target demo project which links a precompiled "easy" xcframework with static libraries, and then showing how it fails/crash.

**Comment by pokryfka** [comment]
> @pokryfka can you reproduce a very small demo? I checked the other demo project and it seems to have other issues. What I would suggest is to try to: have a 1 app + 1 target demo project which links a precompiled "easy" xcframework with static libraries, and then showing how it fails/crash.
> 
> Update: it seems like we already have a fixture for this scenario, can you pinpoint what's the issue there? https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_xcframeworks/Frameworks/MyStaticFramework

I will not have time for that in this week, will try to update the demo later

**Comment by adellibovi** [comment]
@pokryfka any update about this?

> > @pokryfka can you reproduce a very small demo? I checked the other demo project and it seems to have other issues. What I would suggest is to try to: have a 1 app + 1 target demo project which links a precompiled "easy" xcframework with static libraries, and then showing how it fails/crash.
> > Update: it seems like we already have a fixture for this scenario, can you pinpoint what's the issue there? https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_xcframeworks/Frameworks/MyStaticFramework
> 
> I will not have time for that in this week, will try to update the demo later

**Comment by pokryfka** [comment]
> @pokryfka any update about this?
> 
> > > @pokryfka can you reproduce a very small demo? I checked the other demo project and it seems to have other issues. What I would suggest is to try to: have a 1 app + 1 target demo project which links a precompiled "easy" xcframework with static libraries, and then showing how it fails/crash.
> > > Update: it seems like we already have a fixture for this scenario, can you pinpoint what's the issue there? https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_xcframeworks/Frameworks/MyStaticFramework
> > 
> > 
> > I will not have time for that in this week, will try to update the demo later

I am sorry for the wait, been a bit busy.

I did test the the project generated from`ios_app_with_xcframeworks` and it does work.

My scenario is a bit different:

I have Framework which contains all the "live" dependencies (which I dont use at all in my app with mocked environment) including `AppSync` and `Firebase Dynamic Links`.

Then "live" app targets depend on that framework while other builds (with mocked environments) do not.

It all works well for xcframeworks with dynamic libraries (like `AppSync`) but fails for xcframeworks with static libs (like `Firebase`).

I can reproduce that by modifying the fixture to make the app depend on `FrameworkA` which depends on (external) xcframeworks with static libs.

In order to fix the project generated by Tuist I need to manually add the libs to "Link with libraries" in Build Phases.

---

now, its a bit disappointing and made me stop generating project with Tuist.

however I am not sure how much its a limitation of xcframeworks + static libs.
I noticed a comment in https://firebaseopensource.com/projects/firebase/firebase-ios-sdk/carthage/#static_frameworks

> Note that the Firebase frameworks in the distribution include static libraries. While it is fine to link these into apps, it will generally not work to depend on them from wrapper dynamic frameworks.

this is exactly my use case, although "generally not work" is not very specific ...

**Comment by pokryfka** [comment]
I think I fixed that in my very own use case by restructuring the project so that the the xcframeworks with static libraries are only added as dependency in app targets.

**Comment by adellibovi** [comment]
> > Note that the Firebase frameworks in the distribution include static libraries. While it is fine to link these into apps, it will generally not work to depend on them from wrapper dynamic frameworks.

Closing the issue then. Thanks @pokryfka

**Comment by pokryfka** [comment]
> > > Note that the Firebase frameworks in the distribution include static libraries. While it is fine to link these into apps, it will generally not work to depend on them from wrapper dynamic frameworks.
> 
> Closing the issue then. Thanks @pokryfka

Ok, thank you for prompt update.

Note that this could actually be fixed/implemented to handle such scenarios (dependency on framework which depends on xcframeworks with static libs).
Not a blocker for me personally anymore. 
And seems not to be a popular scenario anyway.
