### ISSUE TITLE
Meta-Tuist build test failing, not recognized by CI

### ISSUE THREAD

**Issue by ezraberch** [tuist/tuist#3623]
Currently, the Meta-Tuist build test is failing with the following error:

```
`ArgumentParser` is not a valid configured external dependency
```

There are two separate issues here:
1. `./fourier build tuist all` is failing. I am not sure if this is intended behavior; is it supposed to succeed without running `generate` first?
2. The CI is not properly recognizing the failure as such, so the test seems to be passing.

**Comment by fortmarek** [comment]
> ./fourier build tuist all is failing. I am not sure if this is intended behavior; is it supposed to succeed without running generate first?

Yes, it should, it runs `build` with `--generate` option [here](https://github.com/tuist/tuist/blob/main/projects/fourier/lib/fourier/services/build/tuist/all.rb#L9). If it's not, there's an issue somewhere else. I also think we might want to stop building everything with Xcode 12.5.1 but rather go with some version of Xcode 13.

> The CI is not properly recognizing the failure as such, so the test seems to be passing.

That is weird, is that an issue of the pipeline or does the command `./fourier build tuist all` return 0 exit code itself?

**Comment by ezraberch** [comment]
`./fourier build tuist all` does the following:

```
swift build
.build/debug/tuist build --generate
```

`./fourier generate tuist` does the following:

```
swift build
.build/debug/tuist dependencies fetch
swift build
.build/debug/tuist generate
```

So `./fourier build tuist all` is failing to fetch dependencies first, which is causing the build to fail. Or is `tuist build` supposed to run `fetch` automatically?

> That is weird, is that an issue of the pipeline or does the command ./fourier build tuist all return 0 exit code itself?

`fourier` is returing 0. `tuist` is properly returning 1, so the issue is `fourier` failing to propagate the error.

**Comment by fortmarek** [comment]
> So ./fourier build tuist all is failing to fetch dependencies first, which is causing the build to fail. Or is tuist build supposed to run fetch automatically?

Oh, good catch, yes, that is absolutely what is missing! Could you add this one?

> fourier is returning 0. tuist is properly returning 1, so the issue is fourier failing to propagate the error.

Oh, interesting, that should not be the case. @pepibumur do you have an idea what could be wrong?
