### ISSUE TITLE
[Dependencies.swift][SPM] FirebaseCrashlytics fails with: Expected a platform name here

### ISSUE THREAD

**Issue by ammerzon** [tuist/tuist#3638]
**Describe the bug**
I added `https://github.com/firebase/firebase-ios-sdk` as dependency and manually set the `-ObjC` linker flag.

<details>
  <summary>Dependencies.swift</summary>

```swift
import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: .init(
        [
            .package(url: "https://github.com/firebase/firebase-ios-sdk", .upToNextMajor(from: "8.9.0"))
        ],
        deploymentTargets: [
            .iOS(targetVersion: "13.0", devices: [.iphone, .ipad])
        ]
    ),
    platforms: [.iOS]
)
```
</details>

<details>
  <summary>Project.swift</summary>

```swift
let project = Project.app(name: "TuistFirebase",
                          platform: .iOS,
                          dependencies: [
                            .external(name: "FirebaseCrashlytics")
                          ],
                          additionalTargets: ["TuistFirebaseKit", "TuistFirebaseUI"])
```
</details>

Nevertheless, I still got the following error message if `FirebaseCrashlytics` is added:

<img width="1097" alt="CleanShot 2021-11-05 at 11 18 27@2x" src="https://user-images.githubusercontent.com/7319168/140495548-59dd227c-011d-4b58-88d8-1d98d19c5496.png">

When I add the dependency manually over SPM, this error does not occur. Therefore, I think it has something to do with Tuist.

**To Reproduce**

1. Add `firebase-ios-sdk` as dependency
2. Run `tuist bundle`
3. Run `tuist dependencies fetch`
4. Run `tuist generate --open`
5. Open the workspace and add the `-ObjC` linker flag in the build settings
5.  Start a build

**Expected behavior**
The build should not fail.

**Desktop (please complete the following information):**

- OS: macOS
- Version: 11.6

**Additional context**

[TuistFirebase.zip](https://github.com/tuist/tuist/files/7482348/TuistFirebase.zip)

**Comment by pokryfka** [comment]
related https://github.com/tuist/tuist/issues/3621

**Comment by mihaicris-adoreme** [comment]
https://github.com/firebase/firebase-ios-sdk/issues/8990

**Comment by integer256** [comment]
We have the same issue

**Comment by mgray88** [comment]
This issue appeared for me out of nowhere. I've had Firebase successfully integrated using Dependencies.swift until today. It seems attempting to add a new dependency causes something to happen with SPM in Tuist

**Comment by mgray88** [comment]
Narrowing it down further, it seems Dependencies.swift updated a bunch of dependencies behind my back, one of them notably `firebase-ios-sdk`. I noticed my Package.resolved had a change from 8.6.1 to 8.10.0 for that package, as well as updates for its dependencies

**Comment by danyf90** [comment]
It's a bug of SPM which is not able to follow its own Package.resolved file sometime.

I'll link the issue report as soon as I find it

**Comment by danyf90** [comment]
Here is the [link to the issue](https://bugs.swift.org/browse/SR-14647)

**Comment by nhaarman** [comment]
Is there a workaround available?

**Comment by Banck** [comment]
Hello. 
Is any news here? The same issue when use Dependencies.swift

**Comment by luispadron** [comment]
Hey all, this isn't something we can fix if its a problem with SPM. Please follow the linked issue for more details.

You should also report your feedback there if you would like to see it prioritized.

**Comment by Banck** [comment]
So for now the old way to add spm packages is deprecated, but it doesn’t build with Dependencies.swift with Firebase Crashlytics. So sad 😞
