### ISSUE TITLE
Lint/format code using SwiftFormat (feature request)

### ISSUE THREAD

**Issue by pokryfka** [tuist/tuist#3642]
Tuist already supports linting using [SwiftLint](https://github.com/realm/SwiftLint).

Please consider adding [SwiftFormat](https://github.com/nicklockwood/SwiftFormat) as an alternative.

Perhaps a way to do it would be to add an option to an existing `tuist lint code` command, for example:

```
tuist lint code --tool SwiftFormat-0.48.18 
```

and/or to add new command:

```
tuist format code --tool SwiftFormat-0.48.18 
```

It would be convenient to be able to pass arguments to the tool, example:

```
tuist lint code --tool SwiftFormat-0.48.18 -- --dryrun
```

**Comment by fortmarek** [comment]
I think we'll remove `SwiftLint` from our codebase and move in the direction of tasks which are [in progress](https://github.com/tuist/tuist/pull/3492). After that PR is eventually merged, this can be done easily as a task 🙂

**Comment by luispadron** [comment]
Closing this as the solution is to build a custom task / use a post step
