### ISSUE TITLE
Generate Test Plan (feature request)

### ISSUE THREAD

**Issue by pokryfka** [tuist/tuist#3646]
Since version 11 Xcode allows to create Test Plans.

It would be great to be able to generate Test Plans with tests from specified frameworks nad packages.

**Comment by pokryfka** [comment]
I am not sure if there is any official documentation of the format, for reference content of a simple `CI.xctestplan` created in Xcode:

```JSON
{
  "configurations" : [
    {
      "id" : "0FC8D974-8ED8-4870-AA5B-5F7D68852XXX",
      "name" : "Configuration 1",
      "options" : {

      }
    }
  ],
  "defaultOptions" : {
    "testTimeoutsEnabled" : true
  },
  "testTargets" : [
    {
      "target" : {
        "containerPath" : "container:MyApp.xcodeproj",
        "identifier" : "24D9B46BCAB8DD2BC3D85XXX",
        "name" : "AuthUITests"
      }
    },
    {
      "target" : {
        "containerPath" : "container:..\/..\/Packages\/SharedUI\/StyleKit",
        "identifier" : "StyleKitTests",
        "name" : "StyleKitTests"
      }
    }
  ],
  "version" : 1
}
```

**Comment by fortmarek** [comment]
Hi!

Afaict, test plans are [supported](https://docs.tuist.io/manifests/project/#test-action), could you maybe elaborate a little bit what exactly you are missing?

**Comment by pokryfka** [comment]
Hi @fortmarek, thank you for the reference, I missed that.

So, just tested that it is possible to reference existing test plan which needs to be created and edited manually. 

My idea was to be able to generate test plans by `Tuist`, one could list which targets should be included.

With that said the current implementation covers all my needs.
