### ISSUE TITLE
Docc Support

### ISSUE THREAD

**Issue by Mdgrant116** [tuist/tuist#3650]
**Describe the bug**
There is a bug that causes apples new docc documentation catalogue to be turned from a documentation catalogue into a regular folder, which is then unrecognized when you build documentation.

**To Reproduce**

1. In Xcode, create a new file of type documentation catalogue.
2. Run Tuist Generate. 
3. Go back to the documentation catalogue you've just created and see that it is now just a regular folder.

**Expected behavior**
The expected behavior is that after Tuist generates a project, the documentation catalogue should say one, instead of changing into a regular folder. When its a regular folder, Xcode ignores the article files inside.

**Screenshots**
Before Tuist Generate

<img width="146" alt="Screen Shot 2021-11-09 at 10 30 02 AM" src="https://user-images.githubusercontent.com/42280202/140956756-b53e578a-3cf9-4946-922b-44af3b5c1dd4.png">

After

<img width="240" alt="Screen Shot 2021-11-09 at 10 29 14 AM" src="https://user-images.githubusercontent.com/42280202/140956799-e678ee75-39a5-4bd6-8657-81f1f47b8db3.png">

**Desktop (please complete the following information):**

- OS: [Mac OS Big Sur]
- Version [11.3.1]

**Comment by luispadron** [comment]
We use DocC at work and havent noticed this issue. Could you provide more info about where you are putting the docc catalog and what your project settings look like?

**Comment by Mdgrant116** [comment]
Hey! Glad to hear, must just be something in my configuration! 

In the project I have a folder called resources. In that folder is where the image asset catalogue, the custom fonts, and the docc archive lives.

In my project file in the module section it looks like this.

`.module(
            name: "Example",
            infoPlistPath: "Sources/Example/Info.plist",
            sources: ["Sources/Example/**"],
            resources: [
                "Resources/**",
            ]
        ),`

Im not very familiar with Tuist, just learning the ropes. If this isn't enough detail and there's more information I can provide to make the problem more clear, let me know! Where are you putting your docc archive?

**Comment by luispadron** [comment]
> In the project I have a folder called resources. In that folder is where the image asset catalogue, the custom fonts, and the docc archive lives.

This seems like the issue to me, you should only put things in the `Resources` folder that should be bundled with your app! In this case you are essentially including the DocC catalog as a resource in your app which seems incorrect.

Our setup looks like this:

```
.
├── Derived
├── Package.swift
├── Project.swift
├── README.md
├── Sources
│   ├── <ModuleName>
│   │   ├── ...
│   │   ├── CompassNetworking.docc
```

Then in the `Package.swift` (if you are using that) you can exclude the DocC module:

```swift
        .target(
            name: "<ModuleName>",
            exclude: ["<ModuleName>.docc"]
        ),
```

**Comment by Mdgrant116** [comment]
Ok I'll be trying this out today. Thanks for the explanation, will report the results back!

**Comment by pokryfka** [comment]
@luispadron do you also have Xcode frameworks with docs documentation?

My problem is that `tuist generates` does not add documentation to the Xcode project
