### ISSUE TITLE
FR: Add support with apple store connect

### ISSUE THREAD

**Issue by jesus-qt** [tuist/tuist#3651]
**Describe the bug**
I want to download, recreate, and delete provisioning profiles with a tuist command

**To Reproduce**
I can't

**Expected behavior**
Be able to do it.

**Additional context**
It will awesome if Tuist integrate this sdk: `https://github.com/AvdLee/appstoreconnect-swift-sdk`
Also if it's possible add 2fa method to do download, recreate, and delete provisioning profiles instead of App Store connect key.

**Comment by danyf90** [comment]
I think you will be able to implement this using the new Task @fortmarek is implementing, right?

**Comment by fortmarek** [comment]
Yes, this should be possible with tasks. I will close this for now as either way, we don't plan to implement this in the tuist core repository.

However, this is still a good idea and I'd love to see this as a plugin! Thanks a lot for the suggestion @jesus-qt

**Comment by jesus-qt** [comment]
Hey there:
@fortmarek, @danyf90

What about that? Tuist support that https://docs.tuist.io/commands/signing/
I think that it should be inside of the Tuists core because of the signing code

**Comment by unxavi** [comment]
hey @fortmarek  I think being able to sign apps with Tuist is part of the core of Tuist, no? At least my company is using Tuist to sign the apps. But it feels incomplete that we have to manually download the provision profile every time that something change or a device UUID is added for example. 

Tuist already implement de encrypt/decript of the certificates, handle the manual sigining, why not the certificates and provision profile generation? I'm not sure if with the sdk that @jesus-qt  comments, but from the docs I also though it was something planned

**Comment by jesus-qt** [comment]
I'm totally agree with @unxavi, In my organisation we're planning to swap from fastlane to tuist in terms of signing the apps, but the manually re-generation of provisioning profiles it is a stopper for use it, we're not going to do if the core tool not support it fully. Using that SDK could be a boost for your project and community. How both commented, in this "Signing vendor #1426", you're looking for a way to do that with a command called "vendor". So why not integrate this community supported sdk by the moment to boost your project and make to grow the community?
