### ISSUE TITLE
Manifests.xcodeproj is not portable due to hardcoded paths in pbxproj

### ISSUE THREAD

**Issue by hisaac** [tuist/tuist#3657]
## Describe the bug

When generating an Xcode project for the Tuist manifests using `tuist edit --permanent`, the generated Xcode project contains some hardcoded paths based on the machine the project was originally generated on.

Example:

```xml
FRAMEWORK_SEARCH_PATHS = (
	"\"/Users/isaachalvorson/.tuist/Versions/2.1.1\"",
	"\"/Users/isaachalvorson/.tuist/Versions\"",
);
```

When trying to build/run the Manifests project on another person's machine, Xcode will throw errors because it cannot resolve that path.

Changing these paths to instead use `$HOME` in place of the hardcoded home directory paths fixes the issue.

## To Reproduce

1. Run `tuist edit --permanent`.
2. Open the `Manifests.xcodeproj/project.pbxproj` in a text editor.
3. Notice that there are some file paths hardcoded to point to the `tuist` binary installed on your machine.
4. Optionally, move the project to another machine and verify that the project does not build.

## Expected behavior

I expected the generated Xcode project to be portable, and work on other machines.

## Environment

- macOS version: 12.0.1
- Tuist version: 2.1.1

**Comment by danyf90** [comment]
I agree that would be an easy fix, but could you explain why you need to do that?

**Comment by hisaac** [comment]
Why you would need the manifests project to be portable? In my specific case, I've added a SwiftLint build phase to the Xcode project, so I'm checking it into my git repo.

**Comment by danyf90** [comment]
Can't the build phase be configured in tuist so it's generated by tuist?

**Comment by hisaac** [comment]
I don't think you can currently customize the Xcode project that's created when running `tuist edit permanent`. Is there a way to configure it that I'm unaware of?

**Comment by danyf90** [comment]
Oh I get it now, I had missed the `--permanent` part, sorry 🙏 

I think you can go ahead with the changes, then! 🙌

**Comment by hisaac** [comment]
No worries! I thought maybe we were misunderstanding each other there 😅

**Comment by hisaac** [comment]
@danyf90 I'm still pretty new to the tuist codebase. Any tips on where I should start looking to address this? I'm currently looking at [the `edit(...)` method in `PorjectEditor.swift`](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/ProjectEditor/ProjectEditor.swift#L96), but not sure where to go from there yet.

**Comment by danyf90** [comment]
Not super familiar with that part as well.
Trying to look around it might be the `ProjectEditorMapper.targetBaseSettings`, but surely @pepibumur or @fortmarek know better.

The problem is that there I don't think you can assume you are in some subfolder of the home 🤔

**Comment by luispadron** [comment]
@hisaac Hey! Let me know if you need help here, you are definitely on the right track with that file. You can take a look at: https://github.com/tuist/tuist/blob/main/Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift also as this performs most of the work to build the project.

**Comment by hisaac** [comment]
Thanks @luispadron. I'll look around in there and let you know if I need some help. 🙏

**Comment by pepibumur** [comment]
> In my specific case, I've added a SwiftLint build phase to the Xcode project, so I'm checking it into my git repo.

Am I right assuming that what you are trying to do is to lint your manifest files through the generated manifest project? If that's the case, I suggest taking a different approach. Even though `swiftlint` suggests being integrated through a build phase, you can also run it outside of an Xcode project. You can do:

```
swiftlint lint --path path/to/Project.swift
```

I'd advise not to use `--permanent` because the generated project will always have a dependency on Tuist. Even if we use $HOME, the dependency with an environment state remains. Because we encourage users to do that, we should figure out how to break that dependency.

**Comment by hisaac** [comment]
> Am I right assuming that what you are trying to do is to lint your manifest files through the generated manifest project?

Yes, that's my use case. We are also linting via the command line for our CI, but I find it much nicer to fix issues when the errors appear in Xcode.

> I'd advise not to use `--permanent` because the generated project will always have a dependency on Tuist. Even if we use $HOME, the dependency with an environment state remains. Because we encourage users to do that, we should figure out how to break that dependency.

I agree that removing that dependency would be ideal. Until then though, this change would be a nice one. I think it's reasonable to assume that any developer opening that project is going to have Tuist installed, and by default it would be installed in their home directory, right? I guess I don't know that part for sure, but at least in our environment that will be the case.

**Comment by hisaac** [comment]
I see now that there are some paths in the generated `Manifests.xcscheme` that are going to be harder to fix than just modifying some strings. These are `AbsolutePaths`, and when I try to initialize one with `$HOME/...`, I get and error from the `swift-tools-support-core` library, saying:

```
TSCBasic/Path.swift:556: Precondition failed: Failure normalizing $HOME/Library/Developer/Xcode/DerivedData/tuist-dnbjyhrjidhdaycltqmoulqiivhv/Build/Products/Debug/tuist, absolute paths should start with '/'
```

I also tried using `/$HOME/...`, but that leading `/` broke things (which wasn't that surprising).

I'll keep thinking about it, but I feel that addressing those absolute paths would require some fundamental changes to how projects are generated, and that's well beyond the scope of this issue.

Perhaps a better route would be to add the ability to add build phases to the Manifests project somehow. https://github.com/tuist/tuist/discussions/3655

**Comment by hisaac** [comment]
So the xcscheme has a hardcoded path to the tuist binary

```xml
<PathRunnable
   FilePath = "/Users/isaachalvorson/.tuist/Versions/2.1.1/tuist"
   runnableDebuggingMode = "0">
</PathRunnable>
```

That `FilePath` argument can't handle relative paths, not even ones Xcode provides like `$(SRCROOT)`. If you specify one there, Xcode crashes on launch.

I'll close this for now, as I'm not sure there's a reasonable way around this during project generation at the moment.
