### ISSUE TITLE
Unable to run tuist test command for testing my Test Scheme

### ISSUE THREAD

**Issue by SamarthKejriwal** [tuist/tuist#3668]
**Describe the bug**
tuist test command is failing. I am using SPM as the dependency manager in my project

**To Reproduce**

1. Generate a project via tuist generate
2. Run tests via `tuist test MyAppTests  --device "iPhone 12" --os 15.0`
3. See the error:

```
Generating project for testing
Generating workspace MyApp.xcworkspace
Generating project MyApp
Resolving package dependencies using xcodebuild
Testing scheme MyAppTests
Testing failed:
	Command PhaseScriptExecution failed with a nonzero exit code
	Testing cancelled because the build failed.

** TEST FAILED **

The following build commands failed:
	PhaseScriptExecution InstallReactorTemplates /Users/samarthkejriwal/Library/Developer/Xcode/DerivedData/MyApp-fajtiphchnlphxbdjkefcafnryhx/Build/Intermediates.noindex/MyApp.build/MyApp-Debug-Prod-iphonesimulator/MyApp.build/Script-44D0BAEB25ECD52B0503BA74.sh (in target 'MyApp' from project 'MyApp')
(1 failure)

The 'xcodebuild' command exited with error code 65
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

**Expected behavior**
Test scheme should run and give me the desired output

**Desktop:**

- OS: macOS 11.3.1
- Version 1.48.1
- Xcode Version 13.0

**Comment by fortmarek** [comment]
Hey @SamarthKejriwal!

It is hard to tell without having a reproducible project and/or knowing what's inside the `InstallReactorTemplates` script.

However, my guess is that the script relies on the `SRCROOT` or absolute path but `tuist test` generates a project into a custom directory, so those assumptions fail.

If you could at least post the contents of the script, it'd make it much easier to provide more constructive help.

**Comment by SamarthKejriwal** [comment]
@fortmarek yaa there are some absolute paths in my script, that was causing the issue.
removing the `Target Actions` from the `Project.swift` file resolved my issue because now the absolute paths scripts wont be a part of the project.

**Comment by fortmarek** [comment]
Thanks for getting back, I'll close this then.

**Comment by SamarthKejriwal** [comment]
@fortmarek Hey I have some scripts that are needed in order to run the app. So If I don't run those scripts, then my test target doesn't run the tests, and eventually, it crashes the app during testing.  

Here is the content of my script - 

`# Name of the resource we're selectively copying
GOOGLESERVICE_INFO_PLIST=GoogleService-Info.plist

# Get references to dev and prod versions of the GoogleService-Info.plist
# NOTE: These should only live on the file system and should NOT be part of the target (since we'll be adding them to the target manually)
GOOGLESERVICE_INFO_DEV=${PROJECT_DIR}/Firebase/Dev/${GOOGLESERVICE_INFO_PLIST}
GOOGLESERVICE_INFO_PROD=${PROJECT_DIR}/Firebase/Prod/${GOOGLESERVICE_INFO_PLIST}

# Make sure the dev version of GoogleService-Info.plist exists
echo "Looking for ${GOOGLESERVICE_INFO_PLIST} in ${GOOGLESERVICE_INFO_DEV}"
if [ ! -f $GOOGLESERVICE_INFO_DEV ]
then
    echo "No Development GoogleService-Info.plist found. Please ensure it's in the proper directory."
    exit 1
fi

# Make sure the prod version of GoogleService-Info.plist exists
echo "Looking for ${GOOGLESERVICE_INFO_PLIST} in ${GOOGLESERVICE_INFO_PROD}"
if [ ! -f $GOOGLESERVICE_INFO_PROD ]
then
    echo "No Production GoogleService-Info.plist found. Please ensure it's in the proper directory."
    exit 1
fi

# Get a reference to the destination location for the GoogleService-Info.plist
PLIST_DESTINATION=${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app
echo "Will copy ${GOOGLESERVICE_INFO_PLIST} to final destination: ${PLIST_DESTINATION}"

# Copy over the prod GoogleService-Info.plist for Release builds
if [ "${CONFIGURATION}" == "MyApp-Debug-Staging" ]
then
    echo "Will use debug plist file"
    echo "Using ${GOOGLESERVICE_INFO_DEV}"
    cp "${GOOGLESERVICE_INFO_DEV}" "${PLIST_DESTINATION}"
else
    echo "Will use release plist file"
    echo "Using ${GOOGLESERVICE_INFO_PROD}"
    cp "${GOOGLESERVICE_INFO_PROD}" "${PLIST_DESTINATION}"
fi
`

Can you please provide a constructive solution for this ?

**Comment by fortmarek** [comment]
Hey @SamarthKejriwal - could you open a [new discussion](https://github.com/tuist/tuist/discussions/new) for this instead of reusing this issue for a different topic? I can try to help you there. If you could try to describe in more detail what you are trying to achieve and what does not work, that'd be appreciated!
