### ISSUE TITLE
Headers build phase in application targets

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#367]
**Describe the bug**
Generating a project with an application target that contains headers results in the target having a headers build phase. By default in Xcode iOS application targets don't contain this build phase.

**To Reproduce**

1. Go to `fixtures/ios_app_with_tests`
2. Add an objective-c file & header to Sources
3. Add a bridging header to Sources (to import all the other headers)
4. Modify the Project manifest to:

```swift
let project = Project(name: "App",
                      targets: [
                          Target(name: "App",
                                 platform: .iOS,
                                 product: .app,
                                 bundleId: "io.tuist.App",
                                 infoPlist: "Info.plist",
                                 sources: "Sources/**",
                                 headers: Headers(project: "Sources/**"),
                                 dependencies: [],
                                 settings: Settings(base: [
                                     "SWIFT_OBJC_BRIDGING_HEADER": "Sources/Bridging-Header.h",
                                ])),
// ...
```

5. run `tuist generate`
6. Inspect the generated project

**Expected behavior**
A header phase to not be created for iOS application targets

**Screenshots**

<img width="849" alt="Screen Shot 2019-05-24 at 4 03 43 PM" src="https://user-images.githubusercontent.com/11914919/58337394-95a16d00-7e3d-11e9-8e9f-d191deaafa09.png">

**Desktop (please complete the following information):**

- Tuist master (2ccddada87c30ec48e9b587e9e7c66e0d7679ae5)

**Additional context**
Xcode seems to not mind the headers build phase, but for consistency perhaps it may be worth not including for iOS application targets?

**Comment by pepibumur** [comment]
Ouch, that's a good one 😅

**Comment by rowwingman** [comment]
What if we will add exclude rule. So it will be like this:
```
headers: Headers(public: Path("Sources/**", exclude:["Sources/Bridging-Header.h"]),
                                 project: "Sources/Bridging-Header.h"),
```

**Comment by kwridan** [comment]
I believe an `exclude` rule will be useful in its own right - the question what that should do - exclude completely (not even as a fileReference) or excluded from header visibility attributes but included in the Xcode Project? I can see use cases for both. I've create #705 to help us discuss this further and added a few more ideas.

This particular issue is for the case you have an Application target with headers, typically it doesn't have a headers build phase in Xcode, we should be able to omit that build phase based on the target product type.

**Comment by pepibumur** [comment]
> This particular issue is for the case you have an Application target with headers, typically it doesn't have a headers build phase in Xcode, we should be able to omit that build phase based on the target product type.

Agree. I don't think we need to extend the API here, just generate the project with the right configuration.

**Comment by eito** [comment]
🤚  I have started working on this issue.

**Comment by eito** [comment]
From the description it sounds like this should only be for iOS only, but wouldn't it be for _any_ app product?
