### ISSUE TITLE
Unable to Build EarlGrey dependency using Dependencies.swift

### ISSUE THREAD

**Issue by hisaac** [tuist/tuist#3713]
## Description

I'm trying to use Google's [EarlGrey](https://github.com/google/EarlGrey) UI testing library in my Tuist project using `Dependencies.swift`, but am running into issues during the dependency build phase.

EarlGrey does not support Swift Package Manager right now, so I'm using Carthage to try to import it.

Here is what it's entry looks like in my `Dependencies.swift` file:

```swift
.github(
    path: "google/EarlGrey",
    requirement: .exact("2.2.1")
),
```

Here is the error I get in the terminal when I try to run `tuist dependencies fetch`:

```
❯ tuist dependencies fetch
Using version 2.2.1 defined at /Users/isaachalvorson/Developer/target/ios/.tuist-version
Resolving and fetching dependencies.
The integration of external dependencies is in alpha. Be aware some APIs might change as we iterate the functionality with the feedback we get from users.
Installing Carthage dependencies.
*** No Cartfile.resolved found, updating dependencies
*** Fetching EarlGrey
*** Checking out EarlGrey at "2.2.1"
*** No cache found for EarlGrey, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/_k/lyv4n48j2ybggf7ql767qmw40000gr/T/carthage-xcodebuild.12HcfE.log
*** Building scheme "AppFramework" in EarlGrey.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/isaachalvorson/Developer/target/ios/Tuist/Dependencies/Carthage/Checkouts/EarlGrey/EarlGrey.xcodeproj -scheme AppFramework -configuration Release -derivedDataPath /Users/isaachalvorson/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2_13C5081f/EarlGrey/2.2.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/_k/lyv4n48j2ybggf7ql767qmw40000gr/T/EarlGrey SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/isaachalvorson/Developer/target/ios/Tuist/Dependencies/Carthage/Checkouts/EarlGrey)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_k/lyv4n48j2ybggf7ql767qmw40000gr/T/carthage-xcodebuild.12HcfE.log
The 'carthage' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

## Steps to Reproduce

1. Add the EarlGrey library to a `Dependencies.swift` file like I've done above.
2. Run `tuist dependencies fetch`
3. Observe the build error that results

## Expected Results

I expected the library to be built successfully like others are.

## Environment

- macOS version: 12.0.1
- Tuist version: 2.2.1

**Comment by fortmarek** [comment]
For Carthage, we are using `--use-xcframeworks` flag - I wonder if this could be the issue. Could you try installing `EarlGrey` with `carthage` directly - with and without this flag?

**Comment by hisaac** [comment]
It appears that this may actually be an issue outside of Tuist. I just tried what you recommended @fortmarek, and the same issue occurs.

Apologies for not trying this originally. I assumed EarlGrey would've installed regularly, but apparently not. I'll pursue other avenues for trying to sort this out.
