### ISSUE TITLE
SPM packages with binary targets where the library name does not match the framework name cause errors 

### ISSUE THREAD

**Issue by wattson12** [tuist/tuist#3718]
**Describe the bug**

`tuist` currently assumes that the library name of an xcframework will match its xcframework name. In the `Braze` library [here](https://github.com/braze-inc/braze-ios-sdk) there is a binary target `AppboyPushStoryFramework`, when downloaded this library has the path 
```
AppboyPushStoryFramework.xcframework/ios-arm64_x86_64-maccatalyst/AppboyPushStory.framework/AppboyPushStory
```

Note the variation between `AppboyPushStoryFramework.xcframework` and  `AppboyPushStory.framework/AppboyPushStory` which is also reflected in the `Info.plist` of the xcframework:

```
<key>LibraryPath</key>
<string>AppboyPushStory.framework</string>
```

When generating a target with this dependency `tuist` gives an error 

```
AppboyPushStoryFramework.xcframework is missing architecture ios-arm64_x86_64-maccatalyst/AppboyPushStory.framework/AppboyPushStoryFramework defined in the Info.plist
AppboyPushStoryFramework.xcframework is missing architecture ios-arm64_i386_x86_64-simulator/AppboyPushStory.framework/AppboyPushStoryFramework defined in the Info.plist
AppboyPushStoryFramework.xcframework is missing architecture ios-arm64_armv7/AppboyPushStory.framework/AppboyPushStoryFramework defined in the Info.plist
Couldn't find any supported architecture references at /Users/samwatts/temp/tuist-update-test/Tuist/Dependencies/SwiftPackageManager/.build/artifacts/Appboy_iOS_SDK/AppboyPushStoryFramework.xcframework. It's possible that the .xcframework was not generated properly or that it got corrupted. Please, double check with the author of the framework.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

**To Reproduce**

1. Open the attached sample project
2. Run `tuist dependencies fetch && tuist generate`
3. See error

[braze.zip](https://github.com/tuist/tuist/files/7589434/braze.zip)

**Expected behavior**

The project should be generated with the `.xcframework` correctly linked

**Screenshots**

n/a

**Desktop (please complete the following information):**

- OS: `macOS 11.6`
- Tuist Version: `2.3.0`

**Additional context**

Looking at the code I _think_ this could be fixed with the following code but haven't had a chance to test this on any other packages. The change here is `library.path.basenameWithoutExt` instead of `xcframeworkPath.basenameWithoutExt` for the binary name

```
diff --git c/Sources/TuistCore/MetadataProviders/XCFrameworkMetadataProvider.swift w/Sources/TuistCore/MetadataProviders/XCFrameworkMetadataProvider.swift
index 463cff9dd..1cb6d70f3 100644
--- c/Sources/TuistCore/MetadataProviders/XCFrameworkMetadataProvider.swift
+++ w/Sources/TuistCore/MetadataProviders/XCFrameworkMetadataProvider.swift
@@ -89,11 +89,12 @@ public final class XCFrameworkMetadataProvider: PrecompiledMetadataProvider, XCF

     public func binaryPath(xcframeworkPath: AbsolutePath, libraries: [XCFrameworkInfoPlist.Library]) throws -> AbsolutePath {
         let archs: [BinaryArchitecture] = [.arm64, .x8664]
-        let binaryName = xcframeworkPath.basenameWithoutExt

         guard let library = libraries.first(where: {
             let hasValidArchitectures = !$0.architectures.filter(archs.contains).isEmpty
-            guard hasValidArchitectures, let binaryPath = try? path(for: $0, binaryName: binaryName, xcframeworkPath: xcframeworkPath) else {
+            guard hasValidArchitectures,
+                let binaryPath = try? path(for: $0, binaryName: $0.path.basenameWithoutExt, xcframeworkPath: xcframeworkPath)
+            else {
                 return false
             }
             guard FileHandler.shared.exists(binaryPath) else {
@@ -107,7 +108,7 @@ public final class XCFrameworkMetadataProvider: PrecompiledMetadataProvider, XCF
             throw XCFrameworkMetadataProviderError.supportedArchitectureReferencesNotFound(xcframeworkPath)
         }

-        return try path(for: library, binaryName: binaryName, xcframeworkPath: xcframeworkPath)
+        return try path(for: library, binaryName: library.path.basenameWithoutExt, xcframeworkPath: xcframeworkPath)
     }

     private func path(for library: XCFrameworkInfoPlist.Library, binaryName: String, xcframeworkPath: AbsolutePath) throws -> AbsolutePath {
```

**Comment by danyf90** [comment]
Looks good to me, could you open a PR so that the CI would run on the current test cases? Also, I would add this dependency in the `app_with_spm_dependencies` fixture so we keep testing it in the future.

**Comment by wattson12** [comment]
> Looks good to me, could you open a PR so that the CI would run on the current test cases? 

Done https://github.com/tuist/tuist/pull/3721

> Also, I would add this dependency in the `app_with_spm_dependencies` fixture so we keep testing it in the future.

👍 makes sense

**Comment by mikchmie** [comment]
@wattson12 Could you test if this issue has been resolved by https://github.com/tuist/tuist/pull/4078 ? After that change Tuist should use the absolute path generated by SPM to reference binary artifacts.
