### ISSUE TITLE
Adding framework and bundle file from the framework results in "couldn't find a reference" error

### ISSUE THREAD

**Issue by GermanVelibekovHouzz** [tuist/tuist#3730]
**Describe the bug**
When adding a bundle resource to a Target located inside the framework  (`.framework` folder) together with the framework itself, the following error occurs
```
Couldn't find a reference for the file at path <root-proj>/frameworks/GooglePlaces.framework.
```

Here's an example where such behavior is required:
https://developers.google.com/maps/documentation/places/ios-sdk/start#install-manually

**To Reproduce**

Configure a Target as the following
1. Add framework containing resources to Target (ex. `GooglePlaces.framework`)
2. Add a bundle resource from within the framework (ex `.relativeToRoot(frameworks/GooglePlaces.framework/Resources/GooglePlaces.bundle`)
3. Run `tuist generate`
4. Error is printed in the console

**Expected behavior**
Tuist will generate the project with a Target containing framework in **Frameworks and Libraries** section in Xcode, and a bundle resource placed into **Copy Bundle Resources** section.

**Desktop (please complete the following information):**

- OS: macOS
- Tuist Version: 2.0.2

**Additional context**
If either the framework is added solo (without its bundle resources) or the only bundle resource is added from within the framework, but the framework isn't linked to a target, everything works as expected; in the former case framework is correctly linked to the target and in the latter bundle resource is added into bundle resource of the target.

**Comment by kwridan** [comment]
Thanks for flagging this @GermanVelibekovHouzz 

This is a known limitation (see https://github.com/tuist/tuist/issues/1779 for more details). At the moment the way to resolve this is to create a symlink to the bundle in another path such that doesn't clash with the framework path.

Hope this helps!

**Comment by fortmarek** [comment]
I will close this as a duplicate but thanks for raising this! Since it's not the first time we see this, it might be worth spending some time on this.
