### ISSUE TITLE
Test targets run in parallel?

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#3764]
After #3682 we enabled by default parallel running for tests targets. Unfortunately for unit tests that can be quite a regression, since Xcode would need to clone the simulator, and usually that takes more time than just running unit tests (though it's not the case for UI tests & integration tests which take more time to be executed).
I would suggest adding a way to turn it on or off, also does it make sense to be on as the default option?
cc @fortmarek @danyf90 what you folks think?

**Comment by danyf90** [comment]
I agree and I think it's been implemented [here](https://github.com/tuist/tuist/pull/3755).

If running them in parallel takes more time than non running them in parallel I also agree to revert the default to not being parallel

**Comment by adellibovi** [comment]
Thanks @danyf90! I missed that PR, I will keep this issue open for now and will watch that PR 😄

**Comment by danyf90** [comment]
Feel free to comment there to propose to revert the default to be not parallelizable!
