### ISSUE TITLE
watchOS and XCTest.framework

### ISSUE THREAD

**Issue by orbitekk** [tuist/tuist#3770]
**Describe the bug**
It is not possible to generate a target for watchOS platform when XCTest.framework is linked.

`❌ The SDK XCTest.framework is not currently supported on watchOS.`

**To Reproduce**

1. Create a target:
```
return Target(
  name: "SampleTarget",
  platform: .watchOS,
  product: .framework,
  bundleId: "com.bundleId",
  deploymentTarget: .watchOS(
    targetVersion: "8.0"
  ),
  infoPlist: "Info.plist",
  sources: ["Sources/**"],
  dependencies: [
    .xctest
  ]
)
```
2. run `tuist generate`

**Expected behavior**
Generated project with proper target. As of Xcode 12.5, using XCTest.framework on watchOS is supported.

**Desktop**

- OS: macOS 12.0.1
- Version 2.3.2

**Comment by kwridan** [comment]
Thanks for flagging this @orbitekk 

Indeed `watchOS` now support `XCTest` [as of Xcode 12.5](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes#Testing) 🎉.

We can extend Tuist to support this. 

I believe it's a matter of updating [`Platform.xcodeDeveloperSdkRootPath`](https://github.com/tuist/tuist/blob/main/Sources/TuistGraph/Models/Platform.swift#L111) to return the corresponding path for `watchOS` and adding a sample fixture to verify it all works. Historically it didn't have this directory and this is where the `XCTest` framework resides. 

Happy to guide you through this if you're interested, equally happy to take this on.
