### ISSUE TITLE
[Dependencies.swift][SPM] Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'

### ISSUE THREAD

**Issue by PSKuznetsov** [tuist/tuist#3785]
**Describe the bug**
When using ObjC dependency shipped via SPM you will get "Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'" if there are Bundle Resources 

**To Reproduce**

1. Download test app
[TestApp.zip](https://github.com/tuist/tuist/files/7649475/TestApp.zip)

2. Make tuist dependencies fetch
3. Try to build the project

**Expected behavior**
SWIFTPM_MODULE_BUNDLE will be generated by Xcode for tuist SPM dependencies

macOS 12, Xcode 13.1, tuist 2.3.2

**Comment by danyf90** [comment]
Hello Pavel 👋 

Thanks for reporting this 🙏 

I think we are missing 2 pieces here in order for this to work:
1. as far as I can see, currently we generate bundle accessors only for Swift (cc @pepicrft @fortmarek to confirm)
2. once we generate bundle accessors also for ObjC, we would need to define the SWIFTPM_MODULE_BUNDLE in the PackageInfoMapper logic

For reference, the corresponding SPM logic can be found [here](https://github.com/apple/swift-package-manager/blob/ce959edd3ad914ca256a7f9ea87cf752b8ce4ada/Sources/Build/BuildPlan.swift#L440-L493).

**Comment by fortmarek** [comment]
> as far as I can see, currently we generate bundle accessors only for Swift 

Correct, we don't have such logic for Objc - this would need to be added :(

**Comment by danyf90** [comment]
@PSKuznetsov if you want to try to solve this, we can try to give you some pointers 🙌🙌

**Comment by makleso6** [comment]
Same issue in my project 🙂

**Comment by eukurapov** [comment]
Is there a workaround for this? Except integrating the dependency via SPM directly.
