### ISSUE TITLE
Clarify license of generated code

### ISSUE THREAD

**Issue by RomainBoulay** [tuist/tuist#3786]
Thank you for writing this software and providing it under the MIT license! Can you clarify if projects that include output from tuist should consider those portions of code as being under the same license (and its license condition)? Some projects have statements clarifying this. For example, LLVM has an exception that clarifies that portions of the software that become part of your own software as a result of using LLVM don't need to comply with specific conditions of the license.

I don't think any revision to the license is needed. A note here in this issue, or a brief note added to the README, would be sufficient. Something like "Output of tuist is not subject to the attribution requirement of the MIT license" or the contrary "Output of tuist is subject to the MIT license and its attribution requirement".

**Comment by pepicrft** [comment]
The projects and artifacts generated by Tuist belong to the user. Attribution is appreciated but not required.

**Comment by fortmarek** [comment]
If this is enough, let's close this. Let us know @RomainBoulay if you need anything else 🙌

**Comment by RomainBoulay** [comment]
Thanks @fortmarek for following up, it is indeed resolved 👍
