### ISSUE TITLE
Issues with Fourier vendored binaries

### ISSUE THREAD

**Issue by ezraberch** [tuist/tuist#3789]
1. The `fourier update` command does not support `swiftformat`.

2. There are two different places for vendored binaries: [projects/fourier/vendor](https://github.com/tuist/tuist/tree/main/projects/fourier/vendor) and [projects/tuist/vendor](https://github.com/tuist/tuist/tree/main/projects/tuist/vendor). The former has SwiftLint and SwiftFormat, while the latter has SwiftLint and Xcbeautify. The latter also has license files.

3. The versions of SwiftLint in the two locations are different. `fourier lint` is using the older version.

4. I'm unsure why it's necessary to include these binaries in the repo in the first place. `fourier` already has the ability to fetch and build the desired versions of these tools. `fourier` commands which use these dependencies could fetch and build them first if they are not already there.

**Comment by fortmarek** [comment]
> The fourier update command does not support swiftformat

Good point, that should be fixed.

>  There are two different places for vendored binaries: projects/fourier/vendor and projects/tuist/vendor. The former has SwiftLint and SwiftFormat, while the latter has SwiftLint and Xcbeautify. The latter also has license files.

The binaries in `fourier/vendor` are used for `fourier` commands whereas binaries `projects/tuist/vendor` in are used for using `tuist` itself. 

> The versions of SwiftLint in the two locations are different. fourier lint is using the older version.

Ideally, those should be the same, agree.

> I'm unsure why it's necessary to include these binaries in the repo in the first place. fourier already has the ability to fetch and build the desired versions of these tools. fourier commands which use these dependencies could fetch and build them first if they are not already there.

Yeah, we could switch to `fourier` installing dependencies. We wanted to use the current approach, so it's easier to start contributing. It does have the drawback of committing binaries but so far, it has not really been a real issue.
