### ISSUE TITLE
FRAMEWORK_SEARCH_PATHS not being set for transitive frameworks

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#379]
**Describe the bug**

Given a target
When one of it's dependencies has a Carthage framework
Then the framework search paths are not being set

**To Reproduce**

1. Generate a project with the following:

```swift
        Target(
            name: "ExampleFramework",
            platform: .iOS,
            product: .framework,
            bundleId: "io.tuist.example",
            infoPlist: "Sources/Info.plist",
            sources: [
                "Sources/**",
            ],
            dependencies: [
                .framework(path: "../Carthage/Build/iOS/Networking.framework"),
            ]
        ),
        Target(
            name: "ExampleFrameworkTests",
            platform: .iOS,
            product: .unitTests,
            bundleId: "io.tuist.exampleTests",
            infoPlist: "Tests/Info.plist",
            sources: "Tests/**",
            dependencies: [
                .target(name: "ExampleFramework"),
            ],
//            settings: Settings(
//                // Temporary until search paths are correctly set for transitive frameworks
//                base: [ "FRAMEWORK_SEARCH_PATHS": "$(SRCROOT)/../Carthage/Build/iOS" ],
//                debug: nil,
//                release: nil
//            )
        )
```

2. Notice the warning (and failing build in Xcode) for "could not auto-link framework Networking"

3. Uncomment the settings code to fix the behaviour, this is a temporary work-around

**Expected behaviour**

`FRAMEWORK_SEARCH_PATHS` should inherit from its dependencies if required.

**Comment by kwridan** [comment]
Does `ExampleFrameworkTests` reference `Networking` at all?

If I'm not mistaken, `[fixtures/ios_app_with_transitive_framework](https://github.com/tuist/tuist/tree/master/fixtures/ios_app_with_transitive_framework)` is a similar setup? That doesn't seem to exhibit this 😕(unless I missed something)

**Comment by thelvis4** [comment]
I think the issue described here manifests when a tests (or application) binary tries to link against a **static** framework that depends on a prebuilt framework. Like this (note that `Framework1-iOS` is a static framework):
![graph-static](https://user-images.githubusercontent.com/1589385/107149991-e0d61900-695b-11eb-864a-2f82cd9bbb4b.png)

To reproduce the issue, change `product: .framework` to `product: .staticFramework` in  
[fixtures/ios_app_with_transitive_framework/Framework1/Project.swift](https://github.com/tuist/tuist/blob/1e9a0a5ff641a28cd79f22948d352b99e99b9267/fixtures/ios_app_with_transitive_framework/Framework1/Project.swift#L8), regenerate the project and build the `Framework1Tests-iOS` scheme. You should see a `Could not find or use auto-linked framework 'Framework2'` warning followed by some errors.

My understanding of the issues is that when `Framework1` is built statically, the resulting static archive references symbols from `Framework2` that need to be resolved when linking the tests binary. So any tests or app target that depends on `Framework1` needs to know where to find `Framework2` (`FRAMEWORK_SEARCH_PATHS` has to contain `Framework2`'s path). This is also implied by the linker flags stored as `LC_LINKER_OPTION` load commands in Framework1's object files:
```sh
# Framework1.framework built as static 
$ otool -l Framework1.framework/Framework1
...
Load command 4
     cmd LC_LINKER_OPTION
 cmdsize 40
   count 2
  string #1 -framework
  string #2 Framework2
...
```

**Comment by kwridan** [comment]
Thanks @thelvis4, the reproduction steps are really helpful! 

Ouch, looks like we may have missed this case (or possibly recently regressed this), you are right we need to ensure the framework search paths are set. Even the app target would fail to build in the scenario above!

Will take a closer look at a fix.
