### ISSUE TITLE
Circular dependencies are silently failing

### ISSUE THREAD

**Issue by JulianAlonso** [tuist/tuist#3794]
**Describe the bug**
`tuist generate` fails without any error when a target dependency project has itself as dependency.

**To Reproduce**

1. Define a project with itself as target dependency.
2. run `twist generate`

**Expected behavior**
Output an error telling you what target is failing and what's the problem

**Screenshots**
![Screenshot 2021-12-06 at 14 48 36](https://user-images.githubusercontent.com/5766613/144865941-ac65a420-ff11-43d2-b32b-3752a659a042.png)

**Desktop (please complete the following information):**

- OS: macOS 12.0.1 (M1)
- Tuist version: from 2.2.0 

**Additional context**

**Comment by kwridan** [comment]
ah got it - circular dependencies are no longer getting flagged ‼️

```swift
Target(
  name: "Common",
  //..
  dependencies: [
      .taget(name: "Common")
  ]
)
```

the same can be seen with:

```swift
Target(
  name: "CommonA",
  //..
  dependencies: [
      .taget(name: "CommonB")
  ]
)

Target(
  name: "CommonB",
  //..
  dependencies: [
      .taget(name: "CommonA")
  ]
)
```
