### ISSUE TITLE
SwiftFormat asks for Swift version to be defined in the Tuist repo

### ISSUE THREAD

**Issue by hisaac** [tuist/tuist#3819]
**Describe the bug**

I've noticed that when I commit changes to the Tuist repo, and SwiftFormat runs, it complains that there is no Swift version defined.

```shell
warning: No Swift version was specified, so some formatting features were disabled. Specify the version of Swift you are using with the --swiftversion option, or by adding a .swift-version file to your project.
```

What are your thoughts on adding a `.swift-version` file to the repo, or specifying the version using the `--swiftversion` flag they mentioned?

**To Reproduce**

1. Make a change to the repo.
2. Commit that change using git as normal.
3. Observe the output containing the warning mentioned above.

**Expected behavior**

I'd expect that there would be no warning.

**Desktop (please complete the following information):**

- OS: macOS 12.0.1

**Comment by fortmarek** [comment]
> What are your thoughts on adding a .swift-version file to the repo, or specifying the version using the --swiftversion flag they mentioned?

I'd add a `.swift-version` flag 👍

**Comment by hisaac** [comment]
Perfect! Thanks @fortmarek.
