### ISSUE TITLE
3.0 deprecations

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#3906]
What 🌱

Since we are doing a major release, it's a good opportunity to remove some features that have been deprecated for a while.

**Comment by danyf90** [comment]
Right now `tuist generate` and `tuist focus` have opposite defaults and parameters (`--open` vs `--no-open`) on whether the project should be opened automatically or not.
I'm in favor of opening by default in both

**Comment by danyf90** [comment]
Make plugins project description helpers importable in local project description helpers (cc @luispadron ).

It probably won't be breaking, but reporting here just in case

**Comment by danyf90** [comment]
Improving the schemes as mentioned here could be interesting and possibly breaking: https://tuistapp.slack.com/archives/C02B4JKS8KG/p1637917243004800

**Comment by laxmorek** [comment]
Drop the `tuist lint code` command and provide SwiftLint functionalities using Plugins 2.0 🤔 (cc @fortmarek )

**Comment by fortmarek** [comment]
> We should think about plugins repos storage. We could just create new repositories in tuist organization or we could create new organization (called for example tuist-community) that could store all plugins in order to separate main tuist and additions to it? 🤔 Something similar to this

I like the idea and it has a precedent elsewhere but for now, I'd keep them in the `tuist` organization as it will make the management much easier as new organization does bring a non-trivial amount of overhead.

> If there is no time pressure for this 3.0 release I can create SwiftLint plugin for tuist (with Marek help 🙄)

We want to also publish a new website, so it might take some time - feel free to go ahead and I can help out if it'd become a blocker for merging 3.0 changes.

**Comment by luispadron** [comment]
As discussed in #3968 we should fix up `.autoGeneratedSchemes` to be more useful

**Comment by luispadron** [comment]
- [ ] Done

Add `@resultBuilder` syntax to `ProjectDescription` API
Draft PR: #3971

**Comment by laxmorek** [comment]
- [ ] Done

Drop `tuist lint code` and `tuist lint project` commands.

**Comment by danyf90** [comment]
[ ] [Refactor Project.Options to be a struct](https://github.com/tuist/tuist/pull/4104)

**Comment by danyf90** [comment]
- [ ] Refactor Config.Options to be a struct

**Comment by danyf90** [comment]
- [ ] Address [this comment](https://github.com/tuist/tuist/pull/4093#discussion_r798321114)

**Comment by danyf90** [comment]
Make Tuist.graph() accept a nillable path to make usage easier

**Comment by danyf90** [comment]
Make Workspace.automaticXcodeSchemes default to false

**Comment by danyf90** [comment]
- [ ] Decide whether to move some options of Config.generationOptions to Workspace.options or Project.options
