### ISSUE TITLE
Tuist doesn't do anything when passing `--verbose`

### ISSUE THREAD

**Issue by hisaac** [tuist/tuist#3911]
**Describe the bug**

When using the `--verbose` flag on the command line, Tuist doesn't appear to do anything at all.

**To Reproduce**

1. Run any command with the `--verbose` flag included
2. Note that the Tuist version being used is printed out, but nothing else happens

**Expected behavior**

Tuist runs the given command, and prints out verbose logs.

**Desktop (please complete the following information):**

- OS: 12.1
- Tuist: 2.5.0

**Comment by danyf90** [comment]
I think it might be related to [this](https://github.com/tuist/tuist/pull/3752), right @fortmarek ?

**Comment by hisaac** [comment]
Confirmed fixed by #3752 🎉
