### ISSUE TITLE
ExecutionAction.target doesn't work for workspace scheme

### ISSUE THREAD

**Issue by marcinpodeszwa-medcase** [tuist/tuist#3941]
**Describe the bug**
When I create scheme with preAction for a project schema I can specify target to get build settings. However, when I create ExecutionAction the same way for workspace scheme it doesn't work.

**To Reproduce**
I'm attaching sample project to show the issue. Build action defined in `Tuist/ProjectDescriptionHelpers/Project+Templates.swift` does work, build action defined in `Workspace.swift` doesn't work.

**Expected behavior**
I should be able to set target for build action in workspace scheme.

**Screenshots**

![app schema](https://user-images.githubusercontent.com/95348173/148058006-0788dbfe-5e6e-43ee-bdf1-95bf54c73245.png)
```
// Defined in project scheme ^
                        ExecutionAction(
                            title: "App Schema Action",
                            scriptText: "echo ${PROJECT_DIR}",
                            target: .init(stringLiteral: name)
                        )
```

![workspace schema](https://user-images.githubusercontent.com/95348173/148058020-f46b53f1-145f-4ac8-a30c-9f0007aaa377.png)
```
// Defined in workspace scheme ^
                    ExecutionAction(
                        title: "App Schema Action",
                        scriptText: "echo ${PROJECT_DIR}",
                        target: .project(path: "Targets/TuistPreActionReproduce", target: "TuistPreActionReproduce") // this target doesn't work
                    )
```

**Desktop (please complete the following information):**

macOS 12.1, Macbook Pro 13 M1 2020
Xcode 13.2.1
Tuist version 2.5.0

**Workspace reproducing the bug**
[tuist-pre-action-reproduce.zip](https://github.com/tuist/tuist/files/7807516/tuist-pre-action-reproduce.zip)

**Comment by kwridan** [comment]
Thanks for flagging this @marcinpodeszwa-medcase 

I pushed #3954 to fix this - worth giving a test locally

**Comment by kwridan** [comment]
Note: while testing this I learnt Xcode has a small gotcha in this area

You can only reference targets that are already referenced in the scheme _(e.g. added to the list of buildable targets, or listed as of the testable targets)_
