### ISSUE TITLE
`.autogeneratedSchemes(.disabled)` causes Xcode to pop up "autocreate schemes" dialog constantly

### ISSUE THREAD

**Issue by haifengkao** [tuist/tuist#3943]
**Describe the bug**

**To Reproduce**
1. add ` .autogeneratedSchemes(.disabled)` to disable auto generated schemes
``` swift
import ProjectDescription

let config = Config(
    plugins: [
        .local(path: "../../Plugins/FileResourceGen"),

    ], generationOptions: [
        .autogeneratedSchemes(.disabled)
    ]
)
```
2. `tuist generate -O`
3. Xcode will pop up "autocreate schemes" dialog whenever the project is generated.

**Expected behavior**
No annoying dialog should show up

**Screenshots**
<img width="245" alt="截圖 2022-01-05 上午1 18 51" src="https://user-images.githubusercontent.com/4080524/148098238-dd77863d-471a-4a00-ac66-2d2530d52023.png">

**Desktop (please complete the following information):**

- OS: Big Sur 11.4
- Version: tuist 2.5

**Additional context**

**Comment by kwridan** [comment]
Hi @haifengkao thanks for flagging this.

There's sadly a little bit confusion around the different scheme configurations.

- `.autogeneratedSchemes(.disabled)`: controls if Tuist should create schemes automatically based on the available targets defined in all your manifests

The dialog that appears related to Xcode which has it's own automatic schemes creation. I suspect the new `Workspace.GenerationOption` added by @jakeatoms in #3832 may help here.

```swift
// Workspace.swift

let workspace = Workspace(
    name: "CustomWorkspace",
    projects: [
        "App",
        "Modules/**"
    ],
    generationOptions: [
        .automaticSchemaGeneration(.disabled)
    ]
)
```

See https://docs.tuist.io/manifests/workspace and https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_custom_workspace for an examples.

**Comment by haifengkao** [comment]
thanks
