### ISSUE TITLE
Tuist test - underlying generation doesn't generate Bundle+Framework.swift accessor files 

### ISSUE THREAD

**Issue by gregiOS** [tuist/tuist#3984]
**Describe the bug**
When using `tuist test` command, tuist it's not generating Bundle+FrameworkName.swift that should be visible in `Derivered/Sources`.
After that tuist project generation fails.

**To Reproduce**

1. Crearte tuist manifest with Target that contains `resources`
2. Call `tuist test`
3. Command fails with error: `File not found at /Users/**/Developer/tests/***/Core/Derived/Sources/Bundle+Model.swift`

`tuist test` needs to be first command called in the repo after clean clone.
If you call `tuist generate` in advance it will succeed to generate Bundle accessor files. 

**Expected behavior**
tuist test generates Bundle accessors successfully 

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: MacOS 11.4
- Xcode: 13.1

**Additional context**
N/A

**Comment by luispadron** [comment]
@fortmarek @pepicrft Do ya'll recall if this expected behavior since `tuist generate` is the command that generates the bundles, etc. 

It doesn't seem ideal to have to run one after the other so maybe we can update this behavior.

**Comment by danyf90** [comment]
I think it might be related to [this problem](https://tuistapp.slack.com/archives/GGB99EP1A/p1642240364126500)

In that case the files are generate "in parallel" to another piece of code that instead needs them
