### ISSUE TITLE
Support `.xcframework` dependency type

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#401]
**Is your feature request related to a problem? Please describe.**

`.xcframework`s are the new binary frameworks supported by Xcode 11.

**Describe the solution you'd like**

A few options:

1) Add a new  `.xcframework` dependency type

e.g.

```swift
    Target(
            name: "App",
            platform: .iOS,
            product: .app,
            bundleId: "io.tuist.App",
            infoPlist: "Config/App-Info.plist",
            sources: "Sources/**",
            dependencies: [
                .project(target: "Framework1", path: "../Framework1"),
                .xcframework(path: "Frameworks/MyFramework.xcframework")
            ]
        )
```

2) Enhance the existing `.framework` type

The existing `.framework` dependency type could be enhanced to to detect the framework extension and apply the appropriate rules (e.g. if it's an .xcframework, simply include it in the appropriate phases without needing to call `tuist embed` for it)

**Additional context**

Starting an issue for us to collect what's needed to support this feature. This will help us decide on which option to pursue. 

**Status**

- [x] #757: Add XCFrameworkNode
- [x] #769: Introduce XCFramework dependency (for dynamic XCFrameworks)
- [x] #821: Add support for static XCFrameworks

**Comment by pepibumur** [comment]
Like the suggested approach @kwridan. So .xcframeworks don't need to be embedded?

**Comment by kwridan** [comment]
Still figuring out the details - from my limited testing, looks like Xcode will take care of the embed for you provided it's in the correct build phase (i.e. we wouldn't need to call `tuist embed` to manually copy / sign frameworks - like we need to for the ones built by Carthage)

<img width="551" alt="Screenshot 2019-06-09 at 20 26 39" src="https://user-images.githubusercontent.com/11914919/59163453-622b3780-8af9-11e9-8703-d9e1beecc15a.png">
<img width="550" alt="Screenshot 2019-06-09 at 20 56 51" src="https://user-images.githubusercontent.com/11914919/59163454-622b3780-8af9-11e9-8f76-4f95a7de9a72.png">

**Comment by pepibumur** [comment]
Awesome! That simplifies the things a bit.

**Comment by lakpa** [comment]
I am running a thought as if taking @kwridan first approach would be better as `xcframework` has new `Bundle OS Type code` which is `XFWK` and representing it with its new dependency type appears suitable enough to avoid messing with existing `framework` dependency type. Besides its configuration `info.plist` is different than `static/dynamic` framework types which as follows

<img width="510" alt="Screenshot 2019-11-13 at 23 48 35" src="https://user-images.githubusercontent.com/389328/68814526-fc774480-0670-11ea-8ac1-78b6b992f4be.png">

**Comment by pepibumur** [comment]
> I am running a thought as if taking @kwridan first approach would be better as xcframework has new Bundle OS Type code which is XFWK and representing it with its new dependency type appears suitable enough to avoid messing with existing framework dependency type.

Agree. I'd define a new dependency type instead of messing the existing `.framework`.

**Comment by lakpa** [comment]
@kwridan can we close this?

**Comment by kwridan** [comment]
Indeed we can, thanks for all your hard work on this @lakpa 👍
