### ISSUE TITLE
Ability to create a framework without Info.plist

### ISSUE THREAD

**Issue by pavel-trafimuk** [tuist/tuist#4017]
**Describe the bug**
Latest Xcode (13.2 as minimum) creates frameworks without info.plist. Info.plist file is deprecated.
But `Target.infoPlist` is not optional, I can't select nil or none. 

Suggest to add optional flag for this property

**Comment by kwridan** [comment]
Sounds like a reasonable addition.

`InfoPlist` is already optional in `TuistGraph.Target` as such we can adjust `ProjectDescription.Target` to follow suit. This in theory isn't a breaking change from the initialiser perspective. 

```swift
import ProjectDescription

// existing usage

let infoPlist: InfoPlist = .default

Target(
   // ...
   infoPlist: infoPlist
)
```

```swift
import ProjectDescription

// omitting info plist

Target(
   // ...
   infoPlist: nil
)
```

The `InfoPlist` property is public on `ProjectDescription.Target`, it could be a breaking if anyone references / reads the property in their helpers or within plugins - but I can't think of a valid use case where this may be used, so we may be ok.

I would keep the defaults as they are (`InfoPlist.default`) for the moment:

- Ensures no breaking behaviour change for current users
- Xcode still adds it when using the Storyboard template
- Xcode does indeed omit it when using the Swift UI app template by default however as soon as you attempt to add any custom keys or configurations (e.g. custom fonts) Xcode will automatically add the Info.plist file - I'm not sure it's deprecated per se

**Comment by luispadron** [comment]
@pavel-trafimuk 

The change you and the description @kwridan propose make sense! If you'd like to contribute this we can help with any questions
