### ISSUE TITLE
Project Generation Fails if Project.swift is Not in Root Folder

### ISSUE THREAD

**Issue by stherold** [tuist/tuist#4025]
**Describe the bug**
We build a white-label app which has already 40 different app targets and we therefore have many different Project.swift files which control the different configurations, e.g. additional source files, additional targets, ... We thought it is a good idea to put them in a subfolder of the target `./Targets/<target>/Manifest/Project.swift`. But in this case we get the generation error `SHSearchBar is not a valid configured external dependency`. Basically this is the error [invalidExternalDependency](https://github.com/tuist/tuist/blob/247d98db4bc331e802a027c52b02c66f09638714/Sources/TuistLoader/Models%2BManifestMappers/TargetDependency%2BManifestMapper.swift#L64). When we put it at the root of the whole project generation works just fine... But then we cannot have multiple project configurations.

**To Reproduce**
Here is an [example project](https://github.com/tuist/tuist/files/7912460/tuist-example.zip) which demonstrates the problem. Just execute:
```sh
tuist dependencies fetch
tuist generate -p Targets/TuistExample/Manifest
```

**Expected behavior**

We think the project generation should work in this case because:
1. There is the option `tuist generate -p Targets/TuistExample/Manifest` to generate from a different manifest location. 
2. If we remove all dependencies the project generation works just fine and the (example) project compiles. 

So we think it is intended to have multiple project configs. 

Please help. We still think Tuist is a great tool to split up our project and make the configuration explicit. We hope we can find a solution to this together.

**Desktop:**

- OS: macOS 12.1 (21C52)
- Tuist version 2.6.0

**Comment by stherold** [comment]
@ezraberch thanks for the tip. But I feat that then all the file references in my Project.swift will get confused (maybe). Right now I add the SPM dependencies from Dependencies.swift as local packages via 
```swift
Project([...],
        packages: [.local(path: .relativeToRoot("Tuist/Dependencies/SwiftPackageManager/.build/checkouts/SHSearchBar"))],
        [...])
```
which also works (for now).

---

@adellibovi is #4004 a solution to my problem 🤩 ?

**Comment by danyf90** [comment]
> @adellibovi is #4004 a solution to my problem 🤩 ?

unfortunately I think it is just a wrong link there 🤔

**Comment by adellibovi** [comment]
Oops, yes, @danyf90 link fixed.

**Comment by luispadron** [comment]
@stherold I'm looking into fixing/adding support for something like this, hopefully should have something workable in a few days.

Our setup looks like:

```
- Development
  - RepoOne
    - Projects
      - ProjectA 
        - Project.swift 
    - Tuist
      - ProjectDescriptionHelpers
    - ...
    
  - RepoTwo
    - Projects
      - ProjectA 
        - Project.swift 
    - Tuist
      - ProjectDescriptionHelpers
    - ...
```

And with this setup if you do something like have `RepoTwo` depend on a target from `RepoOne` then you get issues during generation about helpers not being found. I'm working on making a simple reproducible example and then will address the issue.

**Comment by alexanderwe** [comment]
Just found this ticket and we are experiencing the same issues. We have multiple projects which are organized in sub-directories. 

Some of these targets depend on external SPM dependencies defined in an `Dependencies.swift`. When we run 
```
tust generate
```
In the root directory everything works. 

But when we reference a specific project with  `-p <pathToProject>' the project generation fails with the mentioned error.
