### ISSUE TITLE
AppClip dependencies should be embedded

### ISSUE THREAD

**Issue by tsabend** [tuist/tuist#4032]
**Describe the bug**

When adding dependencies to a .appClip target they do not get embedded. This means when you run that target on device the appClip immediately crashes.

**To Reproduce**

[TuistBug.zip](https://github.com/tuist/tuist/files/7921634/TuistBug.zip)
This project takes the basic project added by `tuist init` and adds a minimal appClip target. When you run `tuist generate` you can see that the targets are embedded in the .app target but not in the .appClip target.

**Expected behavior**
The dependencies should be embedded in the app clip just like they are in the application target. I'm relatively new to app clip development so if there's some reason that shouldn't be the case please let me know.

**Screenshots**
<img width="573" alt="Screen Shot 2022-01-23 at 6 04 36 PM" src="https://user-images.githubusercontent.com/7468236/150701681-f00121d4-6924-4c8e-b8e9-fcaaf9bf5457.png">
<img width="620" alt="Screen Shot 2022-01-23 at 6 05 12 PM" src="https://user-images.githubusercontent.com/7468236/150701696-1e527241-5e1b-4eae-a8cb-9473130ae0ed.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version: 11.6
tested on latest tuist 2.6

**Additional context**

**Comment by kwridan** [comment]
Thanks for flagging this @tsabend !

Looks like it was something we missed during the initial implementation of the feature, it should be embedded as you suggested. 

What's odd is, when you add a new framework, Xcode doesn't allow you to embed in the App Clip directly _(most likely an Xcode bug)_, you can however do so afterwards.

![Screenshot 2022-01-24 at 06 52 29](https://user-images.githubusercontent.com/11914919/150737936-70c28bfd-a39e-4f71-8f15-15ff01998ca0.png)

_(in this example `MyAppClipKit` is a framework, `AppWithAppClip` is an Application, and `MyAppClip` is the App Clip)_
