### ISSUE TITLE
GitHub Actions should run unit tests only via `tuist test` and not SPM

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#4046]
**Describe the bug**
Currently, in the workflow `.github/workflows/tuist.yml` we run unit test twice, once via `tuist test` and again via `swift test`. 

**To Reproduce**

1. Run CI actions
2. Unit tests are run twice

**Expected behavior**
Unit tests must be run only via `tuist test`.

**Comment by mohitsaxenaknoldus** [comment]
I don't see where it is saying `swift test` in that file.

**Comment by luispadron** [comment]
> I don't see where it is saying `swift test` in that file.

@mohitsaxenaknoldus The change should be here: https://github.com/tuist/tuist/blob/a639485641284ee74425c9a82d37b2a9aae77022/projects/fourier/test/fourier/services/test/tuist/unit_test.rb#L20-L22. 

If you'd like to contribute this that would be awesome!

**Comment by mohitsaxenaknoldus** [comment]
Sure: https://github.com/tuist/tuist/pull/4063
