### ISSUE TITLE
Cannot fully disable resource synthesizers

### ISSUE THREAD

**Issue by neakor** [tuist/tuist#4050]
**Describe the bug**
Using the approach described in the documentation, setting `resourceSynthesizers` to an empty array in the project manifest does not fully disable all the resource generation.

**To Reproduce**

1. Define a project manifest.
2. Set `resourceSynthesizers: []` in project configuration.
3. Run `tuist generate`
4. `Bundle+PROJECT_NAME.swift` is still generated.

**Expected behavior**
The `Bundle.PROJECT_NAME.swift` is *NOT* generated.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS 11.6.1
- Version 2.6.0

**Additional context**
Using `Config.swift`'s `disableSynthesizedResourceAccessors` produces the same issue.

**Comment by danyf90** [comment]
Have you tried with [disableSynthesizedResourceAccessors](https://docs.tuist.io/manifests/config#generationoption)?

**Comment by neakor** [comment]
That doesn't work either. The other resource accessors are not generated. However the the `Bundle+PROJECT_NAME.swift` one is still generated. This behaves the same as setting the `resourceSynthesizers` to empty array in the project manifest.

**Comment by danyf90** [comment]
Sorry, the right config is `disableBundleAccessors` 🙏

**Comment by neakor** [comment]
Awesome! That worked. Thank you!
