### ISSUE TITLE
Can't disable Xcode automatic scheme generation without defining a Workspace.swift file

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#4053]
In [this PR](https://github.com/tuist/tuist/pull/3832) we added the ability to disable XCode automatic scheme generation, but it is an option of the Workspace manifest so it's not configurable if we don't have such manifest.
What do you think of moving the property to Config.swift instead?

**Comment by danyf90** [comment]
cc @fortmarek @pepicrft @kwridan @adellibovi 🙏

**Comment by danyf90** [comment]
cc also @jakeatoms as the original PR author 🙏

**Comment by jakeatoms** [comment]
I'm curious what issue you're hitting? `Workspace.swift` directly affects how the `xcworkspace` directory is generated, which is where this property comes into play. If you don't have a workspace, what would be the expected behavior? Without a `Workspace.swift` file, does Tuist still generate a workspace directory?

Also, given that `Config.swift` already has a property for disabling schema generation (by Tuist) and seems to be more directly related to Tuist configuration, I'd be concerned about confusion this could cause.

**Comment by danyf90** [comment]
Yes, I don't have a `Workspace.swift` but Tuist generates the `xcworkspace`, it's expected if you use `Tuist/Dependencies.swift`.

**Comment by kwridan** [comment]
Tuist generates an `xcworkspace` in all cases - whether for a single `Project.swift`, multiple or with an explicit `Workspace.swift`. In all cases there is a workspace, when not specified an implicit one is created with all referenced projects.

> What do you think of moving the property to Config.swift instead?

I believe this was considered originally, however I believe we were trying to move generation options closer to their domains, e.g. workspace wide options to workspace manifest, project wide options > project manifest.

Is there something preventing the creation or use of a `Workspace.swift` ?  Perhaps we may have missed a use-case that makes `Config.swift` more preferable?

> Also, given that Config.swift already has a property for disabling schema generation (by Tuist) and seems to be more directly related to Tuist configuration, I'd be concerned about confusion this could cause.

Sadly the confusion between the two APIs will remain no matter where we place those options 😅 - we had hoped explicitly using the terminology `xcodeSchemes` may help.

**Comment by kwridan** [comment]
Indeed it may be a better fit for it

**Comment by jakeatoms** [comment]
Could this be as simple as providing a default value to write when there is no Workspace.swift?

**Comment by danyf90** [comment]
Moved also scheme generation to Workspace.swift:https://github.com/tuist/tuist/pull/3987/commits/1cac3524cacf8688ad46e537c1f127674240c0df

**Comment by albertodebortoli** [comment]
I see this was closed but I'm not sure I understand if there was a solution.
The Workspace scheme gets generated when using a Project manifest with the latest version of Tuist and it wasn't the case with some previous version (in our codebase the workspace scheme started appearing after the update).
Unless I'm misunderstanding, defining a Workspace manifest would cause the Project manifest to be ignored, so it looks to me there is no way to use a Project manifest and not have the workspace scheme generated.

**Comment by danyf90** [comment]
You should be able to define the workspace manifest alongside the project. Please give it a try and let us know 🤞

**Comment by albertodebortoli** [comment]
Thanks @danyf90, my bad in passing the wrong values as the `projects` parameter. I managed to have both Project and Workspace manifests now 👍

**Comment by abhi21git** [comment]
I simply want an option in either `Tuist.swift` or `Project.swift` to disable generation of `.xcworkspace` file without even creating `Workspace.swift` file.
If this is possible, it would be helpful.
Tuist version 4.35.0
