### ISSUE TITLE
Tuist generate unexpected argument

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#4062]
**Describe the bug**
tuist generate
Error: Unexpected argument 'generate'
Usage: tuist <subcommand>
  See 'tuist --help' for more information.

**To Reproduce**

1. Intall tuist
curl -Ls https://install.tuist.io | bash
==> Downloading tuistenv...
==> Unzipping tuistenv...
==> Installing tuistenv...
==> tuistenv installed. Try running 'tuist'
==> Check out the documentation at https://docs.tuist.io/
2. run tuist generate 

terminal prints:
Error: Unexpected argument 'generate'
Usage: tuist <subcommand>
  See 'tuist --help' for more information.

**Expected behavior**
Tuist generate the project

**Desktop (please complete the following information):**

- macOS 12.1
- xcode 13.2.1

**Comment by luispadron** [comment]
Yep sorry about this, it was fixed in #4057 and will be released shortly as part of `2.7.1`
