### ISSUE TITLE
v2.7.0 won't install `tuist` but only `tuistenv`

### ISSUE THREAD

**Issue by GermanVelibekovHouzz** [tuist/tuist#4065]
**Describe the bug**
Now when running `curl -Ls https://install.tuist.io | bash` and then printing `tuist -h` only the `tuistenv` options are displayed.
![image](https://user-images.githubusercontent.com/81903043/151235730-860efc64-6849-4eea-ac65-51912b60a2bd.png)

None of `tuist` options are exposed.

**Comment by danyf90** [comment]
Releasing 2.7.1 right now 👍
