### ISSUE TITLE
Tuistenv update not updating tuistenv

### ISSUE THREAD

**Issue by ezraberch** [tuist/tuist#4069]
I noticed that `tuist update` was not finding 2.7.1. After manually running the install script, it was able to find find 2.7.1. So it seems that my version of `tuistenv` was from before the change from version detection based on Changelog to version detection based on github tags.

Conclusion: `tuist update` is not updating `tuistenv`. Here's the relevant code:

https://github.com/tuist/tuist/blob/1b993a20fef8f1e9742d81a264e9ec8e42b847f3/Sources/TuistEnvKit/Updater/EnvUpdater.swift#L30-L33

So it's looking for a local copy of the install script, and running it. But there is no such local copy, so it fails.

I'm unsure how this is supposed to work. Is there even supposed to be a local copy of the install script? If so, when should it be downloaded, and to where?

There's also a secondary bug here. Since the process fails to launch, rather than launching successfully then failing, the error checking in `System` does not catch it. So it fails silently.

**Comment by luispadron** [comment]
Yeah noticed this earlier as well, thanks for tracking it down.

I think it would make sense for this to simply download this script from the web, its run during an update in which case:

- You're already installing the latest tuist version
- You want the latest environment

**Comment by luispadron** [comment]
@ezraberch Did you want to pick this up? If not I can work on it as I think this should be prioritized.
