### ISSUE TITLE
When GitHub API request limit is reached, tuist does not report the error correctly

### ISSUE THREAD

**Issue by eightbitdave** [tuist/tuist#407]
**Describe the bug**

When the API limit is reached for GitHub tuist seems to be swallowing up the error.

Error output by tuist:

```
$ tuist
Using version 0.15.0 defined at /Users/Dave/projects/example/.tuist-version
Version 0.15.0 not found locally. Installing...
Verifying the Swift version is compatible with your version 5.0.1
⚠️  Warning: Couldn't get the Swift version needed for 0.15.0. Continuing...
Illegal instruction: 4
```

Real error from GitHub:
```
"{\"message\":\"API rate limit exceeded for xx.xx.xx.xx. (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://developer.github.com/v3/#rate-limiting\"}"
```

**To Reproduce**

Reach the API limit and run `tuist`

**Expected behavior**

This is not an error tuist can solve, but the error should be propagated to the user to ensure they know why the command is failing.

**Comment by eightbitdave** [comment]
It would be nice if it were possible to use authenticated requests too.

**Comment by pepibumur** [comment]
I'm closing this issue in favor of [this one](https://github.com/tuist/tuist/issues/848)
