### ISSUE TITLE
`tuist version` also prints an error message

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#4071]
Since 2.7.1, tuist version outputs:
```
tuist version
2.7.1
Couldn't find dispatcher with id: TuistAnalytics
```

I think it has something to do with the recent aasync/await refactor

**Comment by alexanderwe** [comment]
I also noticed this message at the bottom of fast running tasks and had a small look into the code. Seems that if the executed command is very fast the detached task is simply not finished until the main command finishes https://github.com/tuist/tuist/blob/main/Sources/tuist/TuistApp.swift#L26. 

Do you think it would make sense to just hide the dispatcher warning message if it matches the `TuistAnalyticsDispatcher.dispatcherId`? 

Another option I currently see would be to just force the registration of `TuistAnalyticsDispatcher` to be finished before executing a command. But with that approach I am not sure if this will cause any side-effects as I do not know the reason why the task is detached.
