### ISSUE TITLE
SPM integration not working in Xcode 13.3 beta 1

### ISSUE THREAD

**Issue by mikchmie** [tuist/tuist#4077]
**Describe the bug**
Swift Package Manager has updated the format of `workspace-state.json` file in version `5.6` (which is used by Xcode 13.3). Tuist relies on that file during `dependencies fetch` command execution and when it cannot decode it fails with the following error:
`The dependency kind remoteSourceControl is not supported.`

The format has been changed here: https://github.com/apple/swift-package-manager/pull/3764/files#diff-245da07187d4f8cea5e71c43720798627cbb20f3347616fd153476ad8973a81a

**To Reproduce**
1. `xcode-select -s <path_to_Xcode13.3>`
2. `cd` to directory containing project that uses Tuist with SPM packages in defined `Dependencies.swift`
3. `tuist dependencies fetch`

**Expected behavior**
Dependencies are fetched successfully.

- OS: macOS 12.2
- Version: 2.7.2
- Xcode version: 13.3 beta 1

**Comment by adellibovi** [comment]
@danyf90 did something like this happened in the past? I wonder what will be the approach, drop the old one or can make both format working?

**Comment by mikchmie** [comment]
@adellibovi Format version is included in the file, so we can support both formats, maintaining compatibility with all versions of Xcode. See linked PR for details.
