### ISSUE TITLE
Missing generated Bundle.module

### ISSUE THREAD

**Issue by KarimAlweheshy** [tuist/tuist#4095]
**Describe the bug**
Bundle.module is not generated for external SPM dependency

**To Reproduce**

1. Clone [this repo](https://github.com/KarimAlweheshy/tuist-dependencies-sample)
2. Run tuist generate
3. Open workspace
4. Build project

**Expected behavior**
Project builds.

**Screenshots**
<img width="1051" alt="Screen Shot 2022-01-27 at 14 41 01" src="https://user-images.githubusercontent.com/9082720/151991239-0f47a164-5e1e-412c-9192-385b03661b0f.png">
<img width="270" alt="Screen Shot 2022-02-01 at 15 51 51" src="https://user-images.githubusercontent.com/9082720/151991277-dba5c092-3403-44cc-87f8-8ae4b8fc6bd2.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.0

**Additional context**
IS_SPM is a macro added to the dependency's build settings.

**Comment by danyf90** [comment]
I think the point is that we are not generating the `Bundle.module` because the target doesn't have resources, but apparently it might be required anyway in some cases 🤔 

Not a big expert of the Bundle generation part, what do you think @kwridan @fortmarek @pepicrft ?

**Comment by fortmarek** [comment]
It's worth checking whether we get to [this](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift#L80) line and what the value of `supportsResources`. Generally, I think we should generate `Bundle.module` regardless of whether the dependency has modules. However, if the dependency is dynamic, then we might skip generating it.

For now, you should also be able to override `IS_SPM` to false with `targetSettings` (as mentioned [here](https://docs.tuist.io/manifests/dependencies#swiftpackagemanagerdependencies))

**Comment by apps4everyone** [comment]
tried with:

```swift
targetSettings: [
            "A_SDK": ["SWIFT_PACKAGE": false],
            "B_SDK": ["SWIFT_PACKAGE": false],
            "C_SDK": ["SWIFT_PACKAGE": false],
]
```
but didn't worked for me...

**Comment by apps4everyone** [comment]
used like this:

```swift
extension Bundle {
    class var current: Bundle {
        return Bundle(for: A_SDK.self)
    }

    class var resolved: Bundle {
        #if SWIFT_PACKAGE
        return Bundle.module
        #else
        return Bundle.current
        #endif
    }
}
```

**Comment by fortmarek** [comment]
Hey @apps4everyone, do you have a reproducible sample? Maybe with the project attached by @KarimAlweheshy?

**Comment by danyf90** [comment]
@apps4everyone for swift the debug flags are passed in `SWIFT_ACTIVE_COMPILATION_CONDITIONS`, so you should rather set
targetSettings: [
            "A_SDK": ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": ["$(inherited)"]],
            "B_SDK": ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": ["$(inherited)"]],
            "C_SDK": ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": ["$(inherited)"]],
]

**Comment by apps4everyone** [comment]
@fortmarek thx for you suggestions, unfortunately I can't share the project because the SDK's are internal. But the use only the #if SWIFT_PACKAGE flag which is not custom. (it's from SWIFT)

@danyf90 thx, tested this but didn't worked for me

**Comment by apps4everyone** [comment]
SWIFT_PACKAGE is active but there is no Bundle.module, so with or without targetSettings ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": ["$(inherited)"]] the compilation is failing.

In my opinion the only solution would be to generate this even without resources as suggested before. @danyf90

**Comment by apps4everyone** [comment]
SWIFT_PACKAGE doumentation:
https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#packaging-legacy-code

**Comment by apps4everyone** [comment]
this bug is preventing us from migration to Dependencies.swift now for weeks. How much work would i be to generate the `Bundle.module` by default maybe with an opt out flag?

fee migration hint for 3.0: https://github.com/tuist/tuist/discussions/4068#discussioncomment-2110749

**Comment by danyf90** [comment]
@apps4everyone I think it shouldn't be a problem to generate the file anyway, do you want to have a look at it? 🙏

**Comment by fortmarek** [comment]
agree, it should be fine to generate the file regardless of whether the module has any resources 👍

**Comment by apps4everyone** [comment]
@danyf90 do you think it's only removing this line?
https://github.com/tuist/tuist/blob/main/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L590

**Comment by danyf90** [comment]
Not sure if tuist will complain because there are no resources, you can try and see if it is enough 🙏

**Comment by KarimAlweheshy** [comment]
MessageKit has [resources](https://github.com/MessageKit/MessageKit/tree/master/Sources/Assets.xcassets).. it's not imported by tuist for some reason

**Comment by KarimAlweheshy** [comment]
and maybe that's why the .module is not generated

**Comment by danyf90** [comment]
Thanks for pointing out!

I think the problem is that Tuist does not support (yet) automatically imported resources from SPM. It had been implemented at some point, but it has some problems and we had to revert it [here](https://github.com/tuist/tuist/pull/3594) and didn't had the time to have a look at it yet.

If you want to give it a try, let us know and we can try to find a solution together!

**Comment by apps4everyone** [comment]
thx for the infos. Looks like we could label this as a bug?

**Comment by KarimAlweheshy** [comment]
Here's [a reference](https://github.com/apple/swift-package-manager/blob/658654765f5a7dfb3456c37dafd3ed8cd8b363b4/Sources/PackageLoading/TargetSourcesBuilder.swift#L638) to how Apple handles different data in SPM

**Comment by Banck** [comment]
Just a note: still a bug with tuist 3.0.1

**Comment by KarimAlweheshy** [comment]
I see the problem here to be more fundamental to adopting tuist.. we will always have to catch up on mirroring SPM behaviors in tuist for current and future versions

Is the tuist team aware about this challenge? What's the plan here?

**Comment by danyf90** [comment]
@KarimAlweheshy yes we are aware of that, and we plan to keep updating Tuist when needed

**Comment by apps4everyone** [comment]
sadly no update here, unfortunately way to complex to solve with a PR for none core tuist contributors like me.
