### ISSUE TITLE
`envversion` command is non-functional

### ISSUE THREAD

**Issue by ezraberch** [tuist/tuist#4105]
The `envversion` command in `tuistenv` doesn't actually do anything.

https://github.com/tuist/tuist/blob/8ab3f67ecbefb9df47d26b329fda95960fa290a3/Sources/TuistEnvKit/Commands/VersionCommand.swift#L6-L13

**Comment by fortmarek** [comment]
Ouch, good catch! We should be able to simply return the value from `Constants.swift`. This is, indeed, a great issue for new contributors 👀
