### ISSUE TITLE
dyld error with `libswift_Concurrency

### ISSUE THREAD

**Issue by kalkwarf** [tuist/tuist#4107]
**Describe the bug**
Running `main` in Xcode 13.2.1, running on macOS 11.6.2 results in a dyld error:

```
dyld: Library not loaded: @rpath/libswift_Concurrency.dylib
```

I found a workaround at https://github.com/MarcoEidinger/Repeat/blob/main/Package.swift (MIT licensed) which when ported to tuist resolves the problem.

As discussed on Slack, I'm opening this issue, and a PR with the fix.

**Comment by VilleWitt** [comment]
According to [Xcode 13.2.1 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2_1-release-notes) it seems like they fixed it in 13.2.1 and that it had to do with "bitcode enable" Maybe that is a hint?
> Apple Clang Compiler
Resolved Issues
Fixed an issue where apps built with Xcode 13 or Xcode 13.1 sometimes crashed at launch with an error reporting that the libswift_Concurrency.dylib library was not loaded. This only affected apps that used Swift Concurrency features (such as async/await), deployed to iOS prior to 15, tvOS prior to 15, or watchOS prior to 8, and had bitcode enabled. (86349088)

**Comment by VilleWitt** [comment]
And finally, according to [Xcode 13.3 Beta 2 release notes](url)

> Swift
...
Resolved Issues
Apps that use back-deployed Swift Concurrency on operating systems prior to macOS 10.15, iOS 13, tvOS 13, or watchOS 6 no longer crash on launch. (87789769)

**Comment by kalkwarf** [comment]
I wish I could use 13.3, but that requires an OS update my enterprise doesn't allow (yet). I'm ok calling this "won't fix" given all the facts.

**Comment by danyf90** [comment]
Hey 👋 
Until you can use 13.3 or macOS 12, it seems this works for me, ate least for iOS 12: https://developer.apple.com/forums/thread/696960?answerId=703973022#703973022
