### ISSUE TITLE
Manifests project

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#411]
## Context 🕵️‍♀️
I'm starting to use Tuist in a personal project, and I realized that having the `Setup.swift` file as part of the workspace is a bit inconvenient because Xcode doesn't offer autocompletion & syntax highlighting, which is very handy.

## What 🌱
Bring auto-completion and syntax-highlighting back for any manifest file.

## Proposal 🎉
Instead of generating a target inside the project that contains the `Project.swift` file, create a derived project, `Manifests.swift`that gets added to the workspace. The project can have a target per manifest file:

- Project
- Setup
- Workspace

**Comment by pepibumur** [comment]
What are your thoughts on this one @tuist/core ?

**Comment by ollieatkinson** [comment]
I raised something similar a while back, 

I think its nice to keep Project.swift with the relative files but do think there is a need for having a place for the other manifest files to live

https://github.com/tuist/tuist/issues/240

**Comment by pepibumur** [comment]
I can close this one and move the discussion there. Thanks for the reference @ollieatkinson
