### ISSUE TITLE
Report bug errors

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#413]
## Context 🕵️‍♀️
We have a type of errors, bugs, that were intended to be reported to some error tracking platform but we are not doing anything with those currently.

## What 🌱
Configure the error handler to report bug errors automatically. We can use GitHub's API and open issues for those. We'd need to uniquely identify those to avoid duplicated issues.

**Comment by danyf90** [comment]
I think we have already not enough firepower to handle reported issue, I wouldn't bother trying to investigate issues that no-one has reported, and hence are not that impacting
