### ISSUE TITLE
[Dependencies.swift][SPM] Specifying multiple platforms fails during generate command

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#4153]
**Describe the bug**
SPM dependencies
When using multiple platforms, the generate command fails to link correct platform.
For my tvOS app it is trying to link iOS dependencies for some reason.

**To Reproduce**
1. create `Dependencies.swift` with 2 platforms (iOS and tvOS)

```swift
import ProjectDescription

let dependencies = Dependencies(
    carthage: nil,
    swiftPackageManager: [

        .remote(url: "https://github.com/Alamofire/Alamofire.git", requirement: .upToNextMajor(from: "5.4.0")),
    ],
    platforms: [.tvOS]
)
```

2. create Project.swift with target for tvOS with external dependency
```swift
let target = Target(
    name: "tvOS",
    platform: .tvOS,
    product: .app,
    bundleId: "...",
    infoPlist: .default,
    sources: [".../**"],
    dependencies: [
        .external(name: "Alamofire"),
    ]
)

let project = Project(
    name: "tvOS",
    targets: [
        target,
    ]
)
```

3. run `tuist dependencies fetch` and `tuist generate`
4. tuist generate will fail:
> Target tvOS has a dependency with target Alamofire of type staticFramework for platform 'iOS' which is invalid or not supported yet.

**Expected behavior**
the project/workspace is created with correctly linked platform dependencies to all targets with various platforms

**Desktop (please complete the following information):**

- OS: macOS
- Version: 12.2

**Comment by zdnk** [comment]
if i omit the `platforms` parameter in `Dependencies.swift` it behaves the same

**Comment by danyf90** [comment]
Hello @zdnk 👋 
At the moment Tuist does not support multi-platform targets, so it's not possible to have multi-platform dependencies either.
It's explained briefly [here](https://docs.tuist.io/guides/third-party-dependencies#some-notes-on-the-integration-of-swift-packages) and logged as an issue [here](https://github.com/tuist/tuist/issues/397).

Hence I'm closing this as duplicate

**Comment by zdnk** [comment]
Well, I'd suppose that dependency targets may be generated per platform and link correct target to the parent, no need for multiplatform targets at this point, right?

**Comment by danyf90** [comment]
That would require changing the code of the dependencies, as the target would have different names, and it's not something we should do

**Comment by kikeenrique** [comment]
For future reference of people searching for multi platform support, this specific error was indeed fixed in PR https://github.com/tuist/tuist/pull/4570
