### ISSUE TITLE
[Dependencies.swift][SPM] Nested dependencies cannot link correctly

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#4154]
**Describe the bug**
I dont even know how to describe this :D

**To Reproduce**
1. Dependencies.swift
```swift
import ProjectDescription

let dependencies = Dependencies(
    carthage: nil,
    swiftPackageManager: [
        .remote(url: "https://github.com/ReactiveX/RxSwift.git", requirement: .upToNextMajor(from: "6.5.0")),
        .remote(url: "https://github.com/RxSwiftCommunity/RxDataSources.git", requirement: .upToNextMajor(from: "5.0.0")),
    ],
    platforms: [.tvOS]
)

```

2. Project.swift
```swift
let target = Target(
    name: "tvOS",
    platform: .tvOS,
    product: .app,
    bundleId: "...",
    infoPlist: .default,
    sources: [".../**"],
    dependencies: [
        .external(name: "RxSwift"),
        .external(name: "RxCocoa"),
        .external(name: "RcDataSources"),
    ]
)

let project = Project(
    name: "tvOS",
    targets: [
        target,
    ]
)
```

3. `tuist dependencies fetch`
4. `tuist generate`
> Target RxDataSources has a dependency with target RxCocoa of type framework for platform 'tvOS' which is invalid or not supported yet.
> Target RxDataSources has a dependency with target RxSwift of type framework for platform 'tvOS' which is invalid or not supported yet.

**Expected behavior**
the project is generated with correctly generated internal dependencies of the SPM packages

- OS: macOS
- Version 12.2

**Comment by ezraberch** [comment]
This can be resolved if you add `.framework` as a valid link below, like it is for other platforms. Is there some reason such a link would be invalid for `tvOS` specifically?

https://github.com/tuist/tuist/blob/39395e9476fb675aab1d7b28b91a86895d400abc/Sources/TuistGenerator/Linter/GraphLinter.swift#L468-L472

**Comment by danyf90** [comment]
I think we can add it 👍  Just tagging @fortmarek and @kwridan in case I'm missing something, but I just think we forgot to add it there

**Comment by kwridan** [comment]
Sounds reasonable 👍  - I don't believe it was omitted on purpose, rather it's open to additions when valid use-cases come up 🙂

**Comment by fortmarek** [comment]
Yeah, I agree - it's also a good idea to capture the scenario in some of the fixtures when doing the PR 👍

**Comment by danyf90** [comment]
@zdnk do you want to try to fix it yourself? If you need any help just let us know 🙌

**Comment by zdnk** [comment]
Actually yes, I'll try. I wanted to contribute for some time now, but never had time to deep dive to tuist let alone Xcode project files.
