### ISSUE TITLE
Improve distribution of ProjectAutomation and ProjectDescription

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#4156]
Right now Tuist plugins need to depend on the main tuist repo in order to be able to import the required types from `ProjectAutomation` and `ProjectDescription`.
This means having to fetch very big dependencies for 2 very small frameworks.

Moving the 2 to a separate repo would fix this problem but would make tuist contribution more problematic as often changes span across those and other tuist targets.

A possible alternative would be to distribute them as xcframework binaries, so that plugins can import them via SPM as xcframeworks

**Comment by ezraberch** [comment]
> Moving the 2 to a separate repo would fix this problem but would make tuist contribution more problematic as often changes span across those and other tuist targets.

How about keeping contributions in the main repo and having the release script mirror the changes to the other repo?

Also relevant: [SE-0292](https://github.com/apple/swift-evolution/blob/main/proposals/0292-package-registry-service.md) should solve this problem once it's implemented.

**Comment by fortmarek** [comment]
> How about keeping contributions in the main repo and having the release script mirror the changes to the other repo?

I like this idea 👀  that might be the easiest and most convenient approach we currently can take.
