### ISSUE TITLE
install.tuist.io -> "Non-existent domain"

### ISSUE THREAD

**Issue by jpstotz** [tuist/tuist#4167]
The recommended installation using 
    
    curl -Ls https://install.tuist.io | bash

does not work because the domain `install.tuist.io` does not exist (no DNS record found in any DNS resolver I have tested).

**Comment by iSapozhnik** [comment]
Same here. Is there any other way to install it?

**Comment by danyf90** [comment]
Until it gets fixed (maybe also later) to install in CI you can download it from Github: for example from https://github.com/tuist/tuist/releases/download/2.7.2/tuist.zip

**Comment by bcorrea2** [comment]
maybe `curl -Ls https://raw.githubusercontent.com/tuist/tuist/2.7.2/script/install | bash` could be a temporary solucion too?

**Comment by jpstotz** [comment]
> Until it gets fixed (maybe also later) to install in CI you can download it from Github: for example from https://github.com/tuist/tuist/releases/download/2.7.2/tuist.zip

Better download https://github.com/tuist/tuist/releases/download/2.7.2/tuistenv.zip and extract and execute it. It will automatically download and install the latest tuist version or if you have an existing project the version specified in the project.

**Comment by danyf90** [comment]
> > Until it gets fixed (maybe also later) to install in CI you can download it from Github: for example from https://github.com/tuist/tuist/releases/download/2.7.2/tuist.zip
> 
> Better download https://github.com/tuist/tuist/releases/download/2.7.2/tuistenv.zip and extract and execute it. It will automatically download and install the latest tuist version or if you have an existing project the version specified in the project.

In general you know which version you need (it's written in `.tuist-version`), so it's more efficient to download that binary directly

**Comment by fortmarek** [comment]
install.tuist.io should be online again, sorry for the inconveniences. Let us know if you still experience any issues!
