### ISSUE TITLE
Ensure SDKROOT is set so that `sdk` dependencies are correctly resolved

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#417]
**Describe the bug**

If you use the new `sdk` dependency you need to set the SDKROOT for the project otherwise it will default to macOS.

**To Reproduce**

1. cd into `fixtures/ios_app_with_sdk`

2. Add a dependency

```swift
.sdk(name: "MobileCoreServices.framework", status: .required),
```

3. Generate the project

```sh
tuist generate
```

4. Look at the path to the SDK

![7B508A75-C273-4A15-9BF1-C03F3DED857D](https://user-images.githubusercontent.com/1382565/59916121-3885e080-9416-11e9-8256-5434a3acbcd7.png)

**Expected behavior**

This path is wrong, it should be pointing to the iOS SDK.

![74976C7A-0907-4215-852E-562549B5EC6E](https://user-images.githubusercontent.com/1382565/59916282-a3371c00-9416-11e9-8fe4-638bd5074018.png)

**Additional context**

You can workaround the issue by providing the SDKROOT configuration using `Settings`

```swift
import ProjectDescription

let project = Project(name: "App",
                      settings: Settings(base: [ "SDKROOT": "iphoneos" ]),
                      targets: [
                          Target(name: "App",
                                 platform: .iOS,
                                 product: .app,
                                 bundleId: "io.tuist.App",
                                 infoPlist: "Info.plist",
                                 sources: "Sources/**",
                                 dependencies: [
                                     .sdk(name: "CloudKit.framework", status: .required),
                                     .sdk(name: "StoreKit.framework", status: .optional),
                                     .sdk(name: "libc++.tbd"),
                                     .sdk(name: "MobileCoreServices.framework", status: .required),
                                 ],
                                 settings: Settings(base: ["CODE_SIGN_IDENTITY": "",
                                                           "CODE_SIGNING_REQUIRED": "NO"])),
                          Target(name: "AppTests",
                                 platform: .iOS,
                                 product: .unitTests,
                                 bundleId: "io.tuist.AppTests",
                                 infoPlist: "Tests.plist",
                                 sources: "Tests/**",
                                 dependencies: [
                                     .target(name: "App"),
                                 ],
                                 settings: Settings(base: ["CODE_SIGN_IDENTITY": "",
                                                           "CODE_SIGNING_REQUIRED": "NO"])),
])
```

**Comment by kwridan** [comment]
Good catch @ollieatkinson! thanks for flagging this, I completely missed this.

`SDKROOT` is set at the [target level](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/ConfigGenerator.swift#L167), just not the project level. 

The tricky part is figuring out how the project level `SDKROOT` setting could be determined?


- When the `SDKROOT` of all targets defined are equal?
  - e.g.
     - TargetA (iOS) + TargetB (iOS) + TargetC (iOS)  = Project (iOS)
    -  TargetA (iOS) + TargetB (iOS) + TargetC (mac)  = Project (??)

- Define a new explicit `platform` setting at the project level?
  - Will require defaulting it a value to avoid breaking changes
  - e.g. 

```swift
Project(name: "App",
        platform: .iOS,
// ...
)
```

Looking at what Xcode does when manually adding the frameworks via the UI incase the `SDKROOT` isn't set at the project level

```
4229834E22BD669B0013511F /* MobileCoreServices.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = MobileCoreServices.framework; path = Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/MobileCoreServices.framework; sourceTree = DEVELOPER_DIR; };
```

it uses `DEVELOPER_DIR` + the SDK path - that sadly bakes the SDK path (e.g.  `..iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/...`) which varies by Xcode version into the project :( 

Any further insights / ideas on how best to solve this are welcome 🙂

**Comment by ollieatkinson** [comment]
It seems to do what you suggested of using the `sourceTree` set to `DEVELOPER_DIR`. Can we make the same assumption as Xcode. Only when we have a multiple targets with multiple platforms

```
Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks
```

Xcode seems to symlink the current SDK so we can just reference `iPhoneOS.sdk` opposed to the specific version. 

Unless we can think of a reason we need to support multiple SDK versions maybe this is the way to go.
