### ISSUE TITLE
[Dependencies.swift] Package is not a valid configured external dependency

### ISSUE THREAD

**Issue by obrhoff** [tuist/tuist#4186]
**Describe the bug**
Currently I'm struggeling to add `https://github.com/kean/Get` and `https://github.com/kean/URLQueryEncoder` to tuist.

Adding it to Tuist produces following error. `The maccatalyst platform is not supported.` as well later `Get is not a valid configured external dependency`

**To Reproduce**
[Sample project](https://github.com/tuist/tuist/files/8119086/Tuist-Dependency-Bug.zip)

**Desktop (please complete the following information):**

- OS: macOS 12.2
- Version 3.0.0

**Comment by EmilioPelaez** [comment]
I'm seeing the same thing, I even tried using the exact same values as [described in the external dependencies guide](https://docs.tuist.io/guides/third-party-dependencies) and I still get the same error for Alamofire.

**Comment by arnold-plakolli** [comment]
@obrhoff Tuist doesn't seem to have support for mac catalyst yet, hence the message: `The maccatalyst platform is not supported.`.

Meanwhile, to work around this issue with any repo that supports mac catalyst, fork that repo, update `Package.swift` to not include mac catalyst as a supported platform and reference your forked repo. 
I already did that [here](https://github.com/arnold-plakolli/Get) for `kean/Get` so you can just replace
```swift
.remote(
  url: "https://github.com/kean/Get",
  requirement: .upToNextMajor(from: "0.5.0")
)
```
with
```swift
.remote(
  url: "https://github.com/arnold-plakolli/Get",
  requirement: .branch("main")
)
```

**Comment by bvirlet** [comment]
I'm unsure I understand the resolution for this: I'm having a similar issue but when I look at the verbose output for Tuist, it looks like tons of our package dependencies are supporting maccatalyst. I didn't have this problem with Tuist 2.x. Is this a new issue with Tuist 3.0?

**Comment by danyf90** [comment]
I don't remember closing it, maybe I did it by mistake, let me reopen it 🤷‍♂️

**Comment by bvirlet** [comment]
Aren't a lot of packages supporting maccatalyst? Wouldn't there be a way to _ignore_ the `maccatalyst` platform if we're building for a different platform?

**Comment by danyf90** [comment]
@bvirlet should be fixed in [this PR](https://github.com/tuist/tuist/pull/4309) if you want to try 🚀

**Comment by bvirlet** [comment]
@danyf90 thank you.
