### ISSUE TITLE
[Plugin] Lint plugin fetch fails with an 'unexpected response from the network' for zip

### ISSUE THREAD

**Issue by sebj** [tuist/tuist#4189]
**Describe the bug**
The [Tuist Lint plugin](https://github.com/tuist/tuist-plugin-lint) has been added to my `Config.swift` file as follows:

```swift
import ProjectDescription

let config = Config(
	plugins: [
		.git(url: "https://github.com/tuist/tuist-plugin-lint", tag: "ea9b527")
	]
)
```

When I run `tuist fetch` in Terminal, the following error is logged:

```
Resolving and fetching plugins.
Cloning plugin from https://github.com/tuist/tuist-plugin-lint @ ea9b527
/Users/seb/.tuist/Cache/Plugins/fb46839ed54ef4a12a57f8fa2c298087/Repository
Received unexpected response from the network with an url request that sends a GET request to url 'https://github.com/tuist/tuist-plugin-lint/releases/download/ea9b527/tuist-plugin-swiftlint.tuist-plugin.zip'
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

The `tuist lint` command also does not work as a result.

**Desktop:**

- OS: macOS Monterey 12.2.1 (21D62)
- Version: 3.0.0
- Network: Wi-Fi, no VPN or proxy active

**Comment by laxmorek** [comment]
Hey @sebj I'm sorry for inconvenience. The plugin isn't released yet. I will do it until end of the week.

**Comment by ezraberch** [comment]
If you want to use a commit hash instead of a tag, you need to instead use 

```swift
.git(url: String, sha: String)
```

**Comment by fortmarek** [comment]
> If you want to use a commit hash instead of a tag, you need to instead use

Note this currently won't work for tasks such as the `lint` plugin but only for project description helpers.

> Should the plugins API allow to specify a tag?

They should in the future - however, users will have to build the executables locally. It would be a good addition going forward.

**Comment by sebj** [comment]
Thanks! Just tried to add the plugin again – fetched successfully and works well! I was over-eager to try this out after seeing the 3.0 release. 😄
