### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#420]
## Need/problem
Some projects use [CocoaPods](https://cocoapods.org) as a dependency management tool. CocoaPods integrates the dependencies into an existing project by creating a new project that gets added into a workspace, adding some build phases, and changing the targets configuration files.

If developers want to use Tuist in projects that are configured with CocoaPods, they have to remember running `pod install` right after tuist generates the project. That's something Tuist could do as part of the project generation and thus, developers would only have to execute one command, `tuist generate`.

## Motivation

One of Tuist's goals is making the generation and interaction with Xcode projects convenient. Unfortunately, developers don't get the convenience that we are aiming for when they use CocoaPods in their projects. Moreover, the fact that we don't have any "support" for CocoaPods, can make users hesitant to introduce Tuist into their workflows.

Tuist should embrace Apple and community developed tools and make sure that they are well supported in the workflows and features that we design. 

## Detailed design

We introduce a new type of `TargetDependency`, `.cocoapods`:

```swift
let target = Target(dependencies: [
  .cocoapods(path: ".",  useBundler: true)
])
```

Targets can define only **one** CocoaPods dependency. Before the generation of the project, we run `pod install` passing the argument `--no-integrate` that just resolves the dependencies and generates the Pods projects without integrating it into any project.

As part of the project generation, we need to configure the following elements in the targets that have a CocoaPods dependency:
- Add the `Pods.xcodeproj` to the workspace of the project that the target belongs to.
- Set the CocoaPods generated .xcconfig file.
- Add the build phases that CocoaPods generates by default.

## Validations
Tuist should fail if the environment or the manifest configuration is not compatible/configured to have a CocoaPods dependency. The following validations are introduced:

- **Targets have a local .xcconfig set:** Targets only support one .xcconfig file. 
- **Missing CocoaPods:** CocoaPods might not exist in the user's environment. In that case, we need to tell developers and point them to use the `tuist up` feature to configure developers' environment with CocoaPods.

# Drawbacks

- With Apple officially supporting Swift Packages in Xcode projects, CocoaPods will be used less and less. Is it worth investing time in this? I think so... It's a community tool and there are many projects that are using it nowadays and that will continue to use it.
- We rely on `Podfiles` being properly configured. If a `Podfile` is badly configured, the generated project might be invalid and developers will likely think it's Tuist's fault or that should have been detected.

## Alternatives

**Defining hooks**
Instead of defining a new type of dependency, add a new attribute to `Project`, `hooks` so developers can define actions to be executed before and after the generation of projects:

```swift
let project = Project(hooks: [.before("pod", "install")])
```
The downside of that approach is that we'd need to detect whether any of those commands is a CocoaPods command, to adjust the generated project accordingly.

# Adoption strategy

This is not a breaking change. We'll document the feature and mention it in the release blog post. 

# How we teach this

The documentation website has a section for dependencies. We can add another subsection where we document this new type of dependency and give developers some examples of how to use CocoaPods with Tuist in their projects.

# Unresolved questions

- Should we support adding a CocoaPod dependency to targets other than apps (transitive dependencies)?

**Comment by ollieatkinson** [comment]
The hesitation I have here is that Cocoapods is going to be deprecated in favour of SwiftPM. I fear that it's too late to add support for it to really be beneficial to any users.

Is there a pressing need to add Cocoapods support for a particular use-case which SwiftPM doesn't already do?

**Comment by pietrocaselani** [comment]
I am using Tuist and CocoaPods on the same project, and at first, I struggle a little bit to remember running both commands. Now it's all wrapped up on a script and everything is good. So I am super ok with the "lack" of CocoaPods support.

I liked the hooks approach. I think it's a more generic approach and solve the problem, but not on a specific domain (CocoaPods), which is good, because SPM is coming.

Could you please give more context on this downside?
> "The downside of that approach is that we'd need to detect whether any of those commands is a CocoaPods command, to adjust the generated project accordingly."

I was think in something like this
`let project = Project(hooks: [.after("pod", "install")])`
So, after the project is generated, run this command, which I understand as something like `tuist generate && pod install`

**Comment by pepibumur** [comment]
> The hesitation I have here is that Cocoapods is going to be deprecated in favour of SwiftPM. I fear that it's too late to add support for it to really be beneficial to any users.

CocoaPods is a widely used tool so I don't think projects will transition overnight because SwiftPM lacks support for many things that CocoaPods already has support for. 

> Is there a pressing need to add Cocoapods support for a particular use-case which SwiftPM doesn't already do?

I don't think is a matter of pressure, but acknowledging and supporting the tools that project use, and CocoaPods is one of those.

> "The downside of that approach is that we'd need to detect whether any of those commands is a CocoaPods command, to adjust the generated project accordingly."

That was a misunderstanding on my side. There's no need to do all that because CocoaPods does all of that with the project that Tuist generates.

**Comment by kwridan** [comment]
> I liked the hooks approach. I think it's a more generic approach and solve the problem, but not on a specific domain (CocoaPods), which is good, because SPM is coming.

👍 agreed, the hooks approach seems more beneficial generally and doesn't require any specific CoacoPods domain integration.

This will be super handy for code generation tools too such as Sourcery / SwiftGen that can generate new source files which need to be included in the generated Xcode project.

**Comment by kwridan** [comment]
Worth noting, Tuist has `up` commands, I wonder if this is already possible?

```swift
let setup = Setup([
    .custom(name: "Generate the project", meet: ["tuist", "generate"], isMet: [""]),
    .custom(name: "CoacoPods", meet: ["pod", "install"], isMet: [""]),
])
```

```
$ tuist up
Configuring Generate the project
Generating workspace App.xcworkspace
Generating project App
✅ Success: Project generated.
Total time taken: 0.205s
Configuring CoacoPods
...
```

**Comment by pepibumur** [comment]
> Worth noting, Tuist has up commands, I wonder if this is already possible? (I know it was intended for system setup - but perhaps can still prove useful)

`tuist up` focuses on the configuration of the environment with all the tools that are necessary to interact with the project, one of those tools could be CocoaPods. I think hooks fit more into the `Project.swift` where all the information that is used for the project generation is defined.
