### ISSUE TITLE
`tuist cache warm` failing to include arm64 architecture 

### ISSUE THREAD

**Issue by joshgare** [tuist/tuist#4202]
**Describe the bug**

We have setup our decencies in `Dependencies.swift`. They are all SPM packages and resolve with no problem. However after running `tuist cache warm` and the cache being setup our Xcode project no longer runs after generation.

Each framework displayed the following error:

```
The linked framework 'FBLPromises.framework' is missing one or more architectures required by this target: arm64.
```

**To Reproduce**

1. Setup SPM packages in Decencies.swift
2. Run `tuist fetch`
3. Run `tuist cache warm`
4. Run `tuist generate`
5. Build project in Xcode and it will fail with the error

**Expected behavior**

We expected our dependencies to be cached so that we don't need to build them each time we make a change to our code.

**Screenshots**

<img width="454" alt="image" src="https://user-images.githubusercontent.com/113687/156040998-295c3c01-c89c-4c49-8098-708e79db4964.png">

**Desktop (please complete the following information):**

- OS: macOS 12.1
- Tuist version 3.0
- M1 Mac

**Comment by adellibovi** [comment]
Hi @joshgare, I believe as a workaround you can produce .xcframeworks instead of .framework :)

**Comment by joshgare** [comment]
Interesting @adellibovi - thanks for the tip, what's the best way to make sure .xcframewokrs are generated instead?
