### ISSUE TITLE
Focus issue with static library with resources

### ISSUE THREAD

**Issue by erkekin** [tuist/tuist#4209]
**Describe the bug**
focus doesn’t work for the apps with the following pattern.

> App Target -> Static Framework With Resources

**To Reproduce**

Download the [example project](https://github.com/tuist/tuist/files/8184585/accountapp.zip)

```bash
tuist cache warm AccountApp -x
tuist 2 // tuist focus AccountApp -x
tuist 3 // tuist generate AccountApp p-x
```

**Expected behaviour**
I expect not to see the source code of `Account` target in project navigator. 

**Screenshots**
<img width="260" alt="Screenshot 2022-03-04 at 9 02 13 am" src="https://user-images.githubusercontent.com/701481/156736805-486498af-4d8d-4ad6-be8e-6cbc5440ef76.png">

**Desktop (please complete the following information):**

- macOS 11.6.2
- tuist 2.6.0, 2.7.2, 3.0.0

**Comment by danyf90** [comment]
Hey @erkekin 👋 
Caching of static libraries is not supported, you should use `staticFramework` instead 🚀

**Comment by erkekin** [comment]
@danyf90 sorry I meant `staticFramework`, now edited the project and re uploaded. It still can't focus. Should I re open this one?

**Comment by danyf90** [comment]
Tried locally and seems to work fine, what problem are you facing?
<img width="271" alt="Screenshot 2022-03-04 at 11 40 21" src="https://user-images.githubusercontent.com/2794031/156748488-314d8e2d-9071-468c-861d-4efddce67525.png">

**Comment by erkekin** [comment]
@danyf90 

I'm on macOS 11.6.2
and I apply these with tuist 3.0.0

```bash
tuist clean 
tuist cache warm  AccountApp  --xcframeworks
tuist generate  AccountApp  --xcframeworks   
```

however I still see the Account's source code in project navigator.

could thi be because of macOS version? (Big Sur)
