### ISSUE TITLE
Update .sdk dependency type to be less error prone

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#422]
# Need/problem

When specifying a `.sdk` dependency in the manifest, we rely on the extension specified in the name to determine the sdk type.

e.g.

```swift
dependencies: [
   .sdk(name: "CloudKit.framework"),
   .sdk(name: "libc++.tbd"),
]
```

This leaves room for error as any extension can be specified or omitted. 

# Motivation

Currently we mitigate this via displaying an error in the event an unsupported extension is detected.

```swift
dependencies: [
   .sdk(name: "CloudKit.foobar"),
]
```

```
❌ Error: The SDK type of CloudKit.foobar is not currently supported - only [.framework, .tbd] are supported.
```

It is slightly confusing when an extension is omitted

```swift
dependencies: [
   .sdk(name: "CloudKit"),
]
```

```
❌ Error: The SDK type of CloudKit is not currently supported - only [.framework, .tbd] are supported.
```

# Proposal

To reduce the chances of error and have a more explicit manifest, we can introduce the sdk type as an explicit parameter.

e.g.

```swift
dependencies: [
   .sdk(name: "CloudKit", type: .framework),
   .sdk(name: "libc++", type: .tbd), 
]
```

# Detailed design

Currently, the SDK type and paths are determined when translating SDK dependencies to `SDKNode`s when we construct the graph. 

This was one of the reasons we were unable to add the existing checks to one of the linters (e.g. `TargetLinter`) as the creation of the `SDKNode` would throw an error incase it detected an invalid extension - and this the graph wouldn't get created. It's only after a graph is constructed that linking takes place.

With the new proposal, the creation of `SDKNode`s now no longer this check and therefore will no longer need to throw errors. It will simply house the framework name, type, platform and status.

```swift
class SDKNode: GraphNode {
   init(name: String, type: SDKType, platform: Platform, status: SDKStatus) {
       // ...
   }
}
```

# Drawbacks

- This will be a breaking change to anyone using the `.sdk` feature in Version 0.16
- The API may be slightly inconsistent with others that do allow specifying the extension

e.g.

```swift
dependencies: [
   .sdk(name: "CloudKit", type: .framework),
   .framework(path: "Frameworks/Bar.framework")
   .library(path: "Libraries/Bar/libBar.a", publicHeaders: "Libraries/Bar", swiftModuleMap:"Libraries/Bar.swiftmodule")
]
```

# Alternatives

- Add manifest linters to enable linking ahead of creating the graph
  - This won't make the usage less error prone, but may allow more flexibility with displaying errors

# Adoption strategy

- Documentation will need to be updated, and a mention of the change in API in the next release blog post with the rationale behind the change.
- Seeing its a fairly new feature, it's adoption may not yet be wide spread and may be ok to just replace it without any migration steps - however if there's a concern and we want to do some migration work we have some flexibility due to the decoupled Manifests and Models we currently have in place.
   - The manifests (`ProjectDescription`) can contain an additional `SDKType.default` or `SDKType.autodetect` which the `GeneratorModelLoader` can translate to the Model `.framework` or `.tbd` based on the extension of the name specified. It can do this as well as display a deprecation warning stating that this will be removed in the next release and encourage the usage of explicit dependency types. This allows us to maintain backwards compatibility.

e.g.

```swift
dependencies: [
   .sdk(name: "CloudKit.framework"), 
   .sdk(name: "CloudKit.framework", type: .autodetect), // equivalent to the one above
]
```

```
⚠️ Assuming .framework SDK type for "CloudKit.framework" - please specify the SDK type explicitly e.g. `.sdk(name: "CloudKit", type: .framework). The ability to auto detect SDK types will be removed in the next release.
```

Note however, the `GeneratorModelLoader` is intended to be a thin translation layer, as such we would need to introduce new components that are leveraged by the loader to perform this logic. 

# Unresolved questions 

- Is a migration required or are we ok with this being a breaking change? 

# Related issues

https://github.com/tuist/tuist/issues/417

**Comment by adellibovi** [comment]
Resolved in https://github.com/tuist/tuist/pull/3961
