### ISSUE TITLE
"Unrecognized selector sent to instance" when use Dependencies.swift and Release configuration

### ISSUE THREAD

**Issue by Banck** [tuist/tuist#4225]
Tuist version: 3.0.1
**Describe the bug**
Dependencies.swift has SPM lib, for example:
```
let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/roberthein/TinyConstraints", requirement: .upToNextMajor(from: "4.0.0"))
    ],
    platforms: [.iOS]
)
```
Everything works fine, until you try version from testflight or just release configuration. There will be crash in lib:
`2022-03-09 15:30:55.264513+0700 SPMTest[98047:473405] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSLayoutConstraint with:]: unrecognized selector sent to instance 0x600001a98550'
`
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/6259254/157403267-e9460dd3-3593-440b-887e-c54ef769a7c8.png">

**To Reproduce**
Here is an example project. 
[SPMTest.zip](https://github.com/tuist/tuist/files/8213059/SPMTest.zip)

Try to run and then change configuration to release for scheme:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/6259254/157404148-8e882d82-9f74-4524-a667-b06a99d35c85.png">

**Comment by danyf90** [comment]
Not sure if it's the cause, but I would try to set the product type of the dependency to `framework` in the `productType` property [here](https://docs.tuist.io/manifests/dependencies#swiftpackagemanagerdependencies)

**Comment by Banck** [comment]
@danyf90  Yes, with framework works great. Sorry.
Is there any tips how to understand which type for framework do we need to specify for each libs?

**Comment by danyf90** [comment]
Unfortunately not 😢 
I have suggested it because I have seen something similar for a similar dependency
