### ISSUE TITLE
Add full support for arm64 architectures

### ISSUE THREAD

**Issue by luispadron** [tuist/tuist#4230]
**Describe the bug**

Currently, Tuist supports both `arm64` and `x86_64` architectures. This is because we build the `tuist` binary for both of these archs during release. While this is great there are outstanding configurations that prevent / create issues when working with an `arm64` machine. Some example issues: https://github.com/tuist/tuist/issues/4202

Firstly, in the Tuist `Project.swift` we exclude building for `arm64` [here](https://github.com/tuist/tuist/blob/main/Project.swift#L4). This means contributors can only build Tuist via Rosetta. We should look to remove this setting as there is no reason to have this enabled when we support both platforms.

Secondly, there is code that handles building targets, dependencies, etc which does not correctly account for the multiple architectures available to M1 users. For example [here](https://github.com/tuist/tuist/blob/main/Sources/TuistCore/Simulator/SimulatorController.swift#L180), it looks like we default to running builds on Intel architecture which may not be what the user wants. 

Additionally, there are other settings such as when editing projects [here](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/ProjectEditor/ProjectEditorMapper.swift#L239-L243) that cause issues for M1 users if they want a standard project that can be built on both Intel and Apple. 

In summary: We should audit the code base for these exclude flags and any settings that may be preventing M1 users from building the project as is standard. We previously added these flags while we waited for M1 support but now that its readily available we should look to remove any custom settings that override default Xcode behavior and ensure that on M1 macs users can build **both** Intel and Apple platforms as is standard.

### Work

There is a WIP PR available at: https://github.com/tuist/tuist/pull/4031. This does some of the work required to remove these settings but we need to investigate other issues the PR introduces. In particular, I've noticed issues that with the flags removed any `xcodebuild` command on `macOS` must include the correct platform to build which we currently are defaulting to `Intel` but this may be incorrect.

**Comment by danyf90** [comment]
Fixed in https://github.com/tuist/tuist/pull/4031
