### ISSUE TITLE
Can't add `.xib` files as sources

### ISSUE THREAD

**Issue by lucaspioto** [tuist/tuist#4231]
**Describe the bug**
Can't add `.xib` files as sources

**To Reproduce**

1. Targets/myProject/Sources/** or
Targets/myProject/Sources/**/*.xib

Not working... Help me!

**Desktop (please complete the following information):**

- OS: [Catalina]
- Version [10.15.7]

**Comment by vidugloeck** [comment]
I am a beginner to tuist,  but I think the `sources:` parameter only takes source files (e.g. `.swift` files). `.xib` files probably belong to the `resources:` parameter.

**Comment by kwridan** [comment]
As @vidugloeck points out `xib` files are treated as resources and as such can be defined within the `resources` section of the project manifest.

Thank you both for raising this :) - I think we can close this unless you discover any issues we may have missed

**Comment by lucaspioto** [comment]
I would like to keep the structure of my project.
With .swift and .xib files together in one folder.
That's not possible ?

**Comment by kwridan** [comment]
It should still be possible by specifying glob patterns

for example, say all your sources and xib files live under `Sources`:

```swift
// ...
Target(
 // ...
 sources: [
    "Sources/**",
 ],
 resources: [
    "Sources/**/*.xib",
 ]
)
```

Hope this helps!
