### ISSUE TITLE
Dependency with Core data fails in `tuist generate`

### ISSUE THREAD

**Issue by markemer** [tuist/tuist#4232]
**Describe the bug**
Adding `.external("IterableSDK") as a dependency in Project.swift gives me the following error.

```
Trying to add a file at path /PATH/tuist-integration-spm/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/swift-sdk/swift-sdk/Resources/IterableDataModel.xcdatamodeld to a build phase that hasn't been added to the project.
```

**To Reproduce**
I have attached a sample project that shows the behavior. It will do so in the tuist generate phase when running
`tuist edit` and then `tuist generate`

**Expected behavior**
I expect a project to be generated and IterableSDK to be properly included.

**Desktop (please complete the following information):**

- OS: macOS
- Version 12

**Additional context**

**Sample Project:**
[IterableTest.zip](https://github.com/tuist/tuist/files/8234498/IterableTest.zip)

**Slack Thread**
https://tuistapp.slack.com/archives/C018QG7U7SN/p1646866825897799

**Comment by markemer** [comment]
Alex Silva has the seen the same problem and mentioned it on Slack in this thread:
https://tuistapp.slack.com/archives/C018QG7U7SN/p1646866825897799

Here is the file he uploaded
[TestTuist.tar.gz](https://github.com/tuist/tuist/files/8234545/TestTuist.tar.gz)

**Comment by lucaspioto** [comment]
https://github.com/tuist/tuist/issues/3522

```
let target = Target(
                name: "Example",
                platform: .iOS,
                product: .staticFramework,
                bundleId: "com.example.mappingmodel",
                infoPlist: InfoPlist(stringLiteral: "App.plist"),
                sources: "Sources/**",
                coreDataModels: [
                    CoreDataModel("Sources/mappingapp.xcdatamodeld"),
                ]
            )
let project = Project(
    name: "MappingModelExample", 
    targets: [target]
)
```

Hope this helps!

**Comment by lucaspioto** [comment]
Is it possible to put coredata in the Resources folder?

**Comment by lucaspioto** [comment]
https://tuistapp.slack.com/archives/C018QG7U7SN/p1646866825897799

>  How do I join the community?

**Comment by danyf90** [comment]
> https://tuistapp.slack.com/archives/C018QG7U7SN/p1646866825897799
> 
> > How do I join the community?

Clicking on the link should be enough, do you have any problem with that?

**Comment by lucaspioto** [comment]
lucaspioto@gmail.com does not have a workspace account.

To create an account, I get this message: Don't have an email address from the domain @ppinera.es?
Contact your Tuist workspace admin to request an invite.

**Comment by fortmarek** [comment]
> I have a question, referring to the topic... Is it possible to put coredata in the Resources folder?

Not yet, but @adellibovi is addressing it [here](https://github.com/tuist/tuist/pull/4237)

**Comment by lucaspioto** [comment]
Thanks!

**Comment by adellibovi** [comment]
@markemer @lucaspioto the issue is now merged in `main`, in case you want to try it out 😄
