### ISSUE TITLE
Setting custom cache path still stores things in default cache folder

### ISSUE THREAD

**Issue by parse** [tuist/tuist#4245]
**Describe the bug**

When setting a custom cache path, it still stores things in `~/.tuist/Cache/Manifests`

Using this: 
```
cache: .cache(path: .relativeToRoot("Cache"))
```

I am overriding the cache location  and was therefore hoping it would keep all caches in my designated project cache. But it seems like some cache gets stored in ~/.tuist/Cache/Manifests even though I have it overriden.

Therefore, I expected tuist clean to take care of both folders, or another way of looking at it is that Tuist makes sure that nothing gets saved in ~/.tuist/Cache/Manifests if I have overriden it.

**To Reproduce**

1. Override cache location
2. All cached items be stored in the above specified folder.

**Expected behavior**
All cache gets stored in the given location.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]  macOS 12.2.1
- Version [e.g. 22] Tuist version 3.0.1

**Additional context**
I'm currently getting around the issue by running `rm -rf ~/.tuist/Cache` in my build step.

**Old issue**
**Describe the bug**

When running `tuist clean` I assumed that the `~/.tuist/Cache/Manifests` folder was cleaned. But it seems like only these folders gets cleaned:

```
Successfully cleaned artifacts at path /Users/xxxx/azure-agents/main/_work/20/s/Cache/Plugins
Successfully cleaned artifacts at path /Users/xxxx/azure-agents/main/_work/20/s/Cache/BuildCache
Successfully cleaned artifacts at path /Users/xxxx/azure-agents/main/_work/20/s/Cache/TestsCache
Successfully cleaned artifacts at path /Users/xxxx/azure-agents/main/_work/20/s/Cache/Projects
Successfully cleaned artifacts at path /Users/xxxx/azure-agents/main/_work/20/s/Cache/ProjectDescriptionHelpers
Successfully cleaned artifacts at path /Users/xxxx/azure-agents/main/_work/20/s/Cache/Manifests
Successfully cleaned dependencies at path /Users/xxxx/azure-agents/main/_work/20/s/Tuist/Dependencies
```

**To Reproduce**

1. Run `tuist clean`

**Expected behavior**
Expect `~/.tuist/Cache/Manifests` to be emptied.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]  macOS 12.2.1
- Version [e.g. 22] Tuist version 3.0.1

**Additional context**
I'm currently getting around the issue by running `rm -rf ~/.tuist/Cache` in my build step.

**Comment by danyf90** [comment]
That's strange 🤔 
I have tried locally and I get:
```
⋊> ~/D/_/DFNightSelfies on feature/update_dependencies ◦ tuist clean
Successfully cleaned artifacts at path /Users/xxx/.tuist/Cache/Plugins
Successfully cleaned artifacts at path /Users/xxx/.tuist/Cache/BuildCache
Successfully cleaned artifacts at path /Users/xxx/.tuist/Cache/TestsCache
Successfully cleaned artifacts at path /Users/xxx/.tuist/Cache/Projects
Successfully cleaned artifacts at path /Users/xxx/.tuist/Cache/ProjectDescriptionHelpers
Successfully cleaned artifacts at path /Users/xxx/.tuist/Cache/Manifests
Successfully cleaned dependencies at path /Users/xxx/Developer/project/Tuist/Dependencies
```

@fortmarek any idea of what might be going on?

**Comment by danyf90** [comment]
Yeah I guess the issue then is that stuff get saved there even if you specified a different folder 🤔

**Comment by parse** [comment]
> Yeah I guess the issue then is that stuff get saved there even if you specified a different folder 🤔

Should I rephrase the issue above or will it be confusing?

**Comment by parse** [comment]
> > Yeah I guess the issue then is that stuff get saved there even if you specified a different folder 🤔
> 
> Should I rephrase the issue above or will it be confusing?

Done

**Comment by danyf90** [comment]
Can you also add the info of what you see generated in the local cache, and what you see in the global one? It would make much easier to search for the problem

**Comment by parse** [comment]
> Can you also add the info of what you see generated in the local cache, and what you see in the global one? It would make much easier to search for the problem

Of course. Before these two listings, I made sure to empty both cache folders so these are the only files generated.

This is the `.tuist/Cache` Cache:
```
➜  ~ cd .tuist/Cache
➜  Cache find . -type f

./ProjectDescriptionHelpers/408a825/36bd29f55aa141638d2d89119cadf8a2/ProjectDescriptionHelpers.swiftmodule
./ProjectDescriptionHelpers/408a825/36bd29f55aa141638d2d89119cadf8a2/ProjectDescriptionHelpers.swiftdoc
./ProjectDescriptionHelpers/408a825/36bd29f55aa141638d2d89119cadf8a2/libProjectDescriptionHelpers.dylib
./ProjectDescriptionHelpers/408a825/36bd29f55aa141638d2d89119cadf8a2/ProjectDescriptionHelpers.abi.json
./ProjectDescriptionHelpers/408a825/36bd29f55aa141638d2d89119cadf8a2/ProjectDescriptionHelpers.swiftsourceinfo
./Manifests/1.e5889237106498859602997b1fd487dc
```

This is the folder/project specific cache, set using `cache: .cache(path: .relativeToRoot("Cache"))`: 
```
./Manifests/1.e5889237106498859602997b1fd487dc
./Manifests/1.5f3caf005167b945f271808a3dfee8d4
```

**Comment by fortmarek** [comment]
Hey @parse 

thanks for sending the additional information. What you are seeing is expected. Let me explain why.

The custom cache path is defined in `Config.swift`. But `Config.swift` is a manifest as any other and needs to be parsed. But before it is parsed, tuist does not know the custom location for the cache. Since `Config.swift` can include `ProjectDescriptionHelpers`, they also have to be loaded without being able to reuse any information from `Config.swift` (including custom cache location) - as you can see [here](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Loaders/ManifestLoader.swift#L309-L311).

We can either not cache `Config.swift` and `ProjectDescriptionHelpers` at all (not desirable) or keep storing them in the global cache. I'd argue the current situation is better than the alternative and I don't see a better way to do this _without_ using the env variable of `TUIST_CONFIG_FORCE_CONFIG_CACHE_DIRECTORY`. You can already use it but it's not part of the public API, so we don't provide any assurances about it not breaking between minor versions. I'm not sure if it's a common concern that we are sending _some_ data in the global cache - unless it is, I would not start considering the env variable as public API.

@parse let me know if this has answered your question or if there is something else we can clear up.

**Comment by parse** [comment]
Thanks for your detailed response @fortmarek !

I'll try using this value > TUIST_CONFIG_FORCE_CONFIG_CACHE_DIRECTORY

The confusing thing for me was that the `MARKETING_VERSION` that was stored in the global cache (manifest cache) was not reliable and was using old builds and I have to make sure to delete that folder every time.

**Comment by ezraberch** [comment]
> The custom cache path is defined in `Config.swift`. But `Config.swift` is a manifest as any other and needs to be parsed. But before it is parsed, tuist does not know the custom location for the cache. Since `Config.swift` can include `ProjectDescriptionHelpers`, they also have to be loaded without being able to reuse any information from `Config.swift` (including custom cache location) - as you can see [here](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Loaders/ManifestLoader.swift#L309-L311).

Then `tuist clean` should clean the global cache as well — either the whole thing, or just the part which is still used even If a custom cache path is set.

> The confusing thing for me was that the `MARKETING_VERSION` that was stored in the global cache (manifest cache) was not reliable and was using old builds and I have to make sure to delete that folder every time.

This may be another issue. Can you post a sample project and workflow where this is happening?

**Comment by fortmarek** [comment]
> The confusing thing for me was that the MARKETING_VERSION that was stored in the global cache (manifest cache) was not reliable and was using old builds and I have to make sure to delete that folder every time.

How are you defining the `MARKETING_VERSION`? We have a reference for using environment variables [here](https://docs.tuist.io/guides/environment/). Ideally, create a new issue or discussion for this since it's not directly to the issue raised here.

> Then tuist clean should clean the global cache as well — either the whole thing, or just the part which is still used even If a custom cache path is set.

I agree we should at the very clean the project-related manifests and helpers in the global cache (I'd probably try avoiding purging the whole global cache as I think users wouldn't expect that)

**Comment by pepicrft** [comment]
We didn't design the cache directory to be shared across environments. Therefore, using it for that might cause issues. If you believe this is necessary for your use case, I'd appreciate if you could open another issue where you detail why you want to copy the cache directory, and not the what.
