### ISSUE TITLE
Error: cannot convert value of type '[Any]' to expected argument type 'Project.Options'

### ISSUE THREAD

**Issue by rmnblm** [tuist/tuist#4246]
**Describe the bug**
With version 3.0, `disableBundleAccessors` and `disableSynthesizedResourceAccessors`have been moved from `Config.swift` to `Project.ProjectOption`. After migration, on running `tuist generate`, I get the following error:
```
error: cannot convert value of type '[Any]' to expected argument type 'Project.Options'
```

Even an empty array does not work. What am I doing wrong?

**Expected behavior**
`tuist generate` should work.

**Screenshots**

![CleanShot 2022-03-14 at 16 41 44@2x](https://user-images.githubusercontent.com/5942764/158208177-b4b34670-fa17-446f-bee0-58898c4f2476.png)

![CleanShot 2022-03-14 at 16 42 13@2x](https://user-images.githubusercontent.com/5942764/158208261-5515451d-a1f5-40c7-8a43-d398232549f4.png)

**Desktop (please complete the following information):**

- OS: macOS
- Version: Monterey

**Comment by kwridan** [comment]
Draft

Hi @rmnblm 

I believe this was another breaking change in 3.0 where options are no longer declared as an array, rather it is now a struct. 

An example to look at is this fixture 

https://github.com/tuist/tuist/blob/main/projects/tuist/fixtures/ios_app_with_framework_and_disabled_resources/App/Project.swift


```swift
    options: .options(
        disableBundleAccessors: true,
        disableSynthesizedResourceAccessors: true
    ),
```
