### ISSUE TITLE
Adding FLEX dependency to project

### ISSUE THREAD

**Issue by flejmer** [tuist/tuist#4249]
**Describe the bug**
I've been trying to add [FLEX](https://github.com/FLEXTool/FLEX) dependency to my project as a SPM dependency and I encountered two issues.
First, when defining requirement I used `upToNextMajor(from: "4.5.0")` I got `error: /Package.swift has no Package.swift manifest for version 4.6.1` when there clearly is such file defined in repo.
Second, after that I tried to go with requirement `branch("master")`. That allowed me to successfully run `tuist fetch`. However Xcode wasn't able to build the module with the issues being missing header files. This tool is written in Objective-C so perhaps it has something to do with it. 

**To Reproduce**

First:
1. Add `FLEX` dependency to project with requirement `.upToNextMajor(from: "4.5.0")`
2. Add app target dependency `.external(name: "FLEX")`
3. Run `tuist fetch`

Second: 
1. Add `FLEX` dependency to project with requirement `.branch("master")`
2. Add app target dependency `.external(name: "FLEX")`
3. Run `tuist fetch`
4. Run `tuist generate`
5. Add `import FLEX` somewhere in the app
6. Try to build project
7. See build errors

**Expected behavior**
Using `.upToNextMajor(from: "4.5.0")` should work as expected when adding external dependency. If not that, dependency added with `.branch("master")` should be able to build without missing header files.

**Screenshots**
### First:
<img width="541" alt="Screenshot 2022-03-15 at 09 27 59" src="https://user-images.githubusercontent.com/11304134/158341433-331446fb-b0b9-469f-9381-0ec87271e6f4.png">
<img width="1036" alt="Screenshot 2022-03-15 at 09 28 23" src="https://user-images.githubusercontent.com/11304134/158341470-22c93750-59be-43b8-8c5f-319d657d931a.png">

### Second:
<img width="430" alt="Screenshot 2022-03-15 at 09 28 48" src="https://user-images.githubusercontent.com/11304134/158341503-a8335d88-7d56-4151-b00e-4ee912d0edac.png">
<img width="411" alt="Screenshot 2022-03-15 at 09 33 54" src="https://user-images.githubusercontent.com/11304134/158341526-97dd1356-2a51-4e7f-9eb6-6c0a2c5d1f82.png">
<img width="340" alt="Screenshot 2022-03-15 at 09 34 12" src="https://user-images.githubusercontent.com/11304134/158341541-8c0a0da6-c8dc-4f9e-85bf-77766200206d.png">

**Desktop:**
- OS: [macOS]
- Version [3.0.1]

**Comment by flejmer** [comment]
@danyf90 Thanks for pointing out no `Package.swift`. It seems like they are missing it in every tagged release version so I'm left with `branch("master")` for now. 🤔 I will write an issue about it on their repo.

I just tried `-ObjC` for other linker flags but it behaves the same way unfortunately. I also tried to add project classes manually as in copying files into my project as suggested [here](https://github.com/FLEXTool/FLEX#manual) and faced the same issue with header files.

**Comment by flejmer** [comment]
Update. I noticed that when I try to build `FLEX` module target it builds successfully. However when building the app itself I get lots of those **`.h' file not found with <angled> include; use "quotes" instead`**` errors.

**Comment by danyf90** [comment]
Hello @flejmer , could you please attach a sample project and reproduction steps, so whoever takes care of it can easily reproduce the problem? 🙏

**Comment by danyf90** [comment]
Please try with latest FLEX version which should have fixed SPM support, and reopen if it's still an issue
