### ISSUE TITLE
Custom Build Configuration + Dependencies bug

### ISSUE THREAD

**Issue by vidugloeck** [tuist/tuist#4250]
**Describe the bug**
In a project that has a custom build configuration (e.g. beta) and that also uses external dependencies (e.g. Alamofire), the generated Xcode project fails to compile the custom configuration with following error message: "No such module '<DependencyName>"

**To Reproduce**

1. Clone sample project from: https://github.com/vidugloeck/TuistCustomBuildConfigBug
2. Run `tuist fetch`
3. Run `tuist generate`
4. Select `App` scheme
5. Select `Edit Scheme`
6. Select `Beta` build Configuration
7. Build & Run project

Build should fail with `No such module: Alamofire` error message 

**Expected behavior**
Build should be successful

**Desktop (please complete the following information):**

- OS: macOS 12.2.1
- Version: 3.0.1 

**Additional context**
It is possible to get a successful build by creating a Beta Configuration for Alamofire:
1. Select the Alamofire project in Xcode File navigator (Tuist -> Depencencies -> SwiftPackageManager -> .build -> checkouts)
2. Select Alamofire project in General Tab
3. Click the + Button in Configuration section
4. Select 'Duplicate Release Configuration'
5. Name the new configurateion `Beta`
6. Build & Run

This is obviously not a real fix, as these change are not permantent.

Any help that helps me solving / circumventing this issue is much appreciated! 🙏🏽

**Comment by mflknr** [comment]
Hey,
funnily enough I have the exact same setup and the exact same issue. I circumvented this by adding the the settings you added to the project also to the dependencies as baseSettings. See [here](https://docs.tuist.io/manifests/dependencies/#swiftpackagemanagerdependencies).
