### ISSUE TITLE
Bug: Tuist Plugin task: Running command doesn't work

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4251]
**Describe the bug**
To pass from 2.72 to **3.0.1** we have to pass plugin tasks to cli tasks as it is mandatory.
For that, we inspect an example: (https://github.com/fortmarek/ExampleTuistPlugin)

running tuist tuist-create-file doesn't work

**To Reproduce**

1. Add plugin to your project
2. run tuist fetch (all succeeded)
    Resolving and fetching plugins.
    Cloning plugin from https://github.com/fortmarek/ExampleTuistPlugin.git @ 32485ca12fd6a76681fe6220d07963a87e59a6be
3. run: tuist tuist-create-file -> Error: Unexpected argument 'tuist-create-file'
4. run: tuist create-file -> > Error: Unexpected argument 'create-file'
5. Setting **the tag instead of sha** ...
    Received unexpected response from the network with an url request that sends a GET request to url   'https://github.com/fortmarek/ExampleTuistPlugin.git/releases/download/0.4.0/ExampleTuistPlugin.tuist-plugin.zip'
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

**Expected behavior**
Run tuist-create-file and create the file

**Screenshots**

**Desktop (please complete the following information):**

- OS: M1, Big sur 11.3.1

**Additional context**
There's no a migration steps to migrate from task to cli in plugins

Please let me know if I'm doing something wrong, or simply it's a bug

**Comment by jesus-qt** [comment]
Also the archive element inside the zip that tuist plugin achieve generate is not an executable
* Is it expected?
* Why tuist doesn't move the cli to /usr/local/bin/?
* Can we have an example in templates?

**Comment by danyf90** [comment]
I think you need to use `tuist create-file` instead, but I summon @fortmarek or @laxmorek for confirmation 🙏

**Comment by fortmarek** [comment]
> I think you need to use tuist create-file instead

Yes, that's correct!

> Why tuist doesn't move the cli to /usr/local/bin/?

You can do so yourself - if tuist finds a CLI of `tuist-my-command` and you run `tuist my-command`, it will automatically execute it. Otherwise, it tries to run a CLI that is inside of a _remote_ plugin release artifacts. We currently don't support tasks as local plugins but it is something we are considering going forward.

**Comment by jesus-qt** [comment]
@fortmarek I didn't achieve to do it with your example... There's a GitHub api error

**Comment by jesus-qt** [comment]
@danyf90 @fortmarek Any news?

**Comment by fortmarek** [comment]
Hey @jesus-qt 👋 

For inspiration, you can take a look at the lint plugin [here](https://github.com/tuist/tuist-plugin-lint/tree/main/fixtures/Example1). I plan to look at this but have not had the time, yet. But it's most likely an issue with the example as the plugin functionality should work as of now. Let us know if you run into any issues when creating a new plugin!

**Comment by fortmarek** [comment]
What is your tuist version @lordcodes and what `tuist-lint` version are you using? cc @laxmorek

**Comment by lordcodes** [comment]
Tuist 3.2.0. I used the latest version of lint plugin. However, I've tried again. It looks like a new version of plugin was released right after I tried and that has fixed the issue.

To confirm it didn't work with 0.2.1, but it does work with 0.3.0.

Thank you for checking. As it was released right after I tried I thought I was on latest already, I must not have been.

**Comment by fortmarek** [comment]
Thanks for checking! I'm gonna close this issue now.
