### ISSUE TITLE
external Dependencies not working with Dependencies.swift

### ISSUE THREAD

**Issue by BjoernLindner** [tuist/tuist#4254]
**Describe the bug**
I have an iOS+watchOS App, and for today my project is working perfectly with this Project.swift

`import ProjectDescription
import ProjectDescriptionHelpers

// MARK: - Project

let project = Project(
    name: "TuistExample",
    options: .options(),
    packages: [.remote(url: "https://github.com/hmlongco/Resolver", requirement: .upToNextMajor(from: "1.5.0"))],
    targets: [
        Target(
            name: "WatchApp",
            platform: .watchOS,
            product: .watch2App,
            bundleId: "com.tuistexample.watchkitapp",
            infoPlist: .default,
            dependencies: [
                .target(name: "WatchAppExtension")
            ]
        ),
        Target(
            name: "WatchAppExtension",
            platform: .watchOS,
            product: .watch2Extension,
            bundleId: "com.tuistexample.watchkitapp.extension",
            infoPlist: .default,
            dependencies: [
                .package(product: "Resolver")
            ]
        ),
        Target(
            name: "iOS",
            platform: .iOS,
            product: .app,
            bundleId: "com.tuistexample",
            infoPlist: .default,
            dependencies: [
                .target(name: "WatchApp"),
                .package(product: "Resolver")
            ]
        )
    ],
    schemes: [],
    additionalFiles: [],
    resourceSynthesizers: []
)
`

But because of .package is deprecated, I want to switch to the new solution with the Dependencies.swift file.

**To Reproduce**

So my new Project.swift file looks like:

`import ProjectDescription
import ProjectDescriptionHelpers

// MARK: - Project

let project = Project(
    name: "TuistExample",
    options: .options(),
    targets: [
        Target(
            name: "WatchApp",
            platform: .watchOS,
            product: .watch2App,
            bundleId: "com.tuistexample.watchkitapp",
            infoPlist: .default,
            dependencies: [
                .target(name: "WatchAppExtension")
            ]
        ),
        Target(
            name: "WatchAppExtension",
            platform: .watchOS,
            product: .watch2Extension,
            bundleId: "com.tuistexample.watchkitapp.extension",
            infoPlist: .default,
            dependencies: [
                .external(name: "Resolver")
            ]
        ),
        Target(
            name: "iOS",
            platform: .iOS,
            product: .app,
            bundleId: "com.tuistexample",
            infoPlist: .default,
            dependencies: [
                .target(name: "WatchApp"),
                .external(name: "Resolver")
            ]
        )
    ],
    schemes: [],
    additionalFiles: [],
    resourceSynthesizers: []
)`

and the Dependencies.swift:

`import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/hmlongco/Resolver", requirement: .upToNextMajor(from: "1.5.0")),
    ],
    platforms: [.iOS, .watchOS]
)`

I know there are problems with multi target dependencies, but I thought that I'm using different targets for different platforms, and that would work.

**Expected behavior**
I expected that the new way works the same as the old.

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.2.1
- Xcode 13.3
- tuist 3.0.1

**Comment by BjoernLindner** [comment]
the old way that works:
https://github.com/BjoernLindner/TuistExample/tree/master

the new way
https://github.com/BjoernLindner/TuistExample/tree/notWorking

`% tuist fetch
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
Fetching https://github.com/hmlongco/Resolver from cache
Fetched https://github.com/hmlongco/Resolver (0.95s)
Computing version for https://github.com/hmlongco/Resolver
Computed https://github.com/hmlongco/Resolver at 1.5.0 (0.38s)
Creating working copy for https://github.com/hmlongco/Resolver
Working copy of https://github.com/hmlongco/Resolver resolved at 1.5.0
Swift Package Manager dependencies installed successfully.
Dependencies resolved and fetched successfully.

% tuist generate
Resolved cache profile 'Development' from Tuist's defaults
Target WatchAppExtension has a dependency with target Resolver of type staticFramework for platform 'iOS' which is invalid or not supported yet.
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose`

**Comment by danyf90** [comment]
Maybe this might be solvable by creating a target for each platform when mapping SPM targets :thinking:
WDYT @fortmarek @kwridan @adellibovi

**Comment by BjoernLindner** [comment]
> Maybe this might be solvable by creating a target for each platform when mapping SPM targets 🤔
> WDYT @fortmarek @kwridan @adellibovi

I'm not sure, but I think I have single targets for each platform

**Comment by danyf90** [comment]
If got the issue, the problem is that Tuist generates only one platform for the dependencies (e.g. only iOS) while in your code you will have mixed targets. If tuist would product multiple targets, then you could use the correct dependency depending on your target

**Comment by BjoernLindner** [comment]
ok sounds like I have to wait for this feature and in the meantime i use the old way

**Comment by fortmarek** [comment]
> Maybe this might be solvable by creating a target for each platform when mapping SPM targets 🤔

Yeah, until we have support for multiplatform targets (not sure that will ever come 😅), this sounds like a good workaround 👍

**Comment by BjoernLindner** [comment]
> Maybe this might be solvable by creating a target for each platform when mapping SPM targets 🤔
> WDYT @fortmarek @kwridan @adellibovi

can you please post an example of what you mean?

**Comment by danyf90** [comment]
Right now if you have a depndency `A`, only an `A` target will be created, and it will be for iOS.
With the change it would create something like an `A-iOS` and an `A-watchOS` project, and it would map the `.external(name: "A")` to the right target according to the platform
