### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by haifengkao** [tuist/tuist#4269]
**Describe the bug**
Unable to install plugin

**To Reproduce**

1. `mkdir tuisttest`
2.  `cd tuisttest`
3. `tuist init --platform iOS`
4.  add the following to Config.swift 
```
let config = Config(
    plugins: [
        .git(url: "https://github.com/tuist/ExampleTuistPlugin", tag: "2.0.0"),
    ]
```

5. `tuist generate` shows 
```
Plugin.swift not found at path /Users/lionuser/.tuist/Cache/Plugins/4fad21aa12c1a4e12e11e61ee772a12e/Repository
```

**Expected behavior**
should generate the project successfully

**Desktop (please complete the following information):**

- OS: macOS 12.1
- Version: 3.0.1

**Comment by laxmorek** [comment]
Hey @haifengkao 

You have to call the `tuist fetch` command in order to fetch plugins you defined in you `Config.swift`.

**Comment by haifengkao** [comment]
thanks, it works.
I think it should be mentioned somewhere in https://docs.tuist.io/plugins/using-plugins

**Comment by laxmorek** [comment]
You have right. I will address it 👍
