### ISSUE TITLE
Error message when `tuist generate` fails because of non-fetched plugin should suggest to `tuist fetch`

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#4277]
**Describe the bug**
Currently, if a user does a `tuist generate` without fetching plugins tuist will fail (see #4269).
The error message is not helpful

**To Reproduce**
* `tuist generate` for `app_with_plugins` fixture
* Error does not mention to `tuist fetch` for plugins

**Expected behavior**
* Error should suggest the user to `tuist fetch`

**Comment by danyf90** [comment]
Fixed in 3.8.0
