### ISSUE TITLE
Cache with xcframework creates info.plist with iPhoneSimulator platform

### ISSUE THREAD

**Issue by Banck** [tuist/tuist#4286]
Hello. 
There is an issue with cache frameworks with commands:
```
tuist fetch
tuist cache warm --xcframeworks
tuist generate --xcframeworks
``` 
If there is framework with resources, tuist creates Bundle for it with info.plist.
This info.plist contains key 'CFBundleSupportedPlatforms' and value: '[iPhoneSimulator]'
So, the issue is when trying to upload build to app store, there is error:
`ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/MyApp.app/FramewrokResources.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."`

If remove this key from generated bundle - everything is fine.

**Comment by danyf90** [comment]
@fortmarek @kwridan @adellibovi do you know if there is a reason to enforce that?

**Comment by fortmarek** [comment]
I am not aware of this - afaict, the plist will eventually be generated via [this](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/InfoPlistContentProvider.swift) file and there's no mention of `CFBundleSupportedPlatforms` 🤔  Maybe we need to add that key ourselves based on the target platform? It would be helpful to first know why it's there in the first place, though.

**Comment by kwridan** [comment]
👋

This isn't something Tuist is enforcing per se - I believe it relates to how the framework is built, for debug & simulator platform vs archived for release. 

@Banck when you remove it, do you manually update the info.plist within the XCFramework? or something else?

---

If you're curious a bit more details 🙂

The `Info.plist` generated by Tuist doesn't include said key:

Generating [`ios_app_with_static_frameworks_with_resources`](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_static_frameworks_with_resources)

We can see the generated info plist for on the resource bundles `AResources` is 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
</dict>
</plist>
```

It's not till after build time Xcode adds that key as is based on how the product was built, so for example when building in debug for the simulator, inspecting deprived data, we can see the signed bundle has the following `Info.plist`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>21D62</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleIdentifier</key>
	<string>io.tuist.A.resources</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>AResources</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>iPhoneSimulator</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>19C51</string>
	<key>DTPlatformName</key>
	<string>iphonesimulator</string>
	<key>DTPlatformVersion</key>
	<string>15.2</string>
	<key>DTSDKBuild</key>
	<string>19C51</string>
	<key>DTSDKName</key>
	<string>iphonesimulator15.2</string>
	<key>DTXcode</key>
	<string>1321</string>
	<key>DTXcodeBuild</key>
	<string>13C100</string>
	<key>MinimumOSVersion</key>
	<string>15.2</string>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
</dict>
</plist>
```

Whereas if you were to archive, inspecting the resource bundle's Info.plist within the app now has the `iPhoneOS` key

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>21D62</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleIdentifier</key>
	<string>io.tuist.A.resources</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>AResources</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>iPhoneOS</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>19C51</string>
	<key>DTPlatformName</key>
	<string>iphoneos</string>
	<key>DTPlatformVersion</key>
	<string>15.2</string>
	<key>DTSDKBuild</key>
	<string>19C51</string>
	<key>DTSDKName</key>
	<string>iphoneos15.2</string>
	<key>DTXcode</key>
	<string>1321</string>
	<key>DTXcodeBuild</key>
	<string>13C100</string>
	<key>MinimumOSVersion</key>
	<string>15.2</string>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
</dict>
</plist>
```

**Comment by Banck** [comment]
Hey!
Let met show you an example:
For example, this lib contains json file, so tuist will generate Bundle for it: https://github.com/marmelroy/PhoneNumberKit
So the Dependencies.swift will looks like:
```
let dependencies = Dependencies(
    swiftPackageManager: .init([
        .remote(url: "https://github.com/marmelroy/PhoneNumberKit", requirement: .upToNextMajor(from: "3.3.4")),
    ],
    platforms: [.iOS]
)
```
Then call these commands:
```
tuist fetch
tuist cache warm --xcframeworks
tuist generate --xcframeworks
```
And now open the project and look at info.plist in `PhoneNumberKitResources.bundle`:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/6259254/160269246-92ccb5fe-f460-489c-8d74-19a4c696cdbd.png">

So when you'll try to upload your build to app store, you will get the error, which I mentioned before. The solution is manual remove `iPhoneSimulator` from `CFBundleSupportedPlatforms` key.

**Comment by MarekKojder** [comment]
Hi! I'm having the same issue, but on CI side. Is there any better solution than removing key from plist file?
I'm working on script which will do it for me, but it seems to me an ugly solution.
Thank you in advance!

**Comment by danyf90** [comment]
Just to have the full picture, why do you have the need to use cached binaries for the release? does it make a different to save time (let's say 10 mins?) in that workflow?

**Comment by Banck** [comment]
> Just to have the full picture, why do you have the need to use cached binaries for the release? does it make a different to save time (let's say 10 mins?) in that workflow?

Hey!
Yeah, one of my project has a lot of 3rd party dependencies and cache reduced build time in half.

**Comment by MarekKojder** [comment]
The same here 👍

**Comment by danyf90** [comment]
What I meant is that: is the release a critical path in which saving even 20 minutes makes a difference?

**Comment by Banck** [comment]
> What I meant is that: is the release a critical path in which saving even 20 minutes makes a difference?

Yes, this project contains 7 apps. So when we upload all these targets cache really helps)

**Comment by Arafo** [comment]
Is there any progress on the issue?

**Comment by maxvainshtein** [comment]
We also encountered the same problem in CI and must keep using cache, is it possible to somehow bump this issue?

**Comment by Banck** [comment]
> We also encountered the same problem in CI and must keep using cache, is it possible to somehow bump this issue?

Hello!
For workaround I wrote this script and use it right after tuist generate:
```
# Remove iPhoneSumulator from Bundle's info.plist
for FILE in $(find ~/.tuist/Cache/ -name '*.bundle'); do
PLIST_FILE=$(find $FILE -name 'Info.plist')
plutil -remove CFBundleSupportedPlatforms $PLIST_FILE
done
```

**Comment by pepicrft** [comment]
xcframeworks as a bundle format goes away in Tuist 4 so we are not providing a fix for this. For those of you running into this in Tuist 3.x versions, you can use the fix suggested above.
