### ISSUE TITLE
Graph command follow-up work

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#431]
## What 🌱
There were some ideas for the new [`tuist graph`](https://github.com/tuist/tuist/pull/427) command that I left to be implemented in independent PRs. This issue is a check-list that contains those improvements:

- [x] Add support for a --path argument.
- [ ] Create subgraphs that group elements that belong to the same project.
- [ ] Support viewing the graph. For that , I plan to add an endpoint to galaxy, https://galaxy.tuist.io/graph that renders the graph on a web page.

**Comment by adellibovi** [comment]
@pepibumur, I believe we could check the first item (add support for a --path argument) because of #2434. :)
