### ISSUE TITLE
Tuist is not embedding dynamic frameworks in transitive dependencies

### ISSUE THREAD

**Issue by bvirlet** [tuist/tuist#4316]
I have the following project structure using Tuist "deprecated" dependency management:

```
App1 -> Internal framework (as a target dependency, not a Swift Package)
App2 -> Internal framework (ditto)
Internal framework -> AWS SDK Swift Package (provides dynamic frameworks)
Internal framework -> Swift Package (a bunch of other dynamic frameworks)
```

# The problem
The dynamic frameworks from the leaf packages are not embedded in App1 and App2.

# Context

It used to be incorrectly embedded in Internal framework (with Xcode 13.2.1, see https://bugs.swift.org/browse/SR-14292) so I would end up copying it in the app's Frameworks/ folders as a workaround.

But with Xcode 13.3, the "leaf" frameworks are not even present in the InternalFramework.framework/Frameworks folder, so I don't even have a way of copying them.

I'm following two leads in parallel, but none have been successful so far:

1. Fixing the existing dependency management: is it expected that such frameworks are improperly embedded in my app target?
2. Moving to Dependencies.swift. While I made some progress in that regard, I still have a bunch of issues (notably Objective-C headers not being exposed in the frameworks generated by Tuist), so I'm stuck there.

I would appreciate some direction about where to go as I have hit a dead end.

Thank you!

**Comment by bvirlet** [comment]
A solution that would seem to solve the problem is to remove InternalFramework, and integrate directly all the files within App1 or App2, but that's loosing some reusability and compilation benefits.

**Comment by bvirlet** [comment]
Here is a simple project that reproduces the problem (it's `tuist init`'s output with just adding a dependency).

[dynamic-framework-not-embedded.zip](https://github.com/tuist/tuist/files/8373074/dynamic-framework-not-embedded.zip)

# Actual result

- Notice how AWSCore and AWSS3 are not embedded in the `Tuisttest` app.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/792706/160654056-1d3c664a-e915-4c12-beca-11490f3d838a.png">

- Notice how this results in an error when running on device
```
error: module importing failed: invalid pathname
dyld[2537]: Library not loaded: @rpath/AWSCore.framework/AWSCore
  Referenced from: /private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/TuisttestKit.framework/TuisttestKit
  Reason: tried: '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/TuisttestKit.framework/Frameworks/AWSCore.framework/AWSCore' (no such file), '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/System/Library/Frameworks/AWSCore.framework/AWSCore' (no such file)Library not loaded: @rpath/AWSCore.framework/AWSCore
  Referenced from: /private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/TuisttestUI.framework/TuisttestUI
  Reason: tried: '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/TuisttestUI.framework/Frameworks/AWSCore.framework/AWSCore' (no such file), '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/System/Library/Frameworks/AWSCore.framework/AWSCore' (no such file)
Library not loaded: @rpath/AWSCore.framework/AWSCore
  Referenced from: /private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/TuisttestKit.framework/TuisttestKit
  Reason: tried: '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/TuisttestKit.framework/Frameworks/AWSCore.framework/AWSCore' (no such file), '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (no such file), '/usr/lib/swift/AWSCore.framework/AWSCore' (no such file), '/private/var/containers/Bundle/Application/279D2F52-0641-4207-91A7-2745AE286D8C/Tuisttest.app/Frameworks/AWSCore.framework/AWSCore' (n
(lldb) 
```

# Expected

- AWSCore and AWSS3 should be embedded in Tuisttest app.

**Comment by bvirlet** [comment]
The simplest workaround I have found consists in adding in `App1` and `App2` a direct dependency on the dynamic frameworks. Since this are dynamic libraries, it's ok if they are linked both with the internal framework and the apps, but this plus side is that this will have the effect of embedding the frameworks in the apps.

This is an acceptable workaround for me.

**Comment by danyf90** [comment]
Closed as it regards "legacy" dependency import and there is a good enough workaround for it

**Comment by daumantas-versockas** [comment]
@bvirlet, could you provide a more detailed explanation of your workaround? I am currently having the same issue with dynamic dependencies.
