### ISSUE TITLE
SPM Manifest file generation

### ISSUE THREAD

**Issue by denis-egaluev** [tuist/tuist#4317]
**Describe the bug**
I met a bug in generating the Package manifest in the new Xcode 13.3. Apparently the manifest syntax has been updated.

```
'swiftpackagemanager': error: invalidManifestFormat("/Users/[User]/Development/[Project]/Tuist/Dependencies/SwiftPackageManager/Package.swift:7:10: error: \'package(url:exact:)\' is unavailable
        .package(url: \"[package-url]", exact: \"[package-version]\"),
         ^~~~~~~
PackageDescription.Package.Dependency:20:24: note: \'package(url:exact:)\' was introduced in PackageDescription 5.6
    public static func package(url: String, exact version: PackageDescription.Version) -> PackageDescription.Package.Dependency
                       ^", diagnosticFile: nil)
The 'swift' command exited with error code 1
```

Generated Tuist/Dependencies/SwiftPackageManager/Package.swift manifest file:
```
// swift-tools-version: 5.4
import PackageDescription

let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "[swift-package]", exact: "[package-version]"),
    ]
)
```

Seems like it should be:
```
// swift-tools-version: 5.4
import PackageDescription

let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "[swift-package]", .exactItem("[package-version]")),
    ]
)
```

**To Reproduce**

1. Install Xcode 13.3
2. Add packages as external dependencies
3. Run `tuist fetch`

**Desktop (please complete the following information):**

- OS:  macOS
- Version 3.1.0

**Comment by danyf90** [comment]
Hello 👋 
Maybe I got the problem, are you specifying a swift version is `Config.swift`?

**Comment by danyf90** [comment]
Looks like for some reason your package is being generated with the 5.6 syntax, but in the header you are getting `// swift-tools-version: 5.4` 🤔 
What's the output of `swift --version`?

**Comment by denis-egaluev** [comment]
@danyf90 `swift --version` output:
```
swift-driver version: 1.45.2 Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
Target: x86_64-apple-macosx12.0
```

**Comment by denis-egaluev** [comment]
We resolved the issue by upgrading Swift version to 5.6.0 in the Config.swift file. Thanks a lot for the tip!

**Comment by danyf90** [comment]
So the problem was that you had 5.4.0 in the `Config.swift`? I think it is still an issue as it should be considered when generating the Package.swift
