### ISSUE TITLE
R.swift package dependency doesn't create a project file  

### ISSUE THREAD

**Issue by zeevvax** [tuist/tuist#4319]
**Describe the bug**
Getting an error message when trying to include R.swift
Could not locate project at path: iOS/Frameworks/Assets/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/R.swift

**To Reproduce**
Version 3.0.1

1. Create simple dependency on R.swift 
2. Run, tuist clean 
3. Run, tuist fetch
4. Run, tuist generate 
See screenshots for more info

**Expected behavior**
Project was created

**Screenshots**
<img width="1408" alt="Screen Shot 2022-03-29 at 1 54 06 PM" src="https://user-images.githubusercontent.com/1322662/160705806-a3d47988-5fa5-4e72-9b79-352a5e272c76.png">
<img width="620" alt="Screen Shot 2022-03-29 at 1 54 29 PM" src="https://user-images.githubusercontent.com/1322662/160705815-f3ed980f-b591-40ad-8fb6-5b54ce42752e.png">
<img width="1210" alt="Screen Shot 2022-03-29 at 1 54 57 PM" src="https://user-images.githubusercontent.com/1322662/160705818-2513bdcf-bfae-4389-96c9-5ae6dd6b2106.png">
<img width="991" alt="Screen Shot 2022-03-29 at 2 00 18 PM" src="https://user-images.githubusercontent.com/1322662/160706299-ba820fd2-7980-43a7-a83f-a6b0673c099f.png">

**Desktop (please complete the following information):**

- OS: MacOS 12.3, Xcode 13.3
- Version 3.0.1

**Additional context**

**Comment by danyf90** [comment]
Hello, can you please provide a sample project to reproduce the issue? 🙏

**Comment by danyf90** [comment]
Slightly related question, is there any specific reason why you use R.swift instead of Tuist own resource accessors?

**Comment by apps4everyone** [comment]
can you try with https://github.com/mac-cain13/R.swift.Library ?

**Comment by zeevvax** [comment]
Thanks Dany, we use R.swift for historical reasons but as a follow up to the upgrade to Tuist 3.x we are considering a change to another library. 
Here is a link to a sample project https://drive.google.com/file/d/1jK16Lb0_5cc8gRuuSgzuMSUMA8xex9rJ/view?usp=sharing

**Comment by leszko11** [comment]
Hi @zeevvax 

You need to add both `R.swift` and `R.swift.Library` to `Dependencies.swift` file
```
let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(
            url: "https://github.com/mac-cain13/R.swift",
            requirement: .upToNextMajor(from: "6.0.0")
        ),
        .remote(
            url: "https://github.com/mac-cain13/R.swift.Library",
            requirement: .upToNextMajor(from: "5.4.0")
        ),
    ]
)
```
and declare target dependencies as

```
let dependencies: [TargetDependency] = [
    .external(name: "Rswift")
]
```

**Comment by zeevvax** [comment]
Thanks @leszko11

**Comment by leszko11** [comment]
@zeevvax let me know if it helped

**Comment by danyf90** [comment]
@zeevvax I understand the issue is solved, if it's not the case feel free to reopen it

**Comment by zeevvax** [comment]
Will do, I didn't try it yet. This and other issues were blocking me to use 3.0.1 so I ended up using 2.7.2
