### ISSUE TITLE
Can't add ViewInspector as dependecies to a unit test target using Dependencies.swift

### ISSUE THREAD

**Issue by unxavi** [tuist/tuist#4321]
**Describe the bug**
We are adding https://github.com/nalexn/ViewInspector to our project and is working fine using old package method for SPM. But using `Dependencies.swift` we are getting errors when compiling the tests.

On XCode:

<img width="138" alt="imagen" src="https://user-images.githubusercontent.com/3817679/160936443-557b16e6-d1fe-4955-b233-3e7121282a68.png">

And Running `tuist test`

```
❌ /.../app_with_spm_dependencies_and_tests/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/ViewInspector/Sources/ViewInspector/InspectableView.swift:171:13: cannot find 'XCTFail' in scope
            XCTFail("\(error.localizedDescription)", file: file, line: line)
            ^~~~~~~
❌ /.../app_with_spm_dependencies_and_tests/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/ViewInspector/Sources/ViewInspector/InspectableView.swift:191:13: cannot find 'XCTFail' in scope
            XCTFail("\(error.localizedDescription)", file: file, line: line)
            ^~~~~~~
❌ /.../app_with_spm_dependencies_and_tests/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/ViewInspector/Sources/ViewInspector/InspectableView.swift:211:13: cannot find 'XCTFail' in scope
            XCTFail("\(error.localizedDescription)", file: file, line: line)
            ^~~~~~~
❌ /.../app_with_spm_dependencies_and_tests/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/ViewInspector/Sources/ViewInspector/InspectionEmissary.swift:112:17: cannot find 'XCTFail' in scope
                XCTFail("\(error.localizedDescription)", file: file, line: line)
```
[app_with_spm_dependencies_and_tests.zip](https://github.com/tuist/tuist/files/8384397/app_with_spm_dependencies_and_tests.zip)

**To Reproduce**

1. Use the project attached `app_with_spm_dependencies_and_tests`
2. `tuist fetch`
3. `tuist generate`
4. `tuist test`
5.  Run tests from xcode

**Expected behavior**
We can attach the dependencie to the unit test target

**Desktop (please complete the following information):**

- OS: MasOS 12.21
- XCode: 12.2.1
- M1 CPU

**Comment by danyf90** [comment]
Wave @unxavi 👋 
Can you try to add:
```
    targetSettings: [
      "ViewInspector": ["ENABLE_TESTING_SEARCH_PATHS": "YES"],
    ]
```
to your Dependencies.swift?

It that works, you might want to open a PR to add it to the list of [known test dependencies](https://github.com/tuist/tuist/blob/9c4bdc4927acb78a828dbecdfb0adbb46ec10c52/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L317-L323)

**Comment by unxavi** [comment]
@danyf90 thanks a lot for the suggestion
