### ISSUE TITLE
Can't add Stripe as dependecies to a target using Dependencies.swift

### ISSUE THREAD

**Issue by unxavi** [tuist/tuist#4322]
## Describe the bug
When using Stripe SDK, we can't build the app if the Stripe SDK is added using `Dependencies.swift`

Console output:

> ❌ error: Multiple commands produce '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/Stripe3DS2Resources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeApplePayResources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeCoreResources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeResources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeUICoreResources.bundle/Info.plist':
> ⚠️ duplicate output file '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeUICoreResources.bundle/Info.plist' on task: ProcessInfoPlistFile /..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeUICoreResources.bundle/Info.plist /..../AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeUICoreResources.plist (in target 'StripeUICoreResources' from project 'Stripe')
> ⚠️ duplicate output file '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeApplePayResources.bundle/Info.plist' on task: ProcessInfoPlistFile /..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeApplePayResources.bundle/Info.plist /..../AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeApplePayResources.plist (in target 'StripeApplePayResources' from project 'Stripe')
> ⚠️ duplicate output file '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/Stripe3DS2Resources.bundle/Info.plist' on task: ProcessInfoPlistFile /..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/Stripe3DS2Resources.bundle/Info.plist /..../AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/Stripe3DS2Resources.plist (in target 'Stripe3DS2Resources' from project 'Stripe')
> ⚠️ duplicate output file '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeCoreResources.bundle/Info.plist' on task: ProcessInfoPlistFile /..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeCoreResources.bundle/Info.plist /..../AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeCoreResources.plist (in target 'StripeCoreResources' from project 'Stripe')
> ⚠️ duplicate output file '/..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeResources.bundle/Info.plist' on task: ProcessInfoPlistFile /..../Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeResources.bundle/Info.plist /..../AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeResources.plist (in target 'StripeResources' from project 'Stripe')
> The 'xcodebuild' command exited with error code 65
> Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

**To Reproduce**

[app_with_spm_dependencies_stripe.zip](https://github.com/tuist/tuist/files/8384445/app_with_spm_dependencies_stripe.zip)

1. Open the example project app_with_spm_dependencies_stripe
2. `tuist fetch`
3. `tuist generate`
4. `tuist build`

**Expected behavior**
The project builds normally

**Desktop (please complete the following information):**

- OS: MacOS 12.2.1
- XCode: 12.2.1
- M1 CPU

**Comment by danyf90** [comment]
> The project 'App' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Internal (release), Release (release)]
> The project 'FeatureOne' has missing or mismatching configurations. It has [Debug (debug), Release (release)], other projects have [Debug (debug), Internal (release), Release (release)]

You are adding custom config to your dependency but not to your app, isn't iit?

**Comment by unxavi** [comment]
@danyf90 I had because I took the example from the SPM Fixture from Tuist which it had.

Now I've removed the custom config, but the issues are the same. I updated the sample project without the config
[app_with_spm_dependencies_stripe.zip](https://github.com/tuist/tuist/files/8388285/app_with_spm_dependencies_stripe.zip)

Now the output of `tuist test`

> Generating project for testing
> Target 'Alamofire' has been linked from target 'App' and target 'FeatureOneFramework', it is a static product so may introduce unwanted side effects.
> Generating workspace Tuistplayground.xcworkspace
> Generating project App
> Generating project FeatureOne
> Generating project Stripe
> Generating project Alamofire
> Trying to add a file at path /Users/javiervieiraboccardo/AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCardScan/StripeCardScan/Resources/CompiledModels/SSDOcr.mlmodelc/analytics/coremldata.bin to a build phase that hasn't been added to the project.
> Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
> 

And `tuist  build`


> ❌ error: Multiple commands produce '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/Stripe3DS2Resources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeApplePayResources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeCoreResources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeResources.bundle/Info.plist':
> ❌ error: Multiple commands produce '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeUICoreResources.bundle/Info.plist':
> ⚠️ duplicate output file '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeResources.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeResources.bundle/Info.plist /Users/javiervieiraboccardo/AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeResources.plist (in target 'StripeResources' from project 'Stripe')
> ⚠️ duplicate output file '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeApplePayResources.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeApplePayResources.bundle/Info.plist /Users/javiervieiraboccardo/AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeApplePayResources.plist (in target 'StripeApplePayResources' from project 'Stripe')
> ⚠️ duplicate output file '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeUICoreResources.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeUICoreResources.bundle/Info.plist /Users/javiervieiraboccardo/AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeUICoreResources.plist (in target 'StripeUICoreResources' from project 'Stripe')
> ⚠️ duplicate output file '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/Stripe3DS2Resources.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/Stripe3DS2Resources.bundle/Info.plist /Users/javiervieiraboccardo/AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/Stripe3DS2Resources.plist (in target 'Stripe3DS2Resources' from project 'Stripe')
> ⚠️ duplicate output file '/Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeCoreResources.bundle/Info.plist' on task: ProcessInfoPlistFile /Users/javiervieiraboccardo/Library/Developer/Xcode/DerivedData/Tuistplayground-ftwzfjkmwhilnvfsqnpsizvjsoni/Build/Products/Debug-iphonesimulator/StripeCoreResources.bundle/Info.plist /Users/javiervieiraboccardo/AppCodeProjects/app_with_spm_dependencies_stripe/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Derived/InfoPlists/StripeCoreResources.plist (in target 'StripeCoreResources' from project 'Stripe')
> The 'xcodebuild' command exited with error code 65
> Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
> 

 What do you think? any idea?

**Comment by obrhoff** [comment]
Same problem here.

**Comment by unxavi** [comment]
@danyf90 @fortmarek any input on how we can solve this or how can we help?

**Comment by danyf90** [comment]
I haven't had time to have a look at it.
I would start from trying to understand from where we are getting the duplicated copy resource phase, and checking if removing the duplicate from the Xcode project solves the issue.

If you want to have a look, most of the logic for mapping between SPM and Tuist are in the [PackageInfoMapper](https://github.com/tuist/tuist/blob/main/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift)

**Comment by paulsamuels** [comment]
Not sure if this is helpful or not but the integration of this package ends up being quite different across Tuist versions

Tuist 2.6.0

<img width="1357" alt="Screenshot 2022-04-07 at 09 27 07" src="https://user-images.githubusercontent.com/527091/162158810-f5aeb01b-688f-4294-b75c-6183e93e4d31.png">


Tuist 3.1.0
<img width="1360" alt="Screenshot 2022-04-07 at 09 41 16" src="https://user-images.githubusercontent.com/527091/162158566-fc0307e8-19f1-4b17-8696-4e4f35d46b25.png">

**Comment by danyf90** [comment]
@paulsamuels have you moved from "legacy" package integration to Dependencies.swift? If yes, the change is expected

**Comment by paulsamuels** [comment]
Yeah sorry forgot to mention that 🤦🏻 

Looking at stripes `Package.swift` they are explicitly asking for these files to be processed - I've not got enough context to know if this is right or not

https://github.com/stripe/stripe-ios/blob/master/Package.swift#L45-L53

**Comment by mikchmie** [comment]
In the subject of Info.plists - here's a workaround: https://github.com/tuist/tuist/issues/3597#issuecomment-975316079

As for the problem with `[...]/SSDOcr.mlmodelc/analytics/coremldata.bin` when running `tuist test` - I've been looking at `Sources/TuistGraph/Models/Target.swift`, if adding `"mlmodelc"` to `Target.validFolderExtensions` would resolve the issue, but without any luck.

**Comment by obrhoff** [comment]
Just gave it a try with Tuist 3.3.0. It's still not able to get the Stripe SDK to run. It throws following error message while building. The sample project I attached is still usable to reproduce this issue.

```
type 'Bundle' has no member 'module'
```

**Comment by danyf90** [comment]
@obrhoff we know, indeed https://github.com/tuist/tuist/issues/4095 is still open
