### ISSUE TITLE
Can't use custom config in one project of a workspace or with SPM

### ISSUE THREAD

**Issue by jeandavid** [tuist/tuist#4327]
**Describe the bug**
I have an app and two frameworks, A and B, each with their own xcode project. Whenever I define custom config for the app, I run into these issues:

* Both framework A and B need to have the same config than the app. If not, compilation fails with "No such module Framework A".
* If I set the same config to all three xcode proj, but import an external framework (here Alamofire) via SPM, then compilation fails with "No such module Alamofire"

**To Reproduce**
I have a setup a demo project to reproduce the bug: [https://github.com/jeandavid/DemoTuist](https://github.com/jeandavid/DemoTuist)

**Setup**
macOS: 12.1 
Xcode: 13.3 
tuist: 3.1.0

**Comment by jeandavid** [comment]
1. How would I define custom confit for external dependencies?
2. This is a departure from regular Xcode feature, isn't it? 
3. What if I have a workspace, two app projects, each app with their own set of config. They won't be able to share the same dependencies?

**Comment by danyf90** [comment]
1. You can use base settings: https://tuist.github.io/tuist/main/documentation/projectdescription/swiftpackagemanagerdependencies
2. when importing them via Dependencies.swift, SPM dependencies are seen as any other targets, so the same rules apply to them
3. I guess you just need to make sure your dependencies define all the possible combination of config, but I'm not sure about this

**Comment by jeandavid** [comment]
@danyf90 thank you for your answer! I updated the linked demo project based on your suggestions. It does fix my compilation issue. But then I added a second external deps (in this case `RxSwift`) via SPM, and my custom scheme disappear from the newly generated xcworkspace :(

**Comment by jeandavid** [comment]
@danyf90 I have made an even [cleaner repo ](https://github.com/jeandavid/FirebaseTuistDemo)to reproduce the issue. Simple app importing Firebase via SPM. If I define custom configs and a new scheme depending on the config, then the scheme is not created. I don't encounter this behavior with all frameworks. Only see this issue with Firebase and RxSwift at the moment.

<img width="1050" alt="Screen Shot 2022-04-03 at 12 26 30" src="https://user-images.githubusercontent.com/3328783/161421303-eddbfdc4-47b3-45bd-badb-5d935cda9091.png">

**Comment by danyf90** [comment]
@kwridan do you have any idea why the scheme shouldn't be generated? 🤔

**Comment by ezraberch** [comment]
The scheme isn't being generated because it has only a `RunAction` defined. Here's the relevant code:

https://github.com/tuist/tuist/blob/d9ed9a500500ac2caef7fb791351f0a2524b37cc/Sources/TuistCache/Mappers/Graph/TreeShakePrunedTargetsGraphMapper.swift#L81-L103

As you can see, if neither a `BuildAction` nor a `TestAction` is defined, the scheme will be filtered out. You can test this by adding a `BuildAction` to your sample project, after which the scheme will appear.

**Comment by jeandavid** [comment]
@ezraberch you are right, adding one of these actions enable the scheme to be generated. What troubled me was the fact that I am able to generate scheme for some external SPM dependencies without any build nor test action.
