### ISSUE TITLE
Crash when calling objective-c extension

### ISSUE THREAD

**Issue by haifengkao** [tuist/tuist#4329]
**Describe the bug**
My app crashes when it calls `[NSString cookies]` which is defined in [YWebView](https://github.com/haifengkao/YWebView).
It crashes when I use the preferred `Dependencies.swift` to install `YWebView`.
It won't crash if I use the deprecated `package(name:"YWebView")` syntax.

**To Reproduce**
1. Install  [YWebView](https://github.com/haifengkao/YWebView) by  `Dependencies.swift`
2. create YWebView. 
```swift
import YWebView
var webView = YWebView(frame: .init(origin: .init(x: 0.0, y: 0.0), size: .init(width: 200.0, height: 200.0)))
webView.load(.init(url: URL(string: "https://www.yahoo.com")!))
```

It will crash immediately.

**Expected behavior**
It should be able to call objc extension successfully

**Screenshots**
<img width="556" alt="截圖 2022-04-01 下午4 02 43" src="https://user-images.githubusercontent.com/4080524/161221888-dedccda7-68f4-4322-a5f9-7980d08458c8.png">

**Desktop (please complete the following information):**

- OS: 12.1
- Version: Tuist 3.0.1

**Comment by danyf90** [comment]
Can you try to set the dependency as dynamic in Dependencies.swift?

**Comment by haifengkao** [comment]
@danyf90 add `productTypes: ["YWebView": .framework]` avoids the crash

Should I use dynamic framework for all objc packages?

**Comment by danyf90** [comment]
I don't think it is related to the language, but rather to what the library does. I have seen in the past other libraries working with the UI having a similar behavior, and that's why I suggested it, not because of the language 👌

**Comment by kwridan** [comment]
I suspect this could be caused by missing linker flags, especially for any extensions / categories

The one that comes to mind is `-all_load`.

Reference:

- https://stackoverflow.com/a/3998700

**Comment by kwridan** [comment]
@haifengkao those are the defaults baked, you should still be able to define some of your own in the project manifest file

e.g.

```swift
import ProjectDescription

let project = Project(
    name: "Demo",
    targets: [
        Target(
            name: "Demo",
            platform: .iOS,
            product: .app,
            bundleId: "io.tuist.app",
            infoPlist: .default,
            sources: ["Sources/**"],
            settings: .settings(
                base: [
                    "OTHER_LDFLAGS": ["$(inherited)", "-all_load"],
                ]
            )
        ),
    ]
)
```

Does that help?

**Comment by danyf90** [comment]
@haifengkao let us know if it works, and feel free to reopen the issue if it doesn't
