### ISSUE TITLE
How do I add URL Types via Tuist?

### ISSUE THREAD

**Issue by Ruydita** [tuist/tuist#4342]
## Describe the error and expected behaviour

How do I add URL Types via Tuist?

<img width="932" alt="Снимок экрана 2022-04-07 в 16 28 47" src="https://user-images.githubusercontent.com/43744094/162210346-d0baeefd-e145-4695-b2c1-c2e59b721d87.png">

### Additional context

- macOS version: 11.6
- Tuist version: 3.1.0
- Xcode version: 12.5.1

**Comment by danyf90** [comment]
Hey @Ruydita 👋 
It should be enough to configure your [CFBudnleURLTypes](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleurltypes) in the info plist 🚀

**Comment by Ruydita** [comment]
@danyf90 Thanks you!
