### ISSUE TITLE
FR: Add .xcodesample.plist inside the workspace

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4356]
Nowadays, Xcode can't render README.md.
I realise that when we generate the workspace with tuist, it adds to the workspace a file `.tuist-generated`

Could be great if conditionally in workspace tuist could add the .xcodesample.plist to render the MD.

Thanks in advance

**Comment by danyf90** [comment]
Could you please clarify better what is missing and what would be needed?

**Comment by jesus-mg-ios** [comment]
Yeah, please check it: https://www.youtube.com/watch?v=qwqB0e4s7nc

by the include of xcodesample.plist you can render MD inside Xcode

**Comment by danyf90** [comment]
Ok, I guess it can be part of the workspace options then. Do you want to try to implement it? We can provide pointers on what needs to be changed if you need them 🚀

**Comment by jesus-mg-ios** [comment]
Why not? How can I do it? @danyf90

**Comment by danyf90** [comment]
@kwridan do you want to help? I'm not super familiar with that part of the code :D Otherwise, I'll try to study it a bit when I have time and let you know 🚀

**Comment by kwridan** [comment]
Sure 👍 

Thanks for offering to take this on @jesus-mg-ios 

Before we deep dive into implementation though, worth taking a moment to think through if we'd like this to be part of the public API? I'm a little bit torn on this :/ 

- Seeing it's not a well documented behaviour of Xcode it may change in the future - it might be worth holding off adding it as a public API in Tuist
- On the other hand, we do have prior art where we have implemented undocumented features 😅

Perhaps I would suggest some prefix or clarifying via the docs it's experimental if we go through with it?

---

As for the implementation, an easy integration could be via leveraging a `WorkspaceMapper` that would add said file as a side effect in case a particular flag is enabled in generation options.

- Introduce a new optional property on [`ProjectDescription.Workspace.GenerationOptions`](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/WorkspaceGenerationOptions.swift)  - this is effectively the Tuist public manifest API
- Mirror this option in internal models [`TuistGraph.Workspace.GenerationOptions`](https://github.com/tuist/tuist/blob/main/Sources/TuistGraph/Models/WorkspaceGenerationOptions.swift)
- Ensure the properties are mapped  [`ManifestMapper`](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Models%2BManifestMappers/WorkspaceGenerationOptions%2BManifestMapper.swift) 
- Introduce a new `WorkspaceMapper` that would conditionally add the `.xcodesample.plist` to the workspace directory if the corresponding generation option is set (e.g. [`TuistWorkspaceIdentifierMapper`](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Mappers/Workspace/TuistWorkspaceIdentifierMapper.swift#L9) this is how the `.tuist-generated` file is added)
- Lastly, would be handy to have a sample fixture to demo this in `projects/tuist/fixtures`

Hope this helps

**Comment by kwridan** [comment]
An alternate could be to do a small wrapper script 🙂

```sh
tuist generate
touch Workspace.xcworkspace/.xcodesample.plist
```

**Comment by jesus-mg-ios** [comment]
Thanks @kwridan for the support. Of course I can generate it using a script but I think that's not a great user experience.
Also another people want to include for example IDETemplateMacros.plist inside the workspace, or another kind of files ...

Yas! the .xcodesample.plist is not documented by Apple, but it is wide used in swift tutorials made by himself.

**Comment by danyf90** [comment]
I agree having a wrapper script is not great.
I don't see any problem in adding those configurations to Workspace.generationOptions, if anything changes in Xcode in the future, we can always adapt or drop the feature.

@jesus-mg-ios let us know if you need any additional help on this

**Comment by jesus-mg-ios** [comment]
Perfect @danyf90, I gonna make the change, and make a PR. 
Thanks for your support!

**Comment by jesus-mg-ios** [comment]
@danyf90 @kwridan I code the proposal for the ticket, but I have experimented some problems trying to upload the branch to tuist. Is needed any additional step? Seems like I haven't got permissions to upload it due to the 403 code that I receive pushing the branch.

Thanks in advance.

**Comment by danyf90** [comment]
@allcontributors add @jesus-mg-ios for code

**Comment by danyf90** [comment]
As it's your first PR, you need to fork tuist, create a branch on your fork, and create the PR from your branch to the main tuist.
Or maybe @fortmarek can add you as contributor to the project, looks like I don't have permissions to do so 🤔

**Comment by jesus-mg-ios** [comment]
Yeah, I made it but git is showing me the following error:

Pushing to https://github.com/tuist/tuist.git
remote: Permission to tuist/tuist.git denied to jesus-mg-ios.
fatal: unable to access 'https://github.com/tuist/tuist.git/': The requested URL returned error: 403

**Comment by danyf90** [comment]
You need to fork tuist and push to your fork, from the output you can see you are pushing to https://github.com/tuist/tuist.git

**Comment by jesus-mg-ios** [comment]
Thanks @danyf90
