### ISSUE TITLE
How to custom command line and run local shell.

### ISSUE THREAD

**Issue by ondev** [tuist/tuist#4369]
I want to define a custom command, like tuist up.  and run my local shell.

How to do that in the latest version. in the version 1.x, we can use Setup.swift and tuist up command.

the document not clear, can give us a demo or more detail steps?
https://docs.tuist.io/guides/task

**Comment by danyf90** [comment]
An example is this plugin, but looks like there are some problems if you try to run commands without providing the full path (e.g. that plugin fails to find `swift`)
