### ISSUE TITLE
Support for running `tuist` on linux

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#4370]
There are some scenarios in which it could make sense to run tuist on linux:
- run user defined `tuist task`
- generate on (cheaper) linux machine and then run on macos
- maybe others

At the moment Tuist cannot be run on linux due to some of its dependencies:
- Combine
- Checksum
- KeychainAccess

We should see whether we can:
- replace some of them or improve them to support linux
- reduce the functionality on linux by removing features that requires them, still allowing to use the other features

**Comment by danyf90** [comment]
cc @jaerod95 who started [this thread](https://tuistapp.slack.com/archives/C018QG7U7SN/p1649797573532919)

**Comment by hakonk** [comment]
What was the conclusion here? Messages older than 90 days are not available in the Tuist Slack space.

**Comment by ladislas** [comment]
I would also like to have the ability to run tuist on linux to generate simple command line tools that do require macOS.

**Comment by amarcadet** [comment]
Is it still not planned to support linux? It would be great to run some part of tuist on cheaper machine or in docker.

**Comment by pepicrft** [comment]
> Is it still not planned to support linux? It would be great to run some part of tuist on cheaper machine or in docker.

Which parts would you like to run on a Docker machine?

**Comment by amarcadet** [comment]
Sorry for the delayed answer, I would like to run `fetch` or `generate` but, as I deep dive into Tuist, I figured that it use `xcodebuild` under the hood so it might not be possible.

**Comment by pepicrft** [comment]
Tuist does depend on Xcode heavily, so I don't think the investment in supporting Linux by some workflows is worth it. If the motivation for this is to save costs of macOS CI environments, then I'd rather explore other optimizations that we can perform, for example caching the resolution of dependencies or the loading of the manifests across environments. Those are tackable low-hanging fruits that can bring significant performance improvements.

**Comment by pro100filipp** [comment]
Consider following workflow: someone developing command line tool or server application in Swift that is being deployed to Linux/Docker environment (like AWS EC2 or Fargate) AND wants to utilize all the benefits tuist provides along with using single tool for both client and server development.
I was about to switch from SPM to tuist in my server app but it seems to me that tuist is not aimed at Linux server development right now, isn't it?

**Comment by fortmarek** [comment]
>  I was about to switch from SPM to tuist in my server app but it seems to me that tuist is not aimed at Linux server development right now, isn't it?

Not as of now, no. 

What parts of Tuist would you want to leverage in your Linux server? We plan to eventually make this happen with a subset of Tuist features. As we expand into other domains than project generation, which relies on Xcode being present, the benefits will start to outweigh the investment.

**Comment by pro100filipp** [comment]
> What parts of Tuist would you want to leverage in your Linux server?

As of now - only building/running tests. Alternatively if it'd be possible to use just `swift build/test` it'd be enough also – but SPM does not work with tuist project structure.

**Comment by pepicrft** [comment]
> As of now - only building/running tests. Alternatively if it'd be possible to use just swift build/test it'd be enough also – but SPM does not work with tuist project structure.

Out of curiosity @pro100filipp. What's the motivation of building/testing through Tuist over using SPM's interface in the context of a Swift server app?

**Comment by pro100filipp** [comment]
> What's the motivation of building/testing through Tuist over using SPM's interface in the context of a Swift server app?

Nothing special at all to be honest. It's not specifically "I want to build/test using Tuist" – it's "I can not build/test using `swift build/test` when managing Tuist project structure". Like, there's no `Package.swift` file anymore (at least where and what SPM expects to find it).
Regarding my overall intention to use Tuist over SPM for managing a server-side app project – well, that's simple: I just wanted to use the same instrument both for client and server sides. Besides that, there are no (at the moment) any special requirements to use Tuist for my app – like dynamic/static linking for different modules or special schema management and so on.

**Comment by pepicrft** [comment]
Thanks for sharing the details @pro100filipp.

I recommend to use SPM for the server over Tuist to align the build tool with the one that you'll use to build the app to run it in production—I assume in a Linux server. Tuist's focus is on Apple apps, where we can leverage Xcode projects and build system. While we can map packages to Xcode projects, and we do that when integrating dependencies and also showcase Tuist to package developers, I doubt we'll aim at taking the role of SPM when it comes to building sever apps.


Hopefully minor inconveniences in SPM and its flexibility when used within Xcode will be addressed by Apple in the near future.
