### ISSUE TITLE
Warnings when using Tuist cloud cache xcframeworks

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4371]
## Warnings appear in Xcode 13.x.x

When we use in another machine the xcframeworks that are generated and cached with tuist cloud, Xcode advise us about a the lack of a file reference (that is not relative) 

⚠️ /Users/THE_USER_THAT_BUILT_WITH_FRAME_WORK_TUIST/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/24Q1040QE5WX5/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
⚠️ /Users/THE_USER_THAT_BUILT_WITH_FRAME_WORK_TUIST/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/24Q1040QE5WX5/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory

**Comment by fortmarek** [comment]
Hey @jesus-mg-ios 👋 

is that related to a specific xcframework or does it happen with all of them?

**Comment by jesus-mg-ios** [comment]
Yeah, It happens with whatever framework

**Comment by danyf90** [comment]
@jesus-mg-ios we are not getting that warning. can you please add a sample project that generates it an xcframework with this warning?

**Comment by danyf90** [comment]
Closing until reproducible
