### ISSUE TITLE
`tuist fetch` is not working as expected when modifying carthage dependency

### ISSUE THREAD

**Issue by dvkellerman** [tuist/tuist#4374]
## Describe the bug and the expected behavior
In my project i had to fork RxFlow to add Apple Silicon architecture for iOS Simulator. 
I changed the Dependencies.swift and replaced the carthage url with forked repo url.
**Expected Behaviour:** 
`tuist fetch`  should fetch the forked repository of RxFlow. 
**Actual Behaviour:** 
`tuist fetch`  still checkouts the official RxFlow repo.

**What i have tried:**
Cleaned the carthage cache directory`rm -rf ~/Library/Caches/org.carthage.CarthageKit`. But no success.
_What is really strange:_ when i manually do `carthage checkout` with tuist generated Cartfile then my forked library is checked out.

**Question:**
Can some one tell me if tuist does something under the hood what is causing this behavior? 
Maybe tuist has some custom carthage cache directory?

### Additional context
- macOS version: 12.3
- Tuist version:     3.2.0
- Xcode version:  13.2.1

**Comment by danyf90** [comment]
Can you add the sample project as indicated in the issue template?
