### ISSUE TITLE
Custom schemes automatically inherit a run target when one is not specified

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4375]
## Describe the bug and the expected behavior

I'm trying to create a custom scheme for the workspace, because I have to run the tests in a specific configuration name, for example I could get something like 3 configurations debug test release, and I want to have a test action inside of a workspace scheme that runs with test configuration.

I tried with lots of configurations but no one create the newScheme.

## Reproduction steps
```
let workspace = Workspace(
    name: "NAME",
    projects: [
        .... 
    ],
    schemes: [Scheme(name: "NewScheme",
                     shared: true,
                     hidden: false,
                     buildAction: BuildAction(targets: [.init(stringLiteral: "TestTarget"), .init(stringLiteral: "TestTarget2")]),
                     testAction: TestAction.targets([.init(target: .init(stringLiteral: "Module1"), .init(target: .init(stringLiteral: Module2") ],
                                                    configuration: ConfigurationName(stringLiteral: "Test"),
                                                    attachDebugger: true,
                                                    options: .options()),
                     runAction: .runAction(configuration: ConfigurationName(stringLiteral: "Test"), attachDebugger: false, preActions: [], postActions: [], executable: nil, arguments: nil, options: .options(language: nil, storeKitConfigurationPath: nil, simulatedLocation: nil), diagnosticsOptions: []),
                     archiveAction: ArchiveAction.archiveAction(configuration: .release)
                    )],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes:
                .disabled
                //.enabled(codeCoverageMode: .all, testingOptions: .init())
    )
)
```
### Error Comment

The  scheme "NewScheme" doesn't appear.

### Additional context

- macOS version: 12.3
- Tuist version: 3.2.0
- Xcode version: 13.2.1

### Suggestions

Could be great if once created the workspace you can modify the workspace scheme configuration variable before end the swift file.

**Comment by jesus-mg-ios** [comment]
Also I tried to create the scheme with a testPlan (that is the road) and doesn't work

**Comment by kwridan** [comment]
Hi @jesus-mg-ios 

I'm surprised the scheme doesn't appear at all 🤔

We have a few different fixtures that demo this:

- [`ios_app_with_custom_scheme`](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_custom_scheme) for custom workspace schemes
- [`ios_app_with_multi_configs`](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_multi_configs) for custom configurations beyond debug and release _(take note of the how the individual projects are defined too)_

Worth locally testing that to see if you still can't see the custom workspace scheme.

I noticed a few small errors with the scheme definition which may explain why it may have not resulted in generation a valid scheme. As this is a workspace scheme  (one that can include targets from many projects) the longer form target references that include their project paths is needed.

e.g. 

```swift
// For targets
.project(path: "Modules/Module1", target: "Module1")

// For test targets
TestableTarget(target: .project(path: "Modules/Module1", target: "Module1Tests"))
```

For the configuration names, the `stringLiteral` initialiser isn't intended to be used directly, the idea there is to leverage raw strings or possibly strongly typed pre-defined types.

e.g.

```swift
configuration: "Test" // or .configuration("Test")
```

or

```
extension ConfigurationName {
  static var test: ConfigurationName {
      .configuration("Test")
  }
}

// ... and then in the scheme definition
configuration: .test
```

putting all that together, the example you provided would look something like this:

```swift
let workspace = Workspace(
    name: "Workspace",
    projects: [
       // ...
    ],
    schemes: [
        Scheme(
            name: "NewScheme",
            buildAction: .buildAction(
                targets: [
                    .project(path: "Modules/Module1", target: "Module1"),
                    .project(path: "Modules/Module2", target: "Module2"),
                ]
            ),
            testAction: .targets(
                [
                    TestableTarget(
                        target: .project(path: "Modules/Module1", target: "Module1Tests")
                    ),
                    TestableTarget(
                        target: .project(path: "Modules/Module2", target: "Module2Tests")
                    ),
                ],
                configuration: "Test"
            )
        ),
    ]
)
```

Hope this helps!

**Comment by jesus-mg-ios** [comment]
Yeah, it works, thanks a lot. @jesus-mg-ios
Also I'm facing to change the run action, but seems like it doesn't work or I'm doing something wrong.

As I can see, the same behaviour is reproduced in the example [ios_app_with_multi_configs](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_multi_configs)

<img width="994" alt="image" src="https://user-images.githubusercontent.com/85997060/163689137-5b947590-fbcd-4d9b-b2ee-daaca7101430.png">


The executable always is set, if the there's a target app inside the buildAction 

<img width="979" alt="image" src="https://user-images.githubusercontent.com/85997060/163689151-c34b781a-03c7-4d3d-b6d3-d37684e26764.png">
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/85997060/163689234-2523dbf9-988f-46a2-a5fa-811799f336a3.png">

**Comment by kwridan** [comment]
> Always The executable is set to the app, if the there's a target app inside the buildAction, instead of be "None" selected.

Is your goal to have no app selected? 

I believe you're hitting one of the default behaviour in scheme generation https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/SchemeDescriptorsGenerator.swift#L409 

Where a default target is selected if no executable target is specified :/ - we can look to see if that is accidental or on purpose for some of the existing behaviours.

**Comment by jesus-mg-ios** [comment]
Thanks @kwridan for the support.
Yeah, because I don't want to run this scheme, only is for testing purpose.
