### ISSUE TITLE
.sdk dependencies are not transitively linked when used with static frameworks and libraries

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#438]
**Describe the bug**

SDK dependencies for static frameworks or libraries aren't transitively being linked.

**To Reproduce**

1. Add an ObjC++ file that includes some c++ code to `fixtures/ios_app_with_static_frameworks/Modules/C`

```objective-c++
// MyObjcppClass.mm
#include <iostream>

@implementation MyObjcppClass

- (void)hello
{
   std::cout << "Hello from cpp" << std::endl;
}

@end
```

2. Ensure the code is used by the module (internally or externally)
3. Update the project manifest to include `.sdk(name: "libc++.tbd")` (and the `headers`)

```swift
Target(name: "C",
       platform: .iOS,
       product: .staticFramework,
       bundleId: "io.tuist.C",
       infoPlist: "Info.plist",
       sources: "Sources/**",
       headers: Headers(public: "Sources/**/*.h"),
       dependencies: [
          .sdk(name: "libc++.tbd")
    ])
```

4. Run `tuist generate` within `fixtures/ios_app_with_static_frameworks/`
5. Open the generated workspace and build the Scheme `App` or `CTests`
6. **The build yields linking errors**

```
Undefined symbols for architecture x86_64:
  "std::__1::ios_base::getloc() const", referenced from:
      std::__1::basic_ios<char, std::__1::char_traits<char> >::widen(char) const in C(MyObjcppClass.o)
  "std::__1::ios_base::clear(unsigned int)", referenced from:
      std::__1::ios_base::setstate(unsigned int) in C(MyObjcppClass.o)
...
```

_Manually adding `.sdk(name: "libc++.tbd")` to `CTests` or `App` resolves the issue._

**Expected behavior**

- `.sdk` dependencies are transitively linked to the final linking destinations (e.g. Applications, test targets or dynamic frameworks)

**Desktop (please complete the following information):**

- Version 0.16

**Comment by pepibumur** [comment]
Good catch here @kwridan
