### ISSUE TITLE
Add support for WatchOS tests with a Target Application

### ISSUE THREAD

**Issue by Smponias** [tuist/tuist#4382]
## Describe the bug and the expected behavior

Create a WatchApp target and a WatchAppTest target with WatchApp as target. 
Everything should work fine. But it says:
`TargetNameTests has a dependency with target Name of type application for platform 'watchOS' which is invalid or not supported yet.`

## Steps to reproduce 

`tuist init`
`tuist edit`

In `Project.swift` change platform to `.watchOS`

`tuist generate`

**Comment by danyf90** [comment]
Makes sense, I think it's just a use case we haven't faced yet.
Would you like to add it to the valid configurations? It should be something similar to [this PR](https://github.com/tuist/tuist/pull/4211/files)

**Comment by Smponias** [comment]
Yeah sure, I will try it. :)
