### ISSUE TITLE
Watch app bundleId isn't prefixed with its parent's app bundleId & Watch extension bundleId isn't prefixed with its parent's watch app bundleId

### ISSUE THREAD

**Issue by wojtek717** [tuist/tuist#4394]
## Describe the bug and the expected behavior

`tuist generate` command fails when project uses xcconfig files with generic values for bundleId argument creating watch targets.

Tuist should be able to generate project with Bundle Id for watch targets declared in xcconfig file.
## Reproduction steps

Steps to reproduce the bug:

1. Provide xcconfig file with `$(WATCH_APP_PRODUCT_BUNDLE_IDENTIFIER)` property and `$(WATCH_EXTENSION_PRODUCT_BUNDLE_IDENTIFIER)` property
2. Assign the value `$(WATCH_APP_PRODUCT_BUNDLE_IDENTIFIER)` to the argument bundleId creating the watch2App target
3. Assign the value `$(WATCH_EXTENSION_PRODUCT_BUNDLE_IDENTIFIER)` to the argument bundleId creating the watch2Extension target
4. run `tuist generate` command

### Error log
Tuist fails with error:

```
Watch app '' bundleId: $(WATCH_APP_PRODUCT_BUNDLE_IDENTIFIER) isn't prefixed with its parent's app '$(PRODUCT_BUNDLE_IDENTIFIER)' bundleId '$(PRODUCT_BUNDLE_IDENTIFIER)'
Watch extension '' bundleId: $(WATCH_EXTENSION_PRODUCT_BUNDLE_IDENTIFIER) isn't prefixed with its parent's watch app '$(WATCH_APP_PRODUCT_BUNDLE_IDENTIFIER)' bundleId '$(WATCH_APP_PRODUCT_BUNDLE_IDENTIFIER)'
```

### Additional context

- macOS version: 12.2.1
- Tuist version: 3.2.0
- Xcode version: 13.3.1

**Comment by kwridan** [comment]
Thanks for raising this @wojtek717 

For completeness re-posting a suggested alternate for this :)

https://github.com/tuist/tuist/pull/4395#pullrequestreview-951819268
