### ISSUE TITLE
`tuist fetch` fails when a package name doesn't match the Github repo name

### ISSUE THREAD

**Issue by victor-sarda** [tuist/tuist#4411]
## Describe the bug and the expected behavior
I'm currently having an issue with `tuist fetch` on a project that has a local swift Package as a dependency. The package itself has an external dependency to [Cloudinary](https://github.com/cloudinary/cloudinary_ios.git). Cloudinary repo's name doesn't match their package name (`cloudinary_ios` & `Cloudinary`) and it seems like this makes `tuist fetch` fail. I've linked a test project to reproduce the issue.

The test project is quite simple. It has a base project (`tuist init`) and a dependency to a local swift package (in `/Modules`):
```swift
let dependencies = Dependencies(
    swiftPackageManager: [
        .local(path: "Modules/MyPackage")
    ],
    platforms: [.iOS]
)
```

`MyPackage` is also a very simple test package with an external dependency to Cloudinary:

```swift
let package = Package(
    name: "MyPackage",
    products: [
        .library(
            name: "MyPackage",
            targets: ["MyPackage"]),
    ],
    dependencies: [
        .package(url: "https://github.com/cloudinary/cloudinary_ios", from: "3.2.1"),
    ],
    targets: [
        .target(
            name: "MyPackage",
            dependencies: [
                .product(name: "Cloudinary", package: "cloudinary_ios"),
            ]),
        .testTarget(
            name: "MyPackageTests",
            dependencies: ["MyPackage"]),
    ]
)
```
To prove this was linked to the repo's name not matching the package name, I [forked](https://github.com/victor-sarda/Cloudinary) Cloudinary's package and named the repo `Cloudinary` instead of `cloudinary_ios`. This way, `tuist fetch` worked as expected.

I also observed the same issue with one of our packages at Just Eat: https://github.com/justeat/iOS.ErrorUtilities. The fork workaround also worked.

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project: [TestProject.zip](https://github.com/tuist/tuist/files/8584389/TestProject.zip)
2. Run `tuist fetch`
3. See the error "The product Cloudinary of package cloudinary_ios cannot be found."

### Error log

```bash
❯ tuist fetch
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
Fetching https://github.com/cloudinary/cloudinary_ios from cache
Fetched https://github.com/cloudinary/cloudinary_ios (0.60s)
Computing version for https://github.com/cloudinary/cloudinary_ios
Computed https://github.com/cloudinary/cloudinary_ios at 3.2.1 (0.02s)
Creating working copy for https://github.com/cloudinary/cloudinary_ios
Working copy of https://github.com/cloudinary/cloudinary_ios resolved at 3.2.1
The product Cloudinary of package cloudinary_ios cannot be found.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### Additional context

- macOS version: 12.2
- Tuist version: 3.3.0
- Xcode version: 13.2.1

**Comment by victor-sarda** [comment]
Closing as it's a duplicate of https://github.com/tuist/tuist/issues/4303 applying the suggestion from this [comment](https://github.com/tuist/tuist/issues/4303#issuecomment-1081079787) worked 🎉

**Comment by danyf90** [comment]
@victor-sarda should be fixed in [this PR](https://github.com/tuist/tuist/pull/4529), could you please verify?

Once you are on that branch, you can test it by running `./fourier tuist fetch --path /path/to/your/project`
