### ISSUE TITLE
Add more understandable logging

### ISSUE THREAD

**Issue by denizdogan** [tuist/tuist#4430]
## Describe the bug and the expected behavior

Sometimes when I generate my project, basically, nothing happens. The Xcode doesn't open the project and I have no idea why. Sometimes `tuist clean` followed by `tuist fetch` and THEN `tuist generate` solves it, sometimes I'm left just empty-handed in terms of what just happened. Even with `tuist generate --verbose` most of the time I have no idea why it didn't "work".

## Reproduction steps

I can't provide the source code I'm working with, but it's relatively simple. It has about 10 dependencies, a single project, a single app target.

### Error log

```
$ tuist generate
Resolved cache profile 'Development' from Tuist's defaults
```

(That's all, nothing happens after.)

### Additional context

- macOS version: 12.3.1
- Tuist version: 3.3.0
- Xcode version: 13.3.1

I started using this tool this weekend, so I'm relatively new to how everything's supposed to work. It would be very helpful if there were user-friendly messages telling me in plain words what could be the issue.

**Comment by fortmarek** [comment]
> I started using this tool this weekend, so I'm relatively new to how everything's supposed to work. It would be very helpful if there were user-friendly messages telling me in plain words what could be the issue.

Ouch, that's sad to hear 😞 

This case seems like some infinite loop - I remember seeing something like this when we moved to `async` API from Apple (cc @adellibovi). This specific case is going to be hard to fix unless we can more reliable reproduce it. Can you see the same behaviour in one of this [fixture apps](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures) we have inside our repo? As soon as we can reproduce, it is going to be easier to fix it.

**Comment by denizdogan** [comment]
@fortmarek Heheh, don't be sad, it's expected! ;) 

I think I worked my way around this issue by resorting to the now-deprecated way of defining dependencies. This issue was intended to be more general however, not specifically about this problem I was facing! For example, Elm has super-friendly and helpful error messages, basically guiding you towards where you should be looking for the fix.

https://elm-lang.org/news/compiler-errors-for-humans

Something to strive for, perhaps?

**Comment by denizdogan** [comment]
For example, currently the tool says something along the lines of "invalid dependency X" (don't remember the exact phrasing) when the solution is usually that you just forgot to do `tuist fetch`. IMO it would be good to have a sort of framework around some of the possible errors, where we can suggest a few different solutions. I don't think it would require that much effort.

**Comment by fortmarek** [comment]
> For example, currently the tool says something along the lines of "invalid dependency X" (don't remember the exact phrasing) when the solution is usually that you just forgot to do tuist fetch

I agree it's great to make suggestions what next steps a developer should take! For this specific case, we can potentially run `tuist fetch` automatically (see [here](For example, currently the tool says something along the lines of "invalid dependency X" (don't remember the exact phrasing) when the solution is usually that you just forgot to do tuist fetch)).
