### ISSUE TITLE
Bug: SPM error: Tuist doesn't generate the derived file Bundle+StripeCore for Stripe dependency

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4435]
## Describe the bug and the expected behavior
* Tuist 3.3.0
* SPM

I'm using SPM to download Stripe dependency in an M1.
I've experimented an error building the StripeCore.

Seems like Tuist doesn't generate the derived file for Bundle+StripeCore

<img width="407" alt="image" src="https://user-images.githubusercontent.com/85997060/167400009-4bfddb58-91e9-4f8a-a247-cd76a846b607.png">

Because of it, when I try to build it, I get an error:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/85997060/167400186-16045a1c-99cf-4b43-a111-1612f830e71f.png">

## Reproduction steps

Steps to reproduce the bug:

1. Tuist 3.3.0
2. add in Dependencies.swift `.package(url: "https://github.com/stripe/stripe-ios", .exact("22.1.1")),`
3. run tuist fetch
3. run tuist cache warm --xcframeworks

## Error
```
/Users/USER/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCore/StripeCore/Source/Helpers/StripeCoreBundleLocator.swift:15:44: Type 'Bundle' has no member 'module'
```

### Error screenshots

<img width="407" alt="image" src="https://user-images.githubusercontent.com/85997060/167400009-4bfddb58-91e9-4f8a-a247-cd76a846b607.png">
<img width="685" alt="image" src="https://user-images.githubusercontent.com/85997060/167400186-16045a1c-99cf-4b43-a111-1612f830e71f.png">

### Additional context

- macOS version: 12.3 M1
- Tuist version: 3.3.0
- Xcode version: 13.2.1

I think, that for more context you can review this file `Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift`

These are the files generated by Tuist. Notice that there are more files that are not included inside the project, and there's no file called  `Bundle+StripeCore`

<img width="565" alt="image" src="https://user-images.githubusercontent.com/85997060/167410813-96284030-1a23-4d0d-8aaf-bc979ffffc05.png">

**Comment by danyf90** [comment]
This is because Tuist 3.3.0 can't handle default SPM resources.
It has been fixed in main and be available in 3.4.0.
Closing as duplicate 🚀

**Comment by obrhoff** [comment]
I just gave it a try with 3.4.0. Unfortunately it's still there.

**Comment by fortmarek** [comment]
@danyf90 any ideas here?

**Comment by obrhoff** [comment]
Here is a example project, if it helps.

[Stripe-Tuist-Bug.zip](https://github.com/tuist/tuist/files/8708886/Stripe-Tuist-Bug.zip)

**Comment by danyf90** [comment]
> Here is a example project, if it helps.
> 
> [Stripe-Tuist-Bug.zip](https://github.com/tuist/tuist/files/8708886/Stripe-Tuist-Bug.zip)

Looks like the zip is corrupted, could you please upload it again?

**Comment by obrhoff** [comment]
Can you try out this link?

[Tuist-Dependency-Bug.zip](http://droplr.obrhoff.de/vfSgTl)

**Comment by danyf90** [comment]
Looks like they are filtered out because `lproj` is not a [`validFolderExtensions`](https://github.com/tuist/tuist/blob/2a728bec40f4df26288467506b652871ee348167/Sources/TuistGraph/Models/Target.swift#L13-L15).
@fortmarek do you know how it works when lproj are imported as resources in a normal Tuist project? 🤔

**Comment by fortmarek** [comment]
> do you know how it works when lproj are imported as resources in a normal Tuist project? 🤔

I don't know but I'd suggest creating a fixture (dedicated to `lproj` or with the Stripe dependency) and seeing what happens when you make `lproj` a valid extension.

**Comment by shahzadmajeed** [comment]
fwiw: I was facing a similar issue after following documents

https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package
https://developer.apple.com/documentation/swift_packages/localizing_package_resources

I had removed explicit `[.process("Resources"]` from Package.swift because Apple said default resources are picked up but package automatically which they are and package works perfectly fine BUT tuist stopped generating Bundle.module so I had to add explicit `[.process("Resources"]` back

**Comment by danyf90** [comment]
@fortmarek sine lproj are handled well when declared explicitly, I don't think we should add it to that list, but they probably follow a different logic.

I'll try to have a look if I find the time

**Comment by unxavi** [comment]
is it possible to have to know the state of this issue? We have an issue that we can't update Firebase to version 9.x becuase Tuist 3.3.0 does not support it, until Tuist 3.5.0.

But Tuist 3.5.0 does not support Stripe currently 😢

**Comment by danyf90** [comment]
> is it possible to have to know the state of this issue? We have an issue that we can't update Firebase to version 9.x becuase Tuist 3.3.0 does not support it, until Tuist 3.5.0.
> 
> 
> 
> But Tuist 3.5.0 does not support Stripe currently 😢 

If you want to have a look at it we are happy to help
