### ISSUE TITLE
Missing modulemap file

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#4436]
### Discussed in https://github.com/tuist/tuist/discussions/4428

<div type='discussions-op-text'>

<sup>Originally posted by **denizdogan** May  8, 2022</sup>
I have a project with a single target which depends on CleverTapSDK, but I think it's suffering from the familiar issue that can happen when it's an Objective-C library. I am trying to figure out what the HEADER_SEARCH_PATHS setting should be exactly. I've tried the below, but it just doesn't work. The generated project can't find the symbols I'm trying to import from the library.

```
let appAlpha = Target(
    ...
    dependencies: [
        ...
        .external(name: "CleverTapSDK"),
    ],
    settings: .settings(
        base: [
            "HEADER_SEARCH_PATHS": [
                "Tuist/Dependencies/SwiftPackageManager/.build/checkouts/clevertap-ios-sdk/CleverTapSDK/include",
            ]
        ]
    )
)
```

Any ideas?</div>

A working solution has been posted by @denizdogan [here](https://github.com/tuist/tuist/discussions/4428#discussioncomment-2707631) but we should still handle this automatically.

**Comment by danyf90** [comment]
Using the `HEADER_SEARCH_PATHS` should be possible to workaround this, the solution with the `MODULEMAP_FILE` configuration will break tuist caching as the modulemap needs absolute paths.
If we manage to merge [this](https://github.com/tuist/tuist/pull/4002) we should be able to automatically set the proper `HEADER_SEARCH_PATHS` to the dependencies

**Comment by danyf90** [comment]
https://github.com/tuist/tuist/issues/4688
