### ISSUE TITLE
[Dependencies] Graph.json uses incorrect path to xcconfig when using a local package

### ISSUE THREAD

**Issue by parse** [tuist/tuist#4443]
## Describe the bug and the expected behavior

When using a custom configuration with Swift Package Manager, it uses the wrong path to the xcconfig.

In my case, I've created a simple package that I import locally. It also has a dependency that it fetches remote (to show that its xcconfig path becomes correct)

`Dependencies.swift`:

```
import ProjectDescription
let dependencies = Dependencies(
    swiftPackageManager:
        SwiftPackageManagerDependencies([
            .remote(
                url:  "https://github.com/AliSoftware/Dip",
                requirement: .exact("7.1.1")
            ),
            .local(path: .relativeToRoot("Packages/TestPackage"))
        ],
        baseSettings: .settings(configurations: [
            .debug(
                name: "Dev",
                xcconfig: .relativeToRoot("Config/Dev.xcconfig")
            ),
            .debug(
                name: "Prod",
                xcconfig: .relativeToRoot("Config/Prod.xcconfig")
            ),
        ])),
    platforms: [.iOS]
)

```

A `Package.swift` with this content:
```
// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "TestPackage",
    defaultLocalization: "sv",
    platforms: [.iOS(.v14)],
    products: [
        .library(
            name: "TestPackage",
            targets: ["TestPackage"]
        ),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "TestPackage",
            dependencies: []
        )
    ]
)

```

I expect the path to the xcconfig in my `graph.json` to be:
```
 "xcconfig" : "\/Users\/myusername\/prog\/graphtuist\/Config\/Dev.xcconfig",
```

Instead, for my local package `TestPackage` it becomes:
```
"xcconfig" : "\/Users\/myusername\/Config\/Dev.xcconfig",
```

For the other dependency (Dip), it becomes the correct one.

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project ([graphtuist.zip](https://github.com/tuist/tuist/files/8679483/graphtuist.zip))
2. Run `tuist fetch`
3. See the above path that is wrong.

### Error log

It cant generate the project with `tuist generate` since the file `/Users\/myusername\/Config\/Dev.xcconfig` does not (and should not) exists.

### Additional context

- macOS version: 12.3.1
- Tuist version: 3.3.0
- Xcode version: 13.3.1

**Comment by danyf90** [comment]
@parse @shahzadmajeed that's definitely an issue!

If you want to give it a try, let us know and we can provide some pointers 🚀

**Comment by shahzadmajeed** [comment]
@parse which command did you use to generate graph.json? I used `tuist graph -f json` but it didn't include `xcconfig:` in json file

**Comment by shahzadmajeed** [comment]
Oh looks like `graph -f json -p Tuist` includes those paths

**Comment by shahzadmajeed** [comment]
@parse, @danyf90 I can take a look into this issue if you guys haven't started looking already?

**Comment by danyf90** [comment]
Sure @shahzadmajeed ! 🎉

**Comment by parse** [comment]
Thanks for taking a look at this @shahzadmajeed 

Looking forward to testing this!
