### ISSUE TITLE
Bundle accessors lead to a compile error

### ISSUE THREAD

**Issue by evilhonda3030** [tuist/tuist#4467]
## Describe the bug and the expected behavior

The problem is with algorithm used for generation bundle accessors. Seems it generates two bundle accessors with the same name for a single dependency. Unfortunately, disabling bundle accessors in project initializer doesn't help because they are still generated for dependencies. 

## Reproduction steps

I attach a sample project to reproduce an issue.

Steps to reproduce the bug:

1. tuist fetch 

2. tuist generate

3. Build fails with error
### Error log

error: filename "Bundle+MapboxMaps.swift" used twice: '/Users/egormikhailov/Documents/Test/TestTestTuist/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/mapbox-maps-ios/Derived/Sources/Bundle+MapboxMaps.swift' and '/Users/egormikhailov/Documents/Test/TestTestTuist/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Foundation/Extensions/Bundle+MapboxMaps.swift'
note: filenames are used to distinguish private declarations with the same name
### Additional context

- macOS version: 12.2.1
- Tuist version: 3.4.0
- Xcode version: 13.2.1

[ProjectToReproduceIssue.zip](https://github.com/tuist/tuist/files/8732562/ProjectToReproduceIssue.zip)

**Comment by danyf90** [comment]
Looks like I can't download the library and hence can't replicate it:
```
error: error: failed downloading 'https://api.mapbox.com/downloads/v2/mapbox-common/releases/ios/packages/21.3.0/MapboxCommon.zip' which is required by binary target 'MapboxCommon': badResponseStatusCode(401)failed downloading 'https://api.mapbox.com/downloads/v2/mobile-maps-core/releases/ios/packages/10.5.1/MapboxCoreMaps.xcframework-dynamic.zip' which is required by binary target 'MapboxCoreMaps': badResponseStatusCode(401)
```

**Comment by evilhonda3030** [comment]
@danyf90 I forgot to leave a comment about MapBox installation. Here is doc: https://docs.mapbox.com/ios/maps/guides/install/.
In a nutshell, you should create a Mapbox account, create secret token which allows you to install packages containing Mapbox SDK. Could you figure it out in order to test an issue?

**Comment by evilhonda3030** [comment]
It's not a big deal

<img width="667" alt="image" src="https://user-images.githubusercontent.com/103509461/169467624-7e5f3af5-a519-490d-8915-9615422c6ded.png">

**Comment by danyf90** [comment]
I think the problem is that the package already provides the bundle accessor: https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Foundation/Extensions/Bundle%2BMapboxMaps.swift

**Comment by evilhonda3030** [comment]
Okay, I proposed it yesterday in a corresponding discussion. How can I stop generate bundle accessors for certain dependencies? Is there any workaround?

**Comment by evilhonda3030** [comment]
@danyf90 Any tips?

**Comment by danyf90** [comment]
> @danyf90 Any tips?

Commenting on the discussion/issue is enough, no need to ping people 😅

**Comment by fortmarek** [comment]
Hey @evilhonda3030,

I think we can either:
- skip generating the resource accessor by default if we find it in the list of package's source
- still generate the resource accessor but name the file differently
- change the file name we generate to decrease the likelihood of conflicts
- enable folks to opt-out of this feature for dependencies (all of them or specific ones)

Personally, I am most leaning to just changing the name of the resource accessor we generate. Instead of `Bundle+{name-of-dependency}.swift`, it could be `TuistBundle+{name-of-dependency}.swift` (or any other name).

@danyf90, wdyt about this?

**Comment by danyf90** [comment]
I agree that changing the name is the easiest and simpler way.
However it might not be enough add there would be conflicts also in the code (e.g. both would probably create Bundle.module)

**Comment by fortmarek** [comment]
That's a good point. I think we can do both then:
- Change the file name to make more obvious this is file coming from tuist and decrease file name conflicts
- Enable disabling the accessors for dependencies

**Comment by evilhonda3030** [comment]
I guess have a control over code generation occurring in dependencies is a good option. But a hack with Tuist prefix seems like the cheapest and solid solution for this specific problem. I doubt that someone names his/her own file the same way.

I understand that here I most likely could link all deps as binaries but I assume it prevents browsing source of code dependencies during development process and this is an option which I would love to have.

**Comment by danyf90** [comment]
The point is that those accessors are already synthesized by SPM, so I don't get why that package defines them 🤔

**Comment by danyf90** [comment]
Oh I've just checked the code. For SPM it just relies on the SPM synthesized one, so just renaming the file should be enough.
I'll try to prepare a PR later
