### ISSUE TITLE
Trying to reach the bundle resources in a "safe way" from the app. (Bundle target decoupled from the app to be reused along the project)

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4468]
## Describe the bug and the expected behavior

Hey over there: 

I follow the next steps to include a Resources Bundle inside the application target

* Create a Target with product type = bundle
* Include inside the target the resources inside "resources" property
* Add the dependency target to the application target
* Run tuist generate

I expected to see a Derived File inside the application target with title "Assets+AppName" with the assets enum to Reach all the assets inside the Bundle that it is a dependency of the app.

But I was surprised because it wasn't generated.

## Reproduction steps

Steps to reproduce the bug:

* Create a Target with product type = bundle
* Include inside the target the resources inside "resources" property
* Add the dependency target to the application target
* Run tuist generate

### Additional context

- macOS version: 12.3
- Tuist version: 3.2.0
- Xcode version: 13.3.1

### Example project
[ios_app_with_framework_and_resourceBundle.zip](https://github.com/tuist/tuist/files/8737394/ios_app_with_framework_and_resourceBundle.zip)
(Static framework is meanless for the example )

**Comment by danyf90** [comment]
> 1. Use the attached sample project (to be provided when opening the issue)

**Comment by jesus-mg-ios** [comment]
[ios_app_with_framework_and_resourceBundle.zip](https://github.com/tuist/tuist/files/8737394/ios_app_with_framework_and_resourceBundle.zip)

Example project attached. 
Notice that Tuist doesn't generate the assets derived file for ResourcesBundle.
It should be great that this file will be generated for the App and Framework, because both use the same bundle. I don't want to create a framework and import this framework (dynamic framework) inside another frameworks to reuse his bundle, because by this way I cannot achieve a static feature frameworks. 

Thanks in advance.

**Comment by danyf90** [comment]
Can you clarify what you mean by:
> I don't want to create a framework and import this framework (dynamic framework) inside another frameworks to reuse his bundle, because by this way I cannot achieve a static feature frameworks

We have static frameworks with resources everywhere :D

**Comment by jesus-mg-ios** [comment]
Yeah @danyf90, I mean, as you know a static framework has no a bundle. In your cases, you create a static framework with a bundle and import them into the consumer. I don't want to include a static framework and a bundle because with a bundle should be enough.

**Comment by danyf90** [comment]
Tuist defines bundle accessors in the target containing the resources, so I'm afraid that if you just have a bundle it won't generate them.
Maybe @kwridan or @fortmarek knows more 🙏 

Also, is there a reason why you don't add the resources directly to the app target in your case?

**Comment by jesus-mg-ios** [comment]
Thanks @danyf90.

For example, you have a feature X independent from the app target.

* This feature want to access to resources. 
(It could do it accessing to the main bundle, and it's true, but his access it will be "unsafe", I mean with strings instead of variables). Maybe this case in particular could be solved adding a flag to load the bundle accessors also in the feature.

* The feature should only access a part of resources in a clean way, in this case you only need a part of the resources, should be great to access a concrete bundle.

* You have a framework that depending on a flag want to load on type of resources or another. This could be a great way to organise them (two bundles instead of one)

* You have an app extension that need access to a resources, but only for a part of them.

I think that this are all cases that I've in mind. 🤔 Maybe access in a safety way to the third party resources (But I don't know if this case is already managed by Tuist)

Thanks in advance

**Comment by danyf90** [comment]
I think the easiest way to achieve that is to define a static framework with resources and share them through it.

Creating the accessors for a bundle would be quite different in the tuist logic, because it should create the accessors in all the targets depending on it, since the bundle itself can't contain the code

**Comment by kwridan** [comment]
> I think the easiest way to achieve that is to define a static framework with resources and share them through it.

👍 This is the most straightforward if you already have static only targets. I can't recall if the accessors can be made public or if that is something you need to do manually 🤔

In case it helps, https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_static_frameworks_with_resources demos this.

> Creating the accessors for a bundle would be quite different in the tuist logic, because it should create the accessors in all the targets depending on it, since the bundle itself can't contain the code.

Indeed, any additions / modifications to resources would also result in accessor regeneration in several targets. This may / may not be desired depending on setup. 

Some considerations here especially if the SwiftGen integration is also enabled _(e.g. generating strongly typed accessors for the individual resources within the bundle)_

- Are the accessors checked in? _(some teams might chose to do this)_
- Does another team code own a module where the resources are used? _(this means requiring multiple teams to approve code changes in their modules for the addition of a new asset!)_
