### ISSUE TITLE
Product can not found of package

### ISSUE THREAD

**Issue by 94haox** [tuist/tuist#4479]
## Describe the bug and the expected behavior

In Package.swift, we define a dependency with ```.package( name: xxx, url: xxx, from: xxx )```. 
But at Swift 5.6 we will get a warning with ```'package(name:url:from:)' is deprecated: use package(url:from:) instead```, if we use ``` package(url:from:) ```,  tuist generate will be error with msg: ```The product xxx of package xxx cannot be found.```

## Reproduction steps

Steps to reproduce the bug:
1. select any package, change dependencies with ``` package(url:from:) ```
2. any project use this package
3. run tuist generate

### Error log

```
The product xxx of package xxx cannot be found.
```

### Error screenshots
<img width="473" alt="wecom-temp-265734ead6dbe711e45362a4d4879a3f_副本" src="https://user-images.githubusercontent.com/12044982/169738998-a1533dd3-06a7-45e4-9e88-b33f1952c434.png">

### Additional context

- macOS version: 12.2
- Tuist version: 3.0.0
- Xcode version: 13.4

**Comment by Banck** [comment]
Hello, @94haox !
Could you describe your issue in more detail? What exactly do you write in Dependencies.swift and how do you connect it to the project? (.external(name: ))

I tried to connect https://github.com/netcosports/Astrolabe (seems your issue about this lib) to test project via Dependencies swift and all is fine:
in Dependencies.swift:
            `.remote(url: "https://github.com/netcosports/Astrolabe.git", requirement: .upToNextMajor(from: "5.0.0"))`

in Project.swift:
`.external(name: "Astrolabe")`

```
tuist fetch
tuist generate
```

<img width="580" alt="image" src="https://user-images.githubusercontent.com/6259254/169741855-cd730539-46c8-4198-b720-cbf26e2e3acf.png">

**Comment by 94haox** [comment]
this issue has nothing to do with  https://github.com/netcosports/Astrolabe , package name is coincidence.

thers is detail:
we have two package: Astrolabe and LagReport, LagReport is dependency Astrolabe.

Astrolabe's package.swift looks like:
```swift
import PackageDescription

let package = Package(
    name: "Astrolabe",
    products: [
        .library(
            name: "Astrolabe",
            targets: [
                "AstrolabeCore"
            ]
        ),
    ],
    dependencies: [
            xxxx
    ],
    targets: [
        .target(
            name: "AstrolabeCore",
            dependencies: [
                   xxxx
            ]
        )
    ]
)
```

LagReport's package.swift looks like:
```swift

import PackageDescription

let package = Package(
    name: "LaggingReport",
    products: [
        .library(
            name: "LaggingReportStatic",
            targets: ["LaggingReportPlugin"]),
    ],
    dependencies: [
        .package(
            url: "https://xxxx/astrolabe-ios.git",
            from: "1.2.0"
        )
    ],
    targets: [
        .target(
            name: "LaggingReportPlugin",
            dependencies: [
                .product(name: "Astrolabe", package: "astrolabe-ios"),
            ])
    ]
)
```

project tuist's Dependencies.swift: 

```swift
let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "xxxx/lagreport.git", requirement: .exact("1.2.0"))
    ]
    platforms: [.iOS]
)
```

in swiftpackage.swift:
```swift
extension TargetDependency  {
    public static let lagReport = .external(name: "LaggingReportStatic")
}
```

in project.swift:
```swift
let project = Project.module(
    name: "App",
    dependencies: [
        .lagReport
    ]
)

```

when run ```tuist generate```, will fail with msg: 
```
The product Astrolabe of package astrolabe-ios cannot be found.
```

**Comment by danyf90** [comment]
@94haox Can you please attach a sample project?

**Comment by victor-sarda** [comment]
Hey, @danyf90 I had a similar problem a month ago. I opened an issue (https://github.com/tuist/tuist/issues/4411) and closed it after I used the suggestion from this comment: https://github.com/tuist/tuist/issues/4303#issuecomment-1081079787.
Using `package(name:url:from:)` works but I think this is still an issue since it's gonna be deprecated.

https://github.com/tuist/tuist/issues/4411 has a sample project if you want to have a look 👍
