### ISSUE TITLE
An empty `Derived/InfoPlists` folder is always generated on disk

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#449]
**Describe the bug**
Running `tuist generate` will always create a `Derived/InfoPlists` folder on disk even if it isn't required.

**To Reproduce**

1. Run `tuist generate` on `fixtures/ios_app_with_tests`
2. Inspect the file system
3. There's an empty `Derived/InfoPlists` folder

**Expected behavior**
For projects that don't leverage the generated Info plist, there isn't a need to create those directories.

**Additional context**

`Derived/InfoPlists` is used when leveraging `InfoPlist.dictionary()` where the Info plist file is generated by Tuist and placed in `Derived/InfoPlists` - in the event `InfoPlist.file()` is used, no file is generated and in this case the folder creation is unnecessary.

**Comment by pepibumur** [comment]
>  For projects that don't leverage the generated Info plist, there isn't a need to create those directories.

Agree
