### ISSUE TITLE
Problem with init inside 3.5.0

### ISSUE THREAD

**Issue by ViniciusDeep** [tuist/tuist#4514]
## Describe the bug and the expected behavior

Hello guys, we updated tuist to 3.5.0 with a sample update, but we receive this message, 
.tuist/Versions/3.5.0/Templates/default/default.swift:1:8: error: missing required module '_Concurrency'
import ProjectDescription

In 3.4.0, works fine

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project (to be provided when opening the issue)
2. Run `…`
3. See the error

Just update 3.4.0 to 3.5.0 and run tuist generate and get a error, to test I created a sample app and run tuist init --plataform ios and receive the same error, I made a downgrade to 3.4.0 and that's work's fine to both, sample and project.

### Error log

```
.tuist/Versions/3.5.0/Templates/default/default.swift:1:8: error: missing required module '_Concurrency'
import ProjectDescription
```

### Additional context

- macOS version: 12.4
- Tuist version: 3.5.0
- Xcode version: 13.0, 13,3 and 13,4

**Comment by shahzadmajeed** [comment]
I can't reproduce this (on M1). Do you have more detail on this? I would try following this as well:

1. Restart your machine (just for sanity)
2. Uninstall 3.4.0 and only use 3.50
3. Try to use --verbose to collect more logs

**Comment by danyf90** [comment]
Can't replicate as well, I would suggest trying to reinstall it 🤷‍♂️ 
If it is still a problem, feel free to reopen the issue
