### ISSUE TITLE
Can't reference a local swift package in a workspace

### ISSUE THREAD

**Issue by marinofelipe** [tuist/tuist#4515]
## Describe the bug and the expected behavior

I'd like to have a local Swift Package as part of my Tuist managed workspace, after Tuist (re)generate the project.

Is this something that you would be willing to support? I mean, I guess for those users that either can't yet or don't want to go all into `Dependencies.swift`?

In my setup I have an Xcode project managed via Tuist, in a workspace that has it and a local Swift Package. The workspace has to be manually maintained, since Tuist does not support referencing a local Swift Package in the workspace level as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "group:SomeProject/SomeProject.xcodeproj">
   </FileRef>
   <FileRef
      location = "group:Package.swift">
   </FileRef>
   <FileRef
```

## Reproduction steps

Steps to reproduce the bug:

1. Have a workspace managed via Tuist, with one or more Xcode projects and one or more local Swift Packages2. 
2. Try to generate your workspace in a way where your local Package root folder is listed in your workspace, like below:

![Screen Shot 2022-05-31 at 18 01 47](https://user-images.githubusercontent.com/18131704/171218312-b6e0d0ef-1d84-421f-88cb-1854e5d1d7ca.png)

### Error screenshots

![Screen Shot 2022-05-31 at 18 02 09](https://user-images.githubusercontent.com/18131704/171218396-f44ced95-579f-480a-b864-8b07ce9d52a8.png)

### Additional context

- Tuist version: 2.6.0...3.5.0
- Xcode version: 13.4 (13F17a)

1. When exploring the usage of `Dependencies.swift`, which could bring additional benefits with it like cache, a lot of issues were faced when running `tuist fetch` to resolve dependencies from the mentioned local `Package.swift`. That's why, for now, I'm not yet using `Dependencies.swift` to have my local package managed by Tuist.

2. In my, _user_ opinion, having the fallback to just reference a local package into a workspace would be great since it would give me choice, why I don't fully go to `Dependencies.swift`.

I would be super happy and willing to contribute on adding support for it, in case it's in the interests of Tuist and its maintainers.
Thanks, and thanks for the amazing tool 😉🚀!

**Comment by danyf90** [comment]
Hello @marinofelipe 

Regarding point 1, could you please clarify what issues have you faced running `tuist fetch`? it's better to fix issues rather than workaround them :D

Regarding point 2, you can already do it defining your dependencies in the [Project.packages](https://tuist.github.io/tuist/main/documentation/projectdescription/project/init(name:organizationname:options:packages:settings:targets:schemes:fileheadertemplate:additionalfiles:resourcesynthesizers:)) and then adding it to the [target dependencies](https://tuist.github.io/tuist/main/documentation/projectdescription/targetdependency/package(product:))

**Comment by marinofelipe** [comment]
Hey @danyf90, thanks for the support.

Regarding 1, is similar to #4411, the issue is that it happened multiple times to different dependencies of my local Package.swift (which is a very big one), when I was playing with it. On top of that, to be honest, I'm not willing to move all into `Dependencies.swift` at the very moment, but if it helps, I could create an issue for the issues faced on `Dependencies.swift` :).

On 2, isn't that in a project level though? Is there any supported way to have a Package as root level object within a Workspace?

**Comment by shahzadmajeed** [comment]
> Is there any supported way to have a Package as root level object within a Workspace?

I'm not sure I understand the ask but are you expecting to use a swift package in every target in a workspace? Even Xcode or SPM don't allow that, you have to explicitly add swift package products in consuming targets/frameworks.

For reusability, you can declare it in `ProjectDescriptionHelpers` and use in all projects/targets.

**Comment by marinofelipe** [comment]
Hey @shahzadmajeed, as in the picture I had shared before:

![Screen Shot 2022-06-06 at 20 47 25](https://user-images.githubusercontent.com/18131704/172226525-bfe87560-5b95-4a5e-aebb-13d2dd1558bf.png)

The only thing I want, that Xcode allows, is to have a local Swift Package as part of my workspace, so I can work on it at the same time I work on a companion Xcode project.
Currently that's possible on a pure Xcode setup with SPM, but not on a Tuist Workspace declaration.

**Comment by marinofelipe** [comment]
This is no big deal, is just a minor thing, but that could be useful for folks, that like me, rely on Swift Package Manager for their "internal" dependencies. In the scenario I shared in this issue, the Workspace has an Xcode project with apps, app extensions, and a local Swift Package that provides the internal dependencies/modules that I use to compose functionality.
_Sharing, In case more context would be useful_.

**Comment by danyf90** [comment]
that should work fine if you use Dependencies.swift.
In any case I would suggest to define tuist projects instead of using the SPM packages as they better integrate with tuist generation process

**Comment by marinofelipe** [comment]
Ok, thanks!

**Comment by pavm035** [comment]
I'm facing same issue now, If i try to use Dependencies it creates project for Each local SPM and also adds Tuist folder for their dependencies
