### ISSUE TITLE
Add ability to re-generate individual projects

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#452]
## Need/problem

Add the ability to generate individual Xcode projects without generating the entire workspace and dependency projects. 

# Motivation 
When incrementally adopting project generation, generated projects are checked in and placed alongside existing projects in an existing workspace.

Generating a project that has dependencies will generate an Xcode projects for all projects in the dependency graph. This is of course intended and the correct behavior to ensure the generated workspace is up-to-date and can build without any missing dependencies.

When iterating on a new generated project that has dependencies, re-generating it will cause the dependencies to also be re-generated. There are a few scenarios that can lead to the re-generated dependency being slightly different (yet semantically equivalent - e.g. https://github.com/tuist/tuist/issues/425). As such unnecessary changes are introduced and have to be manually reverted.

### Tuist Generator

I propose revising the generator interface slightly to:

```swift
public protocol Generating {
  // Individual project
  func generateProject(at path: AbsolutePath, config: GeneratorConfig) throws -> AbsolutePath

  // Project workspace (existing behavior of project + dependencies)
  func generateProjectWorkspace(at path: AbsolutePath, config: GeneratorConfig, workspaceFiles: [AbsolutePath]) throws -> AbsolutePath

  // Workspace (existing behavior of referenced projects + dependencies)
  func generateWorkspace(at path: AbsolutePath, config: GeneratorConfig, workspaceFiles: [AbsolutePath]) throws -> AbsolutePath
}
```

This will help us distinguish the action of generating a project workspace and an individual project.

Internally we can re-use the existing `ProjectGenerator` component directly _(side-note - it’s great this functions independently!)_.

```swift
public func generateProject(at path: AbsolutePath, config: GeneratorConfig) throws -> AbsolutePath {
    let (graph, project) = try graphLoader.loadProject(path: path)
    
    let generatedProject =  try projectGenerator.generate(project: project,
                                                          options: config.options,
                                                          graph: graph,
                                                          sourceRootPath: path)
    return generatedProject.path
}
```

This ensures only the specified project is generated without generating a workspace.

### Command Line
This can be done separately (or perhaps can be omitted if not deemed worthy). 

We can introduce command line option to trigger a call to the new generator method. (e.g. `--project`)

# Drawbacks
- Is generating an individual project widely applicable for Tuist?
	- We can introduce this into `TuistGenerator` first and expose it via the Tuist command line if there’s a demand for it
- Additional command line logic is needed to determine the appropriate generator method to call - what should the last case do?
	-  `generate` in a directory with `Project.swift`  >  `generateProjectWorkspace`
	- 	 `generate --project` in a directory with `Project.swift`  >  `generateProject`
	-  `generate` in a directory with `Workspace.swift`  >  `generateWorkspace`
	-  `generate` in a directory with `Workspace.swift` & `Project.swift`  >  `generateWorkspace`
	- `generate --project` in a directory with `Workspace.swift` & `Project.swift`  >  `generateProject`
	- `generate --project` in a directory with `Workspace.swift` >  **Error! No project manifest found**?

## Alternatives
- Add a new option to the `GeneratorConfig` that allows specifying a whitelist of project paths from the graph to generate within the `WorkspaceGenerator`
	- While this achieves the result of generating only a single project, it has the negative side effect of generating an invalid workspace which is not desirable.
 
# Adoption strategy
Can be developed over 2 stages:

- Update `TuistGenerator` to support this internally
	- Will allow us to iterate and experiment with this feature and feedback any insights to improve it
- Expose this via command line

# How we teach this
- Update the documentation
- Mention the new option in the release blog post 

# Unresolved questions
- Any other alternates option names in  `tuist generate --project`  ?

**Comment by pepibumur** [comment]
I think this is a solution worth solving to facilitate the migration to Tuist and that it should be configurable through CLI arguments. My only suggestion is renaming the argument `--project` to `--only-project`. The rest looks great.

**Comment by ollieatkinson** [comment]
<3 

What a great idea, i'm in full support of this. 
I agree with @pepibumur that `--only-project` is more obvious at the call-site to what it's actually doing. But happy to consider more options if we think there needs to be some thought.
