### ISSUE TITLE
Add product type "WatchKit App Container" to `ProjectDescription`

### ISSUE THREAD

**Issue by thebarndog** [tuist/tuist#4534]
## Describe the bug and the expected behavior

When creating a standalone watch app, Xcode will generate 3 targets:

- a WatchKit app container with the product type `com.apple.product-type.application.watchapp2-container`
- a watch kit app with the product type `com.apple.product-type.application.watchapp2`
- a watch kit extension with the product type `com.apple.product-type.watchkit2-extension`

`ProjectDescription.Product` needs an additional product type to represent watch kit container targets which is essentially an empty iOS target with corresponding product type `com.apple.product-type.application.watchapp2-container`.

As a side question, are there any tuist plugins that are able to generate a standalone watch app or watch targets in general? Something like that would be incredibly useful rather than the alternative which is having to know exactly what targets Xcode creates and how they're structured.

**Comment by fortmarek** [comment]
Hey @thebarndog 👋 

That's a reasonable addition. Would you want to contribute to this?

> that are able to generate a standalone watch app or watch targets in general?

I'm not aware of something like that being available. But you are more than welcome adding that by creating a template plugin (see documentation [here](https://docs.tuist.io/plugins/creating-plugins#templates))l. Depending on the template, you could then run `tuist scaffold --template watch-target --name WatchName` which would generate the files specified in the template.

**Comment by thebarndog** [comment]
Yeah I can certainly take a crack at it. It might not be for a while but it's definitely something I'd love to see!

**Comment by andrea-bb** [comment]
@fortmarek Is there support in Tuist for building standalone Apple Watch apps (without an iOS companion)?
