### ISSUE TITLE
ResourceSynthesizers folder not added on edit

### ISSUE THREAD

**Issue by Craz1k0ek** [tuist/tuist#4537]
## Description
I've added some custom resource synthesizers, which, according to the docs, should be placed under `Tuist/ResourceSynthesizers/<name>.stencil`. I then quit Xcode, build the project and the template works just fine, but I wanted to tweak it a little further. Upon running `tuist edit` again, the `ResourceSynthesizers` folder does not appear in the file inspector. I even added a `.swift` file in the hope of it forcing the generation, but without luck.

## Expected
I would expect the `ResourceSynthesizers` folder to be present in the file inspector when it is defined and filled with synthesizers.

## Reproduction steps
1. Run `tuist edit`
2. Add the `ResourceSynthesizers` folder under the `Tuist` directory and add a `<name>.stencil` file.
3. Close Xcode
4. Run `tuist edit`
5. The `ResourceSynthesizers` folder is now missing

### Additional context
- macOS version: 12.4
- Tuist version: 3.5.0
- Xcode version: 13.4

**Comment by danyf90** [comment]
Ciao 👋 
Thanks for reporting this! I agree that the synthesizers should be added there 👍 

In case you want to take a look, the logic that implements that part should be [here](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/ProjectEditor/ProjectEditor.swift)
