### ISSUE TITLE
Fetch fails on macOS 13 Ventura (Beta) with Xcode 14 (Beta)

### ISSUE THREAD

**Issue by gutaker** [tuist/tuist#4538]
## Fetch fails on macOS 13 Ventura (Beta) with Xcode 14 (Beta)

When trying to generate project from scratch or after cleaning, `tuist` fails at the end of downloading dependencies.
Project has **14 SPM** and **1 Carthage** dependencies.
On **macOS 12.4** with **Xcode 13.4.1** everything works well.

## Reproduction steps

Steps to reproduce the bug:

1. `tuist clean`
2. `tuist fetch`

### Error log

```
We received an error that we couldn't handle:
    - Localized description: The data couldn’t be read because it is missing.
    - Error: keyNotFound(CodingKeys(stringValue: "name", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "settings", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"name\", intValue: nil) (\"name\").", underlyingError: nil))
```

### Additional context

- macOS version: 13 Ventura (Beta)
- Tuist version: 3.5.0
- Xcode version: 14 (Beta)

**Comment by ffittschen** [comment]
I'm observing the same error on macOS 12.4 with Xcode 14.0 Beta. I tried to debug it but when running `./fourier generate tuist` I get the same error, and running that command with Xcode 13.4 and then opening the generated project with Xcode 14 results in "module has been compiled with incompatible Swift version" errors

**Comment by danyf90** [comment]
Yep, it has already been reported [here](https://github.com/tuist/tuist/discussions/4531#discussioncomment-2907562), looks like the format of Package.swift dump is changed, but it is not available on the public repo yet, so we either have to wait or reverse engineer it (I would wait at least a bit).

To play with it, you can open the Package.swift instead of using fourier generate
