### ISSUE TITLE
`Bundle.module` does not use the same bundle name as official swift package manager.

### ISSUE THREAD

**Issue by wangjiejacques** [tuist/tuist#4540]
## Describe the bug and the expected behavior

Here is the code generated by Tuist
```swift
extension Foundation.Bundle {
    /// Since ContentsquareModuleWrapper is a staticFramework, the bundle containing the resources is copied into the final product.
    static var module: Bundle = {
        let bundleName = "ContentsquareModuleWrapperResources"

        let candidates = [
            Bundle.main.resourceURL,
            Bundle(for: BundleFinder.self).resourceURL,
            Bundle.main.bundleURL,
        ]

        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }
        fatalError("unable to find bundle named ContentsquareModuleWrapperResources")
    }()
}
```

Here is the one generated by official Swift Package Manager

```swift
extension Foundation.Bundle {
    /// Returns the resource bundle associated with the current Swift module.
    static var module: Bundle = {
        let bundleName = "CS_iOS_SDK_ContentsquareModuleWrapper"

        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,

            // Bundle should be present here when the package is linked into a framework.
            Bundle(for: BundleFinder.self).resourceURL,

            // For command-line tools.
            Bundle.main.bundleURL,
        ]

        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }
        fatalError("unable to find bundle named CS_iOS_SDK_ContentsquareModuleWrapper")
    }()
}
```
as you can see the name from tuist is `ContentsquareModuleWrapperResources`. 
the name from SPM is `CS_iOS_SDK_ContentsquareModuleWrapper`, which is `packageName+"_"+targetName`
## Reproduction steps

We are distributing our binary framework as swift package, and our code is depends on the bundle name generated by Swift Package Manager.
Because Tuist doesn't use the same name, we have this error 
```
ContentsquareModule/BundleModule.swift:29: Fatal error: unable to find bundle named CS_iOS_SDK_ContentsquareModuleWrapper
```
It would be better if tuist can use the same name as swift package manager.
### Error log

```
ContentsquareModule/BundleModule.swift:29: Fatal error: unable to find bundle named CS_iOS_SDK_ContentsquareModuleWrapper
```

**Comment by danyf90** [comment]
How do you access/use the Bundle.module from the outside? Isn't it exposed by the package (and hence even if it changes it shouldn't be a problem)?

**Comment by wangjiejacques** [comment]
@danyf90 We are using it inside the binary xcframework, not outside.

Here is our [Swift Package](https://github.com/ContentSquare/CS_iOS_SDK), as you can see,
The [CS_iOS_SDK](https://github.com/ContentSquare/CS_iOS_SDK) can generated the `Bundle.module` code, but we can't access it from our binary xcframework, so we write it manually based on how SPM works.

**Comment by danyf90** [comment]
2 observations:
1. if the package expects users to use their bundle, why don't they expose it like
```
public let bundle: Bundle {
  return .module
}
```
2. as you were assuming the SPM bundle before, can't you now assume the tuist bundle?

**Comment by wangjiejacques** [comment]
> if the package expects users to use their bundle, why don't they expose it like

We don't expects users to use this bundle, it's only used internally inside the binary xcframework.

> as you were assuming the SPM bundle before, can't you now assume the tuist bundle?

Yes, we can, but as it is not really an official product, we prefer not. 
Do you have any reasons to not generate the code same as SPM?

**Comment by danyf90** [comment]
> I'm the developer of this package, We don't expects users to use this bundle, it's only used internally inside our binary xcframework by ourselves.

I'm not sure I got this. What's `our binary xcframework`? Doesn't it depend on the SPM package? If yes, wouldn't be better to expose the bundle from the package instead of guessing its name from the framework?

**Comment by danyf90** [comment]
> Do you have any reasons to not generate the code same as SPM?

This is surely possible but will require some time to implement, so I was trying to find a quicker path for you 👍

**Comment by danyf90** [comment]
I see, still not clear to me what your binary frameworks needs to do with the bundle, but maybe it could get the bundle in input (assuming it exposes some functions)?

**Comment by wangjiejacques** [comment]
The bundle is simply some resources like xib, storyboard.
As swift package only works with static framework (at least for us), so we can't have resource in our binary framework.

**Comment by wangjiejacques** [comment]
> but maybe it could get the bundle in input (assuming it exposes some functions)?

It's too complicated for our user.

**Comment by danyf90** [comment]
I understand, if you want to try to fix it, I'm happy to give some pointers, feel free to write me on Slack
