### ISSUE TITLE
BUG: I cannot disable bundle accessors from an static framework

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#4546]
## Describe the bug and the expected behavior

I've done an static framework that includes resources accessors, so tuist generate bundle with resources.
Because I've got a way to look for the bundle (custom), I want to remove the bundle accessors generated by tuist.
I cannot generate the project.

## Reproduction steps

Steps to reproduce the bug:

1. Generate a project with target product as Static framework and then include inside resources.
2. Disable in project properties the bundle accessors
3. The error: Target CustomTargetName cannot contain resources. staticFramework targets do not support resources

### Error log

```
Target CustomTargetName cannot contain resources. staticFramework targets do not support resources
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### Additional context

- macOS version: 12.4
- Tuist version: 3.2.0
- Xcode version: 13.3.1

**Comment by danyf90** [comment]
Please reopen the issue following the template (e.g. providing sample project)

**Comment by jesus-mg-ios** [comment]
@danyf90 the issue was opened following the template, in this, there's no section specifying that you have to include a sample project (if it's a key point, maybe the template should be reviewed)

**Comment by danyf90** [comment]
Hi Jesus 👋 

This is an extract of the template:
```
…
Steps to reproduce the bug:

1. Use the attached sample project (to be provided when opening the issue)
…
```

could you please let us know what you would change about that? 🙏

**Comment by danyf90** [comment]
No problem, just attach the project and reopen the issue 🙏
