### ISSUE TITLE
Some cache artifacts are very big

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#4556]
## Describe the bug and the expected behavior

We have noticed that some of the xcframeworks created by tuist for caching are very big, for example [gRPC-Core](https://github.com/grpc/grpc) is 2GB 🤯 

## Reproduction steps

1. Get the gRPC-Core hash with `tuist cache print-hashes --xcframeworks --path projects/tuist/fixtures/app_with_spm_dependencies/ | grep gRPC-Core`
2. Create cached artifact with `tuist cache warm gRPC-Core --xcframeworks --path projects/tuist/fixtures/app_with_spm_dependencies/`
3. chech the built artifact in `~/.tuist/Cache/BuildCache/<hash_from_point1>`

### Additional context

- macOS version: 12
- Tuist version: 3.6.0
- Xcode version: 13.4.0

**Comment by kwridan** [comment]
It's not uncommon to have a large artefact size -  what would be interesting is to see is if the size suddenly changed between versions or was it always this large.

**Comment by ezraberch** [comment]
The reason it's so big is that there are two universal binaries with a total of 5 architectures:

```
$ file ios-arm64_armv7/gRPC_Core.framework/gRPC_Core 
ios-arm64_armv7/gRPC_Core.framework/gRPC_Core: Mach-O universal binary with 2 architectures: [arm64:current ar archivecurrent ar archive] [arm_v7]
ios-arm64_armv7/gRPC_Core.framework/gRPC_Core (for architecture arm64):	current ar archive
ios-arm64_armv7/gRPC_Core.framework/gRPC_Core (for architecture armv7):	current ar archive

$ file ios-arm64_i386_x86_64-simulator/gRPC_Core.framework/gRPC_Core 
ios-arm64_i386_x86_64-simulator/gRPC_Core.framework/gRPC_Core: Mach-O universal binary with 3 architectures: [arm64:current ar archivecurrent ar archive] [x86_64] [i386]
ios-arm64_i386_x86_64-simulator/gRPC_Core.framework/gRPC_Core (for architecture arm64):	current ar archive
ios-arm64_i386_x86_64-simulator/gRPC_Core.framework/gRPC_Core (for architecture x86_64):	current ar archive
ios-arm64_i386_x86_64-simulator/gRPC_Core.framework/gRPC_Core (for architecture i386):	current ar archive
```

Do we need all 5?

**Comment by danyf90** [comment]
Closing as it seems expected

**Comment by jesus-mg-ios** [comment]
We notice today, that warm cache errors shown by Tuist are caused in part for this, or they are related to it.

I mean to this: 

```
We received an error that we couldn't handle:
- Localized description: The operation couldn’t be completed. (ZIPFoundation.Archive.ArchiveError error 0.)
- Error: unreadableArchive
```
Tuist uploads an empty zip (0 bytes) to cloud and then is impossible to read it.

If we tried to upload the file using tuist ``tuist cache warm --xcframeworks`` tuist gets stuck uploading the [gRPC-Core](https://github.com/grpc/grpc)

@danyf90 it makes sense? That it to say, It could be an error uploading large files to cloud? is Tuist using aria2 to uploading and downloading artefacts?
