### ISSUE TITLE
AppIcon override

### ISSUE THREAD

**Issue by dtamiazzo** [tuist/tuist#4563]
## Describe the bug and the expected behavior

The Target Primary App Icon Set Name gets overridden with AppIcon

## Reproduction steps

Steps to reproduce the bug:

1. Define ASSETCATALOG_COMPILER_APPICON_NAME in .xcconfig used in Target (in this case, Todo Debug.xcconfig and Todo Release.xcconfig contain two different icon names, AppIcon-Debug, AppIcon-Release)
2. tuist generate
3. In XCode, go to the Targets build settings,  the Target's Primary App Icon Set Name is set to AppIcon in bold, meaning it's overridden from default
4. If you delete the overridden value in XCode, you get the correct ones, not in bold

## Project.swift

```swift
let project = Project(
    name: "Todo",
    settings: .settings(configurations: [
        .debug(name: "Debug", xcconfig: "Configs/TodoProject Debug.xcconfig"),
        .release(name: "Release", xcconfig: "Configs/TodoProject Release.xcconfig"),
    ]),
    targets: [
        Target(
            name: "Todo",
            platform: .iOS,
            product: .app,
            bundleId: "$(PRODUCT_BUNDLE_IDENTIFIER)",
            deploymentTarget: .iOS(targetVersion: "14.0", devices: .iphone),
            infoPlist: "Todo/Info.plist",
            sources: ["Todo/**"],
            resources: ["Todo/Resources/**"],
            settings: .settings(
                configurations: [
                .debug(name: "Debug", xcconfig: "Configs/Todo Debug.xcconfig"),
                .release(name: "Release", xcconfig: "Configs/Todo Release.xcconfig")
            ]),
            coreDataModels: [
                CoreDataModel("Database.xcdatamodeld"),
            ]
        ),
        ......
```     

### Error screenshots

<img width="862" alt="Screenshot 2022-06-24 at 15 24 46" src="https://user-images.githubusercontent.com/79444721/175545181-b1202679-225f-4932-bb21-ae7b2e82627e.png">

### Additional context

- macOS version: 12.4
- Tuist version: 3.3.0
- Xcode version: 13.4.1

### Workaround 

add argument base with the following snippet:

```swift
   settings : .settings(
       base: [
         "ASSETCATALOG_COMPILER_APPICON_NAME": "$(ASSETCATALOG_COMPILER_APPICON_NAME)"
      ],
```

**Comment by kwridan** [comment]
Thanks for raising this @dtamiazzo 

`ASSETCATALOG_COMPILER_APPICON_NAME`  is automatically added by Tuist as as part of its default recommended setting for application targets. You can opt out from some of those default settings via specifying the [`DefaultSettings`](https://tuist.github.io/tuist/latest/documentation/projectdescription/defaultsettings) on `Settings` at either the project or target level.

Typically `essential` or `none` is a good choice for projects where the majority of their settings are in `xcconfig` files.

```swift
Project(
  settings: .settings(
       default: .essentail
  )
)
```

Alternatively if you would like to keep all the other recommended settings but only exclude this one you could:

```swift
Project(
  settings: .settings(
       default: .recommended(excluding: ["ASSETCATALOG_COMPILER_APPICON_NAME"])
  )
)
```

Hope this helps
