### ISSUE TITLE
Signing for resource requires a development team

### ISSUE THREAD

**Issue by Bogdan-Belogurov** [tuist/tuist#4568]
## Describe the bug and the expected behavior

Hello! I'm trying to cache resources using Xcode 14 and getting error `Signing for "name of resource" requires a development team. Select a development team in the Signing & Capabilities editor.`

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project [MyApp.zip](https://github.com/tuist/tuist/files/8984606/MyApp.zip)

2. Run:
- `tuist fetch`
- `tuist cache warm -x`
3. See the error

### Error log

```
❌ error: Signing for "Firebase_FirebaseInAppMessaging_iOS" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'Firebase_FirebaseInAppMessaging_iOS' from project 'Firebase')
❌ error: Signing for "Fakery_Fakery" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'Fakery_Fakery' from project 'Fakery')
```

### Additional context

- macOS version: 12.4 (21F79)
- Tuist version: 3.7.0
- Xcode version: 14 Beta 2

**Comment by danyf90** [comment]
is it specific to Xcode 14 or you get the same also with Xcode 13?

**Comment by Bogdan-Belogurov** [comment]
@danyf90 Specific only for Xcode 14

**Comment by kwridan** [comment]
I think some of the default settings for bundle targets have changed between Xcode 13 & 14, previously bundle targets had `CODE_SIGNING_ALLOWED` set to `NO` vs now it's `YES` - we may need to augment some of the default target settings.

**Comment by aniltaskiran** [comment]
hi,
is there any workaround for that? We are facing with the same problem :/

**Comment by kwridan** [comment]
@aniltaskiran mind testing your project with https://github.com/tuist/tuist/pull/4588 ?

**Comment by aniltaskiran** [comment]
It works 🚀 Thank you 🙏🏼
