### ISSUE TITLE
Project XXX - Upgrade "Watch" to single-target watch app

### ISSUE THREAD

**Issue by pavm035** [tuist/tuist#4572]
Hi

I'm trying to generate the project based on a new feature from Xcode 14 to combine the watch and watchKit extension into a single target, But I'm not able to find a way in the manifest to which support this feature. Any ideas? 
Attached image for reference
![Screen Shot 2022-06-27 at 13 22 54](https://user-images.githubusercontent.com/6092412/175859683-e9c6e6c9-bb01-4d0d-a025-a6f6f2d053a4.png)

Enviroment:
Xcde-beta: 14
tuist: 2.0.2

**Comment by danyf90** [comment]
Is it [this one](https://github.com/tuist/tuist/issues/4534)? If yes, please close this as duplicate 🙏

**Comment by kwridan** [comment]
Thanks for raising this @pavm035 

I did a small test locally, I created an application with a watchOS application in Xcode 13 and then used Xcode 14 and applied its recommendations.

```diff
 /* Begin PBXCopyFilesBuildPhase section */
-               42A5F27A286F7F9F008F9AB6 /* Embed App Extensions */ = {
-                       isa = PBXCopyFilesBuildPhase;
-                       buildActionMask = 2147483647;
-                       dstPath = "";
-                       dstSubfolderSpec = 13;
-                       files = (
-                               42A5F264286F7F9E008F9AB6 /* TimelyWatchApp WatchKit Extension.appex in Embed App Extensions */,
-                       );
-                       name = "Embed App Extensions";
-                       runOnlyForDeploymentPostprocessing = 0;
-               };
                        dependencies = (
-                               42A5F266286F7F9E008F9AB6 /* PBXTargetDependency */,
                        );
                        name = TimelyWatchApp;
                        productName = TimelyWatchApp;
                        productReference = 42A5F25B286F7F9D008F9AB6 /* TimelyWatchApp.app */;
-                       productType = "com.apple.product-type.application.watchapp2";
-               };
-               42A5F262286F7F9E008F9AB6 /* TimelyWatchApp WatchKit Extension */ = {
-                       isa = PBXNativeTarget;
-                       buildConfigurationList = 42A5F277286F7F9F008F9AB6 /* Build configuration list for PBXNativeTarget "TimelyWatchApp WatchKit Extension" */;
-                       buildPhases = (
-                               42A5F25F286F7F9E008F9AB6 /* Sources */,
-                               42A5F260286F7F9E008F9AB6 /* Frameworks */,
-                               42A5F261286F7F9E008F9AB6 /* Resources */,
-                       );
-                       buildRules = (
-                       );
-                       dependencies = (
-                       );
-                       name = "TimelyWatchApp WatchKit Extension";
-                       productName = "TimelyWatchApp WatchKit Extension";
-                       productReference = 42A5F263286F7F9E008F9AB6 /* TimelyWatchApp WatchKit Extension.appex */;
-                       productType = "com.apple.product-type.watchkit2-extension";
+                       productType = "com.apple.product-type.application";
                };
```

Xcode 14 applied the following changes:

- Deleted the WatchKit extension target
- Changed the product type of the watch app from `com.apple.product-type.application.watchapp2` to `com.apple.product-type.application`
- Merged some of the build settings from the extension to the watchOS application target

**Comment by pavm035** [comment]
@kwridan Thanks  lot for quick feedback, BTW any plan to support this feature in upcoming release?

**Comment by pavm035** [comment]
Hi Any progress on this?

**Comment by danyf90** [comment]
@kwridan does this mean we already support the new configuration? I.e. you just need to set platformo to watch and product to app? Maybe we just need to make the linter accept that?

**Comment by kwridan** [comment]
I think so - will do a draft PR with that soon for us to play with, I suspect there might be some subtle extra steps _(e.g. dealing with how to embed the watch app logic)_

**Comment by kwridan** [comment]
Interestingly in Xcode 14 beta 4 I'm no longer getting that prompt to update the watch app 🤔

Another interesting tidbit, there doesn't seem to be any link between the Application and the Watch App, even if you declare the Watch App to be a companion application. Previously, the application would embed the Watch App ... wonder if its a beta bug or there is some other mechanism that links them together

**Comment by pavm035** [comment]
Oh thank you so much for your great effort, may I know when this will be released?

**Comment by kwridan** [comment]
Once merged should be in the next release.

Mind testing out the PR to see if it works as expected? I feel like we're missing something - not sure how the iOS Application now embeds the Watch application anymore 🤔

**Comment by pavm035** [comment]
Sure, Please let me know how do I test this?

**Comment by danyf90** [comment]
@pavm035 you can just move to the branch of that PR and run Tuist commands directly from the Xcode project, let us know if you need further help

**Comment by pavm035** [comment]
@danyf90 I need help on checking PR in my project, Please help me how to validate this?

**Comment by kwridan** [comment]
@pavm035 to test out the branch, you can clone the specific branch from that PR and build tuist from source:

```sh
$ git clone --branch feature/xcode14-watch-application https://github.com/tuist/tuist.git
$ cd tuist
$ swift build tuist
```

Once built 

```sh
$ swift run tuist generate --path /path/to/project
```

**Comment by danyf90** [comment]
@pavm035 any update on this?

**Comment by pavm035** [comment]
@danyf90  Sorry i'm getting build error as steps mentioned by @kwridan, I'm trying this alternate way https://docs.tuist.io/contributors/get-started/#run-tuist-from-xcode
Error:

```swift
➜  tuist (feature/xcode14-watch-application) swift build tuist
error: Unexpected argument 'tuist'
Usage: swift build <options>
  See 'build -help' for more information.
```

**Comment by danyf90** [comment]
@pavm035 can you try using fourier?
```
./fourier tuist generate --path path_to_your_project
```

**Comment by pavm035** [comment]
@danyf90  Still same issue
```
error: cannot assign value of type 'Thread' to type 'Thread?'
                self.thread = thread
                            ^
[41/55] Compiling TSCUtility Versioning.swift
```

**Comment by danyf90** [comment]
Does it build if you open the project from Xcode? Have you tried to clean derived data?

**Comment by pavm035** [comment]
You mean tuist project? If so there no tuist project generated due to above error. Yes I have cleared derived data but still sam e issue. BTW i'musing Xcode 14 beta6 to generate the project

**Comment by danyf90** [comment]
> You mean tuist project? If so there no tuist project generated due to above error. Yes I have cleared derived data but still sam e issue. BTW i'musing Xcode 14 beta6 to generate the project

I would try with stable Xcode

**Comment by pavm035** [comment]
But i think proposed solution is to test for Xcode14 beta since it's new feature there

**Comment by danyf90** [comment]
oh right :D let me check if it compiles on my side 🤞

**Comment by danyf90** [comment]
Looks like swift-tools-support-core has some problems with Xcode 14, let me try to bump it

**Comment by danyf90** [comment]
@pavm035 I have just pushed some changes, could you try again? 🙏

**Comment by pavm035** [comment]
@danyf90  Sorry for delay response looks like build success and tool generated but when I try to generate the project getting following errors

```swift
warning: 'swiftgen': 'swiftgen' dependency on 'https://github.com/kylef/Stencil.git' conflicts with dependency on 'https://github.com/stencilproject/Stencil.git' which has the same identity 'stencil'. this will be escalated to an error in future versions of SwiftPM.
Building for debugging...
Build complete! (0.24s)
Resolved cache profile 'Development' from Tuist's defaults
`ArgumentParser` is not a valid configured external dependency for platform macos
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

**Comment by danyf90** [comment]
I don't get it why it complains for macos 🤔
Do you also have macos targets in your app?

**Comment by danyf90** [comment]
Also, what command are you running?

**Comment by pavm035** [comment]
@danyf90  We don't have macos target, BTW official tuist tool works fine with our project. Below command I'm using, Can you try from your end on sample app?

`swift run tuist generate --path /path/to/project`

**Comment by danyf90** [comment]
Maybe you should run fetch first?
Can you provide a sample project?

**Comment by pavm035** [comment]
@danyf90  You can check `tuist/fixtures/ios_app_with_watch_application` in the tuist directory to reproduce the issue
command:
 `swift run tuist generate <path>tuist/fixtures/ios_app_with_watch_application`

**Comment by danyf90** [comment]
generation works fine for me:
```
⋊> ~/D/tuist on feature/xcode14-watch-application ◦ swift run tuist fetch --path projects/tuist/fixtures/ios_app_with_watch_application
warning: 'swiftgen': 'swiftgen' dependency on 'https://github.com/kylef/Stencil.git' conflicts with dependency on 'https://github.com/stencilproject/Stencil.git' which has the same identity 'stencil'. this will be escalated to an error in future versions of SwiftPM.
Building for debugging...
Build complete! (0.43s)
Resolving and fetching plugins.
Plugins resolved and fetched successfully.

⋊> ~/D/tuist on feature/xcode14-watch-application ◦ swift run tuist generate --path projects/tuist/fixtures/ios_app_with_watch_application
warning: 'swiftgen': 'swiftgen' dependency on 'https://github.com/kylef/Stencil.git' conflicts with dependency on 'https://github.com/stencilproject/Stencil.git' which has the same identity 'stencil'. this will be escalated to an error in future versions of SwiftPM.
Building for debugging...
Build complete! (0.23s)
Resolved cache profile 'Development' from Tuist's defaults
Generating workspace AppWithWatchApp.xcworkspace
Generating project AppWithWatchApp
Project generated.
Total time taken: 0.369s
```

**Comment by BjoernLindner** [comment]
is there any way to help you?

**Comment by danyf90** [comment]
@BjoernLindner are you having this problem as well?
Can you confirm whether it's solved using tuist from [this branch](https://github.com/tuist/tuist/pull/4658)?

**Comment by BjoernLindner** [comment]
what is the best way to install this particular branch without compromising our productive environment?

**Comment by danyf90** [comment]
You can just clone tuist and run the commands from the tuist folder as in [this message](https://github.com/tuist/tuist/issues/4572#issuecomment-1243340664)

**Comment by BjoernLindner** [comment]
`swift run tuist generate --path projects/tuist/fixtures/ios_app_with_watch_application
warning: Usage of /Users/abc/Library/org.swift.swiftpm/collections.json has been deprecated. Please delete it and use the new /Users/abc/Library/org.swift.swiftpm/configuration/collections.json instead.
warning: 'swiftgen': 'swiftgen' dependency on 'https://github.com/kylef/Stencil.git' conflicts with dependency on 'https://github.com/stencilproject/Stencil.git' which has the same identity 'stencil'. this will be escalated to an error in future versions of SwiftPM.
Building for debugging...
Build complete! (1.04s)
Resolved cache profile 'Development' from Tuist's defaults
Couldn't find resource named ProjectDescription`

**Comment by pavm035** [comment]
@danyf90  Thank you so much i can generate the project and let me check more on original problem :). Thanks for your help
Basically I need to run command exactly as you said above
`swift run tuist generate --path <projct_path>`

**Comment by pavm035** [comment]
@kwridan  Looks like the project does not generate when we try to embed the watch app into the host app(iPhone app), If I try to add watchApp as a target dependency in the iOS app then it fails with the following error

<img width="1439" alt="Screen Shot 2022-09-13 at 13 05 15" src="https://user-images.githubusercontent.com/6092412/189805218-4611117b-5693-4ec9-9758-0f25a243946d.png">

To reproduce steps
1. Go to ios_app_with_watch_application
2. Add target dependency 
```swift
dependencies: [
                // ...
                .target(name: "WatchApp")
            ]
```
3. Generate project `swift run tuist generate --path <proj>`

**Comment by kwridan** [comment]
Thanks all for the follow ups here 🙏

> @kwridan Looks like the project does not generate when we try to embed the watch app into the host app(iPhone app), If I try to add watchApp as a target dependency in the iOS app then it fails with the following error

Indeed for the moment I've left this out because it doesn't appear like Xcode correlates or adds anything special to link the iOS App with the watch App anymore - for example, I just create a brand new project in Xcode 14 RC _(using the UI - no generation)_ 

![xcode14-rc](https://user-images.githubusercontent.com/11914919/189834515-eb53dea0-e3bc-46b4-aaf3-18f47163bc46.png)

There no longer appears to be an "Embed Watch App" build phase like there was in the past which strikes me as odd 🤔 - The equivalent now for tuist would be to omit `dependencies: [ .target(name: "WatchApp") ]`

**Comment by BjoernLindner** [comment]
@kwridan choose new watchOS project -> choose Watch App with New Companion iOS App -> there ist a watchApp in the dependencies of the iOS app

**Comment by kwridan** [comment]
Ah thanks @BjoernLindner - this makes more sense!

Looks like Xcode 14 may have a bug where if you choose an existing application it doesn't add said build phase 🤐

I'll update the branch to account for this.

**Comment by kwridan** [comment]
Updates pushed

**Comment by danyf90** [comment]
@pavm035 @BjoernLindner could you please confirm everything is fine with the latest changes on https://github.com/tuist/tuist/pull/4658?

**Comment by si-hartmann** [comment]
@danyf90 Thanks for this work! As Bjoern is on vacation I tried the branch and could build and start our watch app after adopting the new structure. So it looks good!

**Comment by pavm035** [comment]
@danyf90 Sorry for the delay, for me it works fine

**Comment by pavm035** [comment]
@danyf90  May i know when can this be released?

**Comment by pavm035** [comment]
@danyf90  @kwridan  Reason i'm asking for the release is we have an upcoming release in 2 weeks where we use this feature to migrate the existing app into a single target so would you please let me know the possible timeline of release?

**Comment by danyf90** [comment]
@pavm035 I think you can expect a release early next week, would it work for you?

**Comment by pavm035** [comment]
@danyf90  Thank you so much :)

**Comment by stefanomondino** [comment]
Hi @danyf90 and all, just wanted to give this topic a brief followup.
I am trying to setup a project with both iOS and watchOS target, where my watch app is a companion.

Seems like the two of them can work without embedding the watch app inside the iPhone one, however it seems that WatchConnectivity is not working with this setup: the iPhone seems to never understand it has a companion app, therefore it's always returning `false` in the `session.isWatchAppInstalled` of `WCSession`.

I was wondering if any of you had tried this scenario before; in the PR you say that "it's unclear" if embedding is still needed, seems like I may have found a valid reason but wanted to doublecheck first.

**Comment by danyf90** [comment]
> Hi @danyf90 and all, just wanted to give this topic a brief followup. I am trying to setup a project with both iOS and watchOS target, where my watch app is a companion.
> 
> Seems like the two of them can work without embedding the watch app inside the iPhone one, however it seems that WatchConnectivity is not working with this setup: the iPhone seems to never understand it has a companion app, therefore it's always returning `false` in the `session.isWatchAppInstalled` of `WCSession`.
> 
> I was wondering if any of you had tried this scenario before; in the PR you say that "it's unclear" if embedding is still needed, seems like I may have found a valid reason but wanted to doublecheck first.

@kwridan is the master here 🙏

**Comment by stefanomondino** [comment]
Just to clarify after further digging (and fixing) into my complex Tuist setup for a multiplatform application.
- Tuist is properly adding the WatchOS application ("new one", single target, no extension) but only if watch target is declared in the same project as the iOS one. I'm adding the watch target as a dependency of the iOS app and it works - I can see the target in the ios dependencies and the embed build phase is added. 
- If I don't do that, the watchos works anyway as a standalone app.
- Without embedding the app in the iOS target, WatchConnectivity (`WCSession`) doesn't work - the iPhone cannot see the companion app.

I don't think any fix is needed but I'm leaving this message for future readers - it took me a day to figure things out properly.
