### ISSUE TITLE
External C dependencies compile error

### ISSUE THREAD

**Issue by makleso6** [tuist/tuist#4582]
## Describe the bug and the expected behavior
I am using swift-nio-ssl as external dependence
when compile project there is error. But when compile in SPM package it works fine

## Reproduction steps

Steps to reproduce the bug:

clone `https://github.com/makleso6/CNIOBoringSSLError`
Run `tuist fetch`
Run `tuist generate`
build project

### Error log

```
`Include of non-modular header inside framework module 'CNIOBoringSSL.CNIOBoringSSL_bn': '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/clang/include/inttypes.h'`

Could not build Objective-C module 'CNIOBoringSSL'

```

### Additional context

- macOS version: 12.4
- Tuist version: 3.7.0
- Xcode version: 13.2.1

**Comment by danyf90** [comment]
Closed as per linked PR
