### ISSUE TITLE
Not support multiple entitlements

### ISSUE THREAD

**Issue by Qendrimi7** [tuist/tuist#4596]
I want to have 3 entitlements
1. Debug
2. Internal
3. Store

but tuist is not supporting but just once file, so I think you need to change this to array and to support multiple entitlements
<img width="810" alt="Screenshot 2022-07-08 at 3 46 20 PM" src="https://user-images.githubusercontent.com/33896371/178004654-a8bc83f8-8da3-4289-816d-b73f776967fe.png">
ay

**Comment by kwridan** [comment]
We've solved this via using a single entitlements file that references variables that are defined within the xcconfig files for the different configurations.

e.g.

```xml
	<key>key</key>
	<string>$(CUSTOM_KEY_VALUE)</string>
```

```
# debug.xcconfig
CUSTOM_KEY_VALUE = debug_value
```

```
# internal.xcconfig
CUSTOM_KEY_VALUE = internal_value
```

```
# store.xcconfig
CUSTOM_KEY_VALUE = store_value
```

**Comment by danyf90** [comment]
@Qendrimi7 let us know if you find any problem with Kas suggestion
