### ISSUE TITLE
Environment.xxx.getString fails if the string is "0" or "1"

### ISSUE THREAD

**Issue by cccCody** [tuist/tuist#4598]
## Describe the bug and the expected behavior

Environment.xxx.getString fails if the string is "0" or "1"

## Reproduction steps

Steps to reproduce the bug:

1. Start a new project, e.g. `tuist init --platform ios`
2. run `tuist edit`
3. add this line right before the return in Project+Templates.swift
```
print("buildNumber:", Environment.buildNumber.getString(default: ""))
```
4. try running `TUIST_BUILD_NUMBER=1 tuist generate` and get the following output:
```
Resolved cache profile 'Development' from Tuist's defaults
/Users/cody/tuisttest2/Project.swift: buildNumber:
Generating workspace Tuisttest2.xcworkspace
Generating project Tuisttest2
Project generated.
Total time taken: 6.320s
```
note that `buildNumber` is blank
5. try running `TUIST_BUILD_NUMBER=2 tuist generate` and get the following output:
```
Resolved cache profile 'Development' from Tuist's defaults
/Users/cody/tuisttest2/Project.swift: buildNumber: 2
Generating workspace Tuisttest2.xcworkspace
Generating project Tuisttest2
Project generated.
Total time taken: 6.877s
```

### Additional context

- macOS version: 12.4
- Tuist version: 3.8.0
- Xcode version: 13.1

**Comment by fortmarek** [comment]
Hey @cccCody 👋 

We save `1` as `.boolean(true)` [here](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Environment.swift#L21) and we never treat it as a string from that point on. My suggestion would be to save the original value [here](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Environment.swift#L7-L8) as well (extending the enums with another associated value of type `String`) and [here](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Environment.swift#L36), return the original value in case the type is `boolean`. 

Would be great if you wanted to implement this, I'm more than glad to help you out!
