### ISSUE TITLE
SwiftGen String Parser Problem

### ISSUE THREAD

**Issue by fegoulart** [tuist/tuist#4607]
## Describe the bug and the expected behavior

I have the following entry in my Localizable.strings

`"HowPackageWorks.stepView.drc.third.description.bold" = "de forma 100% digital";`

It was expected that a static let constant would be generated on SwiftGen Tuist Resource enum. But a function is generated instead.

`public enum Description {
          /// %@ pessoas
          public static func bold(_ p1: Any) -> String {
            return MeuAleloLegacyStrings.tr("Localizable", "HowPackageWorks.aditional.drc.description.bold", String(describing: p1))
          }
        }`

Here it is the Entry dictionary generated by line 100 (let entries = try parser.parseFile(at: path)) of StringsParser.swift (from SwiftGen / SwiftGenKit dependency) showing that an Integer variable was wrongly detected:

` ▿ 1377 : Entry
    - key : "HowPackageWorks.stepView.drc.third.description"
    - translation : "Pode realizar seus agendamentos diretamente por aqui, de forma 100% digital"
    ▿ types : 1 element
      - 0 : SwiftGenKit.Strings.PlaceholderType.int
    ▿ keyStructure : 5 elements
      - 0 : "HowPackageWorks"
      - 1 : "stepView"
      - 2 : "drc"
      - 3 : "third"
      - 4 : "description"`

## Reproduction steps

Steps to reproduce the bug:

Include a localizable string input with a % character like: 

`"HowPackageWorks.message.bold" = "we can guarantee 100% Just come";`

### Error log

N/A

### Error screenshots

N/A

### Additional context

- macOS version: 12.4
- Tuist version: 3.8.0
- Xcode version: 13.4.1

**Comment by dogo** [comment]
Hi @fegoulart, you need to escape the percentage symbol.

Eg:

"HowPackageWorks.stepView.drc.third.description.bold" = "de forma 100%% digital";
