### ISSUE TITLE
Can't build when a library that includes macCatalyst support is added in dependencies

### ISSUE THREAD

**Issue by DevYeom** [tuist/tuist#4610]
## Describe the bug and the expected behavior

Can't build when a library that includes macCatalyst support is added in dependencies.
Please check if this is caused by not supporting the macCatalyst platform in Tuist.

[Sources/TuistGraph/Models/Platform.swift](https://github.com/tuist/tuist/blob/f98b4427bfbf9cb7152f231caa84457bc1662030/Sources/TuistGraph/Models/Platform.swift)

## Reproduction steps

Steps to reproduce the bug:

1. Add a supporting macCatalyst library such as [kean/Get](https://github.com/kean/Get)
2. Run `tuist fetch` 
3. Run `tuist generate`
4. Build

### Error log

A failure message like the one below appears.

```
No such module 'Get'
```

### Error screenshots

![image1](https://user-images.githubusercontent.com/29133414/178634877-d246bcae-ed87-4683-a9a2-2652015d5a12.png)
![image2](https://user-images.githubusercontent.com/29133414/178634890-a0218b08-87ac-4db1-843a-baaaaa81eccb.png)

### Additional context

- macOS version: 12.0.1
- Tuist version: 3.8.0
- Xcode version: 13.4.1

**Comment by danyf90** [comment]
Please attach reproducible project

**Comment by obrhoff** [comment]
Seeing the same problem here as well with Get.

**Comment by danyf90** [comment]
@DevYeom @obrhoff please reopen when you can provide a reproducible sample project 🙏

**Comment by DevYeom** [comment]
@danyf90 
Here is the project where the bug is reproduced. Thank you :)

[StarterPackage.zip](https://github.com/tuist/tuist/files/9130579/StarterPackage.zip)
