### ISSUE TITLE
Unable to use local SPM dependencies in the root level of the project

### ISSUE THREAD

**Issue by wattson12** [tuist/tuist#4624]
## Describe the bug and the expected behaviour

I am using `tuist` to generate a workspace containing an SPM package, a demo app and unit tests. The structure is roughly this:
```
Workspace
   - Showcase 
       - SPM Target (dependency)
   - SPM Target 
   - SPM Target Tests   
```

I have declared the dependency using `.local(path: .relativeToRoot("."))` and can run `tuist fetch` successfully but when I generate the project using `tuist generate` I get the following error:
```
Swift/arm64e-apple-macos.swiftinterface:13494: Fatal error: Duplicate values for key: '<full path to directory where Package.swift is contained>'
```

## Reproduction steps

Steps to reproduce the bug:

1. Use the attached sample project (to be provided when opening the issue)
2. Run `tuist fetch && tuist generate -n`
3. See the error

### Error log

```
Swift/arm64e-apple-macos.swiftinterface:13494: Fatal error: Duplicate values for key: '<full path to directory where Package.swift is contained>'
```

### Error screenshots

n/a

### Additional context

- macOS version: 12.4
- Tuist version: 3.8.0
- Xcode version: 13.4

I have been able to workaround this issue by moving `Project.swift` to another directory (e.g. under `Tuist/`) and having a `Workspace.swift` file at the same level as `Package.swift` though it would be nice to have a better fix since moving the project file requires changing relative paths which is easy to forget 

### Sample Project 

[tuist-spm-demo.zip](https://github.com/tuist/tuist/files/9142156/tuist-spm-demo.zip)

**Comment by wattson12** [comment]
> Can you try to not put the Package.swift at the same level of the Project.swift?

As with the other workaround that also works, though this project is intended to be an SPM vendored library so I'd rather not move the package definition out (I'm not sure if its a requirement of SPM to have `Package.swift` at the root level but it definitely seems to be the convention)

**Comment by danyf90** [comment]
I see, unfortunatly at the moment I think it's the only way, as Tuist assumes only one project is present in a given folder, and the package is effectively mapped to a Tuist project 🤔 

One slightly unrelated question, why would you define the tests in Tuist rather than in SPM?

**Comment by wattson12** [comment]
> I see, unfortunatly at the moment I think it's the only way, as Tuist assumes only one project is present in a given folder, and the package is effectively mapped to a Tuist project 🤔

makes sense, I have a workaround that I'm fine with for now so feel free to close this if its not a common issue. 

> One slightly unrelated question, why would you define the tests in Tuist rather than in SPM?

Unfortunately the SPM runs tests as macOS targets no matter what platforms you support so using `swift test` will fail if you import `iOS` specific frameworks like `UIKit`. To workaround this (and also since I was already using tuist to generate a demo app) I am using tuist to create a test target (its actually defined in both places in the hope that SPM tests will support iOS at some point)

I could use `xcodebuild` to generate an Xcode project and then run iOS tests but tuist is easier 😄

**Comment by danyf90** [comment]
> Unfortunately the SPM runs tests as macOS targets no matter what platforms you support so using `swift test` will fail if you import `iOS` specific frameworks like `UIKit`. To workaround this (and also since I was already using tuist to generate a demo app) I am using tuist to create a test target (its actually defined in both places in the hope that SPM tests will support iOS at some point)

Makes sense, note that you can use xcodebuild to run tests of the package without generating the project with something like:
```
xcodebuild test -scheme ${scheme_name} -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.4'
``` 

Thanks for reporting it, let's close the issue for now, and we'll see if the needs for it arises again in the future 🙏
