### ISSUE TITLE
Project generated using tuist shows git ignored files to "Xcode => Source Control => Commit Window"

### ISSUE THREAD

**Issue by PatilManoj1717** [tuist/tuist#4630]
Please find attached images

<img width="1331" alt="Screenshot 2022-07-24 at 5 48 47 PM" src="https://user-images.githubusercontent.com/10806194/180647444-501914c3-8d9d-48d9-8dbc-b072643b30b7.png">
<img width="537" alt="Screenshot 2022-07-24 at 5 52 22 PM" src="https://user-images.githubusercontent.com/10806194/180647453-f0476447-6462-45ec-997c-145b0486ae73.png">

- macOS version: 12.0.1
- Tuist version: 3.3.0
- Xcode version: 13.1

**Comment by PatilManoj1717** [comment]
@PierreCapo can you help me on this?

**Comment by danyf90** [comment]
Looks like an Xcode issue 😁

**Comment by PatilManoj1717** [comment]
any work-around? @danyf90

**Comment by PatilManoj1717** [comment]
@danyf90 please look into this issue, don't know how people are using `Xcode Source Control` tool with this bug. 
Any workaround?

Issue is because of Xcode referring to `.git' folders in `/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/{*}/.git`

**Comment by danyf90** [comment]
> don't know how people are using `Xcode Source Control` tool

😁
