### ISSUE TITLE
Tell `tuist graph` not to open the generated image

### ISSUE THREAD

**Issue by danrevah** [tuist/tuist#4636]
## Current behaviour

Running

```
$ tuist graph --format=png
```

Generates a PNG and **opens** the image file.

## Expected behaviour

Add a command flag telling `tuist graph` not to open the generated file.

This is useful in cases where you have CI that generates the image (pre-commit) and you don't want the image to show up.

## Proposed

```
$ tuist graph --format=png --silent    # skips the file opening
```
Or:
```
$ tuist graph --format=png --open      # opens the file
```

**Comment by fortmarek** [comment]
Hey @danrevah 👋 

That's definitely reasonable. We already have `tuist generate --no-open` that achieves exactly that but for generation. Having `tuist graph --format=png --no-open` would thus make sense imho. Would you want to go ahead and implement this? 🙂

**Comment by danrevah** [comment]
I might be able to find some time for this.. Do you want to guide me in the code to save some time though?
Code paths / tests implementation / etc ... ?

**Comment by danrevah** [comment]
Done. PR awaits review
