### ISSUE TITLE
Unable to copy file located in `BUILT_PRODUCTS_DIR` as part of Copy Files build phase

### ISSUE THREAD

**Issue by Killectro** [tuist/tuist#4640]
## Describe the bug and the expected behavior

As part of [setting up EarlGrey](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md) I've tried a few different methods of getting access to the `AppFramework` in Tuist to be able to copy it to the main app target's frameworks directory (as described in the link above). I believe what I'm running into is that Tuist is looking relative to the project directory for any files to copy in this build phase, but this framework exists in `BUILT_PRODUCTS_DIR` which isn't a directory in the repo.

Is there a way that I'm missing to point `CopyFilesAction` to `BUILT_PRODUCTS_DIR` when providing a path? An example of what I tried that didn't work:

```swift
.frameworks(
    name: "Copy AppFramework Into App Target",
    subpath: "some subpath",
    files: [
        "/${BUILT_PRODUCTS_DIR}/AppFramework.framework",
    ]
)
```

## Reproduction steps

Steps to reproduce the bug:

I don't have a sample project because it's not very trivial to create but if contributors deem it necessary I can put one together.

### Error log

```
No files found at: /<path to git repo>/${BUILT_PRODUCTS_DIR}/AppFramework.framework
```

Notice that it isn't interpolating the actual value of `BUILT_PRODUCTS_DIR`, but placing that literal string into the path :(

### Additional context

- macOS version: 12.1.0
- Tuist version: 3.8.0
- Xcode version: 13.2

**Comment by kwridan** [comment]
Thanks for flagging this @Killectro

Currently `CopyFiles` can't handle arbitrary paths with variables. In the Xcode UI, you have to select a valid file or product from the file selector.

![Screenshot 2022-08-12 at 16 24 04](https://user-images.githubusercontent.com/11914919/184388294-f9ecd212-3133-49a8-a2b3-1cd8cff2d302.png)

This differs slightly from `TargetScripts` where input / output paths are raw strings and as such it does allow the use of variables directly:

![Screenshot 2022-08-12 at 16 25 20](https://user-images.githubusercontent.com/11914919/184387910-c7097c0e-3f0e-42e4-a231-694555fb7396.png)

From what I read on early grey, what it's doing is embedding (copying) an extra framework into the app target from the UI test target build phases ... that adds another layer of complication which may not be easily supportable in Tuist 🤐.

One suggestion I would offer is to leverage a custom script to do the copying, as the script has access to the same build variables:

e.g. 

```swift
          scripts: [
                .post(
                    script: """
                    cp -r ${BUILT_PRODUCTS_DIR}/AppFramework.framework ${BUILT_PRODUCTS_DIR}/MyApp.app/Frameworks
                    """,
                    name: "Copy App Framework for testing",
                    basedOnDependencyAnalysis: false
                ),
            ]
```

Hope this helps!

**Comment by danyf90** [comment]
Closing as per Kas' comment
