### ISSUE TITLE
Unit test target as a dependency in iOS platform

### ISSUE THREAD

**Issue by danrevah** [tuist/tuist#4645]
## Describe the bug and the expected behavior

Getting an error while trying to add a unit test target as a dependency of another unit test target.

```
Target ATests has platform 'iOS' and product 'unit tests' and depends on target BTests of type unit tests and platform 'iOS' which is an invalid or not supported yet combination.
```

Is there any particular reason this is not supported? Is there any plan to support this anytime soon?

## Reproduction steps

Add a unit test target as a dependency of another unit test target.

**Comment by kwridan** [comment]
Hi @danrevah 

To my knowledge this is an invalid dependency, so the error seems legit. Is it possible in Xcode (without tuist) to make a unit test target link another?

May help if you can share what you are trying to accomplish by making a unit test target depend on another - there may be other better suited alternatives.

**Comment by danrevah** [comment]
Right, I guess it's not supported as it seems like we can't really import files from a test target.

It came from a requirement to import MOCKS from one test target to another.

For e.g.

```swift
[
    Target(
       // ...
        name: "ATarget",
        platform: .iOS,
        product: .unitTests,
        sources: [ /* Tests + Mocks*/ ]
    ),
   Target(
       // ...
        name: "BTarget",
        platform: .iOS,
        product: .unitTests,
        dependencies: [ /* ATarget has relevant mocks ... */ ]
    )
]
```

I guess adding an additional Target (static library) for `ATargetMocks` would solve it in case it's not possible.

**Comment by kwridan** [comment]
Ah for that use case a common pattern is to create a dedicated mock target to share between test targets

```swift
[
    Target(
       // ...
        name: "AMocks",
        platform: .iOS,
        product: .unitTests,
        sources: [ /* Mocks*/ ]
    ),
    Target(
       // ...
        name: "ATargetTests",
        platform: .iOS,
        product: .unitTests,
        sources: [ /* Tests */ ],
        dependencies: [
            .target(name: "AMocks"),
       ]
    ),
   Target(
       // ...
        name: "BTargetTests",
        platform: .iOS,
        product: .unitTests,
        dependencies: [
            .target(name: "AMocks"),
       ]
    )
]
```

Hope this helps

**Comment by danrevah** [comment]
Makes sense.

Thank you!
