### ISSUE TITLE
Lint projects graph to ensure matching configurations are used in all projects

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#467]
# Overview

Add the ability to lint the project graph to flag any dependency projects that have mismatching configurations.

This can be a warning, as it is technically possible to have projects with different configurations in Xcode, though may not be what is intended.

# Example

- Project A
   - Targets:
        - Target A
   - Configurations:
        - Debug
        - Beta
        - Release
   - Dependencies:
       - Target B

- Project B
   - Targets:
        - Target B
   - Configurations:
        - Debug
        - Release

When linting, the fact Project B has a different set of configurations should be flagged

# Considerations

For projects, the entry node of the graph is the project where `tuist generate` is run.

For workspaces there could be several entry points (which may themself have cross dependencies) as such it may be difficult to identify which is the authoritative list of configurations.

To mitigate we can flag differences we encounter as opposed to what is missing. 

# Additional Context

This was proposed in the context of introducing multiple configurations .

> I wonder if we need to have some linting at the Graph level which notifies the user of configurations not defined in manifests. I can imagine on larger projects it might be easy to miss one, or even worse, mis-spell one.

_Originally posted by @ollieatkinson in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTg5MjUwMTI1OnYy/pull_request_review_threads/discussion_

**Comment by pepibumur** [comment]
This is a good idea. I've seen compilation errors in the past because the configurations of the modules didn't match.
