### ISSUE TITLE
GPU Frame Capture not included in Scheme configuration

### ISSUE THREAD

**Issue by SpectralDragon** [tuist/tuist#4673]
## Describe the bug and the expected behavior

In Project.swift file you can't setup GPU Frame Capture option in `Scheme` constructor. In options I can setup StoreKit or main thread checker options, but no options improved for Metal developers.

## Reproduction steps

Steps to reproduce the bug:

1. Generate any project with tuist
2. Open `Edit Scheme...` and select `Run -> Options`
3. See that `GPU Frame Capture` set as `Automatically`

### Error screenshots

<img width="927" alt="image" src="https://user-images.githubusercontent.com/6003467/184039675-816344f2-7929-4336-9e10-0f20adf05a65.png">

### Additional context

- macOS version: 12.4
- Tuist version: 3.2.0
- Xcode version: 13.3.1

**Comment by danyf90** [comment]
Have you tried with a more recent version? Should be supported now

**Comment by SpectralDragon** [comment]
Yeah, thanks, it works! 
I have been search the question in issues, but I got 0 results for query `GPU Capture Frame` and after that I created the issue.
