### ISSUE TITLE
<Dependency> is not a valid configured external dependency for platform ios

### ISSUE THREAD

**Issue by malcommac** [tuist/tuist#4674]
My app has two frameworks `IndomioMetrics` and `IndomioCommons`.
`IndomioCommons` depends on `IndomioMetrics` and uses several of its external dependencies, along with one, named `Glider`, linked via SPM.

`IndomioCommons (Local) -->  IndomioMetrics (Local) --> (SPM) Glider`

When I try to generate the project of the upper framework `IndomioCommons` it fails with an error about the external lib used by the lower framework: `Glider is not a valid configured external dependency for platform ios`.

No error is triggered with the framework `IndomioMetrics` which imports `Glider` directly.

#### IndomioMetrics Dependencies

`IndomioMetrics`'s `Project.swift`:

```swift
import ProjectDescription
let project = Project(
    name: "IndomioMetrics",
    targets: [
        Target(
            name: "IndomioMetrics",
            platform: .iOS,
            product: .framework,
            bundleId: "com.indomio.metrics",
            deploymentTarget: .iOS(targetVersion: "14.0", devices: [.ipad,.iphone]),
            sources: ["Sources/IndomioMetrics/Classes/**"],
            resources: [

            ],
            dependencies: [
                .external(name: "Glider"),
                .external(name: "GliderSentry")
            ]
        )
    ]
)
```

Inside the `Dependencies.swift` it declares the external library (`Glider`) imported via SPM:

```swift
import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/malcommac/Glider.git", requirement: .branch("main"))
    ],
    platforms: [.iOS]
)
```

#### IndomioCommons Dependencies

`IndomioCommons` declare several other dependencies along with its dependency on `IndomioMetrics`:

```swift
// Project.swift
import ProjectDescription
let baseSettings = SettingsDictionary().bitcodeEnabled(false)
let project = Project(
    name: "IndomioCommons",
    targets: [
        Target(
            name: "IndomioCommons",
            platform: .iOS,
            product: .framework,
            bundleId: "com.indomio.commons",
            deploymentTarget: .iOS(targetVersion: "14.0", devices: [.ipad,.iphone]),
            sources: ["Sources/IndomioCommons/Classes/**"],
            resources: [

            ],
            dependencies: [
                .project(target: "IndomioMetrics", path: "../IndomioMetrics"),
                .external(name: "..."),
                ...
            ],
            settings: .settings(base: baseSettings)
        )
    ]
)
```

#### Glider (External) Dependency

[That's the `Package.swift` file](https://github.com/malcommac/Glider/blob/main/Package.swift) for the external dependency.

#### Error

If I try to use `tuist fetch && tuist generate --no-cache` on `IndomioMetrics` everything works fine.  
It compiles with its external lib.  

**However, when I try the same command on the upper framework `IndomioCommons` results in the following error:**

```
Dependencies resolved and fetched successfully.
Resolved cache profile 'Development' from Tuist's defaults
`Glider` is not a valid configured external dependency for platform ios
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

While it seems strange to me, I've also tried to re-declare the entire dependency also into the upper framework `IndomioCommons`; no error during fetch/generate but I got the following error while compiling:

`Use of undeclared identifier 'SWIFTPM_MODULE_BUNDLE'`

Each time on a different file, for example:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/235645/184102375-2bcd1fb4-e69f-4c58-b7bc-cf7116bdb86f.png">

What's the correct way to declare these kinds of relations?

### Additional context

- macOS version: 12.5
- Tuist version: 3.9.0
- Xcode version: 13.4.1

**Comment by danyf90** [comment]
Ciao 👋 
Having a sample project would greatly simplify understanding the project structure.

If I understood correctly, you have:
- a project (`IndomioMetrics`) defining its own dependencies.swift and depending on external SPM packages
- a project (`IndomioCommons`) (potentially defining its own dependencies.swift?) depending on the above project

If that's the case, it's something we have considered but it's not currently supported.

As a workaround, is there a reason why `IndomioMetrics` must be a separate project with separate dependencies? If you define single Dependencies.swift for the `IndomioCommons` you should be able to prepare the `IndomioMetrics` project from the `IndomioCommons` folder by running `tuist generate IndomioMetrics` (maybe you need to define a `Workspace.swift` to link together the project, or you can even have a single project instead of two).
Another alternative would be to expose IndomioMetrics as an SPM package instead.

**Comment by danyf90** [comment]
The `SWIFTPM_MODULE_BUNDLE` error should be due to [this open issue](https://github.com/tuist/tuist/issues/3785)

**Comment by malcommac** [comment]
> Ciao 👋 Having a sample project would greatly simplify understanding the project structure.

Ciao!  Thanks for the quick reply!
Yes, of course, that's a simple project which demonstrates the issue:
[TestDependencies.zip](https://github.com/tuist/tuist/files/9307760/TestDependencies.zip)

You can execute `tuist generate` on IndomioMetrics and it works fine.  
If you try the same with the IndomioCommons it fails:

```
Dependencies resolved and fetched successfully.
Resolved cache profile 'Development' from Tuist's defaults
`Glider` is not a valid configured external dependency for platform ios
```

> As a workaround, is there a reason why `IndomioMetrics` must be a separate project with separate dependencies? If you define single Dependencies.swift for the `IndomioCommons` you should be able to prepare the `IndomioMetrics` project from the `IndomioCommons` folder by running `tuist generate IndomioMetrics` (maybe you need to define a `Workspace.swift` to link together the project, or you can even have a single project instead of two). Another alternative would be to expose IndomioMetrics as an SPM package instead.

Yes unfortunately I cannot change the structure. In fact, we have several layers of frameworks with the same infrastructure, currently handled by CocoaPods. Each of them imports several external dependencies while also importing underneath local frameworks, all exposed to the upper frameworks.

If I understand correctly your suggestions I should expose all of these frameworks as SPM leaving only the main host application to use Tuist?

**Comment by danyf90** [comment]
> If I understand correctly your suggestions I should expose all of these frameworks as SPM leaving only the main host application to use Tuist?

Yes, in our case for "internal-but-external" frameworks we are using Tuist while developing them, but exposing them as SPM packages to be used by the main app.
This also has the advantage of easily cache them while working on the main app.

Of course having to define also the SPM package is not ideal, and having support for "transitive" external dependencies from other tuist projects would be ideal, but i's not trivial to implement (even though for local project should be simpler).

**Comment by malcommac** [comment]
Ok, that's clear; in fact, it's better to deal with the SPM implementation instead of forcing Tuist to do the "same" work.
I'll move to SPM all of those frameworks and try again with the main project only.
I'll let you know, thank you again for your quick support. Can't wait to move our project to Tuist 🤞
