### ISSUE TITLE
Can't seem to get FirebaseCrashlytics (SPM) building when archiving (can't find header)

### ISSUE THREAD

**Issue by stevelandeyasana** [tuist/tuist#4677]
## Describe the bug and the expected behavior

I'm migrating a complex app from a manually managed Xcode project to Tuist. It's really great! I'm finally at the stage where I'm testing my release pipeline with the migrated project. Unfortunately, I'm seeing this error in `xcodebuild archive` before it even starts compiling my code:

```
[00:15:55]: ▸ Touching FirebaseAnalyticsWithoutAdIdSupportWrapper.framework (in target 'FirebaseAnalyticsWithoutAdIdSupportWrapper' from project 'Firebase')
[00:15:55]: ▸ Processing FirebaseAnalyticsWithoutAdIdSupportTarget-Info.plist
[00:15:55]: ▸ Compiling dummy.m
[00:15:55]: ▸ Compiling FirebaseAnalyticsWithoutAdIdSupportTarget_vers.c
[00:15:55]: ▸ Touching FirebaseAnalyticsWithoutAdIdSupportTarget.framework (in target 'FirebaseAnalyticsWithoutAdIdSupportTarget' from project 'Firebase')
[00:15:56]: ▸ Touching FirebaseCrashlytics.framework (in target 'FirebaseCrashlytics' from project 'Firebase')
[00:15:57]: ▸ Copying Intents.strings
[00:16:09]: ▸ ❌  ************************/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/firebase-ios-sdk/CoreOnly/Sources/Firebase.h:15:9: 'FirebaseCore/FirebaseCore.h' file not found
[00:16:09]: ▸ #import <FirebaseCore/FirebaseCore.h>
```

The exact same project setup works fine when building and running locally.

I'm not sure whether this is a Tuist issue or not, but I think I've done things in a pretty straightforward way and I'm not sure where else to ask, so here's a GitHub issue. :-)

I'm at the point now where I'd consider hiring a maintainer for some realtime debugging, if this isn't a Tuist bug. Email me at stevelandey@asana.com if that makes sense for you. I can't provide an example project here because I can only reproduce the issue on CircleCI at the moment.

## Reproduction steps

**Dependencies**

```swift
let dependencies = Dependencies(
  carthage: CarthageDependencies([/* omitted for brevity */]),
  swiftPackageManager: [
    .remote(url: "https://github.com/google/GoogleSignIn-iOS.git", requirement: .exact("6.0.1")),
    .remote(url: "https://github.com/firebase/firebase-ios-sdk.git", requirement: .exact("9.4.1")),
  ],
  platforms: [.iOS])
```

**Target**

```swift
public let WidgetTarget = Target(
  name: "AsanaWidget",
  platform: .iOS,
  product: .appExtension,
  bundleId: Deploy.current.widgetBundleId, // com.asana.Asana-Nightly.AsanaWidget
  deploymentTarget: Constants.deploymentTarget, // 14.0
  infoPlist: "AsanaWidget/Supporting Files/Info.plist",
  sources: [
    // some files
  ],
  resources: [], // some resources
  scripts: [
    crashlyticsUploadScript(),
  ],
  dependencies: [
    .sdk(name: "SwiftUI", type: .framework),
    .sdk(name: "UIKit", type: .framework),
    .sdk(name: "WidgetKit", type: .framework),

    .target(name: "ObjCHelpers"),

    .external(name: "AFNetworking"),
    .external(name: "FirebaseAnalyticsWithoutAdIdSupport"),
    .external(name: "FirebaseCrashlytics"),
    .external(name: "SAMKeychain"),
  ],
  settings: xcconfig("AsanaWidget/AsanaWidget.xcconfig", settings: Deploy.current.getTargetSettings(suffix: ".AsanaWidget")))
```

### Error log

Full error log with minor censorship: https://gist.github.com/stevelandeyasana/53a782052674587875d0f76e1a62a610

## Differences I can find between my original project file and the Tuist one

My original project shows the SPM dependencies in the navigator sidebar, whereas Tuist seems to precompile them and not add them to the Xcode project.

The dependencies seem to be linked differently. In the original project, I think they are linked as static libraries:
![Screen Shot 2022-08-11 at 10 56 09 AM](https://user-images.githubusercontent.com/38225497/184204791-acc27b42-c65f-4556-b2d6-9ac8a22b2322.png)

But in the Tuist version, I only see frameworks:
![Screen Shot 2022-08-11 at 10 56 31 AM](https://user-images.githubusercontent.com/38225497/184204992-57091b67-4e5b-4a5f-ae01-20f1e9664dfe.png)

### Additional context

- macOS version: X.X.X
- Tuist version: X.X.X
- Xcode version: X.X.X

**Comment by stevelandeyasana** [comment]
I was able to get an unsigned simulator archive to work locally. I was also able to work around the issue by using the (new?) "native SPM" integration instead of Tuist's custom thing. So I think it's some weird interaction between Tuist and either Gym or generic arm64 builds. Happy to provide more info, just let me know what would be most helpful.

For the time being, I have a workaround for the issue: use native SPM for archive builds, and Tuist SPM for development.

**Comment by danyf90** [comment]
So archive works fine locally but not in CI? 🤔

**Comment by stevelandeyasana** [comment]
I'd say archiving works for the simulator when I run xcodebuild manually, and does not work for generic arm64 when using fastlane on CircleCI. There's a lot of wiggle room in there. :-) My gut feeling is that the way Tuist builds SPM packages separately is not working for the way Crashlytics is distributed (static libraries + dummy frameworks).

I really wish I could give you a minimal example, I just think it would take me an hour or two that I don't have. Now that I found a workaround this isn't a critical issue, but maybe something to keep in mind when other bugs are reported.

**Comment by danyf90** [comment]
We have Crashlytics in our project and it works fine.
If you don't have time to provide more info, I'll close the issue for now. Feel free to reopen it when you have more info
