### ISSUE TITLE
Tuist Test fails when adding the Stripe SDK via SPM

### ISSUE THREAD

**Issue by mark-tegan** [tuist/tuist#4684]
## Describe the bug and the expected behavior

Hi. When I add the Stripe SDK via SPM, I am unable to run`tuist test`. I receive the following error:

```
Trying to add a file at path /Users/ski081/Desktop/Payments/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCardScan/StripeCardScan/Resources/CompiledModels/SSDOcr.mlmodelc/analytics/coremldata.bin to a build phase that hasn't been added to the project.
```

I have tried using `Dependencies.swift` and also by creating an external dependency and adding it to the `packages` argument of the project. 
 
## Reproduction steps

1. Create a new project with `tuist init`
2. Add the Strip SDK to `Dependencies.swift`
3. Add the Stripe SDK to the `dependencies` argument in the `Project` initializer.
4. Run `tuist fetch`
5. Run `tuist generate`
6. Run `tuist test`

Steps to reproduce the bug:

1. Use the attached sample project (to be provided when opening the issue)
2. Run `tuist fetch`
3. Run `tuist generate`
4. Run `tuist test`
5. See the error 

### Error log

```
Generating project for testing
Generating workspace Payments.xcworkspace
Generating project Stripe
Generating project Payments
Trying to add a file at path /Users/ski081/Desktop/Payments/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCardScan/StripeCardScan/Resources/CompiledModels/SSDOcr.mlmodelc/analytics/coremldata.bin to a build phase that hasn't been added to the project.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### Additional context

- macOS version: 12.5
- Tuist version: 3.9.0
- Xcode version: 13.4.1

I'm attaching an example project that demonstrates the problem:
[Payments.zip](https://github.com/tuist/tuist/files/9355787/Payments.zip)

**Comment by mikchmie** [comment]
Should be fixed by https://github.com/tuist/tuist/pull/4685
