### ISSUE TITLE
Can't cache Firebase (SPM) when setting `productTypes` as dynamic framework

### ISSUE THREAD

**Issue by Arafo** [tuist/tuist#4694]
### What happened?

I'm trying to get Firebase integrated into my app as a dynamic framework setting  every Firebase dependency `productType` as `.framework`

```
        productTypes: [
            "abseil": .framework,
            "FBLPromises": .framework,
            "Firebase": .framework,
            "FirebaseABTesting": .framework,
            "FirebaseAnalytics": .framework,
            "FirebaseAnalyticsTarget": .framework,
            "FirebaseAnalyticsWrapper": .framework,
            "FirebaseAuth": .framework,
            "FirebaseCore": .framework,
            "FirebaseCoreDiagnostics": .framework,
            "FirebaseCoreInternal": .framework,
            "FirebaseCrashlytics": .framework,
            "FirebaseFirestore": .framework,
            "FirebaseFirestoreTarget": .framework,
            "FirebaseInstallations": .framework,
            "FirebasePerformance": .framework,
            "FirebasePerformanceTarget": .framework,
            "FirebaseRemoteConfig": .framework,
            "GoogleAppMeasurementTarget": .framework,
            "GoogleDataTransport": .framework,
            "GoogleUtilities_UserDefaults": .framework,
            "GoogleUtilities_MethodSwizzler": .framework,
            "GoogleUtilities_Reachability": .framework,
            "GoogleUtilities_Environment": .framework,
            "GoogleUtilities_ISASwizzler": .framework,
            "GoogleUtilities_AppDelegateSwizzler": .framework,
            "GoogleUtilities_NSData": .framework,
            "GoogleUtilities_Network": .framework,
            "GoogleUtilities_Logger": .framework,
            "gRPC-cpp": .framework,
            "gRPC-Core": .framework,
            "GTMSessionFetcherCore": .framework,
            "GTMSessionFetcherFull": .framework,
            "nanopb": .framework,
            "openssl_grpc": .framework
        ]
```

But unfortunately that doesn't work when running `tuist cache warm --xcframeworks`

```
❌ Undefined symbols for architecture x86_64
❌   "typeinfo for grpc::ServerCredentials", referenced from:
❌   "grpc::ServerCredentials::~ServerCredentials()", referenced from:
❌   "grpc::ServerCredentials::ServerCredentials()", referenced from:
❌ ld: symbol(s) not found for architecture x86_64
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I don't set `productType` property and leave every target to be generated as a static framework, it works fine.

### How do we reproduce it?

I attached a sample project showcasing this issue. Steps to test:

1. Download project and decompress it [firebase-tuist-test.zip](https://github.com/tuist/tuist/files/9415590/firebase-tuist-test.zip).
2. Run `tuist fecth`
3. Run `tuist cache warm --xcframeworks`

### Error log

```
❌ Undefined symbols for architecture x86_64
❌   "typeinfo for grpc::ServerCredentials", referenced from:
❌   "grpc::ServerCredentials::~ServerCredentials()", referenced from:
❌   "grpc::ServerCredentials::ServerCredentials()", referenced from:
❌ ld: symbol(s) not found for architecture x86_64
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### macOS version

12.2.1

### Tuist version

3.9.0

### Xcode version

13.4.1

**Comment by Arafo** [comment]
Mainly because of cache size, dynamic frameworks take ~1,7GB and static ones ~2.5GB.

As side effect of going with static frameworks, each time I run `tuist generate`  with cache enabled from tuist cloud, I end up with a behavior similar to the one described [here](https://github.com/tuist/tuist/issues/4556#issuecomment-1213154001), artifacts failing to download and having to run the `generate` command multiple times until it success to download every artifact.

**Comment by danyf90** [comment]
How can you know the different cache size if the command fails?

**Comment by Arafo** [comment]
Sorry for the delay @danyf90, I completely forgot to answer

Answering your question, I was able to know the different because cache warm worked fine and I was able to upload the cached targets through tuist cloud but it failed when running `tuist generate` in a different machine downloading cached targets from tuist cloud.

Anyway I got this sorted out defining `gRPC-Core` as a dynamic framework and setting up some preprocessor variables

```swift
targetSettings: [
    "gRPC-Core": [
        "GCC_PREPROCESSOR_DEFINITIONS": "$(inherited) GRPC_NO_BINDER=0 GRPC_ARES=0"
    ]
]
```

Now `gRPC-Core` xcframework is around 90MB (iOS arm64 and Intel x86_64), still huge but more manageable 

Got a hint from this comment in the gRPC bazel file:
https://github.com/grpc/grpc-ios/blob/cdc88b79889a58b063bd3221630d9d9c6deee1d2/native/BUILD#L52

**Comment by danyf90** [comment]
Thanks a lot for the investigation and for reporting it back @Arafo ! 🙏
