### ISSUE TITLE
[Dependencies.swift] Package.swift uses absolute instead of relative paths for local packages

### ISSUE THREAD

**Issue by thedavidharris** [tuist/tuist#4695]
### What happened?

As noted in this snippet:

```
// MARK: - Package.manifestValue()

extension Package {
    /// Returns `Package.swift` representation.
    fileprivate func manifestValue(isLegacy: Bool) -> String {
        switch self {
        case let .local(path):
            // FIXME: This should be a relative path, not an absolute path
            return #".package(path: "\#(path)")"#
        case let .remote(url, requirement):
            let requirementManifestValue = isLegacy ? requirement.legacyManifestValue : requirement.manifestValue
            return #".package(url: "\#(url)", \#(requirementManifestValue))"#
        }
    }
}
```

The path there is using an absolute path which differs on machines. Although Tuist is able to paper over this since Package.swift is always generated, some teams need to check in the Package.swift and Package.resolved files as these are used to generate things such as license files and scanning of open source software.

### How do we reproduce it?

Fetch dependencies on any project with a local package

### Error log

No specific error log, but the path will change in different machines or even different directories

### macOS version

12.5.1

### Tuist version

3.9.0

### Xcode version

13.4.1

**Comment by thedavidharris** [comment]
I'm having a look at fixing this, doesn't seem super involved, but the one detail I could use some help on how relative paths are built here relative to the root of the project

**Comment by danyf90** [comment]
I think you can just make it relative to the `pathsProvider.destinationPackageSwiftPath`, which is were the Package.swift will end up

**Comment by danyf90** [comment]
> I'm having a look at fixing this, doesn't seem super involved, but the one detail I could use some help on how relative paths are built here relative to the root of the project


I think you can just make it relative to the pathsProvider.destinationPackageSwiftPath, which is were the Package.swift will end up
