### ISSUE TITLE
Fix supported platformFilters

### ISSUE THREAD

**Issue by dever25** [tuist/tuist#4708]
### What happened?

I have enabled mac catalyst support in my application. It is necessary that when connecting libraries, the filter parameter should be set to the "always used" position
<img width="1024" alt="Снимок экрана 2022-09-01 в 16 07 49" src="https://user-images.githubusercontent.com/32138530/187876947-07d4115e-baeb-42dd-854e-39fe2b3e7cb4.png">

But this cannot be set, because the targetDependencyBuildFilesPlatformFilter variable will not return such a value.

```    
/// For iOS targets that support macOS (Catalyst), this value is used
    /// in the generated build files of the target dependency products to
    /// indicate the build system that the dependency should be compiled
    /// with Catalyst compatibility.
    public var targetDependencyBuildFilesPlatformFilter: BuildFilePlatformFilter? {
        switch deploymentTarget {
        case let .iOS(_, devices):
            if devices.contains(.mac) {
                return .catalyst
            } else {
                return .ios
            }
        default:
            return nil
        }
    }
 ```
 
 It seems with such a record
 `.iOS(targetVersion: version, devices: [.iphone, .mac, .iPad])`
 need to return "always used"(nil?)
 

### How do we reproduce it?

```
let appNavigationTarget = Target.framework(
    name: appName + "Navigation",
    deploymentTarget: DeploymentTarget.iOS(targetVersion: "14.0", devices: [.iphone, .mac, .ipad]),
    sourceFolder: .custom("Navigation"),
    dependencies: [
        .internal(.reduxCore)
    ]
)
```

### Error log

-

### macOS version

12.3.1

### Tuist version

3.4.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
Makes sense, I guess you need to change that part to return:
- catalyst if it only contains mac
- ios if it doesn't' contain mac
- nil otherwise

Do you want to try to open a PR for it? 🙏

**Comment by dever25** [comment]
Yes, I do :+1:

**Comment by dever25** [comment]
@danyf90 How can I make tuist binary with my changes until a new version of tuist is available?
I realized what [bundle](https://docs.tuist.io/guides/version-management#bundle) does from the global version, not the local one

**Comment by danyf90** [comment]
./fourier release tuist if I remember correctly 🤔

**Comment by dever25** [comment]
> ./fourier release tuist

Thanks, but isn't this command doing the same thing as bundle? 
`fourier release tuist VERSION` == tuistenv bundle
I need to create a bin file with my changes for `targetDependencyBuildFilesPlatformFilter`. Can I do it?

**Comment by danyf90** [comment]
have you tried to use it?

**Comment by dever25** [comment]
> 
in the terminal, in the folder with the local tuist, I run the command `fourier release tuist`. This is not right?

**Comment by danyf90** [comment]
> > 
> 
> in the terminal, in the folder with the local tuist, I run the command `fourier release tuist`. This is not right?

You should run `./fourier release tuist X.X.X` in the tuist repo, pointing at the branch where you want to create the binary.

If you want to just run commands, you can also do `./fourier tuist XXX --path yourproject` and it will be the same as building the new tuist and running `tuist XXX` in your project

**Comment by dever25** [comment]
It worked, thanks!
