### ISSUE TITLE
condition: .when(platforms:) does not work with tuist-dependencies

### ISSUE THREAD

**Issue by xoxo-anastasi-xoxo** [tuist/tuist#4713]
### What happened?

I use `Dependencies.swift` where I put a path to a local `Package.swift`.
In this `Package.swift` I include dependencies into targets conditionally:
```
.target(
        name: "SomeTarget",
        dependencies: [
           .target(name: "AssetsMobile", condition: .when(platforms: [.iOS])),
           .target(name: "AssetsTV", condition: .when(platforms: [.tvOS]))
         ],
         ....
),
```
As far as I can see via `tuist graph` the `condition(.when(platforms:))` does not have an expected effect: every target which has SomeTarget as deps has also both AssetsMobile and AssetsTV.

Could you please let me know if there are any plans to fix this small issue any time soon?)

### How do we reproduce it?

**Steps:**
1. Create ios tuist project and a few modules, described in `libs/Package.swift`
2. Use `condition: .when(platforms: [.tvOS])` inside `Package.swift`
3. Add Dependencies.swift to your tuist project
```
let dependencies = Dependencies(
    swiftPackageManager: SwiftPackageManagerDependencies(
        [.local(path: .relativeToRoot("libs"))]
    ),
    ...
)
```
4. Check the graph of your project

**Expectation:** project has no dependencies introduced via `condition: .when(platforms: [.tvOS])`

### Error log

-

### macOS version

12.2

### Tuist version

3.9.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
Thanks for reporting this! If you would like to impement the support for this, I am happy to provide some pointers!

**Comment by xoxo-anastasi-xoxo** [comment]
Yes, I would appreciate some pointers! This task seems challenging and unusual for me, but I would like to try! 😊

**Comment by fortmarek** [comment]
That's great to hear @xoxo-anastasi-xoxo!

We generate a special dependencies graph that's then consumed by tuist [here](https://github.com/tuist/tuist/blob/main/Sources/TuistDependencies/SwiftPackageManager/Utils/SwiftPackageManagerGraphGenerator.swift). It seems like we already parse that information as it's in the [PackageInfo](https://github.com/tuist/tuist/blob/main/Sources/TuistSupport/SwiftPackageManager/PackageInfo.swift#L88) struct, so you'll need to look at the `SwiftPackageManagerGraphGenerator` and see where we generate the project targets and only include the dependency when the target includes the platform of the dependency.

You can also [join our Slack](https://join.slack.com/t/tuistapp/shared_invite/zt-g38gajhj-D6LLakrPnVCy4sLm24KxaQ) to get support quicker ❤️
