### ISSUE TITLE
`tuist test`: code coverage not being gathered when using test plans

### ISSUE THREAD

**Issue by Ast3r10n** [tuist/tuist#4714]
### What happened?

Code coverage is not being gathered on a project using no automatic scheme generation, and test targets using test plans with code coverage enabled.

### How do we reproduce it?

1. Open a project using test plans with code coverage enabled, but no automatic scheme generation
2. Run `tuist test`

### Error log

N/A, tests run successfully

### macOS version

13.0 Beta (22A5321d)

### Tuist version

3.10.0

### Xcode version

14 beta 6, 14 RC

**Comment by danyf90** [comment]
Can you provide a sample Project?

**Comment by Ast3r10n** [comment]
[Here](https://github.com/Ast3r10n/tuist-test-plan-issue) is a sample Project where this happens.

**Comment by Ast3r10n** [comment]
[Here](https://github.com/Ast3r10n/tuist-test-plan-issue) is a sample Project. I can provide the `xcresult` file if required.

**Comment by danyf90** [comment]
Just had a closer look at the description, I think it's expected given `tuist test` doesn't run on the whole codebase, but only runs the "changed" tests? Tagging @fortmarek to confirm 🚀

**Comment by Ast3r10n** [comment]
Even so, I think it would be expected to also gather coverage by merging `xcresults` to provide an updated coverage graph. It can't really be used as-is in CI if coverage gathering is required.

**Comment by fortmarek** [comment]
>  I think it's expected given tuist test doesn't run on the whole codebase, but only runs the "changed" tests?

I believe we should be able to provide a test coverage even in this scenario by caching the previous result – but it's not going to be easy to do.

However, I think we do provide a test coverage when not using a test plan, so we should probably just align and mention in the docs that some targets might be missing.
