### ISSUE TITLE
Manifest references API documentation links are broken

### ISSUE THREAD

**Issue by oronbz** [tuist/tuist#4716]
### What happened?

Clicking on any of the links under *API Documentation* inside any of the manifests:
[Project](https://docs.tuist.io/manifests/project)
[Workspace](https://docs.tuist.io/manifests/workspace)
[Dependencies](https://docs.tuist.io/manifests/dependencies)

Resolves to a `404` on github pages.

### How do we reproduce it?

1. Go to [project manifest](https://docs.tuist.io/manifests/project)
2. Click on `latest` or `main` under API documentation section
3. Watch the 404:
4. 
![image](https://user-images.githubusercontent.com/1288090/188809135-f50dc6c7-e7e8-4eb3-9cdb-36c23edf61f4.png)

### Error log

`404`

### macOS version

NA

### Tuist version

NA

### Xcode version

NA

**Comment by danyf90** [comment]
It's literally the issue opened before this

**Comment by oronbz** [comment]
@danyf90 sorry, the "new issue" page was open since yesterday, and I've completed it just now, didn't see the latest issue which was opened 7 hours ago.
