### ISSUE TITLE
Cache generated with an Xcode beta/RC is not valid in another Xcode beta/RC

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#4720]
### What happened?

While using the Xcode RC, we recently got an error:
```
❌  /Users/distiller/project/XXX.swift:3:8: compiled module was created by an older version of the compiler; rebuild 'YYY' and try again: /Users/distiller/project/deriveddata/Build/Products/Debug-iphonesimulator/…
```

The problem is probably that artifacts cached with an older beta of Xcode are not compatible with the Xcode RC.
Having Tuist cloud enabled, the only way to fix this is to remove the element from the backend storage.

Given the hashing logic uses just the swift version (5.7 in this case), the hash is considered the same.
Instead, we should use the full swift version including the build number. It would maybe result in a bit more recompilation of artifacts than needed (probably only during betas), but it would be safer.

### How do we reproduce it?

1. Build cache with Xcode 14 beta 1
2. Generate the project with Xcode 14 RC

### Error log

```
❌  /Users/distiller/project/XXX.swift:3:8: compiled module was created by an older version of the compiler; rebuild 'YYY' and try again: /Users/distiller/project/deriveddata/Build/Products/Debug-iphonesimulator/…
```

### macOS version

12.3

### Tuist version

3.10.0

### Xcode version

14.0.0-RC

**Comment by fortmarek** [comment]
> It would maybe result in a bit more recompilation of artifacts than needed (probably only during betas), but it would be safer.

I agree – the cache should primarily be reliable and it should only secondarily try to minimize the consistency of the cache hash 👍 

Just to confirm, the build number only changes during RCs and won't change with e.g. minor and patch Xcode versions?

**Comment by danyf90** [comment]
> > It would maybe result in a bit more recompilation of artifacts than needed (probably only during betas), but it would be safer.
> 
> I agree – the cache should primarily be reliable and it should only secondarily try to minimize the consistency of the cache hash 👍
> 
> Just to confirm, the build number only changes during RCs and won't change with e.g. minor and patch Xcode versions?

They change also in that case, but the swift version will change also (e.g. going from `5.6.0` to `5.6.1`) so for that case it should be the same

**Comment by fortmarek** [comment]
I see, thanks for clarifying – yeah, let's do it as you suggest 🚀
