### ISSUE TITLE
Crash in a framework imported via Dependencies.swift

### ISSUE THREAD

**Issue by NoFearJoe** [tuist/tuist#4723]
### What happened?

I've add the grpc-swift framework (https://github.com/grpc/grpc-swift) to the Dependencies.swift and linked with the app target.
When I make a request, the app crashes. The crash happens in a framework linked to the grpc-swift – NIOTransportServices. I thought that this is an issue in the framework, but when I added grpc-swift as we usually add swift packages, the crash disappeared.

### How do we reproduce it?

1. Create a simple project
2. Add https://github.com/JohnReeze/TinkoffInvestSwiftSDK.git to the Dependencies.swift (this framework uses grpc-swift and makes it easier to reproduce the bug)
3. Copy-paste code that makes a grpc call - https://github.com/JohnReeze/TinkoffInvestSwiftSDK#grpc--swift-combine.
4. Build & run

### Error log

There is no error produced by Tuist. Just a runtime error – EXC_BAD_ACCESS.

### macOS version

12.5.1

### Tuist version

3.9.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
Can you provide a sample project?

**Comment by NoFearJoe** [comment]
Sure
[TuistBug.zip](https://github.com/tuist/tuist/files/9540108/TuistBug.zip)

**Comment by danyf90** [comment]
Hi @NoFearJoe , it should be enough to add `-ObjC` to `Other Linker Flags` of the target importing the ObjectiveC dependency (i.e. the app target in your sample)

**Comment by NoFearJoe** [comment]
Sorry for the late response. It works, thank you!
