### ISSUE TITLE
Tuist does not respect .copy rule of resources in SPM Package.swift

### ISSUE THREAD

**Issue by alexanderwe** [tuist/tuist#4724]
### What happened?

Currently I am facing an issue which integrating an SPM package which relies on the `.copy` rule in a `resource` definition of some target of it. 

This target declares a `.copy` rule on some directory with different sub directories in. Each subdirectory could potentially contain a file with a name which is already declared in another directory level. From what I found I found out, tuist seems to not check the `.copy` rule and just copies all files from the referenced directory into the `Bundle` in the end. This leads to the issue that all files with the same name will be moved to the same level causing build issues. 
This is the place in the tuist repo where I expect the root cause of the issue https://github.com/tuist/tuist/blob/main/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L657. It seems the `.copy` case is not respected and just everything ends up as a `.glob`. I guess a definition of a `folderReference` could fix this issue, but I am not sure. 

Additionally the directory structure gets lost, which might be expected by the files in the resources folder. 

### How do we reproduce it?

I have created an example project with a local SPM package which demonstrates the issue here https://github.com/alexanderwe/tuist-spm-resources-copy-issue 

### Error log

Here you can see an example error message that the generated Xcode project is producing 

<img width="500" alt="Screenshot 2022-09-11 at 10 35 53" src="https://user-images.githubusercontent.com/12934015/189518814-dd0795c2-2d81-40d5-8e81-b55f41d259c0.png">

### macOS version

12.5

### Tuist version

3.10.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
Hello!
Thank you for reporting and for the sample project! if you would like to have a look at it feel free to write me and I can provide some pointers
