### ISSUE TITLE
New Carthage dependency not being fetched when tuist fetch executed

### ISSUE THREAD

**Issue by anuragajwani** [tuist/tuist#4731]
### What happened?

I have a project with a single Carthage dependency. Upon running `tuist fetch` the command executes successfully. The dependency is fetched and built.

When I add a second dependency to the Carthage dependencies in `Dependencies.swift` and re-run `tuist fetch` then the second dependency is not being fetched and built.

### Problem:

1. Create a new tuist based project
2. Create the file `Tuist/Dependencies.swift`
3. Add the following as a dep under carthage:
```
.github(path: "airbnb/lottie-ios",
                requirement: .upToNext("3.3.0"))
```
4. Save and run tuist fetch
**Note** the command will run with the following output:
```
Installing Carthage dependencies.
*** Checking out lottie-ios at "3.4.3"
*** xcodebuild output can be found in /var/folders/r7/5xrc03195199mmn2yq9rt1r40000gr/T/carthage-xcodebuild.BZelBc.log
*** Valid cache found for lottie-ios, skipping build
Carthage dependencies installed successfully
```
5. Next add the following as a Carthage dependency:
```
.github(path: "krzyzanowskim/CryptoSwift",
                requirement: .upToNext("1.0.0")),
```
6. Re-run `tuist fetch`.
**Note** the following output:
```
Installing Carthage dependencies.
*** Checking out lottie-ios at "3.4.3"
*** xcodebuild output can be found in /var/folders/r7/5xrc03195199mmn2yq9rt1r40000gr/T/carthage-xcodebuild.BZelBc.log
*** Valid cache found for lottie-ios, skipping build
Carthage dependencies installed successfully.
```

The command does not check Dependencies.swift for any changes in Carthage dependencies.

### Work around

1. Delete `Cartfile.resolved`: `rm Tuist/Dependencies/Lockfiles/Cartfile.resolved`
2. Re run `tuist fetch`.
Note the following results:
```
Installing Carthage dependencies.
*** No Cartfile.resolved found, updating dependencies
*** Fetching lottie-ios
*** Fetching CryptoSwift
*** Checking out CryptoSwift at "1.5.1"
*** Checking out lottie-ios at "3.4.3"
*** No cache found for CryptoSwift, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/r7/5xrc03195199mmn2yq9rt1r40000gr/T/carthage-xcodebuild.LlZuiv.log
*** Valid cache found for lottie-ios, skipping build
*** Building scheme "CryptoSwift" in CryptoSwift.xcodeproj
Carthage dependencies installed successfully.
```

### Error log

No error is shown. Please read reproduction steps carefully.

### macOS version

12.5

### Tuist version

3.10.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
I am not super familiar with carthage, but we are basically just invoking the command to resolve carthage dependencies.
Would you expect that to not fetch new dependencies when you add them to the Carthage file without removing the lockfile?
