### ISSUE TITLE
Can't generate project if UnitTests target has spm dependencies & platform is macOS

### ISSUE THREAD

**Issue by dpliushchaiIOS** [tuist/tuist#4732]
### What happened?

I have IOS project but I need to add macOS target + tests with Quick & Nimble. It succesfully fetches dependency but when I am trying to generate project I get error "_Target AppTests has platform 'macOS' and product 'unit tests' and depends on target Quick_macos of type staticFramework and platform 'macOS' which is an invalid or not supported yet combination_"

I attached the sample project to illustrate the issue.
[tuist example 2.zip](https://github.com/tuist/tuist/files/9550572/tuist.example.2.zip)

### How do we reproduce it?

1. Use attached example project
2. tuist fetch
3. tuist generate

### Error log

tuist generate
Resolved cache profile 'Development' from Tuist's defaults
Target AppTests has platform 'macOS' and product 'unit tests' and depends on target Quick_macos of type staticFramework and platform 'macOS' which is an invalid or not supported yet combination.
Target AppTests has platform 'macOS' and product 'unit tests' and depends on target Nimble_macos of type staticFramework and platform 'macOS' which is an invalid or not supported yet combination.
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

13.0

### Tuist version

3.10.0

### Xcode version

14.0 Beta6

**Comment by danyf90** [comment]
Hello @dpliushchaiIOS , I think it should just be a matter of whitelisting that combination inside the linter. If you want to have a look at it, it should just need to be updated here: https://github.com/tuist/tuist/blob/5f03700927e0180e305bd819004213a3d4f643eb/Sources/TuistGenerator/Linter/GraphLinter.swift#L420-L433

Looks like there has been a copy past error, and we just need to change iOS to macOS (tagging @kwridan just to be sure there wasn't an actual reason to have iOS there) :D

**Comment by dpliushchaiIOS** [comment]
@danyf90 Should I create pr?

**Comment by danyf90** [comment]
Sure! 🙌
