### ISSUE TITLE
Tuist output doesn't display colors when run via tuistenv

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#475]
**Describe the bug**
The console output of `tuist` when run via `tuistenv` doesn't have any color.

**To Reproduce**

1. Run `swift run tuist generate --path fixtures/ios_app_with_tests`
2. Run `swift run tuistenv generate --path fixtures/ios_app_with_tests`
3. Compare the outputs 

**Expected behavior**
The console output colors are the same.

**Screenshots**

tuist:

<img width="499" alt="Screen Shot 2019-08-04 at 10 18 41 AM" src="https://user-images.githubusercontent.com/11914919/62421897-7034a900-b6a1-11e9-8658-0d83a194335b.png">

tuistenv:

<img width="517" alt="Screen Shot 2019-08-04 at 10 19 02 AM" src="https://user-images.githubusercontent.com/11914919/62421902-7b87d480-b6a1-11e9-9958-3b6bb09737e9.png">

**Comment by pepibumur** [comment]
🤔 I've been debugging this issue but I couldn't figure out the reason.
