### ISSUE TITLE
Add documentation regarding Settings

### ISSUE THREAD

**Issue by denizdogan** [tuist/tuist#4752]
### What happened?

It's not clear to me how the `Settings` class is supposed to work.

### How do we reproduce it?

1. Be a newbie
2. Be confused
3. Think you get it
4. Find out you don't
5. Go to step 2

### Error log

>Wow, I don't understand anything!

### macOS version

All

### Tuist version

All

### Xcode version

All

**Comment by denizdogan** [comment]
In `Project` we define `settings`, which is a `Settings` object, which has `base`, `debug`, `release`, and `defaultSettings`. I'm assuming that `debug` and `release` are basically just merged with whatever `base` has been set to.

Then there's `defaultSettings`, when is that applied to the rest of the settings? And exactly what does `.recommended` mean, recommended by whomst'd've? What is `.essential` really? Even diving into the source code I couldn't figure this one out.

In `Dependencies.swift` there's also `targetSettings` and `baseSettings`. I think I've misunderstood those settings as well, thinking they had to do with the "settings for the dependencies", but now I think they're actually somehow applied to my project settings? But I've already defined those elsewhere?

On top of this, it seems that sometimes it's okay with a `SettingsDictionary`, but sometimes a `Settings` object is expected. It's not clear to me why I'd prefer one over the other, or what the actual difference is.

It would seem to me that `Settings` is actually "extra OOP sugar" for what is essentially the merging of several `SettingsDictionary` objects?

Could we do entirely without `Settings` and just merge dictionaries into each other? Maybe then there would actually be less confusion about what `baseSettings` and `defaultSettings` really do.

**Comment by danyf90** [comment]
> It would seem to me that Settings is actually "extra OOP sugar" for what is essentially the merging of several SettingsDictionary objects?

That's quite correct.

> Then there's defaultSettings, when is that applied to the rest of the settings? And exactly what does .recommended mean, recommended by whomst'd've? What is .essential really? Even diving into the source code I couldn't figure this one out.

Regarding this I remember we were already discussing whether to remove it.

> On top of this, it seems that sometimes it's okay with a SettingsDictionary, but sometimes a Settings object is expected. It's not clear to me why I'd prefer one over the other, or what the actual difference is.

Regarding these, they are applied to the dependency target you specify in the dictionary.

> On top of this, it seems that sometimes it's okay with a SettingsDictionary, but sometimes a Settings object is expected. It's not clear to me why I'd prefer one over the other, or what the actual difference is.

Just stick to what the API requires :D
