### ISSUE TITLE
Tuist install not working in Apple M1 pro

### ISSUE THREAD

**Issue by 1659338** [tuist/tuist#4763]
### What happened?

Tuist is already installed but I want the version 1.45.1
tuist local:- 3.11.0
so when I run the command tuist install 1.45.1 in Apple M1 pro it always throwing me below error:-

Downloading version 1.45.1
2022-09-20T17:38:02+0530 error io.tuist.support : The '/usr/bin/curl' command exited with error code 6 and message:
curl: (6) Could not resolve host: github.com

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### How do we reproduce it?

install tuist 
Run tuist install 1.45.1

### Error log

Downloading version 1.45.1
2022-09-20T17:38:02+0530 error io.tuist.support : The '/usr/bin/curl' command exited with error code 6 and message:
curl: (6) Could not resolve host: github.com

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

12.6

### Tuist version

3.11.0

### Xcode version

Version 13.3.1

**Comment by danyf90** [comment]
The latest tuistenv is not able to install such an old version of tuist because the location of the binaries is changed.
If you want to use that version just download the binary from github 🙏
