### ISSUE TITLE
Documentation regarding adding system libraries is misleading

### ISSUE THREAD

**Issue by mflknr** [tuist/tuist#4764]
### What happened?

Hello,

I tried adding `libc++.tbd` and `lib.tbd` as a TargetDependency to one of our modules like the [documentation](https://docs.tuist.io/1/guides/dependencies/#system-libraries-and-frameworks-dependencies) states.

What I find misleading are:
1. The sdkType is actually necessary
2. The "lib" prefix is not needing when providing a system library

### How do we reproduce it?

1. Add  `.sdk(name: "libc++", type: .library)` and `.sdk(name: "libz", type: .library)` as a target dependency to a module
2. Look into `Frameworks and Libraries` under `General` on the target that has the sdks as a dependency
3. `liblibc++.tbd`, `liblibz.tbd` and `libc.tbd` are added

Fixed by adding `.sdk(name: "c++", type: .library)` and `.sdk(name: "z", type: .library)` instead. After re-generation the correct sdks are added (`libc.tbd` and `libc++.tbd`).

### Error log

no error log during generation step, just build errors for specific external dependencies that need those libs

### macOS version

12.6

### Tuist version

3.10.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
Thanks for reporting @mflknr ! Feel free to open a PR to fix this 🙏 
everything should be under `projects/docs`, you should be able to find it with a quick code search 🚀
