### ISSUE TITLE
SPM dependencies default deployment target issues warnings in Xcode 14

### ISSUE THREAD

**Issue by jonruiz** [tuist/tuist#4765]
### What happened?

If you have an SPM dependency that does not declare a deployment target, Tuist uses 9.0. It appears to define it in [Platform.swift](https://github.com/tuist/tuist/blob/f98b4427bfbf9cb7152f231caa84457bc1662030/Sources/TuistGraph/Models/Platform.swift)

### How do we reproduce it?

Here's a simple case with CasePaths.
Run `tuist generate`
Build the generated Xcode project
See the warning in the Issue Navigator
[MyApp.zip](https://github.com/tuist/tuist/files/9608716/MyApp.zip)

### Error log

`/Users/jonruiz/repos/MyApp/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/swift-case-paths/swift-case-paths.xcodeproj warning project: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99.
`

### macOS version

12.6

### Tuist version

3.0.11

### Xcode version

14.0.0

**Comment by danyf90** [comment]
Have you run `tuist fetch` with Xcode 14? The min deployment target is dynamic and defined by the Xcode SDK

**Comment by jonruiz** [comment]
Yes, Xcode 14 is all I have installed.

**Comment by waltflanagan** [comment]
I'm also seeing these warnings with Xcode 14 and doing a full `clean`, `fetch`, `generate`.

**Comment by danyf90** [comment]
Thanks, I'll try to have a look 🙏

**Comment by electricalen** [comment]
@danyf90 Thank you for working on this!  Looking forward to the Tuist release so I can upgrade to Xcode 14.

**Comment by romain-eero** [comment]
+1 looking forward, and +100 thanks a lot @danyf90!

**Comment by jonruiz** [comment]
Much appreciated @danyf90 !

**Comment by jonruiz** [comment]
Worked like a charm @danyf90, thank you!
