### ISSUE TITLE
Xcode 14 - Archiving fails with SPM dependency specifying a bundled resource

### ISSUE THREAD

**Issue by brunobrunkow** [tuist/tuist#4767]
### What happened?

A SPM dependency in our project specifies a resource bundle in its manifest. Xcode 14 defaults `CODE_SIGNING_ALLOWED` for resource bundles to `YES` which results in an error when archiving.

Trying to set `CODE_SIGNING_ALLOWED` to `NO` (as suggested in the forum posts below) in the target settings of the dependency declaration in tuist only adds the user-defined  build setting to the framework target and not to the resource target.

Related Developer Forums Post [here](https://developer.apple.com/forums/thread/708659).

Related Issue for CocoaPods [here](https://github.com/CocoaPods/CocoaPods/issues/11402).

### How do we reproduce it?

1. Add this sample project as a SPM dependency in tuist to any project: `git@github.com:brunobrunkow/SPMResourcesTest.git`
2. Run `tuist fetch` & `tuist generate`
3. Archive the generated project.

### Error log

```sh
[...]/SPMResourcesTest.xcodeproj error project: Signing for "SPMResourcesTest_SPMResourcesTest" requires a development team. Select a development team in the Signing & Capabilities editor.

```

### macOS version

12.6

### Tuist version

3.10.0

### Xcode version

14.0.0

**Comment by zh-se** [comment]
Hi guys! We have the same issue. Are there any workarounds maybe?

Thanks!

**Comment by RenatGafarov** [comment]
hello, we're drown at the same shit

**Comment by danyf90** [comment]
No reproducible project? 👀

**Comment by danyf90** [comment]
Is it only related to SPM dependencies or it happens also if you define a static framework with dependencies in your project? 🤔

**Comment by evtuhovaleksander** [comment]
it happens also if you define a static framework with dependencies in your project

**Comment by david-var** [comment]
any updates on this?

**Comment by danyf90** [comment]
Maybe you can workaround it trying to configure the Dependencies.swift so that that the target uses a .framework instead of a .staticFramework?

However we have many static framework targets with resources and we are not facing this problem 🤔
