### ISSUE TITLE
Linting error adding WidgetKit extension to WatchOS app

### ISSUE THREAD

**Issue by si-hartmann** [tuist/tuist#4768]
### What happened?

I use the current main branch with a single target WatchOS app. 

I just tried to add a new WidgetKit Extension to the WatchOS app target. This is newly possible with the single watchos app Target in Xcode 14. Doing this i get a linting error:

```
Target WatchOS has platform 'watchOS' and product 'application' and depends on target 
WatchOSWidgetExtension of type app extension and platform 'watchOS' which is an 
invalid or not supported yet combination.

Fatal linting issues found
```

### Expected
No linting error is expected as this is now a valid combination.

### How do we reproduce it?

1. Use the attached Demo Project
2. Build it with tuist (branch: main, commit: be370e18e1574f251dc0e2658aa65fba1ea78668)
3. See the error

[WidgetKitExtensionDemo.zip](https://github.com/tuist/tuist/files/9624811/WidgetKitExtensionDemo.zip)

### Error log

Resolved cache profile 'Development' from Tuist's defaults
No files found at: /Users/simonhartmann/Development/newa-ios/WatchOSWidgetExtension/Resources/**
Target WatchOS has platform 'watchOS' and product 'application' and depends on target WatchOSWidgetExtension of type app extension and platform 'watchOS' which is an invalid or not supported yet combination.
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

12.6

### Tuist version

main

### Xcode version

14.0

**Comment by danyf90** [comment]
@kwridan is this related to your last PRs?

**Comment by si-hartmann** [comment]
This is a new combination which is now possible with Xcode 14. So I guess this is a missing afterwork for the mentioned PR. Sorry for not seeing this earlier.

**Comment by kwridan** [comment]
no worries, will push another PR soon for this
