### ISSUE TITLE
[Dependencies.swift][SPM] Crash in swift-atomics when install through tuist Dependencies

### ISSUE THREAD

**Issue by DimaMishchenko** [tuist/tuist#4769]
### What happened?

Hi, I've just faced an interesting issue. App crashes on init of `ManagedAtomic` from [`swift-atomics`](https://github.com/apple/swift-atomics).
The issue only appears during runtime, with no compiler errors.
This only happens with tuist Dependencies. Works fine if it is installed through pure SPM. 

### How do we reproduce it?

* add [`swift-atomics`](https://github.com/apple/swift-atomics) through `Dependencies.swift`
* add `let value = ManagedAtomic<Bool>(false)` anywhere 
* run

It should be possible to reproduce by running the attached project.
[AtomicsTuist.zip](https://github.com/tuist/tuist/files/9625993/AtomicsTuist.zip)

Just in case, here is an example of an SPM-only project that works as expected.
[AtomicsPureSPM.zip](https://github.com/tuist/tuist/files/9626005/AtomicsPureSPM.zip)

### Error log

`EXC_BAD_ACCESS`

### macOS version

12.4

### Tuist version

3.11.0

### Xcode version

13.4.1

**Comment by danyf90** [comment]
Maybe you need to specify the dependency as `.framework` instead of `.staticFramework`? You can override that in the `Dependencies.swift` file

**Comment by DimaMishchenko** [comment]
Indeed. That solved an issue. Thank you, @danyf90! 
Closing an issue.
