### ISSUE TITLE
`tuist test` failed when specifying a scheme using test plan

### ISSUE THREAD

**Issue by s22596463** [tuist/tuist#4774]
### What happened?

I created two schemes, one using `.testplan` for test action and `.target` for another. But `tuist test` failed when I specifying the one which is using test plan.

### How do we reproduce it?

1. download [tuist-test-plan-issue repository](https://github.com/s22596463/tuist-test-plan-issue)
2. run `tuist test SchemeWithTestPlan`

### Error log

```
Couldn't find scheme SchemeWithTestPlan. The available schemes are: SchemeWithoutTestPlan, TuistTestPlan-Workspace, UnitTests, TuistTestPlan-Workspace.
```

### macOS version

12.6

### Tuist version

3.10.0

### Xcode version

14.0.1

**Comment by danyf90** [comment]
Thanks for reporting @s22596463 🙏 
it's probably some limitation of the test command, would you like to have a look at it? we can provide all the support you need 🎉
