### ISSUE TITLE
Extra Debug and Release configurations created

### ISSUE THREAD

**Issue by francuim-d** [tuist/tuist#4804]
### What happened?

I have a project with 4 custom configurations. Tuist generates project file with correct configurations and settings.
But then I add Firebase SDK to dependencies list and add FirebaseCrashlytics as dependency to main target. And new regenerated project contains my custom configurations + two extra configuration (Debug and Release).
When I remove FirebaseCrashlytics from dependencies of main target, the problem is gone.

### How do we reproduce it?

Project settings
```swift
settings: .settings(base: [:], configurations: [*Four configurations with custom names and settings*], defaultSettings: .none)
```

### Error log

<img width="539" alt="Снимок экрана 2022-10-11 в 14 38 21" src="https://user-images.githubusercontent.com/86049208/195080164-8e59d405-de63-4f5d-aec7-0ca99aeaf882.png">

### macOS version

12.6

### Tuist version

3.12.0

### Xcode version

14.0.1

**Comment by danyf90** [comment]
Are you adding the custom configurations also in the Dependencies.swift? IIRC you should pass them in the `baseSettings` parameter of `SwiftPackageManagerDependencies`

**Comment by francuim-d** [comment]
> Are you adding the custom configurations also in the Dependencies.swift? IIRC you should pass them in the `baseSettings` parameter of `SwiftPackageManagerDependencies`

Yes
```swift
baseSettings: .settings(configurations: [
    .debug(name: "Dev-Debug"),
    .debug(name: "Prod-Debug"),
    .release(name: "Dev-Release"),
    .release(name: "Prod-Release")
])
```

**Comment by danyf90** [comment]
Can you provide a sample project (as you should have done following the issue template 😇 ) 🙏

**Comment by francuim-d** [comment]
Sorry, [here it is](https://github.com/francuim-d/TuistConfigurationsSample)

**Comment by francuim-d** [comment]
This issue only appears when I add Firebase SDK. Adding Alamofire or any other dependencies I tried works as expected. Extra default configurations does not created

**Comment by francuim-d** [comment]
Additional note: when `settings: .settings(base: [:], configurations: [<custom configurations list>], defaultSettings: .none)` specified both in target's settings and project's settings extra configurations aren't generated.

**Comment by francuim-d** [comment]
In addition, I noticed that whenever extra configurations are created, the build settings for explicitly specified configurations stop being read normally from xcconfig files. Instead, the some default settings seem to be set, although both `base` and `defaultSettings` are `[:]` and `.none`.

**Comment by WedgeSparda** [comment]
> In addition, I noticed that whenever extra configurations are created, the build settings for explicitly specified configurations stop being read normally from xcconfig files. Instead, the some default settings seem to be set, although both `base` and `defaultSettings` are `[:]` and `.none`.

Happens the same to me and I'm going crazy truing to know the reason for this

**Comment by WedgeSparda** [comment]
@francuim-d In my project the `Debug` and `Release` configurations are being generated too alongside my custom ones. Even not including Firebase. Also, content of my xcconfig files is being ignored completely as I explain [here](https://github.com/tuist/tuist/discussions/4809).
