### ISSUE TITLE
[Dependencies.swift] Firebase 10.1.0 integration fails

### ISSUE THREAD

**Issue by francuim-d** [tuist/tuist#4805]
### What happened?

Firebase 10.1.0 integration fails

### How do we reproduce it?

Sample project: https://github.com/francuim-d/TuistConfigurationsSample

I'm trying to add Firebase SDK (Crashlytics) into my project. 
When I add Firebase SDK with native spm its products link as static libraries. And after calling `FirebaseApp.configure()` Crashlytics logs successful initialization.
<img width="533" alt="Снимок экрана 2022-10-11 в 22 10 26" src="https://user-images.githubusercontent.com/86049208/195178368-64780184-5011-4460-b2bb-89d7f14cd614.png">

But when Firebase SDK defined in Dependencies.swift products link as frameworks.
<img width="516" alt="Снимок экрана 2022-10-11 в 22 17 08" src="https://user-images.githubusercontent.com/86049208/195179632-dd56b1aa-45b3-4004-aa0e-e0bf0b1da75a.png">
Calling `FirebaseApp.configure()` do nothing. And when I add `_ = Crashlytics.crashlytics()` project build fails with errors
<img width="266" alt="Снимок экрана 2022-10-11 в 22 18 01" src="https://user-images.githubusercontent.com/86049208/195179770-0aa1385a-8132-440f-9b91-9469f1d1d5af.png">

### Error log

Undefined symbols for architecture arm64:
  "std::get_terminate()", referenced from:
      _FIRCLSExceptionCheckHandlers in FirebaseCrashlytics(FIRCLSException.o)
  "std::set_terminate(void (*)())", referenced from:
      _FIRCLSExceptionInitialize in FirebaseCrashlytics(FIRCLSException.o)
      FIRCLSTerminateHandler() in FirebaseCrashlytics(FIRCLSException.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in FirebaseCrashlytics(FIRCLSException.o)
  "typeinfo for char const*", referenced from:
      _FIRCLSExceptionRaiseTestCppException in FirebaseCrashlytics(FIRCLSException.o)
      GCC_except_table20 in FirebaseCrashlytics(FIRCLSException.o)
  "typeinfo for std::bad_alloc", referenced from:
      GCC_except_table20 in FirebaseCrashlytics(FIRCLSException.o)
  "typeinfo for std::exception", referenced from:
      GCC_except_table20 in FirebaseCrashlytics(FIRCLSException.o)
      typeinfo for std::exception const* in FirebaseCrashlytics(FIRCLSException.o)
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for std::__1::__basic_string_common<true> in FirebaseCrashlytics(FIRCLSException.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__pointer_type_info", referenced from:
      typeinfo for std::exception const* in FirebaseCrashlytics(FIRCLSException.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__vmi_class_type_info", referenced from:
      typeinfo for std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > in FirebaseCrashlytics(FIRCLSException.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "___cxa_allocate_exception", referenced from:
      _FIRCLSExceptionRaiseTestCppException in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_begin_catch", referenced from:
      FIRCLSCatchAndRecordActiveException(std::type_info*) in FirebaseCrashlytics(FIRCLSException.o)
      ___clang_call_terminate in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_current_exception_type", referenced from:
      FIRCLSTerminateHandler() in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_demangle", referenced from:
      +[FIRCLSDemangleOperation demangleCppSymbol:] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
  "___cxa_end_catch", referenced from:
      FIRCLSCatchAndRecordActiveException(std::type_info*) in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_rethrow", referenced from:
      FIRCLSCatchAndRecordActiveException(std::type_info*) in FirebaseCrashlytics(FIRCLSException.o)
  "___cxa_throw", referenced from:
      _FIRCLSExceptionRaiseTestCppException in FirebaseCrashlytics(FIRCLSException.o)
  "___gxx_personality_v0", referenced from:
      +[FIRCLSDemangleOperation demangleBlockInvokeCppSymbol:] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
      +[FIRCLSDemangleOperation demangleCppSymbol:] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
      -[FIRCLSDemangleOperation main] in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
      ___31-[FIRCLSDemangleOperation main]_block_invoke in FirebaseCrashlytics(FIRCLSDemangleOperation.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbol: std::get_terminate()
Undefined symbol: std::set_terminate(void (*)())
Undefined symbol: std::terminate()
Undefined symbol: typeinfo for char const*
Undefined symbol: typeinfo for std::bad_alloc
Undefined symbol: typeinfo for std::exception
Undefined symbol: vtable for __cxxabiv1::__class_type_info
Undefined symbol: vtable for __cxxabiv1::__pointer_type_info
Undefined symbol: vtable for __cxxabiv1::__vmi_class_type_info
Undefined symbol: ___cxa_allocate_exception
Undefined symbol: ___cxa_begin_catch
Undefined symbol: ___cxa_current_exception_type
Undefined symbol: ___cxa_demangle
Undefined symbol: ___cxa_end_catch
Undefined symbol: ___cxa_rethrow
Undefined symbol: ___cxa_throw
Undefined symbol: ___gxx_personality_v0

### macOS version

12.6

### Tuist version

3.12.0

### Xcode version

14.0.1

**Comment by danyf90** [comment]
Have you added the -ObjC flag to the target depending on it?

**Comment by francuim-d** [comment]
Yes, I've tried with and without it

**Comment by francuim-d** [comment]
It seems that there is some kind of problem with linking, because even when the project is successfully built, the behavior of the SDK when calling FirebaseApp.configure() is different from native SPM. The rest of the configuration remain unchanged.

**Comment by francuim-d** [comment]
I found solution by adding `.sdk(name: "c++", type: .library, status: .required)` to target's dependencies combining with -ObjC flag
