### ISSUE TITLE
environment variables and launch arguments not added to scheme on framework target

### ISSUE THREAD

**Issue by eurias-stripe** [tuist/tuist#4825]
### What happened?

The `launchArguments` and `environment` properties of `Target` are doing nothing when I used on a framework.

### How do we reproduce it?

Here is a minimal example to reproduce:

```
let project = Project(
    name: "MyApp",
    targets: [
        Target(
            name: "MyApp",
            platform: .iOS,
            product: .framework,
            bundleId: "com.example.Test",
            environment: ["foo": "bar"]
        ),
    ]
)
```

### Error log

N/A

### macOS version

12.6

### Tuist version

3.12.0

### Xcode version

14.0.1

**Comment by danyf90** [comment]
For run actions, the environment is read [here](https://github.com/tuist/tuist/blob/d501233cfa0a6d0a58cf5f8e9770f2d179f566ce/Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift#L147) from the runnable target.

For test actions we should pass them [here](https://github.com/tuist/tuist/blob/d501233cfa0a6d0a58cf5f8e9770f2d179f566ce/Sources/TuistGenerator/Mappers/AutogeneratedSchemesProjectMapper.swift#L189), but it's not trivial to decide from which of the scheme targets the environment should be taken
