### ISSUE TITLE
`Tuist.graph()` is not configurable as `tuist graph` command

### ISSUE THREAD

**Issue by GermanVelibekovHouzz** [tuist/tuist#4827]
### What happened?

I believe this is more of a feature request than a bug.
The [Tuist.graph()](https://github.com/tuist/tuist/blob/27ef1727a4b3c6547a9962234d717f8da1bc19b2/Sources/ProjectAutomation/Tuist.swift#L30) method exposed for the [external usage](https://github.com/tuist/tuist/blob/27ef1727a4b3c6547a9962234d717f8da1bc19b2/Sources/ProjectAutomation/Tuist.swift#L30) should have the [filtering options](https://docs.tuist.io/commands/graph/#arguments) available to `tuist graph` command

### How do we reproduce it?

-

### Error log

-

### macOS version

-

### Tuist version

3.12.0

### Xcode version

-

**Comment by fortmarek** [comment]
Hey @GermanVelibekovHouzz 👋 

I agree, although I would surface those as extension for the `graph` (or possibly a helper class), so you could do `Tuist.graph().filterExternalTargets()`.

Happy to help if you want to contribute that 🙌
