### ISSUE TITLE
Cocoapods and Swift Package Manager Is it allowed to use at the same time?

### ISSUE THREAD

**Issue by coolxiaohao** [tuist/tuist#4843]
### What happened?

There are currently Swift Package Manager dependencies and Cocoapods dependencies, but I can't find the dependencies of Swift Package Manager when I tuist generate && pod install. It seems that there can only be one of these two package managers.

### How do we reproduce it?

1. Create Project TestApp
2. Execute tuist edit and modify the Dependencies.swift file to add a swiftPackageManager dependency
3. Add a Podfile file Add a cocoapods dependency
4. Execute tuist generate && pod install

### Error log

error build: Framework not found Lottie

Note: Lottie is a dependency in swift package manager.

### macOS version

12.6

### Tuist version

3.12.1

### Xcode version

14.0.1

**Comment by danyf90** [comment]
Should work fine, maybe you forgot a `tuist fetch`?

Otherwise, issues without sample project are harder to analyze, and this kind of question would have been better as a discussion 🙏
