### ISSUE TITLE
Static XCframework linked from static module is linked again from main app target

### ISSUE THREAD

**Issue by GermanVelibekovHouzz** [tuist/tuist#4859]
### What happened?

Considering the following dependency tree

App
- Static Module

Static Module
- Static XCFramework

the `Static XCFramework` is added to the `App` leading to the multiple symbols error.

### How do we reproduce it?

create the dependency above
run `tuist generate`

### Error log

-

### macOS version

12.6

### Tuist version

3.8.0

### Xcode version

14.0

**Comment by kwridan** [comment]
Thanks for flagging this @GermanVelibekovHouzz 

Are you able to create a small fixture or update an existing one in https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures to help reproduce the issue?

To my knowledge the app still needs to do the final linking as static targets themselves don't do any linking per se. We had the opposite issue a while ago and needed to ensure the app target transitively link any pre-compiled static frameworks.

https://github.com/tuist/tuist/issues/3234

**Comment by GermanVelibekovHouzz** [comment]
Hey @kwridan . Thanks for your response.

In the case you mentioned, isn't it create a symbol duplication? I mean eventually, you add the static framework twice 😮. I though the linkage, in this case, is expected to be made via appropriate linker flags.

**Comment by rowwingman** [comment]
I have the similar issue by adding RecaptchaEnerprise from google https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps#swift https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk
