### ISSUE TITLE
Issue when "tuist generate" on Xcode 14.1

### ISSUE THREAD

**Issue by Sparklydust** [tuist/tuist#4864]
### What happened?

When updating Xcode to 14.1, `tuist generate` command triggers an error in my Terminal. 

### How do we reproduce it?

1.  I have updated Xcode from 14.0.1 to 14.1
2. `tuist generate` on a Xcode project
3. An tuist error appears in my Terminal

### Error log

```sh
The selected Xcode version is 14.1, which is not compatible with this project's Xcode version requirement of 14.0.0..<14.1.0.
Fatal linting issues found
```

### macOS version

13.0

### Tuist version

3.13.0

### Xcode version

14.1

**Comment by danyf90** [comment]
Can you provide a reproducible project? probably you have configured an Xcode version in the Config.swift file which is not compatible with 14.1

**Comment by Sparklydust** [comment]
You are right, thank you for pointing out the solution. Tuist was not bumping to the next major version of Xcode, only to the minor one.
