### ISSUE TITLE
Create a tuist task to package targets as XCFrameworks

### ISSUE THREAD

**Issue by shahzadmajeed** [tuist/tuist#4872]
### What happened?

As per discussion here https://tuistapp.slack.com/archives/C018QG7U7SN/p1668452429388099, following would be a nice addition to Tuist

It is very common use case to create XCFrameworks from your source code for internal or external distribution. Currently, tuist build command only builds for one architecture at a time. Allowing something like `tuist {task_name} MyScheme --xcframework --build-output-path {xcframework_output_path}` will be a great addition to Tuist because then library vendors can use a single command to generate a XCFrameworks rather than custom scripts.

The task name is yet to be decided as using existing Xcode actions can confuse the purpose of this task i.e, build, archive etc.

**Comment by luispadron** [comment]
One comment would be that this makes more sense in a separate release or archive command since packaging an xcframework isn't the  same as building the code if we wanted to add this

**Comment by shahzadmajeed** [comment]
Yes, that would be my preference too.

**Comment by danyf90** [comment]
Makes a lot of sense @luispadron !
On top of that, if possible it would be great if it could be a tuist task defined in a separate plugin!
