### ISSUE TITLE
Xcode warning in file generated by ResourcesProjectMapper when strict concurrency checking is enabled

### ISSUE THREAD

**Issue by marcinpodeszwa-medcase** [tuist/tuist#4874]
### What happened?

I enabled strict concurrency checking flag:
<img width="713" alt="Screenshot 2022-11-15 at 11 34 52" src="https://user-images.githubusercontent.com/95348173/201898093-2b8712fd-ffd6-48cd-bd40-3d6607197799.png">

And got this warning:
<img width="915" alt="Screenshot 2022-11-15 at 11 35 30" src="https://user-images.githubusercontent.com/95348173/201898177-27dbfd36-477a-475b-8991-49bc8bdc7140.png">

Note:
Changing `static var` to `static let` fixes this issue, because it's no longer mutable:
```
extension Foundation.Bundle {
    /// Since Resources is a framework, the bundle for classes within this module can be used directly.
    static let module = Bundle(for: BundleFinder.self)
}
```

### How do we reproduce it?

Set settings to `.settings(base: ["SWIFT_STRICT_CONCURRENCY": "complete"])` in generated project with resources.

### Error log

Reference to static property 'module' is not concurrency-safe because it involves shared mutable state

### macOS version

13.0.1

### Tuist version

3.13.0

### Xcode version

14.1

**Comment by danyf90** [comment]
Would you mind opening a PR for this? 🙏
