### ISSUE TITLE
Custom application identifier prefix

### ISSUE THREAD

**Issue by david-all-win-software** [tuist/tuist#4887]
### What happened?

I am importing a project from Xcode to Tuist but I have a provisioning profile with an ApplicationIdentifierPrefix that does not match the TeamIdentifier causing an error that does not occur in the source Xcode project, since Xcode manages to recognize the custom prefix, is there a way to force the prefix change in Tuist or avoid that verification?

### How do we reproduce it?

1. Obtain a provisioning profile with id prefix different from the team id
2. Configuring certificates in tuist
3. Try to run tuist generate, it generates the linting error

### Error log

App id <TeamIdentifier>.com.sample.id does not correspond to <ApplicationIdentifierPrefix>.com.sample.id. Make sure the provisioning profile has been added to the right target.
Fatal linting issues found

### macOS version

12.6

### Tuist version

3.13.0

### Xcode version

14.0.1

**Comment by jesus-mg-ios** [comment]
Yes, please comment below to contributors with write access

**Comment by david-all-win-software** [comment]
@kwridan @danyf90
