### ISSUE TITLE
`tuist generate --project-only` yields `Error: Unknown option '--project-only'`

### ISSUE THREAD

**Issue by jeffremer** [tuist/tuist#4899]
### What happened?

When following the [getting started guide](https://docs.tuist.io/tutorial/get-started) I attempted to generate a sample project without generating the workspace. It appears that `tuist` version `3.14.0` doesn't know about the `--project-only` option.

I wasn't able to find any evidence of this option in the current codebase so it makes me think that it was deprecated, though I can't find any evidence of that in the [CHANGELOG](https://github.com/tuist/tuist/blob/main/CHANGELOG.md) either.

Is the documentation simply wrong, or am I missing something about this option?

### How do we reproduce it?

1. Create a new `tuist` project
2. Run `tuist generate --project-only`

### Error log

```sh
tuist generate --project-only                                                                                                                             ~/D/MyApp 266ms
Error: Unknown option '--project-only'
Usage: tuist generate [--path <path>] [<sources> ...] [--no-open] [--xcframeworks] [--profile <profile>] [--no-cache]
  See 'tuist generate --help' for more information.
```

### macOS version

12.6

### Tuist version

3.14.0

### Xcode version

14.1

**Comment by danyf90** [comment]
I think it could have been removed in 3.0, would you mind opening A PR to fix the documentation? 🙏

**Comment by kkizlaitis** [comment]
Is there a possibility to skip `.xcworkspace` creation? Was it moved somewhere else? This would help with using tuist with Cocoapods as it would not override the `.xcworkspace` generated by Cocoapods.

Right now, if you run `tuist generate`, you also have to run `pod update`, which can be quite time consuming.

**Comment by danyf90** [comment]
Thanks for reporting @jeffremer, fixed [here](https://github.com/tuist/tuist/commit/7f2c254783bfaaf37eec3ebf24d529241a8acb9d)
