### ISSUE TITLE
Compile errors when install Airship through Tuist dependencies

### ISSUE THREAD

**Issue by ainizhaer** [tuist/tuist#4906]
### What happened?

I faced the similar issue to #4901 that compiler fails with "Redefinition of AirshipCoreResourses..' errors. The issue reproduces only with installing Airship as spm dependency via tuist dependencies. It also works if used with native spm integration. 
The name is duplicated in the static AirshipCore library with the automatically generated derived file **TuistBundle+AirshipCore.swift**

### How do we reproduce it?

1. add [Airship](https://github.com/urbanairship/ios-library) through Dependencies.swift
2. add AirshipCore as external dependency to app target
3. tuist fetch
4. tuist generate
5. run project

### Error log

<img width="300" alt="Screenshot 2022-12-05 at 14 20 35" src="https://user-images.githubusercontent.com/117272755/205651541-b35cb91b-274d-4374-a637-aba75303fd46.png">

### macOS version

13.0.1

### Tuist version

3.12.1

### Xcode version

14.1

**Comment by danyf90** [comment]
Please follow the template and provide a reproducible project
