### ISSUE TITLE
Support for SPM `Build Tool Plug-In`

### ISSUE THREAD

**Issue by mo5tone** [tuist/tuist#4909]
### What happened?

I'm following [this guide](https://github.com/realm/SwiftLint#plug-in-support) to add SwiftLint as a `Build Tool Plug-In`.
However, the `TargetScript` only support `pre` and `post`.

### How do we reproduce it?

`TargetScript` should support `Build Tool Plug-In`.

### Error log

This is a feature request, no error log.

### macOS version

12.6

### Tuist version

3.14.0

### Xcode version

14.0

**Comment by danyf90** [comment]
Hello @mo5tone 👋 
Unfortunately this is currently not supported

**Comment by InkyTsar** [comment]
https://github.com/yonaskolb/XcodeGen/issues/1290#issuecomment-1311717457
Some research on build tool plugins has been done in this thread. Hopefully this will help.

**Comment by micHar** [comment]
Not stale, still relevant

**Comment by iteracticman** [comment]
Thank you @BarredEwe for finally making this possible.

I have created a draft PR and would appreciate early feedback: https://github.com/tuist/tuist/pull/5299
