### ISSUE TITLE
Support setting a dependency file (.d) for run script phase.

### ISSUE THREAD

**Issue by a-sarris** [tuist/tuist#4939]
### What happened?

Support setting a dependency file path when defining a run script phase (similar to input-output paths).

### How do we reproduce it?

1. Try to declare a new run script phase
2. No way to set `.d` file.

![image](https://user-images.githubusercontent.com/78614622/208943942-4d6f32f0-b364-4d75-aee3-12ca0100210a.png)

### Error log

There is no log.

### macOS version

13.0.1

### Tuist version

3.15.0

### Xcode version

14.2

**Comment by danyf90** [comment]
Hi @a-sarris, thanks for reporting this! 🙏 
Would you like to try to implement the support? 🚀
