### ISSUE TITLE
tuist does create correct build phase to support App Intent Extensions

### ISSUE THREAD

**Issue by tovkal** [tuist/tuist#4941]
### What happened?

I added an App Intent Extension the same way I have declared other extensions, for example an Intents Extension.

```
let appIntentExtension = Target(
    name: "\(appName)AppIntent",
    platform: .iOS,
    product: .appExtension,
    bundleId: "${CUSTOM_BUNDLE_ID}.AppIntent",
    deploymentTarget: deploymentTarget,
    infoPlist: "\(appName)AppIntent/Sources/Info.plist",
    sources: [
        "\(appName)AppIntent/Sources/**",
    ],
    dependencies: [
        .target(name: repositoryName),
    ],
    settings: Settings.settings(configurations: [
        .debug(
            name: "Debug",
            settings: ["GENERATE_INFOPLIST_FILE": "YES"],
            xcconfig: "Configs/Base+Debug.xcconfig"
        ),
        .release(
            name: "Release",
            settings: ["GENERATE_INFOPLIST_FILE": "YES"],
            xcconfig: "Configs/Base+Release.xcconfig"
        )
    ])
)
```

but when compiling I get this warning:

`SomeAppAppIntent.appex is an ExtensionKit extension and must be embedded in the parent app bundle's Extensions directory, but is embedded in the parent app bundle's PlugIns directory.`

and then the app fails to install on the target device.

I checked the build phases and saw that there's a phase that embeds the extensions:
<img width="1166" alt="Screenshot 2022-12-22 at 16 27 20" src="https://user-images.githubusercontent.com/5960675/209167375-1c6a90c3-83fd-448e-b874-e6310d8740b4.png">

And for the project to compile correctly, it should embed the App Intent Extension in a different step with `Destionation` set to `ExtensionKit Extensions`

<img width="1176" alt="Screenshot 2022-12-22 at 16 28 08" src="https://user-images.githubusercontent.com/5960675/209167523-da64bcf9-a47a-4aea-8e53-42f8f3bab97f.png">

I looked a bit and I think that maybe a new type of product is required `.extensionKitExtension` (🙈) instead of `.appExtension` in order to add the correct build phase but maybe I missed something and tuist already supports App Intent Extensions and I am doing something wrong or missing some parameter. Is there a way to do this now or are changes required?

### How do we reproduce it?

1. Create an app project
2. Add App Intent Extension
3. Generate project with tuist and try to compile

### Error log

SomeAppAppIntent.appex is an ExtensionKit extension and must be embedded in the parent app bundle's Extensions directory, but is embedded in the parent app bundle's PlugIns directory.

### macOS version

13.1

### Tuist version

3.12.1

### Xcode version

14.2.0

**Comment by danyf90** [comment]
I'm quite sure @kwridan knows something about this 👀

**Comment by kwridan** [comment]
Hi @tovkal 

Xcode 14 introduced a new extension product type (`extensionKitExtension`) - Tuist currently supports the older app extensions product type (`appExtension`). 

It's something we'd need to add to Tuist, the good news is some of the prerequisite work to support has already been completed.

https://github.com/tuist/tuist/discussions/4531

**Comment by tovkal** [comment]
Ah, thanks @kwridan. I had forked the repo and hacked together support to use myself (https://github.com/tovkal/tuist/tree/extension_kit), so later I will rename all the changes from `extensionKitExtension` to `appIntentsExtension` and prepare a PR

**Comment by kwridan** [comment]
contributing this would be fantastic 👍 

Small note, from researching this we may need to keep the generic product type `extensionKitExtension` as there are a few new extensions that share that product type but have different info plist keys.

**Comment by tovkal** [comment]
I created the PR with the changes. It is my first time contributing to tuist, so I might have missed some stuff and some I am unsure (do I have to update any docs?)
