### ISSUE TITLE
Support for junit test output

### ISSUE THREAD

**Issue by mohamadrezakoohkan** [tuist/tuist#4951]
### What happened?

Unable to generate junit report from `.xcresult` generated by `tuist test`, this report is mostly done using xcodebuild <action> | xcpretty --report junit` but `tuist test | xcpretty --report junit` is impossible. It could be better if tuist test could provide junit output.

### How do we reproduce it?

1. Run tuist test with `--result-bundle-path`:
```bash
tuist test --result-bundle-path  "build/test_result"
```

### Error log

➜  tuist git:(feature/tuist-migration) ✗ tuist test | xcpretty "--report" "junit" "--output" "build/test-results.xml"
> No error, but it will stuck on this forever

### macOS version

13.1

### Tuist version

3.12.0

### Xcode version

14.2

**Comment by danyf90** [comment]
If you want the raw Xcode output (which should be what xcpretty expects), you should be able to obtain it using `tuist test --verbose`
