### ISSUE TITLE
[Feature Request] Allow resources target custom name

### ISSUE THREAD

**Issue by kientux** [tuist/tuist#4961]
### What happened?

I have this usecase:
- I have a modularized app splitted into several features, each feature is a target. These features include some `.xib` files for UI.
- I also have a separated target for UI components to be shared between features. This target includes assets like colors, icons,... (in `.xcassets`)

By default, Tuist will auto generate resource targets for those targets. Module name of resource target is `PROJECTNAME_TARGETNAME` (or something like that, I don't know exactly the logic behind). And Tuist also generates assets classes using SwiftGen which is great for programmatically UI configs.

The problem is in xib/storyboard, Xcode preview works fine for images/colors from other module, but in runtime it will fail to display images, and colors are fallback to hardcoded-string from xib instead of getting value from assets. Because of this, dark/light variant of colors won't work, and later if someone changes the color, it will not be changed in xib/storyboard.

Before migrate to Tuist, I use CocoaPods to separate those modules. And it supports custom name for resources bundle. I can set a same name for all resources bundle so every resources will go into single bundle and solve the problem. Of course this can causes resources collisions, but that is something devs must be aware of when choose this approach.

Can Tuist also support that?

### How do we reproduce it?

Access image/color assets in xib/storyboard from other module

### Error log

No error log

### macOS version

13.0

### Tuist version

3.14.0

### Xcode version

14.1

**Comment by danyf90** [comment]
Please follow the issue teplate and provide a sample proiect.
Also, given the target is shared you should probably define it as dynamic frameworks, which doesn't involve the naming you have mentioned.

Feel free to reopen the issue if this doesn't fix your problem and you have provided the sample project
