### ISSUE TITLE
Target cannot be cached if PRODUCT_NAME is set

### ISSUE THREAD

**Issue by kientux** [tuist/tuist#4964]
### What happened?

A target with custom setting of `PRODUCT_NAME` will be rebuilt everytime run `cache warm`, even if the last time it has been successfully cached.

### How do we reproduce it?

Demo project: [tuist-demo.zip](https://github.com/tuist/tuist/files/10371578/tuist-demo.zip)

basically it's just newly generated project from `tuist init`, then I set the framework target settings to include custom value:

```swift
let sources = Target(name: name,
                platform: platform,
                product: .framework,
                bundleId: "io.tuist.\(name)",
                infoPlist: .default,
                sources: ["Targets/\(name)/Sources/**"],
                resources: [],
                dependencies: [],
                settings: .settings(base: [
                    "PRODUCT_NAME": "CustomProductName"
                ])
        )
```

Then run `tuist cache warm`.

### Error log

No error log. First time the output will be:

```sh
Building cacheable targets
[TuistDemoKit] Processing TuistDemoKit-Info.plist
[TuistDemoKit] Compiling TuistDemoKit.swift
[TuistDemoKit] Compiling CustomProductName_vers.c
[TuistDemoKit] Generating CustomProductName.framework.dSYM
Signing CustomProductName.framework (in target 'TuistDemoKit' from project 'TuistDemo')
[TuistDemoKit] Touching CustomProductName.framework
Build Succeeded
Storing 1 cacheable targets: TuistDemoKit
All cacheable targets have been cached successfully as frameworks
```

The second time, it does not rebuild the target, but still run `Processing TuistDemoKit-Info.plist` step.

```sh
Building cacheable targets
[TuistDemoKit] Processing TuistDemoKit-Info.plist
[TuistDemoKit] Generating CustomProductName.framework.dSYM
Signing CustomProductName.framework (in target 'TuistDemoKit' from project 'TuistDemo')
Build Succeeded
Storing 1 cacheable targets: TuistDemoKit
All cacheable targets have been cached successfully as frameworks
```

and in `~/.tuist/Cache/BuildCache` dir, hash dir of `TuistDemoKit` is still created but does not have `.framework` file.

![image](https://user-images.githubusercontent.com/4200743/211269644-d37777d2-e482-4aa9-8701-73af62d08f43.png)

When run `tuist generate TuistDemo`, generated project should not include `TuistDemoKit` (because it is cached). But project still include the target sources and will rebuild it.

![image](https://user-images.githubusercontent.com/4200743/211268682-dd9805f9-02fa-4b74-adb1-dd279bff0f21.png)

### macOS version

13.0

### Tuist version

3.14.0

### Xcode version

14.1

**Comment by danyf90** [comment]
There is a `productName` initializer in Target struct, you should use that one instead
