### ISSUE TITLE
Generated assets @available markers break compilation on Xcode 14

### ISSUE THREAD

**Issue by stodirascu** [tuist/tuist#4975]
### What happened?

We introduced a `.colorset` into our xcassets. When generating the project using Tuist, the generated assets swift file contains code that doesn't compile under Xcode 14.

### How do we reproduce it?

1. Use [this project](https://github.com/tuist/tuist/files/10509330/colorset.zip)
3. Run `tuist generate -n`
4. The _TuistAssets+DemoApp.swift_ file will contain the following sections of code which will produce Xcode errors:
```swift
  #if canImport(SwiftUI)
  @available(iOS 13.0, tvOS 13.0, watchOS 6.0, macOS 10.15, *)
  public private(set) lazy var swiftUIColor: SwiftUI.Color = {
    SwiftUI.Color(asset: self)
  }()
  #endif
```
**Error:** Stored properties cannot be marked potentially unavailable with '@available'

```swift
#if canImport(SwiftUI)
public extension SwiftUI.Color {
  @available(iOS 13.0, tvOS 13.0, watchOS 6.0, macOS 10.15, *)
  init(asset: DemoAppColors) {
    let bundle = DemoAppResources.bundle
    self.init(asset.name, bundle: bundle)
  }
}
#endif
```
**Error:** 'Color' is only available in iOS 13.0 or newer

### Error log

Written above.

### macOS version

13.0.1

### Tuist version

3.15.0

### Xcode version

14.2.0

**Comment by danyf90** [comment]
Thanks for reporting, can you provide a sample project to reproduce this?

**Comment by messin9** [comment]
Also generated TuistBundle+{TargetName} gives compile error in Xcode 14 
Errors:
 Invalid redeclaration of 'module'
Ambiguous use of 'module'

**Comment by danyf90** [comment]
> Also generated TuistBundle+{TargetName} gives compile error in Xcode 14 Errors: Invalid redeclaration of 'module' Ambiguous use of 'module'

@messin9 can you open a separate issue with sample project to reproduce?

**Comment by messin9** [comment]
Yea, sure

**Comment by messin9** [comment]
> > Also generated TuistBundle+{TargetName} gives compile error in Xcode 14 Errors: Invalid redeclaration of 'module' Ambiguous use of 'module'
> 
> @messin9 can you open a separate issue with sample project to reproduce?

is this option "disableBundleAccessors" still available in version 3.15?
Or any other variants to get rid off "derived" directory?

**Comment by bc-lee** [comment]
Hello, I am experiencing the same problem. 22b837654d97bc012e8fb8032b45cd844e7c2122 seems to be causing the problem. I ended up using 3.12.1 as a workaround, but I hope this gets fixed.

**Comment by stodirascu** [comment]
Hi @danyf90, sorry, a bit swamped with work. Is the info in the comments enough, or do you want me to prepare a demo project? It's nothing fancy really, just have a .colorset in the assets.

**Comment by danyf90** [comment]
Either you do it, or the person solving this should do it, so better to provide it, isn't it?

**Comment by stodirascu** [comment]
The person solving it would do it anyway, because in order to fix it, they will setup their own project, won't they? And since this is so easy to reproduce, I don't see any impediment for the person solving this to get right into it. Cheers [colorset.zip](https://github.com/tuist/tuist/files/10509330/colorset.zip)

**Comment by danyf90** [comment]
> The person solving it would do it anyway, because in order to fix it, they will setup their own project, won't they? And since this is so easy to reproduce, I don't see any impediment for the person solving this to get right into it. Cheers [colorset.zip](https://github.com/tuist/tuist/files/10509330/colorset.zip)

If I can use you project I don't need to create one, isn't it?

**Comment by danyf90** [comment]
@stodirascu Can you confirm you can replicate with the sample project? it works fine on my side

**Comment by danyf90** [comment]
Note that I'm generating the Xcode project with tuist, not using the one in the zip

**Comment by stodirascu** [comment]
I guess it's because Tuist is removing the deployment target from the Xcode project. Try adding `static let deploymentTarget: DeploymentTarget = .iOS(targetVersion: "11.0", devices: [.iphone, .ipad])` to _Configuration.swift_ in Tuist. Sorry, forgot to add it.

Basically it breaks when the deployment target is lower than iOS 13. If it's higher, the @available is ignored.

I guess it could be a more generic issue where the @available(iOS, xyz) syntax is not behaving well when the deployment target is less than xyz.

**Comment by danyf90** [comment]
> I guess it's because Tuist is removing the deployment target from the Xcode project. Try adding `static let deploymentTarget: DeploymentTarget = .iOS(targetVersion: "11.0", devices: [.iphone, .ipad])` to _Configuration.swift_ in Tuist. Sorry, forgot to add it.
> 
> 
> 
> Basically it breaks when the deployment target is lower than iOS 13. If it's higher, the @available is ignored.
> 
> 
> 
> I guess it could be a more generic issue where the @available(iOS, xyz) syntax is not behaving well when the deployment target is less than xyz.

Can you update the attached project then? 🙏

**Comment by stodirascu** [comment]
@danyf90 you're killing me 😄

**Comment by stodirascu** [comment]
If it's too hard for you, I will

**Comment by stodirascu** [comment]
I realize now that in the initial description I haven't mentioned that the deployment target needs to be lower than 13 for this to reproduce. So @danyf90 I apologize for the bad collaboration on the issue

**Comment by danyf90** [comment]
> I realize now that in the initial description I haven't mentioned that the deployment target needs to be lower than 13 for this to reproduce. So @danyf90 I apologize for the bad collaboration on the issue

Thanks! That's why it's better to use a sample project 😜

**Comment by stodirascu** [comment]
🙌
