### ISSUE TITLE
Support Package.Requirement implement OptionSet

### ISSUE THREAD

**Issue by rgnns** [tuist/tuist#4990]
### What happened?

[Quikkly SDK](https://github.com/quikkly/ios-sdk) support SPM but on a certain branch (xcode13.1-xc). I want to pull a specific version using a `SwiftPackageManager` `Dependency` but can't because I can't combine enums here. For this example specifically, I need to pull from a `.branch` and a specific `.revision`. Maybe a revision is enough to do this but Tuist will fail regardless saying `/Package.swift` does not exist (it does, but on the specific branch).

### How do we reproduce it?

1. Add `.remote(url: "https://github.com/quikkly/ios-sdk", requirement: .revision("5cf8746e9377f5518917f0cb06e18960063133b2"))` to `Dependencies.swift` under `swiftPackageManager`.
2. Call `tuist fetch`.

Error will show up.

### Error log

```
Updating https://github.com/quikkly/ios-sdk
Updated https://github.com/quikkly/ios-sdk (0.48s)
error: the package manifest at '/Package.swift' cannot be accessed (/Package.swift doesn't exist in file system) in https://github.com/quikkly/ios-sdk
The 'swift' command existed with error code 1
```

### macOS version

13.1

### Tuist version

3.15.0

### Xcode version

14.1.0

**Comment by danyf90** [comment]
Can you attach a sample project?

**Comment by danyf90** [comment]
Please reopen when providing a sample project

**Comment by rgnns** [comment]
Here's a sample project, you can run `tuist fetch` on this repo: [SampleQuikklyTuist](https://github.com/rgnns/SampleQuikklyTuist)

**Comment by rgnns** [comment]
(I can't reopen an issue closed by a repo contributor)

**Comment by danyf90** [comment]
There is no Package.swift at the specified repo and commit 🤔

**Comment by rgnns** [comment]
Yeah, you have to be in the xcode13.1-xc branch. As I explained for this feature request is that I need to pull from that branch AND a specific commit, but I can't do both.

**Comment by danyf90** [comment]
> Yeah, you have to be in the xcode13.1-xc branch. As I explained for this feature request is that I need to pull from that branch AND a specific commit, but I can't do both.

a commit is a commit, the branch shouldn't matter 🤔

**Comment by rgnns** [comment]
Oh, just noted `Package.swift` is only added until later. Thanks.
