### ISSUE TITLE
Generated bundleFinder break compiling in Xcode 14

### ISSUE THREAD

**Issue by messin9** [tuist/tuist#5008]
### What happened?

When generating the project using Tuist, the generated TuistBundle+{TargetName} swift file contains code that doesn't compile under Xcode 14.

### How do we reproduce it?

1. app with deployment target IOS 12.0
2. resourceSynthesizers: []
3. run tuist generate
4. build project 

### Error log

<img width="1163" alt="Снимок экрана 2023-01-25 в 16 17 06" src="https://user-images.githubusercontent.com/78151775/214561336-38e1a4e7-07e9-44bf-97f2-b18d0da527f4.png">

### macOS version

12.6.2

### Tuist version

3.15

### Xcode version

14.2

**Comment by danyf90** [comment]
Sample project?

**Comment by messin9** [comment]
> Sample project?

Project manifest or entire project?

**Comment by danyf90** [comment]
Project

**Comment by messin9** [comment]
> Entire project, the less time we need to reproduce, the more probable is that we'll fix this

Adjust something in sources fix that issue
But adding option to disable bundleFinder generation will be great

**Comment by danyf90** [comment]
No sample project
