### ISSUE TITLE
Unable to run local tuist cloud

### ISSUE THREAD

**Issue by anuragajwani** [tuist/tuist#5032]
### What happened?

I am currently testing out tuist cloud. We are still weighing up options. One of the options is to use self-hosted tuist cloud mentioned in the [tuist docs](https://docs.tuist.io/cloud/contributing/). I have followed the instructions on that page. When executing `./up` I get the following error:

```sh
==> Successfully started `postgresql@14` (label: homebrew.mxcl.postgresql@14)
rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/../tuist/projects/cloud/config/environments/development.rb:90:in `block in <main>'
/../tuist/projects/cloud/config/environments/development.rb:5:in `<main>'
/../tuist/projects/cloud/config/environment.rb:7:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/../tuist/projects/cloud/config/environments/development.rb:90:in `block in <main>'
/../tuist/projects/cloud/config/environments/development.rb:5:in `<main>'
/../tuist/projects/cloud/config/environment.rb:7:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

### How do we reproduce it?

Follow the instructions on the [tuist cloud contributing page](https://docs.tuist.io/cloud/contributing/) on a clean repo.

### Error log

```sh
==> Successfully started `postgresql@14` (label: homebrew.mxcl.postgresql@14)
rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/../tuist/projects/cloud/config/environments/development.rb:90:in `block in <main>'
/../tuist/projects/cloud/config/environments/development.rb:5:in `<main>'
/../tuist/projects/cloud/config/environment.rb:7:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
rails aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/../tuist/projects/cloud/config/environments/development.rb:90:in `block in <main>'
/../tuist/projects/cloud/config/environments/development.rb:5:in `<main>'
/../tuist/projects/cloud/config/environment.rb:7:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

### macOS version

13.1

### Tuist version

3.10.0

### Xcode version

14.2.0

**Comment by fortmarek** [comment]
> and create a new credentials.yml file that you will be able to start editing right away.

Does this not happen? The error signals that the credentials file is invalid. Can you post the whole log from `./up`?

**Comment by danyf90** [comment]
Closed as inactive

**Comment by asevko-ydx** [comment]
The solution is:

- Install VSCode
- Add `code` to `PATH`. Open VSCode, `cmd + shift + P`, type `install code to PATH`
- [Install](https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable) `yarn`
- Run `./up`
- In opened editor copy contents of `config.credentials.example.yaml`, except `secret_key_base`, leave generated one
- Close editor
- Run `bin/rails db: create`
- Run `bin/rails db: migrate`
- Run `bin/rails db:seed` - it will generate sample projects and users. Use that creds to login
- Start server via `./dev`
- Navigate to `127.0.0.1:3000` and you will be able to login via generated creds

Note, if you want to use local cache, you need, to provide `aws_creds`, as mentioned in [docs](https://docs.tuist.io/cloud/contributing/).

More info in [Slack](https://tuistapp.slack.com/archives/C022USUJ0DA/p1679327714450889) 🧵
