### ISSUE TITLE
`tuist test` doesn't use cached binaries

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#5034]
### What happened?

When using `tuist test` command the cached binaries are ignored.

We should leverage the tuist cache to speedup the tests execution.

### How do we reproduce it?

- Got to the `app_with_tests` fixture
- Run `tuist cache warm`
- Run `tuist test`

### Error log

Cached targets are built from source even if the cache was already warmed

### macOS version

12.3

### Tuist version

3.15.0

### Xcode version

14.2.0

**Comment by ronanociosoig** [comment]
I presume that what I am looking for in the console is the following line: 

[tvOSFramework] Compiling tvOSFramework_vers.c

A fix would mean this does not appear in the test command output. Is that correct?

**Comment by ronanociosoig** [comment]
Work in progress on this is on the branch bugfix/tuist-test-use-cached-binaries

**Comment by Alex-Ozun** [comment]
@ronanociosoig have you been able to make progress on this work?

**Comment by Alex-Ozun** [comment]
@leszko11 Please feel free to work on it
Cc @fortmarek

**Comment by leszko11** [comment]
Say no more 🏃🏼

**Comment by fortmarek** [comment]
Hey, folks 👋 

Just a quick update that I already have a functioning prototype for this, so this feature should get in `main` relatively soon 🤞
