### ISSUE TITLE
Bug with `.xib` loading in a bundle which contains resources folders with spaces into the name

### ISSUE THREAD

**Issue by malcommac** [tuist/tuist#5036]
### What happened?

Following the discussion on Slack channel ([link](https://tuistapp.slack.com/archives/CCXC295QS/p1673599249723589)) I discovered a bug with Tuist project generation which happens starting from 3.12.0+ (it's actually present on latest 3.15.0 release).

The bug happens when a module contains a bundle with one or more folders with spaces into the name *(I know, I know, we should never-ever use spaces in file/folder names)*.
In this case, if you try to load `.xib` into the same bundle, the process will fail with an error like this:

```
Terminating app due to uncaught expectation 'NSInternalInconsistencyException`, reason: 'Could not load NIB in bundle [bundle name]
```

The `.xib` file is present and compiled into the bundle, but loading never happens.

This is an example:

<img width="1925" alt="image-1" src="https://user-images.githubusercontent.com/235645/217479114-3e4c5c6a-9420-44ec-9a1d-813364746c17.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/235645/217478870-08c59f5d-f241-435e-bb8e-a48ad1c1796b.png">

The SPM's `Package.swift` declaration is:

```swift
resources: [
  .copy("Classes/Indomio/UI Controls/Controls/ICYouTubePlayer/Support Files/"),
]
```

### How do we reproduce it?

I'm able to reproduce the issue with this sample project:
[TuistNibTest.zip](https://github.com/tuist/tuist/files/10683507/TuistNibTest.zip)

As soon as the "Support Files" directory contains whitespace the crash appears. 
Without the whitespace not.
I also did the following:
- Removed the whitespace from the directory, tuist clean, tuist fetch, tuist generate
- Then it works
- Afterwards, I directly modified the Xcode project and inserted the whitespace again in the generated Xcode project
- Then the crash appears again

So I am not sure if this is an Xcode issue or a Tuist one.
In fact, it does not happen with old Tuist versions like 3.11 or earlier

### Error log

```sh
Terminating app due to uncaught expectation 'NSInternalInconsistencyException`, reason: 'Could not load NIB in bundle [bundle name]
```

### macOS version

12.0

### Tuist version

3.12.0+

### Xcode version

14.2.0

**Comment by danyf90** [comment]
If it fails also if changing it from Xcode I would say it's an Xcode problem.
It wasn't failing before tuist 3.12 probably because that resource was included by name instead of by folder, but that was wrong, the change just surfaced the Xcode problem
