### ISSUE TITLE
`ResourceFileElement.glob` treats `.xcframework` as file instead of folder

### ISSUE THREAD

**Issue by UniekLee** [tuist/tuist#5039]
### What happened?

When defining a ResourceFileElement with a path that includes a `.xcframework`, Tuist appears to treat the `.xcframework` as a file rather than a folder, and won't include any files within it. 

When the path is defined as:

```
resources: [
        "Targets/ResourceFileElementGlobDemo/Frameworks/GoogleMaps.xcframework/ios-arm64_x86_64-simulator/GoogleMaps.framework/Resources/GoogleMaps.bundle",
    ],
```

The `tuist generate` command fails with the error: "Couldn't find a reference for the file at path ~/Targets/ResourceFileElementGlobDemo/Frameworks/GoogleMaps.xcframework."

![Screenshot 2023-02-10 at 16 50 04](https://user-images.githubusercontent.com/2877482/218150951-077cd3cf-ea21-4631-b7a3-f929548bcd93.png)

An example use case is the Google Maps framework: [To set up Google Maps, using XCFramework binaries](https://developers.google.com/maps/documentation/ios-sdk/config#xcframework-manual), step 6 requires the GoogleMaps.bundle file to be included in the "Copy Bundle Resources" build phase.

### How do we reproduce it?

1. Use the attached sample project.
    - [ResourceFileElementGlob.zip](https://github.com/tuist/tuist/files/10709706/ResourceFileElementGlob.zip)
2. Run `tuist generate`.
3. See the error

### Error log

```sh
Couldn't find a reference for the file at path ~/.../Targets/ResourceFileElementGlobDemo/Frameworks/GoogleMaps.xcframework.
```

### macOS version

13.2

### Tuist version

3.15.0

### Xcode version

14.0.1

**Comment by kwridan** [comment]
hi @UniekLee 

This sounds similar to a past issue https://github.com/tuist/tuist/issues/1779 which arises due a few limitations with how file elements are handled (especially when multiple references are made, one as an xcframework and another to a path within it).

One solution in the interim is to symlink to the bundle (e.g. `Vendor/GoogleMaps.bundle`) and reference that within the project manifest.

**Comment by Kamajabu** [comment]
If anyone has problems with manually installed GoogleMaps (https://developers.google.com/maps/documentation/ios-sdk/config) - remember to move it from `ios-arm64_x86_64-simulator/GoogleMaps.framework/Resources` to some other directory and then reference it through resources. 

Tuist has problems only if you keep GoogleMaps.bundle nested inside of GoogleMaps.xcframework and then try to reference it, eg. 

`dependencies: [ .xcframework(path: "GoogleMaps/GoogleMaps.xcframework")]`

 while referencing resources as 
 
 ` "GoogleMaps/GoogleMaps.xcframework/ios-arm64_x86_64-simulator/GoogleMaps.framework/Resources/GoogleMaps.bundle"],` 
 
 Moving bundle up in hierarchy and referencing it as 
 
 ` "GoogleMaps/GoogleMaps.bundle"` solves this issue
