### ISSUE TITLE
Test targets of local SPM packages are not set in test scheme

### ISSUE THREAD

**Issue by nwolvo** [tuist/tuist#5043]
### What happened?

I am using tuist to generate an iOS project with some local swift packages and unit tests. I would like to create a scheme for all unit tests, which also includes all unit tests of the local swift packages. However, when I am adding test targets of the  local packages in the testAction array of a scheme configuration, they are not included in the generated scheme.

The scheme for all unit tests are created as follows:
```
schemes: [
        Scheme(
            name: "UnitTests",
            shared: true,
            buildAction: .buildAction(targets: ["ExampleApp"]),
            testAction: .targets(["ExampleAppTests", "ExamplePackageTests"]),
            runAction: .runAction(executable: "ExampleApp")
        )
    ]
```

Unfortunately, only the ExampleAppTests target is set in the generated scheme. The ExamplePackageTests target is missing and must be set manually. 
<img width="935" alt="Bildschirmfoto 2023-02-13 um 12 19 55" src="https://user-images.githubusercontent.com/62283764/218444669-3ac156a5-0bfe-4695-a1cf-d6588cd7d211.png">

### How do we reproduce it?

Steps to reproduce the bug:

1. Use the attached sample project ([example-app.zip](https://github.com/tuist/tuist/files/10721656/example-app.zip))
2. run `tuist generate`
3. see in UnitTest scheme that the ExamplePackageTests are not included

### Error log

n/a

### macOS version

12.6

### Tuist version

3.15.0

### Xcode version

14.2.0

**Comment by danyf90** [comment]
This is currently not possible, but I know @shahzadmajeed is looking at it

**Comment by danyf90** [comment]
In general I would recommend not doing it, as it would mean adding those targets as source instead of cache, and I would rather test those using the Package.swift

**Comment by nwolvo** [comment]
Thanks for your advice, @danyf90. Which way would you recommend to add local dependencies?

**Comment by danyf90** [comment]
> Thanks for your advice, @danyf90. Which way would you recommend to add local dependencies?

Why do you need them to be packages instead of just be part of the tuist project?

**Comment by nwolvo** [comment]
> > Thanks for your advice, @danyf90. Which way would you recommend to add local dependencies?
> 
> Why do you need them to be packages instead of just be part of the tuist project?

I would like to separate each module in one swift package so that you need an explicit import statement to use these functionalities. To be honest, though, I don't have much experience with SPM yet either.

**Comment by danyf90** [comment]
> > > Thanks for your advice, @danyf90. Which way would you recommend to add local dependencies?
> 
> > 
> 
> > Why do you need them to be packages instead of just be part of the tuist project?
> 
> 
> 
> I would like to separate each module in one swift package so that you need an explicit import statement to use these functionalities. To be honest, though, I don't have much experience with SPM yet either.

You can do that with tuist without the need of having spm

**Comment by shahzadmajeed** [comment]
Hi, yes this work is in progress. I had to make some changes to my original approach but got it back on track.. Will put up a PR soon. You can see preliminary changes here if interested https://github.com/shahzadmajeed/tuist/tree/schemes-with-external-targets

**Comment by danyf90** [comment]
Closed by this comment: https://github.com/tuist/tuist/issues/5043#issuecomment-1429449120

**Comment by amine2233** [comment]
> Hi [@nwolvo](https://github.com/nwolvo), why don't you create a test plan "manually" in Xcode instead of the testing scheme through tuist?

works fine,
