### ISSUE TITLE
Core Data model from SPM dependency does not exist

### ISSUE THREAD

**Issue by ammerzon** [tuist/tuist#5046]
### What happened?

I have a project and want to add the [SuperwallKit](https://github.com/superwall-me/Superwall-iOS) (@superwall-me) framework.

```swift
import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: .init(
        [
            .remote(url: "https://github.com/superwall-me/paywall-ios", requirement: .exact("3.0.0-beta.4"))
        ]
    ),
    platforms: [.iOS]
)
```

### How do we reproduce it?

1. Use the attached sample project
2. Run `tuist fetch`
3. Run `tuist generate`
4. See the error

[superwall.zip](https://github.com/tuist/tuist/files/10765933/superwall.zip)

### Error log

```sh
Resolved cache profile 'Development' from Tuist's defaults
The default version of the Core Data model at path my-project-folder/superwall/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/paywall-ios/Sources/SuperwallKit/Storage/Core Data/SuperwallKit_Model.xcdatamodeld, SuperwallKit_Model, does not exist. There should be a file at my-project-folder/superwall/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/paywall-ios/Sources/SuperwallKit/Storage/Core Data/SuperwallKit_Model.xcdatamodeld/SuperwallKit_Model.xcdatamodel
The default version of the Core Data model at path my-project-folder/superwall/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/paywall-ios/Sources/SuperwallKit/Storage/Core Data/SuperwallKit_Model.xcdatamodeld, SuperwallKit_Model, does not exist. There should be a file at my-project-folder/superwall/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/paywall-ios/Sources/SuperwallKit/Storage/Core Data/SuperwallKit_Model.xcdatamodeld/SuperwallKit_Model.xcdatamodel
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

13.1

### Tuist version

3.16.0

### Xcode version

14.2.0

**Comment by danyf90** [comment]
I think it might be related to the space that it's there (the `Core Data` part of the path)

**Comment by ammerzon** [comment]
If this is the case, could this be a problem with multiple libraries containing folder names with spaces?

**Comment by danyf90** [comment]
> If this is the case, could this be a problem with multiple libraries containing folder names with spaces?

Yes, but likely programmers are usually not so crazy to use spaces in filenames 😁
Anyway, this should be easy to fix in tuist

**Comment by danyf90** [comment]
Turned out it was a different problem, fixed [here](https://github.com/tuist/tuist/pull/5049)
