### ISSUE TITLE
Tuist fetch succeeds if run in a folder without a tuist project

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#5047]
### What happened?

`tuist fetch` should fail if not run in a tuist-related folder, similar to what `tuist generate` does

### How do we reproduce it?

1. Be in any folder without a tuist project (even an empty one)
2. Run `tuist fetch`

### Error log

```
tuist fetch
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
```

### macOS version

12.3

### Tuist version

3.16.0

### Xcode version

14.2.0

**Comment by havebeenfitz** [comment]
Hey @danyf9, tried to fix the issue. Please take a look when possible
