### ISSUE TITLE
Swiftgen version uses old URL for stencil, causing a warning when also a dependency for parent projects

### ISSUE THREAD

**Issue by zzt4** [tuist/tuist#5058]
### What happened?

The SwiftGen dependency is using an old URL for Stencil, which causes a warning when a parent project also has a dependency on Stencil. Swift gives the following error:

```sh
warning: 'swiftgen': 'swiftgen' dependency on 'https://github.com/kylef/Stencil.git' conflicts with dependency on 'https://github.com/stencilproject/Stencil.git' which has the same identity 'stencil'. this will be escalated to an error in future versions of SwiftPM. 
```

It looks like updating to at least version `6.6.0` of SwiftGen should fix this issue.

### How do we reproduce it?

Create a new Tuist project that also has a dependency on `Stencil`. When building, Swift package manager will generate the warning.

### Error log

```sh
warning: 'swiftgen': 'swiftgen' dependency on 'https://github.com/kylef/Stencil.git' conflicts with dependency on 'https://github.com/stencilproject/Stencil.git' which has the same identity 'stencil'. this will be escalated to an error in future versions of SwiftPM. 
```

### macOS version

13.1

### Tuist version

3.14.0

### Xcode version

14.2

**Comment by danyf90** [comment]
Hi @zzt4  👋 
Feel free to open a PR for this if you want 🙏
