### ISSUE TITLE
Xcode 11 - Swift 5.1 issue

### ISSUE THREAD

**Issue by dcvz** [tuist/tuist#507]
**Describe the bug**
Now that iOS 13 is out and we're encouraged to use Xcode 11 -- I'm running into an issue running `tuist generate`:

```
module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler
```

**To Reproduce**
Download Xcode 11 and setup the xcode tools and try to run `tuist generate`.

**Expected behavior**
The tool should run.

**Comment by dcvz** [comment]
My guess is the binary is compiled with 5.0.1 and that’s why it’s failing to import the ProjectDescription?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pepibumur** [comment]
> My guess is the binary is compiled with 5.0.1 and that’s why it’s failing to import the ProjectDescription?

Exactly. I wonder if we can compile `ProjectDescription` in such a way that it can be linked from binaries compiled with any version of Swift. In case you want to investigate it:
- [This](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Generator/GraphManifestLoader.swift#L173) is the logic that compiles the manifest linking it against `ProjectDescription`.
- We compile `ProjectDescription` using the Swift Package Manager _(i.e. `swift build`)_ 

cc @tuist/core

**Comment by marciniwanicki** [comment]
I think we won't be able to use a single `ProjectDescription ` framework till swift module stability is implemented (I might be wrong here - don't have much experience with swift precompiled frameworks). I guess we can try to ship two frameworks and based on the user's swift version, determine which one should be linked. It would require an additional system call so shouldn't affect the performance too much... maybe. I will need to look a bit more into it.

**Comment by ollieatkinson** [comment]
Isn’t Module Stability is implemented in 5.1 ?

**Comment by marciniwanicki** [comment]
You're right @ollieatkinson, once we switch to 5.1, it should be all good. There are few extra warnings but current master can be compiled with 5.1.

**Comment by pepibumur** [comment]
According to [this page](https://swift.org/blog/abi-stability-and-more/) is still under active development. We can distribute versions of `ProjectDescription` for different versions of Swift, which would complicate the release logic a bit, or release a new version from which we support only Swift 5.1. Considering teams are usually fast at upgrading Xcode versions, and the OS does it automatically, I'd use this a mechanism to nudge developers to the newest version.

Thoughts @ollieatkinson / @marciniwanicki ?

**Comment by dcvz** [comment]
Looks like Swift 5.1 is out now: https://swift.org/blog/swift-5-1-released/

**Comment by dcvz** [comment]
In the meantime for anyone else experiencing this issue: I've gone ahead and compiled the project from `master` using the Swift Package Manager: `swift build -c release` and made tuist-env use that version.

**Comment by ollieatkinson** [comment]
I agree, we should look at doing another release with the 5.1 compiler for those who wish to upgrade to Xcode 11 - I would hate for Tuist to be a barrier for that decision.

**Comment by ollieatkinson** [comment]
I've implemented the changes required for Xcode 11 in this pull request: https://github.com/tuist/tuist/pull/394

Once I'm happy with the changes inside of it, I will merge it and perform a release of 0.18.0.

**Comment by pepibumur** [comment]
This has already been done so we can close the issue.
