### ISSUE TITLE
[Dependencies.swift][SPM] Support link system framework of Swift Package Manager's .linkedFramework as optional when package deployment target is lower

### ISSUE THREAD

**Issue by 0xWOF** [tuist/tuist#5078]
### What happened?

On Swift Package Manager if package's deployment target is lower than `system framework of .linkedFramework`'s deployment target, Swift Package Manager automatically link system framework as optional. But Tuist do not support this feature. (framework is always linked as required)

- Swift Package Manager
https://forums.swift.org/t/why-swift-package-manager-does-not-support-weak-linking-weak-framework-swiftui/31418
- Tuist 
https://github.com/tuist/tuist/blob/4a4defddc20fd8480706224b2c0f86436e2fa5a0/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L778-L779

Because of this issue, if `A Swift Package` (deployment target is 9.0) has .linkedFramework (deployment target is 15.0) and using `A Swift Package` on Tuist project, App is crashed on iOS 14.0 and is not crashed on iOS 16.0. But if use `A Swift Package` on Xcode project, App is not crashed on iOS 14.0 and iOS 16.0.

### How do we reproduce it?

1. Create Swift Package. (Set deployment target as iOS 11.0)
2. Add .linkedFramework to Package.swift (for example: AdServices.framework (requires iOS 14.3) )
3. Create Tuist project. (Set deployment target (for example: iOS 14.0) as lower than .linkedFramework's deployment target (for example: iOS 14.3) )
4. Add created Swift Package to Dependencies.swift
5. Add Swift Package to dependencies of Target (.linkedFramework will linked as required)
6. Run target on iOS (for example: iOS 14.0) that lower than .linkedFramework's deployment target (for example: iOS 14.3)
7. App is crashed with below message
    ```
    Message from debugger: Terminated due to signal 6
    dyld: Library not loaded: /System/Library/Frameworks/AdServices.framework/AdServices
    ```
8. Create Xcode project. (Set deployment target (for example: iOS 14.0) as lower than .linkedFramework's deployment target (for example: iOS 14.3) )
9. Add Swift Package to dependencies of Target (.linkedFramework will linked as optional)
10. Run target on iOS (for example: iOS 14.0) that lower than .linkedFramework's deployment target (for example: iOS 14.3)
11. App is opened properly

### Error log

```
Message from debugger: Terminated due to signal 6
dyld: Library not loaded: /System/Library/Frameworks/AdServices.framework/AdServices
```

### macOS version

13.2

### Tuist version

3.16.0

### Xcode version

14.2

**Comment by danyf90** [comment]
@kwridan do you see any problem if we always map them to optional?
