### ISSUE TITLE
Multilinked static product lint warning

### ISSUE THREAD

**Issue by klememi** [tuist/tuist#5079]
### What happened?

I have simple project with app, framework and SPM dependency in both targets. Generating project file with tuist produces lint warning that the dependency product is static but it's not. Am I missing something (doing something wrong) or is it really bug? I would like to get rid of this warning.

### How do we reproduce it?

I have Project.swift where I defined:
1. Resolver package `.remote(url: "https://github.com/hmlongco/Resolver.git", requirement: .exact("1.5.0"))`
2. iOS framework target with dependency: `.package(product: "Resolver-Dynamic")`
3. iOS app target with dependencies: `.package(product: "Resolver-Dynamic")`, `.target(name: "B")`
then running `tuist generate` produces lint warning `Warning: Package 'Resolver-Dynamic ' has been linked from target 'A', and target 'B', it is a static product so may introduce unwanted side effects.` which, I assume, is false positive.

### Error log

```sh
Resolved cache profile 'Development' from Tuist's defaults
Generating workspace App.xcworkspace
Generating project App
Resolving package dependencies using xcodebuild

Warning: Package 'Resolver-Dynamic ' has been linked from target 'A', and target 'B', it is a static product so may introduce unwanted side effects.

Project generated.
Total time taken: 3.754s
```

### macOS version

13.2.1

### Tuist version

3.16.0

### Xcode version

14.2

**Comment by klememi** [comment]
They might be static by default but as you can see I use `Resolver-Dynamic` which is dynamic product in Swift package (I forgot to mention it explicitly). That's why I'm confused with that warning.

**Comment by danyf90** [comment]
Then provide a sample project and I'll have look 🙏

**Comment by klememi** [comment]
OK, here's [sample](https://github.com/klememi/TuistSample). Thanks a lot for you help!

**Comment by danyf90** [comment]
That's the deprecated dependency model, using the new model should work fine.
Please refer to this page: https://docs.tuist.io/guides/third-party-dependencies
