### ISSUE TITLE
Dynamic frameworks with name starting with underscore won't build Docc documentation

### ISSUE THREAD

**Issue by gasigo** [tuist/tuist#5087]
### What happened?

![208101563-8ad83d23-955c-4bd9-b344-f395dc25b4b4](https://user-images.githubusercontent.com/8558287/223190744-68a4b510-db7d-4fa2-87c6-8b9cc5b935cf.png)

While trying to generate documentation for a framework importing a dynamic framework the process fails with the above error.

The issue was initially open and discussed here: https://github.com/pointfreeco/swiftui-navigation/issues/55. During the investigation we concluded that the problem is indeed with Tuist.

### How do we reproduce it?

I've create a sample project where the issue can be seen, you can access it in the below repository.

https://github.com/gasigo/tuist-swiftui-navigation-docc

### Error log

```sh
Error: Missing value for '--fallback-bundle-identifier <fallback-bundle-identifier>'
Help:  --fallback-bundle-identifier <fallback-bundle-identifier>  A fallback bundle identifier if no value is provided in the documentation bundle's Info.plist file.
Usage: docc convert [<options>] <source-bundle-path>
  See 'docc convert --help' for more information.
Command CompileDocumentation failed with a nonzero exit code
```

### macOS version

13.2.1

### Tuist version

3.15.0

### Xcode version

14.2.0

**Comment by ThePragmaticArt** [comment]
Same issue on my side, ironically tied to the same TCA SwiftUI navigation library by the Point Free guys (@stephencelis and team https://github.com/pointfreeco/swiftui-navigation).
