### ISSUE TITLE
Can't locate sources for C target in SPM Package.swift

### ISSUE THREAD

**Issue by SpectralDragon** [tuist/tuist#5091]
### What happened?

I'm trying to add SPM package with freetype library https://github.com/AdaEngine/msdf-atlas-gen/blob/master/Package.swift
but when I generate a xcproject file, in console I see the next message:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/6003467/223592272-29b25326-ebdc-4661-ada7-4840173e8907.png">

Example of package manifest file:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/6003467/223592166-ca1599b1-ecfb-43b5-a9a9-331f7cb13c63.png">

### How do we reproduce it?

1) Add this package as macos dependency https://github.com/AdaEngine/msdf-atlas-gen/
2) fetch and generate an xcproject.

### Error log

```sh
Resolved cache profile 'Development' from Tuist's defaults
Generating workspace AdaEngine.xcworkspace
Generating project Yams
Generating project libpng
Generating project msdf-atlas-gen
Generating project AdaEditor
Generating project Math
Generating project swift-collections
Generating project AtlasFontGenerator
Generating project AdaEngine
Generating project box2d

Warning: The target freetype doesn't contain source files.

Project generated.
Total time taken: 0.256s
```

### macOS version

13.1

### Tuist version

3.9.0

### Xcode version

14.3

**Comment by danyf90** [comment]
Can you please follow the template and provide a sample project?

**Comment by danyf90** [comment]
Will reopen once info are provided
