### ISSUE TITLE
Resolve warnings for old API being used in unit tests.

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#510]
**Describe the bug**
After implementing multiline settings we have not updated the unit tests resulting in warnings printed when run.

We should look at removing these warnings so that others do not get hidden.

**To Reproduce**
1. Run unit tests for `tuist`

**Expected behavior**
No warnings

**Screenshots**
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/1382565/65498175-53ec0600-deb3-11e9-886d-b3627e0f534c.png">

**Additional context**
Introduced in https://github.com/tuist/tuist/pull/464

**Comment by mollyIV** [comment]
👋 Just created a PR to resolve the issue, cheers 🙇
