### ISSUE TITLE
3.17.0 has missing BuildRule in https://github.com/tuist/ProjectDescription

### ISSUE THREAD

**Issue by apps4everyone** [tuist/tuist#5100]
### What happened?

3.17.0 has missing BuildRule in SPM https://github.com/tuist/ProjectDescription

### How do we reproduce it?

import SPM ProjectDescription with 3.17.0

### Error log

Cannot find type 'BuildRule' in scope

### macOS version

13.2.1

### Tuist version

3.17.0

### Xcode version

14.2.0

**Comment by danyf90** [comment]
No sample project

**Comment by apps4everyone** [comment]
Hey, attached a example Project and the screenshot to see the errors.

[Test.zip](https://github.com/tuist/tuist/files/10983744/Test.zip)

Hopefully with this the issue can be reproduced and the ticket reopened.

<img width="1190" alt="Screenshot 2023-03-15 at 20 05 57" src="https://user-images.githubusercontent.com/1915802/225416650-8e429a45-af39-46a5-818e-513b2ae8e403.png">

**Comment by danyf90** [comment]
I've re-released tag 3.17.0 for https://github.com/tuist/ProjectDescription, should be fixed now.
You probably need to clear the SPM cache to remove the old wrong tag from your local machine
