### ISSUE TITLE
is not a valid configured external dependency

### ISSUE THREAD

**Issue by onurhuseyincantay** [tuist/tuist#5114]
### What happened?

I tried to add my external package via tuist and couldn't make the project build. when I try to add the package with Xcode manually it finds and adds the project.
I keep getting `Hover` is not a valid configured external dependency for platform ios

### How do we reproduce it?

1. create a sample project with tuist init --platform iOS
2. create Dependencies on Tuist directory
3. add external link (in my case https://github.com/onurhuseyincantay/Hover)
4. provide exact tag 1.1
5. provide platforms [.iOS]
6. add .external(name: "Hover")
7. tuist generate
8. observe the error.

### Error log

Resolved cache profile 'Development' from Tuist's defaults
`Hover` is not a valid configured external dependency for platform ios
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

12.6.3

### Tuist version

3.17.0

### Xcode version

14.2

**Comment by danyf90** [comment]
No sample project

**Comment by onurhuseyincantay** [comment]
@danyf90  sorry for missing out on the sample project I created another issue https://github.com/tuist/tuist/issues/5117 please let me know if you need further details.
