### ISSUE TITLE
Improve error reporting if running `tuist generate` without `tuist fetch`

### ISSUE THREAD

**Issue by danyf90** [tuist/tuist#5118]
### What happened?

If you run `tuist generate` without running `tuist fetch` before, the error message is not clear (for example, "`Alamofire` is not a valid configured external dependency for platform watchos").
If `Tuist/Dependencies.swift` is present but `Tuist/Dependencies/graph.json` is not present, a better error should be printed: "`Tuist/Dependencies.swift` file is defined but `Tuist/Dependencies/graph.json` cannot be found. Run `tuist fetch` first.

The same should probably apply to any other command that needs to parse the Project.swift, such as `tuist cache`

### How do we reproduce it?

- Go to `projects/tuist/fixtures/app_with_spm_dependencies/`
- run `tuist clean`
- run `tuist generate`

### Error log

```sh
The shown error is "`Alamofire` is not a valid configured external dependency for platform watchos"
```

### macOS version

13

### Tuist version

3.17.0

### Xcode version

14.2

**Comment by mustiikhalil** [comment]
I would love to work on this issue if possible. Can I get it assigned to me?
