### ISSUE TITLE
Can not include `.txt` or `.json` in a target

### ISSUE THREAD

**Issue by raphaelbussa** [tuist/tuist#5124]
### What happened?

I'm moving a project to tuist and need some .txt and .json files in a test package as a fixture.
I have tried to add them using `sources` and `additionalFiles`. But in the first case, there are just ignored, and in the second one the files are actually visible in the group but the target membership is not set.

### How do we reproduce it?

Add any txt or json files in the source folder of the default scaffold app. There will not be included in the target.

### Error log

Not available

### macOS version

13.2.1

### Tuist version

3.16.0

### Xcode version

14.2

**Comment by danyf90** [comment]
Shouldn't these be `resources`?

**Comment by raphaelbussa** [comment]
You are right, just got confused by the resources attribute that I thought was used as a source to generate the tuist generated classes.
