### ISSUE TITLE
Make Tuist generated resource accessors internal

### ISSUE THREAD

**Issue by stodirascu** [tuist/tuist#5139]
### What happened?

I'm building a framework. The project is setup using Tuist. It generates resource accessors and marks all entities inside as Public. This is undesirable, as we don't want to expose these to integrators. I had a read here https://docs.tuist.io/guides/resources/, but couldn't find a way to adjust that.

Can you guys help me out please?

### How do we reproduce it?

1. Setup a project using Tuist
2. Run `tuist generate`
3. Open the `TuistAssets+FrameworkName.swift` and `TuistBundle+FrameworkName.swift` files

Observe that all entities there are public.

### Error log

n/a

### macOS version

1.2.1

### Tuist version

3.16

### Xcode version

14.2

**Comment by bvirlet** [comment]
Hello, I wanted to let you know we have the same issue. Could the assets be made internal?
