### ISSUE TITLE
macbook pro（M1 pro）can not installed success

### ISSUE THREAD

**Issue by liury889** [tuist/tuist#5140]
### What happened?

can not install it

### How do we reproduce it?

1.Clone this repository.
2.Install Tuistf needed.
3.In the repository's directory, run “make sensei bundle-id-prefix=io.tuist”

### Error log

tuist fetch
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
    
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
make: *** [sensei] Error 1

### macOS version

13.2.1

### Tuist version

3.17.0

### Xcode version

14.3

**Comment by danyf90** [comment]
No sample project and unclear reproduction steps
