### ISSUE TITLE
import youtube-ios-player-helper by SPM cannot find YTPlayerView

### ISSUE THREAD

**Issue by AlexPan1992** [tuist/tuist#5144]
### What happened?

https://github.com/youtube/youtube-ios-player-helper

I successfully imported youtube-ios-player-helper using a brand new project through Xcode package dependencies SPM. but Tuist fail.

https://github.com/tuist/tuist/issues/3785 << It looks like the same problem. 

### How do we reproduce it?

`    
.package(url: "https://github.com/youtube/youtube-ios-player-helper.git", .exact(.init(1, 0, 4)))
`

### Error log

Cannot find type 'YTPlayerView' in scope

### macOS version

12.6

### Tuist version

3.17.0

### Xcode version

14.2.0

**Comment by danyf90** [comment]
No sample project and (probably) duplicate

**Comment by amarcadet** [comment]
I am facing the same issue with Xcode 15.2 and Tuist 3.42.2, is there a solution?

I tried adding `YouTubeiOSPlayerHelper` as an `.external` or a `.package` dependency without success.
