### ISSUE TITLE
`tuist cache warm --xcframeworks` error code 70, "A library with the identifier 'ios-arm64' already exists"

### ISSUE THREAD

**Issue by joshgare** [tuist/tuist#5150]
### What happened?

When running `tuist cache warm --xcframeworks` we get the following error:

```
A library with the identifier 'ios-arm64' already exists.
The 'xcodebuild' command exited with error code 70
```

Initial thoughts is because we're running this on an Apple Silicon M2 processor - however we didn't have any issues but have started seeing this when we upgraded to Xcode 14.3.

### How do we reproduce it?

1. `tuist clean`
2. `tuist fetch`
3. `tuist cache warm --xcframeworks`

### Error log

```
[FirebasePerformanceTarget] Processing FirebasePerformanceTarget-Info.plist
[FirebasePerformanceTarget] Compiling dummy.m
[FirebasePerformanceTarget] Compiling FirebasePerformanceTarget_vers.c
[FirebasePerformanceTarget] Touching FirebasePerformanceTarget.framework
[ExponeaSDK] Touching ExponeaSDK.framework
[FirebaseFirestore] Touching FirebaseFirestore.framework
[FirebaseFirestoreTarget] Processing FirebaseFirestoreTarget-Info.plist
[FirebaseFirestoreTarget] Compiling dummy.m
[FirebaseFirestoreTarget] Compiling FirebaseFirestoreTarget_vers.c
[FirebaseFirestoreTarget
] Touching FirebaseFirestoreTarget.framework
[Ometria] Compiling Ometria_vers.c
[Ometria] Touching Ometria.framework
Archive Succeeded
A library with the identifier 'ios-arm64' already exists.
The 'xcodebuild' command exited with error code 70
```

### macOS version

13.0

### Tuist version

3.17.0

### Xcode version

14.3

**Comment by joshgare** [comment]
Downgrading to Xcode 14.1 resolves this issue, so something between Xcode 14.1 and 14.3 has caused this to become an issue.

**Comment by NachoSoto** [comment]
This is still an issue on Xcode 15

**Comment by fortmarek** [comment]
Hey @NachoSoto 👋 

Can you create a new issue with a reproducible sample if you're still running into this? 🙏

**Comment by NachoSoto** [comment]
https://github.com/tuist/tuist/issues/6163
