### ISSUE TITLE
Static frameworks in XCFrameworks conflict during install

### ISSUE THREAD

**Issue by regularberry** [tuist/tuist#5152]
### What happened?

Static frameworks are now being added as a Dependency on the target, rather than linked and set to "Do Not Embed". This is fine during normal development, but during an archive, the framework will get "Copied on install", which conflicts with the "Process XCFrameworks phase".

Sorry for not catching this during https://github.com/tuist/tuist/pull/5107 @kwridan 

Here's the fixture that can reproduce this:
[ios_app_with_static_library_in_xcframework.zip](https://github.com/tuist/tuist/files/11236094/ios_app_with_static_library_in_xcframework.zip)

### How do we reproduce it?

1. Use the attached fixture
2. Start an Archive build, or uncheck "Copy only when installing" on the MyStaticFramework dependencies to simulate the installation phase.
3. View failed build

### Error log

```
error: Multiple commands produce '/Xcode/DerivedData/App-aulblbemhdrdoidrzroujcdpcwaz/Build/Products/Debug-iphonesimulator/libMyStaticLibrary.a'
    note: Command: ProcessXCFramework /Projects/tuist/projects/tuist/fixtures/ios_app_with_static_library_in_xcframework/Frameworks/MyStaticLibrary/prebuilt/MyStaticLibrary.xcframework /Xcode/DerivedData/App-aulblbemhdrdoidrzroujcdpcwaz/Build/Products/Debug-iphonesimulator/libMyStaticLibrary.a ios simulator
    note: Target 'MyStaticFramework' (project 'App') has copy command from /Projects/tuist/projects/tuist/fixtures/ios_app_with_static_library_in_xcframework/Frameworks/MyStaticLibrary/prebuilt/MyStaticLibrary.xcframework/ios-arm64-simulator/libMyStaticLibrary.a' to /Xcode/DerivedData/App-aulblbemhdrdoidrzroujcdpcwaz/Build/Products/Debug-iphonesimulator/libMyStaticLibrary.a'
```

### macOS version

13.2.1

### Tuist version

3.18.0

### Xcode version

14.3.0

**Comment by kwridan** [comment]
Ouch, thanks for flagging this @regularberry I missed while researching the fix 😞

It seems the technique we use for regular static targets doesn't quite work in the same way, Xcode still processes the xcframework whereas with regular static target, it simply ignores the operation if the product exists.

A few options I can think of to resolve this:

- **a)** Revert back to explicit linking _(means it won't work for the `-ObjC` cases anymore, but at least won't be as reliably broken as it is now)_
- **b)** Explore adding more fine grained framework search paths to allow intermediate targets to see the symbols of the xcframework without explicitly linking it (e.g. inspired by https://github.com/msaps/XCFramework-Link-Issue/pull/2)
- **c)** Explore alternate dependency build phase options that won't result in the multiple commands issue

if you happen to have Xcode 14.3, would be curious if there's any difference in behaviour, as there was a report of a similar issue being resolved in it 🤔 https://forums.swift.org/t/objc-flag-causes-duplicate-symbols-with-swift-packages/27926/19 - will try it out once I've got it set up.

**Comment by Banck** [comment]
The same issue in our project with Tuist 3.18.0. Downgraded to 3.17.0 for now.

**Comment by kwridan** [comment]
Mind testing https://github.com/tuist/tuist/pull/5157 ?

**Comment by zzt4** [comment]
@kwridan I'm on @regularberry's team and tested this out. That PR fixes the issue for us! Thanks for taking a look so quickly. If we can get a release tag for 3.18.1 after that gets merged in, that would be really helpful.
