### ISSUE TITLE
Warnings in fixtures/ios_app_with_coredata_in_static_framework

### ISSUE THREAD

**Issue by haifengkao** [tuist/tuist#5156]
### What happened?

Xcode displays warning in the example project `fixtures/ios_app_with_coredata_in_static_framework`

### How do we reproduce it?

1. download latest tuist
2. cd  tuist-main/projects/tuist/fixtures/ios_app_with_coredata_in_static_framework
3. tuist generate
4. open the workspace, build project

### Error log

```
The Swift file "/Users/lion/Library/Developer/Xcode/DerivedData/Workspace-fzwpauxsfgnyoohaefqufcosiniy/Build/Intermediates.noindex/Framework.build/Debug-iphonesimulator/Framework_Framework.build/DerivedSources/CoreDataGenerated/Users/User+CoreDataClass.swift" cannot be processed by a Copy Bundle Resources build phase

The Swift file "/Users/lion/Library/Developer/Xcode/DerivedData/Workspace-fzwpauxsfgnyoohaefqufcosiniy/Build/Intermediates.noindex/Framework.build/Debug-iphonesimulator/Framework_Framework.build/DerivedSources/CoreDataGenerated/Users/User+CoreDataProperties.swift" cannot be processed by a Copy Bundle Resources build phase

The Swift file "/Users/lion/Library/Developer/Xcode/DerivedData/Workspace-fzwpauxsfgnyoohaefqufcosiniy/Build/Intermediates.noindex/Framework.build/Debug-iphonesimulator/Framework_Framework.build/DerivedSources/CoreDataGenerated/Users/Users+CoreDataModel.swift" cannot be processed by a Copy Bundle Resources build phase

```

### macOS version

13.0

### Tuist version

3.18

### Xcode version

14.3

**Comment by VaishaliDesai** [comment]
Hello, I'm the first time contributor to twist project and I would like to take up this issue if anyone can help assign to me please :)

**Comment by haifengkao** [comment]
No one is working on it. I don't know why?

**Comment by mustafagunes** [comment]
Hello, this topic caught my attention while I was browsing the topics to contribute. Everything seems fine now. I managed to insert several different test data into the database. We can close this issue 🙂

cc: @pepicrft @fortmarek

![result](https://github.com/tuist/tuist/assets/32392406/36b7e077-0e80-40a7-89c3-44fa4d4f9943)

**Comment by fortmarek** [comment]
Thanks for reporting back, closed!
