### ISSUE TITLE
The selected Xcode version is 14.3, which is not compatible with this project's Xcode version requirement of 13.3.1..<13.4.0 or 13.4.0..<13.5.0 or 14.0.0..<14.1.0 or 14.1.0..<14.2.0 or 14.2.0..<14.3.0.

### ISSUE THREAD

**Issue by anz-ryu** [tuist/tuist#5163]
### What happened?

tuist version: 3.18.0

The selected Xcode version is 14.3, which is not compatible with this project's Xcode version requirement of 13.3.1..<13.4.0 or 13.4.0..<13.5.0 or 14.0.0..<14.1.0 or 14.1.0..<14.2.0 or 14.2.0..<14.3.0.

how can I fix this?

### How do we reproduce it?

Run tuist: `tuist generate -n `

### Error log

The selected Xcode version is 14.3, which is not compatible with this project's Xcode version requirement of 13.3.1..<13.4.0 or 13.4.0..<13.5.0 or 14.0.0..<14.1.0 or 14.1.0..<14.2.0 or 14.2.0..<14.3.0.

### macOS version

13.2.1

### Tuist version

3.18.0

### Xcode version

14.3(14E222b)

**Comment by voghDev** [comment]
Hello @anz-ryu !

I see that you marked the issue as completed. How did you finally solve it? We're experiencing the same with Xcode `15.0.1`, Tuist `3.40.0` and Mac OS X Sonoma `14.2.1`.

```
The selected Xcode version is 15.0.1, which is not compatible with this project's Xcode version requirement of 14.0.0..<15.0.0.
```
Any extra information you can add? 

Thank you so much in advance!

**Comment by anz-ryu** [comment]
@voghDev 

I am sorry that did not comment anything before closing.

This issue is caused by `Tuist/Config.swift`, In this file, you can set 
the Tuist runnable XCode version.

**Comment by voghDev** [comment]
No problem mate!

I can confirm that your fix is right. We also fixed the issue by changing `Tuist/Config.swift` file:

```

import ProjectDescription

let config = Config(
    compatibleXcodeVersions: .upToNextMajor("15"), // This was formerly "14". That's the reason why we had the issue 
    swiftVersion: "5.7.1"
)
```

Thanks for your help!
