### ISSUE TITLE
Linking precompiled xcframework assumes framework is dynamic (Multiple commands produce...)

### ISSUE THREAD

**Issue by itsthejb** [tuist/tuist#5176]
### What happened?

It appears that Tuist has an issue handling precompiled frameworks when the precompiled framework is static. Instead, Tuist appears to assume that it is dynamic, and links it on this basis.

Demo project attached.

It appears that the problem is just that Tuist needs to inspect the precompiled framework, and alter handling if the framework is static.

- `ChildStatic` is a `.staticFramework` defined in `Project.swift`. This is correctly linked, in `Link Binary with Libraries` for the immediate parent:

<img width="750" alt="Screenshot 2023-05-03 at 13 13 33" src="https://user-images.githubusercontent.com/557391/235912438-23f71fd1-f196-47c4-9901-977a48500784.png">

- However, `Precompiled.xcframework` is also static. Tuist copies this to the Products Directory in the `Dependencies` phase:

<img width="754" alt="Screenshot 2023-05-03 at 13 14 00" src="https://user-images.githubusercontent.com/557391/235912689-6fad850d-dfaa-4f76-b037-59faec772264.png">

- Instead, it should (I believe) also be in the `Link Binary with Libraries` phase. If manually edited, this works:

<img width="755" alt="Screenshot 2023-05-03 at 13 16 43" src="https://user-images.githubusercontent.com/557391/235913048-e4547fd5-e30a-4fde-8685-60bd35035c90.png">

This is the same as the `Dynamic` framework in the project:

<img width="749" alt="Screenshot 2023-05-03 at 13 17 28" src="https://user-images.githubusercontent.com/557391/235913187-23a4712a-f2ca-4b5e-b890-3699e2b89335.png">

With the manual change to `Static`, Archive for device passes. So it appears this is just a change required for this edge case.

### How do we reproduce it?

1. Download demo project from https://drive.google.com/file/d/1Ey2uwlA8rFVKbV8JMZWkgzsGTX2dS3KI/view?usp=sharing. `Project.swift` is included, and project and workspace are pre-generated
1. Select the `Static` scheme, archive for any iOS device: fails
1. Manually edit the `Static` target: remove `Precompiled.xcframework` from the `Dependencies` phase and add to `Link Binary with Libraries`
1. Archive again for device, succeeds

### Error log

<img width="974" alt="Screenshot 2023-05-03 at 13 09 33" src="https://user-images.githubusercontent.com/557391/235911762-c0db284d-6754-4362-ae3a-cde99495c96a.png">

```
note: Building targets in dependency order
error: Multiple commands produce '/Users/jc/Library/Developer/Xcode/DerivedData/LinkingTest-bsehfrbeijxeftewymikpeydozbx/Build/Intermediates.noindex/ArchiveIntermediates/Static/BuildProductsPath/Release-iphoneos/Precompiled.framework'
    note: Command: ProcessXCFramework /Users/jc/Desktop/LinkingTest/Precompiled.xcframework /Users/jc/Library/Developer/Xcode/DerivedData/LinkingTest-bsehfrbeijxeftewymikpeydozbx/Build/Intermediates.noindex/ArchiveIntermediates/Static/BuildProductsPath/Release-iphoneos/Precompiled.framework ios
    note: Target 'Static' (project 'LinkingTest') has copy command from '/Users/jc/Desktop/LinkingTest/Precompiled.xcframework/ios-arm64/Precompiled.framework' to '/Users/jc/Library/Developer/Xcode/DerivedData/LinkingTest-bsehfrbeijxeftewymikpeydozbx/Build/Intermediates.noindex/ArchiveIntermediates/Static/BuildProductsPath/Release-iphoneos/Precompiled.framework'
```

### macOS version

13.3.1 (a) (22E772610a)

### Tuist version

3.18.0

### Xcode version

14.3 (14E222b)

**Comment by itsthejb** [comment]
Hey @kwridan. Thanks for the quick response. Oh that sounds promising! I'll check it out now

**Comment by itsthejb** [comment]
@kwridan checked. It looks good from the point of view of our use case. Thanks very much! Sorry for the dupe issue

**Comment by kwridan** [comment]
No worries, glad the issue is resolved and thank you for the detailed report. 👍
