### ISSUE TITLE
[Xcode Cloud] "Multiple commands produce" error occurs in v3.18.0

### ISSUE THREAD

**Issue by nilotic** [tuist/tuist#5181]
### What happened?

"Multiple commands produce" error occurs in v3.18.0, only in Xcode Cloud.

The build works fine on the same Local machine.

- Xcode Cloud
  - Xcode Version: Latest Release (Currently Xcode 14.3 (14222b))
  - macOS Version: Latest Release (Currentlv macOS Ventura 13.3.1 (22E261))

### How do we reproduce it?

After adding firebase and facebook library, build in Xcode Cloud.

<br> 

 **Project.swift**
 
```
 static var dependencies: [ProjectDescription.TargetDependency] = [
    .external(name: "FirebaseAnalytics"),
    .external(name: "FirebaseCrashlytics"),
    .external(name: "FirebaseDynamicLinks"),
    .external(name: "FirebaseRemoteConfig"),
    .external(name: "FacebookCore"),
    .external(name: "FacebookShare"),
  ]
```

<br> 
<br> 

**Dependencies.swift**

```
import ProjectDescription

enum Dependency: CaseIterable {
  case facebook
  case firebase
  
  var url: String {
    switch self {
    case .facebook:
      return "https://github.com/facebook/facebook-ios-sdk"
    case .firebase:
      return "https://github.com/firebase/firebase-ios-sdk"
    }
  }
  
  var requirement: Package.Requirement {
    switch self {
    case .facebook:
      return .upToNextMajor(from: "12.3.2")
    case .firebase:
      return .upToNextMajor(from: "9.5.0")
    }
  }
  
  var package: ProjectDescription.Package {
    .remote(url: self.url, requirement: self.requirement)  
  }
}


let dependencies: Dependencies = {
    var packages = Dependency.allCases.map(\.package)
    
    return Dependencies(
        swiftPackageManager: SwiftPackageManagerDependencies(
            packages,
            productTypes: [],
            baseSettings: Settings.settings(
                configurations: [.debug(name: .debug, settings: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": .string("SWIFT_PACKAGE DEBUG"),
                                                                 "IPHONEOS_DEPLOYMENT_TARGET": .string("13.4")])])
        ),
        platforms: [.iOS])
}()
```
 

### Error log

Xcode Cloud

**Archive - iOS** encountered a failure that caused the build to fail.

❌ **Issue**
Multiple commands produce '/Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Test/BuildProductsPath/Beta-iphoneos/FBSDKCoreKit_Basics.framework'

❌ **Issue**
Multiple commands produce '/Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Test/BuildProductsPath/Beta-iphoneos/GoogleAppMeasurement.framework'

### macOS version

13.3.1 (22E261)

### Tuist version

3.18.0

### Xcode version

Xcode 14.3 (14222b)

**Comment by danyf90** [comment]
Can you try with latests version?

**Comment by Taehyeong-Jo** [comment]
I confirmed that it builds on v3.19.0.
Thank you all for your support.
