### ISSUE TITLE
tuist test has issues with xcconfigs with relative (to-parent) path includes

### ISSUE THREAD

**Issue by itsthejb** [tuist/tuist#5184]
### What happened?

Our projects make extensive use of `.xcconfig` files, particularly for shared build settings. Therefore, our configs always have `#includes` that backtrack up a few parent paths (`#include "../../../..."` or even a little more)

Whilst everything works ok with `tuist generate`, this does not work correctly with `tuist test`, sorry we have a lot of errors such as:

```
Testing failed:
        could not find included file '../../...'
```

... and the command fails.

### How do we reproduce it?

Currently I haven't been successful recreating the issue in a pet-project! What I can do is try to illustrate what may be causing this

- `tuist generate` workspace for module
- `tuist test --verbose`, and pick out the generated test workspace in `~/.tuist/Cache`
- Run [`xcdiff`](https://github.com/bloomberg/xcdiff) to focus on differences in settings.

The results: [diff.txt](https://github.com/tuist/tuist/files/11443879/diff.txt). `tuist generate` is the first, `tuist test` project settings are the second.

It looks for me that the paths for the parent xcconfigs are relative to the `Cache` directory. If so, it makes sense that the relative paths don't work. However, when trying to recreate this in a pet project, everything seemed to work just fine.

So happy to investigate more closely. Sorry I'm not able to give a clearer report right now 😔

### Error log

```
could not find included file '../../TheSettings/Global/Modules/SomeSharedSettings.xcconfig' in search paths
etc.
```

Then missing settings as a consequence. = builds fail

### macOS version

13.3.1 (a) (22E772610a)

### Tuist version

3.18.0

### Xcode version

14.3 (14E222b)

**Comment by danyf90** [comment]
Hard to help if you can't replicate, please try to incrementally make the pet project close to the actual one and at some point you should be able to replicate it, and probably also pin-point the problem

**Comment by itsthejb** [comment]
Indeed! I’ll have another try at that later. Thanks

**Comment by itsthejb** [comment]
@danyf90 Ok, happy to report I've been able to create something that recreates the issue:

- https://drive.google.com/file/d/1G1--hWXqvC74Od7qFeEO6xqDjnumrWFv/view?usp=sharing
- Module is in `TestIssue/ParentDir/TheModule`
- `tuist build TheModule` succeeds:

```
Building scheme TheModule
2023-05-11 10:25:44.878 xcodebuild[86279:869397] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:3525148D-FF01-44B7-88FD-D8769838BC54, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:3525148D-FF01-44B7-88FD-D8769838BC54, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
[[36mTheModule[0m] [1mProcessing[0m TheModule-Info.plist
[1mSigning[0m TheModule.framework (in target 'TheModule' from project 'TheModule')
[32;1mBuild Succeeded[0m
The project built successfully
```

- However, `tuist test TheModule` fails:

```
Generating project for testing
Generating workspace TheModule.xcworkspace
Generating project TheModule
Testing scheme TheModule-Workspace
2023-05-11 10:26:06.174 xcodebuild[86336:869936] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:3525148D-FF01-44B7-88FD-D8769838BC54, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
{ platform:iOS Simulator, id:3525148D-FF01-44B7-88FD-D8769838BC54, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
Testing failed:
	could not find included file '../../ParentDir/GlobalBuildSettings/Modules/Project.ModuleGlobalBuildSettings.all.xcconfig' in search paths
	could not find included file '../../ParentDir/GlobalBuildSettings/Modules/Target.ModuleTestsGlobalBuildSettings.all.xcconfig' in search paths
	could not find included file '../../ParentDir/GlobalBuildSettings/Modules/Target.ModuleGlobalBuildSettings.debug.xcconfig' in search paths
	Value for SWIFT_VERSION cannot be empty.
	Testing cancelled because the build failed.

** TEST FAILED **

❌ /Users/jc/Desktop/TestIssue/ParentDir/TheModule/project/Configuration/Project.TheModule.all.xcconfig:2:1: [31mcould not find included file '../../ParentDir/GlobalBuildSettings/Modules/Project.ModuleGlobalBuildSettings.all.xcconfig' in search paths[0m
/Users/jc/Desktop/TestIssue/ParentDir/TheModule/project/Configuration/Target.TheModuleTests.all.xcconfig:1:1: error: could not find included file '../../ParentDir/GlobalBuildSettings/Modules/Target.ModuleTestsGlobalBuildSettings.all.xcconfig' in search paths
[36m/Users/jc/Desktop/TestIssue/ParentDir/TheModule/project/Configuration/Project.TheModule.all.xcconfig:2:1: error: could not find included file '../../ParentDir/GlobalBuildSettings/Modules/Project.ModuleGlobalBuildSettings.all.xcconfig' in search paths[0m
❌ /Users/jc/Desktop/TestIssue/ParentDir/TheModule/project/Configuration/Target.TheModule.debug.xcconfig:1:1: [31mcould not find included file '../../ParentDir/GlobalBuildSettings/Modules/Target.ModuleGlobalBuildSettings.debug.xcconfig' in search paths[0m
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'TheModuleTests' from project 'TheModule')
[36merror: Value for SWIFT_VERSION cannot be empty. (in target 'TheModuleTests' from project 'TheModule')[0m
❌ [31merror: Value for SWIFT_VERSION cannot be empty. (in target 'TheModuleTests' from project 'TheModule')[0m
⚠️ [33mTraditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'TheModule' from project 'TheModule')[0m
❌ [31merror: Value for SWIFT_VERSION cannot be empty. (in target 'TheModule' from project 'TheModule')[0m
❌ [31merror: Value for SWIFT_VERSION cannot be empty. (in target 'TheModule' from project 'TheModule')[0m
The 'xcodebuild' command exited with error code 65
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

So the question is, why does the project context created for `test` fail (due to the relative paths)?

Hope you can help

**Comment by danyf90** [comment]
Is the `'../../ParentDir/GlobalBuildSettings/Modules/Project.ModuleGlobalBuildSettings.all.xcconfig' in search paths
` pointing outside of the tuist folder? I think (not sure) it might be a problem.
Probably @fortmarek knows more about `tuist test`

**Comment by itsthejb** [comment]
@danyf90 That's my suspicion, yes. I notice that `tuist test` creates the workspace/project in `.tuist/Cache`, but then links in the project are supposed to link back to the original locations. I suspect we've just picked up an edge case there, or it may just be that we haven't configured the file links in the best way

Note I'll be on holiday the next couple of weeks, but my colleagues can be on hand to respond

**Comment by damirdavletov** [comment]
@itsthejb , @danyf90 I did some digging:

1. xcconfig include statements resolves paths in 2 ways: relative to the xcconfig file and relative to the project (SRCROOT)
2. @itsthejb in your sample include statements use "relative" to the project way and when the project is being copied to cache folder relative paths get broken. I tried to change to the other way i.e. replaced all `../../ParentDir` with `../../../../ParentDir` and `tuist test` command works fine. So as a workaround this can be used.

Having said that it seems a limitation from Tuist to support only one way of relative path resolution in xcconfigs and if possible should be addressed.

**Comment by fortmarek** [comment]
@damirdavletov yes, you are correct, we assume `SRCROOT` will be used if you need reference to local source files. However, I agree it causes confusion – it's not the first time somebody has run into this.

I think the best solution is to change the path for the generated test project from `~/.tuist/Cache` to `.test-cache-MyProject.xcodeproj` and users would put this file into `.gitignore`. The reason we want to generate a different project than the one you work with is that during `tuist test` we strip test schemes that should be skipped but we don't want to change the project you probably have opened.

**Comment by itsthejb** [comment]
Following up on this one: yes, we can workaround the issue and get `tuist test` working with the changes suggested by @damirdavletov

@fortmarek Up to you whether or not you leave this issue open in lieu of the change to generate the test project somewhere closer to the normal location. At least we have enough for our needs right now.

Thanks!
