### ISSUE TITLE
Error installing Tuist

### ISSUE THREAD

**Issue by chinkugoyal** [tuist/tuist#5185]
### What happened?

 tuist fetch

Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
    
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
atharvgoyal@Atharvs-MacBook-Pro sendbird-chat-sample-ios-main-2 % 

### How do we reproduce it?

Download https://github.com/sendbird/sendbird-chat-sample-ios
Try inslling twist to Run app

### Error log

atharvgoyal@Atharvs-MacBook-Pro sendbird-chat-sample-ios-main-2 % tuist fetch

Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
    
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
atharvgoyal@Atharvs-MacBook-Pro sendbird-chat-sample-ios-main-2 % 

### macOS version

13.3.1

### Tuist version

3.0

### Xcode version

14.1

**Comment by danyf90** [comment]
Looks like a problem in some of your configuration as the `/usr/bin/xcrun --sdk macosx --show-sdk-platform-path` is not working, not a tuist issue
