### ISSUE TITLE
Clean tuist cloud cache from command-line

### ISSUE THREAD

**Issue by mohamadrezakoohkan** [tuist/tuist#5191]
### What happened?

# Feature Request
New feature to remove tuist cloud cache on tuist default S3 bucket is amazing, but it is necessary to be able to remove caches using command-line as well, since CI might fail regarding to mismatch cache on a branch and cache on the cloud, it is a manual work to detect that and remove the outdated caches.

therefore something like this is requested:
```bash
tuist clean cloud
```

### How do we reproduce it?

1. Initialize new tuist project
2. Link it to a tuist remote cloud
3. Run tuist cache warm on CI
4. Update libraries in Dependencies.swift
5. Now cache on the CI mismatches with latest changes on the repo

### Error log

unable to build project 

### macOS version

13.3.1

### Tuist version

3.19.0

### Xcode version

14.3

**Comment by fortmarek** [comment]
> Now cache on the CI mismatches with latest changes on the repo

`Dependencies.swift` should be taken into the account for the cache (@danyf90 might be able to confirm). I'd say that's the primary thing we should fix here.

However, I can also see utility in being able to clean the cache from the CLI, so we should fix the bug and provide this new command as part of the `tuist cloud` command.

**Comment by fortmarek** [comment]
@mohamadrezakoohkan can you create a separate issue for the cache mismatch? If you could provide a reproduction sample, that'd be perfect but I understand if that might turn out to be too difficult. The more info, the better, however.

`tuist cloud clean` command will be available in the next release but we should still look into the underlying issue of the mismatch.
