### ISSUE TITLE
Can't build target with external SPM dependency

### ISSUE THREAD

**Issue by iSalahK** [tuist/tuist#5195]
### What happened?

When compiling a target with an external SPM dependency, I got this compilation error:

`./MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/XMPPFramework/Package.swift:2:8: No such module 'PackageDescription'
`
It looks like it's trying to compile the SPM Package.swift file, I don't have this kind of issue with other SPM dependencies.
Package repository: https://github.com/robbiehanson/XMPPFramework.git

### How do we reproduce it?

SampleApp with the error:
https://github.com/tuist/tuist/files/11541267/SampleXmppTuist.zip

1. Add https://github.com/robbiehanson/XMPPFramework.git to Dependencies.swift 
```
let packages: [Package] = [
    .package(url: "https://github.com/robbiehanson/XMPPFramework.git", .exact("4.1.0")),
]
let dependencies = Dependencies(
    swiftPackageManager: .init(packages),
    platforms: [.iOS]
)
```

2. Run `tuist fetch`
3. Create a Tuist Project with a target which has the XMPPFramework  as an external TargetDependency
4. Run `tuist generate`
5. Build your target
6. The compilation fails with "No such module 'PackageDescription'"

### Error log

./MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/XMPPFramework/Package.swift:2:8: No such module 'PackageDescription'

### macOS version

13.3.1

### Tuist version

3.19.0

### Xcode version

14.3

**Comment by danyf90** [comment]
Please provide sample project

**Comment by iSalahK** [comment]
Sure, here is a basic sample app with a SPM dependency to the XMPPFramework.

[SampleXmppTuist.zip](https://github.com/tuist/tuist/files/11541267/SampleXmppTuist.zip)

**Comment by Lilfaen** [comment]
Using `.remote(url: "https://github.com/robbiehanson/XMPPFramework.git", requirement: .exact("4.1.0"))` instead of `.package(url: "https://github.com/robbiehanson/XMPPFramework.git", .exact("4.1.0"))` works for me.

See here: https://tuist.github.io/tuist/main/documentation/projectdescription/dependencies/
The `.package` is used in the SPM package description, i believe, not in tuist: https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#package-dependency

**Comment by iSalahK** [comment]
> Using `.remote(url: "https://github.com/robbiehanson/XMPPFramework.git", requirement: .exact("4.1.0"))` instead of `.package(url: "https://github.com/robbiehanson/XMPPFramework.git", .exact("4.1.0"))` works for me.
> 
> See here: https://tuist.github.io/tuist/main/documentation/projectdescription/dependencies/ The `.package` is used in the SPM package description, i believe, not in tuist: https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#package-dependency

@Lilfaen 
I've updated the dependency with .remote instead of .package and I still have the exact same issue.
Can you share a working sample ?
