### ISSUE TITLE
Turning off `renderMarkdownReadme:` parameter still renders the Reamde in read-only mode instead of edit mode

### ISSUE THREAD

**Issue by Buju77** [tuist/tuist#5196]
### What happened?

See our Slack thread [conversation](https://tuistapp.slack.com/archives/C018QG7U7SN/p1684764786985939?thread_ts=1684492937.382289&cid=C018QG7U7SN) with @kwridan triggering this bug.

The `renderMarkdownReadme: false` flag in `Workspace` was added in this [Issue #4356](https://github.com/tuist/tuist/issues/4356#issuecomment-1094827048).

But there is currently a small bug that the `MyApp.xcworkspace/.xcodesamplecode.plist` file is not deleted when the flag is turned on and off again.

Current workaround:

1. Either manually delete that file and re-open Xcode:

```
rm MyApp.xcworkspace/.xcodesamplecode.plist
open MyApp.xcworkspace
```

2. or to delete the workspace and re-generate it again:

```
rm -rf MyApp.xcworkspace
tuist generate
open MyApp.xcworkspace
```

### How do we reproduce it?

1. Create a `Workspace.swift` file with the flag turned on (or use this [fixture](https://github.com/tuist/tuist/blob/main/projects/tuist/fixtures/ios_app_with_custom_workspace/Workspace.swift)):

```
let workspace = Workspace(name: "MyApp",
                          projects: [
                            "."
                          ],
                          additionalFiles: [
                            "README.md"
                            "Workspace.swift"
                          ],
                          generationOptions: .options(
                            enableAutomaticXcodeSchemes: false,
                            autogeneratedWorkspaceSchemes: .disabled,
                            renderMarkdownReadme: true // turn this on
                          ))
```

2. `tuist generate`
3. `open MyApp.xcworkspace`
4. open `README.md` (Xcode will open it in read-only mode)
5. close Xcode
6. Now edit `Workspace.swift` and turn off the flag:

```
                            renderMarkdownReadme: false // turn this off
```
7. `tuist generate`
8. open workspace and `README.md` again (Xcode still renders in read-only mode)

Now applying workaround:
9. `rm MyApp.xcworkspace/.xcodesamplecode.plist`
10. open workspace and `README.md` again (Xcode finally opens it in edit mode ✅ )

### Error log

Xcode still renders README.md in read-only mode instead of edit mode.

### macOS version

13.3.1

### Tuist version

3.19.0

### Xcode version

14.2

**Comment by danyf90** [comment]
Hi @Buju77, thanks for reporting this 🙏 
It should be easy to fix, just need to change `TuistWorkspaceRenderMarkdownReadmeMapper` to delete the file instead of doing nothing when `renderMarkdownReadme` is false

**Comment by Buju77** [comment]
I've just opened a PR to fix this bug. Any feedback is appreciated 🙏
