### ISSUE TITLE
Why is everything with Tuist so hard?

### ISSUE THREAD

**Issue by 23inhouse** [tuist/tuist#5205]
### What happened?

Nothing works and all the docs require that you already know how everything works.

It's just so painful. Not once has anything just worked.

Have you ever watched someone try to use it?

It should already be used by everyone but the learning curve is so step that no one can use it.

You can start by having working examples for the most common use cases. The docs to use them need to be !!WORKING!! copy and paste commands with !!WORKING!! examples.

### How do we reproduce it?

1. Don't be one of the tuist developers .
2. Try to use Tuist

### Error log

Something very cryptic.

### macOS version

13

### Tuist version

all of them

### Xcode version

doesn't matter

**Comment by dogo** [comment]
Why so many rude comments? Instead you can propose some changes to be more user friendly. But yeah when you is trying to build something technical some technical knowledge is needed. 

Sorry about yor frustration, be kind.

Cya and stay safe

**Comment by danyf90** [comment]
Tuist has plenty of documentation and plenty of sample projects.
If something is wrong or missing, Tuist is also open source, so you could have just opened a PR or asked for support, instead of just complaining as you have done, which is very disrespectful of all the contributors which have dedicated their time to it 🤗

**Comment by 23inhouse** [comment]
I'm sorry I was so rude. I was extremely frustrated but in my defense I will not be the only one and this conversation needs to be had before us plebs will be able to get on board. We want to use it! I think Tuist will be the future of xcode project management but at this point it's impossible to use. 

Right now I'm trying to import a package from github.

1. Google "tuist packages remote"
2. go to: https://docs.tuist.io/guides/third-party-dependencies/
3. follow the instructions including running `tuist fetch`
6. Error: Unexpected argument 'fetch'

This has been my experience with everything I've attempted to do. The only way I've successfully found an actual answer is to search through the issues and look at the code changes to see how to do it.

99% of us plebs will drop off at this point.

I apologise for expressing my frustration in such a rude way. I don't know what to do. Adding a package should be less than a 5 minute job. Preferably a 1 minute copy pasta session.

Thank you for your time.

**Comment by 23inhouse** [comment]
I cloned the repo and searched for "fetch" I found this: `tuist dependencies fetch`

1. `tuist dependencies fetch`
2. Error: Dependencies.swift not found at path /Users/benjamin/git/BikeMap
3. Move the file to the path.
4. confirm the file is there with `ls /Users/benjamin/git/BikeMap/Dependencies.swift`

I searched the repo again for "Dependencies" and see that it needs to be in the `Tuist` folder.

1. Move the file to the `Tuist` folder
2. `tuist dependencies fetch`
3. Error: `Carthage was not found in the environment.`
4. comment out carthage I want to use swift package manager
5. `tuist dependencies fetch`
6. No error 👍 and cancel command.
7. Go to SQLite repo copy the code link: `git@github.com:stephencelis/SQLite.swift.git` set the version "0.14.1"
8. `tuist dependencies fetch`
9. Error: The dependency kind remoteSourceControl is not supported
10. try the https version, try the full url from url bar.
11. Same error
12. Try googling "The dependency kind remoteSourceControl is not supported"
13. Found this: https://stackoverflow.com/questions/73990214/ios-tuist-external-dependency-errors-at-steps-fetch-and-generate -> solution found by looking in the `graph.json`
14. change it to "external" -> same error
15. google tuist graph
16. go to https://docs.tuist.io/commands/graph/
17. From the docs: `tuist graph --format json`
18. Error: The value 'json' is invalid for '--format <format>'

All I want to do is put SQLite in my project so I can do `import "SQLite"`.

Should it be this hard? It's errors all the way down.

**Comment by danyf90** [comment]
Open a ticket with a reproducible project and you'll get all the support you need.
For more interactive support, you can also ask in Slack

**Comment by haifengkao** [comment]
@23inhouse you are not alone. Tuist is very hard to use.
I created a whole plugin to support myself using Tuist.

BTW, ChatGPT knows Tuist. Whenever I have questions, I ask ChatGPT.

**Comment by app-arianamini** [comment]
Bro, after 3h I am at level 13, how can I solve remoteSourceControl error? The funny thing is, I am using the “How to add External Dependencies” from Tuist Docs SAME CODE, SAME Package (Alamofire) is not working.
