### ISSUE TITLE
Allow setting additional Scheme diagnostic cases

### ISSUE THREAD

**Issue by eytanbiala** [tuist/tuist#5212]
### What happened?

Similar to https://github.com/tuist/tuist/pull/1382/files, support enabling/disabling additional diagnostics per scheme:

- Address Sanitizer
- Thread Sanitizer
- Undefined Behavior Sanitizer
- Thread Performance Checker
- Memory management - Malloc scribble, guard edges, guard malloc, zombies, stack logging, graph on resource exception
- Metal API Validation

![image](https://github.com/tuist/tuist/assets/1770794/53c8fe96-318e-4ef6-8b7c-acc2af1a7fa8)

### How do we reproduce it?

Generate a project and see that only the Xcode defaults are set

### Error log

N/A

### macOS version

12

### Tuist version

3

### Xcode version

14

**Comment by eytanbiala** [comment]
Reopening, still seems relevant

**Comment by kkizlaitis** [comment]
This has been closed, but I see that, e.g., there is still no possibility to disable "Metal API Validation". As there are many other options for developers to enable/disable, maybe it would be better to have a possibility to add entries to `.xcscheme` by ourselves?

For example, I personally am missing the "Metal API Validation" option.
