### ISSUE TITLE
Address Xcode Recommended Setting: `Enable Parallelization in Command Line Builds Using -target`

### ISSUE THREAD

**Issue by thedavidharris** [tuist/tuist#5219]
### What happened?

<img width="538" alt="image" src="https://github.com/tuist/tuist/assets/5666250/b215e0d4-b0cc-4059-bb1a-367ce8f0bced">

### How do we reproduce it?

1. Create a modular Tuist project
2. See warning when fixits are set to an older Xcode version

### Error log

<img width="538" alt="image" src="https://github.com/tuist/tuist/assets/5666250/ca879803-8883-43c4-95c9-336bead8acff">

### macOS version

13.4

### Tuist version

3.18

### Xcode version

14.3.

**Comment by thedavidharris** [comment]
Some notes on this at https://github.com/tuist/tuist/discussions/5147

**Comment by danyf90** [comment]
Thanks @thedavidharris, if you are planning to work on this I can assign it to you 🙏 
I think it first requires to add support in XcodeProj

**Comment by kwridan** [comment]
I think all the pieces are in place 🙂

If I followed along, this would add a new project level attribute:

https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift#L280 

The only trick / caveat is if we're happy to default this attribute and bump the object version.

**Comment by thedavidharris** [comment]
> https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Generator/ProjectDescriptorGenerator.swift#L280

It looks like it's a new attribute, but also `SWIFT_ACTIVE_COMPILATION_CONDITIONS` no longer seem to be an array but just a list.
