### ISSUE TITLE
Cuts underscore in Framework name. It leads to the build error during compile time

### ISSUE THREAD

**Issue by LuckyDmitry** [tuist/tuist#5224]
### What happened?

I integrated a library via SPM (Swift Package Manager) from the following GitHub repository: https://github.com/1Flow-Inc/1flow-ios-sdk. However, the generated code is not allowed in Swift for classes to start with a digit, which leads to a compile-time error.

```
@objc
public class 1FlowResources: NSObject {
   @objc public class var bundle: Bundle {
         return .module
   }
}
```

### How do we reproduce it?

1. Use any project
2. Try to add .external dependency
3. tuist fetch && tuist generate 
4. compile project
5. see error

### Error log

F' is not a valid digit in integer literal
Class name can only start with a letter or underscore, not a number

### macOS version

13.3.1

### Tuist version

3.20.0

### Xcode version

14.3

**Comment by navtoj** [comment]
@trifon0v Were you able to find a solution to this? I'm running into the same issue.

**Comment by navtoj** [comment]
> @navtoj could you open a new issue with a reproduction project and steps? Thanks!

Issue: https://github.com/tuist/tuist/issues/7144

Reproduction Project: https://github.com/navtoj/debug/tree/tuist-repro-1
