### ISSUE TITLE
Incorrect TuistBundle code

### ISSUE THREAD

**Issue by dankinsoid** [tuist/tuist#5237]
### What happened?

For a dependency that name starts with _1 tuist generate the code that doesn't compile:
```swift
// MARK: - Objective-C Bundle Accessor

@objc
public class 1FlowResources: NSObject {
   @objc public class var bundle: Bundle {
         return .module
   }
}
// swiftlint:enable all
// swiftformat:enable all
```

### How do we reproduce it?

1. create a tuist project
2. add [1Flow](https://github.com/1Flow-Inc/1flow-ios-sdk) dependency
3. tuist generate

### Error log

Build error

### macOS version

13.4

### Tuist version

3.12.1

### Xcode version

14.3.1

**Comment by dankinsoid** [comment]
Hi! it's really critical

**Comment by danyf90** [comment]
Hi @dankinsoid, thanks for reporting 🙏 
I think the problem is in this method: https://github.com/tuist/tuist/blob/451177d3fc40f0839e11320a0717a7eab43feac4/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift#L77

Feel free to have a look and let us know if you need help 🙏

**Comment by dankinsoid** [comment]
@danyf90 thx, I will make a MR

**Comment by dankinsoid** [comment]
@danyf90 https://github.com/tuist/tuist/pull/5256
