### ISSUE TITLE
Only the API Documentation for the latest version is 404 not found

### ISSUE THREAD

**Issue by kxc-waddlaw** [tuist/tuist#5238]
### What happened?

- https://tuist.github.io/tuist/latest/documentation/projectdescription/project

※ main version is working: https://tuist.github.io/tuist/main/documentation/projectdescription/project/

### How do we reproduce it?

1. Access to https://tuist.github.io/tuist/latest/documentation/projectdescription/project

### Error log

<img width="1512" alt="image" src="https://github.com/tuist/tuist/assets/102013500/00d381ba-5a8d-4053-9bbe-a812ce32d3c5">

### macOS version

N/A

### Tuist version

N/A

### Xcode version

N/A

**Comment by fortmarek** [comment]
You can find the latest docs here: https://docs.tuist.io/documentation/tuist/

This should no longer be an issue. Feel free to open a new issue if you still have difficulties with our docs.
