### ISSUE TITLE
feature request: Allow setting deployment target devices

### ISSUE THREAD

**Issue by parse** [tuist/tuist#526]
**Describe the bug**
It would be great if Tuist supported a way to set the project to only "iPhone" etc. 

**Screenshots**
<img width="866" alt="Screenshot 2019-10-01 08 55 30" src="https://user-images.githubusercontent.com/60202/65941147-a042c300-e42a-11e9-90d9-6d0221c4ba66.png">

**Comment by pepibumur** [comment]
@parse what about something along the lines of:

```swift
let target = Target(name: "MyApp", deploymentTarget: .iOS("12.4", .universal))
```

**Comment by parse** [comment]
> @parse what about something along the lines of:
> 
> ```swift
> let target = Target(name: "MyApp", deploymentTarget: .iOS("12.4", .universal))
> ```

That sounds fantastic!

**Comment by mollyIV** [comment]
Hello 👋 

If you do not mind, I would like to give it a shoot 😊 It feels like a good issue to get familiar with the project architecture and core concepts 👍

**Comment by kwridan** [comment]
`deploymentTarget` looks really nice!

As a suggestion, perhaps:

```swift
struct DeploymentDevice: OptionSet {
    let rawValue: Int

    static let iphone = DeploymentDevice(rawValue: 1 << 0)
    static let ipad = DeploymentDevice(rawValue: 1 << 1)
    static let mac = DeploymentDevice(rawValue: 1 << 2)
   
}
```

Usage:

```swift
let target = Target(name: "MyApp", deploymentTarget: .iOS("12.4", [.iphone, .ipad]))
```

Motivation is that on Xcode 11, there's a third option Mac (Catalyst!)

<img width="628" alt="Screenshot 2019-10-08 at 22 49 28" src="https://user-images.githubusercontent.com/11914919/66436003-ef39bb00-ea1d-11e9-9285-db7dd0ccd3e0.png">

**Comment by pepibumur** [comment]
> If you do not mind, I would like to give it a shoot 😊 It feels like a good issue to get familiar with the project architecture and core concepts 👍

Definitively! Let us know if you need help to get context on any of the project areas.

**Comment by mollyIV** [comment]
Great, thanks for the support. I will create a draft PR and if that's fine for you, will ping you guys there if I have questions (and I am sure some will pop up)  🙇

**Comment by pepibumur** [comment]
Awesome! It's great to see your willingness to improve the project and help other users. Can't wait to see that PR landing 🚀
