### ISSUE TITLE
Generation failing from /usr/bin/security error

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5260]
### Discussed in https://github.com/tuist/tuist/discussions/5259

<div type='discussions-op-text'>

<sup>Originally posted by **roanutil** June 27, 2023</sup>
Suddenly today, when generating my workspace, it fails. I use Tuist for signing certificates and provisioning profiles. Although, nothing changed for any of that. Several CI builds worked fine today.

The relevant part of stdout is below:
```
The '/usr/bin/security' command exited with error code 1 and message:
security: SecKeychainItemImport: The specified item already exists in the keychain.
```

I've tried:
- Restarting my computer
- full clean, fetch, and generate
- Building with previous project versions
- Clearing out all files from the local repo checkout that aren't tracked by version control
- Removing the signing certificates used by this project from Keychain
- Removing all Apple developer certificates from Keychain
- Generating a different project (it works)

I'm not sure what else to do. Any suggestions?
</div>

**Comment by roanutil** [comment]
This was caused by a different version of openssl being used. Once `/usr/bin/openssl` was used it works fine.

**Comment by pepicrft** [comment]
Thanks @roanutil. Which version is the one that we should be using? I'm wondering if we should add a check there.

**Comment by roanutil** [comment]
@pepicrft

As of macOS 13.5.1, the system openssl is 3.3.6.

However, it might be best to specify the system openssl by path in tuist. I would expect that macOS has a version of openssl bundled that should fully work with code signing. I have a branch (https://github.com/roanutil/tuist/tree/fix-openssl-to-use-system-path) with that change. I haven't been able to test it for regressions or if it is fully resilient to the wrong openssl version first in PATH.

**Comment by pepicrft** [comment]
Thanks for the info @roanutil.
Does `/usr/bin/openssl` work for you? If you don't mind opening a PR we can ask some users that are currently running into issues that test against those changes, and if it works for them and our tests pass, I'd say that we put your changes. Users might have installed a different version of openssl via Homebrew, which can happen easily if the tool is a transitive dependency of another package, and they might end up with a setup that doesn't quite work.
