### ISSUE TITLE
inconsistent config

### ISSUE THREAD

**Issue by haifengkao** [tuist/tuist#5268]
### What happened?

Same configuration in Project settings and Target settings generate different values.
If the settings is set in Target
![截圖 2023-07-01 下午7 20 35](https://github.com/tuist/tuist/assets/4080524/ce6b5b16-951f-4bfc-95c1-e2d258296508)

"No common blocks" is "No" for DummyConfig
![截圖 2023-07-01 下午7 14 39](https://github.com/tuist/tuist/assets/4080524/a5ab2d38-01bb-4c96-a55d-8f6e74a3c836)

If the settings is set in Project
![截圖 2023-07-01 下午7 23 54](https://github.com/tuist/tuist/assets/4080524/03beb1b1-43a1-4ac6-be65-2b147daaf1cc)

"No common blocks" is "Yes" for DummyConfig
![截圖 2023-07-01 下午7 25 23](https://github.com/tuist/tuist/assets/4080524/4e1df6e8-ab93-4b2f-a4bd-ba560862620d)

### How do we reproduce it?

1. unzip the attached file [DummyConfigExample.zip](https://github.com/tuist/tuist/files/11925668/DummyConfigExample.zip)
2. tuist generate

### Error log

No common blocks is "No" if the configuration is set in Target's settings 
![截圖 2023-07-01 下午7 14 39](https://github.com/tuist/tuist/assets/4080524/a5ab2d38-01bb-4c96-a55d-8f6e74a3c836)

### macOS version

13.0.1

### Tuist version

3.20.0

### Xcode version

14.3

**Comment by fortmarek** [comment]
If you are still running into this, I'd recommend creating a troubleshooting post at our [forum](https://community.tuist.io/). Thanks for your understanding!
