### ISSUE TITLE
Duplicate local Swift packages can appear in a generated project

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#527]
**Describe the bug**

When two projects depend on the same local Swift package - duplicate entries can appear in the generated projects! 

**To Reproduce**

1. Go to `fixtures/ios_app_with_local_swift_package`
2. Create a directory to host new projects (e.g. `mkdir -p Frameworks/FrameworkA`)
3. Create `FrameworkA` (`tuist init --product framework`)
4. Update the manifest to depend on a package

```swift
// fixtures/ios_app_with_local_swift_package/Frameworks/FrameworkA/Project.swift

import ProjectDescription

let project = Project(
    name: "FrameworkA",
    targets: [
        Target(name: "FrameworkA",
               platform: .iOS,
               product: .framework,
               bundleId: "io.tuist.FrameworkA",
               infoPlist: "Config/FrameworkA-Info.plist",
               sources: "Sources/**",
               dependencies: [
                   .package(path: "../../Packages/PackageA", productName: "LibraryA"),
        ]),
    ]
)
```

5. Update the main project manifest to depend on the Framework project

```swift
// fixtures/ios_app_with_local_swift_package/Project.swift

import ProjectDescription

let project = Project(name: "App",
                      targets: [
                        Target(name: "App",
                               platform: .iOS,
                               product: .app,
                               bundleId: "io.tuist.App",
                               infoPlist: "Support/Info.plist",
                               sources: ["Sources/**"],
                               resources: [
                                       /* Path to resouces can be defined here */
                                       // "Resources/**"
                               ],
                               dependencies: [
                                    .project(target: "FrameworkA", path: "Frameworks/FrameworkA"),
                                    .package(path: "Packages/PackageA", productName: "LibraryA"),
                                    .package(path: "Packages/PackageA", productName: "LibraryB"),
                                ]),
                      // ...
                      ])
```

6. Run `tuist generate` within `fixtures/ios_app_with_local_swift_package`
7. Inspect the generated project
8. Notice there's an invalid duplicate file reference to `PackageA`

**Expected behavior**
There isn't duplicate or invalid file references.

**Screenshots**

<img width="265" alt="Screenshot 2019-10-01 at 19 19 43" src="https://user-images.githubusercontent.com/11914919/65989037-d743c380-e480-11e9-9b45-1616fcaa6e8b.png">

**Desktop (please complete the following information):**

- Version 0.18.1

**Additional context**

I believe #515 resolves this.

**Comment by fortmarek** [comment]
Let me know if #515 fixes it, if not, I can look into it.

**Comment by kwridan** [comment]
Thanks @fortmarek, #515 resolves this. 

I've updated the [ios_app_with_local_swift_package](https://github.com/tuist/tuist/tree/master/fixtures/ios_app_with_local_swift_package) to include another project that references the same package.
