### ISSUE TITLE
Allow customizing the directory where Tuist resolves the Packages

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5279]
### What problem or need do you have?

Some organizations cache the derived data directory across build to speed up workflows. Because Tuist uses a custom directory for the resolution of packages, they are not able to leverage their caching configuration. The workaround that developers are using is changing the global derived data location, but they'd love to be able to specify the directory somehow.

### Potential solution

Expose an API in the configuration manifest where users can customise the behaviour and make sure that the default is sensible. If the current default is not, we should add an issue to ensure this is tackled the next time we are able to release a major version

### macOS version

13.4.1

### Tuist version

3.20.0

### Xcode version

15.0 beta 2

**Comment by fortmarek** [comment]
This should be now possible using the [passthroughSwiftPackageArguments](https://docs.tuist.dev/en/references/project-description/structs/config.installoptions#passthroughswiftpackagemanagerarguments)
