### ISSUE TITLE
Setting a Host Application yo my test target

### ISSUE THREAD

**Issue by asalom** [tuist/tuist#528]
## Need/problem

I need to set a specific Host Application to my Target of type `.unitTests` which tests a Target of type `.framework`.

## Motivation

I have a Target of type `.framework` which makes use of the Keychain. In order to test the Keychain, the tests have to run in a device, they can't run directly on the framework. In other words, there can't be a Keychain without a Simulator or device.

I've tried to change the test target settings with:

```swift
Settings(
  base: [
    "TEST_HOST": "$(BUILT_PRODUCTS_DIR)/HostTarget.app/HostTarget"
  ], 
  configurations: [.debug(name: "Debug"), .release(name: "Release")], 
  defaultSettings: .recommended
)
```

However, this is not enough and it produces the following configuration, where the Host Application is not being set properly.
<img width="986" alt="Screenshot 2019-10-01 at 17 11 46" src="https://user-images.githubusercontent.com/1466079/66030778-5decb500-e502-11e9-996d-a845a2fcfaeb.png">

I've tried to manually change the Host Application from Xcode user interface, and the changes that are applied to the xcodeproj file include setting `TEST_HOST` to `$(BUILT_PRODUCTS_DIR)/HostTarget.app/HostTarget` but also `TestTargetID = E4E2F9AB233E5A0600B3CE9B;` and this I have no idea how to obtain from the `Project.swift` file

## Visual desired outcome
<img width="959" alt="Screenshot 2019-10-01 at 16 53 29" src="https://user-images.githubusercontent.com/1466079/66030656-17975600-e502-11e9-9279-0900ca801fcd.png">

**Comment by kwridan** [comment]
Hi @asalom 

I believe this is already supported 

https://github.com/tuist/tuist/pull/300

The way to get it working is to add the Application targets as a dependency to the unit test target and that should set the appropriate test host. 

We should update the docs to capture this :) 

Hope this helps

**Comment by asalom** [comment]
It worked like a charm, thank you. I will leave my configuration in case someone else faces the same issue.

```swift
let tests = Target(
  name: "CommonTests",
  platform: .iOS,
  product: .unitTests,
  bundleId: "com.vodafone.CommonTests",
  infoPlist: "Tests/Info.plist",
  sources: "Tests/**",
  dependencies: [
    .target(name: "Common"), // product is .framework
    .target(name: "HostTarget") // product is .app
  ]
)
```
