### ISSUE TITLE
Dependencies.swift breaks Snyk scanning

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5280]
### What problem or need do you have?

In words of the user:
> We also use snyk for dependency scanning, but the problem is our dependencies have to be part of the tuist definitions. At the moment we have a script to parse those definitions from the Tuist files and create a Package.swift file which can then be parsed by snyk. This is a bit of a rough edge and it would be great if we could use a standard Package.swift file instead of embedding the definitions within Tuist.

### Potential solution

Because Snyk relies on the existence of a `Package.swift`, I think the best solution is to drop support for Carthage and use the `Package.swift` as the interface to declare external dependencies. This move will also fix dependency updaters like Renovatebot or Dependant that also rely on the existence of a `Package.swift`.

### macOS version

13.4.1

### Tuist version

3.20.0

### Xcode version

15

**Comment by danyf90** [comment]
Tuist already generates a Package.swift, so it would be enough to push it with the code
