### ISSUE TITLE
Compile error when installing Realm via SPM

### ISSUE THREAD

**Issue by elesahich** [tuist/tuist#5283]
### What happened?

I am suffering this error when installing the Realm via SPM and I think this is not my area, so weird something. Here is my Dependencies.Swift file.

```Swift
let dependencies = Dependencies(
  swiftPackageManager: SwiftPackageManagerDependencies(
    [
      .remote(url: "https://github.com/SDWebImage/SDWebImageSwiftUI.git", requirement: .upToNextMajor(from: "2.0.2")),
      .remote(url: "https://github.com/realm/realm-swift", requirement: .upToNextMajor(from: "10.15.0"))      
    ],
    targetSettings: makeTargetSettings()
  )
)

public func makeTargetSettings() -> [String: SettingsDictionary] {
  var settings: [String: SettingsDictionary] = [:]
  let dependencyNames  = ["SDWebImage", "Realm"] 
  dependencyNames.forEach { dependency in
    settings[dependency] = makeBaseSettings()
    
    let testPath = "$(SRCROOT)/**"
    let realmPath = "$(SRCROOT)/../realm-core/src/**"
    
    settings[dependency] = [
      "HEADER_SEARCH_PATHS": "$(inherited) \(testPath) \(realmPath)"
    ]
  }
  
  return settings
}
```

and I met this error: 
![image](https://github.com/tuist/tuist/assets/16400721/af323fc8-22c4-4b18-ad83-003ce668b1ef)
![image](https://github.com/tuist/tuist/assets/16400721/c5c796be-56da-4f18-a817-b16730aa7a66)

### How do we reproduce it?

1. Type Dependencies.swift to your project according above my examples.
2. Link the dependencies to the project you are using.
3. Tuist Fetch
4. Tuist generate
5. Complie it

### Error log

[error.log](https://github.com/tuist/tuist/files/11988800/error.log)

Upload a log file because It was too long for text (2.8MB). Please don't worry, it's definitely just log file and not a suspicious file. But I'm not sure it's going to help with debugging.

### macOS version

13.1 Ventura

### Tuist version

3.12.0

### Xcode version

14.3

**Comment by danyf90** [comment]
As per issue template, provide a reproducible project

**Comment by elesahich** [comment]
[TuistTest.zip](https://github.com/tuist/tuist/files/11994239/TuistTest.zip)
Hi @danyf90 , Here is the project. thanks for your support.

**Comment by fortmarek** [comment]
Compiling Realm via the Tuist integration should work now, feel free to reopen if that's not the case for you.
