### ISSUE TITLE
Tuist fails to resolve existing path when both framework and resources are fetched from

### ISSUE THREAD

**Issue by danibachar** [tuist/tuist#5286]
### What happened?

First, here is a link to a repository with an example project, and a very detailed README file on what the issue is and how to reproduce it using the example project.

I have GoogleMaps xcframework copied in my project lets say I have put it in the root folder under a subfolder called `libs`.
I'm adding the xcframework to the app dependencies as follow
```
.xcframework(path: "libs/Google/GoogleMaps/GoogleMaps-6.0.1-beta/GoogleMaps.xcframework"),
```

This xcframework also contains a bundle that I need to copy into my app (don't ask why but that is the fact)

So, I'm adding the bundle as a resource to the app resources as follow:
```
resources: [
"Targets/\(name)/Resources/**",
.glob(pattern: "libs/Google/GoogleMaps/GoogleMaps-6.0.1-beta/GoogleMaps.xcframework/ios-arm64/GoogleMaps.framework/Resources/GoogleMaps.bundle"),
]
```

When I run `tuist generate` I get the following error for the resource stage
```
Couldn't find a reference for the file at path /Users/danielbac/Documents/TuistLongGoogleMapResources/libs/Google/GoogleMaps/GoogleMaps-6.0.1-beta/GoogleMaps.xcframework.

```

### How do we reproduce it?

1) Use the example project [here](https://github.com/danibachar/TuistLongGoogleMapResources)
2) Follow the Readme file
3) For a TL;DR reproduce
3.1) Change line 62 in `Tuist/ProjectDescriptionHelpers/Project+Templates` to fetch the resources from the libs folder - `.glob(pattern: "libs/Google/GoogleMaps/GoogleMaps-6.0.1-beta/GoogleMaps.xcframework/ios-arm64/GoogleMaps.framework/Resources/GoogleMaps.bundle"),`

### Error log

Couldn't find a reference for the file at path /Users/danielbac/Documents/TuistLongGoogleMapResources/libs/Google/GoogleMaps/GoogleMaps-6.0.1-beta/GoogleMaps.xcframework.

### macOS version

Ventura 13.4 (22F66)

### Tuist version

3.18.0

### Xcode version

14.3 (14E222b)

**Comment by kwridan** [comment]
Thanks for flagging this @danibachar 

This is a known limitation 😞 - https://github.com/tuist/tuist/issues/1779 has some notes on possible solutions in the interim.

**Comment by danibachar** [comment]
Oh I missed that issue - thanks for pointing to it @kwridan
