### ISSUE TITLE
SWIFT_PACKAGE not defined when using SPM in Dependencies.swift

### ISSUE THREAD

**Issue by stephanecopin** [tuist/tuist#5294]
### What problem or need do you have?

Some SPM dependency rely on the `SWIFT_PACKAGE` compiler condition and do things differently when defined (e.g. the [Stripe SDK](https://github.com/stripe/stripe-ios/blob/master/StripeCore/StripeCore/Source/Helpers/BundleLocatorProtocol.swift#L46-L48)).

This may result in inconsistencies or crashes (e.g. if `SWIFT_PACKAGE` is not defined in the case of Stripe, the bundle is not located properly and some `assert` result in a crash when in unit testing context).

### Potential solution

There is 2 solutions that I can think of, one that the user of Tuist can do, and one that Tuist could implement directly.

As the user, when defining SPM dependencies, I could specify `SWIFT_PACKAGE` as a settings to the `baseSettings` parameter:
```swift
let dependencies = Dependencies(
    swiftPackageManager: SwiftPackageManagerDependencies(
        [
            /* ... */
        ]
        baseSettings: .settings(base: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": .string("${inherited} SWIFT_PACKAGE")])
    ),
    platforms: [/* ... */]
)
```

Or we could make the change in Tuist, I can think of 2 ways:
1. When a `SwiftPackageManagerDependencies`, we pre-populate `baseSettings` with `["SWIFT_ACTIVE_COMPILATION_CONDITIONS": .string("${inherited} SWIFT_PACKAGE")]`
2. Add a `Bool` parameter indicating whether or not this compiler condition should be included or not
Let me know if you think there's is an alternative solution.

If it's decided modifying Tuist to handle this use case is the best solution, I can make the necessary changes and create a PR.

### macOS version

13.3.1

### Tuist version

3.19.0

### Xcode version

14.2

**Comment by danyf90** [comment]
I think it was already intended to be added automatically, maybe we are doing something wron? 🤔 

https://github.com/tuist/tuist/blob/17af2d3686f6115ab3661d12928df93dfcff838f/Sources/TuistDependencies/SwiftPackageManager/Utils/PackageInfoMapper.swift#L828-L829

**Comment by fortmarek** [comment]
Afaik, this is now automatically added, feel free to reopen if not.
