### ISSUE TITLE
When Cartfile.resolved exists, tuist up fails 

### ISSUE THREAD

**Issue by parse** [tuist/tuist#530]
**Describe the bug**
When `Cartfile.resolved` exists, and I try to run `tuist up` I get the following output:
```
➜  tuist-mo git:(parse/carthage) tuist up
Using bundled version at path /Users/parse/prog/tuist-mo/.tuist-bin
Configuring Carthage update
Error: Command exited with error code 1 and error:
```

(No further error is outputed).

The file content for Cartfile.resolved is: 
```
github "Alamofire/Alamofire" "5.0.0-rc.2"	
github "AliSoftware/Dip" "7.0.1"	
github "Quick/Nimble" "v8.0.4"	
github "Quick/Quick" "v2.2.0"	
github "ReSwift/ReSwift" "5.0.0"	
github "ReactiveX/RxSwift" "5.0.1"
```

It only works the first time around, when there is no `Cartfile.resolved` file.

My Setup.swift
```
import ProjectDescription

let setup = Setup([
    .homebrew(packages: ["swiftlint", "swiftgen", "carthage"]),
    .carthage(platforms: [.iOS])
])

```
**To Reproduce**

1. Create a Cartfile with a dependency
2. Run `tuist up`, cartfile.resolved will be generated
3. Run `tuist up` again, will fail.

**Expected behavior**
I expect it to use the resolved values

**Desktop (please complete the following information):**

- OS: macOSX (10.14.5 (18F132))
- Version: 0.18.0

**Comment by pepibumur** [comment]
Thanks for reporting it @parse. From your description, it seems there's a bug in that up task. We'll investigate it further and fix it.

**Comment by c0diq** [comment]
Now it works but it seems to always do a `carthage update` and not honor the cartfile.resolved.

**Comment by softmaxsg** [comment]
> Now it works but it seems to always do a `carthage update` and not honor the cartfile.resolved.

This issue is addressed within https://github.com/tuist/tuist/pull/1744.

**Comment by fortmarek** [comment]
I believe we can close this issue now, we can reopen it if necessary
