### ISSUE TITLE
Tuist Cloud is down

### ISSUE THREAD

**Issue by mohamadrezakoohkan** [tuist/tuist#5323]
### What problem or need do you have?

Since this morning we are suffering from broken tuist remote cache on our CI, while we investigated possible issues, we identified that tuist cloud dashboard is down. 

After we try to login into https://cloud.tuist.io/ we land on a blank page 

<img width="1512" alt="Screenshot 2023-08-03 at 10 51 52" src="https://github.com/tuist/tuist/assets/37219076/b81e2e9d-05ef-4091-a00f-0b081cfa4d04">

### Potential solution

No solution yet!

### macOS version

13.4.1

### Tuist version

3.12.0

### Xcode version

14.3

**Comment by fortmarek** [comment]
This has been fixed, sorry for the issue 🙇‍♂️ 

Feel free to reopen if you run into this again.
