### ISSUE TITLE
Could not find template default

### ISSUE THREAD

**Issue by protodimbo** [tuist/tuist#5341]
### What problem or need do you have?

I'm following this instruction https://docs.tuist.io/tutorial/get-started. After installing tuist with curl -Ls https://install.tuist.io | bash. I created new folder and run tuist init --platform ios and i get this error 
Could not find template default. Make sure it exists at Tuist/Templates/default
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

13.4

### Tuist version

3.6.0

### Xcode version

14.3.1

**Comment by danyf90** [comment]
Just tried and can't replicate. Could you please post the full command and output?

**Comment by protodimbo** [comment]
@danyf90  yeah, sure 
![Uploading image.png…]()

**Comment by danyf90** [comment]
Can't replicate on latest (`3.22.0`), let me know if you do

**Comment by protodimbo** [comment]
yeah, I still can replicate the issue and also i created Project file myself, and after tuist generate i get this error

Resolved cache profile 'Development' from Tuist's defaults
The 'swift' command exited with error code 1 and message:
/Users/me/Developer/MyApp/Project.swift:1:8: error: no such module 'ProjectDescription'
import ProjectDescription
       ^

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

**Comment by protodimbo** [comment]
And also i can't unistall tuist by the tutorial -

curl -Ls https://raw.githubusercontent.com/tuist/tuist/main/script/uninstall | bash
usage: rm [-f | -i] [-dIPRrvWx] file ...
       unlink [--] file

**Comment by protodimbo** [comment]
I fixed it. Just removed it and install again
