### ISSUE TITLE
Need to set CFBundleShortVersionString and CFBundleVersion after tuist generate

### ISSUE THREAD

**Issue by protodimbo** [tuist/tuist#5345]
### What problem or need do you have?

tuist generate resets App version and Build number for my project. How can I set them? Can't find info in documentation

my Project.swift file:
import ProjectDescription

let projectVersion = "1.5.0"
let buildVersion = "12"

let appTargetDebugConfiguration = Configuration.debug(name: "Debug", xcconfig: .relativeToRoot("Configuration/AppTarget/App.debug.xcconfig"))

let appTargetReleaseConfiguration = Configuration.release(name: "Release", xcconfig: .relativeToRoot("Configuration/AppTarget/App.release.xcconfig"))

let appTarget = Target(
    name: "App",
    platform: .iOS,
    product: .app,
    bundleId: "bla.bla.bla",
    deploymentTarget: .iOS(targetVersion: "14.0", devices: .iphone),
    infoPlist: "Resources/Info.plist",
    sources: [
        "App/**"
    ],
    resources: [
        "Resources/**
    ],
    dependencies: [],
    settings: .settings(configurations: [appTargetDebugConfiguration, appTargetReleaseConfiguration])
)

let project = Project(
    name: "App",
    targets: [
        AppTarget
    ]
)

### macOS version

13.4

### Tuist version

3.22.0

### Xcode version

14.3.1

**Comment by danyf90** [comment]
As you said, you need to set `CFBundleShortVersionString` and `CFBundleVersion` in the Info.plist :)

**Comment by protodimbo** [comment]
I've set them already -
<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>

Can I somehow set them from Project.swift to specific versions? Or I should always set them in info.plist?

**Comment by danyf90** [comment]
You can defined the Info.plist in Project.swift instead of providing a file.
As an alternative I think it should be possible to also use settings instead of Plist, but I can't remember the setting name

**Comment by dogo** [comment]
You need to set the project settings

```swift
let settings = SettingsDictionary()
            .currentProjectVersion("1")
            .marketingVersion("1.0.0")
```
