### ISSUE TITLE
Remove "en" locale from a project

### ISSUE THREAD

**Issue by ALexanderLonsky** [tuist/tuist#5355]
### What happened?

Currently, my project supports multiple localizations. However, I've received a requirement to remove the `English` localization. Even if I delete the `en.lproj` from the resources folder, the generated project still retains `English` as the default localization with `0 files localized`

How can I remove `English` from the project and set another locale as the default?

### How do we reproduce it?

1. remove `en.lproj` from `Resources/Localizations` and keep `uk.lproj`
2. tuist generate
3. the generated project still retains `English` as the default localization  with `0 files localized`

### Error log

no errors

### macOS version

13.4.1

### Tuist version

3.17.0

### Xcode version

14.3

**Comment by leszko11** [comment]
Hey @ALexanderLonsky 👋 
You can try setting [developmentRegion](https://tuist.github.io/tuist/main/documentation/projectdescription/project/options-swift.struct/developmentregion) in Project options and update Tuist to `3.28.0` where #4627 was fixed
