### ISSUE TITLE
No support for simulated locations on scheme's test action configuration

### ISSUE THREAD

**Issue by lchinigioli** [tuist/tuist#5375]
### What problem or need do you have?

I've noticed that there's currently no support for adding a simulated location to a Scheme's test action. While I'm aware of efforts made regarding simulated locations, it appears to be applicable only to Run Actions. The ability to simulate locations within test schemes is crucial – particularly for running UI Tests.

## Screenshot
![Screenshot 2023-08-23 at 12 31 12](https://github.com/tuist/tuist/assets/134450042/ab06afc2-5dcf-49d0-94c4-38f1719b5750)

## Related links
https://github.com/tuist/tuist/pull/2616

### macOS version

13.4

### Tuist version

tuist-3.18-bitrise-35f4f87

### Xcode version

14.3.1

**Comment by woin2ee** [comment]
I'll try it :)
