### ISSUE TITLE
Having a ".bundle" file in resources can lead to generation errors

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#539]
_(This was reported on slack by @asalom)_

**Describe the bug**
In the event there's a `.bundle` file in resources (e.g. Settings.bundle), depending on how the resources are defined in the manifest a generation error can occur.

**To Reproduce**

1. Create a new project `tuist init`
2. Create a new bundle resource (e.g. Settings.bundle) - or fake one from the command line:

```
mkdir -p Resources/MyBundle.bundle
touch Resources/MyBundle.bundle/MyBundleAsset.png
```

3. Update the project manifest to contain a more eager glob pattern

```swift
Target(
    name: "App",
    // ...
    resources: [
        "Resources/**",
    ],
    // ...
)
```
4. Run `tuist generate`
5. The following error is obtained:

```
$ tuist generate
Generating workspace MainApp.xcworkspace
Generating project MainApp
Error: Trying to add a file at path /tmp/tuist/fixtures/ios_app_with_framework_and_resources/App/Resources/MyBundle.bundle to a build phase that hasn't been added to the project.
```

**Expected behavior**
The project generates successfully.

**Desktop (please complete the following information):**
- Version 0.18.1

**Additional context**

Did a bit of digging into this :)

The error only occurs when there's a very broad / eager glob pattern. 

Having a manifest which explicitly lists the `.bundle` doesn't suffer from this issue, 

e.g.

```swift
Target(
    name: "App",
    // ...
    resources: [
        "Resources/MyBundle.bundle",
    ],
    // ...
)
```

I believe this is due to the eager resources evaluating to:

```
[
"Resources/MyBundle.bundle/MyBundleAsset.png",
"Resources/MyBundle.bundle",
"Resources",
]
```

Usually directories are filtered out, however there's some logic to include files within known folder extensions as a resources (`.bundle` is one them) (see [Target.swift](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Models/Target.swift#L116))

So we are filtered down to:

```
[
"Resources/MyBundle.bundle/MyBundleAsset.png",
"Resources/MyBundle.bundle",
]
```

- `ProjectFileElements` will generate an element for `Resources/MyBundle.bundle/MyBundleAsset.png`
  - i.e. Group `Resources`, Group `MyBundle.bundle`, Element `MyBundleAsset.png`
- When `Resources/MyBundle.bundle` is processed next, it is skipped due to the existence of Group `MyBundle.bundle`
- And lastly in `BuildPhaseGenerator` - it attempts to add all the resource files (including `MyBundle.bundle`) - at this point the failure occurs as there is no file element for `MyBundle.bundle`!

We'll need to find a way to filter the resources list in the beginning such that it reduces to:

```
[
"Resources/MyBundle.bundle",
]
```

We'll need to ignore any nested files within any of those known folders. We currently have some similar logic for `.xcassets` but it's split between `Target`, `ProjectFileElements` and `BuildPhaseGenerator` - I wonder if we can simplify by doing the filtering upfront - that said `.lproj` folders are slightly more complicated :( 

Related issues:

https://github.com/tuist/tuist/issues/322
https://github.com/tuist/tuist/issues/330
https://github.com/tuist/tuist/issues/352
https://github.com/tuist/tuist/issues/345
https://github.com/tuist/tuist/issues/361

**Comment by asalom** [comment]
I did have a very broad glob pattern which defined my sources and resources: 

```swift
sources: [
   "Sources/**"
  ]
resources: [
  "Sources/Resources/**"
]
```

As @kwridan pointed out to me in Slack, moving the `.bundle` files to a dedicated directory as a workaround fix the issue:

```swift
sources: [
   "Sources/**"
  ]
resources: [
  "Sources/Resources/**",
  "Sources/Bundles/*.bundle"
]
```

**Comment by jsorge** [comment]
I just ran into this myself and can confirm that it's still an issue.

**Comment by artyom-stv** [comment]
Same issue with Tuist 4.36.0:
```
[Shell] Trying to add a file at path /<project-path>/Resources/GoogleMaps.bundle/GMSCoreResources.bundle to a build phase that hasn't been added to the project.
```

The solution from @asalom fixed the issue.
