### ISSUE TITLE
tuist cache warm with --xcframeworks flag broke after Tuist 3.22.0

### ISSUE THREAD

**Issue by kramo7a** [tuist/tuist#5397]
### What happened?

`tuist cache warm --xcframeworks` flag is trying to build for mac catalyst and crashing in version 3.25.0.
But mac catalyst does not even contained in destinations.
Flags `SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD`, `SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD`, `SUPPORTS_MACCATALYST` are set to `NO`

Deployment target is set to iphones only:
`deploymentTarget: .iOS(targetVersion: "15.0", devices: .iphone, supportsMacDesignedForIOS: false)`

```
tuist cache warm with --xcframeworks --verbose
***
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild archive -scheme ProjectCache-Binaries-iOS -workspace /CacheTest/Project.xcworkspace -archivePath /var/folders/p4/chth4cwx4895cvb7mx2ydp3c0000gn/T/TemporaryDirectory.kwsaOJ/macCatalyst.xcarchive SKIP_INSTALL=NO -destination "platform=macOS,variant=Mac Catalyst" -configuration Debug
xcodebuild: error: Unable to find a destination matching the provided destination specifier: { platform:macOS, variant:Mac Catalyst }
***
```

Example project:
[CacheTest.zip](https://github.com/tuist/tuist/files/12521361/CacheTest.zip)

In 3.22.0 works fine

### How do we reproduce it?

1. Use the attached project
2. Run `tuist fetch`
3. Run `tuist cache warm --xcframeworks`

### Error log
<details><summary>tuist cache warm --xcframeworks</summary>
<p>

> Resolved cache profile 'Development' from Tuist's defaults
> Generating workspace Project.xcworkspace
> Generating project Project
> Generating project Differ
> Hashing cacheable targets
> Targets to be cached: Differ
> Generating workspace Project.xcworkspace
> Generating project Differ
> Building cacheable targets
> 2023-09-05 12:06:08.064 xcodebuild[32000:20643876] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
> { platform:iOS Simulator, id:C3CBB6A4-1F2B-4E1B-8694-051004E5E729, OS:16.4, name:iPad (10th generation) }
> { platform:iOS Simulator, id:C3CBB6A4-1F2B-4E1B-8694-051004E5E729, OS:16.4, name:iPad (10th generation) }
> { platform:iOS Simulator, id:4AB755EF-8130-4DA8-A61C-BE7AA57808E5, OS:17.0, name:iPad (10th generation) }
> { platform:iOS Simulator, id:4AB755EF-8130-4DA8-A61C-BE7AA57808E5, OS:17.0, name:iPad (10th generation) }
> { platform:iOS Simulator, id:1998B448-E622-45E3-B270-92DE63D962A7, OS:16.4, name:iPad Air (5th generation) }
> { platform:iOS Simulator, id:1998B448-E622-45E3-B270-92DE63D962A7, OS:16.4, name:iPad Air (5th generation) }
> { platform:iOS Simulator, id:FB214EF2-D98C-491E-9A86-5D2334694C3D, OS:17.0, name:iPad Air (5th generation) }
> { platform:iOS Simulator, id:FB214EF2-D98C-491E-9A86-5D2334694C3D, OS:17.0, name:iPad Air (5th generation) }
> { platform:iOS Simulator, id:EE1C3960-8872-4FF2-A715-57E9D48F165D, OS:16.4, name:iPad Pro (11-inch) (4th generation) }
> { platform:iOS Simulator, id:EE1C3960-8872-4FF2-A715-57E9D48F165D, OS:16.4, name:iPad Pro (11-inch) (4th generation) }
> { platform:iOS Simulator, id:F154103C-424B-493F-93E0-CA8233EEEAC5, OS:17.0, name:iPad Pro (11-inch) (4th generation) }
> { platform:iOS Simulator, id:F154103C-424B-493F-93E0-CA8233EEEAC5, OS:17.0, name:iPad Pro (11-inch) (4th generation) }
> { platform:iOS Simulator, id:EF301C7C-2D79-4FCE-9E0F-3D9A3CCA33ED, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
> { platform:iOS Simulator, id:EF301C7C-2D79-4FCE-9E0F-3D9A3CCA33ED, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
> { platform:iOS Simulator, id:9AC04BD3-CCA2-4DD6-8338-63CF9DD0E8F1, OS:17.0, name:iPad Pro (12.9-inch) (6th generation) }
> { platform:iOS Simulator, id:9AC04BD3-CCA2-4DD6-8338-63CF9DD0E8F1, OS:17.0, name:iPad Pro (12.9-inch) (6th generation) }
> { platform:iOS Simulator, id:27262545-F206-41E0-B9C3-3FA7E2E60EFB, OS:16.4, name:iPad mini (6th generation) }
> { platform:iOS Simulator, id:27262545-F206-41E0-B9C3-3FA7E2E60EFB, OS:16.4, name:iPad mini (6th generation) }
> { platform:iOS Simulator, id:E8BA9D7F-C429-407D-B357-501C970CF918, OS:17.0, name:iPad mini (6th generation) }
> { platform:iOS Simulator, id:E8BA9D7F-C429-407D-B357-501C970CF918, OS:17.0, name:iPad mini (6th generation) }
> { platform:iOS Simulator, id:83C31901-5A42-4B83-8AC2-40E67E2B358E, OS:16.4, name:iPhone 14 }
> { platform:iOS Simulator, id:83C31901-5A42-4B83-8AC2-40E67E2B358E, OS:16.4, name:iPhone 14 }
> { platform:iOS Simulator, id:E2936586-518A-47D1-B8DD-DFD9F58BE83B, OS:17.0, name:iPhone 14 }
> { platform:iOS Simulator, id:E2936586-518A-47D1-B8DD-DFD9F58BE83B, OS:17.0, name:iPhone 14 }
> { platform:iOS Simulator, id:C4829BBF-524F-411B-B71E-096C816B55CF, OS:16.4, name:iPhone 14 Plus }
> { platform:iOS Simulator, id:C4829BBF-524F-411B-B71E-096C816B55CF, OS:16.4, name:iPhone 14 Plus }
> { platform:iOS Simulator, id:22F86025-76FA-4185-9CB1-DF9BF03DC687, OS:17.0, name:iPhone 14 Plus }
> { platform:iOS Simulator, id:22F86025-76FA-4185-9CB1-DF9BF03DC687, OS:17.0, name:iPhone 14 Plus }
> { platform:iOS Simulator, id:9BD91FDC-CDE8-4380-92E7-C685566663D8, OS:16.4, name:iPhone 14 Pro }
> { platform:iOS Simulator, id:9BD91FDC-CDE8-4380-92E7-C685566663D8, OS:16.4, name:iPhone 14 Pro }
> { platform:iOS Simulator, id:D3857B6C-5B91-447C-B3B1-8235F9D8D849, OS:17.0, name:iPhone 14 Pro }
> { platform:iOS Simulator, id:D3857B6C-5B91-447C-B3B1-8235F9D8D849, OS:17.0, name:iPhone 14 Pro }
> { platform:iOS Simulator, id:63AA52C0-68C3-438A-AECF-9389683AA186, OS:16.4, name:iPhone 14 Pro Max }
> { platform:iOS Simulator, id:63AA52C0-68C3-438A-AECF-9389683AA186, OS:16.4, name:iPhone 14 Pro Max }
> { platform:iOS Simulator, id:429DEE49-C21A-432F-8270-6AA3C1B46435, OS:17.0, name:iPhone 14 Pro Max }
> { platform:iOS Simulator, id:429DEE49-C21A-432F-8270-6AA3C1B46435, OS:17.0, name:iPhone 14 Pro Max }
> { platform:iOS Simulator, id:F24BF835-4045-40F9-ACA0-E2E5FEEE53DC, OS:16.4, name:iPhone SE (3rd generation) }
> { platform:iOS Simulator, id:F24BF835-4045-40F9-ACA0-E2E5FEEE53DC, OS:16.4, name:iPhone SE (3rd generation) }
> { platform:iOS Simulator, id:ABA13E8D-0AC1-42CD-8BDF-E4FB213A4190, OS:17.0, name:iPhone SE (3rd generation) }
> { platform:iOS Simulator, id:ABA13E8D-0AC1-42CD-8BDF-E4FB213A4190, OS:17.0, name:iPhone SE (3rd generation) }
> { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
> [Differ] Processing Differ-Info.plist
> [Differ] Compiling Differ_vers.c
> [Differ] Compiling Differ_vers.c
> [Differ] Building library Differ
> [Differ] Building library Differ
> Signing Differ.framework (in target 'Differ' from project 'Differ')
> [Differ] Touching Differ.framework
> Archive Succeeded
> 2023-09-05 12:06:10.300 xcodebuild[32054:20644079] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
> 2023-09-05 12:06:10.409 xcodebuild[32054:20644079] Writing error result bundle to /var/folders/p4/chth4cwx4895cvb7mx2ydp3c0000gn/T/ResultBundle_2023-05-09_12-06-0010.xcresult
> xcodebuild: error: Unable to find a destination matching the provided destination specifier:
> 		{ platform:macOS, variant:Mac Catalyst }
> 
> 	Available destinations for the "ProjectCache-Binaries-iOS" scheme:
> 		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
> 		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
> 		{ platform:iOS Simulator, id:C3CBB6A4-1F2B-4E1B-8694-051004E5E729, OS:16.4, name:iPad (10th generation) }
> 		{ platform:iOS Simulator, id:C3CBB6A4-1F2B-4E1B-8694-051004E5E729, OS:16.4, name:iPad (10th generation) }
> 		{ platform:iOS Simulator, id:4AB755EF-8130-4DA8-A61C-BE7AA57808E5, OS:17.0, name:iPad (10th generation) }
> 		{ platform:iOS Simulator, id:4AB755EF-8130-4DA8-A61C-BE7AA57808E5, OS:17.0, name:iPad (10th generation) }
> 		{ platform:iOS Simulator, id:1998B448-E622-45E3-B270-92DE63D962A7, OS:16.4, name:iPad Air (5th generation) }
> 		{ platform:iOS Simulator, id:1998B448-E622-45E3-B270-92DE63D962A7, OS:16.4, name:iPad Air (5th generation) }
> 		{ platform:iOS Simulator, id:FB214EF2-D98C-491E-9A86-5D2334694C3D, OS:17.0, name:iPad Air (5th generation) }
> 		{ platform:iOS Simulator, id:FB214EF2-D98C-491E-9A86-5D2334694C3D, OS:17.0, name:iPad Air (5th generation) }
> 		{ platform:iOS Simulator, id:EE1C3960-8872-4FF2-A715-57E9D48F165D, OS:16.4, name:iPad Pro (11-inch) (4th generation) }
> 		{ platform:iOS Simulator, id:EE1C3960-8872-4FF2-A715-57E9D48F165D, OS:16.4, name:iPad Pro (11-inch) (4th generation) }
> 		{ platform:iOS Simulator, id:F154103C-424B-493F-93E0-CA8233EEEAC5, OS:17.0, name:iPad Pro (11-inch) (4th generation) }
> 		{ platform:iOS Simulator, id:F154103C-424B-493F-93E0-CA8233EEEAC5, OS:17.0, name:iPad Pro (11-inch) (4th generation) }
> 		{ platform:iOS Simulator, id:EF301C7C-2D79-4FCE-9E0F-3D9A3CCA33ED, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
> 		{ platform:iOS Simulator, id:EF301C7C-2D79-4FCE-9E0F-3D9A3CCA33ED, OS:16.4, name:iPad Pro (12.9-inch) (6th generation) }
> 		{ platform:iOS Simulator, id:9AC04BD3-CCA2-4DD6-8338-63CF9DD0E8F1, OS:17.0, name:iPad Pro (12.9-inch) (6th generation) }
> 		{ platform:iOS Simulator, id:9AC04BD3-CCA2-4DD6-8338-63CF9DD0E8F1, OS:17.0, name:iPad Pro (12.9-inch) (6th generation) }
> 		{ platform:iOS Simulator, id:27262545-F206-41E0-B9C3-3FA7E2E60EFB, OS:16.4, name:iPad mini (6th generation) }
> 		{ platform:iOS Simulator, id:27262545-F206-41E0-B9C3-3FA7E2E60EFB, OS:16.4, name:iPad mini (6th generation) }
> 		{ platform:iOS Simulator, id:E8BA9D7F-C429-407D-B357-501C970CF918, OS:17.0, name:iPad mini (6th generation) }
> 		{ platform:iOS Simulator, id:E8BA9D7F-C429-407D-B357-501C970CF918, OS:17.0, name:iPad mini (6th generation) }
> 		{ platform:iOS Simulator, id:83C31901-5A42-4B83-8AC2-40E67E2B358E, OS:16.4, name:iPhone 14 }
> 		{ platform:iOS Simulator, id:83C31901-5A42-4B83-8AC2-40E67E2B358E, OS:16.4, name:iPhone 14 }
> 		{ platform:iOS Simulator, id:E2936586-518A-47D1-B8DD-DFD9F58BE83B, OS:17.0, name:iPhone 14 }
> 		{ platform:iOS Simulator, id:E2936586-518A-47D1-B8DD-DFD9F58BE83B, OS:17.0, name:iPhone 14 }
> 		{ platform:iOS Simulator, id:C4829BBF-524F-411B-B71E-096C816B55CF, OS:16.4, name:iPhone 14 Plus }
> 		{ platform:iOS Simulator, id:C4829BBF-524F-411B-B71E-096C816B55CF, OS:16.4, name:iPhone 14 Plus }
> 		{ platform:iOS Simulator, id:22F86025-76FA-4185-9CB1-DF9BF03DC687, OS:17.0, name:iPhone 14 Plus }
> 		{ platform:iOS Simulator, id:22F86025-76FA-4185-9CB1-DF9BF03DC687, OS:17.0, name:iPhone 14 Plus }
> 		{ platform:iOS Simulator, id:9BD91FDC-CDE8-4380-92E7-C685566663D8, OS:16.4, name:iPhone 14 Pro }
> 		{ platform:iOS Simulator, id:9BD91FDC-CDE8-4380-92E7-C685566663D8, OS:16.4, name:iPhone 14 Pro }
> 		{ platform:iOS Simulator, id:D3857B6C-5B91-447C-B3B1-8235F9D8D849, OS:17.0, name:iPhone 14 Pro }
> 		{ platform:iOS Simulator, id:D3857B6C-5B91-447C-B3B1-8235F9D8D849, OS:17.0, name:iPhone 14 Pro }
> 		{ platform:iOS Simulator, id:63AA52C0-68C3-438A-AECF-9389683AA186, OS:16.4, name:iPhone 14 Pro Max }
> 		{ platform:iOS Simulator, id:63AA52C0-68C3-438A-AECF-9389683AA186, OS:16.4, name:iPhone 14 Pro Max }
> 		{ platform:iOS Simulator, id:429DEE49-C21A-432F-8270-6AA3C1B46435, OS:17.0, name:iPhone 14 Pro Max }
> 		{ platform:iOS Simulator, id:429DEE49-C21A-432F-8270-6AA3C1B46435, OS:17.0, name:iPhone 14 Pro Max }
> 		{ platform:iOS Simulator, id:F24BF835-4045-40F9-ACA0-E2E5FEEE53DC, OS:16.4, name:iPhone SE (3rd generation) }
> 		{ platform:iOS Simulator, id:F24BF835-4045-40F9-ACA0-E2E5FEEE53DC, OS:16.4, name:iPhone SE (3rd generation) }
> 		{ platform:iOS Simulator, id:ABA13E8D-0AC1-42CD-8BDF-E4FB213A4190, OS:17.0, name:iPhone SE (3rd generation) }
> 		{ platform:iOS Simulator, id:ABA13E8D-0AC1-42CD-8BDF-E4FB213A4190, OS:17.0, name:iPhone SE (3rd generation) }
> The 'xcodebuild' command exited with error code 70
> Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
</p>
</details> 

### macOS version

13.4.1

### Tuist version

3.25.0

### Xcode version

14.3.1

**Comment by pepicrft** [comment]
@kramo7a do you mind testing the latest Tuist version, 3.26.0? We shipped a fix for this issue.

**Comment by fortmarek** [comment]
This should be fixed now, let us know if you run into this again.
