### ISSUE TITLE
TOCropViewController - compile error manual fix

### ISSUE THREAD

**Issue by tackgyu** [tuist/tuist#5400]
### What problem or need do you have?

From: #4606 

I recently managed to fix the compilation error linking [TOCropViewController](https://github.com/TimOliver/TOCropViewController) as external dependency using tuist, here's how:

---

From reproduction steps in the issue above:

1. Find TOCropViewController/Project/Objective-C/TOCropViewController from project navigator, and click 'Add Files to "TOCropViewController"'.
<img width="708" alt="스크린샷 2023-09-08 오후 3 39 26" src="https://github.com/tuist/tuist/assets/38418559/54e59348-8626-4f14-96ea-79a29a667b76">

2. Select directory 'include'.
<img width="625" alt="스크린샷 2023-09-08 오후 3 39 35" src="https://github.com/tuist/tuist/assets/38418559/4470b34b-e833-4266-a348-d9fbbbddcafc">

3. In 'Build Phases' tab of project TOCropViewController, move all headers to 'Public' group.
<img width="1206" alt="스크린샷 2023-09-08 오후 3 39 55" src="https://github.com/tuist/tuist/assets/38418559/83831151-6975-4860-973f-80bbd23e1156">

4. Compile succeeds.

---

From [Package.swift in TOCropViewController](https://github.com/TimOliver/TOCropViewController/blob/a942414508012b13102f776eb65dac655f31cabb/Package.swift#L35C26-L35C26), `publicHeadersPath` exists but it seems tuist does not handle this property at all.

Hope this helps figuring out supporting Objective-C dependencies.

---

Also I could not find any interfaces that tuist offers to do this. Let me know if any.

### macOS version

13.5.1

### Tuist version

3.25.0

### Xcode version

14.3.1

**Comment by BProg** [comment]
Similar problem happens with Realm when trying to integrate it as a remote dependency
```
.remote(url: "https://github.com/realm/realm-swift.git", requirement: .exact("10.43.0")),
```

**Comment by JackYoustra** [comment]
Another way to solve it is to just use `Carthage` as the dependency manager - it handles the header maps just fine. You're probably not going to want to upgrade until this is addressed.

**Comment by nickaroot** [comment]
You can fix it on Project level

**Fix (Tuist 4.6.0):**

Add _HEADER_SEARCH_PATHS_, _OTHER_CFLAGS_ and _OTHER_SWIFT_FLAGS_  to any target importing TOCropViewController like this:


```swift
let project = Project(
    ...
    settings: .settings(
        base: [
            "HEADER_SEARCH_PATHS": [
                "$(SRCROOT)/Tuist/.build/checkouts/TOCropViewController/Objective-C/TOCropViewController/include/TOCropViewController",
            ],
            "OTHER_CFLAGS": [
                "-fmodule-map-file=$(SRCROOT)/Tuist/.build/tuist-derived/TOCropViewController/TOCropViewController.modulemap",
            ],
            "OTHER_SWIFT_FLAGS": [
                "-Xcc",
                "-fmodule-map-file=$(SRCROOT)/Tuist/.build/tuist-derived/TOCropViewController/TOCropViewController.modulemap",
            ],
        ],
        ...
    )
    ...
)
```

**Comment by fortmarek** [comment]
I've just tested this dependency and the workaround you posted is no longer needed @nickaroot. 

`TOCropViewController` can be integrated without any extra work, so I'm closing this issue. If you keep running into issues, please create a new one 🙏

**Comment by nickaroot** [comment]
This workaround still covering cases, when your modules is external local SPM modules :)

Transitive part between conversion modules to Tuist Projects

**Comment by fortmarek** [comment]
The behavior for local SPM modules should be the same – if it's not, we can take a stab at fixing this if you create an issue with a repro sample ^^
