### ISSUE TITLE
Incorrect StoreKit Configuration path

### ISSUE THREAD

**Issue by gajddo00** [tuist/tuist#5401]
### What problem or need do you have?

Hello! 
I have been trying to add the StoreKit configuration to Tuist using the storeKitConfigurationPath option in scheme run action as follows:

```swift
func appScheme(
    nameSuffix: String?,
    debugConfiguration: BuildConfiguration,
    releaseConfiguration: BuildConfiguration
) -> Scheme {
    let name = [projectName, nameSuffix]
        .compactMap { $0 }
        .joined(separator: "-")
    return Scheme(
        name: name,
        shared: true,
        buildAction: .buildAction(targets: [.init(stringLiteral: appTarget.name)]),
        testAction: .targets(
            [TestableTarget(stringLiteral: testsTarget.name)],
            configuration: debugConfiguration.name,
            expandVariableFromTarget: .init(stringLiteral: appTarget.name)
        ),
        runAction: .runAction(
            configuration: debugConfiguration.name,
            options: .options(
                storeKitConfigurationPath: .relativeToRoot("Projects/AppName/AppName/Application/Products.storekit")
            ),
            diagnosticsOptions: [
                .mainThreadChecker,
                .performanceAntipatternChecker
            ]
        ),
        archiveAction: .archiveAction(configuration: releaseConfiguration.name),
        profileAction: .profileAction(configuration: releaseConfiguration.name),
        analyzeAction: .analyzeAction(configuration: debugConfiguration.name)
    )
}
```

The project structure used (for context):
<img width="605" alt="image" src="https://github.com/tuist/tuist/assets/44062027/b9ecf945-2268-460e-97c3-a72466cf7de5">

I tried different paths using .relativeToManifest or to file, different variations but I always end up with the same result:
```
<StoreKitConfigurationFileReference
identifier = "../AppName/Application/Products.storekit">
</StoreKitConfigurationFileReference>
```

This path is not correct and if I visit the scheme settings in Xcode the StoreKit Configuration is red stating the incorrect path.

```
/Users/username/Desktop/desktop/Projects/root/AppName/Application/Products.storekit StoreKit Configuration file for scheme "AppName" can't be found at path "/Users/username/Desktop/desktop/Projects/root/AppName/Application/Products.storekit "
```

The desired path that Xcode substitutes when I pick the option from Xcode is
```
<StoreKitConfigurationFileReference
identifier = "../Projects/AppName/AppName/Application/Products.storekit">
</StoreKitConfigurationFileReference>
```
If I rewrite the path manually after Tuist generation, Xcode recognizes the path correctly.
So my question is, is this a bug or am I using the feature wrong? How do I get the correct path to work?

Thank you anyone for any sort of help. Much appreciated!

### macOS version

13.4.1

### Tuist version

3.25.0

### Xcode version

15.0 beta 8

**Comment by kwridan** [comment]
Thanks for flagging this @gajddo00 - ouch we missed this.

I had a quick test locally and it seems the store config file paths need to be relative to the workspace as opposed to the project. I suspect we missed this because the paths happen to be correct for single project setups where the workspace and project are in the same path!

**Comment by gajddo00** [comment]
Hey @kwridan I absolutely don't mind, on it 👍
