### ISSUE TITLE
No documentation for Settings struct

### ISSUE THREAD

**Issue by kstenerud** [tuist/tuist#5411]
### What problem or need do you have?

There's no documentation at https://tuist.github.io/tuist/main/documentation/projectdescription/settings that describes what `Settings` is, what its structure is, what its methods are, etc.

### Potential solution

Fill in the documentation.

### macOS version

Doesn't matter

### Tuist version

main

### Xcode version

Doesn't matter

**Comment by danyf90** [comment]
I can see the doc 🤔
