### ISSUE TITLE
Improve the installation script to do a checksum validation of the downloaded file

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5413]
### What problem or need do you have?

The installation script assumes that the downloaded file is the one served by the server, so if a malicious actor is able to interfere in the process and serve a different binary they'd have access to the installer's environment.

### Potential solution

We should extend the script that installs `tuistenv` as well as the logic inside `tuistenv` that installs `tuist` to do checksum validation after downloading the binary. I'd upload the checksums to GitHub and extend the logic to:
1. Verify that the SSL certificate of the connection is GitHub's.
2. That the checksum matches the checksum of the file that has been downloaded.

### macOS version

13.15

### Tuist version

3.26.0

### Xcode version

14

**Comment by danyf90** [comment]
This will be handled by brew when switching to it
