### ISSUE TITLE
Manifest not found at path

### ISSUE THREAD

**Issue by hichunim** [tuist/tuist#5418]
### What problem or need do you have?

"I have one computer where Tuist version 3.4.0 runs smoothly and can execute all relevant Tuist commands. However, when I use another computer with Tuist version 3.26.0 and try to execute the same commands, I run into an issue. After running tuist generate, I get an error message saying `Tuist/Dependencies.swift file is defined but Tuist/Dependencies/graph.json cannot be found. Run tuist fetch first.`
 When I attempt to run tuist fetch, I get another error that says
`Resolving and fetching plugins. Plugins resolved and fetched successfully. Manifest not found at path.`  How can I resolve this issue?"

### Potential solution

I try tuist `fetch first`, and got another error after running this command

### macOS version

12.5

### Tuist version

3.26.0

### Xcode version

14.2.0

**Comment by pepicrft** [comment]
@hichunim do you mind including a small project where we can reproduce this issue?
