### ISSUE TITLE
How to set arch for xcodebuild destination?

### ISSUE THREAD

**Issue by mo5tone** [tuist/tuist#5419]
### What problem or need do you have?

As the Xcode 14.3 has dropped the Rosetta support for Xcode ([Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes)).
So the `arch -x86_64` (#5298) prefix won't work anymore with Xcode 14.3 and later.

The xcodebuild provides an option to select the rosetta simulators for building and testing.
`xcodebuild -workspace App.xcworkspace -scheme App -destination "platform=iOS Simulator,name=iPhone 14,arch=x86_64" test`

But when I ran `tuist test -d 'iPhone 14 (Rosetta),arch=x86_64'` or `tuist test -d 'iPhone 14 (Rosetta)'`, it just failed with below error:
```
Could not find a suitable device for iOS, device name iPhone 14 (Rosetta). Did find iPhone SE (3rd generation) (iOS 16.4), iPhone 14 (iOS 16.4), iPhone 14 Plus (iOS 16.4), iPhone 14 Pro (iOS 16.4), iPhone 14 Pro Max (iOS 16.4), iPad Air (5th generation) (iOS 16.4), iPad (10th generation) (iOS 16.4), iPad mini (6th generation) (iOS 16.4), iPad Pro (11-inch) (4th generation) (iOS 16.4), iPad Pro (12.9-inch) (6th generation) (iOS 16.4)
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

13.0.1 (22A400)

### Tuist version

3.26.0

### Xcode version

14.3.1 (14E300c)

**Comment by apps4everyone** [comment]
This can only be done by hacking and changing the binary and extend the XCFramework

Read this two articles by the arm64-to-sim creator @bogo
https://bogo.wtf/arm64-to-sim.html
https://bogo.wtf/arm64-to-sim-dylibs.html

**Comment by mo5tone** [comment]
> This can only be done by hacking and changing the binary and extend the XCFramework
> 
> Read this two articles by the arm64-to-sim creator @bogo https://bogo.wtf/arm64-to-sim.html https://bogo.wtf/arm64-to-sim-dylibs.html

Nice articles, thanks for sharing. 

But hacking binaries cannot meet our security compliance check.

And I found that fastlane has add a parameter to `scan` for this issue in [[#21284](https://github.com/fastlane/fastlane/pull/21284)], so I think tuist might provide a similar solution for `tuist build\test`.

**Comment by danyf90** [comment]
Thanks @mo5tone  ! I think it makes sense, would you like to try to add support for this in Tuist?

**Comment by mo5tone** [comment]
> Thanks @mo5tone ! I think it makes sense, would you like to try to add support for this in Tuist?

Sure, I'd like to help address this.
