### ISSUE TITLE
Can't implement Live Activity in my project

### ISSUE THREAD

**Issue by Aeeson** [tuist/tuist#5436]
### What problem or need do you have?

I'm trying to add a live activity to my project, I add an extension widget and a scheme through Tuist. The live activity starts, but does not draw the UI. Moreover, if I add an extension with xcode, everything works fine. Can you help with this problem?

### macOS version

13.4

### Tuist version

3.27.0

### Xcode version

14.3.1

**Comment by pepicrft** [comment]
👋🏼 @Aeeson. Could you create a small project where we can reproduce the issue? That'll facilitate our debugging and fixing work.

**Comment by Aeeson** [comment]
Hi, here is a [repo](https://github.com/Aeeson/LiveActivity) with two projects, one is generated using tuist, another one is generated using xcode

**Comment by pepicrft** [comment]
Thanks @Aeeson 🙏🏼. We'll look into it.

**Comment by Aeeson** [comment]
@pepicrft I’ve solved it, was my mistake with dependencies, ty for help
