### ISSUE TITLE
Cryptic Error Message In Tuist Cloud

### ISSUE THREAD

**Issue by ronanociosoig-200** [tuist/tuist#5448]
### What happened?

In the sample project I am working on (https://github.com/ronanociosoig-200/Tuist-Pokedex) I have created both email and Github logins, but only one of them has cached data. If I login to the wrong account then the error message for when I run "tuist cache warm -x" the response is: 

Resolved cache profile 'Development' from Tuist's defaults
Generating workspace Pokedex.xcworkspace
Generating project Pokedex
Generating project swift-snapshot-testing
Generating project JGProgressHUD
Hashing cacheable targets
Failed to check existence of target Backpack with hash 26f1db88b2ea00298436495de457980b, Retrying…
Failed to check existence of target Catch with hash 6b168728113b25a1abfeaf35e2b114ab, Retrying…
Failed to check existence of target Detail with hash 3d43982c84174a601011cde9be59c003, Retrying…
Failed to check existence of target Common with hash 5836a081c5c74cc89ade4234189241d8, Retrying…
Failed to check existence of target Haneke with hash 0af419028bc8990c351305117405d75e, Retrying…
Failed to check existence of target Home with hash 667ecb56888e9f155ab6b9e59902e08a, Retrying…
Error parsing the network response of an url request that sends a GET request to url 'https://cloud.tuist.io/api/cache/exists?project_id=ronanoc/Tuist-Pokedex&hash=5836a081c5c74cc89ade4234189241d8&name=Common': The data couldn’t be read because it is missing.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

The error "Error parsing the network response of an url request that sends a GET request to url" also appears on CI when the token is omitted in either cache warm or generate commands. 

It would be better to give a more descriptive error and suggestions of possible ways to fix the problem.  

### How do we reproduce it?

1: Create 2 cloud accounts, one using email, the other on Github. 
2: Build a project and upload artefacts using account 1. 
3: Logout, clear the cookie in the browser for tuist cloud, and then login with the other account. 
4: Login with the 2nd account
5: Run cache warm -x

### Error log

 % tuist cache warm -x
Resolved cache profile 'Development' from Tuist's defaults
Generating workspace Pokedex.xcworkspace
Generating project Pokedex
Generating project swift-snapshot-testing
Generating project JGProgressHUD
Hashing cacheable targets
Failed to check existence of target Backpack with hash 26f1db88b2ea00298436495de457980b, Retrying…
Failed to check existence of target Common with hash 5836a081c5c74cc89ade4234189241d8, Retrying…
Failed to check existence of target Haneke with hash 0af419028bc8990c351305117405d75e, Retrying…
Failed to check existence of target Detail with hash 3d43982c84174a601011cde9be59c003, Retrying…
Failed to check existence of target NetworkKit with hash b63339f2669d9d63e6d9b846f7f9a890, Retrying…
Failed to check existence of target UIComponents with hash 85ca04a7e137ee304f5bfaf96cdff96d, Retrying…
Failed to check existence of target JGProgressHUD with hash cc06dd5f9d33d81772ddfe009ecb47d1, Retrying…
Failed to check existence of target Catch with hash 6b168728113b25a1abfeaf35e2b114ab, Retrying…
Failed to check existence of target Home with hash 667ecb56888e9f155ab6b9e59902e08a, Retrying…
Error parsing the network response of an url request that sends a GET request to url 'https://cloud.tuist.io/api/cache/exists?project_id=ronanoc/Tuist-Pokedex&hash=85ca04a7e137ee304f5bfaf96cdff96d&name=UIComponents': The data couldn’t be read because it is missing.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

13.5

### Tuist version

3.27.1

### Xcode version

15.0.0

**Comment by pepicrft** [comment]
This should have already been addressed. Feel free to reopen if the issue still persists @ronanociosoig-200
