### ISSUE TITLE
SVG images are getting ignored in the generate process

### ISSUE THREAD

**Issue by Hotzenplotz1337** [tuist/tuist#5450]
### What problem or need do you have?

Dear dev team of Tuist,

I experienced a weird behaviour when generating a project, that contains some SVG images in the assets catalog.
Those images are just getting ignored, when generating the project. Other types like jpg or png are getting generating as expected. 
![Screenshot 2023-09-28 at 11 37 07](https://github.com/tuist/tuist/assets/29718119/380d6d09-b876-4e0c-ad22-cf9dae925d8c)
![Screenshot 2023-09-28 at 11 37 13](https://github.com/tuist/tuist/assets/29718119/e4b6ceea-126d-48ba-996c-0c91ba8baa95)

 So is it possible to fix this in the near future? It should not be a big deal I guess. :)

Thank you for the great work anyway on Tuist project and best regards
Mark

### macOS version

13.6

### Tuist version

3.27.1

### Xcode version

15.0

**Comment by fortmarek** [comment]
Hey 👋 

Can you provide a reproducible sample? That would make the debugging easier.

**Comment by danyf90** [comment]
The problem isn't because it's an 'svg', but because it's a `symbolset` instead of an `imageset` 🤔

**Comment by danyf90** [comment]
I think it depends on the swiftgen template, probably here we need to add something to handle `imageset`s:
```

      {% if asset.type == "arresourcegroup" %}
      {{accessModifier}} static let {{asset.name|swiftIdentifier:"pretty"|lowerFirstWord|escapeReservedKeywords}} = {{arResourceGroupType}}(name: "{{asset.value}}")
      {% elif asset.type == "color" %}
      {{accessModifier}} static let {{asset.name|swiftIdentifier:"pretty"|lowerFirstWord|escapeReservedKeywords}} = {{colorType}}(name: "{{asset.value}}")
      {% elif asset.type == "data" %}
      {{accessModifier}} static let {{asset.name|swiftIdentifier:"pretty"|lowerFirstWord|escapeReservedKeywords}} = {{dataType}}(name: "{{asset.value}}")
      {% elif asset.type == "image" %}
      {{accessModifier}} static let {{asset.name|swiftIdentifier:"pretty"|lowerFirstWord|escapeReservedKeywords}} = {{imageType}}(name: "{{asset.value}}")
      {% elif asset.items and ( forceNamespaces == "true" or asset.isNamespaced == "true" ) %}
      {{accessModifier}} enum {{asset.name|swiftIdentifier:"pretty"|escapeReservedKeywords}} {
        {% filter indent:2 %}{% call casesBlock asset.items %}{% endfilter %}
      }
      {% elif asset.items %}
      {% call casesBlock asset.items %}
```
