### ISSUE TITLE
Extend scaffold to allow passing non-string parameteres to Stencil templates

### ISSUE THREAD

**Issue by Paldom** [tuist/tuist#5462]
### What problem or need do you have?

Currently, when using the scaffold feature, we are only able to pass string parameters from the source code. For instance, the snippet below demonstrates attempting to pass a dictionary as a default parameter, which fails because only string values are permitted.

```
let environmentAttribute: Template.Attribute = .optional("environment", default: environment.toDictionary())
```

On the other hand, Stencil's renderTemplate method allows for a custom context, as shown in the snippet below, which enables passing a dictionary:

```
public func renderTemplate(name: String, context: [String: Any] = [:]) throws -> String {
}

```

There can be many scenarios when you want to pass a non-string context from template's swift code to stencil template during generation.

### Potential solution

Perhaps an additional method or parameter could be introduced to pass non-string values to the stencil file.

If that not possible, a quick solution would be extremely beneficial: to enhance the scaffold's capability by allowing the default parameter type to be `Any` instead of just `String`. This change would align more closely with Stencil's native `renderTemplate` method, thereby providing a more flexible and powerful templating solution.

### macOS version

13.4.1

### Tuist version

3.24.0

### Xcode version

14.3.1

**Comment by danyf90** [comment]
Thanks @Paldom ! I think it makes sense, would you like to try to add support for this in Tuist?
