### ISSUE TITLE
Caching Alogorithms.swift

### ISSUE THREAD

**Issue by justingiffard-impact** [tuist/tuist#5464]
### What happened?

Struggling to cache Swift Algorithms
weirdly the paths in the log are basically the same with the exception of the one starting with `/private` and ending with `/Algorithms`

### How do we reproduce it?

1. add
`.remote(url: "https://github.com/apple/swift-algorithms.git", requirement: .upToNextMajor(from: "1.0.0"))` or
` .package(url: "https://github.com/apple/swift-algorithms.git", from: "1.0.0")` to Dependencies.swift
2. run `tuist fetch`
3. run `tuist cache warm -x --dependencies-only`

### Error log

```Caching Algorithms.xcframework
error: cannot compute path of binary 'Path(str: "/private/var/folders/3p/6syrmsgs3sn6ksskg1nnnlz00000gn/T/TemporaryDirectory.Q06DUa/simulator.xcarchive/Products/Library/Frameworks/Algorithms.framework/Algorithms")' relative to that of '/var/folders/3p/6syrmsgs3sn6ksskg1nnnlz00000gn/T/TemporaryDirectory.Q06DUa/simulator.xcarchive/Products/Library/Frameworks/Algorithms.framework'
The 'xcodebuild' command exited with error code 70```

### macOS version

13.5.2

### Tuist version

3.20.0

### Xcode version

15.0.0

**Comment by danyf90** [comment]
Fixed in Xcode [3.27.1](https://github.com/tuist/tuist/blob/main/CHANGELOG.md#3271---2023-09-21)
