### ISSUE TITLE
Extend to allow passing options to ResourceSynthesizers

### ISSUE THREAD

**Issue by ElonPark** [tuist/tuist#5470]
### What problem or need do you have?

Swiftgen parser protocol can accept options as a dictionary(`[String: Any]`)

In general, this allows you to use "." as a delimiter for keys in a Strings file. to use "/" instead of "." to generate code

 This is currently not possible in Tuist, because you cannot pass options to the parser

### Potential solution

The simplest way to do this is to add an associated value to the current `ResourceSynthesizer.Parser` enum

probably something like this
```swift
    // Declaring a project
    resourceSynthesizers: [
      .strings(options: ["separator": "/"]),
    ]

   // in SynthesizedResourceInterfacesGenerator
    private func parser(for parser: ResourceSynthesizer.Parser) throws -> Parser {
        switch parser {
        /* ... */
        case .strings(let options): 
            return try Strings.Parser(options: options)
       /* ... */
        }
    }
```
- [SwiftGen StringsParser Option](https://github.com/SwiftGen/SwiftGen/blob/1cf6d7eebd70c2157f69d5a991bc57c1ef182ed1/Sources/SwiftGenKit/Parsers/Strings/StringsParser.swift#L52)
- [SynthesizedResourceInterfacesGenerator](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Utils/SynthesizedResourceInterfacesGenerator.swift#L45)

### macOS version

13.6

### Tuist version

3.28.0

### Xcode version

15.0

**Comment by danyf90** [comment]
Makes sense! Do you want to try to add this support? 🙏

**Comment by ElonPark** [comment]
> Makes sense! Do you want to try to add this support? 🙏 

`ResourceSynthesizer.Parser` uses the Equatable protocol, so passing [String: Any] as an associate value is tricky.
but I'll see what I can do.

For example, create a Meta enum and use it like this
```swift
enum MetaValue {
  case stringVale(String)
  case boolValue(Bool)
   /* ... */
}
```

**Comment by ElonPark** [comment]
Oh, already using AnyCodable in Tuist.
That makes things easy
