### ISSUE TITLE
Swift source files don't seem to be compiled correctly in Swift Package declared in Dependencies.swift

### ISSUE THREAD

**Issue by liamnichols** [tuist/tuist#5480]
### What happened?

This is a bit of a weird one, but i'm currently testing out Tuist on our project (looking to move over from XcodeGen) and I ran into a strange unit test failure that I seem to have managed to trace back to an issue with the way that swift-custom-dump is compiled. 

In the project there is a file called [Foundation.swift](https://github.com/pointfreeco/swift-custom-dump/blob/main/Sources/CustomDump/Conformances/Foundation.swift) which adds some conformances to standard types, but when the dependency is integrated into our project using Dependencies.swift, this doesn't seem to get compiled properly because the conformance isn't picked up which was causing my existing tests to fail:

<img width="610" alt="Screenshot 2023-10-05 at 22 21 56" src="https://github.com/tuist/tuist/assets/482871/607bf326-9425-4464-b94c-ba48ebb22968">

it's not immediately obvious in the screenshot above, but it seems that this diff appears because the `NSURL` and/or `URL` extensions in Foundation.swift aren't compiled properly.

Everything looks good in the build log and Compile Sources build phase though:

Build Log|Compile Sources
---|---
<img width="514" alt="Screenshot 2023-10-05 at 22 03 11" src="https://github.com/tuist/tuist/assets/482871/d22e64d6-d579-4789-868f-0172fc733fe6">|<img width="497" alt="Screenshot 2023-10-05 at 22 00 04" src="https://github.com/tuist/tuist/assets/482871/393a6bc0-24e0-48c7-8527-ea513670ad7f">

But the Xcode Breakpoint thinggy does seem to notice that something is up:

<img width="803" alt="Screenshot 2023-10-05 at 21 58 58" src="https://github.com/tuist/tuist/assets/482871/7ed614ba-0773-49e5-ac74-fb89319f1ac2">

### How do we reproduce it?

1. Create a new project with `tuist init --platform ios`
2. Add the following to **Tuist/Dependencies.swift**:
    ```swift
    import ProjectDescription
    import ProjectDescriptionHelpers

    let dependencies = Dependencies(
        swiftPackageManager: [
            .remote(url: "https://github.com/pointfreeco/swift-custom-dump", requirement: .exact("1.1.0"))
        ]
    )
    ```
3. Add the `.external(name: "CustomDump")` dependency to the test `Target` definitions
4. Generate the project with `tuist generate`
5. Add the following test:
    ```swift
    import CustomDump
    import Foundation
    import XCTest
    
    final class GOODWithPackageKitTests: XCTestCase {
        func test_example() {
            let url = NSURL(string: "https://tuist.io")!
    
            var string = ""
            customDump(url, to: &string)
    
            XCTAssertEqual(string, "URL(https://tuist.io)")
        }
    }
    ```
6. Run the unit tests

If the test passes, CustomDump was compiled properly, if it fails with `string == "NSURL()"` then something wrong happened and the extensions in **Foundation.swift** were not compiled as expected.

To save you some effort, i've attached two projects that were generated with Tuist. **BAD-WidthDependencies** follows the steps above and can demonstrate the failing test, whereas **GOOD-WithPackage** adds the CustomDump dependency via `Project.packages` where you can see the expected behaviour:

[CustomDumpTest.zip](https://github.com/tuist/tuist/files/12823011/CustomDumpTest.zip)

They both have identical tests, but the Dependencies.swift one fails

`Project.packages`|Dependencies.swift
---|---
<img width="1512" alt="Good" src="https://github.com/tuist/tuist/assets/482871/0edef513-e03a-4e3f-9beb-3328132ad265">|<img width="1512" alt="Bad" src="https://github.com/tuist/tuist/assets/482871/0ff5fa45-41de-4707-9c52-ecb53c9f8de2">

### Error log

N/A

### macOS version

13.5.2 (22G91)

### Tuist version

3.28.0

### Xcode version

15.0 (15A240d)

**Comment by danyf90** [comment]
If I remember correctly, this is an (Xcode?) bug with static frameworks containing/depending ObjC.
If you don't refer a symbol from the package, then extensions are note picked up 🤷 
In this case you are using `customDump` though, so it should work.
Adding an additional assertion `XCTAssertEqual(url.customDumpValue as! URL, URL(string: "https://tuist.io"))` makes the other assertion work as well, so I think it's related to the bug I was mentioning.

I would probably just define the target as dynamic from the Dependencies.swift

**Comment by liamnichols** [comment]
Thanks for the prompt response @danyf90 ! This is a very interesting one.

In my actual use case, I’m snapshotting a Decodable model that is initialised from JSON. So while the type contains a URL property, it’s value actually bridged from NSURL under the hood which means that I can’t apply your suggested workaround.

But something else worth mentioning is that I wasn’t actually using the SPM package directly before.. I am actually using a [custom podspec](https://github.com/liamnichols/pointfreeco-specs) and integrating the library into our project via Cocopods. I need to double check, but I’m pretty sure it’s doing this with a static framework too (although maybe it’s a library?) and the issue doesn’t occur in that scenario. 

I’ll try to compare how CocoaPods forms the dependency vs how tuist is doing it.. but otherwise I’ll just try marking it as dynamic like you suggested, thanks

**Comment by liamnichols** [comment]
I did work around it in the CustomDump scenario by using `Product.framework`, but I think I've also potentially run into a similar issue with the **FirebaseInAppMessaging-Beta** product from the Firebase SDKs:

<img width="1206" alt="Screenshot 2023-10-06 at 12 14 47" src="https://github.com/tuist/tuist/assets/482871/2fe884cc-3df4-4173-a856-0bae084fa3e8">

I'll try and dig a bit further into this one.

**Comment by liamnichols** [comment]
I also ran into similar with the Adjust iOS SDK (https://github.com/adjust/ios_sdk)

<img width="1213" alt="Screenshot 2023-10-06 at 13 03 26" src="https://github.com/tuist/tuist/assets/482871/1ebc013e-da96-4bca-8ab2-febd809f332b">

At this point i had a bit more of a Google and it seems that we might need to be including `-ObjC` in Other Linker Flags (`OTHER_LDFLAGS`) for the target that links the dependency? I had a go:

```swift
settings: .settings(base: ["OTHER_LDFLAGS": ["$(inherited)", "-ObjC"]])
```

And it works, both for the issues I faced with the Swift extension in CustomDump as well as Adjust and Firebase 🎉 

I had a look back at the .xcconfigs that CocoaPods generated for the projects previously:

```
OTHER_LDFLAGS = $(inherited) -ObjC -framework "CustomDump" -framework "SnapshotTesting" -framework "XCTestDynamicOverlay" -weak_framework "XCTest"
```

So it looks like that might be the missing piece? I can do this manually in my targets, but i'm wondering if this is something that Tuist should do automatically? (or maybe it does but I just haven't wired it up right?) 

It seems that CocoaPods adds this flag to the targets that you integrate Pods into regardless of the type of pods linked, but i'm not totally sure if adding it when it's not needed will cause other problems or not? 

But regardless, I have a solution now that lets me keep my dependencies static in Dependencies.swift 🙂

**Comment by danyf90** [comment]
Oh yep, you need to add it :sisi:
I don't think that blindly adding `-ObjC` is the right thing to do is the right thing to do 🤔 

We could either try to understand whether it's needed, or just live with it (I would go with the second as that's what Xcode is doing, and hopefullly ObjC is slowly dying)

**Comment by liamnichols** [comment]
> I don't think that blindly adding `-ObjC` is the right thing to do is the right thing to do 🤔

Yeah, you're right 😄 

> We could either try to understand whether it's needed

I had a little look at CocoaPods source and found some potentially useful info [in the tests](https://github.com/CocoaPods/CocoaPods/blob/216478820851e7feed9fa512b8183808c57b6cb2/spec/unit/target/build_settings_spec.rb#L226-L424):

> - `other_ld_flags should not include -ObjC when there are not static frameworks`
> - `other_ld_flags should include -ObjC when linking static frameworks`
> - `other_ld_flags should include -ObjC when linking vendored static frameworks`
> - `other_ld_flags should include -ObjC when linking vendored static xcframeworks`
> - `other_ld_flags should not include -ObjC when linking vendored dynamic xcframeworks`

It seems that you need to do so only when linking static frameworks into a target. Given that there isn't much more demand on this at the moment, i'll just leave it there, but I guess it's something to consider if this becomes a problem for others? 

Thanks again for the initial hint!
