### ISSUE TITLE
Generating a new Target requires manual folder creation

### ISSUE THREAD

**Issue by kasrababaei** [tuist/tuist#5484]
### What problem or need do you have?

Trying Tuist for the first time, and noticed when a new string, which is name of a new `Target`, is added to the array that's passed to the `additionalTargets` parameter of the `static app(name:platform:additionalTargets:)` method, generating a new project fails and outputs the following error:

```
tuist generate --no-cache --no-open
Resolved cache profile 'Development' from Tuist's defaults
The target MyAppCore has the following invalid source files globs:
- The directory "/Users/.../MyApp/Targets/MyAppCore/Sources" defined in the glob pattern "/Users/.../MyApp/Targets/MyAppCore/Sources/**" does not exist.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose 
```

To reproduce it:

1. Open terminal
2. Create a new folder, i.e., `mkdir MyApp`
3. Change the current directory, i.e., `cd MyApp`
4. Initialize a new iOS project using SwiftUI template, i.e., `tuist init --platform ios --template swiftui`
5. Being edit the project, i.e., `tuist edit`
6. In `Project.swift` file, add a new additional target like: 
```
let project = Project.app(
    name: Project.appName,
    platform: .iOS,
    additionalTargets: ["MyAppKit", "MyAppUI", "MyAppCore"]
)
```
7. Try generating the project, i.e., `tuist generate`

### Potential solution

I'm not sure if this is intended or not. Ideally, it should check if the folder/subfolder exists, and if not, it should just create the directory.

### macOS version

13.5.2

### Tuist version

3.28

### Xcode version

15.0 (15A240d)

**Comment by danyf90** [comment]
That's intentional, the manifest should describe what the project is, not trying to modify it to adapt to the manifest.
For example, what if you have a folder but you make a typo? Would you prefer an error or a folder (and sources?) generation?

To add basic code for your new target you should use tuist scaffold command
