### ISSUE TITLE
Unit-test doesn't detect in project after generation

### ISSUE THREAD

**Issue by Argon-cell** [tuist/tuist#5486]
### What happened?

Previously, our project was not generated automatically, but now we wanted to tuist migrate. Everything is fine, but tests are not detected (test diamonds are not displayed). If I double click the target it shows up but not after generating

### How do we reproduce it?

Do `tuist generate` in terminal
After do `pod install`
Then open project

### Error log

You can see there's no "test diamonds", in tests 0 errors and all was working good in old version project (without autogeneration)
<img width="1136" alt="Снимок экрана 2023-10-09 в 10 07 56" src="https://github.com/tuist/tuist/assets/68294593/182e89ef-8a01-4f63-a374-93acb3eb4174">

### macOS version

13.2

### Tuist version

3.27.1

### Xcode version

14.3.1

**Comment by danyf90** [comment]
Could you please reproduce the problem in a sample project? 🙏
