### ISSUE TITLE
Missing support for SwiftPackageManager macros

### ISSUE THREAD

**Issue by tackgyu** [tuist/tuist#5488]
### What happened?

When Swift package containing Swift macro added, tuist fetch failed with error messages below.
It seems like the issue #5435 not fixed yet.

### How do we reproduce it?

1. `mkdir Test`
2. `cd Test`
3. `tuist init --platform ios`
4. `echo 3.28.0 > .tuist-version`
5. `touch Tuist/Dependencies.swift`
6. Open `Tuist/Dependencies.swift` and edit as:
```swift
import ProjectDescription

let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/lukepistrol/SFSymbolsMacro", requirement: .exact("0.4.1")),
    ],
    platforms: [.iOS]
)
```
7. `tuist fetch`
8. Open `Tuist/ProjectDescriptionHelpers/Project+Templates.swift` and edit as:
```swift
// Tuist/ProjectDescriptionHelpers/Project+Templates.swift:L23
private static func makeFrameworkTargets(name: String, platform: Platform) -> [Target] {
    let sources = Target(name: name,
            platform: platform,
            product: .framework,
            bundleId: "io.tuist.\(name)",
            infoPlist: .default,
            sources: ["Targets/\(name)/Sources/**"],
            resources: [],
            dependencies: [
                .external(name: "SFSymbolsMacro") // insert here
            ])
    ...
}
```
9. `tuist generate`

### Error log

```sh
Found an inconsistency between target destinations `[TuistGraph.Destination.iPhone, TuistGraph.Destination.macWithiPadDesign, TuistGraph.Destination.iPad]` and deployment target `macOS`
Found deployment platforms (macOS) missing corresponding destination
Target SFSymbolsMacro has platforms 'iOS' and product 'staticFramework' and depends on target SFSymbolsMacroImpl of type 'Swift Macro' and platforms 'iOS' which is an invalid or not yet supported combination.
Target SFSymbolsMacroImpl has platform 'iOS' and product 'Swift Macro' which is an invalid or not yet supported combination.
Target SFSymbolsMacroImpl has platform 'iOS' and product 'Swift Macro' which is an invalid or not yet supported combination.
Fatal linting issues found
```

### macOS version

13.5.1

### Tuist version

3.28.0

### Xcode version

15.0

**Comment by danyf90** [comment]
Macros are currently not supported, I know @pepicrft wanted to start working on it

**Comment by nilotic** [comment]
Can I know when it will be fixed?

**Comment by pepicrft** [comment]
You can already add macros using the `.package` API inside `Target.dependencies`. The support through Xcode native primitives is [in the making](https://github.com/tuist/tuist/pull/5542). Once we have this one, you'll be able to binary-cache the Swift Macro executables. We expect to have an initial version next week.

**Comment by kimxwan0319** [comment]
I have same issue.

**Comment by pepicrft** [comment]
This is a known issue. We are [working on a fix](https://github.com/tuist/tuist/pull/5583)
