### ISSUE TITLE
tuist fetch fails when removing packages from Dependencies.swift file

### ISSUE THREAD

**Issue by mihaicris-adoreme** [tuist/tuist#5489]
### What problem or need do you have?

Removing one entry from Dependencies.swift file will make tuist fetch fail

```sh
tuist fetch
Using version 3.27.1 defined at ....
....
Removing https://github.com/HeshamMegid/HMSegmentedControl
error: 'hmsegmentedcontrol': repository '/Users/mihai.c/adoreme/feature/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/HMSegmentedControl' has uncommited changes
....
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
make: *** [fetch] Error 1


✔ ~/adoreme/feature/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/HMSegmentedControl (:a2852bd|✚3…)
9:34 $ git status
HEAD detached at a2852bd
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   HMSegmentedControl.xcodeproj/project.pbxproj
	modified:   HMSegmentedControl.xcodeproj/project.xcworkspace/contents.xcworkspacedata
	deleted:    HMSegmentedControl.xcodeproj/xcshareddata/xcschemes/HMSegmentedControl.xcscheme

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Derived/

no changes added to commit (use "git add" and/or "git commit -a")
```

Steps: 
1. Add one dependency entry to Dependencies.swift (I think it can be any package PACKAGE_NAME)
2. tuist fetch
3. tuist cache warm --xcframeworks
4. tuist generate --xcframeworks
5. Remove the dependency entry from Dependencies.swift
6. tuist fetch --> ERROR because Tuist/Dependencies/SwiftPackageManager/.build/checkouts/[PACKAGE_NAME] git is dirty and it can be removed?

### macOS version

14.0

### Tuist version

3.27.1

### Xcode version

14.3.1

**Comment by danyf90** [comment]
Can you replicate the same with pure SPM? Because we just rely on it for fetching, so I suspect it's an SPM bug/problem 🤔

**Comment by mihaicris-adoreme** [comment]
I am not sure how to to this outside Tuist with Dependencies. But, I wonder, if someone tries to temporary remove a dependency from his project, will it reproduce? My workaround is to manually remove the folder.

**Comment by danyf90** [comment]
To test I would:
- Copy the Package.swift that gets generated in `Tuist/Dependencies/SwiftPackageManager/Package.swift` in a new folder
- Run `swift package resolve`
- Remove a dependency as mentioned in the issue
- Run `swift package resolve` and see if it fails. If it does, it's an SPM issue

🙏

**Comment by mihaicris-adoreme** [comment]
Issue is not reproduced with above steps
Notes: swift package updates the Package.resolve file but it doesn't delete the checkout package from repositories folder or the checkouts folder.
However, what I think is different while working under tuist, is that the Tuist alters the git status - maybe in the next step cache warm (as seen in the console logs example):

```sh
modified:   HMSegmentedControl.xcodeproj/project.pbxproj
modified:   HMSegmentedControl.xcodeproj/project.xcworkspace/contents.xcworkspacedata
deleted:    HMSegmentedControl.xcodeproj/xcshareddata/xcschemes/HMSegmentedControl.xcscheme
`

Would be maybe better that tuist fetch before starting anything should try to clean (restore) all the repos in checkouts folder, such that the swift package manager should not fail in case the git is dirty?

**Comment by danyf90** [comment]
I wouldn't sacrifice execution time trying to clean up repos when it works well in 99% of the cases.
It might be worth to understand this specific error and do it only in this case.

It is quite low lever priority for us at the moment, do you want to try to implement it?
