### ISSUE TITLE
Carthage ambiguous signing

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#549]
**Describe the bug**
When I have multiple certs in keychain and generate project with tuist with carthage dependendencies, I get this error when trying to build the project:
`Embedding framework Carthage/Build/iOS/UICollectionViewLeftAlignedLayout.framework
iPhone Developer: ambiguous (matches "iPhone Developer: Mr CI (some_id)" and "iPhone Developer: Marek Fort (some_id)" in /Users/marekfort/Library/Keychains/login.keychain-db)
Error: Command exited with error code 1 and error: 
Command PhaseScriptExecution failed with a nonzero exit code`

**To Reproduce**

1. Have two or more signing certs in your keychain
2. Add Carthage dependency
3. `tuist generate`
4. Build project

**Expected behavior**
Build should succeed

**Desktop (please complete the following information):**

- macOS 10.14.6 
- 0.18.1

**Notes**
Would love to add fixture for this, but I think we are not able to reproduce this environment.

**Comment by asalom** [comment]
I had an issue I think it could be related to this. When you configure the project to use a certain signing identity like `"CODE_SIGN_IDENTITY": "iPhone Developer: iOS Dev"` but you don't have any certificate installed in your keychain matching this name, `tuist embed` finishes with the same/smilar error:

```
Embedding framework Binaries/Alamofire.framework
Error: Command exited with error code 1 and error: 
```

**Comment by pepibumur** [comment]
@fortmarek would you mind trying out the latest commit from master to see if that solves the bug that you are facing here?

**Comment by fortmarek** [comment]
Seems to be working well, closing the issue, thanks! 🎊
