### ISSUE TITLE
Failure to parse macOS provisioning profiles

### ISSUE THREAD

**Issue by vcoutasso** [tuist/tuist#5502]
### What problem or need do you have?

I'm trying to setup `tuist signing` for a macOS project as per the [documentation](https://docs.tuist.io/commands/signing) but I keep getting the following error when I run `tuist generate`:

```
We received an error that we couldn't handle:
    - Localized description: The data couldn’t be read because it is missing.
    - Error: keyNotFound(CodingKeys(stringValue: "application-identifier", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "Entitlements", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"application-identifier\", intValue: nil) (\"application-identifier\").", underlyingError: nil))
```

I have tried this process using different profiles (always generated them from the developer portal) with minor changes, but the error persists nonetheless.

### Potential solution

I did some (minor) digging and found out that there is actually a difference to how macOS profiles define entitlements. For an iOS profile we would usually expect something like

```xml
<!-- Rest of the profile here -->
<key>Entitlements</key>
<dict>		
        <key>application-identifier</key>
        <string>TEAM_ID.com.mycompany.myapp</string>
	<!-- Actual entitlements here -->
</dict>
```

But every single macOS provision profile I created through the Developer portal gave me something like

```xml
<!-- Rest of the profile here -->
<key>Entitlements</key>
<dict>
        <key>com.apple.application-identifier</key> <!-- See this prefix? -->
        <string>TEAM_ID.com.mycompany.myapp</string>
        <!-- Actual entitlements here -->
</dict>
```

I tested with three different macOS profiles (macOS App Development, Mac App Store, and Developer ID) and they all share this.

From [ProvisioningProfile.swift](https://github.com/tuist/tuist/blob/main/Sources/TuistSigning/ProvisioningProfile/ProvisioningProfile.swift) we see that the only Coding Key we use for decoding those files is the one present in the iOS profiles (`application-identifier`), which would explain the issue.

Another thing I noticed is that macOS profiles set the Platform field very differently, so they should be easy to spot:

```xml
<key>Platform</key>
<array>
        <string>OSX</string>
</array>
```

This is something that has been bothering me for a while now and I would love to contribute, if possible, to see this through :)

### macOS version

14.0

### Tuist version

3.28.0

### Xcode version

15.0 (15A240d)

**Comment by fortmarek** [comment]
> This is something that has been bothering me for a while time and I would love to contribute, if possible, to see this through :)

Awesome, thanks for doing the initial research 🙌 I think it's reasonable to try to also read the key that's defined in macOS. We could also read the platform target of the target the entitlement file belongs to and choose the key based on that.

Let us know if you need any support from our side 🙂

**Comment by vcoutasso** [comment]
> I think it's reasonable to try to also read the key that's defined in macOS. 

That was my first thought, as it is arguably the simplest solution. I tested it on my fork, and it worked great (the parsing worked, but the project didn't properly use my provisioning profiles, and I'm still investigating). However, there is something bothering me about this approach, and I would appreciate some input.

I'm currently checking to see if the iOS key is present, and if not, I just silently fallback to the macOS key. However, the error message might be a bit misleading and unrepresentative of the process if this fails for some obscure reason in the future (say that there's yet another platform using a different key). The error would complain about the absence of the `com.apple.application-identifier` key, but this is probably the expected case for the vast majority of existing profiles and not a problem by itself (assuming iOS profiles are much more common than macOS). It wouldn't be clear to the end user that we tried decoding using both keys and that it only failed because we couldn't find either.

> We could also read the platform target of the target the entitlement file belongs to and choose the key based on that.

This would complicate things a bit, but perhaps it is the most future-proof and transparent approach. However, I'm not sure if the added complexity would be justifiable, as this whole situation seems more like a small detail that slipped away just this once. Furthermore, I am not aware of documentation regarding this file format, so all platform-specific decision-making would be done based on empirical data only, which could lead to more bugs if there were any oversights.

What are your thoughts?

**Comment by fortmarek** [comment]
> It wouldn't be clear to the end user that we tried decoding using both keys and that it only failed because we couldn't find either.

We definitely want to be more clear. How about we throw a specific error that we can't read the entitlements file due to missing expected keys? This should give users enough information and if they their entitlements file is valid, they'd create an issue, so we can add support for it.

> This would complicate things a bit, but perhaps it is the most future-proof and transparent approach. However, I'm not sure if the added complexity would be justifiable, as this whole situation seems more like a small detail that slipped away just this once.

That's fair, we can read `com.apple.application-identifier` as a fallback if reading `application-identifier` fails.

> Furthermore, I am not aware of documentation regarding this file format, so all platform-specific decision-making would be done based on empirical data only, which could lead to more bugs if there were any oversights.

Yeah, unfortunately, a lot of we do at tuist is based on empirical data and reverse-engineering Apple's formats 😞

**Comment by vcoutasso** [comment]
> We definitely want to be more clear.

Now that you mentioned it, it sounds like this is obviously the way to go :)

> How about we throw a specific error that we can't read the entitlements file due to missing expected keys?

If we apply platform-based decoding strategies we kinda get that for free, right? If we get the OSX platform but read the iOS key, the decoding error message would be appropriate! Much better than just a "fallback and pray that it works" approach. That's of course assuming that this scenario is illegal and constitutes an invalid provisioning profile (which is in line with my testing, but I couldn't find documentation to support this assumption).

I tested pretty much every combination of profiles I could create (except, I think, tvOS Ad Hoc because I don't own one, and it requires a registered device), and it seems like macOS profiles are the only ones with special needs.

With this I'm more comfortable working on a solution now. Thank you very much for the feedback!

**Comment by vcoutasso** [comment]
Actually, there is one more thing: I noticed that there is an [iOS App with signing](https://github.com/tuist/tuist/tree/main/projects/tuist/fixtures/ios_app_with_signing) fixture and figured that it would make sense to have a counterpart test macOS projects for the reasons outlined above.

However, I wasn't able to find a Cucumber test that uses this fixture, so I'm unsure whether or not macOS should have one and where to even put it. 

Am I missing something?
