### ISSUE TITLE
Misleading `generate` error message

### ISSUE THREAD

**Issue by bojan** [tuist/tuist#5506]
### What problem or need do you have?

When you run `tuist generate`, and you haven't fetched the remote content by running `tuist fetch`, the error is misleading:
```
`FooBar` is not a valid configured external dependency
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### Potential solution

A message mentioning the fetch mechanism would point the developer to the right direction.

### macOS version

14.0

### Tuist version

3.8.0

### Xcode version

15.0.0

**Comment by fortmarek** [comment]
Hey @bojan 👋 

I am absolutely with you – we should suggest next steps for a developer if things go south. Would you like to implement this? 😌

**Comment by dxmvsh** [comment]
Hey @fortmarek 👋🏿

I would like to try and solve this issue. Do you have any specific requirements to solve this issue, I mean other cases besides `tuist fetch` error? Or is it enough to close this issue only by showing suggestions to run `tuist fetch`? 

I would appreciate if you have any other recommendations or suggestions about this issue.

Thank you in advance!

**Comment by fortmarek** [comment]
> I would like to try and solve this issue

Amazing! 💜 

> Or is it enough to close this issue only by showing suggestions to run tuist fetch?

Yeah, I think that's enough for now – if an external target is not found, we should update the error message to include the suggestion to run `tuist fetch`. I don't think we want to automatically re-run `tuist fetch`.

**Comment by dxmvsh** [comment]
Hello, @fortmarek 

I believe this issue is fixed in #5193 linking to issue [5118](https://github.com/tuist/tuist/issues/5118). This issue probably can be closed by updating tuist to version `3.20.0`, as changes been included according to [CHANGELOG.md](https://github.com/tuist/tuist/blob/93a06710b6ce738247436958a762c7ca282a790d/CHANGELOG.md?plain=1#L256).

**Comment by DandyLyons** [comment]
This issue still exists on tuist version `4.9.0`

**Comment by fortmarek** [comment]
> This issue still exists on tuist version 4.9.0, but it doesn't happen all the time.

I will close the issue as not that many users seem to run into this anymore. Feel free to create a new issue if you can provide a reproducer 🙏
