### ISSUE TITLE
`DEFINE_MODULE was set` warning occurs in xcode 15

### ISSUE THREAD

**Issue by topkim993** [tuist/tuist#5513]
### What happened?

When building with xcode15, modules created with tuist and third-party modules added with Tuist Dependency generate the following warning. 

```
DEFINE_MODULE was set, but no umbrella header could be found to generate the module map
```

This doesn't happen in xcode 14.

### How do we reproduce it?

1. Create the ThirdPartyLib project through tuist.
2. ThirdPartyLib depends on external libraries via Tuist Dependency external.
3. Look at ThirdPartyLib in App Target.
4. When building the app target, a warning occurs in the ThirdPartyLib target and third-party libraries.

### Error log

DEFINE_MODULE was set, but no umbrella header could be found to generate the module map

### macOS version

13.5.2

### Tuist version

3.29.0

### Xcode version

15.0.0

**Comment by mustiikhalil** [comment]
Finding a similar issue within our project, the external dependencies we are using are firebase that uses SPM. We tried searching for the headers but that didn't really work as expected.

**Comment by ammerzon** [comment]
We have the same problem with Firebase as dependency.

**Comment by cristi-lupu** [comment]
I have the same warnings, and as a workaround, I changed the target settings in `Tuist/Dependencies.swift` file:
```swift
let dependencies = Dependencies(
    swiftPackageManager: .init([
        .remote(url: "https://github.com/firebase/firebase-ios-sdk.git", requirement: .exact("10.8.0")),
       ...
    ], targetSettings: [
        "FBLPromises": ["DEFINES_MODULE": false],
        "Firebase": ["DEFINES_MODULE": false],
        "FirebaseAnalyticsWithoutAdIdSupportTarget": ["DEFINES_MODULE": false],
        "FirebaseAnalyticsWithoutAdIdSupportWrapper": ["DEFINES_MODULE": false],
        "FirebaseCoreExtension": ["DEFINES_MODULE": false],
        "FirebaseSessionsObjC": ["DEFINES_MODULE": false],
        "GoogleAppMeasurementWithoutAdIdSupportTarget": ["DEFINES_MODULE": false],
        "GoogleUtilities-AppDelegateSwizzler": ["DEFINES_MODULE": false],
        "GoogleUtilities-Environment": ["DEFINES_MODULE": false],
        "GoogleUtilities-Logger": ["DEFINES_MODULE": false],
        "GoogleUtilities-MethodSwizzler": ["DEFINES_MODULE": false],
        "GoogleUtilities-Network": ["DEFINES_MODULE": false],
        "GoogleUtilities-NSData": ["DEFINES_MODULE": false],
        "GoogleUtilities-Reachability": ["DEFINES_MODULE": false],
        "GoogleUtilities-UserDefaults": ["DEFINES_MODULE": false],
        "third_party-IsAppEncrypted": ["DEFINES_MODULE": false],
        ...
    ]),
    platforms: [.iOS]
)

```

**Comment by leeari95** [comment]
It's too messy. Please fix it.....😭


<img width="642" alt="image" src="https://github.com/tuist/tuist/assets/75905803/985694ce-ce1e-4342-9cc6-5d734e67a25b">
<img width="642" alt="image" src="https://github.com/tuist/tuist/assets/75905803/3e2af5c2-e528-473c-97aa-77f65eb65207">
<img width="661" alt="image" src="https://github.com/tuist/tuist/assets/75905803/c8ee7bbf-234a-42d2-978e-b8e610565eed">
<img width="660" alt="image" src="https://github.com/tuist/tuist/assets/75905803/f2cb3a09-db81-47ac-91b8-b669d6ce78af">

**Comment by fortmarek** [comment]
Hey, everyone 👋 

This PR should finally resolve this issue: https://github.com/tuist/tuist/pull/5909 🙏

**Comment by fortmarek** [comment]
Should be fixed via: https://github.com/tuist/tuist/pull/5909

Let us know if this issue persists in the new release and we can reopen it.

**Comment by fortmarek** [comment]
Reopening as this [PR](https://github.com/tuist/tuist/pull/5916) will re-introduce this issue for _some_ dependencies. The majority of dependencies should still not show this warning, however.
