### ISSUE TITLE
Support multiplatform Targets

### ISSUE THREAD

**Issue by stodirascu** [tuist/tuist#5515]
### What problem or need do you have?

We're developing a multiplatform iOS/tvOS framework, and have 2 demo apps (one iOS, one tvOS) to test it. However, when running `tuist generate` it errors out for the tv app due to the fact that for the framework we can only specify one platform (example project [attached](https://github.com/tuist/tuist/files/13054412/multiplatform.zip)). We've used xcconfig files to make the framework both iOS/tvOS compatible, as you can see here:
<img width="330" alt="image" src="https://github.com/tuist/tuist/assets/111747822/7b2f2587-1869-4355-9bad-5365435e183b">
And when manually linking with the tv app, it builds and runs fine. So I guess it's a limitation of Tuist.

### Potential solution

Would be great if the `Target` struct could receive an array of `Platform`s to accommodate this feature.

We could create a duplicate tvOS framework with the same source files, but that would complicate our release process, since we're creating an xcframework (which supports multiple platforms natively) which most conveniently is built from a single source framework.

### macOS version

13.5.2

### Tuist version

3.29.0

### Xcode version

15

**Comment by kwridan** [comment]
Thanks @stodirascu 

As it happens this work is in progress - @waltflanagan has been chipping away at adding support for this 🎉. A preview of what's coming can be seen here https://github.com/tuist/tuist/pull/5381

**Comment by Vaberer** [comment]
Hello Tuist team, any updates regarding this feature? Thanks

**Comment by waltflanagan** [comment]
Most updates end up in the `#multi-platform-support` channel if you'd like to follow along.  This is a pretty deep refactor of nearly every part of tuist so it's slow going and high risk but we're trying to land it with as few source breaking changes as possible.

**Comment by pepicrft** [comment]
> @waltflanagan I see some PR's got merged in the meantime. Do you know how near we are to a release for this?

Hey @stodirascu. The work was merged already a few releases ago. Have you given it a try?

**Comment by stodirascu** [comment]
Hm, I'm looking at the init for `Target`, and I still see `public init(name: String, platform: ProjectDescription.Platform, ...)`, as in you can't pass an array for platform.

Any guidance on how to set it up?

**Comment by pepicrft** [comment]
You need to pass [an array of destinations](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Target.swift#L75) with all the destinations that you plan to support.

**Comment by stodirascu** [comment]
Right, thank you @pepicrft. That works!
