### ISSUE TITLE
Swift package products with XCTest dependencies can cause module compilation failure

### ISSUE THREAD

**Issue by dcramps** [tuist/tuist#5538]
### What happened?

We have a few apps, and we share some code between them with a private Swift package. This package has a bunch of products, one of which has some utilities that extend `XCTest`:

```
SomePackage
- Foo // some shared code, used in our app's modules
- Bar // some more shared code
- TestTools // some shared XCTest helpers, used in some of our app's test targets
```

Our apps are modular, and most modules need at least one product from our Swift package, so we have a module that contains nothing but a dependency on that package. So our hierarchy looks something like this:

```
FeatureA Project
- FeatureA
    - SPMContainer // gives access to shared code from SomePackage
- FeatureATests
    - FeatureA
    - TestTools // gives access to the shared XCTest helpers
FeatureB Project
- FeatureB
    - SPMContainer // gives access to shared code from SomePackage
- FeatureBTests
    - FeatureB
    - TestTools // gives access to the shared XCTest helpers
SPMContainer Project
    - SomePackage // only contains a dependency on the Swift package
```

This works fine, except for the test targets. When Tuist generates the framework for `SomePackage`, it does not link `TestTools` with `XCTest`, so when we build `FeatureA` or `FeatureB` for testing, we get the following:

```
Testing failed:
	Cannot find 'XCTFail' in scope
	Testing cancelled because the build failed.
```

If I open the generated `SomePackage.xcodeproj`, select the `TestTools` target, and manually link `XCTest`, everything works as it should.

So the fix I came up with is to add `linkerSettings: [.linkedFramework("XCTest")]` to the `TestTools` target in `SomePackage`'s `Package.swift` file, which does work just fine.

So I guess my question is should this editing of the `Package.swift` file be necessary? If I forego Tuist's generation time resolution (which I must stress I absolutely do not want to do) and add the package as a dependency that uses Xcode's SPM implementation, I have no such issues.

ie:
Add a package dependency to the `SPMContainer` project where `Foo` and `Bar` are added to the `SPMContainer` target, and do the same to `FeatureA` and `FeatureB` where `TestTools` are added to `FeatureATests` and `FeatureBTests` targets

### How do we reproduce it?

Unzip the attached sample project. It contains an app configured with Tuist as described above. The `3rd-party` directory mimics what our private Swift Package is. However in the real world this is a GitHub hosted package, not a local one.

Run the following:

```
tuist fetch
tuist test FeatureA
```

And you will see the error I mentioned previously.

[tuist-xctest-example.zip](https://github.com/tuist/tuist/files/13222091/tuist-xctest-example.zip)

### Error log

See above

### macOS version

13.6

### Tuist version

3.28.0, 3.31.0

### Xcode version

15.0.0, 15.0.1

**Comment by fortmarek** [comment]
> So the fix I came up with is to add linkerSettings: [.linkedFramework("XCTest")] to the TestTools target in SomePackage's Package.swift file, which does work just fine.

This is a valid workaround and one we use to.

I honestly have no idea how Xcode can tell in advance if it should link `XCTest` or not. We could link `XCTest` optionally to every target which would probably work but feels wrong 🤔 

Otherwise, there's no indication from the package that it's a testing framework. Other wild ideas:
- We try to find `import XCTest` mention somewhere in the sources – will take some time and can lead to false positives, would rather not do it
- Is there a convention? In tuist, we use `XXXTesting`, I've also seen `TestTools` elsewhere as a name for these. But since packages are from the general tuist community that is not aware of it, I'm not sure if we can rely on any convention here.
- ??? I'm open to ideas 😄

**Comment by dcramps** [comment]
I was also super confused how it just knows to link XCTest when using native SPM. It's a complete mystery.

Definitely agree that optionally linking XCTest is icky, but I think that scanning the sources is a nice idea. That could end up slowing the generator down though. Having to open each file and search through it might take some time, especially in a very large package. If it doesn't use XCTest anywhere, you'd not know until you checked every single file 😢 

I'm really curious if anyone from Stream has run into this. One of the packages where we've hit this issue is in their [StreamChatTestTools](https://github.com/GetStream/stream-chat-swift/blob/develop/Package.swift#L21-L23) framework. They're a Tuist sponsor and I've read one of their blog posts on Tuist usage, so presumably they're still using it.

As for other ideas:

- could this be solved with a plugin? I don't know much at all about them, but maybe it's possible to build a plugin where you can specify that dependency X should link framework Y, and run it as a step after `tuist generate`?
- an additional parameter to the `TargetDependency` functions
```
.external(name: "TestingUtilities", additionalLinkedFrameworks: ["XCTest"])
```
- an additional parameter to the `Target` to do the same
```
Target(
    name: "SomeTestTarget",
    dependencies: [.external(name: "TestingUtilities"), ...],
    additionalLinkedFrameworks: ["TestingUtilities": ["XCTest"]],
    ...
)
```

I am fine to add the `linkerSettings: [.linkedFramework("XCTest")]` to my own `Package.swift` as needed, but for 3rd party dependencies, it may not be as easy to convince someone to do it when it "just works" with Xcode's implementation 🙁

**Comment by shahzadmajeed** [comment]
You can override build settings of your internal swift packages and third party dependencies.. all you need to do is add `ENABLE_TESTING_SEARCH_PATHS=YES` for targets that depend on XCTest and it will work fine. That is what I do for our internal testing support targets..

We could add an explicit `testingSupportTargets` parameter to Dependencies.swift but not sure if people agree to that

**Comment by johnkodes** [comment]
@dcramps How did you solve this in the end for 3rd party dependencies?
