### ISSUE TITLE
Extend `init` command to include the `deploymentTarget` in the generated manifest

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#554]
## Context 🕵️‍♀️

Recently we added support for deployment targets. 

```swift
let target = Target(name: "MyApp", 
                    deploymentTarget: .iOS(targetVersion: "13.1", devices: [.iphone, ipad]))
```

## What 🌱

[This is a follow-up task](https://github.com/tuist/tuist/pull/541#issuecomment-541345823) about extending [the `init` command](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Commands/InitCommand.swift#L128) to include a deployment target attribute in the generated manifest file. 

## Proposal 🎉

Do not add additional parameters to the `init` command. Instead, default the platform most common's destination device and latest OS device.

The following command

```bash
$ tuist init --name demo --platform ios
```

would produce

```
let project = Project(name: "demo",
                      targets: [
                        Target(name: "demo",
                               platform: .iOS,
                               product: .app,
                               bundleId: "io.tuist.demo",
                               deploymentTarget: .iOS(targetVersion: "13.1", devices: [.iphone]),
                               ...
```

**Comment by danyf90** [comment]
I think the current behavior is perfectly fine, and adding a random/arbitrary deployment target wouldn't add much
