### ISSUE TITLE
Test cache not working

### ISSUE THREAD

**Issue by timbaev** [tuist/tuist#5545]
### What happened?

The `tuist test` command should cache test results and run tests only on changed targets. This information is provided in the [documentation](https://docs.tuist.io/commands/test#caching).

### How do we reproduce it?

1. Download sample project: [app_with_test_plan.zip](https://github.com/tuist/tuist/files/13250669/app_with_test_plan.zip)
2. Run unit tests with a test plan: `tuist test App --test-plan All`. Three tests will pass successfully.
3. Rerun tests: `tuist test App --test-plan All`. All three tests will run even though no changes have been made to the code.

### Error log

```sh
All tests
AppTests.xctest
AppTests
    ✔ test_twoPlusTwo_isFour (0.001 seconds)
All tests
FeatureBarTests.xctest
FeatureBarTests
    ✔ testHello (0.001 seconds)
All tests
FeatureFooTests.xctest
FeatureFooTests
    ✔ testHello (0.001 seconds)
Test Succeeded
Tests Passed: 0 failed, 0 skipped, 3 total (0.006 seconds)
The project tests ran successfully
```

### macOS version

14.1

### Tuist version

3.31.2

### Xcode version

15.0.1

**Comment by fortmarek** [comment]
Hey!

This should have been fixed in: https://github.com/tuist/tuist/pull/6722

Let us know if you are still running into this.
