### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by cdoky** [tuist/tuist#5547]
### What problem or need do you have?

```shell
dyld: Library not loaded: /usr/lib/swift/libswift_Concurrency.dylib
  Referenced from: /usr/local/bin/tuist
  Reason: image not found
[1]    2689 abort      tuist
```

### macOS version

11.7.1

### Tuist version

3.31.2

### Xcode version

13.2.1

**Comment by fortmarek** [comment]
Hey, a lot of things are missing here. We need reproducible steps to debug this.

**Comment by cdoky** [comment]
I dot know what infomation missing, 
I guess this error is caused by the low version of my system and xcode, 
but my computer can no longer install a higher version of the system

**Comment by danyf90** [comment]
Xcode 14.1 or above is required
