### ISSUE TITLE
Cache & Cocoapods: Regeneration of workspace on cache warm

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#5561]
### What problem or need do you have?

My project uses Cocoapods to connect external dependencies. For some reason I can't switch to SPM.

To work on the project, I first run two commands: `tuist generate && pod install`

----

Now I want to add caching of local targets declared in the `Project.swift` manifest.

I call the `tuist cache warm` command and am faced with the **problem of not being able to compile the targets due to the fact that the pod-target dependency could not be found**.

### Potential solution

Based on the logs and sources (`CacheController.swift`), I realized that the reason is that when `cache warm` is launched, tuist regenerates the project to obtain the graph:
```swift
  func cache(
            config: Config,
            path: AbsolutePath,
            cacheProfile: TuistGraph.Cache.Profile,
            includedTargets: Set<String>,
            dependenciesOnly: Bool
        ) async throws {
            let generator = generatorFactory.cache(
                config: config,
                includedTargets: includedTargets,
                focusedTargets: nil,
                cacheOutputType: artifactBuilder.cacheOutputType,
                cacheProfile: cacheProfile
            )
            let (_, graph) = try await generator.generateWithGraph(path: path) // 👀
```

Is regeneration really necessary when we could just load the current graph? Like this:
```swift
let graph = try await generator.load(path: path)
```

It seems to me that this should fix the problem of pre-compiling targets that have built-in dependencies outside the tuist environment.

---- 

I was unable to deploy Tuist to test this hypothesis :c

### macOS version

13.6.1

### Tuist version

3.31.2

### Xcode version

14.3.1

**Comment by danyf90** [comment]
Yes it is necessary, tuist needs to know the graph to be able to cache, hence it can't cache if you use CocoaPods.
If you want to use cache, unfortunately you need to switch away from CocoaPods (which I strongly suggest regardless of the caching thing)
