### ISSUE TITLE
Asset issue with mergeable libraries 

### ISSUE THREAD

**Issue by Banck** [tuist/tuist#5570]
### What happened?

Hello!
There is a crash when accessing to Image in dynamic framework which hasAsset and has flag **Build Mergeable Library** (**mergeable: true**) and application has flag **Create merged binary** (**mergedBinaryType: .automatic**)

I've created a simple example: Application + uUI dynamic framework with asset.
uUI has mergeable: true, Application has mergedBinaryType: .automatic.

UUIAsset.successIcon.image crash app
<img width="1197" alt="image" src="https://github.com/tuist/tuist/assets/6259254/23a85b3f-7131-497e-9ba6-4f87ff54bfa3">

[TuistTestMergeable.zip](https://github.com/tuist/tuist/files/13350854/TuistTestMergeable.zip)

If change **mergeable** to **false** in **uUI** - everything is fine

### How do we reproduce it?

1. Use the attached project
2. tuist generate
3. Run project

### Error log

uUI/TuistAssets+UUI.swift:48: Fatal error: Unable to load image asset named successIcon.

### macOS version

14.1.1

### Tuist version

3.31.2

### Xcode version

15.0.1

**Comment by Banck** [comment]
@AlbGarciam Hello!  
Sorry for bothering you, but as I see you made a [mergeable libraries feature](https://github.com/tuist/tuist/pull/5351)
Have you encountered such an issue or maybe you know what could be wrong?
Thanks!

**Comment by AlbGarciam** [comment]
@Banck whenever you make a framework to behave as a mergeable it treats the resources like a static framework where you need a bundle.

With mergeables the bundle is embedded within the framework itself. So the framework does not contain any resource

Hope that helps ☺️

**Comment by Banck** [comment]
> @Banck whenever you make a framework to behave as a mergeable it treats the resources like a static framework where you need a bundle.
> 
> With mergeables the bundle is embedded within the framework itself. So the framework does not contain any resource
> 
> Hope that helps ☺️

So seems tuist has to generate bundle for dynamic framework if it's marked as mergeable, but currently it's doesn't do it

**Comment by AlbGarciam** [comment]
no, try to archive your mergeable library, you'll find that there's a bundle with the same name of your library embedded within your library.

**Comment by AlbGarciam** [comment]
Guess we could add a feature to do this. @pepicrft what are your thoughts on this?

**Comment by fortmarek** [comment]
> So seems tuist has to generate bundle for dynamic framework if it's marked as mergeable, but currently it doesn't do it

Yeah, that feels like a bug, @Banck would you want to have a look at adjusting the logic? We can update one of our fixtures in `tuist/fixtures` to test this scenario and ensure that the project still builds after.

**Comment by IvanIpatov** [comment]
I have the same problem

**Comment by IvanIpatov** [comment]
Hello everyone. Have you fixed this bug yet? I have the same bug

**Comment by Banck** [comment]
It was my bad. Apparently something was configured incorrectly. Its OK now

**Comment by tackgyu** [comment]
> It was my bad. Apparently something was configured incorrectly. Its OK now

Hi, can you share the corrections you made on this one? 
We're experiencing the same issue and hope to see our configuration is not set appropriately.

**Comment by tackgyu** [comment]
>It was my bad. Apparently something was configured incorrectly. Its OK now

@Banck Hi, can you share the corrections you made on this one?
We're experiencing the same issue and hope to see our configuration is not set appropriately.
