### ISSUE TITLE
Cannot initialize TargetType from invalid String value macro

### ISSUE THREAD

**Issue by KostyaGitWoddi** [tuist/tuist#5574]
### What happened?

cannot fetch [TCA](https://github.com/pointfreeco/swift-composable-architecture)

### How do we reproduce it?

add https://github.com/pointfreeco/swift-composable-architecture as package dependency and fetch it

### Error log

Localized description: The data couldn’t be read because it isn’t in the correct format.
    - Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize TargetType from invalid String value macro", underlyingError: nil))

### macOS version

14.0

### Tuist version

3.22.0

### Xcode version

15.0.1

**Comment by pepicrft** [comment]
@KostyaGitWoddi this should be fixed in the latest version of Tuist, Tuist 3.33.0. Please, give it a shot, and feel free to reopen the issue if the problem persists on your end.
