### ISSUE TITLE
>=3.30.0: `ProjectDescriptionHelpers` fail to build on `generate`?

### ISSUE THREAD

**Issue by itsthejb** [tuist/tuist#5586]
### What happened?

I have just been looking at upgrading to the latest version, and am encountering `generate` errors related to `ProjectDescriptionHelpers` on >= 3.30.0. It would seem that `generate` is not reliably (re-)building `ProjectDescriptionHelpers` post 3.30.0

### How do we reproduce it?

Note do not have a recreation project right now! Here's what happens with our project:

* `tuist local tuist local 3.29.0`
* `tuist generate -p <some module>`
* Succeeds
* `tuist local tuist local 3.30.0` (or greater)
* `tuist generate -p <some module>`
* Fails

### Error log

```
❯ tuist generate -n -p <the module>
Resolved cache profile 'Development' from Tuist's defaults
The 'swift' command exited with error code 1 and message:
<the module>/Workspace.swift:2:8: error: no such module 'ProjectDescriptionHelpers'
import ProjectDescriptionHelpers
       ^
```

The source of the error is not always the Workspace. Can also be:

```
❯ tuist generate
Resolved cache profile 'Development' from Tuist's defaults
The 'swift' command exited with error code 1 and message:
<some child module>/Project.swift:2:8: error: no such module 'ProjectDescriptionHelpers'
import ProjectDescriptionHelpers
       ^
```

### macOS version

14.1.1 (23B81)

### Tuist version

3.30.0

### Xcode version

15.0.1

**Comment by danyf90** [comment]
Not reproducible
