### ISSUE TITLE
Ideas backlog

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#56]
## Context 🕵️‍♀️
This issue contains a backlog of ideas with high potential to become part of xpm in the future.

## What 🌱
- Tasks definition (i.e. Sake)
- Certificates management
- Apps publishing from the terminal

**Comment by ollieatkinson** [comment]
Provide a mechanism to include code into each Project.swift file. This feature would mimic how buck uses its `includes`. See: https://github.com/facebook/buck/tree/8d699a924d67a258b301c5f0d7b4eec3f8c23bbb/test/com/facebook/buck/parser/testdata/parser_with_method_overrides

`.buckconfig` specifies the include file (BUILD_DEFS)
`BUILD_DEFS` is the python code which it is defining and will include in each `BUCK` file 
`BUCK.fixture` (or `BUCK`, aka their version of the Project.swift) uses the new function defined in `BUILD_DEFS`

**Comment by zdnk** [comment]
Sake seems dead to me - unfortunately.

**Comment by pepibumur** [comment]
> Sake seems dead to me - unfortunately.
What do you mean @zdnk ?

**Comment by pepibumur** [comment]
Yep @zdnk. What do you think about tuist adding that feature?

**Comment by pepibumur** [comment]
We have now a public Trello board with a list where all these ideas are https://trello.com/b/DN6HvDzW/tuist
