### ISSUE TITLE
Can't build a test target with Nimble dependency

### ISSUE THREAD

**Issue by Bogdan-Belogurov** [tuist/tuist#5601]
### What problem or need do you have?

After updating the tuist to `3.33.3` I can't build a test target with `Nimble` dependency.
Maybe you know how to solve this issue?

```
Undefined symbols for architecture arm64:
  "_$s6Nimble10beLessThanyAA7MatcherVyxGxSgSLRzlF", referenced from:
      _$s14Target022ServiceC0C4specyyFZyyXEfU_yyXEfU3_yycfU14_ in file.o
      _$s14Target014ServiceC0C4specyyFZyyXEfU_yyXEfU1_yyXEfU16_yyXEfU_yycfU_ in file.o

etc.
```

![image](https://github.com/tuist/tuist/assets/39379705/0f740b26-1d44-437e-9f40-900d40a8802f)

### macOS version

31.3.1

### Tuist version

3.33.3

### Xcode version

14.3

**Comment by danyf90** [comment]
If there is a bug report template, it should be followed -> Not reproducible.
If you have a reproducible project, please reopen the ticket
