### ISSUE TITLE
Generate Scheme for all UnitsTests in Workspace

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#5636]
### What problem or need do you have?

I have workspace generated by tuist. It have follow structure:
```
Workspace
- App Project
     - Application Target
     - UnitTests Target
     - UITests Target
- Modules/ 
   - ModuleA Project
       - Framework target
       - UnitTests Target
   - ModuleB Project
       - Framework target
       - UnitTests Target 
```

I want to create scheme that will contain all UnitTests targets from all projects of my workspace

### macOS version

13.6.1

### Tuist version

3.0.0

### Xcode version

14.3

**Comment by Ernest0-Production** [comment]
> Please follow the template and provide a reproducible project.
> 
> Don't we already have a `XXX-Workspace` Scheme which is exactly that?

I apologize for the misunderstanding. My issue is not a problem, but a question.

I know that tuist has something like `GenerationOptions` arguments in `Project` and `Workspace` models that allow you to generate a schema to combine all the test targets of a project or workspace.

**But they have limited functionality.**
In `Workspace.swift` you can enable schema generation from **all** tests.
The problem is that absolutely all tests (both ui and unit) will be there.
I need the ability to generate a scheme only from unit tests in order to run them at once.

**Comment by danyf90** [comment]
makes sense, I think we can add a GenerationOption for it 👍

**Comment by Ernest0-Production** [comment]
It seems to me that this requires a more complex and flexible solution, rather than an incremental implementation of certain conditions described in the `ProjectDescription`.

I think it would be very cool to also have one entry point before project generation (aka hook), providing the ability to get an initialized `Workspace` instance with the ability of modifying it in a general way:
```swift
// GenerateHook.swift
import ProjectDescriptionHelpers

let hook = GenerateHook { workspace, interceptor in 
     // Add extra-targets
     let unitTests = workspace.projects.flatMap(\.targets).filter { $0.product = .unitTests }
     let allUnitTestsScheme = Scheme(name: "All Unit Tests", testAction: .testTargets(unitTests))
     interceptor.addScheme(allUnitTestsScheme)

     // Pre-generate some files
     for target in workspace.projects.flatMap(\.targets) { 
         for script in target.scripts where script.name == "SwiftGen" { 
                fileManager.createFile(at: script.inputPath, content: "// Created from Tuist")
         }
     }

     // Conventions & additional validations
     let incorrectFeaturesNames = workspace.projects
          .filter { $0.path == .relativeTo("Feature/")
          .filter { $0.name.hasSuffix("Feature") }

     if !incorrectFeaturesNames.isEmpty { 
        interception.failure(with: "Feature should have suffix Feature. Incorrect projects: \(incorrectFeaturesNames)")
    }
}

```

**Comment by pepicrft** [comment]
@Ernest0-Production Tuist already provides an [API](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/Workspace.swift#L33) to define your custom schemes. I'd suggest using that API instead of incorporating that behavior into the Tuist core. If we incorporate specific use cases like this one, we'll have a complex tool. That's why we provide that API, it's a escape hatch for scenarios like this, for users like you to take control and decide how you'd like to configure your schemes.
