### ISSUE TITLE
Not found some of the headers from external dependencies

### ISSUE THREAD

**Issue by muukii** [tuist/tuist#5638]
### What problem or need do you have?

while using specific external dependencies that rely on C implementation and headers, Tuist won't include the headers so that fails on building.

here is the reproducing project
https://github.com/muukii/tust-reproduce-build-error

### macOS version

14.1.1

### Tuist version

3.35.1

### Xcode version

15.0.1

**Comment by fortmarek** [comment]
Closing as a duplicate of https://github.com/tuist/tuist/issues/5320

You can use workarounds mentioned in that issue or contribute back with Danielle's suggestion 🙏
