### ISSUE TITLE
Internal Macro dependency. 

### ISSUE THREAD

**Issue by NSStudent** [tuist/tuist#5639]
### What happened?

After this merge https://github.com/tuist/tuist/pull/5587 I try to upgrade my project to use the last version of TCA.

The TCA package uses the CasePath Macro internally and the Tuist project configuration can't solve this dependency.

### How do we reproduce it?

- Use the Fixture project `app_with_spm_dependencies`
- In the Appkit.swift file add this reducer code.

```
@Reducer
struct Counter {
  struct State: Equatable {
    var count = 0
  }

  enum Action {
    case decrementButtonTapped
    case incrementButtonTapped
  }

  var body: some Reducer<State, Action> {
    Reduce { state, action in
      switch action {
      case .decrementButtonTapped:
        state.count -= 1
        return .none
      case .incrementButtonTapped:
        state.count += 1
        return .none
      }
    }
  }
}
```

- Try to build the app target 

In your Xcode you can see this error (I expand the macro implementation to show the code with the error)
![image](https://github.com/tuist/tuist/assets/895162/65f5e422-0663-4516-8e14-f0c61eb80bf8)
 

### Error log

`External macro implementation type 'CasePathsMacros.CasePathableMacro' could not be found for macro 'CasePathable()'`

### macOS version

14.1.2 (23B92)

### Tuist version

3.35.2

### Xcode version

Version 15.0.1 (15A507)

**Comment by waltflanagan** [comment]
Thanks for the bug report!  It looks like our [logic](https://github.com/tuist/tuist/blob/c2d3d1731074a303a8b4b563f5f47673f3f3f113/Sources/TuistGenerator/Generator/ConfigGenerator.swift#L315) to generate the `-load-plugin-executables` swift flag does not traverse to transitive dependencies currently.  You should be able to work around this bug by adding explicit an explicit dependency to `CasePaths` as we do in the `framework_with_native_swift_macro` fixture.

**Comment by ParkTaeGyu** [comment]
Is there anyone who followed the above procedure and it doesn't work? That's me 😢 

#macOS version
14.1.1(23B81)

#Tuist version
3.36.5

#Xcode version
Version 15.0 (15A240d)

**Comment by pepicrft** [comment]
[This PR](https://github.com/tuist/tuist/pull/5772) fixes the issue.
