### ISSUE TITLE
--test-targets does not accept more than two targets

### ISSUE THREAD

**Issue by nhaarman** [tuist/tuist#5648]
### What happened?

--test-targets does not accept more than two targets

### How do we reproduce it?

This command works:

```
tuist test --test-targets "MyTarget/MyTestClass1 MyTarget/MyTestClass2"
```

This command doesn't:

```
tuist test --test-targets "MyTarget/MyTestClass1 MyTarget/MyTestClass2 MyTarget/MyTestClass3"
```

### Error log

```
Error: The value 'MyTarget/MyTestClass1 MyTarget/MyTestClass2 MyTarget/MyTestClass3' is invalid for '--test-targets <test-targets>': Invalid test identifiers MyTarget/MyTestClass1 MyTarget/MyTestClass2 MyTarget/MyTestClass3. The expected format is TestTarget[/TestClass[/TestMethod]].
```

### macOS version

14.0

### Tuist version

3.35.2

### Xcode version

15.0.1

**Comment by fortmarek** [comment]
Hey 👋 

You shouldn't put the list into `""` as that's treated as a single target. Instead you can run:
```bash
tuist test --test-targets MyTarget/MyTestClass1 MyTarget/MyTestClass2
```

Which should work (I've just tested this locally)
