### ISSUE TITLE
previously working external dependency is failing now - unclear on how to resolve it

### ISSUE THREAD

**Issue by heckj** [tuist/tuist#5671]
### What problem or need do you have?

We have tuist 3.35.5 installed, and previously had everything working - came back to a project that had been sitting a year, and ran "tuist fetch" and its failing to properly parse the `Tuist/Dependencies.swift` file. The error we're seeing is:

```
/Users/heckj/src/yswift/examples/Tuist/Dependencies.swift:4:26: error: cannot convert value of type '[Any]' to expected argument type 'SwiftPackageManagerDependencies?'
    swiftPackageManager: [
                         ^
/Users/heckj/src/yswift/examples/Tuist/Dependencies.swift:5:10: error: type 'Any' has no member 'remote'
        .remote(url: "https://github.com/y-crdt/yswift", requirement: .upToNextMajor(from: "0.1.0")),
        ~^~~~~~
/Users/heckj/src/yswift/examples/Tuist/Dependencies.swift:5:72: error: cannot infer contextual base in reference to member 'upToNextMajor'
        .remote(url: "https://github.com/y-crdt/yswift", requirement: .upToNextMajor(from: "0.1.0")),
                                                                      ~^~~~~~~~~~~~~
```

This matches the pattern in the documentation, and I tried a number of variants, but to no avail. I did see in the latest/new tutorial there looked to be a requirement for a `Package.swift` - and I wasn't sure if that was replacing the Dependencies.swift or not for Swift Package Manager packages.

Are there other/more examples that I could borrow from to understand how to declare this, or is there something obvious I'm missing here?

### macOS version

14.1.2

### Tuist version

3.35.5

### Xcode version

Xcode 15.0.1

**Comment by danyf90** [comment]
Please follow the template and provide a reproducible project

**Comment by danyf90** [comment]
Have you tried doing `tuist edit` and playing with autocomplete?

**Comment by heckj** [comment]
Thanks @danyf90 - wasn't aware of tuist edit. I did finally find an example project that mapped to what I was after (https://github.com/Saik0s/Whisperboard/blob/main/Tuist/Dependencies.swift), and resolved the deprecated format. Very much appreciate the quick response here!

The documentation on the "current" site is pretty woefully out of date for explaining how to set up external dependencies that leverage Swift Package Manager. I migrated from the original docs style example:

```
let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/y-crdt/yswift", requirement: .upToNextMajor(from: "0.1.0")),
    ],
     platforms: [.iOS]
 )
```

To a more explicitly typed result - as well as a newer package declaration style, which made a huge difference:
```
import ProjectDescription

let packages: [Package] = [
    .package(url: "https://github.com/y-crdt/yswift", from: "0.1.0"),
]

let dependencies = Dependencies(
    swiftPackageManager: SwiftPackageManagerDependencies(
        packages
    ),
    platforms: [.iOS]
)
```
