### ISSUE TITLE
Generated macro target should have SKIP_INSTALL set to YES by default

### ISSUE THREAD

**Issue by ainopara** [tuist/tuist#5676]
### What happened?

When archiving an iOS app, the macro target is included in the xcarchive file, which may prevent the archive from being used for export. This issue can be fixed by manually adding build setting `["SKIP_INSTALL": "YES"]`  the macro target.

### How do we reproduce it?

1. Craete an iOS target and add a macro dependency in Dependencies.swift
2. archiving the project
3. the generated archive could not be exported for app store because it contains an macOS executable

### Error log

error log when exporting with xcodebuild
```
error: exportArchive: exportOptionsPlist error for key "method": expected one of {}, but found development
```

### macOS version

14.0

### Tuist version

3.35.2

### Xcode version

15.0

**Comment by pepicrft** [comment]
@ainopara could you update to the latest version and try again? The issue [was fixed last week](https://github.com/tuist/tuist/pull/5641)

**Comment by ainopara** [comment]
Great, I will upgrade my tuist version and remove my workaround. Thanks for replying.
