### ISSUE TITLE
Scheme for framework should be testable

### ISSUE THREAD

**Issue by vytis** [tuist/tuist#569]
**Describe the bug**
A scheme for the framework should have all relevant unit test bundles added as testables i.e. it should be possible to do CMD+U on a framework target.

**To Reproduce**

Setup of a project:
1. Add a Framework target
2. Add a Test target that depends on framework target from step 1.

Steps to reproduce the behaviour:
1. `tuist generate`
2. `tuist focus`
2. Tap Product -> Test or CMD-U

**Expected behavior**
All tests in relevant schemes should run

**Additional context**

I assume the logic should be to add those schemes that depend on the target. Not completely sure how it should be handled when we have a host app also?

I would be interested to try to fix it myself, but need to be sure if that is something you think is a good addition and what the logic should exactly be.

**Comment by kwridan** [comment]
Hi @vytis, 

You can create a custom scheme in order to customise it to your needs, see [Scheme](https://docs.tuist.io/usage-2-projectswift#scheme) - and an example in this [fixture](https://github.com/tuist/tuist/blob/master/fixtures/ios_app_with_custom_scheme/App/Project.swift).

That said, this seems to be quite a common request as such may make sense to provide the ability to tweak the default behaviour.

I've put forward a proposal for that here if you're interested:
https://github.com/tuist/tuist/issues/458

Happy to guide & assist you through it if you're interested in contributing :)

**Comment by vytis** [comment]
Thanks for answer @kwridan! I have tried added a custom scheme with the same name as my framework target and it seems to override the default configuration. Not sure if it's intended to be this way, but the proposed approach worked.

However it seems that this should be the default behaviour - I don't think there are any disadvantages to adding testables to framework target. As a data point, if you create a new framework project with Xcode the test bundle is added to testables by default.

The points raised in your proposal are totally valid, but this issue seems quite a bit simpler than full-blown scheme customisation.

I have looked into how this could be implemented and was thinking of changing this function - https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/SchemesGenerator.swift#L156 to wire up test bundles with their dependent targets. Would that be a good place?

**Comment by kwridan** [comment]
Thanks for the follow up @vytis !

Indeed `SchemeGenerator` is the right component for this. I agree revisiting the defaults here may be needed.

May help for us to talk through some examples to clarify the use cases:

- Project
  - TargetA _(Application)_
      - Dependencies: [TargetB]
  - TargetATests _(Unit Tests)_
      - Dependencies: [TargetA]
  - TargetAUITests _(UI Tests)_
       - Dependencies: [TargetA]
  - TargetB _(Framework)_
       - Dependencies: [] 
  - TargetBTests _(Unit Tests)_
       - Dependencies: [TargetB]

Currently Tuist generates the following schemes:

- TargetA
   - build: [TargetA]
   - test: []
- TargetATests
   - build: [TargetATests]
   - test: [TargetATests]
- TargetAUITests
   - build: [TargetAUITests]
   - test: [TargetAUITests]
- TargetB
   - build: [TargetB]
   - test: []
- TargetBTests
   - build: [TargetBTests]
   - test: [TargetBTests]

We could make the scheme testables a bit smarter such that the generated schemes become:

- TargetA
   - build: [TargetA]
   - test: [TargetATests, TargetAUITests]
- TargetATests
   - build: [TargetATests]
   - test: [TargetATests]
- TargetAUITests
   - build: [TargetAUITests]
   - test: [TargetAUITests]
- TargetB
   - build: [TargetB]
   - test: [TargetBTests]
- TargetBTests
   - build: [TargetBTests]
   - test: [TargetBTests]

Is that what you had in mind?

(cc: @ollieatkinson I recall the "Project" scheme did something similar but was removed resolve an overhead it caused when building Carthage projects https://github.com/tuist/tuist/pull/303 - was the issue the fact it was an additional scheme?)

**Comment by pepibumur** [comment]
You raised a very interesting point here @vytis. I think Tuist should do its best effort to get a project that just works. Having to know about implementation details, and configuring the schemes is, is what makes Xcode not as nice as it could be.

What I would do is add a new option to the `TuistConfig` where the users can opt-in to this feature. Something along the lines of:

```swift
// TuistConfig.swift

let config = TuistConfig(
  generationOptions: [
    .schemeStrategies([.addDependantTestBundles])
  ]
)
```

When that value is set to true, we can get the list of test targets that depend on the one whose scheme is being created, and add them to the test action.

**Comment by ollieatkinson** [comment]
@kwridan You're right that the `Project` scheme played funny with Carthage, however the framework being testable will not introduce any additional schemes so I think we would be OK here.

Why would we not make this setting the defacto behaviour? We currently infer settings for UI Test Targets in the same way - I think that we should be able to implicitly link them up for you. If we cannot determine which one to link, we can introduce a warning to let you know there was trouble and some steps about creating a custom scheme.

**Comment by pepibumur** [comment]
> Why would we not make this setting the defacto behaviour? We currently infer settings for UI Test Targets in the same way - I think that we should be able to implicitly link them up for you. If we cannot determine which one to link, we can introduce a warning to let you know there was trouble and some steps about creating a custom scheme.

Thinking about it again, I agree with you on making this the defacto behavior. When we generate the projects, we can put the schemes in 2 groups:

- The schemes generated by Tuist.
- The schemes defined by the user.

In case of the first group I'd be opinionated and generate something that **works**. In case the user is not happy with the generated scheme they can define their own scheme or open an issue on this repository so that we can reconsider what we defined as the defacto behavior.

**Comment by kwridan** [comment]
@vytis would you still be interested in pursuing this?

Looks like there's more or less agreement on making the default schemes testable per your suggestion.

Does the example I provided in https://github.com/tuist/tuist/issues/569#issuecomment-544608529 match your expectations on how this would work?

**Comment by vytis** [comment]
@kwridan yes, I could try tackling this. The comment describes exactly what I had in mind!
