### ISSUE TITLE
Generate Project.swift from existing Xcodeproj

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#57]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to convert an existing project to XPM, this would generally be a one-shot thing and would be done to easier on-board projects.

**Describe the solution you'd like**

An additional command for xpm to migrate an existing xcodeproj

```sh
xpm migrate
```

This would also have to resolve any dependencies, and would be great if it can traverse for other nested projects and automatically convert them too.

e.g.

```
.
├── Modules
│   ├── Core
│   │   └── Core.xcodeproj
│   ├── FeatureA
│   │   └── FeatureA.xcodeproj
│   └── Result
│       └── Result.xcodeproj
├── MyApp.xcodeproj
└── MyApp.xcworkspace
```

migrates to

```
.
├── Modules
│   ├── Core
│   │   ├── Core.xcodeproj
│   │   └── Project.swift
│   ├── FeatureA
│   │   ├── FeatureA.xcodeproj
│   │   └── Project.swift
│   └── Result
│       ├── Project.swift
│       └── Result.xcodeproj
├── MyApp.xcodeproj
├── MyApp.xcworkspace
├── Project.swift
└── Workspace.swift
```

**Describe alternatives you've considered**
The alternative is not integrating this directly into xpm but having an alternative tool which can be used to perform the migration.

**Comment by pepibumur** [comment]
This is a good idea @ollieatkinson. I'll keep it in the backlog and give it a shot once we have the first version of xpm published.

**Comment by pepibumur** [comment]
Hey @ollieatkinson I don't think this is feasible because Tuist is strong in conventions so we won't be able to map from Xcode projects to Tuist projects easily. I'm closing this.
