### ISSUE TITLE
Remove `Tuist/Dependencies.swift`

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5712]
### What problem or need do you have?

We will remove `Tuist/Dependencies.swift` in Tuist 4 in favor of `Tuist/Package.swift`, with which dependency updaters like Dependabot are compatible. Note that we also need to tackle [this other issue](https://github.com/tuist/tuist/issues/5537) to make sure that the `Package.swift` is editable from the project that we generate with `tuist edit`. Otherwise this change will come with some DX regressions for users.

### Potential solution

Remove `Tuist/Dependencies.swift` and with it all the logic for pulling dependencies using Carthage.

**Comment by shahzadmajeed** [comment]
Could you clarify please what will happen to the stuff we do in `Tuist/Dependencies.swift`? We still want to be able to control dependencies i.e., their build settings, override product types, add schemes, and some conditional logic of when to include which swift package etc.

**Comment by pepicrft** [comment]
Those will be moved to `Tuist/Config.swift`. The configuration API is the same, it'll just live in a different file.

**Comment by fortmarek** [comment]
Correct me if I'm wrong, but I think we decided to use `Workspace.swift` instead as you can't import `ProjectDescriptionHelpers` inside `Config.swift`

**Comment by pepicrft** [comment]
> Correct me if I'm wrong, but I think we decided to use Workspace.swift instead as you can't import ProjectDescriptionHelpers inside Config.swift

You are right. Do you recall why helpers are needed to define the configuration for packages?

**Comment by shahzadmajeed** [comment]
For me, most of my schemes, configurations and build settings live in helpers framework and I would like to continue using those for my dependencies as well.

**Comment by pepicrft** [comment]
> For me, most of my schemes, configurations and build settings live in helpers framework and I would like to continue using those for my dependencies as well.

But have you extracted content from `Dependencies.swift` into helpers? If so, for which reason?

**Comment by danyf90** [comment]
> But have you extracted content from `Dependencies.swift` into helpers? If so, for which reason?

I think `targetSettings` is a good candidate to be shared between project and dependencies

**Comment by shahzadmajeed** [comment]
Exactly target settings and other stuff. 

For my project, any source code I'm compiling is treated the same way whether it's internal code or dependencies. We apply same build settings to all targets

**Comment by haifengkao** [comment]
I really don't like the new design. 
The old design allows me to put Swift module descriptions in a single file

```swift
public extension Module {
    static var Quick: Module {
        .package(.init(name: "Quick", url: "https://github.com/Quick/Quick", requirement: .upToNextMajor(from: "6.0.1"), unitTestTool: true))
    }

    static var Nimble: Module {
        .package(.init(name: "Nimble", url: "https://github.com/Quick/Nimble", requirement: .upToNextMajor(from: "11.2.1"), unitTestTool: true))
    }
}
```
The build setting `unitTestTool`, package url, package name are all stored in a single data structure. 

The new package.swift design forces me to put package url in package.swift
and the rest in dependency.swift. 
If I want to remove a swift package, I have to remove the settings in package.swift and dependency.swift. I don't think it's a good design.

**Comment by pepicrft** [comment]
> I think targetSettings is a good candidate to be shared between project and dependencies

Gotcha. I'm not 100% sure `Workspace.swift` is the right place for that configuration to live in. It forces users to create a `Workspace.swift` for the sake of doing dependency configuration overrides. I believe the configuration needs to be close to where the definition lives, in the `Package.swift`, and that it's feasible. We can allow an API along the lines of:

```swift
// Package.swift

#if TUIST
import ProjectDescription
import ProjectDescriptionHelpers

let packageSettings = PackageSettings(....)
#endif

let package = Package(...)
```
When the SPM resolves the package, since the `TUIST` variable is not set, the compiler will skip that piece of the code behaving as a regular package. When Tuist needs to read the overrides, it'll compile the file with that variable set and the package settings will be serialized into a JSON and output for Tuist to read it.

> If I want to remove a swift package, I have to remember to remove the settings in both package.swift and dependency.swift. I don't think it's a good design.

There needs to be a perfect design. The old design prevented dependency auto-updating tools from working, so we decided to trade some of the ergonomics of our DSL to gain that ability, which we believe it's important for teams to keep up with dependencies and prevent security incidents from happening due to outdated dependencies. Please, if you have a suggestion to achieve a better trade-off here, let us know.

**Comment by shahzadmajeed** [comment]
I suggest we create some sort of system diagrams to showcase our intended system and the use cases we think we are fulfilling. The we can take it to tuist users to ask if there is any additional use case we might be missing. 

In general, I consider ProjectDescriptionHelpers to contain all metadata for my projects including my dependencies and I would want to use it everywhere I can (all manifest tuist manifest files)

**Comment by pepicrft** [comment]
> I suggest we create some sort of system diagrams to showcase our intended system and the use cases we think we are fulfilling. Then we can take it to tuist users to ask if there is any additional use case we might be missing.

Sounds a good idea. Would you like to take this on?

**Comment by shahzadmajeed** [comment]
I can but that might turn out to be my desired system that could be different from what core team has planned for tuist 4.0 - maybe we can meet on zoom to discuss the vision and goals?

**Comment by fortmarek** [comment]
> I believe the configuration needs to be close to where the definition lives, in the Package.swift, and that it's feasible. We can allow an API along the lines of

Yeah, this should be feasible. The downside is worsened discoverability but I do think it's better than to put the configuration in `Workspace.swift` that a lot of users don't have. I'm in favor of this one.

**Comment by fortmarek** [comment]
Resolved via https://github.com/tuist/tuist/pull/5812
