### ISSUE TITLE
Make `ProjectDescription` model constructors private and use static interfaces instead

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5714]
The initialization of `ProjectDescription` models from projects manifests inconsistencies. Some have to use the `init` constructor. Others use static functions defined on those models, which have their init private. We should be consistent and choose the option that's the most descriptive and ergonomic, which I believe is the static interface.

**Comment by fortmarek** [comment]
Resolved via: https://github.com/tuist/tuist/pull/5843
