### ISSUE TITLE
use of a cpp compiled library and modulemap? 

### ISSUE THREAD

**Issue by demhademha** [tuist/tuist#5722]
### What problem or need do you have?

Our application uses the liblouis c/cpp library to translate text to braille. We use a .modulemap so we can use the API in swift. One of our internal modules then relys on this liblouis.a file to operate. The UI then relys on this driver so it can operate: 
UI > driver > liblouis.a 
[a.txt](https://github.com/tuist/tuist/files/13775129/a.txt)
 
We are attempting to move from xcode to tuis as we believe it will allow for better developer productivity 

### Potential solution

Not sure

### macOS version

  14.3 beta 

### Tuist version

 3.36.5

### Xcode version

15.2

**Comment by pepicrft** [comment]
Hi @demhademha, would you mind including a project where we can reproduce the issue, and more details about the issue that you are facing?

**Comment by demhademha** [comment]
Here is a project 
TuistDriver depends on the header, modulemap and the static file. I have included the c file for your convenience but imagine we did not have access to that, (only the static library) 
Then TuistKit depends on this driver to function, (it calls the functions from the header) 
then the UI depends on the TuistKit 
how would we do something with tuist configuration script? 
I hope this explanation is making more sense for your benefit

**Comment by demhademha** [comment]
[demmo.zip](https://github.com/tuist/tuist/files/13780805/demmo.zip)

**Comment by pepicrft** [comment]
This is sufficient. Thanks @demhademha. We'll investigate and I'll report back when the issue is fixed.

**Comment by kwridan** [comment]
Hi @demhademha were asking about how to use static libraries in general or that there was an issue when attempting to migrate to Tuist? 

I believe the [`.library()`](https://tuist.github.io/tuist/main/documentation/projectdescription/targetdependency/library(path:publicheaders:swiftmodulemap:condition:)) target dependency is what' you're after. There's also an example in Tuist fixtures on how to depend on a precompiled static library:

- https://github.com/tuist/tuist/blob/main/fixtures/ios_app_with_static_libraries/Modules/A/Project.swift#L15 (specific line)
- https://github.com/tuist/tuist/blob/main/fixtures/ios_app_with_static_libraries (the full example)

Hope this helps

**Comment by demhademha** [comment]
thank you very much for your supporting in this matter. 
We believe we are almost there: the example project you referenced used a swiftmodule. However we are attempting to use a modulemap. Does tuist have support for this? 
Kind regards

**Comment by demhademha** [comment]
based off the tree diagram from earlier, and the project example, we have: 
import ProjectDescription

let project = Project(
    name: "Braillify",
    targets: [
        Target(
            name: "BraillifyKit",
            platform: .macOS,  // Adjust platform if needed
            product: .framework,
            bundleId: "com.yourdomain.BraillifyKit",
            infoPlist: "Targets/BraillifyKit/Info.plist",
            sources: "Targets/BraillifyKit/**/*.swift",
            dependencies: [
                .library(
                    path: "Targets/Liblouis/lib/liblouis.a",  // Adjust path to liblouis.a
                    publicHeaders: "./Targets/Liblouis/include",      // Adjust path to headers
                    swiftModuleMap: "Targets/Liblouis/include"  // Adjust path to modulemap
                )
            ],
            settings: .settings(base: ["HEADER_SEARCH_PATHS": "$(SRCROOT)/Targets/Liblouis/include"])  // Adjust header search path if needed
        ),
        Target(
            name: "BraillifyUI",
            platform: .macOS,  // Adjust platform if needed
            product: .framework,
            bundleId: "com.yourdomain.BraillifyUI",
            infoPlist: "Targets/BraillifyUI/Info.plist",
            sources: "Targets/BraillifyUI/**/*.swift",
            dependencies: [
                .target(name: "BraillifyKit")
            ]
        )
    ]
) 
however: we get the following error: 

Couldn't find metadata for binary at path /Users/projects/braillify2/Targets/Liblouis/lib/liblouis.a

**Comment by kwridan** [comment]
Hi @demhademha 

I had a look at the sample you provided, is it correctly configured (without Tuist)? It's helpful to start with a working project without Tuist and then trying to see how which pieces are needed to migrate to Tuist to generate a similar project.

I was able to get it working by re-configuring it slightly.

- For c++ clang modules, I believe the module map needs to have the name `module.modulemap` [^1]
- Added the missing header search paths `HEADER_SEARCH_PATHS = $(PROJECT_DIR)/TuistDriver`

For the Tuist integration I had the following:

```swift
import ProjectDescription

let project = Project(
    name: "Demo",
    targets: [
        Target(
            name: "TuistDemoKit",
            platform: .macOS,
            product: .framework,
            bundleId: "io.tuist.tuistDemo.kit",
            infoPlist: .default,
            sources: "TuistDemoKit/**",
            dependencies: [
                .library(
                    path: "TuistDriver/libtuistdriver.a",
                    publicHeaders: "TuistDriver",
                    swiftModuleMap: nil
                ),
            ]
        ),
    ]
)
```

Note there is no need to manually specify the header search paths here as Tuist will automatically set it up based on the path specified to `publicHeaders`.

The error you're getting in your real project is different:

> Couldn't find metadata for binary at path /Users/projects/braillify2/Targets/Liblouis/lib/liblouis.a

It looks like static library isn't being recognised by Tuist, whereas the example provided Tuist can recognise it, is it perhaps built differently?

[^1]: https://www.swift.org/documentation/cxx-interop/project-build-setup/

**Comment by demhademha** [comment]
We have come across a very peculiar find: 
attached is our project. 
1. run bin/compile to get the Liblouis directory (feel free to view the scripts contents) 
2. run tuist build and the error is: 
Couldn't find metadata for binary at path /Users/test/Github/TuistDemo/Liblouis/lib/liblouis.a 
replace the liblouis.a file with libtuistdriver.a (but keep the same file name) 
the project successfully compiles 
Could this be down to the compiler flags that are used? 
Thanks for your support once again 
[TuistDemo.zip](https://github.com/tuist/tuist/files/13789891/TuistDemo.zip)

**Comment by fortmarek** [comment]
If you still need help, I'd recommending creating a new troubleshooting post at our [community forum](https://community.tuist.io/). Thanks for your understanding!
