### ISSUE TITLE
Rename builds cache to binary cache

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5725]
Using **builds cache** to refer to the binary cache we use to speed workflows is inaccurate. The name implies that the feature is exclusive to builds when it's an optimization that we run for workflows other than build, for example, `generate` and `test.` We should rename the name throughout the CLI to **binary cache** including the directory where we output the binary artifacts.

**Comment by fortmarek** [comment]
Resolved via: https://github.com/tuist/tuist/pull/5842
