### ISSUE TITLE
Swift DocC: Migration Guidelines

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5732]
Document migration guidelines

**Comment by kikeenrique** [comment]
I would suggest a point dedicated to tuistenv --> rtx. 
I'm wondering at this moment how _tuistenv bundle_ and _tuistenv local Ver.Si.On_ are handled now.

**Comment by pepicrft** [comment]
> I would suggest a point dedicated to tuistenv --> rtx.
> I'm wondering at this moment how tuistenv bundle and tuistenv local Ver.Si.On are handled now.

We'll include this as part of the Tuist 4 release notes. This migration doc is more about people migrating from Xcode projects to Tuist, not migrating between Tusit versions.

**Comment by cadaniel** [comment]
> > I would suggest a point dedicated to tuistenv --> rtx.
> > I'm wondering at this moment how tuistenv bundle and tuistenv local Ver.Si.On are handled now.
> 
> We'll include this as part of the Tuist 4 release notes. This migration doc is more about people migrating from Xcode projects to Tuist, not migrating between Tusit versions.

Are there any guides for this that exist? 

I've found a lot of cocoapod ones, but my project is SPM, so I haven't found one yet.

**Comment by pepicrft** [comment]
We don't have something specific for SPM, but you can use the following [page as a reference](https://docs.old.tuist.io/guides/adopting-tuist). Moving from SPM is more straightforward than moving from Xcode projects because the declaration of packages tends to be more straightforward (due to the simpler DSL). I'd recommend starting with the most dependent upon a package, migrating that to a `Project.swift`, generating the project with `twist generate` and making sure it compiles, and then keep moving package targets one by one, ensuring they compile.
