### ISSUE TITLE
Unexpected group "Compiled" in generated project

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#5753]
### What happened?

When generating a project with the latest tuist (v 3.37.0) there's now a "Compiled" group instead "Frameworks".

For example, a target with system framework & library dependencies:

![compiled](https://github.com/tuist/tuist/assets/11914919/c7834381-2ebe-411a-a665-7b611caf08d5)

This is not consistent with previous versions of Tuist which was inline with where Xcode places system framework & library dependencies under a "Frameworks" group:

![xcode-default](https://github.com/tuist/tuist/assets/11914919/30d2b591-61d7-4cbe-a667-aff98e04aa92)

I believe this is related to https://github.com/tuist/tuist/pull/5617 which was aiming to improve cached artefact groupings, however in this example no caching features are used as such the expectation is to not see any differences.

While at the surface this may seam like an arbitrary choice as to where to place things, this diverges from projects created by the Xcode UI, so for example, attempting to manually add a new system library from the Xcode UI will now create a "Frameworks" group to place this.

### How do we reproduce it?

Generate the follow sample project using `tuist generate` (no caching):

```swift
import ProjectDescription

let project = Project(
    name: "Sample",
    targets: [
        Target(
            name: "Sample",
            platform: .iOS,
            product: .framework,
            bundleId: "io.tuist.sample",
            infoPlist: .default,
            sources: "Sample/**",
            dependencies: [
                .sdk(name: "Accelerate", type: .framework, status: .required),
                .sdk(name: "c++", type: .library, status: .required),
            ]
        ),
    ]
)
```

Inspect the generated project

### Error log

n/a

### macOS version

13.6.2

### Tuist version

3.37.0

### Xcode version

15.2

**Comment by danyf90** [comment]
👍  I also think that separating cached from other compiled framework would be clearer

**Comment by pepicrft** [comment]
The rationale behind putting them all together in the same folder was to skip an additional pass to the graph, increasing the generation time. I can look into it again to see if I can do it without that additional pass.
