### ISSUE TITLE
Rtx was renamed to mise

### ISSUE THREAD

**Issue by chojnac** [tuist/tuist#5756]
### What problem or need do you have?

Recently, project `rtx` was renamed to `mise` to prevent name conflicts with Nvidia products. Tuist's documentation and project need to be updated. 

### macOS version

12

### Tuist version

3.37.0

### Xcode version

15

**Comment by danyf90** [comment]
Thanks @chojnac 🙏  Feel free to open a PR if you want! 🎉

**Comment by chojnac** [comment]
that was quick 🎖️
