### ISSUE TITLE
`brew install`-ed tuist has no scaffolds

### ISSUE THREAD

**Issue by blimmer** [tuist/tuist#5763]
### What happened?

I recently migrated from the `bash` script installer to using Homebrew, per these instructions: https://docs.next.tuist.io/documentation/tuist/installation/

When I tried to `init` a project, I noticed there are no scaffolds:

```shell
 ~  which tuist
tuist not found
 ✘  ~  brew install tuist/tuist/tuist@3.38.0
==> Fetching tuist/tuist/tuist@3.38.0
==> Downloading https://github.com/tuist/tuist/releases/download/3.38.0/tuist.zip
Already downloaded: /Users/blimmer/Library/Caches/Homebrew/downloads/3ff688f89ef29d3d467d67e9994132b52cc54d6ebc30f3cd3dd5f8e3e3a53ebd--tuist.zip
==> Installing tuist@3.38.0 from tuist/tuist
🍺  /opt/homebrew/Cellar/tuist@3.38.0/3.38.0: 74 files, 115.4MB, built in 2 seconds
==> Running `brew cleanup tuist@3.38.0`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
 ~  tuist scaffold list

 ~ 
```

However, when installed via the legacy installer, two scaffolds are present:

```shell
 ~  brew uninstall tuist/tuist/tuist@3.38.0
Uninstalling /opt/homebrew/Cellar/tuist@3.38.0/3.38.0... (74 files, 115.4MB)
 ~  /bin/bash -c "$(curl -Ls https://install.tuist.io)"
==> Downloading tuistenv...
==> Unzipping tuistenv...
==> Installing tuistenv...
Password:
==> tuistenv installed. Try running 'tuist'
==> Check out the documentation at https://docs.tuist.io/
 ~  tuist scaffold list
Name     Description
───────  ────────────────
default  Default template
swiftui  SwiftUI template


The following warnings need attention:
 · The method used to install this version of Tuist is deprecated and will be deleted soon.
Please, uninstall it by running:

    curl -Ls https://uninstall.tuist.io | bash

And follow the new installation instructions at https://docs.next.tuist.io/documentation/tuist/installation

Read more about the rationale at https://tuist.io/blog/2023/12/15/rtx-default/
```

### How do we reproduce it?

1. Install via homebrew:

```shell
brew install tuist/tuist/tuist@3.38.0
```

2. Run `tuist scaffold`

```
tuist scaffold
```

Note that it returns an empty list.

### Error log

The error message is simply that there are no scaffolds. If you try to use the `tuist init` command from [the onboarding tutorial](https://docs.next.tuist.io/tutorials/tuist/create-project), you receive and error:

```
 tuist init --platform ios --template swiftui
Error: Could not find template swiftui. Make sure it exists at Tuist/Templates/swiftui
```

### macOS version

14.2.1

### Tuist version

3.38.0

### Xcode version

15.1

**Comment by bengidev** [comment]
Hallo, @blimmer . I've the same problem like you, and i'm trying to delete the previous installation way, then installing tuist with `brew install --cask tuist`, and you can use like normal again. 

If you have the error message when running tuist first time, you can allow tuist run from you System Settings -> Privacy & Security -> Security -> Allow applications downloaded from, and you can unlock and allow tuist to run, and you can re-run your previous command.

Sorry for my bad english. Hope it helps, mate 🍻

**Comment by pepicrft** [comment]
Hey folks!
This seems to indicate that the directory structure we created when Tuist was installed via Homebrew is not valid. We'll either have to adjust the formula to align with what Tuist expects or adjust Tuist's logic for looking up templates to ensure it accounts for that directory structure.

Your English is great, @bengidev 🍺. Thanks a lot for chiming in explaining how to fix the error message.

**Comment by intabulas** [comment]
Since I hit this recently I went looking. Seems the swiftui template was completely removed in commit a61e6e59 on Jan 31st

**Comment by KaiOelfke** [comment]
I also had this issue yesterday. It's confusing, when you're new to a tool and try to learn how to use it, but things don't work. I wasn't sure, if I did something wrong or if the tool doesn't come with batteries included (I need to make my own templates). Installing with brew cask finally worked after mise and brew install failed for me.

**Comment by bulmang** [comment]
I also encountered the same problem. I tried the method you provided above, but it failed.
The same error occurs from version 4.0.0 or higher. I tried installing the version below and it was successful.

**Comment by intabulas** [comment]
So is the swiftui template gone for good then? That was part of the original report here and same issue I was encountering. It seems it was removed in `a61e6e5`. Some of the docs/tutorials refer to using the `--template swiftui` and that will still fail on 4.7.0

**Comment by fortmarek** [comment]
SwiftUI template is the new default, the UIKit one is gone. You don't need to specify the template when using tuist init. Wanna contribute to them docs? 😁

**Comment by mtfum** [comment]
Still facing same problem with downloading through Homebrew
```console
$ which tuist
/opt/homebrew/bin/tuist

$ tuist version
4.8.1

$ tuist init
Could not find template default. Make sure it exists at Tuist/Templates/default
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

```

**Comment by ryanmeisters** [comment]
same

**Comment by fortmarek** [comment]
Hey 👋 

I just downloaded tuist from brew, but can't reproduce the issue.

Can you check the following:
> Does running `/opt/homebrew/Caskroom/tuist/4.8.1/tuist init` work?
> What do you see when you run `ls /opt/homebrew/Caskroom/tuist/4.8.1` and `ls /opt/homebrew/Caskroom/tuist/4.8.1/Templates/default`?

**Comment by fortmarek** [comment]
That's a different error. You need to run the tuist init command in an empty directory, as the error suggests. Can you try that and see if that works?

**Comment by mtfum** [comment]
Ah, ok. finally succeeded to init with allowing security alert.
Thank you for your support! @fortmarek

**Comment by fortmarek** [comment]
Glad it works! Will close again then 🤝

**Comment by rakuyoMo** [comment]
> SwiftUI template is the new default, the UIKit one is gone. You don't need to specify the template when using tuist init. Wanna contribute to them docs? 😁

So tuist no longer supports UIKit? How do I retrieve this template?

**Comment by rakuyoMo** [comment]
> @rakuyoMo Tuist supports UIKit, but we don't have a template. You can check out [the fixtures](https://github.com/tuist/tuist/tree/main/fixtures) directory in the repository for some examples that use UIKit. For example [this one](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_custom_scheme)

I don't understand though, if it was there in the past, then why delete it?This leads to a lot of changes every time I create a project with tuist, maybe I need to implement a uikit template myself?This creates quite a problem for tuist beginners like me who use uikit: it doesn't work out of the box anymore.Sincerely hope that the uikit template can be added back as an option.

**Comment by fortmarek** [comment]
We were simplifying the templates because we noticed they can easily go out-of-date and we didn't have time to redo the UIKit one. We also felt majority of our users start with SwiftUI nowadays. I think we could bring the UIKit template back and it could reuse most of the default SwiftUI template.

If you wanna have a look, you could reuse bits of deleted code from this [PR](https://github.com/tuist/tuist/pull/5853) and reuse the SwiftUI template that we have now.

**Comment by voghDev** [comment]
Hi! I was having the same issue with tuist `4.5.0`. This is how I solved it:
First of all, I uninstalled my current version of tuist
```
> brew uninstall tuist@4.5.0
Uninstalling /opt/homebrew/Cellar/tuist@4.5.0/4.5.0... (61 files, 106.4MB)
```
then I installed the latest version, which is `4.12.0` nowadays
```
brew install --cask tuist 
==> Downloading https://github.com/tuist/tuist/releases/download/4.12.0/tuist.zi
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/3141ec2560...e83--tuist.zip
==> Installing Cask tuist
==> Linking Binary 'tuist' to '/opt/homebrew/bin/tuist'
🍺  tuist was successfully installed!
```
After that, the command `tuist init --platform ios` worked
```
tuist init --platform ios
Project generated at path /Users/user/TuistExample. Run `tuist generate` to generate the project and open it in Xcode. Use `tuist edit` to easily update the Tuist project definition.
To learn more about tuist features, such as how to add external dependencies or how to use our ProjectDescription helpers, head to our tutorials page: https://docs.tuist.io/tutorials/tuist-tutorials
```
