### ISSUE TITLE
FYI: Incorrect tuist plugin repo in the mise registry

### ISSUE THREAD

**Issue by jwhitley** [tuist/tuist#5778]
### What happened?

I'm new to tuist, and to mise the now-recommended installer. Currently `mise install tuist` is pointing to https://github.com/cprecioso/asdf-tuist, which was archived on Dec. 26, 2023 and includes a note in the README that it's superseded by https://github.com/asdf-community/asdf-tuist. Digging in, [the mise registry](https://github.com/mise-plugins/registry/blob/main/plugins/tuist) still points to the old repository.

To this end, I've submitted PR mise-plugins/registry#3 to bring the mise registry up to date.

I don't believe that there's further action required, except to watch for that PR to land.

### How do we reproduce it?

1. `mise install tuist`
2. Observe mise's warning about installing a community plugin:
```
⚠️  tuist is a community-developed plugin: https://github.com/cprecioso/asdf-tuist
 Would you like to install tuist? 
```

### Error log

n/a. This is a usage/operational error, not a runtime error.

### macOS version

14.2.1

### Tuist version

3.39.0

### Xcode version

15.1

**Comment by pepicrft** [comment]
Thanks for reporting this @jwhitley. I noticed [this PR](https://github.com/mise-plugins/registry/pull/3) has already been merged, which means this issue should be mitigated now.
