### ISSUE TITLE
using mise to install tuist in xcode cloud fails

### ISSUE THREAD

**Issue by jane-siwonkim** [tuist/tuist#5780]
### What happened?

I used a new mise method to install tuist in xcode-cloud environment.

It seems that tuist is successfully installed but cannot find tuist command in the current directory?

It works perfectly fine in my local environment to install mise with brew, and install tuist with mise. Then generate project with Tuist. 
The problem only occurs within Xcode-cloud.

### How do we reproduce it?

Following shell script is executed in the xcode-cloud environment and i got the error message: `./tuist_install.sh: line 17: tuist: command not found`

```
// ci_post_clone

chmod +x tuist_install.sh
./tuist_install.sh
```

```
// tuist_install.sh

#!/bin/sh
brew install mise

mise install tuist@3.38.0
mise use tuist@3.38.0
mise plugins
mise ls tuist

echo "tuist generate..."

tuist clean --path ..
tuist fetch --path ..
tuist generate --path ..

```

### Error log

![screenshot](https://github.com/tuist/tuist/assets/118710778/0df82569-595d-464c-90d3-2c5674a81960)

### macOS version

14.0

### Tuist version

3.38.0

### Xcode version

15.0

**Comment by pepicrft** [comment]
@jane-siwonkim In local environments, Mise activates in your interactive environment to load the right version of Tuist based on the directory. On non-interactive environments like the one that Xcode Cloud provides, you'll have to use the shims generated by Mise. So your script should be something along the lines of:

```bash

#!/bin/sh
brew install mise

mise install -g tuist@3.38.0
tuist_path=~/.local/share/mise/shims/tuist

echo "tuist generate..."

$tuist_path clean --path ..
$tuist_path fetch --path ..
$tuist_path generate --path ..
```

Please, let me know if that works, and I'll update the docs accordingly for people coming across the same issue in the future.

**Comment by jane-siwonkim** [comment]
Thanks a lot, It worked. You should definitely update the docs :)

**Comment by jane-siwonkim** [comment]
```shell
#!/bin/sh
brew install mise

mise install -g tuist@3.38.0
tuist_path=~/.local/share/mise/shims/tuist
mise use tuist@3.38.0

echo "tuist generate..."

$tuist_path clean --path ..
$tuist_path fetch --path ..
$tuist_path generate --path ..
```

Thanks a lot, It worked. You should definitely update the docs :)
I added this part to your script: `mise use tuist@3.38.0`. Without it, it doesn't work

**Comment by danyf90** [comment]
I think we should update the docs to suggest using the zip from the repo in CI :D
No one wants to waste CI time installing mise when it's benefits are mostly for local dev

**Comment by pepicrft** [comment]
> I think we should update the docs to suggest using the zip from the GitHub to install in CI :D No one wants to waste CI time installing mise when it's benefits are mostly for local dev

Note that using the same version across environments is not specific to a particular environment (e.g. locally). There's room for pulling different versions if teams use different installation methods for local and CI environments. 
And I wouldn't consider the installation of Mise a waste of time. We are talking about 5 Mb, which I expect to be pulled in less than a second in a CI environment.

**Comment by pepicrft** [comment]
@jane-siwonkim I documented it [here](https://github.com/tuist/tuist/pull/5787). Note that I suggest something simpler there using `mise x` to prevent two sources of truth for the version (the script and the `mise.toml`) file.
