### ISSUE TITLE
enforceExplicitDependencies does not work with Google Maps

### ISSUE THREAD

**Issue by cooksimo** [tuist/tuist#5783]
### What happened?

When trying to turn the new `enforceExplicitDependencies` option on, the app no longer builds due to issues with Google Maps.

### How do we reproduce it?

[GoogleMapsTuist.zip](https://github.com/tuist/tuist/files/13880701/GoogleMapsTuist.zip)

In the attached sample project, run:
```
tuist fetch
tuist generate -x
```

Then try to build

### Error log

```
GoogleMapsTuist/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/ios-maps-sdk/Core/GMSEmpty.m:17:9: fatal error: module 'GoogleMaps' not found
@import GoogleMaps;
 ~~~~~~~^~~~~~~~~~
1 error generated.
```

### macOS version

13.6

### Tuist version

3.39.0

### Xcode version

15

**Comment by pepicrft** [comment]
@cooksimo would you mind testing with the latest Tuist version, 4.3.1?

**Comment by cooksimo** [comment]
@pepicrft Just tested this with 4.3.1 and the issue is exactly the same

**Comment by fortmarek** [comment]
I'm closing this as this variable will be now deprecated: https://github.com/tuist/tuist/pull/6869
