### ISSUE TITLE
Unhandled fatal error in TestsCache when migrating from pre-3.36.0 to post-3.36.0

### ISSUE THREAD

**Issue by regularberry** [tuist/tuist#5786]
### What happened?

If you have a project using a version of tuist before 3.36.0, and populate the TestsCache by running some tests - then upgrade to any version >= 3.36.0 (using 3.39.3 also works), then run the tests again, the process crashes with an unhandled error:

```
We received an error that we couldn't handle:
    - Localized description: The file “ba4eb77a3cc10587a6eb6a42399540b4” couldn’t be saved in the folder “TestsCache” because a file with the same name already exists.
    - Error: Error Domain=NSCocoaErrorDomain Code=516 "The file “ba4eb77a3cc10587a6eb6a42399540b4” couldn’t be saved in the folder “TestsCache” because a file with the same name already exists." UserInfo={NSFilePath=/Users/Z006LFH/.tuist/Cache/TestsCache/ba4eb77a3cc10587a6eb6a42399540b4, NSUnderlyingError=0x6000025d3030 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}
    - 
```

### How do we reproduce it?

1. Using the attached project - [TestsCacheIssue.zip](https://github.com/tuist/tuist/files/13906423/TestsCacheIssue.zip)
2. echo "3.35.0" > .tuist-version
3. tuist test
4. echo "3.36.0" > .tuist-version
5. tuist test
6. Observe the crash - you can also switch it to "3.39.3" and view it there as well

### Error log

```
We received an error that we couldn't handle:
    - Localized description: The file “ba4eb77a3cc10587a6eb6a42399540b4” couldn’t be saved in the folder “TestsCache” because a file with the same name already exists.
    - Error: Error Domain=NSCocoaErrorDomain Code=516 "The file “ba4eb77a3cc10587a6eb6a42399540b4” couldn’t be saved in the folder “TestsCache” because a file with the same name already exists." UserInfo={NSFilePath=/Users/Z006LFH/.tuist/Cache/TestsCache/ba4eb77a3cc10587a6eb6a42399540b4, NSUnderlyingError=0x6000025d3030 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}

If you think it's a legit issue, please file an issue including the reproducible steps: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

13.6.2

### Tuist version

3.34.0 -> 3.39.3

### Xcode version

14.3.1 and 15.2

**Comment by regularberry** [comment]
Something happened between 3.35.5 and 3.36.0: https://github.com/tuist/tuist/compare/3.35.5...3.36.0

**Comment by pepicrft** [comment]
I've identified the issue and opened a PR to fix it. Thanks for reporting this @regularberry

**Comment by regularberry** [comment]
@pepicrft thanks for the quick fix!
