### ISSUE TITLE
error: Dependencies could not be resolved

### ISSUE THREAD

**Issue by IlyaMakarevich** [tuist/tuist#5789]
### What problem or need do you have?

I have package in gitlab, and have access via HTTPS to its repository. I can open it in browser or make git clone successfully.

In Dependencies.swift I have write this package:
```
        .remote(
            url: "https://url_to_gitlab",
            requirement: .upToNextMajor(from: "1.0.1")
        )
```

When I use tuist to make project, I constantly get error 

```
Computing version for https://url_to_gitlab
error: Dependencies could not be resolved because no versions of 'MyPackageName' match the requirement 1.0.1..<2.0.0 and root depends on 'MyPackageName' 1.0.1..<2.0.0.
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

I tried to use Xcode 15, 15.1, 15.2
Disable/enable vpn
Update git version
no result(

### macOS version

14.2.1

### Tuist version

3.39.3

### Xcode version

15.2

**Comment by danyf90** [comment]
Does `swift package resolve` run in the `Tuist/Dependencies/SwiftPackageManager` folder works fine?
If not, you have some problem in your local configuration of SPM

**Comment by IlyaMakarevich** [comment]
> SPM

all dependencies resolve successfully, except one:
error: Dependencies could not be resolved because no versions of 'MyPackageName' match the requirement 1.0.1..<2.0.0 and root depends on 'MyPackageName' 1.0.1..<2.0.0.
