### ISSUE TITLE
Backwards-incompatible change to Dependencies.swift parsing

### ISSUE THREAD

**Issue by Arclite** [tuist/tuist#5806]
### What problem or need do you have?

I recently performed a minor (in the semver sense) update of Tuist, from v3.28.0 to v3.40.0. After performing the update, I was no longer able to run a successful `tuist fetch`, with several errors:

```
The 'swift' command exited with error code 1 and message:
/Users/pado/Developer/Kineo/Tuist/Dependencies.swift:4:24: error: cannot convert value of type '[Any]' to expected argument type 'SwiftPackageManagerDependencies?'
  swiftPackageManager: [
                       ^
/Users/pado/Developer/Kineo/Tuist/Dependencies.swift:5:6: error: type 'Any' has no member 'remote'
    .remote(url: "https://github.com/siteline/SwiftUI-Introspect.git", requirement: .exact("0.12.0")),
    ~^~~~~~
/Users/pado/Developer/Kineo/Tuist/Dependencies.swift:5:86: error: cannot infer contextual base in reference to member 'exact'
    .remote(url: "https://github.com/siteline/SwiftUI-Introspect.git", requirement: .exact("0.12.0")),
                                                                                    ~^~~~~
/Users/pado/Developer/Kineo/Tuist/Dependencies.swift:6:6: error: type 'Any' has no member 'remote'
    .remote(url: "https://github.com/airbnb/lottie-ios.git", requirement: .upToNextMajor(from: "3.2.1"))
    ~^~~~~~
/Users/pado/Developer/Kineo/Tuist/Dependencies.swift:6:76: error: cannot infer contextual base in reference to member 'upToNextMajor'
    .remote(url: "https://github.com/airbnb/lottie-ios.git", requirement: .upToNextMajor(from: "3.2.1"))
```

It seems there's been a few other people experiencing this same issue, such as [here](https://github.com/tuist/tuist/issues/5792) and [here](https://github.com/tuist/tuist/issues/5671).

### Potential solution

I dug into it a bit more, and it seems the underlying cause is the [removal of an `ExpressibleByArrayLiteral` conformance](https://github.com/tuist/tuist/commit/36a4e40664dd63c7dd6ccff6d9f151298bd3b982#diff-743c39ba86efdd319493dedadf1378fb1caa4fa8c1799c37572af652fc4220bbL56) in [this PR](https://github.com/tuist/tuist/pull/5503).

As the [old docs](https://docs.old.tuist.io/guides/third-party-dependencies) explicitly leaned on this conformance as "the way" to define SPM dependencies, it's a bit annoying that this was changed without a major version bump. Is there a chance to get this conformance added back?

### macOS version

14.2.1

### Tuist version

3.40.0

### Xcode version

15.2

**Comment by Arclite** [comment]
For anyone else experiencing this same issue, the easiest way to work around it is that assuming you have something like this in your `Dependencies.swift` file:

```swift
let dependencies = Dependencies(
    swiftPackageManager: [
        .remote(url: "https://github.com/siteline/SwiftUI-Introspect.git", requirement: .exact("0.12.0")),
        .remote(url: "https://github.com/airbnb/lottie-ios.git", requirement: .upToNextMajor(from: "3.2.1"))
    ]
)
```

Simply wrap that array with a `.init` call, like so:

```swift
let dependencies = Dependencies(
    swiftPackageManager: .init([
        .remote(url: "https://github.com/siteline/SwiftUI-Introspect.git", requirement: .exact("0.12.0")),
        .remote(url: "https://github.com/airbnb/lottie-ios.git", requirement: .upToNextMajor(from: "3.2.1"))
    ])
)
```

It'll throw a warning saying `'init(_:productTypes:baseSettings:targetSettings:projectOptions:)' is deprecated: Use init without packages parameter instead`, but it'll let you fetch dependencies and generate your project again.

**Comment by danyf90** [comment]
Thanks for reporting! 🙏  I would just keep things as it is as we are near to release Tuist 4 and this will be no longer an option!

**Comment by Arclite** [comment]
If you want to leave this closed, that's fine, but I'd argue that the existence of an upcoming breaking major-version change is **more** of a reason to avoid breaking changes in minor versions, for people who want to remain on the old branch until they're ready to move.

If I were to open a PR on my own accord, would that get closed for similar reasons?

**Comment by fortmarek** [comment]
Making a breaking change was done here by accident – we try to avoid breaking changes in minor versions as much as possible.

> If I were to open a PR on my own accord, would that get closed for similar reasons?

Yes, if you want to open a PR by yourself, that'd be great 🙌

**Comment by pepicrft** [comment]
Apologies for the introduction of the breaking change and the confusion after @Arclite. We do our best to provide the best open-source support and updates possible, but we sometimes make mistakes. We are going to take action to prevent this from happening again.
