### ISSUE TITLE
`enforceExplicitDependencies`: build error when an app module depends on a package with resources

### ISSUE THREAD

**Issue by ak-bs** [tuist/tuist#5808]
### What happened?

Consider the following scenario:
- There's a Swift Package called `SomeLibrary` with a single product which includes some resources (localization strings in the attached project).
- There's an app with 2 modules:
  - `SomeApp` - the actual executable. Depends on the `SomeAppKit`.
  - `SomeAppKit` - an app module (a framework). Depends on the `SomeLibrary`.

This way the dependency graph would look like: `SomeApp` -> `SomeAppKit` -> `SomeLibrary`.

When I generate a project with Tuist it creates a bundle `SomeLibrary_SomeLibrary.bundle` with the product resources and adds it to the `Copy Bundle Resources` build phase of the `SomeAppKit` module. 

However, when I enable the `enforceExplicitDependencies` option the bundle path is set to the `SomeAppKit` scope: 
```
[derived_data_path]/Build/Products/Debug-iphonesimulator/SomeAppKit/SomeLibrary_SomeLibrary.bundle
```
while in fact it is located at:
```
[derived_data_path]/Build/Products/Debug-iphonesimulator/SomeLibrary_SomeLibrary/SomeLibrary_SomeLibrary.bundle
```
and there's also the generated symlink at the root of the built products dir, i.e. just:
```
[derived_data_path]/Build/Products/Debug-iphonesimulator/SomeLibrary_SomeLibrary.bundle
```

Thus, Xcode is unable to find the bundle and the build fails.

**Sample project:** [ExplicitDependenciesTest.zip](https://github.com/tuist/tuist/files/13964475/ExplicitDependenciesTest.zip)

### How do we reproduce it?

1. Open the attached project and navigate to the `SomeApp` directory.
2. Run `tuist fetch`.
3. Run `tuist generate`.
4. Try to build the `SomeApp` or `SomeAppKit` target.

### Error log

```
[derived_data_path]/Build/Products/Debug-iphonesimulator/SomeAppKit/SomeLibrary_SomeLibrary.bundle: No such file or directory
```

### macOS version

14.2.1

### Tuist version

3.40.0

### Xcode version

15.1

**Comment by Ernest0-Production** [comment]
This bug still exists in Tuist version 4.9.0 :(

**Comment by fortmarek** [comment]
Yeah, I'd love to get to it, but can't give you an ETA. I would be more than happy to provide you with pointers if you wanted to take a stab at it yourself. Otherwise, it's in our backlog, but doesn't have immediate priority.

**Comment by Ernest0-Production** [comment]
@fortmarek The task seems very clear 🤔 Could you please give pointers so that I can try to understand first if I can solve the problem

**Comment by fortmarek** [comment]
All the logic for explicit dependencies is in this [mapper](https://github.com/tuist/tuist/blob/main/Sources/TuistGenerator/Mappers/ExplicitDependencyGraphMapper.swift).

There are a couple of references to `.bundle` in that mapper, I'd try to look up where the mismatch of the path happens.

**Comment by ak-bs** [comment]
I've made another attempt to find a solution but no luck so far. 

In particular, I was checking the search paths for the `SomeAppKit` target, looking for any hints.

- The `FRAMEWORK_SEARCH_PATH` is set to:
```
$(CONFIGURATION_BUILD_DIR)$(TARGET_BUILD_SUBPATH)/SomeLibrary_SomeLibrary
$(CONFIGURATION_BUILD_DIR)$(TARGET_BUILD_SUBPATH)/SomeLibrary
```
The first line is exactly where the library bundle is located. Unfortunately, it looks like Xcode does not take the `FRAMEWORK_SEARCH_PATH` into account when looking for resources listed in the `Copy Bundle Resources`.

- The `BUILT_PRODUCTS_DIR` is set to:
```
$(CONFIGURATION_BUILD_DIR)$(TARGET_BUILD_SUBPATH)/SomeAppKit
```
I confirm that the target can be built successfully if I remove the last path component (`SomeAppKit`), but this contradicts the purpose of the feature.

Do you have any ideas on what a reasonable fix would look like?

**Comment by pepicrft** [comment]
@ak-bs I'd need to dive into the business logic to be able to provide a suggestion. Maybe @fortmarek is able to provide one? Otherwise, I added it as one of our priorities, so hopefully we'll be able to provide with a solution soonish.

**Comment by KaiOelfke** [comment]
FWIW: I also ran into this issue. So I can't use this option for now.

**Comment by pepicrft** [comment]
@ak-bs we've decided to [follow a different approach](https://github.com/tuist/tuist/issues/6492) here that's more reliable by leveraging static analysis of code and a new command that can be run separately, `tuist lint dependencies` (or something along those lines). Therefore, I recommend waiting until that solution is implemented. 

Let's continue the discussion in that other issue.
