### ISSUE TITLE
Prevent Tuist from poluting Xcode's most recent projects

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5828]
### What problem or need do you have?

Because the directory where we create the temporary projects for editing the manifests changes in every run, we pollute Xcode's list of most recent projects.

![image](https://github.com/tuist/tuist/assets/663605/49bbc515-5d93-4c10-a065-8291000bce0d)

### Potential solution

We should have a deterministic path for each project that lives in Tuist's global directory. Similar to how Xcode does with the paths inside derived data.

**Comment by annie-gupta** [comment]
I would like to give it a try. Please assign this issue to me.

**Comment by fortmarek** [comment]
Amazing @annie-gupta 🙌 

The idea was to:
- Hash a path based on where the project the user wants to edit is located at
- Generate the project in `~/.tuist/Cache/EditProjects/hash-based-on-project-path`

Let us know if you need any help 🙂
