### ISSUE TITLE
Library not loaded: @rpath/Atomics.framework/Versions/A/Atomics

### ISSUE THREAD

**Issue by JaroVoltix** [tuist/tuist#5848]
### What happened?

When trying to use twist cloud cache with vapor project we can observe that Atomics dependency is not embedded. This result with crash on run

### How do we reproduce it?

1. clone vapor fixture https://github.com/tuist/tuist-vapor-example
2. setup tuist cloud on this project
3. tuist cache warm 
4. sudo rm -rf ~/Library/Developer/Xcode/DerivedData
5. tuist clean
6. tuist fetch
7. tuist generate
8. run project

### Error log

dyld[61899]: Library not loaded: @rpath/Atomics.framework/Versions/A/Atomics
  Referenced from: <411D7E1A-E713-39FC-B315-FF5D50386701> /Users/xxxx/Library/Developer/Xcode/DerivedData/Hello-gbslhaodabuanhenndeddnqcvoms/Build/Products/Debug/App
  Reason: tried: '/Users/xxxx/Library/Developer/Xcode/DerivedData/Hello-gbslhaodabuanhenndeddnqcvoms/Build/Products/Debug/Atomics.framework/Versions/A/Atomics' (no such file)

### macOS version

14.0

### Tuist version

3.42.1

### Xcode version

15.2

**Comment by pepicrft** [comment]
Duplicated https://github.com/tuist/tuist/issues/5794

**Comment by muukii** [comment]
@JaroVoltix 
I'm not sure this is the same issue with mine. but you might want to use Tuist 4.4.0, which should be solved.
