### ISSUE TITLE
Tuist 4 - Beta issues

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5864]
- [x] #5877
- [ ] The message about multi-platform bundles show up even if the bundles are not multiplatform. For example, we shouldn't see the following error in the `tuist/tuist` repository because there's only one platform, macOS: `Multi-platform bundles like ZIPFoundation_ZIPFoundation are not fully supported by binary caching yet and therefore we don't recommend using them for release builds.`
- [ ] Create a `.mise.toml` when creating a new project that pins the Tuist version to the one that's being used to instantiate the project.
- [ ] Investigate why selective tests were skipped in this PR: https://github.com/tuist/tuist/pull/5834
- [x] #5866
- [x] #5870
- [ ] `multiple commands producing .../DerivedData/myApp/Build/Production/Debug-[iphoneos, iphonesimulator, watchos, watchsimulator]/MyFrameworkMacros` when using macros in a multi-platform setup.
- [x] #5867

**Comment by stefanomondino** [comment]
@pepicrft `tuist clean`is supposed to work with no parameter and clean all, but it's returning this error

<img width="1123" alt="image" src="https://github.com/tuist/tuist/assets/1691903/32525e24-9fea-432a-98e3-2c9e57c4b5cf">
