### ISSUE TITLE
Add precompiled header `.pch` in headers 

### ISSUE THREAD

**Issue by VorkhlikArtem** [tuist/tuist#5878]
### What problem or need do you have?

Add a possibility to add precompiled header `.pch` in public headers section
Usual method doesn't add  .pch in public headers if it exists in the TargetName folder:
`headers: .headers(public: "TargetName/**")`
Even if add in the list explicitly:
`headers: .headers(public: ["Header.pch"])`

### Potential solution

In file `PackageInfoMapper.swift` In extension `ProjectDescription.Headers` there is header filtering
I suggest change filtering to
`.filter { $0.extension == "h" ||  $0.extension == "pch" } `

```
extension ProjectDescription.Headers {
    fileprivate static func from(moduleMapType: ModuleMapType, publicHeadersPath: AbsolutePath) throws -> Self? {
        switch moduleMapType {
        case .header, .nestedHeader:
            let publicHeaders = FileHandler.shared.filesAndDirectoriesContained(in: publicHeadersPath)!
                .filter { $0.extension == "h" }     // HERE
            let list: [FileListGlob] = publicHeaders.map { .glob(Path($0.pathString)) }
            return .headers(public: .list(list))
        case .none, .custom, .directory:
            return nil
        }
    }
}
```

### macOS version

13.4

### Tuist version

3.39.0

### Xcode version

14.3

**Comment by danyf90** [comment]
Hello @VorkhlikArtem 👋 
The allowed headers are defined [here](https://github.com/tuist/XcodeProj/blob/41d52ce7424906980fd1b133454b444f5bb5f21b/Sources/XcodeProj/Project/Xcode.swift#L63) in XcodeProj.
We would need to add it there, release it, and update the dependency in Tuist.
Would you like to try and implement the change?

**Comment by VorkhlikArtem** [comment]
Hello @danyf90  , I tried to push my branch with changes in XcodeProj. But It seems I don't have  rights enough  

ERROR: Permission to tuist/xcodeproj.git denied to VorkhlikArtem.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by danyf90** [comment]
> Hello @danyf90  , I tried to push my branch with changes in XcodeProj. But It seems I don't have  rights enough. Could you give me the right t push and do pull requests ?  
> 
> 
> 
> ```
> 
> ERROR: Permission to tuist/xcodeproj.git denied to VorkhlikArtem.
> 
> fatal: Could not read from remote repository.
> 
> 
> 
> Please make sure you have the correct access rights
> 
> and the repository exists.
> 
> ```

Hello @VorkhlikArtem, you need to create a fork, push your changes there, and then open a PR on tuist repo using the fork as source branch

**Comment by pepicrft** [comment]
Here's the PR: https://github.com/tuist/tuist/pull/5967
