### ISSUE TITLE
Unable to manage billing for Tuist Cloud

### ISSUE THREAD

**Issue by anuragajwani** [tuist/tuist#5885]
### What problem or need do you have?

I want to manage billing and add seats to my Tuist Cloud account however I am getting the message "something went wrong" consistently.

<img width="603" alt="Screenshot 2024-02-06 at 11 21 32" src="https://github.com/tuist/tuist/assets/7071488/9d77a515-ef72-42dc-8032-291be135473e">

### macOS version

14.0

### Tuist version

3.35.2

### Xcode version

15.1

**Comment by fortmarek** [comment]
This should be fixed for you now. For anybody else who hits this, please, let us know 🙏

**Comment by anuragajwani** [comment]
thank you @fortmarek 🙇🏽

**Comment by fortmarek** [comment]
@anuragajwani I reached out to you on Slack btw, would be great if you could get back to us there or give us a different contact, so we can discuss your Tuist Cloud plan 🙂
