### ISSUE TITLE
Figure out the impact of privacy manifests in Tuist

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5895]
Some Swift Packages are already including a [privacy manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) that will soon be mandatory by Apple for some of the most popular community packages.
We need to figure out how this impacts Tuist since we generate Xcode projects from Swift packages. We'll most likely have to make sure that the privacy manifest is included as a resource in generated target associated to the package.

**Comment by fortmarek** [comment]
> We'll most likely have to make sure that the privacy manifest is included as a resource in generated target associated to the package.

This is already the case:
![image](https://github.com/tuist/tuist/assets/9371695/cd4b4648-cc0b-4db2-959e-c484e234ae74)

Closing unless we find out there's something extra we need to do.
