### ISSUE TITLE
Use Codable API instead of JSONConvertible

### ISSUE THREAD

**Issue by ollieatkinson** [tuist/tuist#59]
**Is your feature request related to a problem? Please describe.**
Currently there's a custom implementation for JSON - is there a reason that we don't use the Codable API? 

**Describe the solution you'd like**
Remove https://github.com/xcode-project-manager/xpm/blob/master/Sources/ProjectDescription/JSON.swift and make the models implement Codable API. (https://developer.apple.com/documentation/swift/codable)

**Describe alternatives you've considered**
The alternative is to avoid doing the work and keep the current system

**Comment by pepibumur** [comment]
Not really. We could definitively use the Swift encoding/decoding APIs. I'd keep this as a low priority though.
