### ISSUE TITLE
Custom style (color / shapes) for Targets in visual graphs

### ISSUE THREAD

**Issue by stefanomondino** [tuist/tuist#5900]
### What problem or need do you have?

When creating architectures based on microfeatures, we found very useful to split our frameworks into "layers" and build some hierarchical structure around them.

We have "core" frameworks (utilities, low level implementations like a networking wrapper, etc) and "feature" frameworks (some small part of the app, like the login/registration screens, the onboarding screens, etc).

When such micromodule grow, it's useful to use `tuist graph` to print out what's going on and have an immediate visual representation of the situation; however this quickly becomes unreadable at first glance because all types of targets have the same color - orange.

It would be great to have the chance to "style" this from ProjectDescription down to the GraphViz layer.

### Potential solution

I'll draft a PR and link it here :)

### macOS version

14.2.1

### Tuist version

4.0.0

### Xcode version

15.2.0

**Comment by pepicrft** [comment]
Superseded by [this issue](https://github.com/tuist/tuist/issues/5968)
