### ISSUE TITLE
tuist fetch error

### ISSUE THREAD

**Issue by jkimdev** [tuist/tuist#5908]
### What happened?

I tried to fetch TheComposableArchitecture and it fails

remote: https://github.com/pointfreeco/swift-composable-architecture.git
library: ComposableArchitecture

### How do we reproduce it?

tuist fetch

### Error log

- Localized description: The data couldn’t be read because it isn’t in the correct format.
    - Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _JSONKey(stringValue: "Index 2", intValue: 2), CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize TargetType from invalid String value macro", underlyingError: nil))

### macOS version

14.2.1

### Tuist version

3.15.0

### Xcode version

15.2

**Comment by fortmarek** [comment]
Hey @jkimdev 👋 

I'd recommend bumping to Tuist 4 in the ideal case or at least to the last 3.x.y release. 3.15.0 is quite an old version that we don't plan to ship bug fixes for.
