### ISSUE TITLE
Syntax highlighting broken when setting platforms in the package settings

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5910]
### What problem or need do you have?
A user [reported](https://github.com/jgoodrick/SyntaxHighlightingRepro/tree/main) that syntax highlighting is not working as expected in macros when setting platforms through the `PackageSettings` configuration object.

**Comment by pepicrft** [comment]
We might consider getting rid of the `platforms` attribute in the `PackageSettings` interface.

**Comment by fortmarek** [comment]
> We might consider getting rid of the platforms attribute in the PackageSettings interface.

I'm in favor of this one. It's technically a breaking change, but maybe since this interface is new, it _might_ be ok? It's causing a lot of confusion and we should rather rely on the platform narrower graph mapper

**Comment by danyf90** [comment]
I would also remove it, I would consider it a bug that it slipped into 4.x release

**Comment by fortmarek** [comment]
Let's remove it then 🚀
