### ISSUE TITLE
CocoaLumberjack build issue "Cannot find 'DDOSLogger' in scope" using Tuist 4.1.1

### ISSUE THREAD

**Issue by amarcadet** [tuist/tuist#5915]
### What problem or need do you have?

I am facing a build error since https://github.com/tuist/tuist/pull/5887 has been released with CocoaLumberjack : `Cannot find 'DDOSLogger' in scope`.

Despite trying to import all available frameworks shipped with CocoaLumberjack:

```swift
import CocoaLumberjack
import CocoaLumberjackSwift
import CocoaLumberjackSwiftSupport
```

... or even setting the `HEADER_SEARCH_PATHS`:

```swift
.merging([
    "HEADER_SEARCH_PATHS": [
        "$(inherited)",
        // fix Tuist 3.x issue: Could not build Objective-C module 'CocoaLumberjack'
        "$(SRCROOT)/.build/checkouts/CocoaLumberjack/Sources/CocoaLumberjack/include",
    ],
]),
```

Nothing seems to fix my issue.

It is worth noting that I have no issue using `DDLogInfo` like you do in your tests but using `DDOSLogger` does not seem to work.

My dependencies graph looks like this:

```
MyApp → MyFramework → CocoaLumberjack
MyApp → CocoaLumberjack
```

What is happening:
- `MyFramework` builds perfectly but do not use `DDOSLogger`
- `MyApp` do not build and use `DDOSLogger`
- When I use `DDOSLogger` in `MyFramework`, it no longer builds

I am quite lost with the workarounds that was once needed (`HEADER_SEARCH_PATHS`) and no longer required with this MR.

What is the best way to configure CocoaLumberjack in the Package.swift? Should I put all of its product in here as a `.framework` product types?

```swift
let packageSettings = PackageSettings(
    productTypes: [
        "CocoaLumberjack": .framework,
        "CocoaLumberjackSwift": .framework,
        "CocoaLumberjackSwiftSupport": .framework,
```

Thank you for your time and help.

### macOS version

14.2.1

### Tuist version

4.1.1

### Xcode version

15.2

**Comment by amarcadet** [comment]
When I Cmd+Click on `import CocoaLumberjack` all I see is:

```swift
import Foundation
import SwiftOnoneSupport
import _Concurrency
import _StringProcessing
import _SwiftConcurrencyShims

@objc public class CocoaLumberjackResources : NSObject {

    @objc public class var bundle: Bundle { get }
}
```

I wonder if it's not related to the `@_exported` attribute that `CocoaLumberjackSwift` use to export `CocoaLumberjack` and that in my scenario exported symbols are not visible via transitive dependencies.

I have achieved a similar result using your "app_with_spm_dependencies" project by adding:

In  `fixtures/app_with_spm_dependencies/Features/FeatureOne/Project.swift`:
```diff
            dependencies: [
                .external(name: "Alamofire"),
+               .external(name: "CocoaLumberjackSwift"),
            ],
            settings: .targetSettings
```

In `fixtures/app_with_spm_dependencies/Features/FeatureOne/Sources/FeatureOne.swift`:
```diff
import Alamofire
+import CocoaLumberjackSwift

public func start() {
    // Use Alamofire to make sure it links fine
    _ = AF.download("http://www.tuist.io")
}

+public class Foo: DDOSLogger { // error: Cannot find type 'DDOSLogger' in scope

+
+}
```

**Comment by amarcadet** [comment]
For what it's worth I am facing a similar issue with `YouTubeiOSPlayerHelper`.

**Comment by fortmarek** [comment]
Thanks for going deep on this one @amarcadet 🙏 I plan to take a look at this soon, too.

Hmm, it _might_ be the resource bundle. You can edit the `.build/checkouts/CocoaLumberjack` and remove the resource bundle from the `Package.swift` definition and see if `CocoaLumberjackSwift` builds.

I've been testing with the `app_with_spm_dependencies` fixture. You can actually add a `CocoaLumberjackSwift` scheme there and build it on its own. I'm very certain the `@_exported` attribute is not the culprit since that module already fails to build if you try to use the `DDOSLogger`.
