### ISSUE TITLE
Broken tutorial

### ISSUE THREAD

**Issue by 23inhouse** [tuist/tuist#5921]
### What happened?

1. Went to: https://docs.tuist.io/tutorials/tuist/create-project/
2. Tried to generate a project.
3. Got an error at the first tuist command.

### How do we reproduce it?

Go to: https://docs.tuist.io/tutorials/tuist/create-project/
Followed instructions:
1. mkdir MyApp - Worked!
2. cd MyApp - Worked!
3. tuist init --platform ios - FAILED!

### Error log

Could not find template default. Make sure it exists at Tuist/Templates/default
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

14.3

### Tuist version

3.39.3

### Xcode version

15.2

**Comment by fortmarek** [comment]
Hey @23inhouse 👋 

The tutorial is tailored only for the latest tuist version (v4.0.0 and higher). I'd recommend updating the tuist version 🙏 

Let us know if you run into any other issues with the tutorial.

**Comment by wangzhizhou** [comment]
> Happened to me too, using tuist 4.6.0, Xcode 15.3

Me Too.

Xcode 15.2
Tuist 4.12.0
MacOS 14.4.1

![image](https://github.com/tuist/tuist/assets/8174538/b99d436c-2750-4415-b1a3-cec1a92f5506)

**Comment by im4xpro** [comment]
Same problem here:
Xcode 15.3, Tuist 4.14 (installed via Homebrew), macOS 14.4
-> tuist init --platform ios
Could not find template default. Make sure it exists at Tuist/Templates/default
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

**Comment by pepicrft** [comment]
This PR should fix it https://github.com/tuist/tuist/pull/6309
