### ISSUE TITLE
Error in MetalPetal Library: '`DEFINES_MODULE` Set, but No Umbrella Header Found for Module Map Generation'

### ISSUE THREAD

**Issue by leeari95** [tuist/tuist#5934]
### What problem or need do you have?

I'm glad that starting from version 4.2.0, it is now possible to set MetalPetal as an external dependency via Package.swift. Previously, we had to use Xcode native integration to use MetalPetal because methods in .metal files could not be recognized at runtime.

```
// Please note, this was the error message appearing at runtime before.
Thread 6: "-[MTIContext renderImage:toCVPixelBuffer:error:]: unrecognized selector sent to instance 0x280e6a3c0"
```

Starting from Tuist 4.2.0, now, even when setting the MetalPetal library as an external dependency, it works without any issues at runtime. I am very very pleased.

However, there seems to be a new issue that would be great if you could fix.

The following warning appears:

```
DEFINES_MODULE was set, but no umbrella header could be found to generate the module map
```

This warning only occurs in the MetalPetalObjectiveC target within the MetalPetal project, and I'm not sure why this warning is appearing.

Thank you.

<img width="727" alt="image" src="https://github.com/tuist/tuist/assets/75905803/40ea1252-f66c-4fe0-b1dd-8ee785cb782f">

#

To summarize the content above...

1. Setting the MetalPetal library as an external dependency results in a DEFINES_MODULE error.
2. This does not occur when using the MetalPetal library with Xcode native integration.

My dependency graph is as follows:
```
MyApp → MyFramework → MetalPetal
```

</br>

Library configuration:

```swift
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
    import ProjectDescription
    import ProjectDescriptionHelpers


    let packageSettings = PackageSettings(
        productTypes: [],
        baseSettings: .settings(
            base: [
                "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64"
            ],
            configurations: [
                .debug(name: .debug),
                .debug(name: .qa),
                .release(name: .release),
                .release(name: .stage)
            ],
            defaultSettings: .recommended
        ),
        platforms: [.iOS]
    )
#endif

let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "https://github.com/MetalPetal/MetalPetal.git", exact: "1.25.1")
    ]
)
```

### macOS version

14.2.1

### Tuist version

4.2.0

### Xcode version

15.2

**Comment by fortmarek** [comment]
Hey!

Thanks for raising this. Closing as a dup of: https://github.com/tuist/tuist/issues/5513

We're looking into this and hope to have a fix soon. This [PR](https://github.com/tuist/tuist/pull/5935) should eliminate some of these warnings but there might be still some left afterwards. For now, you can update the settings for the `MetalPetal` library yourself using custom `targetSettings` in [PackageSettings](https://docs.tuist.io/documentation/tuist/packagesettings) in your `Package.swift` file.

**Comment by leeari95** [comment]
@fortmarek 

Of course. I tried changing the setting by setting `DEFINES_MODULE` to false in `targetSettings`, but I still encountered a build error related to the MetalPetalObjectiveC target, so I couldn't resolve it with that setting. Please take note…!

**Comment by fortmarek** [comment]
Thanks @leeari95 🙌 Yeah, disabling the setting is not enough for some targets. Some also need -fmodule-name option. I tried the `MetalPetal` library with this [PR](https://github.com/tuist/tuist/pull/5946) and the library builds and the `DEFINES_MODULE` warning is no longer there.
