### ISSUE TITLE
Generated project missing in Xcode recents list

### ISSUE THREAD

**Issue by kapitoshka438** [tuist/tuist#5936]
### What happened?

After upgrading to Tuist 4, generated and opened xcworkspace never appears in recent projects (Xcode startup screen, File -> Open Recent etc.). Instead of xcworkspace, a swift package with the same name is presented in the recents list, which is not correct.

### How do we reproduce it?

Run `tuist generate` for a project with SPM dependencies.
Open and close xcworkspace.
Close and open Xcode.
Generated workspace is not presented.

### Error log

-

### macOS version

14.2.1

### Tuist version

4.2.0

### Xcode version

15.2

**Comment by fortmarek** [comment]
Hey 👋 

Unfortunately, Xcode implicitly favours package if at a given path it finds `Package.swift` – regardless of whether there's also `.xcodeproj` or `.xcworkspace`.

We will allow putting the `Package.swift` also at `Tuist/Package.swift` (not just in the root of your project) to get around this limitation (PR to come soon)

**Comment by vsanthanam** [comment]
Wouldn't this also have been true in Tuist 3.x?

**Comment by fortmarek** [comment]
> Wouldn't this also have been true in Tuist 3.x?

No, in tuist 3.x, the `Package.swift` was in the `Tuist` directory
