### ISSUE TITLE
Customise Strings build script

### ISSUE THREAD

**Issue by artemkrachulov** [tuist/tuist#5951]
### What problem or need do you have?

Hello. I need help with app localization. 
Current localisation method generated in {BundleName}-Strings.swift file:

```
extension {BundleName}Strings {
  private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {
    let format = {BundleName}Resources.bundle.localizedString(forKey: key, value: nil, table: table)
    return String(format: format, locale: Locale.current, arguments: args)
  }
}
```
works well with the device language switch option.

We have to Implement a force language switch option within the app: when the user selects language, the app will save language code and use strings from specific files.  I should have followed the view:

```
extension {BundleName}Strings {
  private static func tr(_ table: String, _ key: String, _ args: CVarArg...) -> String {
    let resourceLanguage = UserDefaults.standard.getAppLanguage() ?? "en"
    let path = {BundleName}Resources.bundle.path(forResource: resourceLanguage, ofType: "lproj")
    let bundle = Bundle(path: path!)
    return NSLocalizedString(key, tableName: table, bundle: bundle!, value: key, comment: key)
  }
}
```

To do that I have to create or modify the generated source. Can you give me a tip on how to do that? Maybe we can create a template for strings files?
 

### macOS version

14.2.1

### Tuist version

3.36.0

### Xcode version

 15.2

**Comment by danyf90** [comment]
Ciao 👋 
Did you have a look at [the documentation](https://docs.tuist.io/documentation/tuist/synthesized-files)? 🙏

**Comment by artemkrachulov** [comment]
@danyf90 thank you!
