### ISSUE TITLE
Problem with SVProgressHUD module bundle

### ISSUE THREAD

**Issue by kapitoshka438** [tuist/tuist#5959]
### What happened?

My app crashes at runtime when trying to address to SVProgressHUD module bundle at startup.

### How do we reproduce it?

`Package.swift`:
```
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
    import ProjectDescription

    let packageSettings = PackageSettings(
        platforms: [.iOS]
    )

#endif

let package = Package(
    name: "PackageName",
    dependencies: [
        ...
        .package(url: "https://github.com/SVProgressHUD/SVProgressHUD", exact: "2.3.1"),
        ...
    ]
)

```
Then:
```
tuist clean
tuist install
tuist cache
tuist generate
```
or
```
tuist clean
tuist generate --no-binary-cache
```

### Error log

<img width="722" alt="Снимок экрана 2024-02-20 в 13 57 37" src="https://github.com/tuist/tuist/assets/3232401/f38f5065-dbf5-4a8b-9af0-8b625dda937d">
<img width="470" alt="Снимок экрана 2024-02-20 в 13 58 00" src="https://github.com/tuist/tuist/assets/3232401/fa18f201-26ef-454f-a66f-5e65f2349c9b">

### macOS version

14.2.1

### Tuist version

4.3.0

### Xcode version

15.2

**Comment by dogo** [comment]
Add to package-settings

        productTypes: [
            "SVProgressHUD": .framework,
         ]

**Comment by kapitoshka438** [comment]
@dogo that didn't help. The app crashes after several minutes of recursively calling `SVProgressHUD_SWIFTPM_MODULE_BUNDLE()`

**Comment by pepicrft** [comment]
Thanks for reporting this @kapitoshka438. We'll look into it.
