### ISSUE TITLE
Add support for the package access level keyword

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5970]
Swift Packages support now the [package](https://github.com/apple/swift-evolution/blob/main/proposals/0386-package-access-modifier.md) access level modifier. We need to ensure we support it, or the integration of packages will start failing for those who use it. I think the work consists of ensuring we pass the right flag to the compiler through the build settings of the generated targets

**Comment by pepicrft** [comment]
This is necessary to unlock [this other work](https://github.com/tuist/tuist/pull/5886)

**Comment by fortmarek** [comment]
Done via: https://github.com/tuist/tuist/pull/5983

**Comment by super-ultra** [comment]
@pepicrft, does it work for local packages? 
I use Tuist 4.9 and it generates `-package-name` for external dependencies, but not for my local dependencies: 
```swift
// Package.swift
let package = Package(
    name: "some-project-packages",
    platforms: [.iOS(.v17)],
    dependencies: [
        .package(path: "path/to/local-package")
    ]
)
```

**Comment by fortmarek** [comment]
@super-ultra It should work for local packages. If it doesn't, would you mind creating a new issue with a reproducible sample? 🙏

**Comment by super-ultra** [comment]
> @super-ultra It should work for local packages. If it doesn't, would you mind creating a new issue with a reproducible sample? 🙏

I found a problem in my project. I defined custom `"OTHER_SWIFT_FLAGS"` and it rewrites default `-package-name` flag. 

```swift 
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
    import ProjectDescription

    let packageSettings = PackageSettings(
        targetSettings: [
            "Logger": SettingsDictionary()
                .appendingWarningFlags()
        ]
    )

extension SettingsDictionary {
    public func appendingWarningFlags() -> SettingsDictionary {
        let flags = [
            "-Xfrontend -debug-time-expression-type-checking",
            "-Xfrontend -debug-time-function-bodies",
            "-Xfrontend -warn-long-function-bodies=200",
            "-Xfrontend -warn-long-expression-type-checking=200"
        ]

        return merging(["OTHER_SWIFT_FLAGS": .array(flags)])
    }
}

#endif

let package = Package(
    name: "PackageLevel",
    dependencies: [
        .package(url: "https://github.com/apple/swift-testing", .upToNextMajor(from: "0.7.0")),
        .package(name: "logger", path: "../packages/logger")
    ]
)
```

In my case, I solved the problem by moving this flags from `targetSettings` to `baseSettings`.

**Comment by fortmarek** [comment]
@super-ultra would you mind creating a reproducible sample and creating a new issue, so we can take a look? 🙏

**Comment by super-ultra** [comment]
> @super-ultra would you mind creating a reproducible sample and creating a new issue, so we can take a look? 🙏

Done -> https://github.com/tuist/tuist/issues/6196
