### ISSUE TITLE
Add a Tuist update checker mechanism

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#5977]
### Discussed in https://github.com/tuist/tuist/discussions/5974

<div type='discussions-op-text'>

<sup>Originally posted by **amarcadet** February 22, 2024</sup>
Other tools like Fastlane (see [update_checker.rb](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/update_checker/update_checker.rb#L11)) or Periphery (see [UpdateChecker.swift](https://github.com/peripheryapp/periphery/blob/master/Sources/Frontend/UpdateChecker.swift)) offer such feature.

Considering the release pace since 4.0 it would be a great way to ensure that the project toolchain is up to date.

The check could be disabled like Fastlane do with an env var like so `TUIST_SKIP_UPDATE_CHECK`.</div>

**Comment by danyf90** [comment]
My 2cents: I think this could be a `mise` feature, rather than having each CLI reimplement the wheel

**Comment by pepicrft** [comment]
I agree with @danyf90 here. I don't think that's something we need to solve at the Tuist layer. The installer, Homebrew or Mise, should take care of that. Note that [Mise](https://mise.jdx.dev/cli/#mise-outdated-tool-version) provides a command to check whether any tools are outdated. I brought up the idea of showing a warning if it's outdated there. Still, we concluded that adding something like that would result in something very annoying and that developers would end up disabling.
