### ISSUE TITLE
error: Multiple commands produce during tuist cache

### ISSUE THREAD

**Issue by JaroVoltix** [tuist/tuist#5988]
### What happened?

When trying to use tuist cache it fails with "Multiple commands produce " error. Previously I was able to workaround on this issue by doing 
1. Tuist cache DataCategory
2. tuist cache DataGenerator
3. tuist cache

but currently it also fails with error 

> The 'xcodebuild' command exited with error code 70 and message:
A library with the identifier 'macos-arm64_x86_64' already exists.

### How do we reproduce it?

1. Open attached project
[TuistCacheBug.zip](https://github.com/tuist/tuist/files/14392654/TuistCacheBug.zip)
2. tuist cache

### Error log

>❌ error: Multiple commands produce '/var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework'
❌ error: Multiple commands produce '/var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework'
⚠️ duplicate output file '/var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework' on task: MkDir /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: MkDir /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: RegisterExecutionPolicyException /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: SetMode u+w,go-w,a+rX /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '/var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework/Headers' on task: SymLink /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework/Headers Versions/Current/Headers (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: Touch /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ unexpected mutating task ('SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework') with no relation to prior mutator ('SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework') (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ unexpected mutating task ('SetMode u+w,go-w,a+rX /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework') with no relation to prior mutator ('SetMode u+w,go-w,a+rX /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework') (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '/var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework/DataGenerator' on task: CreateUniversalBinary /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework/DataGenerator normal arm64 x86_64 (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '/var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework' on task: MkDir /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: MkDir /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: RegisterExecutionPolicyException /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: SetMode u+w,go-w,a+rX /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '' on task: SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataGenerator.framework (in target 'DataGenerator' from project 'SwiftAndTipsMacros')
⚠️ unexpected mutating task ('SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework') with no relation to prior mutator ('SetOwnerAndGroup jaro:staff /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework') (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ unexpected mutating task ('SetMode u+w,go-w,a+rX /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework') with no relation to prior mutator ('SetMode u+w,go-w,a+rX /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework') (in target 'DataCategory' from project 'SwiftAndTipsMacros')
⚠️ duplicate output file '/var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework/DataCategory' on task: CreateUniversalBinary /var/folders/lx/ddnmh1h551xgjnk0329xp2fw0000gn/T/TemporaryDirectory.IqQbV8/derived-data/Build/Intermediates.noindex/ArchiveIntermediates/Binaries-Cache-iOS/InstallationBuildProductsLocation/Library/Frameworks/DataCategory.framework/DataCategory normal arm64 x86_64 (in target 'DataCategory' from project 'SwiftAndTipsMacros')
The 'xcodebuild' command exited with error code 65 and message:
** ARCHIVE FAILED **

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

14.1

### Tuist version

4.3.4

### Xcode version

15.2

**Comment by NachoSoto** [comment]
Any update on this? `tuist cache` is broken for me too. 

Looks like it's trying to create `XCFrameworks` for dependencies that support both `macOS` and `Catalyst` (like OrderedCollections`:
```
/usr/bin/xcrun xcodebuild -create-xcframework 
-archive /private/var/folders/60/737rrmcs6yqbfbl9fd4g0dcw0000gp/T/TemporaryDirectory.5gwC7A/Archives/iOS/simulator.xcarchive 
-framework _CollectionsUtilities.framework 
-archive /private/var/folders/60/737rrmcs6yqbfbl9fd4g0dcw0000gp/T/TemporaryDirectory.5gwC7A/Archives/iOS/mac-catalyst.xcarchive 
-archive /private/var/folders/60/737rrmcs6yqbfbl9fd4g0dcw0000gp/T/TemporaryDirectory.5gwC7A/Archives/iOS/device.xcarchive 
-framework _CollectionsUtilities.framework 
-archive /private/var/folders/60/737rrmcs6yqbfbl9fd4g0dcw0000gp/T/TemporaryDirectory.5gwC7A/Archives/macOS/device.xcarchive 
-framework _CollectionsUtilities.framework -output /var/folders/60/737rrmcs6yqbfbl9fd4g0dcw0000gp/T/TemporaryDirectory.5gwC7A/xcframeworks/_CollectionsUtilities.xcframework 
-allow-internal-distribution

-framework _CollectionsUtilities.framework 
```

Which fails with 
> A library with the identifier 'macos-arm64_x86_64' already exists.

Maybe we should be able to specify which platforms to build when using `tuist cache`.

**Comment by pepicrft** [comment]
Hi there 👋🏼 
I started looking into this and found the culprit of @JaroVoltix's issue. An internal framework the macro macro executable of [this package](https://github.com/JaroVoltix/SwiftAndTipsMacros) depends on, `DataGenerator` is also public. Because both the Swift Macro and the app depend on it, the supported platforms are macOS and iOS, and that causes the `xcodebuild` archive that we run to fail because the build graph that Xcode builds internally has multiple talks that produce the same output. I couldn't figure out how to adjust the graph or the build to prevent ending up in that state, so I decided to iterate on the logic to use `xcodebuild build` instead and us be the ones gathering the binaries from the derived data directory. 

![graph](https://github.com/tuist/tuist/assets/663605/b9f83d95-5dc9-4ec6-8f7c-0abb6b90ffc1)

**Comment by pepicrft** [comment]
@NachoSoto this is something we indeed have plans for. As part of that we'll have to make sure that when users run `generate` we remove the platforms other than the one that was used to generate the binaries. Otherwise developers might try to compile for other platforms and cause issues.

Until that happens, I think I can solve your issue without having to implement that feature. How can I reproduce it?

**Comment by pepicrft** [comment]
@NachoSoto I moved the discussion about your problem to [this issue](https://github.com/tuist/tuist/issues/6227)
