### ISSUE TITLE
Unable to fetch dependencies

### ISSUE THREAD

**Issue by dankinsoid** [tuist/tuist#5991]
### What happened?

Since "tuist fetch" was renamed to "tuist install" Im unable to run any of these commands. 
<img width="462" alt="Снимок экрана 2024-02-25 в 15 51 55" src="https://github.com/tuist/tuist/assets/30962149/a61ce05b-8ffb-4e95-82e7-49d01c9b5462">
<img width="381" alt="Снимок экрана 2024-02-25 в 15 52 52" src="https://github.com/tuist/tuist/assets/30962149/61b7a93c-b75f-4eaa-b064-3afce2cd21dc">

### How do we reproduce it?

1. Run `tuist install` or `tuist fetch`

### Error log

```sh
Error: Missing expected argument '<version>'
Help:  <version>  The version of tuist to be installed
Usage: tuist install <version>
  See 'tuist install --help' for more information.
```

### macOS version

13.5.1

### Tuist version

4.3.4

### Xcode version

15.0.1

**Comment by danyf90** [comment]
You still have tuistenv installed and the command is conflicting with the old tuist install.
Remove the old version and it should be back to work

**Comment by dankinsoid** [comment]
@danyf90 I need the old version too. One my project fixes tuist version and another uses the last one

**Comment by danyf90** [comment]
> @danyf90 I need the old version too. One my project fixes tuist version while another uses the last one

You can uninstall the old version with the old method, and reinstall it using mise!
