### ISSUE TITLE
Error: Could not find template swiftui

### ISSUE THREAD

**Issue by RgarciaH94** [tuist/tuist#5998]
### What happened?

Fail initializing tuist project

### How do we reproduce it?

Install tuist throught mise or homebrew and try to initialize a project
```
➜  ~ tuist init --platform ios --template swiftui
```

### Error log

```sh
Error: Could not find template swiftui. Make sure it exists at Tuist/Templates/swiftui
```

### macOS version

14.3.1

### Tuist version

4.3.4

### Xcode version

14.2

**Comment by danyf90** [comment]
Legacy doc, fixed [here](https://github.com/tuist/tuist/pull/6000)
