### ISSUE TITLE
`tuist generate` won't use all cached dependencies

### ISSUE THREAD

**Issue by mihaicris-adoreme** [tuist/tuist#6015]
### What happened?

Regression
In version tuist 4.4.0 `tuist generate` won't use all cached dependencies
Version 4.3.4 works fine.

### How do we reproduce it?

**Sample project**
[ios_app_with_spm_integration_test.zip](https://github.com/tuist/tuist/files/14460153/ios_app_with_spm_integration_test.zip)

Run
```sh
tuist install
tuist cache
tuist generate
```
**Expect**
All cached dependencies are used as binary.

**Actual**
Some dependencies are used as sources:

- GoogleAppMeasurement
- GoogleDataTransport
- GTMSessionFetcher
- Firebase
- GoogleUtilities

### Error log

n/a

### macOS version

14.3.1 (23D60)

### Tuist version

4.4.0

### Xcode version

15.2

**Comment by mihaicris-adoreme** [comment]
Also thiis warning appears:
`
The following warnings need attention:
 · '/Users/mihai.c/Desktop/ios_app_with_spm_integration_test/Tuist/.build/checkouts/firebase-ios-sdk/FirebaseSessions/Tests/TestApp/Shared/Assets.xcassets' is a directory, try using: '/Users/mihai.c/Desktop/ios_app_with_spm_integration_test/Tuist/.build/checkouts/firebase-ios-sdk/FirebaseSessions/Tests/TestApp/Shared/Assets.xcassets/**' to list its files
`

**Comment by fortmarek** [comment]
Thanks for reporting. This will be fixed in the Monday's release.

The issue with warnings is tracked here: https://github.com/tuist/tuist/issues/5928 (and it's something we already started to look into 🙏)

**Comment by fortmarek** [comment]
The fix for this issue should be released tomorrow 🙏
