### ISSUE TITLE
Custom xcconfigs are not added to the target when enforceExplicitDependencies is enabled

### ISSUE THREAD

**Issue by fdzsergio** [tuist/tuist#6017]
### What happened?

If you have one or multiple targets with a custom **xcconfig**, when you activate the `enforceExplicitDependencies` option, it's not configured for the target. For the project, the **xcconfig** is still maintained, but not for the targets.

### How do we reproduce it?

I've taken the already prepared fixture from **ios_app_with_multi_configs** and enabled the `enforceExplicitDependencies` option. 

I have prepared a sample project with it:
[ios_app_with_multi_configs.zip](https://github.com/tuist/tuist/files/14464567/ios_app_with_multi_configs.zip)

### Error log

Generating a project with `enforceExplicitDependencies` **disabled**:
<img width="520" alt="Screenshot 2024-03-01 at 19 28 31" src="https://github.com/tuist/tuist/assets/557580/34184d15-f51e-419b-8e52-0545aedb8a1a">

Generating the same project with `enforceExplicitDependencies` **enabled**:
<img width="520" alt="Screenshot 2024-03-01 at 19 27 14" src="https://github.com/tuist/tuist/assets/557580/e3955074-63b2-4d04-be32-d48959ef2b53">

### macOS version

14.3.1

### Tuist version

4.4.0

### Xcode version

15.2

**Comment by pepicrft** [comment]
Thanks @fdzsergio for reporting this. I added it to our backlog as something to look into.
