### ISSUE TITLE
Tuist fetch renamed to init conflicts with installation command

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#6025]
### What happened?

I updated to latest tuist version 4.4.0. I notice there is a breaking change of fetching spm dependencies. the command was renamed from fetch to init. However when I run this command it seems like tuist executes install tuist command instead.

### How do we reproduce it?

1. install tuist 4.4.0
2. you project.swift and workspace.swift are located not in the root of the repo but at /MyProject.
3. Moved dependencies to Package.swift at MyProject instead of MyProject/Tuist/Dependencies.swift
5. run tuist install from MyProject or run tuist install --path ./MyProject/

### Error log

```
tuist install --path ./MyProject/
Error: Unknown option '--path'
Usage: tuist install <version>
  See 'tuist install --help' for more information.
```

```
tuist install
Error: Missing expected argument '<version>'
Help:  <version>  The version of tuist to be installed
Usage: tuist install <version>
  See 'tuist install --help' for more information.
```

### macOS version

14.3.1

### Tuist version

4.4.0

### Xcode version

15.2

**Comment by fortmarek** [comment]
You most likely have the old `tuistenv` executable. You have to uninstall it as per [these instructions](https://github.com/tuist/tuist/releases/tag/4.0.0):
> Breaking: Remove tuistenv in favor of [Mise](https://mise.jdx.dev/) as default installer with [Homebrew](https://github.com/tuist/homebrew-tuist) as an alternative. You'll have to uninstall the current version of Tuist by running curl -Ls https://uninstall.tuist.io | bash and then install it using the installation method of your choice. You'll have to propagate this installation method across CI environments and developers' local environment. We strongly recommend the usage of Mise because it's able to install and activate versions deterministically across environments.

**Comment by apps4everyone** [comment]
that's not so easy if this is e.g. an CI runner used in old and new branches
