### ISSUE TITLE
Expose command parameters as ENV vars

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#6031]
### Discussed in https://github.com/tuist/tuist/discussions/5969

<div type='discussions-op-text'>

<sup>Originally posted by **amarcadet** February 21, 2024</sup>
It would be great to expose commands parameters such as `--configuration` or `--no-open` as env vars. For instance, when `generate` is run inside a CI/CD job it is obvious that we prefer to enable `--no-open` in this case.

Vars could be prefixed with `TUIST_`, here are some of my homemade envs:
- `TUIST_CONFIGURATION`: when set add option `--configuration $TUIST_CONFIGURATION`
- `TUIST_NO_OPEN`: when set add the flag `--no-open` to the generate command
- `TUIST_NO_BINARY_CACHE`: same as above but with `--no-binary-cache`
- `TUIST_GENERATE_PATH`
- `TUIST_GENERATE_SOURCES`
- `TUIST_CLEAN_CATEGORIES`
- `TUIST_TEST_PLATFORM`
- `TUIST_TEST_OS`
- `TUIST_TEST_SCHEMES`
- ...

I have implemented such behavior in my own scripts but I think it could benefit to more Tuist users that face this need.</div>

**Comment by mustiikhalil** [comment]
Hey,

 I was just wondering if we can leverage [pkl](https://pkl-lang.org) to keep all the configurations in one place. for example:

```pkl
module Generate

TUIST_CONFIGURATION: Environment
TUIST_NO_OPEN: Boolean
TUIST_NO_BINARY_CACHE: Boolean
PATH: String

typealias CONFIGURATION = "release"|"debug"|"beta"
```

and from there we can have something similar to the following:

Local configuration
```pkl
amends "Generate.pkl"
TUIST_CONFIGURATION = "debug"
TUIST_NO_OPEN = false
TUIST_NO_BINARY_CACHE = false
```

Releasing configuration
```pkl
amends "Generate.pkl"
TUIST_CONFIGURATION = "release"
TUIST_NO_OPEN = true
TUIST_NO_BINARY_CACHE = true
```

Testing configuration
```pkl
amends "Generate.pkl"
TUIST_CONFIGURATION = "beta"
TUIST_NO_OPEN = true
TUIST_NO_BINARY_CACHE = false
```

However I am not sure if we can ignore options within the pkl file.
