### ISSUE TITLE
Cant build project if `MarkdownUI` is imported

### ISSUE THREAD

**Issue by mustiikhalil** [tuist/tuist#6037]
### What happened?

Currently, we have a project that depends on [MarkdownUI](https://github.com/gonzalezreal/swift-markdown-ui). When the package is imported as a normal spm package, it would work normally.

```swift
let project = Project(package:  [MarkdownUI])
```

However, importing it as an external project, will always fail when trying to build [cmark-gfm](https://github.com/gonzalezreal/swift-markdown-ui/tree/main/Sources/cmark-gfm) dependency

```swift
let package = Package(
    name: "PackageName",
    platforms: [.iOS(.v16)],
    dependencies: [
        .package(url: "https://github.com/gonzalezreal/swift-markdown-ui", from: "2.2.0"),
    ]
)

let target = Target(
    dependencies: [
        .external(name: "MarkdownUI")
    ]
)
```

### How do we reproduce it?

1. Add [MarkdownUI](https://github.com/gonzalezreal/swift-markdown-ui) to the [app_with_spm_dependencies](https://github.com/tuist/tuist/tree/main/fixtures/app_with_spm_dependencies)
2. Add it as an `.external` dependency to any iOS target
3. build

### Error log

<img width="554" alt="Screenshot 2024-03-06 at 12 04 21" src="https://github.com/tuist/tuist/assets/26250654/dd674d89-bf90-4ade-a8aa-459da5147dd7">

### macOS version

14.3.1

### Tuist version

4.3.1 ~ 4.5.1

### Xcode version

15.2

**Comment by erudel** [comment]
I was about to report the same issue. This used to work in previous versions – I'm trying to upgrade to the latest from 3.39.3 and just run into this problem.

It looks like the headers for the C target are not added to the generated project. See the difference in the screenshots below:

version 3.39.3
<img width="475" alt="markdownui-tuist-3-39-3" src="https://github.com/tuist/tuist/assets/1148596/da6d12cb-3bd7-4858-8d41-765f7213ea5a">

version 4.5.1
<img width="220" alt="markdown-ui-tuist-4-5-1" src="https://github.com/tuist/tuist/assets/1148596/ec7efaa2-141d-4547-909e-9b1f33e5dbd3">

If the maintainers think this is a good issue to start contributing to the project, I'd be keen to do so (and would appreciate any pointers on where in the codebase the problem could be).

**Comment by fortmarek** [comment]
Hey @erudel 👋 

I don't think this is really suitable for first-time contributors. I've been working a lot on fixing headers and modulemaps lately, so let me take this on. There's definitely a lot of issues suited for someone who wants to contribute, though, so let me know if you want to take something else 😌

**Comment by fortmarek** [comment]
The fix for this issue is here: https://github.com/tuist/tuist/pull/6042 ^^

**Comment by erudel** [comment]
That was quick, thank you @fortmarek !

The time I can dedicate is fairly limited but I'm still interested in contributing. I see there is a `good first issue` label, so I can start looking into some of those.

Thanks again!
