### ISSUE TITLE
Tuist cache and generate are broken

### ISSUE THREAD

**Issue by dogo** [tuist/tuist#6038]
### What happened?

Since Tuist 4.5.0 I'm not able to generate the cache of my dependencies or generate the project

Tuist installed using mise 

### How do we reproduce it?

Clone the repo:
https://github.com/dogo/swdestiny-trades

tuist install
tuist cache or tuist generate

### Error log

```
tuist cache
Loading and constructing the graph
It might take a while if the cache is empty
[1]    34564 illegal hardware instruction  tuist cache 
```

```
tuist generate
Loading and constructing the graph
It might take a while if the cache is empty
[1]    36709 illegal hardware instruction  tuist generate
```

### macOS version

14.3.1

### Tuist version

4.5.1

### Xcode version

15.2

**Comment by mustiikhalil** [comment]
I have a similar issue however the `Error log` is a simple trace without any other explanation

**Comment by pepicrft** [comment]
Just to be sure, are you both using Xcode 15.2? Or the recently-released Xcode 15.3?

**Comment by dogo** [comment]
> Just to be sure, are you both using Xcode 15.2? Or the recently-released Xcode 15.3?

Xcode 15.2

**Comment by pepicrft** [comment]
I was able to reproduce it. I'm looking into it.

**Comment by fortmarek** [comment]
Try to remove the `projects` glob in the `Workspace.swift` if you don't need it. Otherwise, the fix for this is here: https://github.com/tuist/tuist/pull/6039

We'll do a patch release once merged

**Comment by dogo** [comment]
Removing the projects glob, fixed the issue. Thanks @fortmarek
