### ISSUE TITLE
SPM dependencies install is broken

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#6058]
### What happened?

When I generate the project it always fails with trap error

I execute next commands:
1. tuist install
2. tuist generate

### How do we reproduce it?

This is my Package.swift file
```
// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", .upToNextMajor(from: "1.0.0")),
        .package(url: "https://github.com/onevcat/Kingfisher.git", .upToNextMajor(from: "7.0.0")),
        .package(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework", .upToNextMajor(from: "6.0.0")),
        .package(url: "https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk", .upToNextMajor(from: "18.0.0")),
    ]
)
```

### Error log

I moved this file from Tuist folder as a breaking change, however it seems broken. I tried to comment every item of the dependencies, however I receive next to errors:
[1]    38528 trace trap  tuist generate

or 

Swift/arm64e-apple-macos.swiftinterface:13885: Fatal error: Duplicate values for key: '/Users/user_name/project_folder/.build/checkouts/Atributika'
[1]    38047 trace trap  tuist generate

re-captcha from google has next error: error: 'examples': Invalid manifest

if I comment all the dependencies and do install and generate the error will be next `ArgumentParser` is not a valid configured external dependency. Until I remove .build and .spm folders manually

### macOS version

14.3.1

### Tuist version

4.5.1

### Xcode version

15.2

**Comment by danieleformichelli** [comment]
Can you provide a full sample project?

**Comment by rowwingman** [comment]
I  modified sample project from [this issue](https://github.com/tuist/tuist/issues/5917)
[iPhoneTodo.zip](https://github.com/tuist/tuist/files/14546022/iPhoneTodo.zip)

If I remove .external dependencies from Project.swift file, it generates, but when I add it shows

**Comment by danieleformichelli** [comment]
Provide a sample project, not steps to create it, thanks

**Comment by rowwingman** [comment]
I tried to install the dependencies with latest master, it seems like resolving the issue. so will wait for the new version
