### ISSUE TITLE
Using mergeable library - Tuist add MAKE_MERGEABLE flag, unexpectedly?

### ISSUE THREAD

**Issue by muukii** [tuist/tuist#6059]
### What problem or need do you have?

What happens while using MAKE_MERGEABLE flag

![CleanShot 2024-03-09 at 19 42 20@2x](https://github.com/tuist/tuist/assets/1888355/06a7901b-d3d6-44fd-93c1-0a6dbf59c3db)

found it MAKE_MERGEABLE flag
![CleanShot 2024-03-09 at 19 42 43@2x](https://github.com/tuist/tuist/assets/1888355/6ba7749e-f088-4f92-a750-f080f3eb32e1)

and Debug build won't export frameworks that should be exported.
![CleanShot 2024-03-09 at 20 02 47@2x](https://github.com/tuist/tuist/assets/1888355/8a1afe6d-cb15-4759-93ec-f41887d06051)
seems it's merged into App executable binary

And also SwiftUI Preview in AppService module

> ld: -make_mergeable can only be used when creating a dynamic library
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

![CleanShot 2024-03-09 at 20 08 20@2x](https://github.com/tuist/tuist/assets/1888355/292018b0-00c8-4d6d-9449-5eee4272eef6)

How goes on without MAKE_MERGEABLE

SwiftUI Preview in AppService module is fine

![CleanShot 2024-03-09 at 20 09 26@2x](https://github.com/tuist/tuist/assets/1888355/5f370541-4ee1-485e-8970-fe8f0a28e627)

can find exported frameworks
![CleanShot 2024-03-09 at 20 11 18@2x](https://github.com/tuist/tuist/assets/1888355/5e569b5c-1b21-4e80-a2ae-2f55c85fbdaa)

---

repro project
[mergeable.zip](https://github.com/tuist/tuist/files/14546066/mergeable.zip)

and I'm referring this section
https://developer.apple.com/documentation/Xcode/configuring-your-project-to-use-mergeable-libraries#Manually-configure-merging

> In some cases, you may want to manually configure merging between your app or framework target and dependent libraries. For example, you might not want to automatically merge dependencies that you share between an app and an app extension if you’re concerned about the app extension’s binary size. To set up manual merging, configure your app or framework target, then configure your dependent libraries.

> In your app or framework target, add the build setting MERGED_BINARY_TYPE and set it to manual. After you add that setting to your target:

> In release builds, Xcode merges the products of any of its direct dependencies which have MAKE_MERGEABLE enabled using the linker flags -merge_framework, -merge-l, and so on.

> In debug builds, Xcode links any of your target’s direct dependencies which have MERGEABLE_LIBRARY enabled, but not MAKE_MERGEABLE with the linker flags -reexport_framework, -reexport-l, and so on.

> Xcode uses normal linking for targets that don’t have MERGEABLE_LIBRARY enabled. This is the same linking that Xcode uses for static libraries, or dynamic libraries that aren’t mergeable.

> For each dependent library that you want to use merging, add the build setting MERGEABLE_LIBRARY, and set it to YES. For more information on the MERGEABLE_LIBRARY build setting, see [Build Mergeable Library](https://developer.apple.com/documentation/xcode/build-settings-reference#Build-Mergeable-Library).

It sounds bit complicated but seems like we should handle MAKE_MERGEABLE flag for each configuration?
In Debug, no use the flag for not merging but for export.
In Release, add the flag for merging.

Thanks.

### macOS version

14.3.1

### Tuist version

4.4.0

### Xcode version

15.3

**Comment by pepicrft** [comment]
Hi @muukii,
Thanks for reporting this. Mergeable libraries are a bit of a mess, and we discourage them because they add more build-time implicitness that leads to unpredictability and unreliability in the output artifacts and Xcode features. Still, if you'd like to go with it, I'd recommend checking out if the build settings that Tuist generates are the expected ones. If so, I'd recommend following-up with Apple on their discussion forums to learn more about what configuration of options you need to get the desired output.

**Comment by muukii** [comment]
@pepicrft 
Thanks.
Yeah, it's a bit complicated. I ended up using Tuist's technique that uses dynamic modules in dev, static modules in release. For now, I have enough for my case.

That's been said, Since Tuist will add flags for mergeable libraries automatically, consumers can't change behavior. Like removing MAKE_MEAGEABLE flag in some cases. It would be better for consumers to have more controllable options I guess.

**Comment by muukii** [comment]
in anyways as long as using Tuist we don't have to use mergeable libraries unless to use make xcframeworks as mergeable to distribute.
I can understand this case should be low-priority.

**Comment by pepicrft** [comment]
Thanks @muukii. I'll then close this issue. The impact that mergeable configurations have on the build process and the generated artifacts is something out of the responsibilities of Tuist.
