### ISSUE TITLE
PackageSettings baseSettings is not applied as expected

### ISSUE THREAD

**Issue by Topwiz** [tuist/tuist#6065]
### What problem or need do you have?

I was using Tuist 3.16.0 and upgraded to 4.5.0, but I encountered an issue where the custom build settings for SPM frameworks are not being applied as expected.
I configured the PackageSettings as shown below, with five different configurations. In 3.16.0, it appeared as `image 1`, but in 4.5.0, it generates as `image 2`, where there are no configurations and the base setting is not applied. Am I doing something wrong?

```swift
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
    import ProjectDescription
    import ProjectDescriptionHelpers


    let packageSettings = PackageSettings(
        productTypes: [
            Define.SPM.ComposableArchitecture.rawValue: .framework,
            Define.SPM.SunKit.rawValue: .framework
        ],
        baseSettings: .settings(
            base: ["EXCLUDED_ARCHS[sdk=iphonesimulator*]": .string("arm64")],
            configurations: Define.Configuration.configurations
        )
    )
#endif


let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "https://github.com/pointfreeco/swift-composable-architecture", exact: "0.55.0"),
        .package(url: "https://github.com/Sunlitt/SunKit", exact: "2.7.0"),
    ]
)
```

| image 1 | image 2 |
|:-:|:-:|
| ![스크린샷 2024-03-12 오후 5 54 13](https://github.com/tuist/tuist/assets/25401387/3faefa2a-519d-4d5d-9e75-d5dc9339cd90) | ![스크린샷 2024-03-12 오후 6 41 19](https://github.com/tuist/tuist/assets/25401387/39604905-7d84-4ca3-ab0e-7f650588fb13) |

### macOS version

14.3

### Tuist version

4.5.0

### Xcode version

15.2

**Comment by leeari95** [comment]
I'm having the same issue... 🥲

**Comment by fortmarek** [comment]
Thanks for reporting this, the fix is on the way: https://github.com/tuist/tuist/pull/6070 🤞
