### ISSUE TITLE
Installing Tuist with mise failed

### ISSUE THREAD

**Issue by KaiOelfke** [tuist/tuist#6077]
### What happened?

I had unzipping errors (see error log).

And `tuist cloud auth` always resulted in persistently high CPU load (> 100%). After entering the token nothing happened. I got Firewall prompts about allowing incoming connections for Tuist. Allowing that or disabling the Firewall didn't help.

I later uninstalled tuist and mise and successfully installed with brew. But then I ran into this issue: 

https://github.com/tuist/tuist/issues/5763

### How do we reproduce it?

In hindsight I'm not sure, if it's something with my machine or reproducible in general.

I followed the [installation documentation](https://docs.tuist.io/documentation/tuist/installation/).

First I installed mise, which worked. Then tuist. The first attempt failed with this unzipping. Another try worked. But I got stuck with tuist cloud auth.

### Error log

```
2024-03-13T11:50:53+0800 error [http://io.tuist.support](https://t.co/ndqAXkni0G) : The '/usr/bin/unzip' command exited with error code 9 and message:
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/TemporaryDirectory.33OUNc/tuistenv.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/TemporaryDirectory.33OUNc/tuistenv.zip or
        /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/TemporaryDirectory.33OUNc/tuistenv.zip.zip, and cannot find /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/TemporaryDirectory.33OUNc/tuistenv.zip.ZIP, period.
```

### macOS version

14.3.1 (23D60)

### Tuist version

4.6.0

### Xcode version

15.3.0

**Comment by fortmarek** [comment]
Hey 👋 

From what I can understand, the install succeeded (even if on the second try which could be an issue in `mise` and should be reported there) but you currently have issues with `tuist cloud auth`, is that correct?
