### ISSUE TITLE
Documentation:  Adding external Dependencies and Tuist/Dependencies directory

### ISSUE THREAD

**Issue by KaiOelfke** [tuist/tuist#6079]
### What problem or need do you have?

After doing `tuist init` I didn't have a Tuist or Dependencies folder for my project. I then followed the tutorial:

https://docs.tuist.io/tutorials/tuist/external-dependencies/

But it didn't work, because `tuist install` didn't install the SPM dependency. I eventually figured out that I had to create these directories to make it work.

Either the tutorial should make this more clear or tuist init should generate these folder structure. But I'm new to Tuist so I don't know.

### Potential solution

- Generate the folders with tuist init
- Clarify in the tutorial on the folder structure that needs to be present

### macOS version

14.3.1 (23D60)

### Tuist version

4.6.0

### Xcode version

15.3.0

**Comment by danieleformichelli** [comment]
Can you provide a sample project? The tutorial should be correct AFAICT

**Comment by KaiOelfke** [comment]
This is what I ended up with. [SampleProject.zip](https://github.com/tuist/tuist/files/14598414/SampleProject.zip)

> External dependencies are defined in a Package.swift manifest file in the /Tuist directory in the root of your project. **You can also define your Package.swift directly in the root if you are working on an SPM package.**

I'm learning how to use Tuist. Previously my (non-tuist) projects are structured in a minimal app target plus one local package with many targets containing 99% of the code. The Package.swift in the root folder. From the tutorial I understand that this is also ok for Tuist. But it's apparently not ok unless working on just an SPM package.

Without creating a Tuist folder as it's not automatically created with tuist init `tuist install` fails to install the dependency.

**Comment by danieleformichelli** [comment]
Thanks, I can replicate it 🙏 
it's a bug of `tuist install`, rather than a documentation issue! :)

Thanks for reporting it! 🎉

**Comment by pepicrft** [comment]
@KaiOelfke would you like to contribute this one? [This](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Services/InitService.swift) is the logic that creates the project, and [this](https://github.com/tuist/tuist/tree/main/Templates/default) is the template that we use for that. After you add it, you can [update this acceptance test](https://github.com/tuist/tuist/blob/main/Tests/TuistAcceptanceTests/InitAcceptanceTests.swift) to run the `InstallCommand` and ensure it succeeds after initializing the project.

**Comment by fortmarek** [comment]
The missing `Tuist` directory with `Package.swift` should be fixed by: https://github.com/tuist/tuist/pull/6044

**Comment by fortmarek** [comment]
Should be resolved now. I'd recommend opening a new issue if needed.
