### ISSUE TITLE
Change argument name of automaticCodeSigning(devTeam: String) to devTeamID to clarify the team id is needed

### ISSUE THREAD

**Issue by KaiOelfke** [tuist/tuist#6087]
### What problem or need do you have?

The argument name isn’t clear. I first entered “Kai Oelfke” as that’s my team name, which resulted in code signing errors in the generated project. In Xcode it also appears as “Kai Oelfke” in the UI. But with `func automaticCodeSigning(devTeamID: String)` I’d have immediately looked up the ID instead. So a clearer argument name would have saved me some time and trouble here. 

I can create a PR with an argument name change, if you agree with this issue.

### Potential solution

Change `func automaticCodeSigning(devTeam: String)` to `func automaticCodeSigning(devTeamID: String)`.

### macOS version

14.3.1 (23D60)

### Tuist version

4.6.0

### Xcode version

15.3.0

**Comment by danieleformichelli** [comment]
On one side I agree it would be clearer.
On the other, the Xcode setting is called DEVELOPER_TEAM, and there is value in trying to stay close to Xcode naming. Also, I hope the documentation for the method explains that, which would remove any doubt.

**Comment by KaiOelfke** [comment]
The documentation is:

```md
Sets `"CODE_SIGN_STYLE"` to `"Automatic"` and `"DEVELOPMENT_TEAM"` to `devTeam`
```

It would be helpful, if the documentation would link to https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/.

**Comment by KaiOelfke** [comment]
Sure, that makes sense. I forgot the complications of such changes in a library context. I can do the PR later, when I have time again.
