### ISSUE TITLE
Duplicate dependencies in Package.swift do not result in a warning

### ISSUE THREAD

**Issue by KaiOelfke** [tuist/tuist#6090]
### What problem or need do you have?

E.g. doing `tuist install` with this

```swift
// swift-tools-version: 5.10

import PackageDescription

let package = Package(
  name: "PackageName",
  dependencies: [
    .package(url: "https://github.com/pointfreeco/swift-dependencies", from: "1.0.0"),
    .package(url: "https://github.com/pointfreeco/swift-dependencies", from: "1.2.0"),
  ]
)
```

### Potential solution

Show a warning, if the dependency is duplicated unless there's valid use cases for this.

### macOS version

14.3.1 (23D60)

### Tuist version

4.6.0

### Xcode version

15.3.0

**Comment by KaiOelfke** [comment]
[TuistDuplicatePackage.zip](https://github.com/tuist/tuist/files/14626091/TuistDuplicatePackage.zip)

**Comment by danieleformichelli** [comment]
Does SMP shows a warning if you try to swift package resolve it?
