### ISSUE TITLE
SPM dependency with a dash failed to compile

### ISSUE THREAD

**Issue by JohnnyTseng** [tuist/tuist#6099]
### What problem or need do you have?

Hi, 

We are using [YoutubePlayer-in-WKWebView](https://github.com/hmhv/YoutubePlayer-in-WKWebView) as our project's dependency, however, it fails to compile with Tuist 4 (Tuist 3 works fine)

It seems like a issue with a dash 
The import statement tries to import a file that contains a dash, however the actual file does not contain a dash

`#import "TuistBundle+YoutubePlayer-in-WKWebView.h"` ❌
`#import "TuistBundle+YoutubePlayerInWKWebView.h"` ✅

![Screenshot 2024-03-21 at 18 33 38](https://github.com/tuist/tuist/assets/2656519/fa2a5195-2c83-4924-9dbe-b88504e33dce)

After fixing the import, another error popped up

![Screenshot 2024-03-21 at 18 36 24](https://github.com/tuist/tuist/assets/2656519/c10f5cea-f802-4865-826e-6aa23adc4061)

I am not sure if this is an issue that can be fixed on Tuist's end

NOTE: I noticed in Tuist `4.6.0` contains a PR that fixes this issue, however I've already upgraded Tuist to 4.6.0, it still compile fails

### macOS version

14.4

### Tuist version

4.6.0

### Xcode version

15.3

**Comment by pepicrft** [comment]
@JohnnyTseng do you have the link to that PR? If you'd like to look into the issue yourself. [Here's](https://github.com/tuist/tuist/blob/f795995ea83fe022bc2ea1559afbda8862ee9538/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift#L276) the template that's being used. And [this is the place](https://github.com/tuist/tuist/blob/f795995ea83fe022bc2ea1559afbda8862ee9538/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift#L140) where it's being called from. I see that we are passing the raw target name, so I don't think the issue is fixed at all.

**Comment by JohnnyTseng** [comment]
Hi @pepicrft: 

The PR is https://github.com/tuist/tuist/pull/6042 mentioned in release [4.6.0](https://github.com/tuist/tuist/releases/tag/4.6.0), I am not sure if it fixes the same issue I encountered though.

I'll take a look into this issue after I got back from holiday!

**Comment by fortmarek** [comment]
@JohnnyTseng I don't think it does, the PR I did was to make map dash into underscore. But to fix this, we probably need something quite similar 🙏

**Comment by sbo-nemlig** [comment]
Don't know if this is the same issue but firebase in-app messaging looks to have the samme issue. Their framework is named "firebaseInAppMessaging_iOS" but Tuist creates a TuistBundle+FirebaseInAppMessagingIOS file but imports it as "TuistBundle+FirebaseInAppMessaging_iOS.h

**Comment by fortmarek** [comment]
It's quite likely the same issue, thanks for rasiing this @sbo-nemlig. I'm gonna take a look.

**Comment by fortmarek** [comment]
@sbo-nemlig @JohnnyTseng can either of you provide a reproducible sample? That would be really helpful 🙏 I wasn't able to reproduce the issue with `FirebaseInAppMessaging` but maybe I'm missing something.

**Comment by sbo-nemlig** [comment]
@fortmarek  sure here is a simple project where it fail https://github.com/sbo-nemlig/tuist-firebaseInAppMessage
