### ISSUE TITLE
Support privacy manifest files

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#6100]
### What problem or need do you have?

Apple [introduced](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) will soon require apps to include it for a set of predefined dependencies. Therefore, we must ensure we include them when generating targets for Swift Packages.

**Comment by spqw** [comment]
## Issue with google-mobile-ads

The privacy manifest from `google-mobile-ads` is not picked up by Xcode tooling when archiving the project. 

Failing scenario

- Given a project with google-mobile-ads dependency in Tuist/Package.swift
- When user archives project and generates privacy report
- Then user expects to see mentions from google-mobile-ads privacy manifest in the generated app privacy report

It's working for firebase though. 

Following is a sample app with both `firebase` and `google-mobile-ads` dependencies. The generated privacy report includes mentions from `firebase` privacy manifest but not the ones from `google-mobile-ads`. 

[Vanilla.zip](https://github.com/tuist/tuist/files/14958383/Vanilla.zip)

Following is the expected privacy report generated when adding `google-mobile-ads` as a local framework, or when setting "Embed & sign" on Xcode. 

[GoogleMobileAds-PrivacyReport.pdf](https://github.com/tuist/tuist/files/14958392/GoogleMobileAds-PrivacyReport.pdf)


**Links**
- repo for google-mobile-ads: https://github.com/googleads/swift-package-manager-google-mobile-ads/tree/main
- repo for firebase: https://github.com/firebase/firebase-ios-sdk/releases
