### ISSUE TITLE
How to autocomplete api like Xcode did?

### ISSUE THREAD

**Issue by KittenYang** [tuist/tuist#6103]
### What problem or need do you have?

The experience of  writing tuist's `Projecti.swift` is nightmare !! How can it autocomplete api like Xcode? I upgrade it from 3.18.0 to 4.7.0, the api is breaking change, my project is totally broken and can't open anymore. It's horrible !!

### macOS version

12.0

### Tuist version

4.7.0

### Xcode version

15.0

**Comment by KittenYang** [comment]
WTF, doc is also overtime! Waste my whole day!!  https://docs.old.tuist.io/guides/third-party-dependencies
If I use this tool again, I am not human！

**Comment by fortmarek** [comment]
Hey 👋 

You can find the new docs here: https://docs.tuist.io/documentation/tuist/

The breaking changes in tuist 4 can be found here: https://github.com/tuist/tuist/releases/tag/4.0.0

You can edit your projects with Xcode the same way you did with Tuist 3 by running `tuist edit`, nothing changes there. If you have a specific problem, feel free to raise an issue with reproduction steps. For more general help, use Github discussions or join our Slack.
