### ISSUE TITLE
Test target fails to load dynamic libraries of xcframework

### ISSUE THREAD

**Issue by muukii** [tuist/tuist#6115]
### What problem or need do you have?

- Using AgoraSDK which is xcframework that contains dynamic linking binaries.
- Test target that uses them fails to launch because necessary binaries were not found(AgoraSDK)
- rpath looks fine but not working.

![CleanShot 2024-03-25 at 13 53 21@2x](https://github.com/tuist/tuist/assets/1888355/9f4d691d-2cb4-480c-8060-2a01c4ee142c)

reproduction project:
https://github.com/muukii/tuist-catalog/tree/main/agora-test

### macOS version

1.4.3.1

### Tuist version

4.7.0

### Xcode version

15.3

**Comment by OhKanghoon** [comment]
Hi @muukii 
I'm experiencing the same problem, and may I know how you solved it?
In my case, I added AgoraSDK dependency to the framework target, and the same error is occurring in the unit test.

**Comment by muukii** [comment]
just sharing

I've added a script phase like this

```
        .post(script: """
#! /bin/zsh
#set -x

if [ "$ENABLE_PREVIEWS" == "YES" ]; then
  echo "👨🏻 codesign"
  echo "👨🏻 BUILD_PRODUCTS_DIR => $BUILT_PRODUCTS_DIR"
  echo "👨🏻 CODE_SIGN_IDENTITY => $CODE_SIGN_IDENTITY"
  echo "👨🏻 EXPANDED_CODE_SIGN_IDENTITY => $EXPANDED_CODE_SIGN_IDENTITY"
  for file in $(find "$TARGET_BUILD_DIR" -name 'Agora*.framework'); do

    # file name without extension
    name=$(basename "$file" .framework)
    echo $name

    binary_path="$file/$name"

    if codesign -vvv "$binary_path" >/dev/null 2>&1; then
      echo "Already signed, skipping: $binary_path"
    else
      # Sign the binary
      codesign --sign <your sign> --preserve-metadata=identifier,entitlements "$binary_path"
      if [ $? -eq 0 ]; then
        echo "Successfully signed: $binary_path"
      else
        echo "Failed to sign: $binary_path"
      fi
    fi

  done

fi
""", name: "Sign Agora")
```
