### ISSUE TITLE
Add target app icon badge feature

### ISSUE THREAD

**Issue by kapitoshka438** [tuist/tuist#6131]
### What problem or need do you have?

It would be great to add an option to generate AppIcon sets with a badge for each application `Target` by passing path to the badge image. Just like [fastlane-badge-plugin](https://docs.fastlane.tools/actions/badge/) does it.

### macOS version

14.4.1

### Tuist version

4.8.1

### Xcode version

15.3

**Comment by kapitoshka438** [comment]
I'd like to have something similar to this tool or its Fastlane plugin:
https://github.com/HazAT/badge

`Target` init would accept a new parameter (TargetIconBadgeConfig):
- path to a `.appiconset`
- badge text
- badge color
- badge text color
- custom badge image as an option
- badge font (maybe?)
- shield info (colors, text etc, similar to that tool)

This would draw stuff on the source images using CoreGraphics and generate a new icon set for the Target, link it to the target resources and put it somewhere in derived folder to let it be passed to gitignore. 
I know this can be challenging and may not be perceived as something important and related to Tuist core functionality. But this would help to have more features working out the box.
We have 4 application targets: dev, test, pre (pre-release) and production (no-badge) with unique app icons.

**Comment by fortmarek** [comment]
I'd recommend moving the conversation to our [forum](https://community.tuist.io/) if there's still a need for this. I wonder how much of this is actually Tuist's concern. This feature is quite opinionated, so I'd lean for this to be a standalone Swift package/executable instead.
