### ISSUE TITLE
Work with external dependencies is broken, tuist install command is not correct

### ISSUE THREAD

**Issue by starovoytov-s** [tuist/tuist#6138]
### What problem or need do you have?

I have the same problems working with external dependencies on different projects

For example i have started new project with tuist init and with this dependency:
<img width="903" alt="Screenshot 2024-04-01 at 13 16 34" src="https://github.com/tuist/tuist/assets/63556577/e80c2cc7-ae99-4e6c-8493-94072c81426c">
<img width="646" alt="Screenshot 2024-04-01 at 13 25 48" src="https://github.com/tuist/tuist/assets/63556577/bfa4e1aa-8f3d-4b60-871f-616eaa376528">

Next steps:
<img width="737" alt="Screenshot 2024-04-01 at 13 15 54" src="https://github.com/tuist/tuist/assets/63556577/044d2e3d-c850-4fec-b38a-179cc5091495">
<img width="413" alt="Screenshot 2024-04-01 at 13 16 03" src="https://github.com/tuist/tuist/assets/63556577/9cd372d2-fa32-4fdd-991e-9f0f802e44e3">

At the same time the documentation tells us - "install - Installs any remote content (e.g. dependencies) necessary to interact with the project.
<img width="591" alt="Screenshot 2024-04-01 at 13 24 08" src="https://github.com/tuist/tuist/assets/63556577/b6fb6bb9-b566-457b-bddf-eafc3c8e3daa">

Where is the problem?

### macOS version

13.6.5

### Tuist version

4.8.0

### Xcode version

15.2

**Comment by anuragajwani** [comment]
I am having the same problem at the moment. I am on 4.8.1 and still the same. I was wondering if `tuist install` is the wrong command to execute however the docs do specify this:

```
Run tuist install to resolve the dependencies using the Swift Package Manager under Tuist/Dependencies. The generated workspace will contain projects and targets for them.
```

**Comment by anuragajwani** [comment]
Note I was able to fix it by installing tuist CLI from the tuist releases tab (inside tuist.zip). Given the docs no longer mentioning installation via sh command I believe the old installation is somehow interfering with the `install` command

**Comment by starovoytov-s** [comment]
@anuragajwani Thanks, i removed all old versions and installed tuist from scratch, now it is working
