### ISSUE TITLE
Generate test targets when generating from `Package.swift` file

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [tuist/tuist#6143]
### What problem or need do you have?

The docs state:
> If you are working on an SPM package, you shouldn’t need to update anything. Tuist automatically picks up on your root Package.swift and all the features of Tuist work as if it was a Project.swift manifest.

However if you try this with https://github.com/Tyler-Keith-Thompson/Afluent you'll notice that tests do not get generated. 

### Potential solution

I expect that tests get generated along with the production code (including cached test dependencies)

### macOS version

14.2.1

### Tuist version

4.8.1

### Xcode version

15.3

**Comment by danieleformichelli** [comment]
For whoever will work on this, I think it could make sense to generate test targets also for local packages, so that you can freely mix together packages and projects

**Comment by woin2ee** [comment]
I think I may have found a clue while looking into this issue. I'll try to open the PR soon.

**Comment by Tyler-Keith-Thompson** [comment]
Him, I see this is marked completed and merged...however it's notable that when using Tuist 4.20.0 pointed at the example repository I included in this issue test targets are still not generated.

**Comment by fortmarek** [comment]
Hey @Tyler-Keith-Thompson 👋 

What project exactly are you trying to generate?

**Comment by Tyler-Keith-Thompson** [comment]
> Hey @Tyler-Keith-Thompson 👋
> 
> What project exactly are you trying to generate?

https://github.com/Tyler-Keith-Thompson/Afluent

**Comment by fortmarek** [comment]
The fixture I was testing the feature with was [spm_package](https://github.com/tuist/tuist/tree/main/fixtures/spm_package). The generated project for that fixture _does_ include the test targets.

But, indeed, `tuist generate` in your project is missing the test targets. I don't see anything majorly different between the two.

Would you mind opening an issue for this? @woin2ee any ideas? 🤞

**Comment by woin2ee** [comment]
After a bit of debugging, I realized that `destinations` is initialized to 0 when an external dependency included to a dependency of the test target in [here](https://github.com/tuist/tuist/blob/abd0f7689673e46cfd8ba3f3eaec0192ef8db36d/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift#L464-L478).
I think it has not considered to external dependencies. Do you think this is possible? @fortmarek

**Comment by fortmarek** [comment]
@woin2ee good catch! Let's update the `spm_package` fixture with this scenario and find a fix. Do you feel like taking a stab at this 🔪?

**Comment by woin2ee** [comment]
@fortmarek Since I'm feeling a responsibility for this, I'd like to give it a try after work today.

**Comment by fortmarek** [comment]
> Since I'm feeling a responsibility for this, I'd like to give it a try after work today.

Thanks, @woin2ee 🙌 Feel no rush on this, though, especially since this is still a new feature. If you ever need us to pick up something, let us know, we don't want you to burn out!
