### ISSUE TITLE
Failure of 'tuist install' on Jenkins

### ISSUE THREAD

**Issue by topkim993** [tuist/tuist#6150]
### What happened?

When trying to run 'tuist install' via Jenkins, we encounter failures with the following error when the github.com keychain is present. Downloads keep piling up, staying in a downloaded state without progressing, which eventually causes the process to fail.

Removing the github.com keychain manually fixes the problem. After that, the downloads proceed as usual, leading to a successful installation.

### How do we reproduce it?

`tuist install`

### Error log

```
error: Failed to find credentials for 'https://github.com' in keychain: status -25308
...

Downloading https://dl.google.com/firebase/ios/bin/firestore/10.19.0/FirebaseFirestoreInternal.zip, ...
Downloading https://dl.google.com/firebase/ios/bin/firestore/10.19.0/FirebaseFirestoreInternal.zip, https://dl.google.com/firebase/ios/swiftpm/10.17.0/GoogleAppMeasurementIdentitySupport.zip, https://dl.google.com/firebase/ios/swiftpm/10.17.0/FirebaseAnalytics.zip, https://dl.google.com/firebase/ios/bin/grpc/1.49.2/grpc.zip, https://dl.google.com/firebase/ios/bin/grpc/1.49.2/openssl_grpc.zip
(continues to increase)
...

error: fatalError
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

13.6.1

### Tuist version

4.1.1

### Xcode version

15.0.1

**Comment by fortmarek** [comment]
Hey 👋 

`tuist install` only runs `swift package resolve`, so this is not a tuist bug (which is why I'm closing this). You can confirm that by running `swift package resolve` in the Tuist directory.

This sounds like your machine is misconfigured – why do you have an entry for github.com without any credentials?

**Comment by topkim993** [comment]
Understanding that "tuist install" only executes "swift package resolve"

I think this will help streamline the investigation of the problem.

Thank you!
