### ISSUE TITLE
LookinServer cannot be operated through Tuist Dependency

### ISSUE THREAD

**Issue by topkim993** [tuist/tuist#6157]
### What happened?

If you set the lookinserver dependency through tuist, you cannot check inspectable apps.

However, it works fine when using Navtive SPM.

Can I get help?

tuist dependency
<img width="828" alt="스크린샷 2024-04-09 오후 4 35 10" src="https://github.com/tuist/tuist/assets/57055565/a0d00477-9eb5-4492-a28c-a13ce01474fb">

spm
<img width="922" alt="스크린샷 2024-04-09 오후 4 38 20" src="https://github.com/tuist/tuist/assets/57055565/c426b4fb-c471-4711-adb2-3a50eeb4e07f">

### How do we reproduce it?

repro case

download [Lookin Client](https://lookin.work/) and run
download [lookin_test_tuist.zip](https://github.com/tuist/tuist/files/14915100/lookin_test_tuist.zip)
tuist install
tuist genertate
run

Not works
[lookin_test_tuist.zip](https://github.com/tuist/tuist/files/14915100/lookin_test_tuist.zip)

Works
[LookinTestNative.zip](https://github.com/tuist/tuist/files/14915101/LookinTestNative.zip)

### Error log

No error message occurred separately.

It doesn't seem to be functioning due to the SHOULD_COMPILE_LOOKIN_SERVER preprocessing directive.

ref. https://bytedance.larkoffice.com/docx/TvjvdfZsIoTszxxwPLsc29Rhneh

### macOS version

13.5.2

### Tuist version

4.1.1

### Xcode version

15.0.1

**Comment by rakuyoMo** [comment]
When I integrate via tuist, it doesn't even generate the project.See: https://github.com/tuist/tuist/issues/6158

**Comment by fortmarek** [comment]
Hey 👋 

I'm looking into this one. We're not properly handling the [configuration condition](https://github.com/QMUI/LookinServer/blob/develop/Package.swift#L44) and we end up just filtering that condition out.

**Comment by fortmarek** [comment]
The fix for this issue can be found [here](https://github.com/tuist/tuist/pull/6170). Extra testing is always appreciated, you can check out the steps how to do so in the PR 🙂
