### ISSUE TITLE
Static Library Targets Do Not Support Resources

### ISSUE THREAD

**Issue by iteracticman** [tuist/tuist#6172]
### What problem or need do you have?

When trying to use a `Target` with type `.staticLibrary` that contains resources `tuist generate` fails with error message "Target ... cannot contain resources. static library targets do not support resource". At least when used in Projects where both `disableSynthesizedResourceAccessors` and `disableBundleAccessors` are set to `true`.

This probably makes sense, but the there should be hint in the error message that this would be possible is those settings were changed.

Related Slack discussion: https://tuistapp.slack.com/archives/CCXC295QS/p1712754427922909?thread_ts=1712682908.272429&cid=CCXC295QS

Note: Maybe the same/similar issue for `.staticFramework` targets.

### macOS version

14

### Tuist version

4.9.0

### Xcode version

15.3

**Comment by pepicrft** [comment]
> This probably makes sense, but the there should be hint in the error message that this would be possible is those settings were changed.

This is a good point. For whoever takes this, is a matter of improving the error message to indicate that by disabling the synthesizing features, you are also preventing libraries from having resources through an auto-generated bundle
