### ISSUE TITLE
Ability to specify targets to gather coverage info for

### ISSUE THREAD

**Issue by abbasmousavi** [tuist/tuist#618]
## Need/problem

I want to be able to specify the targets that Xcode reports test coverage for them. Currently we can only specify if we want the code coverage or not in `TestAction(targets: [Targets], coverage: true)`

![Screenshot 2019-10-30 at 11 55 31](https://user-images.githubusercontent.com/1249875/67856349-3e01de80-fb0c-11e9-9434-997332509013.png)

## suggetion

We can add a new argument to the `TestAction` initiator like 

```
TestAction(targets: [Targets], coverage: true, codeCoverageTargets: [String]?)
```

**Comment by abbasmousavi** [comment]
I just noticed that there is a `codeCoverageTargets` property in `TestAction` in `XcodeProj`. I will open a PR to add this to Tuist.

**Comment by pepibumur** [comment]
> I just noticed that there is already a codeCoverageTargets property in TestAction in XcodeProj. I will open a PR to add this to Tuist.

Awesome! Thanks for contributing this feature yourself. We appreciate it a lot @abbasmousavi.
By the way, I reviewed the PR and it's very well implemented for being your first contribution, congrats 👏
