### ISSUE TITLE
Missing --derived-data-path in `test test`

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#6184]
### What happened?

When I specify `--derived-data-path` in `tuist generate`I get an error stating that this option does not exist.

But relying on the `TestCommand.swift` sources they should be

### How do we reproduce it?

`tuist test --derived-data-path path/to/directory`

### Error log

Error: Unknown option '--derived-data-path'

### macOS version

14

### Tuist version

4.9.0

### Xcode version

15

**Comment by Ernest0-Production** [comment]
Also missing is the ability to pass additional flags to xcodebuild

for example to generate code coverage

**Comment by fortmarek** [comment]
We'll fix it 🙏 

Regarding the extra `xcodebuild` commands, it's something we'd love to add support for. Would you mind creating a separate issue for that?
