### ISSUE TITLE
Firebase Crashlytics Script Issue

### ISSUE THREAD

**Issue by ungchun** [tuist/tuist#6188]
### What happened?

Hi, I'm a student working on a tuist project
It's not a bug, but there's something I couldn't solve

The project version I was working on was 3.27.1, I recently tried to put firebase Crashlytics on it, but I saw this issue (https://github.com/tuist/tuist/issues/6036) and turned up the version

I tried to write a build script after looking at several examples, but it keeps getting errors
<img width="315" alt="스크린샷 2024-04-14 오후 11 17 04" src="https://github.com/tuist/tuist/assets/50910456/9f7685e9-ec17-4709-837f-4c976bbc04ed">

I've been trying to fix this and that all day, but I couldn't solve it in the end
Maybe the route is wrong.. I don't have a clue where to fix it..

I'll make an example project with a similar environment to the existing project and attach it

### How do we reproduce it?

[test.zip](https://github.com/tuist/tuist/files/14971065/test.zip)
1. Download and decompress the test.zip file
2. mise exec -- tuist clean
3. mise exec -- tuist install
4. mise exec -- tuist generate
5. check error

### Error log

/Users/kimsunghun/Library/Developer/Xcode/DerivedData/tenten-evumcynbymjqaccoioytalvzwkgu/Build/Intermediates.noindex/App.build/Debug-iphonesimulator/App.build/Script-0B2953F44373DD14F0C40408.sh: line 2: /Users/kimsunghun/Library/Developer/Xcode/DerivedData/tenten-evumcynbymjqaccoioytalvzwkgu//Tuist/.build/checkouts/firebase-ios-sdk/Crashlytics/run: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

### macOS version

14.4.1

### Tuist version

4.9.0

### Xcode version

15.2

**Comment by kapitoshka438** [comment]
{project_dir}/Tuist/.build/checkouts/firebase-ios-sdk/Crashlytics/run

**Comment by fortmarek** [comment]
Yup, the location of the script is as @kapitoshka438 posted. Closing as otherwise, I don't see any other issue being reported.

**Comment by stodirascu** [comment]
Ok seems I was using the wrong version of the TargetScript helper function - `.post(path:)` instead or `.post(script)`. I thought the first version is for a script path, and the second one is for the script contents, but actually it's a Tuist path and a regular string path.
