### ISSUE TITLE
Info.plist generation issue

### ISSUE THREAD

**Issue by lukakilas** [tuist/tuist#6192]
### Can't create launch screen

I'm using tuist for my project.
I want to add launchscreen. The new way of adding launchscreen is to use info.plist.

```
private func createInfoPlist() -> InfoPlist {
    let plist: [String: Plist.Value] = [
        "UILaunchScreen": ["Image Name": "LaunchImage",
                           "Background color" : "LaunchScreenColor"],
        "UISupportedInterfaceOrientations": ["UIInterfaceOrientationPortrait"],
        "CFBundleShortVersionString": "\(version)",
        "CFBundleVersion": "\(bundleVersion)",
        "CFBundleDisplayName": "$(APP_DISPLAY_NAME)",
        "BASE_URL" : "$(BASE_URL)"
    ]
    return .extendingDefault(with: plist)
}

```

this is my code inside the Project.swift file, for creating info.plist. After the `tuist generate`, my info.plist file looks like this.
As you see, "Background Color" and "Image Name" show up white, while other properties are grayed out. It means that those properties aren't applied. So my launchscreen doesn't show up. If I add manually those properties from info.plist file everything works as expected.

<img width="1247" alt="Screenshot 2024-04-15 at 11 06 16 AM" src="https://github.com/tuist/tuist/assets/58978519/f95bef1a-bb29-49e6-b9ab-95bf69ce7f8c">

### macOS version

14.2.1

### Tuist version

4.9.0

### Xcode version

15.0.1

**Comment by fortmarek** [comment]
Hey 👋 

I recommend doing a diff on the `Info.plist` if you change the value manually and when the Plist is generated. Xcode simply reads the file directly, so there should be some difference between the two.
