### ISSUE TITLE
Option -package-name disappears if you use target settings

### ISSUE THREAD

**Issue by super-ultra** [tuist/tuist#6196]
### What happened?

If you set `OTHER_SWIFT_FLAGS` for target using 
```swift 
let packageSettings = PackageSettings(
    targetSettings: [
        "Logger": SettingsDictionary()
            .merging(["OTHER_SWIFT_FLAGS": .array(flags)])
    ]
)
```
then `-package-name` option disappears.

This problem can be solved by moving `OTHER_SWIFT_FLAGS` settings from `targetSettings` to `baseSettings`.

Example project: https://github.com/super-ultra/package-level-example

### How do we reproduce it?

1. Use attached project 
2. Run 
```sh 
tuist install
tuist generate
```
3. Option `-package-name` missed for target `Logger`

### Error log

No error. 

### macOS version

14.4.1

### Tuist version

4.9.0

### Xcode version

15.3.0

**Comment by fortmarek** [comment]
Hey 👋 

you need to add `$(inherited)` to the list of custom Swift flags. That's expected, so there's nothing for us to do, closing (sorry for such a late response).
