### ISSUE TITLE
A project cannot be generated when there is .when(platforms:) condition in Package.swift file

### ISSUE THREAD

**Issue by m-appleseed** [tuist/tuist#6199]
### What happened?

Since the release [4.3.2](https://github.com/tuist/tuist/releases/tag/4.3.2), we can't update Tuist because of https://github.com/tuist/tuist/pull/5953. As a result, we have the error.

### How do we reproduce it?

1. Use the attached sample project;
2. Move to the folder `App`;
3. Run ```sh tuist install```;
4. Run ```sh tuist generate```;
5. Get the error;

[ios_app_with_local_swift_package.zip](https://github.com/tuist/tuist/files/14998780/ios_app_with_local_swift_package.zip)

### Error log

> The target 'ModuleA' depends on the target 'Module_tvOS' from the same project at path /path/to/Packages whose hash hasn't been previously calculated.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

14.4.1

### Tuist version

4.9.0

### Xcode version

15.3

**Comment by PhilippeWeidmann** [comment]
I have the same problem with an external dependency.

The dependency Package.swift looks can be found here: https://github.com/swift-server-community/mqtt-nio/blob/main/Package.swift

Here is a minimal example project [tuist-test-platform.zip](https://github.com/tuist/tuist/files/15334248/tuist-test-platform.zip)

`tuist install` works
`tuist generate` gives the following output:
```
The target 'MQTTNIO' from project at path /somepath/tuist-test-platform/Tuist/.build/checkouts/mqtt-nio depends on the target 'NIOSSL' from the project at path /somepath/tuist-test-platform/Tuist/.build/checkouts/swift-nio-ssl whose hash hasn't been previously calculated.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

**Comment by pepicrft** [comment]
Thanks for the reproduction project @PhilippeWeidmann. We flagged this one as high priority to unblock you as soon as possible. We'll post you with any updates on this front.
