### ISSUE TITLE
Add xcodebuild args in tuist build and test command

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#6202]
### What problem or need do you have?

Tuist uses a limited set of Xcodebuild options to build and test my project. And does not allow me to pass additional parameters to Xcodebuild: for example, a flag to enable code coverage, disable spm resolution, skip simulator autodetection like fastlane scan/gym actions

### Potential solution

Detect extra options for passing to xcodebuild options:

### macOS version

15

### Tuist version

4.9.0

### Xcode version

15.3

**Comment by pepicrft** [comment]
I'm closing this one in favor of https://github.com/tuist/tuist/issues/6292
