### ISSUE TITLE
Generated -package-name disappears if package defines swiftSettings

### ISSUE THREAD

**Issue by ffittschen** [tuist/tuist#6203]
### What happened?

When a Swift Package that uses the `package` access level also defines `swiftSettings` in their Package.swift, the `-package-name` generated by Tuist will not be present in the `OTHER_SWIFT_FLAGS` of the generated target. E.g as with the jwt-kit package: 

https://github.com/vapor/jwt-kit/blob/9369604bc0cdf3b9d8cfc0305aa750ec8d8a8085/Package.swift#L29-L31

### How do we reproduce it?

1. Use the attached sample project
2. Run `tuist install`
3. Run `tuist generate`
4. Open the workspace
5. Inspect the `OTHER_SWIFT_FLAGS` of the `jwt-kit` target

[jwt-kit-example.zip](https://github.com/tuist/tuist/files/15012537/jwt-kit-example.zip)

### Error log

```
'base64URLDecodedBytes' has a package access level but no -package-name was specified: /.../Tuist/.build/checkouts/jwt-kit/Sources/JWTKit/Utilities/Base64URL.swift
```

### macOS version

14.4.1

### Tuist version

4.9.0

### Xcode version

15.3

**Comment by fortmarek** [comment]
Thanks for flagging this. I put up a fix [here](https://github.com/tuist/tuist/pull/6299).
