### ISSUE TITLE
How to init a project with Storyboard interface

### ISSUE THREAD

**Issue by isweal** [tuist/tuist#6208]
### What problem or need do you have?

the default action of `tuist init ` is to generate a app with SwiftUI, is there any param to init with Storyboard?

### macOS version

14.4.1

### Tuist version

4.9.0

### Xcode version

15.3

**Comment by fortmarek** [comment]
No, we currently only have a template for initializing a SwiftUI application as explained [here](https://github.com/tuist/tuist/issues/5763#issuecomment-2049069383). We'd be happy to accept a PR to add the UIKit template, possibly with a storyboard, back as that's something that Xcode also still allows.

You can take the removed UIKit template as an inspiration.

**Comment by isweal** [comment]
> No, we currently only have a template for initializing a SwiftUI application as explained [here](https://github.com/tuist/tuist/issues/5763#issuecomment-2049069383). We'd be happy to accept a PR to add the UIKit template, possibly with a storyboard, back as that's something that Xcode also still allows.
> 
> You can take the removed UIKit template as an inspiration.

ok, get it
