### ISSUE TITLE
--xcframework no longer works in v4

### ISSUE THREAD

**Issue by kientux** [tuist/tuist#6224]
### What problem or need do you have?

In tuist v4, the option `--xcframework` no longer exists in generate command. The changelog of v4 doesn't say anything about this. How do we upgrade from v3 if we currently using this param?

### macOS version

14

### Tuist version

3.17.0

### Xcode version

15.0

**Comment by danieleformichelli** [comment]
That parameter is now the default and only option, sorry for missing that in the changelog 🙏 
Feel free to open a PR to update the changelog if you want 🙏

**Comment by kientux** [comment]
Sorry for not asking clearly, but before that we use `--xcframeworks --destination device` to only build cache for device not simulator (some frameworks are not available for simulator slice). What's the equivalent now in v4?

**Comment by fortmarek** [comment]
We currently always build for both. Ideally, you'd use `tuist cache` on `main`, so that the command is not run _that_ often – that should make the compile time hit smaller.

**Comment by fortmarek** [comment]
Caching for device only is currently not possible. We could add support for this, would you mind creating an issue describing your need?
