### ISSUE TITLE
Tuist Manifest Project Compilation Broken With Stripe as Carthage Dependency

### ISSUE THREAD

**Issue by stherold** [tuist/tuist#6238]
### What happened?

We use [Stripe](https://github.com/stripe/stripe-ios) and integrate it using Carthage. They [seem to use tuist too](https://github.com/stripe/stripe-ios/blob/master/.tuist-version) which leads to a Tuist Project.swift file being downloaded to the ./Carthage/Checkouts folder in our projects root folder:
```
Carthage
├── Build
└── Checkouts
```

![image](https://github.com/tuist/tuist/assets/64915710/e3ca6c25-73d0-4d46-a9ef-4ddbb4d1bcaa)

`tuist edit` picks that up and fails compilation of the manifest project using many many error mesges, probably because they use an [older Tuist version](https://github.com/stripe/stripe-ios/blob/master/.tuist-version) than us.

### How do we reproduce it?

1. Create a sample project with Stripe integrated via standard Carthage
2. run tuist edit
3. compile

### Error log

Well they use Tuist 3.x and we use tuist `4.10.2`. They are not compatible. So all the breaking changes of Tuist 4 pop up.

### macOS version

14.4.1 (23E224)

### Tuist version

4.10.2 (newest)

### Xcode version

15.3

**Comment by danieleformichelli** [comment]
Hello :wave:
You can add the carthage folder to your `.tuistignore` file 🚀

**Comment by Blackjacx** [comment]
Oh wow yes that solves the issue! Many thanks. Is there a way such things can be asked quicker than generating such an extensive issue? Do you have Slack/Discord or something or would a GH discussion be more appropriate?

**Comment by fortmarek** [comment]
> Do you have Slack/Discord or something or would a GH discussion be more appropriate?

We generally prefer GH issues/discussions, but for quick questions, our Slack may, indeed, be more suitable in some cases. It's on our website or you can use this link: https://join.slack.com/t/tuistapp/shared_invite/zt-1y667mjbk-s2LTRX1YByb9EIITjdLcLw
