### ISSUE TITLE
Running Tuist through a custom Swift executable

### ISSUE THREAD

**Issue by anuragajwani** [tuist/tuist#6253]
### What problem or need do you have?

I am trying to run tuist command directly by using TuistKit. However the GenerateService is internal and not exposed as paart fo the public interface.

How can I easily run Tuist commands from my custom Swift executable?

I wasn't able to find any examples of how to do this.

### macOS version

14.4.1

### Tuist version

4.11.0

### Xcode version

15.3

**Comment by fortmarek** [comment]
Hey!

You can use [TuistGenerator](https://github.com/tuist/tuist/blob/main/Package.swift#L405-L408) as a lower-level library for generation itself.

If you want to use Tuist itself, you need to go through a Process and call the executable. `TuistKit` is not meant for external usage.
