### ISSUE TITLE
Depend on swift-tools-support-core instead of the swift-package-manager package

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#626]
## Context 🕵️‍♀️
As described [here](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#package-dependency-requirement):

> Note that packages which use branch-based dependency requirements cannot be depended-upon by packages which use version-based dependency requirements; you should remove branch-based dependency requirements before publishing a version of your package.

Packages that depend on the generator target of Tuist will have issues resolving the dependencies because the SPM doesn't support version-based dependencies that have branch-based dependencies. Carthage, for instance, dropped its dependency with some [SPM](https://github.com/Carthage/Carthage/pull/2863) utilities.

## What 🌱

To make it possible to reuse the generation logic, we'll need to drop the dependency with the Swift Package Manager packages. We'll need to find substitutes for the following elements that we are currently using:
- **Absolute & Relative paths:** None of the libraries out there that provide DSLs for file paths make a distinction between absolute & relative paths, and that distinction has been of great value for the project. I suggest re-implementing those classes in the project with only the API methods that we need.
- **DSL for defining a command line interface.** There are many libraries out there for this so we just need to pick one and use it.
- **Their replacement of the process class:** Here we can use the Foundation's `Process` class.

**Comment by kwridan** [comment]
Looks like the utilities have been pulled out to their own package!! 🎉

https://github.com/apple/swift-tools-support-core 

This should allow us to reduce the dependency footprint while keeping those great utilities.

**Comment by pepibumur** [comment]
> Looks like the utilities have been pulled out to their own package!! 🎉

Awesome! Then the name of this PR should be depend on that package instead :)
