### ISSUE TITLE
`KakaoMapsSDK` is not a valid configured external dependency

### ISSUE THREAD

**Issue by Youngs5** [tuist/tuist#6262]
### What happened?

![Uploading 스크린샷 2024-05-08 오후 4.13.55.png…]()
I did a 'tuist edit' on my project managed by tuist.
Open Manifests.xcworkspace and added external dependency for 'KakaoMapsSDK'.
I added up-to-major: 2.10.0 using the SPM link listed in the official documentation and performed tuist install.

Computing version for https://github.com/kakao-mapsSDK/KakaoMapsSDK-SPM.git
Computed https://github.com/kakao-mapsSDK/KakaoMapsSDK-SPM.git at 2.10.4 (0.55s)
Creating working copy for https://github.com/kakao-mapsSDK/KakaoMapsSDK-SPM.git
Working copy of https://github.com/kakao-mapsSDK/KakaoMapsSDK-SPM.git resolved at 2.10.4

I was able to check the following log and found no error log.

As the next task, I performed the 'tuist generate' command, but the error log as in the title is output and it does not generate.

### How do we reproduce it?

1. tuist edit
2. add dependency : KakaoMapsSDK
Manifests/Tuist/Pakage
<img width="674" alt="스크린샷 2024-05-08 오후 4 20 35" src="https://github.com/tuist/tuist/assets/82360640/ec52c7a8-2bdf-4bf2-b488-e5172603b02c">

Manifests/Projects/Presentation/Project.swift
<img width="674" alt="스크린샷 2024-05-08 오후 4 21 01" src="https://github.com/tuist/tuist/assets/82360640/87331011-3faf-4913-8812-746470af94a8">

4. tuist install
5. tuist generate
6. error

### Error log

`KakaoMapsSDK` is not a valid configured external dependency
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

14.3.1

### Tuist version

4.11.0

### Xcode version

15.3.0

**Comment by danieleformichelli** [comment]
The product name is `KakaoMapsSDK-SPM`

**Comment by Youngs5** [comment]
> The product name is `KakaoMapsSDK-SPM`

Thanks :)
