### ISSUE TITLE
Removing a dependency breaks tuist generate.

### ISSUE THREAD

**Issue by hbanzon** [tuist/tuist#6263]
### What happened?

After another developer had removed a third party dependency, other developers are running into this issue after attempting to run `tuist generate`:

```
$ tuist generate
Loading and constructing the graph
It might take a while if the cache is empty

The following warnings need attention:
The artifact for binary target PayPalCheckout of package PayPalCheckout cannot be found.
Consider creating an issue using the following link: 
```

### How do we reproduce it?

Developer A will do the following:
1. Remove a third party dependency, for us it was `PayPalCheckout` (but it can be any project)
2. Check in the change to the repo

Developer B will subsequently do the following:
1. Checkout the change from the same repo
2. Run `tuist install`
3. Run `tuist generate`

This happened to folks using Tuist Cloud and not using Tuist Cloud.

### Error log

```
The artifact for binary target PayPalCheckout of package PayPalCheckout cannot be found.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

14.2.1

### Tuist version

4.10.1

### Xcode version

15.3

**Comment by pepicrft** [comment]
I set this one as high-priority. Our hunch is that the SPM might be leaving some internal files with an updated state, and that causes our logic, which assumes an up-to-date state in those files, to fail. We might need to alleviate the strictness until Apple fixes that in the SPM.
