### ISSUE TITLE
Install by homebrew, and create project failed!

### ISSUE THREAD

**Issue by wangzhizhou** [tuist/tuist#6267]
### What happened?

![image](https://github.com/tuist/tuist/assets/8174538/46dc56ae-610e-41db-83cf-1fe5f5fced71)

### How do we reproduce it?

```bash
brew tap tuist/tuist
brew install tuist
mkdir MyApp
cd MyApp
tuist init --platform ios
```

### Error log

```bash
Could not find template default. Make sure it exists at Tuist/Templates/default
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

14.4.1

### Tuist version

4.12.1

### Xcode version

15.2

**Comment by pepicrft** [comment]
@wangzhizhou this has been [reported before](https://github.com/tuist/tuist/issues/5763). Could you try [this](https://github.com/tuist/tuist/issues/5763#issuecomment-2098204486) and let me know if it works?

**Comment by AballahNsour** [comment]
this happened to me too

**Comment by pepicrft** [comment]
@AballahNsour have you tried [this](https://github.com/tuist/tuist/issues/5763#issuecomment-2098204486)?

**Comment by wangzhizhou** [comment]
> this happened to me too

you can install it use the mise, and it works. maybe the homebrew installation have some problem about file system

**Comment by wangzhizhou** [comment]
the tuist 4.15.0 has fixed this problem, you can install it now:
```bash
brew tap tuist/tuist & brew install tuist
```
