### ISSUE TITLE
Specify output/destination for `generate` command.

### ISSUE THREAD

**Issue by jakeatoms** [tuist/tuist#6269]
## Summary
When running `generate` using the `--path` argument, the resulting xcworkspace is given a name and location that is the project from the `--path` argument. My team would find it quite beneficial to have an optional argument like `--output` that would allows us to name and place the xcworkspace.

## Background
We have a `Workspace.swift` manifest file at the root of the project. Due to some needs arising on the team, this is going to become a CI-only workspace. We're transitioning to using commands like `tuist generate --path Path/To/App1` for local development; allowing Tuist to walk the graph and generate a local, focused workspace. 

## Reasoning
We have a large team and a growing monorepo, so being able to standardize on a top-level xcworkspace really helps simplify our docs, guidance, and general workflows.

### Potential solution

Adding an optional argument to the `generate` command that would be used to override the default location and name of the generated workspace, when not generating from a `Workspace.swift` file.

### macOS version

14.4

### Tuist version

4.10.2

### Xcode version

15.2

**Comment by pepicrft** [comment]
@jakeatoms thanks for your suggestion. I'd need to understand your needs better to be able to provide you with a good path forward here:
> Due to some needs arising on the team, this is going to become a CI-only workspace.

**Comment by fortmarek** [comment]
Let's move the discussion to our [forum](https://community.tuist.io/) if you still have a need for this. Thanks for your understanding!
