### ISSUE TITLE
Tuist with dependency cycle failed to generate

### ISSUE THREAD

**Issue by vvisionnn** [tuist/tuist#6273]
### What happened?

the official [example in fixture folder](https://github.com/tuist/tuist/tree/main/fixtures/ios_workspace_with_dependency_cycle), 
I think this is a example for handle with dependency cycle, but with the latest tuist version 4.12.1, failed to generate
raised an error
```plaintext
Found circular dependency between targets: 
/Users/<username>/<folder>/tuist/fixtures/ios_workspace_with_dependency_cycle/Frameworks/FrameworkA:FrameworkA -> 
/Users/<username>/<folder>/tuist/fixtures/ios_workspace_with_dependency_cycle/Frameworks/FrameworkB:FrameworkB -> 
/Users/<username>/<folder>/tuist/fixtures/ios_workspace_with_dependency_cycle/Frameworks/FrameworkA:FrameworkA
```

### How do we reproduce it?

1. clone tuist repo (this repo)
2. walk into `fixture/ios_workspace_with_dependency_cycle` folder
3. run `tuist generate`
4. you will find the same error with what I reported

### Error log

```sh
Found circular dependency between targets: 
/Users/<username>/<folder>/tuist/fixtures/ios_workspace_with_dependency_cycle/Frameworks/FrameworkA:FrameworkA -> 
/Users/<username>/<folder>/tuist/fixtures/ios_workspace_with_dependency_cycle/Frameworks/FrameworkB:FrameworkB -> 
/Users/<username>/<folder>/tuist/fixtures/ios_workspace_with_dependency_cycle/Frameworks/FrameworkA:FrameworkA
```

### macOS version

14.4.1

### Tuist version

4.12.1

### Xcode version

15.3 Release

**Comment by vvisionnn** [comment]
while I cannot find this example in the official tuist 4 doc, but it still exist in tuist 3 doc, just want to make sure is this an error/bug or you guys just dropped this feature

**Comment by vvisionnn** [comment]
tuist 3 doc link: https://docs.tuist.io/reference/examples/ios_workspace_with_dependency_cycle

**Comment by pepicrft** [comment]
> while I cannot find this example in the official tuist 4 doc, but it still exist in tuist 3 doc, just want to make sure is this an error/bug or you guys just dropped this feature

The feature wasn't dropped in Tuist 4. We have the [tool](https://github.com/tuist/tuist/blob/main/Sources/TuistCore/Graph/CircularDependencyLinter.swift) in place with plenty of unit tests testing various scenarios. 

Based on the logs that you shared, the feature seems to be working fine. What makes you think otherwise?

**Comment by vvisionnn** [comment]
oh I know, so the example showing there does not means that we CAN create a cycle dependency structure but means tuist can detect cycle dependency and report it, am I right?

**Comment by vvisionnn** [comment]
@pepicrft I think this shouldn't be a problem if you can make sure my last reply is correct, I will close this issue for now

**Comment by fortmarek** [comment]
> oh I know, so the example showing there does not means that we CAN create a cycle dependency structure but means tuist can detect cycle dependency and report it, am I right?

Yes, that's correct 🙂
