### ISSUE TITLE
 Issue with enforceExplicitDependencies and Find Implicit Dependencies Checkbox Interaction

### ISSUE THREAD

**Issue by andresbrun** [tuist/tuist#6275]
### What happened?

I've encountered an issue where the enforceExplicitDependencies flag in Config generationOptions does not behave as expected. When this flag is enabled, the Find Implicit Dependencies checkbox remains checked. This appears to contradict the intended function of enforceExplicitDependencies, which suggests that the checkbox should be disabled by default under these conditions. Can this be adjusted for consistency with the flag's purpose?

### How do we reproduce it?

1. Use .options(enforceExplicitDependencies: true) on Config.generationOptions
2. tuist generate
3. Check Find Implicit Dependencies on the scheme is checked

### Error log

![image (1)](https://github.com/tuist/tuist/assets/2039612/beb8a1f3-f31f-4f9c-8261-e1e12ad378a1)
<img width="835" alt="image" src="https://github.com/tuist/tuist/assets/2039612/590145f8-66af-4a8d-8bff-9a7fa9318fe8">

### macOS version

14.4.1

### Tuist version

4.12.1

### Xcode version

15.3

**Comment by pm-dev** [comment]
I'm also curious how to turn off that checkbox. Would have expected it to be an option on [BuildAction](https://docs.tuist.io/references/project-description/structs/buildaction#buildaction)

**Comment by fortmarek** [comment]
`enforceExplicitDependencies` has been deprecated. You can turn of the `findImplicitDependencies` now using the `BuildAction`: https://docs.tuist.dev/en/references/project-description/structs/buildaction#findimplicitdependencies

**Comment by andresbrun** [comment]
Thanks, I'll give it a try
