### ISSUE TITLE
Standalone watchOS apps support

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#628]
# Overview

#623 adds initial support for watchOS platform targets to Tuist. In effort to incrementally add the necessary features this issue will list out the remaining items needed.

# Requirements

- [x] #623: Allow generating watchOS platform targets
- [x] #756: Add support for generating InfoPlist for watchOS apps
- [ ] Generate appropriate schemes to enable running watchOS apps
- [ ] Add standalone watch container product type

**Comment by pepibumur** [comment]
Thanks for opening this up @kwridan :)

**Comment by pontusm** [comment]
Any progress on this? For example, deployment target and device does not seem to support watchOS.

**Comment by kwridan** [comment]
Hi @pontusm, 

There's partial support - but some bits are still missing.

An example of what supported can be seen in the following fixture:
https://github.com/tuist/tuist/tree/master/fixtures/ios_app_with_watchapp2

**Comment by pontusm** [comment]
That's great to hear. I managed to work around it by using xcconfig-files and specifying the deployment target there instead. Maybe that is the recommended way to handle build settings instead of relying on Tuist to implement support for everything?
