### ISSUE TITLE
Braze SDK can't load the resources

### ISSUE THREAD

**Issue by cristi-lupu** [tuist/tuist#6283]
### What happened?

After https://github.com/tuist/tuist/pull/6234, the target resource name and the ones copied in the application target differ.

Tuist generates the following resource targets for Braze:
<img width="367" alt="image" src="https://github.com/tuist/tuist/assets/41613812/b4a594a0-c1a2-4b73-acbe-92bf7524b5f3">
- `braze-swift-sdk_BrazeKitResources`
- `braze-swift-sdk_BrazeUI`

and Braze expects this format and names when it tries to get the bundle (https://github.com/braze-inc/braze-swift-sdk/blob/main/Sources/BrazeUI/Resources.swift#L25):
```swift
    let bundleNames = [
      // SwiftPM source target resources
      "braze-swift-sdk_BrazeUI",
      // SwiftPM binary target resources
      "braze-swift-sdk_BrazeUIResources",
      // Cocoapods or prebuilt resources
      "BrazeUI",
    ]
```

The problem is how the resource bundles are integrated into the app target itself:
<img width="799" alt="image" src="https://github.com/tuist/tuist/assets/41613812/6d8dc476-9983-4c0a-8069-2b74c9d340f1">
<img width="916" alt="image" src="https://github.com/tuist/tuist/assets/41613812/41c26156-c10a-4fd4-bfe9-70e980f37101">
- `braze_swift_sdk_BrazeKitResources.bundle`
- `braze_swift_sdk_BrazeUI.bundle`

and because of the name mismatch, Braze can't find the bundles. Same for Tuist-generated bundle accessors.

### How do we reproduce it?

1. Build and run `fixtures/app_with_spm_dependencies`
2. Expect non-nil `brazeUILocalizedString` in `AppDelegate`, and no warning messages from Braze that it can't load the resources.

### Error log

Xcode logs:
```
[braze] Error: Unable to find UI resources bundle, cannot load localizations and acknowledgments
App/AppDelegate.swift:45: Precondition failed: Failed to fetch localized resource from BrazeUI
```

### macOS version

14.4.1

### Tuist version

4.12.1

### Xcode version

15.3

**Comment by danibachar** [comment]
The fix is already merged to main 
https://github.com/tuist/tuist/pull/6265

**Comment by cristi-lupu** [comment]
@danibachar  Good, waiting for the new version. Thank you!
