### ISSUE TITLE
Tuist doesn't work when used directly against the TCA package

### ISSUE THREAD

**Issue by rhysm94** [tuist/tuist#6288]
### What problem or need do you have?

I’m just trying to learn how to use Tuist, and while following the SPM tutorial I cloned the Composable Architecture GitHub repo, and ran these commands:

```bash
tuist install
```
which appears to have worked fine, but then running
```bash
tuist generate
```
causes this:

```
Loading and constructing the graph
It might take a while if the cache is empty
Using cache binaries for the following targets: SwiftSyntax, SwiftOperators, SwiftBasicFormat, SwiftParser, SwiftParserDiagnostics, SwiftSyntax509, SwiftSyntax510, SwiftDiagnostics
Target _SwiftSyntaxTestSupport which depends on SwiftSyntaxBuilder does not support the required platforms: visionos, tvos, ios, watchos. The dependency on SwiftSyntaxBuilder must have a dependency condition constraining to at most: macos. Target InlineSnapshotTesting which depends on SwiftSyntaxBuilder does not support the required platforms: ios, watchos, visionos, tvos. The dependency on SwiftSyntaxBuilder must have a dependency condition constraining to at most: macos. Target SwiftSyntaxMacrosTestSupport which depends on SwiftSyntaxMacros does not support the required platforms: ios, visionos, watchos, tvos. The dependency on SwiftSyntaxMacros must have a dependency condition constraining to at most: macos.
Target SwiftSyntaxMacrosTestSupport which depends on SwiftSyntaxMacroExpansion does not support the required platforms: visionos, tvos, ios, watchos. The dependency on SwiftSyntaxMacroExpansion must have a dependency condition constraining to at most: macos.
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

I know TCA’s repo is a constantly moving target out of your control, but the tutorial for the SPM method is now not working correctly. Is this just something that tuist doesn’t currently support, or can it be fixed with a minor tweak on the TCA repo, or a tweak to the `tuist generate` command?

Much appreciated! Thanks 😄

### macOS version

14.4

### Tuist version

4.13.0

### Xcode version

15.4.0

**Comment by pepicrft** [comment]
@rhysm94 I'm sorry for that. Would you mind attaching a project where we can reproduce that issue?

**Comment by rhysm94** [comment]
Thanks for replying!
There's not much in the way of a project for me to upload.

I ran these commands:

```bash
git clone https://github.com/pointfreeco/swift-composable-architecture
cd swift-composable-architecture
tuist install
tuist generate
```

It was at the last step that the issue above happens.

**Comment by pepicrft** [comment]
Thanks! I'll try to debug the issue and provide a fix for it. Note that Tuist doesn't support or flavours of projects that use Package.swift as its DSL. We recommend using `Project.swift` instead.

**Comment by kylebrowning** [comment]
Project.swift doesn't seem to work either

**Comment by pepicrft** [comment]
Thanks @rhysm94. We'll look into those. @kylebrowning, which project are you referring to?

**Comment by ahmdyasser** [comment]
> Thanks for replying! There's not much in the way of a project for me to upload.
> 
> I ran these commands:
> 
> ```shell
> git clone https://github.com/pointfreeco/swift-composable-architecture
> cd swift-composable-architecture
> tuist install
> tuist generate
> ```
> 
> It was at the last step that the issue above happens.

@rhysm94 are you sure you are referring to the right project? because it seems that TCA doesn't use Tuist at all

**Comment by rhysm94** [comment]
> > Thanks for replying! There's not much in the way of a project for me to upload.
> 
> > 
> 
> > I ran these commands:
> 
> > 
> 
> > ```shell
> 
> > git clone https://github.com/pointfreeco/swift-composable-architecture
> 
> > cd swift-composable-architecture
> 
> > tuist install
> 
> > tuist generate
> 
> > ```
> 
> > 
> 
> > It was at the last step that the issue above happens.
> 
> 
> 
> @rhysm94 are you sure you are referring to the right project? because it seems that TCA doesn't use Tuist at all

Yeah. I know TCA doesn't use Tuist, but there's a tutorial on using Tuist with a Swift Package here that I tried following: https://docs.tuist.io/guide/introduction/adopting-tuist/swift-package.html

**Comment by varshith257** [comment]
https://docs.tuist.io/guide/introduction/adopting-tuist/swift-package.html

Following the above tutorial and will reproduce and will ping here to ask any questions, if any needed

**Comment by pepicrft** [comment]
We've updated the tutorial with a [different package](https://docs.tuist.io/guides/start/swift-package.html) that's supported. TCA remains unsupported, so I'll leave this issue open and change the title. Note that using Tuist against Swift Packages is just a beta feature for people who want to understand Tuist workflows.

**Comment by varshith257** [comment]
@pepicrft What could be a fix needed here according to issue requirements?

**Comment by fortmarek** [comment]
You should be able to successfully run commands from [this comment](https://github.com/tuist/tuist/issues/6288#issuecomment-2114283567).

It looks like a platform mismatch – Swift packages implicitly support all platforms, but macro executables can always support just macOS. Any dependency between a macro executable and a different SPM target should have a `masOS` condition.

**Comment by ajkolean** [comment]
I think it should work now that [PR 6483](https://github.com/tuist/tuist/pull/6483) ensures only existing dependencies are processed, maintaining platform compatibility. The updated code prevents using default empty sets, accurately reflecting the platform constraints of dependencies.

**Comment by fortmarek** [comment]
@ajkolean you are right, generating and building TCA works now 🥳 

Closing this issue, let's create a new issue if there are any other issues when working with TCA and Tuist.
