### ISSUE TITLE
How to Configure Different Bundle Identifiers Per Scheme in Tuist

### ISSUE THREAD

**Issue by christoschadjikyriakou** [tuist/tuist#6297]
### What problem or need do you have?

I'm trying to configure different bundle identifiers for different schemes in my Tuist project, but I'm encountering some difficulties. Here's what I've done so far:

```swift
import ProjectDescription

let project = Project(
    name: "MyApp",
    settings: .settings(
        configurations: [
            .debug(name: "Debug-Dev", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp.dev"]),
            .debug(name: "Debug-Prod", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp"]),
            .release(name: "Release-Dev", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp.dev"]),
            .release(name: "Release-Prod", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp"])
        ]
    ),
    targets: [
        Target(
            name: "MyApp",
            platform: .iOS,
            product: .app,
            bundleId: "com.mycompany.myapp",
            infoPlist: "Info.plist",
            sources: ["Sources/**"],
            resources: ["Resources/**"],
            dependencies: []
        )
    ],
    schemes: [
        Scheme(
            name: "Development",
            buildAction: BuildAction(targets: ["MyApp"]),
            testAction: TestAction(targets: ["MyApp"]),
            runAction: RunAction(configuration: "Debug-Dev"),
            archiveAction: ArchiveAction(configuration: "Release-Dev")
        ),
        Scheme(
            name: "Production",
            buildAction: BuildAction(targets: ["MyApp"]),
            testAction: TestAction(targets: ["MyApp"]),
            runAction: RunAction(configuration: "Debug-Prod"),
            archiveAction: ArchiveAction(configuration: "Release-Prod")
        )
    ]
)

```

**Issues**
Bundle Identifier Not Changing: When I switch schemes in Xcode, the bundle identifier doesn't seem to update to the expected value.
Scheme Configuration Verification: I'm not sure if I've correctly set up the schemes to use the right configurations.

**Steps Taken**
I ran tuist generate to regenerate the Xcode project.
I checked the schemes in Xcode and ensured they are selected properly.
I verified the Info.plist file to see if the bundle identifier changes based on the scheme, but it remains the same.

**Expected Outcome**
The Development scheme should use the bundle identifier com.mycompany.myapp.dev.
The Production scheme should use the bundle identifier com.mycompany.myapp.

**Actual Outcome**
Both schemes seem to use the same bundle identifier, and I can't get them to differentiate as expected.

**Request**
Could someone provide guidance or examples on how to correctly configure different bundle identifiers for different schemes using Tuist? Any help would be greatly appreciated!

### macOS version

14.5

### Tuist version

4.13.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
Hey 👋 

The best way to do this is to use a setting variable: https://github.com/tuist/tuist/discussions/2521#discussioncomment-372602

In [this](https://github.com/tuist/tuist/issues/927) issue, there's a description _why_ what you're trying to do does not work.

I am closing this because there's no action item for us.

**Comment by kapitoshka438** [comment]
@christoschadjikyriakou have you tried to pass "" to bundleId in Target init?

**Comment by kapitoshka438** [comment]
@christoschadjikyriakou here is a working example of what, I believe, are you trying to reach. This is a simplified version of the project that I'm working on to migrate from "multiple targets" to "one target with multiple configurations" way (I also supply configurations with xcconfigs, pass different AppIcon's per config etc.)

**Project.swift**
```
import ProjectDescription

// Use Debug & Release instead of Debug-Prod & Release-Prod
let configurations: [Configuration] = [
    .debug(name: "Debug-Dev", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp.dev"]),
    .debug(name: "Debug", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp"]),
    .release(name: "Release-Dev", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp.dev"]),
    .release(name: "Release", settings: ["PRODUCT_BUNDLE_IDENTIFIER": "com.mycompany.myapp"])
]

let project = Project(
    name: "MyApp",
    settings: .settings(configurations: configurations),    // configs array must go here
    targets: [
        .target(
            name: "MyApp",
            destinations: .iOS,
            product: .app,
            bundleId: "",
            infoPlist: "Info.plist",
            sources: ["MyApp/Sources/**"],
            resources: ["MyApp/Resources/**"],
            dependencies: [],
            settings: .settings(configurations: configurations)  // and here 
        )
    ],
    schemes: [
        .scheme(
            name: "Development",
            buildAction: .buildAction(targets: ["MyApp"]),
            testAction: .targets(["MyApp"]),
            runAction: .runAction(configuration: "Debug-Dev"),
            archiveAction: .archiveAction(configuration: "Release-Dev")
        ),
        .scheme(
            name: "Production",
            buildAction: .buildAction(targets: ["MyApp"]),
            testAction: .targets(["MyApp"]),
            runAction: .runAction(configuration: "Debug"),
            archiveAction: .archiveAction(configuration: "Release")
        )
    ]
)
```
**Workspace.swift** (to prevent Tuist from autogenerating extra schemes)
```
import ProjectDescription

let workspace = Workspace(
    name: "MyApp",
    projects: [
       "."
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
```
Also, if you have SPM dependencies, you have to describe the same list of configurations in the package manifest.
**Package.swift**
```
#if TUIST
    import struct ProjectDescription.PackageSettings

let packageSettings = PackageSettings(baseSettings: .settings(configurations: [
        .debug(name: "Debug-dev"),
        .release(name: "Release-dev"),
        .debug(name: "Debug"),
        .release(name: "Release"),
    ]))
#endif
```
@fortmarek fyi
