### ISSUE TITLE
`tuist init` DX

### ISSUE THREAD

**Issue by newsve** [tuist/tuist#6354]
### What problem or need do you have?

Feel free too close: Maybe I got things wrong:

1. (minor) init capitalizes the project name, sometimes it even PascalCases it, I think this is preference and can be changed anyway but feels odd (or is this a convention?), agein, very minor
2. (minor) init sets up the LaunchScreen via a Storyboard, again preference and somewhat easy to fix but still work and more files just means more clutter, I'd align with Xcode which doesn't use Storyboards anymore, either when creating a project

Users might not init IRL that often but when they just want to test tuist they, do some sample projects to get a feel and do a few inits and yeah, it feels just slightly jarring

### Potential solution

1. keep the names as they are
2. align with Xcode

### macOS version

latest

### Tuist version

latest

### Xcode version

latest

**Comment by pepicrft** [comment]
100% agree with your suggestions @newsve. Would you like to take a stab at fixing it?

**Comment by newsve** [comment]
I'd love to but I am pretty new to Swift and I am still chatgpt-ing my day through Swift

**Comment by woin2ee** [comment]
I'm interested in this issue. I'll take a look.
