### ISSUE TITLE
Build Issue with swift-system 1.3.0 Using Tuist

### ISSUE THREAD

**Issue by topkim993** [tuist/tuist#6370]
### What happened?

There is a build issue when attempting to build version 1.3.0 of [swift-system](https://github.com/apple/swift-system) using Tuist. The problem does not occur when the dependency is added through a native project setup. It seems that the changes introduced in [this commit](https://github.com/apple/swift-system/commit/7b14e48d0dc485b114efaa4129a33cb97286cdd9) are causing the build to fail when using Tuist to manage Swift Package Manager (SPM) dependencies.

### Step 1

Set up a project using Tuist and add swift-system 1.3.0 as a dependency via Tuist SPM.

### Step 2

Attempt to build the project.

### Step 3

Observe the build failure.

---
I will attach test apps demonstrating the issue for further investigation.

### Success
[SPMTest.zip](https://github.com/user-attachments/files/15571779/SPMTest.zip)
### Failure
[TuistTest.zip](https://github.com/user-attachments/files/15571780/TuistTest.zip)

### Error log

<img width="266" alt="스크린샷 2024-06-05 오전 9 52 48" src="https://github.com/tuist/tuist/assets/57055565/99ce8fcb-77dd-4a9b-a5c6-6e47c96ff2e4">

### macOS version

14.3

### Tuist version

4.12.0

### Xcode version

15.2

**Comment by pepicrft** [comment]
It's duplicated of [this issue](https://github.com/tuist/tuist/issues/6313)
