### ISSUE TITLE
Invalid Manifests Cache on CI/CD

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#6374]
### What happened?

I was encountering an invalid manifest cache issue that was resulting in the following error: 
`JIT session error: Symbols not found`

Removing the `~/.cache/Manifests` and `~/.cache/ProjectDescriptionHelpers` folders solved the problem.

It seems that it would be cleaner to keep the manifest cache in the local project directory

### How do we reproduce it?

I ran into this issue on CI and can't reproduce it locally...

### Error log

```
Loading and constructing the graph
It might take a while if the cache is empty
The 'swift' command exited with error code 255 and message:
JIT session error: Symbols not found: [ _$s18ProjectDescription18FileHeaderTemplateO0aB7HelpersE13companyCopyrightACvau ]
Failed to materialize symbols: { (main, { _$s18ProjectDescription9WorkspaceV4name8projects7schemes18fileHeaderTemplate15additionalFiles17generationOptionsACSS_SayAA4PathVGSayAA6SchemeVGAA04FilehI0OSgSayAA0P7ElementOGAC010GenerationM0VtcfcfA4_, _symbolic Say_____G 18ProjectDescription14TestingOptionsV, ___swift_allocate_value_buffer, _$s18ProjectDescription14TestingOptionsVACs10SetAlgebraAAWL, _$sSa12_endMutationyyF, _main, _symbolic _____16codeCoverageMode______14testingOptions_____Sg12testLanguageSSSg0F6Region_____Sg0F19ScreenCaptureFormatt 18ProjectDescription9WorkspaceV17GenerationOptionsV013AutogeneratedC7SchemesO16CodeCoverageModeO AA07TestingE0V AA14SchemeLanguageV AA19ScreenCaptureFormatO, _$s9Workspace9workspace18ProjectDescriptionAAVvp, _got.$s18ProjectDescription18FileHeaderTemplateOMn, _$sSay18ProjectDescription14TestingOptionsVGSayxGSTsWL, _symbolic _____Sg 18ProjectDescription18FileHeaderTemplateO, _got.$s18ProjectDescription9WorkspaceV17GenerationOptionsV013AutogeneratedC7SchemesO16CodeCoverageModeOMn, _$sSa22_allocateUninitializedySayxG_SpyxGtSiFZ18ProjectDescription6SchemeV_Tgmq5, _$s18ProjectDescription14TestingOptionsVACs10SetAlgebraAAWl, _$sSa22_allocateUninitializedySayxG_SpyxGtSiFZ18ProjectDescription11FileElementO_Tgmq5, __swift_FORCE_LOAD_$_swiftDispatch_$_Workspace, _$sSa22_allocateUninitializedySayxG_SpyxGtSiFZ18ProjectDescription14TestingOptionsV_Tgmq5, _$s18ProjectDescription18FileHeaderTemplateOSgMD, __swift_FORCE_LOAD_$_swiftDarwin_$_Workspace, __swift_FORCE_LOAD_$_swiftFoundation_$_Workspace, ___swift_instantiateConcreteTypeFromMangledNameAbstract, __swift_FORCE_LOAD_$_swiftIOKit_$_Workspace, __swift_FORCE_LOAD_$_swiftCoreFoundation_$_Workspace, ___swift_instantiateConcreteTypeFromMangledName, __swift_FORCE_LOAD_$_swiftXPC_$_Workspace, __swift_FORCE_LOAD_$_swiftObjectiveC_$_Workspace, _$s18ProjectDescription9WorkspaceV4name8projects7schemes18fileHeaderTemplate15additionalFiles17generationOptionsACSS_SayAA4PathVGSayAA6SchemeVGAA04FilehI0OSgSayAA0P7ElementOGAC010GenerationM0VtcfcfA3_, _symbolic _____Sg 18ProjectDescription7VersionV, _$ss27_finalizeUninitializedArrayySayxGABnlF, _$sSay18ProjectDescription14TestingOptionsVGSayxGSTsWl, _got.$s18ProjectDescription7VersionVMn, _$s18ProjectDescription9WorkspaceV17GenerationOptionsV013AutogeneratedC7SchemesO16CodeCoverageModeO04codeiJ0_AA07TestingE0V07testingE0AA14SchemeLanguageVSg04testO0SSSg0P6RegionAA19ScreenCaptureFormatOSg0prsT0tMD, _got.$s18ProjectDescription14TestingOptionsVMn, _$s18ProjectDescription7VersionVSgMD, _$s18ProjectDescription9WorkspaceV4name8projects7schemes18fileHeaderTemplate15additionalFiles17generationOptionsACSS_SayAA4PathVGSayAA6SchemeVGAA04FilehI0OSgSayAA0P7ElementOGAC010GenerationM0VtcfcfA1_, _$sSay18ProjectDescription14TestingOptionsVGMD, ___swift_project_value_buffer, _$s18ProjectDescription7VersionVSgWOh, _got.$s18ProjectDescription14SchemeLanguageVMn, _got.$s18ProjectDescription19ScreenCaptureFormatOMn }) }
```

### macOS version

14

### Tuist version

4.11.0

### Xcode version

15.3

**Comment by Ernest0-Production** [comment]
After demangle: 
```swift
Loading and constructing the graph
It might take a while if the cache is empty
The 'swift' command exited with error code 255 and message:
JIT session error: Symbols not found: [ ProjectDescription.FileHeaderTemplate.companyCopyright ]
Failed to materialize symbols: { 
(main, { 
ProjectDescription.Workspace.init(name: String, projects: [Path], schemes: [Scheme], fileHeaderTemplate: FileHeaderTemplate?, additionalFiles: [FileElement], generationOptions: [GenerationOption]), 
symbolic Say ProjectDescription.TestingOptions, 
swift_allocate_value_buffer, 
ProjectDescription.TestingOptions.SetAlgebra, 
swift.Array.endMutation(), 
main, 
symbolic ProjectDescription.Workspace.GenerationOptions.AutogeneratedSchemes.CodeCoverageMode ProjectDescription.TestingOptions.testingOptions SchemeLanguage ProjectDescription.ScreenCaptureFormat, 
Workspace.workspace ProjectDescription, 
got.ProjectDescription.FileHeaderTemplate, 
swift.Array.symbolic TestingOptions, 
symbolic ProjectDescription.FileHeaderTemplate, 
got.ProjectDescription.Workspace.GenerationOptions.AutogeneratedSchemes.CodeCoverageMode, 
swift.Array.allocateUninitialized Array Slice ProjectDescription.Scheme, 
ProjectDescription.TestingOptions.SetAlgebra, 
swift.Array.allocateUninitialized Array Slice ProjectDescription.FileElement, 
swift_FORCE_LOAD_$_swiftDispatch_$_Workspace, 
swift.Array.allocateUninitialized Array Slice ProjectDescription.TestingOptions, 
ProjectDescription.FileHeaderTemplate.optional Metadata, 
swift_FORCE_LOAD_$_swiftDarwin_$_Workspace, 
swift_FORCE_LOAD_$_swiftFoundation_$_Workspace, 
swift.instantiateConcreteTypeFromMangledNameAbstract, 
swift_FORCE_LOAD_$_swiftIOKit_$_Workspace, 
swift_FORCE_LOAD_$_swiftCoreFoundation_$_Workspace, 
swift.instantiateConcreteTypeFromMangledName, 
swift_FORCE_LOAD_$_swiftXPC_$_Workspace, 
swift_FORCE_LOAD_$_swiftObjectiveC_$_Workspace, 
ProjectDescription.Workspace.init(name: String, projects: [Path], schemes: [Scheme], fileHeaderTemplate: FileHeaderTemplate?, additionalFiles: [FileElement], generationOptions: [GenerationOption]), 
symbolic ProjectDescription.Version, 
swift.finalizeUninitializedArray, 
swift.Array.symbolic TestingOptions, 
got.ProjectDescription.Version, 
ProjectDescription.Workspace.GenerationOptions.AutogeneratedSchemes.CodeCoverageMode.TestingOptions SchemeLanguage optional testRegion ScreenCaptureFormat metadata version, 
got.ProjectDescription.TestingOptions, 
ProjectDescription.Version.optional Metadata, 
ProjectDescription.Workspace.init(name: String, projects: [Path], schemes: [Scheme], fileHeaderTemplate: FileHeaderTemplate?, additionalFiles: [FileElement], generationOptions: [GenerationOption]), 
ProjectDescription.TestingOptions.metadata, 
swift.project_value_buffer, 
ProjectDescription.Version.optional Associated Type metadata, 
got.ProjectDescription.SchemeLanguage, 
got.ProjectDescription.ScreenCaptureFormat 
}) 
}
```

Note:
`ProjectDescription.FileHeaderTemplate.companyCopyright` is my static-factory property helper

**Comment by pepicrft** [comment]
@Ernest0-Production, we'd need to know what changed between the run that was cached and the run that failed. We have some environment information like the Swift version or the content in your files, but based on your description, it seems that there's something that we are missing and that we'd need to incorporate into your logic. 
I'd refrain from changing the cache directory because that doesn't mitigate the issue, it only brings it closer to the developer file-system-wise.

**Comment by Ernest0-Production** [comment]
@pepicrft What is known is that the Swift version (5.10) and the Xcode version (15.3) have not changed.

It is known that everything worked on one machine, but not on the other.

I can assume that the non-working machine had a rather old, backwards-incompatible cache. And yes, deleting the manifest cache solved the problem. (as workaround)

Since the definition of the machine for assembly is determined automatically, it is difficult for me to guess and determine what changes led to such an error, but what is known is that this has already happened several times (but quite rarely)

----

One of the reasons to make the cache closer to the project directory is that otherwise build manifests of all pull requests for all time will accumulate on the CI machine.
This is just as bad as having shared xcode DerivedData.

Another advantage of a local cache directory was the ability to control when it needed to be staged between job runs and when it didn't.
Currently, the `tuist clean <entities>` command clears the entire cache of all projects, which is not convenient.

**Comment by pepicrft** [comment]
@Ernest0-Production, thanks for the clarification. I agree that we should support caching across environments to speed up generation times. However, we did not implement the logic with that use case in mind, and therefore I think we are missing some scenarios when calculating the hash to look up binaries in the cache. If you are interested, [here is the place](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/Loaders/CachedManifestLoader.swift#L158) where we calculate the hash. I think we should extend the logic to incorporate the variables that cause the compiler to output a different artifact (e.g. Xcode version, macOS version, system architeture)

**Comment by Ernest0-Production** [comment]
@pepicrft  Thank you, I looked at this code and it seems to me that the potential problem lies in [﻿ProjectDescriptionHelpersHasher.prefixHash](https://github.com/tuist/tuist/blob/a8259aff812816703d91e921dee8254a62baeba3/Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasher.swift#L48)

```swift
public func prefixHash(helpersDirectory: AbsolutePath) -> String {
    let pathString = helpersDirectory.pathString
    let index = pathString.index(pathString.startIndex, offsetBy: 7)
    return String(helpersDirectory.pathString.md5[..<index])
}
``

I'm not sure why ﻿`offsetBy: 7` is needed here, but it looks like _black magic_.

I can assume that because **there might have been many directories** for my project on the CI (stored under each pull request), a rare situation occurred when two MD5 strings turned out to be equal **because they were truncated** to the given ﻿index in this function. (i.e., it **increases the likelihood of a collision**)

**Comment by Ernest0-Production** [comment]
@pepicrft By the way, I remember in Tuist 3 it was possible to specify the cache directory via `Config.swift`.

Why did they decide to remove this?

**Comment by pepicrft** [comment]
> I can assume that because **there might have been many directories** for my project on the CI (stored under each pull request), a rare situation occurred when two MD5 strings turned out to be equal **because they were truncated** to the given ﻿index in this function. (i.e., it **increases the likelihood of a collision**)

This could indeed be the issue. We can iterate on that logic to prevent collisions from happening. Would you like to take a stab at it?

> Why did they decide to remove this?

We noted that users used that as an escape hatch to reduce the likelihood of conflicts like this one instead of filing issues so that we could solve those bugs. If we design the cache well, users shouldn't encounter scenarios where they need to customize the caching directory.

**Comment by Ernest0-Production** [comment]
@pepicrft I write simple abstract test in playground to detect collision of hashes that computed by current login:
```swift
typealias Path = String
typealias Hash = String
var pathsHashes: [Path: Hash] = [:]
var hashesPaths: [Hash: Path] = [:]

var prNumber = 0
func generatePath() -> Path {
    defer { prNumber += 1 }
    return "Users/jenkins/workspace/PR-\(prNumber)"
}

func computeHash(for pathString: Path) -> Hash {
    let index = pathString.index(pathString.startIndex, offsetBy: 7)

    return String(pathString.md5[..<index])
}

while true {
    let pathString = generatePath()
    guard !pathsHashes.keys.contains(pathString) else { 
        continue
    }

    let hash = computeHash(for: pathString)

    if let collisionPath = hashesPaths[hash] {
        print("Detect collision", collisionPath, pathString)
        break
    } else {
        hashesPaths[hash] = pathString
        pathsHashes[pathString] = hash
    }
}
```

And I receive output:
```log
Detect collision Users/jenkins/workspace/PR-2962 Users/jenkins/workspace/PR-5162
```

The hash for these two paths is indeed the same:
```swift
print(
    computeHash(for: "Users/jenkins/workspace/PR-2962"), // 4be35b3
    computeHash(for: "Users/jenkins/workspace/PR-5162") // 4be35b3
)
```

**Comment by Ernest0-Production** [comment]
Oh suddenly I was also able to reproduce this error when I uninstalled and reinstalled homebrew on m1.

**Comment by pepicrft** [comment]
> Thanks for the explanation! But it still seems that even with hashing working correctly, for deploying an environment on CI it is important to have control over all the artifacts and side effects created during the build process, so that after completion it is cleared up this environment without creating collisions/data races/race conditions

We follow the [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) specification for obtaining the cache directory, so you should be able to control that via the `XDG_CACHE_HOME` environment variable. I'll add documentation about this.

**Comment by pepicrft** [comment]
@Ernest0-Production what would you suggest as an alternative to that MD5 approach to prevent collisions?

**Comment by Ernest0-Production** [comment]
> @Ernest0-Production what would you suggest as an alternative to that MD5 approach to prevent collisions?

Can't we just refuse to create a prefix directory?

**Comment by pepicrft** [comment]
> Can't we just refuse to create a prefix directory?

Could you expand?

**Comment by Ernest0-Production** [comment]
> Could you expand?

Based on the above experiment:
https://github.com/tuist/tuist/issues/6374#issuecomment-2161333689 

The problem is hash collision, which is generated in the function [﻿ProjectDescriptionHelpersHasher.prefixHash](https://github.com/tuist/tuist/blob/a8259aff812816703d91e921dee8254a62baeba3/Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasher.swift#L48)
[Looking at this comment](https://github.com/tuist/tuist/issues/6374#issuecomment-2159223968)

I can’t understand why it was decided to create a `prefixHash` for `ProjectDescriptionHelpers`, but there is no such mechanism for generating a prefix for the project manifest. 
And I propose to simply remove this `prefixHash` functionality, which is used as an intermediate directory in which tuist puts the `ProjectDecsriptionHelpers` cache.

**Comment by Ernest0-Production** [comment]
I also encountered a similar error when I switched between minor versions via mise and at some point when calling `tuist generate` I got the same error.  

Does the tuist version count in the hash function?

**Comment by pepicrft** [comment]
It doesn't seem like [we do](https://github.com/tuist/tuist/blob/a8259aff812816703d91e921dee8254a62baeba3/Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasher.swift#L27). Would you mind contributing a PR fixing that?

**Comment by Ernest0-Production** [comment]
> It doesn't seem like [we do](https://github.com/tuist/tuist/blob/a8259aff812816703d91e921dee8254a62baeba3/Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersHasher.swift#L27). Would you mind contributing a PR fixing that?

On the contrary, you are already doing it :)

-----

I tried to study the Tuist source code in more detail.

And I came across the fact that if there is no `ProjectDescriptionHelpers` cached dyld, it tries to compile it N times! Where N is the number of Project.swift manifests in the project. 

<img width="428" alt="Снимок экрана 2024-07-16 в 02 45 12" src="https://github.com/user-attachments/assets/1e3cee77-9bf4-4f37-9d65-7c98f677ca1e">

<img width="457" alt="Снимок экрана 2024-07-16 в 02 45 24" src="https://github.com/user-attachments/assets/1c214b1b-69aa-49f4-8f35-c8675cf05b12">

The problematic code is somewhere here (screenshot), but I'm having a hard time figuring it out
<img width="746" alt="Снимок экрана 2024-07-16 в 02 46 16" src="https://github.com/user-attachments/assets/15f57f99-9a4b-44bc-b5ab-d5459c70b2d5">

------------

**And I have a hypothesis:**

Due to the fact that the ProjectDescriptionHelpers cache folder is deleted every time the manifest is compiled, a race condition occurs.

Which most likely leads to the fact that some characters cannot be found

<img width="984" alt="Снимок экрана 2024-07-16 в 02 49 02" src="https://github.com/user-attachments/assets/3884f6ba-bfbb-47a9-84e9-f7f2a18b1c04">

**Comment by Ernest0-Production** [comment]
FYI @fortmarek @pepicrft

**Comment by fortmarek** [comment]
@Ernest0-Production thanks a lot for digging deeper into this 🙏 

I haven't been able to reproduce, do you have a reproducer or have you been able to reproduce only in your project?

> Due to the fact that the ProjectDescriptionHelpers cache folder is deleted every time the manifest is compiled, a race condition occurs. (see screenshot)

This is not entirely true afaict. We only rebuild if we can't find a [ProjectDescriptionHelpers module for a given hash](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/ProjectDescriptionHelpers/ProjectDescriptionHelpersBuilder.swift#L169). If you don't change your `ProjectDescriptionHelpers`, we shouldn't rebuild them again.

However, I can definitely see a race condition happening:
- Helpers for a module with a given hash doesn't exist
- We start compiling
- We try to access the builders from elsewhere
- The helpers were not compiled, yet, we start compiling again!
- 💣 

Adding a lock for the compilation based on the `ProjectDescriptionHelpers` hash sounds sensible to me. You might be able to leverage parts of [this](https://github.com/tuist/tuist/blob/main/Sources/TuistSupport/Utils/ThreadSafe.swift) class.

We're happy to take a look as well if you can find a way to more-or-less reliably reproduce.

**Comment by Ernest0-Production** [comment]
@fortmarek 

> This is not entirely true afaict

Yes, it's my mistake....
During the debugging process, I myself deleted the code that checked the presence of the cache) 😅

But Race Condition is actually present during a cold start (without cache).

> I haven't been able to reproduce, do you have a reproducer or have you been able to reproduce only in your project?

Yes, this problem is reproducible on my project, but I can't reproduce it myself when I need it...

It is known that:
- this happens at an arbitrary point in time
- this is fixed when clearing the ProjectDescriptionHelpers cache

And after I looked into the hash generation code for ProjectDescriptionHelpers, I didn't find the true problem in that code.

But I can assume that due to state race, the dyld state may be incorrect if writing to the file does not occur atomically.

----

In my project:
- 44 Project.swift manifesto
- 80% of the codebase is in ProjectDescriptionHelpers

If this is really related to the race of states, then this can only be reproduced in large projects.

**Comment by fortmarek** [comment]
> If this is really related to the race of states, then this can only be reproduced in large projects.

You can create an arbitrarily large project with our `fixturegenerator`. You can run the following in the `tuist` project:
```sh
mise run fixturegenerator:run
```

You can also try reproducing the race conditions with an acceptance or an integration test. It would be really helpful to get a good reproducer, so we know that whatever fix we come up with actually resolves the issue. Happy to provide extra pointers if you need 🙏

**Comment by dankinsoid** [comment]
@pepicrft  Same issue

tuist 4.10.2

tuist clean doesn't help
removing ~/.tuist and ~/.cahce/tuist doesn't help
recloning the repo doesn't help

**Comment by Ernest0-Production** [comment]
@pepicrft We are here again)

tuist 4.68.0

We have migrated from 0.58.2. And during this time, apparently, the atomic caching mechanism of ProjectDescriptionHelpers was broken again

<img width="1920" height="917" alt="Image" src="https://github.com/user-attachments/assets/bbda5075-6a3f-4428-af76-abbf1f989fd5" />
