### ISSUE TITLE
Generated TuistBundle+* files have bad formatting

### ISSUE THREAD

**Issue by cooksimo** [tuist/tuist#6404]
### What happened?

We've just updated Tuist from 4.9.0 to 4.17.0 and now all the generated TuistBundle+* files are causing swiftlint errors.

Previously the file looked like this:
```
// swiftlint:disable all
// swift-format-ignore-file
// swiftformat:disable all
import Foundation

// MARK: - Swift Bundle Accessor

private class BundleFinder {}

extension Foundation.Bundle {
/// Since FakeDoorQuestionnaire is a framework, the bundle for classes within this module can be used directly.
static let module = Bundle(for: BundleFinder.self)
}

// MARK: - Objective-C Bundle Accessor

@objc
public class FakeDoorQuestionnaireResources: NSObject {
@objc public class var bundle: Bundle {
    return .module
}
}
// swiftlint:enable all
// swiftformat:enable all
```

But now it looks like this:
```
// swiftlint:disable all
// swift-format-ignore-file
// swiftformat:disable all
import Foundation// MARK: - Swift Bundle Accessor for Frameworks
private class BundleFinder {}
extension Foundation.Bundle {
/// Since FakeDoorQuestionnaire is a dynamic framework, the bundle for classes within this module can be used directly.
static let module = Bundle(for: BundleFinder.self)
}// MARK: - Objective-C Bundle Accessor
@objc
public class FakeDoorQuestionnaireResources: NSObject {
@objc public class var bundle: Bundle {
    return .module
}
}// swiftlint:enable all
// swiftformat:enable all
```

Looks like a bunch of new lines have been removed andnow we get swiftlint errors despite the directive to disable it (specifically that there should be a single trailing newline at the end of the file)

### How do we reproduce it?

Generate any project with dynamic frameworks and look at the TuistBundle+* file(s)

### Error log

N/A

### macOS version

14.4.1

### Tuist version

4.17.0

### Xcode version

15.3

**Comment by fortmarek** [comment]
Hey @cooksimo 👋 

The bundle accessors are generated in this [mapper](https://github.com/tuist/tuist/blob/08651ef636719ef3386e58972be29b1671e53d68/Sources/TuistGenerator/Mappers/ResourcesProjectMapper.swift#L170). It looks like in your case, we end up with more newlines than we should be.

Would you be up for taking this on? You should be able to update the mapper and remove any extra trailing new lines from the generated accessors 🙂

**Comment by noelcperez** [comment]
Other issue I encountered when I was updating to Tuist 4.17.0 is that brand new `.h/.m` pairs of `TuistBundle+` files are added to the `Derived/Source` folder of the project if it contains Objective C files in it. These new `.h/.m` files gives a `No newline at the end of file` warning as well.

Question derived from this are
Are these new `.h/.m` files necessary? They were not being generated before
Is there a way to not generate these `.h/.m` files? I could not find anything on the docs but a more general https://docs.tuist.io/generated/manifest/structs/Project.Options.html#disablebundleaccessors
Should empty lines be added to the end of the generated files?

**Comment by fortmarek** [comment]
> Other issue I encountered when I was updating to Tuist 4.17.0 is that brand new .h/.m pairs of TuistBundle+ files are added to the Derived/Source folder of the project if it contains Objective C files in it. These new .h/.m files give a No newline at the end of file warning as well.

The objc resource bundle accessors should only be generated for external projects (i.e., those added via `Package.swift`). If that's not the case, there might be a bug. We went on this relatively recently (https://github.com/tuist/tuist/pull/6388) but that PR should be in `4.17.0`.

**Comment by noelcperez** [comment]
> 
> The objc resource bundle accessors should only be generated for external projects (i.e., those added via `Package.swift`). If that's not the case, there might be a bug. We went on this relatively recently (#6388) but that PR should be in `4.17.0`.

I used the latest tuist version and after running `tuist generate` I'm not seeing those `.h/.m` files anymore. These were `internal` projects so the fix on that PR is working as expected as far as the issue I was seeing goes, thanks
