### ISSUE TITLE
App extensions can't have bundles as dependencies

### ISSUE THREAD

**Issue by DmitrySerovWise** [tuist/tuist#6406]
### What happened?

Targets of type `.appExtension` can depend on targets of type `.bundle`. Tuist, however, disallows such links on graph validation stage with the following error:

```
Target MyExtension has platforms 'iOS' and product 'app extension' and depends on target MyBundle of type 'bundle' and platforms 'iOS' which is an invalid or not yet supported combination.
```

### How do we reproduce it?

1. Create a project with two targets, one of type `appExtension`, another of type `bundle`
2. Add the bundle target as a dependency of the extension target
3. Run `tuist generate`

### Error log

```
Target MyExtension has platforms 'iOS' and product 'app extension' and depends on target MyBundle of type 'bundle' and platforms 'iOS' which is an invalid or not yet supported combination.
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

14.5

### Tuist version

4.17.0

### Xcode version

15.4

**Comment by DmitrySerovWise** [comment]
I believe the issue is here in the list of supported target types: https://github.com/tuist/tuist/blob/cdb9197e43a64bf09b1b93ee867df44aa51db351/Sources/TuistGenerator/Linter/GraphLinter.swift#L441

**Comment by fortmarek** [comment]
Hey @DmitrySerovWise 👋 

We added only combinations that we had tests and fixtures for as we knew about those scenarios.

Your scenario definitely sounds valid, if you could create a fixture with an acceptance tests and open a PR with updating the `GraphLinter` above, we'd more than happily accept the PR 😌 

Let us know if you need any help in getting the PR over the finish line if you decide to take it!

**Comment by hanrw** [comment]
found a same with macos 
Target S3Sync has platforms 'macOS' and product 'app extension' and depends on target AWSS3 of type 'static framework' and platforms 'macOS' which is an invalid or not yet supported combination.
Fatal linting issues found
