### ISSUE TITLE
The xcframework supports archive formats, such as `.zip`, `.tar`...

### ISSUE THREAD

**Issue by Binlogo** [tuist/tuist#6411]
### What problem or need do you have?

I have a project which have a dependency for xcframework, when using:
```
    dependencies: [
        .xcframework(path: "../mymath-lib/target/MyMath.xcframework.zip")
    ]
```
it will report error:
```
MyMath.xcframework.zip/Info.plist doesn't contain an Info.plist. It's possible that the .xc
framework was not generated properly or that got corrupted. Please, double check with the author of the framework.
```

While using SPM, it is valid like:
```
	targets: [
		.executableTarget(
				name: "swift-cmd",
				dependencies: ["MyMath"]),
		.binaryTarget(
				name: "MyMath",
				path: "../mymath-lib/target/MyMath.xcframework.zip"
		),
	]
```

### Potential solution

Detect the path provided, determine its format to unarchive if needed.

### macOS version

14.5

### Tuist version

4.17.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
Hey 👋 

> Detect the path provided, determine its format to unarchive if needed.

I think this makes sense. I'd be curious why you don't unarchive the `.xcframework` in the filesystem before running `tuist generate`? Just to understand a bit better where this comes from 🙂

**Comment by Binlogo** [comment]
> I think this makes sense. I'd be curious why you don't unarchive the `.xcframework` in the filesystem before running `tuist generate`? Just to understand a bit better where this comes from 🙂

🤔 The scenery is the `.zip` file used for SPM originally. When migrating to use Tuist, using the `.zip` file directly is a nature path until `tuist generate` fails. Then I realize Tuist only support unarchived `.xcframework` itself.

**Comment by pepicrft** [comment]
> I think this makes sense. I'd be curious why you don't unarchive the .xcframework in the filesystem before running tuist generate? Just to understand a bit better where this comes from 🙂

I agree with @fortmarek here. How a portable binary is transported/stored (e.g., in a zip file) is not something Tuist should be concerned about. If we bring that responsibility into Tuist, we open the door for feature requests to support the infinite options out there, and it'll distract us from other areas of the project that would benefit from deeper focus. 

Is there any concern with unzipping it yourself @Binlogo ?

**Comment by Binlogo** [comment]
> > I think this makes sense. I'd be curious why you don't unarchive the .xcframework in the filesystem before running tuist generate? Just to understand a bit better where this comes from 🙂
> 
> 
> 
> I agree with @fortmarek here. How a portable binary is transported/stored (e.g., in a zip file) is not something Tuist should be concerned about. If we bring that responsibility into Tuist, we open the door for feature requests to support the infinite options out there, and it'll distract us from other areas of the project that would benefit from deeper focus. 
> 
> 
> 
> Is there any concern with unzipping it yourself @Binlogo ?

No, I resolved the issue by unzipping the file first. It's fine with me, not a major issue.

As I mentioned early, when I first encountered Tuist, its design and syntax reminded me of (SPM), leading me to expect that it would function in a similar manner. 

However, if ensuring compatibility with zipped files is not within Tuist's scope, then perhaps my expectations may need adjustment.
