### ISSUE TITLE
Using Tuist with a Swift Package could not locate project

### ISSUE THREAD

**Issue by milanhorvatovic** [tuist/tuist#6423]
### What problem or need do you have?

I tried to follow the documentation here as is: https://docs.tuist.io/guide/introduction/adopting-tuist/swift-package with custom SPM project. As soon as I reached this point: `tuist generate` 
I got this error:
```
Loading and constructing the graph
It might take a while if the cache is empty
Could not locate project at path: /Users/.../TestsFoundation
```
Are there any requirements how and what SPM package is supposed to contain?

Sample project:
[TestsFoundation.zip](https://github.com/user-attachments/files/15914435/TestsFoundation.zip)

### macOS version

14.5 (23F79)

### Tuist version

4.18.0

### Xcode version

15.4 (15F31d)

**Comment by fortmarek** [comment]
Hey!

You need to have a `git` repository set up (or a `Tuist` directory) as that is used to find the [root directory](https://github.com/tuist/tuist/blob/main/Sources/TuistCore/Utils/RootDirectoryLocator.swift#L5-L14). I will update the docs, so that requirement is clear until we figure out a better solution to find the root.

**Comment by milanhorvatovic** [comment]
@fortmarek I see. 
Do you plan to provide some sort of tool to automate and simplify a transition from SPM to your Project.swift definition?

**Comment by fortmarek** [comment]
> Do you plan to provide some sort of tool to automate and simplify a transition from SPM to your Project.swift definition?

It's not in the plans right now, no. `Package.swift` should generally be simple to rewrite to `Project.swift` and automating this part could easily lead to messy `Project.swift` manifests.
