### ISSUE TITLE
ObjC code not linked unless `-ObjC` flag is manually added

### ISSUE THREAD

**Issue by DandyLyons** [tuist/tuist#6432]
### What happened?

This appears to be a regression of this issue. 
https://github.com/tuist/tuist/issues/3294

### How do we reproduce it?

1. Build and run the attached sample project. 
2. Tap the Forget network button. This should trigger a crash with the "unrecognized selector" error. 

(This project is a simple project with one dependency, TCA, and it is following this tutorial: https://www.pointfree.co/collections/uikit/modern-uikit/ep281-modern-uikit-sneak-peek-part-1). 

When the app is run with the `-ObjC` flag added, the app does not crash and a UIAlert is presented. 

### Error log

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIAlertController setOnDismiss:]: unrecognized selector sent to instance 0x131009400'
*** First throw call stack:
(0x18c4d0f20 0x18437a018 0x18c5da480 0x18f5ac2d0 0x18c46dfb4 0x18c46d8d0 0x100beefa0 0x100bf12cc 0x100bf1fe8 0x100bf34c4 0x1977e6204 0x100bb4e44 0x100bf1b44 0x100bf3428 0x1977fd2f8 0x1977e0ad8 0x100bf2848 0x100bf1a40 0x100ba7994 0x100ba7bc0 0x23b1f750c 0x18adc0068 0x23b1f1b40 0x23b1f1bac 0x100ba61b8 0x100ba7b54 0x100ba7d90 0x100bf2b68 0x100bf33fc 0x1977e6204 0x100bb4e44 0x100bf2b20 0x100ab2410 0x101c20b98 0x101c227bc 0x101c32d58 0x101c3290c 0x18c4a3710 0x18c4a0914 0x18c49fcd8 0x1d13501a8 0x18ead890c 0x18eb8c9d0 0x18ed06384 0x100a2ca18 0x100a2c990 0x100a2cac4 0x1afb51e4c)
libc++abi: terminating due to uncaught exception of type NSException

### macOS version

14.5

### Tuist version

4.18.0

### Xcode version

15.4

**Comment by DandyLyons** [comment]
At this point, I'm not even sure if this is a bug or if it's intended tuist behavior. Currently, it doesn't seem to be clear if tuist is supposed to infer if -ObjC flags are necessary or not. 

These docs appear to clarify that it is our responsibility to add -ObjC flags, which is helpful.
https://docs.tuist.io/guide/project/dependencies#static-or-dynamic

However, not long ago, these flags **were** automatically added. 
https://github.com/tuist/tuist/issues/6243

I don't have strong opinions on what is the better design choice. But I do think this seems like a very large design decision and I think it actually warrants more than a section in the docs and a point release. If tuist used to infer something for us and now it is our responsibility to handle it (or vice versa) then that fundamentally changes the mental model required to use it correctly. 

Whatever the decision is, I think it should be highlighted in a blog post announcement.

**Comment by DandyLyons** [comment]
Oh. I just found this blog post about it. 😅
https://pepicrft.me/blog/2024/06/04/why-you-need-objc

**Comment by pepicrft** [comment]
Hey @DandyLyons 
Providing control over that behavior is something [that's being worked on](https://github.com/tuist/tuist/pull/6371), and we also have [some docs](https://docs.tuist.io/guide/project/dependencies.html#objective-c-dependencies) on this subject.
I'll close the issue and continue the discussion in that other PR.
