### ISSUE TITLE
[Xcode16-beta.2] SwiftUI Preview fails under some conditions

### ISSUE THREAD

**Issue by muukii** [tuist/tuist#6446]
### What problem or need do you have?

Since Xcode 16 uses a new way to display SwiftUI Preview, it might affect SwiftUI Preview stability.
I am not able to figure out what exactly condition makes it fail. but it seems that opening Package.swift works fine and other projects like those generated by Tuist will fail to display. this is all that I found.

[swift-dynamic-list.zip](https://github.com/user-attachments/files/16007933/swift-dynamic-list.zip)
this zip that contains a generated project and package.swift.

### macOS version

14.5

### Tuist version

4.18.0

### Xcode version

16.0.0-beta.2

**Comment by pepicrft** [comment]
I'm surfacing some useful context from a Slack conversation.
My hunch is that this is an Xcode bug that we can't do anything about. To confirm the assumption, we'd need to create the same project without Tuist, and see if the same error happens.

**Comment by fortmarek** [comment]
Closing. We can reopen if somebody provides a sample without Tuist that works.
