### ISSUE TITLE
`tuist run` command line tool on Xcode Cloud fails due to derived data path mismatch

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#6452]
### What happened?

`tuist run MyCommandLineTool` builds the tool but fails to find it in the correct location on Xcode Cloud.

### How do we reproduce it?

I execute `tuist run MyCommandLineTool` in `ci_scripts/ci_pre_xcodebuild.sh` and run the build on Xcode Cloud. I get an error message like:

```
The runnable product was expected but not found at /Users/local/Library/Developer/Xcode/DerivedData/Blah-eslrrvbbonlhhqhfmweztxfdafqk/Build/Products/Debug/MyCommandLineTool.
```

If I instead run `tuist build MyCommandLineTool` followed by executing `$CI_DERIVED_DATA_PATH/Build/Products/Debug/MyCommandLineTool` it works.

I assume `tuist run` isn't using the same derived data path that `tuist build` is picking up from the Xcode Cloud env var.

### Error log

```
The runnable product was expected but not found at /Users/local/Library/Developer/Xcode/DerivedData/Blah-eslrrvbbonlhhqhfmweztxfdafqk/Build/Products/Debug/MyCommandLineTool.
```

### macOS version

14.5

### Tuist version

4.18.0

### Xcode version

15.4.0

**Comment by fortmarek** [comment]
Hey @hiltonc 👋 

Are you able to reproduce the issue locally? I am not super familiar with Xcode Cloud, so it might be difficult for me to reproduce the issue.

Are you or Xcode Cloud passing somewhere a custom derived data path?

[This](https://github.com/tuist/tuist/blob/main/Sources/TuistAutomation/Utilities/TargetRunner.swift#L92-L97) is how we locate the derived data path if you wanna try to look into this further yourself.

**Comment by hiltonc** [comment]
@fortmarek I'd be happy to open a PR for this, but I would want to verify that the fix works on Xcode Cloud. Currently I'm installing `tuist` with `mise` in my Xcode Cloud set up. Is there a simple way to have `mise` install from a forked branch, or to script it? I looked through https://docs.tuist.io/contributors/get-started for pointers but nothing stood out.

**Comment by hiltonc** [comment]
> Are you able to reproduce the issue locally? I am not super familiar with Xcode Cloud, so it might be difficult for me to reproduce the issue.

No, it only happens on Xcode Cloud.

> Are you or Xcode Cloud passing somewhere a custom derived data path?

I think Xcode Cloud is setting a custom dir using `CI_DERIVED_DATA_PATH`, which isn't accounted for yet in the derived data locator in Tuist.

**Comment by fortmarek** [comment]
> Currently I'm installing tuist with mise in my Xcode Cloud set up. Is there a simple way to have mise install from a forked branch, or to script it? I looked through https://docs.tuist.io/contributors/get-started for pointers but nothing stood out.

Yeah, there's a relatively fresh support for [SPM backend](https://mise.jdx.dev/dev-tools/backends/spm.html).

You should be able to run something akin to:
```sh
mise x spm:https://github.com/hiltonc/tuist.git@main -- tuist run
```

Note this builds `tuist` from source, so it's really recommended for testing only.

> I think Xcode Cloud is setting a custom dir using CI_DERIVED_DATA_PATH, which isn't accounted for yet in the derived data locator in Tuist.

I see – then yeah, we need to ensure that we respect the value. I'd grab the value from the environment in the `RunService` and then pass it down all the way to the `XcodeBuildController` through the `targetBuilder` and `targetRunner` utilities.

**Comment by hiltonc** [comment]
I'm having a lot of difficulty validating this on Xcode Cloud without a proper tuist release.

At first I tried using the spm backend from mise:

```
mise settings set experimental true
mise install spm:https://github.com/hiltonc/tuist.git@support-run-on-xcode-cloud-release
```

I made a `support-run-on-xcode-cloud-release` release in my fork from head (no changes yet). Running it all I would get is:

```
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Couldn't find resource named ProjectDescription
[1]    35537 trace trap  tuist run MyCommandLineTool
```

Then I tried just cloning and building:

```
git clone https://github.com/hiltonc/tuist.git -b support-run-on-xcode-cloud "$CI_PRIMARY_REPOSITORY_PATH/../tuist-clone"

 (
  cd "$CI_PRIMARY_REPOSITORY_PATH/../tuist-clone"
  mise install
  eval "$(mise activate bash --shims)"
   tuist install
   tuist generate --no-open
  swift build --product ProjectDescription
 )

cd "$CI_PRIMARY_REPOSITORY_PATH"
swift run --package-path "$CI_PRIMARY_REPOSITORY_PATH/../tuist-clone" tuist run MyCommandLineTool
```

Unfortunately this works without any changes. I would have expected it to fail in the way that a mise-installed tuist would. So I can't use that for validation.

I'll go ahead and open a PR with my changes at least. Open to any ideas.
