### ISSUE TITLE
Removed UI test targets when using `--skip-ui-tests`

### ISSUE THREAD

**Issue by woin2ee** [tuist/tuist#6453]
### What happened?

UI test targets are removed when run `tuist test --skip-ui-tests` against an open project.

I'm guessing because it generates a new project in [TestService](https://github.com/tuist/tuist/blob/0c30939eb86d7d9880e43e37b2f69b3034fe423f/Sources/TuistKit/Services/TestService.swift#L211)

I also believe that whatever solution can influence #6314. 

### How do we reproduce it?

1. Run `tuist generate` on the `ios_app_with_tests` fixture.
2. Run `tuist test --skip-ui-tests` with project being open.

### macOS version

14.1.1

### Tuist version

4.17.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
> UI test targets are removed when run tuist test --skip-ui-tests against an open project.

This is expected behavior. `tuist test` generates a new project and replaces your current one.

We used to generate the project for testing in a different location but we [reverted that](https://github.com/tuist/tuist/pull/5501) as it was causing lots of confusion.
