### ISSUE TITLE
Tuist with RealityComposerPro package

### ISSUE THREAD

**Issue by AndreaMiotto** [tuist/tuist#6459]
### What problem or need do you have?

What is the best solution to handle the RealityComposerPro package with Tuist.

If I run `Tuist init` it removes the package file and therefore I cannot open anymore the package with Reality Composer Pro.

### Potential solution

If I add back the package file I can open the project with Reality Composer Pro, but it doesnt look like a maintainable solution.
Otherwise I keep it as a SPM Package

### macOS version

14.5

### Tuist version

4.18.0

### Xcode version

15.4

**Comment by pepicrft** [comment]
@AndreaMiotto is the issue that the package doesn't compile?

**Comment by fortmarek** [comment]
A reproducible sample with reproduction steps would also be appreciated here 🙏

**Comment by fortmarek** [comment]
Closing as we're missing a reproducible sample.
