### ISSUE TITLE
On-demand tags with .rkasserts

### ISSUE THREAD

**Issue by AndreaMiotto** [tuist/tuist#6464]
### What problem or need do you have?

I am unable to find a way to add tags to any file inside an .rkassets

```Swift
resources: [
                .folderReference(path: "./Resources/Assets.xcassets", tags: ["tag1"]),
                .folderReference(path: "./Resources/VR.rkassets", tags: ["tag1"])
            ]
```

the xcassets work while the rkassets don't 

### macOS version

14

### Tuist version

4

### Xcode version

15.4

**Comment by kapitoshka438** [comment]
Is there an option to add ODR tags to rkassets in Xcode or Reality Composer Pro?

**Comment by AndreaMiotto** [comment]
directly to rkassets no. But it could be possible to find all the underneath assets and tag them one by one.

**Comment by kapitoshka438** [comment]
I don't think it's possible to operate with rkassets as on-demand resources. There is a limited list of supported resources which can be tagged as ODR: https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html
Even if Xcode could work with rkassets as data files, a RealityKit project is technically a Swift Package which does not support ODR.

**Comment by pepicrft** [comment]
@AndreaMiotto / @kapitoshka438, how do you think Tuist should handle this, assuming Xcode projects support that scenario?

**Comment by kapitoshka438** [comment]
Xcode does not currently support this. All we can do is close the issue for now.
