### ISSUE TITLE
Duplicate values for key conflict with SPM packages that also use Tuist

### ISSUE THREAD

**Issue by brunoorocha** [tuist/tuist#6465]
### What problem or need do you have?

Hello! I'm having a problem with my project. I have a project using Tuist and I need to include a project as a dependency to this project using SPM. To be more clear let's say that I have a project that I'll call Core and another called Network and I want to use Core as Network's dependecy as a SPM package. Both using Tuist 4.19.0. Following the docs to include dependencies and running tuist install and then tuist generate I have the error:
`Swift/arm64e-apple-macos.swiftinterface:13885: Fatal error: Duplicate values for key: '/Path/to/project/.build/checkouts/my-package'`

We're solving this running tuist install then deleting the `Project.swift` at `/Path/to/project/.build/checkouts/my-package` before running tuist generate but it doesn't looks right.

In order to help with debuging this I've created two repositories reproducing this scenario and you can find them at:
* [https://github.com/brunoorocha/tuist-demo-module-a](https://github.com/brunoorocha/tuist-demo-module-a)
* [https://github.com/brunoorocha/tuist-demo-module-b](https://github.com/brunoorocha/tuist-demo-module-b)

It's possible to reproduce it just cloning the Module A and running `tuist install` and then `tuist generate`.

### macOS version

14.5

### Tuist version

4.19.0

### Xcode version

15.2

**Comment by fortmarek** [comment]
Hey @brunoorocha 👋 

Try to make the glob in your `Workspace.swift` more concrete (in the repro case, it can be simply `projects: ["."]`. `**` is generally not a good practice since it also prolongs your generation times.

That being said, we should handle this more gracefully. I put up a [PR](https://github.com/tuist/tuist/pull/6469) that fixes the issue, but still need to write some tests.

**Comment by brunoorocha** [comment]
Hello, @fortmarek!

It worked for me, thanks a lot for your quick support!
