### ISSUE TITLE
Add a command to validate cache and project description by building each target in isolation

### ISSUE THREAD

**Issue by KaiOelfke** [tuist/tuist#6486]
### What problem or need do you have?

As explained in https://docs.tuist.io/guide/introduction/cost-of-convenience there can be a lot of implicitness in Xcode projects. When converting my most recent app I eventually reached a point where I could successfully build and run the main app target. But when I tried tuist generate with a focused list of target(s) it usually didn't work as some implicit dependency was missing as explicit dependency or something else was wrong on my side with the project. As well as this issue https://github.com/tuist/tuist/issues/6485.

In order to save time I'd love to have a command that basically loops through all targets and for each target does `tuist generate target` and then `tuist build target`. Ideally it would sort the graph so that it starts the generate and build with the targets with the smallest amount of dependencies.

With this I'd get all the errors due to implicitness and could fix them. And when it runs successfully I have confidence that I can work in each focused target in isolation with binary caching.

### Potential solution

I guess it should be possible to already implement this with a script or something else triggering the commands. But maybe this is something that could be built in, if it's deemed useful for others.

### macOS version

14.5

### Tuist version

4.18.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
Hey @KaiOelfke 👋 

Implicit dependencies are definitely tricky to avoid in a large project without any checks.

We're currently leaning to static analysis of dependencies. I will close this issue in favor of: https://github.com/tuist/tuist/issues/6492
