### ISSUE TITLE
Header search paths are not properly escaped to handle whitespace

### ISSUE THREAD

**Issue by KaiOelfke** [tuist/tuist#6487]
### What happened?

I ran into a couple of issues when converting my app with this dependency for syncing Core Data:

http://www.ensembles.io/

This is closed-source unfortunately, but I volunteered some time ago to add SPM support to the Objective-C codebase. It was previously distributed with different ways so I had to do add SPM support without breaking compatibility with that.

The main target in the Package.swift is as follows:

```swift
 .target(
    name: "Ensembles",
    dependencies: [],
    path: "Framework/Source/",
    resources: [.process("SwiftPackageResources")],
    publicHeadersPath: "SwiftPackageHeaders",
    cSettings: [
        .headerSearchPath("General"),
        .headerSearchPath("Asynchronicity"),
        .headerSearchPath("Baselines"),
        .headerSearchPath("Cloud"),
        .headerSearchPath("Cloud File Systems"),
        .headerSearchPath("Ensemble"),
        .headerSearchPath("Events"),
        .headerSearchPath("Integration"),
        .headerSearchPath("Migration"),
        .headerSearchPath("Model"),
        .headerSearchPath("Revisioning"),
    ]
),
```

I found out that Tuist doesn't handle this setting properly:

.headerSearchPath("Cloud File Systems"),

In Tuist generated projects this search path becomes "Cloud".

### How do we reproduce it?

I haven't made a sample. But I assume it should be possible to reproduce by making some dummy SPM package with a header search path with whitespace and then depending on that in the Tuist project description.

### Error log

```
The generated xcodeproject has an invalid header search path truncating all content after the first space.
```

### macOS version

14.5

### Tuist version

4.18.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
> I haven't made a sample. But I assume it should be possible to reproduce by making some dummy SPM package with a header search path with whitespace and then depending on that in the Tuist project description.

It'd be amazing if you could create that reproducible sample yourself 🙏 

If you want to fix this yourself, I believe we most likely need to update [this](https://github.com/tuist/tuist/blob/main/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift#L957) line, so that the header search paths are treated as a single string.

**Comment by KaiOelfke** [comment]
Here's a sample for now. It's also a sample for  #6488, but for this one the header search path stuff is relevant.

[EnsembleSample.zip](https://github.com/user-attachments/files/16140556/EnsembleSample.zip)

If I have time later I can try to setup a local development environment to get a failing test done first.

**Comment by fortmarek** [comment]
> If I have time later I can try to setup a local development environment to get a failing test done first.

That'd be amazing, let us know if you need any pointers 🤞

**Comment by KaiOelfke** [comment]
@fortmarek 

I managed to setup a local environment. I only ran into a Tuist Cloud issue, but I just removed that configuration locally.

> accountname is not authorized to read cached

The line you referenced doesn't seem to be the issue. Or I do things wrong as it's my first time running Tuist locally. When testing project mappers with adjusted unit tests as well as other places the whitespace was always handled correctly. So it must be lost somewhere else.

I don't know yet how I can run tuist generate with a debugger attached on my sample to see where in the process the String is truncated.

**Comment by fortmarek** [comment]
> I managed to setup a local environment. I only ran into a Tuist Cloud issue, but I just removed that configuration locally.

This is a known issue when you're authenticated with Tuist but you don't have access to the `tuist` organization. We plan to fix this, but logging out or removing the configuration is a necessary workaround for now. Sorry 🙏 

> I don't know yet how I can run tuist generate with a debugger attached on my sample to see where in the process the String is truncated.

You should be able to follow the [docs](https://docs.tuist.io/contributors/get-started.html#from-xcode) here to set up a custom path to run `tuist generate` with, so you can point it at your project.

**Comment by KaiOelfke** [comment]
Thanks, that was helpful. I just added a PR.
