### ISSUE TITLE
Detect implicit dependencies

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#6492]
### What problem or need do you have?

Allowing implicit dependencies in Xcode was a terrible decision. We tried to solve it by the addition of [enforceExplicitDependencies](https://docs.tuist.io/generated/manifest/structs/Config.GenerationOptions.html#enforceexplicitdependencies) flag where we augment the derived data, so that each target has its own directory with access to only explicitly defined dependencies.

However, the maintenance of that flag has turned out to be too expensive and we should find an alternative solution.

### Potential solution

We can turn to static analysis and ensure that any `import XXX` is a defined, explicit dependency of that given target. @kwridan mentioned that's what they use at Bloomberg and they'd be willing to contribute that back to `tuist`.

### Tuist version

4.20.0

**Comment by kwridan** [comment]
Thanks for raising this @fortmarek 

The integration we have works as follows:

* There is a dedicated entry point to this via a `lint_dependencies` command
* Step 1) Extract graph data
   * Load all manifests / models
   * Collect target & dependency information (into a `DependenciesDescriptor` type)
* Step 2) Run analysis on the collected data within a `DependenciesLinter` component
   * Extract all the imported modules from target associated sources
   * Compare against the explicitly declared dependencies in the manifest
* Finally results are printed out

The upstreamable part is likely to be the `DependenciesLinter` component

**Comment by pepicrft** [comment]
Thanks a lot @rofle100lvl for taking this one on 🙏🏼. You can't imagine how useful this will be for the users of Tuist.

**Comment by fortmarek** [comment]
Already implemented by @rofle100lvl 🚀
