### ISSUE TITLE
Template files are read-only in `tuist.zip`

### ISSUE THREAD

**Issue by ofalvai** [tuist/tuist#6495]
### What happened?

I ran into a weird bug when using Tuist, asdf, and the [asdf-tuist](https://github.com/asdf-community/asdf-tuist/tree/main) plugin. I'm not sure if this is the right place for this bug report, but I think the ultimate root cause is in this repo, so please bear with me!

When running `asdf install tuist 4.2.0` (or any other version), the process hangs with this output:
```
❯ asdf install tuist 4.2.0
* Downloading tuist release 4.2.0...
tuist 4.2.0 installation was successful!
/Users/oliverfalvai/.asdf/downloads/tuist/4.2.0
override r--r--r-- oliverfalvai/staff for /Users/oliverfalvai/.asdf/downloads/tuist/4.2.0/Templates/default/LaunchScreen+macOS.stencil?
```

The line `tuist 4.2.0 installation was successful!` is printed by the Tuist plugin, so the issue is not in that codebase, something happens after that. I tracked down the problem to [this line](https://github.com/asdf-vm/asdf/blob/master/lib/functions/installs.bash#L241) in asdf itself, which deletes the temporary download.

Looking at the contents of `tuist.zip`, I see that the files in `Templates/default` are read-only:
```
❯ unzip -Z tuist.zip
Archive:  tuist.zip
Zip file size: 26478800 bytes, number of entries: 110
-rwxr-xr-x  3.0 unx 75452360 bx defN 24-Jul-02 12:58 tuist
[...]
drwxr-xr-x  3.0 unx        0 bx stor 24-Jul-02 13:03 Templates/
drwxr-xr-x  3.0 unx        0 bx stor 24-Jul-02 13:03 Templates/default/
drwxr-xr-x  3.0 unx        0 bx stor 24-Jul-02 13:03 Templates/default/macos/
drwxr-xr-x  3.0 unx        0 bx stor 24-Jul-02 13:03 Templates/default/macos/Assets.xcassets/
drwxr-xr-x  3.0 unx        0 bx stor 24-Jul-02 13:03 Templates/default/macos/Assets.xcassets/AppIcon.appiconset/
-r--r--r--  3.0 unx      904 tx defN 24-Jul-02 13:03 Templates/default/macos/Assets.xcassets/AppIcon.appiconset/Contents.json
drwxr-xr-x  3.0 unx        0 bx stor 24-Jul-02 13:03 Templates/default/macos/Assets.xcassets/AccentColor.colorset/
-r--r--r--  3.0 unx      123 tx defN 24-Jul-02 13:03 Templates/default/macos/Assets.xcassets/AccentColor.colorset/Contents.json
-r--r--r--  3.0 unx       63 tx defN 24-Jul-02 13:03 Templates/default/macos/Assets.xcassets/Contents.json
-r--r--r--  3.0 unx     1566 tx defN 24-Jul-02 13:03 Templates/default/default.swift
[...]
```

This is probably why the `rm` call in asdf prompts me. To test this theory, I patched asdf to do `rm -rf` and this time everything worked.

I couldn't find the release workflow or a packaging script in this repo, so I'm stuck here, but I'm happy to raise a PR if the fix is trivial. I also know that Mise is the primary version manager of Tuist, but because Mise also uses the `asdf-tuist` plugin, it would be nice to fix this small blocker.

Edit: I guess the other way to solve this would be a `chmod -R` in `asdf-tuist` right after unzipping the archive.

### How do we reproduce it?

1. Set up ASDF
2. `asdf plugin add tuist`
3. `asdf install tuist 4.2.0`

### Error log

```
* Downloading tuist release 4.2.0...
tuist 4.2.0 installation was successful!
/Users/oliverfalvai/.asdf/downloads/tuist/4.2.0
override r--r--r-- oliverfalvai/staff for /Users/oliverfalvai/.asdf/downloads/tuist/4.2.0/Templates/default/LaunchScreen+macOS.stencil?
```

### macOS version

15.0

### Tuist version

4.2.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
We recommend using `mise` instead of `asdf`. I don't think that issue still happens there. If so, I'd recommend opening a new issue with repro steps for `mise` and we can take a look.

**Comment by ofalvai** [comment]
@fortmarek isn't the Tuist + Mise integration powered by the same [asdf-tuist](https://github.com/asdf-community/asdf-tuist) plugin?

Also, I can understand asdf is not the preferred version manager, but I think the permission issue comes from how Tuist itself is packaged. I would have opened a PR in `asdf-tuist` already if it was fixable there:

> I couldn't find the release workflow or a packaging script in this repo, so I'm stuck here, but I'm happy to raise a PR if the fix is trivial. I also know that Mise is the primary version manager of Tuist, but because Mise also uses the asdf-tuist plugin, it would be nice to fix this small blocker.
