### ISSUE TITLE
tuist cloud clean does not clean the remote cache

### ISSUE THREAD

**Issue by JanC** [tuist/tuist#6501]
### What happened?

hey,
it seems that even after running `tuist cloud clean`, the cached binaries are still present in the cloud and re-downloaded on the next invocation of `tuist generate`

### Populate the cloud cache
1. Use the attached project [tuistapp.zip](https://github.com/user-attachments/files/16164234/tuistapp.zip). The project was generated using `tuist init` + added a dependency to `Alamofire`
2. Add your cloud config in `Tuist/Config.swift`
3. Populate the remote cache using `tuist cache --external-only` 

```shell
Build Succeeded
Creating XCFrameworks
Creating XCFramework for Alamofire
Storing binaries to speed up workflows
Storing remote binaries. Hold tight...
Finished storing remote binaries
1 target(s) stored: Alamofire
```
✅  `Alamofire` is saved to cache as expected

### Attempt to clean the cloud cache

1. clean any local cache using `rm -rf ~/.cache/tuist-cloud`
2. run `tuist cloud clean`
```
❯ tuist cloud clean
Project was successfully cleaned.
```
4. Generate the project again

```
tuist generate --no-open

Loading and constructing the graph
It might take a while if the cache is empty
Fetching remote binaries. Hold tight...
Finished fetching remote binaries
Using cache binaries for the following targets: Alamofire
Generating workspace tuistapp.xcworkspace
```

### Expected
The Alamofire binary is not fetch from the cache

### Actual

-  The log message indicates that Alamofire is fetched from the clould cache
- The `Alamofire.framework` is indeed present in the BinaryCache:

```bash
❯ find ~/.cache/tuist-cloud/BinaryCache/ -name "Alamofire.framework"
/Users/janchaloupecky/.cache/tuist-cloud/BinaryCache//6b0888b8bfa0bb5f8fb3d6c55bc9c2f9/Alamofire.xcframework/ios-arm64_x86_64-simulator/Alamofire.framework
/Users/janchaloupecky/.cache/tuist-cloud/BinaryCache//6b0888b8bfa0bb5f8fb3d6c55bc9c2f9/Alamofire.xcframework/ios-arm64/Alamofire.framework
```

It can also be verified by using a https proxy and inspecting the requests from the tuist cli:

The request to delete the cache succeeds:
```
PUT https://cloud.tuist.io/api/projects/mycompany/myproject/cache/clean

HTTP/1.1 200 OK
```

When regenerating the project, the request to fetch the cache key still returns a valid cache entry

```
GET https://cloud.tuist.io/api/cache?cache_category=builds&project_id=mycompany/myproject&hash=6b0888b8bfa0bb5f8fb3d6c55bc9c2f9&name=Alamofire

HTTP/1.1 200 OK

{
  "data": {
    "url": "https://tuist-cloud-productio<redacted>.com/prometheus/mycompany/myproject/builds/<redacted>Alamofire?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<redacted>Date=20240710T150257Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=c656f9c909e3f10399f2c900b734932eb29d78428781fdc11006c017aab5ad09",
    "expires_at": 1720627377
  },
  "status": "success"
}
```

### Error log

```
tuist generate --no-open

Loading and constructing the graph
It might take a while if the cache is empty
Fetching remote binaries. Hold tight...
Finished fetching remote binaries
Using cache binaries for the following targets: Alamofire
Generating workspace tuistapp.xcworkspace
```

### macOS version

14.6

### Tuist version

4.20.0

### Xcode version

15.3.0

**Comment by fortmarek** [comment]
Thanks again for raising this, the fix is now being deployed and should be available in the next hour 🤞

**Comment by JanC** [comment]
great, thanks 🙏
