### ISSUE TITLE
Targets referenced from a workspace scheme build step aren't validated

### ISSUE THREAD

**Issue by DmitrySerovWise** [tuist/tuist#6510]
### What problem or need do you have?

When I raised the issue of custom, non-Tuist defined schemes not being supported (https://github.com/tuist/tuist/issues/6480), I was advised to define schemes in Workspace.swift instead of Xcode.

While experimenting with this, I noticed that if I want a scheme to have a build action, the target that is supposed to be built is not validated for existence, and Tuist produces an empty build action if a target is invalid.

In other words, given this Workspace.swift:

```
import ProjectDescription

let workspace = Workspace(
    name: "MyWorkspace",
    projects: [
        "MyProject",
    ],
    schemes: [
        .scheme(
            name: "MyScheme",
            buildAction: .buildAction(
                targets: [.target("BASICALLY ANY TEXT WORKS")]
            ),
            testAction: .testPlans([
               ...
            ]),
            runAction: .runAction(
                ...
            )
        ),
    ]
)

```

I can type any text into instead of 'BASICALLY ANY TEXT WORKS' and Tuist will happily generate the scheme. If the target with this name doesn't exist, Tuist doesn't output any warnings or errors, and this is how the resulting scheme's build action looks like:

```
<BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
<BuildActionEntries></BuildActionEntries>
</BuildAction>
```

### Potential solution

There is some validation happening at the workspace level (for example, the projects for the `projects` property are checked for existence and there's a warning if a project doesn't exist).

Validation could be extended to the targets referenced from the workspace. I don't know the order of the things happening, but looking at the output it appears that the Workspace is generated before the projects (and their targets), and checking for the projects's existence doesn't require the project to be generated (hence the existing validation that works). If true, this means the proper way to solve this would be to generate the projects before the workspace, unless there's any reason not to do this – and then apply the knowledge of the projects and their constituent targets during the validation of Workspace.swift.

### macOS version

14.5

### Tuist version

4.20.0

### Xcode version

15.4

**Comment by kwridan** [comment]
Thanks for flagging this @DmitrySerovWise. 

I believe 
https://github.com/tuist/tuist/issues/6491 should address is issue and will be in the next release.

**Comment by kwridan** [comment]
Latest main would produce the following warning:

```
The following warnings need attention:
 · Cannot find targets BASICALLY ANY TEXT WORKS (.)  defined in Workspace-App
```

It does some validation 👍 , however there's a missing piece here which would be good to warn about as well. For workspace schemes targets need to be referenced using `.project(path:, target:)` as opposed to `.target()` to specify which projects they reside in. 

This could take the form of simpler warning that checks for [`TargetReference`](https://github.com/tuist/tuist/blob/main/Sources/ProjectDescription/TargetReference.swift#L8) with unspecified `projectPath`s. The `ManifestLinter` could be extended to also lint `Workspace`s and their associated schemes.

**Comment by pepicrft** [comment]
Let's keep this one to address the scenario that @kwridan mentioned. If anyone wants to take this one on, feel free to do so. You can use [this other implementation](https://github.com/tuist/tuist/pull/6491) as a reference.
