### ISSUE TITLE
Fails to generate when signed in to a different Tuist Cloud organization

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#6511]
### What happened?

I'm generating the Tuist project from source while signed in to my organization's Tuist Cloud and the command fails. The error is unexpected because I didn't expect to be able to use Tuist's build cache, and it worked fine previously when I was not signed in to my organization's Tuist Cloud.

I can work around it with `tuist generate --no-binary-cache`.

### How do we reproduce it?

1. Authenticate with Tuist Cloud with an account other than the Tuist project's cloud account
2. Checkout the source for Tuist
3. Run `tuist generate`

### Error log

```sh
Loading and constructing the graph
It might take a while if the cache is empty
Fetching remote binaries. Hold tight...
<username> is not authorized to read cache
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

14.5

### Tuist version

4.20.0

### Xcode version

15.4

**Comment by pepicrft** [comment]
@hiltonc thanks for reporting this. We have plans to support accessing the cache when using public projects like `tuist/tuist` in this case. We've added it to our backlog.
