### ISSUE TITLE
Use COMPILER_INDEX_STORE_ENABLE=NO during tuist cache

### ISSUE THREAD

**Issue by voidless** [tuist/tuist#6532]
### What problem or need do you have?

Disabling `COMPILER_INDEX_STORE_ENABLE` speeds up build times by 6% in our project.
The indexing is only useful if you're gonna actually work with the project in Xcode, so it is safe to disable during `tuist cache` builds.

### Potential solution

Use `COMPILER_INDEX_STORE_ENABLE=NO` during tuist cache

Other solution is to allow users to pass configuration params to `tuist cache` command.
It can also allow configuring other params like that: `OTHER_SWIFT_FLAGS="-warnings-as-errors"`

### macOS version

14.5

### Tuist version

4.20.0

### Xcode version

15.4.0

**Comment by fortmarek** [comment]
This will be included in the next release, thanks for raising this!

**Comment by voidless** [comment]
Hi, I haven't seen it in the release notes. Is it already included in the latest release?

**Comment by fortmarek** [comment]
Yes, it should be 👍
