### ISSUE TITLE
Generated SWIFTPM_MODULE_BUNDLE does not work with dynamic framework

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#6539]
### What happened?

I have a target that depends on the third-party PocketSVG library, which is written in Objective-C. That library accesses the bundle using `SWIFTPM_MODULE_BUNDLE`. Unfortunately the library is unable to access its bundle when I run the app or run tests against a target that depends on it when I use dynamic linking.

I put a breakpoint in Tuist's generated `PocketSVG_SWIFTPM_MODULE_BUNDLE` and found that it does not find the bundle:

```objective-c
NSBundle* PocketSVG_SWIFTPM_MODULE_BUNDLE(void) {
    NSURL *bundleURL = [[[NSBundle mainBundle] bundleURL] URLByAppendingPathComponent:@"PocketSVG_PocketSVG.bundle"];

    NSBundle *bundle = [NSBundle bundleWithURL:bundleURL];

    return bundle;
}
```

I modified it by hand to this and it does find the bundle:

```objective-c
@interface BundleFinder : NSObject
@end
@implementation BundleFinder
@end

NSBundle* PocketSVG_SWIFTPM_MODULE_BUNDLE(void) {
    return [NSBundle bundleForClass:[BundleFinder class]];
}
```

I'm sure an actual solution, which supports all the various types of linking and module types, would require more than the above. However, this is very much out of my wheelhouse.

### How do we reproduce it?

Repro:

1. Create an app using Tuist that uses the `PocketSVG` library as a dynamic framework
2. Run the app

Expected: runs fine
Actual: crash when it attempts to access data from the bundle that `PocketSVG` loads

Workaround:

1. Replace the generated `PocketSVG_SWIFTPM_MODULE_BUNDLE` function with the implementation and class from above
2. Run the app

Here's a minimal project to repro the issue:

[repro.zip](https://github.com/user-attachments/files/16338521/repro.zip)

It is already generated and has the workaround applied. Run `tuist generate` to re-generate the default implementation which leads to the crash.

### Error log

```
*** Assertion failure in hexTriplet::hexTriplet(NSString *__strong)(), SVGEngine.mm:904
```

### macOS version

14.5

### Tuist version

4.21.2

### Xcode version

15.4

**Comment by fortmarek** [comment]
Hey @hiltonc 

I believe this [PR](https://github.com/tuist/tuist/pull/6565) might have fixed this issue. Would you mind testing this again, either by running [Tuist from source](https://docs.tuist.io/contributors/get-started#run-tuist) or with the new version (once released)?

**Comment by hiltonc** [comment]
@fortmarek Testing results:

* Works in the app
* Fails in tests
* Fails in both the app and tests of the repro project

**Comment by fortmarek** [comment]
Hey @hiltonc 👋 

Turns out allowing _any_ product type in our `PackageSettings` is a mistake. In your repro, you have the following in your `Package.swift`:
```swift
#if TUIST
import ProjectDescription

let packageSettings = PackageSettings(
    productTypes: [
        "PocketSVG": .framework,
    ]
)
#endif
```

Since `.framework` supports resources, we don't generate a bundle for the target, but SVGEngine assumes the bundle to be present when compiled in the context of an SPM package: https://github.com/pocketsvg/PocketSVG/blob/d30bf6678ae93763782a4e19973dc64762d42c4a/Sources/SVGEngine.mm#L885-L890

While such an assumption is not ideal, it's actually correct – the only allowed SPM product types are `.dynamicLibrary` and `.staticLibrary`, neither of which support resources, so regardless of the selected SPM linkage type, both SPM and tuist would generate.

If you change the custom product type of `PocketSVG` to `.dynamicLibrary`, the app will no longer crash in runtime.

**Comment by fortmarek** [comment]
I'm gonna close this issue in favor of: https://github.com/tuist/tuist/issues/6583

**Comment by fortmarek** [comment]
Reopening as my research above was not correct – we should keep the product to `.framework`.

**Comment by fortmarek** [comment]
This is the correct fix: https://github.com/tuist/tuist/pull/6584

Note that you will need to upgrade the library to `2.7.3`.

**Comment by hiltonc** [comment]
Just verified that #6584 + PocketSVG 2.7.3 fixes the issue for both app and tests. Thank you! 💜
