### ISSUE TITLE
Error after migrate - tuist generate

### ISSUE THREAD

**Issue by kusainovaka** [tuist/tuist#6543]
### What problem or need do you have?

After migrate from tuist 3.42.0 to tuist 4.20.0
Can't open project
```
 tuist generate

The 'swift' command exited with error code 1 and message:
/path.../Project.swift:2:8: error: no such module 'ProjectDescriptionHelpers'
import ProjectDescriptionHelpers
```

### macOS version

14.1

### Tuist version

4.20.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
Please, provide a reproducible sample.

See the [docs](https://docs.tuist.io/guides/develop/projects/code-sharing.html#project-description-helpers) for how to use `ProjectDescriptionHelpers`.

**Comment by kusainovaka** [comment]
<img width="959" alt="Снимок экрана 2024-07-24 в 10 50 00" src="https://github.com/user-attachments/assets/575691bb-1fba-42f2-aee9-185f2917234f">
We use  `ProjectDescriptionHelpers` right, on the 3,42 version all works, on new version project doesnt run, but `tuist edit ` success build

**Comment by fortmarek** [comment]
Can you try if you can successfully generate [this](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_helpers) fixture? If so, I'd recommend comparing the fixture with your project and try to spot any differences.

I'd also recommend trying to create a reproducible sample that you can share with us which makes it easier to debug any issues/provide help.

**Comment by kusainovaka** [comment]
Hello, i write from this issue i dont know how to fix this problem,
my steps to migrate from tuist 3.42 to 4.20
1. Install new tuist version 4.20
2. Fix error from migrate( from Target( to Target.target(.. and DeploymentTargets) after this Manifest file success build
3. i try to tuist generate and had error Project.swift:2:8: error: no such module 'ProjectDescriptionHelpers' into Target.framework 

Maybe I forgot something ? Project into tuist 3.42 works without problems

**Comment by fortmarek** [comment]
Have you tried generating the fixtures that use helpers that I sent? We need more information or ideally a reproducible sample, there's no way I can help you right now, sorry.
