### ISSUE TITLE
App extension with test target is not supported by tuist

### ISSUE THREAD

**Issue by InderKumarRathore** [tuist/tuist#6553]
### What happened?

I wanted to add test target for one of my app extension but it's not supported by tuist.

### How do we reproduce it?

`LintableTarget(platform: .iOS, product: .appExtension),` is missing  here

https://github.com/tuist/tuist/blob/6e0d9d5a26e5459e45be748b986261f536db8f2a/Sources/TuistGenerator/Linter/GraphLinter.swift#L449

### Error log

Target ExtensionTests has platforms 'iOS' and product 'unit tests' and depends on target Extension of type 'app extension' and platforms 'iOS' which is an invalid or not yet supported combination.

### macOS version

14.4

### Tuist version

4.21.2

### Xcode version

15.3

**Comment by fortmarek** [comment]
Hey @InderKumarRathore 👋 

This combination does feel like it should be valid. How do you feel about contributing to make this possible?

You can add app extension to the supported list and create a new fixture in the [fixtures](https://github.com/tuist/tuist/tree/main/fixtures) directory. You can then test the fixture in an acceptance test [here](https://github.com/tuist/tuist/blob/main/Tests/TuistGeneratorAcceptanceTests/GenerateAcceptanceTests.swift).

**Comment by InderKumarRathore** [comment]
@fortmarek I created a PR: https://github.com/tuist/tuist/pull/6561
Let me know if this looks good

**Comment by InderKumarRathore** [comment]
@fortmarek when can I expect the new release with these changes?

**Comment by fortmarek** [comment]
> when can I expect the new release with these changes?

Later today 🙏
