### ISSUE TITLE
Add the possibility to specify a custom .lldbinit file

### ISSUE THREAD

**Issue by Blackjacx** [tuist/tuist#6560]
### What problem or need do you have?

I want to populate this field in the scheme settings and don't see that this is currenlty possible: 

![image](https://github.com/user-attachments/assets/be16f536-30bc-48a5-bd16-2bab6dafc6d8)

### Potential solution

Add a new parameter `lldbinitpath` to the `Scheme` initializer.

### macOS version

14

### Tuist version

4.15.0

### Xcode version

15F31d

**Comment by fortmarek** [comment]
Hey 👋 

This is already possible using the [customLLDBInitFile](https://docs.tuist.io/generated/manifest/structs/RunAction#customlldbinitfile). You can see an example usage [here](https://github.com/tuist/tuist/blob/d4a6a56482ee98581276bf53fe34d6335887cc45/fixtures/ios_app_with_custom_scheme/App/Project.swift#L21).

Does this solve your need? Feel free to reopen if not.

**Comment by stherold** [comment]
Oooops thanks for the hint 👍🏼 In the past I just did not find API references that easy. But now your search is perfect 🙏🏼

**Comment by Blackjacx** [comment]
Oooops thanks for the hint 👍🏼 In the past I just did not find API references that easy. But now your search is perfect 🙏🏼
