### ISSUE TITLE
MetaCodable macro cannot work with Tuist

### ISSUE THREAD

**Issue by mo5tone** [tuist/tuist#6579]
### What happened?

I am trying to use some swift macros in my project.
I found that [ComposableArchitecture](https://github.com/pointfreeco/swift-composable-architecture) can work properly as external dependency. 
But the [MetaCodable](https://github.com/SwiftyLab/MetaCodable) not.

Both work well as package dependencies.

### How do we reproduce it?
[demo.zip](https://github.com/user-attachments/files/16427920/demo.zip)

1. Unzip the attached demo.zip
2. cd demo && tuist install && tuist generate
3. Build failed with error

### Error log

Instance method 'decode(_:from:)' requires that 'Foo' conform to 'Decodable'

### macOS version

14.5 (23F79)

### Tuist version

4.21.2

### Xcode version

15.4 (15F31d)

**Comment by TTOzzi** [comment]
I'm having the same problem.
Is this a problem with tuist?

**Comment by mo5tone** [comment]
> I'm having the same problem. Is this a problem with tuist?

They both work well as package dependencies. So I think it should be caused by tuist.

**Comment by mo5tone** [comment]
This seems fixed in 4.36.0

**Comment by mo5tone** [comment]
Close as seem fixed in 4.36.0
