### ISSUE TITLE
Resources from external packages aren't embedded into appExtension

### ISSUE THREAD

**Issue by rock88** [tuist/tuist#6586]
### What happened?

Hello!
I want to make an app with a embedded app extension (LiveActivity) with a dependency on a Localization package. I use an `.external(name: "Localization")` to include the Localization package. But bundle from `Localization` package do not embed to LiveActivity extension (I get a runtime crash when accessing the `Localization` bundle).

I think it's because the resource bundles are not copied into the app extension bundle:

<img width="805" alt="Screenshot 2024-07-31 at 18 42 30" src="https://github.com/user-attachments/assets/5027574f-b695-46e7-943a-92f78ee72ba1">

For example, CocoaPods does copying:

<img width="805" alt="Screenshot 2024-07-31 at 18 48 13" src="https://github.com/user-attachments/assets/feaca122-02a7-4f57-beb2-eb48e2118dc2">

### How do we reproduce it?

Example project: https://github.com/rock88/tuist-app-extension-bundle-issue
1. `tuist generate`;
2. Run on iOS Simulator >= 16.2;
3. Tap on a `Request LiveActivity` (at this step LiveActivity should appear at Lock Screen and Dynamic Island with Hi! text);
4. At this step you can connect to the debugger (Debug -> Attach to Process by PID or Name... -> enter `LiveActivity` and push `Attach` button);
5. Return to the main app and tap Update -> `Localized` button (After this LiveActivity will use localized string from `Localization` package);
6. Crash:
<img width="700" alt="Screenshot 2024-07-31 at 18 39 34" src="https://github.com/user-attachments/assets/7443f7bd-9a01-4cba-bcf2-a33f70f56276">

### Error log

```
Thread 1: Fatal error: unable to find bundle named Localization_Localization
```

### macOS version

14.5

### Tuist version

4.22.0

### Xcode version

15.4

**Comment by rock88** [comment]
Or as a workaround and to avoid duplicating the resource bundles, we can try to find these bundles in the main application:

```diff
// swiftlint:disable all
// swift-format-ignore-file
// swiftformat:disable all
import Foundation// MARK: - Swift Bundle Accessor - for SPM
private class BundleFinder {}
extension Foundation.Bundle {
/// Since Localization is a static framework, the bundle containing the resources is copied into the final product.
static let module: Bundle = {
    let bundleName = "Localization_Localization"
    var candidates = [
        Bundle.main.resourceURL,
        Bundle(for: BundleFinder.self).resourceURL,
        Bundle.main.bundleURL,
    ]
    // This is a fix to make Previews work with bundled resources.
    // Logic here is taken from SPM's generated `resource_bundle_accessors.swift` file,
    // which is located under the derived data directory after building the project.
    if let override = ProcessInfo.processInfo.environment["PACKAGE_RESOURCE_BUNDLE_PATH"] {
        candidates.append(URL(fileURLWithPath: override))
        // Deleting derived data and not rebuilding the frameworks containing resources may result in a state
        // where the bundles are only available in the framework's directory that is actively being previewed.
        // Since we don't know which framework this is, we also need to look in all the framework subpaths.
        if let subpaths = try? FileManager.default.contentsOfDirectory(atPath: override) {
            for subpath in subpaths {
                if subpath.hasSuffix(".framework") {
                    candidates.append(URL(fileURLWithPath: override + "/" + subpath))
                }
            }
        }
    }
+   if Bundle.main.bundleURL.pathExtension == "appex" {
+       candidates.append(Bundle.main.bundleURL.deletingLastPathComponent().deletingLastPathComponent())
+   }
    for candidate in candidates {
        let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
        if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
            return bundle
        }
    }
    fatalError("unable to find bundle named Localization_Localization")
}()
}// swiftlint:enable all
// swiftformat:enable all
```

I tried to check what happens if the main app doesn't have a `Localization_Localization.bundle` and removed `.external(name: "Localization")` from the `LiveActivityApp` target, but the `Localization_Localization.bundle` is still copied to the main app and I can do `import Localization`:

<img width="720" alt="Screenshot 2024-07-31 at 22 00 39" src="https://github.com/user-attachments/assets/04335ebc-fc56-49fe-ad66-6b4ae0fab7b9">


I don't know if this is expected behavior, but if I were doing a similar project manually or using CocoaPods, I wouldn't be able to `import Localization` into the main app and `Localization_Localization.bundle` would only be in `LiveActivity.appex`.

**Comment by rock88** [comment]
Yes, with CocoaPods (and static libraries) I can't do `import Alamofire` in the main app:

<img width="440" alt="Screenshot 2024-07-31 at 22 42 08" src="https://github.com/user-attachments/assets/1a51c6bc-c59e-4c70-905f-2e578ddbc2b4">

And `Alamofire.bundle` copied only to `LiveActivity.appex`.
If I add:

```swift
#if TUIST
    import ProjectDescription

    let packageSettings = PackageSettings(
        productTypes: [
            "Localization": .staticLibrary,
            "LiveActivityKit": .staticLibrary,
        ]
    )
#endif
```

to `Package.swift` I can still `import Localization`, but at the link stage I get the expected error:

<img width="440" alt="Screenshot 2024-07-31 at 22 51 22" src="https://github.com/user-attachments/assets/7cf41ea2-a8ad-4b30-a22f-7aa668188800">

But why don't I get an error earlier at `import Localization`?

---

Sorry for the off-topic, I've only used `Tuist` for small example projects of individual modules before, and now I'm trying to migrate the entire project from Cocoapods to `Tuist/SPM -> Xcode Project targets` 😄

**Comment by rock88** [comment]
Hi @fortmarek,
The main application does not crash, only LiveActivity crashes. If you tap the `Localized` button and look at what's happening with LiveActivity, you'll see something like this:

<img src="https://github.com/user-attachments/assets/adf84005-d8e2-43e2-a534-a79c06044736" width="320" /> <img src="https://github.com/user-attachments/assets/de7eaaef-42ed-46dc-a89b-528f96a1bb39" width="320" />

Instead of localized string `Test (EN)` the loader is displayed, this means that LiveActivity has crashed.

**Comment by rock88** [comment]
> I would also try on `4.21.0` tuist version in case that PR caused a regression.

Hey @fortmarek, I checked `tuist@4.21.0` and in this version everything works like a charm:

<img height ="300" alt="Screenshot 2024-08-04 at 14 44 30" src="https://github.com/user-attachments/assets/a2df98d3-aa62-4287-9454-c80f6faec61f"> <img height ="150" alt="Screenshot 2024-08-04 at 14 44 44" src="https://github.com/user-attachments/assets/d4bad8cd-eb10-463c-9f82-0f1a2511bf69">

<img src="https://github.com/user-attachments/assets/db915781-aa23-4d34-9021-8d7feffc26a2" height="320" />

**Comment by fortmarek** [comment]
Thanks for checking @rock88. Indeed, this is a regression. I put up a fix: https://github.com/tuist/tuist/pull/6604
