### ISSUE TITLE
Detect and warn about outdated dependencies when running tuist generate

### ISSUE THREAD

**Issue by KaiOelfke** [tuist/tuist#6588]
### What problem or need do you have?

As discussed in Slack I was using `tuist generate` on a PR branch of the Tuist repo after merging in the latest upstream changes. I was hit by seemingly random build errors that initially didn't make sense as I didn't change anything in there. Eventually, I figured out that dependencies might be outdated and that I forgot to run `tuist install` before. That fixed the issue.

### Potential solution

I'm not sure what the best experience here would be. Some ideas:

- warn in the output of `tuist generate`, if `tuist install` is recommended / needed
- fail `tuist generate`, if `tuist install` is recommended / needed
- provide some flag e.g. `tuist generate --install-dependencies`
- configure `tuist generate` to automatically run `tuist install`, when dependencies are outdated

Outdated dependencies don't always result in build errors as far as I know as different versions can be compatible. But it's still advisable to work with the latest committed version I guess.

For the implementation there's some ideas in Slack, but basically `tuist generate` needs to know what's installed locally vs what was committed with the last dependencies change.

If package resolution is slow then maybe the check needs to be configurable to not slow down `tuist generate` unless the user wants the check e.g. in cases where `tuist generate` is run often without changed dependencies. If checking is equally fast or slower than installing it's maybe better to run `tuist install` without checking first.

### macOS version

14.5

### Tuist version

4.22.0

### Xcode version

15.4

**Comment by hiltonc** [comment]
One particular edge case I'm interested in is if I've declared an exact version for an SPM dependency. I think not having that version when running `tuist generate` should result in an error.

**Comment by fortmarek** [comment]
Thanks for flagging this @KaiOelfke.

My take on the solution:
- After `tuist install`, save the current state of `Package.resolved` in `Tuist/.build/Derived/Package.resolved`
- During `tuist generate`, check `Tuist/Package.resolved` and `Tuist/.build/Derived/Package.resolved` are equal
- If not, show a warning that you have outdated dependencies and you should run `tuist update`

That should be really it. The experience and implementation should be somewhat similar to the way `Pods/Manifest.lock` works.

**Comment by KaiOelfke** [comment]
> - After `tuist install`, save the current state of `Package.resolved` in `Tuist/.build/Derived/Package.resolved`
> 

So this is not committed and reflects what was last installed locally.

> - During `tuist generate`, check `Tuist/Package.resolved` and `Tuist/.build/Derived/Package.resolved` are equal
> 

So Tuist/Package.resolved is then the committed state of what should be installed.

Correct?

**Comment by fortmarek** [comment]
> So Tuist/Package.resolved is then the committed state of what should be installed.

Yes, correct 👍 That's already the case and it should stay that way 🤞

**Comment by hiltonc** [comment]
Apologies if you already had something in flight @KaiOelfke ... I'm trying to get my org to adopt Tuist and need this to close a concern.

**Comment by KaiOelfke** [comment]
No worries. I don't have time this month for any contributions anyway due to more urgent matters in my personal life. Just need to get those few things sorted first. 🙂

**Comment by stherold** [comment]
So how does this work in the end? I installed tuist 4.26.0 and run it but don't see any warnings about possibl updates. My `Package.swift` looks like this:
```swift
.package(url: "https://github.com/stripe/stripe-ios-spm", .upToNextMajor(from: "23.27.2")),
.package(url: "https://github.com/Quick/Quick", .upToNextMajor(from: "7.3.0")),
.package(url: "https://github.com/Quick/Nimble", .upToNextMajor(from: "12.3.0")),
```


The version specified is installed (Package.resolved) but there are newer versions available…

**Comment by sphanley** [comment]
@stherold, that's unfortunately not exactly what this feature was about. This is to catch a case where a teammate may have updated the packages in your Package.resolved on the remote, and you've pulled and haven't run `tuist install` locally yet to get the updates. The case it prevents is described [here](https://github.com/tuist/tuist/pull/6663#issuecomment-2322243269).

**Comment by fortmarek** [comment]
Correct ☝️ There are already solutions out there to make sure your dependencies are up-to-date with the latest released versions, such as dependabot, so I don't see this as something for Tuist to solve.

**Comment by stherold** [comment]
Ah okay nice 👍 My last info was that Dependabot does not support SPM but it seems to have changed…
