### ISSUE TITLE
xcbeautify Podspec points to non-existent release

### ISSUE THREAD

**Issue by pehagg** [tuist/tuist#6590]
### What happened?

First of all, sorry if this is the wrong repo, but I couldn't find a better place to report the issue.

We have started getting failing pod installs on a non-Tuist project, because the [xcbeautify 0.17.0 Podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/5/3/d/xcbeautify/0.17.0/xcbeautify.podspec.json) points to a tuist/xcbeautify release, but there are no releases in this repo (anymore?) 

### How do we reproduce it?

Include the follow line in a Podfile and run `pod install`: 

```
 pod 'xcbeautify', '0.17.0'
```

### Error log

```
Installing xcbeautify 0.17.0
[!] Error installing xcbeautify
[!] /usr/bin/curl -f
-L -0 /var/folders/p4/41mzjrf51fv44gvty_7k54840000gr/T/d20240801-31043-pfglkk/file.zip https://github.com/tuist/xcbea
utify/releases/download/0.17.0/xcbeautify-0.17.0-universal-apple-macosx.zip create-dirs -netrc-optional -retry 2 -A 'CocoaPods/1.15.2
cocoapods-downloader/2.1'
```

### macOS version

14.5

### Tuist version

N/A

### Xcode version

N/A

**Comment by fortmarek** [comment]
Hey 👋 

`xcbeautify` has been moved here: https://github.com/cpisciotta/xcbeautify

I suggest you open the issue there instead 🙂
