### ISSUE TITLE
Too much file generation after tuist install

### ISSUE THREAD

**Issue by keremersu35** [tuist/tuist#6591]
### What problem or need do you have?

I recently migrated tuist 3.22.0 to 4.15.0 because of firebase problem with the v3 versions. In the new version which is 4.15.0 when I execute tuist install, there are 22k file generation in SourceTree. It decreases when I remove some of dependencies but still generates lots of files. 

My Package.swift file:

```
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
import ProjectDescription
import ProjectDescriptionHelpers

let packageSettings = PackageSettings(
    productTypes: [
        "Alamofire": .framework,
    ],
    baseSettings: Settings.settings(
        configurations: [
            .debug(name: "Debug"),
            .debug(name: "Staging"),
            .release(name: "Release"),
        ]
    )
)
#endif

let package = Package(
    name: "PackageName",
    dependencies: [
        .package(url: "https://github.com/onevcat/Kingfisher.git", from: "7.0.0"),
        .package(url: "https://github.com/danielgindi/Charts", from: "4.0.1"),
        .package(url: "https://github.com/SwipeCellKit/SwipeCellKit", from: "2.7.1"),
        .package(url: "https://github.com/kasketis/netfox", from: "1.21.0"),
        .package(url: "https://github.com/longitachi/ZLPhotoBrowser", from: "4.4.8"),
        .package(url: "https://github.com/hackiftekhar/IQKeyboardManager", from: "7.0.3"),
        .package(url: "https://github.com/firebase/firebase-ios-sdk.git", from: "10.22.0"),
    ]
)
```
And SourceTree:

<img width="662" alt="image" src="https://github.com/user-attachments/assets/b6c28d87-6fcd-4b89-8dcf-1c23733da912">

Thanks for the support

### macOS version

14.3

### Tuist version

4.15.0

### Xcode version

15.2

**Comment by fortmarek** [comment]
`Tuist/.build` should be put into `.gitignore` – the same way you would gitignore `.build` directory if you worked on an SPM-based project.
