### ISSUE TITLE
Hide a scheme for an app extension doesn't work

### ISSUE THREAD

**Issue by squall2022** [tuist/tuist#6600]
### What happened?

When I try to hide a scheme for an app extension, it doesn't work.
It's working correctly for an app.
I'm using `hidden` parameter on `Scheme` object.

### How do we reproduce it?

Use the below manifest and run `tuist generate`: I use `hidden: true` for both `appScheme` and `extScheme`, but only `SchemeHideIssue-app` is hidden (`SchemeHideIssue-ext` is still visible, while it should be hidden)

```swift
import ProjectDescription

let appTarget: Target = .target(
    name: "SchemeHideIssue-app",
    destinations: .iOS,
    product: .app,
    bundleId: "io.tuist.SchemeHideIssue",
    infoPlist: .extendingDefault(
        with: [
            "UILaunchStoryboardName": "LaunchScreen.storyboard",
        ]
    ),
    sources: ["SchemeHideIssue/Sources/**"],
    resources: ["SchemeHideIssue/Resources/**"],
    dependencies: []
)

let extensionTarget: Target = .target(
    name: "SchemeHideIssue-ext",
    destinations: .iOS,
    product: .appExtension,
    bundleId: "io.tuist.SchemeHideIssue.ext",
    infoPlist: .extendingDefault(with: [:]),
    dependencies: []
)

let appScheme: Scheme = .scheme(
    name: "appScheme",
    shared: true,
    hidden: true,
    buildAction: .buildAction(targets: [TargetReference(stringLiteral: "SchemeHideIssue-app")]),
    testAction: nil,
    runAction: nil,
    archiveAction: nil,
    profileAction: nil,
    analyzeAction: nil
)

let extScheme: Scheme = .scheme(
    name: "extScheme",
    shared: true,
    hidden: true,
    buildAction: .buildAction(targets: [TargetReference(stringLiteral: "SchemeHideIssue-ext")]),
    testAction: nil,
    runAction: nil,
    archiveAction: nil,
    profileAction: nil,
    analyzeAction: nil
)

let project = Project(
    name: "SchemeHideIssue",
    targets: [
        appTarget,
        extensionTarget
    ],
    schemes: [
        appScheme,
        extScheme
    ]
)

```

### Error log

No error message

### macOS version

14.2

### Tuist version

4.15.0

### Xcode version

15.4

**Comment by tomekfab** [comment]
+1

**Comment by fortmarek** [comment]
Hey @squall2022 👋 

Can you attach a fully reproducible sample? i.e., a zip with a project that we can use to reproduce the issue? Alternatively, you can use one of our [fixtures](https://github.com/tuist/tuist/tree/main/fixtures) as a starting point. That helps us a lot when looking into issues.

**Comment by squall2022** [comment]
Thanks @fortmarek 

What I only did was create a new Tuist project and update the `Project.swift` file with the content I attached in the first post.

Anyway, here is the project: [schemeHideIssue.zip](https://github.com/user-attachments/files/16495087/schemeHideIssue.zip)

**Comment by squall2022** [comment]
Actually we didn't use the good way to create the scheme for our app extension (we needed to pass the app extension target but also the main app target for creating the scheme). Now we fixed that, the `hidden` flag is working.

I'm closing the issue, the example I provided was actually working, thanks!
