### ISSUE TITLE
SynthesizedPaths for TargetScript

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#6602]
### What problem or need do you have?

We need the ability for build phase scripts to specify a file in outputPaths that does not yet exist. For example, when using Sourcery, SwiftGen, Apollo.

This file (its contents) will be generated during the execution of the script in the build phase.

At the same time, creating a file before `tuist generate` with a separate command is quite inconvenient, because I have many projects and targets and I don’t want to manually write a file generation command for each target in which this script will be used.
```bash

touch TargetA/Generated/SomeFile.swift
touch TargetB/Generated/SomeFile.swift
touch TargetC/Generated/SomeFile.swift
touch TargetD/Generated/SomeFile.swift

tuist generate
```

This approach will have poor cohesion with the project manifest.

### Potential solution

It would be nice to add the ability to `TargetScript.outputPaths` to add the ability to specify not only existing file paths, but also generated ones, which the user will also have to generate when generating the manifest (as a resource synthesizer):
```swift
scripts: [ 
   .pre(
      script: "<some script that write output to File+Generated.swift>",
      ouputPaths: [
           "path/to/File+Generated.swift"
      ],
      synthesizedPaths: [ 
           "path/to/File+Generated.swift",
           "path/to/outputs.xcfilelist"
     ]
]
```

- The path in `synthesizedPaths ` argument **must be files**, not a glob.
- **Intermediate paths** will be automatically generated.
- The file must be generated **before this file is linked** to the target sources/resources. (For example, after `GeneratePrivacyManifestProjectMapper` append `GenerateTargetScriptSynthesizedPaths`)
- Calling `tuist generate` again should **not overwrite** the file

I'm ready to contribute to the implementation of this feature.

### macOS version

-

### Tuist version

-

### Xcode version

-

**Comment by fortmarek** [comment]
Would this be solved by: https://github.com/tuist/tuist/issues/5552 ?

If so, I'd close this as a duplicate.

**Comment by Ernest0-Production** [comment]
> Would this be solved by: #5552 ?

No, it's related to

- https://github.com/tuist/tuist/issues/6245
- https://github.com/tuist/tuist/discussions/6177

This is another way to approach the problem of delayed file generation in a xcode project.

1. The option to create a file in FileManager.default is not entirely correct due to the cache (https://github.com/tuist/tuist/discussions/6128)
2. Resetting the environment cache every time the project is generated does not seem very optimal
3. The special keyword for optional files can look a little dirty.

If I specify what I need for a specific task, then the final goal will be:
_The ability to generate files for scripts that will enrich them with content when compiling the project_

**Comment by kwridan** [comment]
I suspect this https://github.com/tuist/tuist/issues/5925 may help with this. That said, leveraging variables in input / output paths would permit specifying paths that don't exist today.

e.g. 

```swift
scripts: [ 
   .pre(
      script: "<some script that write output to File+Generated.swift>",
      ouputPaths: [
           "$(SRCROOT)/path/to/File+Generated.swift"
      ]
]
```

**Comment by Ernest0-Production** [comment]
Hi! @kwridan 

> I suspect this https://github.com/tuist/tuist/issues/5925 may help with this. That said, leveraging variables in input / output paths would permit specifying paths that don't exist today.

But this will not solve the problem of adding a file to the “compile sources” build phase during generation.

We need not only to specify the output file in the generation script, but also to be able to use this file in the future by integrating it into the project itself

**Comment by kwridan** [comment]
Thanks @Ernest0-Production 

> But this will not solve the problem of adding a file to the “compile sources” build phase during generation, for example.
> 
> We need not only to specify the output file in the generation script, but also to be able to use this file in the future by integrating it into the project itself

Indeed that part is currently missing, one of the suggestions on https://github.com/tuist/tuist/pull/6534#discussion_r1714804964 is to introduce something to permit that on sources such as 

```swift
sources: [
   "$(SRCROOT)/path/to/File+Generated.swift",
]
```

where variable paths would be omitted from globbing or perhaps something more explicit such as:

```swift
sources: [
   .generated("path/to/File+Generated.swift"),
]
```

**Comment by TamarMilchtaich** [comment]
Hi, we’re encountering the same issue and wanted to bring this discussion back up.

What about adding something like this:
```
.pre(
  script: "../BuildTools/user-info-phase.sh",
  name: "Run Script - User System Info",
  outputPaths: ["$(SRCROOT)/LTKit/Generated/LTSystemUserInfo.generated.swift"],
  useOutputPathAsSource: true,
),
```

This way, we can iterate over all the scripts, and use the relevant outputs as sources.

It’s not as clean as using `.generated(...)`. My main concern with `.generated(...)` is that all sources are now assumed to be globs, which introduces an issue: either we make a breaking change to the API by requiring `.glob` to be explicitly written for each path, or we assume that strings are globs. Assuming that strings are globs in this case might leads to unintuitive code IMO. Consider something like this:
```
sources: [
  "path/to/something/**",
  .generated("path/to/File+Generated.swift"),
  "another/path"
]
```
We can take all the string literals and translate them to `.globs`, but the API is confusing.

What do you think about starting with `useOutputPathAsSource` as a solution for this?

**Comment by fortmarek** [comment]
I find the API reads well:
```
sources: [
  "path/to/something/**",
  .generated("path/to/File+Generated.swift"),
  "another/path"
]
```

> What do you think about starting with useOutputPathAsSource as a solution for this?

I think declaring the generated sources with `.generated("...")` is better. For example, what if you don't generate your files with a build phase script?

> We can take all the string literals and translate them to .globs, but the API is confusing.

Could you expand a bit on why the API is confusing? `sources` takes both globs and explicit paths (where explicit path is a specific case of a glob that doesn't have any wildcards), so I think having `.generated` falls neatly into that mind model.

**Comment by TamarMilchtaich** [comment]
Good point about the generation source, I'll try and formulate it into code to explain what's bothering me
Are you thinking about something like [this draft](https://github.com/TamarMilchtaich/tuist/commit/9299be150aa508ca9de2a5e84d93929119a176ed)? (not sure where the parsing of the `.generated` from the manifest is done)

**Comment by fortmarek** [comment]
> Are you thinking about something like [this draft](https://github.com/TamarMilchtaich/tuist/commit/9299be150aa508ca9de2a5e84d93929119a176ed)? (not sure where the parsing of the .generated from the manifest is done)

Sort of – but I'd try to instead have a new static constructor in the `SourceFileGlob` type instead of a new parameter in the `sourceFileList` constructor:
```swift
public struct SourceFileGlob: Codable, Equatable, Sendable {
   // Maybe this could be an enum instead?
   public var isGenerated: Bool
   ...
   public static func generated(_ path: Path) -> Self {
      .init(isGenerated: true, ...)
   }
}
```

What do you think?

**Comment by TamarMilchtaich** [comment]
It is nicer ([draft](https://github.com/TamarMilchtaich/tuist/commit/a421aa283c5a3fe84f0ef0dc7d9783bdc130ca66))
We need to decide what to do when the generated file is given in a glob format:
```
sources: [
  .generated("path/to/something/**"),
]
```
If we keep the generation source as enum, we'll know it came from a script output/file in output file list, so we can find all the output files that match the pattern (tho it will probably require reading the content of the output file lists), but since we are using the enum which means we have the source, I think we can ignore it for now and add it later if that's a request

WDYT? If this seems like what we want, I can go ahead and open a PR

**Comment by fortmarek** [comment]
> If we keep the generation source as enum, we'll know it came from a script output/file in output file list, so we can find all the output files that match the pattern (tho it will probably require reading the content of the output file lists), but since we are using the enum which means we have the source, I think we can ignore it for now and add it later if that's a request

I'd error out when a user would pass a glob in the case of generated files – that list needs to be explicit. Since the files are specified with strings, I don't think we can enforce that there are no globs at compilation time.

**Comment by Ernest0-Production** [comment]
I think it is also important to fix 

- what will happen to the file when the project is re-generated (overwrite or skip)
- Is it exactly necessary to provide the path to the generation or to fix the generation in the Derived directory. If the develop wants to change the path of the generated file in the future, the old file will remain in the current project, which will slightly complicate the logic migration for the developer who did not take this into account in advance.

**Comment by TamarMilchtaich** [comment]
If I understand the questions correctly -
* After this fix, when the project gets generated, there would be a reference to the not-yet-existing file in resources. By the time the build phase that gathers the resources is ran, there will already be a file at this location, so there will be OK
* This works both when the file is and isn't in Derived Data. It makes sense to make it the user's responsibility to chose such path that's not included by any other glob, or to git ignore it if needed. This is by the way not different than what we have before the fix - if the file was listed as a source and it exists in such path because of the previous run, it will be included as a source.

Opened a PR, feel free to add any comments you have there as well:
https://github.com/tuist/tuist/pull/6990

**Comment by Ernest0-Production** [comment]
Hi! Thanks for implementing this feature!

I checked the update and it seems that it is not taken into account that TargetScript.outputPaths can specify generated files.
Currently, if you specify generated paths, Tuist does not add them to the build phase 🤔

**Comment by TamarMilchtaich** [comment]
Hi,
It doesn't automatically take all the output paths from the scripts and use them as resources for their respective targets, but rather allows the user to use declare them as sources, where previously it was only supported to use files that already exist at generation point as sources. We probably don't want to use all the output files as sources automatically, but let the user define explicitly those that they want to use as sources (there might be some output files that are not intended to be sources)

We can take `TargetScript.outputPaths` into account by throwing an error if the generated file is not listed as an output file of any script (though it will also require to read the output file lists, as the output file path might be mentioned there)
