### ISSUE TITLE
Archive action configuration not respected for custom configurations

### ISSUE THREAD

**Issue by nickkhg** [tuist/tuist#6621]
### What happened?

Custom schemes that use a custom configuration for the archive action will not be generated correctly. The generated scheme's archive action seems to always use the`Release` configuration rather than the custom configuration that is set in the manifest. This also happens even if the default `Release` scheme isn't defined.

This is only an issue for the archive action, the build action seems to be correctly generated.

The behaviour can be reproduced on all 4.x versions (I've checked 4.0.0 -> 4.23.0, haven't checked 3.x).

Slack thread: https://tuist-community.slack.com/archives/C018QG7U7SN/p1723197892357129

<img width="928" alt="Screenshot 2024-08-09 at 11 03 35" src="https://github.com/user-attachments/assets/0336ead1-8360-418f-83bb-5e4b201f2009">

### How do we reproduce it?

1. Create two custom configurations (e.g. `Debug-Beta` and `Release-Beta`) using the `settings` parameter of the project definition
2. Create a new scheme using the `schemes` parameter of the project definition, with:
       - `runAction` where the configuration is `Debug-Beta`
       - `archiveAction` where the configuration is `Release-Beta`
3. Generate the project
4. Edit the newly generated scheme
5. Notice that the build action correctly uses `Debug-Beta`, while the archive action uses `Release` instead of `Release-Beta`

Attached demo project below:
[archive-demo.zip](https://github.com/user-attachments/files/16561139/archive-demo.zip)

### Error log

N/A (No error logs, project generates without any errors)

### macOS version

14.5

### Tuist version

4.23.0

### Xcode version

15.4

**Comment by kwridan** [comment]
Thanks for flagging this @nickkhg 

Mind seeing if the fix in https://github.com/tuist/tuist/pull/6636 resolves it?

**Comment by nickkhg** [comment]
Hi Kwridan, thanks for sorting this! I had found the same fix for the issue, but haven't gotten around to actually opening the PR - I've added some extra tests as well, feel free to borrow them from my branch ([diff here](https://github.com/tuist/tuist/compare/main...nickkhg:tuist:feature/6621-fix-archive-action)) if you want
