### ISSUE TITLE
Need to know root or current path in manifest files

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#6629]
### What problem or need do you have?

I would like to know either the root directory of the project (or the path of the current manifest file, from which I could derive the root directory) in my manifest code files. I use this path to locate and process folders and data files which I use to generate targets and schemes.

Currently I use the current working directory which normally works, but this fails when I run Tuist from another directory and supply the `--path` argument (such as when debugging Tuist on my project from Xcode).

### Potential solution

One scalable way to provide this additional context would be:

1. Collect the context into a `Codable` struct:

```swift
public struct Context {
    /// The path to this manifest file.
    public let path: String
}
```

2. Populate an instance of the context and serialize it as JSON
3. Include the serialized context as an argument in `ManifestLoader.buildArguments(_:at:)`
4. Add a `context` property to `ProjectDescription.Environment` that reads the argument and decodes the context

This context would then be available in all the manifests.

Alternatively we could avoid using `Codable` and pass a single `path` argument instead. We'd parse it using `ArgumentParser` in `Environment` to supply the value.

### macOS version

14.5

### Tuist version

4.23.0

### Xcode version

15.4

**Comment by pepicrft** [comment]
> I use this path to locate and process folders and data files which I use to generate targets and schemes.

I'd discourage doing this because it breaks [hermecity](https://bazel.build/basics/hermeticity) making workflows less reproducible, harder to debug and optimize, and can potentially break internal caching functionality that relies on Tuist understanding the inputs and outputs the project depends on.

Could you expand more on the problem you are trying to solve to see if I can provide an alternative solution?

**Comment by hiltonc** [comment]
Currently my team has targets set up in our repo like this:

```
Project/
  Sources/
    Framework1/
      target.yml
      *.swift
    Framework2/
      target.yml
      *.swift
    ...
  Tests/
    Framework1Tests/
      target.yml
      *.swift
    Framework2Tests/
      target.yml
      *.swift
    ...
```

Our `Project.swift` manifest enumerates the contents of the file system to locate all folders with a `target.yml` file and produces a target according to the information within.

We're doing it this way because we have hundreds of targets and it is much more scalable to distribute the definition of targets.

I'm all for hermecity: I don't necessarily need the absolute location of the project in the file system, I just need to be able to enumerate the relative file system.

**Comment by fortmarek** [comment]
> Our Project.swift manifest enumerates the contents of the file system to locate all folders with a target.yml file and produces a target according to the information within.

Running file system operations when parsing the `Project.swift` manifest is something that we discourage. Why do you even use `target.yml` and not the Tuist manifests? 🤔

**Comment by fortmarek** [comment]
Let's move this discussion to the [community forum](https://community.tuist.io/) if still needed.

**Comment by hiltonc** [comment]
I'm now aligned with using Tuist manifests, I switched after your comment but never reported back. This is the way.
