### ISSUE TITLE
`tuist auth` doesn't use `TUIST_CONFIG_TOKEN` env var

### ISSUE THREAD

**Issue by pm-dev** [tuist/tuist#6632]
### What happened?

Running `tuist auth` always uses the browser auth flow even when the `CI` env var is set to 1.

### How do we reproduce it?

```shell
git:(meyers/tuist) export CI=1
git:(meyers/tuist) echo $CI   
1
git:(meyers/tuist) export TUIST_CONFIG_TOKEN=tuist_xyz
git:(meyers/tuist) echo $TUIST_CONFIG_TOKEN
tuist_xyz
iOS git:(meyers/tuist) tuist auth
```

### Error log

Results in:
```shell
Opening https://cloud.tuist.io/auth/cli/187DD91E-A35E-4B5C-8CF5-24481B0A5854 to start the authentication flow
```

I would expect `TUIST_CONFIG_TOKEN` to get picked up without the need to start the authentication flow

### macOS version

14.5

### Tuist version

4.23.0

### Xcode version

15.4

**Comment by pepicrft** [comment]
@pm-dev when you expose the token, the token authenticates requests automatically, therefore you don't need to call `tuist auth`. That workflow is an interactive workflow for people to run locally to authenticate as user.

**Comment by pm-dev** [comment]
@pepicrft thx for the clarification

**Comment by pm-dev** [comment]
It might be nice for `tuist auth` to check if `TUIST_CONFIG_TOKEN` and print out a warning like `tuist auth detected TUIST_CONFIG_TOKEN set, bypassing browser auth flow and using token`
