### ISSUE TITLE
Generated project build performance worse than SPM 

### ISSUE THREAD

**Issue by tburglar** [tuist/tuist#6640]
Hey there,

I am working on modularizing a somewhat large codebase.  Today its about 2million LOC.

As part of this work I am evaluating Tuist vs SPM.  I stumbled on a Bumble article saying the achieved better performance with Tuist.  I wanted to test this theory, so I generated a project to evaluate performance.

This project features 140 packages with a very thick web of dependencies between them.   The biggest chain is 140 dependencies long, from the first to the last package going through all others.

Testing locally I was surprised to find that SPM build performance was significantly (more than 2x) better than Tuist.  Specifically, for an intermediate build of the most leaf package, Tuist was about 70 seconds while SPM was 30.

I attached the generated project I am mentioning.  

I am curious what the Tuist team thinks about this.  Am I missing some optimizations?  Or are there certain kinds of dependency chains where Tuist is known to be slower than SPM?

Overall we are excited to migrate to Tuist since it offers many features that SPM doesn't, but build time is by far our most important concern when picking a technology.

[TestSPM.zip](https://github.com/user-attachments/files/16617239/TestSPM.zip)

### macOS version

14

### Tuist version

4.23

### Xcode version

15.4

**Comment by leeari95** [comment]
I ran the builds out of curiosity, and it seems that Tuist is faster.

<img width="1399" alt="image" src="https://github.com/user-attachments/assets/9cd651ec-8030-43d1-8ca3-e9445fcd0bc9">

**Comment by tburglar** [comment]
Gotcha, thats interesting.   I guess it could be computer dependent.

**Comment by tburglar** [comment]
Results seem to vary...
