### ISSUE TITLE
Don't require a token to generate

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#6645]
### What problem or need do you have?

`tuist generate` on the project with a `fullHandle` configured should succeed even if I'm not authenticated with `tuist auth`.

### Potential solution

When running `tuist generate`, change the `Token for Tuist was not found. Run 'tuist auth' to authenticate yourself.` error into a warning.

Or if we really want that to fail, we could at least let it succeed when `--no-binary-cache` is specified, or maybe a new arg like `--ignore-auth`.

### macOS version

14.6.1

### Tuist version

4.23.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
You can make the authentication optional: https://docs.tuist.io/generated/manifest/structs/Config.GenerationOptions#optionalauthentication. Would that work for you?

**Comment by hiltonc** [comment]
Yes, this works for me. Thank you!
