### ISSUE TITLE
Info Plist Extension `.xml` removed 

### ISSUE THREAD

**Issue by adamkhazi** [tuist/tuist#665]
**Describe the bug**
Looks like `lastKnownFileType` for `isa = PBXFileReference` is now referencing plist files with the `.plist` file extension. I believe this extension used to be `.plist.xml` in the past and it is currently how Xcode does it as well.  

**To Reproduce**

1. Go to 'fixtures/app_with_framework_and_tests' (should occur on other fixtures as well)
2. `tuist generate`
3. Find `PBXFileReference` that references "Info.plist" in `App.xcodeproj/project.pbxproj` 
4. Check the `lastKnownFileType` for the "Info.plist" file

**Expected behavior**
It is expected that `lastKnownFileType` for the "Info.plist" has the extension `.plist.xml`

**Example from app_with_framework_and_tests**
```
/* Begin PBXFileReference section */
// ...
		11EFDFD74F63B1D0D036B695 /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist; path = Info.plist; sourceTree = "<group>"; };
                E06AE2CBE1E7B2CD6E64D83B /* FrameworkTests.xctest */ = {isa = PBXFileReference; explicitFileType = wrapper.cfbundle; includeInIndex = 0; path = FrameworkTests.xctest; sourceTree = BUILT_PRODUCTS_DIR; };
// ...

/* End PBXFileReference section */
```

**Additional Context**
https://github.com/tuist/XcodeProj/pull/500 in Tuist/Xcodeproj might have introduced this.

**Comment by danyf90** [comment]
Given no one else complained in 3 years, I guess this is the expected behavior, feel free to reopen it otherwise 🙏
