### ISSUE TITLE
In-App Purchases capability getting removed after project regenration

### ISSUE THREAD

**Issue by GitNirajHub** [tuist/tuist#6650]
### What happened?

According to https://github.com/tuist/tuist/issues/3431

I have added

```
.sdk(name: "StoreKit.framework", type: .framework),
```

In the project definition

### How do we reproduce it?

Add the capability manually in xcode, and run
tuist generate

### Error log

On completion from the capabilities tab the in app purchase is getting removed.

### macOS version

14.4.1 (23E224)

### Tuist version

4.20.0

### Xcode version

15.4.0

**Comment by fortmarek** [comment]
> Add the capability manually in xcode, and run

Nothing done via the GUI is preserved across project generations. Everything needs to be done in the Tuist manifests which are the source of truth. In this case, capabilities are configured via [entitlements](https://docs.tuist.io/generated/manifest/structs/Target#entitlements)

**Comment by GitNirajHub** [comment]
@fortmarek 

I am aware that the changes made in GUI are not supposed to persist and it should be driven by manifest files.

The problem that i am facing is, that i am unable to find any record in entitlement that corresponds to In - app purchase, i have followed the conversation in: https://github.com/tuist/tuist/issues/3431

And as it mention this solution worked, i had created the issue, can you let me know if you are aware of exact entitlement that i may need to add in  [entitlements](https://docs.tuist.io/generated/manifest/structs/Target#entitlements) to get this working.

**Comment by jakub-kalamarz** [comment]
@GitNirajHub 
I encountered the same problem.

Here is the solution:
```
 dependencies: [
                .sdk(
                    name: "StoreKit",
                    type: .framework,
                    status: .optional
                ),
            ],
```

The way I look for such things is that I create a new project with git.
I set up in the Xcode what I want and analyze the project through uncommitted changes.
