### ISSUE TITLE
Exclude some plist from being derived file generated 

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#6658]
### What problem or need do you have?

I cannot find the way to include some plist in the project but not being parsed to swift code. I can skip plist file generators or generate all together but not choose which ones I want and which don't.

### macOS version

14.1

### Tuist version

4.3.4

### Xcode version

15.2

**Comment by fortmarek** [comment]
Would you mind providing more info? Either way, for questions, use our [community forum](https://community.tuist.io/) instead. Thanks for your understanding!
