### ISSUE TITLE
Firebase dependency prevents boringssl-SwiftPM dependency-Xcode-project from being generated

### ISSUE THREAD

**Issue by monchote** [tuist/tuist#6660]
### What happened?

- Integrating Google Firebase and [Google Nearby](https://github.com/google/nearby) dependencies produces errors when integrated via Tuist.
- The attached sample project points to my own fork because Google's repo has 2 separate issues that I've fixed and PR'd here: https://github.com/google/nearby/pull/2816
- When Firebase is not included, the dependency Xcode project for `BoringSSL-GRPC` gets correctly generated and the app builds well. When Firebase is included `BoringSSL-GRPC` is not generated and the project fails to build. 
- Firebase depends on a [different grpc package](https://github.com/firebase/firebase-ios-sdk/blob/main/Package.swift#L1377), which seems to be the source of the problem.

![Screenshot 2024-08-23 at 11 01 54](https://github.com/user-attachments/assets/ac4e7dfc-5c21-4863-b773-c2ffe18575d2) ![Screenshot 2024-08-23 at 10 51 55](https://github.com/user-attachments/assets/8925c9a2-0afa-4f46-9b2d-fd480b31bdb6)

### How do we reproduce it?

1. Use the attached sample project [tuist-googlenearbyconnections.zip](https://github.com/user-attachments/files/16726592/tuist-googlenearbyconnections.zip)
2. Run `tuist install && tuist generate`
3. Try to build and see errors

To remove Firebase and successfully build:
1. Edit `Package.swift` and comment out line 8
2. Edit `App/Project.swift` and comment out lines 19 and 20

### Error log

![Screenshot 2024-08-23 at 10 51 49](https://github.com/user-attachments/assets/536a9c78-150b-47c2-8f76-02bd6d9e0dcf)

### macOS version

14.6.1

### Tuist version

4.24.0

### Xcode version

15.1

**Comment by fortmarek** [comment]
Attaching a project with the fixed module alias: 
[tuist-googlenearbyconnections.zip](https://github.com/user-attachments/files/16838020/tuist-googlenearbyconnections.zip)
