### ISSUE TITLE
Tuist incorrectly handles SPM dependencies which define targets via .binaryTarget(name: path:) referencing .zip

### ISSUE THREAD

**Issue by sphanley** [tuist/tuist#6665]
### What happened?

Swift Package Manager supports packages declaring precompiled binary targets, using two syntax options: either via a remote URL, as in [binaryTarget(name:url:checksum:)](https://developer.apple.com/documentation/packagedescription/target/binarytarget(name:url:checksum:)), or via a local file path, as in [binaryTarget(name:path:)](https://developer.apple.com/documentation/packagedescription/target/binarytarget(name:path:)). When using Swift Package Manager directly, a dependency's Package.swift can use either of these approaches to reference a zipfile containing an xcframework, which will be unzipped by Swift Package Manager and referenced as a dependency. 

Unfortunately, Tuist seems to be unable to handle a Package.swift which references a zipped XCFramework via a local file path when using [Tuist's XcodeProj-based integration](https://docs.tuist.io/guides/develop/projects/dependencies#tuist-s-xcodeproj-based-integration). While executing `tuist install` seems to parse this syntax correctly, tuist throws an error when trying to run `tuist generate`. In comparison, binary zip targets which are referenced via a remote URL are resolved and loaded correctly. 

### How do we reproduce it?

I've created an [example repository](https://github.com/sphanley/TuistDemo/tree/main) which demonstrates this issue by using a local Package.swift, pointed to the precompiled SPM .zip files distributed by [Realm](https://github.com/realm/realm-swift/releases/tag/v10.53.0).

To reproduce the issue, simply clone the main branch, and first execute a `tuist install`. At this point, you'll see that the local binary targets have been correctly parsed, and the frameworks have been unzipped into `Tuist/.build/artifacts/realmswift/Realm/Realm.xcframework` and `Tuist/.build/artifacts/realmswift/RealmSwift/RealmSwift.xcframework`. 

Then, run `tuist generate`. Instead of generating the graph by using the frameworks which have been unzipped into `Tuist/.build/artifacts`, the Tuist project generator tries to treat the path from the `binaryTarget()` as pointing directly to an already-unzipped .xcframework, and fails because it cannot find an Info.plist by appending to the end of the file path. 

For comparison, you can then uncomment lines 17-24 in `LocalPackages/RealmSwift/Package.swift` and comment out lines 27-34. With that change made, rerunning the `tuist install` and `tuist generate` should successfully generate a project which references frameworks located at `Tuist/.build/artifacts/realmswift/Realm` and `Tuist/.build/artifacts/realmswift/RealmSwift`.

Lastly, the branch `xcode-default-spm` demonstrates consuming the local .zip binary targets via the default Xcode SPM integration, to illustrate that this syntax works as expected when not using Tuist's XcodeProj-based integration. 

Essentially, I believe this bug could be fixed by adjusting logic such that `tuist generate` routes Package.swift targets using `binaryTarget(name:path:)` with a path ending in .zip through the same handling that processes `binaryTarget(name:url:checksum:)` targets, resolving them to the frameworks that are unzipped at `tuist install` time. 

### Error log

When I attempt to generate a tuist project referencing a problematic package, I get the following error: 
```none
❯ tuist generate
Loading and constructing the graph
It might take a while if the cache is empty
The .xcframework at path /Users/samhanley/Development/github.com/sphanley/TuistDemo/LocalPackages/RealmSwift/RealmSwift@15.4.spm.zip/Info.plist doesn't contain an Info.plist. It's possible that the .xcframework was not generated properly or that got corrupted. Please, double check with the author of the framework.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

14.5

### Tuist version

4.24.0

### Xcode version

15.4

**Comment by sphanley** [comment]
Hi @fortmarek! My understanding was that this was similar but not quite a duplicate, because I understood #6411 to be requesting a change to Tuist's [`xcframework(path:status:condition:)`](https://docs.tuist.io/generated/manifest/enums/TargetDependency#xcframework-path-status-condition) target dependency type to support a ".zip" path, which is for referencing an XCFramework _without_ SPM, and which currently has zero support for zipped frameworks. 

In this case, though, I'm suggesting a tweak to [`external(name:condition:)`(https://docs.tuist.io/generated/manifest/enums/TargetDependency#external-name-condition), which consumes a dependency imported through Package.swift, and _does_ already support a .xcframework.zip, as long as the Package.swift is referring to that .zip via a remote URL. If you're able, I'd very much appreciate your taking a few minutes to run through the reproduction sample– my hope is that it makes clear why this is a fixable defect in the externalized SPM support, rather than an enhancement request, which is how I read #6411.

**Comment by fortmarek** [comment]
Thanks for the explanation @sphanley!

I agree this is not a duplicate then and something worth fixing. Happy to provide any help needed if you wanna take a stab at this.

**Comment by sphanley** [comment]
Thanks for the reassessment, @fortmarek! I'm happy to see if I can help with it if nobody's able to get to this right away; I was giving the code a look over to see if I could figure out where the needed change would be, but couldn't quite make heads or tails of it. If you're able to provide any pointers towards finding the code during a `generate` that specifically distinguishes between a Package.swift that's referencing a URL versus a local path, it would be very helpful.

**Comment by sphanley** [comment]
Aha, I suspect the needed change is near [here](https://github.com/Progressive-Insurance/tuist/blob/339a8e7e742154ed7e7211b0f3402569b3deaab8/Sources/TuistLoader/SwiftPackageManager/PackageInfoMapper.swift#L147), possibly just adding a check for `!path.hasSuffix(".zip")`. I'm trying to build it locally but I'm getting a "Missing argument for parameter 'sources' in call" error on [line 52 of Sources/TuistKit/Services/Inspect/InspecImplicitImportsService.swift](https://github.com/Progressive-Insurance/tuist/blob/339a8e7e742154ed7e7211b0f3402569b3deaab8/Sources/TuistKit/Services/Inspect/InspecImplicitImportsService.swift#L52) when trying to build the main branch– looks like the code merged by #6516 may have something missing?

**Comment by sphanley** [comment]
@fortmarek I believe I've got this resolved in the linked PR! I would very much appreciate a review at your convenience– thanks again for your attention to this issue and for your work on the project in general!

**Comment by pepicrft** [comment]
That was fast @sphanley 🚀. Contributions where developers come across the issues, report them, and go ahead with a fix are amazing. I'll add you as collaborator so that you no longer have to make those from forks, which is quite annoying.

**Comment by sphanley** [comment]
Amazing, thank you so much for the quick review and the kind words! I'm happy to be able to contribute to the project and I hope to continue doing so!
