### ISSUE TITLE
Static libraries dependencies fails to compile with `enforceExplicitDependencies` enabled in Debug

### ISSUE THREAD

**Issue by mikhailmulyar** [tuist/tuist#6667]
### What happened?

When project compiled with `enforceExplicitDependencies` config option enabled and it has static libraries dependencies it fails with error `no such module 'StaticDependency'`. It can be easily repeated in this tuist example https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_static_libraries by setting config option.

### How do we reproduce it?

1. Use https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_static_libraries fixture
2. Set config to `let config = Config(generationOptions: .options(enforceExplicitDependencies: true))`
3. Build fixture in Debug
4. Build fails with error `no such module 'B'`

### Error log

`no such module 'B'`

### macOS version

14.1

### Tuist version

4.24.0

### Xcode version

15.2

**Comment by fortmarek** [comment]
Hey 👋 

We will be deprecating the `enforceExplicitDependencies` in favor of adding a new command from this PR: https://github.com/tuist/tuist/pull/6516

We don't plan to ship any new fixes for this flag.
