### ISSUE TITLE
Custom Workspace Schemes

### ISSUE THREAD

**Issue by adamkhazi** [tuist/tuist#667]
## Need/problem

Currently in tuist custom schemes can be specified in the `Project.swift`. A limitation of the current implementation is that a scheme can only reference targets specified in the current project. It would be nice to also reference targets in other projects in the workspace that are in dependencies of the current project's targets (whether transitive or not). This would make custom schemes an even more useful feature.

## Motivation

Custom schemes are a great feature already of tuist. But it would be nice to be able to reference any target (test target or otherwise) that the current project depends on from them. It will offer more flexibility to the user.

For example, we have a few schemes that CI builds and these selectively include certain test targets from various projects in workspace.

## Detailed design

Extend the schemes to enable referencing targets in other projects. And to ensure that we maintain some level of safety we can leverage the graph to check and reference targets that the current project depends on.

## Drawbacks

- It could be confusing for the user in certain large projects which target is being included in their custom scheme. Targets with the similar or the same name in the graph that the current project depends on might be harder to distinguish when adding to a custom scheme. As such we may want to consider adding something like the below to disambiguate:
```swift
Scheme(name: "App-Release",
       shared: true,
       buildAction: BuildAction(targets: ["App"], preActions: [releaseAction]),
       testAction: TestAction(targets: [
                                .project(target: "FrameworkTests", path: "../Frameworks/Framework1"),
                                .project(target: "FrameworkTests", path: "../Frameworks/Framework2")
                              ]),
       runAction: RunAction(executable: "App"))
```

<img width="582" alt="Image" src="https://user-images.githubusercontent.com/9820670/68867440-b90eeb80-06ed-11ea-85f3-1d856f0d7a73.png">

## Adoption strategy

We make sure the change is backwards compatible. For example, the exsting defitnions of custom schemes will still be supported:

```swift
let releaseScheme = Scheme(name: "App-Release",
                           shared: true,
                           buildAction: BuildAction(targets: ["App"], preActions: [releaseAction]),
                           testAction: TestAction(targets: ["AppTests"]),
                           runAction: RunAction(executable: "App"))
```

**Comment by adamkhazi** [comment]
Upon thinking about this issue further and discussing with @kwridan, it might make more sense to implement this custom scheme API at the workspace level rather than the project level.

**Comment by pepibumur** [comment]
Hey @adamkhazi, I think this is a good idea. 

> Extend the schemes to enable referencing targets in other projects. And to ensure that we maintain some level of safety we can leverage the graph to check and reference targets that the current project depends on.

I agree with your point here on making sure that we maintain the safety through the checks. Adding safety as much as we can has been one of Tuist's principles and I think we should continue embracing this principle.

> Upon thinking about this issue further and discussing with @kwridan, it might make more sense to implement this custom scheme API at the workspace level rather than the project level.

Do you have an example of that API?

**Comment by adamkhazi** [comment]
Hey @pepibumur, I've been prototyping a way to add custom schemes to the workspace level while using the same custom scheme generation functions we already have for use during generation of custom workspace and project schemes. I would like to avoid duplicating scheme generation code for the two cases.

For the API for custom schemes at the workspace level it would look very similar to the way it is now for custom project schemes with the addition of a `.project(path: "Frameworks/Framework1", target: "Framework1")`. 

```swift
let scheme = Scheme(name: "SomeExampleCustomWorkspaceScheme",
                        shared: false,
                        buildAction: BuildAction(targets: [.project(path: "Frameworks/Framework1", target: "Framework1")], preActions: []),
                        testAction: TestAction(targets: [.project(path: "Frameworks/Framework1", target: "Framework1Tests")]),
                        runAction: RunAction(executable: .project(path: "Frameworks/Framework1", target: "Framework1Tests")))

let workspace = Workspace(name: "Workspace",
                          projects: [
                              "App",
                              "Frameworks/**",
                            ],
                          schemes: [scheme])
```

The API for custom project schemes would stay the same:
```swift
let scheme = Scheme(name: "SomeExampleProjectCustomScheme",
                           shared: true,
                           buildAction: BuildAction(targets: ["App"], preActions: [releaseAction]),
                           testAction: TestAction(targets: ["AppTests"]),
                           runAction: RunAction(executable: "App"))

let project = Project(name: "MainApp",
                      targets: [
                          Target(name: "App",
                                 platform: .iOS,
                                 product: .app,
                                 bundleId: "io.tuist.App",
                                 infoPlist: "Config/App-Info.plist",
                                 sources: "Sources/**",
                                 dependencies: [
                                     .project(target: "Framework1", path: "../Frameworks/Framework1"),
                                     .project(target: "Framework2", path: "../Frameworks/Framework2"),
                          ]),
                          Target(name: "AppTests",
                                 platform: .iOS,
                                 product: .unitTests,
                                 bundleId: "io.tuist.AppTests",
                                 infoPlist: "Config/AppTests-Info.plist",
                                 sources: "Tests/**",
                                 dependencies: [
                                     .target(name: "App"),
                          ])],
                      schemes: [scheme])
```


As this seems like it could be a relatively large change, we can adopt it using the following steps:
- [ ] Changing the functions in the `SchemeGenerator` to use the graph for look ups by default (as this is the main difference between the project and workspace schemes)
- [ ] Update the scheme model (in TuistGenerator) to start referencing targets using the `.project(...)`
- [ ] Expose workspace scheme type in the project manifest (ProjectDescription)

Note: for the last step we can either reuse the existing scheme type and enhance to allow setting the `.project(...)`. For example:
```swift
public struct BuildAction: Equatable, Codable {
    public let targets: [SchemeTarget] 
    // ...
}
// ... 
public struct SchemeTarget: Equatable, Codable {
    public var projectPath: String?
    public var targetName: String

    public static func project(path: String?, target: String) -> BuildActionTarget {
        return .init(projectPath: path, targetName: target)
    }
}

extension SchemeTarget: ExpressibleByStringLiteral {
    public typealias StringLiteralType = String

    public init(stringLiteral: String) {
        self = .init(projectPath: nil, targetName: name)
    }
}
``` 
This has one downside though, when defined using the types above in a workspace using a string literal like `"App"`maybe too ambiguous as we would need to know which project this target belongs to. We could provide some default behaviour here. Alternatively we can leave the project scheme as it is today. However introduce another dedicated workspace scheme type that allows the functionality above without optional project paths.

![Blank Diagram](https://user-images.githubusercontent.com/9820670/68962966-c3a0b200-07cd-11ea-9645-af6d3fb6be36.png)

**Comment by pepibumur** [comment]
Hey @adamkhazi. I really like the API and the plan that you are proposing for the implementation. I'm also curious about what @tuist/core thinks about it. I personally can't think of any rabbit hole that we might be disregarding but it's good to double check with more people just in case.

Thanks for bringing up this proposal 😛

**Comment by rowwingman** [comment]
Great, that is exactly  what I need :)
What about provide `Testability` parameters: randomize and parallel executing?
What about test plans Xcode 11 new feature ?

**Comment by kwridan** [comment]
+1 on the proposal - this will help us manage schemes across our entire workspace.

I've been paring with @adamkhazi on this, should be ready soon :)

@rowwingman re: the other attributes, they would be really useful addition too. Thanks for spinning that up in a separate issue 👍

**Comment by rowwingman** [comment]
Maybe you will be interested in https://github.com/tuist/tuist/pull/722
