### ISSUE TITLE
Issue with Embedding Dynamic Frameworks via SPM

### ISSUE THREAD

**Issue by heyken** [tuist/tuist#6683]
### What happened?

When integrating a dynamic framework as a package dependency via SPM, the framework is not listed as embedded in the General tab of Xcode.

For example, SnapKit is available in both static and dynamic forms.
(https://github.com/SnapKit/SnapKit)

In the case where the framework is specified as dynamic (SnapKit-Dynamic.framework) for the Test App Target using Tuist, 
it fails to embed properly. 
Consequently, when deploying the app to a physical device, it results in a crash with the following error:

'/private/var/containers/Bundle/Application/A5633D2A-BC93-4539-930B-D725AA57E4ED/TestSnapKit.app/Frameworks/SnapKit-Dynamic.framework/SnapKit-Dynamic' (no such file)

It is necessary for the framework to be configured as Embed rather than Do Not Embed in Xcode.

### How do we reproduce it?

**Tuist Code**
I writed code sample

let project = Project(
…
packages: [
        .package(url: "https://github.com/SnapKit/SnapKit.git", .upToNextMajor(from: "5.0.1"))
    ],
…
targets: [
  .target(
  …
  dependencies[
	 .package(product: "SnapKit-Dynamic", type: .runtime, condition: nil)
  ]
  …
)

### Error log

<img width="525" alt="스크린샷 2024-09-01 오후 5 27 11" src="https://github.com/user-attachments/assets/29069278-512e-4c48-901e-886facfaeb27">

### macOS version

14.1.1(23B81)

### Tuist version

4.25.0

### Xcode version

15.3

**Comment by fortmarek** [comment]
Hey @heyken 👋 

Would you mind attaching a sample project? You can create a new one using `tuist init` and then apply your reproduction steps.

**Comment by ArtemBurmistrov** [comment]
@fortmarek 
I have the same issue with adding Realm as a dependency. They changed the package type to `dynamic` in [`10.49.3`](https://github.com/realm/realm-swift/releases/tag/v10.49.3).
> dyld[2129]: Library not loaded: @rpath/RealmSwift.framework/RealmSwift
>   Referenced from: <D0FE9C34-D197-31CC-9D40-7D84DB7212B8> /private/var/containers/Bundle/Application/F887C040-C8D5-4B02-AC57-799AFFDE2475/TuistTest.app/TuistTest
>   Reason: tried: '/Users/User/Library/Developer/Xcode/DerivedData/TuistTest-fmdsfwukcxstuqarirbgfghnystl/Build/Products/Debug-iphoneos/PackageFrameworks/RealmSwift.framework/RealmSwift' (no such file), '/private/preboot/Cryptexes/OS/Users/User/Library/Developer/Xcode/DerivedData/TuistTest-fmdsfwukcxstuqarirbgfghnystl/Build/Products/Debug-iphoneos/PackageFrameworks/RealmSwift.framework/RealmSwift' (no such file), '/private/var/containers/Bundle/Application/F887C040-C8D5-4B02-AC57-799AFFDE2475/TuistTest.app/Frameworks/RealmSwift.framework/RealmSwift' (no such file), '/Users/User/Library/Developer/Xcode/DerivedData/TuistTest-fmdsfwukcxstuqarirbgfghnystl/Build/Products/Debug-iphoneos/PackageFrameworks/RealmSwift.framework/RealmSwift' (no such file), '/private/preboot/Cryptexes/OS/Users/User/Library/Developer/Xcode/DerivedData/TuistTest-fmdsfwukcxstuqarirbgfghnystl/Build/Products/Debug-iphoneos/PackageFrameworks/RealmSwift.framework/RealmSwift' (no such file), '/private/var/containers/Bundle/Application/F887C040-C8D5-4B02-AC57-799AFFDE2475/TuistTest.app/Frameworks/RealmSwift.framework/RealmSwift' (no such file)

Here is a test project:
[tuist-test.zip](https://github.com/user-attachments/files/16839846/tuist-test.zip)

**Comment by heyken** [comment]
@fortmarek  attached project
please check~ 

```
tuist clean
tuist install
tuist generate
```

A crash occurs on the actual device because it is not embedded.
(If you want to run it on an actual device, please enter the your bundle ID.)

[TestSnapKit.zip](https://github.com/user-attachments/files/16844068/TestSnapKit.zip)

**Comment by scarlettmueller96** [comment]
We are facing the same issue when integrating adjust with the SDK version 5 this way:


```
let project = Project(
…
packages: [
    .remote(url: "https://github.com/adjust/ios_sdk", requirement: .exact("5.0.0"))
],
…
targets: [
    .target(
        …
        dependencies[
            .package(product: "AdjustSdk" type: .runtime),
            .package(product: "AdjustWebBridge", type: .runtime),
        ]
        …
    )
]
```

**Comment by ArtemBurmistrov** [comment]
@pepicrft, could you please clarify what kind of input is expected here from the creator of this issue? The example project is already provided in this comment: https://github.com/tuist/tuist/issues/6683#issuecomment-2325658321

**Comment by fortmarek** [comment]
@ArtemBurmistrov the current info is sufficient 👍 

This looks like an unsupported setup. As per Realm [docs](https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/install/#-optional--build-realmswift-as-a-dynamic-framework), you need to change the `Embed` option for the `Realm` package to `Embed & sign`. The same would help with `SnapKit`.

However, there's currently no way to change the embed option when adding a package as a dependency: https://docs.tuist.io/generated/manifest/enums/TargetDependency#package-product-type-condition

Usually, tuist can make the decision – but that's not the case if you use the default SPM integration instead of the recommended [XcodeProj-based one](https://docs.tuist.io/guides/develop/projects/dependencies#tuist-s-xcodeproj-based-integration) since we don't know whether the package will be dynamic or not.

I'd propose adding a new case for the `PackageType` – `runtimeEmbedded` or `runtimeDynamic` where you could tell Tuist you expect the product to be dynamic and thus we'd always try to embed it.

Let us know if anybody in this thread is interested in implementing this 🤞

**Comment by Garfeild** [comment]
Hey folks! We are also facing this issue in one of project I'm working on. I would like to pick up this for work. As I understand correctly, we will need to replace `runtime` case with two to provide more context to XcodeProj, right?

**Comment by fortmarek** [comment]
Hey @Garfeild 👋 

Amazing to hear 🤩 

> As I understand correctly, we will need to replace runtime case with two to provide more context to XcodeProj, right?

Not replace, it should be a new addition. `.runtime` should keep the current behavior where we don't embed the dependency. `.runtimeDynamic` would then explicitly signal you expect the dependency to be dynamic and it should thus be embedded.

**Comment by Garfeild** [comment]
Hi @fortmarek!

We've decided to go with `.runtimeEmbedded` and here is the first PR, that adds new types to `XcodeGraph` https://github.com/tuist/XcodeGraph/pull/57

**Comment by Garfeild** [comment]
Hi @fortmarek! 

We have opened another PR with actual implementation. We would appreciate to get your feedback on it.
