### ISSUE TITLE
Deprecate `enforceExplicitDependencies` and provide guidelines around how to use the new `inspect implicit-imports` command

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#6696]
### What problem or need do you have?

`enforceExplicitDependencies` was our first attempt to catch implicit dependencies. However, it became clear that it was not a good approach because it tweaked how the build system worked, causing many scenarios not to work leading to a lot of support from our end. The `tuist inspect implicit-imports` superseded that, but we haven't deprecated the old method nor provided guidelines around its usage.

### Potential solution

- Mark `enforceExplicitDependencies` as deprecated. We should show a warning when the user uses that option in their manifest files. We should also mark it as deprecated in the struct definition itself so that it shows up in the docs.
- We should add guide around how to use the new feature. I suggest we do it in the [Guides > Develop > Projects > Best practices](https://docs.tuist.io/guides/develop/projects/best-practices) page. I'd mention where and when we recommend running that command.

**Comment by rofle100lvl** [comment]
Also we need to remove enforceExplicitDependencies from this page of documentation https://docs.tuist.io/en/guides/develop/projects/dependencies#local-dependencies

**Comment by fortmarek** [comment]
True, I missed that! Can you take that on? 😌

**Comment by m-appleseed** [comment]
Could you please clarify if the paragraph in [the article](https://docs.tuist.dev/en/guides/develop/projects/cost-of-convenience#shared-built-products-directory) is referring to the flag that was deprecated in the PR?

**Comment by fortmarek** [comment]
You are right, I updated the docs here: https://github.com/tuist/tuist/pull/7121

Thanks for raising that!
