### ISSUE TITLE
DefaultSettings is missing none case

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#670]
**Describe the bug**
Project.settings.defaultSettings should has none case, but it doesn't exist. You can find it on documentation https://docs.tuist.io/usage-2-projectswift#defaultsettings
In my case, all settings are in `xcconfig` file, I want to control all them in that file. So I want to disable override by tuist.

**To Reproduce**
1). Create settings for `Project` or `Target`, Settings(defaultSettings: .none).
2). `tuist generate`

```
error: type 'DefaultSettings' has no member 'none'
                               defaultSettings: .none)
```

**Expected behavior**
Settings has .none case, settings are not override.

**Comment by pepibumur** [comment]
Thanks for reporting this @marko1503. We have support for it but we forgot to add a public API. Would you like to open a PR yourself? You'll need to include the `none` case [here](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/Settings.swift#L142) and extend [this method](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Generator/GeneratorModelLoader.swift#L410) to take the new case into account.

**Comment by rowwingman** [comment]
@pepibumur How can I test the tool localy? Should I replace `tuist` at /usr/local/bin/tuist manually?

**Comment by pepibumur** [comment]
You can run the `tuist` scheme. If you edit the scheme you can set the `generate` argument, and change the working directory to point to the directory where the project is defined. Before running the `tuist` scheme, make sure you build the `tuist-Package` scheme first.
