### ISSUE TITLE
Mac cannot verify if twist is free of malware

### ISSUE THREAD

**Issue by JohnDemirci** [tuist/tuist#6702]
### What problem or need do you have?

I downloaded tuist using brew

when I tried to verify the installation by checking the --help on the command line I came across

```Apple could not verify “tuist” is free of malware that may harm your Mac or compromise your privacy.```

### Potential solution

you can manually allow tuist to run in the Mac settings

### macOS version

15 beta 2

### Tuist version

4.26.0

### Xcode version

16.0 beta 5

**Comment by fortmarek** [comment]
Hey, we're aware of this and hope to have a look soon.

Closing as this is a duplicate of: https://github.com/tuist/tuist/issues/5985
