### ISSUE TITLE
Not fail workflows if the server is unreachable

### ISSUE THREAD

**Issue by pepicrft** [tuist/tuist#6724]
### What problem or need do you have?

If the server or any of its dependencies (e.g. storage) is down, some CLI workflows like the generation of projects might fail.

### Potential solution

If requests fail, we can turn that into a warning and continue the execution. We should make sure that this errors show up somewhere in our system so that we are aware of potential issues with our server or our server's dependencies.

**Comment by fortmarek** [comment]
This has been already implemented.
