### ISSUE TITLE
Tuist generate doesn't work since MacOS Sequoia + Xcode 16 update

### ISSUE THREAD

**Issue by NicolasBroquet-DJM** [tuist/tuist#6744]
### What problem or need do you have?

I cannot anymore generate my project via the command tuist generate since I have updated my Mac with the Sequoia version and Xcode 16.
I get the error message:
```
We received an error that we couldn't handle:
    - Localized description: The data couldn’t be read because it is missing.
    - Error: keyNotFound(CodingKeys(stringValue: "name", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _CodingKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "settings", intValue: nil), _CodingKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"name\", intValue: nil) (\"name\").", underlyingError: nil))
```

### macOS version

15.0

### Tuist version

4.26.0

### Xcode version

16.0

**Comment by arnauddorgans** [comment]
Seems to be related to https://github.com/tuist/tuist/issues/6729

**Comment by NicolasBroquet-DJM** [comment]
Hello,
Indeed @arnauddorgans, thank you for the link.

**Comment by missingems** [comment]
The latest release, 4.27.0, was supposed to include this fix, but it seems the issue is still persisting for me as well.

**Comment by NicolasBroquet-DJM** [comment]
Hi, it works for me. 
Maybe some cache to clean or the version is not set properly on your machine.

**Comment by fortmarek** [comment]
Closing as things seem to be working now. Please, open a new issue if you still run into this.
