### ISSUE TITLE
Needs support for force not linking dependency

### ISSUE THREAD

**Issue by rgnns** [tuist/tuist#6751]
### What problem or need do you have?

The use case is this:

We have a dynamic framework which is used for multiple app extensions, but not for the app. If we don't add the dependency to the app, then the framework gets embedded to each app extension. If we embed it to the app though, it gets embedded only once and we can use it from any app extension, but it can't be linked though, otherwise it'd lead to duplicate symbols situation.

### Potential solution

There should be finer control over embedding and linking other than the defaults. For this one, I think it would be possible to disable the linking of any dependency if we add a third case to `LinkingStatus`, something such as `.noLinking`. And then take any dependency with `.forceNoLinking` out of becoming part of the linkable dependencies.

Alternatively, there's cases where we want dependencies to be built, but not embedded nor linked (this is needed for EarlGrey2 integration).
For embedding, we can have an additional `embed: EmbedStatus` parameter for TargetDependencies. to `.auto` meaning it lets Tuist do its thing, or it can be `.forceEmbed` or `.forceNoEmbed`.

The strategy between linking and embedding is slightly different, mostly because afaik, there's no case where we want to force linking.

### macOS version

14.6.1

### Tuist version

4.27.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
> We have a dynamic framework which is used for multiple app extensions, but not for the app. If we don't add the dependency to the app, then the framework gets embedded to each app extension

I wonder if there is a reason why one _would_ want to embed a framework each app extension, thus increasing the binary size. Instead of adding extra controls, should we consider making this the default behavior?

However, we can consider adding a `status: .none` option for extra granular control which still might be necessary if we solve the above. The beauty of not adding an option like that is that we get issues like these and we have the opportunity to encode the right behavior for everyone instead of teams silioing that knowledge in their respective codebases.

Do you think it would make sense to encode the behavior or would you lean to the more granular control? Long-term, we can also end up with both.

**Comment by rgnns** [comment]
@fortmarek, I considered making this the default behavior, but it's hard to tell the intention for the project if the framework is added on all app and app extension targets. The developers may want to share the framework with the app target too, or not to (like in our case). There's not really a way to deduce the intention unless we have deep knowledge of the code base.

During the EarlGrey integration I tend to think first of Tuist's philosophy of encouraging the right thing to do. However, I find it hard to establish what the "good practice" is when what we're trying to do is convert existing code bases that do not conform to standard Xcode project setups. Then there's the conversion of EarlGrey to Tuist, and the integration of it, which both require finer control of embedding and linking.

I think for the common developer who is dealing with app extensions, fine control of linking is the one that might come in handy (although rare) for the app extension case mentioned.

**Comment by fortmarek** [comment]
Gotcha, I think some extra fine-grained control is fine when:
- We have sensible defaults
- There are valid cases when Tuist can't tell what behavior it should default to

Would you want to take a stab at implementing this then? 🙂

**Comment by pepicrft** [comment]
> We have a dynamic framework which is used for multiple app extensions, but not for the app. If we don't add the dependency to the app, then the framework gets embedded to each app extension. If we embed it to the app though, it gets embedded only once and we can use it from any app extension, but it can't be linked though, otherwise it'd lead to duplicate symbols situation.

Why shouldn't the default there be that Tuist embeds the framework into the app? Suppose an app depends on extensions, which depend on a dynamic framework, considering extensions run in the context of an app. Is there a setup you might want other than just embedding the dynamic framework into the app?

**Comment by rgnns** [comment]
The case in which you may not want to embed to the app is when the framework is only for a specific app extension. But I think it would be ok if all frameworks are always embedded to the app, since app extensions would also find them there by default.

**Comment by fortmarek** [comment]
> The case in which you may not want to embed to the app is when the framework is only for a specific app extension. But I think it would be ok if all frameworks are always embedded to the app, since app extensions would also find them there by default.

Let's implement that and see if it still makes sense to have fine-grained control over the embed behavior?

**Comment by rgnns** [comment]
Sounds good. I know for certain a `.none` for linking is needed. I'll do that first and then how it goes for embedding requirements. Embedding is a bit more flexible in the sense that it is done right most of the times, and there's some control to it by simply copying the frameworks.

**Comment by kwridan** [comment]
Thanks @rgnns 

> I know for certain a .none for linking is needed.

Is this for the EarlGrey example below?

> Alternatively, there's cases where we want dependencies to be built, but not embedded nor linked (this is needed for EarlGrey2 integration).

Would schemes solve this? Where we can define multiple targets to be built but not direct dependency between the targets?

Note as things stand `.none` may only function in creating a target dependency within the same project but not across projects!

**Comment by rgnns** [comment]
@kwridan for EarlGrey and for targets that should be embedded in the app target but only linked to app extensions.

I don't think schemes work in this case. I think the case of embedding might be trickier than I remembered now that I've been revisiting this. There's multiple things that don't work the way EarlGrey instructs, but I'll see if I can make it work. Amongst the things that are different and to which I have little control over with Tuist:
- Linking a static library to a UI test target links not only the static library but all of its dependencies.
- Setting linking to `.none` according to the PR already created makes the no-linking requirement satisfied. However, the project will still try to embed it, and doesn't show the target in its target dependencies (the last is required  so it makes sure the target is built, and headers are found).
- There's an odd behavior/bug apparently (might not be a bug), where I have an app target, and another UI test rig target (which is also an app but integrates EarlGrey), and Tuist will create a scheme only for the test rig, but not for the app.
