### ISSUE TITLE
Archive problem after adding Swift Macro

### ISSUE THREAD

**Issue by aniltaskiran** [tuist/tuist#6762]
### What problem or need do you have?

The problem I’m experiencing is related to using macros in a Tuist project. Specifically, when trying to archive the project via the terminal using the following command:

`xcodebuild -workspace MyMacroTuist.xcworkspace -scheme MyMacroTuist -configuration Release -sdk iphoneos archive -archivePath Macro.xcarchive -allowProvisioningUpdates`

> ❌ error: Ad Hoc code signing is not allowed with SDK 'iOS 17.2' (in target 'MyMacroMacros' from project 'MyMacro')

However, this issue does not occur when archiving via Xcode directly. Additionally, if I use an SPM package instead of macros in Tuist or if I avoid generating the macros in Tuist, the error doesn't occur either.

It seems like there is an inconsistency between archiving with Tuist macros through the terminal versus using Xcode directly. My expectation is that the terminal archive process should work the same way as in Xcode without this signing issue.

[MyMacroTuistExample.zip](https://github.com/user-attachments/files/17115007/MyMacroTuistExample.zip)

### macOS version

14.6.1

### Tuist version

4.27.0

### Xcode version

15.1

**Comment by fortmarek** [comment]
Hey @aniltaskiran 👋 

Correct me if I'm wrong, but when you try to build an archive, you need to specify the destination to be `generic/platform=iOS Simulator`. The following command does work:
```sh
xcodebuild -workspace MyMacroTuist.xcworkspace -scheme MyMacroTuist -sdk iphoneos -destination 'generic/platform=iOS Simulator' archive
```

Let me know if this works for you and we can close the issue.

**Comment by roanutil** [comment]
When using `xcodebuild -workspace MyMacroTuist.xcworkspace -scheme MyMacroTuist -configuration Release -destination 'generic/platform=iOS' -archivePath Macro.xcarchive -allowProvisioningUpdates archive` the archive is successful with both Xcode 15.1 and 16.0. I get the same error when using the original `xcodebuild` command.

**Comment by aniltaskiran** [comment]
Yep, it worked. Thanks! 🙏🏽 When I added the -sdk iphoneos, it failed. I removed that, and it worked. Thank you! 🎉 Also, when I removed that, we needed to define the destination (it is not necessary; if I don’t add it, it works).
