### ISSUE TITLE
Keep targets order

### ISSUE THREAD

**Issue by c128128** [tuist/tuist#6794]
### What happened?

It seems that the order of targets defined in `Project.swift` is not preserved, and after running `tuist generate`, the targets are arranged alphabetically. I am not sure is this a bug or is a feature request :)

### Tuist version

4.28.1

### Xcode version

16.0.0

**Comment by fortmarek** [comment]
This is expected. If you'd like to propose a change of the behavior, I'd recommending creating a post in our [forum](https://community.tuist.io/).
