### ISSUE TITLE
The 'swift' was interrupted with a signal 9 (swift 5.10) - tuist init

### ISSUE THREAD

**Issue by MuhammadjonTohirov** [tuist/tuist#6804]
### What problem or need do you have?

swift 5.10 bug while running tuist init on Xcode 16 with swift 5.10
The 'swift' was interrupted with a signal 9
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

### macOS version

15.0 (24A335)

### Tuist version

4.28.1

### Xcode version

Version 16.0 (16A242d)

**Comment by fortmarek** [comment]
Hey @MuhammadjonTohirov 👋 

Would you mind providing the exact steps that you did and the _exact_ error message that you are getting? Otherwise, it's hard for us to provide help here.

**Comment by MuhammadjonTohirov** [comment]
Hi @fortmarek 

I've figured out the problem that tust I'm using was an older version so It was getting error because of keywords has changed. I managed to fix this. Thanks for your response
