### ISSUE TITLE
fix: do not require remote when `tuist --help`

### ISSUE THREAD

**Issue by vladimirleonidovich** [tuist/tuist#6819]
### What happened?

`tuist --help` requires a remote for some reason. I typed the command and got a message you can see in the error log below.

### How do we reproduce it?

Open your terminal and type the following commands:

```bash
cd ~
mkdir issue
cd issue
git init
tuist --help
```

### Error log

```sh
The 'git' command exited with error code 2 and message:
error: No such remote 'origin'

Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

13.5

### Tuist version

4.26.0

### Xcode version

14.1

**Comment by tangzhen** [comment]
this issue should fixed by: https://github.com/tuist/tuist/issues/6736#issuecomment-2385269641

**Comment by fortmarek** [comment]
Correct. We can reopen if you're still running into this issue in the latest `tuist` version.
