### ISSUE TITLE
`tuist cache <target> --external-only`

### ISSUE THREAD

**Issue by maschall** [tuist/tuist#6844]
### What problem or need do you have?

I have a Workspace project with three projects: A, B, C
The dependency tree looks like: A -> B -> C
The external tree looks like: C -> (externals)
                                                B -> (other externals)
(A has no external dependencies)

When I run `tuist cache A --external-only`, it will also generate Binaries to cache for B and C

The help page reads:
```
A list of targets to cache. Those and their dependant targets will be cached.
If no target is specified, all the project targets (excluding the external
ones) and their dependencies will be cached.
```

So it seems like it might be working as intended and was different than I expected.

### macOS version

14.6

### Tuist version

4.29.0

### Xcode version

15.4

**Comment by fortmarek** [comment]
Yes, the behavior is expected. We can't cache `A` without caching _all_ its dependencies as the command tells you:
> Those and their dependant targets will be cached.
