### ISSUE TITLE
xcodebuild linking error fille cannot be open()ed, errno=2

### ISSUE THREAD

**Issue by Nonouf** [tuist/tuist#6872]
### What happened?

I’m not entirely sure my problem comes from Tuist. I thought not, but other people had a very similar issue and they’re using Tuist as well, so I thought I reached out.

I very recently migrated our project to Swift 6. After fixing every issues, mostly due to Swift Concurrency, I’m getting the following error `file cannot be open()ed, errno=2` during the linking process with Xcode 16.0 and Tuist 4.29.1 :

At first I checked the path. The files were present and I can open them.

I tried cleaning the project, removing every derived data. I cleaned the cache, removed every dependencies. I fully cleaned the project and recreated it from scratch. Still no luck.
Then I checked the path again and realised that the files were indeed missing … 

II thought it might be an issue with my Xcode installation, so I tried running the project on another machine and I still get the same error every time.

I realised the error message would slightly change sometimes with one or many of the files not missing. I thought an issue in the code could be the cause of the problem, so I started commenting some stuff. I then compiled again and from time to time it’d compile. So I tried again cleaning the project and the derived data. Then I compile again and I get the error message again … 

### How do we reproduce it?

Hard to say how to reproduce it as I can’t share the project.

If needed I can try to reproduce it with a new project.
Happy to try out anything that can help you if you think it comes from Tuist. I'm all ears.

### Error log

```
Multiple errors: file cannot be open()ed, errno=2 
path=/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/Router.o in '/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/Router.o'; 

file cannot be open()ed, errno=2
path=/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/AccountRouter.o in '/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/AccountRouter.o'; 

file cannot be open()ed, errno=2 
path=/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/AlertRouter.o in '/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/AlertRouter.o'; 

file cannot be open()ed, errno=2 
path=/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/AlarmRouter.o in '/Users/MyUser/Library/Developer/Xcode/DerivedData/MyApp-euxwyncffackymerzuntbjccezyq/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/arm64/AlarmRouter.o'
```

### macOS version

15.0

### Tuist version

4.29.1

### Xcode version

16.0

**Comment by fortmarek** [comment]
Hey @Nonouf 👋 

Are you using the [XcodeProj-based integration](https://docs.tuist.io/en/guides/develop/projects/dependencies#tuist-s-xcodeproj-based-integration) of your third-party dependencies? That's the only feature where we diverge noticeably from the community and where I could see Tuist being to blame.

If not, or if the error is not coming from a dependency, I don't really see how this can be a Tuist specific issue. Tuist generates plain Xcode projects that you would have been able to create by "hand" as well.

**Comment by Nonouf** [comment]
No problem @fortmarek ! :) I’ll keep you updated if I find anything related to Tuist.
