### ISSUE TITLE
Build fails when adding `swiftlang/swift-cmark` as an external dependency

### ISSUE THREAD

**Issue by gonzalezreal** [tuist/tuist#6879]
### What happened?

Building the generated project fails when adding [swiftlang/swift-cmark](https://github.com/swiftlang/swift-cmark) as an external dependency in `Package.swift` with the following error:

```
/Users/.../MyApp/Tuist/.build/checkouts/swift-cmark/extensions/autolink.h:6:1
Missing '#include "cmark-gfm.h"'; 'cmark_syntax_extension' must be declared before it is used
```

For context, here is the content of `swift-cmark/extensions/autolink.h`:

```c
#ifndef CMARK_GFM_AUTOLINK_H
#define CMARK_GFM_AUTOLINK_H

#include "cmark-gfm-core-extensions.h"

cmark_syntax_extension *create_autolink_extension(void);

#endif
```

The strange thing is that `cmark-gfm-core-extensions.h` indirecly includes `cmark-gfm.h`. I checked the header search paths and they seem to be ok.

Adding `swiftlang/swift-cmark` as a regular SPM package in the `Project` initialization works fine.

### How do we reproduce it?

You can reproduce the issue with the following `Package.swift`:

```swift
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
  import ProjectDescription

  let packageSettings = PackageSettings(
    productTypes: [:]
  )
#endif

let package = Package(
  name: "MyApp",
  dependencies: [
    .package(url: "https://github.com/swiftlang/swift-cmark", from: "0.5.0")
  ]
)
```

And `Project.swift`:

```swift
import ProjectDescription

let project = Project(
  name: "MyApp",
  targets: [
    .target(
      name: "MyApp",
      destinations: .iOS,
      product: .app,
      bundleId: "io.tuist.MyApp",
      infoPlist: .extendingDefault(
        with: [
          "UILaunchScreen": [
            "UIColorName": "",
            "UIImageName": "",
          ],
        ]
      ),
      sources: ["MyApp/Sources/**"],
      resources: ["MyApp/Resources/**"],
      dependencies: [
        .external(name: "cmark-gfm"),
        .external(name: "cmark-gfm-extensions")
      ]
    ),
    .target(
      name: "MyAppTests",
      destinations: .iOS,
      product: .unitTests,
      bundleId: "io.tuist.MyAppTests",
      infoPlist: .default,
      sources: ["MyApp/Tests/**"],
      resources: [],
      dependencies: [.target(name: "MyApp")]
    ),
  ]
)
```

### Error log

```
/Users/.../MyApp/Tuist/.build/checkouts/swift-cmark/extensions/autolink.h:6:1
Missing '#include "cmark-gfm.h"'; 'cmark_syntax_extension' must be declared before it is used
```

### macOS version

15.0.1

### Tuist version

4.29.1

### Xcode version

16.0 (16A242d)

**Comment by lilidotshi** [comment]
Any update on this issue?

**Comment by fortmarek** [comment]
Hey 👋 

I'm looking into this one. I found the discrepancy between SwiftPM and our integration – the product name for the extensions product should be `cmark_gfm_extensions` but we map it to `cmark-gfm-extensions`. Since the product name is encoded in the modulemap, the build fails when the underscores are changed to dashes. I hope to post a PR fixing this soon.

Thanks for the patience 🙏
