### ISSUE TITLE
Add --quiet flag

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#6905]
### What problem or need do you have?

Based on discussion at https://community.tuist.io/t/enhancing-tuist-output-with-xcbeautify-seeking-customization-options/121/4

When running `tuist build` or `tuist test`, most of the `xcbeautify` on the CI is irrelevant – developers often care only about output from _failing_ test cases. The goal of this issue is to allow developers to skip printing output that's not critical.

### Potential solution

To solve this, we're proposing to add a `--quiet` flag which is a CLI standard. As per this [resource](https://clig.dev/#arguments-and-flags), the `--quiet` flag has the following meaning:
> Quiet. Display less output. This is particularly useful when displaying output for humans that you might want to hide when running in a script.

I believe we should align with the behavior of `swift package`:
```
  -q, --quiet             Decrease verbosity to only include error output.
```

As for the implementation, we need to add a new [case in the logger](https://github.com/tuist/tuist/blob/main/Sources/TuistSupport/Logging/Logger.swift#L12-L17) for `case quiet`. The implementation should be similar to the `--verbose` flag.

**Comment by mollyIV** [comment]
Hi, I'd like to give it a shot. I created a draft pull request to kick off some implementation discussions:

* https://github.com/tuist/tuist/pull/7010

I'd like to make sure the implementation is heading in the good direction. If it does, the next step is adding unit tests. I'm open to further directions 🙏 

So far, I tested it manually: 

|Without --quiet flag|With --quiet flag|
|----|----|
|<img width="1129" alt="Screenshot 2024-11-07 at 16 20 34" src="https://github.com/user-attachments/assets/17088838-35c4-4742-80df-597df50a57db">|<img width="1128" alt="Screenshot 2024-11-07 at 16 20 52" src="https://github.com/user-attachments/assets/2847efe7-e6d8-49d8-bcbe-6378753f63ae">|
