### ISSUE TITLE
Fix searching in docs

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#6909]
### What happened?

The current search in docs doesn't surface symbols from `ProjectDescription`. If I search for something like `ArchiveAction`, I'd expect the docs search to find it.

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/3de49d93-d2a5-4a03-985b-fa0737da1207">

**Comment by fortmarek** [comment]
Actually, it seems the search in docs is currently completely broken cc @pepicrft

**Comment by pepicrft** [comment]
This one should be fixed now.
