### ISSUE TITLE
Require the TuistConfig.swift file to be in the Tuist directory

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#693]
## Context 🕵️‍♀️
With the introduction of the `Tuist` directory to contain the project description helpers and other global files, I think we should require the `TuistConfig.swift` to be there for consistency reasons.

```
Tuist/
  TuistConfig.swift
  ProjectDescriptionHelpers/
    MyHelper.swift
Projects/
  App/
    Project.swift
```

## What 🌱
I propose the following to avoid this being a breaking change:

- Try to find the TuistConfig using the current logic. If we find it, print a warning letting the users know that the file should be under a Tuist directory.
- Update the init command to generate the `TuistConfig.swift` file under `Tuist/`. 

## Proposal 🎉

> Attach your own proposal _(if you have it)_. We'll discuss in on the issue to find the best one that fits into the library.

**Comment by mollyIV** [comment]
👋 Hope you do not mind, but I started working on it 😊
