### ISSUE TITLE
 mise upgrade --bump fails with error: 404 because of app@x.y.z releases

### ISSUE THREAD

**Issue by ladislas** [tuist/tuist#6938]
### What happened?

We are using mise to setup our development environment in our project. tuist is one of our dependencies.

When we want to upgrade the tools to their latest versions, we use:

```
mise upgrade --bump
```

But it now fails.

The reason is that it tries to download `tuist@app@0.3.3` instead of `tuist@4.31.0`.

### How do we reproduce it?

Setup mise in your project, run `mise upgrade --bump`

### Error log

```shell
mise upgrade --bump
curl: (56) The requested URL returned error: 404
mise ERROR ~/.local/share/mise/plugins/tuist/bin/download failed
* Downloading tuist release app@0.3.3...
curl: (56) The requested URL returned error: 404
asdf-tuist: Could not download https://github.com/tuist/tuist/releases/download/app@0.3.3/tuist.zip
mise ERROR Failed to install tuist@app@0.3.3
mise ERROR ~/.local/share/mise/plugins/tuist/bin/download exited with non-zero status: exit code 1
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

### macOS version

15.0.1

### Tuist version

4.30.0

### Xcode version

15

**Comment by ladislas** [comment]
Yes, it does work if I run `mise plugins update` and then `mise upgrade --bump`

it used to work without it (as far as I can recall). maybe it could be mentioned in the README :)

I'll close the issue. Thanks for your help.

**Comment by adamalix** [comment]
@fortmarek i am having this issue on mise `2025.10.12` after running `mise plugins update`.

should i open a new issue?

**Comment by fortmarek** [comment]
Hey @adamalix 👋 

Can you try to run `mise plugins uninstall tuist` and then `mise install` in the directory with tuist? I tried to reproduce the issue but I was not able to, so that leads me to believe it's still related to the plugin.

**Comment by adamalix** [comment]
that worked perfectly. thanks very much!
