### ISSUE TITLE
Feature Request: --show-progress flag (or similar)

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [tuist/tuist#6948]
### What problem or need do you have?

It would be great to have an option to show a simple progress bar with a % percentage indicator when generating new projects.

As we use tuist for many things inside of [SwiftyLaunch](https://swiftylaun.ch), we would love to be able to extract that value directly from the output, instead of having to manually infer the current state depending on the verbose (--verbose) output.

### macOS version

15.0

### Tuist version

4.31.0

### Xcode version

16.0

**Comment by fortmarek** [comment]
Hey @VladislavSmolyanoy 👋 

As usually with a percentage-based progress, it's difficult to provide an accurate value.

The generation process roughly looks like this:
```
Load project from the manifests -> we generate each Project.swift
```

Once the project is loaded, we have a rough sense of progress if you have multiple projects. Before that happens, it's hard for us to say how much time is left.

Ideally, `tuist generate` is fast enough that you wouldn't need to show a progress bar which is something we're tackling [here](https://community.tuist.io/t/improve-tuists-performance/130). However, on cold runs, we still need to compile the manifests and so there's only so much we can optimize.

> instead of having to manually infer the current state depending on the verbose (--verbose) output.

How does that work currently? Would you mind sharing what kind of UI you surface?

**Comment by fortmarek** [comment]
Hey @VladislavSmolyanoy 👋 

As highlighted [here](https://community.tuist.io/t/small-changes-in-how-we-use-github-issues-at-tuist/192), we no longer track ideas in GitHub.

Would you mind providing a more detailed request in the community forum and we can take it from there? Thanks!
