### ISSUE TITLE
How install group name local packages?

### ISSUE THREAD

**Issue by ct4h** [tuist/tuist#6950]
### What problem or need do you have?

With [XcodeGen](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#local-package) can generate structure local packages

```
Packages
│
└───Common
│   │
│   └───CommonUI
│   └───CommonCore
│   
└───Main
│   │
│   └───FeatureA
│   └───FeatureB
...
```

Tuist generate structure:

```
Packages
│
└───CommonUI
└───CommonCore
└───FeatureA
└───FeatureB
...
```

How configure generate custom folders structure with Tuist?

### macOS version

14.6

### Tuist version

4.31.0

### Xcode version

16.0.0

**Comment by fortmarek** [comment]
Hey @ct4h 👋 

Would you mind flagging this in [our forum](https://community.tuist.io/)? GitHub issues are meant for reporting bugs or tracking clearly-defined work. For troubleshooting, ideas, and questions, the forum is our preferred method of communication.

If you end up creating the post in our forum, it'd help us a lot if you provided more details about your project – primarily, how your local packages is defined. Snippets from your `Project.swift` would be appreciated, a sample that we can play with would be even better.
