### ISSUE TITLE
Glob regression in 4.32.0

### ISSUE THREAD

**Issue by waltflanagan** [tuist/tuist#6966]
### What happened?

Using `.glob("*.swift", excluding: ["*Tests.swift"])` no longer properly excludes files.

### How do we reproduce it?

Repro by using tuist 4.32.0 to generate the `fixture/app_with_alamofire` project in this branch https://github.com/tuist/tuist/tree/waltflanagan/GlobBug

### Error log

<img width="280" alt="image" src="https://github.com/user-attachments/assets/6c3c66b6-c256-4c0c-b3af-cfee5b2ae71c">

### macOS version

15.0

### Tuist version

4.32.0

### Xcode version

16.1

**Comment by alpha-moisol** [comment]
+1, also experiencing this issue
