### ISSUE TITLE
Latest tuist version does not respect Convert To Folder in Xcode 16.1

### ISSUE THREAD

**Issue by jesus-mg-ios** [tuist/tuist#6967]
### What happened?

Xcode 16.1 brings the "convert to folder" feature to reduce the project footprint, and improve diffs in case you git it (not the case using Tuist).

### How do we reproduce it?

Build a project with tuist, click on a group or folder > convert to folder. It does work barely, but when you rebuild a tuist project the work you did, was discarded.

### Error log

.

### macOS version

14.5

### Tuist version

4.31.0

### Xcode version

16.1

**Comment by pepicrft** [comment]
@jesus-mg-ios In Tuist projects, using synchronized file groups is not needed. They aim at solving a problem, frequent git conflicts, which is almost non-existent with Tuist projects. Not only that, but they also add more variables to be resolved at opening time, worsening the DX of working with Xcode projects.
I'd go ahead with closing this issue, which we can open again down the line if we see clear value.

**Comment by rhysm94** [comment]
@pepicrft Sorry to perform issue necromancy, but it relates to your reasoning for closing the issue.
One of the problems I frequently face is having to constantly run `tuist generate` after changing git branch. My assumption is that Xcode Folders wouldn't necessarily require that, as they look at what's on the file system, not what's explicitly added in an xcodeproj file. Having support for this would improve the DX by significantly reducing the number of times I need to fully generate my Tuist project.

**Comment by fortmarek** [comment]
Hey @rhysm94 👋 

Can you flag the feature request at our [forum](https://community.tuist.io/)? If you feel like it, an [RFC](https://community.tuist.io/c/rfc/14) would be welcome as well. We can add support for this, but we need to align on the API in the `ProjectDescription` first.

**Comment by InderKumarRathore** [comment]
@rhysm94 did you create feature request or RFC?
My tuist generate takes around half a minute, I believe with the support of folder (new in xcode 16) it might improve generation

**Comment by fortmarek** [comment]
>  My tuist generate takes around half a minute, I believe with the support of folder (new in xcode 16) it might improve generation

How big is your project? Is the generation time on a cold run (without cache) or on a warm run? If the latter, I'd be surprised if it was 30 seconds. Curious if `tuist generate --no-binary-cache` makes any difference?

That being said, we aligned on bringing synchronized groups as discussed [here](https://community.tuist.dev/t/buildable-folders-support/354), but it'd need to come as a community contribution.

**Comment by InderKumarRathore** [comment]
Without cache, my project is huge. Around 40-50 modules.

**Comment by mihaicris** [comment]
+1 to be able to declare sources as synchronized file groups (folders) instead of SourceFileGlob 

` sources: ["path/Sources1", "path/Sources2"],` 

instead of 

` sources: ["path/Sources1/**", "path/Sources2/**"],`

This is also the default new project template on Xcode 16.3
