### ISSUE TITLE
Xcode 16 recommend to remove "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES"

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#6983]
### What problem or need do you have?

Should we remove "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES" from essential settings as Xcode 16 recommended to remove it?

### macOS version

15.1

### Tuist version

4.31.0

### Xcode version

16.0

**Comment by fortmarek** [comment]
Hey @rowwingman 👋 

We're trying to keep the issues to be only for clearly defined tasks or reproducible bugs. I am moving this discussion to the forum that's better tailored for questions like this: https://community.tuist.io/t/alignment-of-recommended-settings-with-new-xcode-projects/174
