### ISSUE TITLE
Align ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES with the Xcode default

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#6989]
### What problem or need do you have?

See the initial discussion for more context:

When creating a new app with Xcode, the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` value is set to `FALSE`. However, generating a Tuist app with`.recommended` settings sets the value to `TRUE` by default.

### Potential solution

The value should be set to `FALSE`. The value will need to be changed here: https://github.com/tuist/XcodeProj/blob/549ed5445c4c84e45fa6b3f1ff3f56bc94973779/Sources/XcodeProj/Utils/BuildSettingsProvider.swift#L378

**Comment by waltflanagan** [comment]
Should this be `false` specifically or just no longer set so that the Xcode default is used?

**Comment by fortmarek** [comment]
Yes, good point @waltflanagan, we can simply remove setting that value and remove `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` from the recommended settings in `tuist/tuist` 👍

**Comment by yungu0010** [comment]
@waltflanagan @fortmarek 
Hi, I'm trying to solve this problem, but when I created an app with recommended settings
It is well made of ALWAYS_EMBED_SWIFT_STANDARD_LIBRARYS = NO.

Do you mean ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO even if it's watchOS?

This is my Project.swift code and I use tuist version 4.32.1
```swift
import ProjectDescription

let project = Project(
    name: "test",
    settings: Settings.settings(configurations: [.debug(name: "debug"), .release(name: "release")], defaultSettings: .recommended),
    targets: [
        .target(
            name: "test",
            destinations: .iOS,
            product: .app,
            bundleId: "io.tuist.test",
            infoPlist: .extendingDefault(
                with: [
                    "UILaunchScreen": [
                        "UIColorName": "",
                        "UIImageName": "",
                    ],
                ]
            ),
            sources: ["test/Sources/**"],
            resources: ["test/Resources/**"],
            dependencies: []
        ),
        .target(
            name: "testTests",
            destinations: .iOS,
            product: .unitTests,
            bundleId: "io.tuist.testTests",
            infoPlist: .default,
            sources: ["test/Tests/**"],
            resources: [],
            dependencies: [.target(name: "test")]
        ),
    ]
)

```

**Comment by fortmarek** [comment]
> Do you mean ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = NO even if it's watchOS?

Yes, the value is set to `YES` only when the platform is `watchOS` and the product is `application`. Afaict, Xcode keeps the default value to `NO` even with that combination.
