### ISSUE TITLE
Missing .bcsymbolmap files during the rsync stage

### ISSUE THREAD

**Issue by santosdiez** [tuist/tuist#699]
## Context 🕵️‍♀️

After upgrading to the latest version (0.19) we have started facing some issues when trying to compile the project in a different machine from the one where it was generated.

## What 🌱

Due to business needs, our CI machines are still running Xcode 10, but our development machines are already using Xcode 11. Everything has been working well so far, until we upgraded to tuist 0.19.

Since then, the stage where the rsync is performed is failing, complaining about some missing `.bcsymbolmap` files.

`rsync --delete -av --filter P .*.?????? --filter - CVS/ --filter - .svn/ --filter - .git/ --filter - .hg/ --filter - Headers --filter - PrivateHeaders --filter - Modules Carthage/Build/iOS/9B83DAAF-0AC1-3B72-80C1-50B1CBBAF3E5.bcsymbolmap /Users/jenkins/Library/Developer/Xcode/DerivedData/UCClient-cktsttaeoyzyikgpgrcyurnpwjlp/Build/Products/Debug-iphonesimulator
building file list ... 
rsync: link_stat "/Users/jenkins/workspace/ucclient-ios_PR-18/uc-client-ios-app/Carthage/Build/iOS/9B83DAAF-0AC1-3B72-80C1-50B1CBBAF3E5.bcsymbolmap" failed: No such file or directory (2)
done`

Doing some research, we've found out that the command that is being used to generate those UUIDs (`xcrun dwarfdump --uuid`) returns different values depending on the machine (probably because of the Xcode version). Hence, since those values are now hardcoded in the project as part of the `tuist generate` it ends up failing under these circumstances.

## Proposal 🎉

I'll let you choose that 😛

**Comment by kwridan** [comment]
Hi @santosdiez 

Thanks for flagging this. 

As a suggestion you can pin to the previous version in the interim.

`tuist version 0.18.1`

**Comment by kwridan** [comment]
Performing a quick sanity check, the `xcrun dwarfdump --uuid` is stable across Xcode versions

With Xcode 11.2
```
$ xcrun dwarfdump --uuid RxSwift.framework/RxSwift 
UUID: 5208952E-CFC2-30C7-8A7C-42E1FDE4D434 (i386) RxSwift.framework/RxSwift
UUID: BCE500F2-2A0D-3C0E-82D6-302D6E433822 (x86_64) RxSwift.framework/RxSwift
UUID: B0976785-81C1-3C9C-BA2C-B7492D352981 (armv7) RxSwift.framework/RxSwift
UUID: 30DB3409-1251-39B4-87F8-2EF5D7E701DD (arm64) RxSwift.framework/RxSwift
```

With Xcode 10.3:
```
$ xcrun dwarfdump --uuid RxSwift.framework/RxSwift 
UUID: 5208952E-CFC2-30C7-8A7C-42E1FDE4D434 (i386) RxSwift.framework/RxSwift
UUID: BCE500F2-2A0D-3C0E-82D6-302D6E433822 (x86_64) RxSwift.framework/RxSwift
UUID: B0976785-81C1-3C9C-BA2C-B7492D352981 (armv7) RxSwift.framework/RxSwift
UUID: 30DB3409-1251-39B4-87F8-2EF5D7E701DD (arm64) RxSwift.framework/RxSwift
```

When carthage builds those frameworks, it produces slightly different products depending on Xcode versions hence the difference in UUIDs. 

An interesting one to figure out 🤔

**Comment by kwridan** [comment]
One option could be to allow customising the embed command

```swift
enum EmbedCommand {
   case `default`
   case carthage
   case custom(script: String)
}
```

Then in `TuistConfig.swift`

```swift
let config = TuistConfig(
  embedCommand: .carthage
)
```

Under the hood this would apply generate a build phase with:

```
/usr/local/bin/carthage copy-frameworks
```

With: 

Input files:
```
$(SRCROOT)/Carthage/Build/iOS/<FrameworkName>.framework
```

Output files:
```
$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/<FrameworkName>.framework
```

**Comment by santosdiez** [comment]
That last one seems to be a good way to go. The way I see it, those UUIDs cannot be explicitly added to the project, since as we've seen.. those might change.

Given that when using Carthage you are already relying on it, makes sense to add that traditional `copy-frameworks` stage at some point, and leave it all to Carthage, making it much more dynamic.

We will stick to the previous version in the meantime, but will help in any way we can! :)

**Comment by danyf90** [comment]
If it was an issue with carthage, should now be solved with dependencies.swift
