### ISSUE TITLE
Image("some_image") return nil in Widget Extension

### ISSUE THREAD

**Issue by nixzhu** [tuist/tuist#6994]
### What happened?

- With Tuist 4.32.0/4.32.1, in my app's Widget Extension, `Image("some_image")` will return nil.
- Back to Tuist 4.31.0, all good.

### How do we reproduce it?

Update Tuist's version.

### Error log

no log

### macOS version

14.6.1

### Tuist version

4.32.0

### Xcode version

16.1

**Comment by fortmarek** [comment]
Hey @nixzhu

Tuist 3.x.y is no longer supported. I'd recommend upgrading to Tuist 4 and flagging a new issue if the behavior is still not the one you'd expect in the latest Tuist version.

**Comment by nixzhu** [comment]
@fortmarek  Sorry for the incorrect info, I mean 4.32.0/4.32.1 has the bug, 4.31.0 is good.

**Comment by fortmarek** [comment]
@nixzhu can you provide a reproducible sample with reproduction steps?

`Update Tuist's version.` doesn't suffice as "Reproduction steps"

**Comment by nixzhu** [comment]
I have try to make a demo project, but doesn't reproduce this bug for now.

**Comment by nixzhu** [comment]
@dudek-j 

@dudek-j Yes, my Widget Extension's `Media.xcassets` has a trailing `/**`, and I can reproduce it in my demo project.

```swift
            resources: [
                <Redacted>,
                <Redacted>,
                "Widget/Resources/Media.xcassets/**",
                <Redacted>,
                <Redacted>,
            ],
```

**Comment by nixzhu** [comment]
@fortmarek Now the demo project is ready https://github.com/nixzhu/TuistDemo
