### ISSUE TITLE
Wrong redirect_uri for github/google authentication on cloud.tuist.io

### ISSUE THREAD

**Issue by stefanomondino** [tuist/tuist#7015]
### What happened?

Seems like the social login configuration is being set-up for tuist.dev redirect_uri but it's failing for cloud.tuist.io.

This prevents even `tuist auth` from working properly when registering through providers other than emails.

I've looked for other "redirect_uri" issues and didn't find anything, sorry if you are already aware of this.

### How do we reproduce it?

1. go here https://cloud.tuist.io/users/log_in
2. try to authenticate with either Github or Google
3. get an error page
4. do the same on tuist.dev domain and it works

### Error log

![image](https://github.com/user-attachments/assets/882c3839-fdd7-4d73-b6ad-2c2a91224e05)

### macOS version

latest

### Tuist version

latest

### Xcode version

not needed

**Comment by pepicrft** [comment]
Thanks for reporting this @stefanomondino. We are missing a redirect. I'll add it

**Comment by pepicrft** [comment]
I configured the redirect from `https://cloud.tuist.io/*` to `https://tuist.dev/{$1}` so authentication should work now. It might take some time for the proxied DNS record to propagate.
