### ISSUE TITLE
 Host key verification failed.

### ISSUE THREAD

**Issue by Dipak-Makwana** [tuist/tuist#7017]
### What happened?

The 'swift' command exited with error code 1 and message:
Fetching https://github.com/inaka/EventSource.git from cache
warning: 'eventsource': skipping cache due to an error: Couldn’t fetch updates from remote repositories:

### How do we reproduce it?

The 'swift' command exited with error code 1 and message:
Fetching https://github.com/inaka/EventSource.git from cache
warning: 'eventsource': skipping cache due to an error: Couldn’t fetch updates from remote repositories:
    Host key verification failed.
fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.

### Error log

The 'swift' command exited with error code 1 and message:
Fetching https://github.com/inaka/EventSource.git from cache
warning: 'eventsource': skipping cache due to an error: Couldn’t fetch updates from remote repositories:
    Host key verification failed.
fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.

### macOS version

14.7

### Tuist version

4.26.0

### Xcode version

16

**Comment by fortmarek** [comment]
Hey @Dipak-Makwana 👋 

`tuist install` runs `swift package resolve` in the path where your `Package.swift` is located. The error is coming from that command and there's most likely nothing we can do. You should be able to reproduce the issue when running `swift package resolve` and then figure out what's missing. It's most likely connected to authorization with GitHub.

I'm gonna close this as SPM issues are out of scope for Tuist.
