### ISSUE TITLE
Glob patters don't work

### ISSUE THREAD

**Issue by serejahh** [tuist/tuist#7026]
### What happened?

After updating to the latest tuist version, glob patterns stopped working (files are not added)

### How do we reproduce it?

I've created an example project based on [the fixture project](https://github.com/tuist/tuist/tree/main/fixtures/app_with_globs):
[app_with_globs_patterns.zip](https://github.com/user-attachments/files/17687877/app_with_globs_patterns.zip)
You can change tuist version in the mise file

**Actual result** (tuist 4.32+):
- run `tuist generate`
- get the warning:
```
The following warnings need attention:
 · No files found at: .../app_with_globs/App/Configs/*.{entitlements,xcconfig}
```
- entitlements, xcconfig files are not added to the project
<img width="250" alt="image" src="https://github.com/user-attachments/assets/517e58af-6d3a-4ef7-9833-d46e7b7e4b2b">

**Expected result** (worked before tuist 4.32):
- run `tuist generate`
- no warnings
- entitlements, xcconfig files are added to the project
<img width="250" alt="Screenshot 2024-11-09 at 16 04 02" src="https://github.com/user-attachments/assets/133534e3-fb9b-4415-b058-a20ef6845dc3">

### Error log

The following warnings need attention:
 · No files found at: .../app_with_globs/App/Configs/*.{entitlements,xcconfig}

### macOS version

14.7

### Tuist version

4.33.0

### Xcode version

16.0

**Comment by serejahh** [comment]
Could be regression after https://github.com/tuist/tuist/pull/6957. @fortmarek could you have a look please?

**Comment by fortmarek** [comment]
Thanks for reporting, I can confirm this regression.

There's a fix up at: https://github.com/tuist/FileSystem/pull/88. Once merged, we'll follow up with updating `FileSystem` in `tuist/tuist`.

**Comment by Ernest0-Production** [comment]
Yes, I faced the same problem and started a similar issue before I came across this one.

https://github.com/tuist/tuist/issues/7051

**Comment by ilia3546** [comment]
Same here +1
