### ISSUE TITLE
`mise install` fails to install `sourcedocs`

### ISSUE THREAD

**Issue by danieleformichelli** [tuist/tuist#7029]
### What happened?

The `mise install` command fails to install `sourcedocs`.
Running `mise plugins update` doesn't help.
It looks like the release is actually not present on GitHub: https://github.com/SourceDocs/SourceDocs/releases/tag/2.0.2

### How do we reproduce it?

Run `mise install`

### Error log

mise install
curl: (56) The requested URL returned error: 404
mise ERROR ~/.local/share/mise/plugins/sourcedocs/bin/download failed
* Downloading sourcedocs release 2.0.2...
curl: (56) The requested URL returned error: 404
asdf-sourcedocs: Could not download https://github.com/SourceDocs/SourceDocs/archive/refs/tags/2.0.2.zip
mise ERROR Failed to install sourcedocs@2.0.2
mise ERROR ~/.local/share/mise/plugins/sourcedocs/bin/download exited with non-zero status: exit code 1
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information

### macOS version

15.1

### Tuist version

3.41

### Xcode version

16

**Comment by fortmarek** [comment]
Hey 👋 

The release is at: https://github.com/tuist/SourceDocs/releases/tag/2.0.2

We are depending on a fork at the original `SourceDocs` repo doesn't support Xcode 16. Given CI successfully installs the dependency, there must be something cached on your machine.

I'd try purging any mise-related cache or outright reinstall it. There's not a lot we can do in `tuist/tuist` directly, so I'm closing this one.
