### ISSUE TITLE
`tuist run PREVIEW_URL` not finding Tuist credentials

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#7044]
### What happened?

I built with `tuist build App`:

```
Build Succeeded
The project built successfully
```

I then uploaded a preview with `tuist share App`:

```
Uploading App...
App uploaded – share it with others using the following link: https://tuist.dev/REDACTED
```

But when I run with `tuist run https://tuist.dev/REDACTED` I get:

```
No valid Tuist credentials found. Authenticate by running `tuist auth`.
```

I run `tuist auth` successfully and try again, same result.

### How do we reproduce it?

Try the above steps with an app using Tuist Server.

### Error log

```
No valid Tuist credentials found. Authenticate by running `tuist auth`.
```

### macOS version

15.1

### Tuist version

4.33.0

### Xcode version

16.0

**Comment by hiltonc** [comment]
Just tried with the macOS app, getting this error:

```
Client error - cause description: 'Middleware of type 'ServerClientAuthenticationMiddleware' threw an error.', underlying error: The operation couldn’t be completed. (TuistServer.ServerClientAuthenticationError error 0.), operationID: downloadPreview, operationInput: Input(path: TuistServer.Operations.downloadPreview.Input.Path(account_handle: "ORG", project_handle: "PROJECT", preview_id: "REDACTED"), headers: TuistServer.Operations.downloadPreview.Input.Headers(accept: [OpenAPIRuntime.AcceptHeaderContentType<TuistServer.Operations.downloadPreview.AcceptableContentType>(contentType: TuistServer.Operations.downloadPreview.AcceptableContentType.json, quality: OpenAPIRuntime.QualityValue(thousands: 1000))])), request: GET /api/projects/ORG/PROJECT/previews/REDACTED [accept: application/json], requestBody: <nil>, baseURL: https://tuist.dev, response: <nil>, responseBody: <nil>
```

**Comment by fortmarek** [comment]
Hey @hiltonc 👋 

Can you provide a reproducible sample?

I just ran the same commands in [this fixture](https://github.com/tuist/tuist/tree/main/fixtures/ios_app_with_frameworks) and both running the app using the `tuist run` command and the macOS app works. For the macOS app, make sure you're on the latest version (`0.5.1`)

**Comment by hiltonc** [comment]
@fortmarek this works correctly with the Tuist 4.34.0 and app 0.5.1. Thank you!
