### ISSUE TITLE
Header improvements

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#705]
# Overview

Devising glob patterns for headers in existing projects with Objective-C / C++ code can be quite challenging as there isn't a standardised convention to distinguish which headers are public, private, project or even completely excluded.

In projects, it's also not uncommon to have headers with no visibility attributes what so ever (e.g. Application and Test targets - #367)

# Suggestion
Here are a few suggestions (they don't have to be all applied together)

## Excluded
Introduce an `excluded` header property 

`excluded`: Completely excluded from the headers of this target

e.g.:
`resolvedPublicHeaders = public - excluded`
`resolvedPrivateHeaders = private - excluded`
`resolvedProjectHeaders = project - excluded`

## Included 
Introduce an `included ` header property 

`included`: Specified headers are included as file references without being assigned any header visibility attributes (i.e. not part of the headers build phase)

This can be somewhat confusing though

## Header Resolution Rules

Tweak the header resolution rules such that:
`resolvedPublicHeaders = public - excluded`
`resolvedPrivateHeaders = private - public - excluded`
`resolvedProjectHeaders = project - private - public - excluded`

e.g.
```swift
Headers(public: ["Sources/MyAPI/MyAPI.h"]
           private: ["Sources/MyAPI/**"],
          project: ["Sources/**"],
         excluded: ["Sources/MyAPIMocks/**"])
```

- `MyAPI.h` will be the only public header
- All other headers in `MyAPI` will be marked as private
- All other headers will be marked as `project`
- Lastly, anything under`MyAPIMocks` won't appear in this target's headers/references at all

# Alternates

- Implement #367 to allow Tuist to automatically manage omitting headers build phase for targets that don't require it
- Restructure the project to have clearer distinctions between the different visibility's (public / private / project / excluded)

# Reference

- Various discussions on slack
- _Originally posted by @rowwingman in https://github.com/tuist/tuist/issues/367#issuecomment-557896103_

**Comment by rowwingman** [comment]
I believe, that exclude something from each type of header is more flexible. You can have different structure of your project. So in this way what you can:
```
let project = ["Sources/Project/**"]
let private = ["Sources/Private/**"]
Headers(public: ["Sources/** "] - project - private,
           private: [private],
          project: [project])
```

We can create a new struct that will describe what you want to include: 
`Header(path: Path, exclude: [Path])`, the same problem can be for the `sources`. Maybe it should be something more generic, however for more generic, I don't know the proper name

**Comment by pepibumur** [comment]
Thanks for taking the discussion ton an issue.

If what we are trying to solve is [this](https://github.com/tuist/tuist/issues/367), I believe we should not complicate the API because the solution can come down to not adding a headers build phase if the target is an application.

The way I see adding a `exclude` argument is something like: Hey, I know the organization of the headers in directories is messed up, let me give you some options for you express that mess, and problem solved. What that means too is that it'll be harder to reason about the headers that belong to a target. 

I'm more inclined to keep this as a restrictions that encourages developers to re-think their headers structure.

**Comment by rowwingman** [comment]
There is always a debut about how what is the best struct of a project.
First, all the discussion is relevant only for objc.
Let me give you some examples.
1).  `Bridging-Header` It's should be in `Sources` folder or `Sources-Project`. In my opinion both works.
2). You are building a framework on objc, and for example, you will write something similar to NSNumber (class cluster), what is the best place for your internal implementation close to the public implementation or in separate `Source-Project`. I think it's better to place it close to implementation. So you usually will mark these files with some suffix.

So I think it will be nice to have excluded not only by folder by some regex too. For example `exclude: "/**/*-Project.[hm]"`

The same exclude rules works for Bazel and BUCK build systems

**Comment by pepibumur** [comment]
> So I think it will be nice to have excluded not only by folder by some regex too. For example exclude: "/**/*-Project.[hm]"

Glob expressions [should be supported](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/FileList.swift#L3) by headers. Isn't that enough to express public, project, and private headers?

**Comment by kwridan** [comment]
Worth considering the `exclude` for headers and sources together (brought up in #808) to ensure the API is consistent.

**Comment by pepibumur** [comment]
> Worth considering the exclude for headers and sources together (brought up in #808) to ensure the API is consistent.

Agree. We should apply the exclude API to all the models that define a list of files.

**Comment by vytis** [comment]
> Agree. We should apply the exclude API to all the models that define a list of files.

So which places would this be? I found `FileElement` and `FileList`? Or there are some others that should be extended in a similar way?

**Comment by pepibumur** [comment]
> So which places would this be? I found FileElement and FileList? Or there are some others that should be extended in a similar way?

Those should be enough. It might be worth evaluating whether it makes sense to merge some of them as part of this effort. What do you think @vytis ?

**Comment by vytis** [comment]
Yeah it seems there is a different struct for each use case. How do you feel about changing the types in ProjectDescription? It seems like a breaking change...

**Comment by pepibumur** [comment]
> How do you feel about changing the types in ProjectDescription? It seems like a breaking change...

I'd figure out if there's a way to do the merge without introducing a breaking change. It might not be possible though, in which case, I'd avoid adding the breaking change and rather, open an issue to tackle this before the next major version. What do you think?

**Comment by vytis** [comment]
Agree that it's not worth making changes like this without careful consideration. I will try to figure something out, maybe it would be possible to factor out some of the functionality in a single place.
