### ISSUE TITLE
False positive "side effects" warnings when using Swift macros and binary cache

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#7050]
### What happened?

I'm getting "static side effects" warnings that are false positives in my project as a result of using Swift Macros and the binary cache. It looks like a regression of https://github.com/tuist/tuist/issues/6209 when using the binary cache.

### How do we reproduce it?

1. Unzip [repro.zip](https://github.com/user-attachments/files/17738312/repro.zip)
2. Run these commands:

```bash
tuist install
tuist generate
tuist cache
tuist generate
```

### Error log

```
The following warnings need attention:
 · Xcframework 'SwiftCompilerPlugin.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftSyntax509.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftSyntaxBuilder.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftUINavigationCore.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftSyntaxMacros.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftSyntax.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftParser.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftDiagnostics.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftBasicFormat.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftSyntaxMacroExpansion.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftParserDiagnostics.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftOperators.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
 · Xcframework 'SwiftCompilerPluginMessageHandling.xcframework' has been linked from target 'Framework' and target 'Framework2', it is a static product so may introduce unwanted side effects.
```

### macOS version

15.1

### Tuist version

4.34.0

### Xcode version

16.0

**Comment by kelvinharron** [comment]
Hey @hiltonc did you get any feedback on this one? We've seen it on and off throughout our time with Tuist Cloud since May time. Treating `SwiftSyntax` or any of the explicit xcframeworks as dynamic frameworks doesn't change anything in my experience. @fortmarek do you have any guidance around this? I understand SwiftSyntax can be particular challenging to deal with!

**Comment by hiltonc** [comment]
@kelvinharron No feedback yet. This is masking real warnings for us. I've similarly tried treating them as dynamic frameworks but it didn't help.

**Comment by fortmarek** [comment]
> It looks like a regression of https://github.com/tuist/tuist/issues/6209 when using the binary cache.

I don't think it's a regression per se. The PR that fixed the issue only handled the scenario when you have actual targets – with cache, you end up having xcframeworks instead.

I think this is closely related to: https://github.com/tuist/tuist/issues/6841

I believe what we can do here is to lint static products on the `initialGraph` and assume that our logic is correct. I'm gonna play with that.
