### ISSUE TITLE
4.34.0 breaks -package-name flag to the linker

### ISSUE THREAD

**Issue by shahzadmajeed** [tuist/tuist#7052]
### What happened?

4.32.1 builds fine but on 4.34.0 I see following errors

![image](https://github.com/user-attachments/assets/e6b0aa6d-fd65-45cb-a755-50ccaf714b64)

### How do we reproduce it?

1. Use add dependency on a swift package that uses `package` access modifier
2. On tuist 4.34.0
3. tuist install & tuist generate
4. build

### Error log

See screenshot

### macOS version

14.0

### Tuist version

4.34.0

### Xcode version

15.4

**Comment by Ernest0-Production** [comment]
Have you changed the target settings in PackageSettings? If yes, then you should explicitly write $(inherited) in the redefined linker settings to prevent overwriting the default SPM settings.

**Comment by fortmarek** [comment]
I can confirm that `-package-name` is still set in our fixtures, such as `app_with_composable_architecture`. @shahzadmajeed, can you provide a reproducible sample? It's quite likely connected to your custom settings, as @Ernest0-Production raised.

**Comment by shahzadmajeed** [comment]
I changed nothing in my project but updated the Tuist version from 4.32.1 to 4.34.0. The previous version 4.32.1 was working fine. I can take a look at the settings.

**Comment by shahzadmajeed** [comment]
I checked I am overriding `targetSettings` for 2 dependency targets from a Swift Package that uses `package` modifier. The error remains after adding $(inherited) to both targets. Reverting back to 4.32.1 fixes the error. I will try to create a sample project later in the week

**Comment by fortmarek** [comment]
Thanks, a reproducer will be really helpful here 🙏

**Comment by vvisionnn** [comment]
should be the same error
```
Tuist/.build/checkouts/swift-navigation/Sources/SwiftNavigation/Internal/HashableStaticString.swift:1:1: the package access level used on 'HashableStaticString' requires a package name; set it with the compiler flag -package-name
```
upgrade from 4.30.0 to 4.36.0
not sure how this happens but I tried the `fixture/app_with_composable_architecture`, no error raised
I didn't change anything but just upgraded the version inside `.mise.toml`

**Comment by fortmarek** [comment]
Can you try adding the following to the `PackageSettings.targetSettings` in your `Tuist/Package.swift`:
```swift
 "SwiftNavigation": [
                    "OTHER_SWIFT_FLAGS": .array([
                        "$(inherited)",
                        "-package-name",
                        "swift-navigation"
                    ]),
                ]
              ]
```

If you could provide a repro sample, that'd be amazing. We have changed how settings are resolved, but without a reproducer, it's tough for us to come up with a fix (or guidance in case we don't consider that a regression but a minor change of behavior)

**Comment by vvisionnn** [comment]
confirmed, both build and cache works like normal after adding the lines above

yeah normally I will attach a repro project but this one I tried it just ok if I add the TCA as dependency for a new created project
I tried re-clone my project and `git clean -ffxd` before, both failed to build with error

**Comment by kamilpowalowski** [comment]
I also encountered this problem after updating SwiftNavigation to 2.2.2 and tuist to 4.37.0
@fortmarek response helped, but with then note that target settings should look like this:
```swift
        targetSettings: [
            "SwiftNavigation": .settings(
                base: [
                    "OTHER_SWIFT_FLAGS": .array(
                        [
                            "$(inherited)",
                            "-package-name",
                            "swift-navigation"
                        ]
                    )
                ]
            )
        ]
```
Because the provided version is deprecated (btw with a very confusing typo) https://github.com/tuist/tuist/blob/f6aa7f1a68c38c59592ab053150ed5c14eed1308/Sources/ProjectDescription/PackageSettings.swift#L79
