### ISSUE TITLE
Versioned CoreData models are breaking build 

### ISSUE THREAD

**Issue by danibachar** [tuist/tuist#7067]
### What happened?

This bug is probably somehow related to the hidden files change that was made (also referenced in here - https://github.com/tuist/tuist/issues/7064).

I know this is not the best way to integration CoreData models with Tuist, but it used to work, and thus this is a degradation in Tuist behaviour.

CoreData models can be versioned for migration, where a hidden file `.xccurrentversion` file is attached to the model and define which version it should use.

When this file is added (basically any hidden file within the Model definition would have that affect) - xcode fails to process the model and it is not accessible through the bundle.

Attached an example project see steps to reproduce - [tuist-core-data.zip](https://github.com/user-attachments/files/17782245/tuist-core-data.zip)

### How do we reproduce it?

1) Use Tuist 4.33.0 - 
2) Download the example project
3) unzip
4) cd into the folder
5) Run `tuist install && tuist generate`
6) Run the test, and see it crash due to the missing files

*Note the warning about processing some xml file

7) Switch to Tuist 4.26.0
8) Repeat steps 4-6, and see the test pass

*Note the warning will not appear

### Error log

See crash

### macOS version

14.7.1

### Tuist version

4.33.0

### Xcode version

15.4

**Comment by danibachar** [comment]
Similar to the other issue, this bug can be solved by changing the `additionalFiles` in the project definitions.
And we are facing the same limitation of explicit needing to mention all the filess.

Would the maintainers be open to extend the capabilities of `FileElement`?

**Comment by fortmarek** [comment]
> Would the maintainers be open to extend the capabilities of FileElement?

As I mentioned in the other issue, yes, we would 🙂 

I'm gonna close this as a duplicate as this boils down to the same issue.
