### ISSUE TITLE
Failing to upload selective tests

### ISSUE THREAD

**Issue by hiltonc** [tuist/tuist#7068]
### What happened?

We've been a seeing a lot of 500s lately when uploading selective tests. This (1) fails our CI build (even though the tests succeeded) and (2) means we have to run the tests again the next time. It sometimes works after a retry.

### How do we reproduce it?

```
export TUIST_TEST_DEVICE="iPhone 16 Pro"
export TUIST_TEST_OS=18.0
export TUIST_TEST_RESULT_BUNDLE_PATH=output/tests.xcresult

# Work around for CircleCI PR handling in Tuist 4.34.0
export CIRCLE_PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}

tuist test RequiredTests \
  -- \
  -derivedDataPath build \
  -retry-tests-on-failure \
  -test-iterations 3 \
  CODE_SIGN_IDENTITY='' \
  CODE_SIGNING_REQUIRED='NO' \
  CODE_SIGN_ENTITLEMENTS='' \
  CODE_SIGNING_ALLOWED='NO'
```

### Error log

After successful build and tests:

```
Storing remote selectiveTests. Hold tight...
You can view a detailed report at: https://tuist.dev/acorns/ios/runs/616099
The cache item could not be uploaded due to an unknown Tuist response of 500.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

### macOS version

14.6.1

### Tuist version

4.34.3

### Xcode version

16.0

**Comment by fortmarek** [comment]
Hey @hiltonc 👋 

this should be fixed now. Let us know if you run into this again.

We will also soon implement a change, so your CI pipelines don't fail when the Tuist server returns a 5xx response: https://github.com/tuist/tuist/issues/7039

**Comment by hiltonc** [comment]
Still getting this error:

```
You can view a detailed report at: https://tuist.dev/acorns/ios/runs/617817
The cache item could not be uploaded due to an unknown Tuist response of 500.
```

**Comment by hiltonc** [comment]
Appears to be resolved now. Thank you!
