### ISSUE TITLE
TestAction has Testability instead of targets

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#707]
## Need/problem

Add options to test target in test action:
*  Execute in parallel
* Randomize execution order

<img width="345" alt="Screenshot 2019-11-24 at 21 57 01" src="https://user-images.githubusercontent.com/351837/69501450-5bf11200-0f05-11ea-9d66-a50ee52720c6.png">

## Motivation

Configurate each test target with options (Execute in parallel and Randomize execution order).

## Detailed design

`TestAction` has `targets: [String]` I propose to change it to next:
```
TestAction {
    tests: [Testable]
    ...
}

struct Testable {
    let target: String
    let isParallelizable: Bool
   let isRandomExecutionOrdering: Bool
}
```
This change can you allow to provide test options for each specific target, by default when will be false.

Reference:
*  https://github.com/tuist/tuist/issues/667

**Comment by rowwingman** [comment]
Quick prototype of the API https://github.com/rowwingman/tuist/commit/dd34bd234f096e77b7b5c374289952c58642c21a

**Comment by pepibumur** [comment]
This features is reasonable, thanks for bringing it up @rowwingman. Would you mind opening a PR with the API proposal? I had a look at it and it looks good to me.

**Comment by rowwingman** [comment]
@pepibumur Yes, sure. I just need some help with naming.
Not sure that `tests: [Testable]` tests, is good, can be misleading.
I'm also not sure with `Testable`. So if you can suggest better naming, that will be nice

**Comment by pepibumur** [comment]
I'd not change the name because it's a breaking change. Unless you believe the current name is very misleading in which case we can introduce a new attribute but with a deprecation strategy in place.

**Comment by rowwingman** [comment]
What is the reason to have the same classes with the same semantic in `ProjectDescription` and `TuistCore`?

**Comment by pepibumur** [comment]
> What is the reason to have the same classes with the same semantic in ProjectDescription and TuistCore?

There are a few reasons:
- The models in `ProjectDescription` are specific to Tuist; that allows developers reusing the generation logic providing their own models. That's what Bloomberg is doing (cc @kwridan)
- We can keep the models in the `ProjectDescription` very lean while adding convenience methods and some other features to the models in `TuistCore`. One of those features for instance is the unfolding of the glob paths into a list of paths. 
- It makes it easier to reason what's the public interface that we are exposing to the users.
