### ISSUE TITLE
Tuist not honoring `when` condition for external dependency's swiftSettings

### ISSUE THREAD

**Issue by lilidotshi** [tuist/tuist#7076]
### What happened?
The `when` condition seems to be generating incorrectly for SPM dependencies.

Using RevenueCat's Package.swift as an example, they define this particular setting:
`let visionOSSetting: SwiftSetting = .define("VISION_OS", .when(platforms: [.visionOS]))`

and set it as a custom SwiftSetting within its target:

```
.target(name: "RevenueCat",
                path: "Sources",
                exclude: ["Info.plist", "LocalReceiptParsing/ReceiptParser-only-files"],
                resources: [
                    .copy("../Sources/PrivacyInfo.xcprivacy")
                ],
                swiftSettings: [visionOSSetting] + ciCompilerFlags + additionalCompilerFlags),
```

|4.33.0|4.34.0|
|-|-|
|![Screenshot 2024-11-20 at 9 23 01 AM](https://github.com/user-attachments/assets/939af14c-1ac2-4014-abf6-ba6d175ed566)|![Screenshot 2024-11-20 at 9 24 02 AM](https://github.com/user-attachments/assets/ea793228-2969-4709-afe5-5dcf3efc56f3)|

### How do we reproduce it?

Easiest way to see this is just to add RevenueCat as an external dependency, and generate a project. Note that the custom setting does not honor the `when(platforms[.visionOS])`. 

### Error log

Because the flag `VISION_OS` is not correctly set on the proper sdk (vision or any vision simulator), builds targeting a version lower than 17.0 will fail, even when building to a non-vision-os simulator.

### macOS version

15.1

### Tuist version

4.34.3

### Xcode version

16.1

**Comment by vvisionnn** [comment]
found same error when using revenuecat package, detail like below
while I selecting **iphone/ipad** target, but the VISION_OS check activated

<img width="914" alt="image" src="https://github.com/user-attachments/assets/9c8b0de8-cb6f-40c5-82d5-b5760a650f2b">

**Comment by vvisionnn** [comment]
confirmed 4.33.0 is ok

**Comment by lilidotshi** [comment]
> confirmed 4.33.0 is ok

I believe this was the PR that updated the package settings: https://github.com/tuist/tuist/pull/7009
cc @Ernest0-Production

**Comment by lilidotshi** [comment]
Current work around for me, since the only thing that RevenueCat seems to be adding to the flag is `VISION_OS` is to put add this line in PackageSettings to overwrite it:

`targetSettings: ["RevenueCat": .settings(base: ["SWIFT_ACTIVE_COMPILATION_CONDITIONS": "$(inherited)"])]`

**Comment by lilidotshi** [comment]
Also, just in searching, it looks like the dependency here might be out of date:
https://github.com/tuist/tuist/blob/main/fixtures/ios_app_with_spm_dependencies/Tuist/Package.swift
```
        // Has custom `swiftSettings` and uses the package access level
        .package(url: "https://github.com/vapor/jwt-kit.git", .upToNextMajor(from: "5.0.0-beta.2.1")),
```

jwt kit doesn't seem to have custom swiftSettings

**Comment by fortmarek** [comment]
Hey, folks 👋 

I can confirm this is an issue. I'm looking into it.
