### ISSUE TITLE
Flag to disable caching Manifests due Project generation

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#7084]
### Why is this needed?

We have encountered a problem with unnecessary manifest caching on CI.
Because each build on CI has a new directory/workspace and environment variables -> the necessary manifest cache is always missing in `~/.cache/tuist` directory -> manifests are always compiled -> the cache is stored in `~/.cache/tuist` and gradually grows.

I know that the cache directory can be overridden using the environment variable `XDG_CACHE_HOME`, but we do not want to disable the entire cache. We still need to share the dependency cache.

### Steps to address the need

A new flag `--no-manifests-cache` could be added, which would not cache `Manifests` and `ProjectDescriptionHelpers` when generating a project:
```
tuist generate --no-manifests-cache
```

**Comment by fortmarek** [comment]
hey @Ernest0-Production 👋 

You can run `tuist clean manifests` to clean the manifests cache. I lean against adding a dedicated flag for ignoring the manifests cache.

Note GitHub issues are not meant for flagging ideas as described [here](https://community.tuist.io/c/ideas/7). I'd suggest using the [community forum](https://community.tuist.io/c/ideas/7). If you wanna continue the conversation, I'd recommend moving it there.
