### ISSUE TITLE
Access to absolute path for TargetScript

### ISSUE THREAD

**Issue by Ernest0-Production** [tuist/tuist#7086]
### Why is this needed?

In Build Phase scripts there is a need to understand in which directory the Workspace is located. 
There is no way to find out this directory using Xcode's built-in environment variables, as far as I know. (`SRCROOT` is the .xcodeproj directory of the project, not the workspace)

### Steps to address the need

Add an extension to `Path` to get the path to absolute and relative paths:
```
// Users/<username>/my-project/
Path.rootDirectory.absoluteString 

// ./
Path.rootDirectory.relativeString

// Users/<username>/my-project/Modules/Core/
Path.manifestDirectory.absoluteString

// ./Modules/Core/
Path.manifestDirectory.relativeString

// ./Modules/Core/Resources/Foo.strings
// Path.relativeToManifest("Resources/Foo.strings").relativeString
```

**Comment by fortmarek** [comment]
> In Build Phase scripts there is a need to understand in which directory the Workspace is located.

Is there? Could you describe what the need actually is and why you can't use the `Path` absolute paths?

As mentioned [here](https://github.com/tuist/tuist/issues/7084#issuecomment-2491083346), I'd suggest using a community forum for suggestions like this. That helps us to keep GitHub issues actionable and makes it easier to prioritize our work, thanks for your understanding 🙏
