### ISSUE TITLE
error: no such module 'CompilerPluginSupport' when performing `tuist fetch` command

### ISSUE THREAD

**Issue by BlueRamp** [tuist/tuist#7125]
### What happened?

When performing `tuist fetch` command, `error: no such module 'CompilerPluginSupport'` returned in macOS Terminal

### How do we reproduce it?

I cannot provide sample project, since it is commercial and under NDA.

1. Clone project via Xcode 15.2;
2. Via Terminal perform `sh ./scripts/code_smell/lint_errors_full.sh` in root directory of the project;
3. Perform `tuist fetch` in the Tuist Workspace directory of the project.

### Error log

error: no such module 'CompilerPluginSupport'
import CompilerPluginSupport
       ^ in https://github.com/pointfreeco/swift-dependencies
The 'swift' command exited with error code 1

### macOS version

14.4

### Tuist version

3.42.2

### Xcode version

15.2

**Comment by fortmarek** [comment]
Hey @BlueRamp 👋 

Tuist 3.x is no longer supported – we recommend migrating to v4. You can find guidance how to do that [here](https://docs.tuist.dev/en/references/migrations/from-v3-to-v4#from-tuist-v3-to-v4). If the issue persists in the latest version, I'd recommend opening a new issue with a reproducible sample.

**Comment by BlueRamp** [comment]
Hi @fortmarek 
Unfortunately migration to Tuist v.4 is not observable for our project. Here is how I resolved this issue if somebody will run into the same, just try performing this command in console: `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`
