### ISSUE TITLE
Binary cache ignored on CI

### ISSUE THREAD

**Issue by sergeykhliustin** [tuist/tuist#7128]
### What happened?

We are using bitrise with base setup for running tests on each PR.
Workflow configured to cache `~/.cache` and `Tuist/.build` directories and it runs `tuist cache` before `tuist tests`.
But I can see that it rebuilds cache on each run.
Checking via remote access, I can see that cache was restored successfully in both directories.
Am I missing something or this is an issue?

### How do we reproduce it?

CI only issue/question

### Error log

no log

### macOS version

15.1

### Tuist version

4.36.0

### Xcode version

16.1

**Comment by fortmarek** [comment]
Hey @sergeykhliustin 👋 

This is expected – you need to go through the Tuist server to reuse binaries across machines. You will need to first create a [Tuist project](https://docs.tuist.dev/en/server/introduction/accounts-and-projects#projects) and then set up a `TUIST_CONFIG_TOKEN` on your CI: https://docs.tuist.dev/en/guides/quick-start/optimize-workflows#optimizations-on-ci
