### ISSUE TITLE
Should we consider using 'Optimize for Mac' as the default setting for the Mac Catalyst interface?

### ISSUE THREAD

**Issue by foyoodo** [tuist/tuist#7146]
### Why is this needed?

iPadOS 18 introduces new API for creating tab bars. When `UITabBarController.Mode` is set to `.sidebar`, `UINavigationController` on Mac Catalyst behaves unexpectedly during navigation. However, when we set the Mac Catalyst interface to 'Optimize for Mac', the behavior of `UINavigationController` returns to normal.

I believe this change doesn’t negatively impact consumers. If they prefer using the ‘Scaled to Match iPad’ option, they can simply continue using ‘Designed for iPad’ as the destination.

### Steps to address the need

https://github.com/tuist/tuist/blob/760b72333d7f7203da44aac97f5f319fc134adbd/Sources/TuistGenerator/Generator/ConfigGenerator.swift#L318-L327

```diff
        var deviceFamilyValues: [Int] = []
        if target.destinations.contains(.iPhone) { deviceFamilyValues.append(1) }
        if target.destinations.contains(.iPad) { deviceFamilyValues.append(2) }
        if target.destinations.contains(.appleTv) { deviceFamilyValues.append(3) }
        if target.destinations.contains(.appleWatch) { deviceFamilyValues.append(4) }
+       if target.destinations.contains(.macCatalyst) { deviceFamilyValues.append(6) }
        if target.destinations.contains(.appleVision) { deviceFamilyValues.append(7) }

        if !deviceFamilyValues.isEmpty {
            settings["TARGETED_DEVICE_FAMILY"] = .string(deviceFamilyValues.map { "\($0)" }.joined(separator: ","))
        }
```

**Comment by fortmarek** [comment]
I'm onboard with this 👍 

Would you be up to open the PR, @foyoodo?

Btw, do we know what's the platform with raw value of 5?
```
 if target.destinations.contains(.appleWatch) { deviceFamilyValues.append(4) }
 // What should be here? 
 if target.destinations.contains(.macCatalyst) { deviceFamilyValues.append(6) }
 if target.destinations.contains(.appleVision) { deviceFamilyValues.append(7) } 
```

**Comment by foyoodo** [comment]
> I'm onboard with this 👍
> 
> Would you be up to open the PR, @foyoodo?
> 
> Btw, do we know what's the platform with raw value of 5?
> 
> ```
>  if target.destinations.contains(.appleWatch) { deviceFamilyValues.append(4) }
>  // What should/could be here? 
>  if target.destinations.contains(.macCatalyst) { deviceFamilyValues.append(6) }
>  if target.destinations.contains(.appleVision) { deviceFamilyValues.append(7) } 
> ```

Sure, happy to do that!

I couldn’t find any reference to the platform with a raw value of 5 in the [documentation](https://developer.apple.com/documentation/xcode/build-settings-reference#Targeted-Device-Families). Some suggest it represents HomePod, we probably don’t need to account for it.

**Comment by fortmarek** [comment]
> Sure, happy to do that!

Amazing 🎉 

> I couldn’t find any reference to the platform with a raw value of 5 in the [documentation](https://developer.apple.com/documentation/xcode/build-settings-reference#Targeted-Device-Families). Some suggest it represents HomePod, we probably don’t need to account for it.

Got it, was just curious :)
