### ISSUE TITLE
Typo in deprecated message "PackageSettings.init(productTypes:productDescrtiptions:baseSettings:targetSettings:projectOptions:)"

### ISSUE THREAD

**Issue by nathansalaun-sofia** [tuist/tuist#7178]
### Why is this needed?

When using the deprecated `PackageSettings` init, Xcode proposes to use the new one instead. 

Since there is a typo in `init(productTypes:productDescrtiptions:baseSettings:targetSettings:projectOptions:)` ("descrtiptions"), it can't find the new init.

### Steps to address the need

Fix the typo in the `@available` annotation.

**Comment by fortmarek** [comment]
Hey! Thanks for raising the issue.

Would you be up to open a PR? 😌
