### ISSUE TITLE
Experimental/Upcoming Features: Missing documentation

### ISSUE THREAD

**Issue by ltns35** [tuist/tuist#7179]
### What happened?

The documentation is missing how to enable experimental/upcoming features.

### How do we reproduce it?

Open the documentation

### Error log

No

### macOS version

15

### Tuist version

4.38.1

### Xcode version

16

**Comment by ltns35** [comment]
I want to be able to set those features in the project settings instead of the package.  Using the following configuration doesn't work when I try to compile the project.

```swift
.otherSwiftFlags([
   "-enable-upcoming-features MemberImportVisibility",
   "-enable-upcoming-features ExistentialAny",
   "-enable-upcoming-features InferSendableFromCaptures"
])
```

**Comment by fortmarek** [comment]
Hey @ltns35 👋 

Have you tried setting the features as such:
```swift
.otherSwiftFlags([
   "-enable-upcoming-features", "MemberImportVisibility",
   "-enable-upcoming-features", "ExistentialAny",
   "-enable-upcoming-features", "InferSendableFromCaptures"
])
```

You can inspect the `OTHER_SWIFT_FLAGS` option in the generated Xcode project and see if it's set to a value you'd expect.

That being said, this doesn't look like a bug. For troubleshooting, use our forum instead: https://community.tuist.dev/c/troubleshooting-how-to/6. If you need further help, let's move the conversation there.
