### ISSUE TITLE
Generation Assets fails with latest version 4.38.1 

### ISSUE THREAD

**Issue by smartreux** [tuist/tuist#7180]
### What happened?

The stencil seems to create an extension of asset but it won't work if you have your assets inside folder 🤔 

### How do we reproduce it?

1. Create assets image
2. Add image inside folder
3. tuist generate

### Error log

Assets.[Without folder].image not found :) 

### macOS version

15.2

### Tuist version

4.38.1

### Xcode version

16.2

**Comment by jayn2u** [comment]
Same issue happens...

**Comment by smartreux** [comment]
Hello, this issue does not happens on earlier version, we have to fallback to 4.37.0 , I think it's a new regression 

In my case, it's when you have a folder inside xassets image, in the latest version 
<img width="117" alt="Capture d’écran 2024-12-23 à 10 10 20" src="https://github.com/user-attachments/assets/43990d8c-a730-4872-b584-4b0cd96ec1c1" />

https://github.com/tuist/tuist/pull/7162/files I think there is something wrong in the modification of the stencil 

A new extension is generated but without the namespace of the folder

**Comment by pepicrft** [comment]
We are [reverting](https://github.com/tuist/tuist/pull/7192) a recent change that caused this issue and we'll do a hot-fix release.

**Comment by pepicrft** [comment]
A fix for this should be available in 4.38.2.
