### ISSUE TITLE
As a developer I want to have different levels of logging

### ISSUE THREAD

**Issue by adri4silva** [tuist/tuist#784]
## Need/problem

Right now Tuist doesn't support logging. 

## Motivation

As a developer I want to configure the logs that Tuist throws.

## Possible result

When executing tuist generate by default the logs could be only blocking errors. We can implement a verbose solution like `tuist generate -v` to print all the logs.

**Comment by pepibumur** [comment]
@ollieatkinson is this something you already started working on?

**Comment by ollieatkinson** [comment]
@pepibumur yes, I will finish this up. I originally just focused on verbose logging but need to re-evaluate with the use of log levels.

**Comment by pepibumur** [comment]
> @pepibumur yes, I will finish this up. I originally just focused on verbose logging but need to re-evaluate with the use of log levels.

Awesome! Looking forward to it.

> FYI we have an open issue covering verbose logging already: #39

I'm closing this issue in favor of [this one](https://github.com/tuist/tuist/issues/39)
