### ISSUE TITLE
Publish release cycles

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#786]
## Need/problem

Make one week or two weeks release cycle. Create a release with some period makes it easier to adopt the current project to the changes. So everyone who uses the tool, can get improvements and updates as soon as possible without a fork or wait until release will be published.

## Motivation

Make releases, for example, every Monday, or every second Monday. The tool is under development, so a lot of changes can be during releases, so I think releases with a smaller batch of changes will make it easier to adopt developers their current projects.

**Comment by lakpa** [comment]
@tuist/core wondering if we can consider setting up nightly build release cycle.

**Comment by pepibumur** [comment]
> @tuist/core wondering if we can consider setting up nightly build release cycle.

Nightly might be too much because we are not merging improvements & fixes that ofetn.  What about a weekly or biweekly cadence? Let's say every Friday?

**Comment by lakpa** [comment]
Weekly would work

**Comment by pepibumur** [comment]
I've included a documentation page [on this PR](https://github.com/tuist/tuist/pull/841) setting the cadence to 2 weeks for now. If we notice it's not frequent enough, we can reconsider it.
