### ISSUE TITLE
Code coverage is no longer working

### ISSUE THREAD

**Issue by marciniwanicki** [tuist/tuist#788]
**To Reproduce**
Create a PR, coverage heat map is not posted in the comments.

**Expected behavior**
coverage heat map / deltas should be posted in the comments.

**Additional context**
Looks like we're missing the codecov token in the github actions.

```
HTTP 400
104
Please provide the repository token to upload reports via `-t :repository-token`
```

I guess we can use https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets to safely store it. 

Also, since Xcode 11 there is a nice way of getting the coverage from the llvm-cov format produced by swiftpm - https://community.codecov.io/t/swift-package-support/675, in that acse generation of xcodeproj wouldn't be necessary.

**Comment by pepibumur** [comment]
`swift test --enable-code-coverage` ❤️ 

Thanks for bringing this up @marciniwanicki. It might have something to do with the secrets not being available on CI when the workflows are run from forks. I'll look into it.
