### ISSUE TITLE
Lost order of launch arguments in schemes

### ISSUE THREAD

**Issue by marciniwanicki** [tuist/tuist#791]
**Describe the bug**

The order of the arguments cannot be defined in the manifest as such the list of arguments cannot be split into multiple lines to ease to process or enabling / disabling them individually

i.e. 
<img width="918" alt="Screen Shot 2019-12-15 at 6 34 32 PM" src="https://user-images.githubusercontent.com/946649/70867122-9e889600-1f69-11ea-88d5-a6de08cc4520.png">

where user can check and uncheck the arguments (like "clean") when needed. This behavior only affects the target applications which relay on the order of the arguments.

https://github.com/tuist/tuist/pull/790 will make the list stable but won't resolve this issue.

It's probably not very popular flow when people relay on positional arguments. Most of the times users define full calls in a single argument and use checkboxes more as radio buttons to select the call they need. 

<img width="914" alt="Screen Shot 2019-12-15 at 6 44 16 PM" src="https://user-images.githubusercontent.com/946649/70867212-ecea6480-1f6a-11ea-92d8-bc571868d52e.png">

Please feel free to close the ticket if this behavior is by design.

**To Reproduce**

1. Create project with custom scheme
2. Define list of launch arguments
3. Generate the project
4. The order of the arguments in the generated scheme is random

**Expected behavior**
The manifest allows to specify the order of the launch arguments.

**Comment by pepibumur** [comment]
This has been fixed [here](https://github.com/tuist/tuist/pull/790). Therefore I'm closing this issue.
