### ISSUE TITLE
Add a glob for excluding files from target

### ISSUE THREAD

**Issue by vytis** [tuist/tuist#808]
## Need/problem

I have a project that uses a pattern of keeping test files next to source code e.g. :

```
A/One.swift
A/OneTests.swift
B/Two.swift
```

I would like to specify that:
1.  My main target would have `["One.swift", "Two.swift"]` 
2. The test target would have `["OneTests.swift"]`

Using the current glob syntax for source files I could use `**/*Tests.swift` that covers no. 2, but there seems to be no way to do a "negative" glob to include all files that DO NOT end with `Tests.swift`. 

## Motivation

It should be reasonable easy to encode various conventions how projects are structured in practice. Keeping tests close to the code might not be the industry-standard but still reasonably popular in my experience.

## Detailed design

Add `excluding` to `SourceFileGlob`.

It would follow the same approach and would require adding one optional parameter to the [SourceFileGlob.init()](https://github.com/tuist/tuist/blob/master/Sources/ProjectDescription/SourceFilesList.swift#L16):

```swift
public init(_ glob: Path, excluding: Path? = nil, compilerFlags: String? = nil) {
    self.glob = glob
    self.excluding = excluding
    self.compilerFlags = compilerFlags
}
```

This mimics how Bazel solves it ([link](https://docs.bazel.build/versions/1.2.0/be/functions.html#glob)). 

The target definition could then be:

```swift
let mainTarget = Target(sources: [.init("**/*.swift", excluding: "**/*Tests.swift")])
```

# Drawbacks

* Adds a bit of complexity to the API
* Might lead to issues when both globs are not defined correctly and overlap in a way that prevents file from being added to a target.

### Specify file list manually

You could list all the source files in the project definition and not use the glob syntax at all. This is error prone and very tedious. It would however be possible to make a function that reads files on disk and generates an array of paths. This would basically re-implement the glob functionality in an ad-hoc way.

### Add a closure to `SourceFileGlob`

This would be a more generic way of solving the problem by getting a callback with file URL and returning a boolean similar to Swift's `filter(_ isIncluded:)`. However it feels like a bit of an overkill and is not very declarative.

# Adoption strategy

Since the new initializer argument has a default value it is an additive change.

# How we teach this

It uses the same approach so no new concepts to introduce. Updating the documentation should be straight-forward.

**Comment by kwridan** [comment]
Hi @vytis 

Thanks for the suggestion and the detailed proposal 👍 

We follow a similar convention for one our projects at work. Agreed not super standard, but can be really useful in large projects.

Swift PM has exclude as a sibling of `sources` in `Target` - (https://developer.apple.com/documentation/swift_packages/target)

I like your suggestion as it provides more flexibility:

```swift
let mainTarget = Target(sources: [.init("**/*.swift", excluding: "**/*Tests.swift")])
```

Adding exclusions for sources, would naturally lead to adding exclusions for headers (#705) and possibly resources too.

@tuist/core - any further thoughts / concerns?

**Comment by pepibumur** [comment]
> @tuist/core - any further thoughts / concerns?

I really like what you suggested @vytis. It's not a breaking change, and I think the resulting API is very straightforward.

Would you like to work on that one?

**Comment by vytis** [comment]
I would give it a go - seems like an easy one to start with!

**Comment by pepibumur** [comment]
> I would give it a go - seems like an easy one to start with!

Awesome! Thanks for bringing it up btw.
