### ISSUE TITLE
Disable schemes automatic generation

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#836]
**Describe the bug**
I create custom scheme in my `Project` file. I have 2 targets: framework and unit tests. I created a scheme that has my framework and unit tests in tests action. Then I generate project and as a result I have 3 schemes:
`Framework` unit tests
`FrameworkTests` unit tests that I declared as a target
`Framework 1` framework.

**To Reproduce**

1. Create `Project.swift`
2. Create 2 targets: one for framework and another for unit tests
3. Create scheme, add framework to build action, unit tests to test action
4. Create `Project(name: projectName, settings: projectSettings, targets: targets, schemes: schemes)`

**Expected behavior**
Schemes list has only 1 `scheme` that is declared in `schemes` property of `Project`

**Comment by rowwingman** [comment]
I have a question about this code:

**Comment by fortmarek** [comment]
Can I ask why did you close the issue? I am wondering the same thing at the moment.

**Comment by gitrubs** [comment]
> Can I ask why did you close the issue? I am wondering the same thing at the moment.

You can disable it on Config.Swift file 😄 
https://docs.tuist.io/manifests/config#generationoption

**Comment by Ast3r10n** [comment]
> You can disable it on Config.Swift file 

Is the documentation not up to date? I don't see an option to do that.

**Comment by danyf90** [comment]
It's in Workspace.swift now 😁

**Comment by Ast3r10n** [comment]
I actually really hoped to skip using a workspace entirely. It does seem a bit redundant when only using native SPM dependencies.
