### ISSUE TITLE
What is the way to add Developer sdk like xctest.framework?

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#837]
## Question

What is the right way to add develooper sdk like xctest.framework to the target. Can we add `xctest.framework` by default to unit tests and ui tests targets?

**Comment by pepibumur** [comment]
Hey @rowwingman. You set `.sdk` dependencies to your targets as [explained here](https://tuist.io/docs/usage/dependencies/#system-libraries-and-frameworks-dependencies). Is that what you are looking for?

```swift
.sdk(name: "XCTest.framework")
```

**Comment by asalom** [comment]
@pepibumur `XCTest.framework` is in a different path than the rest of iOS frameworks

`XCTest.framework` is at`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library`

Whilst `ARKist.framework`, `StoreKit.framework`, etc are at `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library`

**Comment by kwridan** [comment]
One option would be to add a custom build setting to the target:

```swift
Settings(base: [
   "FRAMEWORK_SEARCH_PATHS": ["$(inherited)", "$(PLATFORM_DIR)/Developer/Library/Frameworks"],
])
```

**Comment by kwridan** [comment]
I wonder if for convenience we could auto translate `.sdk(name: "XCTest.framework")` to leverage that path under the hood. That said I worry we'd need to maintain a list of special cases 🤔

**Comment by rowwingman** [comment]
So what can be a solution for this? I suggest add `.developerSdk(name: "XCTest.framework")`

**Comment by rowwingman** [comment]
@kwridan, @pepibumur what is your suggestion will be?

**Comment by kwridan** [comment]
possibly: `.sdk(name: "XCTest.framework", source: .developer)`

where `source` is:

```swift
enum SDKSource {
  case developer // Platforms/iPhoneOS.platform/Developer/Library
  case system // Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library
}
```

**Comment by navtoj** [comment]
Based on #1001, it seems only `TargetDependency.xctest` is currently supported.

Is is possible to add **XcodeKit** as well? Is there another way?

Path: `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/XcodeKit.framework`

<img width="802" height="922" alt="Screenshot 2025-08-04 at 2 47 20 AM" src="https://github.com/user-attachments/assets/6e6789bf-029c-40af-9544-10aee4013695" />

p.s. should i create a new issue for this?

**Comment by fortmarek** [comment]
> p.s. should i create a new issue for this?

Yes! I do think the support for `XcodeKit` is probably missing (it's the first time I'm hearing about this one to be honest).

Would you be up to try and contribute the support for it? You should be able to follow the current implementation of `.xctest` and add another case for `.xcodeKit`. Happy to give additional pointers if needed.

**Comment by navtoj** [comment]
> Would you be up to try and contribute the support for it? You should be able to follow the current implementation of `.xctest` and add another case for `.xcodeKit`.

Okay, I'll give it a try.

> Happy to give additional pointers if needed.

Awesome! I'll ping you in the new issue (https://github.com/tuist/tuist/issues/7973) for any help.
