### ISSUE TITLE
Missing configurations from "Build configuration list for PBXProject"

### ISSUE THREAD

**Issue by andreacipriani** [tuist/tuist#839]
**Describe the bug**
When creating a project with multiple `xcconfig files`, some of them are missing from the `Build configuration list for PBXProject` of the generated project.

**To Reproduce**
I've created a simple project to reproduce the error:

https://github.com/andreacipriani/tuist-configurations-error

**Expected behavior**
The `Alpha` configuration is included in the `Build configuration list for PBXProject` section of the pbxproj.

- OS: macOS 10.14.6

I'm working on this! I just opened the issue to keep track of it

**Comment by andreacipriani** [comment]
cc @pepibumur, I'm having a look at this today

**Comment by andreacipriani** [comment]
I run a debug session and understood the problem.

In your manifest, you need to be sure to pass the custom settings also at the project level. If you don't (they are optional), Tuist defaults to [.default](https://github.com/tuist/tuist/blob/9433dc9f9a85ec3dc29527e38d871a47afe691e0/Sources/TuistCore/Models/Settings.swift#L57).

This was creating confusion on my mind because I was seeing the `debug` and `release` configurations that I've defined, but not "alpha", thinking it was filtered out. But actually `debug` and `release` where not my custom configurations, but the default ones provided by Tuist.
See: https://github.com/tuist/tuist/blob/9433dc9f9a85ec3dc29527e38d871a47afe691e0/Sources/TuistKit/Generator/GeneratorModelLoader.swift#L242

What do you think of making `settings` a mandatory field in the `Project.init` instead of defaulting to this?

**Comment by danyf90** [comment]
I think the current behavior is fine
