### ISSUE TITLE
Pull Tuist from GCS when installing it

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#848]
## Context 🕵️‍♀️
The way we currently install Tuist might fail because the [GitHub API](https://github.com/tuist/tuist/issues/407) errors because we are hitting an API limit. There's this [other issue](https://github.com/tuist/tuist/issues/501) that is related to that problem too.

## What 🌱
Pull the artifacts from [Google Cloud Storage (GCS)](https://github.com/tuist/tuist/pull/504) instead of the GitHub release. GCS has no download limits so downloading the artifacts from there should mitigate the issue that users are facing.

As part of this effort, we can [re-enable](https://github.com/tuist/tuist/pull/849) the install job on CI.

**Comment by jimisaacs** [comment]
Is that what I'm hitting here?
```
Error: Error decoding JSON from API: The data couldn’t be read because it isn’t in the correct format.
```
That's all I see right now, I can't run anything.

**Comment by pepibumur** [comment]
> Is that what I'm hitting here?

Yes! It's exactly the same issue

**Comment by lakpa** [comment]
@pepibumur are you working on this?

**Comment by pepibumur** [comment]
Yes @lakpa, I started tackling it.

**Comment by ollieatkinson** [comment]
If you are hitting this problem you can workaround the issue by using `tuist bundle` to cache tuist inside of your git repository, meaning it does not need to be downloaded.
