### ISSUE TITLE
[Error] Cannot find Carthage framework

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#85]
**Describe the bug**
Generating a project with Carthage dependency ends up with error.
```
❌ Error: /bin/bash: file /Users/__/projects/___/____/Carthage/Build/iOS/Alamofire.framework/Alamofire: No such file or directory
```

**To Reproduce**
Add carthage dependency to target with `.framework(path: "Carthage/Build/iOS/Alamofire.framework"),`

**Expected behavior**
Generates projects with linked binary to `Alamofire.framework`

**Desktop (please complete the following information):**
 - OS: macOS 10.14 Mojave
 - Version Beta 5

Cartfile
```
github "Alamofire/Alamofire"
```

Project.swift:
```swift
import ProjectDescription

let project = Project(name: "tuistTest",
                      targets: [
                        Target(name: "tuistTest",
                               platform: .iOS,
                               product: .app,
                               bundleId: "com.xcodepm.tuistTest",
                               infoPlist: "Info.plist",
                               sources: "Sources/**",
                               dependencies: [
                                    .framework(path: "Carthage/Build/iOS/Alamofire.framework")
                                ]),
                        Target(name: "tuistTestTests",
                               platform: .iOS,
                               product: .unitTests,
                               bundleId: "com.xcodepm.tuistTestTests",
                               infoPlist: "Info.plist",
                               sources: "Tests/**",
                               dependencies: [
                                    .target(name: "tuistTest")
                               ])
                      ])
```

command `tuist generate`

**Comment by pepibumur** [comment]
Looking at the error it seems that the path that we are using to determine whether the framework is dynamic or not is incorrect. Giving you some guidance on how to debug this issue:
- Use xcode and run the `tuist` scheme. Make sure to setup the scheme to pass the same arguments that you are passing from the termian.
- Check out [this method](https://github.com/tuist/tuist/blob/master/Sources/TuistKit/Loader/GraphNode.swift#L166). My guess is that the path that we are passing is not correct.

Let me know if that helps :)

**Comment by zdnk** [comment]
When I run the `tust` scheme with working directory where my `Project.swift` is, I get this:
`[31m[1m❌ Error: [0mCouldn't find ProjectDescription
Program ended with exit code: 1`

**Comment by pepibumur** [comment]
I forgot to mention. Tuist needs to link your `Project.swift` against the `ProjectDescription` framework. Since `tuist` doesn't depend on `ProjectDescription`, Xcode doesn't compile it when running `tuist`. Can you try running `tuist`, but building `ProjectDescription` first?

If that doesn't work, doing `swift build` and then running the scheme should work.

**Comment by pepibumur** [comment]
@zdnk would you mind trying again?

**Comment by zdnk** [comment]
```swift
            dependencies: [
                .framework(path: "Carthage/Build/iOS/Alamofire.framework")
            ]
```

still same

**Comment by zdnk** [comment]
Hmm, I still have version 0.1.0 tho. Tried install script and brew.

**Comment by zdnk** [comment]
Now, how to link system framework like CoreData?

**Comment by pepibumur** [comment]
If I'm not wrong, you should be able to import it from your code. Since CoreData is a system framework, and those should be exposed to your project, you shouldn't need to be explicit about it.
