### ISSUE TITLE
Difficult to discover how to update tuist

### ISSUE THREAD

**Issue by raven** [tuist/tuist#856]
**Describe the bug**
It is difficult to discover how to update tuist. Performing `tuist` or `tuist --help` did not yield any information. There is also no information on how to update that I could find in the docs. 
The only reference I could find was: https://github.com/tuist/tuist/blob/d5f0dfcc5b62b800f7f51d30664e92f469f6ede1/website/markdown/posts/2018-12-03-version-0.9.0/post.md#how-to-update

**To Reproduce**

1. `tuist --help`

**Expected behavior**
In the README.md, `tuist`, or `tuist --help` to detail how to update tuist. 

**Screenshots**

![image](https://user-images.githubusercontent.com/316931/71752336-cf0d8100-2ed2-11ea-90ba-0e9746ae2500.png)

**Comment by raven** [comment]
Because `tuist` (`tuistenv`) forwards unhandled commands to `tuist`, the user never sees the help/list of `tuistenv` commands. The exception being `tuist --help-env` which is caught prior to forwarding commands on to `tuist`. The discovery of `tuist --help-env` requires the user to have read the 'managing versions' doc.

> There is also no information on how to update that I could find in the docs.

Found it under 'managing versions'.
https://github.com/tuist/tuist/blob/master/website/markdown/docs/usage/managing-versions.mdx#tuist-update

I wonder if it makes sense to special-case / surface `--help-env` from the `--help` command?

**Comment by pepibumur** [comment]
> I wonder if it makes sense to special-case / surface --help-env from the --help command?

I think it makes total sense. `tuist` could detect if it's being run through `tuistenv` and in that case include those commands in the list. Would you like to open a PR with this improvement?

**Comment by facumenzella** [comment]
Is anybody working on this? I'd be happy to start to work on this ✋

**Comment by pepibumur** [comment]
Feel free @facumenzella 🙂

**Comment by facumenzella** [comment]
I think that an easy way to get this functionality for free would be to just add this to `TuistCommand` inside `TuistKit`.

```swift
@Flag(
    name: [.customLong("help-env")],
    help: "Display subcommands to manage the environment tuist versions."
)
var isTuistEnvHelp: Bool
```

It's kind of a hack though because the whole purpose of this `@Flag` would be to get the help functionality for free. The flag won't be used by `TuistKit.TuistCommand` since `TuistKitEnv.TuistCommand` will be filtering it.

Let me know what you think.

**Comment by pepibumur** [comment]
Sounds good!
