### ISSUE TITLE
Can't run tuist after install

### ISSUE THREAD

**Issue by jimisaacs** [tuist/tuist#857]
**Describe the bug**
Getting an error when executing whatever the tuist install script installed.

**To Reproduce**

1. Run the recommended install script `bash <(curl -Ls https://install.tuist.io)`
2. See success
```
Installing Tuist
Tuist installed. Try running 'tuist'
Check out the documentation at https://docs.tuist.io
```
3. Execute `tuist`
```
Error: Error decoding JSON from API: The data couldn’t be read because it isn’t in the correct format.
```

**Expected behavior**
I'm not sure, I'd expect to see help output simply by running `tuist`, or at the very least a much more descriptive error.

**Screenshots**
<img width="730" alt="Screen Shot 2020-01-03 at 3 46 03 PM" src="https://user-images.githubusercontent.com/299156/71755646-6249a680-2e40-11ea-93c0-e7420362a542.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.2

**Additional context**
Xcode 11.3
Shell zsh

**Comment by pepibumur** [comment]
Thanks for reporting this @jimisaacs. It's a known issue and we already have an issue to take it [here](https://github.com/tuist/tuist/issues/848) so I'm closing this one and moving the discussion there.
