### ISSUE TITLE
Create custom generate functions

### ISSUE THREAD

**Issue by rowwingman** [tuist/tuist#872]
## Need/problem

Is there any way to declare my own generation functions and use them instead of default ones.
For example I have 10 internal frameworks, I use the same template for target settings, each target has some unique information like: name, identifier, source path, tests path. Each target has the same setup, so `Project.swift` is copy paste.

Is there any way to create something like this:
```
{company_name}_framework(name: String, source: String, tests: String, ...) {
    let projectSettings = ...
    let targets = ...
    let schemes = ...
    Project(name: name,
                  settings: projectSettings,
                  targets: targets,
                  schemes: schemes)
}
```

Use ` {company_name}_framework` in `Project.swift` file for each framework instead of duplication creating targets, settings, schemes,...

**Comment by kwridan** [comment]
@rowwingman I believe "Project Description Helpers" is the feature that you're looking for.

https://tuist.io/docs/usage/helpers/

This will allow you to define custom helper methods to use in all your project manifests.

**Comment by rowwingman** [comment]
> @rowwingman I believe "Project Description Helpers" is the feature that you're looking for.
> 
> https://tuist.io/docs/usage/helpers/
> 
> This will allow you to define custom helper methods to use in all your project manifests.

Do we have a way to convert several `xcconfig` files to `[settings]` that can be used in `Target` then?

**Comment by kwridan** [comment]
> Do we have a way to convert several xcconfig files to [settings] that can be used in Target then?

I don't believe so, though you can achieve the same goal by defining a helper function in the `ProjectDescriptionHelpers` to specify a shared list of settings.

e.g.

```swift
// Tuist/ProjectDescriptionHelpers/Project+Templates.swift

function sharedConfigurations() -> [CustomConfiguration] {
 return [
    .debug(name: "Debug", xcconfig: "//ConfigurationFiles/Debug.xcconfig"),
    .release(name: "Beta", xcconfig: "//ConfigurationFiles/Beta.xcconfig"),
    .release(name: "Release", xcconfig: "//ConfigurationFiles/Release.xcconfig"),
]
}
```

Note the `//` which was introduced in #727 to allow specifying paths that are relative to the root. This means any project using this path will point to the same (even if it lives somewhere different on disk).

Hope this helps.

**Comment by rowwingman** [comment]
But what if you want to specify settings from several xcconfig files, for example:
`Warnings.xcconfig` + `FrameworkDebug.xcconfig` + `podsDebug.xcconfig`?

**Comment by rowwingman** [comment]
What if we could implement something like that:
```
struct Xconfig {
   let path: Path
   var settings: [Setting: SettingValue]
}
```
so then you can combine several `xcconfig` files and convert them to `[settings]`, that you can use then in `CustomConfiguration` What do you think about it?

**Comment by kwridan** [comment]
Typically with xcconfig files, you can `#include "another.xcconfig"`

For example, for an application

- `App-Debug.xcconfig`
   -> `#include "DebugShared.xcconfig"`
   -> `#include "Warnings.xcconfig"`
   -> ...
- `App-Release.xcconfig`
  -> ...

The App target then only needs to reference those top level xcconfig files for its configurations.

It keeps things a little simpler - as attempting to parse xcconfig files and merge settings can get a little tricky - we can let Xcode do that :)
