### ISSUE TITLE
Dependencies via HTTPs

### ISSUE THREAD

**Issue by dcordero** [tuist/tuist#88]
First of all, thanks for open sourcing this amazing project. 🎩 off

**Issue**
I recently faced the same issue described by #73 when installing Tuist in a new machine in which I did not have my SSH certificates configured yet.

Since Github started recommending HTTPs over SSH to clone repos, I think this issue might be faced for more people in the future.

I think defining the dependencies via HTTPs might avoid those issues.

**Additional context**

Definition of dependencies via SSH
https://github.com/tuist/tuist/blob/master/Package.swift#L15

The documentation to install Tuist via Homebrew also relies on SSH:
https://github.com/tuist/tuist/blame/master/README.md#L24

Github recommends HTTPs over SSH here
https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended

**Comment by pepibumur** [comment]
Thanks for bringing this @dcordero. I was not aware of that recommendation but it makes total sense. I'll update all the usages of ssh to use https instead.
