### ISSUE TITLE
UITests Target duplicating Embed Precompiled Frameworks build phase

### ISSUE THREAD

**Issue by miscampbell** [tuist/tuist#887]
**Describe the bug**
When generating a project with 3 Targets: (_.app_, _.uiTests_ and _.unitTests_) where the test targets all define the _.app_ target as their only dependency. The project that is created is duplicating the same Embed Precompiled Frameworks build phase that is added to the .app target on the .unitTests target. 

This causes a compile issue because we are duplicating framework references for the .uiTests target when they are not needed cause we should be linking to the .app target.

This issue I am seeing though does not happen on the .unitTests target

**To Reproduce**
Please see example Project Structure below:
```
Target(name: "TestProject",
                               platform: .iOS,
                               product: .app,
                               bundleId: "$(inherited)",
                               deploymentTarget: .iOS(targetVersion: DEPLOYMENT_TARGET,
                                                      devices: [.iphone, .ipad]),
                               ...
Target(name: "TestProjectUnitTests",
                platform: .iOS,
                product: .unitTests,
                bundleId: "$(inherited).UnitTests",
                infoPlist: "UnitTests/UnitTests.plist",
                sources: "UnitTests/**",
                dependencies: [
                  .target(name: "TestProject")
                ],
                settings: Settings.forTestTarget("UnitTests/DynamicSignalUnitTests-Bridging-Header.h")),
            Target(name: "TestProjectUITests",
                platform: .iOS,
                product: .uiTests,
                bundleId: "$(inherited).UITests",
                infoPlist: "UITests/UITests.plist",
                sources: "UITests/**",
                dependencies: [
                   .target(name: "TestProject")
                ],
                settings: Settings.forTestTarget()),
```

Below is the difference in the output I am seeing between the .unitTests target and .uiTests targets:

**UnitTests - Embed Precompiled Frameworks Build Phase**
`echo "Skipping, nothing to be embedded."`

**UITests - Embed Precompiled Frameworks Build Phase**
This is the same Precompiled Frameworks Build Phase that is implemented on main app project and leads to compile issues due to duplication of frameworks

```
#!/bin/sh
set -e
set -u
set -o pipefail
function on_error {
  echo "$(realpath -mq "${0}"):$1: error: Unexpected failure"
}
trap 'on_error $LINENO' ERR
if [ -z ${FRAMEWORKS_FOLDER_PATH+x} ]; then
  # If FRAMEWORKS_FOLDER_PATH is not set, then there's nowhere for us to copy
  # frameworks to, so exit 0 (signalling the script phase was successful).
  exit 0
fi
echo "mkdir -p ${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
mkdir -p "${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
SWIFT_STDLIB_PATH="${DT_TOOLCHAIN_DIR}/usr/lib/swift/${PLATFORM_NAME}"
# Used as a return value for each invocation of `strip_invalid_archs` function.
STRIP_BINARY_RETVAL=0
...

```
**Expected behavior**
On both the tests targets I would expect the Embed Precompiled Frameworks build phase to be the same containing only:

**echo "Skipping, nothing to be embedded."**

**Screenshots**
![image](https://user-images.githubusercontent.com/3660489/72292875-30a7bb00-364a-11ea-9f4f-ec4c11553845.png)
![image](https://user-images.githubusercontent.com/3660489/72292893-37363280-364a-11ea-8a3f-d8b562309b60.png)

**Desktop (please complete the following information):**

- OS: Mac OS Mojave
- Version  10.14.6

Should you require any further detail please let me know and needs be I can create a separate project to try and show the issue.

Thank you very much for your help with this issue

**Comment by kwridan** [comment]
Was able to reproduce this locally in one of the fixtures - thanks for flagging this @miscampbell!

Can you try out https://github.com/tuist/tuist/pull/888 to see if it resolves the issue for your case?

**Comment by miscampbell** [comment]
Thank you @kwridan for looking into this issue for me. Could you advise what is the best way for me to test this PR? 

Do I switch to this branch by running `tuist local fixtures/ios_app_with_tests`. I am getting the below error when I do the following:

Code Executed in Terminal:
```
tuist local fixtures/ios_app_with_tests
tuist install
tuist install fixtures/ios_app_with_tests
```

Output in Terminal 
```
Warning: The release fixtures/ios_app_with_tests couldn't be obtained from GitHub
Pulling source code
Building using Swift (it might take a while)
Version fixtures/ios_app_with_tests installed
Error: The file “TemporaryDirectory.YYKtJ4” doesn’t exist.
```

**Comment by kwridan** [comment]
ah sadly I don't think tuist local works with branches on forks :( 

An option would be to build from source:

```sh
# Clone
git clone https://github.com/tuist/tuist.git
cd tuist

# Pull changes
git checkout -b fix/precompiled-frameworks-uitests master
git pull https://github.com/bloomberg/tuist.git fix/tests-precompiled-frameworks-uitests

# Build & Run 
swift run tuist generate --path /path/to/project
```
