### ISSUE TITLE
Add support to specify build configurations for profile and analyze for custom schemes

### ISSUE THREAD

**Issue by zhuhaow** [tuist/tuist#893]
Currently, when creating a scheme, we can only specify build, test, run and archive actions. Profile and analyze will always pick the default build configurations. 

I find there is #697 which adds archive action. 

I'm wondering if there are any difficulties in adding profile or analyze actions or simply because people rarely use them. I would love to help to add the support.

**Comment by kwridan** [comment]
Hi @zhuhaow - thanks for suggesting this.

> I'm wondering if there are any difficulties in adding profile or analyze actions or simply because people rarely use them. I would love to help to add the support.

Indeed I believe there wasn't a strong demand for them. Is this something you may be interested in contributing? We'd be happy to help guide you through how to add those. 

@pepibumur has done a fantastic job of adding documentation for contributors here: https://tuist.io/docs/contribution/getting-started/
