### ISSUE TITLE
Passing parameters (or environment variables at least)

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#894]
It would be awesome if there was a way to pass a simple parameters or flags to the `generate` command.

We have complex project and I would like to generate it separately for development and production (app store builds).

I tried using env variables `PRODUCTION=true tuist generate` with following code in `Project.swift`:
```swift
import Foundation
import ProjectDescription

let isDev = ProcessInfo.processInfo.environment["PRODUCTION"] == nil
```

But the `isDev` variable is always `true`. Any ideas how to make at least env vars propagate inside?

**Comment by Rag0n** [comment]
We have similar use case. There are some frameworks that should be linked to the project only for debug builds. For example:
- [BugSee](https://docs.bugsee.com/sdk/ios/installation/)(or any other framework for debugging)
- [earlgrey2](https://github.com/google/EarlGrey/blob/earlgrey2/docs/cocoapods-setup.md) - I'm going to replace podspecs with manifest files, but installation is almost the same.

**Comment by zdnk** [comment]
I did come up with workaround for now. I have a `Makefile` with following targets:
```
xcode:
	echo "development" > .xcode-env
	tuist generate
	bundle exec pod install

xcode-prod:
	echo "production" > .xcode-env
	tuist generate
	bundle exec pod install
```
It outputs selected environment to a `.xcode-env` file and then read this file in `Project.swift`:
```swift
let env = try! String(contentsOf: URL.init(fileURLWithPath: "./.xcode-env"), encoding: .utf8)
let isDev = !env.contains("production")
```

**Comment by lucasmpaim** [comment]
Any update on this?

**Comment by kwridan** [comment]
I believe this can now be closed 🎉

@pepibumur implemented support for `Environment` access within manifests recently

https://tuist.io/docs/usage/projectswift/#environment

**Comment by pepibumur** [comment]
Right!

**Comment by Kylmakalle** [comment]
Not sure why this should be closed because we still unable to pass some envs to generator during runtime for dynamic project generation, insted we should use hacks like @zdnk's one 

I think we need something that's already implemented for other envs (like @pepibumur did for Github API token), but customizable https://github.com/tuist/tuist/blob/426b5dec52612c5da76cf1c8fbf9552b5f760c10/Sources/TuistSupport/Constants.swift#L57-L69


btw, @kwridan's link is broken

**Comment by kwridan** [comment]
The docs website has been changed recently. 

Tuist's environment feature should hopefully help with this requirement. 

https://docs.tuist.io/guides/environment

**Comment by Kylmakalle** [comment]
Thank you so much, that exactly cover my issue.

Unfortunately I was not careful enough and searched the site only by "[Environment](https://docs.tuist.io/search?q=Environment)" word which does not give this article

**Comment by mflknr** [comment]
For anyone who is also ending up here, the new link is that [that one](https://docs.tuist.io/documentation/tuist/generation-environment/).

**Comment by CaramelHeaven** [comment]
how to use environmentVariable, where is the actual docs please tuist)
