### ISSUE TITLE
Fastlane - automatic_code_signing issue - missing `TargetAttributes`

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#904]
**Describe the bug**
Fastlane is not able to open Tuist generated Xcode project.

**To Reproduce**
Generate tuist project and use `automatic_code_signing issue` in fastlane.

**Expected behavior**
Fastlane to work as with regular Xcode project and modify code signing options within the project.

**Cause**
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/automatic_code_signing.rb#L14
This line is causing the crash, it is looking for some `TargetAttributes` key that is missing.

**Desktop (please complete the following information):**

- OS: macOS
- Version 1.1.0
- fastlane: 2.140.0

**Comment by zdnk** [comment]
This one is actually a little hot, could any of you guys look at it anytime soon? @pepibumur @lakpa @ollieatkinson

**Comment by ollieatkinson** [comment]
At the moment we only insert the `TargetAttributes` dictionary when we generate the test target indentity: https://github.com/tuist/tuist/blob/3dc88e53a1d7353fb59fd65da625dd8bb80f7961/Sources/TuistGenerator/Generator/ProjectGenerator.swift#L214

We would need to expand this to _always_ set it for application product types to include the provisioning and capabilities:

```
TargetAttributes = {
	07AD0A181AF77841AE740AF8 = {
		TestTargetID = F94854C32EB8F3551562B719;
	};
	B4B305A47D5248C4087F2757 = {
		TestTargetID = F94854C32EB8F3551562B719;
	};
	F94854C32EB8F3551562B719 = {
		ProvisioningStyle = Manual;
		SystemCapabilities = {
			com.apple.Push = {
				enabled = 1;
			};
		};
	};
};
```

I do not know Fastlane well enough to know if it will be happy with an empty structure here. It's something you could test and let us know, if true, the fix would be trivial.

**Comment by zdnk** [comment]
```ruby
        target_attributes = project.root_object.attributes["TargetAttributes"]
        changed_targets = []

        # make sure TargetAttributes exist for all targets
        target_dictionary.each do |props|
          unless target_attributes.key?(props[:uuid])
            target_attributes[props[:uuid]] = {}
          end
        end

        target_attributes.each do |target, sett|
          found_target = target_dictionary.detect { |h| h[:uuid] == target }
          if params[:targets]
            # get target name
            unless params[:targets].include?(found_target[:name])
              UI.important("Skipping #{found_target[:name]} not selected (#{params[:targets].join(',')})")
              next
            end
          end
```

This is the code from Fastlane and I'd say empty structure would do the trick, I will test it later today, somehow, any pointers on how can I test it by modifying tuist to generate it empty at least?

**Comment by zdnk** [comment]
@ollieatkinson I have added test target to my project, by it still does not generate the `TargetAttributes` dictionary :(
```swift
        Target(
            name: "AppTests",
            platform: .iOS,
            product: .unitTests,
            productName: "Redacted",
            bundleId: "Redacted",
            infoPlist: .file(path: "Redacted/Info.plist"),
            sources: ["Redacted/Sources/**"],
            resources: ["Redacted/Resources/**"],
            dependencies: [
                .target(name: "App"),
            ]
        ),
```

**Comment by pepibumur** [comment]
@zdnk I opened a PR on XcodeProj to fix that behaviour https://github.com/tuist/XcodeProj/pull/517. Once merged, I'll update the logic in Tuist accordingly to get this one fixed :). Thanks for reporting it!

**Comment by zdnk** [comment]
Cool, thanks

**Comment by 2sem** [comment]
fastlane error
Seems to be a very old project file format - please open your project file in a more recent version of Xcode

```ruby
require 'xcodeproj'
module Fastlane
  module Actions
    class UpdateCodeSigningSettingsAction < Action
      def self.run(params)
        FastlaneCore::PrintTable.print_values(config: params, title: "Summary for code signing settings")
        path = params[:path]
        path = File.join(File.expand_path(path), "project.pbxproj")

        project = Xcodeproj::Project.open(params[:path])
        UI.user_error!("Could not find path to project config '#{path}'. Pass the path to your project (not workspace)!") unless File.exist?(path)
        UI.message("Updating the Automatic Codesigning flag to #{params[:use_automatic_signing] ? 'enabled' : 'disabled'} for the given project '#{path}'")

        unless project.root_object.attributes["TargetAttributes"]
          UI.user_error!("Seems to be a very old project file format - please open your project file in a more recent version of Xcode")
          return false
        end
```
