### ISSUE TITLE
Multiple commands produce XXXXX script phase “Embed Precompiled Frameworks”

### ISSUE THREAD

**Issue by asalom** [tuist/tuist#919]
**Describe the bug**
When a project which has a test target depends on another project that also has a test target, both test targets copy precompiled frameworks to the build output directory. This is a problem when having the workspace use the new build system (enabled by default) as both test targets will produce duplicated outputs:

`App` defines targets `App` and `AppTests`
`Core` defines targets `Core` and `CoreTests`

`App` depends on `Core` and `Alamofire`
`Core` depends on `Alamofire`
`App` has a scheme with a test action which runs `AppTests` and `CoreTests`. Because both test targets copy their dependencies into the output build directory, the project won't compile with multiple errors like the following:

```
Multiple commands produce '/Users/asalom/Library/Developer/Xcode/DerivedData/App-dlfvehwtprbyvodalfsmjmvclzaq/Build/Products/Debug-iphonesimulator/Alamofire.framework.dSYM':
1) That command depends on command in Target 'CoreTests' (project 'Core'): script phase “Embed Precompiled Frameworks”
```

If we manually change the workspace settings to use the legacy build system, the project compiles. However, there is no way to produce a workspace which uses the legacy build system using tuist.

**Dependency Graph**
![graph](https://user-images.githubusercontent.com/1466079/72988517-b5ce6500-3dec-11ea-8045-3473e3092974.png)

**Example project**
How to run:
1. Download and unzip [App.zip](https://github.com/tuist/tuist/files/4103278/App.zip)
2. `tuist up`
3. `tuist generate`
4. Open `AppWorkspace.xcworkspace`
5. Select the Scheme `AppWorkspace`
6. Run tests with `CMD+U`

**Comment by kwridan** [comment]
Thanks for the detailed issue description @asalom - and for the sample project its super useful!

It seems this is occurring when attempting to build a scheme that includes multiple targets that leverage the precompiled framework script and reference a common precompiled framework. As you pointed out, those targets will produce the same output.

The script copies the precompiled framework symbols to the same location (from multiple targets).

e.g.

<img width="551" alt="Screenshot 2020-01-24 at 20 17 52" src="https://user-images.githubusercontent.com/11914919/73101718-37ef8400-3ee8-11ea-9a28-5e8e03b65e7a.png">

I believe this script was copied/adapted from CocoaPods and it appears there are some similar issues being raised for it too

- https://github.com/CocoaPods/CocoaPods/issues/9419

The solutions proposed may be applicable here too. 

cc: @pepibumur / @ollieatkinson

**Comment by kwridan** [comment]
We could omit the copy of those files (dSYM and bcsymbolmap) for test targets - I don't think they are needed there. That should minimise the occurrence of this issue, however the issue can still occur in the event there's a scheme that builds two applications that depend on the same precompiled framework too.

**Comment by pepibumur** [comment]
> We could omit the copy of those files (dSYM and bcsymbolmap) for test targets - I don't think they are needed there. That should minimise the occurrence of this issue, however the issue can still occur in the event there's a scheme that builds two applications that depend on the same precompiled framework too.

From the proposed solutions in the CocoaPods issue that you linked I'm leaning more towards the second to avoid having to add another target. However, I'm not sure what implications there are if we export the dSYMs into directories inside `Products`.

**Comment by vytis** [comment]
We seem to be hitting this issue also, there is no way to build the app without switching to legacy build system. Any tips on the possible solution? I am not sure if I understand why it is happening with CocoaPods, but not with Carthage for example?

**Comment by kwridan** [comment]
Typically with a [Carthage setup](https://github.com/Carthage/Carthage#quick-start) the input/output paths are the frameworks only without the other symbol files.

Carthage does however copy those symbols under hood when archiving:

https://github.com/Carthage/Carthage/blob/master/Source/carthage/CopyFrameworks.swift#L94

It does mean Xcode is unaware of those files - should they change between archiving you may get outdated symbols in the final archive. However realistically this is not a very likely scenario

- Archives are often done from clean
- Should the pre-compiled framework change the script phase is going to re-trigger anyways ...

To resolve this I would propose we omit the symbols from the input / output list and add the functionality directly in the script to scan and copy the appropriate symbols.

This approach will also resolve #699 !

**Comment by vytis** [comment]
Makes sense! This sounds like a good solution, I will try to give it a go.

**Comment by vytis** [comment]
I looked at it a bit and see few questions/comments:
* The script is copied from CocoaPods and changing it means we are basically forking it - this might make it hard to integrate changes that they do at some point later.
* Do we think having the copied script is a good approach in general? Do we have any other mechanism of defining a build phase like this? 
* By just removing the `bcsymbolmap` and `dSYM` from input files seem to fix the issue and makes it basically inline with how Carthage does it - do you think it's a good enough solution for now?

**Comment by kwridan** [comment]
> The script is copied from CocoaPods and changing it means we are basically forking it - this might make it hard to integrate changes that they do at some point later.

Taking a look at the script it appears mostly similar but has some minor divergences already it seems (e.g. conditionally 

> Do we think having the copied script is a good approach in general? Do we have any other mechanism of defining a build phase like this?

That's a good question - from memory this is a second iteration to solve embedding pre-compiled frameworks, previously there used to be `tuist embed` command which would get added to the build phase however that meant generated projects required all users to have `tuist` installed #610 introduced the script to make the generated projects stand alone without reliance on tuist. 

> By just removing the bcsymbolmap and dSYM from input files seem to fix the issue and makes it basically inline with how Carthage does it - do you think it's a good enough solution for now?

Sure worth give it a try - I can't think of other alternates
