### ISSUE TITLE
Swift version build setting is overridden when settings are only in xcconfigs

### ISSUE THREAD

**Issue by andreacipriani** [tuist/tuist#920]
**Describe the bug**
If you have a project with all build settings extracted into `.xccconfig` files, `Tuist` thinks that the project hasn't set a `SWIFT_VERSION` build setting and thus overrides your setting. See https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/ConfigGenerator.swift#L187

**To Reproduce**
See example project: https://github.com/andreacipriani/tuist-override-swift-version

**Expected behavior**
Swift version to be 4.0 (like specified in the Example.xcconfig), but it is 5.0 (overriden by Tuist)

**Screenshots**
<img width="934" alt="Screenshot 2020-01-23 at 15 10 35" src="https://user-images.githubusercontent.com/536929/72991666-ae11bf00-3df2-11ea-9296-bc2c4a7809c9.png">

**Proposed solutions**
1) Delete the [line of code](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/ConfigGenerator.swift#L187) that is overriding the Swift version, since a Swift Project without a SWIFT_VERSION, is not valid. Why would we fix it instead of telling "you forgot the set the SWIFT_VERSION"?
2) Read the settings from the `xcconfig` to **really** verify that the Swift version is not set

**Comment by andreacipriani** [comment]
cc @tuist/core

**Comment by kwridan** [comment]
Thanks for raising this @andreacipriani! 

> 1. Delete the line of code that is overriding the Swift version, since a Swift Project without a SWIFT_VERSION, is not valid. Why would we fix it instead of telling "you forgot the set the SWIFT_VERSION"?

This would sadly make new projects not work out of the box unless you add this setting, adding a small barrier to a successful project on first try.

> 2. Read the settings from the xcconfig to really verify that the Swift version is not set

I'd be a bit hesitant on attempting to parse `xcconfig` files as that can get quite complicated, they look deceivingly simple but can get really complex if you take into account variables, `#include` etc... - we can let Xcode take care of that complexity :p

What do you think of the following options?

3. Move the `SWIFT_VERSION` setting to `DefaultSettingsProvider` and treat it as one of the `essential` settings? i.e. specifying `defaultSettings: .none` would not set a default swift version.

All the other settings within `updateTargetDerived` relate to manifest related properties, whereas this is the only odd one out there.

4. Add an explicit `swiftVersion` property to the target in the project manifest, which can be `nil` 

```swift
Target(name: "MyTarget",
           // ...
        swiftVersion: "5.0")
```

```swift
Target(name: "MyTarget",
           // ...
        swiftVersion: nil) // inherit from somewhere else 
```

This would control the `SWIFT_VERSION` setting in the config generator.

The tricky part would be figuring out a sensible migration path for existing users, we'd need to default it to the existing value as opposed to `nil` which might seem a little counter intuitive on first glance.

**Comment by lakpa** [comment]
> 1. Add an explicit `swiftVersion` property to the target in the project manifest, which can be `nil`
> 
> ```swift
> Target(name: "MyTarget",
>            // ...
>         swiftVersion: "5.0")
> ```
> 
> ```swift
> Target(name: "MyTarget",
>            // ...
>         swiftVersion: nil) // inherit from somewhere else 
> ```
> 
> This would control the `SWIFT_VERSION` setting in the config generator.
> 

Language version should be centrally configured and applied wherever it is needed, introducing `swiftVersion` as a parameter in `target` will breed more problems as now we are allowing users to make mistake by allowing them to configure different versions for different targets, wouldn't that be a problem?

**Comment by andreacipriani** [comment]
> Thanks for raising this @andreacipriani!
> 

Thanks for the detailed response.

> > 1. Delete the line of code that is overriding the Swift version, since a Swift Project without a SWIFT_VERSION, is not valid. Why would we fix it instead of telling "you forgot the set the SWIFT_VERSION"?
> 
> This would sadly make new projects not work out of the box unless you add this setting, adding a small barrier to a successful project on first try.
> 

Now I got it, good point!

> > 1. Read the settings from the xcconfig to really verify that the Swift version is not set
> 
> I'd be a bit hesitant on attempting to parse `xcconfig` files as that can get quite complicated, they look deceivingly simple but can get really complex if you take into account variables, `#include` etc... - we can let Xcode take care of that complexity :p
> 

That's also very true and I understand the reasons why you want to avoid parsing xcconfigs.

> What do you think of the following options?
> 
> 1. Move the `SWIFT_VERSION` setting to `DefaultSettingsProvider` and treat it as one of the `essential` settings? i.e. specifying `defaultSettings: .none` would not set a default swift version.
> 
> All the other settings within `updateTargetDerived` relate to manifest related properties, whereas this is the only odd one out there.
> 
> 1. Add an explicit `swiftVersion` property to the target in the project manifest, which can be `nil`
> 
> ```swift
> Target(name: "MyTarget",
>            // ...
>         swiftVersion: "5.0")
> ```
> 
> ```swift
> Target(name: "MyTarget",
>            // ...
>         swiftVersion: nil) // inherit from somewhere else 
> ```
> 
> This would control the `SWIFT_VERSION` setting in the config generator.
> 
> The tricky part would be figuring out a sensible migration path for existing users, we'd need to default it to the existing value as opposed to `nil` which might seem a little counter intuitive on first glance.


I'd prefer to give a try to solution `3` rather than `4` to follow an existing Tuist's pattern and not make the `Target` initialiser too verbose. I also think that could simplify the migration, as you mentioned. Although, to reply to @lakpa , I think that is legit for a codebase to use different Swift versions in different targets.

If you 👍  I'll proceed and try to open a PR for this using `3`, cc @pepibumur

**Comment by kwridan** [comment]
https://github.com/tuist/tuist/issues/954 was raised recently after a similar discussion in slack.

The idea there was to experiment with implementing a simpler xcconfig parser that does not attempt to resolve or even extract any values - rather just checks if a key exists (string exists) and omits it from the default set of settings. It may be worth a prototype / feasibility check.

Either way omitting swift version when specifying `.none` is also a viable option we can pursue.

**Comment by kwridan** [comment]
Ah my mistake, just realised #954 wouldn't help with the `SWIFT_VERSION` case as it's not part of the default settings 😅 - I guess a first step either way is to move `SWIFT_VERSION` > `DefaultSettingsProvider` - which would help resolve this issue and open the door for some enhancements later on.

**Comment by andreacipriani** [comment]
@kwridan Agreed, I'll open a PR to move it into the `DefaultSettingsProvider`, thanks!
