### ISSUE TITLE
Generate project by running the target when `tuist edit`-ing

### ISSUE THREAD

**Issue by vytis** [tuist/tuist#922]
## Need/problem

When working on a project definition the workflow looks like this:
1. `tuist edit` to open the project definition in Xcode
2. Make changes to `Project.swift`
3. Go to command line and run `tuist generate`
4. Check the generated project and go to step 1.

We could add a run step to the `Project.swift` Xcode project that would run `tuist generate` with CMD-R

## Motivation

We could reduce the iteration time when working on project definitions by improving the feedback cycle. 

## Detailed design

TBD

# Drawbacks

None

# How we teach this

It should be quite intuitive to use because this is the normal workflow when working on a project in Xcode.

# Unresolved questions

- [ ] Maybe there could be other improvements to the workflow possible?

**Comment by kwridan** [comment]
This would make the workflow much smoother!

Manually configuring an Xcode scheme to make this work I see the following:

```xml
  <LaunchAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      launchStyle = "0"
      useCustomWorkingDirectory = "YES"
      customWorkingDirectory = "/path/to/current/directory">
      <PathRunnable
         runnableDebuggingMode = "0"
         FilePath = "/path/to/tuist">
      </PathRunnable>
      <CommandLineArguments>
         <CommandLineArgument
            argument = "generate"
            isEnabled = "YES">
         </CommandLineArgument>
      </CommandLineArguments>
   </LaunchAction>
```

It doesn't look like `XcodeProj` has a `PathRunnable` API yet, but shouldn't be too tricky to add support for it.
