### ISSUE TITLE
Depends on virtual Combine interface instead of concrete OpenCombine

### ISSUE THREAD

**Issue by ddddxxx** [tuist/tuist#925]
## Need/problem

#918 introduced a new dependency `OpenCombine`. If anyone would like to build tuist for macOS 10.15, they still have to bundle the whole third party Combine even system Combine is available. Also, For any package depends on `TuistGenerator`, they're forced to use OpenCombine (which does't compatible with SwiftUI) even they target on macOS 10.15+.

## Motivation

Combine is a great tool for processing async value. But we can't use system Combine due to backward compatibility. There're 2 open-source Combine reimplementaions, [CombineX](https://github.com/cx-org/CombineX) and [OpenCombine](https://github.com/broadwaylamb/OpenCombine) AFAIK. Currently OpenCombine is used.

It would be great if we can switch between different combine implementation, or use system Combine as well as remove unnecessary dependency. One day we can eliminate third party Combine completely if backward compatibility isn't a thing.

## Detailed design

CombineX provides `CXShim` as a virtual Combine interface. Allows user to choose underlying Combine implementation at build time (by setting environment variable). It support Apple's Combine, CombineX, OpenCombine, and will support any future Combine reimplementations. See [Combine-Compatible-Package](https://github.com/cx-org/CombineX/wiki/Combine-Compatible-Package) and [packages using CXShim](https://github.com/topics/combine-compatible-package)

We just depends on `CXShim` instead of `OpenCombine`, and use general `AnyPublisher` instead of qualified `OpenCombine.AnyPublisher`.

With `CXShim`, we can still use OpenCombine, and our clients can use system combine if they want.

# Drawbacks

CXShim choose system Combine by default on macOS, so we need to set environment variable to use open-source Combine when developing, [like this](https://github.com/ddddxxx/LyricsX/blob/master/DevOpen).

## Alternatives

Create our own shim package just like CXShim, so we can use open-source Combine by default.

# Adoption strategy

N/A

I'll work on an implementation once this proposal is accepted.

# How we teach this

N/A

# Unresolved questions

N/A

cc @pepibumur

**Comment by ollieatkinson** [comment]
Hi @ddddxxx, thanks for raising this issue. 

CombineX looks great, I particularly like the trick of using `#if canImport(Combine)` inside of the Package.swift manifest.

Are the interfaces for all of the implemenations compatiable? At the moment the `CXShim` is just re-exporting the modules so there's no guarentee the interfaces are the same at that level. 

Off the top of my head this approach does highlight that we might need to consider the following:

- We will need to start running our test suite across mac versions since it will not be using the same implementation.
- We may need to ship multiple binaries, one with Combine linked and the other using CombineX

Do we need to be aware of any other limitations or considerations with using this?

**Comment by ddddxxx** [comment]
[CXShim maintainer hat on]

Yes! As part of CombineX project, `CXShim` is guaranteed to have one unified interface. Our test suit is build on `CXShim` and run against both system Combine and CombineX. Note `CXShim` also re-export [CXCompatible](https://github.com/cx-org/CombineX/tree/master/Sources/CXCompatible) which implement cx namespace for system Combine.

[Combine consistency is described here](https://github.com/cx-org/CombineX/wiki/Combine-Consistency)

**Comment by ddddxxx** [comment]
Other drawbacks I can think of:

1. As a Combine-Compatible-Package, `TuistGenerator` requires it's client to either target on macOS 10.15+, or explicitly specify an open-source Combine. It could be confusing when they get tons of  "... is only available in macOS 10.15 or newer....."

2. Currently CXShim is not fully support OpenCombine, because OpenCombine doesn't have unified namespace. For example, CombineX can do this:
```swift
extension CXWrapping {
    var ocombine: CX { return cx }
}
```
And the client would able to use `anURLSession.ocombine.dataTaskPublisher(...)` as if they're using `OpenCombine`. However `OpenCombine` doesn't provide such protocol. So if we adopt `CXShim`, we still can't support OpenCombine without compilation conditions. (system Combine and CombineX does't requires such compilation conditions)

**Comment by pepibumur** [comment]
Thanks for bringing this up @ddddxxx. This makes me think that we should revert the introduction of Combine for now until we drop the support for macOS 10.14. The setup that you mention could work, but it'd add unnecessary complexity that I'd avoid in the codebase. We introduced Combine to stay aligned with Apple's frameworks but it doesn't seem it's the best idea now.

**Comment by lakpa** [comment]
> Thanks for bringing this up @ddddxxx. This makes me think that we should revert the introduction of Combine for now until we drop the support for macOS 10.14. The setup that you mention could work, but it'd add unnecessary complexity that I'd avoid in the codebase. We introduced Combine to stay aligned with Apple's frameworks but it doesn't seem it's the best idea now.

We can use rxswift with our own abstraction at the top, and once it would make sense to switch to combine, we can with less or no efforts.
