### ISSUE TITLE
Introduce github action to build with latest Xcode release available in Github

### ISSUE THREAD

**Issue by lakpa** [tuist/tuist#926]
## Need/problem

Our PRs build against specific Xcode version but having our PRs constantly build against latest build will allow us to identify the issue before to avoid delaying fixing it and prepare us from unexpected change.

## Motivation

To prepare us to adopt latest Xcode version

## Detailed design

We only need to introduce a new github check to build against latest available Xcode version.

# Drawbacks

It will introduce delay in our PR build to finish.

## Alternatives

Nothing I can think of.

# Adoption strategy

This shouldn't be a breaking change. Besides we can configure the respective status check to be optional and which shouldn't stop respective change to get merged.

**Comment by danyf90** [comment]
I think we are doing fine testing it "manually" when new versions come out (we often try it before such versions are available on GitHub), so I don't think there is a need for this
