### ISSUE TITLE
Package requirement .revision does not work

### ISSUE THREAD

**Issue by zdnk** [tuist/tuist#940]
**Describe the bug**
Declaring 
```
.remote(url: "https://github.com/datatheorem/TrustKit.git",             requirement: .revision("df3e13732604396ff537d84717346b1b7e794141")),
```
fails to generate project.

**Desktop (please complete the following information):**
- Version 1.1.0

**Comment by pepibumur** [comment]
Hi @zdnk. Would you mind including a reproduction case as described [here](https://tuist.io/docs/contribution/reporting-bugs/#reproducible-cases)? Also, could you include the exact error that you get. That will facilitate the debugging.

**Comment by danyf90** [comment]
Closed in favor of Dependencies.swift
