### ISSUE TITLE
Deprecation of release with [String: String]

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#943]
I have found an interesting edge case - we have deprecated `func release(name: String, settings: [String: String], xcconfig: Path? = nil)` in favor of `func release(name: String, settings: [String: SettingValue] = [:], xcconfig: Path? = nil)` - but `SettingValue` is `ExpressibleByStringLiteral` - that means that when I type something like `.release(name: "something", settings: ["SET": "SETTINGVALUE"])` I get a compiler warning because it implicitly uses a `String` - even though if `SettingValue` was the only case, it would have worked just fine!

Unfortunately, getting rid of the old version will be a breaking change:
Most of the time it will work fine, but the below sample will not compile:
`.release(name: "something", settings: ["SET": "\(myFavoriteInterpolatedVar)"])`

Since we have declared Tuist to be stable, I think we should make this 2.0.0 milestone, but I would still consider removing that warning as it causes confusion of the users because it is not immediately obvious what's wrong with the code they have written as it has been raised before: https://github.com/tuist/tuist/issues/540

**Comment by pepibumur** [comment]
> Since we have declared Tuist to be stable, I think we should make this 2.0.0 milestone, but I would still consider removing that warning as it causes confusion of the users because it is not immediately obvious what's wrong with the code they have written as it has been raised before:

Since the interfaces of the 2 methods are the same with the exception of the value type of the settings attribute, which conforms `ExpressibleByStringLiteral`, I think it should be safe to remove the deprecated method. I'd try that and see if acceptance tests fail because of that. If they don't fail, it should be safe to remove the method. Otherwise we have to explore other options.

**Comment by kwridan** [comment]
I believe those deprecated methods have now been removed with #1202
