### ISSUE TITLE
Linking failure when two targets from different projects link the same `.xcframework` dependency

### ISSUE THREAD

**Issue by paciej00** [tuist/tuist#950]
**Describe the bug**
I experienced a problem with a common dependency between two projects. 

I use `SnapshotTesting.xcframework` as a dependency of `SearchTests` (a test target in **Search** project). The `SearchTests` target depends on `TestUtils` target from another project  which in turn depends on `SnapshotTesting.xcframework`.

![Screenshot 2020-01-29 at 16 51 21](https://user-images.githubusercontent.com/2279666/73435105-4c000f00-4348-11ea-8551-c63f54ef36aa.png)

During a compilation of `SearchTests` I get an error that `TestUtils` cannot be linked with `SnapshotTesting` :

| Framework not found SnapshotTesting

![Screenshot 2020-01-29 at 16 49 28](https://user-images.githubusercontent.com/2279666/73435121-56220d80-4348-11ea-83fb-6ae26f164c50.png)

`TestUtils` builds into a **dynamic library** and compilation works correctly in the **TestUtils** project itself

Removing the explicit dependency on `SnapshotTesting.xcframework` from  `SearchTests`  seems to solve the problem. Is there any other way to deal with such an issue?

**Expected behavior**
Linking `.xcframeworks` in bot project works correctly.

**Desktop (please complete the following information):**

- OS: macOS Catalina 
- Version 10.15.2 (19C57)
- Xcode: 11.1, 11.3, 11.3.1,

**Comment by kwridan** [comment]
Thanks for flagging @paciej00 when you get a chance if you're able to include a sample project that reproduces this that would be really helpful. From my quick test I wasn't able to do so sadly.

**Comment by DavidBrunow** [comment]
I'm not currently a user of Tuist (although I plan to check it out now that I know about it) but someone else pointed me to this issue -- I am experiencing what seems like the same issue in an Xcode project created in Xcode. Here is a sample project that replicates the issue when trying to build `ExampleApp`: https://github.com/DavidBrunow/XCFrameworkLinkingExample

I have not found a workaround for the issue yet.

**Comment by lakpa** [comment]
I will look into this issue

**Comment by paciej00** [comment]
@lakpa I think the issue I experienced wasn't related to the `xcframework` itself, but an old `#include` of Pods configuration in an `xcconfig` file. This led to a misconfigured search paths. I am unable to reproduce the issue. I think it can be closed.

**Comment by lakpa** [comment]
Closing the issue for a reason mentioned above by @paciej00
