### ISSUE TITLE
The journey towards Tuist 2.0

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#951]
I'll get a bit **philosophical** in this issue aiming to explain what I think the journey to Tuist 2.0 should look like. As you might know, the main focus of Tuist until version 1.0 has been generation and validation of projects, as well as having a solid and well-architected foundation that allows extending and leveraging project generation to help developers scale up their projects.

During that time, we've also built a **community** of users, contributors, and maintainers around the projects. People that like me, faced the pain of maintaining modular Xcode projects and that decided to give Tuist a try. All of that was possible thanks to the effort that we put into shaping Tuist as a product: *documentation, website, blog posts, talks.* We even put love into having community and contribution guidelines that people can follow to push their first contributions upstream.

I see from time to time people asking on Slack, *is there a roadmap somewhere that I can have a look at?* Unfortunately not, but that's what I'd like to do in this issue. Without going too much into details, I'll include some areas that I believe should be the focus for Tuist 2.0

## Automation 👩‍💻
Proposed owners: ??

I really like how a Rails developer can learn a set of basic commands that apply to any Rails app. In the Xcode world, there's nothing like that. We have tools like xcodebuild or simctl that we can use, but that we need to wrap up in Fastlane lanes or Rake tasks to have a plain list of tasks that are easier to remember. Even with that, those `Rakefiles` and `Fastfiles` can get very messy, flakey, and with inconsistent naming that adds unnecessary indirection.

**What changes with Tuist?** Tuist allows defining a consistent project structure. In other words, projects look the same. If projects look the same, that also means that we can have a CLI to interact with them that is standard across all the projects. And what's more important, we don't require Fastfiles or Rakefiles to define the contract between the tool and the project. We know the contract: *the manifest files*. Tuist can provide a set of basic commands. We can start with the following:
- tuist build
- tuist test
- tuist run
When executed in a directory that contains a `Project.swift`, we'd infer the necessary `xcodebuild` command and any pre and post steps that are required. The commands would be designed with the zero-configuration principle in mind. That means that developers don't need to remember to pass a destination device, or signing values. If we detect some arguments like the destination are required but are not passed, we can infer them too.

Moreover, in commands like `test` we can add features that `xcodebuild` doesn't provide, like running the tests of only the modules that have been impacted by the changes in our branch. Cool, isn't it? Or use `tuist run` to compile the apps, and then run them on a device or simulator.

## Performance ⌚️
Proposed owners: @marciniwanicki / @kwridan 

This is an area that we have disregarded since the inception of the project and that needs some love. @kwridan and @andreacipriani are experiencing slow generation times because they are using Tuist in large projects with many targets and files. There are many things that we can do here to make Tuist faster:
- Run the generation of Xcode projects in multiple threads.
- Instrument the code to spot if there are code paths that we go through several times.
- Minimize IO and find more efficient ways of doing it *(how expensive are globs?)*

As part of this effort, we can come up with some guidelines on how to structure the projects to facilitate the work to Tuist. For example, complex files structure that are defined with complex glob patterns, might result in slow resolution time. We could suggest users to place all the sources under a single directory from which we'd read them without applying any kind of filtering.

## Caching 📦
Proposed owners: @pepibumur / @andreacipriani 

I was so happy when I saw Apple announcing .xcframeworks at the last WWDC. It'll allow us to introduce caching. In a nutshell, this would be the process:
- On CI, for every commit in master developers would execute `tuist cache`. That would compile all the frameworks in the dependency graph as .xcframework and them upload them to a cache with a hash that identifies them. The cache is calculated based on the target and its dependencies *(other targets and files)*
- Locally, when developers run `tuist generate`, we get the hash of all the frameworks and check whether they exist in the cache or not. If they do, we pull them, and swap them in the dependency graph whenever it's possible. The project generation logic will take care of setting up the linking.

It sounds too easy to be true, but I think it's worth exploring. I'm sure we'll find some complications along the process *(e.g. how to hash the targets fast)*, but they are not impossible tasks because we have build systems like Bazel and Buck very likely solved most of the problems that we'll face.

We'll define the cache contract in such a way that we can provide implementation for cloud storages like Amazon S3 or Google Cloud. Developers will be able to configure the storage in their Tuist configuration file.

## [Signing 🔑](https://github.com/tuist/tuist/issues/246)
Proposed owners: ??

There isn't still a solution for managing certs and profiles that integrates well into developers's workflows. The one that got the closest in my opinion was Fastlane, but there's still some room for improvement. I think we can leverage project generation to configure the project and the environment with the right keys and profiles so that the user can run the app on their devices or build it for release.

This is a rough idea about the workflow that I have in mind:
- I place the keys under `Tuist/Signing` following a naming convention:
  - Certificates: {Configuration}.p12 *(e.g. Debug.p12)*
  - Profiles: {Target}.{Configuration}.mobileprivision *(e.g. MyApp.Debug.mobileprovision)*
- Developers would have a key a `Tuist/master.key` that is used to encrypt/decrypt the files.
- `tuist encrypt` encrypts all the files under `Tuist/Signing` and removes the unencrypted version.
- During project generation, we'd read all the files at the directory, and see if there's any certificate that we need to install, or provisioning profile that we need to copy. If so, we'd validate them to make sure they are not expired and that both match, and then set the right build settings in the generated targets.

In the future we can leverage the App Store Connect API to automate the generation of the certificates and the profiles on the developer portal.

cc @tuist/core

**Comment by fortmarek** [comment]
I'd love to get involved in signing. I am not sure how much time I can devote to it at the moment, at least until summer, but is definitely an area that interests me greatly.
