### ISSUE TITLE
`tuist edit` should allow editing workspace and all projects at the same time

### ISSUE THREAD

**Issue by vytis** [tuist/tuist#953]
## Need/problem

When a project contains `Workspace.swift` with several projects it should be possible to edit all of them at once. At the moment you can only edit the workspace or project separately.

## Motivation

`tuist edit` gives much better experience working with project definitions than simply editing the file with a text editor. We should improve it to cover more use cases.

## Detailed design

The "editing" project should mimic the structure of the project itself:
* If only `Project.swift` exists in the current directory, then current behaviour is OK.
* If only `Workspace.swift` exists, then we should include it and all dependent `Project.swift` files. 
* if both `Workspace.swift` and `Project.swift` exists - we should probably have both in the project?

# Adoption strategy

It's a change isolated to `tuist edit` command, no breaking changes.

# How we teach this

Should be straightforward to use because it mimics the structure of project definitions.

# Unresolved questions

- [ ] How do we figure out what `Project.swift` files form subdirectories to include? We basically need to run part of the code and stop short of generating the project.
- [ ] Would this tie in some other functionality that we have?

**Comment by kwridan** [comment]
>  How do we figure out what Project.swift files form subdirectories to include? We basically need to run part of the code and stop short of generating the project.

@pepibumur extracted the graph / graph loading logic not so long ago, this can help you traverse the dependency tree without any generation :) 

One challenge you may run into is, attempting to include all `Project.swift` files in a single project/target may cause some issues for the compile workflow - they all declare top level variables like `project` which will no doubt raise duplicate variables errors. Having separate project/target for each project could mitigate this, but will require configuring it such that there is a top level target that depends on all other targets to get the compile workflow working for them all without needing to switch schemes.

**Comment by pepibumur** [comment]
Totally agree with you here @vytis. `tuist edit` is very convenient and we should keep adding improvements that we believe will add value for the users.

> One challenge you may run into is, attempting to include all Project.swift files in a single project/target may cause some issues for the compile workflow - they all declare top level variables like project which will no doubt raise duplicate variables errors. Having separate project/target for each project could mitigate this, but will require configuring it such that there is a top level target that depends on all other targets to get the compile workflow working for them all without needing to switch schemes.

I think we can have multiple targets to avoid conflicts. The good thing is that we have an awesome `TuistGenerator` that should take care of generating an Xcode project that just works.
