### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by vytis** [tuist/tuist#955]
## Need/problem

Currently releasing a new version of Tuist has several [manual steps](https://github.com/tuist/tuist/blob/master/RELEASE.md). They are not complicated but some need authenticated access to GCS which means everyone doing a release must have them locally.

## Detailed design

We can use a GitHub action that gets triggered on [`release`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#release-event-release) event and does the job without manual intervention. We should probably make sure to run the tests before and add checks that outlined in [Release.md](https://github.com/tuist/tuist/blob/master/RELEASE.md).

# Unresolved questions

- [ ] How does permissions work in this case? Can anyone who is a contributor create a new release or we limit it to the core members?

**Comment by pepibumur** [comment]
> How does permissions work in this case? Can anyone who is a contributor create a new release or we limit it to the core members?

I'd say core members and people that we can designate as release captains would have access to this. They should be able to create the release on GitHub, which for instance will trigger the GitHub actions workflow.

I'll tackle this one :)
