### ISSUE TITLE
Generate only the projects that need to be generated

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#956]
## Context 🕵️‍♀️
When users run `tuist generate`, we load the dependency graph in memory and then traverse all the projects generating them. That's not optimal because we might end up generating projects that don't need to be generated. In essence, generating projects whose manifest file hasn't changed.

To mitigate this a bit, we introduced the `--project-only` argument. When passed, we only generated the project in the directory where the `tuist generate` command is executed from. 

## What 🌱
I propose deprecating the `--project-only` argument in favour of a smarter approach where the command only generates the projects that need to be generated. How would that work?
1. Each `Project` in memory would have a hash attribute that is obtained by hashing the JSON representation of the manifest. This can be done at loading time.
2. When we generate the Xcode projects, we would generate a `Project.lockfile` inside the `.xcodeproj` directory that contains the hash.
3. At generation time, we would only generate the projects if the hash of the project has changed.

**Comment by pepibumur** [comment]
What do you think about this one @tuist/core ?

**Comment by kwridan** [comment]
Thanks for putting this together @pepibumur - having a smarter way to detect changes would be great 👍 

There are a number of different reasons a regeneration may need to take place:

- `Project.swift` manifest has changed
- New files added / removed / moved on disk (e.g. within `Sources`)
- A transitive dependency is added / removed (e.g. A depends B, now B depends C)
- A transitive dependency type is modified (e.g. `.framework` > `.staticFramework`)
- (Possibly) The xcodeproj getting manually modified on disk

> I propose deprecating the --project-only 

There's still value in having this - in addition to the speed gains, we use this to scope generation to a specific project. This is helpful when collaborating in a large workspace where multiple teams own different projects, performing a scoped regeneration ensure that teams don't accidentally modify other teams projects especially during iterating on creating a new manifest or migrating an existing project.

> When we generate the Xcode projects, we would generate a Project.lockfile inside the .xcodeproj directory that contains the hash.

Is it safe to place custom files inside the `.xcodeproj`? I guess technically it would work 😅 - but equally we can place it at the project root alongside the manifest like how Swift PM does with `Project.resolved`

> At generation time, we would only generate the projects if the hash of the project has changed.

I guess we'd need more than just the project hash - almost list the graph and file system hash too 🤔(based on the list of items that would require a re-generation).

Storing the hash of the manifest can help differently - combined with a `json` representation of the manifest on disk it can potentially help optimize the manifest loading process (to minimise the `swiftc` calls).

**Comment by lakpa** [comment]
> 1. Each `Project` in memory would have a hash attribute that is obtained by hashing the JSON representation of the manifest. This can be done at loading time.

why can't we have hash attribute of manifest as serialising to JSON would be redundant effort and also add some delays proportional to how complex it will be?

> 2. When we generate the Xcode projects, we would generate a `Project.lockfile` inside the `.xcodeproj` directory that contains the hash.
I agree to @kwridan, we should avoid storing inside `.xcodeproj`, storing in project root would be safer approach, this way we will not be interfering with `.xcodeproj` and changes in its internal structure will not affect us

**Comment by ollieatkinson** [comment]
> why can't we have hash attribute of manifest as serialising to JSON would be redundant effort and also add some delays proportional to how complex it will be?

At the moment the manifest files are compiled and dumped into JSON format which is then read by Tuist. I really like the idea @pepibumur is proposing with hashing each of the manifest JSON representations - it would certainly cut down on IO when walking through the manifest dependency graph.

**Comment by lakpa** [comment]
> > why can't we have hash attribute of manifest as serialising to JSON would be redundant effort and also add some delays proportional to how complex it will be?
> 
> At the moment the manifest files are compiled and dumped into JSON format which is then read by Tuist. I really like the idea @pepibumur is proposing with hashing each of the manifest JSON representations - it would certainly cut down on IO when walking through the manifest dependency graph.
> 
> We just need to solve the problem of the hash not containing information about files on disk and trasitive dependencies. But we could serialise this too, but by the time we have checked all of this we might not be saving much anyway.
> 
> Personally I would like to see some of the profiling results from the benchmarks, and from there we can start theorising new stragies for speeding things up

An alternative to slow JSON serialisation, we could consider binary serialisation, with Google's Protocol Buffer ("protobuf") serialization technology as it emphasize high performance and programmer safety and there is an apple's Swift Protobuf open source implementation we could take advantage of.

**Comment by pepibumur** [comment]
> There are a number of different reasons a regeneration may need to take place:

You are right. There are many different scenarios that we might want to incorporate into the hashing logic. However, I think we can start by supporting the simplest case which is re-generating the project only of the manifest has changed. Developers can always force a full re-generation by passing an argument such as `--force`. We don't need to set this as the new behaviour. Only when we are happy with how it behaves.

> There's still value in having this - in addition to the speed gains, we use this to scope generation to a specific project. This is helpful when collaborating in a large workspace where multiple teams own different projects, performing a scoped regeneration ensure that teams don't accidentally modify other teams projects especially during iterating on creating a new manifest or migrating an existing project.

We can keep that argument if it gives you value. I'm sure other users will find it valuable too.

> Is it safe to place custom files inside the .xcodeproj? I guess technically it would work 😅 - but equally we can place it at the project root alongside the manifest like how Swift PM does with Project.resolved

We can place it alongside. It's an implementation detail though so not a big deal. If I'm not wrong, Xcode ignores the files that are inside the .xcodeproj directory and that are not supported. We are currently doing that in projects that define Swift dependencies.

> I guess we'd need more than just the project hash - almost list the graph and file system hash too 🤔(based on the list of items that would require a re-generation).


As I mentioned before, we can make this one as accurate as we want and take many inputs into account. However, I don't think we need to start with such level of accuracy.

**Comment by pepibumur** [comment]
> why can't we have hash attribute of manifest as serialising to JSON would be redundant effort and also add some delays proportional to how complex it will be?

I think hashing the JSON representation as a string is faster than hashing the attributes manually. Moreover, I'd not hash the model once it has been loaded into memory because at that point we have the blogs already unfolded and I think we should hash the glob instead.
