### ISSUE TITLE
[Documentation] Provide the guidance / best practices for a CI integration

### ISSUE THREAD

**Issue by mollyIV** [tuist/tuist#972]
## Context 🕵️‍♀️

Tuist has a great [documentation](https://tuist.io/docs/usage/getting-started/) that provides the answers for many questions related to Xcode project generation. The section that may be missing though is a CI integration. Providing such guidance might boost the adaptation of tuist CLI tool. 

There are two frequently asked questions about [`XcodeGen`](https://github.com/yonaskolb/XcodeGen) integration into a team's workflow: 

* [Can I still check in my project?](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/FAQ.md#can-i-still-check-in-my-project)
* [What happens when I switch branches?](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/FAQ.md#what-happens-when-i-switch-branches)

These seem to be valid questions for tuist users as well.

## Proposal 🎉

I'd like to propose adding the guidance / best practices for a CI integration to the documentation. Answering to the above frequently asked questions + providing a snippet for setting up a git hook (project re-generation when a developer switches branches) could be a great start 👍

**Comment by mollyIV** [comment]
I'd be glad to help with this one 🙋

**Comment by kwridan** [comment]
Thanks @mollyIV, a frequently asked questions section would be a great addition! Feel free to take this on.
