### ISSUE TITLE
BuddyBuild can't see generated schemes

### ISSUE THREAD

**Issue by remover** [tuist/tuist#993]
**Describe the bug**

[BuddyBuild](https://www.buddybuild.com/) the CI provider can't find the schemes generated by Tuist. As a result we can't run our app on CI.

**To Reproduce**

We provided them with a very simple app (1 source file, 1 scheme for unit tests).
They ran their tool against this app and confirmed that it doesn't pick up the schemes.

**Expected behavior**
The schemes are discoverable by CI providers

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: unknown
- Version: cff6671a1d596627398c19cda06e5bc90f9a3635

**Additional context**
https://tuistapp.slack.com/archives/CCXC295QS/p1581425210196100

**Comment by pepibumur** [comment]
Hey @remover would it be possible to have access to that example app that you provided to them? Also... it'd be great if you could confirm with them if they are using any of the existing libraries for parsing XcodeProj files.

**Comment by pepibumur** [comment]
Is this something that we can close @remover ?

**Comment by remover** [comment]
> Hey @remover would it be possible to have access to that example app that you provided to them? Also... it'd be great if you could confirm with them if they are using any of the existing libraries for parsing XcodeProj files.

they mentioned that they were using custom xml parsing. we solved the generation of project schemes, e.g. for unit tests, by using Tuist's `Scheme` related APIs in order to include a `TargetReference` for the app target as well as the unit test target.

however, i'd leave this open for now since we still seem to have an issue with workspace schemes. i'm not sure what the solution with that is yet...

**Comment by pepibumur** [comment]
> however, i'd leave this open for now since we still seem to have an issue with workspace schemes. i'm not sure what the solution for that is yet...

I don't think there's an issue in the format of the schemes that we generate. The schemes can run with Xcode and `xcodebuild` and it seems the problem is on their side because they are assuming test schemes should contain the host target. That's not required by Xcode and therefore I wouldn't consider it an issue.

What do you think?

**Comment by remover** [comment]
yea, not an issue on your side but i was just leaving it open to update on the workspace scheme.

i can now confirm that the workspace scheme also needed to have a reference to the main app target. very strange... glad it's resolved now... thanks for your help!
