### ISSUE TITLE
TargetAction script file

### ISSUE THREAD

**Issue by fortmarek** [tuist/tuist#994]
**Describe the bug**
In an example project that you can find [here](https://github.com/fortmarek/tuist_target_action), I have a defined `Project.swift` in `Projects/Script` like this:
```swift
let project = Project.app(name: "Script", platform: .iOS, dependencies: [
    .project(target: "ScriptKit", path: .relativeToManifest("../ScriptKit"))
], actions: [.pre(path: "script.sh", name: "Run Script")])
```
And even though the file exists, the build then fails with error `script.sh not found`.
I suspect that it is because not the right path is copied to the build phase (in build phase it triggers `script.sh`, but it should probably be absolute path there?)

If I manually modify the build phase to `{PROJECT_DIR}/script.sh`, it works (but I can not do that because `tuist generate` would complain that such file does not exist)

**To Reproduce**
1. Download example project
2. `tuist generate`
3. open project and build `Script` target

**Expected behavior**
If the preliminary check that the file exists succeeds, the build phase should the succeed, too.

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.1

**Additional context**
I am willing to help debug this/fix this, but would love to know if someone can confirm that it is in fact a bug, thanks!

**Comment by kwridan** [comment]
This is an interesting one ... good find 👍 

What you're witnessing is consistent with the behaviour in the terminal:

```
$ cd Projects/Script
$ script.sh
bash: script.sh: command not found
```

```
$ cd Projects/Script
$ ./script.sh
Derived                 Script.xcodeproj        Tests
Project.swift           Sources                 script.sh
```

Your proposed solution will make this less error prone. Should be a matter of modifying the [`shellScript(sourceRootPath: AbsolutePath)`](https://github.com/tuist/tuist/blob/master/Sources/TuistCore/Models/TargetAction.swift#L81) method to prepend the appropriate variable - either of  `PROJECT_DIR` or `SRCROOT` should do the trick (the latter is already used in a few places already).
