### ISSUE TITLE
Introduce Chrome tracing to view profiling data

### ISSUE THREAD

**Issue by lakpa** [tuist/tuist#996]
## Need/problem

As we keep adding new and accommodate existing functionalities in tuist, we suffer from performance penalty resulted from some of the approaches we take while overlooking performance due to absence of having any good way of representing nice graphical tool for profiling data to find critical hotspots.

## Motivation

Creating a viewer application for that custom data is a massive time sink, and we instead should leverage what is already available. Chrome tracer is one such tools that you can use to view data in the Chrome web browser rather than writing a visualisation tool yourself. As we are pushing for performance and optimisation, a visual tool such as Chrome tracer, can aid us in pinpointing critical hotspots.

## Detailed design

Understanding the chrome://tracing JSON data

The tracing data format is a non-optimized JSON file containing a sequence of event blocks. Each block includes the following name/value pairs:

`cat` – the category for this event. Useful when doing larger grouping (eg "UnitUpdates")
`name` – the name of this event (eg 'PathingUpdate')
`pid` – the processor ID that spawned this event
`tid` – the thread ID that spawned this event
`ts` – the processor time stamp at the time this event was created
`ph` – the phase or type of this event
`args` – any programmatic metadata that's attached to this event

```
[
    {

         "cat": "MY_SUBSYSTEM",  //category
         "pid": 4260,  //process ID
         "tid": 4776, //thread ID
          "ts": 2168627922668, //time-stamp of this event
          "ph": "B", // Begin sample
          "name": "doSomethingCostly", //name of this event
          "args": { //arguments associated with this event.
          }
    }
]

```

One of the most important features of the tool is that it allows you to load external log files, which is the coolest part of the tool for non-web developers. By modifying your app existing inline-profiling code to output a JSON object compatible with the chrome://tracing tab, you can use it as your visualisation tool for your application profiling purposes.

We only need to generate log in above format to render in chrome to get a visual representation. 

# Drawbacks

Nothing I can think of now.

## Alternatives

Write your own custom viewer, a non-trivial task.

# Adoption strategy

This shouldn't be a breaking change as it won't alter and affect the existing behaviour of tuist. A CLI `chrome-trace-profile`, open to any good name suggestion, option will be introduced which will generate the JSON file with aforementioned format which we could externally load in chrome to get visual representation of time taken by particular covered functionalities.

# How we teach this

Documentation will be suffice to teach about its existence and usage.

More info about the tool can be found [here](http://www.chromium.org/developers/how-tos/trace-event-profiling-tool)

**Comment by kwridan** [comment]
Thanks for putting this together @lakpa!

This could tie in quite nicely with some of the ongoing efforts: #39 (verbose logging + using swift-log) and #957 (benchmarking tool). I could this being useful to analyse a generation log of some form to troubleshoot / get more insights on use cases submitted by users of tuist. 

It's worth noting for more local scenarios Xcode's built in Instruments work just as well to also help gain insights. Combined with [signposts](https://developer.apple.com/documentation/os/logging) it be can be really powerful.

Reference: [WWDC 2018: Measuring Performance Using Logging](https://developer.apple.com/videos/play/wwdc2018/405/)

**Comment by lakpa** [comment]
> This could tie in quite nicely with some of the ongoing efforts: #39 (verbose logging + using swift-log) and #957 (benchmarking tool). I could this being useful to analyse a generation log of some form to troubleshoot / get more insights on use cases submitted by users of tuist.
> 
Yes, I am very much looking forward to that.

> It's worth noting for more local scenarios Xcode's built in Instruments work just as well to also help gain insights. Combined with [signposts](https://developer.apple.com/documentation/os/logging) it be can be really powerful.
> 

Yes definitely, for local use case, the instruments is a great tool. The chrome trace profiling could help other in submitting profiling data to pinpoint critical hotspots. For instance, my local setup is not complex enough to encounter any performance bottleneck but for other organisation, like `Bloomberg` for instance, we could gauge where we can squeeze performance by refactoring the codebase. 

Yes, `signpost` is a good, simple tool to diagnose performance issue.

> Reference: [WWDC 2018: Measuring Performance Using Logging](https://developer.apple.com/videos/play/wwdc2018/405/)

Thanks

**Comment by lakpa** [comment]
@kwridan @ollieatkinson as you guys are having discussion on logging, as introducing this profiling logging, we are introducing one more logging format. I am particularly looking forward to get this integrated, and thinking of abstracting logging to support different formats. I would love to get involved in further discussion.

**Comment by pepibumur** [comment]
> Yes definitely, for local use case, the instruments is a great tool. The chrome trace profiling could help other in submitting profiling data to pinpoint critical hotspots who doesn't want to go through local Xcode setup. For instance, my local setup is not complex enough to encounter any performance bottleneck but for other organisation, like Bloomberg for instance, we could gauge where we can squeeze performance by refactoring the codebase.

I like the idea of exporting that data and opening it in the Chrome debugger. The good thing about using JSON as a format for those reports is that they can share them easily. Imagine there's an user reporting a bad performance in their project. They could attach the profile to the PR and we could use it for debugging purposes.

If the same is achievable with Instruments *(I'm not sure)*, then let's use Instruments, otherwise I think using Google Chrome's API is a good idea.

I really like the direction this logging and more insights effort is taking.
