### ISSUE TITLE
`versionGroupType` should be `wrapper.xcdatamodel` for CoreData models

### ISSUE THREAD

**Issue by TadeasKriz** [tuist/tuist#998]
**Describe the bug**
When generating the **.pbxproj** file, **tuist** generates `XCVersionGroup` for each `.xcdatamodeld` provided to the `coreDataModels` parameter of a target. However, the generated `versionGroupType` is equal to `wrapper.xcdatamodeld` which is probably an incompatible value.

I spent the day debugging this issue and going through disassembled Xcode's binaries and here's what I found:

The value for the `versionGroupType` is taken from `tuist/XcodeProj`. In file `Sources/XcodeProj/Project/Xcode.swift`, there's a property `allExtensions`. Now I believe this list is correct and shouldn't be changed. However, I think **tuist** shouldn't call the `Xcode.filetype(extension:)` method with the extension of the `xcdatamodeld`, but with the extension of its first child. This child should have the extension `xcdatamodel`.

I checked what value is generated by Xcode when I add a new Core Data model. The value is `wrapper.xcdatamodel`, without the `d` at the end. So I went digging through the Xcode's binaries in **Hopper Disassembler** (and purchasing a license so I could get to the bottom of this). Until I finally found the interesting bit. The method `fileType` on `XCVersionGroup` class seems to be the culprit. In the screenshot below, you can see the disassembly. It's appending the `"d"` at the end and then using that new string to find `PBXFileType` specification for that identifier and returning the found value.

![image](https://user-images.githubusercontent.com/284197/74284080-5694ae00-4d23-11ea-9a3d-765e519501f6.png)

This returned value is then used and since it didn't find it, it fails and crashes on an assertion. Here's the one I'm getting on my project:

```
2020-02-11 20:45:45.133 xcodebuild[18442:289870] apply_selection_policy_once: prefer use of removable GPUs (via com.apple.dt.xcodebuild:GPUSelectionPolicy->preferRemovable)
Build settings for action clean and target Rival:
2020-02-11 20:45:45.890 xcodebuild[18442:289798] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-15705/DVTFoundation/FileTypes/DVTFileDataType.mm:626
Details:  stringRep should be a non-empty string, but it is nil
Object:   <DVTFileDataType>
Method:   +fileDataTypeFromStringRepresentation:
Thread:   <NSThread: 0x7f918e412c80>{number = 1, name = main}
Hints:

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   +[DVTFileDataType fileDataTypeFromStringRepresentation:] (in DVTFoundation)
  4   +[DVTFileDataType fileDataTypeWithIdentifier:] (in DVTFoundation)
  5   -[XCBuildFileRefDGSnapshot initWithInformationFromBuildFile:fileReference:groupReference:forTargetSnapshot:withResolver:] (in DevToolsCore)
  6   -[XCBuildPhaseDGSnapshot initWithInformationFromBuildPhase:forTargetSnapshot:withResolver:] (in DevToolsCore)
  7   -[XCSourcesBuildPhaseDGSnapshot initWithInformationFromBuildPhase:forTargetSnapshot:withResolver:] (in DevToolsCore)
  8   -[PBXBuildPhase createDependencyGraphSnapshotForTargetSnapshot:withResolver:] (in DevToolsCore)
  9   -[PBXBuildPhase createDependencyGraphSnapshotsForTargetSnapshot:withResolver:] (in DevToolsCore)
 10   -[XCTargetDGSnapshot initWithInformationFromTarget:withBuildParameters:] (in DevToolsCore)
 11   -[XCNativeTargetDGSnapshot initWithInformationFromTarget:withBuildParameters:] (in DevToolsCore)
 12   -[PBXTarget createDependencyGraphSnapshotWithTargetBuildParameters:] (in DevToolsCore)
 13   -[PBXTarget propagateTargetSnapshotIfNeededWithCompletionBlock:] (in DevToolsCore)
 14   __48-[Xcode3CommandLineBuildTool _showBuildSettings]_block_invoke.3237 (in Xcode3Core)
 15   -[DVTFuture initWithBlock:] (in DVTFoundation)
 16   +[DVTFuture futureWithBlock:] (in DVTFoundation)
 17   -[Xcode3CommandLineBuildTool _showBuildSettings] (in Xcode3Core)
 18   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 19   main (in xcodebuild)
 20   start (in libdyld.dylib)
[1]    18442 abort      xcodebuild clean -showBuildSettings -scheme Rival -project
```

Changing the `versionGroupType` that was generated by **tuist** from `wrapper.xcdatamodeld` to `wrapper.xcdatamodel` also resolves the crash.

**To Reproduce**

1. Create a tuist `Project.swift` with a target named `BugReportTarget` containing at least one `.xcdatamodeld` passed to `coreDataModels` parameter.
2. Run `tuist generate`
3. Run `xcodebuild clean -showBuildSettings -scheme BugReportTarget -project BugReportProject.xcodeproj`
4. See `xcodebuild` crash

**Expected behavior**
The `xcodebuild` command should print all build settings for the given scheme.

**Desktop (please complete the following information):**

- OS: macOS 10.15.3
- Version: tuist 1.2.0

**Comment by kwridan** [comment]
Wow that is quite thorough and insightful!! Appreciate the detailed issue - thanks @TadeasKriz 👍 

Would you be interested in opening a PR with your suggested fix?  

The place where version group file elements are added is inside [`ProjectFileElements`](https://github.com/tuist/tuist/blob/master/Sources/TuistGenerator/Generator/ProjectFileElements.swift#L389). 

Additionally there is a core data fixture in [`fixtures/ios_app_with_coredata`](https://github.com/tuist/tuist/tree/master/fixtures/ios_app_with_coredata) which can be leveraged with the [acceptance tests](https://github.com/tuist/tuist/tree/master/features) where the steps you mentioned could be codified to ensure this is fixed and doesn't regress in the future.

@pepibumur has put together a great [contributions guide](https://tuist.io/docs/contribution/getting-started/) which should help guide you through getting set up - of course happy to also help where I can!

**Comment by TadeasKriz** [comment]
Yes I'll gladly do that once I'm done with my current workload.

**Comment by focker321** [comment]
sorry, could be created the PR for fixing this? I am getting this error now when I run unit test with fastlane
